### PR TITLE
ci: update Apple dev team ID to update the org

### PR DESCRIPTION
**Pull request by jakubgs**
We are trasnferring the Apple app to the new Switzerland based Apple development organization/team from the old Singapore one, and to make this work we also need to update the development team ID.

### CODE REVIEW

**Review by J-Son89 — APPROVED** [review]

**Comment by jakubgs** [comment]
The transfer has taken place today at night and now the Nightly iOS builds are failing:

image

With error:
```
Could not find App ID with bundle identifier 'im.status.ethereum'
```
https://ci.infra.status.im/job/status-mobile/job/platforms/job/ios/854/console

**Comment by jakubgs** [comment]
I might have to re-create the provisioning profiles and certificates to make this work:
```
error: No profile for team '8B5X2M6H2Y' matching 'match AdHoc im.status.ethereum.pr' found:
  Xcode couldn't find any provisioning profiles matching '8B5X2M6H2Y/match AdHoc im.status.ethereum.pr'.
  Install the profile (by dragging and dropping it onto Xcode's dock item) or select a different one in the
  Signing & Capabilities tab of the target editor. (in target 'StatusImPR' from project 'StatusIm')
```

**Comment by jakubgs** [comment]
And there it is. When I try to run `fastlane match adhoc` I get this:
```
[18:05:19]: Verifying that the certificate and profile are still valid on the Dev Portal...
Multiple teams found on the Developer Portal, please enter the number of the team you want to use: 
1) DTX7Z4U3YA "STATUS HOLDINGS PTE. LTD." (Company/Organization)
2) 8B5X2M6H2Y "Status Research & Development GmbH" (Company/Organization)
```

**Comment by jakubgs** [comment]
I nuked the `development` certificate:
```

+---------------------+---------------------------------------------------+
|                   Files that are going to be deleted                    |
|        Git Repo [git@github.com:status-im/ios-certificates.git]         |
+---------------------+---------------------------------------------------+
| Type                | File Name                                         |
+---------------------+---------------------------------------------------+
| development cert    | 9B4467UP8X.cer                                    |
| development cert    | 9B4467UP8X.p12                                    |
| development profile | Development_im.status.ethereum.mobileprovision    |
| development profile | Development_im.status.ethereum.pr.mobileprovision |
+---------------------+---------------------------------------------------+

[18:08:29]: ---
[18:08:29]: Are you sure you want to completely delete and revoke all the
[18:08:29]: certificates and delete provisioning profiles listed above? (y/n)
[18:08:29]: Warning: The :app_identifier value will be ignored - this will delete all profiles for all your apps!
[18:08:29]: ---
[18:08:29]: Hint: You can use --safe_remove_certs option to remove certificates
[18:08:29]: from repository without revoking them.
[18:08:29]: Do you really want to nuke everything listed above? (y/n)
```
But now it doesn't want to re-create it on the new org:
```
Multiple teams found on the Developer Portal, please enter the number of the team you want to use: 
1) DTX7Z4U3YA "STATUS HOLDINGS PTE. LTD." (Company/Organization)
2) 8B5X2M6H2Y "Status Research & Development GmbH" (Company/Organization)
2
[18:11:50]: 
[18:11:50]: ==========================================
[18:11:50]: Could not find App ID with bundle identifier 'im.status.ethereum.pr'
[18:11:50]: You can easily generate a new App ID on the Developer Portal using 'produce':
[18:11:50]: 
[18:11:50]: fastlane produce -u auto@status.im -a im.status.ethereum.pr --skip_itc
[18:11:50]: You will be asked for any missing information, like the full name of your app
[18:11:50]: If the app should also be created on App Store Connect, remove the --skip_itc from the command above
[18:11:50]: ==========================================
[18:11:50]: 
[18:11:50]: An app with that bundle ID needs to exist in order to create a provisioning profile for it
[18:11:50]: ================================================================
[18:11:50]: Available apps:
- im.status.ethereum (Status)
[18:11:50]: Make sure to run `fastlane match` with the same user and team every time.
```
Which I guess kinda makes sense.

**Comment by jakubgs** [comment]
Ok, I found it under `Certificates, Identifiers & Profiles`:

image

I just need to remove those.

**Comment by jakubgs** [comment]
I deleted them but now I'm getting this when I try to `fastlane produce -a im.status.ethereum.pr --skip_itc`:
```
[!] Apple provided the following error info:
        An App ID with Identifier 'im.status.ethereum.pr' is not available. Please enter a different string.
```
It's possible I need to wait a bit for the deletion of old profiles to propagate.

**Comment by jakubgs** [comment]
Ok, I also removed it from the `Identifiers` section and now it worked:
```
[18:33:23]: App Name: Status PR
[18:33:26]: Creating new app 'Status PR' on the Apple Dev Center
[18:33:27]: Created app 4W84S4BXS8
[18:33:27]: Finished creating new app 'Status PR' on the Dev Center
```
image

**Comment by jakubgs** [comment]
I've created all 3 profiles for both identifiers:

image

Expiry dates:
```
+-------------------+---------------------------------------------------------------------+
|                                  Installed Certificate                                  |
+-------------------+---------------------------------------------------------------------+
| User ID           | 8B5X2M6H2Y                                                          |
| Common Name       | Apple Distribution: Status Research & Development GmbH (8B5X2M6H2Y) |
| Organisation Unit | 8B5X2M6H2Y                                                          |
| Organisation      | Status Research & Development GmbH                                  |
| Country           | CH                                                                  |
| Start Datetime    | 2022-12-06 18:27:14 UTC                                             |
| End Datetime      | 2023-12-06 18:27:13 UTC                                             |
+-------------------+---------------------------------------------------------------------+
```
```
+-------------------+------------------------------------------------+
|                       Installed Certificate                        |
+-------------------+------------------------------------------------+
| User ID           | W443X7H6TV                                     |
| Common Name       | Apple Development: Status.im Auto (TD6NWBDSD9) |
| Organisation Unit | 8B5X2M6H2Y                                     |
| Organisation      | Status Research & Development GmbH             |
| Country           | US                                             |
| Start Datetime    | 2022-12-06 18:24:54 UTC                        |
| End Datetime      | 2023-12-06 18:24:53 UTC                        |
+-------------------+------------------------------------------------+
```

**Comment by jakubgs** [comment]
The CI build is failing with:
```
[18:45:11]: Could not find App ID with bundle identifier 'im.status.ethereum.pr'
[18:45:11]: You can easily generate a new App ID on the Developer Portal using 'produce':'
```
I think that's because our autobot is still part of the old org.

**Comment by jakubgs** [comment]
Looks like the `Status PR` identifier also needs some additional Capabilities:

image
image
image

**Comment by jakubgs** [comment]
I tried removing existing provisioning profiles:
```
jenkins@maci7-03.ms-eu-dublin.ci.devel:~ % rm -fr ~/Library/MobileDevice/Provisioning\ Profiles/*
zsh: sure you want to delete all 28 files in /Users/jenkins/Library/MobileDevice/Provisioning Profiles [yn]? y
```
But the issue persists.

**Comment by jakubgs** [comment]
It complains that:
```
Could not find App ID with bundle identifier 'im.status.ethereum.pr'
```
But it clearly exists because this is what I get from `fastlane produce -a im.status.ethereum.pr --skip_itc`:
```
[DevCenter] App 'im.status.ethereum.pr' already exists, nothing to do on the Dev Center
```
Maybe I need to drop the `--skip_itc` flag.

**Comment by jakubgs** [comment]
I tried that:
```
[20:09:02]: [DevCenter] App 'im.status.ethereum.pr' already exists, nothing to do on the Dev Center
[20:09:06]: To not be asked about this value, you can specify it using 'app_name'
[20:09:06]: App Name: Status PR
[20:09:11]: Creating new app 'Status PR' on App Store Connect
[20:09:11]: Sending language name is deprecated. 'English' has been mapped to 'en-US'.
[20:09:11]: Please enter one of available languages: ["ar-SA", "ca", "cs", "da", "de-DE", "el", "en-AU", "en-CA", "en-GB", "en-US", "es-ES", "es-MX", "fi", "fr-CA", "fr-FR", "he", "hi", "hr", "hu", "id", "it", "ja", "ko", "ms", "nl-NL", "no", "pl", "pt-BR", "pt-PT", "ro", "ru", "sk", "sv", "th", "tr", "uk", "vi", "zh-Hans", "zh-Hant"]
[20:09:15]: Ensuring version number
[20:09:15]: Successfully created new app 'Status PR' on App Store Connect with ID 1658398663
1658398663
```
And now I can see another App in the store, but that's not how it was on the old org:

image

Weird, I wonder how this worked before.

**Comment by jakubgs** [comment]
And that didn't work either:
```
Could not find App ID with bundle identifier 'im.status.ethereum.pr'
```

**Comment by jakubgs** [comment]
This might possibly be the reason, or one of the reasons:
```
[nix-shell:~/status-mobile]$ security find-identity -v -p codesigning
  1) B68E1B407C013B517675A30A3463D20E0A96BA00 "Apple Development: Status.im Auto (TD6NWBDSD9)"
  2) 723EB78FC0FB68F46E4C9EA8251D36C9A1423979 "Apple Distribution: Status Research & Development GmbH (8B5X2M6H2Y)"
     2 valid identities found
```

**Comment by jakubgs** [comment]
Okay, i think I know what it is. I think it's because the Fastlane access is using an [ASC API Key](https://developer.apple.com/documentation/appstoreconnectapi/creating_api_keys_for_app_store_connect_api) which we started using here:

* https://github.com/status-im/status-mobile/issues/11713#issuecomment-773234309
* https://github.com/status-im/status-mobile/pull/11714
* https://github.com/status-im/status-jenkins-lib/pull/22

So I probably need to create a new key for the new account to make this work.

**Comment by jakubgs** [comment]
Made a new key in `Users and Access > Keys > App Store Connect API`:

image

And updated All the ASC credentials: Key ID, Issues ID, and the Key File.

**Comment by jakubgs** [comment]
Nice, looks like that was it. A successful build:

image

https://ci.status.im/blue/organizations/jenkins/status-mobile%2Fprs%2Fios/detail/PR-14411/11/pipeline/

DAMN I'm good.

**Comment by pavloburykh** [comment]
@jakubgs thanx for the PR. LGTM. Ready for merge.

**Pull request merged**
