### PR TITLE
Fixed "Download latest nightly" button for Mac

### PR DESCRIPTION
**Pull request by flexsurfer**

### CODE REVIEW

**Comment by flexsurfer** [comment]
@PombeirP @chadyj  do we want this button for Win as well?

**Comment by chadyj** [comment]
Thanks for fixing this 

> @PombeirP @chadyj do we want this button for Win as well?

Would be great :)

**Review by vitvly — APPROVED** [review]

**Comment by goranjovic** [comment]
@flexsurfer Any description, issue reference..?

**Comment by flexsurfer** [comment]
@goranjovic nothing :( just approve please :)

**Review by pedropombeiro — APPROVED** [review]

**Review by rcullito — APPROVED** [review]

**Pull request merged**
