### PR TITLE
Prettify macOS installation .dmg bundle

### LINKED ISSUE #5423: Refine macos app bundle installation experience
**Issue**

It was reported that just replacement of app bundle in Applications directory is not working as expected (old app should be removed to trash manually in advance).
Installation flow is not obvious for users as well.

**Type:** Bug.

**Solution**: Background image for mounted .dmg or at least symlink to Applications folder will enhance app installation user experience. Replacement of available app bundle in Application with new one should work.

**Tasks**:

- [x] add  symlink to Applications folder for mounted .dmg 
- [x] make possible to replace app in Application folder for  reinstalling

### PR DESCRIPTION
**Pull request by gnl**
Closes #5423. 

## Summary

* Add https://github.com/LinusU/node-appdmg as an optional, macOS specific NPM dependency to create the nicer bundle without affecting the build on non-macOS platforms.

* Rename `StatusIm` to `Status`

* Get bundle skeleton from updated `status-im/StatusAppFiles` repo and point to a specific commit insted of `master` to minimise the risk of future breakage.

## ToDo

Will need a lossless TIFF/PNG Retina and non-Retina background image for this...:

screen shot 2018-08-29 at 22 58 16

...so that it looks somewhat like this...:

https://github.com/LinusU/node-appdmg#json-input

But more status-y. :)

## To Test

Installation, launch, login.

### CODE REVIEW

**Comment by EugeOrtiz** [comment]
Designs and specs can be found here >> zpl.io/VknWQKL (Zeplin, permission required)

group 2

**Review by maxhora — APPROVED** [review]

**Review by vkjr — APPROVED** [review]

**Review by jakubgs — APPROVED** [review]
I'm going to approve this but the desktop team really needs to work on automating their build process using something that can by run by a user on their dev machine. If it's just in a `groovy` script/`Jenkisfile` it cannot be.

Also, since when is a shell script file extension a `.bash` instead of `.sh`?

**Comment by gnl** [comment]
@jakubgs 
> I'm going to approve this but the desktop team really needs to work on automating their build process using something that can by run by a user on their dev machine. If it's just in a groovy script/Jenkisfile it cannot be.

Agreed – #5406.

> Also, since when is a shell script file extension a .bash instead of .sh?

Since never, that's just my own thing in order to distinguish between `/bin/sh` and `/bin/bash`. I don't use Bash and rarely write scripts for it so it doesn't quite jump out at me as hard, but I do know it's weird and noone does it, so – fixed.

**Comment by churik** [comment]
@gnl is it expected to have `.background` folder inside mounted disk?
upgr

**Comment by churik** [comment]
As it turned out, I have option "To show hidden files" enabled by default.
Tested: 
- installation
- launching
- log in.
Doesn't affect mobile builds.

**Pull request merged**
