### PR TITLE
Instabug Integration

### PR DESCRIPTION
**Pull request by jarradh**
Instabug allows testers to report feedback, record videos and screenshots within the application.

- [x] I would have also like to add another message for Console, just after phone request message to say "Find a bug or have a suggestion? Just *shake* your phone!" but sign_up.cljs is kind of hard for me to read.

- [x] Should also have a "Got Feedback?\nShake your phone!" in drawer at bottom, text centre aligned.

### CODE REVIEW

**Comment by rasom** [comment]
@jarradh Does it look fine? Should it be bigger/smaller? 

screen shot 2016-11-14 at 16 54 26

**Comment by jarradh** [comment]
thanks for trying to interpret my terrible instructions - shall we get rid of invite friends and FAQ since they don't do anything and do this?

feedback

**Comment by rasom** [comment]
ok, thanks, will do this

**Comment by rasom** [comment]
I added Instabug using cocoapods (https://instabug.com/developers), so from this moment we have to install dependencies via `cd ios; pod install` 

Another change is that we have to open `StatusIm.xcworkspace` instead of `StatusIm.xcodeproj` to run the application.

**Comment by jarradh** [comment]
okay, i was under the assumption that step wasn't necessary if using npm, but good to know, will add to developer guide

**Pull request merged**
