### PR TITLE
[#7002] Add a JS API allowing to install an extension

### LINKED ISSUE #7002: Add a JS API allowing to install an extension
### User Story

As a DApp developer, I want to have access to a JS API to easily add an extension.

```javascript
window.web3.currentProvider.status
 .installExtension("https://get.status.im/extension/ipfs@Qmb1B3jXNdc9WZCcWFzpkTXtrurnKxYQFvUDhp2J4SVCCX")
```

### Description

*Type*: Feature

### PR DESCRIPTION
**Pull request by flexsurfer**
fixes #7002

QA: you can find "install extension" button in simple dapp fro testing

### CODE REVIEW

**Review by jeluard — APPROVED** [review]

**Review by goranjovic — APPROVED** [review]

**Comment by asemiankevich** [comment]
@jakubgs iOS build generated here has link to `null`. https://github.com/status-im/status-react/pull/7031#issuecomment-444907248

**Comment by jakubgs** [comment]
>@jakubgs iOS build generated here has link to null. #7031 (comment)

Oh, because DIAWI uploads are set to be done only during nightlies:
https://github.com/status-im/status-react/blob/develop/ci/Jenkinsfile.ios#L72

Does this mean we should always upload to DIAWI, regardless of build type? I can change that.

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/status-im/status-react">status-im/status-react</a></strong></div><div>a free (libre) open source, mobile OS for Ethereum - status-im/status-react</div></blockquote>

**Comment by asemiankevich** [comment]
> > @jakubgs iOS build generated here has link to null. #7031 (comment)
> 
> Oh, because DIAWI uploads are set to be done only during nightlies:
> https://github.com/status-im/status-react/blob/develop/ci/Jenkinsfile.ios#L72
> 
> Does this mean we should always upload to DIAWI, regardless of build type? I can change that.
> 

Well diawi is used for iOS builds in 100% cases i guess (the only exception is TestFlight). So yeah i think that should be changed

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/status-im/status-react">status-im/status-react</a></strong></div><div>a free (libre) open source, mobile OS for Ethereum - status-im/status-react</div></blockquote>

**Comment by asemiankevich** [comment]
i was able to install 'Principles` extension via Status Test dapp, looks great!

**Comment by jakubgs** [comment]
Fix: https://github.com/status-im/status-react/pull/7040

**Comment by StatusSceptre** [comment]
@flexsurfer Could you add doc for this? :)

**Pull request merged**
