### PR TITLE
fix contrast between Chats and Communities with new messages

### LINKED ISSUE #21231: Lack of contrast between Chats and Communities with new messages compromises UX
# Design Feedback 2.30

## Lack of contrast between Chats and Communities with new messages compromises UX
The colour difference between chats/communities without new messages and chats/communities with notifications is not being implemented correctly. 

Figma review [here](https://www.figma.com/design/oznddnBnDbLlLQIaACYNuj?node-id=2227-55758#931801674)

We received [feedback](https://status.app/cc/G8IAAOT314Z6YqSHpFOJaCNpsn9miJfMOol1QiNGdHLgcPxOdvtaAJbmAeYpC000gcx-F37xQoalBs6t9P_9-kIn251IA4YfYo9CZnZBl-u5sZ47JkhMcN5fT7oJhqnP5K-BezYN0E_Pw2UP-j486xWpEsxogA4HCloRxTXPFExfrQvbPFGwap78XajmJ9XJdrm-0J-IWDJR5bmeiExGMUVEyiziSYFlTBIpikCyhmrIEuJ4CYk=#zQ3shZeEJqTC1xhGUjxuS4rtHSrhJ8vUYp64v6qWkLpvdy9L9) complaining about how hard it is to see the notification dot next to chats with new messages ➡️ problem is the whole chat name should be a different colour, making it easier for the user, as per design

#### Expected behavior

Screenshot 2024-09-09 alle 15 27 08

##### [Light mode]
- if there's no mention or notification the community name should be grey (Neutral/Solid/50)
- notification or mention ➡️ community/chat is black

>
>
Screenshot 2024-09-09 alle 15 29 03

##### [Dark mode]
- if there's no mention or notification the community name should be grey (Neutral/Solid/40)
- notification or mention ➡️ community/chat is white

--------------------
#### Actual behavior

Screenshot 2024-09-09 alle 15 30 41
Screenshot 2024-09-09 alle 15 31 01

>
All the same colour with just the dot, making it hard for the user to see which chats/communities have new messages.

### Additional Information

- Status version: 2.30
- Operating System: Android, iOS
- Devices in the screenshots: iPhone 13, Realme 10

### PR DESCRIPTION
**Pull request by Parveshdhull**
fixes https://github.com/status-im/status-mobile/issues/21231

### Screenshots

status: ready

### CODE REVIEW

**Review by seanstrom — COMMENTED** [review]
Thanks for the PR 🙌 

Can you include some screenshots please since these changes are mostly colour related? 🙏

**Comment by Parveshdhull** [comment]
Thank you @seanstrom for reviewing PR. Updated PR description with screenshots.

**Review by seanstrom — APPROVED** [review]
Nice! thanks for the screenshots 📸, I think it looks right
Though will this be design-reviewed before merge?

**Comment by pavloburykh** [comment]
@Parveshdhull thank you for the fix. Looks good to me. 

@Francesca-G would you mind checking from your side as well? Thanx.

**Review by Francesca-G — APPROVED** [review]
Nice job 👍

**Comment by pavloburykh** [comment]
> Nice job 👍

Thank you @Francesca-G 

@Parveshdhull PR is ready for merge now.

**Pull request merged**
