### PR TITLE
[WIP] Improve content 

### LINKED ISSUE #5088: Improve in-app content for clarity and accuracy
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want clear, consistent and accurate copy and tone so that guidance is clear and I'm confident in my actions.

### Description

Status has evolved but the app has a mismatch of styles, different terms, and lacks a cohesive copy tone and brand voice.

Now that @obi2020 is onboard we can take a fresh look at this.

### PR DESCRIPTION
**Pull request by chadyj**
fixes #5088 

### Summary:

Improves app copy

### Steps to test:
- Open Status
- ...
- Step 3, etc.

status: wip

### CODE REVIEW

**Review by obi2020 — COMMENTED** [review]
I don't understand the change from "web" to "system" - This is opening in Chrome or Brave, for example, vs opening in the Status browser?

**Comment by chadyj** [comment]
> I don't understand the change from "web" to "system" - This is opening in Chrome or Brave, for example, vs opening in the Status browser?

One option opens in Status with the web3 Dapp Browser, and the other in the system default browser such as Safari or Chrome.

**Comment by jeluard** [comment]
@chadyj Is this PR still wip?

**Comment by chadyj** [comment]
@jeluard Yes, @obi2020 is going to give some love to our copy, and this PR is a WIP so jenkins can build the app automatically so Obi can review copy in-app. No engineer required :)

**Comment by obi2020** [comment]
@chadyj Install link failed to generate after another comment. Notice above says there are conflicts that need to be resolved. Could this be why?

**Pull request closed without merging**
