### PR TITLE
Backup of contacts through waku

### PR DESCRIPTION
**Pull request by cammellos**
Fixes: #12745 

Adds backup of contacts through waku.

### Testing

1) Create an account
2) Save the seed phrase
3) Add some people to your contacts, or block or add nicknames
4) Make sure that a backup has been performed after you added your contacts (Go to Settings -> Sync settings -> Backup and you can trigger a backup)
5) Uninstall the app
6) Install the app
7) Restore the same seed phrase
8) Check that contacts added in step 3 are there

status: ready

### CODE REVIEW

**Comment by churik** [comment]
@cammellos 
1. most of possible failures due to same multiaccount on device are addressed by small fix: https://github.com/status-im/status-react/pull/12756
2. `test_pair_devices_sync_one_to_one_contacts_nicknames_public_chat` is failed due to issue that unblocking user doesn't sync with paired device:

**Steps:**
- pair Device1 and Device2
- from Device1 block userA
- from Device1 unblock userA

**Expected result:** userA unblocked on Device2
**Actual result:** userA is blocked on Device2

**Review by Parveshdhull — DISMISSED** [review]
lgtm
fixes #12550 ? (PR Summary)

**Comment by Parveshdhull** [comment]
**Issue**: App is crashing after clicking on saved contact (iOS)

https://user-images.githubusercontent.com/17097240/139349060-9a5c00b0-60d9-4e2e-b7d7-bd1cd6b491ed.MP4


**Edit 1:** Other than this issue, contact restoring working great 👍


**Edit 2:** Issue is only happening in iOS, android works fine 👍

**Comment by churik** [comment]
@cammellos please ping me when it is ready to test, thank you!

**Comment by rasom** [comment]
@Parveshdhull @churik 
I ca't reproduce crash on my iOS devices

**Comment by churik** [comment]
I could reproduce on IPhone 12, IOS 14.8.
Will try on IOS 15 shortly

**Comment by Parveshdhull** [comment]
> I could reproduce on IPhone 12, IOS 14.8. Will try on IOS 15 shortly

Reproducible on IOS 15.1 too

**Comment by Parveshdhull** [comment]
> @Parveshdhull @churik I ca't reproduce crash on my iOS devices

Did you tried PR build? if `^js` type-hint is missed, then error only occurs in PR

**Comment by churik** [comment]
So steps are:
- install PR build
- create multiaccount
- tap on Profile > Contacts > + 
- Add one contact (via QR or via ENS)
- tap on added contact from contacts list

**Comment by cammellos** [comment]
@churik it should be fixed in the next build, thank you and @Parveshdhull for spotting the issue!

**Comment by Parveshdhull** [comment]
It is still reproducible in the new build. @churik can you please confirm?

**Comment by churik** [comment]
confirmed, reproducible on the last build https://github.com/status-im/status-react/commit/8551e2fb3327ecfaa9a1565f90021ba3dbd04cf5

**Comment by cammellos** [comment]
Thank you @churik @Parveshdhull , I'll try to figure out what's happening

**Review by flexsurfer — APPROVED** [review]

**Comment by cammellos** [comment]
@churik would you mind replicating the issue on the latest build and send me the geth.log if you have some time?
Thank you

**Comment by churik** [comment]
@cammellos 
replicated, that's all I can get from IOS without building app locally
[geth.log](https://github.com/status-im/status-react/files/7467020/geth.log)

**Comment by cammellos** [comment]
@churik would you mind doing the same with the latest build? I have addressed some issues that might have caused the behavior :crossed_fingers: 
Thank you

**Comment by churik** [comment]
sorry, didn't help.
Found another way to reproduce: after adding an account can just tap on one of the suggested public chats, app will crash

**Comment by cammellos** [comment]
@churik would you mind sending me the geth.log please for both scenario?
Thank you

**Comment by churik** [comment]
@cammellos sure
1) Tap on public chat > crash:
[geth.log](https://github.com/status-im/status-react/files/7468556/geth.log)

2) Add contact > tap on it > crash:
[geth.log](https://github.com/status-im/status-react/files/7468559/geth.log)


Hopefully they will be useful.

**Comment by cammellos** [comment]
@churik Issue 1 should be resolved, issue 2 might be, would you mind trying the latest build please?
Thanks

**Comment by rasom** [comment]
@cammellos, it crashes on opening an empty pub chat:
```
StatusIm`github.com/status-im/status-go/protocol/common.(*Message).String:
    0x10275c460 <+0>:  movq   0x8(%rsp), %rax
->  0x10275c465 <+5>:  testb  %al, (%rax)
    0x10275c467 <+7>:  movq   %rax, 0x8(%rsp)
    0x10275c46c <+12>: xorps  %xmm0, %xmm0
    0x10275c46f <+15>: movups %xmm0, 0x10(%rsp)
    0x10275c474 <+20>: jmp    0x1026d94e0               ; github.com/status-im/status-go/protocol/protobuf.(*ChatMessage).String
    0x10275c479 <+25>: int3   
    0x10275c47a <+26>: int3   
    0x10275c47b <+27>: int3   
    0x10275c47c <+28>: int3   
    0x10275c47d <+29>: int3   
    0x10275c47e <+30>: int3   
    0x10275c47f <+31>: int3   
```
again
```
StatusIm`github.com/status-im/status-go/protocol.(*Messenger).MessageByChatID:
```
https://gist.github.com/rasom/7d713ab49ab08756c37d50197b2ee37b

**Comment by rasom** [comment]
@cammellos, I'm taking it back, it probably was yesterdays build...

**Comment by churik** [comment]
Crashes are not reproducible on my side anymore, taking PR in testing

**Comment by cammellos** [comment]
Awesome, thanks a lot for your patience and help @rasom & @churik

**Comment by churik** [comment]
@cammellos works awesome!
###  Question 1: if nickname was set up without adding user to contacts, should it be backed up?
The same question for `Mute` option.

### Issue 2: if using same multiaccount on both devices, after blocking contact and performing backup of contacts app is crashing on second device
**Steps:**
- `device a, b`: restore the same multiaccount on both devices
- `device a`: add contact
- `device a`: perform contact backup, so this contact will be shown on device b
- `device a`: block this contact
- `device a`: perform contact backup

On `device b` app is crashing.

Logs from device b: [Status-debug-logs.zip](https://github.com/status-im/status-react/files/7476633/Status-debug-logs.zip)

**Comment by cammellos** [comment]
Thanks for testing @churik 

> Question 1: if nickname was set up without adding user to contacts, should it be backed up?
The same question for Mute option.

Nickname should be backed up, yes, I'll make sure it is.
Mute not currently, we could address that separately if that's ok.

I'll fix issue 2 and take a look at nickname.

**Comment by churik** [comment]
@cammellos 
found cause of failed e2e.
### ISSUE 3: when starting chat with ENS - it is resolving to 3-random username

**Steps:**
1) restore multiaccount from seed phrase
2) tap on + > start new chat
3) enter valid ENS on ropsten (i.e. `sergey`)
4) tap on found user

**Expected result:**
Can see chat with `sergey`
**Actual result:**
chat with 3-random username

**OS:** IOS, Android

**Comment by cammellos** [comment]
@churik issue 2 & 3 should be fixed.
Nickname should be synced even if not in contacts. Mute currently is not synced as it's a different mechanism, if that's ok we'll address separately.
Thank you

**Comment by churik** [comment]
@cammellos thank you for fixes!
### ISSUE 4: "Last backup performed" updated every time on toggle switch
https://user-images.githubusercontent.com/4557972/140944479-20d4c68c-9e67-42d5-880f-720402c2b166.mp4

**OS:** Android

### ISSUE 5: can't restore contacts from backup made 5 days ago
Not sure it is a valid case, but currently the only way to see if the backup is preserved if it was made > 24h ago (in 2 days can recheck on fresh build)
Initially was tested on build with commit https://github.com/status-im/status-react/commit/121a67ed26fea8fae2858e874eac1288b13f2379

**Steps:** 
- created multiaccount, add contacts on 04/11/21, made backup (build https://github.com/status-im/status-react/commit/121a67ed26fea8fae2858e874eac1288b13f2379 )
- restored on build https://github.com/status-im/status-react/commit/9462b4c84db649d8c9c48e516b63d806ee43f64e
Multiaccount: `cinnamon memory exist cost found design pave learn income purse top shop`

**Expected result:**
contacts will be preserved

**Actual result:**
no contacts are preserved

**OS:** IOS, Android

**Comment by cammellos** [comment]
@churik thanks

I think issue 4 if that's fine will be a won't fix, basically the UI is only updated when something happens, so we re-calculate the date only when the user performs an action. Otherwise we could fix separately?

Issue 5 I will take a look, we should def support more than 24h

**Comment by cammellos** [comment]
@churik should be fixed now,
unfortunately you won't be able to recover those old backups as they were sent to the wrong topic, so you will have to test with a fresh account/backup, sorry for the inconvenience.

**Comment by churik** [comment]
fixes #12776

**Comment by churik** [comment]
contacts/blocked users are restored in 5 days. Waiting for e2e results and ready to go.

**Comment by churik** [comment]
e2e failures are not related to PR.

**Devices:**
- IPhone 12 Mini (IOS 14)
- IPhone 7 (IOS 13)
- Xiaomi Mi Note 9 Pro (Android 10)

**Pull request merged**
