### PR TITLE
[WIP] Increase password check to 8 characters and add some basic weakness checks.

### LINKED ISSUE #13137: Increase password requirement
As a user
I want to have a minimum number of characters in my password enforced
So I don't mistakenly choose a weak password

### Description

We should enforce (client side) a minimum of 8 characters for the password
Ideally we exclude a list of common passwords, as per original comment below, but can be done separately

### Original comment

As per the DejaVu security audit that was done in 2018, we should increase the password requirements.

Here's what they said:
> Status currently enforces the user to create a password that is six character or longer. If the user's device were ever compromised and the encrypted private keys were obtained, it would be a trivial task for an attacker to brute force a weak password and decrypt the user's private key.

We should increase the limit to 8 characters, and prevent users from entering passwords with low entropy such as "000000" or "querty". Right now, there's 56 billion possible combinations if the user is using a 6 character password (`62^6`) but that is increased to 218 trillion combinations with an 8 character minimum (`62^8`) which would take longer to crack, without interference to the user.

In addition, we should also allow characters from other systems such as Chinese, Cyrillic, Arabic, and Emojis to add to the allowed complexity.

### PR DESCRIPTION
**Pull request by dangarbri**
Fixes #13137

### Summary

Password limit should be increased to 8 characters and we should have some
checks to make sure users are not entering weak passwords.

In this PR, I've updated the minimum password length to 8 characters and added 2 weakness checks:
 - Make sure the password characters are not all repeated i.e. "aaaaaaaa" and "11111111" are not allowed
 - Make sure passwords are not sequential characters i.e. "abcdefgh" and "12345678" are not allowed

I've also created a password utility so that the onboarding screen and password reset screens can share
the same password validation code.

### Testing notes
Tested on android by inputting passwords to test failing conditions.
- entered 'aaaaaaaa'
- entered '12345678'
- entered other strings of characters

#### Platforms
- Android
- iOS

#### Areas that maybe impacted
- Onboarding password creation
- Password reset

##### Functional
- new account
- user profile updates

### Steps to test
- Clear status storage to simulate being a new user
- Go through onboarding process and create a password, verify password meets minimum requirements mentioned in summary
- Change password and verify password meets minimum requirements mentioned in summary.

status: Ready

### CODE REVIEW

**Comment by dangarbri** [comment]
How do I properly create a namespace? I'm getting this error:

The required namespace "status-im.utils.password-resources" is not available, it was required by "status_im/ui/screens/onboarding/password/views.cljs".

I have (ns status-im.utils.password-resources) in my password_utils.cljs file.

**Comment by dangarbri** [comment]
My all-same function is failing by saying the password is not ISeqable, it should just be a string though, right?

**Comment by dangarbri** [comment]
Found the build documentation and was able to fix my issue. Tested on android.

**Comment by du82** [comment]
The word "phenomenon" fits the requirements that you've listed, but it won't let me create an account. Adding a unicode character (Chinese, Emoji, Symbols) to the end doesn't allow me to create the account either.

Screenshot_20220307-193257_Status PR
Screenshot_20220307-193348_Status PR

**Comment by dangarbri** [comment]
Shoot, let me check on that

**Comment by dangarbri** [comment]
@ducheng0 thanks for catching that, I must have tested without my latest changes, my mistake.
The problem was with my is-sequential function, clojurescript doesn't cast to int like regular clojure, I had to change my character -> number function to use charCodeAt.

It's working now.
Screenshot_20220307-224926

**Comment by du82** [comment]
looks good to me!

**Review by cammellos — APPROVED** [review]
Great job, thanks @dangarbri .
I will approve you to work on the bounty on gitcoin and as soon as it's tested ok I will release the bounty.
Thanks again!

**Comment by qoqobolo** [comment]
Hello @dangarbri, thank you for the contribution!
Could you rebase your PR against the latest develop, please?
After that, PR will be tested. Thanks!

**Comment by dangarbri** [comment]
@qoqobolo @cammellos Rebased, thanks!

**Comment by dangarbri** [comment]
Ah, the test is failing because it can't find the 2nd password input.
It types 'qwerty' into the first one and expects the 2nd input to become available. But it doesn't because it doesn't meet the new minimum requirements.

**Comment by pavloburykh** [comment]
> Ah, the test is failing because it can't find the 2nd password input. It types 'qwerty' into the first one and expects the 2nd input to become available. But it doesn't because it doesn't meet the new minimum requirements.

yeah, this is known issue. we will update test data and then re-run failed tests.

**Comment by dangarbri** [comment]
I updated where I think it was getting qwerty from to qwerty1234. If that's the right place to update it then this should work now.

**Comment by pavloburykh** [comment]
@dangarbri Thanx for your contribution! Please, take a look at following issue. 

### ISSUE 1 Unable to login into account after app upgrade if initial account password does not meet new validation rules 

Steps: 

1. Install any other PR build in order to have possibility to set 6 char password . For instance, you can use this build for Android https://status-im-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-220324-045209-8529e1-pr13185-universal.apk
2. Create an account and set 6 char password
3. Upgrade to current PR build
4. Try to login the account using existing 6 char password

Actual result: Sign in button is disabled. 

Expected result: user with old passwords (< 8 char, no basic weakness validation) should be able to Sign in their accounts. 
photo_2022-03-28 19 18 09

**Comment by dangarbri** [comment]
Mmmm, good catch. I'll work on that.

**Comment by pavloburykh** [comment]
### ISSUE 2 No validation error is shown to user when he tries to reset password to value that does not meet basic weakness checks (e.g. "aaaaaaaa", "12345678", "abcdefghi" etc)

Steps: 

1. Open Status App
2. Sign in / Sign up an account
3. Go to Profile - Privacy and security - Reset password
4. Fill in Current password values
5. Fill in new password and confirm new password field with invalid values that does not meet basic weakness checks ("aaaaaaaa", "12345678", "abcdefghi" etc)
6. Pay attention if there are any validation errors

Actual result: no validation errors are shown that could provide user with info why he is unable to proceed with password reset. The text below password fields do not contain any info about basic weakness reqs, only about minimum 8 chars and type of chars (unicode/emoji).
photo_2022-03-29 12 31 44
photo_2022-03-29 12 31 53


Expected result: user must be shown validation error just like he is shown during initial password set.

**Comment by dangarbri** [comment]
Issue 1 resolved, still working on issue 2.

**Comment by flexsurfer** [comment]
hey @dangarbri are you still working on this issue ?

**Comment by dangarbri** [comment]
Hey, yes and no. If someone else wants to wrap up the last issue here, that
would be good. I haven't had time to work on this lately.

**Comment by flexsurfer** [comment]
feel free to reopen if needed

**Pull request closed without merging**
