### PR TITLE
update to latest status-go

### LINKED ISSUE #4473: Update status-react with new status-go version (contains new enodes)
### Problem

Current enodes are running on the old cluster, which lacks monitoring/logs/scalability. Additionally, the IPs are tied to specific hosts, as opposed to floating IPs that can be moved between hosts.

### Solution

Bump status-go version status-react as soon as https://github.com/status-im/status-go/pull/994 is merged.

Additionally, update Whisper enodes in status-react as well.

### Notes

This is expected to break communication with previous cluster, so it requires some extensive testing.

See https://github.com/status-im/status-go/issues/958

Russia issue:
- https://github.com/status-im/status-cluster/issues/107
- https://github.com/status-im/status-react/issues/4299#issuecomment-392414137

### PR DESCRIPTION
**Pull request by cammellos**
fixes #4473

### Summary:

Updates status-go to latest version

### Testing notes (optional):
General smoke testing

status: ready

### CODE REVIEW

**Review by gravityblast — APPROVED** [review]

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/CA2Uwn for branch PR-4501

<blockquote><div><strong><a href="https://i.diawi.com/CA2Uwn">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/vnWXMi for branch PR-4501

<blockquote><div><strong><a href="https://i.diawi.com/vnWXMi">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Review by rasom — APPROVED** [review]

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/PWeJJX for branch PR-4501

<blockquote><div><strong><a href="https://i.diawi.com/PWeJJX">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/ug9Qxr for branch PR-4501

<blockquote><div><strong><a href="https://i.diawi.com/ug9Qxr">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/MzjsWD for branch PR-4501

<blockquote><div><strong><a href="https://i.diawi.com/MzjsWD">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/npEy4w for branch PR-4501

<blockquote><div><strong><a href="https://i.diawi.com/npEy4w">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Pull request merged**
