### PR TITLE
fix: generate_profile_url crash when login

### LINKED ISSUE #18331: Debug app randomly crashes on login
### Problem

Sometime when logging in debug crashes with error:

<div align="center">
<img src="https://github.com/status-im/status-mobile/assets/17097240/4cd99b52-2144-470b-b55e-fc4d9fb36a79" alt="Screenshot" height="400"/>
</div>


<details>
  <summary>Metro logs</summary>

```
 WARN  Expected `console.groupEnd` to be called after `console.groupCollapsed`.                                                                                                                                                               
 LOG  PRETTY PRINTED EXCEPTION                                                                                                                                                                                                                
                                                                                                                                                                                                                                              
***                                                                                                                                                                                                                                           
NAME: "TypeError"                                                                                                                                                                                                                             
MESSAGE: status_im.common.universal_links(...)rl.cljs$core$IFn$_invoke$arity$2 is not a function (it is undefined)                                                                                                                            
                                                                                                                                                                                                                                              
TypeError: status_im.common.universal_links(...)rl.cljs$core$IFn$_invoke$arity$2 is not a function (it is undefined)                                                                                                                          
    at status_im$common$universal_links$generate_profile_url (JavaScript:1309:91)                                                                                                                                                             
    at call (native)                                                                                                                                                                                                                          
    at anonymous (JavaScript:131:116)                                                                                                                                                                                                         
    at re_frame$std_interceptors$fx_handler__GT_interceptor_$_fx_handler_before (JavaScript:141:4)                                                                                                                                            
    at call (native)                                                                                                                                                                                                                          
    at re_frame$interceptor$invoke_interceptor_fn (JavaScript:216:14)                                                                                                                                                                         
    at call (native)                                                                                                                                                                                                                          
    at re_frame$interceptor$invoke_interceptors (JavaScript:255:63)                                                                                                                                                                           
    at call (native)                                                                                                                                                                                                                          
    at re_frame$interceptor$execute (JavaScript:365:152)                                                                                                                                                                                      
    at call (native)                                                                                                                                                                                                                          
    at re_frame$events$handle (JavaScript:85:34)                                                                                                                                                                                              
    at call (native)                                                                                                                                                                                                                          
    at anonymous (JavaScript:577:32)                                                                                                                                                                                                          
    at re_frame$router$_process_1st_event_in_queue (JavaScript:161:77)                                                                                                                                                                        
    at anonymous (JavaScript:324:44)                                                                                                                                                                                                          
    at re_frame$router$_run_queue (JavaScript:205:60)                                                                                                                                                                                         
    at anonymous (JavaScript:415:34)                                                                                                                                                                                                          
    at call (native)                                                                                                    
    at anonymous (JavaScript:457:22)                                                                                    
    at re_frame$router$_fsm_trigger (JavaScript:117:62)                                                                 
    at anonymous (JavaScript:369:36)                                                                                    
    at apply (native)                                                                                                   
    at anonymous (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&minify=false&app=im.status.ethereum.debug&modulesOnly=false&runModule=true:44725:26)
    at _callTimer (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&minify=false&app=im.status.ethereum.debug&modulesOnly=false&runModule=true:44636:17)
    at callTimers (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&minify=false&app=im.status.ethereum.debug&modulesOnly=false&runModule=true:44844:19)
    at apply (native)                                                                                                   
    at __callFunction (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&minify=false&app=im.status.ethereum.debug&modulesOnly=false&runModule=true:15922:36)
    at anonymous (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&minify=false&app=im.status.ethereum.debug&modulesOnly=false&runModule=true:15642:31)
    at __guard (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&minify=false&app=im.status.ethereum.debug&modulesOnly=false&runModule=true:15859:15)
    at callFunctionReturnFlushedQueue (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&minify=false&app=im.status.ethereum.debug&modulesOnly=false&runModule=true:15641:21)
                                                                                                                        
***                                                        
 ERROR  TypeError: status_im.common.universal_links(...)rl.cljs$core$IFn$_invoke$arity$2 is not a function (it is undefined), js engine: hermes
```  

</details>

### PR DESCRIPTION
**Pull request by yqrashawn**
fixes #18331

### Summary

update the function to have fixed arity

### Review notes
I'm not sure if this is the reason
I checked `.shadow-cljs/builds/mobile/dev/ana/status_im/common/universal_links.cljs.cache.transit.json` and `generate_profile_url.cljs$core$IFn$_invoke$arity$2 ` is definitely defined
But I do come across the crash today

### Testing notes

I don't think it's possible to test this. It might be only a debug build thing.

status: ready

### CODE REVIEW

**Comment by Parveshdhull** [comment]
Thank you @yqrashawn for looking into the issue and PR.

> I'm not sure if this is the reason

Maybe @ilmotta might have some idea about this bug.

[Error](https://github.com/status-im/status-mobile/issues/18331#issuecomment-1873890980): 
> 2024-01-02T11:02:42.631Z ERROR [status-im.setup.schema:106] - Failed to initialize schemas {:error #object[Error Error: Schema error when instrumenting function: status-im.common.universal-links/generate-profile-url. Error: [object Object] is not ISeqable]}

**Review by Parveshdhull — APPROVED** [review]
We should find why Multi-arity functions didn't worked for schema, so we can fix that or avoid using them in future. But it looks this was the cause of issue and this fix works (tested locally on branch 19-20 times)

**Review by mohsen-ghafouri — APPROVED** [review]
Thank you @yqrashawn 🙂

**Comment by ilmotta** [comment]
Thanks for copying me @Parveshdhull. This problem is super tricky and that's why this comment is rather long. Please, bear with me guys. cc'ing @clauxx as well. I believe @J-Son89 hit some kind of bug with multi-arity function schemas in the past when he was trying to spec the function `resolve-color`. 

A few things to take in consideration:

1. Multi-arity schemas should use `[:function [:=> ...]]`, not `[:=> ...]` directly. The original code wasn't using it.
2. But even if `:function` is used, our macro `malli.core/schema` apparently is doing something that malli doesn't like.

Reproduction steps (using a REPL):

```clojure
(defn foo
  ([a]
   (foo a 99))
  ([a b]
   (+ a b)))

(foo 1) ; => 100
(foo 1 2) ; => 3

(malli.core/=> foo [:=> [:cat :int] :int])

;; Notice malli doesn't validate "a" is not an integer.
(status-im.setup.schema/setup!)
(foo "a") ; => "a99"

;; Eval again to re-instrument schemas, this time we see an absurd error because
;; clearly the 1-arity function is defined.
(status-im.setup.schema/setup!)
(foo "a") ; => status_im.common.universal_links.foo.cljs$core$IFn$_invoke$arity$1 is not a function

;; Now re-eval (defn foo ...) and define the schema correctly.
(malli.core/=> foo
               [:function
                [:=> [:cat :int] :int]
                [:=> [:cat :int :int] :int]])

(status-im.setup.schema/setup!)

;; Now malli correctly verifies the argument is not an integer and prints an error.
(foo "a")
;; -- Schema Error --------------------------------------------
;;
;; Invalid function arguments:
;; ["a"]
;;
;; Function Var:
;; status-im.common.universal-links/foo
;;
;; Input Schema:
;; [:cat :int]
;;
;; Errors:
;; {:in [0],
;;  :message "should be an integer",
;;  :path [0],
;;  :schema :int,
;;  :value "a"}
;;
;; ------------------------------------------------------------

;; Re-eval (defn foo ...).
;; This time, we simulate the code in develop this PR is fixing. We wrap the
;; schema in malli.core/schema and we don't wrap the schema in [:function ...].
(malli.core/=> foo (malli.core/schema [:=> [:cat :int] :int]))

;; We see the error the PR is trying to fix.
(status-im.setup.schema/setup!)
;; => Failed to initialize schemas {:error #object[Error Error: Schema error when instrumenting
;; function: status-im.common.universal-links/foo. Error: [object Object] is not ISeqable]}
```

-------

#### Some sort of conclusion...

Our macro `schema.core/=>` wraps every schema in `malli.core/schema`. I thought this was correct & safe given the official documentation (https://github.com/metosin/malli/blob/5211aca498ff7b022c36de4ca713990f5e731a9c/docs/function-schemas.md#multi-arity-functions)

Therefore, to fix the issue and any multi-arity function with a schema, we should:

1. Always wrap the "n-arity schemas" with `[:function [:=> ...] [:=> ...]]`.
2. Fix our `schema.core/=>` macro to not wrap `[:function ...]` with `malli.core/schema`. The reason I originally did this was to fail fast and print an exception in case the schema was invalid, which is great, but unfortunately it doesn't work with `:function`, so the macro should do a bit of parsing on the data structure and detect if we should wrap in `malli.core/schema`. Or not do this check at all, but that's bad because then the invalid schema won't fail at compile time, which I think is really nice/helpful.

**Comment by yqrashawn** [comment]
@ilmotta @Parveshdhull @mohsen-ghafouri I've updated the `schema.core/=>` macro

**Review by mohsen-ghafouri — APPROVED** [review]

**Review by ilmotta — APPROVED** [review]

**Pull request merged**
