### PR TITLE
test bugfix on windows

### PR DESCRIPTION
**Pull request by cammellos**
We will need to test creating new accounts and upgrading from previous version (any pr before this one).

https://github.com/status-im/status-go/pull/5255

### CODE REVIEW

**Review by qfrank — APPROVED** [review]

**Comment by pavloburykh** [comment]
Hey @cammellos! Thanks for the PR. Please take a look at the issue. 

### ISSUE 1 "App is not installed as package appears to be valid" when upgrading from the older app version (Android)

Android only. Tested on Samsung Galaxy A52, Android 12

**Steps:**

1. Install build from some other PR (I used latest build from this PR https://github.com/status-im/status-mobile/pull/20280)
2. Create/restore an account
3. Try to install build from current PR on top of other build to test upgrade
4. Observe the error

**Actual result:** "App is not installed as package appears to be valid" error appears. Unable to upgrade the app

photo_2024-06-03 12 40 49

**Comment by pavloburykh** [comment]
### ISSUE 2 Cannot login the account after upgarde

Tested on IOS

**Steps:** 

1. Install build from some other PR (I used latest build from this PR https://github.com/status-im/status-mobile/pull/20296)
2. Create/restore an account
3. Install build from current PR on top of other build to test upgrade
4. Try to login the account
5. Observe the error

**Actual result:** login results in error

photo_2024-06-03 12 51 17

**Comment by pavloburykh** [comment]
@cammellos I was able to test upgrade on Android using other PR, so ISSUE 1 seems to be not related to this PR. 

At the same time I am still facing ISSUE 2 on IOS cc @yqrashawn

**Comment by yqrashawn** [comment]
IMG_5990

able to reproduce ISSUE2 on iOS

**Comment by yqrashawn** [comment]
Able to reproduce ISSUE1 on a one plus 5, it says app not installed when upgrade
able to install and open the app if not upgrade from old one

**Comment by yqrashawn** [comment]
Just checked the status-go diff, I guess this `BackupDisabledDataDir` is causing ISSUE2? https://github.com/status-im/status-go/compare/v0.179.26...5186-cannot-login-on-windows#diff-3270068c140c83704dd9e117c7b423114a7f6b57307c42c1e68d1c210680fc52R1755-R1764

I'll try debug build tomorrow.

**Comment by yqrashawn** [comment]
Just tested upgrading from https://github.com/status-im/status-mobile/pull/20304 to https://github.com/status-im/status-mobile/pull/20316 on real device and the error in ISSUE2 is gone, able to log in successfully

**Comment by pavloburykh** [comment]
@cammellos closing this one as there is a new PR pointing at the new go branch https://github.com/status-im/status-mobile/pull/20316

**Pull request closed without merging**
