### PR TITLE
set maxFontSizeMultiplier for text and text-input components on iOS

### PR DESCRIPTION
**Pull request by rasom**
according to https://github.com/status-im/status-react/pull/7629#issuecomment-468605192

status: ready

### CODE REVIEW

**Review by mandrigin — APPROVED** [review]
lgtm

**Review by flexsurfer — APPROVED** [review]

**Comment by churik** [comment]
@rasom 
Font is still too large for DApps permissions popup:

I used max font (on 5 size I still able to see the buttons, on 6 and more (size font is the same starting from 6) - buttons are completely overlapped by footer.

Tested on IOS 11.4.1, IPhone 7.

**Comment by mandrigin** [comment]
@churik maybe we can make it a separate issue and issue a bounty on it?

**Comment by churik** [comment]
@mandrigin 
there is separate issue for this https://github.com/status-im/status-react/issues/7215 - issue is exactly about these screens, but in discussion turned out that problem is more general (text size).

So I don't mind actually - we can test and merge this PR, but the initial issue is still not fixed.

**Comment by rasom** [comment]
@churik @mandrigin ok then, let's fix that specific case separately

**Review by errorists — APPROVED** [review]

**Comment by churik** [comment]
Tested on IOS 11.4.1 with the largest font (from accessibility settings).
Tested:
- send, request transactions from chat and wallet
- another user profile view
- pairing (contact list  with 30+ contacts)
- meilserver, bootnodes, scan qr code views
- add custom network screen
- transaction history \ transaction view.
Except of small cutting the bottom part (pretty minor):
photo_2019-04-04 11 01 40 jpeg 2019-04-04 11-02-17 

and  https://github.com/status-im/status-react/issues/7215 (which should be separate bounty) - looks good to me.
Also checked that I can use Android version with largest font (LG V20, Android 8)

**Pull request merged**
