### PR TITLE
The concept of command actions; @browse command actions (#860)

### LINKED ISSUE #860: Going back on webview / on a web page.
### User Story

As a user, I want to be able to go back on a web page/DApp so that i don't get thrown out of browse everytime i hit Back.

### Description
The Back function is quite commonly used when browsing the internet, people are used to it, and not having it can sometimes disrupt the user experience.

*Type*: Feature

#### Expected behavior
When browsing a web page/DApp, and i want to go back to a previous page, i hit the back button on my Android phone and go back to the previous page that i was browsing.

#### Actual behavior
When browsing a web page/DApp, and i want to go back to a previous page, i hit the back button on my Android phone to get back to the previous page that i was browsing, upon hitting back, i get thrown out of browsing, back to the Chats/Contacts page.

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Open ie. Gnosis
- Open ☰ / Menu
- Select API
- You're now on the API Docs, the DApp menu and UI is no longer visible, hit Back to go back to the DApp.
- Thrown back to Chats/Contacts.

### Solution
There should be some way to go back on sites, i've only tested with one Android device, so this can be caused by a different keyboard or device or something.

### Additional Information
* Status version: 0.9.3
* Operating System: Android

### PR DESCRIPTION
**Pull request by alwx**
Fixes #860

### CODE REVIEW

**Comment by alwx** [comment]
This PR adds "actions" for DApps, and demonstrates the idea by making `/browse` command work the way it's specified in Zeplin sketches.

screen shot 2017-05-01 at 19 06 04

**Comment by annadanchenko** [comment]
Issue "Tap on back button does not return to previous page":
1. Open Commiteth 
2. Tap on any link on home page that opens issue description in github
3.  As soon as github page is opened, "back arrow" is active. Tap on back to return to Commiteth page
Currently: nothing happens. Same gihub page is shown
Expected: Commiteth page from step#1 is shown

**Comment by annadanchenko** [comment]
Issue "Can't send new url if type it after page loads (no send button and no Enter on keyboard)
- Open Commiteth
- in input field for browse command type new url, e.g. google.com
- try to send it

**Comment by alwx** [comment]
Fixed both issues

**Comment by annadanchenko** [comment]
still testing.... on Android can go back/fwd most of the times, but there is one case found when it can't go back: from Commitheth open "Crash on Login.." issue with Instabug links in it. Tap on Instabug link. As soon as Log in page is shown, tap on back. It does not go back to github but stays on same page
Video: https://drive.google.com/open?id=0Bz3t9zSg1wb7cGRRUE9Id1FPbUU

**Comment by annadanchenko** [comment]
There is also #1155 found during testing this PR

**Comment by alwx** [comment]
Done. Both issues will be solved separately.

**Pull request merged**
