### PR TITLE
fix JSC locking #2771

### PR DESCRIPTION
**Pull request by rasom**
It was found that JSC doesn't get locked if we call it in the same thread. Unfortunately i don't have explanation atm.

Fix https://github.com/status-im/status-react/issues/2721

status: ready

### CODE REVIEW

**Comment by rasom** [comment]
also probably fixes #2757

**Review by oskarth — APPROVED** [review]
Are there any other consequences of using a an executor? Like blocking somehow?

**Review by janherich — APPROVED** [review]

**Comment by rasom** [comment]
@oskarth that's not related exactly to executor, if we use `Thread` class result is the same. I think the reason is somewhere in `com.github.ericwlange:AndroidJSCore:3.0.1`.

**Comment by oskarth** [comment]
Sorry I mean, does commenting this out:

```
//executor.execute(new Runnable() {
+        //    public void run() {
```

Change semantics of how run is called/blocking etc? Guess if this fixes issue it is fine, but I thought it was there for a specific reason.

**Comment by rasom** [comment]
Yes sure, the reasons are:
1. http://facebook.github.io/react-native/docs/native-modules-android.html#threading, i doubt that this is a heavy operation but still there could by anything in JS 
2. the call may last up to 5 minutes, and assumption was that this will lock main thread though it doesn't. And again `Native modules should not have any assumptions about what thread they are being called on`

**Review by yenda — APPROVED** [review]

**Comment by asemiankevich** [comment]
@oskarth the app is irresponsive on iOS after several seconds 
https://app.testfairy.com/projects/4803590-status/builds/7456853/sessions/7/?accessToken=UISzXhPeskwYSeUvi1/uQs4MBIM

and it is really slow on Android

**Comment by oskarth** [comment]
^ @rasom probably, let's move it back to CONTRIBUTOR

**Comment by rasom** [comment]
@asemiankevich @oskarth original issue was only about Android, so i was under impression that problem doesn't exist on iOS. At least #2721 
@asemiankevich can you reproduce #2721 on Android?

**Comment by asemiankevich** [comment]
@rasom i can't reproduce  #2721 on Android in this branch

**Comment by rasom** [comment]
What about #2757 ? Can you reproduce it on both platforms?

**Comment by asemiankevich** [comment]
it is very difficult to check #2757 on iOS due to the issue i described above. However its not reproducible on Android

**Comment by asemiankevich** [comment]
i talked to @rasom and the following conclusion is made:
1. merge this PR as it fixes #2721 and #2757 
2. log separate issue for iPhone 5S for which was encountered very slow and irresponsive behavior . iPhone 7 and 6 (6S) look good.

**Pull request merged**
