### PR TITLE
Fix profile image in push notifications

### LINKED ISSUE #12331: User profile picture is not shown in PNs
# Bug Report

## Problem 
As a user,  I want to see user picture of my contacts in push notifications.
Currently default icon is shown even if user profile picture is displayed in app.

#### Expected behavior
PN with user profile picture

#### Actual behavior
PN with default user profile icon

### Reproduction

1) User A: open status, add User B to contacts
2) User B: set profile picture
3) User B: send message to User A

### Additional Information

- Status version: 1.15
- Operating System: Android (no preview for messages on IOS at all)

### PR DESCRIPTION
**Pull request by briansztamfater**
fixes #12331 

### Summary

This PR aims to fix user profile picture is not shown in Push Notifications

#### Platforms

- Android

##### Functional

- 1-1 chats

### Steps to test

- Open Status
- User A: open status, add User B to contacts
- User B: set profile picture
- User B: send message to User A
- Verify if profile image is displaying in PN

status: ready

### CODE REVIEW

**Review by rasom — APPROVED** [review]

**Comment by qoqobolo** [comment]
@briansztamfater thanks for PR!

### ISSUE 1: Settings `Show profile pictures of` are not applied to profile pictures in PNs

Profile picture in PN is displayed for receiver even if the `Show profile pictures` setting is set to `Contacts / None`.

**_Reproduction:_**
UserA (Android):
1. Enable PNs
2. Join a public chat (This behavior is reproducible for PNs from any chat)
3. Send a message
4. Put the app in the background

UserB:
1. Join the same public chat
2. Mention UserA

UserA:
1. Check PN

**Expected result:**
No profile image in PN from non-contact / anyone if the `Show profile pictures` setting is set to `Contacts / None`
**Actual result:**
User can see profile images in PN with any settings

### ISSUE 2/Q: Could we have a rounded profile image in PNs?

Screenshot 2021-09-16 at 14 39 15

---
Also, it would be nice to check profile images in PNs after merging [push notification on group chat invite](https://github.com/status-im/status-react/pull/12440). So could you rebase the current PR after merging the other one, please?

**Comment by briansztamfater** [comment]
@qoqobolo I wasn't aware of that setting actually, I'll fix it asap.

Regarding the squared image, it is weird, in my emulator it is shown as a circle. Which device are you using?

**Comment by qoqobolo** [comment]
@briansztamfater 
> Regarding the squared image, it is weird, in my emulator it is shown as a circle. Which device are you using?

Hmm, I'm testing on Google Pixel 2 and Huawei P40 Light (real devices). On both, the image is squared.

**Comment by briansztamfater** [comment]
> @briansztamfater
> 
> > Regarding the squared image, it is weird, in my emulator it is shown as a circle. Which device are you using?
> 
> Hmm, I'm testing on Google Pixel 2 and Huawei P40 Light (real devices). On both, the image is squared.

Ok, I'll do some further testing for this then. Thanks!

**Comment by briansztamfater** [comment]
@qoqobolo did the changes to consider the privacy settings for the profile picture. Also images in notifications should appear circled. Let me know if something arises during testing.

**Comment by qoqobolo** [comment]
@briansztamfater can you please rebase it?
Thanks

**Comment by briansztamfater** [comment]
> @briansztamfater can you please rebase it? Thanks

Sure, rebase done @qoqobolo

**Comment by qoqobolo** [comment]
Thanks, @briansztamfater!
Is it expected that there is no profile image in PN on the group invite?
I believe we could add profile images to this type of PNs ass well, because 3-random name of admin is displayed there. WDYT?
Screenshot 2021-10-01 at 16 15 20

**Comment by briansztamfater** [comment]
@qoqobolo I agree, that would be a nice addition. Updated PR with that change :)

**Comment by qoqobolo** [comment]
@briansztamfater PNs on group chat invites are not received in the latest build (`0affff5`) 👀

**Comment by briansztamfater** [comment]
> @briansztamfater PNs on group chat invites are not received in the latest build (`0affff5`) 👀

@qoqobolo Hmm interesting, worked on my local build but didn't work on the PR apk. I'll dive into the problem and come back to you with previous deep testing. Sorry about that!

**Comment by briansztamfater** [comment]
@qoqobolo diving deeper into notifications UX, it seems that default behavior is to show icons on the right side since Android Lollipop, unless it is a conversation. As this is just an invite to a group and not an initiated chat / conversation, maybe it is ok to show it on the right side.

What do you think?

Captura de Pantalla 2021-10-01 a la(s) 19 40 57



Captura de Pantalla 2021-10-01 a la(s) 19 40 32
 
(Also, if you are OK with that, PR is ready to test)

**Comment by churik** [comment]
@briansztamfater 
It doesn't seem so important to me, as I don't think it is too often the situation when you have several PNs to notice the difference.
However, we can fix it later.
@hesterbruikman better to know your opinion about that.

**Comment by hesterbruikman** [comment]
@briansztamfater to make sure I understand the issue:
- Is the notification only treated differently when it's a group chat invite?
- Do I understand correctly that because the notification is treated differently it can be shown with either no profile image or profile image on the right?
- What happens when a user receives 2 group chat invites from different people at the same time? This makes me think that it's probably better to leave profile image out of group chat invites altogether

Agree with @churik that in any case this would be an uncommon scenario. I do want to understand the issue a bit better though; The scenario might be more common on first time use. You join a community and get invited to a bunch of group chats by members

**Comment by briansztamfater** [comment]
> @briansztamfater to make sure I understand the issue:
> 
> * Is the notification only treated differently when it's a group chat invite?
> * Do I understand correctly that because the notification is treated differently it can be shown with either no profile image or profile image on the right?
> * What happens when a user receives 2 group chat invites from different people at the same time? This makes me think that it's probably better to leave profile image out of group chat invites altogether
> 
> Agree with @churik that in any case this would be an uncommon scenario. I do want to understand the issue a bit better though; The scenario might be more common on first time use. You join a community and get invited to a bunch of group chats by members

@hesterbruikman thanks for your time, really appreciate your questions.

* Exactly, but in reality, the conversation notifications are those treated differently, as the default behavior is to have the icon on the right since Android Lollipop.
* Correct, we can show the notification with no profile image on the right, or with no profile image at all (that's how it is currently working in `develop` branch)
* In that case user should receive two different notifications with different profile pictures at the right (if we decide to show them)

**Comment by qoqobolo** [comment]
@briansztamfater 

### ISSUE 3: In the latest build `d2f80b7` group invites from contacts are sent to the Activity center

**Steps:**
1. UserA and UserB add to contacts each other
2. UserA creates a group chat with UserB

**Expected result:** the group chat to which the user was invited by his contact is displayed on the home screen
**Actual result:** the group chat is displayed in the Activity center

**Comment by briansztamfater** [comment]
@qoqobolo seems I also need to rebase status-go part due to some contacts logic modification, on it right now

**Comment by briansztamfater** [comment]
@qoqobolo Done. Profile image is still showing on group invite notifications, so I'll stay tuned on whether we should remove it or not

**Comment by qoqobolo** [comment]
@briansztamfater let's keep it as it is, with the profile image on the right, it looks good!
Also, tested the case with 2 group chat invites from different users and can confirm that in that case user receives two different notifications with different profile pictures at the right.

Everything works fine now, thanks for the great work!
PR can be merged.

**Pull request merged**
