### PR TITLE
Fix url parsing perf problem

### PR DESCRIPTION
**Pull request by janherich**
[comment]: # (Please replace ... with your information. Remove < and >)
[comment]: # (To auto-close issue on merge, please insert the related issue number after # i.e fixes #566)

Improves performance of chat messages rendering.

### Summary:

[comment]: # (Summarise the problem and how the pull request solves it)

We have this naive implementation (naive is even written in code comment) where we parse content of the chat message to inject url-linking behaviour.
Naive because it’s done with notoriously slow regular expressions matching - 
https://github.com/status-im/status-react/blob/develop/src/status_im/chat/views/message/message.cljs#L154-L171
Problem is, this function is run *every* time when new message is received for *all messages* in chat, with 100 messages in chat, it’s 42ms only to run the fn, with 300 messages ~120ms and so on it grows linearly.
Those number are for fast iOS simulator, likely slower for real device (maybe not for iOS with prod build, for older androids for sure).
This PR just utilises memoization for the win. 

### Testing notes (optional):
Compare the performance of develop vs this branch in following situations (especially on android)
* Sending a new message in chat with lot of (200+) messages
* Receiving new message in chat with lot of (200+) messages

Additionally, make sure that url links in text messages are still correctly translated into clickable action as before. 

status: ready

### CODE REVIEW

**Review by jeluard — APPROVED** [review]

**Review by oskarth — APPROVED** [review]
Clean!

**Review by flexsurfer — APPROVED** [review]

**Review by yenda — APPROVED** [review]

**Comment by asemiankevich** [comment]
@janherich would you mind to look into the crash? I received this right after i send 136 message on iOS to Android in 1x1 chat

`Crashing Thread (Thread 27)
All Threads
0   libobjc.A.dylib                     0x181c341a0 objc_retain (in libobjc.A.dylib) + 16
1   UIKit                               0x18c1dd3cc _UIRenderingWillCaptureCompleteLayerTree (in UIKit) + 104
2   UIKit                               0x18c1dd424 _UIRenderingWillCaptureCompleteLayerTree (in UIKit) + 192
3   UIKit                               0x18c1dd424 _UIRenderingWillCaptureCompleteLayerTree (in UIKit) + 192
4   UIKit                               0x18c1dd424 _UIRenderingWillCaptureCompleteLayerTree (in UIKit) + 192
5   UIKit                               0x18c1dd424 _UIRenderingWillCaptureCompleteLayerTree (in UIKit) + 192
6   UIKit                               0x18c1dd424 _UIRenderingWillCaptureCompleteLayerTree (in UIKit) + 192
7   UIKit                               0x18c1dd424 _UIRenderingWillCaptureCompleteLayerTree (in UIKit) + 192
8   UIKit                               0x18c1dd424 _UIRenderingWillCaptureCompleteLayerTree (in UIKit) + 192
9   UIKit                               0x18c1dd424 _UIRenderingWillCaptureCompleteLayerTree (in UIKit) + 192
10  UIKit                               0x18c1dd424 _UIRenderingWillCaptureCompleteLayerTree (in UIKit) + 192
11  UIKit                               0x18c1dd424 _UIRenderingWillCaptureCompleteLayerTree (in UIKit) + 192
12  UIKit                               0x18c1dd424 _UIRenderingWillCaptureCompleteLayerTree (in UIKit) + 192
13  UIKit                               0x18c1dd424 _UIRenderingWillCaptureCompleteLayerTree (in UIKit) + 192
14  UIKit                               0x18c261080 -[UIView _drawViewHierarchyInRect:] (in UIKit) + 332
15  UIKit                               0x18c6463a4 ___UIDrawViewRectAfterCommit_block_invoke_2 (in UIKit) + 40
16  UIKit                               0x18c645de4 _UIDrawViewRectAfterCommit (in UIKit) + 584
17  StatusIm                            0x101aa8e48 0x100cd4000 + 14503496
18  StatusIm                            0x101aa8b44 0x100cd4000 + 14502724
19  libdispatch.dylib                   0x18234ea54 _dispatch_call_block_and_release (in libdispatch.dylib) + 24
20  libdispatch.dylib                   0x18234ea14 _dispatch_client_callout (in libdispatch.dylib) + 16
21  libdispatch.dylib                   0x18235bea4 _dispatch_root_queue_drain (in libdispatch.dylib) + 1032
22  libdispatch.dylib                   0x18235ba38 _dispatch_worker_thread3 (in libdispatch.dylib) + 120
23  libsystem_pthread.dylib             0x1825f706c _pthread_wqthread (in libsystem_pthread.dylib) + 1268
24  libsystem_pthread.dylib             0x1825f6b6c start_wqthread (in libsystem_pthread.dylib) + 4`

not sure if this related to this PR or not? https://app.testfairy.com/projects/4803590-status/builds/7812322/sessions/5/?accessToken=julY4Zf2/dGk/OJFpBGglp-7m1Q

I will look into develop build meanwhile. UPD : dont see it in latest nightly build

**Comment by janherich** [comment]
@asemiankevich already rebased on newest develop:
Branch: PR-3486
Android: https://i.diawi.com/NQausB
iOS: https://i.diawi.com/HWUzkc

**Comment by asemiankevich** [comment]
@janherich any reason we have this `messages connection problem` right after i create account?  Develop (nightly) looks fine
image

**Comment by asemiankevich** [comment]
`java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.getScheme()' on a null object reference
	at im.status.ethereum.MainActivity.onNewIntent(MainActivity.java:92)
	at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1228)
	at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1240)
	at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:2946)
	at android.app.ActivityThread.performNewIntents(ActivityThread.java:2958)
	at android.app.ActivityThread.handleNewIntent(ActivityThread.java:2967)
	at android.app.ActivityThread.-wrap15(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1648)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:156)
	at android.app.ActivityThread.main(ActivityThread.java:6577)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)`

1. Having android app running on background sent +200 messages from ios
2. Tap status app on Android in order to resume it from the background and see the messages
image

https://app.testfairy.com/projects/4803622-status/builds/7879719/sessions/5/?accessToken=yFBjN2Qn3CSNxbp9M2fSJBkXkxg

One more observation: having more than 250 messages in 1x1 chat makes the android UI very slow so I need to wait for several seconds to have the `send` button become available . Sometimes it is not possible to send messages at all as send button rendering is stuck. Please check out the following TF session https://app.testfairy.com/projects/4803622-status/builds/7879719/sessions/7/?accessToken=PKXMvplPR4WRtnhn9-hjxrHUt7o from 0:30

**Comment by jeluard** [comment]
@asemiankevich Do I understand correctly that we have this exception in develop too?

**Comment by asemiankevich** [comment]
@jeluard yes, when resuming the app from background

**Comment by jeluard** [comment]
@asemiankevich So not related to this PR?

**Comment by asemiankevich** [comment]
yeah i think so!

**Comment by rasom** [comment]
@janherich could you please resolve conflicts?

**Comment by janherich** [comment]
The same change is already implemented in `new-protocol` work, which was recently merged in, therefore closing the PR

**Pull request closed without merging**
