### PR TITLE
Fix the "Choose profile" button in the profile #19551

### LINKED ISSUE #19551: Fix the "Choose profile" button in the profile
# Bug Report

## Problem 
[comment]: # (A problem description)

The "Choose profile" button in the profile header (settings) shows the "sign in by syncing" screen,which doesn't work when already logged in and is inconsistent with the login screen. If the feature is already implemented (check with @Parveshdhull), connect it to the button, otherwise remove the button.

### PR DESCRIPTION
**Pull request by flexsurfer**
fixes #19551

### CODE REVIEW

**Review by clauxx — APPROVED** [review]

**Review by seanstrom — APPROVED** [review]
Does this mean we don't have something for account switching while authenticated inside the app?

**Comment by flexsurfer** [comment]
> Does this mean we don't have something for account switching while authenticated inside the app?

cc @clauxx

**Comment by clauxx** [comment]
> Does this mean we don't have something for account switching while authenticated inside the app?

@Parveshdhull do you know about this?

**Review by Parveshdhull — APPROVED** [review]

**Comment by Parveshdhull** [comment]
> > Does this mean we don't have something for account switching while authenticated inside the app?
> 
> @Parveshdhull do you know about this?

Hi @clauxx, I think we don't have this feature yet.
I guess we can call log-out and login in client, but I think we should properly implement this in status-go.

**Comment by clauxx** [comment]
> > > Does this mean we don't have something for account switching while authenticated inside the app?
> > 
> > 
> > @Parveshdhull do you know about this?
> 
> Hi @clauxx, I think we don't have this feature yet. I guess we can call log-out and login in client, but I think we should properly implement this in status-go.

Thanks! It's best we just hide the button then :+1:

**Comment by churik** [comment]
Hello!
The e2e results are reviewed, the failed tests are not related to the PR.
PR can proceed to the next stage.

**Pull request merged**
