### PR TITLE
Implementation of switcher cards

### PR DESCRIPTION
**Pull request by Parveshdhull**
### Review Notes:
This PR depends on https://github.com/status-im/status-mobile/pull/14006, but for the purpose of review, those changes are currently reverted.
If you want to try the app please install [#6 build](https://github.com/status-im/status-mobile/pull/13854#issuecomment-1226595030) (commit hash fada028)

status: ready

### CODE REVIEW

**Comment by du82** [comment]
Now it errors

Screenshot_2022-09-18-17-51-59-58_65ad86f86fd2321a85272a99323da10f

**Comment by Parveshdhull** [comment]
### Review Notes:
This PR depends on https://github.com/status-im/status-mobile/pull/14006, but for the purpose of review, those changes are currently reverted.
If you want to try the app please install [#6 build](https://github.com/status-im/status-mobile/pull/13854#issuecomment-1226595030) (commit hash fada028)

cc: @du64

**Comment by du82** [comment]
The wallet cards, browser card, and communities discover don't show anything

**Comment by Parveshdhull** [comment]
> The wallet cards, browser card, and communities discover don't show anything

yes, they are currently not implemented. I will work on them later.

**Comment by Parveshdhull** [comment]
we are currently focusing on redesign of messaging and communities first and will work on wallets and browser after that.

**Comment by du82** [comment]
just out of curiosity, where can I find the current figma designs that you all are currently using?

btw I didn't see any problems with the PR :)

**Review by flexsurfer — APPROVED** [review]

**Comment by Parveshdhull** [comment]
> btw I didn't see any problems with the PR :)

Awesome, thank you for testing.

> just out of curiosity, where can I find the current figma designs that you all are currently using?

Redesign Issues also have their corresponding figma files in description.

[Components](https://github.com/status-im/status-mobile/issues?q=is%3Aissue+is%3Aopen+label%3AE%3AMobileComponents), [Shell](https://github.com/status-im/status-mobile/issues?q=is%3Aissue+is%3Aopen+label%3Ae%3AMobileShellRD) , [Messaging](https://github.com/status-im/status-mobile/issues?q=is%3Aopen+is%3Aissue+label%3AE%3AMobileMessagingRD), etc.

**Pull request merged**
