### PR TITLE
Bug/User is not redirected to previous screen after scanning wallet QR code. [#3414]

### LINKED ISSUE #3414: User is not redirected to previous screen after scanning wallet QR code. Transaction details are lost
### Description
*Type*: Bug

*Summary*: When user scans QR code of a wallet address she is being redirected to main Wallet screen. This results in transaction details being lost. Instead, user should be redirected to Send Transaction screen to finish the transaction. 
Issue does not occur when address is typed or recipient is selected from a list.

Note: issue happens only on iOS.

#### Expected behavior
After scanning address QR code user is redirected to Send Transaction screen to finish the transaction. 

#### Actual behavior
After scanning address QR code user is redirected to main Wallet screen.

### Reproduction
- Open Status
- Go to Wallet, then Send transaction
- Choose recipient by scanning correct QR code of a wallet address

### Additional Information
* Status version: nightly, Feb 22
* Operating System: iOS, 11.2.1
* Device: iPhone 6

### PR DESCRIPTION
**Pull request by flexsurfer**
fixes #3414

### CODE REVIEW

**Review by jeluard — APPROVED** [review]

**Review by goranjovic — APPROVED** [review]

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/oLGXgu for branch PR-4454

<blockquote><div><strong><a href="https://i.diawi.com/oLGXgu">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/pGJetT for branch PR-4454

<blockquote><div><strong><a href="https://i.diawi.com/pGJetT">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by asemiankevich** [comment]
image

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/eyYkPY for branch PR-4454

<blockquote><div><strong><a href="https://i.diawi.com/eyYkPY">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/HD1hu7 for branch PR-4454

<blockquote><div><strong><a href="https://i.diawi.com/HD1hu7">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/7cCs4J for branch PR-4454

<blockquote><div><strong><a href="https://i.diawi.com/7cCs4J">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/WdFicm for branch PR-4454

<blockquote><div><strong><a href="https://i.diawi.com/WdFicm">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by flexsurfer** [comment]
@asemiankevich rebased, next build should be fine

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/rrHcHY for branch PR-4454

<blockquote><div><strong><a href="https://i.diawi.com/rrHcHY">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/o7ZjSL for branch PR-4454

<blockquote><div><strong><a href="https://i.diawi.com/o7ZjSL">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/axX2mq for branch PR-4454

<blockquote><div><strong><a href="https://i.diawi.com/axX2mq">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/RHdwCN for branch PR-4454

<blockquote><div><strong><a href="https://i.diawi.com/RHdwCN">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Pull request merged**
