### PR TITLE
Update status-go and set fleet to status.prod

### PR DESCRIPTION
**Pull request by cammellos**
Update to latest version of status-go, and set default fleet to status.prod/test

### CODE REVIEW

**Review by rasom — APPROVED** [review]

**Review by Parveshdhull — APPROVED** [review]

**Review by jakubgs — APPROVED** [review]
Wow.

**Review by flexsurfer — APPROVED** [review]

**Comment by churik** [comment]
e2e failed due to the following issue:
### ISSUE 1: The profile picture is not updated when the user is added as a contact

**Steps:**
1) User1: create multiaccount , set profile image
2) User1: add User2 as contact
3) User2: accept contact request

**Expected result:**
User2 can see profile image of User2

**Actual result:**
User2 can't see new profile photo until re-login

**OS:** IOS, Android

**Comment by cammellos** [comment]
@churik thank you, looking into it

**Review by J-Son89 — APPROVED** [review]

**Review by briansztamfater — APPROVED** [review]

**Comment by cammellos** [comment]
Interesting, it consistently fails using wakuv2 fleet, investigating and trying to replicate in status-go directly

**Comment by churik** [comment]
the reason is different now; let me check

**Comment by churik** [comment]
The reason for failure in the 2 last cases is that no new unread indicator is shown, so seems the contact request was not delivered (the test is waiting for 40 sec).
https://github.com/status-im/status-mobile/issues/14466 may be the reason

UPD: seems that messages are working a way slower than on `eth.prod`, let me add more time

**Comment by churik** [comment]
@cammellos not sure what to do now; normally we were waiting for messages for 10-20 sec and it was enough.
Currently, due to https://github.com/status-im/status-mobile/issues/14466 some messages just couldn't go through. That is the reason for the failure here: https://github.com/status-im/status-mobile/pull/14476#issuecomment-1337468392 

Should we enable the fleet to highlight the issue or is the best to take a look at it first?

**Comment by cammellos** [comment]
> @cammellos not sure what to do now; normally we were waiting for messages for 10-20 sec and it was enough. Currently, due to #14466 some messages just couldn't go through. That is the reason for the failure here: [#14476 (comment)](https://github.com/status-im/status-mobile/pull/14476#issuecomment-1337468392)
> 
> Should we enable the fleet to highlight the issue or is the best to take a look at it first?

I'll take a look at it first, it's a small change, but we want e2e to pass at least

**Comment by flexsurfer** [comment]
hey @cammellos @churik whats the state of this PR, still relevant ?

**Comment by churik** [comment]
I believe this one can be closed

**Pull request closed without merging**
