### PR TITLE
Any link to status.app opens in status even if it's not supported #20420

### LINKED ISSUE #20420: Any link to `status.app` opens in status even if it's not supported
On android, we are not filtering by path the intent, so anything that goes to `status.app` will be intercepted, which means that users can't open these links in the browser, and in status they end up in a loop:

```
                <data android:scheme="http" android:host="status.app" />
```
It should look 
```
<data android:scheme="http" android:host="status.app" android:pathPrefix="..."/>
```
For example. https://developer.android.com/guide/topics/manifest/data-element .

On IOS they are setup correctly and can be used as a reference:

https://github.com/status-im/status-website/blob/main/public/.well-known/apple-app-site-association#L15-L53

### PR DESCRIPTION
**Pull request by flexsurfer**
fixes #20420

### CODE REVIEW

**Review by jo-mut — APPROVED** [review]

**Review by Parveshdhull — APPROVED** [review]

**Comment by churik** [comment]
@cammellos I'm unable to test it in PR, as it doesn't redirect to `status.app` without a browser.
So if you're sure about the fix, we can cherry-pick it and I'll be able to test in in release app.

**Comment by churik** [comment]
OK, when testing this PR I found one more issue: the links that do not have a preview handled, have an empty preview:
IMAGE 2024-06-11 11:25:28

can we fix it here as well? 

To reproduce:
- send link to user profile with preview on desktop (i.e. link to channel or link to user profile) 
- check it on mobile

(It's not a PR bug, it is a release 2.29 bug)

**Comment by flexsurfer** [comment]
@churik looks like a completely different issue, I wouldn't mix them, if it's also a blocker I could take a look, but in another issue, thanks

**Comment by churik** [comment]
OK, I built nightly build from it, and fix is working, ready to be merged, thank you @flexsurfer

**Pull request merged**
