### PR TITLE
Update ne.cljs

### PR DESCRIPTION
**Pull request by yalu**
noticed some typos after previous pull request was pulled.

Made a semantical correction for "left" which at first was interpreted as having to do with direction, where actually it was about "leaving".

Made a grammatical correction relating to singular plural usage.

Made comment consistent.

### CODE REVIEW

**Comment by flexsurfer** [comment]
hi @yalu , thank you, could you please rebase your branch onto feature/translations

**Comment by yalu** [comment]
In all eagerness and some ignorance I apologise if I have polluted commit history. 😅

**Comment by flexsurfer** [comment]
you can just create new branch and cherry-pick your commit, because this still has conflicts

**Comment by yalu** [comment]
I synced my fork to latest upstream and resolved the conflict.

if this is still conflicting, I'll close and try sending another PR.

**Comment by flexsurfer** [comment]
yes, you still have 54 commits in your branch, you need to create a new branch or remove all commits besides yours during interactive rebasing

**Comment by yalu** [comment]
got it. cleaner PR coming up.

**Pull request closed without merging**
