### PR TITLE
Toolbar with dark content (#344), React Native 0.36 support

### PR DESCRIPTION
**Pull request by alwx**
fix https://github.com/status-im/status-react/issues/344

But it is probably not the best idea to merge it now 'cause RC version of React Native may be unstable. 
Waiting for 0.36.0.

### CODE REVIEW

**Comment by rasom** [comment]
https://github.com/facebook/react-native/releases/tag/v0.36.0

**Comment by alwx** [comment]
Finished

**Comment by rasom** [comment]
There are no messages in console chat:

cons

**Comment by alwx** [comment]
Checked it yesterday, and everything was fine.

If you take a look at the changes, you will easily notice that there are no changes that can broke this functionality. Please, remove `node_modules` directory and perform `npm i` before running.

**Comment by rasom** [comment]
I did this 3-4 times.

**Comment by rasom** [comment]
Just did it again, the problem is still there.

**Comment by rasom** [comment]
I just ran `develop` branch with the same npm deps and can reproduce the problem. Seems it is related to `react-native@0.36.0`

**Comment by jarradh** [comment]
*points to shrinkwrap*

**Comment by alwx** [comment]
removed my node_modules, did `npm i` and reproduced it.

seems like this release of React Native fixes one problem, but creates another 😭 
usual thing

diving deeper into React Native changelog

**Comment by jarradh** [comment]
[*points harder*](https://github.com/status-im/status-react/blob/bug/release-build/npm-shrinkwrap.json#L793) we can't do this why?

**Comment by rasom** [comment]
We will do this, but we have to figure what is wrong there before `shrinkwrap`

**Comment by jarradh** [comment]
oh sorry I totally forgot this is a new feature that depends on RN 0.36

**Comment by alwx** [comment]
React Native 0.36.0 introduced several breaking changes (like this: https://github.com/facebook/react-native/commit/0a9b6bedb312eba22c5bc11498b1cc41363e5f27).

The first thing that is broken and doesn't work anymore is our fancy message appearance animation (it is one of the reasons why chat was broken). I am not sure that the way this animation worked before is a good way of working with animations in general (cause we were changing message height instead of changing its offset, which is more time and energy-consuming), but in order to make our app work with React Native I've replaced those animations with the ones that change offset.
The second thing which was broken is the suggestions view. I don't know the exact reason of it (most probably it's because we were using ListView inside a ScrollView), but now it is also fixed.

@rasom you can verify it now.

**Pull request merged**
