### PR TITLE
Feature/desktop update shadow

### PR DESCRIPTION
**Pull request by vitvly**
1. Have a working Qt installation. Download Qt online installer (latest version 5.14.2 seems to work fine). Then in your shell:
```
export QT_PATH=/Users/vvlasov/Qt/5.14.2
export PATH=$QT_PATH/clang_64/bin:$PATH
```
2. As Nix is not yet updated, packages have to be installed manually. Inside status-react folder:
```
ln -sf desktop/js_files/package.json package.json
ln -sf desktop/js_files/yarn.lock yarn.lock
yarn
```
3. Setup qtkeychain:
fetch sources from `https://github.com/status-im/qtkeychain`
Export QTKEYCHAIN_SOURCES env var and set it to the directory where source files fetched
`export STATUS_GO_DESKTOP_LIBDIR=<qtkeychain_source_dir> `

4. Build status-go:
status-go can be built by executing `make status-go-desktop`. It will build status-go static lib (including headers) inside `/nix/store`. When build finished it will show in which folder status-go was built.
Set env vars to this directory (temporarily needed until Nix works and populates this for us):
```
export STATUS_GO_DESKTOP_LIBDIR=<nix_store_status_go build_dir>/lib 
export STATUS_GO_DESKTOP_INCLUDEDIR=<nix_store_status_go build_dir>/include
```
5. In 4 different shells:
```
1. `react-native start` # RN bundler
2. `yarn shadow-cljs watch desktop` # Compile CLJS
3. `node node_modules/react-native-desktop-qt/js-executor.js` # Run Node instance that will execute JS code
4. react-native run-desktop # Run QT app

### CODE REVIEW

**Comment by jakubgs** [comment]
It appears that `qtwebengine` that we pull into our custom Qt package:
https://github.com/status-im/status-react/blob/14e4710253ff9d7efbb2a1d409fbc78c26795a73/nix/pkgs/qt5custom/default.nix#L3-L11
Fails to compile on MacOS only with:
```
In file included from gen/base/base_jumbo_mm.mm:13:
In file included from ./../../3rdparty/chromium/base/mac/mac_util.mm:23:
../../3rdparty/chromium/base/mac/sdk_forward_declarations.h:34:3: error: redefinition of enumerator 'NSPressureBehaviorUnknown'
  NSPressureBehaviorUnknown = -1,
  ^
/nix/store/qx5zxs9kiiwx352l4p7wimsxhk9qng68-apple-framework-AppKit/Library/Frameworks/AppKit.framework/Headers/NSEvent.h:270:5: note: previous definition is here
    NSPressureBehaviorUnknown = -1,
```
https://gist.github.com/siphiuel/707d0c24bdb5ebb3e6d43d524b462bac

**Comment by jakubgs** [comment]
There are known issues with `qtwebengine` on MacOS in `nixpkgs`: https://github.com/NixOS/nixpkgs/issues/76715
But it doesn't look like the error we are getting:
```
/nix/store/4p3bds5cknzwg72np1rzyn3jq0962z84-bash-4.4-p23/bin/bash:
  ../../../../../../../nix/store/1ngwf6wvh9hf1vz3h2h5znqi90fa86q1-clang-wrapper-7.1.0/bin/clang++:
    No such file or directory
```

**Comment by ghost** [comment]
`desktop/js_files/yarn.lock` changed. Pinging @jakubgs and @corpetty

**Comment by jakubgs** [comment]
Is this dead?

**Comment by vitvly** [comment]
Superseded by https://github.com/status-im/nim-status-client

**Pull request closed without merging**
