### PR TITLE
Mitigate long time to login on accounts with many community chats

### PR DESCRIPTION
**Pull request by ilmotta**
Mitigates https://github.com/status-im/status-mobile/issues/20059

### Summary

This PR mitigates the long time to login on mobile devices for users with many chats. On Galaxy A71, with a user in the Status community, login goes down from 17s to 10s (still far from great). For a nice explanation, please refer to the status-go PR https://github.com/status-im/status-go/pull/5218 and to https://github.com/status-im/status-mobile/issues/20059#issuecomment-2126928008

#### Platforms

- Android
- iOS

#### Areas that may be impacted

I don't foresee any regression, but login in general can be affected.

### Steps to test

The fix should make the entire login flow take 60% of the usual time with a user account that has a large number of community chats, such as a user in the `Status` community. Other parts of the login code can also cause slowdown (like the number of contacts, other types of chats), but so far it seems that community chats dominate the hot path.

The better solution that can fully eliminate any delays during login will only come as a separate PR in status-go because we are not sure about the consequences of delaying chat setup until *after* login. We might uncover a few surprises. I'll inform the QA team as soon as I cook that PR :) For the time being, this PR seems to be a step forward.

status: ready

### CODE REVIEW

**Review by qfrank — APPROVED** [review]

**Review by jo-mut — APPROVED** [review]

**Comment by churik** [comment]
For me 17 sec in nightly / 10 sec in PR,
For @pavloburykh 12 sec / 7 sec.
Tried force login / bimetric auth just in case.

It is definitely an improvement, thank you @ilmotta !!!

**Comment by ilmotta** [comment]
Ah great news @churik! I'll update the status-go PR to remove all the log calls I added and rebase this mobile PR. Do you consider this PR already `tested-ok` or do you want to retest after I rebase?

Edit: status-go PR updated and mobile PR rebased. Just waiting for confirmation that the PR is `tested-ok` to merge.

**Comment by pavloburykh** [comment]
> Just waiting for confirmation that the PR is `tested-ok` to merge.

Hey @ilmotta! Let me re-run e2e to make sure rebased go branch does not bring any regression. 
Also, I see integration tests have failed https://ci.status.im/job/status-mobile/job/prs/job/tests/job/PR-20164/2/consoleText Could you please take a look? Thank you!

**Comment by pavloburykh** [comment]
> > Just waiting for confirmation that the PR is `tested-ok` to merge.
> 
> Hey @ilmotta! Let me re-run e2e to make sure rebased go branch does not bring any regression. Also, I see integration tests have failed https://ci.status.im/job/status-mobile/job/prs/job/tests/job/PR-20164/2/consoleText Could you please take a look? Thank you!

@ilmotta E2E are okay. Anyway, I see PR has already been merged. Thank you for your work.

**Pull request merged**
