### PR TITLE
Fix and uncomment tests in contacts.events and utils.pre-receiver

### LINKED ISSUE #2935: Uncomment and fix failing tests
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a developer, I want tests to work so that I can verify modules work as expected.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature/Tests

*Summary*: Uncomment https://github.com/status-im/status-react/blob/develop/test/cljs/status_im/test/runner.cljs tests, fix them and make sure it runs.

 ;;'status-im.test.contacts.events
 ;;'status-im.test.utils.pre-receiver

#### Expected behavior
Tests enabled and run.

#### Actual behavior
Not enabled.

### PR DESCRIPTION
**Pull request by cammellos**
Fixes #2935 

### Summary:

There were a few namespaces in the test suite that were commented out. 

This PR fixes the commented out tests and adds them to the runner.

`contacts.events` was mainly an issue with schema validation
and a few features not covered by tests.

the tests in `pre-receiver `were actually passing, the issue was a
test suite in `wallet.events` which was run asynchronously by re-frame (it was outside `run-test-sync`) which meant the http request in the fx was actually being fired.

status: ready

Thanks for the project!

### CODE REVIEW

**Comment by janherich** [comment]
Thanks for the contribution @cammellos , this is really helpful, fragile tests have been bugging us for quite some time !

**Comment by oskarth** [comment]
Thanks for the PR @cammellos! 

> the tests in pre-receiverwere actually passing, the issue was a
test suite in wallet.events which was run asynchronously by re-frame (it was outside run-test-sync) which meant the http request in the fx was actually being fired.

Ah this makes sense, I didn't understand why it would be failing in pre-receiver and commented out as quickfix. Nice find :)

**Review by oskarth — APPROVED** [review]

**Review by janherich — APPROVED** [review]

**Comment by oskarth** [comment]
CI passing, merging.

**Comment by andytudhope** [comment]
Hey @cammellos - please will you log into openbounty.status.im, go the 'Payment Details' tab and make sure to click the `Update` button once you have put in an adress you control (i.e. not one on an exchange). I can then confirm this bounty for you 😉

**Comment by cammellos** [comment]
@andytudhope 
done!
sorry for the delay

thanks

**Pull request merged**
