### PR TITLE
Feature/show 'opt-in' screen to recovery

### LINKED ISSUE #3632: Add 'opt-in' screen to recovery flow
Newly created accounts have an option to opt-in to helping Status by sharing some anonymous usage metrics. However, this is missing for recovered accounts. 

Since we have no way of knowing the users original opt-in settings we should ask the user again if they would like to share.

Testing: @lukaszfryc

### PR DESCRIPTION
**Pull request by flexsurfer**
fixes #3632

yeah i know it's not a good solution, but it will work fine in this case

### CODE REVIEW

**Comment by jeluard** [comment]
Can you add a comment describing this workaround and eventually how we should do it better?

**Review by jeluard — APPROVED** [review]

**Comment by flexsurfer** [comment]
it's not workaround :) it's not good to use timers because race conditions, but here it will work fine ,we can use it here

**Comment by jeluard** [comment]
Ok well then a comment detailing why it's not good but here it's ok :D To make sure we can hypothetically address this one day ;)

**Comment by asemiankevich** [comment]
@flexsurfer Restoring account is treated as ` account created ` by Mixpanel

image


https://mixpanel.com/report/1541909/live/#chosen_columns:!('$browser','$city',mp_country_code,distinct_id,'$referring_domain'),column_widths:!(200,100,223,153,96,366,182),query:(distinct_ids:!(),is_or_query:!f,on:'(%2225b7e2df%22%20in%20properties%5B%22app-version%22%5D)%20and%20(defined%20(properties%5B%22app-version%22%5D))',property_selectors:!((defaults:(filter_state:(),human_readable_params:!(),query:''),distinct_id_operator:and,distinct_ids:!(),human_readable_params:!((type:property,val:app-version),(type:operator,val:contains),(type:operand,val:'25b7e2df')),query:'(%2225b7e2df%22%20in%20properties%5B%22app-version%22%5D)%20and%20(defined%20(properties%5B%22app-version%22%5D))',valid_segfilter:(filters:!((filter:(operand:'25b7e2df',operator:in),property:app-version,selected_property_type:string,type:string)),op:and)))),resized_columns:!(!f,!f,!f,!f,!t,!t,!t)

we should use  {:label     "Account restored"
  :trigger   [:account-recovered]} i guess https://github.com/status-im/status-react/blob/83b5312a05e1d5bd4e1ed8716a013828b3d765c1/src/status_im/utils/mixpanel_events.edn

<blockquote><div><strong><a href="https://mixpanel.com/report/1541909/live/#chosen_columns:!('$browser','$city',mp_country_code,distinct_id,'$referring_domain'),column_widths:!(200,100,223,153,96,366,182),query:(distinct_ids:!(),is_or_query:!f,on:'(%2225b7e2df%22%20in%20properties%5B%22app-version%22%5D)%20and%20(defined%20(properties%5B%22app-version%22%5D))',property_selectors:!((defaults:(filter_state:(),human_readable_params:!(),query:''),distinct_id_operator:and,distinct_ids:!(),human_readable_params:!((type:property,val:app-version),(type:operator,val:contains),(type:operand,val:'25b7e2df')),query:'(%2225b7e2df%22%20in%20properties%5B%22app-version%22%5D)%20and%20(defined%20(properties%5B%22app-version%22%5D))',valid_segfilter:(filters:!((filter:(operand:'25b7e2df',operator:in),property:app-version,selected_property_type:string,type:string)),op:and)))),resized_columns:!(!f,!f,!f,!f,!t,!t,!t)">Mixpanel | Product AnalyticsLogin - Mixpanel | Product Analytics</a></strong></div><div>Learn how people use your app with the world's most advanced mobile & web analytics. Try it for free.</div></blockquote>
<blockquote><div> GitHub</div><div><strong><a href="https://github.com/status-im/status-react">status-im/status-react</a></strong></div><div>status-react - a free (libre) open source, mobile OS for Ethereum</div></blockquote>

**Comment by flexsurfer** [comment]
yeah maybe @asemiankevich , but not related to this PR, we need separate issue for this

**Comment by asemiankevich** [comment]
cool! Thanks Andrey!

**Pull request merged**
