### PR TITLE
[fix] wallet on-error dispatch

### PR DESCRIPTION
**Pull request by yenda**
the code to dispatch an event on transaction error was not working
this fixes it

status: ready

### CODE REVIEW

**Review by flexsurfer — APPROVED** [review]

**Review by mandrigin — APPROVED** [review]

**Comment by annadanchenko** [comment]
@yenda 
1. Windows build failed
2. To prevent side effects on release 0.12.0 can this PR be merged after we do code freeze (eod Wednesday) please? It's "skip qa" so we will not catch any side effects

**Review by goranjovic — APPROVED** [review]

**Comment by yenda** [comment]
@annadanchenko windows build failure is just so infra error I'll restart it, regarding merge we can wait but it won't matter it is fixing something that was just not working but isn't used in the current app anyway

**Comment by annadanchenko** [comment]
@yenda can you provide some details on how you've tested it, please? we might need to include such test into automated test suite - would be cool to get details for this

**Comment by yenda** [comment]
@annadanchenko this is not something that can be tested as there is no code using it yet, and such code would have not worked as there was a bug that this PR fixes which is why this is skip-qa labelled.

**Pull request merged**
