### PR TITLE
fix_: use 24h batches to retrieve message history

### PR DESCRIPTION
**Pull request by richard-ramos**
Instead of retrieving 30d of messages, split the request in 24h batches. 
Requires: https://github.com/status-im/status-go/pull/6115

To test this:
Ensure that profiles restore from backup successfully, as well as curated communities, and message history older than 24h

### CODE REVIEW

**Comment by Horupa-Olena** [comment]
@richard-ramos Thanks for your PR!

Please resolve conflicts sp I can start testing.

**Comment by churik** [comment]
@richard-ramos
Could you clarify which timeframe is expected to be fetched in the community when someone joins?  
I was under the impression it has always been the last 24 hours—am I mistaken?

**Comment by richard-ramos** [comment]
>  Could you clarify which timeframe is expected to be fetched in the community when someone joins?

9d according to this setting: https://github.com/status-im/status-go/blob/develop/appdatabase/migrations/sql/1682073779_settings_table_remove_latest_derived_path_column.up.sql#L55  It will not load the 9d immediatly though as it will iterate over the result set day by day from most recent to earlier.

Also, perhaps this is a parameter we could change to reduce the load on the storenodes to maybe 3d instead? wdyt @fryorcraken? I imagine this should reduce the number of requests done to a storenode when joining a community to ~1/3 of the number of requests we do now depending on how active a community is.

**Comment by churik** [comment]
@richard-ramos  

I'll comment one by one
**1) Backup**

For today stat the test was failed 3 times and passed 5 times (all that on staging fleet) and it seems unstable on both fleets - so sometimes it is restored, sometimes not.

image

What we should exactly ensure here and in what fleet? 

**2) Curated communities**
Meaning - they should fetch the same way they fetch on nightly (also barely working as it mentioned [here](https://github.com/status-im/status-mobile/issues/21158)) on `status.prod` fleet, right?

**3) Fetching history in communities**
> 9d according to this setting: https://github.com/status-im/status-go/blob/develop/appdatabase/migrations/sql/1682073779_settings_table_remove_latest_derived_path_column.up.sql#L55 It will not load the 9d immediately though as it will iterate over the result set day by day from most recent to earlier.

It has never been working on mobile, so frankly I do not really know how to test it.

When you join for example Status community from mobile, only 24h were fetched. And we do not have an option in nightly of to fetch more history, and usually even the one for 24h is very incomplete (as it can be seen from https://github.com/status-im/status-mobile/issues/21581) which is totally valid issue.

So basically what I can test now for sure that new communities that are created on `status.staging` are fetched.
Will really appreciate if you can clarify all the comments that I mentioned above, as it seems that reality in the app does not match expected behaviour, but we never get a requirements per se :)

**Comment by churik** [comment]
So we made a small investigation of how app behaves on PR and nightly builds (thanks @Horupa-Olena), the comparison spreadsheet is [here](https://docs.google.com/spreadsheets/d/1wm6Nndu-O3pY82uwejmGToyNPiWjFFWW2YceAA3VAUA/edit?gid=0#gid=0)


Based on the comparison table provided in the document, here are the conclusions regarding key differences between the **PR**  and **Nightly builds**:

### General Observations:
1. **Speed**: 
   - Joining the Status community was slightly faster in PR builds compared to nightly builds. Specifically, PR was 5 minutes faster on Android and 2 minutes faster on iOS.

2. **Message Syncing**:
   - **PR builds** tended to show more messages initially when joining the Status community or restoring accounts.
   - **Nightly builds** sometimes displayed fewer or no messages in specific channels.

3. **Data Loss**:
   - For restored accounts, data loss in **close and open test communities** varied significantly:
     - PR builds showed more consistent recovery of messages across all channels.
     - Nightly builds frequently lost messages or displayed empty channels, particularly in the **close test community**.

### Channel-Specific Differences:
- **Channels with Missing Messages**:
  - On Android and iOS, **Nightly builds** consistently showed fewer messages in several channels, including **general, feedback-mobile, general-banter**, and others.
  - PR builds recovered messages from more channels, such as **feedback-desktop, memes**, and **core-desktop**, with better completeness.

- **Close and Open Communities**:
  - In PR builds:
    - The **close community** generally retained or displayed most messages.
    - The **open community** sometimes showed empty channels but performed better than nightly builds.
  - In Nightly builds:
    - There was frequent loss of messages in both **close** and **open communities**, with many channels appearing empty.

### Additional Notes:
- **Message Display Across Platforms**:
  - Both builds showed discrepancies in syncing messages between the mobile app and Discord channels, but this issue was more pronounced in Nightly builds.
  
- **Channel Fetching Behavior**:
  - PR builds fetched messages from a broader range of channels (e.g., **web, memes, sports**) compared to Nightly builds.

### Conclusion:
- **PR builds** generally outperformed Nightly builds in terms of speed, message recovery, and channel syncing when joining or restoring the Status community. The Nightly builds showed significant issues with data completeness and channel syncing, particularly in test communities and less frequently used channels.

**But it all might be a coincidence**
All tests are performed on `status.prod` fleet.
For `staging` I'm re-running tests and continue investigation tomorrow.

**Comment by richard-ramos** [comment]
> Backup: ... What we should exactly ensure here and in what fleet?

That the backup feature still works. This should work on any fleet. 

> Curated communities:  they should fetch the same way they fetch on nightly (also barely working as it mentioned https://github.com/status-im/status-mobile/issues/21158) on status.prod fleet, right?

Yes

> Fetching history in communities: It has never been working on mobile, so frankly I do not really know how to test it.

Perhaps this is something that should be confirmed on the PR created for desktop? cc: @anastasiyaig 

Overall the behaviour should be the same, except that on the background the queries are splitted into 24h batches which should help reduce the load on the storenodes as well as improve the response times for the store queries, which seems to be the case, based on the comment before this! For the cases that sometimes work / sometimes doesn't, it seems to me that this is likely that some storenode is missing messages or maybe it wasn't even possible to publish the message containing the backup. 

I wonder what's the experience like with this PR on desktop?

Thank you, @churik

**Comment by anastasiyaig** [comment]
sadly i did not try yet , pretty loaded with tasks for 2.32 . i will be back to it, there is a desktop pr, which i am planning to try tomorrow @richard-ramos

**Comment by anastasiyaig** [comment]
some context for prod fleet: tests are passing here https://github.com/status-im/status-desktop/pull/16813 
we dont check history in tests but real time messages work.

i need to check staging and backup manually, will reply in desktop pr

**Comment by churik** [comment]
@richard-ramos 

I cannot really prove that this is actually PR issue, but worth checking

**ISSUE 1** sometimes messages are not fetched from history nodes in 1-1 chat when the sender is offline
Mobile-Mobile.

**Reproducibility:** 
- on nightly could not reproduce 3/3
- on Pr build: reproduced 3/5 (2 times messages were lost, and 1 more time part of the messages was lost)

**Prerequisites:** sender and receiver are mutual contacts

**Steps:**
1) Receiver: goes offline
2) Sender: sent 10 messages, wait for them to change status to "Sent"
3) Sender: goes offline (just closed the app, therefore the messages should be stored on the history node)
4) Receiver: goes online
5) Receiver: wait for the messages.

**Expected result:** messages will be fetched from history node in max 2 mins after the receiver goes back online
**Actual result:** messages are not received until the sender goes back online (waited for 6 mins after  receiver goes back online)
Messages that lost were sent at 13:43 (10 items) and received at 13:49(10 items) when sender went back online and they started to re-transmit


Sender logs: [logs.zip](https://github.com/user-attachments/files/17934743/logs.zip)

Receiver logs: [Status-debug-logs.zip](https://github.com/user-attachments/files/17934736/Status-debug-logs.zip)

**Comment by churik** [comment]
apart from https://github.com/status-im/status-mobile/pull/21674#issuecomment-2503859097 and taking into account https://github.com/status-im/status-mobile/pull/21674#issuecomment-2501559236 I can confirm that:
- initial issue with communities are not being fetched on staging fleet is fixed
- e2e failures are not related to PR.

So if you are 100% sure that the message fetching in 1-1 chat is not getting worse in this PR (meaning: https://github.com/status-im/status-mobile/pull/21674#issuecomment-2503859097 is not related to PR), you have a green light from mobile side.

**Comment by richard-ramos** [comment]
Looking at the logs I'm thinking this failure to retrieve messages is not related to the PR. This PR what it does is to change the start/end time of the queries ONLY if they exceed 24h, which is not the case for the queries being done when going from offline to online.

**Comment by churik** [comment]
@richard-ramos if you can upgrade version on mobile client to include your changes, I'd appreciate that

**Comment by richard-ramos** [comment]
Done, in last commit i updated the status-go version to the commit from `develop` that includes my changes

**Comment by churik** [comment]
thanks! it seems that your commit is already included to current mobile version in nightly, tests confirmed that, so I'm closing current PR and initial issue

**Pull request closed without merging**
