### PR TITLE
deps: bump react-native-linear-gradient library

### PR DESCRIPTION
**Pull request by siddarthkay**
## Summary

`react-native-linear-gradient` library has to be upgraded to `3.0.0-alpha.1` for new architecture support on `Android`.

## Testing notes
Only visual elements where gradients are used would be impacted.

## Platforms
- Android
- iOS

status: ready

related issue : https://github.com/status-im/status-mobile/issues/18138

### CODE REVIEW

**Review by flexsurfer — APPROVED** [review]

**Review by clauxx — APPROVED** [review]

**Review by Parveshdhull — APPROVED** [review]

**Review by ilmotta — APPROVED** [review]

**Comment by siddarthkay** [comment]
@status-im/mobile-qa : Actually this PR just requires a design review since this library upgrade could probably have an impact on how gradients are rendered or how they look.
cc @Francesca-G

**Comment by churik** [comment]
@Francesca-G if you can point us to the places in the app where gradients are used, it would be really helpful!!!

**Comment by Francesca-G** [comment]
> @Francesca-G if you can point us to the places in the app where gradients are used, it would be really helpful!!!

**Wallet:**
- [Send and Bridge](https://www.figma.com/design/xLs1KYmF4e6WwRTZVJKeUK/Descoped-Wallet?node-id=15417-73891&t=plQoiApuJDBk8Yk6-1)
Screenshot 2024-06-10 alle 15 22 49

>
- [Wallet account](https://www.figma.com/design/xLs1KYmF4e6WwRTZVJKeUK/Descoped-Wallet?node-id=1869-438898&t=plQoiApuJDBk8Yk6-1)
Screenshot 2024-06-10 alle 15 24 34

>
- [Share QR](https://www.figma.com/design/xLs1KYmF4e6WwRTZVJKeUK/Descoped-Wallet?node-id=15586-132719&t=plQoiApuJDBk8Yk6-1) 
Screenshot 2024-06-10 alle 15 25 41

------------------------------
**Messages:**
- [Group details and new group chat](https://www.figma.com/design/7KIYbhoqNGAIFonE0w9TDz/Messages-for-Mobile?node-id=1818-386184&t=vm07zm8qT1iHSnnF-1)
Screenshot 2024-06-10 alle 15 29 35


------------------------------
**Communities:**
- [Community cover](https://www.figma.com/design/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?m=auto&node-id=15331-284865&t=qrxKx4Gw5mtf0KT2-1)
Screenshot 2024-06-10 alle 15 32 00

>
- [Channel details](https://www.figma.com/design/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?m=auto&node-id=2991-135923&t=qrxKx4Gw5mtf0KT2-1)
Screenshot 2024-06-10 alle 15 33 59


>
>
That should be it, hopefully I'm not forgetting anything 🙈

**Comment by qoqobolo** [comment]
Another one: account switcher in wallet

Screenshot 2024-06-11 at 12 10 17

**Comment by qoqobolo** [comment]
Thanks @siddarthkay @Francesca-G!
No issues found, PR is ready for design review

**Review by Francesca-G — APPROVED** [review]
Looks good to me 🚀

**Comment by siddarthkay** [comment]
Thanks @qoqobolo and @Francesca-G for taking a look :)

**Pull request merged**
