### PR TITLE
remove the PUK and pairing screen from Keycard onboarding

### LINKED ISSUE #12083: remove PUK and Pairing code from keycard onboarding
**Problem:** when a user onboard with a keycard he needs to remember PIN, PUK, Pairing code, and seed. That's too much information and makes the process difficult and confusing for approval

**Solution studied:** we have dismissed the idea to derive puk and pairing from the seed, mostly for security reasons. See the issue here: https://github.com/status-im/status-react/issues/9064

**Solution selected:** we will remove puk and pairing from the onboarding, and allow the user to get these informations in the keycard settings. We also need to allow a user to factory reset his card when he doesn't have his PUK and needs it, because he's blocked. Or when he needs his pairing code and he's blocked (e.g lost phone).

**Description of the solution:**
https://notes.status.im/puk-and-pairing-removal%20from%20onboarding?view

**Sequential steps:**
- [x] factory reset on keycard onboarding 1st screen 
    - PR https://github.com/status-im/status-react/pull/12055
- [x] factory reset on login screen from a keycard multiaccount 
- [x] add copy to all screens where the user is blocked when he doesn't know his PUK saying "you don't know your PUK? learn how to factory reset your card here", redirecting to the flow to factory reset
- [x] add copy to all screens where the user is blocked when he doesn't know his Pairing code saying "you don't know your Pairing code? learn how to proceed here", redirecting to the flow to factory reset
- [x] remove PUK and Pairing from onboarding

### PR DESCRIPTION
**Pull request by bitgamma**
fixes #12083.

Since this removes a screen from the onboarding, E2E tests have been adapted too.

Another affected component is the "Begin setup" screen, which used to have bullet points with the steps to do. Since unless you are creating a new account a single bullet-point would remain, as discussed with @guylouis, the bullet points were replaced with text. The pairing screen also doesn't claim that the pairing code was shown during onboarding anymore.

attached are screenshots for localization. The ``enter-pair-code-description`` is an already existing key which has been modified so localization will need to be updated accordingly.

### CODE REVIEW

**Comment by guylouis** [comment]
@bitgamma indeed I think the text is ok

**Review by Serhy — APPROVED** [review]
👍

**Comment by qoqobolo** [comment]
@bitgamma 

#### ISSUE 1: Text `Pairing code was displaying to you during the Keycard setup` is shown when recovering a multiaccount on another device using Keycard
Since this information is no longer relevant, the text in this flow also should be changed.

Steps:
1. Open Status
2. Access existing key
3. Recover with Keycard

Screenshot 2021-05-26 at 16 56 14

**Comment by bitgamma** [comment]
@qoqobolo thanks for finding this! I have changed the text to reflect the current behaviour

**Comment by qoqobolo** [comment]
@bitgamma thank you! PR looks good to me and can be merged.

**Pull request merged**
