### PR TITLE
Set Activity Center as the new default

### PR DESCRIPTION
**Pull request by ilmotta**
Partially implements https://github.com/status-im/status-mobile/issues/14490

### Summary

This tiny little PR simply enables the new Activity Center (AC) by default. A follow up PR will then remove the old Notification Center code and the flag. The goal is for the AC to be usable in the next release, so we can dogfood the redesigned mobile app.

**Types of notifications supported by the new AC as of 2022-12-06**

- Mentions
- Contact requests
- Identity verification requests (apparently will be deprecated in the MVP).

#### Why?

This PR is needed because I want to be sure the new AC won't disrupt the QA team in the first place. Also because I want the next PR (not yet created) that will remove the old Notification Center to be merged as fast as possible, in order to avoid code conflicts. Hence why enabling the flag is coming before code deletion.

#### Platforms

- Android
- iOS

### Steps to test

The most important case to test IMO is the Contact Request flow, because it's a requirement to chat with other users. To test the Activity Center, simply click on the bell icon in the home screen.

There are many issues already created mapping the work left to be done for the AC. You can check them out here https://github.com/status-im/status-mobile/labels/Activity%20center.

**Figma flows**: https://www.figma.com/file/eDfxTa9IoaCMUy5cLTp0ys/Shell-for-Mobile?node-id=451%3A18681&t=gIS1Vt4Ucc2gSrlr-0

### Note for QA review

- There's an open issue I'm working on right now #14495 

status: ready

### CODE REVIEW

**Review by flexsurfer — APPROVED** [review]

**Review by J-Son89 — APPROVED** [review]

**Comment by VolodLytvynenko** [comment]
hi @ilmotta please, help me with clarification of the notification receiving flow in AC.
Currently, all e2e tests are broken due no ability to find 'ActivityCenterChatElement' element.  This happens because the notification in the Activity Centre is not shown if the flow of chat key adding is going through this  [+] button
image that is shown on the chat page. 
Is this an expected behavior that after key chat is pasted, the notification is not shown? If yes, what should be done with this button if it is not working anymore? Currently, I don't see reasons to use it.

**Comment by ilmotta** [comment]
> hi @ilmotta please, help me with clarification of the notification receiving flow in AC. Currently, all e2e tests are broken due no ability to find 'ActivityCenterChatElement' element. This happens because the notification in the Activity Centre is not shown if the flow of chat key adding is going through this [+] button image that is shown on the chat page. Is this an expected behavior that after key chat is pasted, the notification is not shown? If yes, what should be done with this button if it is not working anymore? Currently, I don't see reasons to use it.

Hey @VladimrLitvinenko, thanks for testing the PR. Let me try to explain some details that might not be obvious.

The new Activity Center is not (necessarily) going to display the same notifications displayed by the current Notification Center. What's currently implemented in the new AC is what I've shared in the PR description:

- Notifications for mentions.
- Notifications for contact requests.
- Notifications for identity verification requests (apparently this feature will be deprecated for the MVP, so I'd say it's lower priority to test it now).

Other kinds of notifications will be supported in the next coming weeks/months. I think it's important to reinforce that **the backend still generates/stores the same notifications, it's just that the new AC frontend has not yet implemented a way to display them**. So the new AC has the same *capabilities* as the old Notification Center, but we need more time to achieve feature parity.

I've just created issue https://github.com/status-im/status-mobile/issues/14501, as it's related to this problem we're discussing now. As I mentioned in #14501, there will be different business rules to how/when 1:1 notifications are generated, but because I haven't been working on this specific type of notification I can't answer precisely the new requirements. This is left for the person that eventually pick the issue.

So, to answer your question:

> If yes, what should be done with this button if it is not working anymore? Currently, I don't see reasons to use it.

I think for now we should keep the button. But perhaps we should disable the failing tests relying on a 1:1 notification being generated. Do you think we can skip the failing tests? I know it's not ideal :man_shrugging:

**Comment by VolodLytvynenko** [comment]
Hi @ilmotta should these UI notifs be in the scope of the current PR

**ISSUE 1: The notif in Activity is not shown as per visual if the light mode is used**
**Steps to reproduce:**
1. Go to Appearance -> Set 'light' mode
2. Go to contacts as User_A
3. Add new contact using the chat key of User_B
4. Check the Activity center as User_B

**Actual result:**
- The 'sent contact request' text is shifted and shown in 2 rows if '3 random name' is too long
- The 'sent contact request' text is black in color
image

**Expected result:**
- The 'sent contact request' text is  shown in 1 row below if '3 random name' is too long
- The 'sent contact request' text is white color
image

**ENV:** Any android device

I am not sure that issues #2 and #3 are in the scope of this PR. Let me know if they should be created separately 
**ISSUE 2. The empty Activity Center is not shown as per visual**
**Steps to reproduce:**
Open empty activity center

**Actual result:**
image

**Expected result:**
image

**ISSUE 3. The accepted and declined contact are not shown in the Activity Center**
**Steps to reproduce:**
1. Go to contacts as User_A
2. Add new contact using the chat key of User_B
3. Check the Activity center as User_B
4. Accept or Decline the request

**Actual result:**
The notification is disappeared

**Expected result:**
The status of the request is shown as per visual as Accepted or Declined
image

**Comment by VolodLytvynenko** [comment]
Currently, I am blocked by https://github.com/status-im/status-mobile/issues/14362 to test this PR fully, because the mentions are not ready yet

**Comment by ilmotta** [comment]
Thanks for the detailed reports @VladimrLitvinenko. Let's see:

> The 'sent contact request' text is black in color

I'm going to fix this real quick in a future PR. Good catch.

> The 'sent contact request' text is shifted and shown in 2 rows if '3 random name' is too long

This is the expected behavior in Figma as well. In your screenshot we can see the text would not fit in a single line without overflowing the surrounding padding, so it has to be displayed in 2 rows.

> The empty Activity Center is not shown as per visual.

This is on purpose, because the Design team has not finished the mockups for the empty state, so meanwhile it was decided to not waste time implementing that temporary empty state (the text will change, styles, etc). This is being tracked on issue [Display empty tab state when there are no notifications](https://github.com/status-im/status-mobile/issues/14493)

> The accepted and declined contact are not shown in the Activity Center

I tried to reproduce this issue, but it works fine for me. So could you give more detailed instructions about the problem? Which tab you had selected? Was the all/unread filter enabled? If it's not asking too much, but a video would help me reproduce :)

**Comment by VolodLytvynenko** [comment]
> I tried to reproduce this issue, but it works fine for me. So could you give more detailed instructions about the problem? Which tab you had selected? Was the all/unread filter enabled? If it's not asking too much, but a video would help me reproduce :)

Sorry, I didn't specify it should be done on Android. The record is done for android studio, but for my real device: Huawei p20 light; Android version: 9 it is reproducible as well.
https://user-images.githubusercontent.com/52490791/206184020-53a719a4-1f3e-4624-ac5e-abfc561d017f.mp4

Also, the error pop up appears when I try to navigate to any tab: "all", "admin", "mention" etc. that also visible on the record
image

**Comment by ilmotta** [comment]
@VladimrLitvinenko

> Sorry, I didn't specify it should be done on Android. The record is done for android studio, but for my real device: Huawei p20 light; Android version: 9 it is reproducible as well.

I exclusively use GNU/Linux and Android Studio :)

> Also, the error pop up appears when I try to navigate to any tab: "all", "admin", "mention" etc. that also visible on the record

I've never seen this error. I'll try to reproduce using other physical devices I have here, because it never happened to me in Android Studio.

---

About the disappearing notification, this is expected according to the current design. It vanished because once you interact with a notification with call to action, the notification is marked as read, but because you had the filter enabled to only display unread notifications, it disappeared. If you accept/reject the contact request with the filter disabled (i.e. show both read/unread), then you'll still see the notification.

As far as I remember, designers chose a behavior similar to WhatsApp or some other known product. I think some sort of animation could be helpful to users, to somehow hint what happens when a notification is marked as read. Some animations will be implemented before the MVP is released @VladimrLitvinenko. I'm taking note of your feedback for future reference.

**Comment by ilmotta** [comment]
> Currently, I am blocked by #14362 to test this PR fully, because the mentions are not ready yet

What's exactly blocking this PR from being further reviewed/approved @VladimrLitvinenko? I'm not sure I understand the relationship between issue #14362 and this PR.

**Comment by du82** [comment]
I am getting the same error. The top bar is also not the same color, and the blur color doesn't match designs

Screenshot_2022-12-07-08-17-51-24_65ad86f86fd2321a85272a99323da10f

**Comment by du82** [comment]
Visually looks good in dark mode, not in light mode. Bug wise, still having problems

**Comment by VolodLytvynenko** [comment]
> > Currently, I am blocked by #14362 to test this PR fully, because the mentions are not ready yet
> 
> What's exactly blocking this PR from being further reviewed/approved @VladimrLitvinenko? I'm not sure I understand the relationship between issue #14362 and this PR.

Currently, as a user, I am not able to mention other users in chats using @. It is described in https://github.com/status-im/status-mobile/issues/14362 in ISSUE 1.  
The relation between those PRs that in the current PR implemented notification that should be shown after some users are mentioned. Am I right?

**Comment by VolodLytvynenko** [comment]
> About the disappearing notification, this is expected according to the current design. It vanished because once you interact with a notification with call to action, the notification is marked as read, but because you had the filter enabled to only display unread notifications, it disappeared. If you accept/reject the contact request with the filter disabled (i.e. show both read/unread), then you'll still see the notification.
> 
Oh. Now I got it. Thank you!

**Comment by ilmotta** [comment]
> Visually looks good in dark mode, not in light mode. Bug wise, still having problems

@VladimrLitvinenko, @du64: I'll try give a round of review for light mode and create an issue to fix these type of errors later.

**Comment by ilmotta** [comment]
> I am getting the same error. The top bar is also not the same color, and the blur color doesn't match designs

@du64, which "same error" are you referring to?

**Comment by ilmotta** [comment]
> > > Currently, I am blocked by #14362 to test this PR fully, because the mentions are not ready yet
> > 
> > 
> > What's exactly blocking this PR from being further reviewed/approved @VladimrLitvinenko? I'm not sure I understand the relationship between issue #14362 and this PR.
> 
> Currently, as a user, I am not able to mention other users in chats using @. It is described in #14362 in ISSUE 1. The relation between those PRs that in the current PR implemented notification that should be shown after some users are mentioned. Am I right?

It's a bit more complicated @VladimrLitvinenko. As I mentioned previously, I've created the issue https://github.com/status-im/status-mobile/issues/14501, which is related to how mentions will be displayed in the new Activity Center. The business rules are different, and some of them still need the blessing/review from designers. We're not quite ready to play that issue. I believe this will affect your testing processes meanwhile.

**Comment by du82** [comment]
@ilmotta this is the bug I was referring to, sent the wrong screenshot before

Screenshot_2022-12-07-08-54-01-09_65ad86f86fd2321a85272a99323da10f

**Comment by ilmotta** [comment]
> @ilmotta this is the bug I was referring to, sent the wrong screenshot before
> 

Thanks @du64. This one seems to be the major blocker IMO. I'm investigating it now.

**Comment by churik** [comment]
@ilmotta thank you for making the activity element in AC so easy-to-find for automation!
Can I ask you in the scope of changes to add accessibility-label to the close button in AC?  
I found a workaround, but the XPath for this element doesn't look quite reliable.
Appium 2022-12-07 17-58-25

**Comment by churik** [comment]
> It's a bit more complicated @VladimrLitvinenko. As I mentioned previously, I've created the issue https://github.com/status-im/status-mobile/issues/14501, which is related to how mentions will be displayed in the new Activity Center. The business rules are different, and some of them still need the blessing/review from designers. We're not quite ready to play that issue. I believe this will affect your testing processes meanwhile.

From this comment and https://github.com/status-im/status-mobile/issues/14501 and from the fact that users just cannot send mentions for now due to https://github.com/status-im/status-mobile/issues/14362 does it make sense to reduce testing scope here only basic flow for contact request? I just see no way to send any type of mention now, including mentions in communities and mentions in group chats (perhaps we can from IOS, but not quite sure)

**Comment by ilmotta** [comment]
> @ilmotta thank you for making the activity element in AC so easy-to-find for automation! Can I ask you in the scope of changes to add accessibility-label to the close button in AC? I found a workaround, but the XPath for this element doesn't look quite reliable. Appium 2022-12-07 17-58-25

Sure @churik, I just committed to add an accessibility label named `close-activity-center` in the button. Please, let me know if you have other unreliable selectors and I'll add the IDs in the code.

**Comment by ilmotta** [comment]
> > It's a bit more complicated @VladimrLitvinenko. As I mentioned previously, I've created the issue #14501, which is related to how mentions will be displayed in the new Activity Center. The business rules are different, and some of them still need the blessing/review from designers. We're not quite ready to play that issue. I believe this will affect your testing processes meanwhile.
> 
> From this comment and #14501 and from the fact that users just cannot send mentions for now due to #14362 does it make sense to reduce testing scope here only basic flow for contact request? I just see no way to send any type of mention now, including mentions in communities and mentions in group chats (perhaps we can from IOS, but not quite sure)

:+1: I think your suggestion is the most sensible @churik. According to the new rules (yet to be set in stone), it could well be the case that mention notifications won't be generated in a way that's very testable (e.g. mentions could be aggregated for a certain amount of time to avoid spamming the user with too many in a short period of time).

**Comment by churik** [comment]
Tests are fixed in https://github.com/status-im/status-mobile/pull/14506
Just tell me when PR can be retested, no blockers from the automation side anymore.

**Comment by ilmotta** [comment]
> Tests are fixed in #14506 Just tell me when PR can be retested, no blockers from the automation side anymore.

That's great news @churik! Thank you.

This PR will receive a fix when I find out why a RN function is undefined after the app is released (error popup https://github.com/status-im/status-mobile/pull/14492#issuecomment-1340927361)

I'll request your reviews again once I find the fix.

**Comment by ilmotta** [comment]
FYI: @VladimrLitvinenko, @churik, @du64

I just pushed two fixes. Please, let me know if we're good to go and I'll merge into `develop`.

- Switching tabs no longer shows an error popup.
- When light mode is enabled, the notification "context tags" section displays the correct color.

**Comment by VolodLytvynenko** [comment]
> FYI: @VladimrLitvinenko, @churik, @du64
> 
> I just pushed two fixes. Please, let me know if we're good to go and I'll merge into `develop`.
> 
> * Switching tabs no longer shows an error popup.
> * When light mode is enabled, the notification "context tags" section displays the correct color.


@ilmotta thank you for your work. Soon it'll be tested

**Comment by VolodLytvynenko** [comment]
@ilmotta  testing for PR is passed and ready to be merged. Thank you!

**Comment by ilmotta** [comment]
> @ilmotta testing for PR is passed and ready to be merged. Thank you!

image

**Pull request merged**
