### PR TITLE
[#5670] [desktop] fix jumping cursor when quickly typing in Recovery phrase

### LINKED ISSUE #5670: Cursor jumps to beginning of the row in when quickly typing in "Recovery phrase"
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: cursor in field "Recovery phrase" moves to the beginning of phrase when you are typing fast.

#### Expected behavior
the cursor doesn't move to the beginning of the line

#### Actual behavior
the cursor moves to the beginning of line

### Reproduction

- Open Status-desktop
- Click "Add existing account"
- Type recovery phrase (fast)

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: desktop nightly 27/08/18
* Operating System: Mac OSx
* Video: http://take.ms/lgVKH

<blockquote><div>Monosnap screenshot tool</div><div><strong><a href="https://monosnap.com/file/Obc0xEAgXtgmBAojid11QPajQTSRG0">File "screencast 2018-08-28 17-02-40.mp4"</a></strong></div><div>Monosnap — the best tool to take & share your screenshots.</div></blockquote>

### PR DESCRIPTION
**Pull request by rasom**
fix #5670

status: ready

### CODE REVIEW

**Comment by ghost** [comment]
### Pull Request Checklist
- [x] Have you updated the documentation, if impacted (e.g. [docs.status.im](https://docs.status.im/docs/build_status.html))?

**Review by dmitryn — APPROVED** [review]

**Review by yenda — APPROVED** [review]
can you put todo in uppercase it's nicer for emacs :D

**Comment by rasom** [comment]
@yenda done

**Comment by churik** [comment]
Tested that issue is not reproducible on Mac OSx build and fix doesn't affect IOS and Android build ("Recovery phrase" field)

**Pull request merged**
