### PR TITLE
chore: lint against re-frame dispatch/subscribe in quo components

### PR DESCRIPTION
**Pull request by yqrashawn**
Add a script to lint against below strings in `src/quo` and `src/quo2`.

1. `re-frame/dispatch`
1. `re-frame/subscribe`
1. `rf/dispatch`
1. `rf/subscribe`
1. `>evt`
1. `<sub`

Script added into `make lint`

status: ready

### CODE REVIEW

**Review by jakubgs — APPROVED** [review]
It would be better if we could somehow check this using the linter we already use, but if there's no such possibility it's fine by me. But check with actual mobile devs.

**Comment by flexsurfer** [comment]
it should be rf/sub

**Comment by yqrashawn** [comment]
Not quite understand, what should be rf/sub
Do you mean keep `rf/...` and remove `re-frame/...`?
@flexsurfer

**Comment by flexsurfer** [comment]
`rf/sub` instead of `rf/subscribe`

**Comment by yqrashawn** [comment]
> `rf/sub` instead of `rf/subscribe`

I added `rf/sub` and kept `rf/subscribe`. Is that ok?

**Comment by ilmotta** [comment]
This is a good implementation for now, thanks @yqrashawn. The best option in the future will be to process the output from clj-kondo's analysis because it's more reliable. The data processing could be performed by [Babashka](https://github.com/babashka/babashka) as well, so it's Clojure all the way down.

> It would be better if we could somehow check this using the linter we already use, but if there's no such possibility it's fine by me. But check with actual mobile devs.

You're correct @jakubgs, there's such a way, but it might be a bit too much work for now. Although I find such work to be quite valuable, because it could be extended to catch other conventions we're trying to establish in the codebase that are not available directly from the default linter rules.

https://cljdoc.org/d/clj-kondo/clj-kondo/2022.06.22/doc/analysis-data

**Pull request merged**
