### PR TITLE
fix delayed display of top bar in chat after sending messages

### LINKED ISSUE #18240: Delayed display of top bar in chat after sending messages
Follow up for https://github.com/status-im/status-mobile/pull/18055

### Steps:
1. Open an empty chat. (or clear the existing one)
2. Send messages sequentially, one by one.
3. Observe the behavior of the top bar.
4. Scroll up within the chat.
5. While at the top, send an additional message.

### Actual result:
The top bar does not appear promptly after sending a message, particularly when the user is positioned at the top of the chat,

On IOS

https://github.com/status-im/status-mobile/assets/52490791/78071f42-8733-4ac4-bf7f-00fab4132a89

On Android

https://github.com/status-im/status-mobile/assets/52490791/f7aac4c2-4d0c-4721-8360-b6abe6d1d225

### Expected result:
The top bar should be shown when the 1-1 avatar is hidden

How it worked on the nightly [18 Dec 2023]

https://github.com/status-im/status-mobile/assets/52490791/3d59d5e0-b02d-4fb7-88d7-6a76e053ce96

### Devices:
- iPhone 11 Pro max, IOS 16
- Pixel 7a. Android 14

### PR DESCRIPTION
**Pull request by Parveshdhull**
fixes https://github.com/status-im/status-mobile/issues/18240

status: ready

### CODE REVIEW

**Review by ibrkhalil — APPROVED** [review]

**Comment by mariia-skrypnyk** [comment]
@Parveshdhull Hi!

I am facing this https://github.com/status-im/status-mobile/issues/18240 issue on Android and iOS. 

Android:

Please, have a look on my video. Top bar appears only as you can see from my third "Hi" message . When i send my first 2 messages Avatar hides partly and it looks not good I suppose.

https://github.com/status-im/status-mobile/assets/147824399/fa9f5987-659d-4870-b338-79ac66eb8ad5

iOS: 

Please, have a look on my video. Top bar appears only as you can see from my second "H" message . When i send my first message Avatar hides partly and it looks not good I suppose.


https://github.com/status-im/status-mobile/assets/147824399/0efc6c0e-98e7-4e25-bf34-ec9b59887946

**Comment by ibrkhalil** [comment]
> @Parveshdhull Hi!
> 
> I am facing this #18240 issue on Android and iOS.
> 
> Android:
> 
> Please, have a look on my video. Top bar appears only as you can see from my third "Hi" message . When i send my first 2 messages Avatar hides partly and it looks not good I suppose.
> 
>  video_2023-12-29_15-28-14.mp4 
> iOS:
> 
> Please, have a look on my video. Top bar appears only as you can see from my second "H" message . When i send my first message Avatar hides partly and it looks not good I suppose.
> 
>  IMG_5859.MP4

According to design description when designing this animation, They wanted to show the small name once the big name is not visible, And they shouldn't both be visible at the same time.

**Comment by Parveshdhull** [comment]
hi @mariia-skrypnyk,
Thank you very much for testing the PR and finding the issue.

**Android Issue:** This was an interesting edge case. When we closed the keyboard by scrolling (instead of the back button) both the `on-scroll` function and `on-layout`(closing of the keyboard) updated the final position and resulted in the wrong value. Should be fixed now.

About the Android/IOS issue top nav appearing after 2/3 of messages is expected. As @ibrkhalil, mentioned according to the design team top nav should be visible once the big avatar is hidden and both should not be visible at the same time. (like in ios case, a big avatar is still visible a little)

**Comment by mariia-skrypnyk** [comment]
> 🤖`apk`

**Comment by mariia-skrypnyk** [comment]
> > @Parveshdhull Hi!
> > I am facing this #18240 issue on Android and iOS.
> > Android:
> > Please, have a look on my video. Top bar appears only as you can see from my third "Hi" message . When i send my first 2 messages Avatar hides partly and it looks not good I suppose.
> > video_2023-12-29_15-28-14.mp4
> > iOS:
> > Please, have a look on my video. Top bar appears only as you can see from my second "H" message . When i send my first message Avatar hides partly and it looks not good I suppose.
> > IMG_5859.MP4
> 
> According to design description when designing this animation, They wanted to show the small name once the big name is not visible, And they shouldn't both be visible at the same time.

Thanks for your comment @ibrkhalil .  I just have a small question regarding the behaviour you described above. 
Please @Parveshdhull feel free to look too.
Is this situation is correct when the big name isn't hidden totally but we already see a small name appeared:
Screenshot 2024-01-03 at 10 36 24

**Comment by mariia-skrypnyk** [comment]
@Parveshdhull I've found such an issue on your latest PR build. Please have a look on my description below. 

**ISSUE 1: [Android]** Profile avatar quickly moves to the left while user closes keyboard. 
I've made video from my device and from saucelabs real device:

https://github.com/status-im/status-mobile/assets/147824399/a97e9a95-ecf5-4aac-8999-50d612b5a85e


https://github.com/status-im/status-mobile/assets/147824399/161463d6-d467-41e9-a90a-6bb2bd086e4f

**Review by alwx — APPROVED** [review]

**Comment by Parveshdhull** [comment]
hi @mariia-skrypnyk, Thank you for finding these issues.

> Is this situation correct when the big name isn't hidden totally but we already see a small name appear:

I am not sure which one is correct behavior, as we don't have any animations for this situation. Only have this [old](https://vimeo.com/803434748) video which don't work anymore.
But still I updated the animation, so name should not visible at same time. Please let me know if this looks ok.

About another issue, jumping of top-bar in left. It looks this one is also in develop. Will it be ok if I fix this one separately?

**Comment by mariia-skrypnyk** [comment]
> I've made video from my device and from saucelabs real device:



> hi @mariia-skrypnyk, Thank you for finding these issues.
> 
> > Is this situation correct when the big name isn't hidden totally but we already see a small name appear:
> 
> I am not sure which one is correct behavior, as we don't have any animations for this situation. Only have this [old](https://vimeo.com/803434748) video which don't work anymore. But still I updated the animation, so name should not visible at same time. Please let me know if this looks ok.
> 
> About another issue, jumping of top-bar in left. It looks this one is also in develop. Will it be ok if I fix this one separately?

Thanks! I am going to test your fix with the name case.
As for top-bar jumping I've created separated PR [here](https://github.com/status-im/status-mobile/issues/18409).

**Comment by Parveshdhull** [comment]
hi, no new changes. Just rebased the PR.

**Comment by Parveshdhull** [comment]
~hi, no new changes. Just rebased the PR.~

fixed a small issue in ios where the big avatar is sometime not shown when the chat screen is opened

<div align="center">
Screenshot
</div>

**Comment by mariia-skrypnyk** [comment]
Hi @Parveshdhull !

Androids looks much better! Great Thanks!
But now we do not have the same behaviour for iOS. Let me show you.

**ISSUE 2:**  [iOS] User see no profile picture in 1to1 chat top bar after sending his second message

**Steps:** 

1. Login as User B on iOS
2. Open 1to1 chat with User B
3. Clear history
4. Type "Hi" and send
5. Type one more "Hi" and Send

**Actual result:** User see no profile (big or small) at the top bar
no_profile_iOS

**Expected result:** as we do not see big profile name at this case we should see the small one. Such case works great on Android PR build
Android

**Tested on:** 
iPhone 13 iOS 17.1.2
Samsung A34 13.0

**Comment by Parveshdhull** [comment]
hi @mariia-skrypnyk, Thank you for finding this issue. Should be fixed now.

**Comment by mariia-skrypnyk** [comment]
> hi @mariia-skrypnyk, Thank you for finding this issue. Should be fixed now.

Thanks @Parveshdhull!
Great job! Feel free to merge this PR.

Tested on:
real iPhone 13 
Sauce Labs devices: iPhone 12 mini and iPhone 13 max

**Pull request merged**
