### PR TITLE
[fix 5814] fix add custom bootnode

### LINKED ISSUE #5814: Can't add custom bootnode or network. "Save" button is inactive
### Description

*Type*: Bug

*Summary*: Even though a bootnode address is provided, the "Save" button in the add bootnode screen is still inactive. In result, users can't add custom bootnodes. Same happens when adding custom network. It worked fine on nightly from Sep 11 (`bd3f95`) but stopped working in `ca1490`.

This issue is related to https://github.com/status-im/status-react/issues/5813.

### Reproduction

Custom bootnode:
- Open Profile -> Advanced -> Bootnodes and click "+" to add custom bootnode
- Provide  name and `enode://a8a97f126f5e3a340cb4db28a1187c325290ec08b2c9a6b1f19845ac86c46f9fac2ba13328822590fd3de3acb09cc38b5a05272e583a2365ad1fa67f66c55b34@167.99.210.203:30404` as custom bootnode 
- Try to click Save

Custom network:
- Try to add custom ropsten network `https://ropsten.infura.io/iMko0kJNQUdhbCSaJcox` 

### Additional Information
* Status version: `ca1490`, https://ci.status.im/job/status-react/job/nightly/689/
* Operating System: Android, iOS

<blockquote><div><strong><a href="https://ci.status.im/job/status-react/job/nightly/689/">status-react » nightly #689 [Jenkins]</a></strong></div></blockquote>

### PR DESCRIPTION
**Pull request by yenda**
the validation regexp is expecting a password, there is no password
for bootnodes

partial-fix #5814 

status: ready

### CODE REVIEW

**Review by janherich — APPROVED** [review]

**Review by mandrigin — APPROVED** [review]

**Comment by lukaszfryc** [comment]
@yenda "Save" button is still disabled when I enter bootnode address. Also, I nothing happens when I want to scan valid QR code of a bootnode. I use https://www.qr-code-generator.com/. It works fine on last released version (0.9.27).  

<blockquote><div><strong><a href="https://www.qr-code-generator.com/">QR Code Generator - Create QR codes here</a></strong></div></blockquote>

**Comment by yenda** [comment]
@lukaszfryc sorry the PR wasn't ready yet I was waiting for artifactory to be able to test in the simulator. should be fixed now

**Comment by lukaszfryc** [comment]
@yenda custom bootnodes work both on Android and iOS now. But, https://github.com/status-im/status-react/issues/5814 is also about inability to add custom networks. Could you fix custom networks as well in this PR (probably the same cause)? If not, please change "fixes https://github.com/status-im/status-react/issues/5814" to "partially fixes https://github.com/status-im/status-react/issues/5814". Thanks!

**Comment by yenda** [comment]
@lukaszfryc it's quite a different error, I'm making a PR

**Pull request merged**
