### PR TITLE
[#13007] Move ENS logic to status-go

### LINKED ISSUE #13007: Move ENS logic to status-go
Our friends from desktop moved some logic for ENS to status-go, so it's shared across clients.

We should leverage as much as possible the shared code, so removing ideally some code from status-react, in order to re-use code:

https://github.com/status-im/status-go/commit/22bb09a94f702c20d017644156c0997f0c8f0a0e
https://github.com/status-im/status-lib/blob/master/status/statusgo_backend_new/ens.nim
 https://github.com/status-im/status-lib/blob/master/status/ens.nim
 
I don't know to which extent it covers all the functionalities in status-react, if necessary we can move in steps or implement the remaining in status-go.

### PR DESCRIPTION
**Pull request by flexsurfer**
fixes #13007

### CODE REVIEW

**Review by rasom — APPROVED** [review]

**Comment by pavloburykh** [comment]
@flexsurfer thanks for PR. I'm trying to rebuild IOS build as it is outdated but building fails with Lint error, could you please take a look? 

```
15:41:04  + make lint
15:41:04  yarn clj-kondo --confg .clj-kondo/config.edn --lint src && \
15:41:04  	TARGETS=$(git diff --diff-filter=d --cached --name-only src && echo src) && \
15:41:04  	clojure -Scp "$CLASS_PATH" -m cljfmt.main check --indents indentation.edn $TARGETS
15:41:04  [0;32mConfiguring Nix shell for target 'clojure'...[0m
15:41:06  error: syntax error, unexpected $end, expecting '"', at (string):1:24
15:41:06  make: *** [lint] Error 1
```

https://ci.status.im/job/status-react/job/prs/job/ios/job/PR-13029/3/consoleText

**Comment by flexsurfer** [comment]
@pavloburykh rebased and pushed

**Comment by pavloburykh** [comment]
@flexsurfer 
## Issue 1 

### Existing ENS is not resolved in wallet
Preconditions: ropsten test network is chosen. 

STR: 

1. Open Sent transaction page
2. Tap choose recipient
3. In address field type valid ENS, for example pavlotest.eth
4. Observe the result

Actual result: 
Recipient with such ENS is not found. Below I attach the video from PR build (reproducing the bug) and nightly build for comparison and demonstration that pavlotest.eth is an existing ENS. 

https://user-images.githubusercontent.com/97245802/150815645-9187e357-d61d-4bfc-9f44-f8f184d0883f.mp4
[logs (4).zip](https://github.com/status-im/status-react/files/7926814/logs.4.zip)


Expected result: 
Recipient's address is found and displayed under address field. Done button is active. User is able to proceed with transaction.

**Comment by flexsurfer** [comment]
thanks @pavloburykh , fixed

**Pull request merged**
