### PR TITLE
Filter debugging [WIP]

### PR DESCRIPTION
**Pull request by vitvly**
Includes some extra filter-related logging. Related to investigation of message delivery issues in https://github.com/status-im/status-mobile/issues/16873

Depends on https://github.com/status-im/status-go/pull/4020

### CODE REVIEW

**Comment by churik** [comment]
PR doesn't cause any regression, safe to merge to give more insights about issues with message reliability

**Comment by flexsurfer** [comment]
hey @siphiuel status-go version looks incorrect, could you check ?

**Comment by vitvly** [comment]
@flexsurfer yes it's WIP, will mark it so, sorry. Some more changes pending as outlined here https://github.com/status-im/status-go/issues/4042

**Comment by flexsurfer** [comment]
i mean, even wip doesn't make sense, probably better to open PR when its ready?

**Comment by vitvly** [comment]
@flexsurfer that is fine. Closing this one to be superseded by a new PR once https://github.com/status-im/status-go/pull/4020/ is ready.

**Pull request closed without merging**
