### PR TITLE
Update saucelabs endpoint

### PR DESCRIPTION
**Pull request by Serhy**
We migrated to EU datacenter in saucelabs and needed to make some changes in code.
Sorry for awkward package in requirements, as a quick fix it should be OK. There is just no updated version on sauceclient package in PyPI yet which has support of different endpoints.

### CODE REVIEW

**Review by jakubgs — APPROVED** [review]
Nice, closer to our own CI servers.

**Comment by churik** [comment]
🎉

**Review by churik — APPROVED** [review]

**Comment by Serhy** [comment]
@jakubgs e2e-tests PR builds are failing because it doesn't see an apk. There was a same function pulling PR build to upload to saucelabs (and everything were working fine) but now it's ```FileNotFoundError: [Errno 2] No such file or directory: '11624.apk'``` 
https://ci.status.im/job/end-to-end-tests/job/status-app-prs/1570/console

Can't understand why. Do you have an idea?

**Comment by jakubgs** [comment]
@Serhy well, here's why. The `ci/Jenkinsfile.android` calls `uploadToSauceLabs`:
https://github.com/status-im/status-react/blob/d68f7679df50ac28402c4a261a829f78a1f14196/ci/Jenkinsfile.android#L106-L108
Which in turn calls Fastlane:
https://github.com/status-im/status-react-jenkins/blob/3acdd1ea56c7e100a4bbeb33b5bcb0d1d9e9a457/vars/android.groovy#L131
Which in turn uses `curl` to upload it to SauceLabs:
https://github.com/status-im/status-react/blob/d68f7679df50ac28402c4a261a829f78a1f14196/fastlane/Fastfile#L60-L62
See anything wrong there?

**Comment by Serhy** [comment]
Yes I see. Fixed in https://github.com/status-im/status-react/pull/11628

**Pull request merged**
