### PR TITLE
Improve log format in StatusIm.log and add timestamps

### PR DESCRIPTION
**Pull request by pedropombeiro**
[comment]: # (Please replace ... with your information. Remove < and >)
[comment]: # (To auto-close issue on merge, please insert the related issue number after # i.e fixes #566)

This PR adds timestamps to the desktop log, organizes logs into columns, and removes extraneous line feeds, making the log much more readable.

status: ready

### CODE REVIEW

**Review by maxhora — APPROVED** [review]
Nice! 👍

**Comment by chadyj** [comment]
Woah fantastic @PombeirP!

Will be even better once someone picks up https://github.com/status-im/status-react/issues/5848

**Review by vkjr — APPROVED** [review]

**Comment by lukaszfryc** [comment]
Here is how it looks now: 

```
11:37:23.678- D -UIManager::manageChildren for containerReactTag:  103  moveFromIndicies:  ()  moveToIndices:  ()  addChildReactTags:  (59, 60, 102)  addAtIndices:  (0, 1, 2)  removeAtIndices:  ()
11:37:23.678- D -UIManager::manageChildren container->childItems().size():  0
11:37:23.678- D -UIManager::manageChildren container->childItems():  ()
```

@PombeirP maybe you want to add spaces between timestamp, log level and message? https://github.com/status-im/status-react/pull/5853/files#diff-b3598ffec8b87686b94e17539c68ea4aR347



<blockquote><div> GitHub</div><div><strong><a href="https://github.com/status-im/status-react/pull/5853">Improve log format in StatusIm.log and add timestamps by PombeirP · Pull Request #5853 · status-im/status-react</a></strong></div><div>This PR adds timestamps to the desktop log, organizes logs into columns, and removes extraneous line feeds, making the log much more readable.
status: ready</div></blockquote>

**Comment by pedropombeiro** [comment]
Noticed that the merge script was broken when the local develop was out of sync with remote develop. If you told it to reset the branch, it would reset the local PR branch instead of the local develop branch. Fixed and tested it in this PR submission.

**Pull request merged**
