### PR TITLE
Show mainnet warning

### LINKED ISSUE #4718: Inform beta users that mainnet is default
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a beta user, I want to be informed of new default network behavior so that I'm aware of the changes.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

Users upgrading to beta might not be aware that Mainnet is the default network which could cause confusion, or even worse. To be clear about significant changes we should alert users when installing the beta clearly informing them that the default network in now mainnet. 

### Solution
Similar to previous upgrade alerts we have used, let's show an alert:

> Hello
> Thanks for choosing Status! We are now in Beta, which means new installs are automatically connected to the Mainnet. If you upgraded, you may still need to switch networks, which you can do easily by navigating to your Profile -> Advanced Mode -> Switch Developer Mode on -> Choose your network. Now just have fun! Browse DApps, exchange assets, start your own #chats, and message your friends, all from the world's first decentralised, mobile client for Ethereum. 
>
>Please note that this is a beta release and we advise you that using this app should be done for testing purposes only and you assume the full responsibility for all risks concerning your data and funds.

### PR DESCRIPTION
**Pull request by dmitryn**
fixes #4718

### Summary:

Show "mainnet is default" popup after login. Since we want to show popup only once, i've added flag `mainnet-warning-shown?` to account realm record.

### Testing notes (optional):

Please check that popup gets shown only once after installation for both new and recovered accounts.

status: ready

### CODE REVIEW

**Review by janherich — APPROVED** [review]

**Review by rasom — APPROVED** [review]

**Review by mandrigin — APPROVED** [review]

**Comment by asemiankevich** [comment]
@dmitryn keyboard hides the message on iOS and tapping outside the warning does not close the keyboard, neither scrolling is working. Can't read the full warning as result. iPhone 7, iOS 11.4

image

**Comment by dmitryn** [comment]
@asemiankevich didn't have this as i'm using Simulator (don't have real iOS device). But i fixed this by moving alert to after PN notifications alert get shown. Please check.

**Comment by asemiankevich** [comment]
on it

**Comment by asemiankevich** [comment]
warning is not shown when i upgrade

1. create account or recover it on testflight build
2. upgrade to current pr
3. check the warning

**Comment by dmitryn** [comment]
@asemiankevich fixed. Please take a look.

**Comment by asemiankevich** [comment]
for new accounts on ios. recovered looks good.
image

**Comment by dmitryn** [comment]
@asemiankevich i have disabled showing this warning on this screen. Please check again.

**Comment by asemiankevich** [comment]
image

Steps:

- install build
- recover any known account
- logout
- tap create new account
- wait for a while staying on this screen

**Comment by dmitryn** [comment]
Error seems unrelated to PR changes, here is the trace:
```
06-21 17:14:03.551 13282 13362 D ReactNativeJS: DEBUG [status-im.utils.handlers:38] - Handling re-frame event:  :update-transactions
06-21 17:14:03.561 13282 13362 I ReactNativeJS: PRETTY PRINTED EXCEPTION
06-21 17:14:03.561 13282 13362 I ReactNativeJS:
06-21 17:14:03.561 13282 13362 I ReactNativeJS: ***
06-21 17:14:03.561 13282 13362 I ReactNativeJS: NAME: "Error"
06-21 17:14:03.561 13282 13362 I ReactNativeJS: MESSAGE: No matching clause:
06-21 17:14:03.561 13282 13362 I ReactNativeJS:
06-21 17:14:03.561 13282 13362 I ReactNativeJS: status_im$utils$transactions$get_api_network_subdomain
06-21 17:14:03.561 13282 13362 I ReactNativeJS: status_im$utils$transactions$get_transaction_url
06-21 17:14:03.561 13282 13362 I ReactNativeJS: status_im$utils$transactions$get_transactions
06-21 17:14:03.561 13282 13362 I ReactNativeJS:
06-21 17:14:03.561 13282 13362 I ReactNativeJS: re_frame$fx$do_fx_after
06-21 17:14:03.561 13282 13362 I ReactNativeJS: re_frame$interceptor$invoke_interceptor_fn
06-21 17:14:03.561 13282 13362 I ReactNativeJS: re_frame$interceptor$invoke_interceptors
06-21 17:14:03.561 13282 13362 I ReactNativeJS: re_frame$interceptor$execute
06-21 17:14:03.561 13282 13362 I ReactNativeJS: re_frame$events$handle
06-21 17:14:03.561 13282 13362 I ReactNativeJS: re_frame$router$IEventQueue$_process_1st_event_in_queue$arity$1
06-21 17:14:03.561 13282 13362 I ReactNativeJS: re_frame$router$_process_1st_event_in_queue
06-21 17:14:03.561 13282 13362 I ReactNativeJS: re_frame$router$IEventQueue$_run_queue$arity$1
06-21 17:14:03.561 13282 13362 I ReactNativeJS: re_frame$router$_run_queue
06-21 17:14:03.561 13282 13362 I ReactNativeJS:
06-21 17:14:03.561 13282 13362 I ReactNativeJS: re_frame$router$IEventQueue$_fsm_trigger$arity$3
06-21 17:14:03.561 13282 13362 I ReactNativeJS: re_frame$router$_fsm_trigger
06-21 17:14:03.561 13282 13362 I ReactNativeJS:
06-21 17:14:03.561 13282 13362 I ReactNativeJS: http://10.0.2.2:8081/index.android.delta?platform=android&dev=true&minify=false:3072:26
06-21 17:14:03.561 13282 13362 I ReactNativeJS: _callTimer@http://10.0.2.2:8081/index.android.delta?platform=android&dev=true&minify=false:2989:17
06-21 17:14:03.561 13282 13362 I ReactNativeJS: callTimers@http://10.0.2.2:8081/index.android.delta?platform=android&dev=true&minify=false:3196:19
06-21 17:14:03.561 13282 13362 I ReactNativeJS: __callFunction@http://10.0.2.2:8081/index.android.delta?platform=android&dev=true&minify=false:2600:49
06-21 17:14:03.561 13282 13362 I ReactNativeJS: http://10.0.2.2:8081/index.android.delta?platform=android&dev=true&minify=false:2368:31
06-21 17:14:03.561 13282 13362 I ReactNativeJS: __guardSafe@http://10.0.2.2:8081/index.android.delta?platform=android&dev=true&minify=false:2562:13
06-21 17:14:03.561 13282 13362 I ReactNativeJS: callFunctionReturnFlushedQueue@http://10.0.2.2:8081/index.android.delta?platform=android&dev=true&minify=false:2367:21
06-21 17:14:03.561 13282 13362 I ReactNativeJS: callFunctionReturnFlushedQueue@[native code]
06-21 17:14:03.561 13282 13362 I ReactNativeJS:
06-21 17:14:03.561 13282 13362 I ReactNativeJS: ***
06-21 17:14:03.561 13282 13362 E ReactNativeJS: No matching clause:
06-21 17:14:03.742 13282 13362 D ReactNativeJS: DEBUG [status-im.utils.handlers:38] - Handling re-frame event:  :show-tab-bar
06-21 17:15:02.282 13282 13362 I ReactNativeJS: INFO [status-im.utils.ethereum.core:133] - {"meta":null,"cnt":2,"arr":[{"ns":null,"name":"code","fqn":"code","_hash":null,"cljs$lang$protocol_mask$partition0$":2153775105,"cljs$lang$protocol_mask$partition1$":4096},-32700,{"ns":null,"name":"message","fqn":"message","_hash":null,"cljs$lang$protocol_mask$partition0$":2153775105,"cljs$lang$protocol_mask$partition1$":4096},"504 Gateway Timeout <html>\r\n<head><title>504 Gateway Time-out</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>504 Gateway Time-out</h1></center>\r\n</body>\r\n</html>\r\n"],"__hash":null,"cljs$lang$protocol_mask$partition0$":16647951,"cljs$lang$protocol_mask$partition1$":139268}

```

It fails here https://github.com/status-im/status-react/blob/develop/src/status_im/utils/transactions.cljs#L6

/cc @goranjovic 

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/status-im/status-react">status-im/status-react</a></strong></div><div>status-react - a free (libre) open source, mobile OS for Ethereum</div></blockquote>

EDIT:
It runs `update-transactions` after old account logged out and new account is not yet created. Maybe we need to think of putting `update-transactions` requests into sort of queue (in case when we have many of them queued) and clear that queue on logout.

**Comment by asemiankevich** [comment]
lets merge it , looks good.

1. warning shown when I create the account in this build
2. also shown when I recover account in this build
3. shown when I create the account in release and upgrade to this build
4. shown when I recover account in release and upgrade to this build

this should be sufficent to merge based on initial requirements described in issue

**Pull request merged**
