### PR TITLE
[WIP] #2998: Allow both release and develop version to coexist

### LINKED ISSUE #2998: Allow both release and develop version to coexist
### User Story

As a developer, I want to have both release and developer version running at the same time on android.

### Description

Currently both versions share same identifier preventing to keep the released version installed.

*Type*: Feature

### PR DESCRIPTION
**Pull request by pacamara**
Unfinished attempt at #2998: "Allow both release and develop version to coexist"
Note: currently debug build fails at runtime with 
```
bot.js loading failed
console
ReferenceError: Can't find variable: require
```

### Summary:
Allow  both release and develop version to coexist on the same Android device. The debug build has package name suffix .debug, and its name is "Status Debug".

android/app/google-services.json has been moved to android/app/src/debug and .../release. The version in release has a different package_name entry.

### Steps to test:
* Build and install release build on Android.
* Do same for the debug build.
* Verify that both builds operate independently, and the debug build appears as "Status Debug" on the device.

status: wip

### CODE REVIEW

**Comment by jeluard** [comment]
Awesome!

We might want to hook some special screens for this build too. Do you have a suggestion? It would be great to have it working on iOS too.

**Comment by pacamara** [comment]
:cool: ! No ideas about extra screens right now, will have a think...
Am not geared up for IOS development right now but that could change!

**Comment by jeluard** [comment]
@pacamara I'd like to know in the code that the app started as `debug` so that some specifics can be enabled. Sorry I was not very clear :)

**Review by jeluard — CHANGES_REQUESTED** [review]
How can we check from code which flavour is started?

**Comment by pacamara** [comment]
@jeluard Ah got it. The check should he 
```
if (BuildConfig.DEBUG) {
```
Will add some small example of this to the PR.

**Comment by jeluard** [comment]
@pacamara Thanks! Ideally this information should be available at the Clojure level, agnostic of the platform (so maybe always release on iOS for now)

**Comment by pacamara** [comment]
@jeluard Done! Now displays a debug-specific toast on startup. Also added an unrelated needed change to the run-android target in Makefile for the debug build.

**Comment by jeluard** [comment]
@pacamara Thanks! Is this message something that disappears?

Also what I expect to be able to do from clojure code:

```clj
(when (config/debug?)
  ....
  )
```

Do you think there is a simple way to do that?

**Comment by pacamara** [comment]
@jeluard Yes, the toast disappears after a few seconds and doesn't need user interaction. Couldn't find a clojure equivalent that works across both platforms.

Unfortunately, with further testing I see that startup of the debug build now fails with the error message
``` 
bot.js loading failed 
console
ReferenceError: Can't find variable: require
```
Unable to fix this so far, so marking this PR as wip again :frowning_face:

**Comment by jeluard** [comment]
Weird I wonder what could cause that! Does it still work in release mode?

**Comment by pacamara** [comment]
@jeluard Yes it still works fine in release mode. I must have missed another dependency on the package name at the clojure level?

**Comment by jeluard** [comment]
@pacamara Any luck with that? I would be thrilled to have both release and dev version on my phone :)

**Comment by pacamara** [comment]
@jeluard Sorry not so far. :frowning:  Seems this error is most often linked to failing to load the bundle file from the server. But have checked and that's not the case here. I've one more idea I'll try today, and let you know...

**Comment by pacamara** [comment]
@jeluard OK I'm defeated by this one for now. I will remove the "Fixes" from this PR so that others are not put off from attempting this bounty, perhaps someone else will have more luck! (I'll keep looking at it though...)

**Comment by flexsurfer** [comment]
@pacamara thanks for your effort, let's close it, for now, feel free to reopen or create new one, thanks

**Comment by pacamara** [comment]
@flexsurfer Sure, thanks 👍

**Pull request closed without merging**
