### PR TITLE
[Feature] Enable Test Networks by default on E2E and PR builds

### LINKED ISSUE #19347: Enable Testnet mode by default in e2e/PR builds
# Problem

In order to check wallet functionality in more effective way we need to have e2e automated tests created for that. Now our e2e tests take quite a long time, 35-40 min, and we need to avoid increasing that time as much as we can. So it would be very effective to have **Testnet mode** enabled by default in e2e builds instead of turning it on each time when running the tests.

## Acceptance Criteria
1. Open Profile
2. Click Advanced button

On **e2e and PR builds** Testnet mode toggle is turned on.
On **nightly and release builds** Testnet mode toggle is turned off

### PR DESCRIPTION
**Pull request by smohamedjavid**
fixes #19347

### Summary

This PR enables Test Networks in E2E and PR Builds by default and disables in Release/Nightly Builds.

`status-go` PR: https://github.com/status-im/status-go/pull/4971

### Platforms

- Android
- iOS

status: ready

### CODE REVIEW

**Review by qfrank — COMMENTED** [review]
we don't want enable it for local dev build? i mean no changes to `.env`? @smohamedjavid

**Comment by smohamedjavid** [comment]
> we don't want enable it for local dev build? i mean no changes to `.env`? @smohamedjavid

@qfrank - Nice to have. I made changes as per the Issue. There's no harm in enabling it on Dev builds. I will add it 👍

**Review by qfrank — APPROVED** [review]
LGTM, thank you for your PR

**Review by ulisesmac — APPROVED** [review]

**Review by jakubgs — APPROVED** [review]

**Comment by yevh-berdnyk** [comment]
Hi @smohamedjavid 
Thanks for this PR, everything looks good for me!

**Pull request merged**
