### PR TITLE
Show proper error when bio metric fails

### LINKED ISSUE #20007: Show proper error when bio metric fails
https://github.com/status-im/status-mobile/blob/f50ca4606f0e92ffc45900e468139242aa44fb3e/src/react_native/biometrics.cljs#L44

image

We have access to original error "Too many failed attempts", So I think we should show that to user instead of unknown error. 

Steps to reproduce: https://github.com/status-im/status-mobile/issues/19488

_Originally posted in https://github.com/status-im/status-mobile/issues/19989#issuecomment-2106255606_

### PR DESCRIPTION
**Pull request by Parveshdhull**
fixes https://github.com/status-im/status-mobile/issues/20007

leftover from https://github.com/status-im/status-mobile/pull/19989#issuecomment-2106255606

### Testing

PR is manually tested and safe to merge. I only added request-manual-qa to make sure error message gets double checked. `Too many attempts. Enter the password manually or try again after some time`

UPD: Adding skip-manual-qa and merging. We can always update msg if it needs to.

status: ready

### CODE REVIEW

**Review by clauxx — APPROVED** [review]
Do we need to handle the error for iOS as well?

**Comment by Parveshdhull** [comment]
> Do we need to handle the error for iOS as well?

hi @clauxx, Thank you very much for approving PR. I currently don't have access to ios device with touch-id and don't know what will be error message for ios for too many attempts. We can add for ios later.

**Comment by Parveshdhull** [comment]
@status-im/mobile-qa Please can you check failed e2e tests.

**Comment by pavloburykh** [comment]
@Parveshdhull thank you for the PR. Failed e2e are not PR related. Ready for merge.

**Pull request merged**
