### PR TITLE
fix No tabs are available in the app on Graphene OS

### LINKED ISSUE #21509: No tabs are available in the app on Graphene OS
# Bug Report

## Problem 
No tabs available on Pixel 7A, Graphene OS.

Issue is not reproducible on the same device on Android.
It was not the case for 2.30, so it is regression.

#### Expected behavior
can see tabs

#### Actual behavior
no tabs available

https://github.com/user-attachments/assets/a9d06f41-7ab4-4927-bac1-198e2ca619bb

### Reproduction

1. Install 2.31 

### Additional Information

- Status version: release 2.31 
- Operating System: **Graphene OS**
- Logcat: [logcat_no tabs.log](https://github.com/user-attachments/files/17542978/logcat_no.tabs.log)

### PR DESCRIPTION
**Pull request by Parveshdhull**
fixes https://github.com/status-im/status-mobile/issues/21509

status: WIP

### CODE REVIEW

**Comment by Parveshdhull** [comment]
Thank you, @churik, for helping me resolve this issue. Could you please attach a screenshot of the home screen and the status.log file for the build?

**Comment by churik** [comment]
image

Full logcat:  [status_no_tabs.log](https://github.com/user-attachments/files/17553832/status_no_tabs.log)


Full logs: [Status-debug-logs.zip](https://github.com/user-attachments/files/17554080/Status-debug-logs.zip)

**Comment by Parveshdhull** [comment]
Thank you very much @churik for providing logs. Please can you check if issue is fixed now?

Also most probably it will not create any regressions, but please also test https://github.com/status-im/status-mobile/issues/15164 https://github.com/status-im/status-mobile/issues/14894

**Comment by churik** [comment]
Now it is good on both devices when Testmode is off. I believe this is acceptable, we can fix Testmode banner issues separately

Xiaomi: 
IMAGE 2024-10-29 15:06:07


Graphene OS:
IMAGE 2024-10-29 15:06:10


@Parveshdhull 🥇

**Review by flexsurfer — APPROVED** [review]

**Pull request merged**
