### PR TITLE
Make the information sharing screen usable on tiny screens.

### PR DESCRIPTION
**Pull request by mandrigin**
e.g. an iPhone app on an iPad
This doesn't make it *pretty*, just usable.

### Steps to test:
- Open Status iOS on an iPad
- Expect to be able to pass the information sharing screen

status: ready

### CODE REVIEW

**Review by jeluard — COMMENTED** [review]
Doesn't that conflict with #4655 ?

**Comment by mandrigin** [comment]
@jeluard nope. restricting our app to iPhone-only won't really restring it from being installed launched on an iPad. In that case, it will appear in a tiny window in the centre of the screen. This window has exactly iPhone 4 dimensions. I tested our UI there and this was the only unusable screen I found, so I fixed that :)

**Comment by mandrigin** [comment]
*before*
simulator screen shot - ipad pro 9 7-inch - 2018-06-06 at 15 55 02

*after*
simulator screen shot - ipad pro 9 7-inch - 2018-06-06 at 17 41 15

**Comment by jeluard** [comment]
@mandrigin Right but we don't intend to support iPad anyway.
I guess it's not an intrusive change so doesn't really matter.

**Review by jeluard — APPROVED** [review]

**Review by flexsurfer — APPROVED** [review]

**Comment by lukaszfryc** [comment]
I've checked it on Android Emulator with WVGA (800x480) screen. It looks not bad. No buttons are covered: 

zrzut ekranu 2018-06-07 o 09 24 44
zrzut ekranu 2018-06-07 o 09 25 16
zrzut ekranu 2018-06-07 o 09 25 27
zrzut ekranu 2018-06-07 o 09 40 04
zrzut ekranu 2018-06-07 o 09 43 29
zrzut ekranu 2018-06-07 o 09 44 48

**Comment by chadyj** [comment]
Great changes to make things usable on an iPad!

https://github.com/status-im/status-react/issues/4662 will make it optimized :)

**Pull request merged**
