### PR TITLE
fix: Sync is hanging in "syncing devices" stage

### LINKED ISSUE #17223: Sync is hanging in "syncing devices" stage
# Bug Report

IMAGE 2023-09-08 11:38:38

## Problem 
Android won't go further after sync with latest desktop RC (0.14.0-rc.4 with go [0.166.6](https://github.com/status-im/status-go/tree/v0.166.6))

#### Expected behavior
can sync 

#### Actual behavior
sync is stuck

### Reproduction

1. Desktop: open Profile > Syncing > setup Syncing > generate QR
2. Android: Sign in > Scan QR

### Additional Information

- Status version: nightly  08.09.23
- Operating System: Android
- Logs: [Status-debug-logs.zip](https://github.com/status-im/status-mobile/files/12558011/Status-debug-logs.zip)

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by qfrank**
fixes #17223 

status: ready

### CODE REVIEW

**Review by siddarthkay — APPROVED** [review]

**Review by yqrashawn — APPROVED** [review]

**Comment by VolodLytvynenko** [comment]
Hi @qfrank thank you for PR. Did I understand correctly, that this PR does not currently resolve the syncing issue and it only resolves the problem of the app getting stuck when the 'try again' button is tapped?

However, a new issue has been introduced. After scanning the QR code on Android, the 'Syncing device' stage doesn't hang anymore, but now there's an issue where the scan section is displayed without a QR code inside the scan area after the QR code has been scanned.

### Actual result:
the scan section is displayed without a QR code inside the scan area after the QR code has been scanned. (for at least 5 seconds)


https://github.com/status-im/status-mobile/assets/52490791/b87cf2cb-b77f-46a0-acec-178a86122df6



### Expected result:
The 'Oops something went wrong'  page is shown as soon as the QR is scanned 

### Env
Desktop 0.14.0, rc4

### logs:
[android_logcat2.txt](https://github.com/status-im/status-mobile/files/12559874/android_logcat2.txt)

**Comment by churik** [comment]
For me still stuck on the same stage: 
[Status-debug-logs.zip](https://github.com/status-im/status-mobile/files/12559907/Status-debug-logs.zip)

**Comment by qfrank** [comment]
> For me still stuck on the same stage: [Status-debug-logs.zip](https://github.com/status-im/status-mobile/files/12559907/Status-debug-logs.zip)

I thought this should be fixed at least, but i missed another cert generation, will make an update soon.

**Comment by qfrank** [comment]
> Hi @qfrank thank you for PR. Did I understand correctly, that this PR does not currently resolve the syncing issue and it only resolves the problem of the app getting stuck when the 'try again' button is tapped?
> 
> However, a new issue has been introduced. After scanning the QR code on Android, the 'Syncing device' stage doesn't hang anymore, but now there's an issue where the scan section is displayed without a QR code inside the scan area after the QR code has been scanned.
> 
> ### Actual result:
> the scan section is displayed without a QR code inside the scan area after the QR code has been scanned. (for at least 5 seconds)
> 
>  scan3.mp4 
> ### Expected result:
> The 'Oops something went wrong' page is shown as soon as the QR is scanned
> 
> ### Env
> Desktop 0.14.0, rc4
> 
> ### logs:
> [android_logcat2.txt](https://github.com/status-im/status-mobile/files/12559874/android_logcat2.txt)

so retry connections doesn't solve "no route to host", any idea on this? @Samyoul @cammellos

**Comment by qfrank** [comment]
> For me still stuck on the same stage: [Status-debug-logs.zip](https://github.com/status-im/status-mobile/files/12559907/Status-debug-logs.zip)

Apologies for the inconvenience. Please try again when you have a moment. @churik

**Comment by qfrank** [comment]
> Hi @qfrank thank you for PR. Did I understand correctly, that this PR does not currently resolve the syncing issue and it only resolves the problem of the app getting stuck when the 'try again' button is tapped?
> 
> However, a new issue has been introduced. After scanning the QR code on Android, the 'Syncing device' stage doesn't hang anymore, but now there's an issue where the scan section is displayed without a QR code inside the scan area after the QR code has been scanned.
> 
> ### Actual result:
> the scan section is displayed without a QR code inside the scan area after the QR code has been scanned. (for at least 5 seconds)
> 
>  scan3.mp4 
> ### Expected result:
> The 'Oops something went wrong' page is shown as soon as the QR is scanned
> 
> ### Env
> Desktop 0.14.0, rc4
> 
> ### logs:
> [android_logcat2.txt](https://github.com/status-im/status-mobile/files/12559874/android_logcat2.txt)

Looks like "retry connections" not work for @VolodLytvynenko (no route to host), any ideas(i've checked network detail from @VolodLytvynenko [before](https://github.com/status-im/status-mobile/pull/17166#issuecomment-1706535241), seems good to me)? cc @Samyoul @cammellos

**Comment by churik** [comment]
@qfrank still the same unfortunately
[Status-debug-logs.zip](https://github.com/status-im/status-mobile/files/12560647/Status-debug-logs.zip)

**Comment by qfrank** [comment]
> @qfrank still the same unfortunately [Status-debug-logs.zip](https://github.com/status-im/status-mobile/files/12560647/Status-debug-logs.zip)

Upon further consideration, I believe the desktop application will also need to be updated along with my status-go [PR]((https://github.com/status-im/status-go/pull/4010)) in order to fully resolve this issue. Since the desktop app plays the role of generating the certificate in this case, it seems including the changes from my PR on the desktop side as well is necessary to produce the expected behavior. @churik cc @igor-sirotin

**Comment by qfrank** [comment]
update: I've asked @saledjenic (thanks to @saledjenic !) to create a desktop PR to include my status-go PR, so you can retry cc @churik

**Comment by churik** [comment]
@qfrank @saledjenic  can you point me to the PR?

**Comment by qfrank** [comment]
@saledjenic will tag us when it's ready

> @qfrank @saledjenic can you point me to the PR?

**Comment by qfrank** [comment]
Regarding to @VolodLytvynenko 's issue (different issue from @churik faced, `no route to host ...`) , i still have no idea.
Something i checked with @VolodLytvynenko are following:
can not ping the target ip(192.168.0.103 , desktop) with:
```
adb shell
ping 192.168.0.103
```
image

the result of `ifconfig` LGTM, and android device can pass ping test to gateway:
image

cc @cammellos @Samyoul

**Comment by saledjenic** [comment]
@churik @qfrank here is a PR:
https://github.com/status-im/status-desktop/pull/12117

**Comment by churik** [comment]
@qfrank @saledjenic 

tested builds with IOS and Android, works fine now. 
Let's merge in to our `develop` and start release cut branch on mobile side.

@saledjenic can you please make sure this commit will be included to 0.14? 

Thank you!

**Comment by saledjenic** [comment]
> @saledjenic can you please make sure this commit will be included to 0.14?

@churik when desktop app QAs confirm we can merge the status-go PR to status-go develop branch, I will ensure that the desktop app master includes it.

@churik I guess you meant to 0.15.0? That should be the next desktop app release version.

**Comment by saledjenic** [comment]
@qfrank @churik check this [comment](https://github.com/status-im/status-desktop/pull/12117#issuecomment-1713601305) please.

**Comment by churik** [comment]
@saledjenic I meant 0.14, which is in RC now, otherwise we got incompatible builds from mobile and desktop.

Thank you!

**Comment by Samyoul** [comment]
> Regarding to @VolodLytvynenko 's issue (different issue from @churik faced, `no route to host ...`) , i still have no idea. Something i checked with @VolodLytvynenko are following: can not ping the target ip(192.168.0.103 , desktop) with:
> 
> ```
> adb shell
> ping 192.168.0.103
> ```
> 
> image
> the result of `ifconfig` LGTM, and android device can pass ping test to gateway: image
> 
> cc @cammellos @Samyoul

Hmm, that is frustrating @qfrank. We need to build out some better debugging tools for these kind of issues. I opened 
an issue for this last month https://github.com/status-im/status-go/issues/3885, and I have some work on this issue. Obviously this doesn't resolve the problem.

I notice that the desktop is pinging `192.168.0.103` and an error returns from `192.168.0.106`. Which seems to suggest that that `192.168.0.106` is the IP address of the desktop installation.

@VolodLytvynenko which device is producing the QR code, desktop or mobile? Do you know if the android device can ping `192.168.0.106`?

**Comment by Samyoul** [comment]
@VolodLytvynenko I can see in this comment https://github.com/status-im/status-mobile/pull/17226#issuecomment-1711612746 it is the desktop that generates the QR code.

**Comment by qfrank** [comment]
> > Regarding to @VolodLytvynenko 's issue (different issue from @churik faced, `no route to host ...`) , i still have no idea. Something i checked with @VolodLytvynenko are following: can not ping the target ip(192.168.0.103 , desktop) with:
> > ```
> > adb shell
> > ping 192.168.0.103
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > image
> > the result of `ifconfig` LGTM, and android device can pass ping test to gateway: image
> > cc @cammellos @Samyoul
> 
> Hmm, that is frustrating @qfrank. We need to build out some better debugging tools for these kind of issues. I opened an issue for this last month [status-im/status-go#3885](https://github.com/status-im/status-go/issues/3885), and I have some work on this issue. Obviously this doesn't resolve the problem.
> 
> I notice that the desktop is pinging `192.168.0.103` and an error returns from `192.168.0.106`. Which seems to suggest that that `192.168.0.106` is the IP address of the desktop installation.
> 
> @VolodLytvynenko which device is producing the QR code, desktop or mobile? Do you know if the android device can ping `192.168.0.106`?

Hi @Samyoul , thanks for your reply, FYI, 
image

**Pull request merged**
