### PR TITLE
Make whisper interchangeability Rinkeby & Mainnet & Ropsten

### PR DESCRIPTION
**Pull request by mandrigin**
### How to Test
- have 2 clients, one on Mainnet, one on Rinkeby
- try to do a 1:1 conversation, a public chat
- messages should go through

status: ready

### CODE REVIEW

**Comment by mandrigin** [comment]
https://ci.status.im/job/status-react/job/parametrized_build/745/console

<blockquote><div><strong><a href="https://ci.status.im/job/status-react/job/parametrized_build/745/console">status-react » parametrized_build #745 Console [Jenkins]</a></strong></div></blockquote>

**Comment by annadanchenko** [comment]
on Android build on real Galaxy S6, Android 6.0.1, after creating account and trying to login, popup is shown and Status is stopped:
```
java.lang.RuntimeException: Could not invoke Status.parseJail
```

on iOS can create account and login

**Comment by annadanchenko** [comment]
on iOs - can send messages in 1:1 chat  and public chat to user on Rinkeby while I’m on Rinkeby, Mainnet or Ropsten. Can get pn if app is on background, can send test eth in Rinkeby and ropsten in chat, I think it’s enough

**Review by flexsurfer — APPROVED** [review]

**Comment by mandrigin** [comment]
it's already merged to the release build, I will think about integrating it to `develop` a bit later...
let's keep it open for a while

**Comment by mandrigin** [comment]
not needed anymore

**Pull request closed without merging**
