### PR TITLE
[Fix] Community Context for Mention or Replies Notification in Activi…

### LINKED ISSUE #15233: Community Context is missing on Mentions and Replies notifications in Activity Center
## Bug Report

The community name and community image (if the community has one) are missing in Mentions/Replies Notifications in Activity Center

AC BUG

### Expected behaviour

If the mention or replies is from the community, the Activity Center Notification should display the community name along with the community image in the context.

Screenshot 2023-03-02 at 7 35 50 PM

### Reproduction

1) Open Status
2) User `A` got mentioned by User `B` in a community
3) User `A` receives a notification in Activity Center

### Additional Information

- Status Version: nightly 
- Operating System: Android, iOS

### Developer Notes:

This requires an update in `status-go`.

### PR DESCRIPTION
**Pull request by smohamedjavid**
fixes #15233 

`status-go` PR: https://github.com/status-im/status-go/pull/3250

status: ready

### CODE REVIEW

**Review by ilmotta — APPROVED** [review]
@smohamedjavid, I had to dig a bit to find which status-go PR is related to the commit revision present in `status-go-version.json` (https://github.com/status-im/status-go/pull/3250). LGTM

For reference in case you don't know: you can also run `scripts/update-status-go.sh $branch_name` pointing to a branch name, this can be helpful for reviewers to get an idea of which branch is related to the commit revision in `status-go-version.json`.

**Comment by smohamedjavid** [comment]
> @smohamedjavid, I had to dig a bit to find which status-go PR is related to the commit revision present in `status-go-version.json` ([status-im/status-go#3250](https://github.com/status-im/status-go/pull/3250)). LGTM
> 
> For reference in case you don't know: you can also run `scripts/update-status-go.sh $branch_name` pointing to a branch name, this can be helpful for reviewers to get an idea of which branch is related to the commit revision in `status-go-version.json`.

My bad. I updated the PR description with the `status-go` PR link. 

Thanks for sharing the info! 😄

**Comment by pavloburykh** [comment]
@smohamedjavid thanx for the PR. Could you please rebase it to the latest develop, cause there are some new commits with fixes/refactoring related to AC. I would like to test current PR with those commits included. Thanx.

**Comment by pavloburykh** [comment]
@smohamedjavid thanx for the fix. Tested, ready to be merged.

**Pull request merged**
