### PR TITLE
Fix race condition on sending messages

### LINKED ISSUE #15385: Some messages get stuck in "sending" status for sender despite they have been sent/delivered to receiver
I faced the issue in all kind of chats but seems like it is easier to reproduce in community channels. 

**Preconditions:** User A - sender, User B - receiver

**Steps:**

1. Try sending several messages by User A to User B until some of the messages gets stuck in "sending" status
2. See if such message has been received by User B

**Actual result:** Some messages get stuck in "sending" status for sender despite they have been sent/delivered to receiver

[User_A_sender_logs.zip](https://github.com/status-im/status-mobile/files/10990054/User_A_sender_logs.zip)
[User_B_receiver_logs.zip](https://github.com/status-im/status-mobile/files/10990055/User_B_receiver_logs.zip)

https://user-images.githubusercontent.com/97245802/225603454-6d3fcab9-bd92-4620-8aa4-348220137540.mp4

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by cammellos**
Fixes: #15385

https://github.com/status-im/status-go/pull/3611

### CODE REVIEW

**Comment by cammellos** [comment]
Still something to fix :(

**Review by flexsurfer — APPROVED** [review]

**Review by jo-mut — APPROVED** [review]

**Review by qfrank — APPROVED** [review]

**Review by erikseppanen — APPROVED** [review]

**Comment by pavloburykh** [comment]
@cammellos thanx a lot for the fix! Currently message statuses work almost as expected. Please, take a look at the issue below. 

### ISSUE 1 Messages change status from sent to sending after opening community channel from Shell

**Preconditions:** User A and User B are members of the same community

**Steps:** 

1. User A sends messages in community channel
2. Wait until messages change status to "Sent"
3. User A taps Jump-to button to enter Shell screen
4. User A goes back to community channel from Shell screen
5. Pay attention at status of the last messages that have been sent by User A

**Actual result:** some messages changed status from "Sent" to "Sending". 


https://github.com/status-im/status-mobile/assets/97245802/c826a3e7-d607-4e7b-95f2-da307905a1ab

[UserA_sender.zip](https://github.com/status-im/status-mobile/files/11787705/UserA_sender.zip)
[UserB_receiver.zip](https://github.com/status-im/status-mobile/files/11787707/UserB_receiver.zip)

**Comment by cammellos** [comment]
@pavloburykh thank you, looking into it

**Comment by pavloburykh** [comment]
> ISSUE 1 Messages change status from sent to sending after opening community channel from Shell

@cammellos small clarification: bug happens not only in case of going back to channel from Shell screen but also in case of re-entering channel from community screen: 

1. User A sends message
2. User A taps Back button/or system back button (community screen is opened)
3. User A re-enters channel

**Comment by cammellos** [comment]
@pavloburykh thanks, I figured out the root issue, I'll be fixing it today.

Thank you!

**Comment by cammellos** [comment]
@pavloburykh it should be fixed now, would you mind testing it again? (only for new messages, old messages will still show as pending if sent with the old build)

Thanks!

**Comment by pavloburykh** [comment]
> @pavloburykh it should be fixed now, would you mind testing it again? (only for new messages, old messages will still show as pending if sent with the old build)
> 
> Thanks!

Thanx @cammellos! Those issues are fixed. Please take a look at another issue.


### ISSUE 2 Messages are displayed in "Sent" status when sent from offline [IOS]

Reproducing on IOS 14.1, iPhone X

Preconditions: User A - sender IOS, User B - receiver any other device. 

**Steps:**

1. User A enables Flight mode
2. User A starts sending messages in channel or chat
3. Observe the status of the sent messages

**Actual result:** 

- Messages are displayed in "sent" status. After chat re-opening part of messages change status to "sending", part remains as "sent'
- After coming back online part of the messages that were sent from offline are not delivered to receiver. @cammellos regarding this behaviour I am not sure if it is PR related or related to our global problem of data delivery. 

You can observe described above behaviour on video below:

https://github.com/status-im/status-mobile/assets/97245802/7d3d6bbe-d0dc-4191-a6ae-9a424daecc9c

photo_2023-06-21 13 59 22

[Android_receiver.zip](https://github.com/status-im/status-mobile/files/11816723/Android_receiver.zip)
[IOS_sender.zip](https://github.com/status-im/status-mobile/files/11816736/IOS_sender.zip)

@cammellos please, let me know if you consider this issue better to be fixed in followup.

**Comment by pavloburykh** [comment]
@cammellos feel free to ping me up when PR is ready for re-test. Thank you!

**Comment by pavloburykh** [comment]
Discussed in DM with @cammellos : [ISSUE 2](https://github.com/status-im/status-mobile/pull/16260#issuecomment-1600634581) is a known bug. 

According to @cammellos :

> "it's because basically the "sent" confirmation is whether the message has left our device
not whether the other end has received it. When you cut the connection it takes some time for the system to realize that the connection is lost. During that time, you can still write to the socket, and it won't throw an error 
the way we fixed it in waku-1, was to receive a confirmation from the next hop". 

PR is ready for merge.

**Pull request merged**
