### PR TITLE
[TEST] set proxy to test

### PR DESCRIPTION
**Pull request by cammellos**
do not merge

### CODE REVIEW

**Comment by churik** [comment]
After 1h of testing (3 people involved):
randomly still seeing provider is down;
routes can stop building randomly.

related log entries:
1)
`
ERROR[08-12|12:59:43.206|github.com/status-im/status-go/protocol/communities/manager.go:677]                                                       failed to get owner                      error="test.api.status.im.error: context deadline exceeded, test.api.status.im.error: context deadline exceeded, optimism-archival.rpc.grove.city.error: context deadline exceeded, optimism-mainnet.infura.io.error: context deadline exceeded"`

2)

`INFO [08-12|13:55:04.475|github.com/status-im/status-go/services/wallet/async/async.go:172]                                                        async.Command failed                     error="test.api.status.im.error: context canceled, test.api.status.im.error: context canceled, eth-archival.rpc.grove.city.error: context canceled" d.error="test.api.status.im.error: Post \"https://test.api.status.im/grove/ethereum/mainnet/\": dial tcp: lookup test.api.status.im: no such host, test.api.status.im.error: Post \"https://test.api.status.im/infura/ethereum/mainnet/\": dial tcp: lookup test.api.status.im: no such host, eth-archival.rpc.grove.city.error: Post \"https://eth-archival.rpc.grove.city/v1/1fec70c0d1247dc818107ac7\": dial tcp: lookup eth-archival.rpc.grove.city: no such host, mainnet.infura.io.error: Post \"https://mainnet.infura.io/v3/40ec14d9d9384d52b7fbcfecdde4e2c0\": dial tcp: lookup mainnet.infura.io: no such host" group=finiteGroup`

3)
`DEBUG[08-12|13:55:04.685|github.com/status-im/status-go/services/wallet/async/async.go:282]                                                        ErrorCounter setError                    msg=transfersCommand err="test.api.status.im.error: hystrix: circuit open, test.api.status.im.error: hystrix: circuit open, eth-archival.rpc.grove.city.error: Post \"https://eth-archival.rpc.grove.city/v1/1fec70c0d1247dc818107ac7\": dial tcp: lookup eth-archival.rpc.grove.city: no such host, mainnet.infura.io.error: Post \"https://mainnet.infura.io/v3/40ec14d9d9384d52b7fbcfecdde4e2c0\": dial tcp: lookup mainnet.infura.io: no such host" cnt=2
`

Video: 

https://github.com/user-attachments/assets/b76cbbc7-8864-451e-95f8-17f8a50a9442

Full logs from this time:
[logs (113).zip](https://github.com/user-attachments/files/16587998/logs.113.zip)

**Comment by churik** [comment]
`ERROR[08-13|13:43:25.346|github.com/status-im/status-go/services/wallet/transfer/commands_sequential.go:1286]                                      getHeadBlockNumber                       error="test.api.status.im.error: context deadline exceeded, test.api.status.im.error: context deadline exceeded, arbitrum-one.rpc.grove.city.error: context deadline exceeded, arbitrum-mainnet.infura.io.error: context deadline exceeded"
`
right after changing to mainnet - almost constant provider is down for all 3 networks.

Full log: 
[logs (114).zip](https://github.com/user-attachments/files/16600498/logs.114.zip)

**Comment by cammellos** [comment]
looks like this is not hitting the proxy maybe? can someone confirm @Samyoul @alaibe @dlipicar ?

**Comment by pavloburykh** [comment]
### Zero balance on IOS while user is online

[zero_balance.zip](https://github.com/user-attachments/files/16600864/zero_balance.zip)

photo_2024-08-13 17 10 23

https://github.com/user-attachments/assets/201feae0-c765-4a5b-94da-f3a17dda75ef

**Comment by churik** [comment]
another observation:
the constant  "Provider is down" is reproduced on IOS, but not on Android. I was able to see it on Android once, but on IOS it is almost constant,
Another thing - on Android the routes building is extremely slow  (sometimes may take > 1 min), but that might be the regression of the other PR
[Status-debug-logs.zip](https://github.com/user-attachments/files/16600928/Status-debug-logs.zip)

**Comment by pavloburykh** [comment]
### Routes still randomly not found

As you can see on the video the same route (Mainnet - Arb) cannot be found at some moment and is found after couple of tries

[routes_not_found_andr.zip](https://github.com/user-attachments/files/16601182/routes_not_found_andr.zip)

https://github.com/user-attachments/assets/22d5bdda-d76f-4b20-afce-3c5e28f9b605

**Pull request closed without merging**
