### PR TITLE
Profile validations (#235)

### PR DESCRIPTION
**Pull request by alwx**
I've added spec validations to profile — now it is impossible to use names like "wallet" and "console", there is also a check for validity of email.

This task also includes small fixes for `status-im.components.text-field.view`: it now sets and uses `default-value` instead of just `value` and don't re-render the component each time we change its text.

### CODE REVIEW

**Comment by rasom** [comment]
There are different options... Should we check `wallet`/`console` for Cyrillic symbols?

**Comment by jarradh** [comment]
yes probably a good idea to find unicode variants, also uppercase i ( I ) for L as well

**Comment by alwx** [comment]
Done! I've decided to use homoglyph-search (https://github.com/codebox/homoglyph) instead of simple regular expressions to exclude all possible options. For example, now it is also impossible to use names like `Cønsole`, `Wa11et` or `c0nsóle` and also some crazy similarities like words with greek A letter.

**Comment by jarradh** [comment]
wow thats really cool! nice find!

**Comment by rasom** [comment]
I used uppercase i ( I ) as @jarradh described:

**Comment by rasom** [comment]
Got this error on android:

ezgif-682233065

**Comment by alwx** [comment]
@rasom fixed
there was the issue with `homoglyph-search` and also small lowercase problem in my code. now everything is fine

**Pull request merged**
