### PR TITLE
[#12332] Shown PNs on message with mention in community chats (iOS)

### LINKED ISSUE #12332: No redirect to chat when receive PN with mention from community (Android) and no PN at all on IOS
# Bug Report

## Problem 
When receive mention in community channel:
- on Android: PN is received, when tapping - redirect to "Browse" popup instead of channel
- on IOS: no PN at all

#### Expected behavior
- on Android: redirect to community channel after tap
- on IOS: PN

#### Actual behavior
IMAGE 2021-07-21 15:39:42

### Reproduction

1) User A: create a community, invite User B, create a channel
2) User B: join community
3) User A: send in channel message with User B mention

### Additional Information

- Status version: nightly 21/07/21
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by rasom**
fixes #12332 partially

This bug was also partially reproducible for public chats. If user just joined a new pub chat and then put app into background PNs wouldn't be shown until next relogin.
 
Currently there is no proper redirection to pubcaht/community chat on pressing PN, this will be handled separately. 

status: ready

### CODE REVIEW

**Review by bitgamma — APPROVED** [review]

**Comment by qoqobolo** [comment]
@rasom 
#### ISSUE 1: Can't receive PNs for mentions in community  until relogin

_**Steps:**_

Device1:
1. Join community
2. Put the app into background 

Device2:
1. Mention Device1 in community

Note: everything is fine with mentions in public chat
___
Edited: The issue is relevant for WiFi as well

**Comment by rasom** [comment]
@qoqobolo hopefully that's due to this mess
Screenshot 2021-09-01 at 14 41 07

**Comment by qoqobolo** [comment]
@rasom ugh.. okay. Will wait for the ios build and retest it.
Also, the e2e didn't seem to run. Will do it manually.

**Comment by rasom** [comment]
@qoqobolo I definitely can reproduce the issue though

**Comment by rasom** [comment]
@qoqobolo ok so... if I create a new community chat then I will receive a new mention without relogin. But when I'm invited to community, then pn is received only after religion... I tested only the first case, that's why I was under impression that it works, looking into this now...

**Comment by qoqobolo** [comment]
@rasom thanks!

**Comment by rasom** [comment]
@qoqobolo, just pushed another commit which should fix issue 1

**Pull request merged**
