### PR TITLE
Obscure CreateAccount result to put into the log; .re-natal config updated.

### LINKED ISSUE #5816: Recovery phrase is visible in logs
### Description

*Type*: Bug
*Summary*: `RCTStatus::createAccount CreateAccount` and  `RCTStatus::recoverAccount` in `StatusIm.log` contain sensitive data - mnemonic phrase.

#### Expected behavior
no mnemonic pharse is shown

#### Actual behavior
```
{"address":"...","pubkey":"...","mnemonic":"......","error":""}
```

### Reproduction

- Open Status
- Create one account
- Recover another account
- Open `StatusIm.log` and search for `RCTStatus::recoverAccount RecoverAccount result` and for `RCTStatus::createAccount CreateAccount result:`

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: nightly 12/09/18
* Operating System: Mac Os X high Sierra

### PR DESCRIPTION
**Pull request by maxhora**
fixes #5816

### Summary:

Don't log CreateAccount result details #5816;
Update .re-natal config with new JS modules

status: ready

CreateAccount output to be put into the log file changed to:

```
call of RCTStatus::createAccount with param callbackId:  2699
RCTStatus::createAccount CreateAccount result:  "Success"
```

### CODE REVIEW

**Review by vitvly — CHANGES_REQUESTED** [review]
The `obscuredResult` change should also be applied to `RCTStatus::recoverAccount` method.

**Review by vkjr — APPROVED** [review]

**Comment by maxhora** [comment]
@siphiuel it looks like RecoverAccount returns only:

```
address, pubKey, nil
```

https://github.com/status-im/status-go/blob/develop/account/accounts.go#L156

Going to check others methods

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/status-im/status-go">status-im/status-go</a></strong></div><div>The Status module that consumes go-ethereum. Contribute to status-im/status-go development by creating an account on GitHub.</div></blockquote>

**Comment by vitvly** [comment]
@MaxRis  this is an internal method reference, the one that is called via `RCTStatus` module is this: https://github.com/status-im/status-go/blob/5b98b8831b63ef6b79635d9df1bc8291ed47dfd5/lib/library.go#L157

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/status-im/status-go">status-im/status-go</a></strong></div><div>The Status module that consumes go-ethereum. Contribute to status-im/status-go development by creating an account on GitHub.</div></blockquote>

This one returns `mnemonic`.

**Comment by pedropombeiro** [comment]
Maybe we could load the JSON into a `QJsonDocument` in https://github.com/status-im/status-react/blob/develop/modules/react-native-status/desktop/rctstatus.cpp#L157 to clean up the `mnemonic` field before converting it back to a string and logging it?

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/status-im/status-react">status-im/status-react</a></strong></div><div>a free (libre) open source, mobile OS for Ethereum - status-im/status-react</div></blockquote>

**Comment by maxhora** [comment]
@PombeirP yep, what I'm supposing to do, is to add new method, which will just filter out value of Error field and show it. Others data will not be in the log, so such issues will not appear anymore...

**Comment by maxhora** [comment]
@siphiuel thank you! was not able to find it

**Comment by maxhora** [comment]
@siphiuel , @PombeirP changes updated, thanks

**Review by pedropombeiro — APPROVED** [review]

**Review by vitvly — APPROVED** [review]

**Comment by churik** [comment]
Tested:
- installation
- creating new accoun
- log in with existing accoun
- recovering account

No menemonic phrase is visible in logs, so consider PR as ready to merge

**Pull request merged**
