### PR TITLE
prefill response parameters with request data

### LINKED ISSUE #417: Response parameters prefill
Prefill response parameters with data provided by request.

### PR DESCRIPTION
**Pull request by adrian-tiberius**
fixes #417

### CODE REVIEW

**Comment by rasom** [comment]
Should it already work with ETH request?

**Comment by adrian-tiberius** [comment]
Yes

**Comment by rasom** [comment]
req

I checked that project is at `a0b37c4211ed8fdfc241ee7f8217a45e80757ea9`

**Comment by jarradh** [comment]
can confirm no prefill in latest develop

**Pull request merged**
