### PR TITLE
re-enable desktop builds

### PR DESCRIPTION
**Pull request by jakubgs**
Time to re-enable desktop builds.

### CODE REVIEW

**Review by vkjr — APPROVED** [review]

**Comment by jakubgs** [comment]
Fucking windows fails with:
```
File: "/home/jenkins/workspace/status-react/combined/desktop-windows\resources\icons\" -> no files found.
```
Which is due to the backslashes being used in a Unix path, which is defined here:
https://github.com/status-im/status-react/blob/699810a54a72c905f76ddbd1655b040cde855a39/deployment/windows/nsis/setup.nsi#L638-L639
This used to work just fine...

**Comment by vkjr** [comment]
@jakubgs could this be because of `resources/icons` directory removed  from `status-react'?

**Comment by jakubgs** [comment]
Oh shit, you're right, it was, I was checking the wrong CI host(`01` instead of `03`) and saw the files there, but when I checked correctly it is indeed gone:
```
admin@linux-03.do-ams3.ci.misc:~ % ls -l /home/jenkins/workspace/status-react_prs_windows_PR-9004/resources/ 
total 20
drwxrwxr-x 2 jenkins jenkins 4096 Sep 17 08:04 config
-rw-rw-r-- 1 jenkins jenkins  205 Sep 17 08:04 default_public_chats.json
drwxrwxr-x 2 jenkins jenkins 4096 Sep 17 08:04 fonts
drwxrwxr-x 4 jenkins jenkins 4096 Sep 17 08:04 images
drwxrwxr-x 2 jenkins jenkins 4096 Sep 17 08:04 js
```
So if it was removed where should the bundle find its icons?

**Review by pedropombeiro — APPROVED** [review]

**Comment by vkjr** [comment]
@jakubgs, instead of `resources/icons` you can use `desktop/resources` directory. It will be available when #8630 commited. See this commit -  https://github.com/status-im/status-react/pull/8630/commits/69dc1f0856494474e177979c331c426ad2f322db

**Comment by vkjr** [comment]
@jakubgs, maybe it worth making changes from this PR directly in #8630?

**Comment by jakubgs** [comment]
@vkjr if you think it makes sense please do, happy to close this PR if you do.

**Comment by vkjr** [comment]
@jakubgs, ok, will transfer now changes from this PR to #8630 to see what happens :)

**Pull request merged**
