### PR TITLE
Allow any unicode character as topic name for public chat

### PR DESCRIPTION
**Pull request by yenda**
status: ready

### CODE REVIEW

**Review by rasom — APPROVED** [review]

**Review by janherich — APPROVED** [review]

**Review by mandrigin — CHANGES_REQUESTED** [review]
we need to figure out how to avoid scam and potential security issues by allowing all of the Unicode there

**Comment by mandrigin** [comment]
Also, we still need to limit the character set. Unicode contains a lot of invisible control characters, zero-width spaces, etc.
And we need to make sure that channel names are always normalized somehow.

**Comment by chadyj** [comment]
Fair point.
As a workaround would it work to hardcode the unicode channel names in https://github.com/status-im/status-react/blob/develop/src/status_im/ui/screens/add_new/new_public_chat/view.cljs#L56?

Users can't create unicode channels, but it can be at least in the default list.

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/status-im/status-react">status-im/status-react</a></strong></div><div>status-react - a free (libre) open source, mobile OS for Ethereum</div></blockquote>

**Comment by yenda** [comment]
@chadyj Yes that would be the simplest solution for a quick update.

**Comment by mandrigin** [comment]
@chadyj @yenda that works for me 👍
I can try to translate Chromium's URL display logic into Clojure (or Javascript) to have a library that checks if it is safe to display Unicode characters.
WDYT?

**Comment by chadyj** [comment]
Quick solution works great for now. :+1:
We can use this and to kick start our international communities and then work on improving later.

New chats are: `"中文" "日本語" "한국어" "русский" "español"`

**Comment by oskarth** [comment]
Maybe we shouldn't expand scope and add features when our goal is to ship something? Cut scope, cut scope, cut scope. After beta: sure.

**Pull request closed without merging**
