### PR TITLE
fix(wallet)_: price not found on swap

### LINKED ISSUE #21555: ERC20 bridge and swap transactions are broken
### Steps to Reproduce:
1. Navigate to the swap/bridge page.
2. Attempt to perform a swap/bridge transaction of erc20 token.

### Actual Result:
In case of swap transaction fails with "price route not found" error. In case of bridge - no errors in UI but transaction does not appear in blockchain. 

https://github.com/user-attachments/assets/0ff2426f-acda-4b42-9c37-943afe53bbca

### Expected Result:
The swap transaction should proceed successfully

### Devices:
Pixel 7a, Android 13
iPhone 11 Pro Max, iOS 17

### Logs:
[logs.zip](https://github.com/user-attachments/files/17617778/logs.zip)

### ENV:
Nightly 4 Now, 2024

### PR DESCRIPTION
**Pull request by smohamedjavid**
fixes #21555

### Summary

This PR fixes the `Price route not found` error thrown on performing ERC20 Bridge and Swap transactions

Status-go PR: https://github.com/status-im/status-go/pull/6059

status: ready

### CODE REVIEW

**Review by briansztamfater — APPROVED** [review]

**Comment by VolodLytvynenko** [comment]
hi @smohamedjavid @saledjenic thank you for PR. take a look please at found issues. Seems some still are not resolved

## PR_ISSUE 1: "price route not found" after attempting to swap ERC-20

### Steps:
1. Go to swap selecting ERC20 
2. Perform swap

### Actual result:

https://github.com/user-attachments/assets/6935914f-b47e-4d20-a692-c3e8bfca2de6

### Expected result:
Swap is performed

### Devices:
- Pixel 7a, Android 13
### Logs
[Status-debug-logs (1).zip](https://github.com/user-attachments/files/17667230/Status-debug-logs.1.zip)

**Comment by VolodLytvynenko** [comment]
## PR_ISSUE 2: ERC 20 Bridge transactions stuck in the hopper with "pending" status

### Steps:
1. Perform bridge transaciton using ERC 20 token 


### Actual result:
Transaction stucks into pending status
image

[Hopper link](https://explorer.hop.exchange/?transferId=0x29f704ac393a4c249e319f252d4e2bd88527a6ebba81ef51a5a8b815b8a98cbc)

[Arbiscan tx ](https://arbiscan.io/tx/0x29f704ac393a4c249e319f252d4e2bd88527a6ebba81ef51a5a8b815b8a98cbc)

### Devices:
- Pixel 7a, Android 13

### Logs
[Status-debug-logs (2).zip](https://github.com/user-attachments/files/17667725/Status-debug-logs.2.zip)

**Comment by VolodLytvynenko** [comment]
## PR_ISSUE 3: ERC-20 send + bridge transactions are randomly failed
Unfortunately, this issue doesn't happen consistently, and there are no exact steps to reproduce it. Hopefully, the logs will help

### Steps:
1. Go to send flow
2. Perform bridge transaction using ERC-20 token


### Actual result:
https://arbiscan.io/tx/0x0b6ffdc4ca896dbcded5693d96099b74d68e718b61b16966a942e958560eb8f7

### Devices:
- Pixel 7a, Android 13

### Logs
[Status-debug-logs (2).zip](https://github.com/user-attachments/files/17667759/Status-debug-logs.2.zip)

**Comment by saledjenic** [comment]
@VolodLytvynenko this is pretty weird, cause. Would you check the same in the desktop app?

@smohamedjavid could you confirm if the mobile app uses the old or new sending endpoints?
Cause if it's using the old sending flow, then this is expected.

**Comment by smohamedjavid** [comment]
> @smohamedjavid could you confirm if the mobile app uses the old or new sending endpoints? Cause if it's using the old sending flow, then this is expected.

Mobile still uses the old sending flow. 

Migration to the new send flow is done separately at https://github.com/status-im/status-mobile/pull/21541

In that case, we can update that PR to point to that status-go PR. 

cc @alwx

**Pull request closed without merging**
