### PR TITLE
chore: update icons for iOS and iPadOS release apps

### LINKED ISSUE #21110: Update Status' icons for release 2.30
# Feature Issue

### Description

We need to update Status' icons for release 2.30. Please, reach out to @Francesca-G, @pedro-et, or @xAlisher to obtain assets. Example PR from many years ago, might be useful https://github.com/status-im/status-mobile/pull/4524/files

* Here's [the updated designs for Android icons](https://www.figma.com/design/gZss5EzKuqdcSXOlqrQZoZ/Logo?node-id=590-153)
* And here's [the updated design for iOS icons](https://www.figma.com/design/gZss5EzKuqdcSXOlqrQZoZ/Logo?node-id=589-19)

### Notes

Files to change are found in directories:

- `ios/StatusIm/Images.xcassets/`
- `android/app/src/main/res/`

### Acceptance criteria

- Double-check installed builds are using the new icon for both Android and iOS.
- With all images correctly included in `ios/StatusIm/Images.xcassets/AppIcon.appiconset`, the correct icon should be detected in App Store Connect when we upload a build.
- We can ignore icons for PR and debug builds and focus only on those that will be used for the release build.

### PR DESCRIPTION
**Pull request by seanstrom**
partially fixes #21110 

### Summary

* This PR attempts to update the release app icons for iOS and iPadOS

#### Platforms

- Android
- iOS
- iPadOS

##### Non-functional

- Icon appearance

status: ready

### CODE REVIEW

**Review by ilmotta — APPROVED** [review]
We can't test based on the PR build because the PR icons use different assets, but asset changes look very much correct 👍🏼 Thank you!

Just for the sake of a quick test @seanstrom, can you install a release build in iOS to check if icons look correct?

**Comment by seanstrom** [comment]
@ilmotta Just to leave a note here, I couldn't build the app in release mode because I don't have a certificate for distributing the app. Perhaps there's another way to build/test this?

**Comment by ilmotta** [comment]
> @ilmotta Just to leave a note here, I couldn't build the app in release mode because I don't have a certificate for distributing the app. Perhaps there's another way to build/test this?

There's probably a way. It's not the first time I hear somebody needs to test a local release build in iOS. @siddarthkay might know and if there's a way it would be nice to have it documented somewhere (or maybe it is already).

**Comment by siddarthkay** [comment]
Easiest way is to make a branch like this -> https://github.com/status-im/status-mobile/tree/release/pr/21111
This should push a release build to `Testflight` which QA can use.
cc @mariia-skrypnyk 
Its been a while since I built the `iOS` release locally but happy to document it the repo sometime next week.

**Comment by siddarthkay** [comment]
Screenshot 2024-08-22 at 11 26 14 PM

looks like its working @seanstrom  ;)

**Comment by mariia-skrypnyk** [comment]
Thanks @siddarthkay 🙌
Build is in Testflight and I have ability to test.

@ilmotta do we need any changes on the splash screen?
Or is it better to address my question to the design team?

Screenshot 2024-08-22 at 20 14 25

**Comment by ilmotta** [comment]
> do we need any changes on the splash screen? Or is it better to address my question to the design team?

Thanks for testing already @mariia-skrypnyk. The design team can clarify for us how it should be.

**Comment by mariia-skrypnyk** [comment]
@ilmotta asked them here https://discord.com/channels/1210237582470807632/1274068685266489434/1276250337073692744

**Comment by mariia-skrypnyk** [comment]
Hi @seanstrom @ilmotta !
   
I found that we have old icon here, think we need to change it too.

Screenshot 2024-08-23 at 10 47 07

**Comment by mariia-skrypnyk** [comment]
@seanstrom @ilmotta 

And icon on Push Notifications too.

Screenshot 2024-08-23 at 10 55 40

**Comment by mariia-skrypnyk** [comment]
> Hi @seanstrom @ilmotta !     I found that we have old icon here, think we need to change it too.
> 
> Screenshot 2024-08-23 at 10 47 07

@seanstrom seems it could be cash issue, as restart fixes it. Do not think it it a priority right now @ilmotta 
I can check it one more time on release build with and without upgrade. 
Will we fix icon on PN's?

**Comment by seanstrom** [comment]
I cannot seem to find any reference to an outdated push notification icon, but it could be possible that push notifications are somehow using an older version of the icon from cache still, or that there's a push notification setting be used to to display a different icon.

One way of testing this would be to try searching for the app using spotlight, and see which icon appears in the spotlight list, if it's the old icon then I think it's more likely to be something cache related for the whole phone, because we have all the icons set to the correct icon in Xcode.

Screenshot 2024-08-23 at 16 49 52

**Comment by mariia-skrypnyk** [comment]
Thanks @seanstrom .
As the icon on PN and the icon when app is minimized fixes with a device restart, we can merge it as is for our 2.30 release.
PR can be merged and cherry-picked.

**Pull request merged**
