### PR TITLE
[fix 4574] do not send updates to pending contacts

### LINKED ISSUE #4574: Do not update username/userpic for contacts who not in my contact list if I edit my profile info
### User Story

As a user I don't want to reveal my profile username and userpic to the contact who is not in my contact list if I change my profile data

### Description

***Type***: Bug

*Summary*: When contact updates the profile username/userpic, - the updated username and userpic are sent to all the contacts I have on my Home screen, even those I have not added in my contacts 

#### Expected behavior
Contacts who not in my contact list are not updated with my profile username and userpic when I edit any of last
#### Actual behavior
Contacts who not in my contact list are updated with my profile username and userpic when I edit any of last

### Reproduction
- Open Status on Device1 and Device2
- Create Contact1 and Contact2 respectively
- Update Contact2's username and userpic
- Contact1 adds Contact2 and sends a text message in 1-1 chat (Note: Contact2 displays with the default username and userpic on the Contac1 side on this step)
- Contact2 updates his username (or userpic)
- Check if on Contact1 side there are non-default username+userpic of the Contact2

### Additional Information
* Status version: Develop (nightly 421st Jenkins build) / Release 0.9.19
* Operating System: Android and iOS

#### Logs

TF session with logs for Contact1: https://app.testfairy.com/projects/4803622-status/builds/8406720/sessions/377/?accessToken=YF68t61Zv1/i3QNUzieeXCMg5VM
TF session with logs for Contact2: https://app.testfairy.com/projects/4803590-status/builds/8412189/sessions/21/?accessToken=L/2uaNon9/9U--FR6HceB6dKgCs

<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803622-status/builds/8406720/sessions/377/?accessToken=YF68t61Zv1/i3QNUzieeXCMg5VM">TestFairy: Status 0.9.19 (6022) @377</a></strong></div></blockquote>
<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803590-status/builds/8412189/sessions/21/?accessToken=L/2uaNon9/9U--FR6HceB6dKgCs">TestFairy: Status 0.9.20d66 @21</a></strong></div></blockquote>

### PR DESCRIPTION
**Pull request by yenda**
fixes #4574

updates were sent to all pending contacts
fixes that by filtering on the pending? key

# Steps to test
- add contact A with B
- do not accept B with A
- change A profile info
- B should not update
- accept B with A
- B should see latest profile info of A

status: ready

### CODE REVIEW

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/db3tep for branch PR-4579

<blockquote><div><strong><a href="https://i.diawi.com/db3tep">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/XFoSox for branch PR-4579

<blockquote><div><strong><a href="https://i.diawi.com/XFoSox">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Review by janherich — APPROVED** [review]

**Review by cammellos — APPROVED** [review]
Looks good, again we should get into the habit of having tests with each PR whenever possible, especially if it touches core logic, this definitely looks like a good candidate.

**Review by dmitryn — APPROVED** [review]

**Review by rasom — APPROVED** [review]

**Comment by Serhy** [comment]
@yenda it's all works fine! But could you rebase off develop, please. (Autotests are failing with https://github.com/status-im/status-react/issues/4456 which is not the case for latest nightly develop build - (Android: http://artifacts.status.im:8081/artifactory/nightlies-local/im.status.ethereum-b47caf-n-fl.apk
 iOS: https://i.diawi.com/E4tvaVdue)

<blockquote></blockquote>
<blockquote><div><strong><a href="https://i.diawi.com/E4tvaVdue">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by Serhy** [comment]
Looks good! (Failed autotest are false failures (rechecked them manually) are not a part of this PR)

**Pull request merged**
