### PR TITLE
Don't autocorrect amounts (but still show errors).

### LINKED ISSUE #4361: Typing fast on iOS amount field leads to incorrect sums
### Description

*Type*: Bug

*Summary*:  when i type fast on iOS small sums like 0,0094 it appears as 94

#### Expected behavior
when i enter anount in Amount field it is shown correctly 

#### Actual behavior
wrong amount is shown (2 instead of 0,02)

### Reproduction
- Open Status
- Go to wallet - send
- Enter 0,02 amount quickly in amount field

### PR DESCRIPTION
**Pull request by mandrigin**
Don't autocorrect amounts (but still show errors).

fixes: #4361 

status: ready

### CODE REVIEW

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/s7WcUH for branch PR-4388

<blockquote><div><strong><a href="https://i.diawi.com/s7WcUH">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/iWiMmq for branch PR-4388

<blockquote><div><strong><a href="https://i.diawi.com/iWiMmq">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Review by rasom — APPROVED** [review]

**Review by goranjovic — APPROVED** [review]

**Review by yenda — APPROVED** [review]

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/ed8Ggg for branch PR-4388

<blockquote><div><strong><a href="https://i.diawi.com/ed8Ggg">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/EbdV5q for branch PR-4388

<blockquote><div><strong><a href="https://i.diawi.com/EbdV5q">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by annadanchenko** [comment]
Sometimes when typing 1,000000 it becomes ,000000 or 100000
amount typing 2

**Comment by mandrigin** [comment]
@annadanchenko forgot to remove the unnecessary timer 😅 the next build will have this fixed.

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/thmTz8 for branch PR-4388

<blockquote><div><strong><a href="https://i.diawi.com/thmTz8">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/zUsBjx for branch PR-4388

<blockquote><div><strong><a href="https://i.diawi.com/zUsBjx">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/4fzwxx for branch PR-4388

<blockquote><div><strong><a href="https://i.diawi.com/4fzwxx">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/gfww8g for branch PR-4388

<blockquote><div><strong><a href="https://i.diawi.com/gfww8g">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Pull request merged**
