### PR TITLE
[Fixes: #12486] Fix delete of messages

### PR DESCRIPTION
**Pull request by cammellos**
fixes deletion of messages in a row 
and https://github.com/status-im/security-reports/issues/28

### CODE REVIEW

**Review by flexsurfer — APPROVED** [review]

**Comment by qoqobolo** [comment]
@cammellos thanks for the fixes!

#### ISSUE 1: A preview of one of the deleted messages is displayed on the home screen

**_Reproduction:_** 

1. User A, User B: open status, join same public chat
2. User B: close app
3. User A: send several messages (i.e. 1, 2, 3, 4, 5, 6, 7)
4. User A: delete all these messages
5. User B: open app, login and check chat preview on the home screen


https://user-images.githubusercontent.com/67952253/132712349-f2343c2f-4853-488b-a3ef-5c167d305482.mp4

**Comment by cammellos** [comment]
@qoqobolo It should be fixed now, I have tested the latest build and could not replicate, so :crossed_fingers: 
Thank you

**Comment by qoqobolo** [comment]
@cammellos unfortunately, the issue is still reproducible on the latest build :(
But this is no longer so noticeable because if a user deletes several messages in a row and then sends at least one more, this preview will not be visible to anyone.
So I believe we can register this leftover separately and merge this PR, if you agree.

**Comment by cammellos** [comment]
@qoqobolo sounds good with me, let's do that
Thank you

**Review by shivekkhurana — APPROVED** [review]

**Pull request merged**
