### PR TITLE
[nix][fix] hostname with uppercase and use host

### PR DESCRIPTION
**Pull request by hlolli**
This is bit redundant commit, but there's an annoying error popping up due to wrong argument given to hostname, but it doesn't seem to be a source of any problems. By using hostname from nixpkgs we can be sure all are using the same hostname binary, therefore the argument should work on all environments.

@PombeirP

### CODE REVIEW

**Comment by pedropombeiro** [comment]
Thanks @hlolli for the PR. What is the reasoning from switching from `-I` to `-i`? From what I see in the tool help, they are both valid options:

```
    -i, --ip-address       addresses for the host name
    -I, --all-ip-addresses all addresses for the host
```

in my case, `hostname -I` returns:

```
192.168.10.12 172.17.0.1 172.16.237.1 192.168.122.1 172.16.38.1 fd00:30b7:d487:a322:1f1a:f7b9:48a6:ef48
```

and `hostname -i` returns:

```
fe80::422:36e2:f766:edde%wlp2s0 fe80::250:56ff:fec0:1%vmnet1 fe80::250:56ff:fec0:8%vmnet8 fd00:30b7:d487:a322:1f1a:f7b9:48a6:ef48 192.168.10.12 172.17.0.1 172.16.237.1 192.168.122.1 172.16.38.1
```

(totally agree with adding hostname to the Nix expressions)

**Comment by hlolli** [comment]
```
[hlolli@nixos:~]$ nix-shell -p hostname --pure

[nix-shell:~]$ hostname --version
net-tools 1.60_p20170221182432

[nix-shell:~]$ hostname -I
hostname: invalid option -- 'I'
Usage: hostname [-v] {hostname|-F file}      set hostname (from file)
       domainname [-v] {nisdomain|-F file}   set NIS domainname (from file)
       hostname [-v] [-d|-f|-s|-a|-i|-y|-n]  display formatted name
       hostname [-v]                         display hostname

       hostname -V|--version|-h|--help       print info and exit

    dnsdomainname=hostname -d, {yp,nis,}domainname=hostname -y

    -s, --short           short host name
    -a, --alias           alias names
    -i, --ip-address      addresses for the hostname
    -f, --fqdn, --long    long host name (FQDN)
    -d, --domain          DNS domain name
    -y, --yp, --nis       NIS/YP domainname
    -F, --file            read hostname or NIS domainname from given file

   This command can read or set the hostname or the NIS domainname. You can
   also read the DNS domain or the FQDN (fully qualified domain name).
   Unless you are using bind or NIS for host lookups you can change the
   FQDN (Fully Qualified Domain Name) and the DNS domain name (which is
   part of the FQDN) in the /etc/hosts file.

[nix-shell:~]$ hostname -i
2003:d1:4706:d00:2b69:bd0:35bf:5e62 2003:d1:4706:d00:dd04:b9:bb41:e7bb fe80::5d97:b12b:fec6:5647
```

to add, that in global environment on my computer

```
~ hostname -i                                                       ~
127.0.1.1

~ hostname -I                                                       ~
hostname: invalid option -- 'I'
Try 'hostname --help' or 'hostname --usage' for more information. 
```

it uses my /etc/hosts config

not sure which nettools/hostname you're working with? Isn't the goal with this command to get the localhost address(es)?

**Comment by hlolli** [comment]
This error can be seen here too https://github.com/status-im/react-native-desktop/issues/245 tough the ticket is not about this error.

**Comment by hlolli** [comment]
closeing in favour of https://github.com/status-im/status-react/pull/7759

**Comment by pedropombeiro** [comment]
> not sure which nettools/hostname you're working with? Isn't the goal with this command to get the localhost address(es)?

Ah yes, outside the nix-shell environment I have hostname 3.20 which has that option. Didn't expect the Nix version of it to be that outdated.

**Pull request closed without merging**
