### PR TITLE
don't make e2e builds use modified ID

### LINKED ISSUE #7953: E2E Android nightly/release build is 'Status PR' (im.status.ethereum.pr)
**_Summary_**: e2e Android builds should have `im.status.ethereum` ID. But they latest nightly creates them with `im.status.ethereum.pr` ID.
Regression from https://github.com/status-im/status-react/pull/7493

#### Expected behavior
Nightly/release Android e2e job creates 'Status' artefact

#### Actual behavior
Nightly/release Android e2e job creates 'Status PR' artefact

### PR DESCRIPTION
**Pull request by jakubgs**
Fixes #7953

### CODE REVIEW

**Review by mandrigin — APPROVED** [review]

**Review by pedropombeiro — APPROVED** [review]

**Comment by jakubgs** [comment]
Okay, I don't get this e2e test error. I downloaded the build from https://ci.status.im/job/status-react/job/prs/job/android-e2e/job/PR-7954/ and its app ID doesn't have the `.pr` suffix.
```bash
 caspair > wget -q https://status-im.ams3.digitaloceanspaces.com/StatusIm-190411-104124-c8f5bc-e2e.apk 

 caspair > aapt dump badging StatusIm-190411-104124-c8f5bc-e2e.apk | grep package:\ name              
package: name='im.status.ethereum' versionCode='2019041110' versionName='0.12.0' platformBuildVersionName=''
```

**Comment by Serhy** [comment]
> Okay, I don't get this e2e test error. I downloaded the build from https://ci.status.im/job/status-react/job/prs/job/android-e2e/job/PR-7954/ and its app ID doesn't have the `.pr` suffix.
> 
> ```shell
>  caspair > wget -q https://status-im.ams3.digitaloceanspaces.com/StatusIm-190411-104124-c8f5bc-e2e.apk 
> 
>  caspair > aapt dump badging StatusIm-190411-104124-c8f5bc-e2e.apk | grep package:\ name              
> package: name='im.status.ethereum' versionCode='2019041110' versionName='0.12.0' platformBuildVersionName=''
> ```

But it should have. `if (type == 'pr')` -> True, it's PR. 
So both `Android` and `Android e2e` build should have id `im.status.ethereum.pr`

**Comment by jakubgs** [comment]
Oh, so what you're saying is that we should change e2e tests to `im.status.ethereum.pr`, rather than make e2e builds not have `.pr` prefix?
If that's the case then I misunderstood your issue.

**Comment by Serhy** [comment]
Sorry for not been clear.
e2e Android build is the same build as non-e2e with the major difference that Ropsten RPC is the default network
With recent changes we've made (in https://github.com/status-im/status-react/pull/7493) :
 - if there is PR job -> Android artefact is created as `im.status.ethereum.pr` (and app name value = 'Status PR')
- if there is nightly/release job -> Android artefact is created as `im.status.ethereum` (and app name value = 'Status')

Android e2e jobs should behave in the same way:
- PR e2e Android job -> creates`im.status.ethereum.pr` artefact
- any other than PR build_type job -> creates `im.status.ethereum` artefact (and app name value = 'Status')

**Comment by jakubgs** [comment]
>PR e2e Android job -> createsim.status.ethereum.pr artefact

But that's already the case. I don't think there's anything to be done.

**Comment by jakubgs** [comment]
Okay, I see now. The issue was that the e2e build for `release` build type had the `.pr` suffix which was wrong. Fixed.

**Comment by Serhy** [comment]
Looks good to me! If build_type is PR - `Status PR` builds created. If build_type is nightly/release - 'Status' builds are created.
Thanks @jakubgs could you please resolve conflict? And lets merge then.

**Review by Serhy — APPROVED** [review]

**Pull request merged**
