### PR TITLE
Rename filter-tags and refactor token-tag 

### LINKED ISSUE #14030: Rename filter-tags and refactor token-tag
This is a simple issue to rename filter-tag and filter-tags components files to tag and tags as is if figma so that its easy to follow up what figma designs have been implemented

### PR DESCRIPTION
**Pull request by jo-mut**
fixes #14030

This PR renames filter-tag/filter-tags files to tag/tags and refactors the token-tag component. This is so that file naming can match components as named in figma designs

### CODE REVIEW

**Review by J-Son89 — APPROVED** [review]

**Comment by J-Son89** [comment]
nice one 😃

**Comment by jo-mut** [comment]
@J-Son89  @flexsurfer is it okay if i just merge this as i only renamed the files to match figma naming

**Comment by qoqobolo** [comment]
Hey @jo-mut, can you rebase this one again please, and move it to the E2E column? 
Thanks

**Comment by jo-mut** [comment]
@qoqobolo done

**Comment by qoqobolo** [comment]
Thanx @jo-mut, PR can be merged.

**Comment by jo-mut** [comment]
thank you  @qoqobolo

**Pull request merged**
