### PR TITLE
Bump go

### LINKED ISSUE #18315: [Android] User doesn't see Request to join community screen after tap on invitation link
# Bug Report

## Problem 
[comment]: # (A problem description)
User doesn't see Request to join community screen after tapping on the invitation link.

Reproduced randomly in all PRs stating from 28.12.23 (before it was working with 5 sec of waiting) 

#### Expected behaviour
User sees Request to join community screen after tap on invitation link (pause between screens can be but not more than 2-4 seconds)

https://github.com/status-im/status-mobile/assets/147824399/3b8f95fa-b4b9-44f3-a149-093d653afff2

#### Actual behavior
User sees this screen (1 minute and more)  and doesn't move to the Request to join community screen 
photo_2023-12-28_15-27-45

**Precondition**
PR build installed from this PR https://github.com/status-im/status-mobile/pull/17839

### Reproduction

1. User A (desktop) adds User B as a member to his community
2. User B opens 1 to 1 chat with User A and taps on invitation link

### Additional Information

- Status version: PR build from here https://github.com/status-im/status-mobile/pull/17839
- Operating System: Android

[comment]: # (Please, add logs/notes if necessary)

Log from failed test (last 20 seconds matters):

[TestCommunityMultipleDeviceMerged_geth1 (5).log](https://github.com/status-im/status-mobile/files/13787473/TestCommunityMultipleDeviceMerged_geth1.5.log)

### PR DESCRIPTION
**Pull request by ibrkhalil**
fixes #18315

### Summary

Bumps status-go to add [Igor's fix](https://github.com/status-im/status-go/pull/4509) to fetchCommunity ability to get community from store nodes, I reproduced the #18315 with this [PR](https://github.com/status-im/status-mobile/pull/17839), But couldn't reproduce it after testing it on latest status-go.

status: ready

### CODE REVIEW

**Review by siddarthkay — APPROVED** [review]

**Review by Parveshdhull — APPROVED** [review]

**Comment by pavloburykh** [comment]
Hey @ibrkhalil! Thanks for the PR! According to failed e2e that the issue is still there. So bumping go version did not help unfortunately. 

1. Device 1 [sends](https://app.eu-central-1.saucelabs.com/tests/930202e4d6894fb9a9e8cca24e41e355?auth=5558420bd1e60a941d5f3fac069081dc#127) community link to Device 2
2. Device 2 to [taps](https://app.eu-central-1.saucelabs.com/tests/34c2130bd71e48458a216e5868fa3d2d?auth=053621e8f45ad5120e767c6cc79a67e4#101) the link and appears on empty community screen

[Device1_link_sender.log](https://github.com/status-im/status-mobile/files/13816817/Device1_link_sender.log)
[Device2_link_receiver.log](https://github.com/status-im/status-mobile/files/13816818/Device2_link_receiver.log)

**Comment by ibrkhalil** [comment]
I ran the TestRequestCommunityInfo on status-go which fetches the community info from store nodes 300 times without failure.
But I found this in the receiver logs

```go
INFO [12-30|09:14:15.615|github.com/status-im/status-go/protocol/messenger_store_node_request_manager.go:337]                               request finished                         requestID="{RequestType:0 DataID:0x02471dd922756a3a50b623e59cf3b99355d6587e43d5c517eb55f9aea9d3fe9fe9}" communityFound=false contactFound=false shardFound=false error="too many failed requests"
```
It's an error indicating that the request from store nodes came back successfully but couldn't find community.

Investigating

**Comment by igor-sirotin** [comment]
> It's an error indicating that the request from store nodes came back successfully but couldn't find community.

Actually not.  If it was a successful request, then a `nil` error and `nil` community would have been returned.

 `too many failed requests` error means that current active store node replied "bad" too many times and we're disconnecting from it now (and connecting to another one in the mailserver loop).

-----

AFAIK `shards.test` fleet is unstable and it's possible to face such problems there. And I think both desktop and mobile use this fleet as default now.

I suggest maybe testing this with `status.prod` fleet.

-----

We could probably make `StoreNodeRequestManager` smarter on this. So that when one store node failed to reply, we wait for a new active store node and make another request. But this sounds as a helper, but not the actual proper fix to me.

**Comment by pavloburykh** [comment]
@igor-sirotin thank you your feedback on this issue. 

> I suggest maybe testing this with `status.prod` fleet.

Regarding this, from my point of view it is not the best option to get back to the deprecated status.prod fleet during testing process. It would be better to focus on finding the solution for shards.test as it is in fact our new version of prod fleet and we should continue further testing using this fleet.

**Comment by igor-sirotin** [comment]
> from my point of view it is not the best option to get back to the deprecated `status.prod` fleet during testing process

@pavloburykh Sure, I agree. I propose to test this just to make sure the problem is indeed in `shards.test` only.
We should ofc make the `shards.test` work stable, as it's the default fleet now.

**Comment by pavloburykh** [comment]
> I propose to test this just to make sure the problem is indeed in shards.test only.

@igor-sirotin unfortunately I was not able to test the old status.prod fleet on mobile, because data is not delivered at all on this fleet.

**Comment by pavloburykh** [comment]
> > I propose to test this just to make sure the problem is indeed in shards.test only.
> 
> @igor-sirotin unfortunately I was not able to test the old status.prod fleet on mobile, because data is not delivered at all on this fleet.

Hey @igor-sirotin!

**UPDATE:**

I have managed to check on status prod fleet and confirm that the issue is there as well. So it is not shards.test specific.

**Comment by pavloburykh** [comment]
Closing this PR as the issue has been fixed on the shards.test fleet side. @igor-sirotin thanks a lot for investigating and fixing the issue.

**Pull request closed without merging**
