### PR TITLE
[WIP] PR to upgrade react-native IOS side only

### LINKED ISSUE #14386: Research into upgrading react-native
Rn Upgrade helper is here : https://react-native-community.github.io/upgrade-helper/
Current version of React Native is 0.63.5
Attempt to upgrade to 0.68.5
Wish to ultimately reach 0.70.x (So far it's only possible to aim for 0.68.5)

Rough todos below :
- [x] for android : Figure out the change here https://github.com/status-im/status-mobile/blob/develop/nix/pkgs.nix
- [x] Some research on latest version that clojurescript officially supports ( I believe latest versions of React Native require us to switch to latest versions of Reactjs as well )

**Attempt and log findings on upgrading IOS while ignoring Android**
- [x] update dependencies and dev dependencies in package.json 
- [x] update metro config
- [x] update ios/~/Info.plist
- [x] update ios/~/AppDelegate.m
- [x] update ios/~xcworkspace/contents.xcworkspacedata
- [x] update ios/~.xcodeproj/xcshareddata/xcschemes/RnDiffApp.xcscheme
- [x] update ios/~.xcodeproj/project.pbxproj
- [x] update ios/Podfile
- [x] update .flowconfig

**- Android Related Stuff**
- [x] update android/gradle.properties
- [x] update android/build.gradle
- [x] update android/app/src/main/res/values/styles.xml
- [x] update android/app/src/main/AndroidManifest.xml
- [x] update android/app/src/debug/AndroidManifest.xml
- [x] update android/app/build.gradle

Take care of Libraries specially modified to work with Older Versions of React Native
- [x]  react-native-hole-view
- [x]  react-native-mail

### PR DESCRIPTION
**Pull request by siddarthkay**
do not review yet :)
status: wip

### CODE REVIEW

**Comment by yqrashawn** [comment]
Potential related issue https://github.com/wix/react-native-navigation/issues/7547

**Comment by flexsurfer** [comment]
feel free to reopen when needed

**Comment by siddarthkay** [comment]
i plan to work on this tomorrow so re-opening this for now @flexsurfer  :)

**Comment by flexsurfer** [comment]
feel free to reopen if needed

**Comment by jakubgs** [comment]
This PR needs to be rebased. The iOS build will forever be stuck in the queue because it expects old Xcode which doesn't exist:
https://github.com/status-im/status-mobile/blob/1599006982e2c868237b589b3fe78a146aa52d18/ci/Jenkinsfile.ios#L7

**Comment by siddarthkay** [comment]
closing in favour of : https://github.com/status-im/status-mobile/pull/14809

**Pull request closed without merging**
