### PR TITLE
Fix mail client on android 13 fro sending logs

### LINKED ISSUE #16251: [Pixel 7a, Android 13] 'Mail client should be configured' pop-up appears after attempting to submit the logs by gmail client
### Note:
The issue is likely device-specific, as it has only been reproduced on the Pixel 7a running Android 13 (It has also been reproduced by @qoqobolo, who uses the same device. ). The issue occurs specifically when using Gmail as the mail client, but works with Outlook mail client. Other similar applications successfully open the Gmail client in their 'contact us' sections.

### Preconditions:
 Ensure that no mail client is currently configured on the system.

### Steps to Reproduce:
1. Launch the application.
2. Generate logs by shaking the app
3. Click on the "Submit by email with Logs" button.
4. Ensure that no mail client is currently configured on the system.

### Actual Result:
A pop-up message with the text 'mail client should be configured' appears, preventing the logs from being submitted via gmail.

On the 16th sec I've just show that the similar functionality works well for 'Podcast Discover' application

https://github.com/status-im/status-mobile/assets/52490791/85d48707-09b2-4af3-bf1e-0ecb9680520d

### Expected Result:
The mail client is opened

### Device:
- real device: Pixel 7a, Android 13

### Logs:
[android_logcat.txt](https://github.com/status-im/status-mobile/files/11723845/android_logcat.txt)

### PR DESCRIPTION
**Pull request by rasom**
fix #16251

statue: wip

### CODE REVIEW

**Comment by rasom** [comment]
@VladimrLitvinenko would be nice if you take a look at this PR, I don't have that Pixel 7a device to test it

**Comment by VolodLytvynenko** [comment]
Hi @rasom the ability to share logs via Android 13 is fixed. A few new issues are found:

## ISSUE 1: The images are not fetched to the gallery for Android 10 devices

### Steps to reproduce:
1. Open any chat
2. Tap "open gallery" button

### Actual result:
- Images are not shown in the gallery album after its opening for Android 10
Record from Android Studio device: Pixel XL API 29

https://github.com/status-im/status-mobile/assets/52490791/08e8c1ee-dbac-4ce2-ab7d-5f9b6b8361c1


### Expected result:
Images are shown in the opened gallery
The screen is from the same device on the last nightly build 

https://github.com/status-im/status-mobile/assets/52490791/b5ab4164-864a-4c60-a3d2-41dce8f0f9bc

### Device:
Android Studio device: Pixel XL API 29

**Comment by VolodLytvynenko** [comment]
## ISSUE 2: "Open Gallery" button is unresponsive on Android 13

### Steps to reproduce:
1. Open any chat.
2. Tap the "Open gallery" button.

### Actual result:
The "open gallery" button does not respond to taps on the device.

https://github-production-user-asset-6210df.s3.amazonaws.com/52490791/251451297-a2f54307-357d-4c62-9fc5-b4369ddea915.mp4

### Expected result:
The gallery should open when the "Open gallery" button is tapped

**Comment by rasom** [comment]
@VladimrLitvinenko that's kind of expected outcome as a number of libs was affected. looking into it. Thanks

**Comment by rasom** [comment]
@VladimrLitvinenko both issues should be fixed now though I don't have a device to check the second one

**Comment by VolodLytvynenko** [comment]
@rasom That's strange, but it seems that the issue has disappeared. I have tested it on the latest nightly build and the issue is no longer present. Additionally, other members of the QA team who are using Android 13 have also verified that the issue is resolved. Based on this, it appears that there is no need to merge this PR anymore..

**Comment by rasom** [comment]
@VladimrLitvinenko that doesn't make too much sense as the issue is not imaginary and actually logged in react-native-mail repo https://github.com/chirag04/react-native-mail/issues/196, and we do have an old version of that lib in develop. On the other hand I'm happy to stop working on it and we can just wait till it will pop up again :)

**Pull request closed without merging**
