### PR TITLE
Drawer UI refresh

### PR DESCRIPTION
**Pull request by GustavoNunes**
### Summary:
- Larger drawer.
- 2 most recent unsigned transactions, shortcut to transactions list.
- Show current network.
- Removed "Discover" and "Contacts" labels.
- Removed "Shake your phone" text.
- Switch accounts now under menu button in top.

status: ready

### CODE REVIEW

**Comment by GustavoNunes** [comment]
@rasom, this PR is ready.
@flexsurfer, I've added the current network ("Ropsten" hardcoded [here](https://github.com/status-im/status-react/pull/1103/files#diff-cf41762f48ab010a9d1b9902839f4e07R134)), you can make this dynamic in your PR.

**Comment by flexsurfer** [comment]
@GustavoNunes great, thanks

**Comment by annadanchenko** [comment]
app crashes on launching if use build Branch: feature/drawer-ui-refresh
iOS: https://i.diawi.com/sKkYgP

**Comment by annadanchenko** [comment]
@GustavoNunes there are some differences with design (example is for iOS but same applies to Android except #2: there is no separator lines between transactions in Android design):
1. no blue background is shown
2. no date
3. no separator lines between transactions
ios drawer compare

**Comment by GustavoNunes** [comment]
@annadanchenko I fixed these issues, thank you!

**Comment by annadanchenko** [comment]
@GustavoNunes Thanks! I'm still in progress of testing (waiting when Wallet will get some ether from faucet). However, there is some difference in time format. Currently, it shows 10:19 (no PM/AM) while it's 22:19. 
img_1531


I also see that in previous PR build there was 13:02, so it was OK there. To get the exact transaction: 
- open Auction house DApp
- tap on Create an Auction
- in 1st editbox "Name to reserve" type any title.eth and tap on Register name (to get ransaction of 0 ETH)
- as soon as transaction is created open Profile

**Comment by GustavoNunes** [comment]
@annadanchenko Fixed, thanks!

**Comment by annadanchenko** [comment]
@GustavoNunes Changes look good! I found that both design and implementation on Android have regular fond for User Name instead of Medium font on iOS. So, user name is not so visible together with status text. In current UI, Android user name has "bold" font. I propose to make same style on both platforms. It can go as a separate issue if you prefer, and this PR can be merged.
img_0090
screenshot_20170525-154246

**Comment by GustavoNunes** [comment]
good idea @annadanchenko, this was a quick change

**Comment by annadanchenko** [comment]
Tested. Looks OK

**Pull request merged**
