### PR TITLE
fix send button z-index

### LINKED ISSUE #16023: Audio button z-index changes before send button animation completes when sending message
Audio button appears on top of blue send button before opacity animation completes

https://github.com/status-im/status-mobile/assets/29354102/87535d66-a2f3-459d-aa07-6330b59e8216

### LINKED ISSUE #16036: ISSUE: Composer UI elements are displayed incorrectly
### Preconditions
- Composer shouldn't be resized manually
- Composer must be empty from text

### Steps to reproduce
1. Paste/type text into composer
2. Pay attention to composer opacity level
3. Pay attention at Send button UI
4. Continue typing/pasting text into composer until it is fully expanded
5. Collapse composer
6. See if Jump to button is located above composer

https://github.com/status-im/status-mobile/assets/97434915/0d8038f1-d70d-4e1f-95de-ffcdd207a2a1

#### Actual results: 
2. Composer is transparent
3. Send button opacity is not 100% and has white square background 
6. Jump Button partly hidden under the composer

photo_2023-05-26_15-14-41
photo_2023-05-26_15-18-20
photo_2023-05-26_15-18-43

#### Expected results:
2. Composer is not transparent
3. Send button has 100% opacity with no background
6. Jump Button sticks to the top of the composer

#### Additional Info:
Device: Redmi Note 8 Pro
OS: MIUI Global 12.0.8 Stable

### PR DESCRIPTION
**Pull request by OmarBasem**
fixes: https://github.com/status-im/status-mobile/issues/16023
fixes https://github.com/status-im/status-mobile/issues/16036

Fixes z-index for send button, plus a minor UI fix

### CODE REVIEW

**Review by ajayesivan — APPROVED** [review]

**Review by J-Son89 — APPROVED** [review]

**Comment by VolodLytvynenko** [comment]
Hi @OmarBasem thank you for PR. In most cases the issue related to the audio button appearing is fixed. One more case is still available.

## ISSUE 1: 'Audio' button appears on top of blue send button when record is located in the composer. [Reproduced in 20% of cases]

### Steps:
1. Start recording the audio
2. Leave the record in the composer
3. Check the 'send' button

### Actual result:
The part of audio button is still visible

https://github.com/status-im/status-mobile/assets/52490791/4f097f70-9bc8-4de9-a6eb-9cde4d282cad

### Expected result:
The audio button is not visible if audio record already located in the composer

### Devices:
- Huawei p20 light, Android 9
- iPhone 11 Pro max, IOS 16

### Additional info:
No exact steps for this issue. Tt seems that the it is reproducible randomly, with a higher success rate on iOS devices

**Comment by OmarBasem** [comment]
Hi @VladimrLitvinenko, thanks for your testing.

I am not able to reproduce this issue. I tried many times, but never got that result.

**Comment by pavloburykh** [comment]
> Hi @VladimrLitvinenko, thanks for your testing.
> 
> I am not able to reproduce this issue. I tried many times, but never got that result.

@OmarBasem @VladimrLitvinenko! Let's not block current PR with this issue. We need this PR to be merged to fix this more serious issue https://github.com/status-im/status-mobile/pull/16024 

If we discover clear steps for ISSUE 1 - we will log it separately. @VladimrLitvinenko WDYT? Besides ISSUE 1 PR is tested and ready for merge?

**Comment by VolodLytvynenko** [comment]
> > Hi @VladimrLitvinenko, thanks for your testing.
> > I am not able to reproduce this issue. I tried many times, but never got that result.
> 
> @OmarBasem @VladimrLitvinenko! Let's not block current PR with this issue. We need this PR to be merged to fix this more serious issue #16024
> 
> If we discover clear steps for ISSUE 1 - we will log it separately. @VladimrLitvinenko WDYT? Besides ISSUE 1 PR is tested and ready for merge?

Hi @OmarBasem . Agree with @pavloburykh  No additional issues from my side. PR can be merged.

**Pull request merged**
