### PR TITLE
[#6162] fix passphrase validation

### LINKED ISSUE #6162: There is no tooltips above 'recovery phrase' field for invalid passphrase value when recovering an account
***Type***: Bug

***Summary***: We lost the tooltip above passphrase field, when recovering an account, which notifies user about possible passphrase value validation issues. When user put the focus out of passphrase field then: 
- `Required field` tooltip shown if passphrase field is empty or has only whitespace chars
- `Recovery phrase is invalid` tooltip shown if passphrase field has wrong number of words or invalid characters withing 12-word phrase (numbers, symbols, etc.)
-  `Some words might be misspelled` if word count and chars are ok but it contains some words not on our list

See steps to reproduce with examples when above should be shown.

#### Expected behavior
An appropriate tooltip is shown above passphrase field when phrase is invalid

#### Actual behavior
No tooltips above 'recovery phrase' field for invalid passphrase value when recovering an account

### Reproduction
1) Open Status
2) Tap `Add existing account`
3) Type several whitespaces in passphrase field
4) Put cursor in Password field
**Actual result:** No `Required field` tooltip shown above 'Recovery phrase' field
----- 
5) Tap top-left `<` back button
6) Tap `Add existing account`
7) Type any of `robot seed robot seed robot seed robot seed robot seed robot seed.` / `robot` / `seed seed seed seed seed seed seed seed seed seed seed` / `seed seed seed seed seed seed seed seed seed seed seed seed seed `
8) Put cursor in Password field
**Actual result:** No `Recovery phrase is invalid` tooltip shown above 'Recovery phrase' field
----- 
9) Tap top-left `<` back button
10) Tap `Add existing account`
11) Type `one two three four five six seven eight nine ten eleven twelve`
12) Put cursor in Password field
**Actual result:** No `Some words might be misspelled` tooltip shown above 'Recovery phrase' field

### Additional Information
* Status version: Develop `0.9.29 (9952)` (It all **OK in Release 0.9.29**)
* Operating System: Android and iOS

#### Logs

TF session with logs: https://app.testfairy.com/projects/4803622-status/builds/8617463/sessions/4403197266/?accessToken=V5oDVJHdmCoDhPW991mWEjN0E1Y

<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803622-status/builds/8617463/sessions/4403197266/?accessToken=V5oDVJHdmCoDhPW991mWEjN0E1Y">TestFairy: Status 0.9.29 (9952) @2018</a></strong></div></blockquote>

### PR DESCRIPTION
**Pull request by rasom**
fix #6162

status: ready

### CODE REVIEW

**Review by dmitryn — APPROVED** [review]

**Review by vitvly — APPROVED** [review]

**Comment by asemiankevich** [comment]
checked this scenario https://ethstatus.testrail.net/index.php?/cases/view/5363

e.trim error https://github.com/status-im/status-react/issues/6122 will be fixed in another PR.

One thing i want to think of:

1. no error is shown if enter more than 12 words, for example i enter 
`beyond stage sleep clip because twist token leaf atom beauty genius food business side grid unable middle armed observe pair crouch tonight away coconut` and i **can**  proceed on desktop without any pop-ups and i **cant** proceed on mobile - done button and enter are disabled

image

image

at least we should align the behaviour through the platforms. @rasom @goranjovic ?

<blockquote><div><strong><a href="https://ethstatus.testrail.net/index.php?/cases/view/5363">Login - TestRail</a></strong></div></blockquote>

**Comment by goranjovic** [comment]
@asemiankevich allowed number of words can be 12, 15, 18, 21 or 24. apparently some apps other than status use the other word counts.

**Comment by asemiankevich** [comment]
@goranjovic that is correct, my question is how to handle this? we have 2 different ways (having 18 words passphrase):
- desktop allows to enter this phrase and proceed with recovering (no pop-ups, errors etc)
- mobile does not allow to proceed - buttons are inactive.

So what is expected? I want to have same behavior though platforms cc @rasom

**Review by flexsurfer — APPROVED** [review]

**Comment by asemiankevich** [comment]
looks good, i might be grabbing wrong mobile build

**Pull request merged**
