### PR TITLE
kotlinify parts of status module, package & Utils

### PR DESCRIPTION
**Pull request by siddarthkay**
parent issue: https://github.com/status-im/status-mobile/issues/18310

## Summary

This PR converts the following `Java` files to `Kotlin` : 

- modules/react-native-status/android/src/main/java/im/status/ethereum/module/StatusModule.java
- modules/react-native-status/android/src/main/java/im/status/ethereum/module/StatusPackage.java
- modules/react-native-status/android/src/main/java/im/status/ethereum/module/Utils.java

## Testing notes
This PR converts Java code to `Kotlin` which involves a helper function that is used to execute `statusgo` methods.
It may impact everything or nothing.

## Platforms
- Android

status: ready

### CODE REVIEW

**Review by mohsen-ghafouri — APPROVED** [review]

**Review by jo-mut — APPROVED** [review]

**Review by jo-mut — APPROVED** [review]

**Review by alwx — APPROVED** [review]

**Comment by VolodLytvynenko** [comment]
Hey @siddarthkay, thank you for the PR. Are there any known areas that might have been impacted by this PR? It would be very helpful

**Comment by siddarthkay** [comment]
Hi @VolodLytvynenko : This PR impacts a function which is used for executing almost all calls to status-go.
So either everything works or nothing works :D 
If that makes any sense :)

**Comment by VolodLytvynenko** [comment]
> Hi @VolodLytvynenko : This PR impacts a function which is used for executing almost all calls to status-go. So either everything works or nothing works :D If that makes any sense :)

@siddarthkay Got it :) Thanx

**Comment by VolodLytvynenko** [comment]
Hi @siddarthkay thank you for PR. No issues from my side. Ready to be merged

**Pull request merged**
