### PR TITLE
update default wallet account's color to blue for old mobile user

### LINKED ISSUE #20476: The wallet is shown as white after upgrade from V1 to V2
Follow up for https://github.com/status-im/status-mobile/pull/20151
### Steps:
1. Create new user in old apk https://github.com/status-im/status-mobile/pull/20123
2. Install new apk
3. CHeck how wallet is migrated

### Actual result:
The wallet is shown as white.
image

### Expected result:
The wallets should be shown with the default color (blue).
image

### ENV:
Nightly 17 Jun 2024

### PR DESCRIPTION
**Pull request by qfrank**
fixes #20476

status-go [PR](https://github.com/status-im/status-go/pull/5594)

status: ready

### CODE REVIEW

**Review by Parveshdhull — APPROVED** [review]

**Review by ajayesivan — APPROVED** [review]

**Review by ilmotta — APPROVED** [review]

**Review by J-Son89 — APPROVED** [review]

**Comment by mmilad75** [comment]
It's working properly, but it's still missing the emoji. Thanks @qfrank 

https://github.com/user-attachments/assets/cade379a-e16c-49d2-a89c-242866ddc2d2

**Comment by churik** [comment]
It works, indeed!
Don't upgrade status-go version in our repo now, please, we want to cherry-pick it to status-go release.

I'll close the PR, I believe it was for testing purposes

**Comment by qfrank** [comment]
> It's working properly, but it's still missing the emoji. Thanks @qfrank
> 
>  Screen_Recording_20240729_135246_Status.PR.mp4

Sorry, just know this, I'll add it as well, thank you @mmilad75

**Comment by qfrank** [comment]
reopen for testing emoji

**Comment by qfrank** [comment]
moved test PR [here](https://github.com/status-im/status-mobile/pull/20917)

test result looks good:
IMG_7855
IMG_2027
IMG_6294
IMG_7552

cc @mmilad75 @churik

**Pull request closed without merging**
