### PR TITLE
iOS registration (#232), other iOS fixes

### PR DESCRIPTION
**Pull request by alwx**
1. Registration works on iOS, layout looks the way it should;
2. Lots of small fixes for iOS;
3. iOS Info.plist modifications to make camera and storage-specific components work correctly on iOS;
4. The project became buildable in XCode 8 with iOS 10 SDK;
5. Camera-related updates (iOS camera works on a real device);
6. Integration of `react-native-drawer-layout` library.

Everything kinda works, but there are still some problems with hot reloading, second launch, etc. All those things will be fixed in some other task.

Also fixes https://github.com/status-im/status-react/issues/183

### CODE REVIEW

**Comment by rasom** [comment]
Some `text-input` elements are prefilled with the first 1-2 symbols from the value of `!keypair`. It sounds a bit weird, but happens when you create a new account.

**Comment by rasom** [comment]
`./run-osx.sh real` output:
```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> A problem occurred configuring project ':react-native-image-crop-picker'.
   > Could not resolve all dependencies for configuration ':react-native-image-crop-picker:_debugCompile'.
      > Could not find com.android.support:appcompat-v7:24.2.0.
        Searched in the following locations:
            file:/Users/rasom/.m2/repository/com/android/support/appcompat-v7/24.2.0/appcompat-v7-24.2.0.pom
            file:/Users/rasom/.m2/repository/com/android/support/appcompat-v7/24.2.0/appcompat-v7-24.2.0.jar
            https://jcenter.bintray.com/com/android/support/appcompat-v7/24.2.0/appcompat-v7-24.2.0.pom
            https://jcenter.bintray.com/com/android/support/appcompat-v7/24.2.0/appcompat-v7-24.2.0.jar
            file:/Users/rasom/clj/status-react/node_modules/react-native/android/com/android/support/appcompat-v7/24.2.0/appcompat-v7-24.2.0.pom
            file:/Users/rasom/clj/status-react/node_modules/react-native/android/com/android/support/appcompat-v7/24.2.0/appcompat-v7-24.2.0.jar
            file:/Users/rasom/clj/status-react/node_modules/react-native-image-crop-picker/android/libs/appcompat-v7-24.2.0.jar
            file:/Users/rasom/clj/status-react/node_modules/react-native-image-crop-picker/android/libs/appcompat-v7.jar
            http://185.90.37.89:8081/artifactory/libs-release-local/com/android/support/appcompat-v7/24.2.0/appcompat-v7-24.2.0.pom
            http://185.90.37.89:8081/artifactory/libs-release-local/com/android/support/appcompat-v7/24.2.0/appcompat-v7-24.2.0.jar
            https://jitpack.io/com/android/support/appcompat-v7/24.2.0/appcompat-v7-24.2.0.pom
            https://jitpack.io/com/android/support/appcompat-v7/24.2.0/appcompat-v7-24.2.0.jar
            file:/usr/local/Cellar/android-sdk/24.4.1_1/extras/android/m2repository/com/android/support/appcompat-v7/24.2.0/appcompat-v7-24.2.0.pom
            file:/usr/local/Cellar/android-sdk/24.4.1_1/extras/android/m2repository/com/android/support/appcompat-v7/24.2.0/appcompat-v7-24.2.0.jar
        Required by:
            StatusIm:react-native-image-crop-picker:unspecified > com.facebook.react:react-native:0.33.0
      > Could not find com.android.support:appcompat-v7:24.2.0.
        Searched in the following locations:
            file:/Users/rasom/.m2/repository/com/android/support/appcompat-v7/24.2.0/appcompat-v7-24.2.0.pom
            file:/Users/rasom/.m2/repository/com/android/support/appcompat-v7/24.2.0/appcompat-v7-24.2.0.jar
            https://jcenter.bintray.com/com/android/support/appcompat-v7/24.2.0/appcompat-v7-24.2.0.pom
            https://jcenter.bintray.com/com/android/support/appcompat-v7/24.2.0/appcompat-v7-24.2.0.jar
            file:/Users/rasom/clj/status-react/node_modules/react-native/android/com/android/support/appcompat-v7/24.2.0/appcompat-v7-24.2.0.pom
            file:/Users/rasom/clj/status-react/node_modules/react-native/android/com/android/support/appcompat-v7/24.2.0/appcompat-v7-24.2.0.jar
            file:/Users/rasom/clj/status-react/node_modules/react-native-image-crop-picker/android/libs/appcompat-v7-24.2.0.jar
            file:/Users/rasom/clj/status-react/node_modules/react-native-image-crop-picker/android/libs/appcompat-v7.jar
            http://185.90.37.89:8081/artifactory/libs-release-local/com/android/support/appcompat-v7/24.2.0/appcompat-v7-24.2.0.pom
            http://185.90.37.89:8081/artifactory/libs-release-local/com/android/support/appcompat-v7/24.2.0/appcompat-v7-24.2.0.jar
            https://jitpack.io/com/android/support/appcompat-v7/24.2.0/appcompat-v7-24.2.0.pom
            https://jitpack.io/com/android/support/appcompat-v7/24.2.0/appcompat-v7-24.2.0.jar
            file:/usr/local/Cellar/android-sdk/24.4.1_1/extras/android/m2repository/com/android/support/appcompat-v7/24.2.0/appcompat-v7-24.2.0.pom
            file:/usr/local/Cellar/android-sdk/24.4.1_1/extras/android/m2repository/com/android/support/appcompat-v7/24.2.0/appcompat-v7-24.2.0.jar
        Required by:
            StatusIm:react-native-image-crop-picker:unspecified > com.yalantis:ucrop:2.2.0-native

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 12.751 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html
```

**Comment by alwx** [comment]
@rasom you need to update your support library in Android SDK manager

**Comment by rasom** [comment]
thanks, @alwx

**Pull request merged**
