### PR TITLE
Add 6 new languages as public channels in the localized language. Closes #4753

### LINKED ISSUE #4753: Add more localized channels to public chats for beta
User Story
As a user, I want to discover new public chats so that I can discuss topics of interest in my localized language.

As a core contributor, I want to also be able to join the topic relevant to my dialect 

Description
Type: Feature

Summary:

Add 5 new languages as public channels in the localized language
Chinese: #中文
Japanese: #日本語
Korean: #한국어
Russian: #русский
Spanish: #español

Expected behavior
The default public chat list includes 5 new language options by default as default public channels.

### PR DESCRIPTION
**Pull request by pedropombeiro**
Closes #4753 

### Summary:

[comment]: # (Summarise the problem and how the pull request solves it)
This PR adds 6 new public chats to the default chat list. The Russian chat name was adapted according to a suggestion by Igor.

### Review notes (optional):

Test sending/receiving messages in each of these channels. 

status: ready

### CODE REVIEW

**Review by mandrigin — APPROVED** [review]
lgtm

**Review by oskarth — APPROVED** [review]

**Review by janherich — APPROVED** [review]

**Comment by churik** [comment]
1) At attempt to join Chinese channel: `#status 中文` got an error:
chinese
TF session: [01:10-01:20](https://app.testfairy.com/projects/4803590-status/builds/8500352/sessions/4394432251/?accessToken=XqoSuiDnQGIhWEC7lMmsa2LxHuE)
Can be reproduced on both Android and IOS.
The error appears only once.

2) When you type `Hola! Como están? Ñ` in #español channel, got an error:
esapn
TF session: [18:00-18:30](https://app.testfairy.com/projects/4803590-status/builds/8500352/sessions/4394432251/?accessToken=XqoSuiDnQGIhWEC7lMmsa2LxHuE)

If I should create a separate issue for (2), please let me know.

**Comment by cammellos** [comment]
@churik ready to be tested again!

**Comment by churik** [comment]
Tested ok both iOS and Android:

Fresh install: 
- join to every of 6 chats
- send a message in chat language in each chat
- create a new public channel
- message in Spanish in 1-1 chat

**Pull request merged**
