### PR TITLE
Ensure shell.nix uses same nixpkgs as the rest of the environment

### PR DESCRIPTION
**Pull request by pedropombeiro**
[comment]: # (Please replace ... with your information. Remove < and >)
[comment]: # (To auto-close issue on merge, please insert the related issue number after # i.e fixes #566)

fixes https://github.com/status-im/infra-ci/issues/6

### Summary

[comment]: # (Summarise the problem and how the pull request solves it)
This PR ensures a single source of truth for our pinned version of nixpkgs and ensures that shell.nix follows it.

status: ready

### CODE REVIEW

**Comment by pedropombeiro** [comment]
What the hell is Wrike doing???

**Comment by jakubgs** [comment]
Wtf, why can't I reopen this?

**Comment by oskarth** [comment]
@PombeirP it was probably marked as closed because it was completed in Wrike.

@jakubgs Probably because another PR was opened from the same branch https://github.com/status-im/status-react/pull/8436

**Comment by jakubgs** [comment]
Ah, the same branch PR makes sense.

**Pull request closed without merging**
