### PR TITLE
chore: Update release branch 2.30.x

### PR DESCRIPTION
**Pull request by ilmotta**
### Cherry-picks (oldest first):

- https://github.com/status-im/status-mobile/pull/20924
- https://github.com/status-im/status-mobile/pull/20893
- https://github.com/status-im/status-mobile/pull/20891
- https://github.com/status-im/status-mobile/pull/20929
- https://github.com/status-im/status-mobile/pull/20945
- https://github.com/status-im/status-mobile/pull/20942
- https://github.com/status-im/status-mobile/pull/20943

### New changes from status-go `release` (oldest first)

- https://github.com/status-im/status-go/pull/5637
- https://github.com/status-im/status-go/pull/5635
- https://github.com/status-im/status-go/pull/5632
- https://github.com/status-im/status-go/pull/5644
- https://github.com/status-im/status-go/pull/5649
- https://github.com/status-im/status-go/pull/5625

### Waiting

- Unmerged on mobile https://github.com/status-im/status-mobile/pull/20931

status: ready

### CODE REVIEW

**Comment by ilmotta** [comment]
@churik, let me know of any other commits we may need or add them directly in the PR description. The description has a section named `Waiting` where I added all the links for PRs that should be merged and/or available in status-go release branch **before** we merge this mobile PR.

**Review by churik — APPROVED** [review]

**Comment by churik** [comment]
New one: 
https://github.com/status-im/status-mobile/pull/20941

**Comment by ilmotta** [comment]
@churik, do you think we need anything extra to be included in this PR, apart from https://github.com/status-im/status-mobile/pull/20931? I was thinking of merging this one now because we already accumulated quite a few commits in back/front repos.

**Comment by churik** [comment]
Also these PRs are ready:
https://github.com/status-im/status-mobile/pull/20942 
https://github.com/status-im/status-mobile/pull/20945
https://github.com/status-im/status-mobile/pull/20926
https://github.com/status-im/status-mobile/pull/20943 (if the comments were addressed and no need to retest)


Yes, let's cherry pick these and merge this PR, and also please update status-go

**Comment by churik** [comment]
And also this one, bugfix: https://github.com/status-im/status-mobile/pull/20852

**Comment by clauxx** [comment]
@churik https://github.com/status-im/status-mobile/pull/20943 was merged and can be cherry-picked

**Pull request merged**
