### PR TITLE
Testing different go changes required for release 2.31

### PR DESCRIPTION
**Pull request by pavloburykh**
PR is created to test `806b2587dbbc6730129bab84689559895c3dcaf2` commit which includes following changes:

https://github.com/status-im/status-go/pull/5950
https://github.com/status-im/status-go/pull/5924
https://github.com/status-im/status-go/pull/5941
https://github.com/status-im/status-go/pull/5945

-o-

Bumped to status-go commit `5a19cc2a6ebc23d5dd8fcac2530a2897b0443e42`

to include https://github.com/status-im/status-go/pull/5957 as well

### CODE REVIEW

**Comment by VolodLytvynenko** [comment]
I'm not sure if this is related to the current PR. I've never swapped SNT on L1; I usually swap tokens with lower fees like DAI, USDC, or ETH on this network. Should it be fixed within the scope of this PR?

## ISSUE 1: "Spending cap failing" Error is shown  when attempting to swap SNT

### Steps:
1. Recover user with SNT tokens.
2. Go to the swap page.
3. Attempt to approve SNT for the swap transaction.

### Actual Result:
"Spending cap failing" Error is shown  when attempting to swap SNT

https://github.com/user-attachments/assets/ff75eac3-06fb-49c2-8e9e-3cd61b424f04


### Expected Result:
The approval should be successful 

### Devices:
Pixel 7a, Android 13

### Logs:
[Status-debug-logs (1).zip](https://github.com/user-attachments/files/17395009/Status-debug-logs.1.zip)

**Comment by churik** [comment]
So let me check what we should expect from these PRs all together:
1) https://github.com/status-im/status-go/pull/5950 - should in theory fix limit problem (if we're hitting it?), we have no means to test it, can someone help to look in the proxy logs to identify that we do not have this error anymore (and we need text of error in this case)?

2) https://github.com/status-im/status-go/pull/5924 - should provide more monitoring, can someone help us to check that?

3) https://github.com/status-im/status-go/pull/5941 - re-ordering; the same issue with proxy - idk how to identify that order is right.

4) https://github.com/status-im/status-go/pull/5945 - just a regression and should decrease the number of requests the we send to providers

Overall we consider PR as succesfull:
- if we can request balance from Arb network (doesn't work from today morning)
- if https://github.com/status-im/status-mobile/issues/21424  and https://github.com/status-im/status-mobile/issues/21423 and https://github.com/status-im/status-mobile/issues/21180 are fixed, as these errors were from Grove providers
- no new regression in send / bridge / swap

If someone can help us to analyze logs from kibana or use any other tools to identify how it really works with 3d party services, please, let us know.

As now it seems we're just trying to guess whether it works or not.

@saledjenic @friofry @shivekkhurana

**Comment by friofry** [comment]
Yeah sounds correct, RPS limiter removal might help with the circuit breaker problem. And Goerli fix doesn't affect non-testnet. 

> If someone can help us to analyze logs from kibana or use any other tools to identify how it really works with 3d party services, please, let us know.

After changing provider order, if we hit grove, then we should check the logs and see why nodefleet and infura are failing.

Please ping me if you need help analysing logs ([nginx](https://kibana.infra.status.im/goto/17c267f0-8af2-11ef-bfa2-75c6d129a2cb) and [status-go](https://github.com/status-im/status-go/pull/5924#issuecomment-2413608076))

**Comment by pavloburykh** [comment]
This issue https://github.com/status-im/status-mobile/issues/21449 is still reproducible in this PR. So we still facing problem when balances are not fetched on certain network. This time it is Arbitrum. Recently we encountered same issue with Optimism. 

Here are the log from this PR 

[Status-debug-logs - 2024-10-16T190825.193.zip](https://github.com/user-attachments/files/17399118/Status-debug-logs.-.2024-10-16T190825.193.zip)

**Comment by friofry** [comment]
> This issue #21449 is still reproducible in this PR. So we still facing problem when balances are not fetched on certain network. This time it is Arbitrum. Recently we encountered same issue with Optimism.
> 
> Here are the log from this PR
> 
> [Status-debug-logs - 2024-10-16T190825.193.zip](https://github.com/user-attachments/files/17399118/Status-debug-logs.-.2024-10-16T190825.193.zip)

Thanks for the logs

here is a error log. It could be a combination of client logic bugs:
```
error="json: cannot unmarshal string into Go value of type map[string]float64 - {\"Response\":\"Error\",\"Message\":\"cccagg_or_exchange market does not exist for this coin pair (11155111-ZEENUS-USD), cccagg_or_exchange market does not exist for this coin pair (11155111-USDC-USD), cccagg_or_exchange market does not exist for this coin pair (11155420-ETH-USD), cccagg_or_exchange market does not exist for this coin pair (11155111-WEENUS-USD), cccagg_or_exchange market does not exist for this coin pair (11155111-WETH9-USD), cccagg_or_exchange market does not exist for this coin pair (11155111-UNI-USD), cccagg_or_exchange market does not exist for this coin pair (11155420-USDC-USD), cccagg_or_exchange market does not exist for this coin pair (11155111-EUROC-USD), cccagg_or_exchange market does not exist for this coin pair (11155111-XEENUS-USD), cccagg_or_exchange market does not exist for this coin pair (421614-USDC-USD), cccagg_or_exchange market does not exist for this coin pair (11155111-WETH-USD), cccagg_or_exchange market does not exist for this coin pair (11155111-YEENUS-USD), cccagg_or_exchange market does not exist for this coin pair (11155111-STT-USD), cccagg_or_exchange market does not exist for this coin pair (11155111-ETH-USD), cccagg_or_exchange market does not exist for this coin pair (421614-ETH-USD), cccagg_or_exchange market does not exist for this coin pair (11155111-DAI-USD)\",\"HasWarning\":false,\"Type\":2,\"RateLimit\":{},\"Data\":{},\"Cooldown\":0}"
```


1. 
We try to parse prices from a response with error
```
error="json: cannot unmarshal string into Go value of type map[string]float64 - 
```
The code is probably called by [FetchPrices](https://github.com/status-im/status-go/blob/385933a60dc0182eb0da9575d582739fe5d20010/services/wallet/market/market.go#L246) in market.go:
```
prices := response.(map[string]map[string]float64)
```

2.
```
... cccagg_or_exchange market does not exist for this coin pair (11155111-ZEENUS-USD), ...
```
and the second error is related to `cccagg_or_exchange`. Not sure why it happens

3.

```
"fsyms param is invalid. (fsyms length is higher than maxlength: 300) provider=cryptocompare
```
It's from [cryptocompare/client.go](https://github.com/status-im/status-go/blob/1d173734a608de2d71480d6ad39f4559f11a75e2/services/wallet/thirdparty/cryptocompare/client.go#L83) **FetchPrices**

4.

```
unsuccessful request: 429 Too Many Requests" provider=rarible1
```


The proxy seems working fine:
```
{
  "statusPerChainPerProvider": {
    "11155111": {
      "status-proxy-0": {
        "name": "status-proxy-0",
        "last_success_at": "2024-10-16T15:25:43.692430957Z",
        "last_error_at": "0001-01-01T00:00:00Z",
        "last_error": null,
        "status": "up"
      }
    },
    "11155420": {},
    "421614": {
      "status-proxy-0": {
        "name": "status-proxy-0",
        "last_success_at": "2024-10-16T15:25:43.680861738Z",
        "last_error_at": "0001-01-01T00:00:00Z",
        "last_error": null,
        "status": "up"
      }
    }
  }
}
```

**Comment by saledjenic** [comment]
From the attached logs in this comment https://github.com/status-im/status-mobile/pull/21445#issuecomment-2416569837 I see that 2 approvals failed, but the both txs have empty data and doesn't call approve function:
- https://etherscan.io/tx/0xcf08a709d5b7bc9ad58d82e1cc96f77eb1af153f01530c389fc101a1a5a75c79
- https://etherscan.io/tx/0x0af50cc91d4653ee3c8bd094f86db60c27ec4f0ddd74cbc4546cb1af2bb353db

----
> https://github.com/status-im/status-go/pull/5950 - should in theory fix limit problem (if we're hitting it?), we have no means to test it, can someone help to look in the proxy logs to identify that we do not have this error anymore (and we need text of error in this case)?

In theory, yes, but as I mentioned in Discord, can be also up to wrongly configured/used hystrix. We need to inspect that.

> https://github.com/status-im/status-go/pull/5941 - re-ordering; the same issue with proxy - idk how to identify that order is right.

You can check that in the log, for error that you're getting and see the order of errors. So error in the log should have firstly error from `api.status.im/nodefleet/`, then `api.status.im/infura/`, then `infura.io/v3/`, then `api.status.im/grove/` and at the end from `rpc.grove.city/v1/`, so that's the worst case. In theory `api.status.im/nodefleet/` should not have error.

**Comment by VolodLytvynenko** [comment]
hi @saledjenic I checked this issue on desktop as well using [today's latest master](https://ci.status.im/job/status-desktop/job/nightly/558/) and was able to approve SNT once, but I couldn't approve it a second and more time. Below are the steps I followed

### Preconditions:
Current User has:
- 15500 SNT
- 0.21 ETH

### Steps:
1. Select L1 network.
2. Enter 13,500 SNT to swap to ETH.
3. Approve the transaction (approval is successful https://etherscan.io/tx/0x8c5a4450b2a7eed54a9376b0848b88b41854d5df893923688197d3fa68ac6bf7).
4. Enter a higher amount of SNT (e.g., between 13,501 and 15,000 SNT).

### Actual result:
image

### Expected result:
Users can click approve and navigate to approved page

### Logs:
Desktop: [geth copy.log](https://github.com/user-attachments/files/17409536/geth.copy.log)

**Comment by VolodLytvynenko** [comment]
@saledjenic Just FYI. It's very possible that this [issue](https://github.com/status-im/status-mobile/pull/21445#issuecomment-2416569837
) related to the current PR. I successfully approved SNT (this works only if the user does not have approved SNT and this approval is the first) on the latest nightly build on both Desktop and Mobile, but when I tried it again in the build of the current PR, I encountered the same issue again.

**Comment by VolodLytvynenko** [comment]
[this issue](https://github.com/status-im/status-mobile/pull/21445#issuecomment-2419023534)is present on the latest master as well. I just [tracked it](https://github.com/status-im/status-mobile/issues/21424) separately

**Comment by saledjenic** [comment]
@VolodLytvynenko the log is useless. :( The only I could see there is this error `err="status-proxy-0.error: execution reverted"` and nothing else, but that somehow looks like provider issue.

>  I successfully approved SNT (this works only if the user does not have approved SNT and this approval is the first) on the latest nightly build on both Desktop and Mobile, but when I tried it again in the build of the current PR, I encountered the same issue again.

If it passed once, means the code is good. Also if new approval has the same or lower value than previously approved, then you won't be ask to approve again, but if the value is higher then you should approve that higher value and that's a new tx, and has nothing with previously approved value. Also since the new value is higher than previous, but still less than the total balance, there is no reason for getting an error. I can only blame providers for that.

**Comment by churik** [comment]
@saledjenic what can we do to make log not useless? do we have any ideas? 

@friofry new health monitoring doesn't give us more clarity? 

because seems we're blind now - and might be `status-proxy-0.error: execution reverted` is coming again from Grove, and we don't know when the app is falling back to Grove and why.

**Comment by churik** [comment]
I mean based on https://github.com/status-im/status-mobile/issues/21424#issuecomment-2410843323 - it is Grove in Swap. Here we changed the order, why it is still Grove then?

**Comment by VolodLytvynenko** [comment]
> If it passed once, means the code is good. Also if new approval has the same or lower value than previously approved, then you won't be ask to approve again, but if the value is higher then you should approve that higher value and that's a new tx, and has nothing with previously approved value. Also since the new value is higher than previous, but still less than the total balance, there is no reason for getting an error. I can only blame providers for that.

Hi, @saledjenic @churik perhaps this could be the solution to the issue. When I try to approve ERC-20 assets on other apps (like Uniswap, MetaMask), they often set the approval to "unlimited," meaning you don’t need to approve the same asset again. This could prevent the error on the second approval on our side. However, I’m not sure if it’s technically possible for us to implement unlimited approval on our side. WDYT?

image

**Comment by churik** [comment]
@saledjenic can you please point us to the same PR in desktop in order to verify?

Fo now:
- on desktop master: reproducible
- on desktop PR: didn't check
- on mobile master: reproducible
- on mobile PR: reproducible

So perhaps we're checking the wrong places, but to my understanding so far we're not able to approve SNT once more (may be not only SNT actually) if the approve value is bigger than the previous one.

**Comment by VolodLytvynenko** [comment]
Here's a quick summary of the swap feature for the current PR:

- [Issue 1](https://github.com/status-im/status-mobile/pull/21445#issuecomment-2416569837): This issue is reproducible for me on mobile with the current build, but I was not able to reproduce it in the [Desktop PR](https://github.com/status-im/status-desktop/pull/16537) or latest desktop masters. This is reproducible only on mobile of current PR

**Mobile logs:** 
[Status-debug-logs.1.zip](https://github.com/user-attachments/files/17413287/Status-debug-logs.1.zip)


- [Issue 2](https://github.com/status-im/status-mobile/issues/21424): This issue is not related to the current PR and exists in both the Mobile and Desktop latest masters. I also tested it within the [Desktop PR](https://github.com/status-im/status-desktop/pull/16537), and it is reproducible there as well. I've tracked this issue separately  [here](https://github.com/status-im/status-mobile/issues/21424) 

**Desktop logs:** 
[geth copy.log](https://github.com/user-attachments/files/17413255/geth.copy.log)
**Mobile logs:**
[logs.zip](https://github.com/user-attachments/files/17413273/logs.zip)

**Comment by VolodLytvynenko** [comment]
just added logs for both issues in [comment](https://github.com/status-im/status-mobile/pull/21445#issuecomment-2419533023) above

**Comment by saledjenic** [comment]
> Should we consider then to make unlimited approve like Uniswap does(and basically a lot of other DeFi that I saw)? That will resolve the issue by itself.

I guess yes (we can do that only if user is about to swap SNT).

> Can be deprioritized from 2.31 as 

It can be with lower priority, but we need to keep that in mind and don't log issues for that. 

> it is reproducible only if user swapped less SNT that approved

Not exactly like that, the issue is happening if the user already has approval for swaping X SNT, and wants to swap Y now, where X<Y. Now based on that usecaed we should re-think what to do, but setting unlimited approval for SNT only is for sure one of solutions.

> https://github.com/status-im/status-mobile/issues/21180 - bridge; can sometimes currently work in develop as well - so reproducible sometimes

As said in comment in that issue, I don't have other explanation atm except that's happening due to some chain issues, cause checking that the tx is packed and sent well, so there's nothing else specially that we can do after that. One possibility could be that gas goes too high in meantime, cause bridging usually takes a bit longer than a normal tx.

> @saledjenic in geth.log I see no sequence of providers, so I have no idea how to check it.

If you don't see it, then it's good. :) It means that the changes work.

**Comment by VolodLytvynenko** [comment]
[issue 1](https://github.com/status-im/status-mobile/pull/21445#issuecomment-2416569837) is fixed after [latest commit](https://github.com/status-im/status-mobile/pull/21445/commits/e03757b4d4bf68ed67a4a4e4fb3455686366baab). @dlipicar thank you!

**Comment by churik** [comment]
so what we have now: 
1) [Issue 1](https://github.com/status-im/status-mobile/pull/21445#issuecomment-2416569837) - **only mobile PR build**, mentioned here

**Should we report it for mobile team only?**

2) [Issue 2](https://github.com/status-im/status-mobile/issues/21424) - according to @saledjenic it is a contract problem, so we can't really fix that now.

Should we consider then to make unlimited approve like Uniswap does(and basically a lot of other DeFi that I saw)? That will resolve the issue by itself.
**Can be deprioritized from 2.31 as it is reproducible only if user swapped less SNT that approved**

3) Other issues: 

- https://github.com/status-im/status-mobile/issues/21423 - Arbitrum-related, so provider.
- https://github.com/status-im/status-mobile/issues/21449 - Arbitrum-related, so provider.
- https://github.com/status-im/status-mobile/issues/21180 - bridge; can sometimes currently work in `develop` as well - so reproducible sometimes

**Can be deprioritized from 2.31 as again can be network or provider related**

As for functionality:
- @saledjenic in geth.log I see no sequence of providers, so I have no idea how to check it. 
- @friofry just based on data for the last 15 minutes from kibana for `proxy.test`
nidefleet / infura / grove - 665 / 87 / 184 - it **seems** that it is right, but for real check we need to find the way to filter logs by device


4) @dlipicar 
as for https://github.com/status-im/status-mobile/pull/21445#issuecomment-2417307858: we have fresh logs, if you point us where to look at or check by yourself, would be amazing.
[Status-debug-logs - 2024-10-17T180228.278.zip](https://github.com/user-attachments/files/17414870/Status-debug-logs.-.2024-10-17T180228.278.zip)


### Conclusion
I don't see any blockers for now related to status-go itself. 
So we need to wait for clear confirmation that all mentioned above is right and issues mentioned [here](https://github.com/status-im/status-mobile/pull/21445#issuecomment-2417307858) are fixed and we're OK to merge. 

also it seems useless to try to check some funtionalities while one of the chain is out of sync.

cc @shivekkhurana @alaibe

**Comment by saledjenic** [comment]
> @saledjenic in geth.log I see no sequence of providers, so I have no idea how to check it.

If you don't see it, then it's good. :) It means that changes work.

**Comment by dlipicar** [comment]
@churik
The good: No more errors about the 300 character limit
The bad: Still getting one error

```
WARN [10-17|13:55:24.101|github.com/status-im/status-go/circuitbreaker/circuit_breaker.go:180]                                             hystrix error                            error="no data found - {\"Response\":\"Error\",\"Message\":\"cccagg_or_exchange market does not exist for this coin pair (1-IOTX-USD), cccagg_or_exchange market does not exist for this coin pair (10-SUSD-USD), cccagg_or_exchange market does not exist for this coin pair (1-ELON-USD), cccagg_or_exchange market does not exist for this coin pair (1-TRU-USD), cccagg_or_exchange market does not exist for this coin pair (42161-MOG-USD), cccagg_or_exchange market does not exist for this coin pair (42161-BOND-USD), cccagg_or_exchange market does not exist for this coin pair (42161-USDC.E-USD), cccagg_or_exchange market does not exist for this coin pair (1-POWR-USD), cccagg_or_exchange market does not exist for this coin pair (1-BAND-USD), cccagg_or_exchange market does not exist for this coin pair (1-JASMY-USD), cccagg_or_exchange market does not exist for this coin pair (1-MKR-USD), cccagg_or_exchange market does not exist for this coin pair (1-MATH-USD), cccagg_or_exchange market does not exist for this coin pair (10-BAL-USD), cccagg_or_exchange market does not exist for this coin pair (1-ALICE-USD), cccagg_or_exchange market does not exist for this coin pair (1-CBETH-USD), cccagg_or_exchange market does not exist for this coin pair (1-POND-USD), cccagg_or_exchange market does not exist for this coin pair (10-ZRO-USD), cccagg_or_exchange market does not exist for this coin pair (42161-1INCH-USD), cccagg_or_exchange market does not exist for this coin pair (1-ICOS-USD), cccagg_or_exchange market does not exist for this coin pair (1-GALA-USD), cccagg_or_exchange market does not exist for this coin pair (10-ARPA-USD), cccagg_or_exchange market does not exist for this coin pair (42161-KUJI-USD), cccagg_or_exchange market does not exist for this coin pair (42161-LINK-USD), cccagg_or_exchange market does not exist for this coin pair (1-MAGIC-USD), cccagg_or_exchange market does not exist for this coin pair (42161-ANKR-USD), cccagg_or_exchange market does not exist for this coin pair (1-BAL-USD), cccagg_or_exchange market does not exist for this coin pair (1-IDEX-USD), cccagg_or_exchange market does not exist for this coin pair (1-ERN-USD), cccagg_or_exchange market does not exist for this coin pair (10-LDO-USD), cccagg_or_exchange market does not exist for this coin pair (1-DPY-USD), cccagg_or_exchange market does not exist for this coin pair (42161-LUSD-USD), cccagg_or_exchange market does not exist for this coin pair (42161-ZRX-USD), cccagg_or_exchange market does not exist for this coin pair (42161-ACX-USD), cccagg_or_exchange market does not exist for this coin pair (1-BNT-USD), cccagg_or_exchange market does not exist for this coin pair (1-AGLD-USD), cccagg_or_exchange market does not exist for this coin pair (1-GAL-USD)\",\"HasWarning\":false,\"Type\":2,\"RateLimit\":{},\"Data\":{},\"Cooldown\":0}" provider=cryptocompare

```

Checked `requests.log`, saw this
```
t=2024-10-17T13:52:16+0000 lvl=dbug msg=callPrivateRPC params="[{\"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"wallet_fetchPrices\",\"params\":[[\"11155111-ZEENUS\",\"11155111-USDC\",\"11155420-ETH\",\"11155111-WEENUS\",\"11155111-WETH9\",\"11155111-UNI\",\"11155420-USDC\",\"11155111-EUROC\",\"11155111-XEENUS\",\"421614-USDC\",\"11155111-WETH\",\"11155111-YEENUS\",\"11155111-STT\",\"11155111-ETH\",\"421614-ETH\",\"11155111-DAI\"],[\"usd\"]]}]" resp="{\"jsonrpc\":\"2.0\",\"id\":1,\"result\":{}}" duration=556.929947ms
```

So, the mobile client seems to be calling `wallet_fetchPrices`, `wallet_fetchMarketValues` and `wallet_fetchTokenDetails` with a list of "ChainID-Symbol", where it should just be "Symbol". We'll need a mobile dev to look at this.

**Comment by friofry** [comment]
> So, the mobile client seems to be calling `wallet_fetchPrices`, `wallet_fetchMarketValues` and `wallet_fetchTokenDetails` with a list of "ChainID-Symbol", where it should just be "Symbol". We'll need a mobile dev to look at this.

we generate symbols with [this function](https://github.com/status-im/status-mobile/blob/2bf3e6ce1312c6faf4b714ab2165795574a3367b/src/status_im/contexts/wallet/tokens/data.cljs#L33):

```
(defn tokens-by-address
  [props]
  (tokens-by-key (assoc props
                        :key-fn
                        (fn [{:keys [chainId address]}]
                          (str chainId "-" address)))))
```
I'll try to quickly prepare a fix

**Comment by balducciv** [comment]
This has been tested from deskop app end and looks good.

**Comment by pavloburykh** [comment]
> fix(wallet): client should pass a list with "Symbol" and without "ChainID-" to status-go #21453

Hey @dlipicar @friofry Could you please help to understand how does this issue affect app functionality/UI? Asking, cause it seems for me little bit risky to implement the last minute fixes (before release cut) which we do not know how to test properly and what potential regression we can get. I would prefer to implement those fixes on mobile side after we cut the release branch unless you are sure it is safe to include into upcoming release. Please share your thoughts on that. Thank you!

**Comment by dlipicar** [comment]
> > fix(wallet): client should pass a list with "Symbol" and without "ChainID-" to status-go #21453
> 
> Hey @dlipicar @friofry Could you please help to understand how does this issue affect app functionality/UI? Asking, cause it seems for me little bit risky to implement the last minute fixes (before release cut) which we do not know how to test properly and what potential regression we can get. I would prefer to implement those fixes on mobile side after we cut the release branch unless you are sure it is safe to include into upcoming release. Please share your thoughts on that. Thank you!

@pavloburykh I really don't know... I can only say there must be some place where you're expecting a token price or market data and you're not getting it. There could be other parts of the app that expect a "Symbol" and are getting a "ChainID-Symbol".

**Comment by friofry** [comment]
> > fix(wallet): client should pass a list with "Symbol" and without "ChainID-" to status-go #21453
> 
> Hey @dlipicar @friofry Could you please help to understand how does this issue affect app functionality/UI? Asking, cause it seems for me little bit risky to implement the last minute fixes (before release cut) which we do not know how to test properly and what potential regression we can get. I would prefer to implement those fixes on mobile side after we cut the release branch unless you are sure it is safe to include into upcoming release. Please share your thoughts on that. Thank you!

The intention of #21453 was to highlight my findings. I have asked @alwx and @briansztamfater to review this idea.

**Comment by saledjenic** [comment]
@churik I've just updated this comment https://github.com/status-im/status-mobile/pull/21445#issuecomment-2419599912 please check it again, cause I see that from what I've wrote yesterday just a single thing was saved.

**Comment by pavloburykh** [comment]
> so what we have now:
> 
> 1. [Issue 1](https://github.com/status-im/status-mobile/pull/21445#issuecomment-2416569837) - **only mobile PR build**, mentioned here
> 
> **Should we report it for mobile team only?**
> 
> 2. [Issue 2](https://github.com/status-im/status-mobile/issues/21424) - according to @saledjenic it is a contract problem, so we can't really fix that now.
> 
> Should we consider then to make unlimited approve like Uniswap does(and basically a lot of other DeFi that I saw)? That will resolve the issue by itself. **Can be deprioritized from 2.31 as it is reproducible only if user swapped less SNT that approved**
> 
> 3. Other issues:
> 
> * [Consistent "Intrinsic gas too low" Error on swap page after transaction approval attempt on Arbitrum network #21423](https://github.com/status-im/status-mobile/issues/21423) - Arbitrum-related, so provider.
> * [Balances are not fetched on Arbitrum #21449](https://github.com/status-im/status-mobile/issues/21449) - Arbitrum-related, so provider.
> * [L1 - L2 transaction fails with `L1_ETH_BRG: Value does not match amount` in blockchain #21180](https://github.com/status-im/status-mobile/issues/21180) - bridge; can sometimes currently work in `develop` as well - so reproducible sometimes
> 
> **Can be deprioritized from 2.31 as again can be network or provider related**
> 
> As for functionality:
> 
> * @saledjenic in geth.log I see no sequence of providers, so I have no idea how to check it.
> * @friofry just based on data for the last 15 minutes from kibana for `proxy.test`
>   nidefleet / infura / grove - 665 / 87 / 184 - it **seems** that it is right, but for real check we need to find the way to filter logs by device
> 
> 4. @dlipicar
>    as for [Testing different go changes required for release 2.31 #21445 (comment)](https://github.com/status-im/status-mobile/pull/21445#issuecomment-2417307858): we have fresh logs, if you point us where to look at or check by yourself, would be amazing.
>    [Status-debug-logs - 2024-10-17T180228.278.zip](https://github.com/user-attachments/files/17414870/Status-debug-logs.-.2024-10-17T180228.278.zip)
> 
> ### Conclusion
> I don't see any blockers for now related to status-go itself. So we need to wait for clear confirmation that all mentioned above is right and issues mentioned [here](https://github.com/status-im/status-mobile/pull/21445#issuecomment-2417307858) are fixed and we're OK to merge.
> 
> also it seems useless to try to check some funtionalities while one of the chain is out of sync.
> 
> cc @shivekkhurana @alaibe

**UPDATE after re-testing today:**

 1. ~~[Issue 1](https://github.com/status-im/status-mobile/pull/21445#issuecomment-2416569837)~~ not reproducible. this issue might a random one, we will keep an eye on it during release testing cc @VolodLytvynenko 
 2. [Issue 2](https://github.com/status-im/status-mobile/issues/21424) - still reproducible, most likely a contract problem, so we can't really fix that now. There is a separate issue opened https://github.com/status-im/status-mobile/issues/21424

3. Other issues:

* ~~[Consistent "Intrinsic gas too low" Error on swap page after transaction approval attempt on Arbitrum network #21423](https://github.com/status-im/status-mobile/issues/21423) - Arbitrum-related, so provider.~~ not reproducible any more, issue will be closed. 
* ~~[Balances are not fetched on Arbitrum #21449](https://github.com/status-im/status-mobile/issues/21449) - Arbitrum-related, so provider.~~ not reproducible any more
* [L1 - L2 transaction fails with `L1_ETH_BRG: Value does not match amount` in blockchain #21180](https://github.com/status-im/status-mobile/issues/21180) - bridge; can sometimes currently work in `develop` as well - so reproducible sometimes. Still reproducible. 

cc @shivekkhurana

**Pull request closed without merging**
