### PR TITLE
Revert "don't auto-generate contact address from whisper pub key"

### PR DESCRIPTION
**Pull request by mandrigin**
This reverts commit b3416f5ad54d5b8fb8bb227db2850841156c2cc9.

status: ready

### CODE REVIEW

**Review by cammellos — APPROVED** [review]

**Comment by cammellos** [comment]
@gravityblast we are reverting this for now, as it wasn't tested through manual QA or e2e, could you please open a PR again so it can go through testing?
Thanks!

**Review by antdanchenko — APPROVED** [review]

**Comment by mandrigin** [comment]
let's make sure that e2e tests pass there and I will merge it

**Comment by antdanchenko** [comment]
@mandrigin there are 3 other PRs in queue for running e2e tests, so it will take ~1 hour. 
I'd prefer to merge this PR now in order to prevent those issues in other PRs which might be created/rebased during this hour

**Review by gravityblast — APPROVED** [review]

**Comment by mandrigin** [comment]
@antdanchenko okay, I will merge it then

**Pull request merged**
