### PR TITLE
[fix 5695] remove close icon in add to contacts bar

### LINKED ISSUE #5695: Tap on close icon doesn't close "Add to contacts" message
### Description

*Type*: Bug
*Summary*: when"Add to contacts" message appears in one chat in both devices - [Close] icon doesn't work; this only appears if you navigate to user profile and create chat via [Send transaction]. This option doesn't add user to contact automatically (unlike [Send message]). I'm suggesting to add user to contact list if using "Send transaction" (as it implemented for  "Send message") for consistency.

#### Expected behavior
message is closed

#### Actual behavior
message isn't closed; 
gh

### Reproduction

- Open Status
- Navigate to public chat
- Tap on user pic (who is not added to your contact list)
- Tap on [Send transaction]
- Tap on [Close] to close "Add to contacts"

### Additional Information
* Status version: nightly 29/08/2018
* Operating System: Android, iOS
* TF session: https://app.testfairy.com/projects/4803590-status/builds/8573399/sessions/4399754140/?accessToken=9SkMFRL4RFnCJbi0Eq-GIX0uVMg

<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803590-status/builds/8573399/sessions/4399754140/?accessToken=9SkMFRL4RFnCJbi0Eq-GIX0uVMg">TestFairy: Status 0.9.26 (6797) @2018</a></strong></div></blockquote>

### PR DESCRIPTION
**Pull request by yenda**
fix #5695 after discussing with @errorists it was concluded that there is no point fixing the close icon and that the best solution was to remove it. 

status: ready

### CODE REVIEW

**Review by vitvly — APPROVED** [review]

**Review by flexsurfer — APPROVED** [review]

**Comment by asemiankevich** [comment]
@yenda @errorists  the toolbar is now aligned to the right, is that expected? 

image

**Comment by errorists** [comment]
ewww, hell no

**Comment by asemiankevich** [comment]
@yenda please assist :)

**Comment by yenda** [comment]
@asemiankevich my bad, tested on Android:

Screenshot_1553164752

**Comment by asemiankevich** [comment]
thanks, looks good now!

**Pull request merged**
