### PR TITLE
[Fixes #7760] Allow copy/paste in browser URL bar

### LINKED ISSUE #7760: Paste and other options are not shown after long press on URL input, on DApps screen
Type: Bug

Summary: There are no `PASTE` and other options, after pressing on URL input for 10+ seconds

**Steps to reproduce:**
1. Create new account
2. Go to DApps screen
3. Hold URL input for several seconds

**Expected behavior**
PASTE and other options are shown, after pressing for ~2 seconds on URL input

**Additional Information**
Status version: 0.11.0
Operating System: Android

### PR DESCRIPTION
**Pull request by jeluard**
fixes #7760

### Summary

Allow copy/paste in browser URL bar

status: ready

### CODE REVIEW

**Review by goranjovic — APPROVED** [review]

**Review by flexsurfer — APPROVED** [review]

**Comment by yenda** [comment]
Is it intentional that the PR contains another commit that fixes another bug?

**Comment by jeluard** [comment]
@yenda Yes :)

**Comment by churik** [comment]
Test is failed due to infrastructure issue (faucet is not working)
Tested that can cut/copy/past (IOS and Android) on:
- browser field in Dapp tab;
- browser field when open link from public chat;
- browser field when open link when open particular DApp;
- browser field when open link when open ENS Dapp in profile;
- recipient in address;
- password and username input fields during sign up / login.

**Comment by jeluard** [comment]
@mandrigin Looks like the right commit message has been lost during your squash.
I was actually waiting for another PR before merging this one.

**Pull request merged**
