### PR TITLE
View token-gated requirements is shown for non toked gated communitie…

### LINKED ISSUE #20237: View token-gated requirements is shown for non toked gated communities (i.e. Status)
# Bug Report

## Problem 
"View token requirements" opens empty bottom sheet

https://github.com/status-im/status-mobile/assets/4557972/e07166ec-1c87-416b-bb64-3286ccae1e97

#### Expected behavior
no option if there is nothing to display or placeholder with explanation that community is free to join

### Reproduction

1. open options on Status community > View token requirements

### Additional Information

- Status version: release 2.29 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by flexsurfer**
fixes #20237

feature is not implemented so hide it under non implemented flag, no QA needed

### CODE REVIEW

**Review by Parveshdhull — APPROVED** [review]

**Review by jo-mut — APPROVED** [review]

**Comment by pavloburykh** [comment]
> feature is not implemented so hide it under non implemented flag, no QA needed

Hey @flexsurfer! Actually, this feature has been implemented. In case of token gated community it will show the requirements. 

So as was [mentioned](https://github.com/status-im/status-mobile/issues/20237#issue-2322876723) by @churik, expected result is:

```no option if there is nothing to display or placeholder with explanation that community is free to join```

Below is the video how it looks like in case of token gated community:

https://github.com/status-im/status-mobile/assets/97245802/4aeeb11d-1400-4b94-bcaa-8ed881fe0825

**Comment by flexsurfer** [comment]
thank @pavloburykh could you please explain how the community can be token gated but has no permissions? does that mean only some channels are gated in that token-gated community?

**Comment by pavloburykh** [comment]
> thank @pavloburykh could you please explain how the community can be token gated but has no permissions? does that mean only some channels are gated in that token-gated community?

by token gated community we mean only those communities that have set permissions for membership. Other kinds of permissions (Admin/channel permissions) do not make community token gated.

**Comment by flexsurfer** [comment]
thanks @pavloburykh should be fixed now

**Comment by pavloburykh** [comment]
I am temporary blocked from testing this PR, as my node is down and communities data is not fetched. Waiting for fix from Waku team.

**Comment by pavloburykh** [comment]
Hey @flexsurfer! Thanks for the fix. Please take a look at the issue:

### ISSUE 1 View token gated requirements option is not shown in communities with permissions

Please, also see the [comment](https://github.com/status-im/status-mobile/pull/20240#issuecomment-2139166941) below

Example of community https://status.app/c/ixaACiwKEnRva2VuIGdhdGVkIG1heSAzMBILZnNhZnNkYXNhZmQYASIHIzQzNjBERgM=#zQ3shahCqDog69f3hu6YdeZmdpyssWVUUMYuuxkTjvdnkjXLw

**Steps:** 

1. Open given community
2. Open community options
3. See if View token gated requirements option is there

**Actual result:** View token gated requirements option is not shown

Below is comparison PR with nightly


https://github.com/status-im/status-mobile/assets/97245802/84834a18-a663-4737-9a67-270dc191a97f

**Comment by pavloburykh** [comment]
@flexsurfer I propose to get back to your initial solution and just hide this option behind feature flag. We should not spend too much time on this issue now, as it is not a priority. After hiding this option I will log a separate issue so we can fix the logic of showing this option in future.

**Comment by flexsurfer** [comment]
thanks @pavloburykh done

**Comment by pavloburykh** [comment]
skipping manual qa, as we got back to safe changes.

**Pull request merged**
