### PR TITLE
Fixing fx arguments and event dispatches

### PR DESCRIPTION
**Pull request by yenda**
status: ready

### CODE REVIEW

**Review by janherich — APPROVED** [review]

**Review by oskarth — APPROVED** [review]

**Comment by yenda** [comment]
Branch: PR-3515
Android: https://i.diawi.com/eG7sPZ
iOS: https://i.diawi.com/bt1HQ9

I can't reproduce with the method described in the issue, I got the error again later with a different random scenario and was not able to reproduce it again. It's worth testing to see if it reduces the frequency of the error or it is just a coincidence.

**Comment by asemiankevich** [comment]
I have checked the PR and it seems I can receive the error more rarely however it still does exist
https://app.testfairy.com/projects/4803622-status/builds/7817735/sessions/19/?accessToken=Lgg4b8RcJjCE2svpcdaVm7lARLo

I also noticed that the error is less reproducible when you loggin out by clicking the log out button in profile . When killing the app - it is reproducible all the time.

**Review by flexsurfer — APPROVED** [review]

**Review by jeluard — APPROVED** [review]

**Comment by yenda** [comment]
I want to merge this but remove the mentions of #3505. I will investigate possible race condition in separate PR.

**Comment by yenda** [comment]
After 26 commits to build variants I am just gonna try to revert the swipe-to-delete commit

**Pull request merged**
