### PR TITLE
fixes #4846

### LINKED ISSUE #4846: Username emojis are not fully visible in home and chat screens
### Description

*Type*: Bug

*Summary*: Only on iOS, emojis in user name are cutted in following places:

- Home screen

- Chat screen

### Reproduction

- Open Status on iOS
- Go to Profile, edit username and set emoji there

### Additional Information
* Status version: 0.9.20
* Operating System: iOS
* Android works fine

### PR DESCRIPTION
**Pull request by 751895405**
fixes #4846 Username emojis are not fully visible in home and chat screens

### CODE REVIEW

**Review by goranjovic — APPROVED** [review]

**Review by yenda — APPROVED** [review]

**Review by rasom — APPROVED** [review]

**Review by yenda — APPROVED** [review]

**Comment by lukaszfryc** [comment]
@751895405 please rebase this branch to include latest changes from `develop`. Otherwise our CI (jenkins) will not be able to build it.

**Comment by yenda** [comment]
@751895405 Hi ! Thanks for you contribution, can you please run `git pull --rebase upstream develop` after adding the following to your config file in `.git/config`:
```
[remote "upstream"]
	url = git@github.com:status-im/status-react.git
	fetch = +refs/heads/*:refs/remotes/origin/*
```
That will rebase your develop branch onto our develop branch so that the CI can build it.
Cheers

**Comment by 751895405** [comment]
@yenda thank you remind me and I have done following your tips

**Comment by yenda** [comment]
@751895405 you still need to force push your branch on GitHub now I think you only did it locally

**Comment by vitvly** [comment]
@751895405 can you please force push the latest rebased version?

**Comment by lukaszfryc** [comment]
All looks fine. I tested on iPhone 8 (iOS 12) and Galaxy S8 (Android 8).

**Comment by yenda** [comment]
@751895405 thank you very much for your contribution ! Could you please squash you commits and sign them with pgp so we can merge the PR. 

If you don't know how to proceed github has some good guides on pgp https://help.github.com/articles/managing-commit-signature-verification/
For squashing : https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit

<blockquote><div><strong><a href="https://help.github.com/articles/managing-commit-signature-verification/">Managing commit signature verification - User Documentation</a></strong></div><div>You can sign your work locally using GPG or S/MIME. GitHub will verify these signatures so other people will know that your commits come from a trusted source. GitHub will automatically sign commits you make using the GitHub web interface.
…</div></blockquote>
<blockquote><div> GitHub</div><div><strong><a href="https://github.com/todotxt/todo.txt-android">todotxt/todo.txt-android</a></strong></div><div>Official Todo.txt Android app for managing your todo.txt file stored in Dropbox. - todotxt/todo.txt-android</div></blockquote>

**Comment by yenda** [comment]
@andmironov there was a bounty there can you have a look

**Pull request merged**
