### PR TITLE
feat: changes to publish to 2 peers for lightpush 

### PR DESCRIPTION
**Pull request by chaitanyaprem**
### Summary

This PR  takes changes in underlying status-go so that messages are published to 2 lightpush nodes for reliability and not rely on storev3 confirmations for sent messages in lightclients.

### Testing notes
Check sending of messages in lightmode which would be by default and check for send confirmations if they are consistent.

##### Functional

- 1-1 chats
- public chats
- group chats

### Steps to test

- Open Status
- ...
- Step 3, etc.

status: ready 

### Risk

Described potential risks and worst case scenarios.

Tick **one**:
- [x] Low risk: 2 devs MUST perform testing as specified above and attach their results as comments to this PR **before** merging.
- [ ] High risk: QA team MUST perform additional testing in the specified affected areas **before** merging.

@pavloburykh can we run e2e tests on this one?

### CODE REVIEW

**Comment by pavloburykh** [comment]
@chaitanyaprem thanks for the PR. Let me run couple more runs to get valid results. I will provide an update tomorrow.

**Comment by chaitanyaprem** [comment]
I have done mobile and desktop dogfooding using these changes and did not see any issues so far. 
Will wait for your feedback @pavloburykh to merge underlying branch.

**Comment by pavloburykh** [comment]
@chaitanyaprem thanks for the PR! e2e tests are okay. If additional manual testing is not required - PR is ready for merge.

**Comment by chaitanyaprem** [comment]
> @chaitanyaprem thanks for the PR! e2e tests are okay. If additional manual testing is not required - PR is ready for merge.

Thanks @pavloburykh , won't be merging this underlying PR but these changes will get merged as part of another PR https://github.com/status-im/status-go/pull/5505.

**Pull request closed without merging**
