### PR TITLE
🧹🧹🧹 Cleaning 3 🧹🧹🧹

### PR DESCRIPTION
**Pull request by flexsurfer**
- removed `react-native-fast-image` component
- removed `register-handler-fx` usage, moved all events to models and used `fx/defn`
- removed unused code
- removed warnings related to nested virtualized list , replaced flatlist by `[:<>]`
- moved root view component to ui/views ns
- used `LogBox` for yellow warning ignorance 
- improved constants ns
- cleaned `status-im.db`
- removed fiddle folder (because its outdated and nobody use it) :(
- removed outdated folders and files
- renamed vector-icons on icons
- removed chaos mode code
- moved i18n namespaces to i18n package

image

### CODE REVIEW

**Review by jakubgs — APPROVED** [review]
This is amazing :heart:. Although I don't know if I agree with moving `RELEASES.md` to `docs`.

Also, we could rename `doc/RELEASE.md` to something more descriptive like `doc/RELEASE_PROCESS.md` or `doc/RELEASE_GUIDE.md`.

**Comment by flexsurfer** [comment]
thanks, good point about RELEASES.md i'll revert it

**Comment by qoqobolo** [comment]
@flexsurfer 
### ISSUE 1: Can't pair devices

While attempting to pair devices two issues were found, due to which pairing is not possible:
- The name of the second device is not displayed in the list of devices for pairing (just "No info").
- Can't switch toggles to select a device for pairing 

#### Reproduction

1. Restore the same multi-account on two devices
2. Open Settings > Sync settings > Devices
2. Set a name for your device > tap `Continue` 
3. Repeat for the secondary device 
4. Tap `+ Advertise device` on both devices
5. On the primary device find the secondary device in the list by its hash
6. Try to switch the toggle (Android) or tick the box (iOS)

#### Expected behavior

- Can switch the toggle/tick the box
- Can see the name of the first device on the second one
- Can pair devices

#### Actual behavior

https://user-images.githubusercontent.com/67952253/108059670-24184200-7056-11eb-9e9d-e8db0bf7e9d6.mp4

**Comment by flexsurfer** [comment]
thanks @qoqobolo , fixed

**Comment by Serhy** [comment]
Will look to fix at failed tests separately to not hold this huge PR.

**Comment by qoqobolo** [comment]
@flexsurfer thank you for this great work and prompt fixes!
@Serhy thanks for your help!

Tested on:
- Pixel 2
- Galaxy S20 
- iPhone SE
- iPhone X

No regressions found. PR is ready to be merged.

**Pull request merged**
