### PR TITLE
[DO NOT MERGE] Add scrollbars to ScrollViews

### LINKED ISSUE #5447: No scroll bar is shown when you browse chat history
### User Story

As a user, I want to see scroll bar to navigate through chat history easily.

### Description
*Type*: Bug
*Summary*: the scroll bar is missing in public and 1-1 chats

#### Expected behavior
scroll bar is presented, so I can pull it and easily navigate through chat history

#### Actual behavior
no scroll bar is presented.
NOTE: on both IOS and Android mobile apps scroll bar is presented.
noscr

### Reproduction

- Open Status
- Join any public chat with long history (need to scroll to see all messages)
- Scroll to the top to see previous messages

### Additional Information
* Status version: nightly 10/08/2018
* Operating System: Mac OS x High Sierra

### PR DESCRIPTION
**Pull request by vitvly**
Fixes #5447

Depends on https://github.com/status-im/react-native-desktop/pull/372

Video: https://monosnap.com/file/olDpWahn9BOTdYs1J9blOJmObiqF1h

### CODE REVIEW

**Review by rasom — APPROVED** [review]

**Comment by chadyj** [comment]
Issue >> #5447

**Comment by vitvly** [comment]
@MaxRis @vkjr can you please review this one so that it can go to testing?

**Review by maxhora — APPROVED** [review]

**Comment by MaxRis** [comment]
@siphiuel , probably, you can just use manual Jenkins pipeline to get the packages built https://ci.status.im/blue/organizations/jenkins/status-react%2Fmanual/activity ( since there is no changes on status-react side )

**Comment by churik** [comment]
@siphiuel scrollbar width is not constant when you scroll chat history
Video: http://take.ms/hC6bql
Screenshots:
default


<blockquote><div>Monosnap screenshot tool</div><div><strong><a href="https://monosnap.com/file/PcbiMZhpZf66KnlaHE7QiRCiTSmf58">File "screencast 2018-10-23 10-55-36.mp4"</a></strong></div><div>Monosnap — the best tool to take & share your screenshots.</div></blockquote>

**Comment by maxhora** [comment]
@churik that, probably, happens because height of the surface is increased when you load more and more messages from the history by scrolling up (the size of scroll bar is decreased in parallel). If that's the case, it's the feature, but not the issue =)

**Comment by churik** [comment]
@MaxRis no, it is not; can replicate when history is fetched and also when you scrolling to the newest - so from the top to the bottom.
Also it can decrease\increase when you scroll to the top - so no pattern in behavior IMO.
It is not critical actually, but would be nice at least to take a look.
One more video: http://take.ms/wt50p

**Comment by maxhora** [comment]
@siphiuel probably, makes sense to try to set `size` property explicitly https://github.com/status-im/react-native-desktop/pull/372/files#diff-1f7d5697a7053ae732027531a4cb9e38R64 Curious, if, for example, corresponding flexbox object already knows the calculated general height of all elements in ListView.

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/status-im/react-native-desktop/pull/372">Add vertical scroll bar to ScrollViews by siphiuel · Pull Request #372 · status-im/react-native-desktop</a></strong></div><div>Small fix for some kind of scrollbar to appear.</div></blockquote>

**Comment by vkjr** [comment]
@siphiuel, usually you can skip review for `status-react` PR if it only tests `react-native-desktop` changes, since you already have reviews in rnd PR. Just move it in `To Test` on pipeline for QA board to request testing.
@churik, please correct me if I'm wrong.

**Comment by vitvly** [comment]
@vkjr - thanks for advice. I was thinking that without the reviews issue transition will be blocked. Good to know this is not the case.

**Comment by vitvly** [comment]
@maxris - thanks for pointing this out, trying to adjust size/visualSize now.

**Comment by churik** [comment]
@vkjr @siphiuel yes, you can skip the review! Just don't forget to add `RN-related` label to such PRs

**Comment by maxhora** [comment]
Will take a look at the issue appeared there as discussed during Friday's meeting

**Comment by maxhora** [comment]
@churik I've looked into issue with scrollbar size jumping and was not able to find reliable solution ( ScrollBar attached to Flickable has the mentioned issue with size calculation of position indicator; introducing of ScrollBar with custom calculations introduces much more issues and requires more investigation).
If that's not really critical, I suggest to merge current implementation.

**Comment by churik** [comment]
will be created as separate issue https://github.com/status-im/status-react/pull/6403#issuecomment-432162867

**Comment by churik** [comment]
Merged on RN-side

**Pull request closed without merging**
