### PR TITLE
custom network symbol

### PR DESCRIPTION
**Pull request by flexsurfer**
custom network symbol

### CODE REVIEW

**Review by Parveshdhull — APPROVED** [review]

**Comment by churik** [comment]
### ISSUE 1: error at attempt to send assets in 1-1 chat

**Steps:**
1) restore multiaccount with funds from seed phrase
2) open 1-1 chat
3) try to send any asset

**Expected result:**
can send
**Actual result:**
IMAGE 2021-11-11 14:04:40

**OS:** IOS, Android

**Comment by flexsurfer** [comment]
@churik thanks, fixed

**Comment by churik** [comment]
@flexsurfer 
Thanks! issue is fixed, however I noticed that tx history + collectibles are not available on test networks anymore.
Can we return it (only for test networks)?

**Comment by flexsurfer** [comment]
thanks @churik  done

**Pull request closed without merging**
