### PR TITLE
Adding BCShop.io dapp to Status

### PR DESCRIPTION
**Pull request by olekon**
BCShop.io is a service for selling digital goods or services as software codes, game currency, e-books, discount coupons, online conference tickets, electronic tickets to live events, etc.

### CODE REVIEW

**Comment by andytudhope** [comment]
Hi @olekon! Thanks for this, and BCShop looks amazing, would love to see it living within Status. I browsed to the https://testnet.bcshop.io link you submitted in your file and couldn't quite get it working, as the option to connect using Status was not there. I tried the MetaMask one (as its the same thing essentially), but no dice. Can you give me some direction on how to test this properly?

**Comment by olekon** [comment]
Oh, we haven't implemented connection via Status yet. Where can I learn about this?

**Comment by andytudhope** [comment]
Status injects the same web3 object that MetaMask does, so it should pick up either. On a simple react site I have, I just use the good ole:
```
if (typeof web3 !== 'undefined') {
            // Use Status'/MetaMask's provider.
            web3 = new Web3(web3.currentProvider)
        } else {
            this.setState({
                errorMessage: 'Unable to connect to Ethereum. Please check you have MetaMask installed and that you have access to your account.',
            })
            return
        }
```

**Comment by olekon** [comment]
There was a bug in metamask usage on the website. Now it’s fixed. Check it please

**Comment by olekon** [comment]
andytudhope, could you please look at https://testnet.bcshop.io/ again to check if it is accessible with Status now?

**Comment by olekon** [comment]
andytudhope, should I open new pull request or stay in this? It's been 5 days since bugfix.

**Comment by andytudhope** [comment]
Hi @olekon. This is currently under review with the team. I confirm that I can sign in, but it doesn't seem like I can do much else as there are no vendors and I can't find any products?

**Comment by olekon** [comment]
Hi, @andytudhope. Thanks for the response and feedback.
Vendors and products are user-generated content. You can create those for you and share the product's link with anybody who is willing to make a purchase.
You can find more information here https://bcshop.io/
Here is our Medium post which you can find useful too https://medium.com/@bcshop.io/use-smart-contracts-and-short-links-instead-of-unreadable-addresses-2acd73eb686f

p.s. I forgot to mention that Welcome page is currently in development.

**Comment by pablanopete** [comment]
Hey Oleg first of all thank you for your submission and passion for getting your DApp into Status.

 At the current moment we are not accepting contacts that are in the process of a token launch - once a further review is established we will be happy to evaluate adding your DApp as a native contact.

**Pull request closed without merging**
