### PR TITLE
nl.cljs

### PR DESCRIPTION
**Pull request by Akariko**
Hi, apart from a few minor alterations (for example, changing "your" into "you" when "you" was to be translated... I've actuallly added quite a lot. I noticed the English file had a lot of extra lines which aren't in the Dutch translation. I've added these, and translated them too. Hope it will be of value. The new document is one line longer than the English one because of one additional line in the Dutch which I did not dare remove; line 227, "other". Line 63 I've left untranslated, because I believe it has to remain as is. Hope I could be of help.

[comment]: # (Please replace ... with your information. Remove < and >)
[comment]: # (To auto-close issue on merge, please insert the related issue number after # i.e fixes #566)
fixes #...

### Summary:
[comment]: # (Summarise the problem and how the pull request solves it)
...

### Steps to test:
- Open Status
- ...
- Step 3, etc.

[comment]: # (PRs will only be accepted if squashed into single commit.)
status: <ready|wip>

### CODE REVIEW

**Comment by flexsurfer** [comment]
hi @Akariko , thank you for your contribution, unfortunately, there are conflicts, could you please resolve conflicts, and we can merge this PR

**Comment by Akariko** [comment]
Conflicts, hmmm. I've directly copied the English file, and even used the same lines so it would be easier to overview. Except for the one additional line which I mentioned was in the Dutch but not the English file, which I didn't delete. What do you recommend, proofreading this Dutch file with the English file as proof, and see if I messed up a line? I can hardly believe I did, but if this is the case I can take another look.

**Comment by flexsurfer** [comment]
@Akariko we have five PRs for nl.cljs, we have merged the biggest one, and looks like there were  changes in same lines in this PR as in your PR, and conflicts appeared

**Comment by flexsurfer** [comment]
@Akariko we'll close this PR, please reopen it or open new one, thank you

**Pull request closed without merging**
