### PR TITLE
[#21336] feat: upgrade wallet connect

### LINKED ISSUE #21336: Use the Reown dependency instead of WalletConnect
# Problem

Due to the WalletConnect rebranding to Reown, future updates will only be available under the new package names. The guide for upgrading is [here](https://docs.reown.com/walletkit/upgrade/from-web3wallet-react-native).

Make sure the older versions are supported, since we're stuck with the current one due to Android not working the up-to-date version.

## Acceptance Criteria

- [ ] Everything should work as it did before

### PR DESCRIPTION
**Pull request by mohsen-ghafouri**
fixes #21336

### Summary

upgrade wallet connect to Reown library

#### Areas that maybe impacted

- Wallet connect interaction

### Test Note:

They only did some rebranding, but we also upgraded the minor version. Everything is supposed to work as it currently does. but please do a quick test in both android and iOS for sign and send transaction. 

status: ready

### CODE REVIEW

**Review by vkjr — APPROVED** [review]

**Comment by pavloburykh** [comment]
@mohsen-ghafouri thank you for the PR. Please take a look at the issue below. Mind, that it is hard to verify if the issue is PR related or not. In PR I reproduce it most of the time, in develop we have faced the same issue but couple of times. 

### ISSUE 1 Confirmation modal does not appear if event was triggered while Status app was offline (logged out) 

1. Connect to dapp (for example https://se-sdk-dapp.vercel.app/ )
2. Logout Status app
3. Trigger any request on dapp's side
4. Login Status app
5. Check if confirmation modal is shown

**Actual result:** confirmation modal does not appear, cannot confirm triggered event. 

[Status-debug-logs - 2024-12-20T151702.615.zip](https://github.com/user-attachments/files/18211181/Status-debug-logs.-.2024-12-20T151702.615.zip)

https://github.com/user-attachments/assets/da6286eb-9896-4a4c-860f-f45beb9c8868

**Comment by pavloburykh** [comment]
Besides that, I am facing different other random issues, which I try to investigate now. For example: 

1. After confirming connection in Status app, it connection is not updated on dapp's side, i.e. QR code remains open, connected address is not displayed in dapp. At the same time dapp is listed among connected in Status app. This one is reproducible in develop as well.  
2. Sometimes event remains in Pending on dApp's side after signing in Status app. I have faced this problem once when swap on 1inch dapp.

**Comment by pavloburykh** [comment]
@mohsen-ghafouri regarding [ISSUE 1 ](https://github.com/status-im/status-mobile/pull/21833#issuecomment-2557013966), we have logged a separate issue which is reproducible in develop, maybe those issues are related, I am not sure https://github.com/status-im/status-mobile/issues/21853.

**Comment by mohsen-ghafouri** [comment]
Hey @pavloburykh, thanks for testing this PR. I think the issue 1 is not related to my PR as we don't handle it logically. I will do more check to make sure.

**Review by smohamedjavid — APPROVED** [review]

**Comment by pavloburykh** [comment]
> Hey @pavloburykh, thanks for testing this PR. I think the issue 1 is not related to my PR as we don't handle it logically. I will do more check to make sure.

@mohsen-ghafouri if ISSUE 1 is not PR related, then PR is ready for merge. I can log ISSUE 1 separately.

**Comment by mohsen-ghafouri** [comment]
I will check Issue 1 along with https://github.com/status-im/status-mobile/issues/21853

**Pull request merged**
