### PR TITLE
upgrade react-native

### LINKED ISSUE #6973: react-native-i18n is deprecated
# Problem

react-native-i18n has been deprecated  https://github.com/AlexanderZaytsev/react-native-i18n

# Implementation

replace it by https://github.com/react-community/react-native-languages

# Acceptance Criteria

react-native-i18n is replaced by react-native-languages

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/AlexanderZaytsev/react-native-i18n">AlexanderZaytsev/react-native-i18n</a></strong></div><div>React Native + i18n.js. Contribute to AlexanderZaytsev/react-native-i18n development by creating an account on GitHub.</div></blockquote>
<blockquote><div> GitHub</div><div><strong><a href="https://github.com/react-community/react-native-languages">react-community/react-native-languages</a></strong></div><div>🌍 Get the user preferred languages and use the library of your choice to translate your app - react-community/react-native-languages</div></blockquote>

### PR DESCRIPTION
**Pull request by debragail**
downgraded realm in order to install
removed deprecated react-native-i18n

fixes #6973 
https://github.com/status-im/status-react/issues/6973

#### Areas that maybe impacted (optional)
**Functional**
- package.json

status: ready

### CODE REVIEW

**Comment by ghost** [comment]
### Pull Request Checklist
- [ ] Have you updated the documentation, if impacted (e.g. [docs.status.im](https://docs.status.im/docs/build_status.html))?

**Comment by debragail** [comment]
@StatusSceptre

**Comment by debragail** [comment]
gitcoin is broken and I can't submit work.

**Comment by StatusSceptre** [comment]
Being resolved via #7261

**Pull request closed without merging**
