### PR TITLE
fix_: ignore log partial API request

### PR DESCRIPTION
**Pull request by qfrank**
For change description see [details](https://github.com/status-im/status-go/pull/5865)

relate [comment1](https://github.com/status-im/status-go/pull/5812#issuecomment-2364599434) / [comment2](https://github.com/status-im/status-go/pull/5812#issuecomment-2364600859)

status: ready.

### CODE REVIEW

**Review by Parveshdhull — APPROVED** [review]

**Comment by ilmotta** [comment]
@qfrank, shouldn't this mobile PR use all the new `*V2` endpoints you created in the status-go PR? Otherwise, doing QA in this mobile PR won't validate the new endpoints work.

Another way to frame my question is, why did we create V2 functions if status-mobile is the only consumer of the functions in `mobile/status.go`? Why keep V1 and V2 versions if we only need to point to the V2 ones?

If this mobile PR changed to use the new V2 endpoints:

1. We would QA only once, thus no need for a follow-up.
2. We would be able to remove all deprecated functions in `mobile/status.go`.

Maybe I'm missing something and there's a good reason to keep deprecated and v2 functions in `mobile/status.go`.

**Review by ilmotta — COMMENTED** [review]
@qfrank, shouldn't this mobile PR use all the new `*V2` endpoints you created in the status-go PR? Otherwise, doing QA in this mobile PR won't validate the new endpoints work.

Another way to frame my question is, why did we create V2 functions if status-mobile is the only consumer of the functions in `mobile/status.go`? Why keep V1 and V2 versions if we only need to point to the V2 ones?

If this mobile PR changed to use the new V2 endpoints:

1. We would QA only once, thus no need for a follow-up.
2. We would be able to remove all deprecated functions in `mobile/status.go`.

Maybe I'm missing something and there's a good reason to keep deprecated and v2 functions in `mobile/status.go`.

**Comment by qfrank** [comment]
> shouldn't this mobile PR use all the new *V2 endpoints you created in the status-go PR? Otherwise, doing QA in this mobile PR won't validate the new endpoints work.

It depends on time, I thought we should fix the issue quickly, WDYT?🤔 cc @churik We can create separate PR to use all the new *V2 endpoints and validating then. 

> Another way to frame my question is, why did we create V2 functions if status-mobile is the only consumer of the functions in mobile/status.go? Why keep V1 and V2 versions if we only need to point to the V2 ones?"

create V2 should keep application stable, status-mobile is **NOT** the only consumer of the functions in mobile/status.go, desktop also use it.

@ilmotta

**Comment by ilmotta** [comment]
> create V2 should keep application stable, status-mobile is **NOT** the only consumer of the functions in mobile/status.go, desktop also use it.

Thanks for the clarification. I think we could at least use the V2 endpoints on the mobile repo in this PR. It thought it was just a matter of renaming in mobile in a handful of places because V2 functions are backwards compatible. But this is just my personal preference, if you and QA team think it's alright to have a follow-up no worries by me.

**Review by ilmotta — APPROVED** [review]

**Comment by qfrank** [comment]
> It thought it was just a matter of renaming in mobile in a handful of places 

It's easy for you but not for me. Merely renaming and constructing JSON request parameters. I doubt that it will be completed in a short time for me under strict clojure coding rules 😉. If someone(clojure expert) can help, that's another story

**Comment by ilmotta** [comment]
> > It thought it was just a matter of renaming in mobile in a handful of places
> 
> It's easy for you but not for me. Merely renaming and constructing JSON request parameters. I doubt that it will be completed in a short time for me under strict clojure coding rules 😉. If someone(clojure expert) can help, that's another story

No worries then @qfrank. To each their own cup of tea 😄 PR more than approved, it's just that QAs should be aware they won't be testing some of the new code being merged in status-go, as that will come only in the follow-up PR using new endpoints. I would like to help, but realistically I'll probably just cause a delay on the process due to other tasks on me already.

**Comment by churik** [comment]
@qfrank @ilmotta 
did I understand correct that we need to create follow-up on this issue to use new endpoints in status-mobile?

From my side I don't have an info where particular methods can be used in the app, so I checked:
- changing password
- signing tx in Dapp

I didn't notice any sensitive info (i.e. passwords) in `requests.log`

Let me know if additional check are required.
I'll launch e2e tests and move PR to merge.

**Comment by qfrank** [comment]
> did I understand correct that we need to create follow-up on this issue to use new endpoints in status-mobile?

yes

> Let me know if additional check are required.

no more from my side, thank you!

**Comment by churik** [comment]
e2e test failures are not related, green light, thanks!

**Pull request merged**
