### PR TITLE
fix: Rounded edges of color sections of identity rings

### LINKED ISSUE #16954: Rounded edges of color sections of identity rings
# Bug Report

## Problem 

The edge of the color sections now has a radius that shouldn't be there.

Screenshot 2023-08-09 at 15 40 20

#### Expected behavior

Screenshot 2023-08-09 at 15 41 22

### Additional Information

- Status version: nightly 9/08
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by qfrank**
fixes #16954

#### Platforms

- Android
- iOS

status: ready

### CODE REVIEW

**Review by yqrashawn — APPROVED** [review]

**Comment by VolodLytvynenko** [comment]
Hi @qfrank, thank you for the PR. I don't see any issues from my end. Please dont merge this PR for now, until PR #17091 is merged. I will keep you updated

**Review by Francesca-G — COMMENTED** [review]
Here's the [Figma frame](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS/Feedback-for-Mobile?type=design&node-id=5019%3A87950&mode=design&t=guxUx6MO1dwuFOYv-1) with the design review :)

**Comment by VolodLytvynenko** [comment]
Hi @Francesca-G, I'm not sure if this PR requires a design review since it involves minor changes related to rounding the edges for identifier rings. It might be better to perform a review once the overall fixes for all identifier ring sizes are implemented in https://github.com/status-im/status-mobile/pull/17034. 

Nevertheless, let me know if a review is conducted and if any pixel mismatches are identified. Thank you!

**Comment by VolodLytvynenko** [comment]
> Here's the [Figma frame](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS/Feedback-for-Mobile?type=design&node-id=5019%3A87950&mode=design&t=guxUx6MO1dwuFOYv-1) with the design review :)

thank you for reviewing. The changes related to ring sizes will be implemented in https://github.com/status-im/status-mobile/pull/17034

**Pull request merged**
