### PR TITLE
WC: Proper handling of disconnection, both from the dapp itself and from the list of connected dapps

### LINKED ISSUE #20797: Disconnected Dapp is removed from the list only after app re-login
Originally reported here https://github.com/status-im/status-mobile/pull/20711#issuecomment-2235963134

**Steps:** 

1. Connect to any dAapp
2. Disconnect dAapp on dApp's side
3. See if dApp disappeared from dApps list in Status app

**Actual result:** dApp dissappears from the list only after relogin

https://github.com/user-attachments/assets/d7e8c769-8635-4681-b3d6-a2956c4f9be9

**Expected result:** dApp should disappear from the list without need to re-login

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

### LINKED ISSUE #20798: Disconnection of dApp in Status app does not result in disconnection on dApp's side
Originally reported here https://github.com/status-im/status-mobile/pull/20711#issuecomment-2236003896

**Steps:** 

1. Connect to any dApp
2. Disconnect dApp in Status app
3. See if wallet is disconnected on dApp's side 

**Actual result:** wallet is still displayed as connected on dApp's side despite it has been disconnected in Status app

**Expected result:** wallet should be disconnected on dApp's side
### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

### PR DESCRIPTION
**Pull request by alwx**
fixes #20797
fixes #20798 

#### Platforms

- Android
- iOS

status: ready

### CODE REVIEW

**Review by shivekkhurana — APPROVED** [review]
GG.

**Review by smohamedjavid — APPROVED** [review]

**Review by clauxx — APPROVED** [review]
ah, so we were using the wrong topic. Amazing API design from them as always. Great fix @alwx!

**Comment by alwx** [comment]
@clauxx yes, there is `topic` and `pairingTopic` and even they sometimes confuse them in the docs :D

**Comment by qoqobolo** [comment]
Hey @alwx , thanks for the fixes!

I'm finishing work for today, will continue on Monday, but so far I've faced this issue with OpenSea:

### ISSUE 1: Disconnection of the OpenSea dapp in Status doesn't result in disconnection on the Opesea side

**Steps:**
1. Connect to https://opensea.io/
2. Press **Disconnect** in Status

**Expected result:** the wallet is disconnected on OpenSea
**Actual result:** the wallet stays connected, you need to log out manually

**Comment by qoqobolo** [comment]
> Hey @alwx , thanks for the fixes!
> 
> I'm finishing work for today, will continue on Monday, but so far I've faced this issue with OpenSea:
> 
> ### ISSUE 1: Disconnection of the OpenSea dapp in Status doesn't result in disconnection on the Opesea side
> **Steps:**
> 
> 1. Connect to https://opensea.io/
> 2. Press **Disconnect** in Status
> 
> **Expected result:** the wallet is disconnected on OpenSea **Actual result:** the wallet stays connected, you need to log out manually

Same situation for https://dydx.trade/ - the wallet is displayed as connected after disconnection on the Status side.

It seems this issue is relevant for dapps where a message signature is required when connecting.

**Comment by alwx** [comment]
It does seem like *they* don't handle the disconnect event properly.
This is what happens when I try it with opensea:
- I see the toast in the Status app saying that the disconnection was successful
- OpenSea doesn't show anything BUT in 10 seconds or so it starts experiencing issues with fetching my balance
- if I refresh the page on OpenSea I see the following:
Screenshot 2024-07-22 at 13 29 09

So it does look like we disconnected from OpenSea but they didn't process it correctly despite us sending the "disconnect" event to them.

@qoqobolo

**Comment by qoqobolo** [comment]
@alwx yep, looks like this. And I suspect there's nothing we can do about it, right?

**Comment by alwx** [comment]
Also, I see following errors in the devconsole of OpenSea:
Screenshot 2024-07-22 at 13 32 32

**Comment by alwx** [comment]
@qoqobolo sadly, no. Once we sent the disconnect event, we cannot control the process anymore — we have no connection to the dapp itself and no way of telling them to really disconnect.

**Comment by qoqobolo** [comment]
@alwx gotcha.
Let's merge this PR then since everything except that case looks good to me. Thanks for your work!

**Pull request merged**
