### PR TITLE
Fix - Scanning Local Pairing QR Code Sometimes Gives Weird Error

### PR DESCRIPTION
**Pull request by Samyoul**
For QA testing purposes.

`status-mobile` build of https://github.com/status-im/status-go/pull/3750

### CODE REVIEW

**Review by ibrkhalil — APPROVED** [review]

**Comment by qoqobolo** [comment]
Hey @Samyoul, thanks for creating this PR for testing!
The `invalid ciphertext length`  error is still here for iOS.

To reproduce this you need to keep holding your phone over the QR code so that the camera can continue to "see" it after it has already been scanned. If you remove the camera immediately after scanning, the error will not occur.

Screenshot 2023-07-19 at 12 29 29

https://github.com/status-im/status-mobile/assets/67952253/6f209b02-0207-449b-bcec-32dc02a261d6

**Comment by Samyoul** [comment]
Hey @qoqobolo . Oh. ... Hmmm, that should have worked. I'm very sorry that this wasted your time, I don't have an iOS device otherwise I'd check myself.

`invalid ciphertext length` is a `status-go` error that normally is the result of trying to decrypt / encrypt an empty input with AES encryption. But no decryption / encryption should happen if the endpoint is locked. ... So some of my presumptions are wrong here.

I'll spend some time checking what inputs would trigger the `invalid ciphertext length` error and see if there are any async processes that may trigger that.

May I ask, do you have any logs from your test process? I wonder if there are any clues in there.

**Comment by qoqobolo** [comment]
@Samyoul sorry for the long response!
Could you check if some of these logs would be useful to you?

[geth.log](https://github.com/status-im/status-mobile/files/12129372/geth.log)
[Status.log](https://github.com/status-im/status-mobile/files/12129374/Status.log)

**Comment by Samyoul** [comment]
A little update on this issue, I've merged https://github.com/status-im/status-go/pull/3750 . I expected that PR to fix the reported issue, but it didn't. So to prevent that work going stale I've merged it and it appears to fix https://github.com/status-im/status-mobile/issues/16548.

It is a shame that the PR didn't resolve both issues.

**Comment by qoqobolo** [comment]
> A little update on this issue, I've merged https://github.com/status-im/status-go/pull/3750 . I expected that PR to fix the reported issue, but it didn't. So to prevent that work going stale I've merged it and it appears to fix https://github.com/status-im/status-mobile/issues/16548.
It is a shame that the PR didn't resolve both issues.

Thanks for the update, and for taking care of both issues!

**Comment by flexsurfer** [comment]
hey @Samyoul can we close this PR for now ?

**Comment by flexsurfer** [comment]
will close it for now, feel free to reopen when needed

**Comment by Samyoul** [comment]
@flexsurfer I am sorry, and yes it is fine to close this for now. The `status-go` pr has been merged, although this specific problem wasn't resolved in that PR.

**Pull request closed without merging**
