### PR TITLE
[#4320] Do not inject jQuery in DApps browser

### LINKED ISSUE #4320: Do not inject external js libs in DApps browser
### User Story

As a developer, I want a DApp browser to start with no extra dependencies

### Description

*Type*: Bug

DApps browser currently starts with a bunch of [extra libs](https://github.com/status-im/status-react/blob/1d196d2e82f862c33c16a684aeb4e20ed1e2cea2/src/status_im/ui/screens/browser/views.cljs#L101) like jQuery. We only want to inject web3.

It also injects our `web3` implementation conditionally which introduces issues (should we fail or override existing one?).

Clean this up.

### PR DESCRIPTION
**Pull request by jeluard**
fixes #4320

### Summary:

Do not always inject jQuery in DApps browser.

### Steps to test:
- Open Status
- Make sure all featured DApps work as expected :sweat_smile: 

status: ready

### CODE REVIEW

**Review by goranjovic — APPROVED** [review]

**Review by flexsurfer — APPROVED** [review]

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/KjeNgF for branch PR-4379

<blockquote><div><strong><a href="https://i.diawi.com/KjeNgF">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/megMce for branch PR-4379

<blockquote><div><strong><a href="https://i.diawi.com/megMce">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/x9iSAr for branch PR-4379

<blockquote><div><strong><a href="https://i.diawi.com/x9iSAr">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/2Kpkzh for branch PR-4379

<blockquote><div><strong><a href="https://i.diawi.com/2Kpkzh">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/pTwhwu for branch PR-4379

<blockquote><div><strong><a href="https://i.diawi.com/pTwhwu">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/A84dmg for branch PR-4379

<blockquote><div><strong><a href="https://i.diawi.com/A84dmg">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by asemiankevich** [comment]
I have checked CryptoKitites and Airswap - works fine

**Pull request merged**
