### PR TITLE
fix Blink of shell screen occurs when the Scan sync button is tapped

### LINKED ISSUE #19096: [Android] Blink of shell screen occurs when the [Enter or enter sync code] button is tapped on the Syncing screen.
### Steps:
1. Go to Syncing
2. Tap [+] 
3. Tap [Enter or enter sync code] button
4. Tap 'back' button

### Actual result:
- The shell screen blinks when the [Enter or enter sync code] button after step 3
- Wrong navigation after step 4

https://github.com/status-im/status-mobile/assets/52490791/398cadf3-8c20-483a-a94c-d506ff1f8adc

### Expected result:
- The "Pair devices to sync" screen should be shown without blinking when the [Enter or enter sync code] button is tapped.
- When the back button is tapped, the user should be navigated to the 'Pair devices to sync' screen

### ENV:
Nightly [4 Mar 2024]

### LINKED ISSUE #19103: [IOS] Wrong navigation after 'scan or enter sync code' button is tapped
### Steps:
1. Go to Syncing
2. Tap [+] 
3. Tap [Enter or enter sync code] button

### Actual result:
The user is navigated to the shell

https://github.com/status-im/status-mobile/assets/52490791/0812611c-a776-4fb6-a816-f923fcbcee54

### Expected result:
Scan sync code screen is opened

### ENV:
Nightly [5 Mar 2024]

### PR DESCRIPTION
**Pull request by Parveshdhull**
fixes https://github.com/status-im/status-mobile/issues/19096
fixes https://github.com/status-im/status-mobile/issues/19103

### Testing
Please let me know if any of the flow in settings screen is not working as expected

status: ready

### CODE REVIEW

**Comment by VolodLytvynenko** [comment]
hi @Parveshdhull Can the fix of this issue https://github.com/status-im/status-mobile/issues/19103 be also included in this PR?

**Comment by Parveshdhull** [comment]
> hi @Parveshdhull Can the fix of this issue #19103 be also included in this PR?

Hi @VolodLytvynenko, I think same fix should work for both issues. But let me know if this is not the case

**Comment by Parveshdhull** [comment]
Also, please let me know if any of the other flow is not working in settings screen. I can include in this PR. Thank you for finding this case.

**Review by jo-mut — APPROVED** [review]

**Comment by VolodLytvynenko** [comment]
hi @Parveshdhull thank you for PR. No issues from my side. Ready to be merged

**Pull request merged**
