### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by puilp0502**
### Summary:

The links in CONTRIBUTING.md was broken. This PR fixes it.

status: ready

### CODE REVIEW

**Comment by AlessandroSpallina** [comment]
riot link is missing

**Comment by puilp0502** [comment]
https://chat.status.im will redirect to Riot.

**Review by pablanopete — CHANGES_REQUESTED** [review]
Hey thanks so much for the cleanup - couple things, can you link the FAQ here - https://wiki.status.im/Frequently_Asked_Questions instead 
and change the verbiage to "Join our Riot" instead? 

Other than that LGTM, thanks!

**Comment by puilp0502** [comment]
@pablanopete Fixed it!

**Review by pablanopete — APPROVED** [review]

**Pull request merged**
