### PR TITLE
Cleaning 2

### PR DESCRIPTION
**Pull request by flexsurfer**
Removed contacts groups and debug console

image

### CODE REVIEW

**Review by jeluard — APPROVED** [review]

**Review by goranjovic — APPROVED** [review]

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/eMEaRs for branch PR-4321

<blockquote><div><strong><a href="https://i.diawi.com/eMEaRs">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/hhjDMJ for branch PR-4321

<blockquote><div><strong><a href="https://i.diawi.com/hhjDMJ">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/517L3M for branch PR-4321

<blockquote><div><strong><a href="https://i.diawi.com/517L3M">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by flexsurfer** [comment]
SHOULD BE MERGED AFTER https://github.com/status-im/status-react/pull/4308

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/c4pRvK for branch PR-4321

<blockquote><div><strong><a href="https://i.diawi.com/c4pRvK">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/cSzPY5 for branch PR-4321

<blockquote><div><strong><a href="https://i.diawi.com/cSzPY5">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Pull request merged**
