### PR TITLE
Bug/profile screen #298

### LINKED ISSUE #298: Profile Screen - cannot tap phone, status field bizarre behaviour
After tapping three dot icon;
- tap on all 3 field items
- typed in bad email
- couldn't tap on phone anymore no matter how hard i tried
- i tapped on status in the middle and started typing but the behaviour is really weird

please ensure
- [x] fields are tappable (phone)
- [x] #hashtags turn blue in status, like in discover
- [x] status field doesn't behave erratically as seen in gif - it seems to be typing RTL instead to LTR in english???
- [x] don't have to double tap on the save icon (although i saw this was already fixed)
- [x] selectable (but not editable) fields for address and public key
- [ ] do we need email field?
- [x] name should default to GFYcat style naming convention #303

profile-screen

### LINKED ISSUE #303: GFYCat-style Naming convention (instead of Anonymous)
Instead of "Anonymous" or public key as default username, 
let's adopt "adjective adjective animal" (each word selection is random)
using these word lists;

http://assets.gfycat.com/adjectives
http://assets.gfycat.com/animals

Example names would look like "Easygoing Good Hylaeosaurus" & "Pessimistic Wiggly Crossbill"
fixes #225

### PR DESCRIPTION
**Pull request by adrian-tiberius**
Fixes #298 
Fixes #303

### CODE REVIEW

**Comment by rasom** [comment]
Maybe better to use something like [`ellipsizeMode=middle`](https://facebook.github.io/react-native/docs/text.html#ellipsizemode) for `address`/`public-key`, because it doesn't look cool now

@jarradh, should we ask @andmironov to help us with this?

**Comment by rasom** [comment]
Can not update profile photo on android device:

wowow

**Comment by rasom** [comment]
That's what i see on iOS simulator:

**Comment by rasom** [comment]
Validation:

1) this email is correct:
screenshot_2016-10-11-13-13-32

2) Instead of showing validation message it just skips changes, when phone number is invalid

ph

**Comment by rasom** [comment]
Let's remove `email` input from this screen

**Comment by jarradh** [comment]
agreed, that was my question in #298

**Comment by rasom** [comment]
1. There is a warning



2.
 
pr

3. Don't know, maybe better to create another task about styles but

**Comment by adrian-tiberius** [comment]
1 and 1 fixed.
On 2, I'm not sure what the best solution is. I left them as editable text-inputs so that the select text functionality works and be consistent with ios. If I set editable to false, this doesn't work anymore (at least in simulator). Also this might be a new feature for anger management support :D.

**Comment by rasom** [comment]
@adrian-tiberius, can you please fix font color for status field on iOS (it is fine on android), then squash and rebase, and will merge PR
screen shot 2016-10-14 at 10 33 08

**Pull request merged**
