### PR TITLE
draft PR for testing fixes for #20296

### PR DESCRIPTION
**Pull request by yqrashawn**
PR created to test corresponding go changes https://github.com/status-im/status-go/pull/5284

### QA Notes:

Areas to be tested:

- all kind of create/restore/login with and without keycard
- local pairing
- verify this [ISSUE](https://github.com/status-im/status-mobile/pull/20296#issuecomment-2144769202) is fixed on IOS

### CODE REVIEW

**Comment by pavloburykh** [comment]
@yqrashawn could you please update current PR so it would use the latest commit from https://github.com/status-im/status-go/pull/5284 ? Thank you!

**Comment by igor-sirotin** [comment]
This need to be updated to point to `22eec2cee2e30d9f1a1f9c20117bdd5109ba19ab` status-go commit

**Comment by igor-sirotin** [comment]
@pavloburykh upgraded to point to latest commit 👌

**Comment by yqrashawn** [comment]
Rebased to mobile develop

**Comment by pavloburykh** [comment]
@yqrashawn @igor-sirotin 

Thanks for the PR, no issues from mobile side. 

What has been tested: 

1. Migration
2. Create/restore/login 
3. local pairing
4. verified this [ISSUE](https://github.com/status-im/status-mobile/pull/20296#issuecomment-2144769202) is fixed on IOS

**Comment by yqrashawn** [comment]
Thanks @pavloburykh, close this issue since the status-go PR is merged into dev

**Pull request closed without merging**
