### PR TITLE
 [Fix #3472] Add accessibility labels for Profile screens 

### LINKED ISSUE #3472: Add accessibility labels for Profile screens
### User Story
As an automation engineer I need accessibility labels to be added for specific elements so I could use them in my Appium scripts.

### Description
Accessibility labels are required for building stable mobile test automation solution. Please, add accessibility labels for all elements listed below.

#### Profile
- edit-button
- share-my-contact-code-button
- notifications-button
- network-button
- offline-messages-settings-button
- log-out-button
- profile-tab-button

#### Edit profile
- done-button
- edit-profile-photo-button
- username-input

#### Edit profile
- done-button
- edit-profile-photo-button
- username-input

#### Contact code 
- done-button
- share-code-button
- qr-code-image
- address-text

#### Log out
- cancel-button
- log-out-button

#### Network settings
- back-button
- network-item
  - connected-text 

#### Network settings details
- back-button
- network-details-text

#### Offline messages settings
- back-button
- mailserver-item

### PR DESCRIPTION
**Pull request by foopang**
### Summary:

Add accessibility labels for Profile screens 

status: wip (on top of https://github.com/status-im/status-react/pull/3517)

### CODE REVIEW

**Review by yevh-berdnyk — APPROVED** [review]

**Comment by yevh-berdnyk** [comment]
@foopang LGTM, all labels are added, thank you!

UPD: Just realised one issues. On the Network settings details view for a network which is not connected network-details-text label is added for two elements. 
screen shot 2018-03-12 at 7 37 36 pm
Also it would be very useful to add a label for the Connect button

**Review by yevh-berdnyk — CHANGES_REQUESTED** [review]
https://github.com/status-im/status-react/pull/3529#issuecomment-372392614

**Comment by foopang** [comment]
@yevh-berdnyk Thanks for checking! I added a label for the Connect button as "network-connect-button", also removed a wrongly placed network-details-text label.

**Comment by yevh-berdnyk** [comment]
@foopang now it's good, thank you!

**Review by yevh-berdnyk — APPROVED** [review]

**Review by jeluard — APPROVED** [review]

**Pull request merged**
