### PR TITLE
Add method for fast creation of communities

### LINKED ISSUE #16362: Add method for fast creation of communities on status-go side
# Feature Issue

As the community creation flow from mobile is out of scope for now, it is required to find a quick way to test the community functionality without a desktop, but with the predefined data for automation needs.

### User Story
As a QA automation, I need to have buttons in UI to quickly open 3 types of communities in e2e builds in order to speed up automation testing.

### Description

1) Closed community
`name`: closed community
`description`: closed community to check membership requests
`logo`: any 
`banner`: any
`colour`: #887af9 
`community history service` enabled: yes
`request to join required` : yes
`any member can pin a message`: yes

Additionaly:
`channels`: #general (no category), #cats (category `pets`), #dogs (category `pets`), #rules (category `household`)
`categories` : `pets`, `household`

2) Open community
`name`: open community
`description`: open community to join with no requests
`logo`: any
`banner`: any
`colour`: #26a69a
`community history service` enabled: yes
`request to join required` :
`any member can pin a message`: no

3) Token-gated community
`name`: SNT community
`description`: require 10 SNT Goerli to use
`logo`: any 
`banner`: any
`colour`: #eab700
`community history service` enabled: yes
`request to join required`: yes
`any member can pin a message`:  no
`PERMISSIONS`: 10 STT on Goerli network to become a member 

### Acceptance Criteria
3 buttons on e2e and PR builds are available for creation 3 types of mentioned above communities.

### Notes

[comment]: # (For the developer who will implement. Include planning poker estimates, guidance, etc.)

### PR DESCRIPTION
**Pull request by qfrank**
close #16362 

#### Platforms

- Android
- iOS

status: ready

### CODE REVIEW

**Review by siddarthkay — APPROVED** [review]

**Comment by churik** [comment]
@qfrank thank you for PR!!

I made manual nightly build from this branch and the option is available [there](https://ci.infra.status.im/job/status-mobile/job/manual/290/) 

Expected that it will be available in PRs and e2e builds only.

**Comment by yevh-berdnyk** [comment]
Other things related to communities types, channels etc. look good, thanks @qfrank!

**Comment by qfrank** [comment]
> @qfrank thank you for PR!!
> 
> I made manual nightly build from this branch and the option is available [there](https://ci.infra.status.im/job/status-mobile/job/manual/290/)
> 
> Expected that it will be available in PRs and e2e builds only.

it should be resolved now @churik 🙏

**Comment by churik** [comment]
For some reason, in PR builds only token gated community is available.
IMAGE 2023-08-01 16:34:21
No option available on nightly, how expected, thank you!

**Comment by qfrank** [comment]
> For some reason, in PR builds only token gated community is available.

this should be fixed now with latest commit @churik

**Comment by yevh-berdnyk** [comment]
Hi @qfrank,
Now we can't see any issues here, thanks!

**Pull request merged**
