### PR TITLE
fix: community permission context not passing community-id

### LINKED ISSUE #19661: Broken UI when opening a channel before joining a community
# Bug Report

### Reproduction

1. Open an open community, e.g https://status.app/c/iw2AChoKB1RHIDJfMjgSBGR2ZnYYASIHI0VDMjY2QwM=#zQ3shUWBq4d1tLnQZdPn1Fz2FfRxcxh71H2oCxqsmU66hwqXg
2. Open `#general` channel
3. Press `Join community to post`

https://github.com/status-im/status-mobile/assets/67952253/64ba618c-7c1b-4cea-aa38-e8d29c5d4743

### Additional Information

- Status version: nightly 16/04
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by clauxx**
fixes #19661

### Summary

[comment]: # (Summarise the problem and how the pull request solves it)
Fixed the permission context for community channel not showing the community information

status: ready

### CODE REVIEW

**Review by flexsurfer — APPROVED** [review]

**Review by ibrkhalil — APPROVED** [review]
lgtm

**Comment by mariia-skrypnyk** [comment]
Hi @clauxx !

Thanks for your PR!
Please, see small issue described below:

**ISSUE 1: Request to join has incorrect alignment**

**Steps:**

1. Open an open community, e.g https://status.app/c/iw2AChoKB1RHIDJfMjgSBGR2ZnYYASIHI0VDMjY2QwM=#zQ3shUWBq4d1tLnQZdPn1Fz2FfRxcxh71H2oCxqsmU66hwqXg
2. Open #general channel
3. Press Join community to post

**Actual result:** 
Screenshot 2024-04-19 at 14 12 49

**Expected result:**
Screenshot 2024-04-19 at 14 12 02
https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?type=design&node-id=650-30484&mode=design&t=0XGUrkz6xEC8qvDu-0

**Comment by mariia-skrypnyk** [comment]
Hi @clauxx !

Will you be able to fix this small issue?

**Comment by clauxx** [comment]
Hey, I think this issue is fixed outside this PR. Wasn't caused by this PR

**Comment by mariia-skrypnyk** [comment]
Testing is Blocked by https://github.com/status-im/status-mobile/issues/19736

**Comment by mariia-skrypnyk** [comment]
Thanks @clauxx !

Failed e2e are not related, you can merge your PR!

**Pull request merged**
