### PR TITLE
Top bar stability & animation improvements

### LINKED ISSUE #16564: Top bar followup issues
followup of https://github.com/status-im/status-mobile/pull/16506 cc @alwx 

### ISSUE 1 Top bar disappears when user is at the beginning of chat history (IOS)

Reproducible on IOS only

**Steps:** 

1. Start a new chat
2. Send a couple of messages
3. See if top bar is displayed when closing/opening keyboard

**Actual result:** top bar disappears. 

https://github.com/status-im/status-mobile/assets/97245802/7190d2d2-30a7-421e-8b89-49d61823b36b

### Additional Information

- Status version: nightly 
- Operating System: iOS

### PR DESCRIPTION
**Pull request by alwx**
fixes #16564 

Basically almost all the issues described in #16564 are caused by one problem: improper calculation of `scroll-y` when user hides and shows the keyboard.

#### Platforms

- Android
- iOS

##### Functional

- 1-1 chats
- public chats

status: ready

### CODE REVIEW

**Review by ilmotta — APPROVED** [review]
Seems to work well in my poor tests @alwx. Nice fix.

> Basically almost all the issues described [...]

Which bugs still remain to be fixed?

**Comment by alwx** [comment]
@ilmotta just the design improvements (super small ones) — it's `ISSUE 2 See comments from @Francesca-G related to top bar` in the description

**Comment by ilmotta** [comment]
> @ilmotta just the design improvements (super small ones) — it's `ISSUE 2 See comments from @Francesca-G related to top bar` in the description

Awesome! Thanks

**Comment by pavloburykh** [comment]
@alwx please take a look at the issues

### ISSUE 1 Top bar disappears after removing user from contacts and going back to 1-1 chat (Android)

It is originally reported [here](https://github.com/status-im/status-mobile/issues/16564#issuecomment-1660543579) and is still reproducible

Reproduced on Android 12, Samsung Galaxy A52

**Preconditions:** User A (Android) and User B (any other platform) are mutual contacts. They have 1-1 chat with some amount of history in it and at least 1 message from User B. 

**Steps:** 

1. User A enters 1-1 chat with User B
2. User A opens User's B profile screen by tapping on his profile icon aside of his message in chat
3. User A removes User B from contacts
4. User A goes back to 1-1 chat
5. Pay attention at top bar

**Actual result:** top bar disappeared. It re-appears after chat re-opening. 


https://github.com/status-im/status-mobile/assets/97245802/d6c75543-2a6b-426a-9691-3c250a318d3e

**Comment by pavloburykh** [comment]
### ISSUE 2 Wrong opacity of pinned bar after chat opening

**Steps:** 

1. Generate some chat history
2. Pin a message
3. Re-open chat
4. Pay attention at pin bar opacity

**Actual result:** pin bar is transparent. Opacity is being fixed after chat scrolling.

photo_2023-09-04 16 42 56

https://github.com/status-im/status-mobile/assets/97245802/d3d254b3-5d23-44b2-8418-40c0142f4a38

**Review by flexsurfer — APPROVED** [review]

**Comment by alwx** [comment]
@pavloburykh fixed; ready to be checked again!

**Comment by churik** [comment]
@alwx 

confirmed that top-bar improved a lot, tested on IPhone 14 + Google Pixel 7

**Comment by churik** [comment]
@Francesca-G can you please look at this one if there are no clear blockers from your side? 
Thank you!

**Comment by pavloburykh** [comment]
> @ilmotta just the design improvements (super small ones) — it's `ISSUE 2 See comments from @Francesca-G related to top bar` in the description

@Francesca-G please, take into consideration that these comments https://github.com/status-im/status-mobile/issues/16564#issuecomment-1631327237 were not addressed in this PR. So followup will be required cc @alwx

**Review by Francesca-G — APPROVED** [review]
It looks good from a design perspective.

The only thing I'd address is that the top bar doesn't load quickly when I open and close the composer:


https://github.com/status-im/status-mobile/assets/122543089/02f219cb-a486-4c82-b284-a849fb011ad0

**Comment by alwx** [comment]
@pavloburykh @Francesca-G yes, this will be done in a separate PR today/tomorrow. Will not be closing the original issue.

**Pull request merged**
