### PR TITLE
fix!: cache data related to token price and market data locally for GetWalletToken

### PR DESCRIPTION
**Pull request by seanstrom**
[comment]: # (Please replace ... with your information. Remove < and >)
[comment]: # (To auto-close issue on merge, please insert the related issue number after # i.e fixes #566)

related to: https://github.com/status-im/status-mobile/issues/20975
related status-go pr: https://github.com/status-im/status-go/pull/5832
related status-desktop pr: https://github.com/status-im/status-desktop/pull/16347
and a continuation of [the "balance zero" work group](https://www.notion.so/Working-group-for-0-balances-and-provider-being-down-blocker-7125b05e3a3d4247b09378d3b50120e6?pvs=4)

### Summary

[comment]: # (Summarise the problem and how the pull request solves it)

* This PR attempts to resolve some of the issues with the mobile app displaying a balance of zero by updating status-go to cache the related token price and market data.
* Currently the status-go can occasionally be rate-limited when making too many requests from refreshing the wallet home screen. When the requests are rate-limited 

### Testing notes

The main areas that should be affected is the wallet home screen, and technically some changes happened for wallet router, so it would be worth double checking that wallet transactions / estimates are still working.

#### Platforms

- Android
- iOS

##### Functional

- wallet home screen
- wallet transactions / router

### Steps to test

- Open Status mobile
- Login as a user
- Navigate to the wallet home screen
- Pull to refresh many times quickly (roughly 5 times under 60 seconds)
- View the wallet balance and token balances

#### Before Changes

https://github.com/user-attachments/assets/dd7a2fd7-ef9a-4c5b-9620-bdcc59b33592

#### After Changes

https://github.com/user-attachments/assets/54bc1e55-4fe0-48fc-ae0b-553a2243eac9

### Risk

Described potential risks and worst case scenarios.

Tick **one**:
- [ ] Low risk: 2 devs MUST perform testing as specified above and attach their results as comments to this PR **before** merging.
- [x] High risk: QA team MUST perform additional testing in the specified affected areas **before** merging.

status: ready

### CODE REVIEW

**Review by Parveshdhull — APPROVED** [review]

**Review by ilmotta — APPROVED** [review]
Nice work @seanstrom!

Linking directly with status-go PR https://github.com/status-im/status-go/pull/5832

> Pull to refresh many times quickly (roughly 5 times under 10 seconds)

In status-go we're caching for 60s, is there a reason the user can't pull to refresh less frequently and still benefit from caching? I'm just trying to understand the impact to users and I thought the effects would be positive even with just 2 pulls to refresh per 60s.

There's this Figma under construction by @xAlisher that will impact the behavior of pull to refresh and how we inform users about the freshness of balances and token prices https://www.figma.com/design/xLs1KYmF4e6WwRTZVJKeUK/Wallet?node-id=17025-536817&node-type=frame&t=WysUpXeljfC2aaUv-0. In future iterations about caching, we should try to align the technical implementation with this new UX once it's finalized and prioritized. cc @shivekkhurana

**Comment by seanstrom** [comment]
> Nice work @seanstrom!
> 
ty 🙌 

> Linking directly with status-go PR [status-im/status-go#5832](https://github.com/status-im/status-go/pull/5832)
> 

Oops I forgot to link that PR, I'll add that link to the description 🙏 

> > Pull to refresh many times quickly (roughly 5 times under 10 seconds)
> 
> In status-go we're caching for 60s, is there a reason the user can't pull to refresh less frequently and still benefit from caching? I'm just trying to understand the impact to users and I thought the effects would be positive even with just 2 pulls to refresh per 60s.
> 

You're absolutely right, users will benefit for the cache for the 60s. Pulling to refresh 5 times is only necessary to show the glitch when the data is not cached.

> There's this Figma under construction by @xAlisher that will impact the behavior of pull to refresh and how we inform users about the freshness of balances and token prices. In future iterations about caching, we should try to align the technical implementation with this new UX once it's finalized and prioritized.

Yeah definitely agree that we should try to explain how fresh the data is to the user, and the good news is that we timestamp the data for token-pricing and market-data inside status-go, so we could eventually forward that extra context to the status-mobile client. Although, I'm not sure if we track the timestamps for each network chain.

**Comment by VolodLytvynenko** [comment]
hi @seanstrom thank you for PR. No issues from my side. PR is ready to be merged

**Comment by seanstrom** [comment]
I've updated the commit in this PR to update status-go to version `v2.1.0`.
Do we want to update the status-go version in this PR, or will we do it later?
Let me know if there's anything else to do before merging please 🙏

cc @VolodLytvynenko

**Comment by VolodLytvynenko** [comment]
> I've updated the commit in this PR to update status-go to version `v2.1.0`. Do we want to update the status-go version in this PR, or will we do it later? Let me know if there's anything else to do before merging please 🙏
> 
> cc @VolodLytvynenko

@seanstrom hey. thank you for the update. The PR with updated status go works well. Can be merged. Thank you!

**Pull request merged**
