### PR TITLE
chore : rename crypto phrases, buy Eth and buy assets

### LINKED ISSUE #21396: [EPIC] ⏫ Update crypto purchase copy
# Feature Issue

The legal wants to change how we display certain words and phrases around buying crypto and swaps. 
Although not urgent, it will be good to get this in 2.31.

### User Story

As a legal representative of Status
I want certain "words and phrases" to be changed
To best protect our interests and position as an open-source wallet

### Description

Discord Conversation: https://discord.com/channels/1210237582470807632/1217171454940938341/1291440846838693970

### Acceptance Criteria

All sub issues should be resolved.

### LINKED ISSUE #21397: ✏️ Rename "Buy Assets" to "Ways to Buy Assets"
# Feature Issue

For legal purposes, we need to change the phrase on the wallet screen.

Figma Link:
https://www.figma.com/design/xLs1KYmF4e6WwRTZVJKeUK/Wallet?node-id=15725-76906&m=dev

### Acceptance Criteria

- [x] The buy modal should say "Ways to buy" matching Figma Design

### LINKED ISSUE #21398: 📝  Rename copy on accounts page buy assets button
# Feature Issue

For legal reasons, we need to avoid using the term "Buy assets". Instead, use "Ways to buy assets"

Figma Link: https://www.figma.com/design/xLs1KYmF4e6WwRTZVJKeUK/Wallet?node-id=16641-94692&m=dev

### Acceptance Criteria

- [x] When a user clicks Buy assets from an individual wallet account screen, the modal should show the title "Ways to buy assets" like in Figma file

### LINKED ISSUE #21399: 🪙 Change copy when prompting to buy ETH in case of low gas
# Feature Issue

Change buy crypto copy on low gas error. This error happens on Send, Swap and Bridge.

### Description

Send/Bridge Figma Link: https://www.figma.com/design/xLs1KYmF4e6WwRTZVJKeUK/Wallet?node-id=16655-189081&m=dev

Swaps Figma Link: https://www.figma.com/design/AD2JSKg0I8dZcylyiGa62O/Swap-for-Mobile?node-id=48-124279&m=dev

Change the copy on the `Buy` button and `Buy Assets` modal title. 

### Acceptance Criteria

**Swap Flow**
- [ ] The new copy should show "Add Eth" on the button
- [ ] The modals should show "Ways to buy assets" as in Figma File 

**Bridge Flow**
- [ ] The new copy should show "Add Eth" on the button
- [ ] The modals should show "Ways to buy assets" as in Figma File 

**Send Flow**
- [ ] The new copy should show "Add Eth" on the button
- [ ] The modals should show "Ways to buy assets" as in Figma File

### LINKED ISSUE #21400: ✏️ Change copy that prompts the user to buy a missing asset while swapping
# Feature Issue

[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a <user|developer|...>, I want to <task> **so that** <goal>. 

### Description

Figma Link: https://www.figma.com/design/AD2JSKg0I8dZcylyiGa62O/Swap-for-Mobile?node-id=171-36214&m=dev

When the user is swapping an asset, it's possible that she might not have enough tokens to swap. This is where we plugin our error message with a CTA to buy. 

For legal reasons we should not call it "Buy", but "Add assets" (check figma file). The title of the buy modal should also be updated. 

### Acceptance Criteria

- [ ] In case of insufficient assets to swap the CTA on error should say "Add assets"
- [ ] The buy modal should be titled "Ways to buy assets"

### PR DESCRIPTION
**Pull request by mohsen-ghafouri**
fixes #21396

It closes subtasks: 

- fixes #21397
- fixes  #21398 
- fixes #21399 
- fixes #21400

### Summary

rename "buy ETH" -> "Add ETH" , "Buy assets" -> "Add assets", "Buy Assets" in title -> "Ways to buy assets"

### Testing notes
No code changes, only labels. please check if e2e needs any adjustment. 

status: ready

### CODE REVIEW

**Review by shivekkhurana — APPROVED** [review]

**Review by ulisesmac — APPROVED** [review]

**Review by briansztamfater — APPROVED** [review]
LGTM!

**Comment by Horupa-Olena** [comment]
@mohsen-ghafouri Hi! Thanks for your PR!
Please rebase it and fix the errors, because my try was failed(

**Comment by Horupa-Olena** [comment]
@mohsen-ghafouri Hello! Thanks for your PR. All looks great, but I have few questions.

1. Did you work on renaming the button for the collectibles send flow? I’m encountering an error that doesn’t match the [design](https://www.figma.com/design/xLs1KYmF4e6WwRTZVJKeUK/Wallet?node-id=16655-189054&node-type=frame&t=nFkcJjnT3zZ0OzKX-0). Can this be fixed in this PR, or should I submit a separate bug report?

IMG_0015

2. Also, are the changes only related to 'Buy ETH' and 'Buy assets'? Do we need to change 'Buy crypto' as shown on the screen?
IMG_0016

**Comment by mohsen-ghafouri** [comment]
Hi @Horupa-Olena, thanks for testing this PR, for point 1, no i didn't have any changes regarding this kind of error and it's different from Not enough asset. 
for point 2, we only changed the title of modal. there wasn't any request about modal list item changes in mentioned issue's description.

**Review by jakubgs — COMMENTED** [review]
Not sure how I'm related to these changes.

**Comment by Horupa-Olena** [comment]
@mohsen-ghafouri Thanks for your answers. You can merge this PR, I don't see any other issues.

**Pull request merged**
