### PR TITLE
[WIP] Feature/Network Confirguation (#1091)

### LINKED ISSUE #1091: Network Configuration
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As user, I want to switch networks so that I can use Status on mainnet. 

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Implement the designs we have and reboot node after switching networks.

### PR DESCRIPTION
**Pull request by flexsurfer**
[comment]: # (Please replace ... with your information. Remove < and >)
[comment]: # (To auto-close issue on merge, please insert the related issue number after # i.e fixes #566)
fixes #1091

### Steps to test:
- Open Status
- Open Profile
- Open Network Settings
- Connect to another network

[comment]: # (PRs will only be accepted if squashed into single commit.)
status: wip

### CODE REVIEW

**Comment by rasom** [comment]
When i'm trying to create a new account (after reinstalling application) I can't finish creation as app stays in the next state:

**Comment by flexsurfer** [comment]
1) we need to know which network is currently running to avoid restarting if user switches to account with the same network (reason of behavior in previous comment [above](https://github.com/status-im/status-react/pull/1115#issuecomment-298519775))
2) we need to show loader if node is restarting, as this takes some time (waiting design from @andmironov )
3) we need to write iOS code 
4) implement `VerifyAccount` method (waiting https://github.com/status-im/status-go/issues/151)
5) implement stop node signal (waiting https://github.com/status-im/status-go/issues/152)

**Comment by 3esmit** [comment]
While we are in alpha, would be nice to add a warning when logging into mainnet and/or in mainnet transactions password screen.

**Comment by jarradh** [comment]
Yes actually we should be making it much more clear that Status is in alpha in general

**Comment by annadanchenko** [comment]
App crashes if browse some url or open a DApp than put app to background and bring back to foreground.
- In Console @browse google.com
- put app to back ground
- put app to foreground -> crash

iOS 10.3.2, iPhone 7 plus
[StatusIm-2017-05-26-105137.crash.txt](https://github.com/status-im/status-react/files/1031202/StatusIm-2017-05-26-105137.crash.txt)

**Comment by annadanchenko** [comment]
on iOS: app crashes if use Auction House DApp. Sometimes it happens on tap on "Create an Auction" - app does not respond and crash. If not then it crashes if Register a name for sample name asset: Create an auction, in Name to reserve type "somethingdoesnot.eth" and tap Register Name. At this point app stops responding - you can't close window or scroll and than it crashes
[StatusIm-2017-05-29-220843.crash.txt](https://github.com/status-im/status-react/files/1036491/StatusIm-2017-05-29-220843.crash.txt)

[crash2208.consolelog.txt](https://github.com/status-im/status-react/files/1036492/crash2208.consolelog.txt)

**Comment by annadanchenko** [comment]
Sometimes app crashes after confirming transaction initiated from Auction House DApp or after closing Auction House:
- Open Auction House
- Tap on Create an auction
- in Name to reserve type "somerandomname.eth" and tap Register Name. 
- Wait for confirm transaction screen
- confirm transaction and tap on Got it
At this moment in some case app freezes. If not: close Action House. Tap on back to return to Chats. Sometimes on this action app freezes

[StatusIm-2017-05-30-103958.crash.txt](https://github.com/status-im/status-react/files/1037599/StatusIm-2017-05-30-103958.crash.txt)

**Pull request closed without merging**
