### PR TITLE
chore: statusgo changes to remove default pubsubtopic (not to merge)

### PR DESCRIPTION
**Pull request by chaitanyaprem**
### Summary
Includes changes from https://github.com/status-im/status-go/pull/5474 which changes statusgo to only use shards and no defaultpubsubTopic. This is for dogfooding only.

#### Areas that maybe impacted

Communities and messaging.

- Test community creation and shard assignment. Try asssigning a community to shard 128 or 256(not sure if this is possible from mobile).
- Send and receive of messages should work before and after assignment of the community.
- Join community and send/receive messages.
- All messaging send and receive i.e communities, groups and 1:1 chat.

##### Functional

- 1-1 chats
- public chats
- group chats
- community chats

status: ready 

### Risk

Described potential risks and worst case scenarios.

Tick **one**:
- [ ] Low risk: 2 devs MUST perform testing as specified above and attach their results as comments to this PR **before** merging.
- [x] High risk: QA team MUST perform additional testing in the specified affected areas **before** merging.

### CODE REVIEW

**Comment by pavloburykh** [comment]
@chaitanyaprem unfortunately we cannot proceed with testing as currently we experience global Waku issues which result in communities failed to be fetched. This is a reason why [e2e](https://github.com/status-im/status-mobile/pull/20658#issuecomment-2210300356) run in this PR has mostly failed. 

I have already pinged Waku team about the problem, waiting for the fix. 

Here is example of logs of a user from this PR who failed to fetch community when following community link. 

[Status-debug-logs - 2024-07-05T101140.382.zip](https://github.com/user-attachments/files/16106612/Status-debug-logs.-.2024-07-05T101140.382.zip)

**Comment by chaitanyaprem** [comment]
> @chaitanyaprem unfortunately we cannot proceed with testing as currently we experience global Waku issues which result in communities failed to be fetched. This is a reason why [e2e](https://github.com/status-im/status-mobile/pull/20658#issuecomment-2210300356) run in this PR has mostly failed.
> 
> I have already pinged Waku team about the problem, waiting for the fix.
> 
> Here is example of logs of a user from this PR who failed to fetch community when following community link.
> 
> [Status-debug-logs - 2024-07-05T101140.382.zip](https://github.com/user-attachments/files/16106612/Status-debug-logs.-.2024-07-05T101140.382.zip)

Can we rerun e2e once to check..i think store node issue is resolved.

**Comment by pavloburykh** [comment]
> Can we rerun e2e once to check..i think store node issue is resolved.

Hello @chaitanyaprem! Unfortunately it is not. You can track discussion here https://discord.com/channels/1110799176264056863/1250797808227979364

**Comment by pavloburykh** [comment]
@chaitanyaprem store nodes issue should be resolved. Could you please rebase status go and mobile branches? After that I will proceed with testing.

**Comment by chaitanyaprem** [comment]
> @chaitanyaprem store nodes issue should be resolved. Could you please rebase status go and mobile branches? After that I will proceed with testing.

rebased both statusgo and mobile. we can rerun the tests now.

**Comment by pavloburykh** [comment]
@chaitanyaprem thanks for rebasing. 

Unfortunately our e2e still failing but this time due to other issue (related to our sessions provider). It prevents us from getting valid e2e results. 

Meanwhile I have tried to test sharded communities manually and I am facing the issue below

### ISSUE 1 Community on shard 128/256 cannot be fetched

**Steps:** 

1. Create community on Desktop
2. Enable shards and assign community to 128 or 256 shard
3. Share community to mobile user
4. Follow community link by mobile user
5. See if community is fetched

**Actual result:** community failed to fetch. At the same time I am able to fetch non sharded community

[Status-debug-logs - 2024-07-10T152915.050.zip](https://github.com/user-attachments/files/16161972/Status-debug-logs.-.2024-07-10T152915.050.zip)

https://github.com/status-im/status-mobile/assets/97245802/cc47541c-3ea4-4131-9db9-65b5e430980c

**Examples of sharded communities:** 

256 shard https://status.app/c/ixSACiEKCnNoYXJkcyAyNTYSCGRzYWRzYWRhGAEiByM0MzYwREYSBQgQEIACAw==#zQ3shtuPJUXmesqAtBVzLJFXHzodKYNft1RjZUodqkXCiRDKg

128 shard https://status.app/c/ixqACi0KFFNoYXJkIDEyOCBjb21tdW5pdHlkEgVzYWRzYRgBIgcjNDM2MERGKgMAAQISBQgQEIABAw==#zQ3shbcMeFGge7G6zxsTvnYMoWNHJnN1w6r5igfaUJTWLU2UE

**Comment by pavloburykh** [comment]
@chaitanyaprem recent [e2e run](https://github.com/status-im/status-mobile/pull/20658#issuecomment-2221087027) is fine. But we still need to take a look at [ISSUE 1 ](https://github.com/status-im/status-mobile/pull/20658#issuecomment-2220393506)

**Comment by chaitanyaprem** [comment]
> @chaitanyaprem recent [e2e run](https://github.com/status-im/status-mobile/pull/20658#issuecomment-2221087027) is fine. But we still need to take a look at [ISSUE 1 ](https://github.com/status-im/status-mobile/pull/20658#issuecomment-2220393506)

any thoughts on what could the issue be @richard-ramos ? 
went through community code briefly, and noticed that shard info for a community is published by control node constantly.
Did the changes modify the shard this message is sent?

**Comment by chaitanyaprem** [comment]
> Status-debug-logs - 2024-07-10T152915.050.zip

These logs are not that helpful as i couldn't find the logs related to trying to fetch the community.
Is this reproducible? If i try to access one of the links now, obviously it fails because the control node seems to be offline after July-9th and hence updated-communityinfo may not be present in store node.

**Comment by chaitanyaprem** [comment]
> **Steps:**
> 
>     1. Create community on Desktop
> 
>     2. Enable shards and assign community to 128 or 256 shard
> 
>     3. Share community to mobile user
> 
>     4. Follow community link by mobile user
> 
>     5. See if community is fetched

@pavloburykh i have tested the steps but with desktop instance and i see the community (assigned to shard 128) is fetched successfully by the link from another desktop instance and a mobile instance as well.
Wondering maybe there was a storeNode issue which has caused fetch failure when you are testing?

This is the test-community link on shard 128 that works without issues for me.

https://status.app/c/GzYAAGS97cHYg92T-JFvUJ6FpyQFsAGnAXvCgQyEN0J1p3BgKapeBPt0beOsFZDnVGixm93pziERfQA=#zQ3shhm5wzug1yAcHZtStPkxyHcWQ1MipzK4BFpjXntmVGZe7

**Comment by chaitanyaprem** [comment]
Closing this PR as dogfooding is done and underlying status-go PR is ready to merge.

**Pull request closed without merging**
