### PR TITLE
Transactions UI refresh code review

### PR DESCRIPTION
**Pull request by GustavoNunes**
### Summary:
Fixes some leftovers from #953 review.

status: ready

### CODE REVIEW

**Comment by rasom** [comment]
@GustavoNunes, please resolve conflicts

**Comment by GustavoNunes** [comment]
@rasom, unfortunately this is still not ready, I'm having an issue very similar to https://github.com/facebook/react-native/issues/9822, just lost some 5 hours trying to fix it. I will take another look tomorrow, if I can't make progress I will finish the PR without this feature.

Exactly this is happening, btw:
https://cloud.githubusercontent.com/assets/2188620/18381821/5ea49ea4-767e-11e6-9da6-b0f935b45384.gif

**Comment by flexsurfer** [comment]
@GustavoNunes I think it's right behavior, user shouldn't have the ability to enter text when he doesn't see the textinput, so it's better to make password field sticky to bottom, imo, or we can modify list of transactions and when user enters the password we can show details for all transactions not the list of transactions, for example, "you're confirming 4 transactions for a total of  5 ETH"

**Comment by GustavoNunes** [comment]
@rasom, this now contains just minor code changes from #953, and is ready for review.

@flexsurfer I agree that the text input must be visible, however the bug is that Android isn't adding padding to the bottom to compensate the keyboard (like it does correctly with our `sticky-button`, for example).

I will check with @andmironov about this, whether we keep the sticky form or add a separate screen for it.

Also @flexsurfer, I couldn't find a satisfactory code design for [the renderer](https://github.com/status-im/status-react/pull/953#discussion_r110327133), that's because this specific case requires both a condition using the `row-id` from the callback, and a custom style.
I think it is fine not to use the common renderer in such different use-case, it is still useful for the more common lists.

**Pull request merged**
