### PR TITLE
Fix for Android error `route ip+net: netlinkrib: permission denied`

### LINKED ISSUE #17156: `Reveal` sync code is broken on Android (stays blurred)
# Bug Report

#### Expected behavior
can see QR

#### Actual behavior

Uploading FILE 2023-08-31 13:59:32.mp4…

### Reproduction

1. Open Profile > Syncing> +
2. Reveal sync code, enter valid password

### Additional Information

- Status version: nightly 31/08/2023
- Operating System: Android

[comment]: # (Please, add logs/notes if necessary)
[Status-debug-logs.zip](https://github.com/status-im/status-mobile/files/12485827/Status-debug-logs.zip)

### PR DESCRIPTION
**Pull request by Samyoul**
Mobile build of https://github.com/status-im/status-go/pull/3982

Resolved https://github.com/status-im/status-mobile/issues/17156

### CODE REVIEW

**Comment by Samyoul** [comment]
Hey @status-im/on-call there seems to be something weird going on with this PR, it keeps failing to build for Android

**Comment by Samyoul** [comment]
Follow up on the Android build failure, the root `status-go` PR is building for android fine https://ci.status.im/job/status-go/job/prs/job/android/job/PR-3982/1/display/redirect

**Comment by churik** [comment]
@Samyoul 
Fix for Android error `route ip+net: netlinkrib: permission denied` by Samyoul · Pull Request #17166 · status-im:status-mobile 2023-09-04 11-01-16
is not that an issue?

**Review by qfrank — APPROVED** [review]

**Comment by churik** [comment]
@qfrank 
Android still stuck on scanning QR from Desktop RC (go-version[ 0.164](https://github.com/status-im/status-go/tree/v0.164.0)).
Logs from Android: [Status-debug-logs.zip](https://github.com/status-im/status-mobile/files/12514185/Status-debug-logs.zip)


@qfrank can you please recheck whether it is the same https://github.com/status-im/status-mobile/issues/17137#issuecomment-1705187880 or https://github.com/status-im/status-mobile/issues/16987 ? 

should I report it separately or add info to existing issues?

**Comment by qfrank** [comment]
> can you please recheck whether it is the same https://github.com/status-im/status-mobile/issues/17137#issuecomment-1705187880 or https://github.com/status-im/status-mobile/issues/16987 ?
should I report it separately or add info to existing issues?

they are the same @churik

**Comment by Samyoul** [comment]
@churik I've pushed an updated version using the commit hash as the target. I didn't realise that targeting PR number would cause a problem with the build... Well we'll see what happens

**Comment by qfrank** [comment]
> @churik I've pushed an updated version using the commit hash as the target. I didn't realise that targeting PR number would cause a problem with the build... Well we'll see what happens

Hi @Samyoul , welcome back! Your PR on status-go side seems not work according their test [result](https://github.com/status-im/status-mobile/pull/17166#issuecomment-1705289777) (I've updated status-go-version.go to point to your status-go PR before) ..

**Comment by churik** [comment]
@qfrank 
scanning QR with the current desktop master (go v 0.166.5) is not working either (Android)

Logs: 
[Status-debug-logs.zip](https://github.com/status-im/status-mobile/files/12514573/Status-debug-logs.zip)

**Comment by qfrank** [comment]
Hi @churik , pls let me know if the new commit works for you, thank you! cc @pavloburykh @VolodLytvynenko

**Comment by churik** [comment]
@qfrank 
With current desktop master now I can scan QR, but the app is stuck on the "Syncing device" stage, waited for 5 mins - no success.
IMAGE 2023-09-04 17:53:14
[Status-debug-logs.zip](https://github.com/status-im/status-mobile/files/12515136/Status-debug-logs.zip)

**Comment by qfrank** [comment]
> @qfrank With current desktop master now I can scan QR, but the app is stuck on the "Syncing device" stage, waited for 5 mins - no success. IMAGE 2023-09-04 17:53:14 [Status-debug-logs.zip](https://github.com/status-im/status-mobile/files/12515136/Status-debug-logs.zip)

Hi @churik , would you mind retry using release version of desktop which use status-go v0.164.0 ?  because the test get passed with my last commit in my local machine using android emulator, but the issue can be reproduced without my last commit

**Comment by VolodLytvynenko** [comment]
> v0.164.0

Hi @qfrank I'm still unable to sync using Android and IOS, even when trying to sync with the release desktop where status go is v0.164.0.

### Actual result:
- When the camera is pointed at the sync QR code, the "Oops, something went wrong" screen is displayed. 
- Then: The app is stuck on the "Syncing device" stage when 'try again' button is tapped

 https://github.com/status-im/status-mobile/assets/52490791/de3adc6c-a1da-4270-be09-8732c3f936fe

### Device:
- Real device: Pixel 7a, Android 13
- Real device: iPhone 11 Pro max, IOS 16.6
### Logs:
[android_logcat.txt](https://github.com/status-im/status-mobile/files/12520268/android_logcat.txt)
[Status.log](https://github.com/status-im/status-mobile/files/12520285/Status.log)
[geth.log](https://github.com/status-im/status-mobile/files/12520287/geth.log)

**Comment by qfrank** [comment]
emm... 
another error:
```
09-05 10:32:54.880 15935 16043 I ReactNativeJS: INFO [status-im2.contexts.syncing.events:70] - Initiated local pairing {:response "{\"error\":\"failed to connect to any of given addresses. connecting to 'https://192.168.0.103:57548' failed: dial tcp 192.168.0.103:57548: connect: no route to host; \"}", :event :syncing/input-connection-string-for-bootstrapping}
```
cc @Samyoul

**Comment by Samyoul** [comment]
Oh man, thank you @qfrank hmm, I wonder if this is related to matching the ip to network?

**Comment by qfrank** [comment]
> Oh man, thank you @qfrank hmm, I wonder if this is related to matching the ip to network?

android logcat shows device was using `192.168.0.106` i guess? Do you mean the server on desktop side has a restriction on the ip coming from client?

```
:32:53.505  I  1141 [CONN] WiFi connected [SLID:0], network: 173 [com.shannon.imsservice.conn.DefaultNetworkCallback@346fca3] (DefaultNetworkCallback%onCapabilitiesChanged:42)
10:32:53.506  D  9207 [0][PROX][TELE] onCapabilitiesChanged, Network: 173, NetworkCapabilities: [ Transports: WIFI Capabilities: NOT_METERED&INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN&VALIDATED&NOT_ROAMING&FOREGROUND&NOT_CONGESTED&NOT_SUSPENDED&NOT_VCN_MANAGED LinkUpBandwidth>=26767Kbps LinkDnBandwidth>=40792Kbps TransportInfo: <SSID: <unknown ssid>, BSSID: 02:00:00:00:00:00, MAC: 02:00:00:00:00:00, IP: /192.168.0.106, Security type: 2, Supplicant state: COMPLETED, Wi-Fi standard: 5, RSSI: -56, Link speed: 526Mbps, Tx Link speed: 526Mbps, Max Supported Tx Link speed: 866Mbps, Rx Link speed: 650Mbps, Max Supported Rx Link speed: 866Mbps, Frequency: 5180MHz, Net ID: -1, Metered hint: false, score: 60, isUsable: true, CarrierMerged: false, SubscriptionId: -1, IsPrimary: -1, Trusted: true, Restricted: false, Ephemeral: false, OEM paid: false, OEM private: false, OSU AP: false, FQDN: <none>, Provider friendly name: <none>, Requesting package name: <none><none>MLO Information: , AP MLD Address: <none>, AP MLO Link Id: <none>, AP MLO Affiliated links: <none>> SignalStrength: -56 UnderlyingNetworks: Null] (DefaultNetworkCallback%onCapabilitiesChanged:76)
10:32:53.506  I  [57] gko.c: Connected state: [1], networkType: [WIFI]
```

**Comment by Samyoul** [comment]
Thank you @VolodLytvynenko for your work repeatedly testing this issue. I have implemented some additional fixes for this problem and all problems related to accessing network data on an Android device should be resolved now. I'm sorry for all of these bugs.

**Comment by VolodLytvynenko** [comment]
> Thank you @VolodLytvynenko for your work repeatedly testing this issue. I have implemented some additional fixes for this problem and all problems related to accessing network data on an Android device should be resolved now. I'm sorry for all of these bugs.

This is no problem for me. Thank you for fixing it!

**Comment by VolodLytvynenko** [comment]
Hi @Samyoul @qfrank The devices already don't get stuck if to scan the desktop release **v0.164.0** and master  code, but the 'Oops, something went wrong' screen always appears for Android and iOS devices after a valid QR code sync

### Actual result:
The 'Oops, something went wrong' screen always appears for Android and iOS devices after a valid QR code sync

https://github.com/status-im/status-mobile/assets/52490791/c9fd03cc-7f0e-41e8-979e-97b807e4a3bc




### Logs:
[android_logcat.txt](https://github.com/status-im/status-mobile/files/12522585/android_logcat.txt)
[Status.log](https://github.com/status-im/status-mobile/files/12522593/Status.log)
[geth.log](https://github.com/status-im/status-mobile/files/12522594/geth.log)


### Devices:
- iPhone 11 Pro max, 16 IOS
- Pixel 7a, Android 13

### ADDITIONAL INFO:
The same behavior when  master desktop with 0.166.5 status go is scanned

**Comment by Samyoul** [comment]
Thank you. Ok so this is good news, the happy path is working, but if we test for feature robustness it falls over. 🎉 🫣

So the problems reported in https://github.com/status-im/status-mobile/issues/17156 and https://github.com/status-im/status-mobile/issues/17137 seem to be resolved. We now need to resolve the problem with trying to scan the QR code again.

Is that correct @VolodLytvynenko ?

**Comment by Samyoul** [comment]
```
13:52:09.554  I  INFO [status-im2.contexts.syncing.events:70] - Initiated local pairing {:response "{\"error\":\"failed to connect to any of given addresses. connecting to 'https://192.168.0.103:61851' failed: dial tcp 192.168.0.103:61851: connect: no route to host; \"}", :event :syncing/input-connection-string-for-bootstrapping}
13:52:09.555  D  DEBUG [utils.re-frame:21] - Handling re-frame event:  :signals/signal-received
13:52:09.556  I  INFO [status-im.signals.core:33] - local pairing signal received {:event {:type "connection-error", :error "failed to connect to any of given addresses. connecting to 'https://192.168.0.103:61851' failed: dial tcp 192.168.0.103:61851: connect: no route to host; ", :action 1}}
13:52:09.560  E  failed to connect to any of given addresses. connecting to 'https://192.168.0.103:61851' failed: dial tcp 192.168.0.103:61851: connect: no route to host; 
```

The main error I see here is `no route to host`, which is a network type error. This means that the Android device cannot target the desktop machine via the network.

**Comment by VolodLytvynenko** [comment]
> Thank you. Ok so this is good news, the happy path is working, but if we test for feature robustness it falls over. 🎉 🫣
> 
> So the problems reported in #17156 and #17137 seem to be resolved. We now need to resolve the problem with trying to scan the QR code again.
> 
> Is that correct @VolodLytvynenko ?

Yep. That's correct. Also works correct when mobile -> mobile are synced

**Comment by qfrank** [comment]
> The main error I see here is no route to host, which is a network type error. This means that the Android device cannot target the desktop machine via the network.

curious what caused this ...  could you show us the detail of network of android device @VolodLytvynenko

**Comment by VolodLytvynenko** [comment]
> could you show us the detail of network of android device

@qfrank sure. Which specific network details would you like me to share? recorded details of my wifi

https://github.com/status-im/status-mobile/assets/52490791/7fd30727-e04e-424d-a8e4-921d06f77f2d

**Comment by qfrank** [comment]
> > could you show us the detail of network of android device
> 
> @qfrank sure. Which specific network details would you like me to share? recorded details of my wifi
> 
>  newwork.mp4

thank you, the detail LGTM, what about the network detail of desktop system(DNS/subnet mask/router etc.)? can you reproduce this issue with ios? @VolodLytvynenko

**Comment by VolodLytvynenko** [comment]
> > > could you show us the detail of network of android device
> > 
> > 
> > @qfrank sure. Which specific network details would you like me to share? recorded details of my wifi
> > newwork.mp4
> 
> thank you, the detail LGTM, what about the network detail of desktop system(DNS/subnet mask/router etc.)? can you reproduce this issue with ios? @VolodLytvynenko

**DNS/subnet mask**
image
image

**router IP**
image

**Comment by VolodLytvynenko** [comment]
@qfrank Just wanted to collect logs from iOS, but it seems this issue is not reproducible for me anymore. I've successfully synced with the desktop, and the same goes for Android. I will investigate it and let you know if it happens again.

**Comment by churik** [comment]
I'll try last builds too with desktop master and desktop RC.

**Comment by VolodLytvynenko** [comment]
@Samyoul @qfrank One question: Did I understand correctly that the scope of this PR is to fix only the happy path, which includes:

- Successful syncing from mobile to desktop.
- Successful syncing from mobile to mobile.
- The mobile device can generate the QR code.

I'm asking because there is an additional issue: the iOS app always crashes after the initial QR code syncing. However, when the app is reopened, the synced account is already displayed and able to be logged in
### Steps
1. The IOS user does not have any created accounts
2. The IOS user syncs with the desktop (status go v0.164.0 or v0.166.5)

### Actual result:
The app crashes on IOS during sync process (but as result the account is synced)


https://github.com/status-im/status-mobile/assets/52490791/9f06818d-1204-4ea9-b92d-214106d2aca9


### Logs:
[Status.log](https://github.com/status-im/status-mobile/files/12523812/Status.log)
https://www.dropbox.com/s/hlt862peoreoa9o/geth.log?dl=0

### Device:
iPhone 11 Pro max, IOS 16

**Comment by churik** [comment]
> the iOS app always crashes after the initial QR code syncing


@VolodLytvynenko yes, it is reproducible for me too

**Comment by churik** [comment]
@VolodLytvynenko @qfrank 
sync is also working in base flow for me between desktop master / pr, desktop rc / pr

If there is no option to fix crash mentioned https://github.com/status-im/status-mobile/pull/17166#issuecomment-1706581496 quite fast, I believe it would be better to merge current PR

**Comment by qfrank** [comment]
> @VolodLytvynenko @qfrank sync is also working in base flow for me between desktop master / pr, desktop rc / pr
> 
> If there is no option to fix crash mentioned [#17166 (comment)](https://github.com/status-im/status-mobile/pull/17166#issuecomment-1706581496) quite fast, I believe it would be better to merge current PR

agreed, not that easy to reproduce using xcode, but it can be reproduced with PR build in 100%, i need to find out the difference between xcode build and PR build.

cc @Samyoul

**Comment by Samyoul** [comment]
Ok, I'll merge https://github.com/status-im/status-go/pull/3982 as this does fix a set of problems. I do have this PR https://github.com/status-im/status-mobile/pull/16694 which is trying to / has already fixed some other pairing issues that seem related to double scanning a QR code.

**Comment by Samyoul** [comment]
> ## Steps
> 1. The IOS user does not have any created accounts
> 1. The IOS user syncs with the desktop (status go v0.164.0 or v0.166.5)
> ## Actual result:
> The app crashes on IOS during sync process (but as result the account is synced)

Ok, this sounds like another problem though with iOS. Where iOS syncs but returns an error after the process has completed Or one of the end pairing processes fail.

**Comment by VolodLytvynenko** [comment]
> > ## Steps
> > 
> > 1. The IOS user does not have any created accounts
> > 2. The IOS user syncs with the desktop (status go v0.164.0 or v0.166.5)
> > 
> > ## Actual result:
> > The app crashes on IOS during sync process (but as result the account is synced)
> 
> Ok, this sounds like another problem though with iOS. Where iOS syncs but returns an error after the process has completed Or one of the end pairing processes fail.

I will create a separate issue for this with xcode logs if they are helpful

**Comment by VolodLytvynenko** [comment]
No additional issues from my side. @Samyoul @qfrank thank you for the fixes

**Comment by pavloburykh** [comment]
hey @qfrank! If there are no additional issues, could you please merge this PR when you have a chance? We need this fix to unblock testing of https://github.com/status-im/status-mobile/pull/16916 Thank you!

**Comment by qfrank** [comment]
> hey @qfrank! If there are no additional issues, could you please merge this PR when you have a chance? We need this fix to unblock testing of #16916 Thank you!

doing it now

**Comment by qfrank** [comment]
Oh, i made a mistake... i saw @Samyoul changed file VERSION to `0.166.6`, and status-go-version.json already pointed to v0.166.6 , so i reverted status-go-version.json , but someone else taged the wrong commit as v0.166.6 @pavloburykh , i'll fix this right now

**Pull request merged**
