### PR TITLE
feature #3953 - enabled mainnet on release builds, with a warning

### LINKED ISSUE #3953: Add mainnet as a network option
### User Story

As an alpha user, I want to use Mainnet so that I can test with real ETH and use real Dapps.

As a Status developer, I want to get Mainnet feedback so that I can improve the app.

As a dapp developer, I want to test my Dapp on Mainnet so that I can verify it works.

### Description

*Type*: Feature

*Summary*: Status app is in alpha for testing, development, and feedback, but usage is limited because users are limited to Testnet and can't test real Dapps or do transactions with real ETH.  Over the last few weeks there have been only several recorded transactions but in comparison, there have been thousands of messages sent. Adding mainnet as a network option will allow testing for users acquainted with the risks and get valuable feedback.

#### Expected behavior

A user goes to Profile, taps Advanced, taps Network, then taps Mainnet. A warning message with opt-in is displayed. Confirming will switch to Mainnet.

#### Actual behavior

A user goes to Profile, taps Advanced, taps Network, but Mainnet is not an option.

### Solution

- Add Mainnet as a [non-default] option to Alpha release builds
- Show a warning message

Details:
- [Design: WIP prototype of the flow showing the steps to enable](https://invis.io/A5H52F12NBK)
- [Copy: WIP copy of the opt-in warning alert](https://docs.google.com/document/d/1UfNy8o5clvvRppGbF0aeMx2p1ce-YZsJ7PXcsfXGfqo/edit?usp=sharing)

This solution is only needed until Beta when Mainnet will be the default network.

### Additional Information

This issue is WIP until any associated security or UX concerns can be investigated.

Related issues to research:
- Encrypt realm https://github.com/status-im/status-react/issues/3798 & PR https://github.com/status-im/status-react/pull/3829 
- Mixpanel ID's https://github.com/status-im/status-react/issues/4006 & PR https://github.com/status-im/status-react/pull/4068

cc @goranjovic @adambabik

### PR DESCRIPTION
**Pull request by goranjovic**
fixes #3953 

### Summary:

Enabled mainnet on release builds as a non-default option. When users tries to switch to mainnet, they are shown a warning stating the experimental state of this option.

### Testing notes (optional):
The behavior added in this PR depends on whether or not the app is built in release or dev mode. Both need to be tested. (Will run a release build in jenkins and add the links here)

### Steps to test:
- Start a release build
- Check that network is not already set to mainnet
- Check that switching to mainnet is possible and that the warning is there

- Start a nightly build 
- Check that network is mainnet by default
- Check that switching from and to mainnet has no warnings

status: ready

### CODE REVIEW

**Comment by goranjovic** [comment]
screenshot-2018-05-07_18 06 10 347

**Review by jeluard — APPROVED** [review]

**Comment by chadyj** [comment]
Woah what a milestone!  Nice work Goran 🍻 

The copy just needs a quick tweak. It was linked as a google doc in the issue, but for clarity I'll include it below:

```
Warning!

While we highly appreciate your contribution as a tester of Status, we’d like to point out the dangers. You’re switching to Mainnet mode which is still in Alpha. This means it is still in development and has not been audited yet. Some of the risks you may be exposed to include: 
- Accounts may be unrecoverable due to breaking changes
- Loss of ETH and tokens
- Failure to send or receive messages

Switching to Mainnet should be done for testing purposes only. By tapping “I understand”, you confirm that you assume the full responsibility for all risks concerning your data and funds. 

Button: [Cancel]/ [I understand]
```

**Review by adambabik — APPROVED** [review]

**Comment by goranjovic** [comment]
Updated copy, rebuilding both versions

**Review by cammellos — APPROVED** [review]

**Comment by goranjovic** [comment]
Dev version:

Branch: PR-4138
Android: https://i.diawi.com/pBUHPA
iOS: https://i.diawi.com/R9qf4n

**Comment by goranjovic** [comment]
Dev (nightly) mode:

----------------
Branch: PR-4138
Android: https://i.diawi.com/BmFrji
iOS: https://i.diawi.com/JBhpTu

**Comment by goranjovic** [comment]
Release mode:

Branch: status-im:feature/enabled-mainnet-warning-3953
Android: https://i.diawi.com/VCYBPX
iOS: https://i.diawi.com/EQBvsH

**Comment by goranjovic** [comment]
Dev version:

Branch: PR-4138
Android: https://i.diawi.com/DLUpHj
iOS: https://i.diawi.com/uLq92V

<blockquote><div><strong><a href="https://i.diawi.com/DLUpHj">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>
<blockquote><div><strong><a href="https://i.diawi.com/uLq92V">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by goranjovic** [comment]
Release flags version:

Branch: status-im:feature/enabled-mainnet-warning-3953
Android: https://i.diawi.com/KKPufv
iOS: https://i.diawi.com/FcUR17

<blockquote><div><strong><a href="https://i.diawi.com/KKPufv">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>
<blockquote><div><strong><a href="https://i.diawi.com/FcUR17">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by lukaszfryc** [comment]
All works fine 👍

**Review by rasom — APPROVED** [review]

**Pull request merged**
