### PR TITLE
[WIP] Add pfs

### PR DESCRIPTION
**Pull request by cammellos**
[comment]: # (Please replace ... with your information. Remove < and >)
[comment]: # (To auto-close issue on merge, please insert the related issue number after # i.e fixes #566)

If you submit PR for issue with bounty then write here Fixes #NN where NN is issue number

*otherwise*

fixes #...

### Summary:

[comment]: # (Summarise the problem and how the pull request solves it)
...

### Steps to test:
- Open Status
- ...
- Step 3, etc.

status: ready

### CODE REVIEW

**Comment by ghost** [comment]
### Pull Request Checklist
- [ ] Have you updated the documentation, if impacted (e.g. [docs.status.im](https://docs.status.im/docs/build_status.html))?

**Comment by rasom** [comment]
@PombeirP @cammellos is it worth keeping this PR open?

**Comment by cammellos** [comment]
@rasom not at all, forgot it was pending, I will close it but please do not delete the  branch for now as some code it is still to be used.

**Comment by rasom** [comment]
ok @cammellos

**Pull request closed without merging**
