### PR TITLE
[ISSUE #2883] Migrate wallet/request to latest mockups

### LINKED ISSUE #2883: Update wallet receive transaction screen
User Story

As a user, I want to have access latest wallet UI changes

Description

Update wallet receive transaction screen so that it reflects mockup changes.

Type: Feature

### LINKED ISSUE #3042: Remove wallet custom error handling
### User Story

As a user, I want to have all errors surfaced the same way

### Description

*Type*: Feature

Wallet main screen currently shows errors in a specific way. We want all errors to be shown the same way. 
It might be interesting to introduce a generic error handling facility (backed by native popup for now).

### LINKED ISSUE #3220: Done button is not visible when pasting user address on iOS
*Type*: Bug

*Summary*: There is a `Done` button on the screen where user can paste wallet address manually. This button is not visible on iOS.

#### Expected behavior
I am able to paste the address and tap Done in order to apply the changes and being redirected to previous screen. So I expect the Done button to be visible once I entered user address.

image

#### Actual behavior
image

### Reproduction

- Open Status
- Tap wallet
- Tap send transaction
- Tap specify recipient
- Tap enter contact code
- Pay attention to the Done button in the footer -> button present and is graded-out
- Enter any value to recipient address textbox
- Pay attention to the footer

### Additional Information
* Status version: develop
* Operating System:  iOS

### PR DESCRIPTION
**Pull request by jeluard**
fixes #2883
fixes #3042
fixes #3220
improves #3196

### Summary:

Migrate wallet/request to latest mockups while relying on components.

### Steps to test:
- Open Status
- Navigate wallet / 
- Screen should work as previously and respect mockups

status: ready

### CODE REVIEW

**Review by goranjovic — APPROVED** [review]

**Comment by jeluard** [comment]
Branch: PR-3247
Android: https://i.diawi.com/tedFFU
iOS: https://i.diawi.com/vqmqh2

**Comment by asemiankevich** [comment]
new branch should has fixes for:
1. Cross button on Android
2. Done button on iOS

Branch: PR-3247
Android: https://i.diawi.com/swgjdt
iOS: https://i.diawi.com/gUUHxy

**Comment by asemiankevich** [comment]
Remaining to fix (however it is not critical):
1. rename and adjust footer on `New request` screen according to mocks
2. adjust the margins and whatever needed to remove the scrolling on `Request transaction` screen
3. cross button should be black on android (share my contact screen)

**Comment by asemiankevich** [comment]
Branch: PR-3247
Android: https://i.diawi.com/KDeqvR
iOS: https://i.diawi.com/w4NcV5

all above mentioned issues are fixed. 1 new found: cant send request on iOS (send button is not shown when keyboard appears)
There is a workaround to do this: tab back - then send transaction request -> tap send request.
iOS

image

Android
image

**Comment by asemiankevich** [comment]
Branch: PR-3247
Android: https://i.diawi.com/RToUVr
iOS: https://i.diawi.com/PhJYw7

**Comment by asemiankevich** [comment]
Branch: PR-3247
Android: https://i.diawi.com/RToUVr
iOS: https://i.diawi.com/PhJYw7

all issues are gone in ^ build. Done button is in place as well as Send request (iOS). No regressions.

**Pull request merged**
