### PR TITLE
Show raw payload for messages in dev mode, as an option.

### LINKED ISSUE #6125: Show original and parsed payload for chat messages in development mode
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a developer, I want to see the exact payload of rendered chat messages to be able to debug issues like messages coming out of order or wrong text or anything.

### Description
*Type*: Feature

When Development mode is enabled in Settings, show an additional flag called "show debug info in chats".

When this mode is selected, add a section to every rendered message showing JSON payload of this message, like `["~c4", ["boo!", "text/plain", ":public-chat-message", 19191991919, 000001, {"blah":"blah"}]]`.

### PR DESCRIPTION
**Pull request by mandrigin**
fixes #6125 

it looks like this, disabled by default, but can be enabled

simulator screen shot - iphone xs max - 2018-10-09 at 15 51 42

status: ready

### CODE REVIEW

**Comment by goranjovic** [comment]
@mandrigin is this something that we still can/want to merge?

**Comment by oskarth** [comment]
@mandrigin what's the state of this PR?

**Comment by mandrigin** [comment]
@oskarth @goranjovic @annadanchenko is something like (like on screenshot) that would be useful? If so, I can resurrect and wrap this thing up this week. Otherwise, I can drop it, it is a hella rebase.

**Comment by mandrigin** [comment]
Okay, since I got no answer, closing the PR.

**Comment by oskarth** [comment]
You wrote the issue and solved it, so probably best judge yourself :) seems like it can be revisited when the need is stronger.

**Pull request closed without merging**
