### PR TITLE
feat: undo delete with toast

### PR DESCRIPTION
**Pull request by yqrashawn**
this add undo toast to delete message for everyone and delete message for me

1. delete action will trigger undo toast
1. continue delete within undo time limit will update existing undo toast, `1 message deleted` -> `2 messages deleted`
1. continue delete within undo time limit will reset all undoable deletes undo time limit
1. undo when toasting `4 messages deleted` will undo 4 messages
1. swaped the dark/light theme of toast component based on this [figma design](https://www.figma.com/file/PPWkgOYlZZDxZv5SDGsZVV/Posts-%26-Attachments-for-Mobile?node-id=5713%3A624120&t=h8EZBmIX2jH49yLS-4)

https://user-images.githubusercontent.com/15090582/209910901-24f0724c-e812-49bf-967e-ae6f9ace60c7.mp4

image

status: ready

### CODE REVIEW

**Comment by flexsurfer** [comment]
hey @yqrashawn banner design looks strange, it's not implemented yet and not part of this PR ?

**Comment by yqrashawn** [comment]
> hey @yqrashawn banner design looks strange, it's not implemented yet and not part of this PR ?

You mean the toast? I think maybe we should use the dark one here. But not sure. I'll ask designer.

**Comment by yqrashawn** [comment]
@flexsurfer changed to dark toast on light theme, ready for review

**Review by flexsurfer — APPROVED** [review]

**Comment by flexsurfer** [comment]
> @flexsurfer changed to dark toast on light theme, ready for review

we should ask the designers (@pedro-et @xAlisher ) I think the color was correct, but the implementation is wrong, there is no opacity in designs 
image

**Comment by yqrashawn** [comment]
@flexsurfer Thanks for your comment. I checked again. There's defiantly opacity, seems what's missing is the blur effect and the shadow, I'll create an [issue](https://github.com/status-im/status-mobile/issues/14702#issue-1518552482) for that.

CleanShot 2023-01-04 at 16 31 28@2x

**Comment by pavloburykh** [comment]
@yqrashawn Thanx for the PR. Please take a look at the following issues

### ISSUE 1 User is redirected to broken Jump to screen after he deletes message and re-enters the chat

**NOTE:** This bug is better to reproduce on IOS. I have managed to reproduce it  on Android, but following below steps will guarantee reproduction only on IOS. 

**Steps:** 

1. Open any chat
2. Send a message
3. Delete message (for me or for everyone)
4. Tap back button to close chat
5. Re enter the chat (on this step you might notice that Jump to screen is opened before redirection to chat, see video below)
6. Tap back button once again to close the chat and go back to Messages screen
7. Observe the result

**Actual result:** instead of Messages screen user is redirected to the Jump to screen with non working elements. Tapping on jump to button results in it's disappearing. Trying to jump to the open chat screen has no response. UI stucks, app needs to be relaunched. 

**Expected result:** user is redirected to Messages screen, not Jump to


https://user-images.githubusercontent.com/97245802/210589096-4a60098a-37b9-4fb4-bde8-a52be127b7c5.mp4

[geth.log](https://github.com/status-im/status-mobile/files/10345321/geth.log)
[Status.log](https://github.com/status-im/status-mobile/files/10345322/Status.log)

**Comment by pavloburykh** [comment]
### ISSUE 2 After message deletion for a moment it is still displayed overlapped by already appeared system message about deletion. Delivery status of deleted messages disappear only after chat re-opening 

Bug is reproducible both on IOS and Android but in my case it is easier to reproduce on IOS. 

**Steps:** 

  1. Open any chat
  2. Send couple of messages
  3. Start deleting messages one after another
  4. Pay attention at the UI of deleted messages

**Actual result:** After message deletion for a moment it is still displayed overlapped by already appeared system message about deletion. Also, statuses of messages (sent/delivered) keep remain to be shown for deleted messages and disappear only after chat re-entering. 

**Expected result:** system message about message deletion should appear after message already disappeared. 

photo_2023-01-04 17 42 17

**Comment by pavloburykh** [comment]
### ISSUE 3 Accessibility ids are missing 

Following elements miss accessibility ids which are required for development of e2e tests

1. Undo toast
2. Undo button within the toast
3. Element inside the toast that contains dynamic text "1..2..3... messages deleted for you/everyone"

Appium 2023-01-04 18-00-45

**Comment by pavloburykh** [comment]
### ISSUE 4 It is possible to pin already pinned message if it's deletion has been undone before

**Steps:**

1. Open any chat
2. Send a message
3. Pin that message
4. Select delete option for pinned message and undo deletion
5. Re enter the chat
6. Open list of pinned messages by tapping on pinned banner
7. Longtap on pinned message
8. See if unpin option is displayed for that message

**Actual result:** pin instead of unpin option is shown. It is possible perform pin action for already pinned message

**Expected result:** unpin option is displayed


https://user-images.githubusercontent.com/97245802/210599937-1b159ae1-d240-4f48-9010-0a845e5e1c2d.mp4

**Comment by pavloburykh** [comment]
### ISSUE 5 Deleted image is partially shown until chat re-opening

I guess it might be the same problem as described in [ISSUE 2](https://github.com/status-im/status-mobile/pull/14618#issuecomment-1371092929) 

**Steps:**

1. Open chat
2. Send an image
3. Delete the image
4. See if image is deleted 

**Actual result:** image is partially displayed until chat re-opening

**Expected result:** image is deleted and system message about image deletion is displayed


https://user-images.githubusercontent.com/97245802/210724431-fe783796-7a54-4e9b-83d6-3af1e03f1b04.mp4

**Comment by yqrashawn** [comment]
Thanks for your review @pavloburykh  
Progress update:
- can reproduce all the issues
- ISSUE 1 is caused by toast, still working on fix this one

**Comment by yqrashawn** [comment]
Issue 2, 3, 5 is fixed
Issue 4 is not caused by delete message (can reproduce with pin, leave, re-enter chat)
Still stuck on issue 1

**Comment by pavloburykh** [comment]
> 

thank you for the update @yqrashawn Ping me please when issue 1 fix will be ready. Take your time!

**Comment by pavloburykh** [comment]
I've logged a separate [issue](https://github.com/status-im/status-mobile/issues/14729) for ISSUE 4. Thanks for clearing out!

**Comment by yqrashawn** [comment]
@pavloburykh Issue 1 is fixed. It's caused by not enabling reanimated layout animation beforehand manually. Thanks to @Parveshdhull help figure out the issue.

**Note**: layout animation is not enabled by default because it caused issue before (screen flicker) related issue https://github.com/status-im/status-mobile/issues/13452#issuecomment-1159800179

**Comment by VolodLytvynenko** [comment]
> @pavloburykh Issue 1 is fixed. It's caused by not enabling reanimated layout animation beforehand manually. Thanks to @Parveshdhull help figure out the issue.
> 
> **Note**: layout animation is not enabled by default because it caused issue before (screen flicker) related issue [#13452 (comment)](https://github.com/status-im/status-mobile/issues/13452#issuecomment-1159800179)

@yqrashawn thank you for the update. I will check all fixes and provide you feedback soon

**Comment by VolodLytvynenko** [comment]
Hi @yqrashawn . The PR is tested and ready to be merged. Thank you for a great job!

**Pull request merged**
