### PR TITLE
[Fixes #4944] Enable universal/deep links

### LINKED ISSUE #4944: Add universal/deep links
As a user, 
I want to send a link to a public channel 
so I can invite others to join a discussion. 

Eg clicking https://status.im/chats/public/status opens the Status app then joins the #status public channel 

As a user, 
I want to send a link to my profile 
so that others can easily add me as a contact. 

Eg clicking https://status.im/profiles/0x234567890876 opens the Status app, then opens the profile of this user so they can be added to contacts or a 1-1 chat can be started 

#### Chats
When a user clicks on a link in the format:

`https://status.im/chats/public/name-of-the-chat`

* If the user has status installed, it should open up that public chat ( or create and open if necessary).

* If the user has not status installed, it should redirect to the relevant app store.

#### Profile

When a user clicks on  a link in the format:

`https://status.im/profiles/user-public-key`

* If the user has status installed, it should open up that contact profile page

* If the user has not status installed, it should redirect to the relevant app store.

### Solution

Other use cases that we might want to implement in the future and might be helpful to take into consideration when coming up with a solution:

* Link to one-to-one chats `https://status-im/chats/one-to-one/pk`
* Link to a specific message in a chat `https://status.im/chats/public/chat-id/messages/message-id`

Unicode characters should not be allowed when handling urls for now until (add issue link here) is fixed

This should work on both ios & android.

This will ideally pave the way for https://github.com/status-im/status-react/issues/3488 to be implemented.

Some preliminary investigation was done on https://github.com/status-im/status-react/issues/1592 , but a generic solution is not required as long as it fulfills the main use cases.

### PR DESCRIPTION
**Pull request by cammellos**
### Summary:

Enables universal links in the app, adds to changelog

### Testing notes (optional):
There are 3 kinds of paths  supported:
`/chat/public/abc` -> will open/create the public chat
`/user/profile-id`   -> will open the profile of the user
`/browse/www.cryptokitties.co` -> will ask you to open in dapp browser or cancel

The format of the link is either:
`https://get.status.im/....`
or
`status-im://...`

If the app is not installed:

1) Clicking on `https://get.status.im/...` will redirect you to the website, and you should see a link to the play store for android, or https://status.im/success for ios.
2) Clicking on `status-im://..` if the app is not installed will probably not do anything useful :)

If the app is installed, clicking on any of those links should:
1) If status is closed should open it and execute the corresponding action
2) If status is in the background it should bring it to the foreground and execute the corresponding action
3) If clicked inside status it should execute the corresponding action

In any cases of the above, if the user is logged out, it will act after the user has logged in.

status: ready 

<blockquote><div><strong><a href="https://status.im/success">Status, a Mobile Ethereum OS</a></strong></div><div>Status is an interface to access Ethereum, built for Android & iOS. Enjoy encrypted messaging, a cryptocurrency wallet, and seamless access to DApps.</div></blockquote>

### CODE REVIEW

**Review by janherich — APPROVED** [review]

**Comment by chadyj** [comment]
I've tested on both Android and iOS and it works beautifully!
I did find this https://github.com/status-im/status-react/issues/4944#issuecomment-402115986 but DApp team can handle if they decide its an issue.

When testing an earlier build I also came across an issue where the links stopped being registered on iOS, but it seems to be an OS issue that happened during my testing. The fix was step 1 [here](https://blog.branch.io/3-steps-to-troubleshoot-ios-9-and-ios-10-universal-links/).

For some other thoughts:

- Design team is improving the get.status.im site
- There are several improvements we can make in the app to make it easier to invite friends, share links, etc but we can do that after this is merged
- There is a wiki page up at https://wiki.status.im/Universal_Links
- This will also come to [desktop](https://github.com/status-im/status-react/issues/5038) 
- Some weird stuff about[ universal links](https://medium.com/mobile-growth/the-things-i-hate-and-you-should-know-about-apple-universal-links-5beb15f88a29)



<blockquote><div><strong><a href="https://wiki.status.im/Universal_Links">Universal Links - Status Wiki</a></strong></div></blockquote>

**Comment by chadyj** [comment]
@cammellos Had this question come up: How do we link to unicode channel names?
Eg https://get.status.im/chat/public/status%20español doesn't seem to work
or I tried encoding the URL https://get.status.im/chat/public/status+%e6%97%a5%e6%9c%ac%e8%aa%9e and that didn't work either, although the web app displayed the unicode OK.

<blockquote><div><strong><a href="https://get.status.im/chat/public/status+%e6%97%a5%e6%9c%ac%e8%aa%9e">Join the public chat: #status+日本語 in Status</a></strong></div></blockquote>

**Comment by cammellos** [comment]
@chadyj until we handle the security issue with unicode urls it's probably best to disable them, as we would allow otherwise users to create chats with unicode. Once that's fixed we can re-enable it. We can't prevent the user to create links with unicode characters, but we can just noop on them, even though that's not a great UX.

**Comment by chadyj** [comment]
Another issue: The browse page shows an error when sharing a URL with a path.

Eg Both of these show an error on get.status.im:

https://get.status.im/browse/www.cryptokitties.co/marketplace
https://get.status.im/browse/ipfs.infura.io/ipfs/QmboUYi1eZryDwFMpLWaeo4gAQVNzSiqLtPB595g5xVbdr/

```
404

NotFoundError: Not Found
    at /srv/app.js:25:8
    at Layer.handle [as handle_request] (/srv/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/srv/node_modules/express/lib/router/index.js:317:13)
    at /srv/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/srv/node_modules/express/lib/router/index.js:335:12)
    at next (/srv/node_modules/express/lib/router/index.js:275:10)
    at /srv/node_modules/express/lib/router/index.js:635:15
    at next (/srv/node_modules/express/lib/router/index.js:260:14)
    at Function.handle (/srv/node_modules/express/lib/router/index.js:174:3)
    at router (/srv/node_modules/express/lib/router/index.js:47:12)
```

<blockquote></blockquote>
<blockquote></blockquote>

**Comment by cammellos** [comment]
@chadyj You should be able to access it now

**Comment by chadyj** [comment]
> @chadyj You should be able to access it now

@cammellos  Fixed! 🍻

**Review by dmitryn — APPROVED** [review]

**Comment by yevh-berdnyk** [comment]
Please ignore tests failed with `Password in logcat!!!`, it's false failure and will be fixed soon

**Comment by lukaszfryc** [comment]
My test results:

1. When https://get.status.im/user/0x044166fa04e967e333211ae0cc1087c9c74exxx is opened, the back button does not work and user can’t leave the profile view
2. If app is not installed, https://get.status.im shows „Open in Status” link that leads to status-im://chat/public/blah. When clicked, „Safari cannot open the page because address is invalid” error appears. Maybe by changing the link from status-im:// to get.status.im we could get rid of this error. Ideally, we should detect if Status is installed (maybe not possible) and not show this button but instead „Download Status”
3. When https://get.status.im/browse/www.cryptokitties.co is opened, options menu appear with only one option - „Open in browser”. I suggest to get rid of the option menu and open the url in Status browser immediately
4. When app was killed, tapping on https://get.status.im/chat/public/blah opens the app, but when I log in the „blah” is not opened

I used this gist as a reference https://goo.gl/TJzRyA
  
I think we should fix 1) before merging this PR. For 2), 3), 4) we can create a separate issues. @cammellos wdyt?

Also, right after PR is merged we should update https://wiki.status.im/Universal_Links:
a) Remove "Note: Universal links are WIP and do not work in release builds."
b) Add https://get.status.im/user/0x044166fa04e967e333211ae0cc1087c9c74exxx to supported links

<blockquote><div><strong><a href="https://get.status.im/user/0x044166fa04e967e333211ae0cc1087c9c74exxx">View user 0x044166fa04e967e333211ae0cc1087c9c74exxx's profile in Status</a></strong></div></blockquote>
<blockquote><div><strong><a href="https://get.status.im/">Status, a Mobile Ethereum OS</a></strong></div><div>Status is an interface to access Ethereum, built for Android & iOS. Enjoy encrypted messaging, a cryptocurrency wallet, and seamless access to DApps.</div></blockquote>
<blockquote><div><strong><a href="https://get.status.im/browse/www.cryptokitties.co">Browse to www.cryptokitties.co in Status</a></strong></div></blockquote>
<blockquote><div><strong><a href="https://get.status.im/chat/public/blah">Join the public chat: #blah in Status</a></strong></div></blockquote>
<blockquote><div> Gist</div><div><strong><a href="https://gist.github.com/lukaszfryc/c12ccdcf67ee1bbc554dffe0879ffba1">deep_links.md</a></strong></div><div>GitHub is where people build software. More than 28 million people use GitHub to discover, fork, and contribute to over 85 million projects.</div></blockquote>
<blockquote><div><strong><a href="https://wiki.status.im/Universal_Links">Universal Links - Status Wiki</a></strong></div></blockquote>
<blockquote><div><strong><a href="https://get.status.im/user/0x044166fa04e967e333211ae0cc1087c9c74exxx">View user 0x044166fa04e967e333211ae0cc1087c9c74exxx's profile in Status</a></strong></div></blockquote>

**Comment by cammellos** [comment]
thanks ,

1 definitely needs fixing, 2 i will have a look at it,  i thought the link
would take you to the store, maybe something has changed. 3 i had a chat
with the dapps team and for security reason we decided to show the pop up
with only one entry. 4 should not happen, could you please give me some
repro steps? i will fix it in the scope of this pr.

 thanks!

**Comment by chadyj** [comment]
Good catch on 1. Should be fixed.

2 is expected. There is the same behavior in other apps.

3 was discussed with the Dapp team and they recommending showing the message for security/awareness reasons

For 4, it seems to work with dapps, but not the other 2 links

**Comment by lukaszfryc** [comment]
@cammellos 

> 4 should not happen, could you please give me some
repro steps

1. Install the app, log in
2. Kill the app
3. Click on https://get.status.im/chat/public/blah link. You can open this PR url in Chrome and click the link
4. When the app open, log in
5. Now the #blah public chat should open but it's not

It's not a big deal. We can still fix it in a separate GHI I think. Thanks!

**Comment by cammellos** [comment]
@lukaszfryc 1 & 4 have been addressed, thanks!

**Comment by lukaszfryc** [comment]
@cammellos works great. The PR is ready to be merged 👍

**Pull request merged**
