### PR TITLE
move quo preview

### PR DESCRIPTION
**Pull request by flexsurfer**
move quo preview
rollback (.ignoreAllLogs LogBox)
small fixes

### CODE REVIEW

**Review by jo-mut — APPROVED** [review]

**Comment by OmarBasem** [comment]
@flexsurfer why rollback `(.ignoreAllLogs LogBox)` ?

**Comment by flexsurfer** [comment]
hey @OmarBasem yeah, good question, first of all as i was saying it's annoying during development and hotreload, lots of warnings which are related only to development process, so at some point you just start ignoring them all and just closing, i guess @ilmotta agree with me, if you want we can still look how we could improve it if we want to enable them

**Comment by OmarBasem** [comment]
Hmm weird.. I am not getting a single warning tho.. nvm it's fine

**Comment by ilmotta** [comment]
> hey @OmarBasem yeah, good question, first of all as i was saying it's annoying during development and hotreload, lots of warnings which are related only to development process, so at some point you just start ignoring them all and just closing, i guess @ilmotta agree with me, if you want we can still look how we could improve it if we want to enable them

Yeah, just as @flexsurfer said, I'm getting constant warnings during development, so I found myself having to close the log box to interact with the app all the time. @OmarBasem, based on what we've seen so far, it seems these warnings vary between environment (OS, etc) :shrug:

**Pull request merged**
