### PR TITLE
Fix community offline updates

### LINKED ISSUE #17950: Message updates (deletion/editing) are not delivered when have been done from offline (communities only)
# Bug Report

## Problem 
If a  message was deleted/edited when a user was offline or the connection was lost, the updates are not received by other users when the sender comes back online.
Reproduced for both clients (desktop/mobile) and only for communities. 

#### Expected behavior
Can see updated messages

#### Actual behavior
The message stays the same (re-login doesn't affect, chacked after an hour - no updates) 

Status Desktop 2023-11-20 14-26-50

### Reproduction
1. Sender: send message 
2. Sender: go to offline
3. Sender: edit initial message
4. Sender: go online
5. Reciever: wait for the message to be updated

### Additional Information

- Status version: release 1.26. 
- Operating System: all

Sender logs (IOS) :  [logs (65).zip](https://github.com/status-im/status-mobile/files/13415310/logs.65.zip)

Receiver logs (IOS): [geth copy.log](https://github.com/status-im/status-mobile/files/13415316/geth.copy.log)

### PR DESCRIPTION
**Pull request by vitvly**
Fixes #17950

Relies on https://github.com/status-im/status-go/pull/4365

Tested between mobile device and desktop.

### CODE REVIEW

**Comment by vitvly** [comment]
@churik addressed review comments in status-go PR, updated this one to point to latest version.

**Comment by vitvly** [comment]
@churik rebased to develop

**Comment by pavloburykh** [comment]
@vitvly thank you! The initial issue reported by Tetiana seems to be fixed. 

Below I will describe some issues which I have faced during my testing session. I believe those issues are not related to this PR but I would like to point them out here. 

Here are the logs of IOS and Android builds used in current session

[Android_logs_delivery_session.zip](https://github.com/status-im/status-mobile/files/13490227/Android_logs_delivery_session.zip)
[IOS_logs_delivery session.zip](https://github.com/status-im/status-mobile/files/13490228/IOS_logs_delivery.session.zip)

**Issue 1. Part of messages are not delivered to Receiver who was offline during messages were sent by Sender.** 

Initially reported [here](https://github.com/status-im/status-mobile/issues/16873#issuecomment-1819346648) and not fixed in updated go branch. 

On the video below IOS is Sender, Android is Receiver. 

https://github.com/status-im/status-mobile/assets/97245802/0eea5605-a97d-4cea-ac41-8f52ca2d62da

Screenshot with comparison Sender's and Receiver's history taken 20 minutes after sending messages. As can be observed, 3 of 10  messages has not been delivered

photo_2023-11-28 17 28 50 jpeg 2023-11-28 17-29-22

Another screenshot with comparison of another stack of messages. Taken after 1.5 hour after sending. Only 3 of 9 messages have been delivered to Receiver. 

photo_2023-11-28 17 35 17 jpeg 2023-11-28 17-35-49


**Issue 2. Messages stuck in sending status for a long time despite the message can be already sent in fact**

It can be observed in Video from the above Issue 1. 

**Issue 3. Sometimes messages are not delivered even when both Sender and Receiver are online**

https://github.com/status-im/status-mobile/assets/97245802/549e535f-4c66-4a8e-92ec-5f964b07facc


**Issue 4. Crash on logout** 

I have faced crash on logout. Reproduced once on IOS and once on Android. Below video is from Android. 

https://github.com/status-im/status-mobile/assets/97245802/a4f8d6b0-0ba5-4848-bcc9-51f4fe36cb75

**Comment by pavloburykh** [comment]
@vitvly I have reported issues 1-4 separately here https://github.com/status-im/status-mobile/issues/18022

Meanwhile I have encountered another issue. And am not aware if it is PR related or something caused by go develop. 


### ISSUE 5 Cannot mark as read messages in communities

**Steps:** 

1. Generate unread messages in community for User A
2. By User A open communities tab
3. Longtap on community => Mark as read
4. See if unread badges disappeared in community and its channels for User A

**Actual result:**  messages remain unread, badges do not disappear. 

**Expected result:** messages should be read, unread badges should disappear from community and channels. 

[Status-debug-logs (85).zip](https://github.com/status-im/status-mobile/files/13500379/Status-debug-logs.85.zip)

https://github.com/status-im/status-mobile/assets/97245802/b6c5f842-ce9d-46de-80bf-b5c326631bbe

**Comment by pavloburykh** [comment]
@vitvly I have also logged ISSEU 5 separately https://github.com/status-im/status-mobile/issues/18023 as it is not related to your PR changes. So you are good to merge the go part. Thank you!

**Comment by churik** [comment]
@pavloburykh I suppose we can merge the PR and cherry-pick changes to release branch?

**Comment by vitvly** [comment]
@pavloburykh @churik added a pr with cherry-pick https://github.com/status-im/status-go/pull/4410

**Pull request closed without merging**
