### PR TITLE
Experiment/whisper many topics

### LINKED ISSUE #55: Lightning fast messaging and cold phone
## Preamble

    Idea: <to be assigned>
    Title: Lightning fast messaging and cold phone
    Status: In progress
    Created: 2017-12-01
    Started: 2017-12-11 (estimated)

## Summary

Make the app usable from a performance point of view for all the supported user flows for product MVP.

## Vision

Use basic hypothesis testing to solve the following qualitative user statement:

> "I don't want to use the app; it is slow and buggy […] My phone gets hot, it uses up too much battery, and interface is laggy"

As well as focusing on critical path, making assumption explicit, operating under assumptions/uncertainty and doing minimal and tooling work necessary to solve the user story.

## Swarm Participants
- Lead Contributor: @oskarth (10h/w)
- Testing & Evaluation: @annadanchenko (10h/w)
- Testing & Evaluation: @Serhy (10h/w)
- Go Contributor: @b00ris (40h/w)
- Go Contributor: @JekaMas (40h/w)
- Go Contributor: @divan (10h/w)
- Clojure Contributor: @rasom (30h/w)
- Clojure Contributor: @dmitryn (30h/w)
- Clojure Contributor: @janherich (30h/w)
- Clojure Contributor: @yenda (20h/w)

Swarm size: 10 people.

## Requirements

Loosely: Understanding of supported user stories and devices. No additional requirements in this idea outside of what has been or will be specified as part of everyday work. Creating additional tooling is not part of this swarm's work.

## Goals & Implementation Plan

(a) Get a global overview of this problem
(b) Use rigor and hypothesis testing to pursue the most fruitful directions
(c) Work as close to the root of the assumption tree as possible while still having leverage

See https://docs.google.com/document/d/1OZtzfojToJtZhj2LnokA9-YU7aL_gm9NzaGtI-vuZ6E/edit# for original doc.

General heuristics:

1) Minimal scope in all dimensions to simplify the problem.
- Supported devices: iPhone 6 and Samsung Galaxy Note 4 (fallback Galaxy S6).
- Supported network: RPC only.
- Supported user stories: minimal as defined by MVP (e.g. public/group chat optionally cut).

2) Focus on iteration speed.
Testing hypotheses quickly. If it takes 1 month to test hypothesis then we can only do 2-3 in 3 months, and we don’t learn a lot. But if we can do 2 a week we can do 20+ and our knowledge will be correspondingly higher.

### Minimum Viable Product

Goal Date: 2017-12-29
Completed: 2018-01-10 (partial completion)

Description:

1) Identify and agree on user stories / behaviors which causes unacceptable
performance on supported devices and are part of Status Core MVP supported
flows.

Example: As a user on iPhone 7 I want to be able to sign up in <30s without
feeling like my phone gets hot.

2) Reproduce these behaviors and collect metrics that are currently available to
us; identify needs for plausible but currently opaque metrics.

Example: Figure out how to get disk IO statistics over time on Android.

3) Based on information in (2), outline hypotheses, with clear assumptions, as
well the quickest way to test these hypotheses.

Example: Assuming phone gets hot due to high CPU usage, Whisper decryption is
causing high CPU usage. Quickest way to test: disable Whisper and simulate user
story without it.

### Iteration 1

Goal Date:  2018-01-18
Description: 

Deliverable 1: Test hypotheses:
- [Perf] Test hypothesis: RN Bridge render bottleneck https://github.com/status-im/status-react/issues/2963 (Roman)
- [Perf] Test hypothesis: Many Whisper topics increase performance https://github.com/status-im/status-react/issues/2964 (Eric, Eugene, Boris)
- [Perf] Test hypothesis: Whisper network overhead https://github.com/status-im/status-react/issues/2965 
	- Risk
	- Partial status-go test baseline test (Eugene)
- TBD Test hypothesis related to event/UI parallelized: (Dmitry)

Deliverable 2: User stories that are unacceptable right now for supported devices (Anna, Chad?)

Deliverable 3: Come up with new hypotheses based on what we learn in 1.

### Iteration 2...N

Goal Date: TBD

Once we have all the tools for benchmarking in place and most bottlenecks are fixed, we need to ensure we have documents how to avoid having performance regressions in future as well as automated performance tests developed under #22.

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

### PR DESCRIPTION
**Pull request by oskarth**
Addresses https://github.com/status-im/status-react/issues/2920

Experiment to use many topics as opposed to one in order to fix https://github.com/status-im/ideas/issues/55#issuecomment-355511183

Due to perf we don't want a single topic for all messages, instead we want many. We need a way for user A and B to agree on which topics to use. By using first 10 characters of the pub-key, we construct a topic that requires no coordination for 1-1 chats.

## Review notes
Just a spike, doesn't fix all whisper mesasge filters like ack/send seen etc. Flag off by default too. More feedback on general idea, and then more importantly to verify CPU check.

Also @JekaMas @b00ris would be great with a custom `status-go-gCOMMIT` build we can include and check logs for open envelopes on this, since we have overlapping filters etc in real-world scenario.

## Testing notes

- Ensure 1on1 chat still works with flag _OFF_

(- Ensure 1on1 chat works with this build _and another of the same build_ (Oskar: checked this, but confirm))
(LATER: In other PRs - Compare general (CPU) perf vs nightly, say. Or flag on vs flag off.)

status: ready

### CODE REVIEW

**Comment by oskarth** [comment]
Confirmed 1on1 messaging still works assuming both clients are using this build with flag on.

**Comment by dmitryn** [comment]
@oskarth does `send-seen!` also require using new topic? Now it uses default from `message-defaults`

**Comment by oskarth** [comment]
@dmitryn Most likely, I just wanted to spike the minimal path to see if we could do some perf checking. But maybe it is worth it to fix that one as well (as opposed to all the stuff here https://wiki.status.im/Whisper_Messaging)

**Comment by janherich** [comment]
@dmitryn @oskarth `send-seen!` doesn't work at all currently in develop. Regarding message statuses, it's important that `:delivered` works, which is implemented by message of type `:ack`.
Its:
`:sending` -> `:sent` -> `:delivered` -> `:seen`
Last transition doesn't work currently, `:sending` is just a default placeholder, `:sent` is set by callback on sender device when pending-message is processed and I'm not really sure about the `:ack`/`:delivered` mechanism.

**Review by flexsurfer — APPROVED** [review]

**Review by yenda — APPROVED** [review]

**Comment by oskarth** [comment]
@yenda needs this for perf work, and perf work on critical path, so moving this to high priority.

**Comment by oskarth** [comment]
Evolution of this issue: https://github.com/status-im/status-react/issues/2964

This issue can be closed once associated PR is merged.

**Comment by Serhy** [comment]
@oskarth could you update this PR with develop, please?

**Comment by yenda** [comment]
@Serhy done

**Comment by oskarth** [comment]
@yenda Oh, thanks!

**Comment by Serhy** [comment]
@oskarth Regression testing (including 1-1chat and group chat) been performed on Android 7.0 (Samsung J7 real device) and iPhoneX against the app version: 3cdb05e5+ (for Android) and 0.0.2153 (for iOS).
No issues was seen.

**Pull request merged**
