### PR TITLE
#4128 upgrade instabug to 2.10.0

### LINKED ISSUE #4128: Upgrade Instabug to 2.12.0
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a developer and tester, I want to see [crash reports](https://instabug.com/crash-reporting) so that I can debug crashes.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Improvement

*Summary*: Instabug v2.12.0 now has [crash reporting](https://instabug.com/crash-reporting) which can be useful for debugging

#### Expected behavior

Instabug version is 2.12.0

#### Actual behavior

Instabug version is older

### PR DESCRIPTION
**Pull request by debragail**
Changed version to 2.10.0 in package json

Fixes #4128 

[comment]: # (Please replace ... with your information. Remove < and >)
[comment]: # (To auto-close issue on merge, please insert the related issue number after # i.e fixes #566)

If you submit PR for issue with bounty then write here Fixes #NN where NN is issue number

*otherwise*

fixes #...

### Summary:

[comment]: # (Summarise the problem and how the pull request solves it)
...

### Steps to test:
- Open Status
- ...
- Step 3, etc.

status: ready

### CODE REVIEW

**Review by rasom — APPROVED** [review]

**Review by dmitryn — CHANGES_REQUESTED** [review]
It should be 2.11.0
Check https://github.com/Instabug/instabug-reactnative for latest version available

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/kE4EvM for branch PR-4160

<blockquote><div><strong><a href="https://i.diawi.com/kE4EvM">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/xTs8Df for branch PR-4160

<blockquote><div><strong><a href="https://i.diawi.com/xTs8Df">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/3tEQjA for branch PR-4160

<blockquote><div><strong><a href="https://i.diawi.com/3tEQjA">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/eLdanj for branch PR-4160

<blockquote><div><strong><a href="https://i.diawi.com/eLdanj">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/kATAmC for branch PR-4160

<blockquote><div><strong><a href="https://i.diawi.com/kATAmC">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by chadyj** [comment]
Hey @debragail I'd love to see this in our next release. Is there any way I can help you get it merged?

**Comment by chadyj** [comment]
Instabug is at 2.11.1 now. 
@debragail great if you can bump to that, thanks!

**Comment by debragail** [comment]
@chadyj totally ... i don't know why @rasom is on this PR tho i might just create another one because of that

**Comment by debragail** [comment]
@chadyj updated to 2.11.1

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/zorVPv for branch PR-4160

<blockquote><div><strong><a href="https://i.diawi.com/zorVPv">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/1EPPrC for branch PR-4160

<blockquote><div><strong><a href="https://i.diawi.com/1EPPrC">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/vsuCqz for branch PR-4160

<blockquote><div><strong><a href="https://i.diawi.com/vsuCqz">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/iEHjNL for branch PR-4160

<blockquote><div><strong><a href="https://i.diawi.com/iEHjNL">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/UbyH8c for branch PR-4160

<blockquote><div><strong><a href="https://i.diawi.com/UbyH8c">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/624SMg for branch PR-4160

<blockquote><div><strong><a href="https://i.diawi.com/624SMg">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/oCGCbz for branch PR-4160

<blockquote><div><strong><a href="https://i.diawi.com/oCGCbz">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/CQpokY for branch PR-4160

<blockquote><div><strong><a href="https://i.diawi.com/CQpokY">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/v6cGkw for branch PR-4160

<blockquote><div><strong><a href="https://i.diawi.com/v6cGkw">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/EGhMWY for branch PR-4160

<blockquote><div><strong><a href="https://i.diawi.com/EGhMWY">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by jeluard** [comment]
@dmitryn Can you update your review?

**Review by dmitryn — APPROVED** [review]

**Comment by pedropombeiro** [comment]
Hey @debragail could you please resolve the merge conflicts (you're free to use the `origin/bug/#4128-update-instabug` branch where I already did that)?

**Comment by asemiankevich** [comment]
i tried to reproduce https://github.com/status-im/status-react/issues/4103 and i managed, however it did not show up as crash report in instabug @debragail @chadyj

**Comment by pedropombeiro** [comment]
Also reproduced https://github.com/status-im/status-react/issues/4205 after a rebase and no report was seen in Instabug.

**Comment by chadyj** [comment]
I emailed Instabug support.

@Korazy any ideas?

**Comment by chadyj** [comment]
Reply from Instabug:

> So the issue here seems to be that you have another crash reporting tool installed. More than one crash reporting tool on the same application usually causes unexpected behavior such as a crash not being caught which is the reason the crash might not be sent to the dashboard. 

Test team, any ideas? Maybe have Instabug for release? Testfairy for dev?

**Comment by asemiankevich** [comment]
@chadyj well i do not... Nothing except Status on my phone

**Comment by debragail** [comment]
Try deleting it from the package-lock and having it recreate package-lock on build to pull the instabug version from package.json.  Thats all I can think of to try to "refresh" instabug to the new version in your build.  Maybe we should roll back to the not so new new version I was asked to change it to?

**Comment by debragail** [comment]
the package-lock.json has an "integrity" value.  
screen shot 2018-05-23 at 00 02 28

https://w3c.github.io/webappsec-subresource-integrity/

See if you have better luck after deleting package-lock.json and creating it on a new build.
 

<blockquote><div><strong><a href="https://w3c.github.io/webappsec-subresource-integrity/">Subresource Integrity</a></strong></div></blockquote>

**Comment by pedropombeiro** [comment]
What the guys from Instabug seem to be referring to is not related to other apps on the phone, but actually something in the react code which might already be subscribing to unhandled exceptions and therefore preventing Instabug to be the one handling them. I can only think of TestFairy. @dmitryn do you have any insight on what might be happening?

**Comment by dmitryn** [comment]
@PombeirP we have global exception handler registered here https://github.com/status-im/status-react/blob/develop/src/status_im/utils/error_handler.cljs#L52 which might prevent instabug handler from catching JS exceptions.

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/status-im/status-react">status-im/status-react</a></strong></div><div>status-react - a free (libre) open source, mobile OS for Ethereum</div></blockquote>

**Comment by dmitryn** [comment]
I think we could manually report exception from there by calling `Instabug.reportJSException(error);` https://docs.instabug.com/docs/react-native-crash-reporting#section-report-exception

<blockquote><div><strong><a href="https://docs.instabug.com/docs/react-native-crash-reporting#section-report-exception">Crash Reporting</a></strong></div><div> In this page, you will find some APIs specific for the crash reporting. In the [**Reports Data** ](react-native-reports-data) section, you can find more information about the information and data sent with each crash report.   If your [**plan**](https://instabug.com/pricing) has crash reporting, cr...</div></blockquote>

**Comment by pedropombeiro** [comment]
+1 Yeah, that's what I was thinking

**Comment by dmitryn** [comment]
@debragail please add manual exception reporting

**Comment by rasom** [comment]
closed because of https://github.com/status-im/status-react/pull/4649

**Pull request closed without merging**
