### PR TITLE
Add remove-chat button next to chat title

### PR DESCRIPTION
**Pull request by vitvly**
This replaces https://github.com/status-im/status-react/pull/4636 due to Jenkins being unable to build a rebased branch

### CODE REVIEW

**Review by maxhora — APPROVED** [review]

**Comment by vitvly** [comment]
Fixed #3 (User photos are mixed in chat header)

**Comment by churik** [comment]
Continue https://github.com/status-im/status-react/pull/4636#issuecomment-405600898:

- [x] 1) "Add to contacts" button doesn't work
- [x] 2) The app is unusable after deleting chat or clearing history
- [x] 3) User photos are mixed in chat header
- [x] 4) During chat switching, I still face with behavior that username is cut( [video]
- [x]  5) after deleting chat, switching to profile and coming back to "Home" - Unknown chat is shown

*Steps:*
 - Sign Up
 - Join public chat
 - Delete chat
 - Go to Profile
- Go to Home
*Expected result:* Status.im page is shown, when no chat is selected
*Actual result:* 
upl

Video is [here](http://take.ms/r9r0f)
this issue also can be reproducible when switching between Home and Profile, when user doesn't have chats.

**Review by vkjr — APPROVED** [review]

**Comment by vitvly** [comment]
Fixed #5 - after deleting chat home screen is shown after navigating to `Profile` and back.

**Comment by churik** [comment]
Tested: 
- 5 issues are fixed
- account is created;
- add new contact;
- join public chat;
- 1-1 chat, public chat - deleting chat, clearing history;
- relogin after deleting chat, clearing history;

**Pull request merged**
