### PR TITLE
Top bar UI (design review)

### LINKED ISSUE #16782: Wrong UI on the top bar (design review)
- [x] Add more space between 'back' button and user avatar picture  (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3614:306079&mode=design#507797774))
- [x] Change the font for online/offline status mark (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3614:306079&mode=design#507795612))
- [x] Add "offline" status when a user is offline (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3614:306079&mode=design#507812461))

### Additional Information
Status version: nightly
Operating System: Android, iOS

### PR DESCRIPTION
**Pull request by alwx**
fixes #16782 

- Adds more space between 'back' button and user avatar picture (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3614:306079&mode=design#507797774))
- Changes the font for online/offline status mark (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3614:306079&mode=design#507795612))
- Adds "offline" status when a user is offline

#### Platforms

- Android
- iOS

##### Functional

- 1-1 chats
- public chats
- group chats

status: ready

### CODE REVIEW

**Review by flexsurfer — APPROVED** [review]

**Comment by qoqobolo** [comment]
Hey @alwx, thanks for the fixes!

### ISSUE 1: `Offline` mark in channels and group chats

We should only display it for 1-1 chats
 
Screenshot 2023-08-01 at 15 06 40
Screenshot 2023-08-01 at 15 06 53

**Comment by alwx** [comment]
@qoqobolo oops, that's a good catch. Will update it in a sec.

**Comment by alwx** [comment]
@qoqobolo please recheck. 
I suspect "Online" should also be shown only for 1-1 chats, right? (that's how I implemented it in this PR)

**Comment by qoqobolo** [comment]
> I suspect "Online" should also be shown only for 1-1 chats, right? (that's how I implemented it in this PR)

Yeah, right. I was referring to the online status itself but didn't figure out how to get `Online` for channels and groups :)
Thank you, I'll recheck.

**Comment by qoqobolo** [comment]
Thanks @alwx, looks good to me now 👍
PR is ready for design review.

**Review by Francesca-G — COMMENTED** [review]
Here's the [Figma frame](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS/Feedback-for-Mobile?type=design&node-id=3817%3A74882&mode=design&t=KdF0myxaoFKq5Bp6-1) with the design review

**Pull request merged**
