### PR TITLE
[17514] Use OS emojis in emoji picker

### LINKED ISSUE #17514: emoji in message long-press reaction menu should be OS emojis
# Bug Report

design feedback: https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=5960:8249&t=BpzZ5GTnwcCRiIIf-0&locale=en&type=design#567176292

### PR DESCRIPTION
**Pull request by ibrkhalil**
fixes #17514 
CleanShot 2024-01-04 at 18 52 44

### Summary

Uses OS emojis in emoji picker

status: ready

### CODE REVIEW

**Review by yqrashawn — APPROVED** [review]
LGTM

**Review by Parveshdhull — APPROVED** [review]

**Comment by clauxx** [comment]
2024-01-09 10 19 13 github com 1b02188b41fc

@ibrkhalil thanks for the PR. There seems to be no bottom space below the `add-reaction` icon. Is this intended or outside the scope of the PR?

**Comment by ibrkhalil** [comment]
> 2024-01-09 10 19 13 github com 1b02188b41fc
> 
> @ibrkhalil thanks for the PR. There seems to be no bottom space below the `add-reaction` icon. Is this intended or outside the scope of the PR?

Good point, I don't think it should show if the message is rendered in the preview state (Long pressed)
Will fix

**Comment by ibrkhalil** [comment]
> 2024-01-09 10 19 13 github com 1b02188b41fc
> 
> @ibrkhalil thanks for the PR. There seems to be no bottom space below the `add-reaction` icon. Is this intended or outside the scope of the PR?

Done

**Comment by qoqobolo** [comment]
@ibrkhalil thanks for PR!

### ISSUE 1: Chat view still uses old emojis

**Steps:**
1. Open chat
2. Send a message
3. Add a reaction

**Expected result:** OS emojis are used everywhere
**Actual result:** OS emojis are only used in emoji picker

I see that in the issue and description only emoji picker is mentioned but emojis should be updated everywhere.
Could you fix this as part of this PR, please?

Screenshot 2024-01-15 at 11 01 05
Screenshot 2024-01-15 at 11 01 13

**Comment by ibrkhalil** [comment]
> @ibrkhalil thanks for PR!
> 
> ### ISSUE 1: Chat view still uses old emojis
> **Steps:**
> 
> 1. Open chat
> 2. Send a message
> 3. Add a reaction
> 
> **Expected result:** OS emojis are used everywhere **Actual result:** OS emojis are only used in emoji picker
> 
> I see that in the issue and description only emoji picker is mentioned but emojis should be updated everywhere. Could you fix this as part of this PR, please?
> 
> Screenshot 2024-01-15 at 11 01 05 Screenshot 2024-01-15 at 11 01 13

Should be done now, Thanks!

**Comment by qoqobolo** [comment]
Thanks for the fix @ibrkhalil!

Question about margins in two places:
**1. when the message is long-pressed** 
 
It looks a bit different comparing to the designs, check Figma here: https://www.figma.com/file/PPWkgOYlZZDxZv5SDGsZVV/Posts-%26-Attachments-for-Mobile?type=design&node-id=2869-258244&mode=design&t=4sfccVUp2eVQ0a6d-4

Screenshot 2024-01-15 at 14 09 37

**2. In the chat view when all the reactions are added**

The `add reaction` button goes beyond the highlighted area. It was only visible on small screen devices before, but now, with new OS emojis, I can see this on Pixel 7a as well

Screenshot 2024-01-15 at 14 23 21

Are these issues in the scope of this PR or should we log them separately? WDYT?

**Comment by ibrkhalil** [comment]
> Thanks for the fix @ibrkhalil!
> 
> Question about margins in two places: **1. when the message is long-pressed**
> 
> It looks a bit different comparing to the designs, check Figma here: https://www.figma.com/file/PPWkgOYlZZDxZv5SDGsZVV/Posts-%26-Attachments-for-Mobile?type=design&node-id=2869-258244&mode=design&t=4sfccVUp2eVQ0a6d-4
> 
> Screenshot 2024-01-15 at 14 09 37
> **2. In the chat view when all the reactions are added**
> 
> The `add reaction` button goes beyond the highlighted area. It was only visible on small screen devices before, but now, with new OS emojis, I can see this on Pixel 7a as well
> 
> Screenshot 2024-01-15 at 14 23 21
> Are these issues in the scope of this PR or should we log them separately? WDYT?

Issue 1 is related, Issue 2 can be separate since it's related to how the message shows it's content
But I can do it here too.
Thank you very much for the review, I'll ping you when I do the issues as I am currently working on another task.

**Comment by qoqobolo** [comment]
@ibrkhalil thank you!

**Comment by ibrkhalil** [comment]
> @ibrkhalil thank you!

Issue 2 is fixed, Issue 1 I think is happening because we're using emojis different than the designs
I think we can see if it happens again during implementation of the Twemojis.

**Comment by qoqobolo** [comment]
> Issue 2 is fixed

I still can reproduce it on Pixel, could you recheck please? @ibrkhalil 
Screenshot 2024-01-18 at 11 49 52

>  Issue 1 I think is happening because we're using emojis different than the designs
I think we can see if it happens again during implementation of the Twemojis.

Got it, let skip it for now then.

**Comment by qoqobolo** [comment]
@ibrkhalil ah another thing

#### ISSUE 3: Wrong `crying` and `laughing` emojis

Both for Android and iOS

**Figma**

https://www.figma.com/file/PPWkgOYlZZDxZv5SDGsZVV/Posts-%26-Attachments-for-Mobile?type=design&node-id=8952-68170&mode=design&t=7vnF6CBm4uzMbmYz-4

Screenshot 2024-01-18 at 16 18 53

**PR**

Screenshot 2024-01-18 at 16 20 51

**Comment by ibrkhalil** [comment]
> @ibrkhalil ah another thing
> 
> #### ISSUE 3: Wrong `crying` and `laughing` emojis
> Both for Android and iOS
> 
> **Figma**
> 
> https://www.figma.com/file/PPWkgOYlZZDxZv5SDGsZVV/Posts-%26-Attachments-for-Mobile?type=design&node-id=8952-68170&mode=design&t=7vnF6CBm4uzMbmYz-4
> 
> Screenshot 2024-01-18 at 16 18 53
> **PR**
> 
> Screenshot 2024-01-18 at 16 20 51

Both issues should be fixed now.

**Comment by qoqobolo** [comment]
@ibrkhalil thanks for the fixes, LGTM!
and thanks @yevh-berdnyk for fixing e2e 🙏
PR can be merged.

**Pull request merged**
