### PR TITLE
[#18752] fix: The W/O address shouldn't be in account selection

### LINKED ISSUE #18752: Account selection: watch-only accounts are displayed in the account selector
# Bug Report

## Problem 

We should not include watch-only addresses in account selection when joining a community (both for sharing with the community and airdrop?)

https://github.com/status-im/status-mobile/assets/67952253/d0cfd136-8076-4419-a7ba-cbbed3695b56

### Reproduction

1. Add a watch-only address 
2. Open a token-gated community > open account selection screen

#### Expected behavior
The W/O address is not in the list

#### Actual behavior

The W/O address is displayed in the list

### Additional Information

- Status version: [nightly ](https://github.com/status-im/status-mobile/pull/18530)
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by mohsen-ghafouri**
fixes #18752

### Summary

We should not include watch-only addresses in account selection when joining a community

### Result

https://github.com/status-im/status-mobile/assets/71308738/177e4593-d7cc-4e2f-9adb-c5420873cec6

status: ready

### CODE REVIEW

**Review by cammellos — APPROVED** [review]

**Review by ajayesivan — APPROVED** [review]

**Comment by qoqobolo** [comment]
Thanks for the fix @mohsen-ghafouri!

### ISSUE 1: Watch-only accounts are still visible on the `Request to join` page

These two accounts are watch-only

image

**Comment by qoqobolo** [comment]
@mohsen-ghafouri also there is still a problem that the watch-only account balance also counts when checking if you meet requirements. 
Should this PR fix it?

That is, my account has 0 balance.
I add a watch-only which has 0.5 ETH.
I set permission in the community: `Anyone who holds 0.2 ETH is allowed to become a member`.

As you can see in the video, I can send a request to join the community, although the `Join Community` button should become inactive. 
And although the request has been sent, the member will not join the community in fact and the status will remain `Pending` forever.


https://github.com/status-im/status-mobile/assets/67952253/b356b4d0-9e1e-4616-bdac-40bc12cf1308

**Comment by mohsen-ghafouri** [comment]
@qoqobolo could you please check again for issue 1? second issue doesn't seems to be related to this PR and looks more complicated

**Comment by qoqobolo** [comment]
Thank you @mohsen-ghafouri, Issue 1 is fixed.
We're discussing what to do with the second one. I'll let you know when the PR can be merged.

**Comment by mohsen-ghafouri** [comment]
@qoqobolo I just tested my PR with @cammellos changes in status-go and now it looks fine. could you please check again the second issue?

**Comment by qoqobolo** [comment]
Thanks @mohsen-ghafouri and @cammellos , great job!
PR can be merged.

**Pull request merged**
