### PR TITLE
Update status-go to develop-gd71c66a2

### PR DESCRIPTION
**Pull request by adambabik**
### Summary:

Update status-go to a version build with Go 1.9.2.

### CODE REVIEW

**Review by oskarth — APPROVED** [review]
@adambabik Any breaking changes since gb7fb51d9?

**Comment by adambabik** [comment]
@oskarth no breaking changes expected but it requires some additional testing I would say as we bumped go from 1.7.1 to 1.9.2 + I had some issues with building those Docker images for cross-building, so you know :)

However, I run it on iOS simulator today and it was just fine.

**Comment by oskarth** [comment]
QA: Sanity check of app. A dev could also do this and then merge if they want.

**Comment by oskarth** [comment]
No specific new capabilities introduced as far as I'm aware of (at least not that status-react is waiting for). Marking as low priority for QA for now.

**Review by flexsurfer — APPROVED** [review]

**Review by rasom — APPROVED** [review]

**Comment by adambabik** [comment]
It got build successfully: https://jenkins.status.im/job/status-react/job/pull%20requests/view/change-requests/job/PR-2954/

**Comment by rasom** [comment]
Android: https://i.diawi.com/QxzCho
iOS: https://i.diawi.com/GQ3vTS

**Comment by oskarth** [comment]
@adambabik Assuming https://github.com/status-im/status-go/issues/547 is indeed a status-go bug, we'll need to bump this status-go and make it high prio for QA to test so we can get it into release.

QA: don't test until https://github.com/status-im/status-go/issues/547 is fixed and this is bumped, then we remove low prio and this should be tested asap

**Comment by oskarth** [comment]
Moving back into CONTRIBUTOR until it is clear what state of https://github.com/status-im/status-go/issues/547 is.

Also requires resolving conflicts.

**Comment by rasom** [comment]
fixes status-im/status-react#2653

**Comment by asemiankevich** [comment]
I'm adding `release` and `high-priority` to this PR, it fixes https://github.com/status-im/status-react/issues/2653

**Comment by asemiankevich** [comment]
----------------
Branch: PR-2954
Android: https://i.diawi.com/XbZ7Xb
iOS: https://i.diawi.com/H7ZdRb

so @adambabik @rasom what i have noticed so far when testing it:

1. communication problem returned, i don't see messages neither on iOS nor on Android . No add contact requests, no transactions send obviously. Restart does not help much. **NOTE**: latest develop looks fine per @Serhy 

2. the lags when creating account are really visible for end user, the messages are overlapping each other and "jumping". **NOTE**: it is less visible in latest develop. Please check TFs for this and screenshots:

Android: https://app.testfairy.com/projects/4803622-status/builds/7504300/sessions/4/?accessToken=GfyHNCFWYmroELsVcmgY9FeSTNQ

image


iOS: https://app.testfairy.com/projects/4803590-status/builds/7504140/sessions/5/?accessToken=iMiuSICtWTio4WA2Pbqt53pkpmQ

image

3. This PR **solves** problem with sending transaction to dApp (auction house for example).
image

**Comment by annadanchenko** [comment]
@asemiankevich @rasom @adambabik I've also installed same PR build and there is no communication problem for my 2 devices - can see empty 1-1 chat after added as a contact, can send and receive text and transactions. Fix solved the problem with Dapp. 

I'd like to get it in the release build, so we start testing with upgraded go asap.

**Pull request merged**
