### PR TITLE
Replaced incorrect aget access FIX #3067

### LINKED ISSUE #3067: Replace incorrect aget access
### User Story

As a developer, I want to rely on good dev practises

### Description

*Type*: Feature

`aget` is only supposed to be used for `array` access and not `object fields` access. Replace all incorrect usages with proper access (to be defined).

### PR DESCRIPTION
**Pull request by ghost**
fixes #3067
Summary: Replaced incorrect `aget` access.

status: ready

### CODE REVIEW

**Comment by jeluard** [comment]
@audriu Is it still WIP?

**Comment by audriu** [comment]
@jeluard well yes but CI is failing and I can not know why...

**Comment by audriu** [comment]
@jeluard @janherich It is ready now!

**Comment by audriu** [comment]
This CI setup fails at random. Even whitespace change push can fix...

**Review by jeluard — APPROVED** [review]

**Review by dmitryn — APPROVED** [review]

**Comment by dmitryn** [comment]
I've tested this by running app with figwheel. Also, i run `lein with-profile prod cljsbuild android` - no issues detected.

**Comment by audriu** [comment]
Could someone give me CI output please?

**Comment by jeluard** [comment]
@goranjovic Do you mind looking at Jenkins log?

**Comment by goranjovic** [comment]
@audriu 
```
+ lein test-cljs
clojure.lang.ExceptionInfo: failed compiling file:src/status_im/chat/models/input.cljs {:file #object[java.io.File 0x6817722b "src/status_im/chat/models/input.cljs"]}
	at clojure.core$ex_info.invokeStatic(core.clj:4739)`
```
Can you try running `lein test-cljs` locally and see what happens?
I don't think build touches any test code, so it could be the reason.

**Comment by ghost** [comment]
Oops sorry, I thought it was usual CI glitch.
@rasom @janherich could you review this PR?

**Comment by dmitryn** [comment]
I don't see error in Jenkins and `lein test-cljs` goes fine for me. 

@audriu why do you need additional reviewers for this PR?

**Comment by ghost** [comment]
@dmitryn I want it merged. I can see that 2 more reviewers are assigned to this ticket, so just assuming that if they will review it could be merged.

**Comment by dmitryn** [comment]
I'm going to merge this if @goranjovic and @jeluard don't have anything to add here.

**Comment by jeluard** [comment]
@dmitryn Please go ahead

**Pull request merged**
