### PR TITLE
chore: bump status-go

### PR DESCRIPTION
**Pull request by osmaczko**
Run regression tests for: https://github.com/status-im/status-go/pull/6025

### CODE REVIEW

**Comment by osmaczko** [comment]
@qfrank can you please check if logging works as expected on mobile? Thanks :pray:

**Comment by qfrank** [comment]
> @qfrank can you please check if logging works as expected on mobile? Thanks 🙏

LGTM though I only checked `geth.log` and `requests.log` with ios build

**Comment by osmaczko** [comment]
> > @qfrank can you please check if logging works as expected on mobile? Thanks 🙏
> 
> LGTM though I only checked `geth.log` and `requests.log` with ios build

Thank you!

**Comment by pavloburykh** [comment]
@osmaczko thanks for the PR. e2e results are fine, failures are not PR related. Do we need any additional manual testing of this PR? If yes, could you please provide some details on what specifically should be tested and which areas are affected?

**Comment by osmaczko** [comment]
> @osmaczko thanks for the PR. e2e results are fine, failures are not PR related. Do we need any additional manual testing of this PR? If yes, could you please provide some details on what specifically should be tested and which areas are affected?

@pavloburykh thank you very much. e2e and confirmation from @qfrank is more than enough :ok_hand:

**Pull request closed without merging**
