### PR TITLE
Shows app version.

### LINKED ISSUE #889: Show app version
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to find app version in the app's interface so that I know which version is used.

Instabug: 
* https://dashboard.instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/264
* https://dashboard.instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/387

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature 

*Summary*: There is no app version in the app. User needs to go to settings and check the version there. It would be better to show the app version, e.g. in profile

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
App version can be found in the app
#### Actual behavior
[comment]: # (Describe what actually happened.)
there is no app version now in the app interface

### Solution
[comment]: # (Please summarise the solution and provide a task list on what needs to be fixed.)
*Summary*: 

- [ ] Design app version place and look
- [ ] Implement "show app version"

### PR DESCRIPTION
**Pull request by ghost**
fixes #889

### Steps to test:
- Open Status
- Open profile screen
- Observe version number

status: ready

I believe it may not fit on smaller devices. Please advice!

screenshot from 2018-03-06 12-17-54

### CODE REVIEW

**Comment by jeluard** [comment]
@audriu Any way we can do that without introducing a new dependency?

**Comment by audriu** [comment]
@jeluard I will try to do so.
What do you think about position of the Version string?

**Comment by jeluard** [comment]
I would say it's good enough for now? @denis-sharypin WDYT?

Can we enable it only for dev build somehow? (maybe using a special flag?)

**Comment by denis-sharypin** [comment]
@audriu what's the font size of version string? Should be 11 px

**Comment by jeluard** [comment]
@audriu Did you close by mistake?

**Comment by audriu** [comment]
@jeluard I closed it on purpose. I understood that all this needs different solution.

**Comment by jeluard** [comment]
@audriu I understand it is related to the RN dependency? A workaround could be to integrate this code in our native layer, as I understand it's pretty small.

**Comment by lukaszfryc** [comment]
Any progress on it? The Status version would be great to have. We could even implement it as a method of `web3` in Console.

**Comment by denis-sharypin** [comment]
@lukaszfryc  Good idea actually! @annadanchenko what do you think?

**Comment by audriu** [comment]
@lukaszfryc  @denis-sharypin  I am not working on this...

**Pull request closed without merging**
