### PR TITLE
Bug/message ordering #2699

### LINKED ISSUE #2699: Messages are received in different order then sent
[comment]: # (Please replace ... with your information. Remove < and >)

### Description

When user A sends messages in rapid succession to user B, while user B is offline, once user B starts the app and and the messages are received, they are displayed in a wrong order, see the attached screenshot.

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status on device A
- Open Status on device B
- Exchange contact info so A and B are mutual contacts
- Starts 1-1 chat between A and B (doesn't matter who starts it)
- Close the app on device B
- Send couple of messages in rapid succession from device A to device B
- Open status app on device B, wait till messages from A are received and examine their order
screen shot 2017-12-12 at 13 53 14

### PR DESCRIPTION
**Pull request by janherich**
[comment]: # (Please replace ... with your information. Remove < and >)
[comment]: # (To auto-close issue on merge, please insert the related issue number after # i.e fixes #566)

fixes #2699 

### Summary:

[comment]: # (Summarise the problem and how the pull request solves it)
This PR implements work already done in `experiment/new-protocol-app` branch, definitely fixing message ordering in 1-1 chats. It's little bit more tricky for group chats, where it's still the old "the messages are displayed in order they arrive".

Description of the clock logic implemented in this PR (relevant only for 1-1 chats):

We start with [0 0] ([`from-clock-value` `to-clock-value`]) for each participant of 1-1 chat (local perspective on each device).
Now for sending, we always increment the `to-clock-value` and include it in message payload being sent (so only `to-clock-value` is present in network message).
Locally, the sent message always replicates the `latest-from-clock-value` of the chat.
Upon receiving message, receiver reads the `to-clock-value` of the received message and sets that to be the `from-clock-value` locally (this will be also the new `latest-from-clock-value` of the chat), `to-clock-value` for the message is the `latest-to-clock-value` of the 1-1 chat`. 

All this ensures, that there will be no [`from-clock-value` `to-clock-value`] duplicate in chat message on each device + the local order will appear consistent, even if it’s possible it won’t be the same on both devices (for example user A sends 5 messages, during the sending, he receives the message from user B, so his local order will be `A1, A2, B, A3, A4, A5`, but his messages will take a long time to reach user B, for some reason, so user B will see it as `B, A1, A2, A3, A4, A5`).
I don’t think that’s very problematic and I don’t think we can do much about it without single source of truth where order received messages are serialised and definite order is established (server), it is the case even in the current implementation.

### Testing notes (optional):
Test the scenario described in the ticket + make sure that standard messaging in all types of chats work correctly (though it's not necessary to test all message types, commands/requests are unaffected, so testing with plain text messages is fully sufficient).
Eventually, we will need to support migration from previous versions, that doesn't currently work (old messages already in app before migration will have no definite order, only the new created after migration), opening it either way, as it's high priority to have this working in nightly build by offsite (and I will probably add migrations tomorrow).

status: ready

### CODE REVIEW

**Comment by oskarth** [comment]
Can you explain the exact semantics around`:last-to-clock-value` and `:last-from-clock-value 0`? How does this impact the current `send` and `recv` clock functions? E.g. https://github.com/status-im/status-react/blob/15f4c90caabe92efe22ef7f37845cccbd35707de/src/status_im/chat/models/message.cljs#L61 etc

**Review by yenda — APPROVED** [review]

**Comment by janherich** [comment]
@oskarth clock util is not used at all.

**Review by oskarth — CHANGES_REQUESTED** [review]
It's not clear to me how the semantics around this new type of clock works, :last-to-clock-value and :last-from-clock-value. Since this is a fairly complex piece of code it'd be really useful to see this in PR description as well as in documentation (and tests?) in a namespace or so. Clocks in distributed systems is a non-trivial problem so it should be especially well-documented.

For example, see the existing Lamport clock semantics documentation: https://github.com/status-im/status-react/blob/80fb8dde8baea957d37cdf94f0ea88f74b7c810a/src/status_im/utils/clocks.cljs and tests: https://github.com/status-im/status-react/blob/9bacc65c8d2a6719ff73a0866f3a57ce205bced6/test/cljs/status_im/test/utils/clocks.cljs

**Comment by janherich** [comment]
@oskarth I provided description of clock logic, please check.

**Review by oskarth — APPROVED** [review]
Approve pending basic documentation in code so we don't lose this

**Comment by annadanchenko** [comment]
Sent 18 messages to ios, they are received in ok order but when iOS device who received them sends new message then it’s shown not as a last one in chat but in the mid of that 18 messages….

TF (00:27) https://app.testfairy.com/projects/4803590-status/builds/7812300/sessions/13/?accessToken=BKO3eNqtbSCeU93oDuqrrm56tm0

**Comment by annadanchenko** [comment]
On the build with a fix: PN is not shown on iOS device if send to it message in 1:1 chat  (sender and receiver are in contacts for each other). App is run in background or closed - for both cases there is no PN. 

On Android works ok (PN is shown) if send message from iOS device while app is in background. 

Also checked on nightly build - PN is shown ok both for ios and android devices
Branch: status-im:bug/message-ordering-#2699
Android: https://i.diawi.com/tVX7qf
iOS: https://i.diawi.com/LGTX34

**Comment by janherich** [comment]
@annadanchenko this is very strange as the changes have nothing to do with PNs... are you sure it's not happening on develop as well ?

**Comment by asemiankevich** [comment]
@janherich I am looking into it now but https://github.com/status-im/status-react/issues/3505 blocks me =( UPD: it does not happen in Genymotion so i will check there

**Comment by asemiankevich** [comment]
@janherich odd thing that i noticed:

I have both android and ios upgraded to Android: https://i.diawi.com/FcCASN
iOS: https://i.diawi.com/ayvUsB
Both of them have 20 messages shown in wrong order
I am logging on Android and creating new account (after upgrade). Then this account is added to friends of iOS device which is running the account created before upgrade. Then i send message from ios to android and turn ios offline. Sending to ios 20 messages from android and then bring the device back online. 

As a result the very first message i send from ios to android is always at the bottom of the chat. Please see TF from 0:47 https://app.testfairy.com/projects/4803622-status/builds/7817838/sessions/4/?accessToken=PV8g54V6byjgVXIBhSFmkcfgYQU

I have tested the PR without upgrade and it seems to be okay.

**Comment by janherich** [comment]
@asemiankevich Unfortunately this (sending messages from upgraded device to non-upgraded device) can't work.
The only migration which is supported is that all devices upgrade to new code and start exchanging messages only after that.

**Comment by asemiankevich** [comment]
@janherich  i am sorry for the confusing - all the devices are upgraded. The difference between 2 is that one device is running the same account (i created it on release build and was able to login after upgrade) and second (android) can't relogin so I had to create new account

**Comment by asemiankevich** [comment]
@janherich I have checked this once more - the message order is fine and looks good to me in both cases: 
1. when fresh install of this PR
2. when upgrading develop to this PR

Maybe we can handle the release migration in separate task? I would like to have this PR merged anyway.

**Pull request merged**
