### PR TITLE
[fixes #2523] fix RU translations

### LINKED ISSUE #2523: Ru translation fixes
### Description

*Type*: Bug
***NOTE* still collecting all the discrapencies please do not build any pr untill this is done**
*Summary*: 

1. in line 330 change `не применимо` to `неприменимо`
2. Remove line 123 as this case is no more valid
3. Make line 201 and 202 alike so make ether `скопировать` for both or `копировать` for both
4. Fix usage. Please put this:

line 66 :datetime-second                       {:one   "секунда"
line 67                                                     :other "секунд(ы)"}
line 68 :datetime-minute                       {:one   "минута"
line 69                                                    :other "минут(ы)"}
line 70  :datetime-hour                         {:one   "час"

5 Line 71 - need to fix the usage, please check examples
 - 1 `час назад`
 - 2 `часа назад`
 - 5 `часов назад`
6. Line 72 fix the usage:
- 1 день
- 2 дня 
- 5 дней
7. `Send location` modal header is not translated 
#### Expected behavior
`неприменимо для неподписанных транзакций`
 - 1 `час назад`
 - 2 `часа назад`
 - 5 `часов назад`

#### Actual behavior
image

image

### Additional Information
* Status version: latest develop

#### Logs
https://github.com/status-im/status-react/blob/develop/src/status_im/translations/ru.cljs

### PR DESCRIPTION
**Pull request by dmitryn**
Fixes some of russian translations

See #2523 for details.

status: ready

### CODE REVIEW

**Comment by andytudhope** [comment]
Was gonna do this myself with a PR to clean up Spanish and Korean too, but you might as well edit this in here while you're at it. Please add back the `:status-sending` key at line 57 of ru.cljs like so:
```
:status-sending                        "Отправляется..."
```
I can then test fully. (This was left out of the last Russian translation - nothing to do with your PR - and we now have a neat bunch of tests that identify this for us, see here for ref: https://github.com/status-im/status-react/pull/2510 )

**Comment by dmitryn** [comment]
@andytudhope ok, i've added `:status-sending` key to RU translation.

**Review by flexsurfer — APPROVED** [review]

**Review by andytudhope — APPROVED** [review]

**Comment by oskarth** [comment]
@andytudhope Can this be merged?

**Comment by flexsurfer** [comment]
@oskarth is it tested?

**Comment by andytudhope** [comment]
Yes, we can merge this @oskarth - have tested. No bounty, so let's merge now.

**Comment by oskarth** [comment]
Merging directly without code signing due to https://github.com/status-im/status-react/issues/2636. Thanks @trybeee!

**Pull request merged**
