### PR TITLE
Webview is still active after unmount [#4353]

### LINKED ISSUE #4353: Webview is still active after unmount
Actual:
webview JS still running after webview has been unmounted

Expected:
webview JS should be destroyed after component is unmounted

### PR DESCRIPTION
**Pull request by flexsurfer**
Removed unused code for nfc, and made quick "fix" for just clear js, but webview still active

fixes #4353

### CODE REVIEW

**Comment by jeluard** [comment]
@flexsurfer Can you detail what it fixes and what would be the proper fix?

**Review by jeluard — APPROVED** [review]

**Comment by flexsurfer** [comment]
@jeluard yes sure, so for some reason after we unmount webview component, it still active, and JS code running, so i just reload web content to blank, so JS is not running anymore, but in proper way webview component should be destroyed , it should be done in native component, i couldn't find a way how to fix it in native component

**Review by goranjovic — APPROVED** [review]

**Review by dmitryn — APPROVED** [review]

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/uCmeT8 for branch PR-4400

<blockquote><div><strong><a href="https://i.diawi.com/uCmeT8">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/re6Duo for branch PR-4400

<blockquote><div><strong><a href="https://i.diawi.com/re6Duo">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/srGE45 for branch PR-4400

<blockquote><div><strong><a href="https://i.diawi.com/srGE45">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/UnFiNZ for branch PR-4400

<blockquote><div><strong><a href="https://i.diawi.com/UnFiNZ">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/udrcQ9 for branch PR-4400

<blockquote><div><strong><a href="https://i.diawi.com/udrcQ9">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/DVMVwx for branch PR-4400

<blockquote><div><strong><a href="https://i.diawi.com/DVMVwx">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by lukaszfryc** [comment]
I didn't experience any regressions. 

I'm rechecking performance (battery, network) today. Hopefully this PR will make a difference in battery consumption.

**Comment by flexsurfer** [comment]
@lukaszfryc please don't expect much from this change, it can affect battery if for example, you open a lot of dapps , and they doing a lot of calculation in the loop

**Pull request merged**
