### PR TITLE
Prevent profiles list from disappearing after onboarding and logging out

### LINKED ISSUE #19094: After logging out, the list of profiles is not displayed
Unfortunately, there are no exact steps to reproduce this issue. It seems to happen randomly. Hope that the logs can provide more info what's going on

### Steps:
1. Leave logged in user for a while (2-3 minutes)
2. Tap log out
3. Navigate to the list of profiles
image

### Actual result:
The empty screen is shown

https://github.com/status-im/status-mobile/assets/52490791/5ce47226-e032-4c8b-ac37-df38eacc7ec5

### Expected result:
The list of profiles is shown

### Logs:
[logs.zip](https://github.com/status-im/status-mobile/files/14484427/logs.zip)

### Env:
Env [4 Mar 2024]

### PR DESCRIPTION
**Pull request by seanstrom**
[comment]: # (Please replace ... with your information. Remove < and >)
[comment]: # (To auto-close issue on merge, please insert the related issue number after # i.e fixes #566)

fixes #19094 

### Summary

[comment]: # (Summarise the problem and how the pull request solves it)

* This PR attempts to fix the issues related to the profiles list not appearing when choosing a user profile at login.
  * This PR modifies the unmount hook of the profiles view to reset the `translate-x` offset to `0` after unmounting.
    * This seems necessary because the profiles view seems to display other views / modals inside of itself, which causes the profile list to be moved / animated offscreen. 
    * This offset value is supposed to be reset after the onboarding screens have finished or when the user navigates back to the profiles list.
    * This PR attempts to ensure that the offset value will always be reset whenever the profiles view or onboarding screens are finished.

#### Platforms

- Android
- iOS

##### Functional

- account recovery
- new account
- existing account sync
- onboarding

### Steps to test

- Open Status mobile
- Press the profiles list button (if viewing the login screen)
- Press the "+" button
- Press the "Create new profile" button
- Create a new profile or recover a profile
- Once passed the welcome screen, logout from the app
- While viewing the login screen, press the profiles list button

#### Before

https://github.com/status-im/status-mobile/assets/2845768/8b3c59f6-3165-4112-9fbd-ebe12123f550

#### After

https://github.com/status-im/status-mobile/assets/2845768/ec68bcfe-38de-45e3-a660-d3ff43c147ff

status: ready

### CODE REVIEW

**Review by mohsen-ghafouri — APPROVED** [review]
LGTM :)

**Review by jo-mut — APPROVED** [review]

**Comment by mariia-skrypnyk** [comment]
Hi @seanstrom !
Thanks for your PR!
Please, can you do a rebase?

**Comment by seanstrom** [comment]
@mariia-skrypnyk yup yup, I've rebased and pushed now 🙏

**Comment by mariia-skrypnyk** [comment]
Hi @seanstrom!
Fix looks great! Thanks!
Please, feel free to merge it.

**Pull request merged**
