### PR TITLE
Fetch new version of base images with fixed ubuntu-server

### PR DESCRIPTION
**Pull request by vkjr**
Related to status-im/security-reports#6

### Summary

New binaries of `ubuntu-server` with security fix were generated for all platforms and uploaded to digitaloceanspaces
Nix files were updated to use fixed binaries

### Review notes
ubuntu-server binaries uploaded, nix files changed to download new versions

### Testing notes
Replacing ubuntu-server won't affect app logic but can affect app startup. So if it starts and able to login then `ubuntu-server` works fine with `react-native-desktop` and `realm.

#### Platforms
- macOS
- Linux
- Windows

##### Functional
- new account
- user profile updates

### Steps to test

- Open Status
- Ensure it runs
- Ensure you are able to login

status: ready

### CODE REVIEW

**Review by mandrigin — APPROVED** [review]

**Review by pedropombeiro — APPROVED** [review]

**Review by jakubgs — APPROVED** [review]

**Comment by annadanchenko** [comment]
@vkjr is it to include the fix into nightlies?

**Comment by asemiankevich** [comment]
@annadanchenko @vkjr is 0.13 version expected here? Also, do we need to verify checksummes here again?

I've checked MacOS - looks okay with upgrade and fresh install, can recover and create account and receive some messages.

**Comment by vkjr** [comment]
@annadanchenko, yes, this one fixes the same thing in `develop`, so will affect nightlies.

@asemiankevich, yes, version 0.13 expected, it is bumped in `develop` [3 days ago](https://github.com/status-im/status-react/commit/713a461415a479277658a66036917830436eb0f6)
I don't think there is a need to check hashes. You already checked that packages on our servers contain correct versions of `ubuntu-server`. This commit uses the same packages, so your check still valid.

**Comment by annadanchenko** [comment]
Will do smoke test on Windows

**Comment by Serhy** [comment]
Linux smoke test looks good to me. 
Can create new account, recover account, receive messages in 1-1 chat, offline history of public chats. 
shasum of ubuntu-server = `2b1219f249e71b6f2cffd6ed2f77c1a5747194c8879b9af5b83da0db61c16263` as expected.

**Comment by annadanchenko** [comment]
same tests on windows are ok (create new account, recover account, receive messages in 1-1 chat, offline history of public chats, upgrade from previous stable version)

**Comment by vkjr** [comment]
Thanks! Merged

**Pull request merged**
