### PR TITLE
Custom fonts loading added to desktop app

### LINKED ISSUE #4860: Correct font (San Francisco) is missing
**Issue:**
"San Francisco", the OSX native font is missing 
Download SF > https://developer.apple.com/fonts/

**Problem:**
Without the proper font displayed, sizes, spacing, and measurements don't match the design specifications.

**Expected results:**
Users should be able to see all content in the app displayed using SF font (as specified in the designs).

### PR DESCRIPTION
**Pull request by vkjr**
fixes #4860

### Summary:

- fonts for macos added to resources
- desktop files updated to load fonts from resources (changes copied from already existing feature in `react-native-desktop`
- references to new fonts added in `status-im.desktop.platform.cljs`

### Testing notes (optional):
Text input fields like chat adding and new contact adding doesn't support fonts changing due to react-native issue. Will be fixed automatically when this PR merged - https://github.com/status-im/react-native-desktop/pull/313https://github.com/status-im/react-native-desktop/pull/313

### Steps to test:
- Open Status
- Navigate to different pages, make sure that San Francisco font used on mac, or Arial on linux

status: ready

### CODE REVIEW

**Review by janherich — APPROVED** [review]

**Comment by vkjr** [comment]
@MaxRis, @janherich, I had an issue with rebasing in #5435, so recreated PR. Could you please approve it again. Thanks.

**Review by yenda — APPROVED** [review]

**Review by maxhora — APPROVED** [review]

**Comment by vkjr** [comment]
@churik, please take a look at this one, thanks.

**Comment by churik** [comment]
1) Selected chat and header are not bold;
Expected: https://zpl.io/aRqj4dv
Actual result:
monosnap 2018-08-17 15-45-18

 2) A lot of chars also not avilable in this font (issue https://github.com/status-im/status-react/issues/5344) - is it possible to resolve it somehow? all these chars are displayed correctly in mobile (I asked because I thought it can be fixed when we add new font)

**Comment by vkjr** [comment]
@churik, I made header and selected chat text bolder.
As for #5344, I'm not sure what is exact problem that causes that and suggest to fix it separately.

**Comment by churik** [comment]
Tested (Mac OSx):
- new font is using in all screens and input fields
- selected items in Profile, chats and chat headers are marked as bold. 


Tested (IOS):
- installation
- join to several chats. 
No regression issues are found.

**Comment by churik** [comment]
1. Cannot navigate to user profile when there are several messages in a row (should be last in chat)
Steps:
- join to any chat where several last messages are sent in a row from one user (21/08/18 it is `#tery` and `status-desktop`)
- click on user pic to navigate to user profile

* Expected: *
navigated to user profile

* Actual: *
cannot navigate when clicking on user picture
dfsfd

* Video: * http://take.ms/I0jFN
* Log: * [StatusIm.txt](https://github.com/status-im/status-react/files/2306728/StatusIm.txt)

**Pull request merged**
