### PR TITLE
Optimized counter increment logic for 1-1 chat messages

### LINKED ISSUE #16696: Optimized counter increment logic for 1-1 chat messages
See the original feature description provided by @John-44 in this conversation (see point B) https://discord.com/channels/624634427930312714/928646594314784859/1129407293256122429

Currently, in a 1-1 chat, each message sent increments the counter, regardless of the proximity of the messages in time. To enhance the user experience we should implement an optimized logic for the counter incrementation.

The suggested behavior is as follows: When a 1-1 chat message is sent, the counter will be incremented by 1. However, if another message is sent within 2 minutes of the previous message, the counter will not be incremented, and the 2-minute window will reset. Only when no further messages are received within the subsequent 2 minutes after the most recent message, the counter will increment again upon sending a subsequent message.

By implementing this logic, the counter will accurately reflect the number of distinct messaging events rather than incrementing for each individual message sent within a short time frame. This optimization will provide a more meaningful representation of chat activity while avoiding unnecessary counter increments and reducing visual clutter.

### PR DESCRIPTION
**Pull request by alwx**
fixes https://github.com/status-im/status-mobile/issues/16696

well, the fix is actually done here: https://github.com/status-im/status-go/pull/3889
this PR basically just updates the status-go version to make it possible to test the change in status-mobile

#### Platforms

- Android
- iOS
- macOS
- Linux
- Windows

status: ready

### CODE REVIEW

**Comment by alwx** [comment]
Nothing for code review here because the change is done in Go part — moving it to `E2E Tests`
cc @churik @qoqobolo

**Comment by qoqobolo** [comment]
> Nothing for code review here because the change is done in Go part — moving it to E2E Tests

@alwx GH won't allow you to merge a PR without at least one approval, so you need to get it purely formally anyway

**Comment by churik** [comment]
@alwx hello!
why this PR is merged on go side?
It needs to be tested first on mobile side, otherwise we risk to get a bug on status-go side which will block partially both platforms

**Comment by churik** [comment]
@alwx can you rebase it against the last develop?
app keeps crashing after creating account 

https://github.com/status-im/status-mobile/assets/4557972/16c27ec0-b078-49d9-9a7d-f625924f894c

**Comment by alwx** [comment]
The actual feature is implemented in this PR now: https://github.com/status-im/status-go/pull/3889 (because the previous one was reverted)

**Comment by alwx** [comment]
@churik done!

**Comment by churik** [comment]
@alwx 
### ISSUE 1: no unread counter after reopeneing chat view

**Steps:**
1) User A: send CR to User B
2) User A: open chat > tap on back
3) User B: accept CR 
4) User B: send new messages 

**Expected result:**
can see new messages


**Actual result:**

https://github.com/status-im/status-mobile/assets/4557972/8d64513c-e560-420f-ad8a-80d2418b5d19

**OS:** IOS, Android

**Comment by alwx** [comment]
@churik updated the condition to make it work fine in this case. Please, recheck!

**Comment by qoqobolo** [comment]
@alwx Issue 1 is still reproducible, could you recheck, please?


https://github.com/status-im/status-mobile/assets/67952253/6ccb16fa-aae5-4396-b050-a3b1e43c5262

**Comment by flexsurfer** [comment]
hey @alwx what the status of this PR ?

**Comment by alwx** [comment]
@flexsurfer closing it since there are no actual changes — the go counterpart was merged.

**Pull request closed without merging**
