### PR TITLE
[Feature #3616] Add 'Selectable' to a Text component on profile and wallet screens

### LINKED ISSUE #3616: Add 'Selectable' to a Text component on profile and wallet screens
### User Story

As a user, I want to have an opportunity to copy contact codes and wallet address manually.

### Description

*Type*: Feature

Afer a long press, I would like to have an opportunity to copy contact codes and wallet adress through a native platform instrument for iOS and Android. I believe it could be done by adding props `Selectable` to a Text component. Docs: https://facebook.github.io/react-native/docs/text.html#selectable

slice
(pic for iOS, on Android it should show its native instrument)

### Reproduction
All three codes that have to be copyable could be found here:

1. User contact code
- Open Status
- Tap `Profile tab`
- Tap `Share my contact code` button
- See Contact code below QR code

2. Wallet address
- Open Status
- Tap `Wallet tab`
- Tap `Receive transaction` button
- See Wallet address below QR code

3. Friends contact code
- Open Status
- Tap `plus button` on a `Home tab`
- Tap `Start new chat`
- Choose contact ex. Jarrad
- See contact profile and contact code on it 

### Additional Information
* Operating System: Android|iOS

### PR DESCRIPTION
**Pull request by kixi**
fixes #3616 

### Summary:
add selectable to text component on profile and wallet screens

status: ready

### CODE REVIEW

**Review by jeluard — APPROVED** [review]

**Comment by flexsurfer** [comment]
hey @kixi thank you for contribution, is it possible to copy this text?

**Comment by kixi** [comment]
Yes copy works on Android AVD on all 3 screens. On iOS I cannot test, because I don't have an environment yet. Need to buy a Mac ...

**Review by cammellos — APPROVED** [review]

**Review by flexsurfer — APPROVED** [review]

**Comment by annadanchenko** [comment]
@kixi It's possible to copy values for Contact code and Address so it's OK in iOS (iPhone 7 plus, ios 11.0.3) and Android (Galaxy S6, Android 6.0.1). 
However, when long tap on these fields in iOS then there is no selection shown, only "Copy" is shown. So user does not see what's selected: 
10_fb7e2d530c6566841f4b853da0423bec72bf8861_o

On the design, there is selection and Copy. I would expect that text selection is shown.
See video (after 00:40) https://app.testfairy.com/projects/4803590-status/builds/7949991/sessions/4/?accessToken=UkeTixXMtI4-5NRr2sy0uV9fhPA

**Comment by denis-sharypin** [comment]
@kixi Yes, please add selection rectangle as it's on a mockup. Use color for this that we use as button color on the profile page for instance
img_3801

**Comment by kixi** [comment]
Hi, unfortunately I do not have an iOS development right now, so I cannot continue on this issue at the moment. How shall we proceed? Should I withdraw the PR?

**Comment by flexsurfer** [comment]
@kixi let's close it for now, fill free to reopen or file new, thanks for your effort

**Pull request closed without merging**
