### PR TITLE
Enable lightclient

### PR DESCRIPTION
**Pull request by cammellos**
Enable lightclient

### CODE REVIEW

**Review by J-Son89 — APPROVED** [review]
Looks good! @cammellos want me to checkout this branch and test anything?

**Comment by cammellos** [comment]
@J-Son89 thank you, that's ok, it won't be needed, it's only network stuff and the QA will find any issue with it.

**Review by flexsurfer — APPROVED** [review]

**Comment by cammellos** [comment]
The error is:
```
failed to leave community 0x0353b951df5855b2e77a022f983f4b921273e8cfd5fa85f7775f2a7e24ebc7f66f {:code -32000, :message "failed to unsubscribe: no suitable remote peers"}
```
Investigating, definitely due to this PR

**Comment by cammellos** [comment]
> The error is:
> 
> ```
> failed to leave community 0x0353b951df5855b2e77a022f983f4b921273e8cfd5fa85f7775f2a7e24ebc7f66f {:code -32000, :message "failed to unsubscribe: no suitable remote peers"}
> ```
> 
> Investigating, definitely due to this PR

This was due to the fact that we were not passing a flag to go-waku to unsubscribe from all peers, this has been fixed in go-waku by defaulting to that behavior, so that it doesn't have to be explicitly set. Testing the fix.

**Comment by churik** [comment]
### ISSUE 1: can't send/receive messages after going back offline > online (IOS)

**Steps:**
1) IOS: go offline
2) Android: send several messages to IOS
3) IOS: send several messages from offline
4) IOS: get back online and what for messages to be received / re-sent

**Expected result:** the messages will be received/sent within 2 min

**Actual result:** messages were received/sent ~ 10 min

**OS:** IOS 

**Logs:**  [logs_46.zip](https://github.com/status-im/status-mobile/files/11957578/logs_46.zip)

**Comment by churik** [comment]
The messages were not re-sent at all in 15 mins.
logs from sender device: 
[geth_5.log](https://github.com/status-im/status-mobile/files/11960218/geth_5.log)

**Comment by churik** [comment]
@cammellos still messages are not re-sent after coming back online (but fetching immediately)
[logs (47).zip](https://github.com/status-im/status-mobile/files/11966900/logs.47.zip)

https://github.com/status-im/status-mobile/assets/4557972/104ccc3c-7db2-411c-8ca2-69f144b1c38a

**Pull request merged**
