### PR TITLE
[#18962] Add emoji-hash and bio contact profile data

### LINKED ISSUE #18962: Feature: stranger contact profile user info
blocked by 
- #18961

User story

Viewing a Stranger’s Profile
As a user, I want to view a stranger’s profile, so that I can learn more about them and see if I want to connect with them.

- UI in the blue box
- send contact request button points to nothing

Figma https://www.figma.com/file/jGs1P4RU4R1NRrY0xXmHC1/Profile-interactions?type=design&node-id=0-38965&mode=design&t=L27O8eaCfS59gCGl-4

Image

### PR DESCRIPTION
**Pull request by seanstrom**
[comment]: # (Please replace ... with your information. Remove < and >)
[comment]: # (To auto-close issue on merge, please insert the related issue number after # i.e fixes #566)

fixes #18962 

### Summary

[comment]: # (Summarise the problem and how the pull request solves it)

This PR attempts to populate the contact profile with a contact's profile bio and and emoji-hash. ~~And it also adds the initial "Send Contact Request" button as a placeholder for upcoming work~~. Update: I've decided to split some these changes into a separate PR, this PR will focus on adding more profile data, and another PR will focus more on the UI development here #19039.

Note:
* I don't think this can skip **manual-qa** because it modifies the contacts decoder, which could affect other features relying on the contacts data.

#### Platforms

- Android
- iOS

##### Functional

- Feature Flags Contact Profiles
- Existing Contact Profiles
- Contacts

### Steps to test

- Open the Status mobile and desktop app
- Ensure the Status desktop profile as a bio description
- Ensure the profile `new-contact-ui` feature flag is disabled on mobile
- Send a contact request from mobile user to desktop user
- Accept contact request via the desktop app
- Enable the profile `new-contact-ui` feature flag on mobile
- View the Status desktop profile as a contact from the mobile app

### Before screenshot

Screenshot 2024-02-28 at 09 35 23

### After screenshot

Screenshot 2024-02-28 at 15 12 00

status: ready

### CODE REVIEW

**Review by yqrashawn — APPROVED** [review]

**Review by mohsen-ghafouri — APPROVED** [review]

**Comment by seanstrom** [comment]
Hey @status-im/mobile-qa I have a question,
This PR adds more contact data to each contact that could be displayed in the app, but it doesn't change any of the existing UI. Should this PR be manually QA'd because it could affect something in the app?

**Comment by pavloburykh** [comment]
> Hey @status-im/mobile-qa I have a question, This PR adds more contact data to each contact that could be displayed in the app, but it doesn't change any of the existing UI. Should this PR be manually QA'd because it could affect something in the app?

Hey @seanstrom! Let us perform a smoke check to ensure there us no regression.

**Comment by seanstrom** [comment]
@pavloburykh Okay sounds good 👍 thanks for checking this 🙏

**Comment by mariia-skrypnyk** [comment]
Hi @seanstrom !
Thanks for your PR and sorry for the delay.

During my testing of bio part I've noticed some issues:

**ISSUE 1: The only moment User A get "Bio" data of User B is when User B accepts contact request. If User B updates his Bio in the desktop app User A won't have an updated data.**

**Steps:**
***User A** - mobile
  **User B** - desktop

1. Login to mobile app as User A (new-contact-ui flag is OFF)
2. As User B make sure you have text in your Bio field
3. As user A send contact request to User B 
4. Accept contact request as user B
5. As user A turn ON new-contact-ui flag
6. As User A go to Contacts - User B profile
7. As User B change test in your Bio field
8. As User A close re-open User B again

**Actual Result:** No Bio data updated in User's B Profile
**Expected result:** Bio data should be updated if it's updated on the Status Desktop

**ISSUE 2: If user A has User B in a contacts and sees User's B bio then do a logout - no Bio data in User's B Profile**

**Steps:**

1. Login to mobile app as User A (new-contact-ui flag is OFF)
2. As User B make sure you have text in your Bio field
3. As user A send contact request to User B 
4. Accept contact request as user B
5. As user A turn ON new-contact-ui flag
6. As User A go to Contacts - User B profile (sees Bio data)
7. Logout as User A
8. As User A go to Contacts - User B profile 

https://github.com/status-im/status-mobile/assets/147824399/c05afe30-8f7b-49da-8d9a-8d7b536f8d1e


**Actual Result:** No Bio data in User's B Profile
**Expected result:** data should't disappear after relogin

**Comment by seanstrom** [comment]
@mariia-skrypnyk Thanks for finding those issues 🙏 
I think we'll be trying to solve those issues in separate PRs since it seems we need to update status-go.

**Comment by mariia-skrypnyk** [comment]
@seanstrom Sounds like a plan!
I've created followups on issues.
Thanks for your PR, let's merge it in case no design review is required.

**Pull request merged**
