### PR TITLE
Fix mentions animation when disappearing

### PR DESCRIPTION
**Pull request by OmarBasem**
This PR fixes the suggestions list animation not executing when disappearing.

### CODE REVIEW

**Review by ilmotta — APPROVED** [review]

**Comment by ilmotta** [comment]
Unrelated to your PR, but in the same function that you changed, just to let you know in case you can/want to work on it:

https://github.com/status-im/status-mobile/pull/15879/files#diff-5b85161990a87823fb326afac57185ceb1ad8cee035767e03a8f65236b803435L49

There we can see a timer being used without being cleared on unmount.

**Comment by OmarBasem** [comment]
> There we can see a timer being used without being cleared on unmount.

@ilmotta I see a timeout not a timer (interval)

**Comment by ilmotta** [comment]
> > There we can see a timer being used without being cleared on unmount.
> 
> @ilmotta I see a timeout not a timer (interval)

Different terminology I guess. In the Mozilla docs they're considered timers https://developer.mozilla.org/en-US/docs/Web/API/setTimeout. Whether they repeat or not is another detail.

From my point of view the rule is simple: if a timer is registered inside a `useEffect` we should basically always cancel it on unmount (returned function from `useEffect`).

Edit: @OmarBasem

**Comment by OmarBasem** [comment]
Thanks for the info and the reference @ilmotta. I will consider fixing it in another PR.

**Pull request merged**
