### PR TITLE
Editing message UI redesign

### LINKED ISSUE #13726: UI Component - Editing
This issue is to track the creation of the component: Editing

You can access the link at https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Mobile-Components?node-id=4170%3A78081

Please have a chat with the design team before starting with the component, and don't forget to add sizing to the issue

### PR DESCRIPTION
**Pull request by briansztamfater**
fixes #13726 

### Summary

Editing message redesign

#### Platforms

- Android
- iOS

##### Functional

- 1-1 chats
- public chats
- group chats

### Steps to test

- Open Status
- Long tap on an own message
- Select Edit
- Review redesign of the editing component

status: ready

### CODE REVIEW

**Review by ibrkhalil — CHANGES_REQUESTED** [review]
Just revert the podfile changes and all good from my side.

**Comment by briansztamfater** [comment]
Done @ibrkhalil!

**Review by ibrkhalil — APPROVED** [review]
Thanks Brian
lgtm

**Review by flexsurfer — APPROVED** [review]

**Comment by pavloburykh** [comment]
Thanx @briansztamfater! Old UI has been tested for regression, no issues found. Ready for merge.

**Pull request merged**
