### PR TITLE
[#4068] keep existing device UUID when changing account

### PR DESCRIPTION
**Pull request by rasom**
fix for https://github.com/status-im/status-react/issues/4006#issuecomment-388071856

status: ready

### CODE REVIEW

**Review by jeluard — APPROVED** [review]

**Review by goranjovic — APPROVED** [review]

**Review by flexsurfer — APPROVED** [review]

**Review by janherich — APPROVED** [review]

**Comment by lukaszfryc** [comment]
@rasom I don't see any events in Mixpanel using this build. I checked it few times on both Android and iOS. Events appear on latest nightly.  

Could you double check it on your side?

**Comment by rasom** [comment]
@lukaszfryc did you check `Status local`?
screen shot 2018-05-11 at 12 04 00

**Comment by lukaszfryc** [comment]
oh, no. Let me check it

**Comment by lukaszfryc** [comment]
@rasom I don't see Distinct ID when I log out and created a new account:

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/LPXyds for branch PR-4210

<blockquote><div><strong><a href="https://i.diawi.com/LPXyds">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/s6rgju for branch PR-4210

<blockquote><div><strong><a href="https://i.diawi.com/s6rgju">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/yd8yR6 for branch PR-4210

<blockquote><div><strong><a href="https://i.diawi.com/yd8yR6">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/7NBc2B for branch PR-4210

<blockquote><div><strong><a href="https://i.diawi.com/7NBc2B">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by lukaszfryc** [comment]
@rasom works 👍 

I tested Android and iOS.

**Comment by jeluard** [comment]
@rasom Can you squash your commits?

**Pull request merged**
