### PR TITLE
[Fixes: #12596] Fix timeline messages

### PR DESCRIPTION
**Pull request by cammellos**

### CODE REVIEW

**Review by flexsurfer — APPROVED** [review]

**Comment by churik** [comment]
@cammellos 
don't know particular reason, but on this PR build and on https://github.com/status-im/status-react/pull/12605 collectibles on mainnet are not shown after enabling.
All fine on nightly 21/09/21
IMAGE 2021-09-21 16:54:09

**Comment by qoqobolo** [comment]
@cammellos thanks for the fix! Timeline messages work fine now.
But [this issue above](https://github.com/status-im/status-react/pull/12608#issuecomment-924068385) from @churik is only reproducible on PR build.
Take a look when you have time, please

**Comment by cammellos** [comment]
mmh, I don't think is my change, is it possible that is this change https://github.com/status-im/status-go/commit/a6e7ff6ddde4819c091a2cd73899214df9c12b58 (not on develop in status-react, but already in status-go) @shivekkhurana any idea?

**Comment by churik** [comment]
likely yes, as it also reproducible on https://github.com/status-im/status-react/pull/12605

**Comment by churik** [comment]
So, as it is not reproducible in https://github.com/status-im/status-react/pull/12615 not sure how to proceed with that - for you to decide @cammellos

**Pull request merged**
