### PR TITLE
testing cud mode with test DNS record

### PR DESCRIPTION
**Pull request by jakubgs**
This is only for testing purposes, no need for reviews, __DO NOT MERGE__.

### CODE REVIEW

**Comment by mandrigin** [comment]
@annadanchenko I'll rebase it, give me 1 minute

**Comment by annadanchenko** [comment]
testing is done 
1. when dns entry is on and staging cluster is off: User gets popup with a unicorns and link to details only once when chaos mode is turned on.After this can't sent transaction (500 error), can't see history of transactions, can't see usd value in wallet/chat, can't get chat history but can send messages. Unfortunately, whisper nodes are re-used from other fleets, so peers were available. Can add custom bootnode and mailserver after this can get history (used QRs from https://gist.github.com/jacqueswww/3ddfc5ecfa09ecea702744ab15a2200d ). 
2.  when dns entry is switched off and when staging cluster is back: Tx and messages can be sent without restarting app. Chaos mode is switched off automatically

**Comment by jakubgs** [comment]
Wait, shouldn't the changes done by @mandrigin and @cammellos be merged? Or were those just for tests?

**Comment by annadanchenko** [comment]
> Wait, shouldn't the changes done by @mandrigin and @cammellos be merged? Or were those just for tests?

there was separate pr from @cammellos that is merged: https://github.com/status-im/status-react/pull/7839

**Comment by jakubgs** [comment]
Cool.

**Pull request closed without merging**
