### PR TITLE
stop showing notifications for muted chats

### LINKED ISSUE #12890: Add mute option to android
As an android user 
I want to be able to mute a chat
So that I won't receive notifications from it

### Description

We should allow users to mute a contact in the same way we do on IOS for Android.
If a contact is muted that way, we should not show notifications when receiving a message from them.

### Technical details

Most of the changes are in status-go, there's already an endpoint that we use to mute chats/contacts, we just need to enable the UI in status-react and make sure that we don't show notifications for muted contacts, that's done in status-go.

### PR DESCRIPTION
**Pull request by jo-mut**
Fixes https://github.com/status-im/status-react/issues/12890

### Summary
When a user mutes a particular one on one chat, the user will not receive notifications for new chat messages

### Testing notes
Mute a chat between your User (A) and User B
Send a message to User B from User A
Notice that User B does not receive notifications for new chat messages
Unmute User B from User A
Notice that user B now receives notifications for new chat messages

### Summary

[comment]: # (Summarise the problem and how the pull request solves it)
...

Documentation change PR (review please): https://github.com/status-im/status.im/pull/xxx

#### Platforms

- Android
- iOS
- macOS
- Linux
- Windows

##### Functional

- 1-1 chats
- public chats
- group chats
- wallet / transactions
- dapps / app browsing
- account recovery
- new account
- user profile updates
- networks
- mailservers
- fleet
- bootnodes

##### Non-functional

- battery performance
- CPU performance / speed of the app
- network consumption

### Steps to test

- Open Status
- ...
- Step 3, etc.

status: ready

### CODE REVIEW

**Review by rasom — APPROVED** [review]

**Comment by qoqobolo** [comment]
@jo-mut thanks for your work! I have a question regarding PNs on mentions in public chats.

Currently, I can still receive PNs from a muted user on mentions in public chat with _local push notifications_ enabled (with remote notifications - no PN).
Could you clarify, please, is it expected?

**Steps to reproduce:**
1. UserA (Android): start 1-1 chat with UserB, mute them
2. UserA: enable local push notifications (background service), join a public chat, send a message, send the app to the background
3. UserB: join the same public chat, mention UserA
4. UserA: check notifications

**Expected result:** no PN, as UserB is muted
**Actual result:** PN received

However, probably this feature is only relevant for remote notifications, so need your clarification here.
Thanks!

**Comment by jo-mut** [comment]
Hi @qoqobolo. Regarding PNs on mentions in public chats I think its good to open another issue to address that. As it is that is the expected behaviour on this PR

**Comment by jo-mut** [comment]
@qoqobolo just wanted to let you know i have created a new issue to address push notifications on public chat mentions as you had pin pointed above. 

thanks

**Comment by qoqobolo** [comment]
> @qoqobolo just wanted to let you know i have created a new issue to address push notifications on public chat mentions as you had pin pointed above.

Cool, thanks very much! Added a comment about PNs on group chat messages as it's relevant for them too.

Also, PR is tested and can be merged.
Thank you @jo-mut!

**Comment by qoqobolo** [comment]
> @qoqobolo just wanted to let you know i have created a new issue to address push notifications on public chat mentions as you had pin pointed above.

Cool, thanks very much! Added a comment about PNs on group chat messages as it's relevant for them too.

Also, PR is tested and can be merged.
Thank you @jo-mut!

**Comment by jo-mut** [comment]
> > @qoqobolo just wanted to let you know i have created a new issue to address push notifications on public chat mentions as you had pin pointed above.
> 
> Cool, thanks very much! Added a comment about PNs on group chat messages as it's relevant for them too.
> 
> Also, PR is tested and can be merged. Thank you @jo-mut!

thank you too @qoqobolo

**Comment by jo-mut** [comment]
@qoqobolo I would like to merge this as its fine

**Comment by qoqobolo** [comment]
@jo-mut yes, you can merge a PR once it is moved to the `MERGE` column and given the `Tested - OK` label (this was done 2 days ago).

**Comment by jo-mut** [comment]
cool

**Pull request merged**
