### PR TITLE
Update translation for 1.20

### LINKED ISSUE #13272: Update Fastlane names and summaries as per fdroid requirement
# Problem

The names and summaries currently we are using for Fastlane have more characters than the allowed limit.
**Original Error Report:** https://gitlab.com/fdroid/fdroiddata/-/merge_requests/10879#note_906129831

> `summary` in `de-DE` should be shorter than 80 characters!  
> `name` in `es-419` should be shorter than 50 characters!  
> `summary` in `es-419` should be shorter than 80 characters!  
> `name` in `es-AR` should be shorter than 50 characters!  
> `summary` in `es-AR` should be shorter than 80 characters!  
> `name` in `es-ES` should be shorter than 50 characters!  
> `summary` in `es-ES` should be shorter than 80 characters!  
> `name` in `fil` should be shorter than 50 characters!  
> `name` in `fr-FR` should be shorter than 50 characters!  
> `summary` in `fr-FR` should be shorter than 80 characters!  
> `name` in `it-IT` should be shorter than 50 characters!  
> `summary` in `it-IT` should be shorter than 80 characters!  
> `name` in `pt-BR` should be shorter than 50 characters!  
> `summary` in `ru-RU` should be shorter than 80 characters!  
> `name` in `tr-TR` should be shorter than 50 characters!  
> `name` in `uk` should be shorter than 50 characters!  
> `summary` in `uk` should be shorter than 80 characters!

### PR DESCRIPTION
**Pull request by jinhojang6**
Updated

- ja : Japanese
- hi: Hindi
- zh: Simplified Chinese
- zh_TW: Traditional Chinese
- ru: Russian

fixes: #13272

### CODE REVIEW

**Comment by Parveshdhull** [comment]
Hi @jinhojang6, Please also checkout https://github.com/status-im/status-mobile/issues/13272
We also need to update translations for fdroid, as length of current translations is more than the allowed value.

**Comment by jinhojang6** [comment]
@Parveshdhull Can you please let me know a list of languages that need to be shorter?

**Comment by Parveshdhull** [comment]
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/10879#note_906129831

```
summary in de-DE should be shorter than 80 characters!
summary in es-419 should be shorter than 80 characters!
name in es-419 should be shorter than 50 characters!
summary in es-AR should be shorter than 80 characters!
name in es-AR should be shorter than 50 characters!
summary in es-ES should be shorter than 80 characters!
name in es-ES should be shorter than 50 characters!
name in fil should be shorter than 50 characters!
summary in fr-FR should be shorter than 80 characters!
name in fr-FR should be shorter than 50 characters!
summary in it-IT should be shorter than 80 characters!
name in it-IT should be shorter than 50 characters!
name in pt-BR should be shorter than 50 characters!
summary in ru-RU should be shorter than 80 characters!
name in tr-TR should be shorter than 50 characters!
summary in uk should be shorter than 80 characters!
name in uk should be shorter than 50 characters!
```

**Comment by jinhojang6** [comment]
It's gonna take som time to update all the languages. Let's use the English title and description until our ambassadors help make it shorter

**Review by flexsurfer — APPROVED** [review]

**Comment by churik** [comment]
@jinhojang6 any updates on this or should I merge it as it is?

**Comment by jinhojang6** [comment]
Sorry for the late reply. I didn't receive a notification for some reason. It is okay to merge this PR as it is. @churik

**Pull request merged**
