### PR TITLE
[#14728] Fix sender avatar in reply

### LINKED ISSUE #14728: Sender's image icon is not displayed in reply message
**Steps:**

1. Open any chat
2. Send a message
3. Send reply to that message
4. See if sender's image icon is displayed in the reply

**Actual result:** sender's image icon is not displayed in reply message

**Expected result:** sender's image icon is displayed in reply message

photo_2023-01-09 10 58 00

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by rasom**
fix #14728

status: ready

### CODE REVIEW

**Review by Parveshdhull — APPROVED** [review]

**Review by J-Son89 — APPROVED** [review]

**Review by ilmotta — APPROVED** [review]

**Comment by pavloburykh** [comment]
@rasom thanx for the PR. LGTM. 
Before checking this PR I also checked latest nightly to make sure that issue https://github.com/status-im/status-mobile/issues/14728 still exists and turned out that bug is not reproducible there anymore. Probably the bug has been fixed by some other PR which has been merged into develop.
@rasom  Based on this, should we still merge this PR or it doesn't make sense anymore, WDYT?

**Comment by rasom** [comment]
@pavloburykh that's interesting, because it was reproducible yesterday. I will take a look before merging

**Comment by rasom** [comment]
@pavloburykh I still can reproduce this in `develop` (last message), thus merging 

Screenshot 2023-01-24 at 14 30 50

**Comment by pavloburykh** [comment]
> @pavloburykh I still can reproduce this in `develop` (last message), thus merging

Thanx @rasom. When I tried to replicate this morning - profile icon displayed for me in reply (in case if profile image has not been added yet). But I have re-checked once again - and now I also reproducing the bug. Thanx for fixing and merging.

**Pull request merged**
