### PR TITLE
feature #3916 - added a few ropsten erc20 tokens, rearranged icon res…

### LINKED ISSUE #3916: Add test tokens under Ropsten so i can send and receive them
### Description

*Type*: Feature

*Summary*: To make Status more interactable i want to add some more test tokens user can play with so STT not is the only one in the list

#### Expected behavior
1. Several tokens are added to the assets list : HND, LXS, ADI, WGN, MDS (use any abbreviations as those will be test tokens created on our own)
2. I can claim for above mentioned tokens using faucet or sending 0 txn to specific smart contract (please list them in PR when fixing the issue)
3. I can receive the tokens from wallet
4  I can send the tokens from wallet
5. Tokens have nice pics (any) that look nice and attractive

#### Actual behavior
only STT is present in the list which is boring

### Additional Information
* Status version: develop
* Operating System: Android|iOS

### PR DESCRIPTION
**Pull request by goranjovic**
fixes #3916

### Summary:

Adds a bunch of test tokens on Ropsten network:

```
HND
Handy Test Token
0x9e47fb3049f0d9c953f5428ce2e6c3a8321780bf

LXS
Lucky XS Test
0xf29d2dc0687d7d49f57d4a731ac8bfb6edc23473

ADI
Adi Test Token
0xd2a816110c1177478c7e644ae4853d8e80aaec35

WGN
Wagner Test Token
0x65c69bc258afa0906683f42e576b272a95c203dd

MDS
Modest Test Token
0x972b0570d9cd8b7c41aa8349f707ec7356daa825
```

User can get 1000 of each of those by sending exactly 0 ether to the appropriate contract address.

## Review notes

This PR also rearranges token assets to clearly separate test assets from any mainnet ones and thus avoid the confusion.

### Steps to test:
- Open Status
- Check if mainnet assets still look ok
- Switch to Ropsten and try out these

status: ready

### CODE REVIEW

**Comment by goranjovic** [comment]
screenshot-2018-04-18_13 55 01 485
screenshot-2018-04-18_13 57 12 657

**Review by asemiankevich — APPROVED** [review]

**Comment by asemiankevich** [comment]
@goranjovic please add some hints how to claim for each one

**Comment by goranjovic** [comment]
@asemiankevich Just send 0 ether to its address. They are all listed above. And don't forget to increase 
gas limit a bit, same as with STT.

I'd rather not add any in-app hints or anything like that because claiming those is specific to these tokens
and generally not something you'll find on mainnet. Not for free anyway :)

**Comment by flexsurfer** [comment]
@goranjovic why so much new png files?

**Comment by goranjovic** [comment]
@flexsurfer Not many new ones, just moved the existing ones to a subdirectory for mainnet.

**Review by flexsurfer — APPROVED** [review]

**Review by jeluard — APPROVED** [review]

**Pull request merged**
