### PR TITLE
Chore: update icons for android

### LINKED ISSUE #21110: Update Status' icons for release 2.30
# Feature Issue

### Description

We need to update Status' icons for release 2.30. Please, reach out to @Francesca-G, @pedro-et, or @xAlisher to obtain assets. Example PR from many years ago, might be useful https://github.com/status-im/status-mobile/pull/4524/files

* Here's [the updated designs for Android icons](https://www.figma.com/design/gZss5EzKuqdcSXOlqrQZoZ/Logo?node-id=590-153)
* And here's [the updated design for iOS icons](https://www.figma.com/design/gZss5EzKuqdcSXOlqrQZoZ/Logo?node-id=589-19)

### Notes

Files to change are found in directories:

- `ios/StatusIm/Images.xcassets/`
- `android/app/src/main/res/`

### Acceptance criteria

- Double-check installed builds are using the new icon for both Android and iOS.
- With all images correctly included in `ios/StatusIm/Images.xcassets/AppIcon.appiconset`, the correct icon should be detected in App Store Connect when we upload a build.
- We can ignore icons for PR and debug builds and focus only on those that will be used for the release build.

### PR DESCRIPTION
**Pull request by seanstrom**
partially fixes #21110 

### Summary

* This PR attempts to update the icon assets for the Android app
  * I've tried to migrate any existing assets to the new designs, however there were some slight mismatches, so I removed some assets that seem unrelated (old launch_screens assets).
  * There's also a good chance that we don't need to define so many variations of `drawable-` folders for the foreground and background assets since we're now using SVG. But I haven't been able to confirm if this is true yet.
  * I've also included/kept assets for the rounded icon look, but these may also be unnecessary. I've also adjusted the Android manifest to look for rounded icons.
  * There's a chance that the app may have grown a bit more in size because of the asset sizes, so I've tried compressing the assets. But we may still need to remove if we find that they're not needed anymore.

#### Platforms

- Android

##### Non-functional

- App icons
- Splash screen

status: ready

### CODE REVIEW

**Comment by mariia-skrypnyk** [comment]
@ilmotta can you please review this PR and I will test it.

**Comment by ilmotta** [comment]
> @ilmotta can you please review this PR and I will test it.

Hey @mariia-skrypnyk, it's still under development due to some issues with SVGs. When @seanstrom gives the green light I will review.

**Comment by xAlisher** [comment]
Let me know if I can help with SVG

**Review by ilmotta — APPROVED** [review]
@seanstrom icons look good. The only issues I found happen when _themed icons_ is enabled (a beta feature on Android), but I think we can flag this problem in a separate low-priority issue and not block the release.

**Inner part of the logo is too large** The other icons don't expand as much to the edges of the icon circle. Only happens if _themed icons_ are enabled.



**PR logo would arguably look better without the surrounding green "border"**.

**Comment by xAlisher** [comment]
@ilmotta @seanstrom This looks strange because their own template displays the standard size for the themed icon.

image
https://www.figma.com/design/gZss5EzKuqdcSXOlqrQZoZ/Logo?node-id=590-488&t=KOW7TgBXGS9vUnfk-1

Can we try making it a bit smaller and see if it affects pre-adaptive icons? Alternatively, should we keep a separate size for this specific case?

CC @pedro-et

**Comment by seanstrom** [comment]
@xAlisher @ilmotta I've pushed up some changes to those icons. I've tried to make the themeable (monochrome) icon match the regular icon in proportions.

Screenshot 2024-08-23 at 09 49 11

**Comment by mariia-skrypnyk** [comment]
@seanstrom @ilmotta   is it ready to test?

**Comment by mariia-skrypnyk** [comment]
@seanstrom icon is still too big. Not only my result, checked also by @pavloburykh .

Screenshot 2024-08-23 at 14 31 22

**Comment by xAlisher** [comment]
@seanstrom Just a bit smaller to match the design please 🙏

**Comment by seanstrom** [comment]
Okay I've tried making the icons a good amount smaller, and making sure the themeable icons also match.

Screenshot 2024-08-23 at 16 28 27

Screenshot 2024-08-23 at 16 29 54

cc @mariia-skrypnyk @xAlisher @ilmotta

**Comment by ilmotta** [comment]
@mariia-skrypnyk @xAlisher The icons look better with and without themed icons in my tests, but you have the final word.

In my opinion, the previous blue icon size had the perfect proportion of background and foreground, but for the sake of this release I think we shouldn't worry anymore about striking perfection because we can make more size adjustments in the follow-up release.

Thank you @seanstrom, you did great work taming the Android beast!

**Comment by mariia-skrypnyk** [comment]
Hey @seanstrom @ilmotta @xAlisher .

As for me app logo looks good!

Now vs Before

Screenshot 2024-08-24 at 17 44 42
Screenshot 2024-08-24 at 17 44 48

Push Notifications logo looks just orange:

Screenshot 2024-08-24 at 17 45 02

And Notificaions logo in the tray looks blue:

Screenshot 2024-08-24 at 17 45 18

So the main fix of this PR is done and from my perspective nothing blocking from merge.

**Comment by xAlisher** [comment]
I agree with @ilmotta. Thanks, @seanstrom, for the amazing work! 🙏💪

I hope @pedro-et is also okay with what we have for this release. For the next release, I would prefer to have only the white shape without a white background in both notification cases.

cc @Francesca-G

**Pull request merged**
