### PR TITLE
[#5649] Change react-native-i18n language files to json

### LINKED ISSUE #5649: Change react-native-i18n language files to js
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a developer, I want react-native-i18n language files in js so that I can integrate with Lokalise

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Improvement

[Lokalise](https://lokalise.co) is a leading platform to manage translations for apps and websites with a git-based integrated and open workflow.  They support react-native-i18n out of the box, but only with js language files.  If we converted our [files from cljs to js](https://github.com/status-im/status-react/blob/develop/src/status_im/translations/en.cljs) we can easily integrate with the Lokalise service. [See these docs for more info](https://docs.lokalise.co/supported-file-formats/react-native-i18n-js).

This issue is a good contender as it unblocks other team members and workflows to ensure that Status is available in other languages.

#### Expected behavior
[en.cljs](https://github.com/status-im/status-react/blob/develop/src/status_im/translations/en.cljs) converted to en.js (and other language files)

### PR DESCRIPTION
**Pull request by rasom**
fix #5649 

1. the first commit contrains only JSON files with translation copied from cljs files
2. the second contains code which reads JSON translations
3. the last removes all cljs translations

notes for `Lokalise`:

1) by default `Lokalise` ignores `"zero"` plural option. so in order to make it work the next actions should be applied for each language:
 
### **Go to language settings, turn on `Custom plural form`, select `zero`. Only after this resources for this particular language should be imported to Lokalise (otherwise zero will not be recognized)**
screen shot 2018-09-09 at 19 59 57

2) when configure GitHub integrations we have to select `Web` as a platform, otherwise `Lokalise` will not file github PRs on export
screen shot 2018-09-09 at 09 08 55

status: ready

### CODE REVIEW

**Comment by chadyj** [comment]
Some info on the format required for Lokalize https://docs.lokalise.co/supported-file-formats/react-native-i18n-js

<blockquote><div><strong><a href="https://docs.lokalise.co/supported-file-formats/react-native-i18n-js">React Native (i18n, .js)</a></strong></div></blockquote>

**Review by flexsurfer — APPROVED** [review]

**Review by chadyj — APPROVED** [review]
I tested the files and flow in lokalise and it all worked.

**Review by janherich — APPROVED** [review]

**Review by yenda — APPROVED** [review]

**Comment by lukaszfryc** [comment]
@rasom @chadyj should the app language change to German or others when I change language of my phone? It does not work now and I am wondering if it has worked before :) 
I tested 0.9.27 and it does not work there either.

**Comment by rasom** [comment]
@lukaszfryc right now it's only Korean and Russin (because @chadyj mentioned that we want to experiment with those languages) except English. Translations are not ready yet, so no. I can change this if necessary  
https://github.com/status-im/status-react/pull/5780/commits/0d8db9283b43436c134ad83dcba259f7d01b327d#diff-640fd584c0f806e87bf9fbded11fef3bR16

**Comment by rasom** [comment]
@lukaszfryc it doesn't work in develop https://github.com/status-im/status-react/blob/develop/src/status_im/i18n.cljs#L126

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/status-im/status-react">status-im/status-react</a></strong></div><div>a free (libre) open source, mobile OS for Ethereum - status-im/status-react</div></blockquote>

**Comment by lukaszfryc** [comment]
@rasom then I think there is nothing else I should test here. Can we re-enable other languages in a separate PR https://github.com/status-im/status-react/blob/develop/src/status_im/i18n.cljs#L126?

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/status-im/status-react">status-im/status-react</a></strong></div><div>a free (libre) open source, mobile OS for Ethereum - status-im/status-react</div></blockquote>

**Comment by rasom** [comment]
yes, if necessary, let's discuss in #localization

**Pull request merged**
