### PR TITLE
Tech debt/kebab case

### LINKED ISSUE #3139: Migrate hiccup properties to kebab-case
### User Story

As a developer, I want to follow good coding convention

### Description

*Type*: Feature

`reagent` allows to define component properties in `kebab-case` (e.g. `:background-color`). Make sure all existing `camel-case` usages (e.g. `:backgroundColor`) are migrated to `kebab-case`.

### PR DESCRIPTION
**Pull request by rcullito**
Fixes #3139

### Summary:
migrates remaining reagent properties from `camelCase` to `kebab-case`

status: ready (as far as I can tell, this is my first contribution)

### CODE REVIEW

**Review by jeluard — COMMENTED** [review]
Looks great! Please make sure map values alignment is not broken due to key changes.

**Review by yenda — APPROVED** [review]
Same here good but please fix alignements

**Comment by rcullito** [comment]
thank you both for the review! the map alignments were addressed in the most recent commit.

**Comment by yenda** [comment]
@rcullito, Great thanks, please squash the commits into one so we can merge it
@jeluard does it need to go to QA ?

**Comment by jeluard** [comment]
@yenda Probably a quick QA yes to be on the safe side

**Comment by rcullito** [comment]
@yenda sure thing! just squashed them into one commit 👍

**Review by jeluard — APPROVED** [review]

**Comment by rcullito** [comment]
@jeluard what next steps do you suggest I take for this? In resolving merge conflicts I wasn't able to follow the link to the jenkins output, so was unsure whether it was on me or QA to follow up on the android selenium tests? thanks! 🙏

**Comment by yenda** [comment]
@rcullito Hi, you need to do a rebase not a merge.

```
git revert a249d828bd8aad2dde71ad3f2e64992966a90038
git pull --rebase origin develop
```

then you deal with the merge conflicts during rebase and you'll have a clean commit on top of develop

**Comment by rcullito** [comment]
thanks for the suggestion @yenda. I had originally resolved it right from the github editor on the PR itself but have since rebased instead. 🌤

**Comment by rcullito** [comment]
Hi @yenda, are there any other changes you guys need to see from your end on this before it goes to QA?

**Comment by yenda** [comment]
@rcullito no it is already in QA just needs to be picked up by a testee

**Comment by rcullito** [comment]
@yenda sweet, thanks for the heads up.

**Comment by rcullito** [comment]
@yenda sorry I know asked a similar question previously, but is there any other flag or label I should put on this to avoid having to rebase every few days to keep this out of conflict with develop while it awaits a merge? thanks!

**Comment by asemiankevich** [comment]
sanity tested this and looks good

**Comment by asemiankevich** [comment]
@yenda @jeluard can we revert it back? seems this commit is reason of 
image

**Comment by asemiankevich** [comment]
I retested it again and seems I am wrong - this PR does not have mentioned issue. No need to revert. Sorry for confusion

**Pull request merged**
