### PR TITLE
fix: add min 5 characters validation for display names

### LINKED ISSUE #15540: Add min 5 characters validation for display names
cc @cammellos 

**Problem:** 

Currently it is possible to set display name with 1 character on mobile during onboarding

photo_2023-03-30 21 49 10

Such display names are subsequently not validated by backend which causes different issues including users will not see messages from owners of such display names as happened here https://github.com/status-im/status-mobile/issues/14797#issuecomment-1490575410

We need to add min 5 characters validation for display names in order it to be aligned with validation rules on backend. 

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by briansztamfater**
fixes #15540 

### Summary

Add minimum character validation on profile name. Error message was not validated with design team but I suppose we can change it later if necessary.

 

#### Platforms

- Android
- iOS

##### Functional

- onboarding
- message reliability impact

### Steps to test

- Open Status
- Create new account
- Type profile name
- Verify user can't continue profile creation if enters a name of less than 5 characters

status: ready

### CODE REVIEW

**Review by ibrkhalil — APPROVED** [review]

**Comment by VolodLytvynenko** [comment]
Hi, @briansztamfater thank you for the fixes. The validation looks well. Unfortunately, some additional issue is present where some additional validation should be implemented.

## ISSUE 1: The messages are not delivered for receiver user If sender user name contains at least one dot or spaces at the beginning and at the end
**Steps to reproduce:**
1. Set up the display name with 'dot' for User_A. (example: `Mr.Sherlock` or  `  SOS  `)
2. Send CR as User_B to User_A -> Accept CR
3. User_A: Open 1-1 chat
4. User_A: Send the message
5. User_B: Check the message

#### Actual result:
The message is not shown for User_B 


#### Expected result
Potential solutions:
- 'Special characters are not allowed' validation is shown if dot is specified during display name set up
- The spaces are ignored if they are typed at the beginning and at the end for 'display name'. So, if the user types '` Vov `', then 'Name must have at least 5 characters' validation message is shown

#### Additional info
- The issue with spaces is reproducible only if the name consists of 5 characters (example:`  SOS  ` ). 
- For cases, if the name is more than 5 characters  or if space is somewhere in the middle, then it works well and the messages are received successfully (Example: `Sh Sh` or  `  Sherlock `)


**Logs:**
logcat: [Untitled document.txt](https://github.com/status-im/status-mobile/files/11122961/Untitled.document.txt)
geth.log: https://www.dropbox.com/s/w1jarzztf14nxek/geth.log?dl=0
[Status.log](https://github.com/status-im/status-mobile/files/11122981/Status.log)

**Comment by cammellos** [comment]
@briansztamfater the validation regex for the username is:

```
	if match, _ := regexp.MatchString("^[\\w-\\s]{5,24}$", name); !match {
		return ErrInvalidDisplayNameRegExp
	}
```

and should not have _eth .eth or -eth suffix

**Comment by VolodLytvynenko** [comment]
Hi @cammellos maybe we should consider changing validation on beck-end side in the future. 5 chars limit is very strict I guess. There are popular names such as Jo or Ben or Anna

**Comment by briansztamfater** [comment]
@VladimrLitvinenko thanks for testing, I've added trimming and extra validation with regex @cammellos provided, let me know if that works

**Comment by briansztamfater** [comment]
I think it is good to have validation on the client side for a better UX, but we should add validation also on status-go side for consistency between clients and avoid issues that may affect messages like this one

**Comment by VladimrLitvinenko** [comment]
Hi, @briansztamfater could you rebase this PR, please?

**Comment by VolodLytvynenko** [comment]
hi, @briansztamfater thank you for your work. Issue 1 is fixed.  PR is ready to be merged

**Comment by J-Son89** [comment]
> I think it is good to have validation on the client side for a better UX, but we should add validation also on status-go side for consistency between clients and avoid issues that may affect messages like this one

it's possible to get the validation rules from Status-Go to use on the frontend? 🤔

**Comment by briansztamfater** [comment]
> > I think it is good to have validation on the client side for a better UX, but we should add validation also on status-go side for consistency between clients and avoid issues that may affect messages like this one
> 
> it's possible to get the validation rules from Status-Go to use on the frontend? 🤔

I think it is totally possible, we should discuss the approach, and maybe have the desktop team input

**Pull request merged**
