### PR TITLE
fix libgnustl_shared.so is 32 bit instead of 64-bit

### LINKED ISSUE #4478: Error libgnustl_shared.so is 32 bit instead of 64-bit (android)
### Description

*Type*: Bug

*Summary*: `libgnustl_shared.so is 32 bit instead of 64-bit`

#### Expected behavior
no errors when launching status

#### Actual behavior
image

### Reproduction
- Open Status with latest nightly on Android

### Additional info
- Huawei P10 lite android 7
- Google Pixel XL android 8

### PR DESCRIPTION
**Pull request by rasom**
fixes #4478
status: ready

### CODE REVIEW

**Review by yenda — APPROVED** [review]

**Review by flexsurfer — APPROVED** [review]

**Review by mandrigin — APPROVED** [review]

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/6zpafF for branch PR-4479

<blockquote><div><strong><a href="https://i.diawi.com/6zpafF">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Review by janherich — APPROVED** [review]

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/kmuJSA for branch PR-4479

<blockquote><div><strong><a href="https://i.diawi.com/kmuJSA">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Review by yenda — COMMENTED** [review]
Deleted comment

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/s1juCi for branch PR-4479

<blockquote><div><strong><a href="https://i.diawi.com/s1juCi">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/m6adjG for branch PR-4479

<blockquote><div><strong><a href="https://i.diawi.com/m6adjG">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Pull request merged**
