### PR TITLE
[15128-followup]

### PR DESCRIPTION
**Pull request by ibrkhalil**
fixes #15128 followup
status: ready

### CODE REVIEW

**Review by flexsurfer — APPROVED** [review]
thanks!

**Comment by pavloburykh** [comment]
@ibrkhalil hello! Does this PR fix only @flexsurfer review comments or also these issues https://github.com/status-im/status-mobile/pull/15128#issuecomment-1601064999 ?

**Comment by flexsurfer** [comment]
@ibrkhalil it's still better to wait for e2e before merge

**Comment by ibrkhalil** [comment]
> @ibrkhalil hello! Does this PR fix only @flexsurfer review comments or also these issues https://github.com/status-im/status-mobile/pull/15128#issuecomment-1601064999 ?

Only review comments, To make code match our standards better.

I'll do the other fixes asap.

**Pull request merged**
