### PR TITLE
[#11760] Allow copying and pasting of images in chat's input

### PR DESCRIPTION
**Pull request by MalcolmTomisin**
Feature implementation for #11760 

### Summary

[comment]: # (Summarise the problem and how the pull request solves it)
...

### Review notes

- A native module to accomplish the feature was written in java(android) in addition to react-native-clipboard's(formerly react-native-community/clipboard) ios paste image features, these functions pass images from the clipboard as base64 strings.
- implementations/styles of the text input are still quite unclear to me so these base64 strings aren't being passed to any functions or components, I have reached out to @cammellos concerning this, hopefully I get a response soon
- a context menu component is wrapped around text-input to provide the text-input options to "paste" image which is quite different from native tooltips/context-menus. Although this custom context-menu is fired on long press of component. Plugging in to native events from actions on native tooltips is still quite unclear on respective iOS and android platforms. Looks like [extending ReactNative's native implementations of the these components is the only way to go to achieve pasting from native tooltips/context-menu. Here's a npm package that successfully extended native implementations to create native tooltips and context menus](https://github.com/Astrocoders/react-native-selectable-text) ,e.g. I tried implementing a subclass for React Native's ReactTextInputManager.java, I was able to implement native context menus but couldn't get the text input view to focus on interactions. There's a [stackoverflow question](https://stackoverflow.com/questions/68794869/how-to-maintain-focus-in-custom-textinput-component-in-react-native-android) I opened concerning that. 
- code written by a newbie to clojure 🙂🙂🙂

#### Platforms

- Android
- iOS

##### Functional

- 1-1 chats
- public chats
- group chats

### Steps to test

- Copy photo to clipboard 
- Open Status
- Proceed to initiate chat
- Long press on text input and press "paste" button on context menu
- base64 string logged on metro console

status: wip

### CODE REVIEW

**Comment by cammellos** [comment]
Hi @MalcolmTomisin ,
> implementations/styles of the text input are still quite unclear to me so these base64 strings aren't being passed to any functions or components, I have reached out to @cammellos concerning this, hopefully I get a response soon

Do you still need help with this? 
I have also rebased and pushed a fix to yarn.lock that was not generated.
Sorry for the delay on this one, I was on holiday and it slipped under my radar.

**Comment by MalcolmTomisin** [comment]
Hi @cammellos , I would appreciate understanding how image additions to a chat are implemented currently so that I can plug in to the component and pass the base64 strings to the image component. There's an image gallery that pops up when the image icon in the text input is clicked, clicking an image passes the image to a view styled with a black background. This section is what I don't fully understand.

**Comment by MalcolmTomisin** [comment]
Hi @cammellos , I would appreciate understanding how image additions to a chat are implemented currently so that I can plug in to the component and pass the base64 strings to the image component. There's an image gallery that pops up when the image icon in the text input is clicked, clicking an image passes the image to a view styled with a black background. This section is what I don't fully understand.

**Comment by MalcolmTomisin** [comment]
Hi @cammellos, I would appreciate understanding how image additions to a chat are implemented currently so that I can plug in to the component and pass the base64 strings to the image component. There's an image gallery that pops up when the image icon in the text input is clicked, clicking an image passes the image to a view styled with a black background. This section is what I don't fully understand.

**Pull request closed without merging**
