### PR TITLE
Added ATT for easy testing on Ropsten

### LINKED ISSUE #3869: Add ATT tokens support in Status
### Description

*Type*: Bug

*Summary*: as we discussed with @andytudhope and @jeluard , Andy will be able to add ATT tokens support so we can exchange the tokens in Status app

#### Expected behavior
I can exchange ATT tokens in Status under Ropsten testnet

#### Actual behavior
no ATT support now

### Additional Information
* Status version: nightly
* Operating System: Android, iOS

### PR DESCRIPTION
**Pull request by andytudhope**
Fixes #3869 

### Summary:

This PR changes the address for ATT, which I redeployed with some additional logic that will send 1000 ATT to anyone who sends a 0 ETH txn to the contract address, which is:

0x00a8e52df8f4f1f4b67bded9ae6090b35489a973

I also added Aragon logos to make it look purrrty.

### Steps to test:

- Open Status
- Ensure you are on Ropsten
- Navigate to the wallet, see if you can see the ATT address and send a 0 ETH txn to it.
- Make sure your balance of ATT increases by 1000.

status: ready

### CODE REVIEW

**Review by goranjovic — APPROVED** [review]

**Review by asemiankevich — APPROVED** [review]

**Review by rasom — APPROVED** [review]

**Comment by andytudhope** [comment]
Verified source if you need it: https://ropsten.etherscan.io/address/0x00a8e52df8f4f1f4b67bded9ae6090b35489a973#code

**Comment by asemiankevich** [comment]
weird i received 0.00001 ATT @andytudhope

**Comment by jeluard** [comment]
@andytudhope It's probably the decimals that are incorrect.

**Review by jeluard — APPROVED** [review]

**Comment by asemiankevich** [comment]
@andytudhope now i receive 0.000000000000001 ATT

**Comment by asemiankevich** [comment]
@andytudhope it is now giving me 100 ATT and its okay :D

**Comment by yenda** [comment]
@andytudhope Please squash the commits so we can merge

**Pull request merged**
