### PR TITLE
The wrong validation is applied for entered amount within send assets page #18751

### LINKED ISSUE #18751: The wrong validation is applied for entered amount within send assets page
### Steps:
1. Recover the user with available assets.
2. Navigate to the 'Send Assets' page.
3. Enter a value larger than what the user has, causing it to be highlighted in red.
4. Adjust the value by removing excess numbers at the beginning to make it valid for sending.

### Actual result:
Even after adjusting the value to a valid amount, the red highlight indicates a validation error.

https://github.com/status-im/status-mobile/assets/52490791/df35ac39-9497-406d-b78e-e653a8a199b1

### Expected result:
Once the user enters a valid value, the red highlight indicating a validation error should be removed

### PR DESCRIPTION
**Pull request by mmilad75**
fixes #18751 

The function that was handling on-delete-press was working with the value of the input before deleting

### CODE REVIEW

**Review by briansztamfater — APPROVED** [review]

**Review by ilmotta — APPROVED** [review]

**Review by J-Son89 — APPROVED** [review]

**Comment by mmilad75** [comment]
@VolodLytvynenko Can you please check this PR?

**Comment by mmilad75** [comment]
@status-im/mobile-qa Can you please check this PR?

**Comment by VolodLytvynenko** [comment]
> @status-im/mobile-qa Can you please check this PR?

Hey @mmilad75 Over the next few days, the Mobile QA team will be partially occupied with testing of release 2.27. This may result in some additional delays in PR testing. I believe I can take this PR today, but a bit later

**Review by ulisesmac — APPROVED** [review]
:+1:

**Comment by VolodLytvynenko** [comment]
Hi @mmilad75 thank you for PR. Take a look please found issue:

## ISSUE 1: Incorrect validation is applied when the decimal 0 is removed from a value.
### Steps to Reproduce:
1. Select an asset with a value of 0.
2. Navigate to the "Send Assets" page.
3. Enter "0.00" as the value.
4. Remove the last 0.

### Actual Result:
The value is highlighted in red after the last 0 is removed.

https://github.com/status-im/status-mobile/assets/52490791/4b78949a-bf8f-4c41-aacc-f79dcc158b6d


### Expected Result:
The value should not be highlighted in red.

**Comment by VolodLytvynenko** [comment]
## ISSUE 2: Incorrect validation is applied for pasted amounts.

Unfortunately, the issue can't always be reproduced after following the current steps. It seems to occur randomly. hope the logs might help 

### Steps:
1. Select any token.
2. Navigate to the "Send Assets" page.
3. Enter a value that exceeds the value of the current token.
4. Navigate back to the "Send Assets" page.
5. Select a token with an available value (e.g., 2.35 ETH).
6. Paste an available value to find the routes (e.g., 2.01 ETH).

### Actual result:
The pasted value is highlighted as red

https://github.com/status-im/status-mobile/assets/52490791/e53fee31-218d-49d0-9c83-6b905be9d7e4


### Expected result:
The pasted value is not highlighted as red

### Devices:
- iPhone 11 Pro max, IOS 17
- Pixel 7a, Android 13

### Logs:
[Status-debug-logs.zip](https://github.com/status-im/status-mobile/files/14448444/Status-debug-logs.zip)

**Comment by mmilad75** [comment]
@VolodLytvynenko Can you please test again?

**Comment by VolodLytvynenko** [comment]
Hi @mmilad75 thank you for PR. No issues from my side. PR is ready to be merged

**Pull request merged**
