### PR TITLE
[#13006] Use token list from status-go

### LINKED ISSUE #13006: Use token list from status-go
Our friends from desktop moved the token list to status-go.
We should use that one so it's shared across clients.

https://github.com/status-im/status-go/pull/2482/files

### PR DESCRIPTION
**Pull request by flexsurfer**
fixes #13006

### CODE REVIEW

**Review by Parveshdhull — APPROVED** [review]

**Comment by qoqobolo** [comment]
@flexsurfer thanks for PR!

### ISSUE 1: Error when recovering an account from seed phrase (Android)

**Steps:**
1. Install the `7cf8082` build on Android device
2. Recover some account from the seed

Screenshot 2022-01-19 at 15 35 27

[geth.log](https://github.com/status-im/status-react/files/7897913/geth.log)

**Comment by qoqobolo** [comment]
@flexsurfer thanks for PR!

### ISSUE 1: Error when recovering an account from a seed phrase (Android)

**Steps:**
1. Install the `7cf8082` on an Android device
2. Recover some account from the seed
Screenshot 2022-01-19 at 17 06 35

[geth.log](https://github.com/status-im/status-react/files/7898635/geth.log)

**Comment by flexsurfer** [comment]
hey @qoqobolo what do you mean same account ?

**Comment by flexsurfer** [comment]
thanks @qoqobolo should be fixed now

**Comment by qoqobolo** [comment]
@flexsurfer could you take a look at the last failed e2e results, please? 

### ISSUE 2
There are many token contract validation errors in PR build, which are not reproducible manually (can switch to Mainnet, add tokens from the assets list, no error).
Could you verify if they are relevant?

Examples:
`Unexpected Alert is shown: 'Wrong name for token SOCKS at address 0x23b608675a2b2fb1890d3abbd85c5775c51691d5 - set to Unisocks but detected as Unisocks Edition`

`Unexpected Alert is shown: 'Wrong decimals for token PPP at address 0xc42209accc14029c1012fb5680d95fbd6036e2a0 - set to 8 but detected as 18'`

**Comment by flexsurfer** [comment]
@qoqobolo , hm it seems like we need to compare list we had in status-react and new list in status-go, seems like they are different
cc @alaibe

**Comment by flexsurfer** [comment]
status-react list : https://github.com/status-im/status-react/pull/13015/files#diff-e5a2c61803ca95ab1ac1d8a1905e7ac3b152363d2634995fde6ea502f0139c35L72

status-go list: https://github.com/status-im/status-go/pull/2482/files#diff-62a71432c768162907bd8f305cd41a0a2f9408a2d8e66bd993c4fcca954b1a89R7

**Comment by flexsurfer** [comment]
in status-react all names are equal to names in contracts
```
{:address  "0x23b608675a2b2fb1890d3abbd85c5775c51691d5"
                    :symbol   :SOCKS
                    :name     "Unisocks Edition 0"
                    :decimals 18}
```
in status-go not
```
common.HexToAddress("0x23b608675a2b2fb1890d3abbd85c5775c51691d5"): &Token{
			Address:  common.HexToAddress("0x23b608675a2b2fb1890d3abbd85c5775c51691d5"),
			Name:     "Unisocks",
			Symbol:   "SOCKS",
			Color:    "#f8f8f8",
			Decimals: 18,
			ChainID:  1,
		},
```

**Comment by flexsurfer** [comment]
@qoqobolo updated tokens to latest status-react version

**Comment by qoqobolo** [comment]
Thanks @flexsurfer!

### ISSUE 3: Error when requesting/sending token in 1-1 chat and receiving such tx-messages

If the user sends or receives a transaction message in 1-1 chat requesting/sending a token, an error occurs. 
Also, after receiving this error both sender and receiver cannot open the chat again. 

Screenshot 2022-01-28 at 16 31 39

**Steps:**
1. UserA: start 1-1 chat with UserB
2. Open tx-dialog and request a token 
3. UserB: try to open the chat with UserB

[UserA geth.log](https://github.com/status-im/status-react/files/7959933/geth.log)
[UserB geth.log](https://github.com/status-im/status-react/files/7959936/geth.log)

### ISSUE 4: Icons of some tokens are missing in all views
Full list:
ADX, ATM, AVT, CSNO, TIME, ENS, HEZ, USPD, PRG, XDATA, RARE, TGT, VRS, 

Steps:
1. Open Wallet
2. Manage assets

Screenshot 2022-01-28 at 16 48 52

**Comment by flexsurfer** [comment]
thanks @qoqobolo , is there issue 2 ?  or only 3 and 4 ?

**Comment by qoqobolo** [comment]
@flexsurfer oh, I counted [this one](https://github.com/status-im/status-react/pull/13015#issuecomment-1019944800) but forgot to rename it.
Now naming is correct, sorry!

**Comment by flexsurfer** [comment]
thanks @qoqobolo , all fixed

**Comment by qoqobolo** [comment]
@flexsurfer thank you! With tx-messages in 1-1 everything is fine now, but Issue 4 is still relevant, some icons are still missing.
Can you recheck, please?

**Pull request closed without merging**
