### PR TITLE
chore: status-go fix to avoid log flooding in case of DNS failure (not to merge)

### PR DESCRIPTION
**Pull request by chaitanyaprem**
[comment]: # @qfrank  has noticed that in case of DNS failure in lightClient mode, there is a log flooding happening due to node state not being indicated properly. This PR is to be used for dogfooding the fix made in status-go so that node state is set to offline if we are not able to resolve DNS and connect to bootnodes or any other peers.

Linked status-go PR https://github.com/status-im/status-go/pull/5682

### Summary

Fix has already been verified by @qfrank in his setup where the issue was occuring and i have verified on status-desktop running in relay mode that no side-effects were introduced with this fix. 

We just need e2e tests to pass in order to merge the underlying PR.

#### Platforms
- Android
- iOS

##### Functional

- 1-1 chats
- public chats
- group chats
- networks

status: ready 

### Risk

Described potential risks and worst case scenarios.

Tick **one**:
- [x] Low risk: 2 devs MUST perform testing as specified above and attach their results as comments to this PR **before** merging.
- [ ] High risk: QA team MUST perform additional testing in the specified affected areas **before** merging.

### CODE REVIEW

**Comment by chaitanyaprem** [comment]
@churik can we run mobile e2e tests for this PR?

There used to be a pipeline to select before, i don't see it now for some reason.

**Comment by qfrank** [comment]
> @churik can we run mobile e2e tests for this PR?
> 
> There used to be a pipeline to select before, i don't see it now for some reason.

generally, it should be automatically, but currently there's issue relate to this, I already added it manually for you :)

**Comment by qfrank** [comment]
[source](https://discord.com/channels/1210237582470807632/1217175516294021173/1268520306264248321)

**Review by qfrank — APPROVED** [review]

**Comment by chaitanyaprem** [comment]
> generally, it should be automatically, but currently there's issue relate to this, I already added it manually for you :)

Thanks!

**Comment by pavloburykh** [comment]
Hey @qfrank @chaitanyaprem! Thanx for the PR. I have just triggered e2e run manually here https://ci.status.im/job/status-mobile/job/e2e/job/status-app-prs-rerun/4308/ because in this case (PR containing go) we need to run a full testrun. 

When testrun is triggered automatically we are triggering just a smoke run with limited amount of cases which is not enough for PRs containing go changes. 

Please, ping @yevh-berdnyk  e2e once results are posted here so she can analyse them before merge. Thank you!

**Comment by yevh-berdnyk** [comment]
> ## 82% of end-end tests have passed

E2E failures are not PR related, thanks! 
@chaitanyaprem @pavloburykh

**Comment by chaitanyaprem** [comment]
Closing the PR as underlying status-go PR is merged.

**Pull request closed without merging**
