### PR TITLE
ci: don't fail on Diawi upload failure

### PR DESCRIPTION
**Pull request by yakimant**
https://www.jenkins.io/doc/pipeline/steps/workflow-basic-steps/#catcherror-catch-error-and-set-build-result-to-failure

### CODE REVIEW

**Review by siddarthkay — APPROVED** [review]

**Review by jakubgs — COMMENTED** [review]
Are we sure this is a good idea? Why?

**Comment by siddarthkay** [comment]
> Why?

https://ci.status.im/blue/organizations/jenkins/status-mobile%2Fprs%2Fios/detail/PR-18424/19/pipeline#step-105-log-1

**Comment by jakubgs** [comment]
Okay, but why would we want to ignore that failure?

**Comment by jakubgs** [comment]
I think we should undo this change.

**Comment by yakimant** [comment]
I think we can keep ignore if
- diawi downtime is causing build problems often
- diawi upload is not mandatory (for example there is another way to install app from Jenkins artifacts)
- we can notice diawi issue through some monitoring

But I'm fine with both - keeping and removing

**Comment by jakubgs** [comment]
Diawi is the primary way devs and QA install iOS builds. If they can't there's a big chance the build will have to be re-run so the Diawi link is available. Diawi is not known for frequent downtime. This change should be undone.

**Pull request merged**
