### PR TITLE
fix hole view usage for create profile picture

### PR DESCRIPTION
**Pull request by Parveshdhull**
leftover from https://github.com/status-im/status-mobile/pull/15561#issuecomment-1494063367

### Testing
- Please make sure https://github.com/status-im/status-mobile/issues/15553 is still fixed (also in ios)
- hole view is used for camera icon, fixes https://github.com/status-im/status-mobile/pull/15561#issuecomment-1494063367

status: ready

### CODE REVIEW

**Review by J-Son89 — APPROVED** [review]

**Comment by pavloburykh** [comment]
@Parveshdhull Thanx for the PR! Please, take a look at the following issues. 


### ISSUE 1 Accent color is not applied for empty (default) profile icon (Android)

Reproduced on Samsung Galaxy A52, Andrdoid 12

**Steps:** 

1. Open Create Profile onboarding step
2. Start changing accent colors
3. See if color are applied to profile icon

**Actual result:** 

Accent color is not applied for empty (default) profile icon


https://github.com/status-im/status-mobile/assets/97245802/fdc0c93f-25be-45fd-a84d-89c26a6a5b83

**Comment by pavloburykh** [comment]
### ISSUE 2 Symbols inside default icon are not updated while typing name and dispositioned (Android)

Reproduced on Samsung Galaxy A52, Andrdoid 12

**Steps:** 

1. Open Create Profile onboarding step
2. Start typing name
3. See if symbols are updated according to entered name value
4. See if symbols are not dispositioned

**Actual result:** symbols inside default icon are not updated while typing name and get dispositioned. Sometimes only 1 symbol is updated regardless multiword name value is entered. 



https://github.com/status-im/status-mobile/assets/97245802/113fc1a3-5aba-40ac-9218-b3970d306763

**Comment by pavloburykh** [comment]
### ISSUE 3 Wrong hole color? 

Not sure about this one. @Parveshdhull  could you please re-check and confirm that colors are the same as on design. Looks like hole color is lighter than currently implemented. 

**Actual result:**

**IOS:** 

photo_2023-05-26 15 18 00

**Android:**

photo_2023-05-26 15 17 57

**Expected result:** 

https://www.figma.com/file/o4qG1bnFyuyFOvHQVGgeFY/Onboarding-for-Mobile?type=design&node-id=2241-251162&t=SWwcLHfABEwbl6L6-0

Onboarding for Mobile – Figma 2023-05-26 14-29-53

**Comment by pavloburykh** [comment]
### ISSUE 4 Profile icons with set pictures disappear on login/profile list screens after app being in background for a while (IOS)

Reproduced on iPhone X, IOS 14.1

@Parveshdhull actually I am not sure if this is PR related. I also faced it while testing release build. Logging here because you asked to check this fix https://github.com/status-im/status-mobile/issues/15553

**Preconditions:** user has set profile picture.

**Steps:** (these steps are not 100% reliable) 

1. Open Profile list screeen
2. Background app for some time. (2-5 minutes)
3. Open app 
4. See if profile icons are displayed 
5. If still displayed - open any profile from the list
6. See if profile picture is displayed on login screen
7. If profile picture is not displayed - go back to profile list screen and see if profile pictures are displayed

**Actual result:** sometimes profile icons with set pictures disappear on login/profile list screens

photo_2023-05-26 15 28 19

https://github.com/status-im/status-mobile/assets/97245802/6fc3d04c-a0bf-4570-8d66-18d01854fd53

**Comment by Parveshdhull** [comment]
hi @pavloburykh, Thank you very much for testing the PR and for your patience.
Issues 1 & 2 should be fixed now.

For issue 3, I checked the camera icon color (white - 5% opacity) and the background color (primary - 50 - 40% opacity) are the same as Figma.
Still, they look different to me too.
- As they are transparent, their net result also gets affected by background color. Which might be different than Figma, maybe due to different background slide or issues in blur view.
- Device specific color vibrancy etc, not sure.

Is Issue 4 still reproducible? If yes, probably something related to image server, Please feel free to log it.

**Comment by pavloburykh** [comment]
Hi @Parveshdhull ! thanx for your work and fixes. Please, take a look at a few new issues. 

### ISSUE 5 Profile picture is not shown after being set until some action that triggers prophile icon reload (typing text/changing accent color) [ANDROID only]

Reproducible on Android 12, Samsung Galaxy A52

**Steps:** 

1. Proceed to Create Profile screen
2. Set profile picture
3. See if Profile picture is shown

**Actual result:** Profile picture is not shown after being set until some action that triggers prophile icon reload (typing text/changing accent color)


https://github.com/status-im/status-mobile/assets/97245802/1337fd21-71ef-4832-be47-03f29a5391df


**Expected result:** profile picture is shown

**Comment by pavloburykh** [comment]
### ISSUE 6 Loading spinner appears in profile icon during typing/cnhaging accent color [IOS]

This is a minor one. If you consider to fix it as followup let me know and I will log a separate issue. 

Reproducible in IOS 14.1, iPhone X

**Steps:** 

1. Proceed to Create Profile screen
2. Set profile picture
3. Start typing name/changing accent color
4. See if loading spinner is visible on profile icon 

**Actual result:** loading spinner appears in profile icon during typing/cnhaging accent color

https://github.com/status-im/status-mobile/assets/97245802/edda2cd1-0f69-45ca-bc48-1f29b222c20e

**Expected result:** if it is possible - we would better not show that spinner. BTW is there any reason why we are updating profile icon so frequently during typing (after each letter is typed)?

**Comment by pavloburykh** [comment]
> Is Issue 4 still reproducible? If yes, probably something related to image server, Please feel free to log it. 

Sure, I will try to catch it and log separately if it is still there. Thank you!

**Comment by Parveshdhull** [comment]
hi @pavloburykh, Issue 5 & 6, should be fixed now.

> Expected result: if it is possible - we would better not show that spinner. BTW is there any reason why we are updating profile icon so frequently during typing (after each letter is typed)?

Good question.
- Our implementation of fast image shows loading spinner until image is not loaded.
- And as we are using hole-view for camera icon, dynamic updates like changing image, user name, customization color don't directly work. We have to force re-render user avatar. https://github.com/status-im/status-mobile/issues/15577
- And as every time user avatar was re-created, it was showing that spinner.

Now, we are using simple image view, instead of fast-image. So it should be fixed.

**Comment by Parveshdhull** [comment]
> Now, we are using simple image view, instead of fast-image.

Also added check to make sure, only re-render every-time while typing when no image is present, otherwise only re-render when image is updated.

**Comment by pavloburykh** [comment]
> hi @pavloburykh, Issue 5 & 6, should be fixed now. 

@Parveshdhull Thanx for the fixes and explanation!

I have 1 more minor behaviour which I am not sure to be expected or not. If it is expected - PR is ready to be merged. 

### ISSUE 7 Abbreviation of "Your name" placeholder is not displayed in Profile icon if some text has been already entered and then cleared

**Steps:** 

1. Proceed to Create profile screen
2. Type some text in the input filed
3. Clear the input field
4. See if YN abbreviation (for "Your name" placeholder) is displayed inside Profile icon

**Actual result:** abbreviation is not displayed

https://github.com/status-im/status-mobile/assets/97245802/79d423aa-42fe-4ac2-97b4-219f670e927f

**Expected result:** abbreviation should be displayed

**Comment by Parveshdhull** [comment]
> I have 1 more minor behaviour which I am not sure to be expected or not.

Lets fix this one too

**Comment by pavloburykh** [comment]
@Parveshdhull thanx for your work and patience! PR is ready to be merged.

**Pull request merged**
