### PR TITLE
[#12867] Add accessibility IDs to toggles for e2e

### LINKED ISSUE #12867: Add accessibility IDs to toggles/checkboxes for e2e
# Problem

currently there is no way to distinguish enables/disabled toggles (or checkboxes).
For e2e we need some attributes (i.e. accessibility-ids) to find them in XML.

### PR DESCRIPTION
**Pull request by flexsurfer**
fixes #12867

### CODE REVIEW

**Comment by churik** [comment]
Still the same:
image

**Comment by flexsurfer** [comment]
sorry, fixed

**Comment by churik** [comment]
On build with commit https://github.com/status-im/status-react/commit/947ad9c22c554cef6ee876c33a3601ab83f3718c still have "switch"
Appium 2021-12-02 14-55-34

Also, if that's possible to do the same for checkboxes, really appreciate that 🙏

**Comment by churik** [comment]
Thank you @rasom, works perfectly with toggles.
for checkboxes still no difference
Appium 2021-12-15 10-06-44

**Comment by rasom** [comment]
@churik let's try again

**Comment by churik** [comment]
🥇  Wohoooo, works!!!!
thank you!

**Review by churik — APPROVED** [review]

**Pull request merged**
