### PR TITLE
Arch Linux Support

### PR DESCRIPTION
**Pull request by azer**
### Summary

It creates umbrella commands for all Linux packages and adds support for Arch Linux' package manager `pacman`. 

### Testing 

You can run it inside a Docker with Arch Linux image. I've tested it in Arch before submitting this PR though. 

Status: ready

### CODE REVIEW

**Comment by jeluard** [comment]
Thanks for the contribution @azer ! So it works fine with `pacman` using existing package names used for `apt`? I would assume this could be incorrect for some other package manager.

**Comment by azer** [comment]
@jeluard I think you missed the part I added separete `pacman` functions; https://github.com/status-im/status-react/pull/3186/files#diff-14c08a9aa99b4897b4a08988fb7d8d88R130

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/status-im/status-react/pull/3186">Arch Linux Support by azer · Pull Request #3186 · status-im/status-react</a></strong></div><div>Summary
It creates umbrella commands for all Linux packages and adds support for Arch Linux' package manager pacman.
Testing
You can run it inside a Docker with Arch Linux image. I've tested it in ...</div></blockquote>

**Comment by jeluard** [comment]
We use `apt` to install some packages (see `linux_install "$package"`). So all package names must be the same for both `pacman` and `apt`?

**Comment by azer** [comment]
@jeluard gotcha! Currently package names are same on both sides (only maven and nodejs), it'd require some sort of mapping as the list grows though...

**Comment by jeluard** [comment]
Makes sense! Can you add a comment in the script so that we keep this in mind for eventual future changes?

**Review by jeluard — APPROVED** [review]

**Comment by azer** [comment]
Thanks, just added a comment.

**Review by oskarth — APPROVED** [review]

**Comment by oskarth** [comment]
Thanks @azer!

**Comment by oskarth** [comment]
@azer Can you please squash your commits into one first? (We do merges outside of GH for code signing with a script).

**Comment by azer** [comment]
@oskarth squashed

**Pull request merged**
