### PR TITLE
Added Greek translation

### PR DESCRIPTION
**Pull request by tryice3**
### Summary:
Translate App Strings to Greek.
Modified my previous translation according to the feedback that I received in https://github.com/status-im/status-react/pull/2354
I also included the newest changes from en.cljs

### CODE REVIEW

**Comment by andytudhope** [comment]
Hey @fibice3 - thanks for doing this! Will try and get to testing sometime this evening/tomorrow 🎉

**Comment by andytudhope** [comment]
Ok @fibice3 there are 3 changes I need you to make to `i18n.cljs` in order to get our translation tests to pass.

1. Add `[status-im.translations.el :as el]` to the `require` statement on line 2.

2. Add `:el          el/translations` to the function on line 68 (make sure line spacing is correct)

3. Add the key `:el` to the function on line 272.

If you run `lein test-cljs` after this, you will see that you have indeed translated all the required keys as all the tests pass. 

Thank you for doing this!

**Review by andytudhope — APPROVED** [review]
LGTM

Please squash your commits, do one final check that you are happy with all the translations, and I will work on getting it merged @fibice3 🎉

**Comment by tryice3** [comment]
@andytudhope ok great!
I asked from one more friend to review it and I will probably push the final version tomorrow.

**Comment by andytudhope** [comment]
Perfect, thanks! Make sure to join https://chat.status.im and ping me @cryptowanderer and I will hook you up with a reward for doing all this seeing as there is not a bounty directly associated with this translation 👍

**Comment by tryice3** [comment]
@andytudhope I pushed the final version and I sent you a message on chat.status.im!

**Comment by andytudhope** [comment]
Hey @fibice3 - please rebase onto latest develop, squash your commits here and then I will merge 👍

**Comment by tryice3** [comment]
@andytudhope Done!

**Pull request merged**
