### PR TITLE
Use status-go build and add FEATURE_SYNC_DELAY env naively

### PR DESCRIPTION
**Pull request by oskarth**
Addresses https://github.com/status-im/status-react/issues/2504

Don't merge, just to trigger build for now.

status: wip/experiment

### CODE REVIEW

**Comment by oskarth** [comment]
Added this as experiment branch which means Jenkins doesn't recognize it. Reminder to self and others: Use parameterized builds (repo/branch right now) in Jenkins to remedy this and manually trigger build.

**Comment by oskarth** [comment]
Android build of status-go is failing. See https://jenkins.status.im/job/status-react/job/pull%20requests/job/experiment%252Fcpu-test-%25232504/1/console for full logs.

```
...
16 errors
:react-native-status:compileReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.
```

Trying with iOS only.

**Comment by oskarth** [comment]
Similar issue with iOS only:

```
** ARCHIVE FAILED **


The following build commands failed:
	CompileC /Users/jenkins/Library/Developer/Xcode/DerivedData/StatusIm-bjlrmrbkzxeclqbjyeyxxesfedko/Build/Intermediates.noindex/ArchiveIntermediates/StatusIm/IntermediateBuildFilesPath/RCTStatus.build/Release-iphoneos/RCTStatus.build/Objects-normal/arm64/RCTStatus.o RCTStatus.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
```
https://jenkins.status.im/job/status-react/job/pull%20requests/job/experiment%252Fcpu-test-%25232504/2/console

As the build works in general on our side, and the only relevant difference here is the status-go artifact included, it appears something is wrong with this artifact.

@adambabik @divan can you check?

**Comment by adambabik** [comment]
@oskarth it's because we changed some bindings in status-go some time ago. We discussed with @rasom. There was no following PR from status-react side?

This is the error while it failed:
```
error: implicit declaration of function 'Parse' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    char * result = Parse((char *) [chatId UTF8String], (char *) [js UTF8String]);
```

**Comment by oskarth** [comment]
status-go updated in develop, no longer blocked; rebase and make try this custom build.

**Comment by oskarth** [comment]
Build started here: https://jenkins.status.im/job/status-react/job/pull%20requests/job/experiment%252Fcpu-test-%25232504/5/ don't know if it will pick up ENV or not. Will verify tomorrow but feel free to try it if you want.

**Comment by oskarth** [comment]
Unable to verify build while https://github.com/status-im/status-react/issues/2534 regression remains.

**Comment by oskarth** [comment]
Strictly speaking not stopped by file logs as it appears all logs get mungled into STDOUT together with RN etc logs. It'd just make it a lot easier to debug.

However, I don't see any signs of `FEATURE_SYNC_DELAY`. Since `writeDelay` defaults to 0 and it only logs if it is above that, with no echo of `FEATURE_SYNC_DELAY` state, there are no traces of this diff. I will remedy this by making a custom build of status-go that prints some useful state.

**Comment by oskarth** [comment]
Made custom build. Different ENV completely and flag not set. We do some similar ad hoc stuff but it infiltrates configs everywhere so not really proper encapsulated flags. Trying some different things. Not straightforward unfortunately. Will continue tomorrow or later this week. Possibly easier to do just hardcoded throw-away build, but having a better flag setup have multiplier value.

**Comment by oskarth** [comment]
Spent some more time on this. Added partial support for seemless flag/env syncing between RN and status-go land. Still hacky in checkout but will prepare PR soon; it'll simplify things a bunch for these types of things. Essentially you only need to set ENV variable as usual in status-react and then read it in status-go as if it was the same filesystem.

Noticed the `Init` fn in @divan's peer is called _before_ StartNode, and even before React Native! is initialized. This made it hard to initialize ENV properly, for obvious reasons. Changed this to super hacky, and possibly bad, doing inline read of ENV in InsertHeaderChain instead. This should be moved upstream but wasn't clear to me where to do that.

Main problem now is getting that, InsertHeaderChain fn, to be called. web3.eth.syncing keeps returns flag and I'm not sure if this is because the Infura change or what I need to do in order to force a sync. Pinged Clojure chan; will check-in tomorrow.

**Comment by oskarth** [comment]
1. Sync, I forgot I had to switch network.

2. Env variables not supported by default, forking issue to https://github.com/status-im/status-react/issues/2544 EDIT: Cherrypicked this hack into this branch

3. The other problem is with Init fn / InsertHeaderChain where state is the same as above. EDIT: See https://github.com/status-im/status-go/pull/484 for temp "fix"

**Comment by oskarth** [comment]
@divan was OK with https://github.com/status-im/status-go/pull/484 approach for quick (ehm) and dirty tezt. Need to update status-go version here, check CI/Artifactory for that branch, verify that flag set in logs, then check CI for this build and prepare basic instructions for testers. Will need two builds since we don't have parameterized Jenkin yet. I suggest this one at delay=100 and then compare with develop. Will look at this soon/later.

**Comment by oskarth** [comment]
Moving to testing, assuming build goes through. Preliminary testing instructions:

- Goal: compare this build with status-react develop and profile/verify CPU/temp difference per original status-go issue
- Use Ropsten which syncs, not with upstream
- Verify flag is set properly by grepping geth logs for  "FEATURE_SYNC_DELAY"

**Comment by oskarth** [comment]
Verified build works as expected. See https://github.com/status-im/status-react/issues/2504#issuecomment-348264727 for what to test.

Caveats:
- iOS only for now
- Set Ropsten network
- 1ms delay hardcoded, compare with normal develop build for 0

(no log checks necessary)

**Comment by oskarth** [comment]
@annadanchenko Can you try on Android again? My Android setup is a bit wonky but I added the binding and should be straightforward. If you have access to logs (even RN logs) you should see something if grepping for "addEnv" such as `addEnv FEATURE_SYNC_DELAY 1000`. If you see this then the behavior is the same as iOS build you tested.

**Comment by oskarth** [comment]
Tested, nothing to merge, closing.

**Pull request closed without merging**
