### PR TITLE
[#3881] Stop parsing web3.* as a URL

### LINKED ISSUE #3881: Web3 commands are links instead of text in Console chat
### Description

*Type*: Bug

*Summary*:  web3 commands are treated as links which is not correct since they are not links :)

#### Expected behavior
web3 commands are not clickable when being sent to console chat

#### Actual behavior

web3 commands are shown as links

image

### Reproduction
- Open Status
- Enable Console chat in Profile
- Switch to Ropsten
- Send web3.eth.blocknumber command in console chat

### Additional Information
* Status version: develop
* Operating System: Android, iOS

### PR DESCRIPTION
**Pull request by kwingram25**
Fixes #3881 

### Summary:
- Fixes chat message URL parser to not process web3 api calls

### Steps to test:
- Open Status development mode console
- Type web3... commands and verify they are not treated as links

Status: Ready

### CODE REVIEW

**Comment by rasom** [comment]
@kwingram25 could you please also add some test?

**Comment by kwingram25** [comment]
New tests added, also I needed to refine regex as it was catching things after web3 as a URL still. Now it includes whitespace or start of string and moves any empty spaces to the previous word. I tried to use the \K flag/lookbehind but it doesn't seem to be in the regex engine used here

**Comment by flexsurfer** [comment]
hey @kwingram25 i can't see tests in changes

**Comment by rasom** [comment]
tests are failing 
```
FAIL in (parse-url) (cljs/test.cljs:476:9)

expected: (= (lazy-seq [{:text "Status - ", :url? false} {:text "https://github.com/status-im/status-react", :url? true} {:text " a Mobile Ethereum Operating System", :url? false} nil]) (message/parse-url "Status - https://github.com/status-im/status-react a Mobile Ethereum Operating System"))

  actual: (not (= ({:text "Status - ", :url? false} {:text "https://github.com/status-im/status-react", :url? true} {:text " a Mobile Ethereum Operating System", :url? false} nil) ({:text "Status -", :url? false} {:text "https://github.com/status-im/status-react", :url? true} {:text " a Mobile Ethereum Operating System", :url? false} nil)))
```

**Comment by kwingram25** [comment]
Found the problem - used a wrong variable name

**Comment by jeluard** [comment]
@kwingram25 Thanks for your PR! After more consideration this particular case should be handled upfront to reduce perf cost and complexity. This will be a more complex change requiring architectural changes.
I will close this PR but you will receive some tokens for your contribution anyway.

Thanks again!

**Comment by andytudhope** [comment]
Hi @kwingram25 - thanks again for the PR! We have paid out half the original bounty for the work you did here and I am sure the inimitable @jeluard will keep you informed on the fix as it progresses.

https://etherscan.io/tx/0x5a813616bc2ca0fbdf878b8adbe986dc310469f1a80c6556be851b17025eec51

<blockquote><div><strong><a href="https://etherscan.io/tx/0x5a813616bc2ca0fbdf878b8adbe986dc310469f1a80c6556be851b17025eec51">Ethereum Transaction 0x5a813616bc2ca0fbdf878b8adbe986dc310469f1a80c6556be851b17025eec51</a></strong></div><div>Ethereum (ETH) detailed transaction info for 0x5a813616bc2ca0fbdf878b8adbe986dc310469f1a80c6556be851b17025eec51</div></blockquote>

**Pull request closed without merging**
