### PR TITLE
[#5839] fix logo on welcome screen on desktop

### LINKED ISSUE #5839: Wrong logo on desktop welcome screen
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a developer, I want to use the right logo to show a good brand and image.

### Description

This is a very small thing, but with out first release coming up we should put our best foot forward. This is the first screen everyone sees and our logo is wrong! Hopefully a quick fix that will make desktop feel less broken, which will be a little UX win :)

screen shot 2018-09-14 at 7 41 13 am

### PR DESCRIPTION
**Pull request by dmitryn**
fixes #5839

### Summary:

Fixes logo on welcome screen - fills it with white color.

status: ready

screenshot 2018-10-19 00 44 41

### CODE REVIEW

**Review by maxhora — APPROVED** [review]
@dmitryn nice!

**Review by janherich — APPROVED** [review]

**Review by yenda — APPROVED** [review]

**Review by flexsurfer — CHANGES_REQUESTED** [review]
can we fix colours for icons? use color here https://github.com/status-im/status-react/blob/d32f15243d2a1c42ed15bea529417354dcc6042c/src/status_im/ui/components/icons/vector_icons.cljs#L184

**Review by vitvly — APPROVED** [review]

**Comment by vkjr** [comment]
@dmitryn, did you try `[icons/icon icon {:style {:tint-color :white}}]` instead?

**Comment by flexsurfer** [comment]
> @dmitryn, did you try `[icons/icon icon {:style {:tint-color :white}}]` instead?

better to use the same component for mobile and desktop
```
(defn desktop-icon
  [name {:keys [color container-style style accessibility-label width height]
         :or   {accessibility-label :icon}}]
  (let [default-viewbox {:width 24 :height 24}
color-style {:tint-color (cond
                       (keyword? color)
                       (case color
                         :dark colors/black
                         :gray colors/gray
                         :blue colors/blue
                         :active colors/blue
                         :white colors/white
                         :red colors/red
                         colors/black)
                       (string? color)
                       color
                       :else
                       colors/black)}
        icon-style      (if width
                          (assoc default-viewbox :width width :height height)
                          default-viewbox)]
    [react/view {:style               container-style
                 :accessibility-label accessibility-label}
     [react/image {:source (get icons (normalize-property-name name))
                   :style  (merge icon-style color-style style)}]]))
```

cond should be moved in separate function and used in both desktop and mobile icons

**Comment by dmitryn** [comment]
@vkjr thanks for advice with `tint-color`, it works.
@flexsurfer made changes to use same logic for mobile and desktop, please check

**Review by flexsurfer — APPROVED** [review]

**Review by vkjr — APPROVED** [review]

**Comment by SlizkovaGanna** [comment]
Tested on MacOS and Linux (emulated), also double-checked on mobile.
The logo was changed to a correct one, functionality was not affected.

**Tested on:**
iOS 12.0.1 
Android 7.0 
MacOS 10.13.4
Ubuntu 18.04.1 LTS

**Pull request merged**
