### PR TITLE
Fixes #2332, spanish translatios by a Native Mexican

### LINKED ISSUE #2332: Translate App Strings to Spanish
### User Story

As a Spanish language speaker, I want to be able to interact with Status in my native language.

### Description

*Type*: Feature

*Summary*: We need someone fluent (and eloquent) in Spanish to translate all the latest strings in Status from English. We would like to invite our community members to take on these tasks in order
a) To become a bit more acquainted with the Status repos and perhaps wander further into the codebase and set of issues we need help with, earning yourself Open Bounties all the way down this rabbit hole, and
b) To make sure that the product we deliver has been built by the same community that uses it, in a virtuous feedback loop of increasing understanding and value-generation.

#### Expected behavior
The Spanish translation ought to be as up-to-date as the English one.

#### Actual behavior
We have not yet updated it, preferring to leave this open as an opportunity for our community to get involved again.

### Solution

*Summary*: 

- The file [here](https://github.com/status-im/status-react/blob/develop/src/status_im/translations/es.cljs) needs to be updated to match the new English one [here](https://github.com/status-im/status-react/blob/develop/src/status_im/translations/en.cljs).
- How you translate is a matter of your preference. There were significant updates to the English file for the 0.9.12 release, with lots of strings both add and REMOVED. We need you to make sure that the files are exact mirrors of each other, except in different languages.
- It might be easier to simply take the new English file and translate from scratch rather than going through the current translated files line by line (though we leave this up to you).

### Additional Information

* Status version: 0.9.12+

There are bounties available for these translations. Please see the QR codes that will be added below after the DevCon 3 announcement.

### PR DESCRIPTION
**Pull request by adnx2h**
[comment]: # (Please replace ... with your information. Remove < and >)
[comment]: # (To auto-close issue on merge, please insert the related issue number after # i.e fixes #566)

If you submit PR for issue with bounty then write here Fixes #NN where NN is issue number

*otherwise*

addresses #...

### Summary:

[comment]: # (Summarise the problem and how the pull request solves it)
...

### Steps to test:
- Open Status
- ...
- Step 3, etc.

[comment]: # (PRs will only be accepted if squashed into single commit.)

status: ready

*or*

status: wip

### CODE REVIEW

**Review by LaloGarza — COMMENTED** [review]
Hello, you are missing the accents on some words that requires them.

**Comment by adnx2h** [comment]
Changes ready to be reviewed.

**Comment by poiga** [comment]
Is "Native Mexican" same sort of thing as "Native American"?

**Comment by yenda** [comment]
Thank you for your contribution.

We can't review this you changed the english translation file, you need to put your translation in the spanish translation file `es.cljs`.

Could you also remove the translation for :browsing-browse and add one for :status-sending.

Once you are done please squash your commits into one, PR should only have one commit.

**Comment by andytudhope** [comment]
Spanish PR already accepted some time ago - closing here.

**Pull request closed without merging**
