### PR TITLE
[15834] Send single notification when mentioned in message with multiple images

### LINKED ISSUE #15834: Multiple duplicate notifications in AC when receiving images with a mention
# Bug Report

## Problem 
The mentioned user receives as many notifications in the activity center as many images are added to the message.

#### Expected behavior
One mention = one notification

#### Actual behavior

https://user-images.githubusercontent.com/67952253/236830094-112991cd-ca9b-4592-bd9e-17d779fd52bc.MP4

### Reproduction

1. UserA and UserB join the same community or group chat
2. UserA opens the home screen
3. UserB selects several images from the gallery and adds one mention of UserA as a description of the message, sends the message
4. UserA checks AC

### Additional Information

- Status version: nightly 8/05
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by ibrkhalil**
fixes #15834 

##### Functional

- notifications

Notes to QA: This PR might affect how the image notification behavior is handled on status-desktop, So please take into consideration testing the same behavior on status-desktop, Thanks in advance!

### CODE REVIEW

**Review by qfrank — APPROVED** [review]

**Review by ilmotta — APPROVED** [review]

**Comment by pavloburykh** [comment]
@ibrkhalil hi! Is this PR ready for testing? If yes - please move it to E2E column in order qa team could pick it up. As for now, I see that go PR is still under review. Also kindly rebase current PR to the latest develop. Thank you!

Regarding desktop testing, I have pinged desktop qa team in correspondent go PR https://github.com/status-im/status-go/pull/3485

**Comment by ibrkhalil** [comment]
> @ibrkhalil hi! Is this PR ready for testing? If yes - please move it to E2E column in order qa team could pick it up. As for now, I see that go PR is still under review. Also kindly rebase current PR to the latest develop. Thank you!
> 
> Regarding desktop testing, I have pinged desktop qa team in correspondent go PR [status-im/status-go#3485](https://github.com/status-im/status-go/pull/3485)

Thank you so much for looking into this Pavlo, Yes PR is ready for QA review.

**Comment by churik** [comment]
blocked until resolving this conversation https://github.com/status-im/status-go/pull/3485#pullrequestreview-1430275389 and getting reveiw on status-go side

**Comment by ibrkhalil** [comment]
> blocked until resolving this conversation [status-im/status-go#3485 (review)](https://github.com/status-im/status-go/pull/3485#pullrequestreview-1430275389) and getting reveiw on status-go side

Conversation is resolved, Ready for QA.

**Comment by flexsurfer** [comment]
@ibrkhalil @VladimrLitvinenko seems like there are no changes in this PR

**Comment by ibrkhalil** [comment]
> @ibrkhalil @VladimrLitvinenko seems like there are no changes in this PR

The status-go changes are merged, The QA process should happen in develop.

I forgot and merged the PR before QA took place.

**Comment by ibrkhalil** [comment]
@VladimrLitvinenko can you please test this on develop and we can close this PR if there are no issues

**Comment by VolodLytvynenko** [comment]
> @VladimrLitvinenko can you please test this on develop and we can close this PR if there are no issues

@ibrkhalil thank you for the fixes. Yes, we can close this issue. No additional issues from my side

**Comment by ibrkhalil** [comment]
> > @VladimrLitvinenko can you please test this on develop and we can close this PR if there are no issues
> 
> @ibrkhalil thank you for the fixes. Yes, we can close this issue. No additional issues from my side

Thank you so much!

**Pull request closed without merging**
