### PR TITLE
[#8008] Error "No protocol method IDeref.-deref defined for type unde…

### LINKED ISSUE #8008: Error "No protocol method IDeref.-deref defined for type undefined:" and crash if open DApp permissions
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Error and crash if open DApp permissions
```
04-22 09:48:15.835 12036 12081 E ReactNativeJS: Error: No protocol method IDeref.-deref defined for type undefined: 
04-22 09:48:15.835 12036 12081 E ReactNativeJS: 
04-22 09:48:15.835 12036 12081 E ReactNativeJS: This error is located at:
04-22 09:48:15.835 12036 12081 E ReactNativeJS:     in dapps-permissions
04-22 09:48:15.835 12036 12081 E ReactNativeJS:     in reagent66
04-22 09:48:15.835 12036 12081 E ReactNativeJS:     in RCTView
04-22 09:48:15.835 12036 12081 E ReactNativeJS:     in reagent65
04-22 09:48:15.835 12036 12081 E ReactNativeJS:     in r
04-22 09:48:15.835 12036 12081 E ReactNativeJS:     in s
04-22 09:48:15.835 12036 12081 E ReactNativeJS:     in RCTView
04-22 09:48:15.835 12036 12081 E ReactNativeJS:     in u
04-22 09:48:15.835 12036 12081 E ReactNativeJS:     in C
04-22 09:48:15.835 12036 12081 E ReactNativeJS:     in n
04-22 09:48:15.835 12036 12081 E ReactNativeJS:     in E
04-22 09:48:15.835 12036 12081 E ReactNativeJS:     in RCTView
04-22 09:48:15.835 12036 12081 E ReactNativeJS:     in n
04-22 09:48:15.835 12036 12081 E ReactNativeJS:     in RCTView
04-22 09:48:15.835 12036 12081 E ReactNativeJS:     in H
04-22 09:48:15.835 12036 12081 E ReactNativeJS:     in L
04-22 09:48:15.835 12036 12081 E ReactNativeJS:     in RCTView
04-22 09:48:15.835 12036 12081 E ReactNativeJS:     in h
04-22 09:48:15.835 12036 12081 E ReactNativeJS:     in v
04-22 09:48:15.835 12036 12081 E ReactNativeJS:     in h
04-22 09:48:15.835 12036 12081 E ReactNativeJS:     in _
04-22 09:48:15.835 12036 12081 E ReactNativeJS:     in N
04-22 09:48:15.835 12036 12081 E ReactNativeJS:     in s
04-22 09:48:15.835 12036 12081 E ReactNativeJS:     in RCTView
04-22 09:48:15.835 12036 12081 E ReactNativeJS:     in RCTView
04-22 09:48:15.835 12036 12081 E ReactNativeJS:     in l
04-22 09:48:15.835 12036 12081 E ReactNativeJS:     in RCTView
04-22 09:48:15.835 12036 12081 E ReactNativeJS:     in n
04-22 09:48:15.835 12036 12081 E ReactNativeJS:     in RCTView
04-22 09:48:15.835 12036 12081 E ReactNativeJS:     in n
04-22 09:48:15.835 12036 12081 E ReactNativeJS:     in _
04-22 09:48:15.835 12036 12081 E ReactNativeJS:     in h
04-22 09:48:15.835 12036 12081 E ReactNativeJS:     in N
04-22 09:48:15.835 12036 12081 E ReactNativeJS:     in s
04-22 09:48:15.835 12036 12081 E ReactNativeJS:     in RCTView
04-22 09:48:15.835 12036 12081 E ReactNativeJS:     in u
04-22 09:48:15.835 12036 12081 E ReactNativeJS:     in C
04-22 09:48:15.835 12036 12081 E ReactNativeJS:     in n
04-22 09:48:15.835 12036 12081 E ReactNativeJS:     in E
04-22 09:48:15.835 12036 12081 E ReactNativeJS:     in RCTView
04-22 09:48:15.835 12036 12081 E ReactNativeJS:     in n
04-22 09:48:15.835 12036 12081 E ReactNativeJS:     in RCTView
04-22 09:48:15.835 12036 12081 E ReactNativeJS:     in H
04-22 09:48:15.835 12036 12081 E ReactNativeJS:     in L
04-22 09:48:15.835 12036 12081 E ReactNativeJS:     in RCTView
04-22 09:48:15.835 12036 12081 E ReactNativeJS:     in h
04-22 09:48:15.835 12036 12081 E ReactNativeJS:     in v
04-22 09:48:15.835 12036 12081 E ReactNativeJS:     in h
04-22 09:48:15.835 12036 12081 E ReactNativeJS:     in _
04-22 09:48:15.835 12036 12081 E ReactNativeJS:     in N
04-22 09:48:15.835 12036 12081 E ReactNativeJS:     in s
04-22 09:48:15.835 12036 12081 E ReactNativeJS:     in c
04-22 09:48:15.835 12036 12081 E ReactNativeJS:     in h
04-22 09:48:15.835 12036 12081 E ReactNativeJS:     in N
04-22 09:48:15.835 12036 12081 E ReactNativeJS:     in RCTView
04-22 09:48:15.835 12036 12081 E ReactNativeJS:     in reagent2
04-22 09:48:15.835 12036 12081 E ReactNativeJS:     in root
04-22 09:48:15.835 12036 12081 E ReactNativeJS:     in reagent1
04-22 09:48:15.835 12036 12081 E ReactNativeJS:     in RCTView
04-22 09:48:15.835 12036 12081 E ReactNativeJS:     in RCTView
04-22 09:48:15.835 12036 12081 E ReactNativeJS:     in c

```

#### Expected behavior

Dapp permission screen is opened 

#### Actual behavior

Error "No protocol method IDeref.-deref defined for type undefined:" and crash

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status and create new account
- Profile -> DApp permissions

### Additional Information

[comment]: # (Please do your best to fill this out.)
- Status version: nightly April 22 - 0.12.0(2019042202)
- iOS 12.2, real iphone 7 plus 
- Android 9, real Pixel xl

#### Logs

[Status.log](https://github.com/status-im/status-react/files/3102654/Status.log)

### PR DESCRIPTION
**Pull request by flexsurfer**
fixes #8008

### CODE REVIEW

**Review by jeluard — APPROVED** [review]

**Review by mandrigin — APPROVED** [review]

**Review by goranjovic — APPROVED** [review]

**Comment by asemiankevich** [comment]
@jeluard @flexsurfer @jakubgs e2e build is failing please assist

**Comment by jeluard** [comment]
@jakubgs Maybe related to "The user limit on the total number of inotify watches was reached; increase the fs.inotify.max_user_watches sysctl" ?

**Comment by jakubgs** [comment]
Yeah, i increased that limit a few times now, but I guess it going to `524288` fixed it:
https://github.com/status-im/infra-ci/commit/4f7992cf1d2e4c5e44b82f5ca8cf9e1513870516

**Comment by asemiankevich** [comment]
@Serhy @churik should be false fails here with e2e , could u please confirm?

**Comment by Serhy** [comment]
@asemiankevich yes, after tests re-ran, the one with "Faucet not received" failed.. - it's known issue for this moment (False Failure for this test)

**Comment by asemiankevich** [comment]
okay, we will merge it as is then.

**Pull request merged**
