### PR TITLE
Moved to new react-native-webview community project

### LINKED ISSUE #6398: Implement Google Safe Browsing
### User Story

As a user, I want to be protected from visiting known scam sites in the Status browser.

### Description

*Type*: Feature

*Summary*: This is a build on #5801. At the time, we decided to implement only MetaMask phishing detect while [discussing](https://discuss.status.im/t/3rd-party-http-services/437) the addition of more HTTP services, like Google Safe Browsing. 

After speaking with our security leads, we feel that the Google Safe Browsing API is a justifiable addition of HTTP reliance and risk exposure.

#### Expected behavior
The [Google Safe Browsing API](https://developers.google.com/safe-browsing/v4/) is used to check URLs navigated in the browser against Google's list of dangerous websites.

#### Actual behavior
Only MetaMask's phishing detect list is used to identify dangerous URLs.

### LINKED ISSUE #7471: Enable remote webview debug in dev mode
### User Story

As a developer, I want to remote debug my DApp when in dev mode

### Description

*Type*: Feature

### PR DESCRIPTION
**Pull request by jeluard**
### Summary:

fixes #6398
fixes #7471
relates to #6861
relates to #6300

Migrated browser to latest [react-native-webview](https://github.com/react-native-community/react-native-webview/)

This migration modifies significantly how the browser works on both iOS and android.

## Google safe browsing

Some relevant links:

* https://transparencyreport.google.com/safe-browsing/search?url=malware.testing.google.test%2F&hl=en
* https://developers.google.com/safe-browsing/

## Left to do

* restore ServiceWorker injection support

## Tests

* make sure the testing DApp is augmented to cover more scenario
* add missing tests from the [existing](https://docs.google.com/spreadsheets/d/1xTz1MSDUoeRoNlbd3BrxXu3RzTFwr4FatN2YdxVdn3Y/edit#gid=2060193276) manual tests

## Missing tests

* cookies/localStorage persistence
* file uploads
* file browsing (pdf, .)

status: wip  (only Android migration yet)

### CODE REVIEW

**Comment by jeluard** [comment]
@corpetty This PR makes webview debugging always enabled. WDYT?

**Comment by mandrigin** [comment]
@jeluard is there any thoughts to switching there? that might help with bancor issues.
@rachelhamlin or maybe we can just contact Bancor because their app doesn't work in Android WebViews or any apps that use these webviews at all. Chrome and Opera for Android bundle it's own rendering engine that is why it is fine there.

**Comment by jeluard** [comment]
@mandrigin Yes we still plan to switch at some point. It will still use the Android webview though.
Any way we could arrange that for Bancor? Probably simpler to contact them.

**Comment by mandrigin** [comment]
yeah, I hoped maybe @rachelhamlin or @andytudhope can reach out to them and ask, I made a simple native app based on an Android WebView (no JS injections, plain vanilla webview) and I see that white page in Bancor just like in our case. And our injection looks correct when I see the injected source of the page.

**Pull request closed without merging**
