### PR TITLE
Increase mailserver page size 10 times to make initial sync faster.

### PR DESCRIPTION
**Pull request by mandrigin**
It should speed up the initial sync on empty accounts on slow networks.

status: ready

### CODE REVIEW

**Review by cammellos — APPROVED** [review]

**Review by rasom — APPROVED** [review]

**Comment by Serhy** [comment]
Tested on Android and iOS. Results below provided for Android as slower device (than iPhoneX I was looking at - sync completes faster on both devices anyway!)

1) Install fresh Status build on Android7 (Samsung J7 real device) connected to a stable WiFi connection
2) Create new account
3) Once you appear on Home screen -> switch Mailserver at `Profile` -> `Mailservers` -> to `mail-01.do-ams3.eth.beta` (I chose this mailserver as the most stable one since issues we had with mailservers described in #7408 are not the case for mail-01.do-ams3)
4) Switch back to Home screen and measure the time until sync indication disappear at top of Home screen

| Average from | Current PR build:  | Nightly 5th February develop  build: |
| ------------- | ------------- | ------------- |
| 6 cycles | 20 sec  | 55 sec |

Almost trippled mailserver sync for new accounts!

Reeceinving 200 text messages from same public chat freezes app for the 7s in both nightly/currentPR builds.

**Comment by Serhy** [comment]
@mandrigin could you please rebase develop (so that #7413 is included here)

**Comment by mandrigin** [comment]
done

**Comment by mandrigin** [comment]
cherry-picked to `release/0.9.33`

**Pull request merged**
