### PR TITLE
disable auto-correction for pubchat name

### PR DESCRIPTION
**Pull request by rasom**
status: ready

### CODE REVIEW

**Review by flexsurfer — APPROVED** [review]

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/SfTCh8 for branch PR-4521

<blockquote><div><strong><a href="https://i.diawi.com/SfTCh8">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/a99LaG for branch PR-4521

<blockquote><div><strong><a href="https://i.diawi.com/a99LaG">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/M4dd3j for branch PR-4521

<blockquote><div><strong><a href="https://i.diawi.com/M4dd3j">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/rfkZLe for branch PR-4521

<blockquote><div><strong><a href="https://i.diawi.com/rfkZLe">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Pull request merged**
