### PR TITLE
Feature/added reload page button

### PR DESCRIPTION
**Pull request by flexsurfer**
added reload page button

### CODE REVIEW

**Review by goranjovic — APPROVED** [review]

**Review by jeluard — APPROVED** [review]

**Comment by rachelhamlin** [comment]
@flexsurfer One small improvement: can we gray out the navigation buttons when back/forward is not possible?

ERC dEX is an example of a DApp where browser history isn't available and buttons could be faded.

**Comment by flexsurfer** [comment]
@rachelhamlin i hope we can achieve this in this PR https://github.com/status-im/status-react/pull/4919

**Comment by Serhy** [comment]
This looks good to me (on Android 6.0.1/7.0, iOS 11.2.5)
Now we are able to use back/fwd buttons in most of Dapps (e.g. ERC dEX)
Page refresh has no impact on navigation history refreshing the page (by URI).

@flexsurfer am I right that similar to @rachelhamlin request in https://github.com/status-im/status-react/pull/4911#issuecomment-399948830 for ERC dEX Dapp, - we aim that #4919 should deliver next items (which take place in this PR)?
- The `Back` button should be greyed out if nowhere to navigate back in the browser
- The `Forward` button should be greyed out if nowhere to forward page in the browed history
(to reproduce above - simply navigate to any Dapp and tap 'Back' button on the very first page load)

**Comment by Serhy** [comment]
Since it's all fine, no regressions - above issues we'll address separately. 
Lets merge!

**Comment by flexsurfer** [comment]
please DO NOT merge!

**Comment by asemiankevich** [comment]
depends on https://github.com/status-im/status-react/issues/4919

**Pull request merged**
