### PR TITLE
increase pow target to 0.002

### PR DESCRIPTION
**Pull request by yenda**
The pow required by the nodes is 0,001
However when receiving a message, nodes call calculatePOW on the enveloppe with a diff parameter based on timestamps (sent - now + 1). This diff is enough for the POW of some messages to be considered to be below 0,001. The consequence is that the message is dropped and the peer is disconnected.
The solution is to use a higher PowTarget on the sending device so that POW of the message is always above the required threshold of the nodes.

status: ready

### CODE REVIEW

**Comment by rasom** [comment]
Why not change it in `.env`?

**Comment by yenda** [comment]
Just testing for now, but if 0.001 is the reason messages get lost it shouldn't be the default

**Comment by rasom** [comment]
it is "ready" that's why i asked. If you are testing please mark it as WIP or something

**Comment by yenda** [comment]
@rasom I edited the files as well, because it wouldn't have worked anyway since Jenkins would have used the env value which was 0.001 thanks for noticing

**Review by rasom — APPROVED** [review]

**Review by cammellos — APPROVED** [review]

**Review by janherich — APPROVED** [review]

**Review by flexsurfer — APPROVED** [review]

**Comment by lukaszfryc** [comment]
I didn't notice any issues with receiving messages 👍

**Pull request merged**
