### PR TITLE
fix(dev exp): auto disable fast refresh on iOS

### PR DESCRIPTION
**Pull request by yqrashawn**
-------

[comment]: # (Please replace ... with your information. Remove < and >)
[comment]: # (To auto-close issue on merge, please insert the related issue number after # i.e fixes #566)

### Summary

- old `(.-setHotLoadingEnabled (.-_nativeModule DevSettings))`
- new `(.-setHotLoadingEnabled (.-DevSettings NativeModules))`
- fall back to the old one with `or`

### Review notes
- tested on iOS and Android (not working on Android)
- I suggest skip manual QA

status: ready

### CODE REVIEW

**Comment by siddarthkay** [comment]
Tested locally on iOS Simulator. 
Fast Refresh seems to be disabled by default, which is nice.
Screenshot 2024-05-21 at 1 28 05 PM

**Review by siddarthkay — APPROVED** [review]

**Review by Parveshdhull — APPROVED** [review]

**Review by ilmotta — COMMENTED** [review]
@yqrashawn, I can't test this PR because I don't have access to iOS, but it would be lovely to disable fast refresh automatically on Android as well. Do you know if that can be cleanly accomplished? This problem trips up a lot of contributors, particularly external ones.

**Comment by yqrashawn** [comment]
> @yqrashawn, I can't test this PR because I don't have access to iOS, but it would be lovely to disable fast refresh automatically on Android as well. Do you know if that can be cleanly accomplished? This problem trips up a lot of contributors, particularly external ones.

I tried this approach on Android and the app crashed on every launch, I'll look further see if there's Android-specific solutions

**Comment by yevh-berdnyk** [comment]
> ## 77% of end-end tests have passed


Hi @yqrashawn, thanks for the PR! E2E failures are not related

**Pull request merged**
