### PR TITLE
[IMPORTED] Tags-network(bounty)

### LINKED ISSUE #16727: Implement Quo2 Tags/Network Tags component
Implement this component in the quo2 component library as per the design spec:

Designs
https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?type=design&node-id=22566-204870&mode=design&t=Y3eE3KsOE35InEBp-4

Acceptance Criteria:

component spec tests - https://github.com/status-im/status-mobile/blob/develop/doc/component-tests-overview.md
quo2 preview screen
export from quo2/core.cljs
following best practices - https://github.com/status-im/status-mobile/blob/develop/doc/new-guidelines.md

Note
Please align with design team before starting this

### PR DESCRIPTION
**Pull request by siddarthkay**
[comment]: # (Please replace ... with your information. Remove < and >)
[comment]: # (To auto-close issue on merge, please insert the related issue number after # i.e fixes #16727)

Original PR : https://github.com/status-im/status-mobile/pull/16747

fixes #16727

Added Tags/  Network Tags component to quo2 library.

link to designs - https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?type=design&node-id=22566-204870&mode=dev

### CODE REVIEW

**Review by J-Son89 — APPROVED** [review]
this pr already had approvals in original pr: https://github.com/status-im/status-mobile/pull/16747

**Comment by J-Son89** [comment]
@Francesca-G could you take a look at this pr when you have a chance please?

btw this is a pr I opened to add the review notes you made in this pr: https://github.com/status-im/status-mobile/pull/16747

**Review by Francesca-G — APPROVED** [review]
@J-Son89 looks good ✨

**Comment by J-Son89** [comment]
Thanks @Francesca-G, going to merge as it does not need QA - only a new quo2 component :)

**Pull request merged**
