### PR TITLE
Enable partitioned topic

### PR DESCRIPTION
**Pull request by rasom**
status: ready

### CODE REVIEW

**Comment by cammellos** [comment]
Probably we should have a discussion about this, as this will break with 0.9.33 when release (both actual and nightlies), @mandrigin is this the plan?

**Comment by rasom** [comment]
@cammellos we can wait another week before merging this PR, but anyway it was planned to be done in the next release

**Review by cammellos — APPROVED** [review]

**Review by adambabik — APPROVED** [review]
Is there any documentation how it is implemented? I would like to port it to my console client.

**Comment by cammellos** [comment]
I don't think we have docs, worth documenting:
https://github.com/status-im/status-react/blob/6ff36b5dd56b535e66abe686d52d2e5eba135c4e/src/status_im/transport/partitioned_topic.cljs#L27

basically it's a random integer between 0 4999 and -discovery (i.e "3-discovery"), and to calculate this we seed https://chancejs.com/ with the public key of the recipient.

**Comment by rasom** [comment]
`Stable Topic` here https://notes.status.im/9T8Nt1CIQlu2Wps1-8fIQg , not docs but some notes

**Comment by annadanchenko** [comment]
Discussed in status-core sync, agreed to warn users in #status public chat and on social channels too that this change will be introduced on March 18 and users on 0.9.33 or lower should update (we have ~800 Android users on 0.9.33 on March 11). So PR is to be merged on March 18. Meanwhile, we can start testing it. 

Exact message for #status chat: "If you're currently using version 0.9.33 of mobile Status app (or lower), please upgrade to the latest 0.10.1 version! We'll be adding a change on Monday, March 18 to nightly builds and upcoming 0.11.0 release, that will prevent you from receiving messages in 1:1 and group chats from users on these versions."

**Comment by annadanchenko** [comment]
@rasom 
### issue 1. Can't receive messages in 1:1 and group chat if they are sent by a user who didn't add me to his Contacts

Steps:
1. as user A: add user B to contacts (e.g. by tapping on user profile from public chat and adding to contacts)
2. as user A: send message to user B in 1:1 chat. Check if user B gets it
3. as user A: create group chat and add user B.
4. as user B: accept group invite
5. as user A: send message to group chat
6. as user B: send message to group chat. as user A: check you can see message from user B in group chat

used build 2 for Android

Logs from user B (who didn't add user A to contacts)
[geth.log](https://github.com/status-im/status-react/files/2956401/geth.log)
[Status.log](https://github.com/status-im/status-react/files/2956402/Status.log)

user B sent messages but they have spinner instead of sent status (for several minutes already)
Screenshot_20190312-114341

**Comment by cammellos** [comment]
`Error: envelope does not match bloom filter, hash=[0xc9c92c9634b4875c897958c86ad    9eb8f9fe9b46d6cdca18a59b2187cc7a1f161], bloom:` possibly we are not setting up the filter if the user in to in our contacts?

**Comment by rasom** [comment]
@cammellos most likely

**Comment by rasom** [comment]
@cammellos should be fixed now

**Comment by cammellos** [comment]
@rasom looking at the code, we hit the discovery topic (old) if it's not in our contacts, otherwise we hit the partitioned topic, is that correct? (sounds reasonable, just want to make sure I understand correctly)

**Comment by rasom** [comment]
@cammellos correct, should I add some comments there though?

**Comment by cammellos** [comment]
Comments never hurt I guess :)

**Review by cammellos — APPROVED** [review]

**Comment by rasom** [comment]
@annadanchenko should be fixed now

**Comment by rasom** [comment]
looks like it is not fixed though...

**Comment by cammellos** [comment]
@rasom there's also group chat that is missing https://github.com/status-im/status-react/blob/7cad165a66fbf3d80017c00684e6dc5cbeb553bf/src/status_im/group_chats/core.cljs#L132 
but probably that's not the problem you are referring to?

**Comment by cammellos** [comment]
We could also change strategy, rather than check if the user is in the contact, we could check if we are listening to that topic, in which case we send on that topic, otherwise discovery

**Comment by rasom** [comment]
> We could also change strategy, rather than check if the user is in the contact, we could check if we are listening to that topic, in which case we send on that topic, otherwise discovery

will try this

It also works locally, which is weird

**Comment by rasom** [comment]
@annadanchenko can we restart tests?

**Comment by annadanchenko** [comment]
> @annadanchenko can we restart tests?

@rasom I see build 5 is in progress. Should it wait for new build or fine to trigger tests on previous build 4?

**Comment by rasom** [comment]
should be fine with 4

**Comment by annadanchenko** [comment]
@rasom I still have an issue with group chats
on build 8 https://status-im-prs.ams3.digitaloceanspaces.com/StatusIm-190314-102902-34e1b1-pr.apk
on build 9 for ios https://i.diawi.com/jrtGRr
user A: ios
user B: Android

in group chat only once got message sent from user B to user A (user A is not in contact of B), same steps as  https://github.com/status-im/status-react/pull/7670#issuecomment-471945726
Screenshot_20190314-121131

[geth.log](https://github.com/status-im/status-react/files/2966076/geth.log)
[Status.log](https://github.com/status-im/status-react/files/2966077/Status.log)

**Comment by rasom** [comment]
group chats should be fixed now

**Comment by rasom** [comment]
@annadanchenko are there still some unsolved issues?

**Comment by annadanchenko** [comment]
> @annadanchenko are there still some unsolved issues?

there are no known issues atm, I'm in process of retesting upgrade, expect to finish in about 2 hrs

**Comment by annadanchenko** [comment]
@rasom what's interesting is that communication between PR build and 0.9.33 release is possible in 1:1 and group chat if the users are not in contacts of each other. As soon as they are contacts - 0.9.33 does not see messages from PR (expected behaviour for partitioned topic) Don't think it's a bug, just a note.

**Comment by annadanchenko** [comment]
for some reason last ios build 11 https://ci.status.im/job/status-react/job/prs/job/ios/job/PR-7670/11/ is not shown in Jenkins Builds comment https://github.com/status-im/status-react/pull/7670#issuecomment-469588448 but I was using ipa file from build 11 for final testing.

Screen Shot 2019-03-15 at 11 45 19

**Comment by annadanchenko** [comment]
@rasom upgrade looks ok. I'll move PR to merge on Monday, March 18 as was agreed https://github.com/status-im/status-react/pull/7670#issuecomment-471527940

**Comment by rasom** [comment]
ok, thanks @annadanchenko

**Pull request merged**
