### PR TITLE
fix: ROW_NUMBER() not work on ios for some reason

### LINKED ISSUE #16421: "DB is dirty after migration..." error on login by newly created user [IOS]
Reproducing on IOS 14.1, iPhone X

**Steps:** 

1. Proceed with creation of a new account (user will get stucked on Generating keys screen)
2. Reopen the app
3. Try to login multiaccount
4. Observe an error

**Actual result:**  "DB is dirty after migration..." error. Cannot login multiaccaunt

photo_2023-06-28 10 35 36

https://github.com/status-im/status-mobile/assets/97245802/632fe130-726f-446a-8dbe-60fb738f3ba2

### Additional Information

- Status version: nightly 
- Operating System: iOS

### PR DESCRIPTION
**Pull request by qfrank**
fixes #16421 

status: ready

### CODE REVIEW

**Comment by qfrank** [comment]
cc @churik @pavloburykh

**Review by siddarthkay — APPROVED** [review]

**Comment by pavloburykh** [comment]
> cc @churik @pavloburykh

thank you @qfrank! Waiting for review and approval of go PR https://github.com/status-im/status-go/pull/3687

**Comment by pavloburykh** [comment]
@qfrank still unable to log in. Now receiving error both on IOS and Android

### ISSUE 1 "failed to create bindata migration source..." error on login

**Steps:** 

1. Proceed with creation of a new account (user will get stucked on Generating keys screen)
2. Reopen the app
3. Try to login multiaccount
4. Observe an error

**Actual result:** "failed to create bindata migration source..." error on login

photo_2023-06-28 16 31 48

**Comment by qfrank** [comment]
emm.. shouldn't be, maybe because i rebased with latest `develop`, let me try to reproduce

**Comment by qfrank** [comment]
pls retry with the latest commit, thank you @pavloburykh

**Comment by pavloburykh** [comment]
@qfrank thank you for the fix! Now I am able to login multiaccount on both IOS and Android. Please take a look at the new issues. 

### ISSUE 2 Unable to perform manual backup 

**Steps:** 

1. Open backup settings: profile => sync settings => backup settings
2. Tap Perform backup button
3. See if backup has been performed

**Actual result:** backup has not been performed

[Status-debug-logs (36).zip](https://github.com/status-im/status-mobile/files/11895959/Status-debug-logs.36.zip)

https://github.com/status-im/status-mobile/assets/97245802/4d0d036f-2b85-4e47-b552-f114cd62984d

**Comment by pavloburykh** [comment]
### ISSUE 3 Sync results in errors on both sides

**Steps:** 

1. User A generates sync QR
2. User B scans QR
3. Observe the result

**Actual result:** sync failed. User A an User B observe following errors

**User A:** "no such column:include_watch_only_account"

photo_2023-06-28 17 39 52

**User B:**"[client] status not ok when receiving sync device data, received 500 Internal Error'

photo_2023-06-28 17 39 54

**Comment by qfrank** [comment]
Hi @pavloburykh , issue 2-3 should not be relate to this PR, it's relate to this [one](https://github.com/status-im/status-go/pull/3676), we can fix it in a separate PR. WDYT?

**Comment by pavloburykh** [comment]
@qfrank thank you! ISSUEs 2 and 3 are fixed. 

Though, I am experiencing troubles with pairing: 

1. IOS is crashing after scanning sync QR
2. Data is not being updated between pairing devices (or updating takes a long time)

https://github.com/status-im/status-mobile/assets/97245802/379b6940-349f-4716-803a-e96b504578d1

[Android_sync_log.zip](https://github.com/status-im/status-mobile/files/11904114/Android_sync_log.zip)
[IOS_sync.zip](https://github.com/status-im/status-mobile/files/11904115/IOS_sync.zip)

These issues will be addressed in followup after merging of this PR. 

@qfrank I am still waiting for the results of e2e re-run. Will ping you when PR will be ready for merge

**Comment by qfrank** [comment]
I think we can merge the PR first so that it won't block other ppl to create new account ... any other issue should not be relate to my fix... my fix is simple, also I got information from @cammellos , he said we changed the way we run tests in status-go, so there could be more issues comes out, I found new PRs (e.g. this [one](https://github.com/status-im/status-go/pull/3676) ) for status-go can be merged without pass test(run test in local will fail, but CI will ignore the failure)... that's why issue 2-3 comes out... 
@cammellos is working on this PR https://github.com/status-im/status-go/pull/3696 to fix the way we run test

**Comment by pavloburykh** [comment]
@qfrank failed e2e are not PR related. Ready for merge. Thank you for your work!

**Pull request merged**
