### PR TITLE
Feature/chat list optimized

### PR DESCRIPTION
**Pull request by maxhora**
Enable rendering optimization for chat list

Testing notes:

Very long list of active chats should not decrease application responsiveness.
No new crashes or unexpected behavior.

### CODE REVIEW

**Review by vitvly — APPROVED** [review]

**Review by yenda — APPROVED** [review]

**Review by vkjr — APPROVED** [review]

**Review by flexsurfer — APPROVED** [review]

**Comment by maxhora** [comment]
Adding high-priority since PR should address the issue which heavily affect user experience

**Comment by asemiankevich** [comment]
@MaxRis @yenda 

i have opened all the chats we have now in status.
i noticed status consumed 1 GB memory
keeping monitor opened i switched between chats (status / core / desktop) 15-20 times which increased memory consumption to 2GB in literally 40-50 seconds.

I am not sure this fix is effective. 

let me know better scenarios to test it or any further decisions.

**Comment by maxhora** [comment]
@asemiankevich this change doesn't resolve memory leaks issue.
It just automatically hides visual elements (chat) once they are not on the screen. This should allow to keep in the list more than 50 active chats, but UI responsiveness should not degrade (currently, it should degrade with increase of opened chats number).

**Comment by asemiankevich** [comment]
@MaxRis it is fine then! Sorry for the misunderstanding. Lets merge it.

**Comment by maxhora** [comment]
@asemiankevich thanks!

**Comment by chadyj** [comment]
@MaxRis can you take a look at this possibly related issue? https://github.com/status-im/status-react/issues/5960

Chat list and Message list will jump around when scrolling.

**Comment by maxhora** [comment]
@chadyj sure

**Pull request merged**
