### PR TITLE
[#11502] Handle tx fetching failure

### LINKED ISSUE #11502: Sometimes pull-ro-refresh in individual account view leads to endless spinner
# Bug Report

## Problem
Following to https://github.com/status-im/status-react/pull/11478#issuecomment-736486097

Sometimes on switching to WI-Fi from cellular network or when WI-FI signal is weak.
Also faced with this issue after getting 429 error (too many requests) in e2e (@rasom please tell me if it should be reported separately)
image

#### Expected behavior
Info that transaction cannot be fetched or transaction history

#### Actual behavior
endless spinner;
even if you switched to WI-FI, transaction history still can't be downloaded until relogin

### Reproduction

1) restore multiaccount from seed phrase when on cellular network
2) open individual account view
3) pull-to-refresh

### Additional Information

[comment]: # (Please do your best to fill this out.)
- Status version: nightly 02/12/20
- Operating System: Android, iOS

#### Logs
- From e2e:
Session of e2e: https://app.saucelabs.com/tests/48645b9793b34e5f8ca37fdcd05f54f9?auth=54f95a473cd8a89c7b83a1d367e1440f#114
Logcat: [logcat.log](https://github.com/status-im/status-react/files/5624053/logcat.log)

- IOS (cellular network): 
https://github.com/status-im/status-react/files/5622297/status_logs.zip

### PR DESCRIPTION
**Pull request by rasom**
fix #11502

status: ready

### CODE REVIEW

**Review by flexsurfer — APPROVED** [review]

**Comment by rasom** [comment]
@churik @Serhy this one should be ready for testing now

**Comment by Serhy** [comment]
@rasom when using Status with no WiFi/mobile network there is an popup error appears:

Screenshot 2020-12-07 at 17 21 34

And everytime pull-to-refresh is made in wallet the same error occurs. I think it's enough in that case to ignore this error (to not display). 

To reproduce:
1) Turn off all networks on device
2) Open Status and login to account (or create / recover an account while offline)

**Comment by rasom** [comment]
@Serhy well that's expected behaviour at the moment, we can't fetch history if we have no connection. The question is rather how do we want to proceed with it. Do we wan't to disable pull to refresh if no connection, show different error, keep this one or other option?

probably @hesterbruikman @errorists know, or @churik has ideas

**Comment by rasom** [comment]
imo just ignoring error isn't ideal, I'm fine if we do that though

**Comment by churik** [comment]
@rasom 
IMO to show more user-readable error should be OK for this case. will ask @hesterbruikman

**Comment by hesterbruikman** [comment]
Thanks for the ping @churik 

@rasom here's the error state design: https://www.figma.com/file/XUehMnhyD1FGcWzvGz6SXqvh/Wallet?node-id=4183%3A797

I made a minor copy update to cover for the case where the user is not connected to internet. 
"Balance could not be updated. Check your connection and pull down to try again"

Can you let me know if you see any issues with that?
Error loading

**Comment by churik** [comment]
@rasom any updates here?

**Comment by rasom** [comment]
@churik not yet, will continue today

**Comment by rasom** [comment]
@churik updated PR

**Comment by churik** [comment]
Thanks @rasom, last build looking good.
Tested:
- pull-to-refresh offline (errors appears) -> pull-to-refresh online
- restoring multiaccount on LTE -> pull-to-refresh 
- handling online/offline/cellular tx history cases 

e2e failures are not related to PR.
Tested basic flows, LGTM!

**Devices:**
- IPhone 12 Mini (IOS 14)
- IPhone 7 (IOS 13)
- Xiaomi Mi Note 9 Pro (Android 10)

**Comment by joeleonjr** [comment]
Hi! I'm a security researcher @TruffleSecurity. I found a valid API key leaked in a comment in this Issue. I highly recommend rotating the API key immediately (not just deleting the comment). Here's a blog post I wrote on remediating these types of vulnerabilities: https://trufflesecurity.com/blog/remediate-leaked-api-keys-with-key-rotation.<br><br>If you can't find the leaked API key, you can use the following [TruffleHog](https://github.com/trufflesecurity/trufflehog) command to automatically scan for it:<br>`trufflehog github --repo https://github.com/<your_username>/<your_reponame> --issue-comments --only-verified`<br><br>If it's not clear where/what the security issue is, please let me know. I'd be happy to help. Please note that the API key might be in the past edit of a comment.<br><br><br><br>(cc @status-im-auto)

**Pull request merged**
