### PR TITLE
[#14962] Update AC notification on EditMessage

### LINKED ISSUE #14962: Mentions and replies are not updated in AC in case they were edited by sender in chat
Affects both community channels and group chats

**Preconditions:** Users A and B are mutual contacts and members of the same group/community. 

**Steps:**
1. User A generates mention and reply notifications for User B
2. User A edits message containing mention/reply
3. Open AC by User B and see if text of reply/mention has been updated in notifications. 

**Actual result:** AC is empty, all unread notifications disappeared. 

**Expected result:** only notification for deleted message should disappear. The rest of unread notifications should remain in AC. 

https://user-images.githubusercontent.com/97245802/216122450-687e6176-25fa-4f20-bd42-1569185f13e4.mp4

[User_A.zip](https://github.com/status-im/status-mobile/files/10559954/User_A.zip)
[User_B.zip](https://github.com/status-im/status-mobile/files/10559956/User_B.zip)

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by rasom**
fix #14962

status: ready

### CODE REVIEW

**Review by flexsurfer — APPROVED** [review]

**Comment by qoqobolo** [comment]
Hi @rasom, could you rebase the PR, please

**Comment by rasom** [comment]
@qoqobolo done

**Comment by qoqobolo** [comment]
@rasom can you pls rebase again? Jakub just pushed the fix for e2e.
Thanks!

**Comment by rasom** [comment]
@qoqobolo done

**Comment by qoqobolo** [comment]
Thanks @rasom!
Sorry for the delay with merging, we're trying to catch one nasty crash which is reproducible better in PRs.
I'll let you know when it's ready to go.

**Comment by qoqobolo** [comment]
@rasom thanks for waiting!
There is still some mysterious crash in tests, but hopefully, it's fixed [here](https://github.com/status-im/status-mobile/pull/14985).
PR can be merged once iOS builds are fixed.
Thank you

**Pull request merged**
