### PR TITLE
[#11499] Fix multiple notifications for a single erc20 transfer

### LINKED ISSUE #11499: Several wallet push notifications are arrived for sender when sending tokens
# Bug Report

## Problem
When sending some assets from wallet several PNs are coming for sender, which is confusing.
Reproduced in develop 01/12/2020.
Was found during testing  https://github.com/status-im/status-react/pull/11478

##  **Steps:**
1) restore multiaccount from seed phrase
2) enable wallet transactions
3) send tokens to another multiaccount

##  **Expected result:**
1 PN

##  **Actual result:**
several PNs (2-3)
IMAGE 2020-12-01 11:30:16

**OS:** IOS, Android

### PR DESCRIPTION
**Pull request by rasom**
fix #11499

status: ready

### CODE REVIEW

**Review by flexsurfer — APPROVED** [review]

**Comment by qoqobolo** [comment]
@rasom unfortunately #11499 is still reproducible. 
The first notification is received when the app is in the background, and the second when it returns to the foreground.
Note that this is true for ETH as well (not just for tokens).

**_Steps:_**

- Send transaction
- Wait for the first notification while the app is in the background
- Tap the notification to open the app

[geth.log](https://github.com/status-im/status-react/files/5666726/geth.log)
[Status.log](https://github.com/status-im/status-react/files/5666727/Status.log)

ezgif com-gif-maker (12)

**Comment by rasom** [comment]
@qoqobolo 
> The first notification is received when the app is in the background

that's interesting because we shouldn't receive PN in background at the moment

**Comment by qoqobolo** [comment]
@rasom just rechecked: sender received PN in background again (at least on Android)

**Comment by qoqobolo** [comment]
@rasom 
[geth.log](https://github.com/status-im/status-react/files/5672158/geth.log)
[Status.log](https://github.com/status-im/status-react/files/5672159/Status.log)

**Comment by rasom** [comment]
@qoqobolo should be fixed now

**Comment by qoqobolo** [comment]
@rasom now tx notifications are not received at all :( 

logs:
[Sender](https://github.com/status-im/status-react/files/5678508/Status-debug-logs.3.zip)
[Receiver](https://github.com/status-im/status-react/files/5678513/status_logs.1.zip)

**Comment by rasom** [comment]
@qoqobolo 
fixed

**Pull request merged**
