### PR TITLE
 [Fix #3477] Add accessibility labels for New Chat screens 

### LINKED ISSUE #3477: Add accessibility labels for New Chat screens
### User Story
As an automation engineer I need accessibility labels to be added for specific elements so I could use them in my Appium scripts.

### Description
Accessibility labels are required for building stable mobile test automation solution. Please, add accessibility labels for all elements listed below.

### Related Issues
- #3394
- #3472

#### New chat
- back-button
- start-1-1-chat-button
- start-group-chat-button
- join-public-chat-button
- open-dapp-button
- invite-friends-button

#### New 1-1 chat
- back-button
- done-button (if contact is selected)
- enter-contact-code-input
- scan-contact-code-button
- contact-item

#### Scan contact QR code
- back-button

#### New group chat
- back-button
- next-button (if contact is selected)
- contact-item
  - checkbox-button

#### Provide group chat name
- back-button
- create-button
- chat-name-input
- chat-member-item

#### Join public chat
- back-button
- next-button
- chat-name-input

#### Open DApp
- back-button
- dapp-url-input
- dapp-item
  - dapp-name

#### DApp profile
- back-button
- dapp-name-text
- open-dapp-button

#### DApp screen
- back-button
- dapp-name-text
- previou-page-button
- next-page-button

### PR DESCRIPTION
**Pull request by foopang**
### Summary:
Fix #3477
Add accessibility labels for New Chat screens

status: ready

### CODE REVIEW

**Review by jeluard — APPROVED** [review]

**Review by yevh-berdnyk — APPROVED** [review]

**Comment by yevh-berdnyk** [comment]
@foopang looks good, thank you. I've checked all labels from the PR

**Comment by lukaszfryc** [comment]
@yevh-berdnyk could you take a look at the test results? Why 12 tests failed? Please push the updated test code here and run the tests again. 

Goal should be to have 100% tests passed before merging this PR.

**Comment by yevh-berdnyk** [comment]
@lukaszfryc these tests are failing not due to current changes, @antdanchenko is working on them
@foopang please fix conflicting files and let's merge it

**Comment by foopang** [comment]
@yevh-berdnyk good to merge now. Thanks!

**Pull request merged**
