### PR TITLE
Non-bundle build logging to file support; Custom log path with STATUS…

### PR DESCRIPTION
**Pull request by maxhora**
…_LOG_PATH env var.

- Redirects app output for "non-bundle" build to file on disk by default;
- Reads STATUS_LOG_PATH env var for creation of log file with custom file path.

### CODE REVIEW

**Comment by vkjr** [comment]
@MaxRis, any reason to always output log to file?
For me it looks like having output in console during dev session is more convenient than watching it in a separate text editor.

**Comment by maxhora** [comment]
@vkjr if all logs are turned on, the amount of texts is really big and depending on used terminal app not all log might be available to look at and text searching capabilities of terminal window app are usually low.
I was much happier when log output file was opened, for example, in MS Code editor and received constants updates automatically on log file change (MS Code works by default in this manner).
Also just setting of `STATUS_LOG_PATH` to some another path and running app from terminal will bring possibility to compare new and older log texts files without any additional extra actions.

It makes sense still to have possibility to print logs to console, but really not sure what is more usable for devs. Some time ago I have seen requests to have ability to redirect log output into file.

**Review by vitvly — APPROVED** [review]

**Comment by vitvly** [comment]
@MaxRis can you please also update docs.status.im repo with a note on specifying log file name?

**Comment by maxhora** [comment]
@siphiuel yes, sure, will do once we will reach some agreement on final changes for that PR :)

**Review by pedropombeiro — APPROVED** [review]

**Review by vkjr — APPROVED** [review]

**Comment by asemiankevich** [comment]
@MaxRis @siphiuel any changes still pending here? how we can proceed with this PR ? looks it is a bit stuck in `to test` :)

**Comment by maxhora** [comment]
@asemiankevich thank you for reminder! Yes, I've just updated the changes according to the received feedback.
@vkjr @siphiuel 
```
"STATUS_LOG_FILE_ENABLED" == 1 // Env var enables debug output redirect into log file with default path

STATUS_LOG_PATH // Sets custom log file path
```

Will update docs accordingly

**Comment by churik** [comment]
Doesn't affect Mac OS build, waiting for automation tests results.

**Comment by maxhora** [comment]
@churik going to merge this, thanks

**Comment by maxhora** [comment]
Docs will be updated with related PR https://github.com/status-im/status.im/pull/117

**Pull request merged**
