### PR TITLE
fix keycard account shown as regular account on theme change while login

### LINKED ISSUE #13740: Keycard account is displayed as regular on login screen after switching dark/light mode
# Bug Report

## Problem 
_This is an edge case, but might be worth a look. Feel free to close if you think it's a `won't fix`._ 

There are two scenarios for regular and keycard accounts.

### 1. Keycard account [still relevant]

**Steps (same as for regular account):**
1. Create a keycard account on an Android device
2. Close the app
3. Open the app and very quickly tap the overview system Android button (square one) while the splash screen is shown
4. Change the mode of device from dark to light or wise versa
5. Open the app

**Actual result**: 

Two types of behavior were found on different Android devices.
- on Huawei P40 Lite: regular account is opened instead of keycard account; cannot log in until re-opening the app

https://user-images.githubusercontent.com/67952253/182149476-0d19033a-c7a4-4005-a592-965ac267a60c.mp4

- on Pixel 2: error (until re-opening the app)

Screenshot 2022-08-01 at 14 38 46

### 2. Regular account [FIXED in #13759, kept for context]

**Steps:**
1. Create a new account on an Android device
2. Close the app
3. Open the app and very quickly tap the overview system Android button (square one) while the splash screen is shown
4. Change the mode of device from dark to light or wise versa
5. Open the app

**Actual result**: error `Cannot read property 'root' of null`; reopening helps
**Expected result**: no error

https://user-images.githubusercontent.com/67952253/182148156-941420b0-821c-4aec-a98e-93b4b3296de5.mp4

### Additional Information

- Status version: 1.19
- Operating System: Android

### PR DESCRIPTION
**Pull request by Parveshdhull**
fixes: https://github.com/status-im/status-mobile/issues/13740

status: ready

### CODE REVIEW

**Comment by Seifollahy** [comment]
> fixes: https://github.com/status-im/status-mobile/issues/13740
> 
> status: ready

**Review by flexsurfer — APPROVED** [review]

**Comment by qoqobolo** [comment]
@Parveshdhull thanks again for the fix and for finding the broader issue!

Found another place where it's still reproducible: `Your keys` screen

**STR:**
1. Log out of keycard account
2. Tap back on the login screen
3. Change theme


https://user-images.githubusercontent.com/67952253/188122072-3ff61e4c-832c-46e0-81c9-3c3f1279343e.MP4

**Comment by Parveshdhull** [comment]
Hi @qoqobolo,

Thank you for finding this issue, it is fixed now.

But root stack for multi-accounts is created in a way that on initialization it also opens the `login screen`. I can navigate back to the `Your keys` screen, but that looks like an unnecessary step.

So for now, on theme change (on the `Your keys` screen), it will also navigate to the corresponding login screen.
 If the account is a keycard account, then the keycard account login screen, otherwise a regular account login screen.

Will this be ok?

**Comment by qoqobolo** [comment]
> Thank you for finding this issue, it is fixed now.

Works great!

> So for now, on theme change (on the Your keys screen), it will also navigate to the corresponding login screen.
If the account is a keycard account, then the keycard account login screen, otherwise a regular account login screen.
Will this be ok?

Sure, sounds good. I tried with several accounts - regular and keycard, and everything is fine.
Thank you for the fix, @Parveshdhull!

Now we have to wait until e2e are fixed to run them in this PR, Chu is working on it in #13920 and is about to finish.
Thanks for waiting!

**Comment by qoqobolo** [comment]
@Parveshdhull PR is ready to be merged.
Thanks!

**Pull request merged**
