### PR TITLE
Kotlinify some of react-native-status android module

### PR DESCRIPTION
**Pull request by siddarthkay**
### Summary

This PR adds `Kotlin` plugin to native module `react-native-status` and converts these files to `Kotlin` : 
- `modules/react-native-status/android/src/main/java/im/status/ethereum/module/RNSelectableTextInputViewManager.java`
- `modules/react-native-status/android/src/main/java/im/status/ethereum/module/RNSelectableTextInputModule.java`

### Platforms
- Android

### Testing Notes
This PR simplifies the implementation of input text formatting which was introduced here : https://github.com/status-im/status-mobile/pull/14249
as mentioned here : https://github.com/status-im/status-mobile/issues/14423#issuecomment-1635727851 this feature is tagged as post MVP.
In this case just a smoke test of android chat view is enough.

status: ready

### CODE REVIEW

**Comment by siddarthkay** [comment]
@status-im/mobile-qa : hmmm 6% E2E passing means something definitely broke. Could you pls tell me few major cases for failure and I'll try to fix them.

**Comment by siddarthkay** [comment]
@status-im/mobile-qa : not urgent btw, this can wait until next year 😃

**Comment by siddarthkay** [comment]
I see this issue, will fix : 

0025screenshot

**Review by mohsen-ghafouri — APPROVED** [review]
🚀

**Review by ilmotta — APPROVED** [review]
So nice to see these piece-meal PRs. Thanks @siddarthkay 🚀

**Review by qfrank — APPROVED** [review]

**Comment by qoqobolo** [comment]
Thanks @siddarthkay, everything looks good to me.
PR can be merged.

**Comment by siddarthkay** [comment]
@qoqobolo : Thanks for testing :)

**Pull request merged**
