### PR TITLE
fix broken screen and navigation when syncing fails

### LINKED ISSUE #20885: Broken screen when syncing fails
# Bug Report

## Problem 

Upon failure in the syncing process, we present a broken screen to the user both in the onboarding and from the settings screen. The second problem is that the `Try again` button doesn't work **when the user is syncing from within the settings**.

#### Expected behavior

It should look as in Figma https://www.figma.com/design/V6nlpAWIf2e1XU8RJ9yQPe/Syncing-for-Mobile?node-id=675-179635&t=btGB9vN5GCYgNE5i-0 as this should be a straightforward implementation.

Additionally, the user should be able to retry the syncing process, as if they started from scratch. After pressing `Try again`, we should bring the user back to the `Scan Sync Code screen`, so that they can decide if they want to use the sync code or scan a QR code.

https://www.figma.com/design/V6nlpAWIf2e1XU8RJ9yQPe/Syncing-for-Mobile?node-id=675-179635&t=btGB9vN5GCYgNE5i-0

#### Actual behavior

1. The screen looks broken.
2. While syncing from within the settings (thus logged in), the user presses on `Try again`, the modal just closes and no action is taken.

Note: the PR from https://github.com/status-im/status-mobile/pull/20883 @Parveshdhull already fixed the screen not expanding correctly.

### Reproduction

1. Open the desktop app and copy the sync code. The desktop version doesn't matter.
2. Close the desktop app.
3. Open the mobile app and paste the sync code in `Settings > Syncing > Add > Scan or enter sync code`
4. Optionally, press on the `Try again` button to see it just closes the modal.

Any failure on the sync process will cause the error screen to be displayed, but the above steps are a sure way to reproduce.

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

### PR DESCRIPTION
**Pull request by Parveshdhull**
fixes https://github.com/status-im/status-mobile/issues/20885

### Summary
Manually tested failed flow on all three screen (from onboarding, from login and from settings). Also tested success flow from login screen.

status: ready

### CODE REVIEW

**Review by ilmotta — APPROVED** [review]
Thanks @Parveshdhull!

Just one detail, which we can solve in a separate PR if you prefer, it's not a blocker, the four images are adding around 2.7MB. That's a lot for just 4 images. If we compress they should each individually probably be no more than 150KB (when I compare with other backgrounds we have in the repo) if we use the compression solution used in this PR https://github.com/status-im/status-mobile/pull/20076.

@jo-mut would have more context to help.

**Comment by jo-mut** [comment]
> Thanks @Parveshdhull!
> 
> Just one detail, which we can solve in a separate PR if you prefer, it's not a blocker, the four images are adding around 2.7MB. That's a lot for just 4 images. If we compress they should each individually probably be no more than 150KB (when I compare with other backgrounds we have in the repo) if we use the compression solution used in this PR #20076.
> 
> @jo-mut would have more context to help.

ooooh yeah I can compress these images with the script. I somehow got caught up and forgot about the script for reducing the image sizes. I could compress the images and push them to this pr and get back to working on that script if thats okay with you @Parveshdhull

**Comment by Parveshdhull** [comment]
> ooooh yeah I can compress these images with the script

Thank you @jo-mut and @ilmotta. Lets merge the fix for now and we can compress images in separate PR. (Will create an issue for that and ping you @jo-mut, thank you for helping)

**Comment by mariia-skrypnyk** [comment]
Hi @Parveshdhull !

Thanks for a such important fix!
Looks good on both platforms except of two minor things that I will add as followups.
Please merge your PR as it is. It's very needed for the release.

I will create separate low issues for these:

1. `Try again` is too low for `iOS `

Screenshot 2024-07-26 at 15 28 34

2. Text area for code is prefilled with data after you `Try again`

Screenshot 2024-07-26 at 15 28 43

**Pull request merged**
