### PR TITLE
Delivered messages marked in private chats

### LINKED ISSUE #11439: Add "delivered" message confirmations to 1-to-1 messages
```
As a user
I want to know my message has been delivered to the recipient
So that I have confidence that it will eventually be read
```

### Description

Next to each 1-to-1 sent chat message there should be an icon indicating the state of the message:

- The message is actually being sent (I will refer to it as the `sending` state)
- The message has been propagated to the network (I will refer to it as the `sent` state)
- The message has reached its destination (I will refer to it as the `delivered` state)

### Out of scope

- Private group chats
- Public chats
- Transaction messages

### Designs

https://www.figma.com/file/aS1ct66VQ6V0cio7vSqS8UoG/Chat?node-id=1%3A2

### Implementation details

-  A message can be marked as `delivered` once is acknowledged at the datasync level https://github.com/vacp2p/mvds 
  This information is not currently available and need to be surfaced, so it might required a change to the library above.
  Also note that datasync sends messages in batches, so it might be that a single datasync message includes multiple chat messages.

### PR DESCRIPTION
**Pull request by vkjr**
fixes #11439

### Summary

Client listens for `message.delivered` signal from `status-go` and mark messages with double-check icon:

Screenshot 2021-02-16 at 14 25 48

Works only for 1-1 chats

#### Platforms
- Android
- iOS

##### Functional

- 1-1 chats
- public chats
- group chats

### Steps to test
- Open private chat between Alice and Bob
- Open client for Alice and send message to Bob
- make sure message marked as sent but not delivered
- Login into Bob client
- make sure message now marked as delivered for Alice

status: ready

### CODE REVIEW

**Review by cammellos — APPROVED** [review]

**Comment by churik** [comment]
@vkjr 
can you please add accessibility ids for message statuses ("confirmed", "delivered"?)
It will help to automate it quickly.
Thank you!

**Comment by vkjr** [comment]
@churik, done

**Comment by qoqobolo** [comment]
@vkjr thanks for your work!

Checked:
- both devices are logged in and in foreground
- both devices are logged in, one of it is in background
- one device is logged out (app is closed)
- receiver was forcibly logged out (from settings)
- send message to device with PN background service enabled (Android)
- send messages to iOS device, which has been logged out after being in background (~3 mins for iOS)
- switching between online and offline
- on mobile network
- with status nodes disabled
- after switching to another status node (including custom node)
- all message types (text, reply, link, tag, mentions, long collapsed messages)
- sending messages to user with ENS
- public and group chats (no changes)

PR is ready to be merged.

**Comment by vkjr** [comment]
thanks for testing!

**Pull request merged**
