### PR TITLE
Revert "Fix message ordering for 1-1 chats"

### PR DESCRIPTION
**Pull request by cammellos**
This reverts commit 7efcdcb15046c6b6fdfa2d03965a3af00fb9c5a7.

We decided to revert this commit as it introduced a couple of issues in
message ordering. In order to release we revert back to the old
behaviour.

status: ready

### CODE REVIEW

**Review by yenda — APPROVED** [review]

**Review by flexsurfer — APPROVED** [review]

**Comment by flexsurfer** [comment]
@cammellos could you resolve conflicts please

**Comment by cammellos** [comment]
@flexsurfer done!

**Comment by janherich** [comment]
@cammellos What are the "couple of issues" this revert fixes, can you point me to them ?
How is possible that those issues were release blockers (that's why this revert was merged), while the original issue (https://github.com/status-im/status-react/issues/2699) the reverted commit solved (now again happening, and marked as high priority before) was not release blocker ?
Basically, I would much rather solve those particular issues, then revert the whole commit.

**Comment by cammellos** [comment]
@janherich As mentioned this was a shared decision, I just happen to have pulled the trigger :) I have sent you a link with the discussion on slack, the issues are mentioned there. In terms of release blockers etc I am afraid I don't have context, but the test team will be able to answer those questions.

**Pull request merged**
