### PR TITLE
ci: upgrade Xcode from 14.2 to 14.3

### PR DESCRIPTION
**Pull request by jakubgs**
https://developer.apple.com/documentation/xcode-release-notes/xcode-14_3-release-notes

Related: https://github.com/status-im/infra-role-bootstrap-macos/commit/30656dc0

### CODE REVIEW

**Comment by jakubgs** [comment]
And it looks like iOS build explodes due to:
```
❌  /Users/jenkins/workspace/status-mobile_prs_ios_PR-15581/node_modules/react-native/ReactCommon/yoga/yoga/Yoga.cpp:2285:9: use of bitwise '|' with boolean operands [-Werror,-Wbitwise-instead-of-logical]

        node->getLayout().hadOverflow() |
                   ^~~~~~~
```
Which appears to have been fixed in Yoga already:

* https://github.com/facebook/yoga/commit/f174de70afdde2492e8677bd0e716eb41bf64469 - Use logical operator instead of bit operation

And there's no releases with this fix included. Last [1.19.0](https://github.com/facebook/yoga/releases/tag/v1.19.0) release is from May of 2021.

**Comment by siddarthkay** [comment]
A fix for Xcode 14.3 was probably patched yesterday in react-native 0.69.9 : https://github.com/facebook/react-native/releases/tag/v0.69.9
 and other newer versions 0.70 and 0.71 
 not sure if its related to this error

**Comment by jakubgs** [comment]
Thanks to this fix we can now try to proceed:

* https://github.com/status-im/status-mobile/pull/15589

**Review by flexsurfer — APPROVED** [review]

**Comment by jakubgs** [comment]
I believe we are putting this on-hold until the release is out. Unless for some reason we want Xcode `14.3` for the `1.23` release.

**Review by cammellos — APPROVED** [review]

**Comment by churik** [comment]
The next release is planned for the end of May, so I believe we're ready to go -  1.22 is already out

**Pull request merged**
