### PR TITLE
Design note fixes (#15781)

### LINKED ISSUE #15781: Design notes: generate keys flow > profile name screen
## Problem 
Suggestions/issues on implementation in Figma are [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS/Feedback-for-Mobile?node-id=1908-165988&t=IygHPkoLwgiVR8Xa-4)

### Profile name
- [ ] Change paddings (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1908:165988#428217503))
- [ ] Check avatar size (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1908:165988#428005167))
- [ ]  Check initial text size (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1908:165988#428005420))
- [ ] Align photo icon to the avatar (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1908:165988#428006053))
- [ ]  Make edit box focused by default with opened keyboard (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1908:165988#428007727)) 
- [ ] "Name" shouldn't start with a capital letter (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1908:165988#428008049))
- [ ]  Check font size of placeholder(full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1908:165988#428217177))
- [ ]  Medium font size for "Accent colour"(full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1908:165988#428011481)) 
- [ ]  Change the background according to design (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1908:165988#428189441)) 

### Avatar drawer

- [ ]  Check icon design/size (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1908:165988#428200533)) 
- [ ]  Check drawer background (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1908:165988#428203070)) 

### Profile name - errors
- [ ]  "Special chars are not allowed" - Check size, design, distance to the text.... (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1908:165988#428266752)) 
- [ ]  Flickering screen on focus (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1908:165988#428273559)) 
Video (slowed down 1/4X)

https://user-images.githubusercontent.com/4557972/235442939-54820d73-062d-459e-a9dd-5ef9b7b1036a.mp4

### PR DESCRIPTION
**Pull request by erikseppanen**
fixes #15781

### Profile name
- [X] Change paddings (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1908:165988#428217503))
  - No changes: paddings/spacing looks accurate
- [X] Check avatar size (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1908:165988#428005167))
  - Confirmed: correct size = 48 (same as figma)
- [X] Check initial text size (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1908:165988#428005420))
  - Confirmed: :heading-2, font size: 19px
- [X] Align photo icon to the avatar (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1908:165988#428006053))
- [X] Make edit box focused by default with opened keyboard (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1908:165988#428007727)) 
  - Q: Is iOS, I cannot open the keyboard unless focus is already in the edit box
- [X] "Name" shouldn't start with a capital letter (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1908:165988#428008049))
  - Fixed in translations/en.json
- [X] Check font size of placeholder (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1908:165988#428217177))
  - Confirmed: :heading-2, font size: 19px
- [X] Medium font size for "Accent colour" (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1908:165988#428011481)) 
  - Fixed: Added ":weight :medium" (weight was not specified).
- [X] Change the background according to design (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1908:165988#428189441)) 
  - Figma Notes:
    This background is wrong:
    Only has to appear when button covers top content (colours)
    It's too dark, check design here: https://www.figma.com/file/o4qG1bnFyuyFOvHQVGgeFY/Onboarding-for-Mobile?node-id=6345%3A327366&t=azdmhomknDfXwYtl-1
  - Recommend this be added as a new issue: this appears to be a new UX feature (I don't see any place where this is already implemented).
  - pavloburykh: "Logged a separate issue to track that #16181"

### Avatar drawer
- [X] Check icon design/size (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1908:165988#428200533)) 
  - Confirmed: camera icon is correct image, and is 20x20 (gallery image is correct as well)
- [X] Check drawer background (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1908:165988#428203070)) 
  - Figma Note: Check drawer background, looks like dark theme, not blur theme
  - Recommend deferring this issue since blur implementation hasn't stabilized yet for iOS/Android.
  - J-Son89: "I imagine this is just a generic solution for bottom sheets so not necessary to fix in your issue/pr imo"

### Profile name - errors
- [X] "Special chars are not allowed" - Check size, design, distance to the text.... (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1908:165988#428266752)) 
  - Figma Notes: Icon is broken: Check size, design, distance to the text....
  - Icon size: correct (16)
  - Icon design: correct (info)
  - Distance to text: 'info-message' component modified as below:
    - removed extra icon container
    - changed text padding from 8 to 4
    - added align-items: center 
- [X] Flickering screen on focus (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1908:165988#428273559)) 
Video (slowed down 1/4X)
  - Figma Note: When you tap to focus on the name input, the title "Create profile" disappears for a second and the content jump

https://user-images.githubusercontent.com/4557972/235442939-54820d73-062d-459e-a9dd-5ef9b7b1036a.mp4

### Avatar selector
- [X] Flickering screen on selecting profile photos(full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1908:165988#428294187), video is [here](https://drive.google.com/file/d/1JCZSsSNYy_2Q5UGoHOhQg6gJo_r_-K5K/view))
  - In the video, the photo is selected, which triggers the screen to be minimized while the photo fades out. Then the photo selection suddently appear for a split second (the flicker).
  - When I attempted to reproduce, the flicker did not occur.
  - J-Son89: "Afaik the flickering on image select is an issue with the package- https://github.com/ivpusic/react-native-image-crop-picker/issues/1658 I believe they have fixed it and once we upgrade the dependency then we will get that fix for free."

status: ready

### CODE REVIEW

**Review by flexsurfer — APPROVED** [review]

**Comment by flexsurfer** [comment]
hey @erikseppanen could you fix lint pls

**Review by smohamedjavid — APPROVED** [review]

**Comment by smohamedjavid** [comment]
> Make edit box focused by default with opened keyboard (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1908:165988#428007727))
Q: Is iOS, I cannot open the keyboard unless focus is already in the edit box

Passing `:auto-focus true` key-val to `title-input-props` in `quo/profile-input` might solve the issue.

**Comment by pavloburykh** [comment]
@erikseppanen hello! Thanx for the PR. Please add request-manual-qa label when PR will be ready for testing.

**Comment by J-Son89** [comment]
@erikseppanen Afaik the flickering on image select is an issue with the package- https://github.com/ivpusic/react-native-image-crop-picker/issues/1658
I believe they have fixed it and once we upgrade the dependency then we will get that fix for free.

**Comment by J-Son89** [comment]
Re: the note for "Check drawer background" - I imagine  this is just a generic solution for bottom sheets so not necessary to fix in your issue/pr imo

**Review by J-Son89 — APPROVED** [review]
Looks great. Can you please be sure to verify these visual changes with iPhone 11 Pro (or iPhone 12 Pro), from the description I believe you have but just commenting to be sure 👍

**Comment by pavloburykh** [comment]
Thank you for the fixes @erikseppanen ! Please take a look at the following issues

### ISSUE 1 Photo icon is not aligned to the bottom

> Q: In Figma itself the photo icon is not aligned to the bottom with the avatar (it's 1 pixel higher). iOS matches Figma.

@erikseppanen  could you please re-check the designs. It seems that photo icon is aligned to the bottom with the avatar according to Figma. 

https://www.figma.com/file/o4qG1bnFyuyFOvHQVGgeFY/Onboarding-for-Mobile?type=design&node-id=2241-250931&t=1ZK8iQJxoF5AkmGs-0

Onboarding for Mobile – Figma 2023-06-05 12-38-55

**Comment by pavloburykh** [comment]
### ISSUE 2 Flickering screen on focus 

> Flickering screen on focus (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1908:165988#428273559))
Video (slowed down 1/4X)
Figma Note: When you tap to focus on the name input, the title "Create profile" disappears for a second and the content jump
Can't reproduce this behavior

@erikseppanen I am able to reproduce on my iPhone X, IOS 14.1 

Could you try the following preconditions: fresh install, app is closed (not backgrounded) 

**Steps:** 

1. Open the app
2. Proceed to Create profile screen
3. See if there is flickering on focus

**Actual result:** there is flickering when Create profile screen is opened for the first time. If to go back end re-enrer the screen - flickering does not occur. 


https://github.com/status-im/status-mobile/assets/97245802/6f089220-9d22-49f1-be58-020114ef23b5

**Comment by pavloburykh** [comment]
> Change the background according to design (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1908:165988#428189441))
Figma Notes:
This background is wrong:
Only has to appear when button covers top content (colours)
It's too dark, check design here: https://www.figma.com/file/o4qG1bnFyuyFOvHQVGgeFY/Onboarding-for-Mobile?node-id=6345%3A327366&t=azdmhomknDfXwYtl-1
Recommend this be added as a new issue: this appears to be a new UX feature (I don't see any place where this is already implemented).

Logged a separate issue to track that https://github.com/status-im/status-mobile/issues/16181

**Comment by erikseppanen** [comment]
> Looks great. Can you please be sure to verify these visual changes with iPhone 11 Pro (or iPhone 12 Pro), from the description I believe you have but just commenting to be sure 👍

Thanks @J-Son89! Yes, my default simulator is iPhone 11 Pro

**Comment by erikseppanen** [comment]
@pavloburykh Issues 1 & 2 are fixed

**Comment by pavloburykh** [comment]
@erikseppanen thank you for the fixes. Ready for merge.

**Pull request merged**
