### PR TITLE
Upgrade status-go and turn chaos mode on

### PR DESCRIPTION
**Pull request by cammellos**
Call `status-go` when chaos mode is toggled.
status: ready

### CODE REVIEW

**Review by mandrigin — APPROVED** [review]

**Review by rasom — APPROVED** [review]

**Comment by annadanchenko** [comment]
@cammellos on iOS if switch chaos mode off I still can't send test eth and have 500 error (for android it worked fine)

[geth.log](https://github.com/status-im/status-react/files/3003101/geth.log)
log from Console for StatusIm process: https://gist.github.com/annadanchenko/6a5c6bf1c68fbbf689f530b05783a7f6

**Comment by annadanchenko** [comment]
@cammellos also can't start app on Windows (no errors, no logs) asked for help from test team to confirm if it happens for them too

**Comment by Serhy** [comment]
MacOS build from https://ci.status.im/job/status-react/job/prs/job/macos/job/PR-7817/3/: 
- Can install -> replace previous build -> launch Status
- Can recover account
- Can create account -> receive text messages in 1-1 chat / public chat

**Comment by annadanchenko** [comment]
> @cammellos also can't start app on Windows (no errors, no logs) asked for help from test team to confirm if it happens for them too

ignore this, I have similar issue on nightly

**Comment by churik** [comment]
On Windows 10 Home:
1) can't start (will be reported separately)
On Linux 18.04:
1) can install, create new account or restore the existing account, send message in 1-1 chat

**Comment by cammellos** [comment]
Having some issues setting up my mac os, I don't have enough disk space to set up the new config with nixos, might take some fiddling as I might have to re-partition the hard drive, @rasom if you have any spare bandwidth would you mind taking over this one? otherwise I might just bite the bullet and try to fix the mac. Thank you.

**Comment by cammellos** [comment]
@antdanchenko next build should fix the issue. @rasom managed, nevermind, thanks!

**Comment by annadanchenko** [comment]
@cammellos yes, issue with sending tx after turning off chaos mode on ios is ok now. testing on Android and triggering autotests

**Pull request merged**
