### PR TITLE
[#5211] show welcome screen after account creation

### LINKED ISSUE #5211: Info text is shown instead of Welcome to Status picture on first sign in
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: There is info text shown instead of  Welcome to Status picture after user signs in for the first time

Now:
screenshot_20180718-112528

Expected:
screen shot 2018-07-18 at 10 23 34

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Install Status 
- Create new account
- Sign in and check content of the Home tab

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: nightly July 18 (0.9.23 (6212))
* Operating System: Android and iOS

### LINKED ISSUE #5212: No Push Notification permission is asked for iOS once new account created
***Type***: Bug

***Summary***: App doesn't asking to grant permission for PN during onboarding on iOS. Thus, no PN could be enabled for iOS for new users with the fresh build. Exactly the same issue we had fixed in the https://github.com/status-im/status-react/issues/4240

**Note**: In a case of upgrading from the previous version where permissions granted - works fine. 
The issue with the new accounts on a fresh build.  
**Note2**: apparently we lost it when removed Mixpanel check (along with the Welcome screen - reported in https://github.com/status-im/status-react/issues/5211). 

### Expected behavior
Status asks for PN permission when onboarding on iOS
This can be managed in settings then

### Actual behavior
No PN prompt when onboarding on iOS
No setting available to toggle

### Reproduction

- Instal fresh develop build (`0.9.23 (6212)`)
- Open Status app
- Tap 'Create account'
- Submit new password (create password screen + confirm password)
- Submit new account name
- Once on Home screen check whether pop-up asking about permissions appear

### Additional Information
* Status version: `0.9.23 (6212)` (500th Jenking nightly build)
* Operating System: iOS

#### Logs

TF session with logs: https://app.testfairy.com/projects/4803590-status/builds/8528574/sessions/4396589176/?accessToken=B9m3GOAh-77CFEN2hgEq4DyBO4s

<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803590-status/builds/8528574/sessions/4396589176/?accessToken=B9m3GOAh-77CFEN2hgEq4DyBO4s">TestFairy: Status 0.9.23 (6212) @2018</a></strong></div></blockquote>

### PR DESCRIPTION
**Pull request by rasom**
fix #5211
fix #5212 

status: ready

### CODE REVIEW

**Review by dmitryn — APPROVED** [review]

**Review by flexsurfer — APPROVED** [review]

**Review by mandrigin — APPROVED** [review]

**Review by janherich — APPROVED** [review]

**Comment by Serhy** [comment]
@rasom Welcome screen and the PN pop-up to grant permissions for notifications (on iOS) are back which is cool!

The only issue is that there is no "PN permissions pop-up" on iOS when account is recovered (however it'll appear if to create a new account as second account). We had this pop-up earlier right after Mixpanel screen for recovered accounts, - lets try to fix it here:
**Steps to reproduce:** 
1) Install fresh build on iOS
2) Open Status
3) Navigate to 'Add existing account'
4) Fill in the valid recovery phrase and password and submit
5) On Home screen check whether `Status would like to send you notification` pop up appears.

TF session: https://app.testfairy.com/projects/4803590-status/builds/8529096/sessions/4396605090/?accessToken=cgXMchV2ZWg21I9QDoTyx7YVOR0

**Comment by rasom** [comment]
@Serhy fixed

**Comment by Serhy** [comment]
@rasom It almost good: pop-up asking about permissions appears fine on iOS.
However, when account is recovered - the `Thanks for choosing Status. We are in Beta…….` pop-up appears twice. Please, see two steps for reproduce and TF session for issues:

**Steps to reproduce:**
1) Install fresh build on iOS
2) Open Status
3) Navigate to 'Add existing account'
4) Fill in the valid recovery phrase and password and submit
**Actual result:** Once submitted user appears on Home screen and right away the `Thanks for choosing Status!...` pop-up appears. Wait 2-3 seconds -> "Status want to grant permissions" appears appears. 
**Expected result:** No `Thanks for choosing Status!...` pop-up. "Status want to grant permissions" pop up appears.
5) Tap 'Allow'
**Actual result:**`Thanks for choosing Status!...` pop-up appears twice and it requires twice to be closed.
**Expected result:** `Thanks for choosing Status!...` pop-up appears.
6) Now log out and recover one more account
**Actual result:** `Thanks for choosing Status!...` pop-up appears twice and it requires twice to be closed.
**Expected result:** `Thanks for choosing Status!...` pop-up appears only one time 

TF session: https://app.testfairy.com/projects/4803590-status/builds/8529096/sessions/4396616548/?accessToken=PRcNEx6pTnBjhHpxR66/Y7qGjsA

**Comment by rasom** [comment]
@Serhy, it seems i can reproduce this bug in older builds https://status-im.slack.com/archives/C8RNGLKRT/p1531798553000077 ,  so it's likely unrelated to the current scope

**Comment by rasom** [comment]
@Serhy, sorry, i installed the wrong build, that's a new bug

**Comment by rasom** [comment]
Actually... "Thanks for choosing Status!..." is a first thing which appears in old versions

**Comment by Serhy** [comment]
Latest builds - looks great now, @rasom! Thanks a lot!
iOS behaves like it should: Welcome screen for new accounts is present along with the 'PN permissions' pop-up. And for recovered accounts - no Welcome screen but `Request for permissions` and `Welcome to Status` pop-ups are present.
Welcome screen on Android is present as well!
Failed autotests are false failure will be addressed separately

Let's merge!!

**Pull request merged**
