### PR TITLE
[Fixes: #12061] Add unread mentions count

### LINKED ISSUE #12061: Show number of unread mentions in public and communities chats
As a user
I want to see the number of unread mentions in a public or community chat
So I know if a message was directed to me

### Description

In public chats and communities chats we should show a count of unread mentions

### Designs

https://www.figma.com/file/aS1ct66VQ6V0cio7vSqS8UoG/Chat?node-id=8499%3A140

### PR DESCRIPTION
**Pull request by cammellos**
Fixes: #12061

This commit adds an unread mentions count in 3 places:

1) Public chats
2) Communities in home
3) Communities chats

The logic is that if you have unread mentions, it will show you the
count of messages with unread mentions, while if you have only unread
messages, you will see a blue dot.

cc @errorists

### CODE REVIEW

**Review by flexsurfer — APPROVED** [review]

**Comment by churik** [comment]
@cammellos caught by e2e and can be reproduced manually:
### ISSUE 1: when chat appears in activity centre with command message, it is shown as group chat

**Steps:**
1) user A: restore multiaccount from seed phrase
2) user B: create multiaccount
3) user A: send transaction request to 1-1 with user B
4) user B: open Activity centre

**Expected result:**
1-1 is shown
**Actual result:**
image

**OS:** IOS, Android

Also can you please rebase PR to recent develop, as several e2e are fixed there?
thank you!

**Comment by churik** [comment]
### ISSUE 2: unread messages counter is reset after relogin

**Steps:**
1) User A, B: join same public chat
2) User B: go to home view
3) User A: mention User B in public chat
4) User B: with unread mentions counter, reopen app

**Expected result:**
unread mentions will be the same
**Actual result:**
unread mention amount is reset
**OS:** IOS, Android

**Comment by cammellos** [comment]
@churik is that related or separate?

**Comment by churik** [comment]
e2e failures are not related to PR, looking into this separately

**Comment by churik** [comment]
Tested basic flows, mentioned in description + communities + PNs.
LGTM, thank you @cammellos !

**Devices:**
- IPhone 12 Mini (IOS 14)
- IPhone 7 (IOS 13)
- Xiaomi Mi Note 9 Pro (Android 10)

**Pull request merged**
