### PR TITLE
Update status-go to v0.13.1

### LINKED ISSUE #5688: Fix calculating a node version
### Description

*Type*: Bug

*Summary*: Recently, status-go changed the way the node version is presented. From now on, it will look like this: `StatusIM/v0.13.1/android-arm/go1.10.1`.

#### Expected behavior
When I open About screen, I should see a proper app and node versions.

#### Actual behavior
Node version is displayed as `N/A`.

### Reproduction
Currently, it's reproducible with status-go defined in this PR: https://github.com/status-im/status-react/pull/5664.

### Solution
- [ ] it seems like [this code fragment](https://github.com/status-im/status-react/blob/dacfe97a5809b44f894533f0b02e771d4ae17ee3/src/status_im/web3/core.cljs#L41-L53) needs to be adjusted.

### Additional Information
* Status version: Only using status-go `v0.13.1` or later.
* Operating System: Android and iOS

#### Logs
Check out https://github.com/status-im/status-react/pull/5664#issuecomment-416874951 for more details.

### PR DESCRIPTION
**Pull request by adambabik**
This build fixes a problem with broadcasting expired messages by Whisper.

edit(yenda) also fix #5688

### CODE REVIEW

**Review by mandrigin — APPROVED** [review]

**Review by flexsurfer — APPROVED** [review]

**Comment by annadanchenko** [comment]
@adambabik 
# Issue 1 Version for status-go is N/A in Profile -> About (on Android and iOS)
in geth.log from Android: ```  instance=StatusIM/vv0.13.1/android-arm/go1.10.1``` - maybe "v.v" is the reason for bug?
[geth.log](https://github.com/status-im/status-react/files/2331409/geth.log)

screenshot_20180829-103759

**Review by yenda — APPROVED** [review]

**Comment by annadanchenko** [comment]
@adambabik @yenda last build failed, maybe it should be rebased as Jacob suggested "but we need you to rebase your PR branches so as to include the newest changes for Jenkinsfiles form `develop`, once that's done we can re-enable the PR builds"

**Comment by maxhora** [comment]
Should be Desktop updated with this as well? Looks like

**Comment by maxhora** [comment]
Commits in this PR rebased and force pushed to try to overcome Jenkins build failure.

**Comment by annadanchenko** [comment]
issue 1 is fixed. Node N/A now is node v.0.13.1 https://github.com/status-im/status-react/pull/5664#issuecomment-416874951

**Comment by adambabik** [comment]
Ok, so can I merge it?

**Comment by churik** [comment]
@adambabik 
on [MacOS](https://status-im.ams3.digitaloceanspaces.com/StatusIm.180830.081106.92c79f.pr.dmg) build crash at attempt to create new account (log in, recovering are working fine)
Issue is reported trough Google Breakpad in status-desktop, details are in GHI
https://github.com/MaxRis/StatusImDesktopReports/issues/18
Please, take a look.

**Comment by annadanchenko** [comment]
@adambabik not yet, waiting for @churik to confirm it's working with desktop

**Comment by adambabik** [comment]
```
Debug: RCTStatus::createAccount CreateAccount result:  {"address":"0x7615aa350b2337c046Caee2Bfb7a6B4c5eE50C14","pubkey":"0x04759f7c878565e0acc2a088ff1af5851f87b5d7620c94682fd211feacf11d8cf1bfc8e1ba5826d184f910e7cf6f4cbf734580d9a0458da820c15f732b3b220253","mnemonic":"squirrel range output slender clean foot twice myth crystal hood power matter","error":""}
Warning: QCoreApplication::postEvent: Unexpected null receiver
Debug: call of RCTStatus::callPrivateRPC with param callbackId:  42427
Debug: RCTStatus::callPrivateRPC CallPrivateRPC result:  [{"jsonrpc":"2.0","id":14784,"error":{"code":-32000,"message":"filter not found"}}]
Debug: ubuntu-server std:  "DEBUG [status-im.utils.handlers:37] - Handling re-frame event:  :account-created" 
Debug: ubuntu-server std:  "DEBUG [status-im.ui.screens.accounts.models:68] - account-created"
```

It looks like the account was created properly but almost at the same time another error occurred. @MaxRis can you comment on this?

**Comment by maxhora** [comment]
WiIl investigate and put update here, thanks

**Comment by churik** [comment]
@MaxRis I investigated it a bit more; this crash appeared only 2 times when I created account.
Now after creating aсcount I can see blank screen after clicking "OK" on this error:

slack - status 2018-08-30 12-57-45
So in any case I cannot use build when create fresh account.
Log:
```
Debug: RCTStatus::callPrivateRPC CallPrivateRPC result:  [{"jsonrpc":"2.0","id":33,"result":[]}]
 
Debug: call of RCTStatus::statusGoEventCallback ... event:  {"type":"mailserver.request.expired","event":{"hash":"0xc9a57aaaa7082814bc54c19b89d742d063439a6736794b56b938af1fb01a112c"}}
 
Debug: call of RCTStatus::emitStatusGoEvent ... event:  "{\"type\":\"mailserver.request.expired\",\"event\":{\"hash\":\"0xc9a57aaaa7082814bc54c19b89d742d063439a6736794b56b938af1fb01a112c\"}}"
 
Debug: call of RCTStatus::onStatusGoEvent ... event:  {"type":"mailserver.request.expired","event":{"hash":"0xc9a57aaaa7082814bc54c19b89d742d063439a6736794b56b938af1fb01a112c"}}
 
Debug: ubuntu-server std:  "DEBUG [status-im.utils.handlers:37] - Handling re-frame event:  :inbox/check-fetching"
 
Debug: ubuntu-server std:  "DEBUG [status-im.utils.handlers:37] - Handling re-frame event:  :signal-event {\"type\":\"mailserver.request.expired\",\"event\":{\"hash\":\"0xc9a57aaaa7082814bc54c19b89d742d063439a6736794b56b938af1fb01a112c\"}}"
 
Debug: ubuntu-server std:  "DEBUG [status-im.signals.events:10] - :event-str {\"type\":\"mailserver.request.expired\",\"event\":{\"hash\":\"0xc9a57aaaa7082814bc54c19b89d742d063439a6736794b56b938af1fb01a112c\"}}"
 
Debug: ubuntu-server std:  "DEBUG [status-im.signals.core:48] - Event  mailserver.request.expired  not handled"
 
Debug: call of RCTStatus::callPrivateRPC with param callbackId:  1651
 
Debug: RCTStatus::callPrivateRPC CallPrivateRPC result:  [{"jsonrpc":"2.0","id":34,"result":[]}]
 
Debug: call of RCTStatus::callPrivateRPC with param callbackId:  1655
 
Debug: RCTStatus::callPrivateRPC CallPrivateRPC result:  [{"jsonrpc":"2.0","id":35,"result":[]}]
 
Debug: call of RCTStatus::callPrivateRPC with param callbackId:  1659
 
Debug: RCTStatus::callPrivateRPC CallPrivateRPC result:  [{"jsonrpc":"2.0","id":36,"result":[]}]
 
Debug: call of RCTStatus::callPrivateRPC with param callbackId:  1663
 
Debug: RCTStatus::callPrivateRPC CallPrivateRPC result:  [{"jsonrpc":"2.0","id":37,"result":[]}]
 
Debug: call of RCTStatus::callPrivateRPC with param callbackId:  1667
 
Debug: RCTStatus::callPrivateRPC CallPrivateRPC result:  [{"jsonrpc":"2.0","id":38,"result":[]}]
 
Debug: call of RCTStatus::callPrivateRPC with param callbackId:  1671
 
```

**Comment by maxhora** [comment]
@adambabik @yenda as discussed with @churik , please, feel free to merge these changes.
I'm going to address found issues in separate PR.

P.S. It seems that this PR doesn't update status-go version for Desktop in `modules/react-native-status/desktop/CMakeLists.txt` file. I will add this in mentioned above separate PR.

**Comment by vkjr** [comment]
@adambabik, @maxr, does anything stop us from updating status-go version for desktop also within this PR?

**Comment by maxhora** [comment]
Locally, I haven't seen issues if to update status-go version for Desktop.

**Comment by adambabik** [comment]
@MaxRis I will work on updating Status Desktop automatically. I use a file `scripts/update-status-go.sh` to update status-go but it does not recognize Status Desktop yet.

**Pull request merged**
