### PR TITLE
Do not show biometrics onboarding screen if biometric is not available

### PR DESCRIPTION
**Pull request by flexsurfer**
Do not show biometrics onboarding screen if biometric is not available

### CODE REVIEW

**Comment by J-Son89** [comment]
can you update the description with what has been done? 🙏 It will make it easier to understand if we ever need to look back at these changes.

**Review by J-Son89 — APPROVED** [review]

**Comment by yevh-berdnyk** [comment]
@flexsurfer I've pushed a commit with a quick fix for e2e tests, restarting them now

**Comment by VolodLytvynenko** [comment]
Hi @flexsurfer thank you for PR. Only one issue is found:

## ISSUE 1: [Android] Enable biometrics screen is skipped for newly created accounts with set Fingerprint
### Preconditions:
1. The status app is installed and the account is onboarded
2. The fingerprint is not set in the device settings

### Steps:
1. Set up the fingerprint in the device settings.
2. Log out of the current account.
3. Start creating a new account.

### Actual result:
During the creation of a new account, the Enable Biometrics screen, which allows users to enable biometric authentication, is skipped when the fingerprint is set in the device settings.

### Expected result:
The Enable Biometrics screen should be shown for all newly created accounts when the fingerprint is set

### Additional info:
The error is shown in case a new account is created when the app is set up and the fingerprint is removed from the settings.
image

### Device:
- Real device: Pixel 7a, Android 13

**Comment by VolodLytvynenko** [comment]
One question: should the Enable biometrics screen be skipped for IOS devices when Face id is not set? For now, it is skipped only for Android devices

**Comment by flexsurfer** [comment]
>

**Comment by flexsurfer** [comment]
> One question: should the Enable biometrics screen be skipped for IOS devices when Face id is not set? For now, it is skipped only for Android devices

if there is also the error then yes

**Review by churik — APPROVED** [review]

**Comment by churik** [comment]
@flexsurfer please, update your PR locally to include Yevhenia's commit, thanks!

**Comment by VolodLytvynenko** [comment]
@flexsurfer ISSUE 1 can be fixed as a follow-up. Let me know if it will be addressed within the scope of this PR; otherwise, the current PR can be merged. Thank you!

**Pull request merged**
