### PR TITLE
Fix Discover typo (#483)

### PR DESCRIPTION
**Pull request by jarradh**

### CODE REVIEW

**Comment by rasom** [comment]
We need to add db migration here

**Comment by alwx** [comment]
Do we? Maybe it is not really important because this commit will be introduced in the first alpha release

**Comment by jarradh** [comment]
i don't know how to do a db migration

**Comment by rasom** [comment]
Ok. So then maybe better to skip all `db` versions other than 1 and remove them from code before release. I understand that we don't have any valuable data in application at the moment but we don't need to have `db` schema in some inconsistent state

**Comment by rasom** [comment]
Not in this PR anyway

**Comment by jarradh** [comment]
so what should we do with this then? migration or just truncate db migrations? and could someone take a look at this since I can't atm

**Comment by rasom** [comment]
We will truncate migrations in another PR, i will check this PR later

**Comment by jarradh** [comment]
thanks

**Pull request merged**
