### PR TITLE
Remove 3 words alias

### PR DESCRIPTION
**Pull request by cammellos**
This commit replaces the 3 random words alias with `zQ....something`, as per designs.
It will only work for accounts that are not in your contact yet, previous accounts will still show the 3 random words name (thought that could be fixed, but I could do in a separate PR).

### CODE REVIEW

**Review by J-Son89 — APPROVED** [review]

**Review by yqrashawn — APPROVED** [review]

**Review by Parveshdhull — APPROVED** [review]

**Comment by pavloburykh** [comment]
@cammellos thanx for the PR! 

1) Regarding this comment

> It will only work for accounts that are not in your contact yet, previous accounts will still show the 3 random words name (thought that could be fixed, but I could do in a separate PR).

I restored my main account which used to have a lot 3 random names contacts and I see that all of those contacts are displayed with keys (without 3 random names) 

photo_2023-08-21 16 55 59

2) @cammellos do I understand correctly that after merging current changes Desktop team will need to implement them on their side? 

Currently when I add Desktop user as a contact I observe Display name not being fetched until CR is accepted. Tested on Desktop release version 0.13.3.

[Mobile_CR_sender.zip](https://github.com/status-im/status-mobile/files/12396900/Mobile_CR_sender.zip)


https://github.com/status-im/status-mobile/assets/97245802/4084bd1a-d172-439f-a8f0-7394f4ff44d6

**Comment by cammellos** [comment]
Thanks for testing @pavloburykh 

> I restored my main account which used to have a lot 3 random names contacts and I see that all of those contacts are displayed with keys (without 3 random names)

Yes, that's expected, anytime you saw a 3 random words username, now you see a compressed pk, looks ugly, but if we are to get rid of 3 random names, that's the only way, we should make sure we limit the time you see pks, but a fallback is inevitable.

> @cammellos do I understand correctly that after merging current changes Desktop team will need to implement them on their side?

Not quite, if they use the status-go version, they will also default to compressed pks instead of 3 random words, they just have to upgrade status go, but no work should be necessary (if they implemented things in the same way as mobile).

> Currently when I add Desktop user as a contact I observe Display name not being fetched until CR is accepted. Tested on Desktop release version 0.13.3.

Is it different in this PR from develop? That code should not have changed in this PR

Thank you

**Comment by pavloburykh** [comment]
> Is it different in this PR from develop? That code should not have changed in this PR

@cammellos yes, it is different. I checked with mobile nightly build - Desktop display name is being fetched right after scanning QR code from mobile.

**Comment by pavloburykh** [comment]
> > Is it different in this PR from develop? That code should not have changed in this PR
> 
> @cammellos yes, it is different. I checked with mobile nightly build - Desktop display name is being fetched right after scanning QR code from mobile.

@cammellos ignore this for now please. I think it is randomly happening. Sometimes display name still not fetched right after scanning QR code. I believe it has nothing to do with this PR changes.

**Comment by pavloburykh** [comment]
### ISSUE 1 PN does not appear for receiver

E2E tests a catching this issue in all re-runs. Manually I have faced it once, but failed to reproduce after app re-install. 

Below I provide links to e2e video and logs

Failed test https://ethstatus.testrail.net/index.php?/tests/view/3217537

**Steps:** 

1. Device 2 sends message in group chat https://app.eu-central-1.saucelabs.com/tests/48ce510aca564dd1a19c835520a1c313?auth=b3e271f7fd2d3828d3eb308b8f77df6e#83

2. Device 1 is looking for PN from this group https://app.eu-central-1.saucelabs.com/tests/357227fa9ae541ed96abbe636e6e7a43?auth=b4d06adc30736857c342b3c40dfd318c#134

**Actual result:** PN does not appear for Device 1

[PN_receiver.log](https://github.com/status-im/status-mobile/files/12398120/PN_receiver.log)
[Sender_PN.log](https://github.com/status-im/status-mobile/files/12398121/Sender_PN.log)

@cammellos could you please check the above logs and tell if it will help to figure out the problem

**Comment by yevh-berdnyk** [comment]
hi @cammellos, thanks for you PR!
I see 2 issues found by automated tests and appeared after the last rebase commit (2 last comments in this PR).
1. Looks like rendering or some background process is happening in the chat screen because in the tests we get StaleObjectException for the chat message input. That means that Appium can't interact with the message input element because the DOM was reloaded.
Logs:
[logcat (1).log](https://github.com/status-im/status-mobile/files/12409490/logcat.1.log)
[test_community_markdown_support_geth2.log](https://github.com/status-im/status-mobile/files/12409507/test_community_markdown_support_geth2.log)


3. In some tests the app was crashed or closed after creating an account. Here is a video example and logs:
 https://app.eu-central-1.saucelabs.com/tests/e573ab8441824060aa87db6020fad60b?auth=a62a41e9b3c949495c6976aee3b78c59#21
[logcat (3).log](https://github.com/status-im/status-mobile/files/12409539/logcat.3.log)
[TestActivityMultipleDevicePR_geth0.log](https://github.com/status-im/status-mobile/files/12409570/TestActivityMultipleDevicePR_geth0.log)

**Comment by pavloburykh** [comment]
> hi @cammellos, thanks for you PR! I see 2 issues found by automated tests and appeared after the last rebase commit (2 last comments in this PR).
> 
> 1. Looks like rendering or some background process is happening in the chat screen because in the tests we get StaleObjectException for the chat message input. That means that Appium can't interact with the message input element because the DOM was reloaded.
>    Logs:
>    [logcat (1).log](https://github.com/status-im/status-mobile/files/12409490/logcat.1.log)
>    [test_community_markdown_support_geth2.log](https://github.com/status-im/status-mobile/files/12409507/test_community_markdown_support_geth2.log)
> 2. In some tests the app was crashed or closed after creating an account. Here is a video example and logs:
>    https://app.eu-central-1.saucelabs.com/tests/e573ab8441824060aa87db6020fad60b?auth=a62a41e9b3c949495c6976aee3b78c59#21
>    [logcat (3).log](https://github.com/status-im/status-mobile/files/12409539/logcat.3.log)
>    [TestActivityMultipleDevicePR_geth0.log](https://github.com/status-im/status-mobile/files/12409570/TestActivityMultipleDevicePR_geth0.log)

@yevh-berdnyk thanx for pointing out these issues. 

@cammellos small update:
-  point 1 looks like a global problem now not related to this PR, so we will log this issue separately as it is e2e blocker. 

- regarding point 2 (app crash) -  would be great if you take a look before merging this PR as for now we have not faced such issue in other PRs which have no updated go version.

**Comment by pavloburykh** [comment]
> * regarding point 2 (app crash) -  would be great if you take a look before merging this PR as for now we have not faced such issue in other PRs which have no updated go version.

@cammellos @yevh-berdnyk since we are facing point 2 in other PRs already it is not in scope of current PR and should be addressed separately.

**Comment by churik** [comment]
2 is reported in https://github.com/status-im/status-mobile/issues/17114

**Comment by pavloburykh** [comment]
@cammellos hi! Could you please rebase go and mobile branches once again? I will re-run e2e and perform smoke test so we can merge this PR. As far as understand all mentioned go bugs should be already fixed.

**Comment by cammellos** [comment]
@pavloburykh done, thank you for reminding me!

**Comment by pavloburykh** [comment]
@cammellos thank you for the PR. Failed e2e are not PR related. Ready for merge.

**Comment by pavloburykh** [comment]
@cammellos oops, I have forgotten about design-review stage. Let's wait for @Francesca-G approval before merge.

**Comment by cammellos** [comment]
@pavloburykh this PR has no visual changes, other than replacing 3 words name to compressed pk, and I am not sure we ever show that in the designs (designs always show a display name), but happy for it to go through a design review of course

**Review by Francesca-G — APPROVED** [review]
Looks good to me.

The only place I've managed to find 3-worded names is the community member list which I think hasn't been implemented yet with the new design, so it makes sense

97079777-96BF-4B2E-B956-56B02B81D2F8_1_102_o

**Pull request merged**
