### PR TITLE
Fix base image path import in Windows setup

### LINKED ISSUE #7826: Can't start app on Windows (after fresh install)
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug
*Summary*: After installation can't start Status app. No logs are created.

#### Expected behavior
can start status app
#### Actual behavior
app doesn't start

### Reproduction

If you have the previous installation of Status App:
- uninstall app 
- delete app data in /AppData/Local/Status
- restart your laptop (or vm)

After this:
- install status nightly
- try to start it

### Additional Information
* Status version: nightly 25/03/2018
* Operating System: Windows 10 Home

### PR DESCRIPTION
**Pull request by pedropombeiro**
[comment]: # (Please replace ... with your information. Remove < and >)
[comment]: # (To auto-close issue on merge, please insert the related issue number after # i.e fixes #566)

fixes #7826 

### Summary:

[comment]: # (Summarise the problem and how the pull request solves it)
...

### Review notes (optional):

This PR adds a missing slash to the path. Without it, the `src/` folder was being copied to the installer, instead of its contents. Not sure how this worked before...

#### Platforms (optional)
- Windows

status: ready

### CODE REVIEW

**Review by jakubgs — APPROVED** [review]

**Review by mandrigin — APPROVED** [review]

**Comment by churik** [comment]
Tested on Windows:
- fresh install
- upgrade from release from https://status.im/get_desktop/ (https://status-im.ams3.digitaloceanspaces.com/StatusIm-190305-152317-ff3c9d-release.exe)

Also upgraded from latest nightly on Mac OSx and Linux.
Waiting for e2e tests.

**Comment by pedropombeiro** [comment]
The failures look unrelated. cc @antdanchenko

**Comment by antdanchenko** [comment]
@churik please use e2e.apk instead of pr.apk 
@PombeirP The job was triggered with wrong apk ^

**Comment by churik** [comment]
Yeah, my fault, I'll trigger another one

**Comment by pedropombeiro** [comment]
That reminds me, we'll need to take some time to fix the bot workflow

**Pull request merged**
