### PR TITLE
Fix Wallet Connect structure 

### LINKED ISSUE #20040: Fix Wallet Connect structure
# Problem

After the feedback received from @J-Son89, I adjusted the ns structure, moved constants to the appropriate ns and removed the utils ns. Along the way, found an unexpected bug in the re-frame effects usage.

### PR DESCRIPTION
**Pull request by clauxx**
fixes #20040 

### Summary

* moved wallet connect utils to the `react-native` ns
* moved metadata's url and icon to constants
* fixed the init metadata function not being called
* fixed the `:effects.wallet-connect/register-event-listener` effect not receiving the args (didn't know that if the fx receives multiple args they are wrapped in a vector 🤷‍♂️)
* fixed the formatting issue of `"@walletconnect/react-native-compat"`, which wasn't sorted properly, so it was moved to `status-im.core`

### Steps to test

use the same steps as in https://github.com/status-im/status-mobile/pull/19909

status: ready

### CODE REVIEW

**Review by alwx — APPROVED** [review]

**Review by J-Son89 — APPROVED** [review]

**Comment by clauxx** [comment]
@pavloburykh are the e2e failures caused by this PR?

**Comment by pavloburykh** [comment]
> @pavloburykh are the e2e failures caused by this PR?

Lot of the failures related to infrastructure. We should better re-run e2e in order to get valid results.

**Comment by yevh-berdnyk** [comment]
> 🤖`apk`



> > @pavloburykh are the e2e failures caused by this PR?
> 
> Lot of the failures related to infrastructure. We should better re-run e2e in order to get valid results.

I've just restarted them

**Comment by yevh-berdnyk** [comment]
> ## 92% of end-end tests have passed

E2E failures are known and not related to the PR, thanks!

**Pull request merged**
