### PR TITLE
Use with-precision for token requirements

### LINKED ISSUE #17871: Trailing zeros formatting Issue for numerical token value in token gated communities permission requirements
Followup of https://github.com/status-im/status-mobile/pull/17799 cc @ilmotta 

**Steps:** 

1. Open token gated community screen
2. Pay attention at formatting of token value in permission requirements description

**Actual result:** 

photo_2023-11-10 13 58 26

**Expected result:** 

Communities for Mobile – Figma 2023-11-10 13-59-45

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

### PR DESCRIPTION
**Pull request by ibrkhalil**
fixes #17871 

### Summary

Use with-precision for token requirements
image

status: ready

### CODE REVIEW

**Review by ilmotta — COMMENTED** [review]
You found a clean solution @ibrkhalil :)

I have just one question, how have you arrived at the 3-digit precision? I ask that because we should do the same as desktop.

**Comment by ibrkhalil** [comment]
> You found a clean solution @ibrkhalil :)
> 
> I have just one question, how have you arrived at the 3-digit precision? I ask that because we should do the same as desktop.

To be honest, I just picked an appropriate value to me.
I'll look into what precision does desktop use and apply it here.
Thanks Icaro!

**Comment by ilmotta** [comment]
@ibrkhalil, this issue on Desktop seems relevant. https://github.com/status-im/status-desktop/issues/8640 It seems that the ideal solution can be quite complicated, and the correct values should likely come from status-go, and not be done on the client. As a quick workaround, I have the opinion that it's probably okay to use `with-precision` as you did here, but we should know it's not where we want to go in the future.

@qoqobolo shared with me because I also had questions in my current work about which precision I should use in status-go.

**Comment by qoqobolo** [comment]
@ibrkhalil @ilmotta just for more context, there was also a PR that implemented max possible decimals for mobile wallet: https://github.com/status-im/status-mobile/pull/18267
Maybe you could find some useful information in it

**Comment by ilmotta** [comment]
> @ibrkhalil @ilmotta just for more context, there was also a PR that implemented max possible decimals for mobile wallet: #18267 Maybe you could find some useful information in it

Very useful @qoqobolo, thanks. So I was late to the party because that's already coded on the client.

@J-Son89, do you know if there's any plan for the mobile wallet team to move precision logic to the backend?

**Comment by J-Son89** [comment]
Afaik it's done the same on desktop and it is not planned to be to Go. I guess we want to ensure the data is stored correctly on the backend and it's easier/safer to handle this on the fe to avoid any mix up.
@alaibe or @OmarBasem would probably know more than me about this however

**Comment by OmarBasem** [comment]
> Afaik it's done the same on desktop and it is not planned to be to Go. I guess we want to ensure the data is stored correctly on the backend and it's easier/safer to handle this on the fe to avoid any mix up. @alaibe or @OmarBasem would probably know more than me about this however

We need to read that data from status-go https://github.com/status-im/status-go/blob/develop/services/wallet/currency/currency.go#L71 
We are yet to integrate that into status-mobile

**Comment by alaibe** [comment]
So far status-go give u the format (number of decimals...) however this is the client who is in responsible to actually format the data.
Most number data is in hex (or will be) in case there is computation needed on client side such as summing balances

This is why we don't format, there is many numbers that are displayed that are computed based on parameters such as network selected, account selected

**Comment by ilmotta** [comment]
> So far status-go give u the format (number of decimals...) however this is the client who is in responsible to actually format the data. Most number data is in hex (or will be) in case there is computation needed on client side such as summing balances
> 
> This is why we don't format, there is many numbers that are displayed that are computed based on parameters such as network selected, account selected

Makes sense to format on clients @alaibe. It's just that the logic to find the max number of decimals is currently implemented on the mobile code, but I think this data should come from status-go. It would be ideal I think if max decimals always accompanied crypto amounts returned by status-go. In the case of the mobile app this is useful also for performance reasons because the implementation to find max decimals is quite involved.

Edit: @OmarBasem replied we just need to integrate an endpoint from status-go. It's all good! Thanks guys.

**Comment by flexsurfer** [comment]
hey @ibrkhalil still relevant?

**Comment by ibrkhalil** [comment]
> hey @ibrkhalil still relevant?

Nope, Already fixed in prod.

**Pull request closed without merging**
