### PR TITLE
cli clojurescript build

### PR DESCRIPTION
**Pull request by rasom**
1. run `lein compile-cli` in one tab, wait for compilation 
2. and try `node target/cli/index.js arg1 arg2` in another
3. see output
```
Hello world! args ("arg1" "arg2")
Veryl...
```

further steps: adding figwheel support https://github.com/bhauman/lein-figwheel/wiki/Node.js-development-with-figwheel

status: ready

### CODE REVIEW

**Comment by jeluard** [comment]
@rasom Is this an example or something we want to merge?

**Comment by rasom** [comment]
@mandrigin any progress on this? Is this PR useful, do you need any help?

**Comment by cammellos** [comment]
@rasom I will be working with @mandrigin on the swarm, thanks for the cli, I think it will be very useful. 
For now though I would close the pull request as we won't be using it until we get a bit closer to implementing the swarm. 
We will keep the branch and then add it once we have some more substantial contribution from the swarm.
Is this ok with everyone?

**Comment by jeluard** [comment]
@cammellos Sounds good to me!

**Pull request closed without merging**
