### PR TITLE
Chat messages UI refresh

### PR DESCRIPTION
**Pull request by GustavoNunes**
### Summary:

- 1-on-1 chats now visually similar to group chats: sender's icon besides messages
- Sender's name in each message
- Datemark styles
- Confirmation status only in last outgoing message
- Small style tweaks everywhere

#### Note:
I didn't rework the commands' messages (location, request, etc), only made small tweaks to make them fit together with the other changes. I think it will make more sense to rework these together with the commands themselves.

status: ready

### CODE REVIEW

**Comment by GustavoNunes** [comment]
@rasom this PR is ready for review.

**Comment by rasom** [comment]
**ios**

screen shot 2017-03-18 at 10 03 17

1. Message bubble has wrong size
2. icon is smaller than in Zeplin
3. Do we still need this checkmark?

**Comment by rasom** [comment]
**ios**

screen shot 2017-03-18 at 10 17 19
Distance between messages from different authors should be bigger

**Comment by GustavoNunes** [comment]
@rasom, I fixed these issues.
There is only 1 thing missing, regarding the distances between messages: when the message comes after a datemark (e.g. "Today", "Yesterday"), the distance should be 20.

However, I couldn't add the key needed for this to the message ([this one](https://github.com/status-im/status-react/pull/910/files#diff-68a91e52488740033aa29d9dcb179de5R29)). So this distance is falling to the default 24. The previous key (`new-day`) wasn't implemented either.
I tried some things but didn't figure out how to do it. If someone could point me to the right direction it would be much appreciated.

**Comment by rasom** [comment]
@GustavoNunes, please resolve conflicts and I will merge this PR. We will create another issue for messages after datemark.

**Comment by GustavoNunes** [comment]
done @rasom, thanks!

**Pull request merged**
