### PR TITLE
[#4218] Removed some DApps

### LINKED ISSUE #4218: Remove DApps with usability issues
### User Story

As a user, I want to be presented with DApps that are truly usable in Status.

### Description

*Type*: Bug

*Summary*: 
The following DApps have too many usability issues for users to easily accomplish what the DAPp intends:

- Auction House 
- Decentraland 
- FirstBood 
- Flight Delays Suck 

They should be removed.

#### Expected behavior
All curated DApps should be navigable, with decent mobile UX, a clear value prop and support for cryptocurrencies. 

#### Actual behavior
Auction House is in demo mode only and has some webview issues in Status.
Decentraland is difficult to play on mobile due to the map on Atlas screen.
FirstBlood has too many webview issues to be navigable.
Flight Delays Suck only supports fiat currency right now. 

### Reproduction
Open any of these DApps and toy around. 

### Solution

- [x] Remove these 4 DApps from "Open DApp" list

### Additional Information
* Status version: https://i.diawi.com/DJC2LB
* Operating System: iOS 6s+

<blockquote><div><strong><a href="https://i.diawi.com/DJC2LB">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

### PR DESCRIPTION
**Pull request by jeluard**
fixes #4218 

### Summary:

Removed older DApps

status: ready

### CODE REVIEW

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/bY8FF1 for branch PR-4232

<blockquote><div><strong><a href="https://i.diawi.com/bY8FF1">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/fec7o9 for branch PR-4232

<blockquote><div><strong><a href="https://i.diawi.com/fec7o9">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Review by rachelhamlin — APPROVED** [review]

**Review by janherich — APPROVED** [review]

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/iMR44f for branch PR-4232

<blockquote><div><strong><a href="https://i.diawi.com/iMR44f">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/1XeG4b for branch PR-4232

<blockquote><div><strong><a href="https://i.diawi.com/1XeG4b">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/S3xfX6 for branch PR-4232

<blockquote><div><strong><a href="https://i.diawi.com/S3xfX6">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/KviD9k for branch PR-4232

<blockquote><div><strong><a href="https://i.diawi.com/KviD9k">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/8NaUDT for branch PR-4232

<blockquote><div><strong><a href="https://i.diawi.com/8NaUDT">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Pull request merged**
