### PR TITLE
[HOTFIX][#15056] Can't see display/ens/name when mentioning in community hotfix

### LINKED ISSUE #15056: Can't see display/ens/name when mentioning in community
When mentioning someone, I can only see 3 words names, we should display (and search on), the contact names.

### PR DESCRIPTION
**Pull request by flexsurfer**
fixes #15056

### CODE REVIEW

**Review by Parveshdhull — APPROVED** [review]

**Comment by pavloburykh** [comment]
@flexsurfer thanx for the fix. Please. take a look at the following issue

### ISSUE 1 Regular text instead of mention is sent when trying to mention user by displayed name

I am not sure about specific steps and preconditions as in some cases it is possible to mention user by name in other not.

The easiest way to replicate is using my specific user with existing community. 

**Preconditions:** use this user for reproduction. seed phrase: outdoor portion desk extend lend ugly canvas inquiry ski buffalo custom loud

**Steps:** 

1. Recover given above user
2. Tap Community tab
3. Wait until communities are restored
4. Enter "testing release /1.22" community
5. Open any channel in given community
6. Try to mention desktop user @Pavlo
7. Observe the result

**Expected result:** it is possible to mention user. 

**Actual result:** Regular text instead of mention is sent. Same happens in 1-1 chat with user Pavlo. At the same time in new communities it is possible to mention user Pavlo. 


https://user-images.githubusercontent.com/97245802/218830669-d25de9dd-1f44-4871-8e93-fb53147d10f9.mp4

[Status-debug-logs.zip](https://github.com/status-im/status-mobile/files/10735876/Status-debug-logs.zip)

**Comment by pavloburykh** [comment]
### ISSUE 2 Few other issues which might not be in scope of the PR

I have recovered my desktop user (member of Status community) on mobile and here what I observe in terms of mentions:

1. Most of users in the initial mention list (when you start typing @) are still displayed with 3 random names. At the same time on desktop all users in mention list are displayed with their names. [video](https://drive.google.com/file/d/1gKeWi8VFswKtQwGlONPqWio7DHZqa3OI/view?usp=share_link)

2. Not all users are available for mentioning on mobile. For example, on desktop I see 2 users with name andrey On mobile I see only one. There are a lot of other examples if to go through the whole list of names which is displayed on desktop. 


**Screenshot from mobile**
1_mobile


**Screenshot from desktop**
2_desktop

**Comment by flexsurfer** [comment]
hey @pavloburykh @churik @cammellos currently we have a mess with all the different names (from status 1.0 and status 2.0), contacts non contacts, communities , syncing etc , i would work on this and make it cleaner, but not in this PR, could we pls agree on what we want to fix in this PR ?

**Comment by flexsurfer** [comment]
i'll take a look into `ISSUE 1 Regular text instead of mention is sent when trying to mention user by displayed name`

**Comment by cammellos** [comment]
> hey @pavloburykh @churik @cammellos currently we have a mess with all the different names (from status 1.0 and status 2.0), contacts non contacts, communities , syncing etc , i would work on this and make it cleaner, but not in this PR, could we pls agree on what we want to fix in this PR ?

I'd say any client side issue is in scope, but not any status-go issue. For example Issue 2 is most likely a status-go issue, since contacts' display names are not synced between clients. 

But basically, given that you have either a ENS name, display name, nickname, it should show in the list and work when mentioning (so issue 1 would be in scope).
If those are not available in re-frame (such as in issue 2, my suspicion is that they were just not synced), that's definitely out of scope.

What do you think @flexsurfer ?

**Comment by pavloburykh** [comment]
> could we pls agree on what we want to fix in this PR ?

IMHO in terms of RC-1 it will be enough to clear out and fix [issue 1](https://github.com/status-im/status-mobile/pull/15086#issuecomment-1430229370), cause we want to make sure that user is able to mention other users by displayed name. Other issues are subjects for investigation and fixing in future releases.

**Comment by flexsurfer** [comment]
@pavloburykh user with name "Pavlo" works fine for me in communities
image

it will be difficult to fix, without steps to replicate :(

**Comment by pavloburykh** [comment]
> @pavloburykh user with name "Pavlo" works fine for me in communities

@flexsurfer thanx for investigation. You have tried mentioning specifically in "testing release /1.22" community, correct? Because the screenshot provided by you is from "test_comm_enc" community.

**Comment by flexsurfer** [comment]
ISSUE 1  should be fixed now

**Comment by churik** [comment]
e2e failures are not related to PR.
Tested in communities, group chats, 1-1 chats

**Devices:**
- IPhone 12 Mini (IOS 16)
- IPhone 7 (IOS 13)
- Xiaomi Mi Note 9 Pro (Android 10)

Please, cherry-pick it to release/1.22.x branch, thank you!

**Comment by flexsurfer** [comment]
cherry-picked

**Pull request closed without merging**
