### PR TITLE
[fix] align min chat input container height with tab menu

### PR DESCRIPTION
**Pull request by yenda**
#### Platforms (optional)
- macOS
- Linux
- Windows

status: ready

### CODE REVIEW

**Review by vitvly — APPROVED** [review]

**Review by rcullito — APPROVED** [review]
🚢

**Review by rasom — APPROVED** [review]
thank you, Eric!

**Comment by rasom** [comment]
general question: can these values somehow be dependent on each other so that we don't have such problem next time (i mean input container height & tab menu height). Or this doesn't make sense?

**Comment by yenda** [comment]
@rasom the odd thing is the tabs-height is 68 as well. I'll consider this a quickfix and keep in mind that this should be revisited at some point

**Comment by rasom** [comment]
let's add some comment then?

**Review by flexsurfer — APPROVED** [review]

**Comment by SlizkovaGanna** [comment]
Failed tests are unrelated/infrastructure fails

Resized and checked that the tab field and input fields do match

image

Confirmed on MacOS, Linux (emulated)

**Pull request merged**
