### PR TITLE
Upgraded natal-shell

### PR DESCRIPTION
**Pull request by jeluard**
### Summary:
Upgraded `natal-shell` to latest version. Reduces the number of deps transitively added.

status: ready

### CODE REVIEW

**Comment by rasom** [comment]
Something is wrong with build http://185.90.37.243:8080/blue/organizations/jenkins/Github%20Org%20Builder%2Fstatus-react/detail/feature%2Fupgrade-natal-shell/1/pipeline

**Comment by jeluard** [comment]
Looks like some transitive dependency issue? I will look at it this evening.

**Comment by jeluard** [comment]
Tests pass correctly now.

**Comment by rasom** [comment]
Hm, just checked again, and it seems that we are not using `natal-shell` in project, am i missing something? There is one place, but it's not really used there https://github.com/status-im/status-react/blob/99147706b320016d08cb1d38d145ff5cb9b5487a/src/status_im/utils/listview.cljs

**Comment by jeluard** [comment]
Even better! I will make sure we don't need it.

**Comment by jeluard** [comment]
I can confirm it's not needed so I removed it.

**Pull request merged**
