### PR TITLE
hide not implemented composer features

### LINKED ISSUE #19870: Hide emojii button in composer
We should hide the emoji button in composer behind the not-implemented feature flag

### LINKED ISSUE #19871: Hide text formatting button in composer
We should hide the text formatting button in the composer under the not-implemented feature flag

### LINKED ISSUE #19872: Hide audio message button in composer
We should hide the audio message button in the composer behind the not implemented feature flag.

### PR DESCRIPTION
**Pull request by Parveshdhull**
fixes https://github.com/status-im/status-mobile/issues/19872
fixes https://github.com/status-im/status-mobile/issues/19871
fixes https://github.com/status-im/status-mobile/issues/19870

### Testing Note
Manual testing is not needed because no changes in the functionality, just not implemented elements are hidden now

status: ready

### CODE REVIEW

**Review by ibrkhalil — APPROVED** [review]
✅

**Comment by J-Son89** [comment]
@Parveshdhull - can we add a few reviewers to these prs? 
It helps ensure that more people see them. Even if the changes are simple it's good that more of us are aware to what changes are happening 👍

**Review by J-Son89 — APPROVED** [review]

**Comment by Parveshdhull** [comment]
> @Parveshdhull - can we add a few reviewers to these prs? It helps ensure that more people see them. Even if the changes are simple it's good that more of us are aware to what changes are happening 👍

Hi @J-Son89, Thank you very much for reviewing PRs. These PRs were created on the weekend and I didn't want to ping devs on their off time. Will request a review today on other PRs (this one already have two approvals).

**Comment by Parveshdhull** [comment]
@status-im/mobile-qa Please can you check out e2e test results. Thank you

**Comment by mariia-skrypnyk** [comment]
> @status-im/mobile-qa Please can you check out e2e test results. Thank you

Hi @Parveshdhull !

Waiting for rerun of failed tests.
Let you know!

**Comment by mariia-skrypnyk** [comment]
@Parveshdhull thanks for waiting!

Failed e2e are not related, please fill free to merge!

**Pull request merged**
