### PR TITLE
Chat header text & arrow alignment off (#301)

### PR DESCRIPTION
**Pull request by alwx**
Fixes https://github.com/status-im/status-react/issues/301

### CODE REVIEW

**Comment by rasom** [comment]
Console's eye intersects with dapp icon border:



1. So it seems to me that dapp's icon is a bit higher on android screen than on example from zeplin, at least its position relatively `online status` is a bit different.

2.  `Chat's name` on android screen is closer to the center (maybe 1dp) than it is in zeplin


There is chance that i just have hallucinations

**Comment by rasom** [comment]
The first image is iOS simulator, the second is from zeplin

**Comment by rasom** [comment]
Android looks fine, problems in iOS are still the same:

**Comment by alwx** [comment]
Fixed

**Pull request merged**
