### PR TITLE
Toggle dev mode to change network

### PR DESCRIPTION
**Pull request by Serhy**
Enable Dev mode to change the network (changed in #4294 )

### CODE REVIEW

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/zpzvd5 for branch PR-4348

<blockquote><div><strong><a href="https://i.diawi.com/zpzvd5">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/BCm3PH for branch PR-4348

<blockquote><div><strong><a href="https://i.diawi.com/BCm3PH">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Review by antdanchenko — APPROVED** [review]

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/1Am1pA for branch PR-4348

<blockquote><div><strong><a href="https://i.diawi.com/1Am1pA">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/6iQ4FP for branch PR-4348

<blockquote><div><strong><a href="https://i.diawi.com/6iQ4FP">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Pull request merged**
