### PR TITLE
[fix 6334] request multiple topics at once

### LINKED ISSUE #6334: Support for multiple topics in mailserver requests
### Description

*Type*: Bug

*Summary*: Use https://github.com/status-im/status-go/pull/1240 in status-react.

### Additional Information
* Operating System: all

### PR DESCRIPTION
**Pull request by yenda**
- group requests by last-request to request multiple topic at once
- fix bug where fetching popup was shown when the app was actually in error
state

fixes #6334

# Testing
- upgrade current nightly with lots of pending requests
- number of pending requests should be greatly reduced

status: ready

### CODE REVIEW

**Review by dmitryn — APPROVED** [review]

**Review by janherich — APPROVED** [review]

**Comment by lukaszfryc** [comment]
@yenda 

Looks good to me. I tested all platforms with different scenarios like upgrading with pending requests, joining multiple public chats in offline mode and then going online. Messages were fetched pretty fast 👍 

The only issues I noticed were:

1) Unexpected EOF from status-go in status logs:  

```
10-16 16:32:24.705 29548-29599/? D/StatusNativeLogs: ERROR[10-16|14:32:24.705] Failed handling message with error       package=status-go/services/sshext.PublicAPI err="unexpected 
    EOF"
10-16 16:32:24.740 3775-5166/? I/ActivityManager: KPU : put [com.samsung.android.mobileservice] : 36797 K
    Killing 29392:com.samsung.android.mobileservice/u0a197 (adj 906): DHA:empty #25
10-16 16:32:24.752 29548-29599/? D/StatusNativeLogs: ERROR[10-16|14:32:24.752] Failed handling message with error       package=status-go/services/sshext.PublicAPI err="unexpected 
    EOF"
    ERROR[10-16|14:32:24.752] Failed handling message with error       package=status-go/services/sshext.PublicAPI err="unexpe
    cted EOF"
    ERROR[10-16|14:32:24.752] Failed handling message with error       package=status-go/services/sshext.PublicAPI err="u
    nexpected EOF"
    ERROR[10-16|14:32:24.752] Failed handling message with error       package=status-go/services/sshext.PublicAPI e
    rr="unexpected EOF"
    ERROR[10-16|14:32:24.752] Failed handling message with error       package=status-go/services/sshext.Public
    API err="unexpected EOF"
    ERROR[10-16|14:32:24.752] Failed handling message with error       package=status-go/services/sshext.P
    ublicAPI err="unexpected EOF"
    ERROR[10-16|14:32:24.752] Failed handling message with error       package=status-go/services/ssh
    ext.PublicAPI err="proto: can't skip unknown wire type 7"
    ERROR[10-16|14:32:24.752] Failed handling message with error       pa
    ckage=status-go/services/sshext.PublicAPI err="unexpected EOF"
    ERROR[10-16|14:32:24.752] Failed handling message with error    
       package=status-go/services/sshext.PublicAPI err="unexpected EOF"
    ERROR[10-16|14:32:24.752] Failed handling message with erro
    r       package=status-go/services/sshext.PublicAPI err="unexpected EOF"
10-16 16:32:24.788 4482-27784/? D/ForegroundUtils: could not check pending caller
```

2) One time, the app crashed when I changed mailserver. I could not replicate it. Please have a look at the logs. If it's not related, I will create a separate GHI.

[StatusIm  16-10-2018, 16-22.log](https://github.com/status-im/status-react/files/2483554/StatusIm.16-10-2018.16-22.log)

**Comment by yenda** [comment]
@lukaszfryc that is some weird looking logs there is nothing useful there for me

**Comment by lukaszfryc** [comment]
Fair enough. Please merge :) I will create separate issues for those.

**Comment by cammellos** [comment]
that s not related, it s the pfs layer trying to decrypt messages, it s
expected in jenkins builds

**Pull request merged**
