### PR TITLE
Continue button is invisible behind keyboard in Add Address To Watch …

### LINKED ISSUE #17888: Continue button is hidden behind active keyboard on create Watch-only account screen
**Steps:** 

1. Open create "Watch-only" account screen
2. Open keyboard
3. See if continue button is displayed above active keyboard

**Actual result:** 

**IOS**

photo_2023-11-13 10 57 46

**Android**

photo_2023-11-13 10 57 49

**Expected result:** "Continue" button should be located above active keyboard

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

### PR DESCRIPTION
**Pull request by ibrkhalil**
fixes #17888 

CleanShot 2023-11-18 at 14 24 11

status: ready

### CODE REVIEW

**Comment by J-Son89** [comment]
Thanks for the pr @ibrkhalil - @ulisesmac & I have been working on a generic approach for this as it is common to many pages in the wallet / redesign screens. We merged the pr last week and intending to use this approach on this screen. 
Feel free to try it here as it would be better to take this approach if possible 👍

**Comment by ibrkhalil** [comment]
> Thanks for the pr @ibrkhalil - @ulisesmac & I have been working on a generic approach for this as it is common to many pages in the wallet / redesign screens. We merged the pr last week and intending to use this approach on this screen. Feel free to try it here as it would be better to take this approach if possible 👍

I used it, Can you kindly take another look?

**Comment by J-Son89** [comment]
Thanks @ibrkhalil - code looks good to me. WDYT about that component, looks alright/ working okay? api makes sense etc?

**Review by J-Son89 — APPROVED** [review]

**Comment by ibrkhalil** [comment]
> Thanks @ibrkhalil - code looks good to me. WDYT about that component, looks alright/ working okay? api makes sense etc?

I think the animation that happens when keyboard opens can be improved as there's a 'slight' jump that happens when the keyboard gets toggled on my iOS simulator, I think that's caused because rn/keyboard returns it's values after the keyboard gets completely loaded/dismissed. We can utilize composer's focused property here which I think would make it seamless.

Other than that the code looks excellent, Thank you!

**Comment by J-Son89** [comment]
thanks for the feedback @ibrkhalil - sure we can adjust that in another pr :)

**Comment by ulisesmac** [comment]
@ibrkhalil 

>  'slight' jump that happens when the keyboard gets toggled on my iOS simulator, I think that's caused because rn/keyboard returns it's values after the keyboard gets completely loaded/dismissed

Very interesting, yep, we can improve the behavior @J-Son89 :)

**Comment by churik** [comment]
@ibrkhalil 
please, resolve the conflicts and re-send to testing, thank you!

**Comment by ibrkhalil** [comment]
> @ibrkhalil please, resolve the conflicts and re-send to testing, thank you!

Done

**Comment by VolodLytvynenko** [comment]
Hi @ibrkhalil thank you for PR. Ready to be merged

**Pull request merged**
