### PR TITLE
[TESTS #3924] Chat management tests

### PR DESCRIPTION
**Pull request by antdanchenko**
added public chat leave/clear history/swipe to delete test
group chat tests/test parts disabled
added more errors to rerun tests list

### CODE REVIEW

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/arza1i for branch PR-4399

<blockquote><div><strong><a href="https://i.diawi.com/arza1i">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/oHS8Gz for branch PR-4399

<blockquote><div><strong><a href="https://i.diawi.com/oHS8Gz">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/74M8am for branch PR-4399

<blockquote><div><strong><a href="https://i.diawi.com/74M8am">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/EwQxoe for branch PR-4399

<blockquote><div><strong><a href="https://i.diawi.com/EwQxoe">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/7BfDtQ for branch PR-4399

<blockquote><div><strong><a href="https://i.diawi.com/7BfDtQ">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/hi2Ru8 for branch PR-4399

<blockquote><div><strong><a href="https://i.diawi.com/hi2Ru8">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Review by yevh-berdnyk — APPROVED** [review]

**Pull request merged**
