### PR TITLE
Pull request to require adding Auctus to Dapps listing

### PR DESCRIPTION
**Pull request by ludmila-omlopes**
Pull request to require adding Auctus to Dapps listing.

### CODE REVIEW

**Comment by oskarth** [comment]
@pablanopete @chadyj can you take a look at this and see what you think?

**Comment by oskarth** [comment]
Requesting 3 reviewers based on previous Dapp discussion in Slack.

**Review by andytudhope — APPROVED** [review]
This seems to be a really awesome DApp that works well (for the most part) within Status. It is mobile optimised and looks pretty good for the most part. I'd like to see the tool tips placed in a slightly different way so as not to cover the input fields, and some other minor fixes, but it is better than most we have seen submitted so far.
The app crashed twice when I was testing this, but that may well be nothing to do with the DApp itself. Second time was a clear crash on the image captcha, which I think is something we are struggling with in general (they force a captcha before deploying the contract that manages your investment/401(k)).
Was interesting to me that they are deploying onto Rinkeby (and Status is mostly on Ropsten), though it still seemed to work well. Assuming Auctus is footing the gas bill on the test networks for now. 
A little slow in general, but that is likely my connection and nothing to do with the DApp.
I'm going to approve this because it is one of the best ones I have seen so far, but am happy to hear Chad's thoughts when he has a moment.

**Comment by chadyj** [comment]
Hey Ludmila! Thanks for the PR! I don't have any specific comments about Auctus or this PR.

But as a general comment about Dapps, Status doesn't yet have a way to scale to show a lot of Dapps, and have this be meaningful for users so they can browse categories, search, show which networks the Dapp is compatible with, explain what Dapps are, learn about individual Dapps before they install, etc etc. In short, there is a lot we can do to make an amazing Dapp experience, but we aren't there yet. We are currently working on the [Status beta](https://github.com/status-im/ideas/issues/26), and I hope after that release we will have a comprehensive Dapp plan. 

But in the meantime, as a Dapp author what do you think is the best Dapp experience for Status users? How would they discover your Dapp, learn about it, and use it? I'd love your feedback and insight!

**Comment by oskarth** [comment]
Closing this PR as we are currently looking over how to do our dapp selection. Please reach out to us in Riot if you have more questions. Also see Chad's reply above.

**Comment by ludmila-omlopes** [comment]
Thank you guys so much for your review, comments and tips! I'm really proud of our dev team and they indeed have been doing a great job with our development. I understand the current situation and looking foward to test Status beta.

As suggestions I think that the standard model of having an app store, users review and rating, suggestions based on use works well for mobile experience. I'll join your Riot and invite the rest of our team to join this discussion and do some brainstorming with you. Maybe some great ideas can come up from that =)

**Comment by andytudhope** [comment]
Perfect @ludmila-omlopes - thanks for the understanding and feedback ❤️ ! You can ping me anytime in the Riot chat @cryptowanderer (because life is just that much more fun as a pseudonym 😉 )

**Pull request closed without merging**
