### PR TITLE
New Icons

### PR DESCRIPTION
**Pull request by ajayesivan**
This PR adds all the icons from here: https://www.figma.com/file/qLLuMLfpGxK9OfpIavwsmK/Iconset?type=design&node-id=1%3A413&t=SGSFkhz6o6GJfsif-1

status: ready

### CODE REVIEW

**Review by siddarthkay — CHANGES_REQUESTED** [review]
The current code expects icons to be named with lower case, thats also one of the reasons why tests are failing :)

**Review by siddarthkay — APPROVED** [review]

**Comment by flexsurfer** [comment]
hey @ajayesivan just wondering what the size of new icons ?

**Comment by ajayesivan** [comment]
> hey @ajayesivan just wondering what the size of new icons ?

icon2 folder was `2.5MB`(590 files) after adding all the new icons it's `4.3MB`(1032 files).

**Review by ilmotta — APPROVED** [review]

**Comment by ilmotta** [comment]
@ajayesivan, quick question, how did you re-generate all the icons from Figma? Do we have a script of sorts?

**Comment by ajayesivan** [comment]
> @ajayesivan, quick question, how did you re-generate all the icons from Figma? Do we have a script of sorts?

No script. I regenerated the icons manually by selecting and exporting them all at once. Figma grouped them automatically by size, so it was easy.

**Comment by qoqobolo** [comment]
Hey @ajayesivan, can I ask you to rebase this PR against the latest develop, please, as we have one important fix merged?
Thanks!

**Comment by ajayesivan** [comment]
@qoqobolo Rebased 👍

**Pull request merged**
