### PR TITLE
removing testnet DApps while preparing for mainnet

### PR DESCRIPTION
**Pull request by pablanopete**
This PR removes all the testnet DApp contacts for now, there is too far of a gap in DApps that are supporting both testnet and main net; and while we will continue to research and test both testnet and main-net DApps it's better to remove those that aren't supported on main-net until we ship. 

Will need to keep in mind the communication of this to the community - trying to balance a DApp list of testnet DApps vs. Main-net DApps is unrealistic from a UX perspective and Status will be a main-net DApp itself very soon!

### CODE REVIEW

**Comment by chadyj** [comment]
👍 
This will help with testing confusion, and pave the way for new mainnet Dapps for the beta.

**Comment by oskarth** [comment]
@pablanopete Thanks! In future, please add to REVIEW if PR is ready for review. Also, would you mind resolving conflicts?

**Review by oskarth — APPROVED** [review]
IIRC changes to contacts (`resources/default_contacts.json`) might require migrations. But I guess we'll find out in QA.

**Comment by janherich** [comment]
@pablanopete Please resolve conflicts

**Review by yenda — APPROVED** [review]

**Comment by pablanopete** [comment]
@oskarth yes sorry did not know, not quite sure what can be done to fix conflicts.

**Comment by annadanchenko** [comment]
I'm strongly against removing All DApps. We Can clean up the list and leave only working DApps to showcase we can run them. See https://github.com/status-im/status-react/issues/3240

**Review by annadanchenko — CHANGES_REQUESTED** [review]
As we do not allow mainnet now in released builds it’s useless to control and remove them because Dapps are targeting Testnet. Users will be able to run them only on Testnet. They will not be able to switch to mainnet anyway. It's better to keep working DApps and remove only non-working. See #3240

**Comment by flexsurfer** [comment]
@pablanopete @annadanchenko let's close this PR for now, feel free to reopen or create new one, thanks

**Pull request closed without merging**
