### PR TITLE
fix(wallet): fix bridge transactions

### LINKED ISSUE #20534: User is not navigated to the activity tab after a bridge transaction is performed
Unfortunately, I was not able to report this issue initially within https://github.com/status-im/status-mobile/pull/19984 due to a bridge issue. I decided to postpone and retest it when bridge routes are able to be found.

### Steps:
1. Recover a user with available assets on mainnet (only on mainnet mode can the bridge be built).
2. Go to the bridge flow.
3. Select the network assets you want to bridge (Note: The mainnet bridge can be expensive, costing 30-70 USD. It is recommended to build the L2 bridge only, such as Opt -> Arb or Arb -> Opt where fee is less).
4. Perform the transaction.

### Actual result:
- After the transaction is performed, the user is navigated to the list of assets on the bridge page.
- "invalid argument 2:json: cannot unmarshal non-string" error is shown

image

### Expected result:
After the transaction is performed, the user should be navigated to the activity page of the account from which the transaction originated.

### Logs:
[logs.zip](https://github.com/user-attachments/files/15928483/logs.zip)

### ENV:
NIghtly 21 Jun 2024

### LINKED ISSUE #20850: App crashes after attempt to send collectible
### Steps:
1. Go to send a flow of any collectible
2. Confirm collectible sending

### Actual result:
App crashed after entering a password on the confirmation page of collectible sending

https://github.com/user-attachments/assets/4eb9c7c3-4d45-4ae1-bfe5-17341cbafb3f

### Expected result:
The collectible is sent (this flow works correctly on the desktop)

### Logs:
[mobile.txt](https://github.com/user-attachments/files/16338384/mobile.txt)

### ENV:
Nightly 22 Jul

### LINKED ISSUE #20900: {"code":"WPP-008","details":"no fee found"} {"code":"WPP-008","details":"no fee found"} error toast is shown after bridge transaction confirmation
Problems with bridge:
- error at attempt to bridge
- missing wallet details
IMAGE 2024-07-26 11:54:48

### Steps:
1. Perform any bridge transaction (no matter L1->L2,  L2->L2,  L2->L1)

### Actual result:
{"code":"WPP-008","details":"no fee found"} error toast is shown

https://github.com/user-attachments/assets/3205fe39-1ca3-446d-9917-38a158aa0f8f

### Expected result:
No error after bridge transaction confirmation

### Additional info:
On the desktop, the bridge routes can't be built at all
image

### Logs mobile
[logs bridge.txt](https://github.com/user-attachments/files/16252860/logs.bridge.txt)

### Logs desktop
[logs bridge desktop.txt](https://github.com/user-attachments/files/16252925/logs.bridge.desktop.txt)

_Originally posted by @VolodLytvynenko in https://github.com/status-im/status-mobile/issues/20631#issuecomment-2231241382_

### PR DESCRIPTION
**Pull request by briansztamfater**
fixes #20900 
fixes #20534
fixes #20850

### Summary

This PR fixes bridge transactions and UI fix on transaction confirmation page for bridge transactions as well. Also minor fix on navigation on bridging flow (dynamic set start-flow? param to wizard depending on where it is called).

#### Platforms

- Android
- iOS

##### Functional

- wallet / transactions

### Steps to test

- Open Status
- Go to bridge flow
- Enter a valid amount
- Go to transaction confirmation page
- Verify UI is not broken as in the screenshot of the linked issue
- Slide to confirm transaction
- Verify transaction is executed correctly

status: ready

### Risk

Described potential risks and worst case scenarios.

Tick **one**:
- [ ] Low risk: 2 devs MUST perform testing as specified above and attach their results as comments to this PR **before** merging.
- [x] High risk: QA team MUST perform additional testing in the specified affected areas **before** merging.

### CODE REVIEW

**Review by J-Son89 — APPROVED** [review]

**Comment by J-Son89** [comment]
Awesome work @briansztamfater! I tested this out.

I could bridge Ether from Mainnet to Optimism
I also tried Mainnet to Arbitrum, first time I confirmed it showed some error in the toast. 
I tried again and it worked then too 🙌

**Review by smohamedjavid — APPROVED** [review]

**Comment by J-Son89** [comment]
@briansztamfater - I updated branch in UI so QA have recent changes to block some assets from being bridged. Hope that's all good 👍
cc @status-im/mobile-qa

**Review by vkjr — APPROVED** [review]

**Comment by churik** [comment]
@briansztamfater 
Found a bug at an attempt to bridge 0.1 USD from Arbiscan to Optimism

Consequences: 
1) was not redirected to activity page
2) tx is failed and reverted with "Fail with error 'ERC20: transfer amount exceeds allowance", example https://arbiscan.io/tx/0xa834e4772e11daf3cfe0a9afba521e7fb0c4c2280bca6483fa27bbe99c99a5f2
3) Wallet freeze at update and eventually shows 0
Re-login helps.

We need to find out what is this error about (I believe some tx limits in Hop might not be met) and prevent users from making faulty txs.

Video:
https://github.com/user-attachments/assets/953e125f-2fe4-4487-a20b-52bdc8eb04e9

Logs: 

[logs (103).zip](https://github.com/user-attachments/files/16412198/logs.103.zip)

What I get after pull-to-refresh:
IMAGE 2024-07-29 13:49:35

Update: reproduced with USDc (any amount) at attempt to bridge to Optimizm

**Comment by churik** [comment]
reported separately, other than that PR is ready.

**Comment by Cuteivist** [comment]
@briansztamfater  @OmarBasem  Looks like it might fix https://github.com/status-im/status-mobile/issues/20850 (multi-tx-type has value 7 instead of 0 when payload is sent to status-go)

**Comment by churik** [comment]
@briansztamfater based on [discussion](https://discord.com/channels/1210237582470807632/1217175477395914893/1267459112875200626) I think it should be fixed inside PR

**Comment by briansztamfater** [comment]
> @briansztamfater based on [discussion](https://discord.com/channels/1210237582470807632/1217175477395914893/1267459112875200626) I think it should be fixed inside PR

Thanks @churik @VolodLytvynenko for testing. Support for approval transactions has been added in this PR here 4510a802606fa856a3fb0d2064c52bfe8d83cbb5

Another thing to note: even if we approve the token amount before executing the bridge transaction, bridge transactions can still fail if bonderFees are higher than the bridging amount.  Check this transaction to see the error: https://arbiscan.io/tx/0x75cffa208239be4706a26a4c7b0b728ac18e48969ddc107d8d1577ed398f4f86
I think we can add this check in the clients to prevent failing transactions, IMO we can implement that in a follow up PR for mobile in #20914.

**Review by J-Son89 — APPROVED** [review]

**Pull request merged**
