### PR TITLE
Crash when trying to add Waku settings in Advanced Settings #21155

### LINKED ISSUE #21155: Crash when trying to add Waku settings in Advanced Settings
# Bug Report

## Problem 

Crash when user attempts to add Waku settings.

### Expected behavior

User should be able to manage Waku custom settings. **Note**: This feature is not working on mobile already for a long time (many months).

### Actual behavior

In a release build the app crashes, in debug this is the error:

```
Error: No protocol method IDeref.-deref defined for type undefined:

This error is located at:
    in edit-node (created by legacy.status_im.ui.screens.wakuv2_settings.edit_node.views.edit_node)
    in legacy.status_im.ui.screens.wakuv2_settings.edit_node.views.edit_node
```

### Reproduction

1. Go to Advanced Settings
2. Open Wakuv2 settings
3. Press plus button

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

### PR DESCRIPTION
**Pull request by flexsurfer**
fixes #21155

### CODE REVIEW

**Review by Parveshdhull — APPROVED** [review]

**Comment by ilmotta** [comment]
Thanks @flexsurfer for resurrecting this feature and fixing the bug.

I kindly ask you to update the PR description with more details about what the feature looks like and what QAs can test about this, or problems that they might face while testing. The PR description would serve as a reference point for us to understand what this feature is all about. This is particularly important because nobody remembers exactly how this feature used to work since it has been broken for a long time, and there's nothing in Figma.

**Comment by flexsurfer** [comment]
hey @ilmotta thank you, actually, I would cc @churik, because it's an existing feature and i just fixed a small bug, which is referred to in the description, so I'm not sure if I can add anything

**Comment by churik** [comment]
Honestly it was probably added silently and a lot of time ago, we didn't even test it. 

So we won't be able to verify the expected behavior in particular case as we do not have any requirements, but we'll make sure that crash doesn't happen anymore

**Comment by mariia-skrypnyk** [comment]
HI @flexsurfer!

Thanks for your fix!
I reproduced this error on nightly build.
Now on your PR it is fixed for both platforms. 🙌🔧
Great job!
PR can be merged.

cc @churik @ilmotta

**Comment by ilmotta** [comment]
> So we won't be able to verify the expected behavior in particular case as we do not have any requirements, but we'll make sure that crash doesn't happen anymore

@churik @mariia-skrypnyk @flexsurfer, I failed to describe in the GH issue the expectation I personally had that we should understand if the feature works as intended, not just fix the UI crash.

Just one quick question, did you get a chance to test if the added nodes have the desired effects in the network? Everything is likely working because the endpoint in `status-go` wasn't changed, but testing this is important if we want to be able to promote the feature to power users, which I think would be nice for 2.31.

I'll try to bring this feature to @xAlisher's attention when he comes back, just so they can at least translate this feature to Figma.

**Pull request merged**
