### PR TITLE
Setup syncing timer fix

### LINKED ISSUE #15807: The counter of QR code showing is frozen on the 'Setup Syncing' page
### Steps to reproduce:
1. Open profile page -> Syncing -> tap [+] button -> activate "Reveal sync code"
2. Check  the counter

### Actual result:
The counter of QR code showing is frozen and always shown with 2:00 value
image

### Expected result:
The counter is going on
https://www.figma.com/file/V6nlpAWIf2e1XU8RJ9yQPe/Syncing-for-Mobile?type=design&node-id=675-178473&t=E8Cb80CFqKTSBBaD-0

### Additional Information
- Status version: nightly [4 May 2023]
- Operating System: Android, iOS

### PR DESCRIPTION
**Pull request by ajayesivan**
fixes #15807 

status: ready

### CODE REVIEW

**Review by J-Son89 — APPROVED** [review]

**Review by flexsurfer — APPROVED** [review]

**Review by alwx — APPROVED** [review]

**Comment by pavloburykh** [comment]
Hey @ajayesivan! Thanx for the PR. Please take a look at the following issue. 

### ISSUE 1 Sync code does not expire after 2 minutes and can be successfully used for syncing

**Steps:** 

1. Generate Sync code on Device 1
2. Make screenshot of QR code because it will be unavailable after timer is up. 
3. Wait until 2 minutes for expiration of timer 
4. Scan Sync QR by Device 2
5. See if error about sync code expiration will appear for Device 2

**Actual result:** error does not appear. Sync code does not expire and can be used after expiration period is up. 

**Expected result:** sync code should expire in 2 minutes after being generated. Using expired code should result in error "This sync code has expired". [Figma](https://www.figma.com/file/V6nlpAWIf2e1XU8RJ9yQPe/Syncing-for-Mobile?type=design&node-id=675-179730&t=vHafgfaYP1zPGpUV-0)

**Review by briansztamfater — APPROVED** [review]

**Comment by pavloburykh** [comment]
@ajayesivan I will move PR to CONTRIBUTOR column. Please, move it to E2E column when its ready for re-test. Thank you!

**Comment by ajayesivan** [comment]
> Hey @ajayesivan! Thanx for the PR. Please take a look at the following issue.
> 
> ### ISSUE 1 Sync code does not expire after 2 minutes and can be successfully used for syncing
> **Steps:**
> 
> 1. Generate Sync code on Device 1
> 2. Make screenshot of QR code because it will be unavailable after timer is up.
> 3. Wait until 2 minutes for expiration of timer
> 4. Scan Sync QR by Device 2
> 5. See if error about sync code expiration will appear for Device 2
> 
> **Actual result:** error does not appear. Sync code does not expire and can be used after expiration period is up.
> 
> **Expected result:** sync code should expire in 2 minutes after being generated. Using expired code should result in error "This sync code has expired". [Figma](https://www.figma.com/file/V6nlpAWIf2e1XU8RJ9yQPe/Syncing-for-Mobile?type=design&node-id=675-179730&t=vHafgfaYP1zPGpUV-0)

@pavloburykh This bug was not introduced in this PR, so can we go ahead and merge this PR? I will take care of this separately(https://github.com/status-im/status-mobile/issues/15945).

**Comment by pavloburykh** [comment]
> @pavloburykh This bug was not introduced in this PR, so can we go ahead and merge this PR? I will take care of this separately(#15945).

Hi @ajayesivan ! Sounds good. Should this PR be retested after rebasing branch? I see there are a lot of new commits in develop which could result in conflicts after rebasing. If re-test is not needed - then you are good to merge.

**Pull request merged**
