### PR TITLE
[Fix #2834] Migrate android build to latest gradle plugin

### LINKED ISSUE #2834: Migrate android build to latest gradle plugin
### User Story

As a developer, I want to use latest tools to benefit from greater performance

### Description

*Type*: Feature

Migrate to latest [gradle plugin](https://developer.android.com/studio/build/gradle-plugin-3-0-0-migration.html) as it provides greater compilation performance.

### PR DESCRIPTION
**Pull request by pacamara**
Fixes #2834 :  Migrate android build to latest gradle plugin

### Summary:

Upgrade the android build to use gradle 3.0.1.

### Steps to test:

Follow usual Android build instructions at https://wiki.status.im/Building_Status#Building_Status_for_Development

### CODE REVIEW

**Comment by jeluard** [comment]
Thanks! Is there anything special to consider when upgrading from a working dev environment? Or just `git pull` and it works?

**Comment by pacamara** [comment]
@jeluard  You're welcome! :)   I'll check the upgrade behaviour.
For a fresh checkout I needed these extra steps on my Debian distro (none of which are due to the gradle upgrade):
* Increase /proc/sys/fs/inotify/max_user_watches 
* Set ANDROID_NDK_HOME env var
* Generate a bogus ~/.gradle/status-im.keystore for release build

Have updated the PR as I'd missed a necessary fix for release build. Did a force push to keep it as a single commit, the extra change is in gradle.properties. Both release and debug builds now build per https://wiki.status.im/Building_Status

**Comment by pacamara** [comment]
@jeluard Upgrade works! Tested like this:
* git clone https://github.com/status-im/status-react.git  
* Follow steps for debug build
* git remote add pacamara https://github.com/pacamara/status-react.git
* git pull pacamara develop_issue2834
* Follow steps for debug build again, it works
* Follow steps for release build, also works

**Review by jeluard — APPROVED** [review]

**Comment by pacamara** [comment]
@jeluard  I notice it's failing the jenkins build, but at the moment I can't view the log so have no idea why. Could you paste the log somewhere? (say pastebin)

**Comment by jeluard** [comment]
@pacamara We currently have issues with our internal jenkins. I will get back to you as soon as we have it back up!

**Comment by pacamara** [comment]
@jeluard Got it :)

**Comment by jeluard** [comment]
@pacamara We still have some issues with Jenkins. Can you rebase this branch with latest develop?

**Comment by pacamara** [comment]
@jeluard Sure, one moment...

**Comment by pacamara** [comment]
@jeluard Done! Force pushed here so we can keep it on this PR.

**Review by goranjovic — APPROVED** [review]

**Comment by oskarth** [comment]
@jeluard @goranjovic Can either of you sanity check test this locally and make sure CI builds? If it does, lets merge it. (QA TODO too big).

**Comment by jeluard** [comment]
@oskarth I tried locally and it works fine. No idea why Jenkins fails. I understand from @v2nek external PR  are not supposed to be build.

**Comment by oskarth** [comment]
Couldn't find it in Jenkins, but I triggered build here: https://jenkins.status.im/job/status-react/job/parametrized%20build/ #280 - let's see what it says.

**Comment by goranjovic** [comment]
@jeluard @oskarth I can't build #2858 - also external PR, tried locally and looked ok, not sure what is wrong with Jenkins

**Comment by oskarth** [comment]
@goranjovic (Unrelated) tests failed for build 280 anyway, so most likely because it isn't rebased. But on the other hand `JENKINS_REBASE_DEVELOP` is set to 1 in that build, so it should rebase. Not sure what's wrong.

**Comment by pacamara** [comment]
@oskarth It's been a week since this PR was last rebased, shall I rebase again?

**Comment by oskarth** [comment]
@pacamara Yes please, our CI should do it automatically but doesn't appear to be working.

cc @v2nek

**Comment by pacamara** [comment]
@oskarth @v2nek  Done! 
Debug and release local builds pass normally after rebasing.

**Comment by pacamara** [comment]
@oskarth  @v2nek ...as does the jenkins build :beers:

**Comment by oskarth** [comment]
Thanks @pacamara! Merging.

**Comment by oskarth** [comment]
Nightly looks like it is failing because of this change, looks like CI on this PR didn't actually succeed:

```
[react_pull_requests_PR-2844-5AUROJC26LUPXLHJXYU5BYGUT6EEAHFTHBRQA6RRMH7MVVF2KI5Q] Running shell script
+ curl https://upload.diawi.com/ -F token=**** -F file=@android/app/build/outputs/apk/app-release.apk -F find_by_udid=0 -F wall_of_apps=0
+ jq -r .job
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (26) couldn't open file "android/app/build/outputs/apk/app-release.apk"
[Pipeline] sh
[react_pull_requests_PR-2844-5AUROJC26LUPXLHJXYU5BYGUT6EEAHFTHBRQA6RRMH7MVVF2KI5Q] Running she
```

Likely due to folder change when upgrading Gradle. We should figure out why CI failed and test it before merging.

**Comment by oskarth** [comment]
@v2nek issued probable fix: https://github.com/status-im/status-react/pull/3026

**Pull request merged**
