### PR TITLE
feature #4255 - backup recovery phrase in desktop app

### LINKED ISSUE #4255: Display seed phrase after creating a desktop account
### User Story

As a user, I want to restore my account from seed phrase if it was created in status-desktop

### Description
*Type*: Feature
*Summary*: no seed phrase is displayed in profile after creating an account in status-desktop

#### Expected behavior
you can back up your seed phrase in 'Profile'

#### Actual behavior
no seed phrase is displayed

### Reproduction

- Install `status-desktop` 
- Open StatusIm 
- Create new account
- Go to profile

### Additional Information
* Status version: StatusIm desktop (version 2018-05-07)
* Operating System: MacOS High Sierra 10.13.4, Ubuntu 18.04

### PR DESCRIPTION
**Pull request by goranjovic**
fixes #4255 

### Summary:

Adds the option to Backup recovery phrase in user profile, the same way it works in mobile app.

### Testing notes (optional):
The image is intentionally omitted from the first (intro) step, due to an issue with screen dimensions on desktop.

### Steps to test:
- Upgrade desktop app with existing account and then back up the recovery phrase from Profile
- Create an account on desktop and back up the recovery phrase
- Try recovering it either on another desktop or on mobile
- Double check that recovery phrase backup is still ok on mobile 

status: ready

### CODE REVIEW

**Review by rasom — APPROVED** [review]

**Review by vkjr — APPROVED** [review]

**Review by vitvly — APPROVED** [review]

**Comment by churik** [comment]
@goranjovic 
can you please rebase on latest `develop`?
If I try to log in with existing account, I see message "We detected problem with your encription key"
image

[StatusIm.log](https://github.com/status-im/status-react/files/2437526/StatusIm.log)
Probably rebasing to latest `develop` will fix it.

**Comment by churik** [comment]
@goranjovic Thank you for PR!
Tested on IOS, Android - couldn't find any regression issues.
On desktop it works the same way as mobile.
Only one small enhancement - we can proceed with `Enter` key when creating account, joining public, 1-1 chat, account restore (after meging https://github.com/status-im/status-react/pull/6041)
This behavior is missing on 2,3 steps in backup recovery phrase, thus should manually click on "Next".
Would you mind to add it in this PR or will be better to create separate issue?

**Comment by goranjovic** [comment]
@churik Ok, I managed to make it react on Enter on the two screens where you enter a random word from the phrase. That worked using the same trick from #6041.

To make enter work on the other screens, however, we'll probably need to update react-native-desktop

**Comment by churik** [comment]
Tested backup recovery phrase on IOS, Android, desktop app (Mac OSx only).
Can proceed with Enter on 2,3 steps.
Backup recovery phrase is not shown if account is recovered.

**Comment by chadyj** [comment]
@goranjovic I thought you mentioned that backup recovery phrase is shown if account is recovered? (so that the accounts on desktop got a chance to recover)

**Pull request merged**
