### PR TITLE
Introduce OFFLINE_INBOX_MANY_ENABLED flag for perf quickfix

### PR DESCRIPTION
**Pull request by oskarth**
Workaround for https://github.com/status-im/status-react/issues/2852 to unblock people from running app (it prevented @yenda from attending test session e.g. IIRC).

Since offline inboxing and desktop were introduced, we went from testing with ~10 messages to ~1000 messages. This surfaced inefficiencies such as this issue. It also means someone who joins a public channel such as #status will experience significant lag when signing in. To remedy this, we put offline inboxing for public/group chats under a flag until the underlying perf issue has been resolved.

### Testing notes (optional):
- Make sure offline inboxing doesn't work for public / group chat
- Check if perf issues are still as bad as #2852 when lots of messages to #status in Desktop e.g. 

This might require setting up a new account to get a fresh state of messages. Otherwise you are likely to hit perf issue due to old messages.

status: ready

### CODE REVIEW

**Comment by oskarth** [comment]
See https://github.com/status-im/status-react/issues/2942 for factored issue to track, which is separate from root perf problem.

**Comment by dmitryn** [comment]
@oskarth i'm not sure what this change is about. According to the name, this flag should turn on/off feature with using many whisper topics, as far as i get it.

We already have flag to enable/disable offline inboxing, why do you use 2 flags to toggle that feature?

**Comment by oskarth** [comment]
@dmitryn This is additional flag only for public and group chat, not 1on1. Workaround for perf problems that arise with thousands of messages in e.g. #status 

> using many whisper topics

nope, that's a different flag :D

**Comment by dmitryn** [comment]
@oskarth i see. The name of the flag confused me, sorry.

**Review by yenda — APPROVED** [review]

**Review by dmitryn — APPROVED** [review]

**Comment by oskarth** [comment]
Possibly already tested in release branch, in which case this can be merged straight away if CI passes.

cc @annadanchenko @asemiankevich

**Comment by annadanchenko** [comment]
1. expected: Offline inboxing does not work in group/public chat
2. Performance is better but still bad if user had even one 1-1 chat with 6-7 messages on both sides, 1 group chat and recovered an account: on Android 1-1 chat is shown with messages from one side only and Group chat with no messages. If try to switch tabs it's slow, if open chats and then return back to Chats and try to switch tabs then they do not switch, in about a minute after it OS closes app (so it's kind of crashed)

TF after recover: https://app.testfairy.com/projects/4803622-status/builds/7457990/sessions/11/?accessToken=QZZj9nRRFo2KPGElTMtIll9SgF0

**Comment by oskarth** [comment]
> but still bad if user had even one 1-1 chat with 6-7 messages on both sides, 1 group chat and recovered an account: on Android 1-1 chat is shown with messages from one side only and Group chat with no messages.

@annadanchenko This is expected. This PR doesn't fix root perf issue, just the issue where you have 1000 messages coming in from public chat like #status.

> on Android 1-1 chat is shown with messages from one side only and Group chat with no messages. If try to switch tabs it's slow, if open chats and then return back to Chats and try to switch tabs then they do not switch, in about a minute after it OS closes app (so it's kind of crashed)

Hm ok. This seems like possibly a few different issues.

**Comment by oskarth** [comment]
@annadanchenko 

> on Android 1-1 chat is shown with messages from one side only and Group chat with no messages.

What's minimal steps to reproduce this? Can we create another issue for this?

> If try to switch tabs it's slow, if open chats and then return back to Chats and try to switch tabs then they do not switch, in about a minute after it OS closes app (so it's kind of crashed)

Same with this one

To me it isn't clear that they are the same issue as e.g. https://github.com/status-im/status-react/issues/2852#issuecomment-354779995

**Comment by annadanchenko** [comment]
Made a separate issue for new perf problems: https://github.com/status-im/status-react/issues/2990

**Pull request merged**
