### PR TITLE
Fetch new version of base images with fixed ubuntu-server (Release edition)

### PR DESCRIPTION
**Pull request by vkjr**
Related to status-im/security-reports#6

## NOTE: Changes taken from  #8212 
This PR created because release branch has not latest changes from develop and cherry-picking of #8212 is impossible.
Per discussion with @mandrigin, this is a fastest way to get vulnerability fix into release.

### Summary

New binaries of `ubuntu-server` with security fix were generated for all platforms and uploaded to digitaloceanspaces
Nix files were updated to use fixed binaries

### Review notes
ubuntu-server binaries uploaded, nix files changed to download new versions

### Testing notes
Replacing ubuntu-server won't affect app logic but can affect app startup. So if it starts and able to login then `ubuntu-server` works fine with `react-native-desktop` and `realm.

#### Platforms
- macOS
- Linux
- Windows

##### Functional
- new account
- user profile updates

### Steps to test

- Open Status
- Ensure it runs
- Ensure you are able to login

status: ready

### CODE REVIEW

**Review by pedropombeiro — APPROVED** [review]

**Comment by vkjr** [comment]
@jakubgs, in `develop` we have few commits with nix changes and they aren't in `release/0.12.x` branch. So when build system tries to rebase this PR onto `develop`, it fails.
Can we avoid this without having to transfer all nix-related commits from @PombeirP to release branch?

**Comment by jakubgs** [comment]
The rebase happens almost alway, with few exceptions:
https://github.com/status-im/status-react/blob/713a461415a479277658a66036917830436eb0f6/ci/utils.groovy#L44-L62
For example when `BUILD_TYPE` is `release`. For PRs the value is `pr` so it would rebase.
If you don't want it to you'd have to modify the `doGitRebase` method with some exception.

**Comment by annadanchenko** [comment]
@vkjr @mandrigin @PombeirP is it a big issue to add nix changes to release/0.12.x ?

**Comment by jakubgs** [comment]
I don't think it's a big issue, it's just that there's a bunch of them. @PombeirP would know best.

**Comment by vkjr** [comment]
I tried to create a branch from release and apply all cherry-picked commits that touched `nix` folder to it. But faced a conflict in the end. I'd prefer not to take a risk of solving it without @PombeirP and understanding what is going on.

Can we apply changes from this PR directly to `release/0.12.x` branch without creating PR (and without rebasing)? Or that is prohibited by our git policies and will break next PRs?

**Comment by jakubgs** [comment]
>Can we apply changes from this PR directly to release/0.12.x branch without creating PR (and without rebasing)? Or that is prohibited by our git policies and will break next PRs?

It shouldn't break anything as far as I know.

**Comment by vkjr** [comment]
@mandrigin, wdyt?

**Comment by pedropombeiro** [comment]
I don't see the point in rebasing a release branch build anyway. In my perspective that should only happen for PR branch builds.

**Comment by jakubgs** [comment]
https://github.com/status-im/status-react/pull/8218 - this would solve this issue

**Comment by jakubgs** [comment]
I've merged https://github.com/status-im/status-react/pull/8218 and cherry picked c90fe74d9fa5ed71cfe52d95156280e35ff344a5 for the release branch: b356339a0f8c22c2f01971c3822cb7445a99c2b6

Please rebase your branch.

**Comment by jakubgs** [comment]
Ooooh, I'm stupid. your branch doesn't start with `release/`, it starts with `fix/release/`... ugh.

**Comment by jakubgs** [comment]
Maybe you could rename it to `release/fix/...`? Not sure if this is doable...

**Comment by vkjr** [comment]
@jakubgs, I created #8219. It starts with `release`.. but that didn't help

**Comment by jakubgs** [comment]
Well, that doesn't make any sense... I'll check it.

**Comment by jakubgs** [comment]
Okay, is see what's happening:
```
On branch PR-8214
```
The way Jenkins does this is it pulls the PR branch as `refs/remotes/origin/PR-8214`, and not as `refs/remotes/origin/fix/release/0.12.x/ubuntu_binaries`, which makes the check do nothing.

**Comment by mandrigin** [comment]
probably you can make doGitRebase do nothing in this branch... it is not indended to be in `develop` anyway

**Review by mandrigin — APPROVED** [review]

**Comment by jakubgs** [comment]
This should be better: https://github.com/status-im/status-react/pull/8220
We use the `CHANGE_TARGET` variable that Jenkins sets to rebase against the right branch, not always against `develop`.

**Comment by jakubgs** [comment]
Ok, merged #8220 as 4f4cc91b88866b437bfe2858c016098bcff625d9, cherry picked for release as 1129f361d4bd32918fd18cd64f4a6e067a456aa3, try rebasing.

**Comment by jakubgs** [comment]
NICE, it worked:
```
18:03:18  + git status
18:03:18  On branch PR-8214
18:03:18  nothing to commit, working tree clean
[Pipeline] sh
18:03:18  + git fetch --force origin release/0.12.x:release/0.12.x
18:03:19  From https://github.com/status-im/status-react
18:03:19   * [new branch]          release/0.12.x -> release/0.12.x
[Pipeline] sh
18:03:19  + git rebase release/0.12.x
18:03:19  Current branch PR-8214 is up to date.
```
I took the liberty to rebase myself.

**Comment by mandrigin** [comment]
okay, everything was build okay, so I cherry-picked it to the release branch

**Comment by mandrigin** [comment]
see https://github.com/status-im/status-react/commit/d944244aa284e5282051918fff3efddaf5bd10af
closing this PR

**Comment by vkjr** [comment]
@jakubgs, @mandrigin, thank you!

**Pull request closed without merging**
