### PR TITLE
fix: sometimes channels do not randomly appear in test community afte…

### LINKED ISSUE #18455: Sometimes channels do not randomly appear in test community after its creation
# Bug Report

## Problem 

Sometimes channels do not randomly appear in the test community after its creation, this leads to failures in e2e tests and is also reproducible manually.

Example:
https://github.com/status-im/status-mobile/pull/18374#issuecomment-1884660314 in `1. test_community_hashtag_links_to_community_channels, id: 702948`
On the [video](https://app.eu-central-1.saucelabs.com/tests/f4c8fcc2d8b145fbbd06c0718dd7cf14?auth=cf2405c3f14cb355888676d06d06f72c#245) (14:19) you can see that the `#general` channel is not displayed on the channel list and this caused the test to fail.

### Reproduction

1. Install any PR build 
2. Open the `Communities` screen
3. Tap `+`
4. `Create closed community`
5. Open the community

You may have to repeat these steps several times until the community opens without one of the channels.
Full list of channels: #general, #cats, #dogs, #rules

#### Expected behavior
Screenshot 2024-01-10 at 18 23 08

#### Actual behavior

No `#rules` channel
Screenshot 2024-01-10 at 18 23 54

### Logs

[geth.log.zip](https://github.com/status-im/status-mobile/files/13891149/geth.log.zip)
[Status.log.zip](https://github.com/status-im/status-mobile/files/13891150/Status.log.zip)

### Additional Information

- Status version: nightly (only for x86 builds used for e2e), PR builds
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by qfrank**
fixes #18455

#### Platforms

- Android
- iOS

status: ready

### CODE REVIEW

**Review by mohsen-ghafouri — APPROVED** [review]

**Review by ilmotta — APPROVED** [review]

**Comment by qoqobolo** [comment]
Pinging @status-im/mobile-qa: please review the e2e results once they are ready, whoever has free hands, thanks!

**Comment by VolodLytvynenko** [comment]
Hi @qfrank thank you for the PR. The original issue is fixed. However, a regression issue has been found, which seems to have originated from the Status-Go code. Could you please check it?

## ISSUE 1: The app crashes during the sync process; After reopening the app and logging in, the community is not synced
### Steps to reproduce:
1. `User A` creates a community.
2. `User A` generates a sync QR code.
3. `User B` scans `User A's` sync QR code.

### Actual result:

`User B's` app crashes during the sync process.
After reopening the app and logging in, the community is not synced.

https://github.com/status-im/status-mobile/assets/52490791/34f859ec-d6d3-4d58-861a-4d40f3375867

### Expected result:

User B should be able to sync with User A's without the app crashing, and the community should be successfully synced.

### Devices:
- iPhone 11 Pro max, IOS 17
- Pixel 7a, Android 13

### Logs:
logcat [sync.txt](https://github.com/status-im/status-mobile/files/14362162/sync.txt)
[Status-debug-logs.zip](https://github.com/status-im/status-mobile/files/14362166/Status-debug-logs.zip)

**Comment by VolodLytvynenko** [comment]
@qfrank Will be appreciated if you can share any other areas related to the communities or the entire system that could be impacted by the current PR

**Comment by qfrank** [comment]
Hi @VolodLytvynenko , thank you for the feedback, issue 1 reproduced, `creating community chat/category` /  `receiving community message` could be impacted, latest commit should fix issue 1 now

**Comment by VolodLytvynenko** [comment]
hi @qfrank thank you for PR. Sorry for the testing delay. I have been waiting for e2e results. PR is ready to be merged

**Pull request merged**
