### PR TITLE
fix_: no peers available supporting LightPush protocol after network restored from disabled state

### PR DESCRIPTION
**Pull request by qfrank**
fix relate mobile issues: [21452](https://github.com/status-im/status-mobile/issues/21452) / [21394](https://github.com/status-im/status-mobile/issues/21394), and might also fix part(missing messages) of [21172](https://github.com/status-im/status-mobile/issues/21172)

relate status-go [PR](https://github.com/status-im/status-go/pull/6153)

#### Platforms

- Android
- iOS

status: ready

### CODE REVIEW

**Comment by mariia-skrypnyk** [comment]
Hi @qfrank !

Thanks for PR.
Can I start testing it as I see open discussion here https://github.com/status-im/status-mobile/issues/21172#issuecomment-2513897147
In case "yes" then rebase please current PR and resolve conflicts.
Thanks!

**Review by ilmotta — APPROVED** [review]

**Comment by qfrank** [comment]
> Hi @qfrank !
> 
> Thanks for PR. Can I start testing it as I see open discussion here [#21172 (comment)](https://github.com/status-im/status-mobile/issues/21172#issuecomment-2513897147) In case "yes" then rebase please current PR and resolve conflicts. Thanks!

rebased :) @mariia-skrypnyk

**Comment by mariia-skrypnyk** [comment]
Hey @qfrank !

I've checked: 

1)  https://github.com/status-im/status-mobile/issues/21452 / https://github.com/status-im/status-mobile/issues/21394 messages sending-receiving checked and looks lood
https://github.com/status-im/status-mobile/issues/21172 - I saw no issue with messages but not sure is this issue is still under fixing or finished and ready.
     

**2) Online/Offline statuses visibility** 

I've noticed that if user A and user B become mutual contacts they both see each other as offline for 4-5 min.
We can trigger status change in Profile.
User A: accepted contact request of User B and waited 4 min till saw User B became "online"
User B: finally sees user A online after 5 min
User A: turn on Pilot mode (no internet) and send messages to User B
User B: wait till User A became offline (I counted 6 min)
User A: turn off  Pilot mode
User B: receives all messages from User A and after 5 min waiting finally sees User A became "online"

iOS: 
[logs_status_ios.zip](https://github.com/user-attachments/files/18023530/logs_status_ios.zip)

Android: 
[logs_status_android.zip](https://github.com/user-attachments/files/18023545/logs_status_android.zip)


**3) Receiving messages after Sender returned from offline**

**Good news:** User B got ALL messages in 1-2 sec right after User A became online (got result from my steps above)

So, from my perspective status change is too long and doesn't show the real user status.
Messages receiving in 1-1 chats works good.

**Bad news:** I have not all messages fetched in Status community. (after 20 min)
Could it be addressed here or separatelly?
[logs_status_community.zip](https://github.com/user-attachments/files/18023561/logs_status_community.zip)

**Comment by churik** [comment]
From the feedback above I consider this PR as significant improvement to message reliability and suggest to merge it for 2.32.

Online/Offline statuses visibility  are out of scope of this Pr to my understanding

**Pull request merged**
