### PR TITLE
[WIP] Experiment with `react-native-skia` Library

### PR DESCRIPTION
**Pull request by siddarthkay**
- PR made to test CI builds
- Upgraded `reactjs` to `18.0.0`
- Added `react-native-skia` library.
- Added `cmake` to Android `shells.nix`
- Specify `cmake` -> `3.10.2`
- Specify `ndkVersion` -> `21.1.6352462`

This may or may not solve our blur issues, idk : https://shopify.github.io/react-native-skia/docs/image-filters/blur will play around and find out.

status: wip

### CODE REVIEW

**Comment by flexsurfer** [comment]
> This may or may not solve our blur issues, idk

it won't solve, because its an image on the canvas, its not a RN tree

**Comment by siddarthkay** [comment]
Issue : 
```log
[2023-05-10T08:06:17.812Z] * Exception is:

[2023-05-10T08:06:17.812Z] org.gradle.api.internal.tasks.TaskDependencyResolveException: 
Could not determine the dependencies of task ':shopify_react-native-skia:generateJsonModelRelease'
.
.
.
[2023-05-10T08:06:17.813Z] Caused by: java.lang.RuntimeException: 
CMake '3.10.2' was not found in PATH or by cmake.dir property.
```

lol : https://shopify.github.io/react-native-skia/docs/getting-started/installation#troubleshooting

**Comment by siddarthkay** [comment]
argh, still this : 

```log
[2023-05-10T09:44:05.393Z] FAILURE: Build failed with an exception.
[2023-05-10T09:44:05.393Z] 
[2023-05-10T09:44:05.393Z] * What went wrong:
[2023-05-10T09:44:05.393Z] Could not determine the dependencies of task 
':shopify_react-native-skia:generateJsonModelRelease'.
[2023-05-10T09:44:05.393Z] > CMake '3.10.2' was not found in PATH 
or by cmake.dir property.
[2023-05-10T09:44:05.393Z] 
[2023-05-10T09:44:05.393Z] * Try:
[2023-05-10T09:44:05.393Z] Run with --info or --debug option to get more log output. 
Run with --scan to get full insights.
[2023-05-10T09:44:05.393Z] 
[2023-05-10T09:44:05.393Z] * Exception is:
[2023-05-10T09:44:05.393Z] org.gradle.api.internal.tasks.TaskDependencyResolveException: 
Could not determine the dependencies of task 
':shopify_react-native-skia:generateJsonModelRelease'.
```

will resume workin on this later.

**Comment by flexsurfer** [comment]
hey @siddarthkay still relevant?

**Comment by siddarthkay** [comment]
@flexsurfer : I'll try again after RN69 upgrade

**Pull request closed without merging**
