### PR TITLE
[#21615] fix: hide mercuryo provider

### LINKED ISSUE #21615: 🙈 Hide Mercuryo from the list of on-ramp providers
# Feature Issue

### User Story

As a lawyer, 
I want to hide Mercuryo from the list of on-ramp providers
**so that** we stay compliant with UK law. 

### Description

Mercuryo doesn't have the license to operate in UK. Having non-licensed financial providers can lead to legal troubles. So we have decided to hide it in the interim.

This is a UI only change, ie the Mercuryo provider should be hidden behind a feature flag. 
Mercuryo might make a comeback as they are already working on the license.

### Acceptance Criteria

- [ ] A feature flag hides Mercuryo from the list of on-ramp providers

### PR DESCRIPTION
**Pull request by mohsen-ghafouri**
fixes #21615

### Summary

hide Mercuryo from the list of on-ramp providers
so that we stay compliant with UK law.

Note: it only has [status-go changes](https://github.com/status-im/status-go/pull/6100)

#### Areas that maybe impacted

- Ways to buy asset modal

### Result

status: ready

### CODE REVIEW

**Review by vkjr — APPROVED** [review]

**Comment by Horupa-Olena** [comment]
@mohsen-ghafouri Thanks for your PR!
Could you please resolve the issues with the failed builds?

**Review by smohamedjavid — APPROVED** [review]

**Comment by mohsen-ghafouri** [comment]
Hi @Horupa-Olena, all good now.

**Comment by Horupa-Olena** [comment]
@mohsen-ghafouri Thanks for your work!
Since Mercuryo has been hidden from the app, the Recurrent tab is now empty, which doesn’t look great. Could you also hide this tab as part of this PR?
photo_2024-11-21_10-35-32
photo_2024-11-21_10-35-29

**Comment by mohsen-ghafouri** [comment]
Hi @Horupa-Olena, please test again. applied changes.

**Comment by Horupa-Olena** [comment]
@mohsen-ghafouri Thanks for your work!
Please resolve the conflicts so I can start testing.

**Comment by mohsen-ghafouri** [comment]
@Horupa-Olena done

**Comment by Horupa-Olena** [comment]
@mohsen-ghafouri Thank you! Everything looks good.
This PR is ready to be merged.
photo_2024-11-22_15-41-07

**Pull request merged**
