### PR TITLE
Profile picture sync

### LINKED ISSUE #11558: Profile picture is not syncing across devices
# Feature Issue
Following on #11347

### User Story

As a user, I want to have my profile picture updated across all my synced devices.
**Steps:**

- Device 1: restore multiaccount A from seed phrase, set profile picture
- Device 2: restore multiaccount A from seed phrase
- Pair both devices
- Sync both devices

### Acceptance Criteria
after updating profile image it is updated on all synced devices

### PR DESCRIPTION
**Pull request by vitvly**
Fixes #11558
Depends on https://github.com/status-im/status-go/pull/2606

Verified that once 2 devices are synced, profile picture updates are synced between devices on-the-fly.

### CODE REVIEW

**Review by Parveshdhull — APPROVED** [review]

**Comment by pavloburykh** [comment]
@siphiuel hi! IOS builds are failing. Could you please take a look at this when you have a chance. Thanx!
This one I tried to rebuild today https://ci.status.im/job/status-react/job/prs/job/ios/job/PR-13249/11/console

**Comment by vitvly** [comment]
@pavloburykh sorry, missed it. ios builds seem to be ok after full rebase

**Comment by pavloburykh** [comment]
> @pavloburykh sorry, missed it. ios builds seem to be ok after full rebase

@siphiuel thank you. Works perfect now.

**Comment by pavloburykh** [comment]
@siphiuel Thanks for PR. Please, take a look at the following issue

### ISSUE 1 Profile picture does not appear on second device after sync and pairing

**Steps to reproduce:**
1. Create new account on Device 1 (in my case Android)
2. Add profile picture in Device 1
3. Restore same account on Device 2 (in my case IOS)
4. Pair and sync Device 1 and Device 2
5. Check if profile picture appeared on Device 2 after sync

**Actual result:** profile picture has not appeared on Device 2 after sync. Relogin does not help. Further changing of pictures does not result in syncing on paired devices. 

**Expected result:** profile picture is synced

On below video Device 1 (Android) is on the left side, Device 2 (IOS) is on the right

[android_geth.log](https://github.com/status-im/status-react/files/8472507/android_geth.log)
[ios_geth.log](https://github.com/status-im/status-react/files/8472513/ios_geth.log)


https://user-images.githubusercontent.com/97245802/162952472-c4960063-e5b3-4fec-91f9-f4b4a39aae10.mp4

**Comment by vitvly** [comment]
@pavloburykh weird, i just tried to reproduce it with Xiaomi A2 Lite real device and ios simulator, with fresh account created on the android phone. It works ok. Thinking what could be wrong in your case.

**Comment by pavloburykh** [comment]
> @pavloburykh weird, i just tried to reproduce it with Xiaomi A2 Lite real device and ios simulator, with fresh account created on the android phone. It works ok. Thinking what could be wrong in your case.

@siphiuel that is my fault, I messed up with apks on my Android and installed the wrong one. Sorry for that. Will continue testing. For now, basic sync test worked as expected.

**Comment by pavloburykh** [comment]
@siphiuel please, take a look at this bug. This time it is valid issue))

### ISSUE 2 Profile picture is not synced if "show your profile picture to"/"show profile pictures from" settings values were changed

**Steps to reproduce:**
1. Create new account on Device 1 (in my case Android)
2. Add profile picture on Device 1
3. Change "show your profile picture to" or "show profile pictures from" settings value from default "Contacts" to "Everyone"
photo_2022-04-12 20 45 41

4. Restore same account on Device 2 (in my case IOS)
5. Pair and sync Device 1 and Device 2
6. Check if profile picture appeared on Device 2 after sync

**Actual result:** profile picture is not synced

**Expected result:** profile picture is synced

On below video Device 1 (Android) is on the left side, Device 2 (IOS) is on the right

[android_geth.log](https://github.com/status-im/status-react/files/8475312/android_geth.log)

[ios_geth.log](https://github.com/status-im/status-react/files/8475314/ios_geth.log)


https://user-images.githubusercontent.com/97245802/163023168-312f3b6d-b64e-4413-aea8-553cda591dc9.mp4

**Comment by vitvly** [comment]
@pavloburykh fixed it, it wasn't really the profile picture visibility setting, but any setting changed from default would've triggered this. Thanks for spotting the issue.

**Comment by pavloburykh** [comment]
@siphiuel thanx for fixes. Ready for merge.

**Pull request merged**
