### PR TITLE
fix long-press message/chat preview is missing

### LINKED ISSUE #20312: Long-press message/chat preview is missing
# Bug Report

## Problem 

We should display a message/chat preview on long press. 

### Reproduction

1 - Message
1. Send a message
2. Long press on the message

2 - Chat
1. Open the home screen
2. Long press on the chat 

3 - Reactions
1. Send a message
2. Add a reaction
3. Long press on the reaction

#### Expected behavior

https://www.figma.com/design/7KIYbhoqNGAIFonE0w9TDz/Messages-for-Mobile?node-id=1447-349773&t=Oz48qhdeErsOTl7W-4

https://www.figma.com/design/7KIYbhoqNGAIFonE0w9TDz/Messages-for-Mobile?node-id=1803-400893&t=Oz48qhdeErsOTl7W-4

https://www.figma.com/design/PPWkgOYlZZDxZv5SDGsZVV/Posts-%26-Attachments-for-Mobile?node-id=2869-259157&t=zFLgxEKPDjeSSnGu-4

Screenshot 2024-06-03 at 17 49 05

Screenshot 2024-06-03 at 17 49 24

Screenshot 2024-06-03 at 17 51 51

#### Actual behavior

Screenshot 2024-06-03 at 17 48 37

Screenshot 2024-06-03 at 17 51 05

Screenshot 2024-06-03 at 17 52 46

### Additional Information

- Status version: RC 2.29 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by Parveshdhull**
fixes https://github.com/status-im/status-mobile/issues/20312

### Testing
Please also test https://github.com/status-im/status-mobile/issues/19662

status: ready

### CODE REVIEW

**Review by flexsurfer — APPROVED** [review]

**Comment by pavloburykh** [comment]
@Parveshdhull thank you for such a quick fix. Please, take look at the issue

### ISSUE 1 Border radius is not applied for syncing screen bottomsheet (IOS)

Affects only IOS. Tested on iPhone X, IOS 16.7.7


photo_2024-06-05 14 16 11

**Comment by Parveshdhull** [comment]
Thank you @pavloburykh for testing the PR and finding the issue. The issue should also be fixed for iOS now.

**Review by jo-mut — APPROVED** [review]

**Comment by pavloburykh** [comment]
@Parveshdhull thank you! ISSUE 1 is fixed. Please, take a look at ISSUE 2

### ISSUE 2 Group chats are missing preview

@Parveshdhull if this is not an easy fix I propose to address it separately in order not to block PR from merging. I do not remember if Group chats Preview has been implemented before, maybe not. 

**Actual result:** 


https://github.com/status-im/status-mobile/assets/97245802/7f9c248a-a1f6-45cb-b704-4b9b0fbd458c


**Expected result:** 

https://www.figma.com/design/7KIYbhoqNGAIFonE0w9TDz/Messages-for-Mobile?node-id=1803-400893&t=jkFSEIv1o4po6IdD-0


Screenshot 2024-06-03 at 17 49 24

**Comment by pavloburykh** [comment]
Will log ISSUE 2 separately as this component has never been implemented. @Parveshdhull PR is ready for merge. Thank you!

**Pull request merged**
