### PR TITLE
Hide group chats behind flag

### PR DESCRIPTION
**Pull request by janherich**
[comment]: # (Please replace ... with your information. Remove < and >)
[comment]: # (To auto-close issue on merge, please insert the related issue number after # i.e fixes #566)

Introduces flag `GROUP_CHATS_ENABLE` in `.env` files in accordance with https://github.com/status-im/status-react/pull/4244, which will control if option to create new group chat is shown or not. This will enable us to still resolve all the bugs in development mode, while the group chats will be disabled in jenkins/prod builds.

### Testing notes (optional):
Make sure that when creating new chat, group chat option is not shown, so it's impossible to create new group chat.

status: ready

### CODE REVIEW

**Review by cammellos — APPROVED** [review]

**Comment by cammellos** [comment]
Is there value do you think in showing them in dev mode? So ideally we can code against it, and fix them incrementally and still be able to easily test it (qa team as well).

**Comment by janherich** [comment]
@cammellos actually yes, I will change the `.env` value to 1, thanks !

**Review by goranjovic — APPROVED** [review]

**Review by dmitryn — APPROVED** [review]

**Review by yenda — APPROVED** [review]

**Comment by antdanchenko** [comment]
Group chats will be disabled in nightly builds and in PRs which are rebased on `/develop`, after merging the PR.

Please, disable group chats only for release builds.

**Comment by janherich** [comment]
@annadanchenko Done, group chats are now disabled only for release builds, enabled everywhere else.

**Pull request merged**
