### PR TITLE
Allow to fetch more history in public chats (up to 30 days)

### PR DESCRIPTION
**Pull request by rasom**
Please review only the last commit, merge after #8025

status: ready

### CODE REVIEW

**Review by hesterbruikman — APPROVED** [review]
- I feel like I have my memory back being able to go into history! Great work! 
- I'll create that issue to polish and animate new messages being loaded. 
- I believe we decided to keep 'Fetch more messages' rather than load to maintain consistency. But I prefer load as it's more conventional. I'll check other places we need to update to Load for consistency.

**Review by goranjovic — APPROVED** [review]

**Comment by rasom** [comment]
@hesterbruikman it is still "Fetch more messages" for gaps which appear between history requests. I just wanted to emphasize that this one is rather about **loading/fetching of older messages** than about **fetching of missed messages**. It looks and works similarly but that's two different cases imo. Let me know if it should be changed.

**Comment by hesterbruikman** [comment]
Thanks @rasom. Let's stick with "Fetch more messages" for both, for now. It is the most accurate capture of what happens.  The more I think about it 'Load' might set the wrong expectations.

In time, a more suitable solution for *older messages* would be to fetch on scroll, which I realize comes with it's own challenges. It would however require less effort from the user to mentally process as it's a response to existing behavior  rather than demand for something extra ('tap this button'). Cc @errorist

**Comment by rasom** [comment]
> a more suitable solution for older messages would be to fetch on scroll,

I would add fetching by scroll separately and we will still need to have current ui, for the case when fetching history is disabled by default on mobile connection. Because this fetching comes with some traffic cost

**Comment by yenda** [comment]
This features relies on mailservers being able to store 30 days of all whisper traffic doesn't it? How much is it right now? How does it grows with increased user base?

**Comment by cammellos** [comment]
@yenda it's 30 days currently I believe, I don't know how much it grows with current user base as I don't know how large it is, but at the moment 30 days worth of data are around 2.2/2.5 GB

**Comment by jakubgs** [comment]
Correct, around `2.6 GB`:
```
 $ ansible mail -o -a 'du -hs /docker/statusd-mail/data/wnode'
mail-03.do-ams3.eth.beta | CHANGED | rc=0 | (stdout) 2.6G	/docker/statusd-mail/data/wnode
mail-02.do-ams3.eth.beta | CHANGED | rc=0 | (stdout) 2.4G	/docker/statusd-mail/data/wnode
mail-01.do-ams3.eth.beta | CHANGED | rc=0 | (stdout) 2.6G	/docker/statusd-mail/data/wnode
mail-02.gc-us-central1-a.eth.beta | CHANGED | rc=0 | (stdout) 2.6G	/docker/statusd-mail/data/wnode
mail-03.ac-cn-hongkong-c.eth.beta | CHANGED | rc=0 | (stdout) 2.6G	/docker/statusd-mail/data/wnode
mail-02.ac-cn-hongkong-c.eth.beta | CHANGED | rc=0 | (stdout) 2.3G	/docker/statusd-mail/data/wnode
mail-01.gc-us-central1-a.eth.beta | CHANGED | rc=0 | (stdout) 2.6G	/docker/statusd-mail/data/wnode
mail-01.ac-cn-hongkong-c.eth.beta | CHANGED | rc=0 | (stdout) 2.4G	/docker/statusd-mail/data/wnode
mail-03.gc-us-central1-a.eth.beta | CHANGED | rc=0 | (stdout) 2.6G	/docker/statusd-mail/data/wnode
```
And it is indeed 30 days:
https://github.com/status-im/infra-eth-cluster/blob/c6a847fefa7267a731ac1e0eee638fdad2c6be00/ansible/roles/statusd-mailsrv/defaults/main.yml#L57

But considering the amount of space left we could easily double it. Though of course the more users we get the bigger it will grow over time.

**Comment by churik** [comment]
@rasom thanks for additional  "Fetch 48-60h", "Fetch 84-96h", you can remove it now.

1) Just FYI: https://github.com/status-im/status-react/issues/6946 and https://github.com/status-im/status-react/issues/6419 are very visible in this PR - because if you have a message out of order after fetching the previous 24h you will be redirected to last message according to chat order.
I would prefer to see then fixed if it is possible along with this PR or at least put high-priority after this PR.
What do you think?
Video (example with wrong timestamps): https://take.ms/zggUk

2) On month history also more visible problems with scrolling, i.e. :
- 2.1 blinking of the message that starts history when scrolling up
ezgif com-crop

- 2.2 that messages are not rendering quickly enough when scrolling fast
ezgif com-video-to-gif (1)

- 2.3 that there is no way to be scrolled fast to the last message from the middle of the chat.

I know, that it is not about this particular PR right now, just want to emphasize that these problems will be more visible if we decide to merge this PR now.

Tested on IOS and Android:
- history can be fetched during the last month, day by day on `ams3-do` and `mail-03-hongkong` mailservers. Didn't notice any spikes.
- history matches history on desktop (checked for several days)
- "Fetch messages" (gaps in history) and feature from PR are working fine together
- can't  fetch messages when offline
- messages fetching normally while offline->online during fetching
- the feature is available only for public chats.
- the desktop build is not affected (checked Mac OSx)

@rachelhamlin @annadanchenko let me know if you think we should include this PR in 0.12.0.
IMO we can (but taking into account issues 1 and 2)

**Comment by rasom** [comment]
> I know, that it is not about this particular PR right now, just want to emphasize that these problems will be more visible if we decide to merge this PR now.

both problems are out of the scope of this PR. That behavior on video doesn't seem to be a problem imo. Regarding slow scroll - it's a problem for anyone who used app regularly for more than month. I would say that ability to fetch history gives more advantages than slow scrolling disadvantages (assuming that's only a revealing of an existing issue).

**Comment by mandrigin** [comment]
> I would say that ability to fetch history gives more advantages than slow scrolling disadvantages 

I agree with that too

**Comment by rachelhamlin** [comment]
I don't think the time stamp issues (#6946, #6419) or slow scroll should block this PR—user has to manually change or have custom time on their device? Sounds far out. But whether to include this PR in the current release is test team's decision. Very nice to have, imo, not a need. Nice work @rasom.

**Pull request merged**
