### PR TITLE
[#4292] Use separate jobs to upload files to iTC and Google Play.

### LINKED ISSUE #4292: Separate iOS and Android releases
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a developer, I want to release iOS and Android separately so that I can independently manage release timing and app store approvals.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Currently iOS and Android release builds are uploaded at the same time to iTunes Connect and the Play store using Fastlane. This is problematic because the Android build is realeased automatically, but the iOS build takes ~24 hours to be approved, and so it becomes impossible to schedule synchronized releases.

#### Expected behavior
Separate jobs to upload iOS and Android independently

#### Actual behavior
Builds are uploaded at the same time

### Solution

One job for Android, and another for iOS.

### PR DESCRIPTION
**Pull request by mandrigin**
fixes #4292 

@chadyj you'll like that ;)

status: ready

### CODE REVIEW

**Review by janherich — APPROVED** [review]

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/hX4bCy for branch PR-4441

<blockquote><div><strong><a href="https://i.diawi.com/hX4bCy">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/gB2x9Y for branch PR-4441

<blockquote><div><strong><a href="https://i.diawi.com/gB2x9Y">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Review by rasom — APPROVED** [review]

**Review by jakubgs — APPROVED** [review]
This is great, but please make sure to merge from develop since I've merged my changes that use `VERSION` file from: https://github.com/status-im/status-react/pull/4420

**Comment by jeluard** [comment]
@mandrigin Can you rebase and merge?

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/HjZX9W for branch PR-4441

<blockquote><div><strong><a href="https://i.diawi.com/HjZX9W">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/Bf4pYa for branch PR-4441

<blockquote><div><strong><a href="https://i.diawi.com/Bf4pYa">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Pull request merged**
