### PR TITLE
WIP: use candidate node to build this PR [DO NOT MERGE]

### PR DESCRIPTION
**Pull request by mandrigin**

### CODE REVIEW

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/5sgi2L for branch PR-4357

<blockquote><div><strong><a href="https://i.diawi.com/5sgi2L">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/nSKKdy for branch PR-4357

<blockquote><div><strong><a href="https://i.diawi.com/nSKKdy">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/i2w9kb for branch PR-4357

<blockquote><div><strong><a href="https://i.diawi.com/i2w9kb">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/tUgehe for branch PR-4357

<blockquote><div><strong><a href="https://i.diawi.com/tUgehe">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/SVQxQ5 for branch PR-4357

<blockquote><div><strong><a href="https://i.diawi.com/SVQxQ5">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/HcsCjF for branch PR-4357

<blockquote><div><strong><a href="https://i.diawi.com/HcsCjF">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/fGX8yt for branch PR-4357

<blockquote><div><strong><a href="https://i.diawi.com/fGX8yt">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by mandrigin** [comment]
not neeeded anymore

**Pull request closed without merging**
