### PR TITLE
remove old bottom sheet

### PR DESCRIPTION
**Pull request by flexsurfer**
1) The code for the old bottom sheet has been removed because it's not used in the app
2) Because it's not used in the app, nothing to test, just looked that app still works

### CODE REVIEW

**Review by Parveshdhull — APPROVED** [review]

**Review by ibrkhalil — APPROVED** [review]

**Review by clauxx — APPROVED** [review]

**Comment by flexsurfer** [comment]
@status-im/mobile-qa could someone please check e2e if they not related to PR and it's ok to merge, thank you

**Comment by mariia-skrypnyk** [comment]
Hi @flexsurfer ! 🙌

I am moving back your PR to the corresponding column as it doesn't meet the requirements outlined here:
https://github.com/status-im/status-mobile/blob/develop/doc/pipeline_process.md

Please, make sure your fix should't be tested by QA's and if so - add necessary information to PR's description.
Thanks!

**Comment by flexsurfer** [comment]
thanks @mariia-skrypnyk moved to testing column because don't want to trigger e2e

**Comment by mariia-skrypnyk** [comment]
Thanks for description!

Should it be done by QA team?

> just looked that app still works

If so than please change the label.

**Comment by flexsurfer** [comment]
> Should it be done by QA team?

no, please just check e2e, and we'll merge it if they are not related

**Comment by mariia-skrypnyk** [comment]
Failed e2e are known and not related.
Please, go ahead and merge.

Thanks.

**Pull request merged**
