### PR TITLE
Bug/checkmark in chat item ui refresh #912

### LINKED ISSUE #912: Checkmark in chat item [ui-refresh]
### Description
[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Checkmark in chat item breaks styles.

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Log in
- See chat list

### PR DESCRIPTION
**Pull request by flexsurfer**
[comment]: # (Please replace ... with your information. Remove < and >)
[comment]: # (To auto-close issue on merge, please insert the related issue number after # i.e fixes #566)
fixes #912

### Summary:
[comment]: # (Summarise the problem and how the pull request solves it)
...

### Steps to test:
- Open Status
- Send chat message
- Open chats list

[comment]: # (PRs will only be accepted if squashed into single commit.)
status: ready

### CODE REVIEW

**Comment by jarradh** [comment]
Looks fine on Android & iOS

**Comment by jarradh** [comment]
Okay there is something visually strange

If there is no checkmark then a longer name  is truncated with `...`
If there is a checkmark then a longer name is truncated but there is no `...`

**Comment by flexsurfer** [comment]
can't reproduce but I've made a change which should fix

**Comment by flexsurfer** [comment]
can't reproduce, but i've reworked chat list inner styles, it should work fine

**Pull request merged**
