### PR TITLE
Feature/remove old screens and code

### PR DESCRIPTION
**Pull request by flexsurfer**
remove old screens and code

Affected screens: old settings,ens
Because there are no changes in the functionality, I didn't test anything, just looked that app still working and screens open

### CODE REVIEW

**Review by Parveshdhull — APPROVED** [review]

**Comment by VolodLytvynenko** [comment]
Hi @flexsurfer thank you for PR. Take a look at one problem issue.

## PR_ISSUE 1: [Android] Android legacy screen overlapping Status Bar

### Description:
The screens of some legacy screens are shifted up, causing the status bar to overlap. This makes it impossible to close such screens using the [x] close button.

### Steps:
1. Open the following pages:
- Notification settings
- Appearance
- Legacy settings

### Actual result:
image
image

### Expected result:
The status bar should not be overlapped

### OS: 
Android

### Devices:
- Pixel 7a, Android 13

**Comment by flexsurfer** [comment]
thanks @VolodLytvynenko fixed

**Comment by VolodLytvynenko** [comment]
Hi @flexsurfer, thanks for the PR. No issues from my side, but let's hold off on merging it for now. We need to update the e2e tests to match the changes in this PR to avoid any failures in the develop branch.

@yevh-berdnyk, what do you think? Should we merge this PR now and address the failing e2e tests later with additional fixes, or should the PR wait to add the e2e commits in the scope of this PR?

**Comment by cammellos** [comment]
@flexsurfer as discussed, could you please refrain for the time being from large refactoring? it's best to keep the changes contained to avoid regressions and minimize the impact on the QA team, splitting it off in small scale refactors is also an option to minimize the impact on the codebase and avoid potential bugs

**Comment by flexsurfer** [comment]
@cammellos it's not a refactoring, it's more UI fit and finish task, I removed outdated not worked screens from settings, It could be merged without QA, but it seems like there are outdated e2e which should be removed as well

**Comment by cammellos** [comment]
@flexsurfer ah thank you for explaining, apologies I didn't notice at first, maybe is worth to split it off in smaller chunks? it's much easier to understand exactly what's changed and how the codebase is impacted, and it's a lower testing surface for qa and easier review for devs

**Comment by yevh-berdnyk** [comment]
> Hi @flexsurfer, thanks for the PR. No issues from my side, but let's hold off on merging it for now. We need to update the e2e tests to match the changes in this PR to avoid any failures in the develop branch.
> 
> @yevh-berdnyk, what do you think? Should we merge this PR now and address the failing e2e tests later with additional fixes, or should the PR wait to add the e2e commits in the scope of this PR?

hi, I've just pushed an update for e2e

**Comment by VolodLytvynenko** [comment]
Hi @flexsurfer e2e are fixed. PR is ready to be merged

**Pull request merged**
