### PR TITLE
Improve notifications life-cycle

### LINKED ISSUE #13245: PNs are not auto cleared after messages are read. (IOS and Android with turned on local notifications)
# Bug Report

PNs are not automatically cleared after opening chat (1-1/group/ public) and reading unread messages. Bug is reproducible for IOS and Android with remote notifications on. For local notifications on Android everything works correct. 

### Reproduction 

1. Open Status on Device 1 (message receiver) and Device 2 (message sender)
2. Enable notifications on Device 1
3. In case if Device 1 is Android: turn on Remote notifications (Profile => Notifications => Remote notifications toggle ON) 
4. Device 1 starts chat with Device 2
5. Close Device 1 
6. Send message form Device 1 to Device 2 in order to generate PN on Device 1
7. Open chat containing new message on Device 1
8. Pay attention if PN disappeared after reading message on Device 1
 

#### Actual behavior
PN remains uncleared

#### Expected behavior
PN is cleared 

### Additional Information

- Status version: nightly 
- Operating System: Android(with remote notifs ON), iOS

[comment]: # (Please, add logs/notes if necessary)

https://user-images.githubusercontent.com/97245802/161277859-a257e2f4-a828-4e95-9aa6-7b8eec9b06a9.mp4

[geth.log](https://github.com/status-im/status-react/files/8398304/geth.log)

### PR DESCRIPTION
**Pull request by Parveshdhull**
fixes https://github.com/status-im/status-react/issues/13245

### PR Scope https://github.com/status-im/status-react/issues/13245#issuecomment-1086989435

> - [x] Clear all remote notifications on opening any chat
> - [x] Clear user local notifications(for one-to-one chat) when a user is blocked
> - [x] Clear user local notifications(for one-to-one chat) when a user's chat is deleted
> - [x] Clear community chat notifications when leaving the community or Mark read 
> - [x] Remove notifications from the activity center when leaving the community or Mark read 
> - [x] Clear group chat notifications when leaving the group or Mark read 
> - [x] Remove notifications from the activity center when leaving the group or Mark read 

### status-go PR
https://github.com/status-im/status-go/pull/2623

status: ready

### CODE REVIEW

**Review by rasom — APPROVED** [review]

**Review by flexsurfer — APPROVED** [review]

**Comment by qoqobolo** [comment]
Great improvements @Parveshdhull, thank you!
But let’s make sure some of them work as expected. Please, correct me if I've misunderstood those features. 

### ISSUE 1: Local PNs are not cleared when a user's chat is deleted on Android

> Clear user local notifications when a user's chat is deleted

**Steps:**
1. Enable local notifications on an Android device (UserA)
2. UserA: add UserB to contacts
3. Start a 1-1 chat between UserA and UserB
4. UserA: send the app to the background
5. UserB: send a message 
6. UserA: open the app > long tap on the 1-1 chat > Delete chat > Check notifications

**Expected result:** the notification is deleted
**Actual result:** the notification is not cleared

https://user-images.githubusercontent.com/67952253/161564851-3ce077ad-383e-41e6-b2a2-f050ef5d251e.mp4

### ISSUE 2: Only 1-1 chat PNs are cleared when a user is blocked

> Clear user local notifications when a user is blocked

Currently, PNs on messages in group chats and mentions in public chats are not cleared after blocking the user who sent these messages. Is this expected?
Not sure, what you mean by **_user_** local notifications. 


https://user-images.githubusercontent.com/67952253/161576676-fe214ec8-4905-44d9-a76b-6d1f4b83c8b4.mp4



### ISSUE 3: Notifications in the activity center are not cleared when the user leaves the group
Currently, only **push** notifications themselves are cleared when the user leaves the group.
Should notifications in the activity center be cleared as well?

**Comment by Parveshdhull** [comment]
hi @qoqobolo,
Thank you very much for testing PR.
Yes, Issue 2 is expected, as the user is not leaving groups when blocked we should also keep groups PNs. (Sorry about the confusing issue statement)
Also, Thanks for finding Issue 1 and Issue 3, I will fix them 👍

**Comment by Parveshdhull** [comment]
ok, we are keeping group chats but removing user's messages in those chats on blocking users 🤔. I think the PN's should also be removed. will fix Issue 2 also. Thanks for finding it.

**UPDATE**: Have to check more if issue 2 can be fixed, but as group notifications are delivered by groups chat key as notification id, I think it will not be possible to selectively dismiss notifications which has content from user.

**Comment by qoqobolo** [comment]
@Parveshdhull awesome work, thank you!
PR is ready to be merged.

**Pull request merged**
