### PR TITLE
fix_: message history loading took too much time

### LINKED ISSUE #21358: Chats and message history loading after login takes too much time (30-40 seconds)
**Precondition:** 

In my case user is a member of 4 communities (including Status community) and has two 1-1 chats

**Steps:** 

1. Close the app
2. Generate some unread messages in 1-1 chats and communities. In my case there were 20 unread 1-1 messages and 5 unread mentions in community. 
3. Login the app
4. See how much time is needed to fetch chats and messages

**Actual result:** in my case it takes 30-40 seconds for complete fetching of chats and chat history. I suspect the culprit of such delay is Status community which has a lot of channels and messages. 

As has been reported by @86doteth [here](https://github.com/status-im/status-mobile/issues/21120#issuecomment-2371885924) it can take even more time for messages to be fetched (more than 4 minutes). 

[Status-debug-logs - 2024-10-01T163043.807.zip](https://github.com/user-attachments/files/17210529/Status-debug-logs.-.2024-10-01T163043.807.zip)

https://github.com/user-attachments/assets/f9b09685-f84e-4df3-9eb0-146745326960

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

### PR DESCRIPTION
**Pull request by qfrank**
For details pls see description in related status-go [PR](https://github.com/status-im/status-go/pull/5932)

fixes #21358

### CODE REVIEW

**Review by seanstrom — APPROVED** [review]

**Comment by mariia-skrypnyk** [comment]
Hey @qfrank !

Thanks for your PR.
Loading time is reduced to max 20 sec till all messages appear for receiver.

I have 2 questions to discuss. The second one can be a separate issue I guess.

1. Is it expected that the Receiver sees messages loading chaotically? For example, the last messages may load first, then the first ones, and then the ones in between? I have tested this multiple times, and it is not a one-time occurrence when there are more than 10 messages.
2. When I tested PR on one device (Receiver) and used another device with nightly build (Sender) I observed that several messages got lost for a Receiver. They didn't come even after 30 min. I assume this is not a scope of a current PR and can report a separate issue. When I tested PR-PR devices everything was fine with no lost messages.

If both my questions are not in scope of current PR then PR can be merged.

**Comment by qfrank** [comment]
> Hey @qfrank !
> 
> Thanks for your PR. Loading time is reduced to max 20 sec till all messages appear for receiver.
> 
> I have 2 questions to discuss. The second one can be a separate issue I guess.
> 
> 1. Is it expected that the Receiver sees messages loading chaotically? For example, the last messages may load first, then the first ones, and then the ones in between? I have tested this multiple times, and it is not a one-time occurrence when there are more than 10 messages.
> 2. When I tested PR on one device (Receiver) and used another device with nightly build (Sender) I observed that several messages got lost for a Receiver. They didn't come even after 30 min. I assume this is not a scope of a current PR and can report a separate issue. When I tested PR-PR devices everything was fine with no lost messages.
> 
> If both my questions are not in scope of current PR then PR can be merged.

@mariia-skrypnyk  Thank you for testing! 
I also have serveral questions for you :)
- Could you tell me how long it took before this PR?
- How long it take until you see the chat list appear after login?
- Could you share the log so that I can continue optimising it in another PR as 20 seconds still sounds not good but maybe in another PR
<br/>

> Is it expected that the Receiver sees messages loading chaotically? For example, the last messages may load first, then the first ones, and then the ones in between? I have tested this multiple times, and it is not a one-time occurrence when there are more than 10 messages.

From a normal user view, this should definitely be fixed. I doubt if it's relate to this PR, can you reproduce it without this PR?
<br/>
> When I tested PR on one device (Receiver) and used another device with nightly build (Sender) I observed that several messages got lost for a Receiver. They didn't come even after 30 min. I assume this is not a scope of a current PR and can report a separate issue. When I tested PR-PR devices everything was fine with no lost messages.

Let's create a separate issue for this and attach the logs for sender and receiver, both debug level pls 🙏

**Comment by churik** [comment]
Confirmed by @ilmotta that waku has no change in this Pr, so shouldn't make a difference;

Speaking of:
> Is it expected that the Receiver sees messages loading chaotically? 

It was always like this, just eventually it should be in the same order that it was sent (so the sequence in the chat view after all messages are loaded will be the same eventually).

So basically we should check that that performance is better in this PR in terms of communiy /chat loading

**Comment by mariia-skrypnyk** [comment]
Hey @qfrank !

> I also have serveral questions for you :)

Always welcome!)

**1) Could you tell me how long it took before this PR?**
**2) How long it take until you see the chat list appear after login?**

will combine these 2 questions because for me chat appeared after 2 min of waiting and contained all uploaded messages (develop). I've tried several times to trick this process by scaning Sender's QR to get into the chat quicker (wanted to observe in what order messages are loading) but no chance to have chat in the list of chats less then 2 min of waiting

**3) From a normal user view, this should definitely be fixed. I doubt if it's relate to this PR, can you reproduce it without this PR?**

yes, I cought it on develop too

**4) Let's create a separate issue for this and attach the logs for sender and receiver, both debug level pls 🙏**

ok, will do a separate issue

Thanks @churik!

> It was always like this

I assume that it's not a correct behaviour and I will create an issue on this.
Greate if we can fix it.

> performance is better in this PR in terms of communiy /chat loading

definatelly is!

@qfrank you are free to merge it 🙌

**Comment by qfrank** [comment]
> Hey @qfrank !
> 
> > I also have serveral questions for you :)
> 
> Always welcome!)
> 
> **1) Could you tell me how long it took before this PR?** **2) How long it take until you see the chat list appear after login?**
> 
> will combine these 2 questions because for me chat appeared after 2 min of waiting and contained all uploaded messages (develop). I've tried several times to trick this process by scaning Sender's QR to get into the chat quicker (wanted to observe in what order messages are loading) but no chance to have chat in the list of chats less then 2 min of waiting
> 
> **3) From a normal user view, this should definitely be fixed. I doubt if it's relate to this PR, can you reproduce it without this PR?**
> 
> yes, I cought it on develop too
> 
> **4) Let's create a separate issue for this and attach the logs for sender and receiver, both debug level pls 🙏**
> 
> ok, will do a separate issue
> 
> Thanks @churik!
> 
> > It was always like this
> 
> I assume that it's not a correct behaviour and I will create an issue on this. Greate if we can fix it.
> 
> > performance is better in this PR in terms of communiy /chat loading
> 
> definatelly is!
> 
> @qfrank you are free to merge it 🙌

what about the logs ... @mariia-skrypnyk

**Comment by mariia-skrypnyk** [comment]
Hi @qfrank !

Thanks for merge 🙌.
I've created separate issue for investigation of the ability to more optimize perfomance of messages reload.
You can find it here https://github.com/status-im/status-mobile/issues/21456.

**Comment by qfrank** [comment]
Thanks for creating the followup issue, but the attached log didn't contain `requests.log` since it's not PR build , could you try this PR again and attach the new logs? @mariia-skrypnyk

**Comment by mariia-skrypnyk** [comment]
Thanks for catching it @qfrank .

I've changed logs there.
BTW loading this time took 7 sec but it was the first time it took so fast.
Another my testing attempts took aprox 18-20 sec.
Let me know if anything else is needed.
Also I suppose I need to change my logs here https://github.com/status-im/status-mobile/issues/21460 ?
Or develop logs appropriate in this case?

**Comment by qfrank** [comment]
> Also I suppose I need to change my logs here https://github.com/status-im/status-mobile/issues/21460 ?

No need for 21460 ❤️

**Comment by pavloburykh** [comment]
Hey @mariia-skrypnyk @qfrank 

I have also checked performance from my side. Below is comparison between PR and nightly Android builds. 

PR - took 8 seconds to load chats and unread messages
Nightly - took 17 seconds to load chats and unread messages

So it seems like we really see improvement in PR. But at the same time we still have space for additional improvements. @qfrank what do you think, does it makes sense to keep https://github.com/status-im/status-mobile/issues/21358 open (or we can open a new similar issue with updated statistics)? 

cc @churik 

On the video below PR screen is at the right and nightly is at the left part. 


https://github.com/user-attachments/assets/f667e027-4ea9-4407-a413-fea5e54949f5

**Comment by qfrank** [comment]
> does it makes sense to keep https://github.com/status-im/status-mobile/issues/21358 open (or we can open a new similar issue with updated statistics)?

There is [a](https://github.com/status-im/status-mobile/issues/21456) followup issue, I'll continue to improve it @pavloburykh

**Pull request merged**
