### PR TITLE
Improve message notifications

### LINKED ISSUE #3352: Play a sound for new messages
### User Story

As a user, I want to be notified with a sound/vibration so that I know there is a new private message.

As a user, I want to edit sound preferences on the profile/settings screen, so that I can turn on/off sounds.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Sounds and haptic notifications are a standard way to alert users when there is a new message, and is quite common for IM clients.  This issue will add a sound for new messages, along with settings to enable/disable.

* Add setting for sounds/vibration/notification (designs below)
* Play sound for new private messages ([Download MP3 sound](https://github.com/status-im/status-react/files/1767705/Notification.In.App.wav.zip))

### LINKED ISSUE #4327: Migrate from `react-native-fcm` to `react-native-firebase`
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a developer, I want to upgrade from `react-native-fcm` to `react-native-firebase` so that I have access to the latest APIs and bugfixes.

The `react-native-fcm` package is no longer guaranteed to have any active development, while `react-native-firebase` has great backing:

image

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Solution
[comment]: # (Please summarise the solution and provide a task list on what needs to be fixed.)
*Summary*: Follow steps in https://github.com/evollu/react-native-fcm#to-existing-react-native-fcm-users to upgrade current setup to `react-native-firebase`

### PR DESCRIPTION
**Pull request by dmitryn**
fixes #3352
fixes #4327

### Summary:

* Migrate to react-native-firebase
* Set custom sound
* Tap on notification opens chat 
* Show message notifications when app in foreground, but user is not in current chat (temporary disabled under configuration flag, needs more design/UX thinking and work to be done)

### Testing notes (optional):

I haven't tested it on iPhone. Please help me with that.

In order for custom sound and tap to open chat work, both devices should have this app version installed.

status: ready

### CODE REVIEW

**Review by jeluard — APPROVED** [review]

**Review by janherich — APPROVED** [review]

**Review by cammellos — APPROVED** [review]

**Comment by lukaszfryc** [comment]
@dmitryn I found couple of issues

1. When user logged out and received a notification, clicking on it opens "unknown" chat screen.

 
Instead, the app should open on login screen for corresponding account. After login, the correct chat should screen should open automatically.

2. When user has multiple accounts and is logged in to one of them and then receives notification for a different account, the first chat from the current account is opened BUT it's a wrong chat. 

Instead, user should be either logged out and end up on login screen for the correct account. OR - clicking notification should only open the current state of the app (this is how it works now).

3. I think we use the wrong notification sound (bell.mp3). It's really long. I see Chad posted another sound which is much better in [this comment](https://github.com/status-im/status-react/issues/3352#issuecomment-369277812).

Also, I see this PR does not include in-app [notification settings](https://github.com/status-im/status-react/issues/3352#issuecomment-369308191). I agree we can do it separately. I'll create another GHI for it.

**Comment by lukaszfryc** [comment]
Hey @dmitryn any update on this issue?

**Comment by dmitryn** [comment]
@lukaszfryc work in progress, will be fixed in early August, i'm on vacation without my work laptop at the moment.

**Review by yenda — APPROVED** [review]

**Comment by dmitryn** [comment]
Hey @lukaszfryc ! I've made changes based on your comments, please check this build:

branch PR-4997:
apk uploaded to https://i.diawi.com/c7mMqq
ipa uploaded to https://i.diawi.com/fsuLiU

>When user logged out and received a notification, clicking on it opens "unknown" chat screen.


>Instead, the app should open on login screen for corresponding account. After login, the correct chat should screen should open automatically.

Fixed.

>When user has multiple accounts and is logged in to one of them and then receives notification for a different account, the first chat from the current account is opened BUT it's a wrong chat.

>Instead, user should be either logged out and end up on login screen for the correct account. OR - clicking notification should only open the current state of the app (this is how it works now).

If user is logged in different account, open app in current state (i.e. don't do anything)
If user is logged out, open login screen for proper account, then open corresponding 1-1 chat after sign in.

>I think we use the wrong notification sound (bell.mp3). It's really long. I see Chad posted another sound which is much better in this comment.

Changed the sound file to the correct one.



<blockquote><div><strong><a href="https://i.diawi.com/c7mMqq">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>
<blockquote><div><strong><a href="https://i.diawi.com/fsuLiU">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by lukaszfryc** [comment]
@dmitryn I tested all the cases you mentioned and used my original testing notes to cover other cases. The only thing I found is `JSON Parse error: Unexpected identifier “message”` when receiving message from older build (my 2nd device was on 0.9.25) and that there were no notification sound. 

Steps to reproduce:
- Install 0.9.24 on first device (iOS in my case)
- Install this PR build on 2nd device (Android in my case)
- Open 2nd device and scan QR code of the 0.9.24 user. Then put the app into background
- From 0.9.24, sent a message 
- Open 2nd device from notification. **The error pops up and there is no notification sound.** When it's closed, everything works fine, the message can be seen and new messages are recevied properly but still no sound.

TF session: https://app.testfairy.com/projects/4803622-status/builds/8550849/sessions/4398181491/?accessToken=5LCDaYCwC1lEe6W/9/PeXFvY1GM


<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803622-status/builds/8550849/sessions/4398181491/?accessToken=5LCDaYCwC1lEe6W/9/PeXFvY1GM">TestFairy: Status 0.9.26 (6337) @2018</a></strong></div></blockquote>

**Comment by dmitryn** [comment]
@lukaszfryc i've fixed case with old client <=> new client message sending. Please check


apk uploaded to https://i.diawi.com/UHXrEc
ipa uploaded to https://i.diawi.com/5uEfiR

<blockquote><div><strong><a href="https://i.diawi.com/UHXrEc">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>
<blockquote><div><strong><a href="https://i.diawi.com/5uEfiR">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by lukaszfryc** [comment]
@dmitryn I tested the builds and I the error is gone. But, I noticed few strange issues:

1. On Android, there is no sound or preview of a notification. I have all options enabled in system settings and if I receive a message from another device (iPhone which has this build installed), the notification appears in the Android Notification Center (Status icon is visible in top left corner) but there is no sound or preview of the notification. **The same scenario works fine on iOS.**. [TF session from Android](https://app.testfairy.com/projects/4803622-status/builds/8553850/sessions/4398283049/?accessToken=U9CxBSUOUgEHPEXsg-HaCbFcYmo)

2. When the app with this build is killed, there is no notification when it receives a message from 0.9.25  build.

3. When the app with this build is in background, there is no sound when it receives a message from 0.9.25.

4. This one is really strange - 0.9.24 (and probably other versions as well) have notifications with sound for messages received from this PR build. The sound is default system sound.

What I suggest is to focus on 1) and skip the rest as those are scenarios that involve older versions of the app. @dmitryn let me know if I can help you in any way.

**Comment by dmitryn** [comment]
@lukaszfryc regarding point 1)
It works well (both sound and preview) on Android 8.1 (oneplus 5 and lg nexus 5).
On nvidia shield tablet with Android 7 i have sound and notification tray icon, but no preview.

What Android versions do you test on? Also, i don't have iphone to test, but i assume everything is fine there.

**Comment by lukaszfryc** [comment]
@dmitryn I'm testing on Galaxy S8, Android 7.1. But, let me try an emulator as well.

Yes, iOS looks fine.

**Comment by lukaszfryc** [comment]
@dmitryn my mistake, it looks like my sound of my notifications was muted when I tested it. Feel free to merge :)

**Comment by maxhora** [comment]
Jenkins Desktop job seems failed for this PR:
```
PR-4997(feature/push-notifications-sound-#3352) [color:bad] https://ci.status.im/job/status-react/job/desktop/job/pull-requests/job/PR-4997/2/
```
Not sure why it didn't block it from merging, but Desktop can't be built now.

**Pull request merged**
