### PR TITLE
local pair: check netIPs if empty before find server cert

### PR DESCRIPTION
**Pull request by qfrank**
fix relate [issue](https://github.com/status-im/status-mobile/issues/17634#issuecomment-1806768628)
with this PR we should see the error as screenshot shows when doing local pair and client/server are in different network.
image

status: ready

### CODE REVIEW

**Review by siddarthkay — APPROVED** [review]
LGTM

**Review by BalogunofAfrica — APPROVED** [review]

**Comment by pavloburykh** [comment]
Hi @qfrank! Unfortunately go develop is currently broken. Until it is fixed we are unable to test PRs containing go changes. 
I have logged issues in another PR containing go changes https://github.com/status-im/status-mobile/pull/17834#issuecomment-1809042890

**Comment by qfrank** [comment]
> Hi @qfrank! Unfortunately go develop is currently broken. Until it is fixed we are unable to test PRs containing go changes. I have logged issues in another PR containing go changes [#17834 (comment)](https://github.com/status-im/status-mobile/pull/17834#issuecomment-1809042890)

updated @pavloburykh

**Comment by pavloburykh** [comment]
Hey @qfrank!  Could you please rebase go branch to include the revert?  Also, please rebase mobile branch as it is outdated compared to release branch. Thank you!

**Comment by qfrank** [comment]
> Hey @qfrank! Could you please rebase go branch to include the revert? Also, please rebase mobile branch as it is outdated compared to release branch. Thank you!

Hi @pavloburykh , i think it's already the latest as i did rebase this morning (6 hours ago), no? 🙂

**Comment by pavloburykh** [comment]
> Hi @pavloburykh , i think it's already the latest as i did rebase this morning (6 hours ago), no? 🙂

You are right @qfrank! Sorry for confusion.

**Comment by pavloburykh** [comment]
@qfrank Thank you for the fix! Ready for merge.

**Comment by qfrank** [comment]
close now as cherry picked

**Pull request closed without merging**
