### PR TITLE
Fix currency and sticker synchronisation

### LINKED ISSUE #12889: Sychronize sticker packs across devices
As a user
I want to have my sticker packs synchronized across devices
So I don't have to install them on each device.

### Description

When a user installs a sticker pack, it should also appear on any paired device that they own.
Similarly, if a sticker pack is removed, the same should happen on the paired device.

This settings should also be backed up, similarly as we do for contacts.

### LINKED ISSUE #13190: Synchronise `currency` setting
Implement functionality that handles the syncing of the `currency` setting.

### Background

In `status-go` syncing of settings has been implemented, and additional setting sync *should be* a relatively straightforward process. The syncing of the `currency` setting has been implemented from the `status-go` side.

See https://github.com/status-im/status-go/pull/2478 and https://github.com/status-im/status-react/pull/13053

However there is additional functionality that needs to be implemented on the `status-react` side to make currency work correctly.

See the QA report here [ISSUE 6: Error on the synced device when changing currency](https://github.com/status-im/status-react/pull/13053#issuecomment-1065179963)

### `status-go` Implementation

Currently the `currency` setting has its sync functionality disabled:

```go
Currency = SettingField{
	reactFieldName: "currency",
	dBColumnName:   "currency",
	// TODO resolve issue 6 https://github.com/status-im/status-react/pull/13053#issuecomment-1065179963
	syncProtobufFactory: &SyncProtobufFactory{
		inactive:          true, // Remove after issue is resolved
		fromInterface:     currencyProtobufFactory,
		fromStruct:        currencyProtobufFactoryStruct,
		valueFromProtobuf: StringFromSyncProtobuf,
		protobufType:      protobuf.SyncSetting_CURRENCY,
	},
}
```

To reactivate the `currency` functionality in `status-go` simply remove the `inactive` field from the `SyncProtobufFactory`

### PR DESCRIPTION
**Pull request by audriu**
Closes #12889
Closes #13190

### Summary
Enable currency settings and installed sticker pack synchronization between devices on the same account. 

### Testing notes
there are some steps to reproduce currency synchronization 
https://github.com/status-im/status-react/pull/13053#issuecomment-1065179963

#### Platforms
- Android
- iOS

##### Functional
- wallet / transactions
- account recovery

### Steps to test
there are some steps to reproduce currency synchronization 
https://github.com/status-im/status-react/pull/13053#issuecomment-1065179963

- Open Status
- Change currency selection on another device but on the same account
- Purchase sticker package on another device but on the same account
- check if it changed on another account in this account.

status: READY

### CODE REVIEW

**Comment by Parveshdhull** [comment]
hi @audriu, Please rebase your PR and push changes again

**Comment by audriu** [comment]
> hi @audriu, Please rebase your PR and push changes again

This PR only works against this commit of status-go. Status-go will have to be updated after testing this.

**Review by Samyoul — APPROVED** [review]
Looks good to me

**Comment by qoqobolo** [comment]
Hey @audriu, builds for this PR were not built, could you please take a look, rebase it against the latest develop, and ping someone from the QA team when it's ready to be tested (or just move it to the `E2E tests` column in pipeline).
Thanks

**Comment by pavloburykh** [comment]
Hi @audriu ! Could you please rebase the branch to develop. I guess there are some changes in develop, that I don't see in current PR. Thanx.

**Comment by pavloburykh** [comment]
@audriu thanx for the PR. Please, take a look at next issues. 

### ISSUE 1  Stickers are not synced throughout devices after syncing

**STR:**
1. Login the same account on Device 1 and Device 2
2. Install any stickerpack on Device 1 (join any chat - tap sticker icon - select and install any stickerpack )
3. Sync devices: on both devices go to Profile - Sync settings - Devices (set names for both devices) - tap Advertise on both  devices - Add checkmarks on both devices in front of name of another device - **on Device 1** tap sync Sync all devices
4. Check if installed stickers appeared on Device 2

**Actual result:** stickerpack is not synced from Device 1 to Device 2
**Expected result:** stickerpack is synced


### ISSUE 2 Stickers are not synced on paired devices

**STR:**
1. Login the same account on Device 1 and Device 2
2. Pair devices: on both devices go to Profile - Sync settings - Devices (set names for both devices) - tap Advertise on both  devices - Add checkmarks on both devices in front of name of another device 
3. Install any stickerpack on Device 1 (join any chat - tap sticker icon - select and install any stickerpack)
4. Check if installed stickers appeared on Device 2

**Actual result:** stickerpack did not appear on paired Device 2
**Expected result:** stickerpack appeared on paired Device 2

### ISSUE 3 Stickerpacks are not backed up

According to @cammellos [description](https://github.com/status-im/status-react/issues/12889#issue-1074145557) "This settings should also be backed up, similarly as we do for contacts." Currently back up does not work.

**STR:**
1. Login the same account on Device 1 and Device 2
2. Install any stickerpack on Device 1 (join any chat - tap sticker icon - select and install any stickerpack )
3. Wait some time for automatic back up or perform it manually **on Device 1:** go to Profile - Sync settings - Backup settings - tap Perform backup
4. Check if installed stickers appeared on Device 2

**Actual result:** stickerpack did not appear on Device 2 after back up
**Expected result:** stickerpack appeared on Device 2 after back up

Attached video demonstrates the process of reproduction of all 3 issues. On the left screen side is Android, on the right is IOS. 

https://user-images.githubusercontent.com/97245802/167587064-8f931520-8873-44ef-9ce9-473ea70caba6.mp4

I've attached logs only from Android device, as sharing logs from IOS is currently broken.
[geth.log](https://github.com/status-im/status-react/files/8659879/geth.log)

**Comment by pavloburykh** [comment]
@audriu Thank you for fixes. ISSUES 1 and 2 are fixed. 

Although still reproducing ISSUE 3.

**Comment by audriu** [comment]
@pavloburykh thanks for testing. Backups will come when I implement this ticket https://github.com/status-im/status-react/issues/13193

**Comment by pavloburykh** [comment]
@audriu thanx. Ready for merge.

**Pull request merged**
