### PR TITLE
feat: unstoppable domains crypto payments integration

### PR DESCRIPTION
**Pull request by amritkumarj**
### Summary

Integrate Unstoppable domains in status to send crypto using NFT domains

#### Platforms

- Android
- iOS

#### Areas that maybe impacted
Domain Service

status: ready

https://user-images.githubusercontent.com/72156537/195350714-2d3f40bc-7bb2-4e1a-baab-dd91e3b18681.mov

### CODE REVIEW

**Comment by flexsurfer** [comment]
hey @amritkumarj , thank you for your PR, could you please elaborate on the changes and why ens namespace has been renamed

**Comment by du82** [comment]
I think this is a really cool option, since the `.eth` namespace is saturated, and it would be great to let users use other names as their @ tag the way we do with ENS usernames currently.

**Comment by flexsurfer** [comment]
@J-Son89 I'm not sure why it's possible to assign non-team members, but better to do not do it, so you can see in the list that if there is no assigned means its an external contributor

**Comment by J-Son89** [comment]
> @J-Son89 I'm not sure why it's possible to assign non-team members, but better to do not do it, so you can see in the list that if there is no assigned means its an external contributor

cool, thanks for letting me know! :)

**Comment by amritkumarj** [comment]
@flexsurfer, thanks for the swift reply

After Integrating this PR user can use Unstoppable Domain to send payments in status mobile app (using unstoppable domain as username is still pending because of some complication but will be added soon)

Changes:-
1) We have replaced ENS namespace to Domain namespace (as it now resolves both uns domain and ens domains)
2) Edited translation files to replace ENS with Domain (at the places where UNS Domain and ENS Domain both are working)
3) Added a new file named UNS in ethereum folder similar to ENS for resolving Unstoppable Domains 
4) Calling a function "initialize-uns-tlds" at login to cache the tlds of Unstoppable Domain


ENS namespace has been renamed to Domain as it now resolves both UNS and ENS Domains

**Comment by amritkumarj** [comment]
Hey, the code is working fine when I build it, also working prefectly on the UI side, but if I run "make test" command it shows this error - 
"TypeError: shadow.js.shim.module$react_native_fetch_polyfill.default is not a function" 

have you encountered this problem before, as I can understand it is because of calling the http/get function, but don't know why

**Comment by amritkumarj** [comment]
Hey @flexsurfer @J-Son89 @du64,  just bumping the last comments

**Comment by J-Son89** [comment]
> Hey @flexsurfer @J-Son89 @du64, just bumping the last comments

I can take a look today and see if I get this error 👍

**Comment by J-Son89** [comment]
> Hey, the code is working fine when I build it, also working prefectly on the UI side, but if I run "make test" command it shows this error - "TypeError: shadow.js.shim.module$react_native_fetch_polyfill.default is not a function"
> 
> have you encountered this problem before, as I can understand it is because of calling the http/get function, but don't know why

I checked out your repo and not seeing this error when I run `make test`, perhaps you just need to clean up some folders?
try deleting `target` folder as there where everything gets compiled to for tests. I think you can run `make clean`, should remove all temporary/git ignored files and folders. Might be worth making sure everything is backed up before running as not 100% on this command but it looks correct.

Anyway, these tests get run in the CI. At the moment the build job for tests are failing but if you rebase and then run `make lint` and address the errors and push your changes the tests will be run in CI.

**Comment by amritkumarj** [comment]
@J-Son89 Thanks for the review, I fixed all the errors in  "make lint"

image

But Still the CI is failing. Can you please give it a check.
Thanks!

**Comment by J-Son89** [comment]
> @J-Son89 Thanks for the review, I fixed all the errors in "make lint"
> 
> image
> 
> But Still the CI is failing. Can you please give it a check. Thanks!

Hey @amritkumarj , I checked the CI and yes lint looks good. It seems the error message is the same: "TypeError: shadow.js.shim.module$react_native_fetch_polyfill.default is not a function".

I will try to reproduce this on my machine today and if so I will look to see what might be causing/fixing this. :)

**Comment by siddarthkay** [comment]
@amritkumarj : Hello! Thank you for all the work you have done for this PR. 
Before you put in any more work towards this I would like to let you know that we are currently reviewing this PR internally and @John-44 @cammellos would get back to you on this.

**Comment by amritkumarj** [comment]
Hey, just checking if there is any update or help required?

**Comment by 3esmit** [comment]
By including unstoppable domains, this means we should start adding other name systems as well? What is the criteria for supporting a domain name? Anyone can claim a new domain system and start selling domains, and then Status should support it?

Here a list of NFT Domain systems: https://sourceforge.net/software/nft-domain/

**Comment by du82** [comment]
@3esmit 
I don't think we should add too many, since the more we add, the more complicated it is for users, and the more possibility for name conflicts there is. I think Unstoppable and ENS is enough :)

**Comment by jim-unstoppable** [comment]
Hey @du64 - interesting comment for sure, allow me to add some more context. Naming collisions for sure is something that is bad for the industry, Unstoppable Domains works very hard to avoid this. UD's TLDs are very carefully selected to avoid any collisions. UD also is the market leader with 2.7M domains registered and over 550 integrations, so it surely does add a lot of value to Status to be in the ecosystem I believe. Status is a super cool app and I think it'd be awesome for uns + ens to coexist here.

UD also loves to work with partners and would love to do a co-marketing announcement to the UD fam upon integration

**Comment by du82** [comment]
> Hey @du64 - interesting comment for sure, allow me to add some more context. Naming collisions for sure is something that is bad for the industry, Unstoppable Domains works very hard to avoid this. UD's TLDs are very carefully selected to avoid any collisions. UD also is the market leader with 2.7M domains registered and over 550 integrations, so it surely does add a lot of value to Status to be in the ecosystem I believe. Status is a super cool app and I think it'd be awesome for uns + ens to coexist here.
> 
> UD also loves to work with partners and would love to do a co-marketing announcement to the UD fam upon integration

Unstoppable is great, it's nice to give users the option to actually **own** their name instead of paying an outrageous fee to rent it. This isn't Web2, we don't need SaaS lol. Seriously, charging a $50,000,000 premium that goes down over the course of a month is REALLY stupid for adoption, and the main reason why I dislike ENS.

I recommend talking to @jinhojang6 for marketing when this PR does get merged.

**Comment by jim-unstoppable** [comment]
> jinhojang6 for marketing when this PR does get merged.

Awesome, sounds like a plan!

**Comment by cammellos** [comment]
@jim-unstoppable thanks for the PR.
I have spoken to security/product and unfortunately it's not something we would like to include at this moment.
We tend to minimize the amount of external apis we make use of, and generally we allow the user to opt-in, which would require further work and discussion, so for the time being we decided to pause and re-evaluate after we are finished with the MVP.
We will keep the PR for reference and thanks a lot for the hard work, it will be very helpful when/if we decide to integrate it.

**Pull request closed without merging**
