### PR TITLE
Fix key uniqueness in message history and chat list

### LINKED ISSUE #4225: Chat list is changing when user sends or types a message
### User Story

As a user, I want to see the constant list of added contacts or public chats so that I can switch between them any time.

### Description
*Type*: Bug
*Summary*: when entering new channel or contact to "Join to public chat" or "Add new contact" fields, then send a message in new chat - existing chat list is changing, and some chats are disappearing.

#### Expected behavior
Sent messages don't affect chat list

#### Actual behavior
existing chats are disappearing when the message is sent
### Reproduction

- Install `status-desktop` 
- Open StatusIm 
- Create new account
- Add one channel
- Add second channel 
- Send a message to the second channel 

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: StatusIm desktop (version 2018-05-07)

* Operating System: MacOS High Sierra 10.13.4, Ubuntu 18.04

#### Logs

Video: http://take.ms/oGw3T

### LINKED ISSUE #4226: Message history is mixed when the user switches between chats
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to see message history that only belonging to selected chat.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug
*Summary*: when entering new channel or contact to "Join to public chat" or "Add new contact" fields, then send a message in new chat - existing chat list is changing, and some chats are disappearing.

#### Expected behavior
history is empty

#### Actual behavior
history from 1 chat is displayed
chat1

### Reproduction

- Install `status-desktop` 
- Open StatusIm 
- Create new account
- Add one chat, send several messages
- Add second chat 
- Switch on the first chat
- Switch to second chat again

### Additional Information
* Status version: StatusIm desktop (version 2018-05-07)
* Operating System: MacOS High Sierra 10.13.4, Ubuntu 18.04

#### Logs

Video: http://take.ms/nMUJ6

### PR DESCRIPTION
**Pull request by vitvly**
Fix #4225, #4226 

Also correct typo in Figwheel output-to file name for desktop build.

### CODE REVIEW

**Review by rcullito — APPROVED** [review]
Looks good!

**Review by yenda — APPROVED** [review]

**Review by maxhora — APPROVED** [review]

**Review by vkjr — APPROVED** [review]

**Comment by maxhora** [comment]
https://github.com/status-im/react-native-desktop/pull/252 should resolve ui glitches with messages history

**Comment by vkjr** [comment]
@siphiuel, should this be merged?

**Comment by vitvly** [comment]
Needs to be tested first.

**Comment by churik** [comment]
## 1. Empty space above text input field

Steps:

1) log in
2) open chat with 10+ message

### Actual result:
monosnap 2018-06-18 15-59-05

### Expected result: 
no space between last message and text input field

**Note:**  is not reproducible on other PRs 
**Build:** [PR-4578, 8](https://jenkins.status.im/job/status-react/job/desktop/job/pull-requests/view/change-requests/job/PR-4578/8/)

**Comment by churik** [comment]
## 2. Last message can be overlapped by text field

Steps:

1) log in
2) join any public chat
3) paste long issue (in my case 497 chars)
4) send it

### Actual result:


### Expected result: 


**Note:**  is not reproducible on other PRs 
**Build:** [PR-4578, 8](https://jenkins.status.im/job/status-react/job/desktop/job/pull-requests/view/change-requests/job/PR-4578/8/)

**Comment by churik** [comment]
## Important note: 

full testing is blocked by #4730

**Comment by vitvly** [comment]
Decreased the bottom padding to chat list to match design (https://zpl.io/bWY4LKx).

Branch has been merged with desktop, so updated chat window does not seem to exhibit the problem #2.

<blockquote><div> Zeplin</div><div><strong><a href="https://zeplin.io/">Zeplin - Login</a></strong></div><div>Collaboration app for UI designers and frontend developers</div></blockquote>

**Comment by churik** [comment]
1 is fixed.
2 is reproduced if you send several long messages in a row (i.e. 3 one-by-one). Is not reproducible on current `Desktop` branch.

But I've experienced one more problem:

## 3. Message history is overlapping when you have several chats with history>1 day (when switching between chats)

Steps:
*Requirements:* have 1-1 and public chat with history more than 1 day

1) log in
2) switch between chats with history>1 day (i.e. "Today" and "Yesterday")
3) check history in 1-1 ha

### Actual result:
"Today" disappears
messages from "Yesterday" are overlapping between chats
m1


### Expected result: 
no overlapping

* Video: http://take.ms/yMabF
* Log: [StatusIm.log](https://github.com/status-im/status-react/files/2145576/StatusIm.log)

**NOTE**: if you switch to chat with "Today" messages only, and then to chat with several days history - you cannot see an issue until you switch to another chat with several days history.

**Comment by vitvly** [comment]
After conversation with @MaxRis it seems that #2 and #3 are related to https://github.com/status-im/react-native-desktop/issues/253.

**Comment by churik** [comment]
Issue with chat history is moved to #4995

**Pull request merged**
