### PR TITLE
fix: revert removal of key in profile settings view

### PR DESCRIPTION
**Pull request by seanstrom**
[comment]: # (Please replace ... with your information. Remove < and >)
[comment]: # (To auto-close issue on merge, please insert the related issue number after # i.e fixes #566)

### Summary

* This PR attempts to fix the displaying of the profile settings screen.
  * This PR adds a `key` prop to a component, which is needed atm.
  * Ideally, we would fix the `quo/overlay` component to use `into` to avoid needing `:key` props for children.
    * Here's a previous discussion about this for context: https://github.com/status-im/status-mobile/pull/18674#discussion_r1473539054

[comment]: # (Summarise the problem and how the pull request solves it)

#### Platforms

- Android
- iOS

##### Functional

- Opening Profile Settings 

### Steps to test

- Open Status mobile
- Login as a user
- Press the profile settings button

#### Before

https://github.com/status-im/status-mobile/assets/2845768/7727960f-218b-4a60-9a5a-dfe274a6f80e

#### After

https://github.com/status-im/status-mobile/assets/2845768/8d9c18df-daa8-4ce7-9127-fa89edcc3fd8

status: ready

### CODE REVIEW

**Comment by Parveshdhull** [comment]
Hi, I am currently afk for an hour, will look into this.

Please hold merging till then

**Comment by seanstrom** [comment]
@Parveshdhull Yup yup will do 👍

**Comment by Parveshdhull** [comment]
Hi, Thank you for adding context in PR description.
Please also create an issue, so that we remove these keys and fix bugs in quo/overlay. 
Otherwise this weird hack of :key is spreading, which doesn't make sense.

**Review by Parveshdhull — APPROVED** [review]

**Comment by seanstrom** [comment]
Okay will do 👍 

Update:
new issues is created here: https://github.com/status-im/status-mobile/issues/19331

**Review by mohsen-ghafouri — APPROVED** [review]

**Comment by seanstrom** [comment]
@status-im/mobile-qa can you review these E2E results please? 🙏

**Comment by pavloburykh** [comment]
> @status-im/mobile-qa can you review these E2E results please? 🙏

Hey @seanstrom! E2E failures are not PR related. Ready for merge.

**Pull request merged**
