### PR TITLE
feature #3243 - contact profile screen cleanup

### LINKED ISSUE #3243: Other contact's profile needs cleanup
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: If open other contact's profile from 1:1 chat (even if it's in my Contacts) that this screen is shown:
img_2588

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
Remove: status, qa view,
Leave: username, image and keys. And buttons: Start chat and Send transaction. And testnet warning

Found on develop build from Feb 6. Both Android and iOS

### PR DESCRIPTION
**Pull request by goranjovic**
fixes #3243

### Summary:

Fixes the contact's profile screen:
- removes status and qa screen
- adds back keys

### Steps to test:
- Start chatting, then open contact profile

status: ready

### CODE REVIEW

**Comment by goranjovic** [comment]
screenshot-2018-02-08_13 31 18 485

**Review by jeluard — APPROVED** [review]

**Comment by goranjovic** [comment]
Also fixes #3268

**Review by alwx — APPROVED** [review]

**Comment by yevh-berdnyk** [comment]
Branch: PR-3266
Android: https://i.diawi.com/ARTWK2
iOS: https://i.diawi.com/UtXNGS

Found issues

On iOS for all contacts it’s not possible to copy or share address and public key
png 1 copy



After recovering access to existing account I see the next issues for profiles of users which I was chatted before.

Some profiles have broken profile layout and functionality: 
- username is not shown
- profile picture differs from one in the chat, it’s nor default neither set by the user
- address and public key are not shown, Copy to Clipboard and Share buttons for them are not available
- nothing happens when pressing Start conversation (staying on the Profile view) and Remove from contacts (users stays in contacts).

Android:


iOS:
png 1



On Android for some recovered contacts I also see last login time

**Comment by goranjovic** [comment]
The ios menu issue was resolved in #3260 - I rebased against develop to include the fix.

The other issue is really a bug in Recover, not introduced in this PR and not within the scope of this change (to clean up the screen). We should have a separate issue for this. I thought we already had, but can't find it.

**Comment by yevh-berdnyk** [comment]
Branch: PR-3266
Android: https://i.diawi.com/aAFNNf
iOS: https://i.diawi.com/ChCKGh

Rechecked - no new issues found.
@goranjovic I've created the issue #3307 for profiles after recovery

**Pull request merged**
