### PR TITLE
[#3818] If a message contains only an emoji, show it without chat bubble

### LINKED ISSUE #3818: If a message contains only an emoji, show it without chat bubble
### User Story

As a user, I want to see a big emoji and don't want to have them in the 'chat bubble jail' so that I will get more fun.

### Description

*Type*: Feature

*Summary*: Currently when you send emoji in a chat it appears in a chat bubble that makes it really small to recognize. We would like to remove this bubble for messages that contain only emojis. 

#### Expected behavior
emoji free

#### Actual behavior
emoji jail01

### Solution

- use fontSize:40, lineHeight: 45 for emoji
- you need to render an emoji without a chat bubble right after it's sent to a chat
- this should work not only for one emoji also for multiple emojis  

### Additional Information

* Operating System: Android|iOS

### PR DESCRIPTION
**Pull request by endenwer**
Fixes #3818

Every message parsed only once when saving to data store. Message length does not matter. If message contains only emoji and spaces then message content type is changed to `emoji`. Regexp should match all the existing emojis cause it use unicode property escape feature(https://mathiasbynens.be/notes/es-unicode-property-escapes#emoji) transpiled to es5 here https://mothereff.in/regexpu.

simulator screen shot - iphone 6 - 2018-04-12 at 10 56 44

<blockquote><div><strong><a href="https://mathiasbynens.be/notes/es-unicode-property-escapes#emoji">Unicode property escapes in JavaScript regular expressions · Mathias Bynens</a></strong></div></blockquote>
<blockquote><div><strong><a href="https://mothereff.in/regexpu">ES6 Unicode regular expression transpiler</a></strong></div><div>An online, on-the-fly transpiler for ES6 Unicode regular expressions.</div></blockquote>

### CODE REVIEW

**Review by janherich — APPROVED** [review]
Very nice, great work !

**Review by yenda — APPROVED** [review]

**Comment by rasom** [comment]
Branch: PR-3843
Android: https://i.diawi.com/usaR2w
iOS: https://i.diawi.com/xrBX45

<blockquote><div><strong><a href="https://i.diawi.com/usaR2w">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>
<blockquote><div><strong><a href="https://i.diawi.com/xrBX45">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by endenwer** [comment]
@rasom Seems like failed tests don't relate to this pr. Can this tests just fail randomly?

**Comment by rasom** [comment]
@endenwer let me check

**Comment by rasom** [comment]
yep it's something on our side, anyway PR was tested already

**Pull request merged**
