### PR TITLE
add swipe to reply feature

### LINKED ISSUE #12361: Swipe-to-reply gesture
As a user
I want to be able to swipe-to-reply
So that I can easily reply to a message

### Description
A user should be able to swipe on a message, and that should populate the reply input.

Swipe-To-Reply

### PR DESCRIPTION
**Pull request by Jonathansoufer**
[comment]: # This PR implements a "swipe to reply" feature on chat messages.

fixes #12361

### Summary

[comment]: # This PR implements swipe gesture replacing onLongPress to allow users reply a message with a better UX. 
...

#### Platforms

- Android
- iOS
- macOS
- Linux
- Windows

##### Functional

- 1-1 chats
- public chats
- group chats

### Steps to test

- Step 1: Swipe a message to right
- Step 2: Reply a message

- Open Status
status: ready

https://user-images.githubusercontent.com/44679989/137039662-0664759b-a7bd-4d03-ad24-72767b5cca61.mp4

### CODE REVIEW

**Comment by ghost** [comment]
Hey @Jonathansoufer, and thank you so much for making your first pull request in status-react! :heart: Please help us make your experience better by filling out this brief questionnaire https://goo.gl/forms/uWqNcVpVz7OIopXg2

**Review by cammellos — COMMENTED** [review]
Hi @Jonathansoufer , thanks for the contribution!

Would you mind storing the magic number in some consts please, so it's easier to understand what they are used for?

Also, I think the linting is failing, you can run `make lint` that should give you a report, and often things can be fixed by running `make lint-fix`

Thank you

**Comment by hesterbruikman** [comment]
Thanks for this PR @Jonathansoufer! I had a try on Android. Feels smooth, good work.

https://user-images.githubusercontent.com/35233054/137480425-630cb1eb-08fe-4415-bb64-d24c014b131a.mp4

Two comments:

1) I did notice a persistant reply icon at the top of chat, looks like a bug. Can you take a look at that?
2) How are you timing the transition to show the reply message at the top of the chat input? I think it could be a few ms slower so it feels less instant/abrupt

**Comment by briansztamfater** [comment]
Hi @Jonathansoufer, thanks for the contribution :)

I tested the latest apk build on an Android Emulator (Pixel 2) and the transition feelt good overall, but there's a "jump" at the start of it that I would suggest to improve.

https://user-images.githubusercontent.com/18485527/137497276-1585b576-6a92-4b07-a385-564aa11bd542.mp4

Also I'd expect to be able to swipe to reply to my own messages which I wasn't able to make it work while testing.

Besides that, and the comments from the rest of the team above, I think it is a good work.

**Comment by Jonathansoufer** [comment]
- Persistent reply icon: Fixed
- "Jump" at the start: Fixed
- Lint Issues: Fixed
- Timing of the transition to show the reply message: This is triggered by the dispatch function and the only option I found was to use dispatch-later instead.  Since this wasn't at core scope of the PR, I left out to treat it separately.
-  Storing the magic number:  Values related to transformation axis are now stored in constants.

**Comment by briansztamfater** [comment]
Thanks @Jonathansoufer, I tried the last available build (commit `af22665`). The "jump" in swipe gesture was indeed fixed, thanks for that, it feels much better now!

I still see the persistant reply icon that @hesterbruikman mentioned above, seems to happen on each message sent by the current logged user, and also I couldn't be able to reply to my own messages (tried swiping to the left but nothing happened). Attaching screenshot below.

**Comment by briansztamfater** [comment]
There are still some linting issues, maybe running `make lint` locally will help you to point you to the actual problem if `make lint-fix` doesn't solve it.

**Comment by shivekkhurana** [comment]
I see the same issue as Brian on Android (rogue reply icon). It seems fine on iOs. Sometimes the gesture is not smooth but that can be attributed to me scrolling the list.

**Comment by Jonathansoufer** [comment]
https://user-images.githubusercontent.com/44679989/138253864-85a44566-ee2d-4b33-9096-cfe1cb1f6fbd.mp4

Unnecessary reply icon removed from responses. When replying to your own messages the icon isn't displayed to give users a sense of reply (to others) and extending their own replies.

**Comment by briansztamfater** [comment]
Now it is much better, I just found that the icon is still being shown but it is hidden behind the message so a tiny portion of it is sometimes visible (check the top-left corner of some messages on the screenshot below).



I know it is not too noticeable as it was before but it triggered my OCD 😄

**Comment by Jonathansoufer** [comment]
I didn't see this before. Got fixed now.

**Comment by du82** [comment]
I've noticed scrolling issues with this update because when I scroll vertically on a chat, it thinks I am trying to swipe horizontally to reply.

**Comment by flexsurfer** [comment]
comment for this task in general, not about implementation: messages are very critical part of the app, and currently renderer is very complex and heavy, so we need to reduce its complexity, but this task only adds complexity and implementation will make renderer less performant, so I would postpone implementation of this task

**Comment by Jonathansoufer** [comment]
> comment for this task in general, not about implementation: messages are very critical part of the app, and currently renderer is very complex and heavy, so we need to reduce its complexity, but this task only adds complexity and implementation will make renderer less performant, so I would postpone implementation of this task

Hello, but what's the idea? Leave this implementation on hold or reimplement this feature w/ a different approach when performance for chats get's reviewed overall?

**Comment by flexsurfer** [comment]
let's close it for now, original issue doesn't have design team input

**Comment by hesterbruikman** [comment]
fyi @pedro-et will review design once he's available

**Pull request closed without merging**
