### PR TITLE
[#14574] Update chat clock on group event

### LINKED ISSUE #14574: "Invalid event protocolMembershipUpdateEvent..." error is shown after invited to the group chat user sends the message
**Steps to reproduce:**
1. Check the status.prod fleet is set for USER_A and USER_B
2. Make USER_A and USER_B mutual contacts
3. Create a group chat as USER_A -> Invite USER_B 
4. Open group chat as USER_B
5. Send the message

**Actual result:**
"Invalid event protocolMembershipUpdateEvent..." error is shown

https://user-images.githubusercontent.com/52490791/208422879-1912a44f-7d28-4f6f-b7e9-48d2e82bc5c3.mp4

**Logs:** [geth.log](https://github.com/status-im/status-mobile/files/10259099/geth.log)

**Expected result:**
The message is sent

**ENV:** any android

**Additional info:**
- Reproduced only in 10% of cases. Maybe logs can help to understand the error
- The current issue happens for USER_B only for 1st group chat. If it is not reproduced during message sending in the group chat, then the user should be re-created and steps from 'steps to reproduce' should be repeated again

### PR DESCRIPTION
**Pull request by rasom**
fixes #14574

status: ready

### CODE REVIEW

**Review by Parveshdhull — APPROVED** [review]

**Comment by VolodLytvynenko** [comment]
Hi @rasom Thank you for your work. I didn't finish the testing fully but was faced with some critical issue. Take a look at it, please.

**ISSUE 1 Requested contact is not shown after his keychat is pasted and [+] button is tapped**
**Steps to reproduce:**
1. Go to the 'contact' page -> Add new contacts
2. Paste some valid chatkey to the textbox -> tap [+]

**Actual result:**
The contact's '3 random name' is not shown as added within contacts page
https://user-images.githubusercontent.com/52490791/212086292-ff2cb082-3bbc-4748-ba05-fea413f4b511.mp4

**Expected result:**
The contact's '3 random name' is shown as added within contacts page
image

**Comment by rasom** [comment]
@VladimrLitvinenko this is either introduced in `develop` or in `status-go`. It can't be because of changes from this specific PR

**Comment by VolodLytvynenko** [comment]
> @VladimrLitvinenko this is either introduced in `develop` or in `status-go`. It can't be because of changes from this specific PR

ok. I will rebuild develop and recheck it there. Let you know the result soon

**Comment by VolodLytvynenko** [comment]
> @VladimrLitvinenko this is either introduced in `develop` or in `status-go`. It can't be because of changes from this specific PR

Sorry for the invalid issue. You are right, this is on develop branch

**Comment by rasom** [comment]
@VladimrLitvinenko I can't open the video. What do you call `a valid chat key`, public key?

**Comment by VolodLytvynenko** [comment]
> 

yes. I paste valid chat key

**Comment by pavloburykh** [comment]
@rasom tested by @VladimrLitvinenko and can be merged. Issue with contact is introduced in develop and turned out to be feature not a bug.

**Pull request merged**
