### PR TITLE
[#16422] Merge profile and profile overview into one map in status-go

### LINKED ISSUE #16422: Merge profile and profile overview into one map in status-go
Currently, its done in the subscriptions, we merge profile overview and profile because some settings (for example customization color) we have only in the profile overview map, it should be done in status-go

related issue: https://github.com/status-im/status-go/issues/3684

### LINKED ISSUE #16444: Selected accent color is not applied inside newly created account until re-login
**Steps:** 

1. Proceed with creating a new user
2. Select some non-default accent color on Profile creation screen
3. Pay attention if selected accent color has been applied inside account

**Actual result:** selected accent color is not applied until re-login

https://github.com/status-im/status-mobile/assets/97245802/b3910156-b931-49e7-87e1-c95b3ddc5b1a

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

### PR DESCRIPTION
**Pull request by flexsurfer**
fixes #16444
fixes #16422

QA: for already existing accounts , default color will be used

### CODE REVIEW

**Review by vkjr — APPROVED** [review]

**Review by Parveshdhull — APPROVED** [review]

**Comment by VolodLytvynenko** [comment]
hi @flexsurfer Could you resolve please the failed integration tests [fix](https://ci.status.im/job/status-mobile/job/prs/job/tests/job/PR-16449/2/consoleText) and existing conflicts? After that, we can perform manual testing. Thanx!

**Comment by VolodLytvynenko** [comment]
hi @flexsurfer Could you resolve please the failed integration tests (https://ci.status.im/job/status-mobile/job/prs/job/tests/job/PR-16449/2/consoleText) and existing conflicts? After that, we can perform manual testing. Thanx!

**Comment by pavloburykh** [comment]
> hi @flexsurfer Could you resolve please the failed integration tests [fix](https://ci.status.im/job/status-mobile/job/prs/job/tests/job/PR-16449/2/consoleText) and existing conflicts? After that, we can perform manual testing. Thanx!

@VladimrLitvinenko this PR introduces changes in status go and introduces new go version. That's why you see conflicts in status-go-version.json 
So nothing should be resolved here.

**Comment by flexsurfer** [comment]
sorry @VladimrLitvinenko its not ready for review yet

**Pull request closed without merging**
