### PR TITLE
Show token requirements only for token gated channels

### LINKED ISSUE #19350: User can still view token requirements in a non-token gated community
# Bug Report

## Problem 
In the case of a non-token gated community with some token gated channels, the user is able to view the token requirements bottom sheet even when there are no tokens requirements to view. We dont need to launch the bottom sheet where there no permissions on the community level and in this case we dont need to show the option to view token requirements on the community context action sheet

This bug is to simply remove the `view token requirements` from the the community context action sheet in the case where there are no permissions on a community level

#### Expected behavior
The options to view token requirements for a non-token gated community should not be shown

#### Actual behavior
The options to view token requirements for a non-token gated community is shown

### Reproduction

1.  Open Status app
2. Navigate to a non-token gated community with a token gate channel
3. Try to view community context sheet
4. The user can view token requirements

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

### PR DESCRIPTION
**Pull request by clauxx**
fixes #19350

### Summary
Differentiating the token-gated communities and channels when showing the token requirements bottom-sheet. -
Added:
- hiding token requirements from **community** context menu when community has no "role-based" permissions 
- hiding token requirements from **channel** context menu when channel is not token-gated

#### Platforms

- Android
- iOS

### Steps to test

*Community*
- Open Status
- Open community with no token requirements but with token gated channels
- Open context-menu
- No "View token requirements" menu should be visible

*Channel*
- Open Status
- Open community
- Open non token gated chat
- Open context-menu
- No "View token requirements" menu should be visible

status: ready

### CODE REVIEW

**Review by Parveshdhull — APPROVED** [review]

**Review by jo-mut — APPROVED** [review]

**Review by J-Son89 — APPROVED** [review]

**Review by seanstrom — APPROVED** [review]

**Comment by churik** [comment]
@clauxx  
Thank you for your contribution, and apologize for the delay in testing! 

Could you please resolve any conflicts, rebase your branch for updated builds, and notify QA once it's ready for review (please follow the process [here](https://github.com/status-im/status-mobile/blob/develop/doc/pipeline_process.md)) ? 
We appreciate your understanding and cooperation.

**Comment by churik** [comment]
So I tested PR with different combinations of community channels/community permissions, tried to update them - no issues are found.

Thank you for your quality work!
e2e results are not related to a particular PR.
Please, make sure that you re-tested it after resolving conflicts, in case of any doubts you can ping me to help.

I'm moving PR to merge, but please make sure that it is working after rebase.

**Comment by clauxx** [comment]
@churik 

> Thank you for your contribution, and apologize for the delay in testing!

no worries :+1: 

> Could you please resolve any conflicts, rebase your branch for updated builds, and notify QA once it's ready for review (please follow the process [here](https://github.com/status-im/status-mobile/blob/develop/doc/pipeline_process.md)) ?
We appreciate your understanding and cooperation.

sorry, was off earlier today. Just did the rebase, but I think it's difficult to guarantee that a PR will have no conflicts when it's picked up by QA (not when manual QA is requested).

> So I tested PR with different combinations of community channels/community permissions, tried to update them - no issues are found.
Thank you for your quality work!
e2e results are not related to a particular PR.
Please, make sure that you re-tested it after resolving conflicts, in case of any doubts you can ping me to help.
I'm moving PR to merge, but please make sure that it is working after rebase.

Thank you! :relaxed: I just tested it and it works so I'll put it through E2E again just in case before merging

**Comment by churik** [comment]
Good to go, @clauxx 
Thank you!

**Pull request merged**
