### PR TITLE
Online Status Indicator

### LINKED ISSUE #12547: Add online status indicator
As a user
I want to be able to be able to set my online status
So that other users can see whether I am online

### Description

We should allow a user to set their own status.
By default that should be "invisible", this needs to be changed in status-go, otherwise it's ready in status-go.

### Designs

https://www.figma.com/file/TNCyHKtR3sx5EL6YznFWUa4O/Profile?node-id=7253%3A27195

### PR DESCRIPTION
**Pull request by Parveshdhull**
fixes #12547

### Summary
PR implements Online Status Indicator
<div align="center">
Screenshot
Screenshot
Screenshot
</div>

PR follows these design guidelines: [Designs](https://www.figma.com/file/TNCyHKtR3sx5EL6YznFWUa4O/Profile?node-id=7253%3A27195)

#### Design Input Required
- Offline white circle looks a little weird above chat icon. Should circle only be visible for online & DND and no circle for offline?
- Options to keep? (online, offline, DND)

#### TODO
Currently, DND is working as an invisible/offline, and the real invisible button don't do anything. This will start working once status-go will include this option.

#### Code
There were some residue code in [styles.cljs](https://github.com/status-im/status-react/pull/12706/files#diff-f54bb761ef81cb3f9f1af35f7080f4edc667f1e88fb816755a5d14d7d442992d) file from 2016 implementation of online status indicator. Currently, it is not used anywhere, so removed to avoid confusion between styles.

Thanks

### CODE REVIEW

**Comment by du82** [comment]
Just a few things I noticed while bug testing this PR:

Screenshot_20211014-195915_Status PR

It's not possible to tap the 'Invisible' option to set my online status to invisible.

Screenshot_20211014-195948_Status PR

Also, if someone is online, and I open the profile of that online person, it doesn't show that they are online even though it shows that circle as green everywhere else in the app.

Hope this helps,
~ Du

**Comment by Parveshdhull** [comment]
Hi, Thank you very much for testing the app and your valuable insights.

1. Invisible button will start working, once it is implemented in status-go.

2. Did you tested in latest version # 6? I retested and it seems to work fine.

**Comment by du82** [comment]
Having "Always online" is great, but can you bring back the options for Do Not Disturb and Idle in addition to the new options? Those are genuinely useful to many people, and I think having them back on Status would be neat :)

**Comment by Parveshdhull** [comment]
Maybe in the future. Dnd is just online with push notifications disabled. You can still manually disable notifications from settings even without Dnd 👍

**Comment by du82** [comment]
Having it as an option to turn off notifications AND make others aware that you have notifications off would be great, it was a really useful feature back when I used Discord, and it would be great to have back on Status.

**Comment by Parveshdhull** [comment]
The purpose of this draft PR was only testing. Now, as the feature is ready, will create a separate PR for QA and review 👍

**Pull request closed without merging**
