### PR TITLE
Fix migrations

### LINKED ISSUE #6381: Problem with encryption key error after upgrade from 0.9.29
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: User gets "We detected problem with the encryption key" error and can't log in to existing account after upgrading from 0.9.29. There should be specific data in 1:1 chat for the user, all in Ropsten:
1. send ETH  in 1:1 chat
2. request ETH in 1:1 chat
3. request ETH from same user in Wallet (so request message is shown in 1:1 chat)
4. get a request message in 1:1 chat and a text message
screenshot_20181018-113016

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
User can log in after upgrade
#### Actual behavior
[comment]: # (Describe what actually happened.)
On signing in user gets "We detected problem with the encryption key" error and can't log in to existing account after upgrading from 0.9.29
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

User A (will get an issue after upgrade):
- Install 0.9.29 from PlayStore
- Add user B (B also has 0.9.29 installed from PlayStore)
- both users switch to Ropsten
- send text message to user B
- as user B: send text message to A and add to the contacts 
- as user A: in 1:1 chat with B send 0.0001 ETH
- as user A: in 1:1 chat with B request 4 ETH
- as user A: in wallet send request of 6 ETH to user B
- as user B: in 1:1 chat with user A send request of 0.0008 ETH
- as user A: close app and upgrade to last nightly
- as user A: try to sign in to the app
logcat contains 
```
Could not change account TypeError: undefined is not an object (evaluating 'e["content-type"]="command"')
```

on user A side 1:1 chat with user B looks like this:

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: upgrade from 0.9.29 to nightly from 18.10.2018
* Operating System: Android on both devices

#### Logs
[logcat.txt](https://github.com/status-im/status-react/files/2490956/logcat.txt)

```
10-18 11:28:01.550 21356 21443 D ReactNativeJS: DEBUG [status-im.data-store.realm.core:35] - Opening realm at  /data/user/0/im.status.ethereum/files/../no_backup/realm/accounts/0xc37a96f2fe109574a8e44092fd2d791145a6b2845147ce6d79ffdc5151b5b58d ...
10-18 11:28:01.550 21356 21443 D ReactNativeJS: DEBUG [status-im.data-store.realm.core:37] - Using encryption key...
10-18 11:28:01.560 21356 21443 D ReactNativeJS: DEBUG [status-im.data-store.realm.schemas.account.migrations:91] - migrating v14 account database
10-18 11:28:01.570 21356 21443 W ReactNativeJS: WARN [status-im.accounts.login.core:33] - Could not change account TypeError: undefined is not an object (evaluating 'e["content-type"]="command"')
10-18 11:28:01.570 21356 21443 D ReactNativeJS: DEBUG [status-im.utils.handlers:37] - Handling re-frame event:  :init.callback/account-change-error
```

### PR DESCRIPTION
**Pull request by janherich**
[comment]: # (Please replace ... with your information. Remove < and >)
[comment]: # (To auto-close issue on merge, please insert the related issue number after # i.e fixes #566)

fixes #6381 

status: ready

### CODE REVIEW

**Review by rasom — APPROVED** [review]

**Review by yenda — APPROVED** [review]

**Comment by lukaszfryc** [comment]
@janherich 

I replicated the original issue on my device to make sure I can test this PR. The fix seems to work fine, there is no "encryption key" error BUT, the "request" command send from wallet is not rendered correctly in chat after the upgrade. There is "Unhandled content type" error:



To replicate, in wallet send request of 6 ETH to user B and then upgrade the app.

**Comment by janherich** [comment]
@lukaszfryc Should be fixed in a new build (coming soon)

**Comment by lukaszfryc** [comment]
OK, I did not notice any issues while upgrading from 0.9.28 or 0.9.29. I had 1-1 chats with all commands cobinations (including commands from wallet), profile changes, public chats, dapps, etc. 

I think we can assume that the upgrade error is fixed now. Thanks @janherich and @annadanchenko!

**Comment by lukaszfryc** [comment]
Of course, we will do additional tests on iOS when TestFlight build for release branch is ready.

**Pull request merged**
