### PR TITLE
fix Lost the syncing state in fallback recovery, when first enter the seed phrase for the wrong account

### LINKED ISSUE #21258: Lost the syncing state in fallback recovery, when first enter the seed phrase for the wrong account
# Bug Report

## Problem 
Follow up: #21090 
In seed phrase fallback recovery, if you first enter the seed phrase for the wrong account and press 'Continue,' then go back and enter the seed phrase for the correct account, you will lose the syncing state.

### Reproduction

1. Initiate the fallback flow.
2. Enter the correct seed phrase for syncing two devices.
3. Click 'Continue' (expected to open the screen for creating a password).
4. Return to the previous screen.
5. Enter the correct seed phrase, but from a different status profile not used on this device.
6. Click 'Continue' (expected to open the screen for creating a new account).
7. Return to the previous screen.
8. Enter the correct seed phrase for syncing two devices.
9. Click 'Continue'.

#### Actual result: 
The screen for creating a new account is opened (this happens every time if the user triggers account creation in the fallback flow).

https://github.com/user-attachments/assets/2ece11ad-da89-4a3c-8a4a-c6a627dc239b

#### Expected result: 
The screen for creating a password should be opened.

### Additional Information

- Status version: PR build #21090 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by Parveshdhull**
fixes https://github.com/status-im/status-mobile/issues/21258

status: ready

### CODE REVIEW

**Review by flexsurfer — APPROVED** [review]

**Review by qfrank — APPROVED** [review]

**Comment by Horupa-Olena** [comment]
@Parveshdhull 
I created a new account for testing and noticed that this [screen](https://www.figma.com/design/V6nlpAWIf2e1XU8RJ9yQPe/Syncing-for-Mobile?node-id=3338-72168&node-type=frame&t=epgQSCNN581wGfku-0) appears, but it shouldn’t. Becuase it's not fallback flow

**Comment by Parveshdhull** [comment]
> @Parveshdhull I created a new account for testing and noticed that this [screen](https://www.figma.com/design/V6nlpAWIf2e1XU8RJ9yQPe/Syncing-for-Mobile?node-id=3338-72168&node-type=frame&t=epgQSCNN581wGfku-0) appears, but it shouldn’t. Becuase it's not fallback flow

Hi @Horupa-Olena,

Thank you very much for testing the PR. Could you please share a screen recording so that I can replicate the issue?

**Comment by Horupa-Olena** [comment]
@Parveshdhull Sorry, I forgot add the video because it's simple flow of account creation and don't need any special actions. 

https://github.com/user-attachments/assets/55f8ee20-0f54-47a2-b89d-81e9123cdc7d

**Comment by Parveshdhull** [comment]
> @Parveshdhull Sorry, I forgot add the video because it's simple flow of account creation and don't need any special actions.

Thank you, @Horupa-Olena, for sharing the video. Interestingly, I was unable to reproduce this issue when I tried to create an account from the profiles screen instead of the intro. The issue should be fixed now.

**Comment by Parveshdhull** [comment]
> The issue should be fixed now.

Also rebased the PR, so that fix from https://github.com/status-im/status-mobile/pull/21300 is also included.

**Comment by Horupa-Olena** [comment]
@Parveshdhull The main issue has been fixed.

However, on iOS, I encountered the following issue: 

#### ISSUE 1: ios onboarding: missing screen after password creation, "generating keys..." screen appears instead
**Steps:**
1. Device A1 try to sync with Device A2
2. Initiate fallback flow
3. Look for onboarding screen after entered seed phrase

**Expected results:**
This [screen](https://www.figma.com/design/V6nlpAWIf2e1XU8RJ9yQPe/Syncing-for-Mobile?node-id=3338-72168&node-type=frame&t=h2aHliWk1VIpyOk2-0) should appears. 

**Actual results:**
Instead, the default screen with the message "Generating keys..." appears.

[Video link](https://github.com/user-attachments/assets/0b390817-2b5f-4ed1-80fd-dd6e88a79947)

**Comment by Horupa-Olena** [comment]
@Parveshdhull @jrainville 
I also noticed two issues with notifications in the AC after sync:

1. After a successful sync that doesn’t use the fallback flow (but follows the main path), this [notification](https://www.figma.com/design/V6nlpAWIf2e1XU8RJ9yQPe/Syncing-for-Mobile?node-id=3347-74825&node-type=frame&t=HVq4vRcCF2A3Aafc-0) appears in the AC. However, in this case, no notification should be shown.

2. After a successful sync using the fallback flow, this [notification](https://www.figma.com/design/V6nlpAWIf2e1XU8RJ9yQPe/Syncing-for-Mobile?node-id=3347-103361&node-type=frame&t=HVq4vRcCF2A3Aafc-0) appears in the AC, but it should display this [notification](https://www.figma.com/design/V6nlpAWIf2e1XU8RJ9yQPe/Syncing-for-Mobile?node-id=3347-74825&node-type=frame&t=HVq4vRcCF2A3Aafc-0) instead (this can also be seen in the end of video 

https://github.com/user-attachments/assets/75835c47-8a73-4e55-9f8f-cd36c8967a1d

I assume some changes were made on the status-go side, as these issues were not present in the main PR for the fallback flow. Could you confirm that notifications changes by the status-go side or I mistake? So I can create separately bug reports for this issues

**Comment by Parveshdhull** [comment]
> I also noticed two issues with notifications in the AC after sync:

Hi @Horupa-Olena,

Thank you very much for reporting these issues. Could you please confirm whether you are using a new account for testing? (Old notifications may have been fetched from the last fallback recovery flow.) -  https://github.com/status-im/status-mobile/pull/21090#issuecomment-2345841505

**Comment by Horupa-Olena** [comment]
@Parveshdhull Thank you for your quick fix.

This [issue ](https://github.com/status-im/status-mobile/pull/21090#issuecomment-2345820848) still reproduces if I use the old profile. The difference is that in this PR, if I use a new account, I receive an incorrect notification. Previously, the first sync on a new account worked fine.
For the old account, these two issues now just overlap.

**Comment by Parveshdhull** [comment]
> ISSUE 1: ios onboarding: missing screen after password creation, "generating keys..." screen appears instead

Thank you for finding this issue. Should be fixed now.

**Comment by Parveshdhull** [comment]
> This [issue ](https://github.com/status-im/status-mobile/pull/21090#issuecomment-2345820848) still reproduces if I use the old profile. The difference is that in this PR, if I use a new account, I receive an incorrect notification. Previously, the first sync on a new account worked fine. For the old account, these two issues now just overlap.

Issue already logged here and have not been worked on yet: https://github.com/status-im/status-mobile/issues/21260

**Comment by Parveshdhull** [comment]
> if I use a new account, I receive an incorrect notification. 

Oh, you mean even if for new accounts we are showing wrong notification? Sorry I missed this.

**Comment by Parveshdhull** [comment]
> > if I use a new account, I receive an incorrect notification.
> 
> Oh, you mean even if for new accounts we are showing wrong notification? Sorry I missed this.

Weird, I just tested latest build and I am seeing correct notifications.

**Comment by Horupa-Olena** [comment]
> > > if I use a new account, I receive an incorrect notification.
> > 
> > 
> > Oh, you mean even if for new accounts we are showing wrong notification? Sorry I missed this.
> 
> Weird, I just tested latest build and I am seeing correct notifications.

@Parveshdhull Agreed. I think (but not sure) it can be some changes on status-go side, because this issue was found in nightly build. I see it only once in #21090, but now it reproduce more oten. 

> After a successful sync that doesn’t use the fallback flow (but follows the main path), this [notification](https://www.figma.com/design/V6nlpAWIf2e1XU8RJ9yQPe/Syncing-for-Mobile?node-id=3347-74825&node-type=frame&t=HVq4vRcCF2A3Aafc-0) appears in the AC. However, in this case, no notification should be shown.

**Comment by Horupa-Olena** [comment]
@Parveshdhull Thank for your fix!

> After a successful sync using the fallback flow, this [notification](https://www.figma.com/design/V6nlpAWIf2e1XU8RJ9yQPe/Syncing-for-Mobile?node-id=3347-103361&node-type=frame&t=HVq4vRcCF2A3Aafc-0) appears in the AC, but it should display this [notification](https://www.figma.com/design/V6nlpAWIf2e1XU8RJ9yQPe/Syncing-for-Mobile?node-id=3347-74825&node-type=frame&t=HVq4vRcCF2A3Aafc-0) instead (this can also be seen in the end of video

This fix is ok!

> ISSUE 1: ios onboarding: missing screen after password creation, "generating keys..." screen appears instead

This fix is ok, too.

**Comment by Horupa-Olena** [comment]
@Parveshdhull 

> After a successful sync that doesn’t use the fallback flow (but follows the main path), this [notification](https://www.figma.com/design/V6nlpAWIf2e1XU8RJ9yQPe/Syncing-for-Mobile?node-id=3347-74825&node-type=frame&t=HVq4vRcCF2A3Aafc-0) appears in the AC. However, in this case, no notification should be shown.

Could you confirm, for this issue, we need to create a separate bug report, right?

**Comment by jrainville** [comment]
> @Parveshdhull
> 
> > After a successful sync that doesn’t use the fallback flow (but follows the main path), this [notification](https://www.figma.com/design/V6nlpAWIf2e1XU8RJ9yQPe/Syncing-for-Mobile?node-id=3347-74825&node-type=frame&t=HVq4vRcCF2A3Aafc-0) appears in the AC. However, in this case, no notification should be shown.
> 
> Could you confirm, for this issue, we need to create a separate bug report, right?

@Parveshdhull I just tested this on Desktop -> Desktop and I couldn't reproduce, so my guess is that you call `finishPairingThroughSeedPhraseProcess` when it's not needed?

As far as I can see, it's not a status-go issue, because it would reproduce on the Desktop side then.

cc @Horupa-Olena

**Comment by Parveshdhull** [comment]
> Could you confirm, for this issue, we need to create a separate bug report, right?

If this is happening even for fresh account then I think its probably a new bug in UI side. But if its happening on the same account which we used earlier or fallback recovery then its the same issue. - https://github.com/status-im/status-mobile/pull/21090#issuecomment-2349134620

**Comment by Horupa-Olena** [comment]
> > Could you confirm, for this issue, we need to create a separate bug report, right?
> 
> If this is happening even for fresh account then I think its probably a new bug in UI side. But if its happening on the same account which we used earlier or fallback recovery then its the same issue. - [#21090 (comment)](https://github.com/status-im/status-mobile/pull/21090#issuecomment-2349134620)

@Parveshdhull unfortunately it's reproduce on new accounts too

**Comment by Parveshdhull** [comment]
> @Parveshdhull unfortunately it's reproduce on new accounts too

Thank you for confirming, issue should be fixed now.

**Comment by Parveshdhull** [comment]
Please let me know if PR also fixes https://github.com/status-im/status-mobile/issues/21260

**Comment by Horupa-Olena** [comment]
@Parveshdhull Hey! Thanks for your fix! 
> If this is happening even for fresh account then I think its probably a new bug in UI side.

This issue is fixed. But for old accounts (old = account that have few tries to syncs before) issue from #21260 still reproduce.

**Comment by Horupa-Olena** [comment]
@Parveshdhull I don't see any other issues. The PR is ready to be merged.

**Pull request merged**
