### PR TITLE
Update status-go to develop-e6610f3

### PR DESCRIPTION
**Pull request by adriacidre**
fixes https://github.com/status-im/ideas/blob/master/ideas/63-refactor-geth-packages.md

### Summary:
Updates status-go to **develop-e6610f3** including [#63-refactor-geth-packages](https://github.com/status-im/ideas/blob/master/ideas/63-refactor-geth-packages.md)

status: wip

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/status-im/ideas">status-im/ideas</a></strong></div><div>ideas - Swarm Home. New, completed and in-progress features for Status</div></blockquote>

### CODE REVIEW

**Review by flexsurfer — APPROVED** [review]

**Review by jeluard — APPROVED** [review]

**Comment by lukaszfryc** [comment]
@adriacidre what kind of testing is needed here? I suppose regression of all messaging features. Anything else, Wallet?

**Comment by adriacidre** [comment]
hey @lukaszfryc, changes since last `status-go` update covers almost everything from messaging to wallet.

**Comment by lukaszfryc** [comment]
So, I will do core regression tests and if there are no bugs we merge it. Tomorrow I'll do full regression during nightly testing.

**Comment by lukaszfryc** [comment]
Overall looks good. I experienced big delays in receiving messages. Also, when I clicked on an incoming message the chat opened but the new message didn't appear. But, the same issues happen on latest nightly so I believe it has nothing to do with this PR. I think we can merge it.

@adriacidre I wonder whether the issues are related to some network overload (I used Ropsten) or maybe some bugs introduced by the new protocol. Is there a way to debug this? Like tracking what is happening with a message, what its status, if it's on a mailserver or was delivered? Any way we could do it for debug builds?

**Comment by adriacidre** [comment]
@lukaszfryc only internal refactor was done here, so theoretically nothing should have changed

**Pull request merged**
