### PR TITLE
Correct username in public group

### PR DESCRIPTION
**Pull request by rasom**
partial fix for #2892 

status: ready

### CODE REVIEW

**Review by yenda — APPROVED** [review]

**Comment by flexsurfer** [comment]
@rasom it would be good to add `:username sender-name` to `::send-group-message` too, because in group chat we have "unknown contact" too

**Comment by rasom** [comment]
That's actually a bit different issue because in private group chat you should have the whole list of participants here https://github.com/status-im/status-react/blob/develop/src/status_im/data_store/realm/schemas/account/v19/chat.cljs#L16 .   

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/status-im/status-react">status-im/status-react</a></strong></div><div>status-react - a free (libre) open source, mobile OS for Ethereum</div></blockquote>

**Review by flexsurfer — APPROVED** [review]

**Comment by asemiankevich** [comment]
@rasom could you please clarify what means `partial` fix?

**Comment by asemiankevich** [comment]
Branch: PR-3128
Android: https://i.diawi.com/5vuuPq
iOS: https://i.diawi.com/vzsriL

**Comment by asemiankevich** [comment]
I can confrim that custom names are now shown in `public chat`. This is the only fix in current PR related to issue raised (https://github.com/status-im/status-react/issues/2892). @chadyj do we want to close the original issue and open new one with the rest of work remaining?

**Comment by chadyj** [comment]
@asemiankevich Fantastic that it is working! What is the remaining work? We can probably update the original issue and break it out into parts.

**Comment by asemiankevich** [comment]
@rasom please do not close initial issue when the PR is merged

**Comment by rasom** [comment]
@asemiankevich sure

**Pull request merged**
