### PR TITLE
bug fix #2419 : make status message box adapt to written text

### LINKED ISSUE #2419: "Description" is partly overlapped by "Save" button on  "Profile > Edit" screen (IPhone 5S, "Predictive" is enabled)
### Description

*Type*: Bug

*Summary*: 
Last row in "Description" is overlapped by "Save" button, so user cannot see what he types. Scrolling to the bottom fixes text in the same state, so "Save" button covers last row.

"Predictive" option on IPhone settings  should be enabled.

#### Expected behavior
"Save" button does not overlap last row, "Description" is shown correctly

#### Actual behavior
Last row in "Description"  is overlapped by "Save"

### Prerequisites
- "Predictive" option should be enabled (Settings > General > Keyboard)

### Reproduction
- Open Status
- Login with existing account
- Open Profile
- Tap on Edit
- Fill up "Description" (more than 4 rows)

### Additional Information

* Status version: 0.9.12

* Operating System: IOS 10.3.2

*Device: IPhone 5s

txt

### PR DESCRIPTION
**Pull request by SHA-2048**
fixes #2419

### CODE REVIEW

**Review by oskarth — APPROVED** [review]
Thanks for the contribution @mlahia!

Not sure about all these magic numbers, but I guess it's same as it was before :D Best to let QA check it I think.

**Comment by SHA-2048** [comment]
@oskarth yeah it deserves some explanation indeed.
So the issue is mostly due the fact the message box hight was fixed. So I've replaced it with a `max-heigth` option. other padding changes I did was just to make tinks symetrical a bit, it looked nice to me.

**Review by goranjovic — APPROVED** [review]

**Comment by oskarth** [comment]
@goranjovic Ditto this one :p

**Comment by churik** [comment]
@mlahia can you please rebase this one on current dev brunch?

**Comment by oskarth** [comment]
Auto rebased build hopefully here https://jenkins.status.im/job/status-react/job/parametrized%20build/242/ (only core contributors)

**Comment by SHA-2048** [comment]
@churik done !

**Comment by churik** [comment]
@mlahia issue is still reproducible on Iphone 5s, see details in #2419

**Comment by SHA-2048** [comment]
@chrik ok thanks! Will take a look at it.

**Comment by SHA-2048** [comment]
So I've tweeked the description edit text box size to make it viewable on an iPhone 5s. Also I made the view scrollable, in case same problem happen again, at least user can scroll to the hidden lines.

**Pull request merged**
