### PR TITLE
Feature/profile ui refresh 

### PR DESCRIPTION
**Pull request by flexsurfer**
### Summary:
[comment]: # (Summarise the problem and how the pull request solves it)
Profile screen has been reworked

### Steps to test:
- Open Status
- Open user profile
- Open your profile and modify name, photo, status

[comment]: # (PRs will only be accepted if squashed into single commit.)
status: ready

### CODE REVIEW

**Comment by rasom** [comment]
**ANDROID**

1. 
screen shot 2017-03-15 at 19 11 25

2. "Phone number" section looks a bit off if phone number is not set, maybe we need to add some placeholder there or, at least, fix position of label. The same thing can happen with status if it is empty.

screen shot 2017-03-15 at 19 07 11

**Comment by rasom** [comment]
**Android**
1. 
screenshot_2017-03-16-11-13-49

2. 1) profile image is cropped a bit 2) only one input is focused but both are underlined 
screenshot_2017-03-16-11-16-24

3. Contact's profile. Empty fields should be hidden or contain some placeholders, because it doesn't look good now
screenshot_2017-03-16-11-22-50

4. 
screenshot_2017-03-16-11-20-09

5. Input text is overlapped by "save" button and can not be scrolled
screenshot_2017-03-16-11-19-58

6. Weird behaviour of the "name" input
w

**Comment by rasom** [comment]
**iOS**
1. Wrong positioning of underlines, wrong color
screen shot 2017-03-16 at 12 50 23

2. Wrong styles of text inputs for name and status 
screen shot 2017-03-16 at 12 51 23

3. I'm not sure that we can fix this, but anyway 
screen shot 2017-03-16 at 12 52 45

4. Wrong font
screen shot 2017-03-16 at 12 55 33

**Comment by rasom** [comment]
Also we need to highlight hashtags in status on both platforms:

screenshot_2017-03-16-11-49-59

**Comment by flexsurfer** [comment]
Android

1. - [ ] list background ( @andmironov participation is required)
2. - [ ] empty field  ( @andmironov participation is required) Contact's profile. Empty fields should be hidden or contain some placeholders because it doesn't look good now
3. - [ ] name is cutted 
4. - [x] profile image is cropped a bit
5. - [x] only one input is focused but both are underlined
6. - [ ] wrong input line height
7. - [ ] Input text is overlapped by "save" button and can not be scrolled
8. - [ ] Weird behavior of the "name" input

ios
1. - [ ] Wrong positioning of underlines, wrong color
2. - [ ] Wrong styles of text inputs for name and status
3. - [x] Wrong font 


- [ ] Also we need to highlight hashtags in status on both platforms  ( @andmironov participation is required)

**Comment by rasom** [comment]
I didn't find the way to fix Android.3

**Comment by rasom** [comment]
Let's create another task for Android 1 and 2

**Pull request merged**
