### PR TITLE
[#21708] [Android] Login with Keycard stucks on Preparing screen from…

### LINKED ISSUE #21708: [Android] Login with Keycard stucks on Preparing screen from time to time
# Bug Report

## Problem 
[comment]: # (A problem description)

User stucks and nothing happens.
Only close the app helps.

### Reproduction

1. You need a Keycard with a key pair on it
2. Install app
3. Go to Log in -> Log in with Keycard
4. Go through the flow

#### Actual behavior

Log in stops on Prepare screen.
Image

Today I've faced that my Log in stuck 5 times.
Logs: [Log_in_keycard.zip](https://github.com/user-attachments/files/17950039/Log_in_keycard.zip)

#### Expected behavior

User is successfully Logged in.

### Additional Information

- Status version: nightly and https://github.com/status-im/status-mobile/pull/21705
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by flexsurfer**
fixes #21708

### CODE REVIEW

**Comment by seanstrom** [comment]
I've tried reproducing the error with current status-go release version and this branch. And it seems I'm running into an issue where I get stuck on the "Preparing Status" screen, but only after I initially recover the profile (login with keycard), then remove the profile, and then recover the profile again (login with keycard again).

---

Here's a snippet of the logs that possibly relates to the error:
```
2024-12-13T02:24:42.903Z	ERROR	mobile/status.go:605	failed to restore account	{"error": "failed to prepare for keycard: failed to get keycard pairings: file does not exist", "errorVerbose": "file does not exist\nfailed to get keycard pairings\ngithub.com/status-im/status-go/api.(*GethStatusBackend).prepareForKeycard\n\tgithub.com/status-im/status-go/api/geth_backend.go:1718\ngithub.com/status-im/status-go/api.(*GethStatusBackend).prepareNodeAccount\n\tgithub.com/status-im/status-go/api/geth_backend.go:1526\ngithub.com/status-im/status-go/api.(*GethStatusBackend).RestoreKeycardAccountAndLogin\n\tgithub.com/status-im/status-go/api/geth_backend.go:1397\ngithub.com/status-im/status-go/mobile.restoreAccountAndLogin.func1\n\tgithub.com/status-im/status-go/mobile/status.go:599\ngithub.com/status-im/status-go/api.RunAsync.func1\n\tgithub.com/status-im/status-go/api/utils.go:18\nruntime.goexit\n\truntime/asm_arm64.s:1197\nfailed to prepare for keycard\ngithub.com/status-im/status-go/api.(*GethStatusBackend).prepareNodeAccount\n\tgithub.com/status-im/status-go/api/geth_backend.go:1528\ngithub.com/status-im/status-go/api.(*GethStatusBackend).RestoreKeycardAccountAndLogin\n\tgithub.com/status-im/status-go/api/geth_backend.go:1397\ngithub.com/status-im/status-go/mobile.restoreAccountAndLogin.func1\n\tgithub.com/status-im/status-go/mobile/status.go:599\ngithub.com/status-im/status-go/api.RunAsync.func1\n\tgithub.com/status-im/status-go/api/utils.go:18\nruntime.goexit\n\truntime/asm_arm64.s:1197"}

```

---

[Status-debug-logs-v1.zip](https://github.com/user-attachments/files/18119935/Status-debug-logs-v1.zip)

**Comment by flexsurfer** [comment]
thanks @seanstrom i've reproduced , but error is different
```
2024-12-13T11:35:43.631Z	ERROR	GethStatusBackend	api/geth_backend.go:1412	start node	{"error": "UNIQUE constraint failed: settings.synthetic_id"}
2024-12-13T11:35:43.631Z	ERROR	mobile/status.go:605	failed to restore account	{"error": "failed to start node: UNIQUE constraint failed: settings.synthetic_id", "errorVerbose": "UNIQUE constraint failed: settings.synthetic_id\nfailed to start node\ngithub.com/status-im/status-go/api.(*GethStatusBackend).RestoreKeycardAccountAndLogin\n\tgithub.com/status-im/status-go/api/geth_backend.go:1413\ngithub.com/status-im/status-go/mobile.restoreAccountAndLogin.func1\n\tgithub.com/status-im/status-go/mobile/status.go:599\ngithub.com/status-im/status-go/api.RunAsync.func1\n\tgithub.com/status-im/status-go/api/utils.go:18\nruntime.goexit\n\truntime/asm_arm64.s:1197"}

```

error you mentioned should be fixed in this PR , did you install packages and build the app ?

**Review by Parveshdhull — APPROVED** [review]

**Comment by VolodLytvynenko** [comment]
Hi @flexsurfer, thank you for the PR. I noticed the original issue is Android-specific, but I can also reproduce it on iOS and Android in a specific scenario. However, I believe this can be considered a minor issue, and I can create it as a follow-up then

## PR_ISSUE 1: Login with keycard stuck on "Preparing" screen when current user already onboarded

### Steps:
1. User with seed phrase "A" is already onboarded
2. Log out
3. Login using key card where seed phrase "A" is located

### Actual result:
The Keycard login process gets stuck on the "Preparing" screen.


### Expected result:
- Instead of being stuck, the app should display the "Profile already added" screen.
- The user can then navigate to the list of profiles
image

https://www.figma.com/design/YGm3igIOAcwMqUVJWCJ6f1/Keycard?node-id=4495-45340&node-type=ellipse&m=dev

### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

### Logs
[logs.zip](https://github.com/user-attachments/files/18127446/logs.zip)

**Comment by flexsurfer** [comment]
yeah thanks @VolodLytvynenko it's known different issue cc @mariia-skrypnyk

**Comment by seanstrom** [comment]
@flexsurfer ah apologies, I double checked that I installed the packages and rebuilt the app, and now I'm no longer reproducing this issue 🙌

**Review by seanstrom — APPROVED** [review]

**Comment by VolodLytvynenko** [comment]
@flexsurfer thank you for your work. No issues from my side. PR is ready to be merged

**Comment by flexsurfer** [comment]
thank you, @VolodLytvynenko could you reproduce issue with these steps 
> And it seems I'm running into an issue where I get stuck on the "Preparing Status" screen, but only after I initially recover the profile (login with keycard), then remove the profile, and then recover the profile again (login with keycard again).

if so could you pls create a new issue ?

**Pull request merged**
