### PR TITLE
Ensure no ubuntu-server process is running at startup

### LINKED ISSUE #6584: Desktop app crashed and is unable to start anymore
Yesterday I've experienced for the first time with Status Desktop that, right after trying to login, the "App quit unexpectedly". After that, the application seems unable to start again. While I can start the Status program, there's no window showing up with the app (basically like running any program on mac but having all windows closed).

I've reinstalled the latest nightly and now luck. After I restarted my machine, I was at least able to get the login screen again. However, same thing, after entering my password to login, the app crashes and I'm exactly where I left off. 

Status version: `https://status-im.ams3.digitaloceanspaces.com/StatusIm-181104-025922-fd5fc6-nightly.dmg`
OS: MacOS 10.13.5 High Sierra

If there's anything else I can do to provide more information that helps debugging this, please let me know!

### PR DESCRIPTION
**Pull request by pedropombeiro**
[comment]: # (Please replace ... with your information. Remove < and >)
[comment]: # (To auto-close issue on merge, please insert the related issue number after # i.e fixes #566)

Fixes #6584

### Summary:

[comment]: # (Summarise the problem and how the pull request solves it)
Lots of users continue to be confused about the fact that the app sometimes doesn't show a UI, and having the instructions in the FAQ doesn't seem to be sufficient. This PR ensures that any rogue process is killed as the app is starting up.

#### Platforms
- macOS
- Linux
- Windows

### Steps to test:
- Ensure ubuntu-server is running in the background, but not Status
- Open Status
- App should start normally, whereas previously no UI would show up

status: ready

### CODE REVIEW

**Review by yenda — APPROVED** [review]

**Comment by yenda** [comment]
@PombeirP just wondering for developpers is it going to kill the dev/prod instance while they start the other one?

**Comment by pedropombeiro** [comment]
@yenda no because this hidden behind the `BUILD_FOR_BUNDLE` preprocessor flag.

**Review by vitvly — APPROVED** [review]

**Review by maxhora — APPROVED** [review]

**Comment by pedropombeiro** [comment]
I don't think this will work on Windows without going through privilege escalation with UAC. Curious about MacOS.

**Comment by pedropombeiro** [comment]
OK, next build will contain the changes required for Windows. Only MacOS is unknown right now.

**Comment by churik** [comment]
@PombeirP 
Thank you for amazing work!
It is working on all available for me platforms - Mac OSx Mojave 10.14.1, Windows Home 10 edition, Ubuntu 18.04.

So if I manually stop status-process and leave ubuntu-server running - I can start it again.

**Pull request merged**
