### PR TITLE
Style fixes for pinned messages

### LINKED ISSUE #17523: Posts & attachments - Pinned messages drawer - Empty state text doesn't match Figma
# Bug Report

The pinned message empty state text should have a line break and should use two lines.

<table>
  <thead>
    <tr>
      <th>Actual</th>
      <th>Expected</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td></td>
      <td></td>
    </tr>
  </tbody>
</table>

## Resources

Reported in: https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS/Feedback-for-Mobile?type=design&node-id=6130-58226&mode=design&t=ZiIFjqxnna5FtOFo-0

Figma specs: https://www.figma.com/file/PPWkgOYlZZDxZv5SDGsZVV/Posts-%26-Attachments-for-Mobile?type=design&node-id=3513-380099&mode=design&t=tqru9be4o4mYQhQm-0

### LINKED ISSUE #17524: Posts & attachments - Pinned messages drawer - Incorrect bottom margin
# Bug Report

On Android, the margin at the bottom of the pinned messages drawer is incorrect.

<table>
  <thead>
    <tr>
      <th>Actual</th>
      <th>Expected</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td></td>
      <td></td>
    </tr>
  </tbody>
</table>

## Resources

Reported in: https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS/Feedback-for-Mobile?type=design&node-id=6130-58226&mode=design&t=ZiIFjqxnna5FtOFo-0

Figma specs: https://www.figma.com/file/PPWkgOYlZZDxZv5SDGsZVV/Posts-%26-Attachments-for-Mobile?type=design&node-id=3513-380099&mode=design&t=tqru9be4o4mYQhQm-0

### LINKED ISSUE #17527: Posts & attachments - Pinned messages drawer - incorrect spacing between name and message
# Bug Report

In the pinned messages context drawer, the spacing between the name and message are incorrect.

## Resources

Reported at: https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS/Feedback-for-Mobile?type=design&node-id=6130-58226&mode=design&t=ZiIFjqxnna5FtOFo-0

Figma specs: https://www.figma.com/file/PPWkgOYlZZDxZv5SDGsZVV/Posts-%26-Attachments-for-Mobile?type=design&node-id=3513-380080&mode=design&t=tqru9be4o4mYQhQm-0

### PR DESCRIPTION
**Pull request by alwx**
Updates the visual style of pinned messages so they now match the designs.

fixes https://github.com/status-im/status-mobile/issues/17523
fixes https://github.com/status-im/status-mobile/issues/17524
fixes https://github.com/status-im/status-mobile/issues/17527

#### Platforms

- Android
- iOS

##### Functional

- 1-1 chats
- public chats
- group chats

status: ready

### CODE REVIEW

**Review by flexsurfer — APPROVED** [review]

**Review by ibrkhalil — APPROVED** [review]

**Review by ilmotta — APPROVED** [review]

**Comment by churik** [comment]
@alwx I can't see the illustration for empty state of pinned messages: 
IMAGE 2023-12-04 16:06:34

**Comment by alwx** [comment]
@churik this PR doesn't update the illustration — there is a separate issue for it (https://github.com/status-im/status-mobile/issues/17522) and this issue remains unfixed (because there is no illustration yet)

**Comment by churik** [comment]
@alwx ah, sorry, missed the description. Thank you!

**Comment by churik** [comment]
@Francesca-G please, review if PR fixes issues from design perspective, thank you!

**Review by Francesca-G — APPROVED** [review]
Looks good to me :)

**Pull request merged**
