### PR TITLE
[#19264] fix: add contact bottom margin

### LINKED ISSUE #19264: View profile button bottom margin issue [iOS]
# Design Feedback 2.27

## [iOS] Bottom margin issue of the _View profile_ button
**Bottom margin** [[comment](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj?node-id=118:72067&mode=design#712622016)] of the _View profile_ button is too narrow, causing the button to touch the composer in the Add a contact screen

Screenshot 2024-03-15 alle 10 30 30

#### Expected behavior

Screenshot 2024-03-15 alle 10 31 03

### Reproduction

1. Open the messages home
2. Tap the ➕ button at the top right corner
3. Tap on _Add a new contact_

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS
- Devices in the screenshots: iPhone 13

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by mohsen-ghafouri**
fixes #19264

### Summary

View profile button is too narrow, causing the button to touch the composer in the Add a contact screen

#### Platforms

- iOS

#### After

status: ready

### CODE REVIEW

**Review by ajayesivan — APPROVED** [review]

**Comment by shivekkhurana** [comment]
I had this problem in another feature. Should we not resolve this at a lower level? 

Because every view  that uses `keyboard-avoiding-view` will have this problem due to ios keyboard suggestions.

**Comment by mohsen-ghafouri** [comment]
@shivekkhurana I can see in other places they used either `keyboard-vertical-offset` or add bottom space in other ways. so in this small PR i prefer to not extend the scope and do any refactoring.

**Comment by mohsen-ghafouri** [comment]
@status-im/mobile-qa does it require manual QA or we can do just design review?

**Comment by mariia-skrypnyk** [comment]
Hi @mohsen-ghafouri !

We can check it quickly. 
Just rebase it, please.

**Comment by mohsen-ghafouri** [comment]
Thanks @mariia-skrypnyk, rebased.

**Comment by mariia-skrypnyk** [comment]
@mohsen-ghafouri Thanks for your fix.
iOS looks as you showed on your example.
But Android looks like this:
Screenshot 2024-03-26 at 16 22 01
Can you fix it?

**Comment by ulisesmac** [comment]
@J-Son89 Proably this is also a good place to use the `floating-button` component?

**Comment by mohsen-ghafouri** [comment]
@mariia-skrypnyk I already tested and it was fine, also here in design review you can see Android looks fine https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj/Release-Reviews?type=design&node-id=9-108908&mode=design&t=9yEb61MuyLycw31z-4, but could you please share device information you tested it?

**Comment by mariia-skrypnyk** [comment]
@mohsen-ghafouri yes, please.
I use Samsung A34 14.0
I've retested it once more.
Here are my steps:

https://github.com/status-im/status-mobile/assets/147824399/af2d830a-1462-4a26-af41-a3469d007f11

**Comment by mohsen-ghafouri** [comment]
@ulisesmac could you please review it again? i used what you mention for this screen.

**Comment by mohsen-ghafouri** [comment]
@mariia-skrypnyk could you please test again?

**Comment by ulisesmac** [comment]
> @ulisesmac could you please review it again? i used what you mention for this screen.

@mohsen-ghafouri Sure! and sorry for the delay reviewing this.

**Review by ulisesmac — APPROVED** [review]
@mohsen-ghafouri  The code looks good :+1:

**Comment by mariia-skrypnyk** [comment]
> @mariia-skrypnyk could you please test again?

Hi @mohsen-ghafouri !
Sorry for the delay!
Can you please rebase your PR?

**Comment by mohsen-ghafouri** [comment]
Hi @mariia-skrypnyk, done

**Comment by mariia-skrypnyk** [comment]
Thanks @mohsen-ghafouri for your fix!

I've checked iOS and Android.
For last one I'll ask @Francesca-G to leave her comment from design perspective. 
Is it ok that user's profile is not fully visible because of blurred View profile button.
Screenshot 2024-04-02 at 13 36 33

**Review by Francesca-G — APPROVED** [review]
Looks good ✨

**Pull request merged**
