### PR TITLE
fix_: community sync

### LINKED ISSUE #21303: Part of communities are not synced after syncing with Desktop
**Note:** bug might not be reproducible every time. 

**Steps:**

1. Desktop Device joins a number of communities. In my case it was Status community and two additional ones
2. Perform Syncing of Mobile device with Desktop
3. See if all of the communities present on Mobile device after sync is finished

**Actual result:** in my case only 2 of 3 communities have been synced. 

[Desktop_geth.log.zip](https://github.com/user-attachments/files/17077948/Desktop_geth.log.zip)
[Mobile_synced.zip](https://github.com/user-attachments/files/17077949/Mobile_synced.zip)

https://github.com/user-attachments/assets/123261fc-e07b-4b56-ba73-83a7b9e77e22

**Screenshot from Desktop:** 

sync desktop

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

### PR DESCRIPTION
**Pull request by qfrank**
fixes #21303

relate status-go [PR](https://github.com/status-im/status-go/pull/5880)

status: ready.

### CODE REVIEW

**Comment by VolodLytvynenko** [comment]
hi @qfrank no issues from my side. All communities are synced for me. PR is ready to be merged

**Comment by qfrank** [comment]
> hi @qfrank no issues from my side. All communities are synced for me. PR is ready to be merged

Thank you for your feedback ❤️, let's wait for the [integration test](https://github.com/status-im/status-go/pull/5880#issuecomment-2376983219) so that we won't  see it randomly again @VolodLytvynenko  cc @osmaczko

**Comment by osmaczko** [comment]
> > hi @qfrank no issues from my side. All communities are synced for me. PR is ready to be merged
> 
> Thank you for your feedback ❤️, let's wait for the [integration test](https://github.com/status-im/status-go/pull/5880#issuecomment-2376983219) so that we won't see it randomly again @VolodLytvynenko cc @osmaczko

The integration test is already in place. @VolodLytvynenko, may I kindly ask you to test community requests to join between the old (one before that PR) and new version (current PR) for any regressions, in both directions?

**Comment by pavloburykh** [comment]
> > > hi @qfrank no issues from my side. All communities are synced for me. PR is ready to be merged
> > 
> > 
> > Thank you for your feedback ❤️, let's wait for the [integration test](https://github.com/status-im/status-go/pull/5880#issuecomment-2376983219) so that we won't see it randomly again @VolodLytvynenko cc @osmaczko
> 
> The integration test is already in place. @VolodLytvynenko, may I kindly ask you to test community requests to join between the old (one before that PR) and new version (current PR) for any regressions, in both directions?

I have posted results in go [PR](https://github.com/status-im/status-go/pull/5880#issuecomment-2402622675) but posting it here as well:

> I have checked, community join request seem to work fine, let's wait for update from @anastasiyaig

> The only problem I have faced is that https://github.com/status-im/status-mobile/issues/21303 still reproducible for me. Same user, same steps, same community not synced as described in the issue.

> @osmaczko I am using Desktop nightly as device A and PR mobile build (with current changes) as device B. Desktop generates sync QR code and I scan it via mobile.

> I do not see any links to corresponding Desktop PR that's why I used Desktop nightly build when testing this PR between mobile-desktop.

> @osmaczko maybe it could be some problem with Status community itself which is not synced...I have this community for user which is recovered Desktop. But when I recover this user on another device (mobile), Status community is not recovered. To sum up: Status community both not recovered and not synced for me on mobile.


@osmaczko @qfrank @churik 

I have not faced the issue with any other community except of Status community. Based on that I would merge this PR and try to figure out the problem with Status community separately. As I have mentioned above, I am not able neither to sync no to recover Status community for specific user (both in PR and develop). We need to investigate more deeply if this is a problem of community itself or the problem of my user.

**Comment by qfrank** [comment]
> I am not able neither to sync no to recover Status community for specific user (both in PR and develop). We need to investigate more deeply if this is a problem of community itself or the problem of my user.

Could you share the logs so that I can take a quick look? Or attach it in a separate issue pls, thank you! @pavloburykh

**Comment by pavloburykh** [comment]
> Could you share the logs so that I can take a quick look? Or attach it in a separate issue pls, thank you! @pavloburykh

@qfrank for some reason I am not able to reproduce the issue today. Once I face it again I will log a separate ticket. Current PR is ready for merge. cc @osmaczko

**Comment by qfrank** [comment]
> > Could you share the logs so that I can take a quick look? Or attach it in a separate issue pls, thank you! @pavloburykh
> 
> @qfrank for some reason I am not able to reproduce the issue today. Once I face it again I will log a separate ticket. Current PR is ready for merge. cc @osmaczko

I guess it was because proxy not stable, as I faced this issue before and the error log shows clearly

**Review by flexsurfer — APPROVED** [review]

**Comment by pavloburykh** [comment]
Hey @qfrank. Corresponding go [PR](https://github.com/status-im/status-go/pull/5880) has been merged into develop. Could you please bump go version on mobile side so we get this fix in mobile develop? Thank you!

**Pull request merged**
