### PR TITLE
status-go: group chat adjustments

### PR DESCRIPTION
**Pull request by osmaczko**
https://github.com/status-im/status-go/compare/86054875...8c17c3af

status-go PR: https://github.com/status-im/status-go/pull/2828
status-desktop PR: https://github.com/status-im/status-desktop/pull/7188

### Summary

Now:

- only mutual contacts can be added to the group (either on group creation or later)
- any member has the ability to add its mutual contact to the group
- any member has the ability to change the name and color of the group

If in any doubts please refer to the specs: https://github.com/status-im/feature-specs/blob/3bcd4909d730bea213ad94412ed8e0077a32e7ba/content/raw/chat/group_chat.md

#### Areas that maybe impacted

- creating group chat
- adding/removing members to group chat
- changing group chat properties: name, ~~image~~(not implemented yet), color

##### Functional
- group chats

status: ready

### CODE REVIEW

**Comment by osmaczko** [comment]
Hi @churik, any progress on that one?

**Comment by churik** [comment]
Hello! PR testing was a bit suspended due to release on mobile -side, sorry for the delay. We're close to the end and will be able to tackle it in several next days
Meanwhile can you please rebase your PR to the current `develop`?

**Comment by osmaczko** [comment]
Sure, will do that. Sorry for rushing you. Good luck with the release!

**Comment by osmaczko** [comment]
Rebased both this PR and status-go PR on latest develops :)

**Comment by osmaczko** [comment]
@churik I've decided to merge status-go PR without mobile regression testing results. It is mainly due to the high conflict-proneness of my PR. It was tested on the status-desktop side where no major issues were found. Also, recently the workflow has changed and developers don't need to wait for QA approval before merging.

Nevertheless, I will be happy to see the regression test from your side :pray: cause there is a chance something was missed while testing desktop.

**Comment by churik** [comment]
@osmaczko 
we'll test it in 1 hour or so, at least need to launch group chat related e2e.

Is that fine?

**Comment by pavloburykh** [comment]
Hi @osmaczko! Thank you for the PR. 

After testing basic flow of new feature I found out that on mobile app that new changes haven't applied:

1. Admin can still add any of his contacts into the group even if they are not mutual ones
2. Members of group still do not have _ability to add its mutual contact to the group_ and _ability to change the name of the group_

Therefore, could you please clarify couple of questions: 

1. By "mutual contacts" we understand the state when User 1 added to contacts User 2 and User 2 in its turn added User 1 to his contacts too. In case if User 2 hasn't added User 1 to contacts those users are not considered to be mutual contacts. Is it correct? 

2. Is it possible that some changes should be also implemented on status react side in order your status go changes are applied?

**Comment by osmaczko** [comment]
@pavloburykh thank you for testing.

> Admin can still add any of his contacts into the group even if they are not mutual ones

This is indeed an issue. Wasn't caught on Desktop, because the UI doesn't permit adding non-mutual contacts to group chats. It should be fixed now, could you please retest this case?

> By "mutual contacts" we understand the state when User 1 added to contacts User 2 and User 2 in its turn added User 1 to his contacts too. In case if User 2 hasn't added User 1 to contacts those users are not considered to be mutual contacts. Is it correct?
 
 Correct.
 
 > Members of group still do not have ability to add its mutual contact to the group and ability to change the name of the group
 > Is it possible that some changes should be also implemented on status react side in order your status go changes are applied?
 
 Yes, it is most likely status-mobile UI limitation. Adaptation is required.

**Comment by pavloburykh** [comment]
> 

thanx @osmaczko I will need to re-run e2e tests and perform manual re-test. So it will take some more time.

**Comment by pavloburykh** [comment]
@osmaczko still facing same issue: admin is able to add to the group contact who is not mutual to him.

**Comment by pavloburykh** [comment]
@osmaczko thanx for the fix. PR is ready for merge.

**Pull request closed without merging**
