### PR TITLE
Fix generating build number for mobile builds

### PR DESCRIPTION
**Pull request by jakubgs**
Latest nightly uses development build number `9999`, and it should be a timestamp:
https://status-im.ams3.digitaloceanspaces.com/StatusIm-190117-031340-b51b56-nightly.apk

Changes:
* Move `genBuildNumber` to `prep` method after `make clean` which removes the `BUILD_NUMBER` file
* Adds messages sent to `stderr` to see what's happening for easier debugging

### CODE REVIEW

**Review by mandrigin — APPROVED** [review]

**Comment by mandrigin** [comment]
@jakubgs nice description of this PR: concise and very clear! :star:

**Comment by jakubgs** [comment]
@mandrigin

**Comment by jakubgs** [comment]
Logs from https://ci.status.im/job/status-react/job/prs/job/android/job/PR-7293/2/ show the fix works:
```
00:00:54.973 Build number file found, using: 2019011717
```

<blockquote><div><strong><a href="https://ci.status.im/job/status-react/job/prs/job/android/job/PR-7293/2/">status-react » prs » android » PR-7293 #2 [Jenkins]</a></strong></div></blockquote>

**Comment by mandrigin** [comment]
@jakubgs 
senpai assistant to the sensei - imgur

**Review by rasom — APPROVED** [review]

**Pull request merged**
