### PR TITLE
bug #5265 - transaction history populated only with own transactions

### LINKED ISSUE #5265: Transactions from other account on the same app may appear in transaction history
### User Story

As a user I want correct transaction history shown in all my accounts

### Description

If user has two accounts on the same phone, it is possible that transaction history update is requested, then in the mean time user logs out and logs back in as a different account. Received transactions should not be added to the history of the other account.

*Type*: Bug

#### Expected behavior

Only transactions from the current account are shown

#### Actual behavior

Transactions from the other accounts on the same phone may be shown

### Reproduction

1. Have two accounts A and B
2. Log in to A and create some transactions
3. Open Transaction History and pull to refresh
4. Quickly log out and log in as B
5. Open Transaction history and wait to see A's transactions

Note: it may be easier to reproduce with slow/throttled network

### Solution

Filter out any transaction history responses not related to the current account

### PR DESCRIPTION
**Pull request by goranjovic**
fixes #5265

### Summary:

It was possible for transaction history entries to appear in other accounts on the same device if user logs out and back in (to another account) quickly.

This PR fixes the issue by double checking the account in the callback.

### Steps to test:
see #5265

status: ready

### CODE REVIEW

**Review by yenda — APPROVED** [review]

**Review by mandrigin — APPROVED** [review]

**Comment by flexsurfer** [comment]
maybe better to "kill" all http handlers on logout, because it can be not only for transactions

**Comment by jeluard** [comment]
Right, as @flexsurfer mentioned, can this be addressed more systemically?

**Comment by goranjovic** [comment]
@flexsurfer @jeluard Ok, I like the idea. It's maybe too defensive, but I'd still prefer to keep the check even in that case.

**Comment by goranjovic** [comment]
@jeluard @flexsurfer Created a separate issue for the general solution

**Review by jeluard — APPROVED** [review]

**Comment by asemiankevich** [comment]
i can't repro https://github.com/status-im/status-react/issues/5265 in this PR

**Pull request merged**
