### PR TITLE
[#13444] No unread indicator for messages received after disabling fl…

### LINKED ISSUE #13444: No unread indicator for messages received after disabling flight mode (going back online)
# Bug Report
Unread indicator does not appear for messages which where send to receiver during period of his being offline and received after going back online. 

**Steps:** 

1. Start 1-1 chat between Device 1 and Device 2 
2. Device 1 enables flight mode
3. Device 2 sends message to Device 1
4. Device 1 enters 1-1 chat and closes it while being offline
5. Device 1 disables flight mode and comes back online
6. On Device 1 pay attention if unread indicator appears for message received after disabling flight mode. 

**Actual result:** unread indicator does not appear. Message preview is presented. 

**Expected result:** unread indicator appears for message received after going back online. 

- Status version: nightly 
- Operating System: Android, iOS

https://user-images.githubusercontent.com/97245802/171643126-32fdac9b-cdac-430a-8710-db2eba6d2f19.mp4

[geth.log](https://github.com/status-im/status-react/files/8824461/geth.log)

### PR DESCRIPTION
**Pull request by flexsurfer**
fixes #13444

QA: please check that read messages sync work fine

### CODE REVIEW

**Review by audriu — APPROVED** [review]

**Review by audriu — APPROVED** [review]

**Comment by pavloburykh** [comment]
@flexsurfer thanx for the PR. Please, take a look at following issue

### ISSUE 1 Unread indicator does not disappear for paired Device 1 which has been offline or logouted when messages have been received and read by paired Device 2 

**Steps:** 

1. Recover same account on Device 1 and Device 2 
2. Pair Device 1 and Device 2
3. Start 1-1/group chat with Device 3 or join same public chat 
4. Log out or disable network on Device 2 
5. From Device 3 send messages to 1-1/group or public chat
6. Read messages on Device 1
7. Login or enable network on Device 2
8. Pay attention if unread indicator presented on Device 2 

**Actual result:** unread indicator is still present on Device 2 although messages have been already read on paired Device 1

**Expected result:** no unread indicator is present on paired device if messages have already been read. 

https://user-images.githubusercontent.com/97245802/173830264-27adbb9f-e050-4218-bb7b-de73bfbb9511.mp4

[geth.log](https://github.com/status-im/status-react/files/8909396/geth.log)

**Comment by flexsurfer** [comment]
thanks @pavloburykh implemented another solution, we need to retest this PR

**Comment by pavloburykh** [comment]
@flexsurfer still reproducing [ISSUE 1](https://github.com/status-im/status-react/pull/13474#issuecomment-1156429997l) with one difference in behaviour: 

Most of the time, indicator shows 1 unread message regardless of how many messages where sent and read on paired device before (can be observed on video below). Although sometimes indicator still shows the exact amount of messages that have been received and read. 


https://user-images.githubusercontent.com/97245802/174628829-7a141d28-3f33-4a2c-a120-b3a17d3ce218.mp4

logs form Android are attached

[geth.log](https://github.com/status-im/status-react/files/8941653/geth.log)

**Comment by flexsurfer** [comment]
thanks @pavloburykh actually there are no changes for sync functionality, so could you pls try to replicate it in latest nightly ?

**Comment by pavloburykh** [comment]
> thanks @pavloburykh actually there are no changes for sync functionality, so could you pls try to replicate it in latest nightly ?

Behaviour on nightly is pretty weird. Before logging this issue here I've tried to replicate it on nightly but failed, that's why considered it to a PR issue. 

Now I have retested it on latest nightly again and found out that it's been replicated but not all the time. I attached video from nightly which demonstrates that the bug can replicated on nightly but the same time it is not reproducible every time. 

On the other hand, I am replicating this bug on current PR build 10 out of 10. 

I've check this issue on other PR builds and it's also been replicated 10 out of 10. The only thing that differs in behaviour of current PR and other PR builds is that in current PR most of the time indicator shows 1 unread message regardless of how many messages where sent and read on paired device before. 

Anyway, as I have managed to replicate the bug on nightly and others PR builds I will log a separate issue for that. 

@flexsurfer thank you. 


https://user-images.githubusercontent.com/97245802/174761099-64a41a73-3746-4d57-9c52-72bd287e259d.mp4

**Comment by flexsurfer** [comment]
i think i can try to fix "1" in this PR

**Comment by pavloburykh** [comment]
> i think i can try to fix "1" in this PR

Thanx @flexsurfer, it would be great.

**Comment by flexsurfer** [comment]
@pavloburykh should be fixed now

**Comment by pavloburykh** [comment]
@flexsurfer thanx for the fix. Ready for merge.

**Pull request closed without merging**
