### PR TITLE
chore: update status-go

### PR DESCRIPTION
**Pull request by igor-sirotin**
Test this breaking change in status-go: https://github.com/status-im/status-go/pull/5810

### CODE REVIEW

**Comment by igor-sirotin** [comment]
@churik @pavloburykh can you please give it a quick test? We need to ensure that URL unfurling is working fine.
I removed an old deprecated `urls` package and it's a breaking change. According to the code, it's not used in mobile and desktop already, but worth testing just in case.

And https://github.com/status-im/status-go/pull/5810 needs to merged ASAP, as all tests in status-go are failing now 🫠

**Comment by churik** [comment]
Any commit, starting from https://github.com/status-im/status-go/commit/e6a2f0afd64c54d60df3eaa675209560f785eb80 to https://github.com/status-im/status-go/commit/771a0c356295469577eb80e0e9428b89fbef976e can be the reason of the following issues: 
1)  the pairing works slower as far as I can see in comparison with release (cannot prove it though, but especially it can be seen on contact requests when Alice sends a message to Bob and Bob has 2 devices)
2) likely https://github.com/status-im/status-go/commit/060918bcd4acb88f5bcb0aa4ad4eda703e602f84 caused another regression 

**Steps:**
- try to mute chat for 7 days or until they will be unmuted
**Expected results:**
- toasts and texts on menu are changed accordingly
**Actual results:**
image
image

Video (first demonstrating in nightly, then  in Pr build)

https://github.com/user-attachments/assets/db9c72e6-db51-49b6-95fc-b8f13baacbcc

**Comment by churik** [comment]
No regression is found related to url previews, the app behaves the same in comparison with 2.30.
@igor-sirotin

**Comment by igor-sirotin** [comment]
> 2. likely [status-im/status-go@060918b](https://github.com/status-im/status-go/commit/060918bcd4acb88f5bcb0aa4ad4eda703e602f84) caused another regression

oops, this indeed will cause a regression 🙁 And I assume we're facing it on desktop too.

`MuteFor24Hr` should have been added to the end of the enum, not to break current enum values.
I was the one to approve and merge, and I didn't think about this 🤦 

@caybro can you please take care of the desktop side, if it's not updated yet?

I've write it down to remember in the future: [Code-smell #7: Inserting enums](https://www.notion.so/Code-smell-7-Inserting-enums-627948a9f1ff4a27b5a4d2789fd2c595)

**Comment by igor-sirotin** [comment]
@churik apart from this, is it fine to merge https://github.com/status-im/status-go/pull/5810 now?

**Comment by caybro** [comment]
> > 2. likely [status-im/status-go@060918b](https://github.com/status-im/status-go/commit/060918bcd4acb88f5bcb0aa4ad4eda703e602f84) caused another regression
> 
> oops, this indeed will cause a regression 🙁 And I assume we're facing it on desktop too.
> 
> `MuteFor24Hr` should have been added to the end of the enum, not to break current enum values. I was the one to approve and merge, and I didn't think about this 🤦
> 
> @caybro can you please take care of the desktop side, if it's not updated yet?
> 
> I've write it down to remember in the future: [Code-smell #7: Inserting enums](https://www.notion.so/Code-smell-7-Inserting-enums-627948a9f1ff4a27b5a4d2789fd2c595)

Yeah we need this PR merged: https://github.com/status-im/status-desktop/pull/14118 Anything else?

**Comment by igor-sirotin** [comment]
oh, since https://github.com/status-im/status-desktop/pull/14118 not merged yet, maybe we can postpone it and change status-go?
We could move the `MuteFor24Hr` to the end of the enum, then it won't be a breaking change.
@caybro wdyt?

**Comment by caybro** [comment]
> oh, since [status-im/status-desktop#14118](https://github.com/status-im/status-desktop/pull/14118) not merged yet, maybe we can postpone it and change status-go? We could move the `MuteFor24Hr` to the end of the enum, then it won't be a breaking change. @caybro wdyt?

Yeah, as you wish; I'll just have to adjust the desktop PR afterwards, because currently it looks like:
```qml
enum MutingVariations {
        For15min = 1,
        For1hr = 2,
        For8hr = 3,
        For24hr = 4,
        For1week = 5,
        TillUnmuted = 6,
        For1min = 7,
        Unmuted = 8
    }
```

which matches the status-go counterpart

**Comment by igor-sirotin** [comment]
> I'll just have to adjust the desktop PR afterwards

Alright, I'll open a status-go PR for this then. Please don't merge the desktop PR mean while then 🙂

**Comment by churik** [comment]
@igor-sirotin tell me if you plan to fix it , when it is ready, I'll do retest, thanks!

**Comment by igor-sirotin** [comment]
> @igor-sirotin tell me if you plan to fix it , when it is ready, I'll do retest, thanks!

The fix is on the way: https://github.com/status-im/status-go/pull/5813
But I won't be able to pass tests without merging https://github.com/status-im/status-go/pull/5810 😄 🤦 

Let me go this way:
- I will merge https://github.com/status-im/status-go/pull/5810, because it's blocking tests for all PRs
- wait for https://github.com/status-im/status-go/pull/5813 to pass status-go tests
- update this PR to point to https://github.com/status-im/status-go/pull/5813 
- ensure the issue is resolved

I will be in short contact if something gets broken.

-----

Also, I'm not sure what's wrong with this:
> the pairing works slower as far as I can see in comparison with release

**Comment by churik** [comment]
> the pairing works slower as far as I can see in comparison with release

I don't know either, there is no way to identify the responsible commit right now, we'll try to investigate later in nightly builds

**Comment by igor-sirotin** [comment]
@churik updated this PR to point to https://github.com/status-im/status-go/pull/5813.
The `mute` issue should be fixed now

**Comment by churik** [comment]
Thank you @igor-sirotin , the issue is fixed!

**Comment by churik** [comment]
can you may be bump the version in mobile as well?

**Comment by igor-sirotin** [comment]
@churik rebased to latest `develop` and updated status-go to `v0.185.0` 👌

**Review by alwx — APPROVED** [review]

**Review by shivekkhurana — APPROVED** [review]

**Comment by igor-sirotin** [comment]
image

oops @Parveshdhull I also rebased. Not sure what's the state now.
Taking my hands off this PR then, not to interfere 🙂

**Pull request merged**
