### PR TITLE
Testing mailserver refactor in status-go

### PR DESCRIPTION
**Pull request by vitvly**
Related status-go PR: https://github.com/status-im/status-go/pull/5420

### CODE REVIEW

**Comment by pavloburykh** [comment]
Hey @vitvly!

Last [run](https://github.com/status-im/status-mobile/pull/20622#issuecomment-2205760361) has failed because community failed to be fetched after user follows community link.  

I cannot say for sure if this is Waku issue (which we are facing quite often) or PR related. 

Attaching logs below so you can check. 

[TestCommunityMultipleDeviceMerged_geth1 (3).log.zip](https://github.com/user-attachments/files/16084130/TestCommunityMultipleDeviceMerged_geth1.3.log.zip)

Meanwhile, I will trigger another e2e run.

**Comment by pavloburykh** [comment]
@vitvly I have performed re-run but I see the same issues when community failed to be fetched as I described [here](https://github.com/status-im/status-mobile/pull/20622#issuecomment-2205929420)

In addition to this, in [latest](https://github.com/status-im/status-mobile/pull/20622#issuecomment-2206076833) run 1 testsuite failed because data from Waku [has not been restored](https://app.eu-central-1.saucelabs.com/tests/d4729ea834834f8e9bafdb1667fcae54?auth=c76efbb66eb15481aa7139aa7b0c58e0#327) for user who restored account via seedphrase. 

Attaching logs below

[test_restore_multiaccount_with_waku_backup_remove_switch_geth1 (1).log.zip](https://github.com/user-attachments/files/16086628/test_restore_multiaccount_with_waku_backup_remove_switch_geth1.1.log.zip)

**Comment by pavloburykh** [comment]
@vitvly thankks for the PR. e2e failures are not PR related. Ready for merge.

**Comment by vitvly** [comment]
Thank you, merged status-go PR, closing this one.

**Pull request closed without merging**
