### PR TITLE
Bump version to 0.9.22

### LINKED ISSUE #5060: Bump version to 0.9.22
### Description

*Type*: Bug

*Summary*: Bump version name in Profile screen from 0.9.21 to 0.9.22. It's done in https://github.com/status-im/status-react/blob/release/0.9.22/VERSION. See PR with previous bumps  like https://github.com/status-im/status-react/pull/4812

### Reproduction

- Open Status
- Open Profile
- See version name

### Additional Information
* Status version: 0.9.22
* Operating System: Android, iOS

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/status-im/status-react">status-im/status-react</a></strong></div><div>status-react - a free (libre) open source, mobile OS for Ethereum</div></blockquote>

### PR DESCRIPTION
**Pull request by lukaszfryc**
fixes #5060 

status: ready

### CODE REVIEW

**Review by jakubgs — APPROVED** [review]
We should remember to also update `CHANGELOG.md`, but that can be done separately.

**Review by janherich — APPROVED** [review]

**Comment by lukaszfryc** [comment]
@jakubgs yeah, changelog changes are here: https://github.com/status-im/status-react/pull/5061

**Comment by lukaszfryc** [comment]
@jakubgs could you check why the jenkins build failed? https://jenkins.status.im/blue/organizations/jenkins/status-react%2Fpull%20requests/detail/PR-5062/1/

```
+ git rebase origin/develop

fatal: Needed a single revision

invalid upstream origin/develop

script returned exit code 1
```

<blockquote><div><strong><a href="https://jenkins.status.im/blue/organizations/jenkins/status-react%2Fpull%20requests/detail/PR-5062/1/">Jenkins</a></strong></div></blockquote>

**Comment by jakubgs** [comment]
It appears the repo for this PR build was set to fetch only a specific branch:
```
 jenkins$ git config --get remote.origin.fetch
+refs/heads/release/0.9.22:refs/remotes/origin/release/0.9.22
```
Not sure why that is yet, let me investigate.

**Comment by jakubgs** [comment]
Yeah, so it appears you've created your branch by forking from `origin/release/0.9.22` instead of from `develop`. That's why Jenkins can't fetch the `develop` branch, because `remote.origin.fetch` is set to:
```
+refs/heads/release/0.9.22:refs/remotes/origin/release/0.9.22
```
And hence cannot rebase from `develop`.

**Comment by lukaszfryc** [comment]
@jakubgs I don't want to branch of `origin/develop` since there are new commits that should not be included in the `release/0.9.22`. What do you suggest to do?

**Comment by lukaszfryc** [comment]
@jakubgs can I just merge it using the script?

**Comment by jakubgs** [comment]
It should work using the script just fine.

**Pull request merged**
