### PR TITLE
fix: increase numbered keyboard touchable area

### LINKED ISSUE #18205: Buttons lack sensitivity on send page, resulting in difficulty selecting values when tapped on the edge
Follow up for https://github.com/status-im/status-mobile/pull/17786

### Steps:
1. Open send to page (Flow to open 'send to' page: Open eth address -> tap 'send' -> tap 'my accounts tab' -> tap on exist account -> tap any asset)
2. Tap the number buttons not precisely on the button to select the value to send

### Actual result:
When tapping the buttons precisely on the edge, the value does not get inputted. This reveals a lack of sensitivity in the buttons, causing difficulty in selecting the desired value.

https://github.com/status-im/status-mobile/assets/52490791/c1ac8663-29df-4494-85a2-cf245c601317

### Expected result:
The buttons should be more responsive to inputs when tapped on the edge

Example numbers input on the send page on Binance:

https://github.com/status-im/status-mobile/assets/52490791/1564084e-5d8e-4f02-bd96-a2ec5731c9d5

### PR DESCRIPTION
**Pull request by briansztamfater**
fixes #18205

### Summary

This PR increases touchable area of keys in numebered keyboard to improve responsiveness of touches

#### Platforms

- Android
- iOS

### Steps to test

- Open Status
- Log in
- Open wallet, go to send tokens
- Select a token, reach to input amount screen
- Verify responsiveness of touches in numbered keyboard

status: ready

### CODE REVIEW

**Review by J-Son89 — APPROVED** [review]

**Review by ibrkhalil — APPROVED** [review]

**Review by OmarBasem — APPROVED** [review]

**Review by smohamedjavid — APPROVED** [review]

**Review by ulisesmac — APPROVED** [review]

**Comment by mariia-skrypnyk** [comment]
Hi @briansztamfater ! Nice to meet you and thanks for your PR:)

I am faced with a crush that blocks me in my testing. Please, take a look on it's details here:

**ISSUE 1:** [Android/iOS] app crushes when user tries to select any asset

Steps: 

1. Open wallet
2. Tap + to create one more account
3. Tap on your first Eth account
4. Open send to page (Flow to open 'send to' page: Open eth address -> tap 'send' -> tap 'my accounts tab' -> tap on created at step 2 account -> tap any asset)

Actual result: app crushed
photo_2024-01-03_12-41-29
I've also attached android logs below. 
[Status-debug-logs.zip](https://github.com/status-im/status-mobile/files/13818569/Status-debug-logs.zip)

**Comment by briansztamfater** [comment]
Hi @mariia-skrypnyk! Thanks for assigning this issue. About the error you mentioned, there is another PR that tries to fix the error: https://github.com/status-im/status-mobile/pull/18326

So probably we can give that PR priority once approved.

**Comment by mariia-skrypnyk** [comment]
> Hi @mariia-skrypnyk! Thanks for assigning this issue. About the error you mentioned, there is another PR that tries to fix the error: #18326
> 
> So probably we can give that PR priority once approved.

Thanks Brian! 
So I'll wait https://github.com/status-im/status-mobile/pull/18326 to be reviewed and merged and then I will retest current PR :)

**Comment by briansztamfater** [comment]
> > Hi @mariia-skrypnyk! Thanks for assigning this issue. About the error you mentioned, there is another PR that tries to fix the error: #18326
> > So probably we can give that PR priority once approved.
> 
> Thanks Brian! So I'll wait #18326 to be reviewed and merged and then I will retest current PR :)

@mariia-skrypnyk The fix was merged and I just rebased this PR so hopefully we can continue testing this one 🙏

**Comment by mariia-skrypnyk** [comment]
> > > Hi @mariia-skrypnyk! Thanks for assigning this issue. About the error you mentioned, there is another PR that tries to fix the error: #18326
> > > So probably we can give that PR priority once approved.
> > 
> > 
> > Thanks Brian! So I'll wait #18326 to be reviewed and merged and then I will retest current PR :)
> 
> @mariia-skrypnyk The fix was merged and I just rebased this PR so hopefully we can continue testing this one 🙏

Thanks @briansztamfater for merge and rebase!
I've checked your fix: everything is fine and it can be merged now!

**Pull request merged**
