### PR TITLE
bug #4983 - a few workarounds for blinking token transactions in history

### LINKED ISSUE #4983: Optimize merging of transaction and transfer info
### User Story

As a user I want the history of my transactions and token transfers to be clear and not confusing.

### Description

We can cover the most common special cases of #4556 (e.g regular token send via `transfer` method)
using a few tricks:

- generate a mock unconfirmed token transfer immediately after Send (the way we do with transactions)
- merge the new pieces of info more selectively (so that there is no flickering between transaction and transfer info)

*Type*: Improvement

#### Expected behavior

When minting tokens from Simple Dapp, there will first be a 0 ETH transaction, that will eventually get updated to an incoming token transfer (e.g. HND) and after that will remain a token transfer. Some data may still get updated (e.g. spent gas info or confirmation count). The same behavior should occur for any other token transfer that happens in a dapp, e.g. exchanges.

When sending tokens to someone (whether from chat or from wallet), there will first be an unconfirmed token transaction that will eventually get updated with remaining pieces of info (spent gas, confirmations). This history entry will initially be and then remain displayed as a token transfer and will not flicker back and forth between ETH and token.

When receiving tokens from someone, the behavior will remain the same as before this change - it will appear with token transfer data alone, plus the confirmation count (i.e. nothing about spent gas).

#### Actual behavior

When minting tokens or sending to someone, the transaction appears as a 0 ETH transaction and then flickers back and forth between ETH and token.

### Reproduction

- Mint tokens and check transaction history
- Send tokens and check transaction history

### PR DESCRIPTION
**Pull request by goranjovic**
fixes #4983 

### Summary:

Adds a few workarounds to prevent blinking token transactions in transaction history:
- improves entry merging
- creates an unconfirmed transaction entry immediately after sending

### Steps to test:
see #4983 

status: ready

### CODE REVIEW

**Review by janherich — APPROVED** [review]

**Review by flexsurfer — APPROVED** [review]

**Comment by asemiankevich** [comment]
@goranjovic some things i noticed:

1. it is blinking a bit when i send a token txn and then open history 
2. also `sent` tokens blink a bit when i refresh history
3. when i send 0 tokens transaction has some scary notice `ERC-20 Token Transfer Error (unable to locate corresponding Transfer event log), check with sender. ` 
https://ropsten.etherscan.io/tx/0xd70864a53ea9289e8527cbc5ede54b121d3926a663935b303a9098a86b0bda34 

Not sure if the blinking should be gone completely or just get better at some point in this PR? 

<blockquote><div><strong><a href="https://ropsten.etherscan.io/tx/0xd70864a53ea9289e8527cbc5ede54b121d3926a663935b303a9098a86b0bda34">Ropsten Transaction 0xd70864a53ea9289e8527cbc5ede54b121d3926a663935b303a9098a86b0bda34</a></strong></div><div>Ropsten (ETH) detailed transaction info for 0xd70864a53ea9289e8527cbc5ede54b121d3926a663935b303a9098a86b0bda34</div></blockquote>

**Comment by goranjovic** [comment]
@asemiankevich 

1 and 2 - double checked - this is as good as it gets with these workarounds 
3 - this one #4877

Also, I just rebased.

**Comment by asemiankevich** [comment]
okay thank you @goranjovic !

**Comment by asemiankevich** [comment]
lets merge this with known (discussed) limitations

**Comment by goranjovic** [comment]
Too bad we don't have :thisisfine: emoji here!

**Pull request merged**
