### PR TITLE
[#17873] - Add support to display token images in token gated communities

### LINKED ISSUE #17873: Token icons are not fetched in token gated communities' requirements description
Followup of https://github.com/status-im/status-mobile/pull/17799 cc @ilmotta 

**Steps:** 

1. Open token gated community screen
2. Pay attention if token icon is fetched for token value requirement

**Actual result:** token icons are not fetched

photo_2023-11-10 14 19 05

**Expected result:** token icons are fetched

Communities for Mobile – Figma 2023-11-10 14-16-25

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by ulisesmac**
fixes #17873 

### Summary

This PR add support to display token images received  in token gated communities.

## Review notes and QA notes

I tested it locally passing some images. but I couldn't find a way to get a community that is returning token images from status-go.

Example:
image

This community has 4 tokens as requirement, but we are not receiving the images from status-go, we are just looking at the images stored in our app and showing them.

We only have stored images for ABYSS and XPA so those are the only ones showed.

### Then, what is this PR doing?

If we receive community token images from status-go, they'll be properly displayed.

It'll be highly appreciated if you can share a link to a community that token images associated.

#### Platforms

- Android
- iOS

### Steps to test

- Open Status
- Go to communities tab
- Open a token gated community -> three dots -> view token requirements

status: ready

### CODE REVIEW

**Comment by ulisesmac** [comment]
@mohsen-ghafouri  @ilmotta 
 I was thinking that maybee the `token-images` key in the `:community` re-frame path is designed to the "mint owner token"  feature, since that's a token with a custom image.
 
 Do you guys can give some clarity on this?
 
 thanks!

**Review by mohsen-ghafouri — APPROVED** [review]
Great work @ulisesmac, yes token-> img-src is come from communityDescription- CommunityTokensMetadata and it's just for custom asset and collectibles(not sure). 

for the global assets as you already implemented we read token icon from local resources.

there are some open issues about sharing a community so I couldn't test it.

**Comment by ulisesmac** [comment]
> Great work @ulisesmac, yes token-> img-src is come from communityDescription- CommunityTokensMetadata and it's just for custom asset and collectibles(not sure).
> 
> for the global assets as you already implemented we read token icon from local resources.
> 
> there are some open issues about sharing a community so I couldn't test it.

@ilmotta @mohsen-ghafouri 
Then maybe this PR just needs QA to test that tokens are displayed as in develop to get merged?

Or @ilmotta  maybe you have a link to a community showing custom tokens?

**Review by ajayesivan — APPROVED** [review]
LGTM!

**Comment by ajayesivan** [comment]
@ulisesmac QA team will be able to help you with a community with minted tokens.

**Comment by ulisesmac** [comment]
> @ulisesmac QA team will be able to help you with a community with minted tokens.

Thanks @ajayesivan !  :+1:

**Review by ilmotta — APPROVED** [review]

**Comment by VolodLytvynenko** [comment]
Hi @ulisesmac could you please resolve conflicts and rebase the current PR? Thanx!

**Comment by ulisesmac** [comment]
> Hi @ulisesmac could you please resolve conflicts and rebase the current PR? Thanx!

Hey @pavloburykh, it has been updated!

**Comment by qoqobolo** [comment]
Hey @ulisesmac, thanks for your work!
I was able to test it with custom (minted) community tokens and that seems to work!
 
image


As you can see in the screenshot, some token icons are not fetched indeed, as you mentioned in the description. But there are no icons of these tokens on the Desktop either.
Do I understand correctly that this is expected and we can go with it for now?

**Comment by ulisesmac** [comment]
@qoqobolo Thanks for testing! :)

> As you can see in the screenshot, some token icons are not fetched indeed, as you mentioned in the description. But there are no icons of these tokens on the Desktop either. Do I understand correctly that this is expected and we can go with it for now?

Yes, exactly, that is expected!

Just to make it clear:

- We have some token images stored within the app.
- Sometimes status-go returns a token name we don't have images for, then we show an ugly placeholder (we're waiting for designers to create a nice one).
- When status-go returns token images (not just token names), we are able to show them (it's what this PR does for communities)
- it seems currently status-go only returns images for custom minted tokens.


is it ready to be merged?

**Comment by qoqobolo** [comment]
@ulisesmac thanks for the clarification and your work!
Yes, PR can be merged.

**Pull request merged**
