### PR TITLE
remove navigate-to-nav2 event

### LINKED ISSUE #15437: Navigation and theme refactoring
### Summary
- Remove `navigate-to-nav2` (we don't need this anymore, as this was created when we had two namespace)
- Mostly themes are changed on the root level, So apart from the system theme change calls and changes from appearance profile, we can store all those in roots file or something, so easier to change and track (still exploring)
(and then change theme in init-root function itself `(theme/set-theme (:root-id roots/theme)`)

### PR DESCRIPTION
**Pull request by Parveshdhull**
partially fixes: https://github.com/status-im/status-mobile/issues/15437

### Testing
Please make sure that shell cards are working same as develop

status: ready

### CODE REVIEW

**Review by flexsurfer — APPROVED** [review]

**Comment by Parveshdhull** [comment]
Looks like half of e2e tests are failed, but not sure why :(
cc: @status-im/mobile-qa

**Comment by churik** [comment]
@Parveshdhull 
the reason for failed e2e is that on tapping "View" on a community link the user got an error:
image, therefore couldn't join the community.

Logcat: 
[logcat (9).log](https://github.com/status-im/status-mobile/files/11046882/logcat.9.log)
 Video: https://app.eu-central-1.saucelabs.com/tests/2e7363834cc64e409efc6095c2ff1f96?auth=f87f79ab9eac3cd7882943196e80f495#70

**Comment by Parveshdhull** [comment]
Hi @churik, Thank you for checking the issue, it should be fixed now.
Also on clicking the link, creating a community, etc. we were going to old community designs, now replaced them too with new community designs so that shell cards will be also added even when the community opened after creating or clicking on the link.
(Tests might need to be modified)
Please let me know if anything is not working as expected.

**Comment by Parveshdhull** [comment]
Please don't test yet, I am making a small change where user will always land on communities tab on creating account as in designs.

**Comment by Parveshdhull** [comment]
Hi @flexsurfer,
Now the user will see the communities tab on creating an account as same as Figma.
Please let me know if anything needs to be changed.

Changes: https://github.com/status-im/status-mobile/pull/15454/commits/eeec24f21e8b1db910db7c9f9a239b5165b38892

**Comment by Parveshdhull** [comment]
PR is ready for testing

### Testing Notes & Changes
- Please make sure the shell card's lifecycle is the same as the develop
- All community flows are using the new community screen. (Example clicking on shared community, opening new community after creation) 
- User lands on the communities tab on creating a new account
- On login or reopenign of the app, the same tab is opened as last (Note: Different account doesn't have separate state, currently they all share. So if one account was on the wallet, another will also land on wallet)

**Comment by churik** [comment]
tests aligned in https://github.com/status-im/status-mobile/pull/15460, waiting for results

**Comment by churik** [comment]
@Parveshdhull ready to be merged

**Pull request merged**
