### PR TITLE
Fixes #709 "Your phone appears to be ROOTED" message shown less often.

### LINKED ISSUE #709: "Your phone appears to be ROOTED" message nuisance.
I think it's important to have the pop-up message appear, but because it appears every time Status is opened, it will start to get pretty annoying pretty fast.
I suggest changing the message to appear for the initial start of the app and then every Nth time Status is opened, ie. every twentieth/fiftieth time just to remind people that this can be a security issue. 
The message will get especially annoying when people use Status daily and open the app possibly many times a day.

### PR DESCRIPTION
**Pull request by ghost**
[comment]: # fixes #709 

### Steps to test:
- Open Status on a rooted device.
- Observe "Your phone appears to be ROOTED" message (always shows first time)
- Click continue and agree with warnings
- Restart the App
- Observe the "Your phone appears to be ROOTED" message shown only 5% of the time.

status: ready

[comment]: # reused these changes. https://github.com/jiriknesl/status-react/commit/753b0449e54fa2b993cc48fc1a4a317edcf27c15

### CODE REVIEW

**Comment by yenda** [comment]
Thanks for your contribution ! So if I understand correctly this will show the warning with a probability of 5% everytime you run the app ?

**Comment by ghost** [comment]
Yes, and first time always.

**Comment by jeluard** [comment]
@poiga Can you add a comment describing this logic? Also it looks like you added a second confirmation?

**Comment by ghost** [comment]
Do you mean comment the code? Yes I will.
Do you think the second confirmation is a good idea?

**Comment by jeluard** [comment]
@poiga I'd rather not add a second confirmation (whole point is to reduce the annoyance in the first place :))

**Comment by asemiankevich** [comment]
I have tested this with Gennymotion and here are the thoughts:
1. Not sure why we need second confirmation? @poiga @yenda @jeluard 
2. This merge will impact autotests so cc @antdanchenko

**Comment by ghost** [comment]
I have removed the second confirmation.

**Comment by asemiankevich** [comment]
@poiga i will move the PR back to `In Progress` then. Please, add changes as discussed

**Comment by ghost** [comment]
@asemiankevich I can see your comment "will move the PR back to In Progress" means that you are using some system outside of Github?

**Comment by asemiankevich** [comment]
@poiga just changed the pipline for current issue since it requires additional input from your side. Once ready you can change the pipline back to `ready-for-testing`

**Comment by jeluard** [comment]
@poiga Yes this is done in Zenhub

**Comment by poiga** [comment]
Could someone add me to the Zenhub please? :)

**Comment by ghost** [comment]
@asemiankevich "you can change the pipline back to ready-for-testing" - but board tells me: "To edit this Board, you must have write permissions for this repo."
Still looks like this feature only for team members.

**Comment by yenda** [comment]
I moved it.

Thanks for your contributions and your patience @poiga 

Can you edit your first comment and put ready instead of wip because it will confuse reviewers otherwise.

**Comment by oskarth** [comment]
> Once ready you can change the pipline back to ready-for-testing - @asemiankevich 


@asemiankevich  Moved to ready for testing

**Review by yenda — APPROVED** [review]

**Review by oskarth — APPROVED** [review]

**Pull request merged**
