### PR TITLE
[WIP] slower bottom nav animation

### PR DESCRIPTION
**Pull request by rasom**

### CODE REVIEW

**Comment by rasom** [comment]
@churik does it look better? :)

**Comment by churik** [comment]
well, it looks as animation now but I don't know what is the reason to put bottom nav above keyboard and then hide. Probably we need another opinion about this?
I would prefer to remove this animation if we have such a possibility to do this.

**Comment by rasom** [comment]
@churik , you can read starting from this comment https://github.com/status-im/status-react/pull/7483#issuecomment-463920754

**Comment by churik** [comment]
thanks, OK, I'll close an issue then.
No need for PR I believe, no much difference - probably after a while we will get more feedback.
Thanks for a try!

**Pull request closed without merging**
