### PR TITLE
[FIX #2530] Create `catalog` variable on client-side.

### LINKED ISSUE #2530: Create `catalog` cell variable on status-react side
### User Story

As a developer, I'd like to move creating `catalog` variable from status-go to status-react, as status-go has no knowledge about it and why it is required.

### Description

*Type*: Feature

*Summary*: In status-go, during cell initialization, the following code is executed:
```js
var catalog = JSON.stringify(_status_catalog);
```

status-go does not know about `_status_catalog`, thus, it should not rely on it.

#### Expected behavior
There is no change in cell initialization after executing that JS fragment on status-react side.

#### Actual behavior
It is correct.

### Solution
`catalog` variable should be created on status-react side using [`ExecuteJS` binding](https://github.com/status-im/status-go/blob/develop/lib/library.go#L343-L346).

Please, comment on https://github.com/status-im/status-go/issues/450 after resolving.

### Additional Information
* Status version: All
* Operating System: Android and iOS

### PR DESCRIPTION
**Pull request by mandrigin**
### Summary:

Addresses https://github.com/status-im/status-react/issues/2530

This is my second attempt to prepare the client codebase to the go library refactoring mentioned in [status-go#450](https://github.com/status-im/status-go/issues/450).
This time `executeJS` is not exposed.

### Review notes:
Backward compatible, tested on [`status-go/develop`](https://github.com/status-im/status-go/commit/cbd05535ae72e96f38340d5245b075e06b0cf96c) and [`status-go/PR489`](https://github.com/status-im/status-go/pull/489)

### Steps to test (UPDATED):
- Open Status
- Create an account
- Expect `/password` and other `/`-commands to show up and work

status: done

### CODE REVIEW

**Review by oskarth — APPROVED** [review]

**Review by oskarth — COMMENTED** [review]
Can we pull out the `str` form into its own fn?

**Comment by mandrigin** [comment]
@oskarth thanks for reviewing!

are you suggesting something like this?

```clj
(defn- append-catalog-init [js]
     (str js "\n" "var catalog = JSON.stringify(_status_catalog); catalog;"))

(call-module #(.parseJail status
                          bot-id
                          (append-catalog-init file)
                          callback)))
```

**Review by janherich — APPROVED** [review]

**Comment by rasom** [comment]
```
Caused by: clojure.lang.ExceptionInfo: src/status_im/native_module/impl/module.cljs [line 263, col 1] Unexpected EOF while reading item 18 of list, starting at line 123 and column 1. {:type :reader-exception, :ex-kind :eof, :file "src/status_im/native_module/impl/module.cljs", :line 263, :col 1}
```
Looks like one parenthesis is missing

**Review by rasom — DISMISSED** [review]
see comment above

**Comment by mandrigin** [comment]
@rasom is this issue reproducible while compiling?

sorry for delays, was away for the Christmas holiday.

**Comment by mandrigin** [comment]
@rasom can I see the error message behind CI? It builds on my machine...
```
Figwheel: Starting server at http://0.0.0.0:3449
Figwheel: Watching build - ios
Compiling "target/ios/app.js" from ["react-native/src" "src" "env/dev"]...
Successfully compiled "target/ios/app.js" in 68.544 seconds.
Figwheel: Watching build - android
Figwheel: Cleaning build - android
Compiling "target/android/app.js" from ["react-native/src" "src" "env/dev"]...
WARNING: Protocol IFn implements method -invoke with variadic signature (&) at line 61 target/android/reagent/impl/util.cljs
Successfully compiled "target/android/app.js" in 42.669 seconds.
Figwheel: Starting nREPL server on port: 7888
re-frisk server has been started at http://localhost:4567
nREPL server started on port 60636 on host 127.0.0.1 - nrepl://127.0.0.1:60636
REPL-y 0.3.7, nREPL 0.2.12
Clojure 1.9.0-alpha17
Java HotSpot(TM) 64-Bit Server VM 1.8.0_152-b16
```

**Comment by rasom** [comment]
You are right, that was some local problem

**Comment by churik** [comment]
# Tests
## Install:
- console chat - /password, /faucet, /debug, /phone, /confirmation-code, web3.eth.syncing, web3.isConnected, /browse
- 1-1 chat - /send, /request, /browse, /location
- group chat - /send, /request, /browse, /location
- public chat -  /browse, /location
- chat DApp - /browse
## Upgrade:

### before: 
- 1-1 chat - /send, /request, /browse, /location
- group chat - /send, /request

### after
-  1-1 chat - /send, /request, /browse, /location
- group chat - /send, /request, /browse, /location

**Pull request merged**
