### PR TITLE
Granting profile access to a DApp gives access to any DApp with same host [#6585]

### LINKED ISSUE #6585: Granting profile access to a DApp gives access to any DApp with same host
### User Story

As a user, I want to know that my data is granted only to the DApps I specify, so that I have control over my privacy and information. 

### Description

*Type*: Bug

*Summary*: Currently, requests for a user's contact code or Ethereum provider come from the hosting service, typically `ipfs.infura.io/...`. 

Once the user grants permission for their data, the permission is given to _any_ DApp handled by that same host.

#### Expected behavior
User grants permission on a case-by-case basis, as triggered by the DApp. 

An improvement would be to grant permission for a specific DApp—not for any DApp hosted by IPFS/Infura.

#### Actual behavior
My contact code is shared with any `ipfs.infura` DApp once I grant access once.

### PR DESCRIPTION
**Pull request by flexsurfer**
fixes #6585

### CODE REVIEW

**Review by jeluard — APPROVED** [review]

**Review by goranjovic — APPROVED** [review]

**Comment by goranjovic** [comment]
@flexsurfer Looks like unit tests are failing:

```
FAIL in (url-host-check) (cljs/test.cljs:476:9)
Extract host/domain from URL Blank domainlocalhost
expected: (nil? (http/url-host "localhost:3000/testing"))
  actual: (not (nil? "localhost"))

FAIL in (url-host-check) (cljs/test.cljs:476:9)
Return nil for Invalid URL Bad scheme
expected: (nil? (http/url-host "invalid//status.im/testing"))
  actual: (not (nil? "invalid"))

FAIL in (url-host-check) (cljs/test.cljs:476:9)
Return nil for Invalid URL No scheme
expected: (nil? (http/url-host "status.im/testing"))
  actual: (not (nil? "status.im"))
```

**Comment by flexsurfer** [comment]
@goranjovic yes, fixed

**Comment by asemiankevich** [comment]
https://github.com/status-im/status-react/issues/6585#issuecomment-438184029

**Comment by asemiankevich** [comment]
seems ens dapp does not support web3 opt in requests. This is not a problem of this PR rather than dapp itself. Lets merge this PR.

**Comment by flexsurfer** [comment]
@asemiankevich i made changes, there was a bug, it shows domain from the previous url, for vote.status.im it should show ipfs.infura.io

**Comment by flexsurfer** [comment]
hm wondering why my PR includes commit from Jan

**Comment by yenda** [comment]
I merged his PR before yours but it failed because is not part of the org anymore and then when I merged yours the script probably included it because it wasn't cleaned up

**Pull request merged**
