### PR TITLE
[TESTS] Fixes and improvements

### PR DESCRIPTION
**Pull request by antdanchenko**
- reworked verification for transaction tests (find transaction by unique amount)
- fixed simple DApp test
- added new errors to rerun tests list

### CODE REVIEW

**Review by yevh-berdnyk — APPROVED** [review]

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/5pJmWY for branch PR-4462

<blockquote><div><strong><a href="https://i.diawi.com/5pJmWY">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/zghg5t for branch PR-4462

<blockquote><div><strong><a href="https://i.diawi.com/zghg5t">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/73bgnZ for branch PR-4462

<blockquote><div><strong><a href="https://i.diawi.com/73bgnZ">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/g9LodY for branch PR-4462

<blockquote><div><strong><a href="https://i.diawi.com/g9LodY">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/rKDQ8M for branch PR-4462

<blockquote><div><strong><a href="https://i.diawi.com/rKDQ8M">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/R1i8rL for branch PR-4462

<blockquote><div><strong><a href="https://i.diawi.com/R1i8rL">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/DpWQph for branch PR-4462

<blockquote><div><strong><a href="https://i.diawi.com/DpWQph">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/taqZar for branch PR-4462

<blockquote><div><strong><a href="https://i.diawi.com/taqZar">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Pull request merged**
