### PR TITLE
[#4541] fix versioning on ios

### LINKED ISSUE #4541: App version in Profile tab does not match the build in TestFairy
### Description

*Type*: Bug

*Summary*: As a QA , i want to find my session fast in TF service so I can check logs or whatever is needed to make my work more effective. 

#### Expected behavior
App version shown in Profile matches the build in TF so I can easily find a session

#### Actual behavior

For example i have this session https://app.testfairy.com/projects/4803590-status/builds/8405150/sessions/2/?accessToken=2uOGM8yr6O2brOx36IY9EG0AFKw showing build as `0.9.20d53` and in Profile it is shown as `0.9.19 (5aae87a)`

<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803590-status/builds/8405150/sessions/2/?accessToken=2uOGM8yr6O2brOx36IY9EG0AFKw">TestFairy: Status 0.9.20d53 @2</a></strong></div></blockquote>

### PR DESCRIPTION
**Pull request by rasom**
fixes #4541

status: ready

### CODE REVIEW

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/fwcwot for branch PR-4562

**Review by jakubgs — APPROVED** [review]
Nice, I missed that could have been simplified.

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/Cduat7 for branch PR-4562

<blockquote><div><strong><a href="https://i.diawi.com/Cduat7">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/3BKfU4 for branch PR-4562

<blockquote><div><strong><a href="https://i.diawi.com/3BKfU4">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/3t6BS6 for branch PR-4562

<blockquote><div><strong><a href="https://i.diawi.com/3t6BS6">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/TtEy6D for branch PR-4562

<blockquote><div><strong><a href="https://i.diawi.com/TtEy6D">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Review by yenda — APPROVED** [review]

**Pull request merged**
