### PR TITLE
Update ko.json

### PR DESCRIPTION
**Pull request by jinhojang6**
Korean translations update

### CODE REVIEW

**Review by rasom — APPROVED** [review]

**Comment by rasom** [comment]
already tested by @jinhojang6

**Review by jakubgs — COMMENTED** [review]
This PR would benefit from running this file through `jq --sort-keys`.

**Review by goranjovic — APPROVED** [review]

**Comment by rasom** [comment]
@jakubgs I'm not sure it actually matters because usually these files are generated by Lokalise and it might be just changed again in the next PR, not very important

**Comment by jakubgs** [comment]
Yeah, which is why I didn't block the PR on this.
Maybe we'd like a pre-commit check that would sort those in the future.

**Comment by churik** [comment]
Korean translations are updated in the build, checked on IOS 11.4.1 and Android 8

**Pull request merged**
