### PR TITLE
Feature/push notifications

### LINKED ISSUE #4432: Implement desktop push notifications
### User Story

As a user, I want to receive push message when I receive new message.

### Description

*Type*: Feature
*Summary*: implement push notifications for user when the application is running in background, so they should be visible once when message is received and then in "Control Center".
Example:
jfjfjf

### In mobile
push

### LINKED ISSUE #5571: status_im.utils.notifications.request_permissions is not a function after creating account and first log in
### Description

*Type*: Bug

*Summary*: after creating account and first log in I'm getting an error `status_im.utils.notifications.request_permissions  is not a function`  and when I click on "OK', I can proceed.

#### Expected behavior
no error is shown

### Reproduction

- Open Status
- Create an account
- Log in

### Additional Information
* Status version: nightly 21/07/18
* Operating System: Mac OSx

#### Logs

[StatusIm.txt](https://github.com/status-im/status-react/files/2305361/StatusIm.txt)

### PR DESCRIPTION
**Pull request by vitvly**
Duplicate of https://github.com/status-im/status-react/pull/5129 to account for Jenkins's issues with rebased branches.

Fixes #4432 
Fixes #5571

### CODE REVIEW

**Review by maxhora — APPROVED** [review]

**Comment by churik** [comment]
@siphiuel can you please put it to `TO TEST` column once conflicts will be resolved?

**Review by vkjr — APPROVED** [review]

**Comment by churik** [comment]
- [ ] 2) Push notifications aren't coming for new messages (1-1, public channels).
Steps:
- Open Status on primary testing machine
- Open Profile, enable Notifications
- Navigate to some chat
- Open another Status instance on another device
- Send several messages into chat opened on primary testing machine
- Desktop notification "New Message" with message content should be triggered

NOTE: I got only one push, and couldn't receive any others. Tried disable/enable Notifications, restarting app, mode when chat is active or in the background - nothing helps.

*Expected:* new push notification in `Notification Center`
*Actual:* cannot trigger > 1 notification
*Video:*  http://take.ms/bujmb
*Log:* [StatusIm.txt](https://github.com/status-im/status-react/files/2248734/StatusIm.txt)

**Comment by maxhora** [comment]
Hey @churik , could you please elaborate, is this single showed notification issue the regress in comparison with previous builds where you was able to receive maximum 3 unread push notifications and after some was accepted you was able to receive new notifications? Or it is first time when you are trying to test notifications and you haven't seen before correct behavior on previous app builds? Thank you

**Comment by churik** [comment]
@MaxRis 
On first version of push notifications I was able to receive notifications when I have 3 unread only after restarting the app.
So,

> and after some was accepted you was able to receive new notifications?

there was no "after". Only restarting app helped to see other 3 notifications.

Now I saw only one push and cannot see others at all - disable/enable Notifications, restarting app, mode when chat is active or in the background - nothing helped.
Neither version is not acceptable, because in fact push notifications didn't work.

**Comment by maxhora** [comment]
@churik thank you!

**Comment by maxhora** [comment]
Have started looking to rebase this PR and check for described issue

**Comment by maxhora** [comment]
@siphiuel PR is updated to work with recent Jenkins changes.

New blocking issue is found. On start app fails with
```
WARN [status-im.ui.screens.events:106] - Could not decrypt database Error: Migration is required due to the following errors:

- Property 'account.desktop-notifications?' has been added.
```

Will try to look into it.

**Comment by churik** [comment]
@siphiuel 
Cannot read property 'sendNotification' of undefined when message for public chat is received.
hjhj
*Steps:*
- install app
- log in
- open profile
- turn on notifications
- join to public chat
- send message to public chat sent from other device

Log: [StatusIm.txt](https://github.com/status-im/status-react/files/2314091/StatusIm.txt)

**Comment by vitvly** [comment]
Blocked a bit by snorenotify not working properly (getting the qdebug log output about notification, but nothing appears in Notifications Center)

**Comment by vkjr** [comment]
@siphiuel, @maxris, maybe we can separate changes for fixing #5571 into separate PR, to make its merging independent from push notifications state. What do you think?

**Comment by maxhora** [comment]
@siphiuel do you have an idea if mentioned issue #5571 is resolved within this PR ?

**Comment by maxhora** [comment]
Oh, it seems I can see the fix. Going to try to apply it in PR with new status-go version.

**Comment by vitvly** [comment]
@vkjr @maxris yes it's available in this PR and is quite independent.

**Comment by maxhora** [comment]
superseded by https://github.com/status-im/status-react/pull/6097

**Pull request closed without merging**
