### PR TITLE
[#7930] fix - No label is shown for empty chat screen if you open pub…

### LINKED ISSUE #7930: No label is shown for empty chat screen if you open public chat via valid deep link after opening another public chat via deep link
### Description

*Type*: Bug
*Summary*: can't see label \ icon of public chat when navigating to 2 different chats one by one via deep links.
Introduced by https://github.com/status-im/status-react/issues/7454

#### Expected behavior
Can see chat name / icon

#### Actual behavior
Chat area is empty
photo_2019-04-08 12 07 10

### Reproduction

**Steps:**

- tap on valid deep link outside Status(i.e. https://get.status.im/chat/public/test)
- go back to browser
- tap on another valid deep link outside Status (i.e. https://get.status.im/chat/public/test1)
- pay attention to opened chat

### Additional Information

* Status version: nightly 08/04/2018
* Operating System: Android 8,  iOS 11.4.1

### PR DESCRIPTION
**Pull request by bitsikka**
fixes #7930 

tested on android-avd

status: ready

### CODE REVIEW

**Review by rasom — APPROVED** [review]

**Review by pedropombeiro — APPROVED** [review]

**Comment by churik** [comment]
@bitsikka thanks for your contribution!
The issue found -  navigation on public chat link (i.e. https://get.status.im/chat/public/tst1 ) when  you are on other tab (i.e. DApps, Wallet, Profile) - leads to error:
sdfsdf
Steps: 
- open app
- navigate to wallet
- open public chat link

This issue is not reproducible on nightly 09/04/2018.

**Comment by bitsikka** [comment]
@churik on it

**Comment by bitsikka** [comment]
@churik done!

**Comment by churik** [comment]
Rechecked links to public chats and user profiles on IOS 11.4.1 and Android 8, joining to public chats / links to public channels inside app.
Looks good to me!

**Pull request merged**
