### PR TITLE
Chore: setup feature-flag for not-implemented settings

### LINKED ISSUE #19582: Hide showcase settings inside the edit profile screen
depends on #19585 

### Summary
At the moment, we've not yet implemented the showcase settings that are shown while editing a user's profile. For the moment, we should hide these settings until they're implemented.

### Examples

<details>
<summary>
Edit Profile - Communities Showcase shows "not implemented"
</summary>

https://github.com/status-im/status-mobile/assets/2845768/a398310b-ca4c-4e64-bdd4-b604b12839e8

</details>

---

<details>
<summary>
Edit Profile - Accounts Showcase shows "not implemented"
</summary>

https://github.com/status-im/status-mobile/assets/2845768/6610451c-e443-48f1-bd59-9bcfce433938

</details>

---

<details>
<summary>
Edit Profile - Collectibles Showcase shows "not implemented"
</summary>

https://github.com/status-im/status-mobile/assets/2845768/8f447229-fd04-476e-999d-e607d9c3887d

</details>

---

<details>
<summary>
Edit Profile - Assets Showcase shows "not implemented"
</summary>

https://github.com/status-im/status-mobile/assets/2845768/c51a4759-5bef-4d26-ae3b-5f607860ba25

</details>

---

### LINKED ISSUE #19584: Hide profile preview button inside the edit profile screen
depends on #19585 

### Summary
At the moment, we've not implemented profile-preview while editing a user's profile. For the moment, we should hide the profile-preview button inside the edit profile screen until it's implemented.

### Example

https://github.com/status-im/status-mobile/assets/2845768/526d3f7d-9d5c-47f3-9808-2f42e5cea100

### LINKED ISSUE #19585: Chore: setup feature-flag for not-implemented features
### Summary
At the moment, we have several features that are not-implemented or unfinished. For the moment, we should create a feature-flag that allows us to hide these features until they're implemented.

#### Notes

* Perhaps we can use the name `show-not-implemented-features?` for the feature-flag.

### LINKED ISSUE #19586: Hide on-the-web links setting inside the edit profile screen
depends on #19585 

### Summary

At the moment, we've not yet implemented the "On the web" links setting while editing a user's profile. For the moment we should hide this setting until it's implemented.

### Example

https://github.com/status-im/status-mobile/assets/2845768/85834612-95e0-45fc-8dc4-5deed90bb8d6

### LINKED ISSUE #19587: Hide some profile settings that are not-implemented
depends on #19585 

### Summary

At the moment, we have some profile settings that are not implemented. For the moment, we should hide these not implemented settings until they're implemented.

### Examples

<details>
<summary>
Profile Settings - dApps shows "not implemented"
</summary>

https://github.com/status-im/status-mobile/assets/2845768/0d819e32-af42-434e-a9ec-83d256f3db22

</details>

---

<details>
<summary>
Profile Settings - Browser shows "not implemented"
</summary>

https://github.com/status-im/status-mobile/assets/2845768/7753b28c-01dc-4b32-8585-c145e7728b13

</details>

---

<details>
<summary>
Profile Settings - Keycard shows "not implemented"
</summary>

https://github.com/status-im/status-mobile/assets/2845768/3dd4b682-9980-4e0b-8f26-f06ba8db5c70

</details>

---

<details>
<summary>
Profile Settings - Language and Currency shows "not implemented"
</summary>

https://github.com/status-im/status-mobile/assets/2845768/5600a1e6-4572-42de-8aad-910c498978f9

</details>

---

<details>
<summary>
Profile Settings - Data Usage shows "not implemented"
</summary>

https://github.com/status-im/status-mobile/assets/2845768/a410474c-1869-450c-b14d-71eab487e638

</details>

---

<details>
<summary>
Profile Settings - Wallet shows "not implemented"
</summary>

https://github.com/orgs/status-im/projects/125/assets/2845768/1a7aec8e-7521-4e06-a9e2-9019b403303a

</details>

---

<details>
<summary>
Profile Settings - Messages shows "not implemented"
</summary>

https://github.com/status-im/status-mobile/assets/2845768/f13d9eff-45c8-44a6-861b-025ad3676240

</details>

---

### LINKED ISSUE #19588: Patch through "About" (Status) profile setting to legacy screen
### Summary

At the moment, we've not yet implemented the "About" (Status) profile setting. For the moment, we should forward the navigation to the legacy "About" screen.

### Example

https://github.com/status-im/status-mobile/assets/2845768/1d13af76-2c54-4ea3-8afe-3830ee9509a9

### LINKED ISSUE #19589: Patch through "Status Help" profile setting to legacy screen
### Summary

At the moment, we've not yet implemented the "Status Help" profile setting. For the moment, we should forward the UI to the legacy "Need help?" screen.

### Example

https://github.com/status-im/status-mobile/assets/2845768/b06346fa-eb2e-4bd6-8e63-158eb6fe9829

### PR DESCRIPTION
**Pull request by flexsurfer**
fixes: https://github.com/status-im/status-mobile/issues/19585
fixes: https://github.com/status-im/status-mobile/issues/19582
fixes: https://github.com/status-im/status-mobile/issues/19584
fixes: https://github.com/status-im/status-mobile/issues/19586
fixes: https://github.com/status-im/status-mobile/issues/19587
fixes: #19588
fixes: #19589

### CODE REVIEW

**Review by Parveshdhull — APPROVED** [review]

**Comment by ibrkhalil** [comment]
What about these namespaces?
https://github.com/status-im/status-mobile/blob/06aa4671b69f563e3edf20516173ade6a2975127/src/status_im/contexts/communities/overview/view.cljs#L11
https://github.com/status-im/status-mobile/blob/06aa4671b69f563e3edf20516173ade6a2975127/src/status_im/contexts/shell/activity_center/notification/reply/view.cljs#L6

**Comment by ibrkhalil** [comment]
This PR is only for settings but what are we going to do with other non-implemented usages?

**Comment by flexsurfer** [comment]
> What about these namespaces?

what about them?

**Comment by flexsurfer** [comment]
> This PR is only for settings but what are we going to do with other non-implemented usages?

create issues for them and fix them?

**Review by seanstrom — APPROVED** [review]
Awesome stuff ✅

**Comment by pavloburykh** [comment]
Hey @flexsurfer! I have checked latest PR builds ([Android](https://status-im-mobile-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-240410-103426-e4163492c0666f68d5f5b45f9fa7d8f90db7fe9a-pr19591-universal.apk) / [IOS](https://i.diawi.com/KeBMUL)) and see that all settings remain unhidden. Is this a problem of PR builds or I am missing something? 


https://github.com/status-im/status-mobile/assets/97245802/309457c8-3536-4ecb-ab70-ac9acc5c9526

Also, I do not see any feature flag toggles for enabling/disabling of those settings

photo_2024-04-11 13 30 06

**Comment by flexsurfer** [comment]
hey @Parveshdhull this flag is enabled for PRs and e2e, it is disabled only for release, I'm not sure if this flag should be in feature flags cc @seanstrom.

**Comment by pavloburykh** [comment]
> hey @Parveshdhull this flag is enabled for PRs and e2e, it is disabled only for release, I'm not sure if this flag should be in feature flags cc @seanstrom.

What about nightly builds? 

And the other question - what should be manually QAed here taking into consideration that nothing has changed in PR/e2e and probably nightly builds? 

As far as I know we do not have some easy way to create release build based on PR branch to check those fixes. Correct me if I am wrong @churik

**Comment by pavloburykh** [comment]
> this flag is enabled for PRs and e2e, it is disabled only for release 

Would be nice to have such details in PR description @flexsurfer as I was not aware about any decisions which were made related to this PR, so little bit confused.

**Comment by pavloburykh** [comment]
@flexsurfer thank you for the PR. We have built release build based on PR branch (thanks @churik) so I managed to check the changes. 

There is 'Change password' feature which is also not implemented. 

I am wondering if we can include it's hiding in this PR in order to cover all profile related features? Or you prefer if I log separately @flexsurfer ?


https://github.com/status-im/status-mobile/assets/97245802/79821aa5-debc-4d80-bd0b-1edb16ec53d1

**Comment by Parveshdhull** [comment]
> hey @Parveshdhull this flag is enabled for PRs and e2e, it is disabled only for release, I'm not sure if this flag should be in feature flags cc @seanstrom.

https://github.com/status-im/status-mobile/issues/19585
> At the moment, we have several features that are not-implemented or unfinished. For the moment, we should create a **feature-flag** that allows us to hide these features until they're implemented.

To me its ok both way.

**Comment by seanstrom** [comment]
> hey @Parveshdhull this flag is enabled for PRs and e2e, it is disabled only for release, I'm not sure if this flag should be in feature flags cc @seanstrom.

I think we can include this feature-flag inside the feature-flag screen, that way we can always what flags are available. Thoughts?

**Comment by seanstrom** [comment]
> @flexsurfer thank you for the PR. We have built release build based on PR branch (thanks @churik) so I managed to check the changes.
> 
> There is 'Change password' feature which is also not implemented.
> 
> I am wondering if we can include it's hiding in this PR in order to cover all profile related features? Or you prefer if I log separately @flexsurfer ?
> 
>  telegram-cloud-document-2-5242436055000434685.mp4

I think we have a PR for implementing the Change Password setting: https://github.com/status-im/status-mobile/pull/19474

**Comment by pavloburykh** [comment]
> I think we have a PR for implementing the Change Password setting: #19474

oh, thank you @seanstrom! @flexsurfer please ignore my comment here https://github.com/status-im/status-mobile/pull/19591#issuecomment-2049602814

**Comment by flexsurfer** [comment]
> I think we can include this feature-flag inside the feature-flag screen, that way we can always what flags are available. Thoughts?

i don't see how it could be useful, so I wouldn't add it, it's different kind of features and flags

**Comment by pavloburykh** [comment]
@flexsurfer no issues from my side. ready for merge.

**Pull request merged**
