### PR TITLE
[#11958] Add activity center

### LINKED ISSUE #11958: Add activity center
As a user
I want to have a activity center 
So incoming invitation/messages from new contacts can be grouped and don't pollute the chat area

### Description

Chats from non-contacts and new group chat invitation from non contacts should open in the activity center first, with an option  to accept, in which case they will be moved to the main chat view.

### Acceptance criteria

- A chat from a non-contact should open first in the activity center, and should not be shown in the main chat view.
- A group chat invitation from a non-contact should open in the activity center, and should not be shown in the main chat view.
- The user should be able to navigate on the activity center, and `Accept and add` or `Reject and delete` a 1-to-1 chat or a group chat from the activity center. If deleted it should not show anymore and if accepted it should show in the main chat area.

### Designs

https://www.figma.com/file/r59kCQxl6tlC0dHkcAJOpP/Action-center-MVP---Mobile?node-id=2%3A8012

### LINKED ISSUE #11981: Add option to receive chats invites and new chats only from contacts
As a user
I want to have an option to receive chats invites & new chats only from contacts
So that I can't be easily spammed

### Description

A user should have an option to allow new chats & messages only from contacts as a stop-gap measure for spam.
If the user is not in contacts, new messages or chat invitations should not be received by the user (it's very similar to block feature, but they will be received in public chats).

### Designs

https://www.figma.com/file/TNCyHKtR3sx5EL6YznFWUa4O/Profile?node-id=6851%3A25959

### PR DESCRIPTION
**Pull request by flexsurfer**
fixes #11958
fixes https://github.com/status-im/status-react/issues/11981
ready

### CODE REVIEW

**Comment by jakubgs** [comment]
This is neat, but where has the node connectivity button gone? I thought it was really neat and helped users figure out what's up.

**Comment by flexsurfer** [comment]
@jakubgs did you try this PR and there is no connectivity button ? i mean it should be still there

**Comment by jakubgs** [comment]
@flexsurfer nope, it's gone, it only shows up when I put phone in airplane mode:

image

**Comment by flexsurfer** [comment]
@jakubgs but we showed it only when you're offline or on cellular, we didn't show it on wi-fi , so it works same as before

**Comment by jakubgs** [comment]
Oh, you're right, I compared with the nightly, sorry.
Though it is a bit annoying, what if I want to see the connection status while on wifi?

**Comment by flexsurfer** [comment]
honestly i also kinda like it , so you can check mailservers connection and nodes, @errorists wdyt ?

**Comment by errorists** [comment]
u guys are geeks but ok, I promise to revisit it once I have some free time. just don't change anything in this PR please 🙏

**Review by cammellos — APPROVED** [review]

**Comment by Serhy** [comment]
Thank you @cammellos and @flexsurfer  !
Agreed to merge and fix separately few points:

1) If I have 2 or more items in Activity Center, and I navigate to chat view (Group/1-1) from Activity Center (doen't matter which one - Group->Decline or Group -> Join or open 1-1 chat) --- then next time I open Activity Center - there will be still two group but the one which supposed to be removed from list, - it duplicates the one which left.

2) User icon not picked up in Activity center but shown as default

3) UX of Activity Center (different from design): increment of unseen items (we now have common one like on public chats unread messages), 'Deselect All' option.

E2E tests updated separately in https://github.com/status-im/status-react/pull/11983

**Pull request merged**
