### PR TITLE
changes corresponding to refactor of local pair of status-go (PR #3248)

### PR DESCRIPTION
**Pull request by qfrank**
make sure it's compatible with refactor of local pair of status-go.
relate [PR](https://github.com/status-im/status-go/pull/3248) for status-go

### Testing notes
makes sense to check old sync/pairing flow for regression

#### Platforms

- Android
- iOS

status: ready

### CODE REVIEW

**Review by Samyoul — APPROVED** [review]
Looks good. Thank you 🙏

**Review by siddarthkay — APPROVED** [review]

**Comment by pavloburykh** [comment]
@qfrank thanx for the PR. Please, take a look at the following issue. 

### IOS is not redirected into account after scanning sync QR, manual login into paired account results in sql error

Reproducible on IOS

**Preconditions:** Device A (any device), Device B (IOS)

**Steps:** 

1. Generate sync QR on Device A
2. Scan QR code by Device B (IOS)
3. See if Device B has been redirected into account and paired with Device A

**Expected result:** Device B is redirected into scanned account. Data is synced, devices are paired. 

**Actual result:** IOS device is not redirected into account after scanning sync QR. Manual login into paired account (and all other existed accounts) results in sql error: no rows in result set. 

photo_2023-03-21 15 15 31


https://user-images.githubusercontent.com/97245802/226618799-9a1f7748-7a15-4ac0-9861-3ee5a486269e.MP4

**Comment by pavloburykh** [comment]
@qfrank also I have faced another error on IOS when trying to login one of paired accounts

photo_2023-03-21 15 15 34

**Comment by pavloburykh** [comment]
@qfrank **NOTE:** currently it is not possible to scan QR code on fresh installed app, as new designs are not ready yet for that flow. 

For now it is possible to scan qr code from login page (i.e. when user already has an account).

But after merging into develop this PR https://github.com/status-im/status-mobile/pull/15376 it will be impossible to scan QR even from login screen, as PR will introduce new design of login page. It will be merged soon. After that there will be no UI possibility to test local pairing functionality, until new designs with new pairing flow will be implemented.

**Comment by qfrank** [comment]
Hi @pavloburykh , can you retry the latest build? thank you 🫶

**Comment by pavloburykh** [comment]
> Hi @pavloburykh , can you retry the latest build? thank you 🫶

@qfrank thank you, ISSUE 1 is fixed. Please, take a look at another issue


### ISSUE 2 App crashes on syncing QR of the account that has previously been restored numerous times on different devices before. 

For reproduction use this seed phrase that belongs to account which has been restored lot of times on different devices: section involve corn song gold verb topic nurse morning dream snack very

**Steps:** 

1. Restore given above account on Device A
2. Generate sync QR on Device A
3. Scan sync QR on Device B
4. Observe the result

**Actual result:** Device B crashes after scanning QR. It is possible to login account on Device B manually, data is synced **BUT** devices are not paired. 


https://user-images.githubusercontent.com/97245802/226872792-9a30219f-f110-43e7-a394-259a42b92c23.mp4

**Comment by pavloburykh** [comment]
> ### ISSUE 2 App crashes on syncing QR of the account that has previously been restored numerous times on different devices before.

We agreed with @qfrank that ISSUE 2 will be addressed separately as it is not PR related. 
Current PR is ready to be merged.

**Pull request merged**
