### PR TITLE
Add changelog from status-go on upgrade #13090

### LINKED ISSUE #13090: Add changelog from status-go on upgrade
If status-go is upgraded in status-react, we should add in the commit the changelog of the changes, this should be done automatically through hooks. Ideally that's reflected as well in the PR description so QA is aware of the changes brought in each PR.

### PR DESCRIPTION
**Pull request by audriu**
fixes https://github.com/status-im/status-react/issues/13090
Summary

- If status-go is upgraded in status-react, add the link of changelog in to the next PR message.

Testing notes

 - Run scripts/update-status-go.sh "tag" and commit the changes. The PR message contains link to the changelog.
 - Also check a commit made using this hook `https://github.com/status-im/status-react/commit/f9f78e23d31db7f5eb31595b0b8fe645d6017dc7` the commit message contains link to the status-go changelog/

Platforms

   - command line

status: READY

### CODE REVIEW

**Comment by jakubgs** [comment]
Previous history can be found here: https://github.com/status-im/status-react/pull/13138

**Review by jakubgs — APPROVED** [review]
Looking good, but we'll need to do some testing with devs.

**Comment by jakubgs** [comment]
This script could use some comments though.

**Review by churik — APPROVED** [review]
👍

**Review by cammellos — APPROVED** [review]

**Pull request merged**
