### PR TITLE
#17945 Scanned address persists in ETH address textbox after reopening 'Add address to watch' screen

### LINKED ISSUE #17945: [Android] Scanned address persists in ETH address textbox after reopening 'Add address to watch' screen
Follow up for https://github.com/status-im/status-mobile/pull/17829

### Steps:
1. Tap 'Add address to watch' option - > Scan any address
2. Go back using device's back button
3. Tap 'Add address to watch' option again
4. Check result

### Actual result:
The previous address (or part of this address) is still shown within ETH address textbox

https://github.com/status-im/status-mobile/assets/52490791/03b6d9a7-b645-45d6-af4c-0ed2b72193f9

### Expected result:
The ETH address textbox should be empty upon reopening the 'Add address to watch' screen.

### PR DESCRIPTION
**Pull request by alwx**
Fixes #17945

#### Platforms

- Android
- iOS

status: ready

### CODE REVIEW

**Review by J-Son89 — APPROVED** [review]
Thanks @alwx! 🙌🏼

**Comment by churik** [comment]
@alwx please, resolve conflicts and rebase PR, than we'll take PR to test, sorry for the delay!

**Comment by alwx** [comment]
@churik done!

**Comment by J-Son89** [comment]
@alwx can we merge this?

**Pull request merged**
