### PR TITLE
fixed incorrect space between name and message card in selected messa…

### LINKED ISSUE #17513: incorrect space between name and message card in on-long-press selected message
# Bug Report

might be duplicate with 3 in https://github.com/status-im/status-mobile/issues/16875

design feedback at: https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=6130:58226&t=BpzZ5GTnwcCRiIIf-0&locale=en&type=design#570487148
design: https://www.figma.com/file/PPWkgOYlZZDxZv5SDGsZVV/Posts-%26-Attachments-for-Mobile?type=design&node-id=5364-584099&mode=design&t=x9KsXnPC8iQcsid7-4

### PR DESCRIPTION
**Pull request by jo-mut**
fixes #17513

### Summary

**Before**  & **Figma Design** & **After** screenshots in order

Screenshot 2024-01-09 at 13 50 47

...

### CODE REVIEW

**Review by ajayesivan — APPROVED** [review]

**Review by siddarthkay — APPROVED** [review]

**Review by BalogunofAfrica — APPROVED** [review]

**Comment by jo-mut** [comment]
@Francesca-G kindly also take a look at this. thanks

**Comment by mariia-skrypnyk** [comment]
Hi @jo-mut ! Thanks for your PR!

I've tested your fix with this space between name and message card on:

- iOS/Android
- Dark/Light theme
- min/max length
 
I found this issue but it seems it is out of your PR and I'll figure out where to document it.
[
Screenshot 2024-01-15 at 15 43 32
](url)

So I move it for @Francesca-G to review and thanks @jo-mut !
*failed e2e are known and are not related to this PR

**Review by Francesca-G — APPROVED** [review]
Looks good ✨

**Comment by jo-mut** [comment]
> Hi @jo-mut ! Thanks for your PR!
> 
> I've tested your fix with this space between name and message card on:
> 
> * iOS/Android
> * Dark/Light theme
> * min/max length
> 
> I found this issue but it seems it is out of your PR and I'll figure out where to document it. [ Screenshot 2024-01-15 at 15 43 32 ](url)
> 
> So I move it for @Francesca-G to review and thanks @jo-mut ! *failed e2e are known and are not related to this PR

once you have logged this you can assign me the issue as I have a bit of a background working with this particularly. I should be able to fix it without much difficulty. In the meantime i will investigate it

**Pull request merged**
