### PR TITLE
Update status-go to `develop-g9cc9982a`.

### PR DESCRIPTION
**Pull request by mandrigin**
### Summary:

```
commit 9cc9982a6a1c9c8d852a1b567bf933e2eaac548d (HEAD -> develop, upstream/develop)
[#639] Disable filter removal in `go-ethereum`. (#650)

commit 2d964bfe9f9554fdb34c6c19095f3c5e88c527e6
Remove async operations from node manager (#584)

commit 4cddc362acc2e05ad7b0538a7aaf10b7fea2b2ab
Fix all data races in jail package (#632)

commit 00df3ff9f8fcd75074bf2b403db8e7e874617146
[#618] Jail.Call to return valid JSON string based results (#619)

commit d0ef64a177aa609314b0680faf38bd5c80958c62
Maintain local copy of the nonce for each used address (#538)

commit ca719af71c2ecdc793673820a039b46d96e1ec7d
Sync blockchain before running e2e tests on public testnet #568 (#612)

commit ca5a8f666982a516c32740b1635c9fceff2c4fc1
Enable ethereum metrics collection (#616)

```
status: ready

### CODE REVIEW

**Comment by mandrigin** [comment]
Most importantly, should fix https://github.com/status-im/status-react/issues/3116

**Review by flexsurfer — APPROVED** [review]

**Comment by flexsurfer** [comment]
@mandrigin please resolve conflicts

**Comment by mandrigin** [comment]
@flexsurfer done

**Review by yenda — APPROVED** [review]

**Comment by Serhy** [comment]
It was checked with Android: https://i.diawi.com/kbXL3i and iOS: https://i.diawi.com/vES3kF on Android 7.0 (Samsung j7 real device), iPhoneX (iOS 11.2.2) and Android 6.0 (Nexus 5 emulator). 

The #3116 is not reproducible anymore. As well as keeping the device with opened App without internet connection overnight and resuming in the morning chat exchange between two contacts (enabling network connection) - also loos good and both contacts could send/receive messages.
No regression issues were noticed.

@mandrigin nice job!! Ready for merge!

**Comment by Serhy** [comment]
Have to return it with the major issue:
Everything works good on 'Ropsten with upstream' network.
However, after switch on any other network - contact can not log in to account. App stays on log in screen with the spinning figwheel icon indefinitelly (I waited up to 5 minutes)

**Reproduction**:
1) Open Status and create account
2) Navigate to Profile -> Network
3) Change network from 'Ropsten with upstream RPC' to 'Rinkeby with upstream RPC'
4) Re-login to account
**Actual result:** App crashed and closed.
TF session for first log in attempt: https://app.testfairy.com/projects/4803622-status/builds/7692844/sessions/35/?accessToken=Glt6J5BAXC-UIUMVDpJdq3VhH3g

5) Open App again and log in to account created before
**Actual result:** App stays on log in screen with the spinning figwheel icon indefinitelly
TF session for second log in attempt: https://app.testfairy.com/projects/4803622-status/builds/7692844/sessions/36/?accessToken=jpnBtvm6PJW2KHRiW74yE9swEH4

**Comment by mandrigin** [comment]
@Serhy good catch! I'll take a look tomorrow.

**Comment by Serhy** [comment]
Here is the geth log from Android 7.0 that logs all steps below:

1) Fresh Android: https://i.diawi.com/kbXL3i version (332cc8d9+) installed.
2) Open Status and create account
3) From Profile -> Network -> Network settings: change from `Ropsten with upstream RPC` to `Rinkeby with upstream RPC`. Tap 'Connect' button.
4) Log in to account
5) Open app log in again

[geth.log](https://github.com/status-im/status-react/files/1724387/geth.log)

**Comment by dshulyak** [comment]
It looks like that react part is waiting for a signal that node is stopped. That thing should be fixed in https://github.com/status-im/status-go/pull/663 . Will try it on simulator right now

**Comment by mandrigin** [comment]
@Serhy I just pushed a fix that @dshulyak mentioned. When the build is done, can you please re-test?

**Comment by Serhy** [comment]
Builds Android: https://i.diawi.com/3GY9HD and iOS: https://i.diawi.com/HABc8d tested and confirmed are good to merge! 
Above regression changing the network not reproduced anymore.
Messages sent and delivered after contact went online after being 20 minutes offline.

@mandrigin, @dshulyak - awesome job!

**Comment by mandrigin** [comment]
Squashed the commits

**Review by janherich — APPROVED** [review]

**Pull request merged**
