### PR TITLE
fix inability to move cursor to next line in bio field

### LINKED ISSUE #20306: [IOS] Inability to move cursor to next line in bio field by tapping the 'return' button on the keyboard.
### Steps:
1. Go to 'Edit Profile' flow -> Bio.
2. Enter a few characters in the 'bio' field.
3. Attempt to move to the next line by tapping the 'enter' button on the keyboard.
4. If step 3 does not work, remove a few characters.
5. Attempt to move to the next line again by tapping the 'return' button on the keyboard.

### Actual result:
The cursor remains on the same line and does not move to the next line.

https://github.com/status-im/status-mobile/assets/52490791/7d748ad3-16ad-4773-97ec-976bdc831b60

### Expected result:
The cursor should move to the next line after tapping the 'enter' button on the keyboard.

### Devices:
- iPhone 11 Pro Max, IOS 17
 
### Logs
[logs.zip](https://github.com/user-attachments/files/15534460/logs.zip)

### PR DESCRIPTION
**Pull request by Parveshdhull**
fixes https://github.com/status-im/status-mobile/issues/20306

status: ready

### CODE REVIEW

**Review by mohsen-ghafouri — APPROVED** [review]
👍

**Review by ajayesivan — APPROVED** [review]

**Comment by mariia-skrypnyk** [comment]
Hi @Parveshdhull !

Thanks for your fix.
Return button now works as expected 🙌!

Just a tiny detail that I want to mention. If you will think it should be a follow up - ok.

**ISSUE 1:** Save bio button blinks when user tap on return button.

**Steps:** 

1. Login
2. Go to Profile -> Bio
3. Add some text and tap return on your keyboard

**Actual result:**

https://github.com/status-im/status-mobile/assets/147824399/8be3c85c-2d6a-4733-aad7-25ed04bdce3c

**Expected result:** no blinking

**Comment by Parveshdhull** [comment]
hi @mariia-skrypnyk, Thank you very much for testing the PR and reporting this issue.

From the code it seems this blink(disabling of button when typing) was intentional and implemented in https://github.com/status-im/status-mobile/pull/18765.

Probably its ok to remove this behaviour as bio validation don't take that much time, but lets wait for @mohsen-ghafouri for confirmation.

**Comment by mohsen-ghafouri** [comment]
Yes it was a request from design team to keep button disable when user is typing @Parveshdhull @mariia-skrypnyk 
https://github.com/status-im/status-mobile/pull/18270#pullrequestreview-1809009905

**Comment by Parveshdhull** [comment]
> Yes it was a request from design team to keep button disable when user is typing @Parveshdhull @mariia-skrypnyk [#18270 (review)](https://github.com/status-im/status-mobile/pull/18270#pullrequestreview-1809009905)

Thank you @mohsen-ghafouri for confirming and providing link

**Comment by mariia-skrypnyk** [comment]
@Parveshdhull thanks!
Please merge your PR!

**Pull request merged**
