### PR TITLE
[#9255] Fix erasing ens after back to profile

### LINKED ISSUE #9255: Value is erased when go back to Profile from ENS username after validating it
# Bug Report

## Problem

After entering valid name if you go back to profile and open ENS name again - value will be erased, but button "To continue" will be enabled

#### Expected behavior
Value is preserved

#### Actual behavior
ens_name

IMG_A9F0BFA81AEA-1

### Reproduction

- Open Status
- Go to Profile > ENS > Add username
- Enter valid ENS (to see message "Continue to set `Show my username` in chat"
- Go back
- Open "Add username" again

### Additional Information
- Status version: nightly 21/10/2019
- Operating System: Android, iOS

### PR DESCRIPTION
**Pull request by maymax777**
### Description

fixes #9255 

### Screen record

https://user-images.githubusercontent.com/46853869/153536223-5758f8d8-3cee-456c-a450-c50d39cad9d0.mov

### CODE REVIEW

**Comment by flexsurfer** [comment]
hey @maymax777 thanks for the contribution, what if you go back to main screen and open ens registration again? field should be empty in that case

**Comment by maymax777** [comment]
> hey @maymax777 thanks for the contribution, what if you go back to main screen and open ens registration again? field should be empty in that case

@flexsurfer  thanks for your review! :+1
sorry for that, thought it was pretty simple but i didnt realize about it. I'm updating a bit to remove the ens if it's started from profile screen again

**Comment by churik** [comment]
@maymax777 please, ping here when it is ready to test again.
When your commit is ready, rebase your branch to latest develop.
Thanks!

**Comment by flexsurfer** [comment]
@maymax777 is this PR still relevant?

**Comment by flexsurfer** [comment]
@maymax777 please feel free to reopen

**Pull request closed without merging**
