### PR TITLE
[#17288] refactor: migrate previews to new api

### PR DESCRIPTION
**Pull request by mohsen-ghafouri**
to accomplish #17288

migrated :
- numbered_keyboard
- onboarding
- password

status: ready

### CODE REVIEW

**Review by ibrkhalil — APPROVED** [review]

**Comment by mohsen-ghafouri** [comment]
@status-im/mobile-qa all changes are related to just quo preview screens. does it need manual qa?

**Review by ajayesivan — APPROVED** [review]
LGTM!

**Comment by VolodLytvynenko** [comment]
> @status-im/mobile-qa all changes are related to just quo preview screens. does it need manual qa?

Good question. In my experience, changes related to 'quo' do not introduce additional issues. Perhaps we should consider PRs like this for direct movement to design review

**Review by J-Son89 — APPROVED** [review]

**Comment by qoqobolo** [comment]
> https://github.com/orgs/status-im/teams/mobile-qa all changes are related to just quo preview screens. does it need manual qa?

Thanks for the ping @mohsen-ghafouri 🙏
As it was agreed, such PRs require manual testing if the changes also affect components/code _that are already used in the app_. If the components are completely new, then manual testing is not required (only e2e tests and design reviews). 
cc @VolodLytvynenko

**Comment by VolodLytvynenko** [comment]
Thats correct https://github.com/status-im/status-mobile/pull/17420#issuecomment-1738693706 @qoqobolo Thank you!
@mohsen-ghafouri Thank you for PR. e2e failures are not related to current PR.

hi @Francesca-G could you take a look, please?

**Review by Francesca-G — APPROVED** [review]
Looks good :)

Issue, not design-related: when finishing the onboarding flow the app crashed, right after pressing "Start using Status". I reopened and it worked normally after that first crash

**Pull request merged**
