### PR TITLE
make sure profile image is saved before node started

### LINKED ISSUE #15794: Profile image set from gallery is not fetched on identifiers screen and inside account until re-login
I consistently experience this issue on my Samsung Galaxy A52, Android 12, while @qoqobolo encounters it occasionally on her Huawei P40 Lite, Android 10.

Also, reproduced on iPhone 10, IOS 14.1

**Steps:** 

1. Proceed with creating/restoring multiaccount
2. Set up profile picture from gallery (not from camera) on Create profile step. Select picture which has not been uploaded before on current build. 
3. Continue onboarding
4. Pay attention if selected profile picture is fetched on Identifiers screens and inside the account

**Actual result:** profile picture is not fetched on identifiers screen. Inside account profile picture appears only after re-login. 

https://user-images.githubusercontent.com/97245802/235621151-6de2ccdd-a438-4dd9-a465-31473d76b3ba.mp4

**Expected result:** profile picture is fetched on all screens after set up. 

### Additional Information

- Status version: nightly 
- Operating System: Android

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by qfrank**
when creating account and login, profile image is saved after `node.login` dispatched, there is a possible frontend won't get latest profile image. 

fixes #15794

status: ready

### CODE REVIEW

**Review by flexsurfer — APPROVED** [review]

**Review by Parveshdhull — APPROVED** [review]

**Comment by pavloburykh** [comment]
@qfrank thanx for the PR! Please take a look at the following issue

### ISSUE 1 Selected accent color is not applied inside newly created account until re-login

**Steps:** 

1. Proceed with creating a new user
2. Select some non-default accent color on Profile creation screen
3. Pay attention if selected accent color has been applied inside account

**Actual result:** selected accent color is not applied until re-login


https://github.com/status-im/status-mobile/assets/97245802/b3910156-b931-49e7-87e1-c95b3ddc5b1a

**Comment by qfrank** [comment]
> @qfrank thanx for the PR! Please take a look at the following issue
> 
> ### ISSUE 1 Selected accent color is not applied inside newly created account until re-login
> **Steps:**
> 
> 1. Proceed with creating a new user
> 2. Select some non-default accent color on Profile creation screen
> 3. Pay attention if selected accent color has been applied inside account
> 
> **Actual result:** selected accent color is not applied until re-login
> 
>  telegram-cloud-document-2-5255999720634986619.mp4

this issue seems not relate to my fix, could you check if it also exist on branch `develop` ? thank you! @pavloburykh

**Comment by pavloburykh** [comment]
> this issue seems not relate to my fix, could you check if it also exist on branch `develop` ? thank you! @pavloburykh

my bad @qfrank I was checking on outdated develop and did not reproduce the issue. Now I see that it is in develop. PR is ready for merge, thank you!

**Comment by qfrank** [comment]
can be closed now since @cammellos already updated status-go-version.json to a higer version

**Pull request closed without merging**
