### PR TITLE
chore_: bump go-waku fixes on peers and concurrent access

### PR DESCRIPTION
**Pull request by qfrank**
relate status-go [PR](https://github.com/status-im/status-go/pull/6187)

status: ready

### CODE REVIEW

**Review by ilmotta — APPROVED** [review]

**Comment by churik** [comment]
The delay between messages in this PR is around 1 min.
Check out the video: 

https://github.com/user-attachments/assets/193eedf0-a6db-4770-9c05-e7926416c52c

Logs for sender: [logs (27).zip](https://github.com/user-attachments/files/18112534/logs.27.zip)
Logs for receiver: [receiver.zip](https://github.com/user-attachments/files/18112544/receiver.zip)


In comparison the same test case in release build, messages are arriving instantly:

https://github.com/user-attachments/assets/dd9efa2a-9fe4-4672-a235-b8e5caf0aab5



There might be some other changes in status-go that introduced these problems, we may try to rebase these commits to release branch as per https://discord.com/channels/1210237582470807632/1217172571917647932/1316758979627716639  and re-test.

@plopezlpz @qfrank @richard-ramos @ilmotta

**Comment by churik** [comment]
Confirmed that https://github.com/status-im/status-mobile/pull/21809#issuecomment-2539022490 is not introduced by tested commit, messages are not getting delayed in the PR. Continue testing.

**Comment by churik** [comment]
Video:
https://drive.google.com/file/d/1j3Qgjj9MgQ6TIphXGvM205UPjUTSyLdZ/view?usp=drive_link


Here’s the timeline for 1-1 chats (from video):
1. **00:00–00:15 (Wi-Fi)**: Sender sends messages O-O5 (15 sec).
2. **00:15–01:40 (Wi-Fi)**: Receiver app in the background; after returning to the foreground and waiting 90 seconds, **nothing happened**.
3. **01:41 (Wi-Fi)**: Sender sends one message O6.
4. **01:45–02:33 (Wi-Fi)**: Receiver gets message O6, but **slowly** starts to receive O-O5 afterward.
5. **02:33–03:00 (Wi-Fi)**: Receiver verifies only Wi-Fi is enabled in settings. Switches to **5G** to check how messages are received.
6. **03:00–03:15 (Wi-Fi)**: Sender sends messages S1–S5.
7. **03:15–05:06 (5G)**: Receiver **never gets these messages** (after re-login he could, did in 40 mins)

Logs for sender: [Status-debug-logs-1.zip](https://github.com/user-attachments/files/18125203/Status-debug-logs-1.zip)

Logs for receiver: [logs (28).zip](https://github.com/user-attachments/files/18125210/logs.28.zip)

**Comment by ilmotta** [comment]
@churik I just merged PR https://github.com/status-im/status-mobile/pull/21806 into the mobile release branch and it already points to the latest hash in status-go `release/7.1.x` https://github.com/status-im/status-go/commit/d3fd630db9223207d36144371bd6b0c85ee24d62 which includes the fix you tested here https://github.com/status-im/status-go/pull/6209#issuecomment-2541705493

Therefore, I'm closing this PR because we already have what we need in the mobile release branch.

**Pull request closed without merging**
