### PR TITLE
Mark seen when loading more

### LINKED ISSUE #4726: Unread messages counter reappears with old count after restarting app
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want the unread count to persist after restarting the app so that the count is meaninful for me.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: After I read all the messages in a public chat and navigate to the home screen, and restart the app, the unread messages count has the old value, instead of showing that all messages are read.

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Create a new account and join a stale public chat containing a large number of unread messages (let's say > 50, exemplified with `#test` public chat below):
image

- While the app is retrieving messages from mailserver, go back to home screen (make sure that the unread badge is visible for the chat)
- Go to the OS home screen
- Kill the Status app by swiping it away in the running app list
- Start app again and sign in to the same account
- Enter the public chat screen and scroll up until all are considered read
- Go back to the main screen (notice that unread badge has disappeared from `#test`):
image

- Go to the OS home screen
- Kill the Status app by swiping it away in the running app list
- Open Status again and sign in to the same account (notice that unread badge has reappeared for `#test`):

image

#### Expected behavior
[comment]: # (Describe what you expected to happen.)

App shows that no unread messages exist for that public chat.

#### Actual behavior
[comment]: # (Describe what actually happened.)

App still shows the old number of unread messages for that public chat.

### Additional Information
* Status version: Nightly 0.9.19 build 6044
* Operating System: Android

### PR DESCRIPTION
**Pull request by janherich**
[comment]: # (Please replace ... with your information. Remove < and >)
[comment]: # (To auto-close issue on merge, please insert the related issue number after # i.e fixes #566)

fixes #4726 

### Summary:

We recently fixed the problem with unread message counter not being persisted at all (due to incorrect realm query), but we forgot to plug-in "marking messages seen" logic into handler loading more messages when scrolling up in the chat.
The result was that after initial load when going to chat, where currently loaded messages were correctly marked as seen in app-db, realm & network (relevant in case of 1-1 chat), we didn't repeat the logic whenever more messages were loaded, this PR fixes the problem, it also removes one line of code as a bonus :)

### Testing notes (optional):
Check that #4726 is not happening anymore.

status: ready

### CODE REVIEW

**Review by rasom — APPROVED** [review]

**Review by cammellos — APPROVED** [review]

**Comment by lukaszfryc** [comment]
I didn't notice any significant difference between this PR build and develop. So, if it's a hack, I would not merge it.

**Comment by janherich** [comment]
@lukaszfryc This is not performance enhancing PR, but bugfixing PR fixing bug #4726 :) It's not a hack, it even makes code cleaner (one less line of code) :)

**Comment by lukaszfryc** [comment]
Ah, sorry! I mistaken it with https://github.com/status-im/status-react/pull/4660 :)

**Comment by Serhy** [comment]
Builds https://i.diawi.com/sjev3y (Android) and https://i.diawi.com/wSsKgN (iOS) has been tested and confirmed that #4726 fixed. Unread message counter does not persist staying after messages were actually read by contact after app restarts. 
No regressions found.

**Pull request merged**
