### PR TITLE
Change deps.edn to properly resolve transitive deps

### LINKED ISSUE #4072: Fix build.clj script
We would like to move from lein to the new clj cli tool for project task.
There is currently an error with the figwheel task that prevents us from using it.

#### Expected behavior
`clj -R:repl build.clj figwheel android` works like `lein figwheel-repl android`

#### Actual behavior
`clj -R:repl build.clj figwheel android` produces the following error in the android simulator when running the app:

```
05-01 12:42:07.448  5046  5102 E ReactNativeJS: Error rendering component (in status_im.android.core.app_root)
05-01 12:42:07.452  5046  5102 E ReactNativeJS: ReferenceError: Can't find variable: performance
05-01 12:42:07.452  5046  5102 E ReactNativeJS: 
05-01 12:42:07.452  5046  5102 E ReactNativeJS: This error is located at:
05-01 12:42:07.452  5046  5102 E ReactNativeJS:     in status_im.android.core.app_root (created by env.android.main.reloader)
05-01 12:42:07.452  5046  5102 E ReactNativeJS:     in env.android.main.reloader
05-01 12:42:07.452  5046  5102 E ReactNativeJS:     in Unknown (at renderApplication.js:35)
05-01 12:42:07.452  5046  5102 E ReactNativeJS:     in RCTView (at View.js:71)
05-01 12:42:07.452  5046  5102 E ReactNativeJS:     in View (at AppContainer.js:102)
05-01 12:42:07.452  5046  5102 E ReactNativeJS:     in RCTView (at View.js:71)
05-01 12:42:07.452  5046  5102 E ReactNativeJS:     in View (at AppContainer.js:122)
05-01 12:42:07.452  5046  5102 E ReactNativeJS:     in AppContainer (at renderApplication.js:34)
05-01 12:42:07.458  5046  5102 E ReactNativeJS: { [ReferenceError: ReferenceError: Can't find variable: performance
05-01 12:42:07.458  5046  5102 E ReactNativeJS: 
05-01 12:42:07.458  5046  5102 E ReactNativeJS: This error is located at:
05-01 12:42:07.458  5046  5102 E ReactNativeJS:     in status_im.android.core.app_root (created by env.android.main.reloader)
05-01 12:42:07.458  5046  5102 E ReactNativeJS:     in env.android.main.reloader
05-01 12:42:07.458  5046  5102 E ReactNativeJS:     in Unknown (at renderApplication.js:35)
05-01 12:42:07.458  5046  5102 E ReactNativeJS:     in RCTView (at View.js:71)
05-01 12:42:07.458  5046  5102 E ReactNativeJS:     in View (at AppContainer.js:102)
05-01 12:42:07.458  5046  5102 E ReactNativeJS:     in RCTView (at View.js:71)
05-01 12:42:07.458  5046  5102 E ReactNativeJS:     in View (at AppContainer.js:122)
05-01 12:42:07.458  5046  5102 E ReactNativeJS:     in AppContainer (at renderApplication.js:34)] line: 60, column: 22 }
05-01 12:42:07.485  1446  1446 D SurfaceFlinger: duplicate layer name: changing im.status.ethereum/im.status.ethereum.MainActivity to im.status.ethereum/im.status.ethereum.MainActivity#2
```

### PR DESCRIPTION
**Pull request by dmitryn**
fixes #4072 

### Summary: 

Change deps.edn to properly resolve transitive deps

status: ready

### CODE REVIEW

**Review by janherich — APPROVED** [review]

**Review by jeluard — APPROVED** [review]
@dmitryn Can you add a comment detailing why this is needed and what this does?

**Comment by dmitryn** [comment]
@jeluard when https://github.com/clojure/tools.deps.alpha resolves dependencies, it ends up choosing `re-frame` 0.10.1 (re-frisk-remote's dependency) but not `status-im/re-frame` 0.10.5 because `status-im/re-frame` is published under `status-im` org on clojars.
But when you fetch dependency from github, you could provide any dependency name (just `re-frame` in this case), so tools.deps picks `re-frame` 0.10.5 over 0.10.1.

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/clojure/tools.deps.alpha">clojure/tools.deps.alpha</a></strong></div><div>Contribute to tools.deps.alpha development by creating an account on GitHub.</div></blockquote>

**Comment by dmitryn** [comment]
@yenda i've tested this already, but you could test this too to make sure app runs fine.

**Comment by rasom** [comment]
just tested locally, it works

**Pull request merged**
