### PR TITLE
updated invite friends banner image

### LINKED ISSUE #19260: Messages - Messages home issues
# Design Feedback 2.27

## [Messages] Messages home page issues
Figma frame of the Review [here](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj/Release-Reviews?type=design&node-id=7%3A111976&mode=design&t=hS39AbDcBnA1KjAm-1)

- **Status bar isn't visible** [[comment](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj?node-id=7:111976&mode=design#711383498)] tracked here: https://github.com/status-im/status-mobile/issues/15260
- **Illustration in the _Invite friends_ card** [[comment](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj?node-id=7:111976&mode=design#716254834)] needs to be updated

Screenshot 2024-03-15 alle 09 45 38

>
- **Date and icon alignment** [[comment](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj?node-id=7:111976&mode=design#716257387)] next to the contact name in the _Recent_ tab is wrong
- **Vertical spacing** [[comment](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj?node-id=7:111976&mode=design#728610632)] between contacts in the _Contacts_ list tab doesn't match design

Screenshot 2024-03-15 alle 09 46 12

### Reproduction

1. Open the Status app
2. Go to the Messages home page

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS
- Devices in the screenshots: iPhone 15 Pro Max, iPhone 13

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by jo-mut**
fixes https://github.com/status-im/status-mobile/issues/19260

### Summary
Simple pr to update the invite friends banner image on message home screen

### Before and after screenshots comparison

status: ready

### CODE REVIEW

**Review by mohsen-ghafouri — APPROVED** [review]

**Comment by jo-mut** [comment]
@mohsen-ghafouri just checking with you that its okay to skip manual qa as this is just replacing the banner. I added the label `skip-manual-qa`

**Comment by mohsen-ghafouri** [comment]
@jo-mut I believe so

**Comment by yevh-berdnyk** [comment]
hi @jo-mut , thanks for the PR! E2E failures are known and not related

**Review by ibrkhalil — APPROVED** [review]

**Review by Francesca-G — APPROVED** [review]
Looks good to me 👍

**Pull request merged**
