### PR TITLE
Update end-end test report for Github

### LINKED ISSUE #3433: Improve Github test report for end-end tests
## Summary
Our current report is really long and maybe hard to read. Having in mind that we are going to extend our test suite, we need to make sure the test report is still easy to understand and does not clutter thread of a Github issue.

[Example of current test report](https://github.com/status-im/status-react/pull/2962)

## Who should read end-end test report and why?

* developers (internal and external contributors)
   * high level overview of end-end tests that were executed
   * understand which tests failed
   * have link to full report (and video) to dig into why the tests failed
* test engineers
   * same reasons as developers + understand what tests were executed to be aware of the exact test coverage

### PR DESCRIPTION
**Pull request by lukaszfryc**
fixes #3433 + refactors `TestData`

status: ready

### CODE REVIEW

**Comment by lukaszfryc** [comment]
- [ ] test

**Comment by lukaszfryc** [comment]
@antdanchenko to see the latest version of report  please start `pr` tests when sandbox job is fixed.

**Comment by lukaszfryc** [comment]
Also, since everyone including external devs receives report comment by email, I think we need to polish it a bit more. Here is how it currenty look like:
image
As you may see, it's long which makes it unreadable.

How about we have it in this version:
image
Here I added numers to tests and show only 3 last relevant steps in case of failure. For successful tests the report would only contain links to device sessions.

I feel that listing all low level steps (clicks, taps) does not bring much value. I don't see anyone looking at the github comment and checking what low level steps were executed. We could always include link to Jenkins console or Jenkins test results for low level report.

@antdanchenko wdyt?

**Comment by Serhy** [comment]
Makes sense to make email shorter, @lukaszfryc ! 
I'd even say to get rid of "Last test steps:" + actual steps part for emails for failed test. Full picture of test execution could be seen in github for example (or navigation right to Device Sessions) and to keep three-four last actions doesn't bring too much value. 

So for me it's fine to have it similar to:
```
1. test_sign_in. Pass!
Device sessions:
 * Device 1
 * Device 2

2. test_log_out. Something went wrong here :(
Error: [actual_error_message_here]
See device sessions:
 * Device 1
 * Device 2

......
......
......
```

**Comment by lukaszfryc** [comment]
@Serhy big thanks for the feedback! We can get rid of the test steps in mail but it means they will not appear on github as well. Anyway, it makes sense to shorten them. So I'd suggest - let's go in that direction and see how it works.

The last test automation framework I worked with also had idea of **test steps**. But, they were much more high level / business level, like "login in as {email}, {password}", "start chat with {name}". The taps, typing, etc. were considered as **actions**. A high level **test step** consisted of multiple user **actions**. This way we were able to have clear understanding of what is done in a test. Reports were also shorter. We may consider this in our framework too.

**Comment by lukaszfryc** [comment]
@antdanchenko @yevh-berdnyk how is it going with the review? Would be great to merge this PR as soon as possible :)

**Comment by antdanchenko** [comment]
I am checking 80% of `Device Sessions` during reviewal of tests results
On my opinion it makes sense to move `Device Sessions` on the same level as `Error` for failed tests, instead of having them under `Click to expand full logs`

@lukaszfryc wdyt?

**Review by yevh-berdnyk — APPROVED** [review]

**Review by antdanchenko — APPROVED** [review]

**Pull request merged**
