### PR TITLE
chat: order chat list by most recent (#680)

### LINKED ISSUE #680: Chat list not ordered by most recent
Most recently received messages do not appear at the top of the chat list.

https://instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/48?status=New

### PR DESCRIPTION
**Pull request by tpatja**
fixes #680

### CODE REVIEW

**Comment by Smokyish** [comment]
Thank you for the contribution @tpatja!

**Comment by jarradh** [comment]
please pull into `develop`, not `master`, thanks :)

**Comment by tpatja** [comment]
Will do. Should we generally use `develop` for PRs? If that is the case the [docs](https://wiki.status.im/contributing/development/building-status/#contributing) should probably be updated.

**Comment by jarradh** [comment]
Yes it needs to be updated, sorry about that

**Comment by tpatja** [comment]
No worries. Here's a new one against develop: https://github.com/status-im/status-react/pull/715.
Doc update PR: https://github.com/status-im/wiki.status.im/pull/3

**Pull request closed without merging**
