### PR TITLE
Fix android minify and macos debug

### PR DESCRIPTION
**Pull request by pedropombeiro**
[comment]: # (Please replace ... with your information. Remove < and >)
[comment]: # (To auto-close issue on merge, please insert the related issue number after # i.e fixes #566)

### Summary

[comment]: # (Summarise the problem and how the pull request solves it)
This PR fixes a couple of issues I came across today, namely Android CI builds not being minified, and macOS debug builds still looking for gcc instead of clang (should have been done in fca01891baae35146216e3f9e0aaa90341ad2dad).

status: ready

### CODE REVIEW

**Comment by ghost** [comment]
### Pull Request Checklist
- [x] Have you updated the documentation, if impacted (e.g. [docs.status.im](https://docs.status.im/docs/build_status.html))?

**Review by jakubgs — APPROVED** [review]

**Review by yenda — APPROVED** [review]

**Comment by pedropombeiro** [comment]
Also added disabling of automatic PNG optimization to ensure reproducible builds, as explained in https://f-droid.org/en/docs/Reproducible_Builds/

**Comment by jakubgs** [comment]
https://github.com/nihgwu/react-native-dva-starter/issues/13#issuecomment-313110578

**Comment by jakubgs** [comment]
The thing is, I don't see any errors there, just warnings. And we already have a `proguard-rules.pro` file:
https://github.com/status-im/status-react/blob/develop/android/app/proguard-rules.pro

**Comment by jakubgs** [comment]
I love how the link suggested by the warning doesn't exist:
https://www.guardsquare.com/en/products/proguard/manual/troubleshooting-2#unresolvedclass

**Comment by jakubgs** [comment]
There's this:
https://www.guardsquare.com/en/products/proguard/manual/troubleshooting

**Comment by jakubgs** [comment]
https://www.guardsquare.com/en/products/proguard/manual/troubleshooting
>Note: the configuration refers to the unknown class '...'
>Your configuration refers to the name of a class that is not present in the program jars or library jars. You should check whether the name is correct. __Notably, you should make sure that you always specify fully-qualified names, not forgetting the package names.__

**Comment by jakubgs** [comment]
There's 3 of those:
```
Note: the configuration refers to the unknown class 'com.facebook.react.uimanager.UIProp'
Note: the configuration refers to the unknown class 'sun.misc.Unsafe'
Note: the configuration refers to the unknown class 'com.google.android.gms.common.api.internal.BasePendingResult$ReleasableResultGuardian'
Note: the configuration refers to the unknown class 'sun.misc.Unsafe'
```

**Comment by jakubgs** [comment]
Based on some reading I did([example](https://medium.com/androiddevelopers/troubleshooting-proguard-issues-on-android-bce9de4f8a74)) I think we need someone better versed in the Android codebase to fix the ProGuard rules. It seems to be pretty critical to know which classes can be handled how by ProGuard.

**Pull request merged**
