### PR TITLE
[#4874]: Specified gas price is automatically reverted to default one if open Assets or any screen to specify Recipient

### LINKED ISSUE #4874: Specified gas price is automatically reverted to default one if open Assets or any screen to specify Recipient
### Description

*Type*: Bug

*Summary*: Gas price specified by the user is automatically reverted to the default value if 
1. open any of screens to specify Recipient (e.g. Contacts). There is no need to select other recipient, just opening and closing the screen is enough to cause Gas price change
2. open Assets screen. Also no need to select other asset

Note that Gas limit value is not changed. So, 2 fields on Transaction screen behave in different way: Gas price is reverting to default value when Gas limit does not.

#### Expected behavior
Values in all fields on Send Transaction and Transaction Fee screens stay the same if 
1. open Assets screen but do not do any changes or select same asset as already selected
2. open Recipient -> Contact and close it or select some recipient
3. open Recipient -> Enter recipient value and close it or provide valid or invalid value for recipient address
4. special case: Recipient -> scan QR there are 2 cases:
4.1 Asset = ETH, scan QR code does not change asset and it stays ETH: we should keep values in Gas limit and Gas price as they were before scan
4.2 Asset != ETH (so some token, e.g. SNT), scan QR: it's expected that Asset will be changed to ETH, amount field will be cleared. In this case we can revert values in Gas limit and Gas price to default values

#### Actual behavior
1. If scan QR code when Asset = ETH then values in Gas limit and Gas price are reverted to default values automatically
2. In all other cases only Gas price is reverted back to default value:
2.1 if open Recipient -> Contacts, Recipient -> Enter recipient address 
2.2 if open Assets

### Reproduction
from 00:18 https://app.testfairy.com/projects/4803622-status/builds/8500248/sessions/4394466347/?accessToken=Cw1vyX1bPFQuq9Z0e3Z33-2TqSU
- Open Status
- Open Wallet -> Send transaction
- Open Advanced and change values for Gas limit and Gas price
- Open Assets do not change anything and close it. Check values in advanced
- Repeat checks for modified Gas limit and Gas price specified in Expected behavior section

### Additional Information
* Status version: nightly June 20
* Operating System: Android and iOS

<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803622-status/builds/8500248/sessions/4394466347/?accessToken=Cw1vyX1bPFQuq9Z0e3Z33-2TqSU">TestFairy: Status 0.9.21 (6078) @2018</a></strong></div></blockquote>

### PR DESCRIPTION
**Pull request by alwx**
Fixes #4874
Status: ready

### CODE REVIEW

**Review by jeluard — APPROVED** [review]

**Review by goranjovic — APPROVED** [review]

**Review by flexsurfer — APPROVED** [review]

**Review by janherich — APPROVED** [review]

**Comment by asemiankevich** [comment]
1. Gas price is changing when i scan wallet qr code as recipient. Steps:
- open wallet 
- tap send transaction
- open advanced and check the values
- OPTIONAL: modify gas price and tap Done
- tap specify recipient and scan `request` wallet QR
image
- check Advanced (gas limit and gas price). Transaction fee and gas price are changed. 

https://app.testfairy.com/projects/4803590-status/builds/8502876/sessions/4394553174/?accessToken=SpJo6iJ1VLuioMtcmSQuN9te9M4

<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803590-status/builds/8502876/sessions/4394553174/?accessToken=SpJo6iJ1VLuioMtcmSQuN9te9M4">TestFairy: Status 0.9.21 (6095) @2018</a></strong></div></blockquote>

<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803590-status/builds/8502876/sessions/4394553174/?accessToken=SpJo6iJ1VLuioMtcmSQuN9te9M4">TestFairy: Status 0.9.21 (6095) @2018</a></strong></div></blockquote>

**Comment by asemiankevich** [comment]
@alwx pay attention that `gas limit` should also remain the same when scanning QR. It changes now. (gas price stays same)

**Comment by asemiankevich** [comment]
@alwx selecting `same` asset resets gas limit to the default

- Open wallet
- Change gas limit / gas price on sender side
- Scan code of recipient (request wallet QR)
- Pay attention gas limit and gas price are not changed
- Tap asset - tap ETH

NOTE: happens even if u dont scan code.

Result: gas limit has been changed to default when i select `same` asset. Gas price stays not changed

TF: https://app.testfairy.com/projects/4803590-status/builds/8503466/sessions/4394587774/?accessToken=Q58tA/JYOXa/IZ0WcfjiY4ybqbs

<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803590-status/builds/8503466/sessions/4394587774/?accessToken=Q58tA/JYOXa/IZ0WcfjiY4ybqbs">TestFairy: Status 0.9.21 (6101) @2018</a></strong></div></blockquote>

**Comment by asemiankevich** [comment]
looks good to me

**Pull request merged**
