### PR TITLE
improve ethereum.send

### LINKED ISSUE #13121: Website with MetaMask support does not work with Status Wallet
# Bug Report

_I assume that we aim for Status Wallet to work with all dApps, even if they display MetaMask support only_

This is related to an NFT claim that seem to have worked for several other users (presumably using MetaMask).

## Problem 

1. Open https://www.iwwon.com/newworldorder
2. Click on "Cyrptomories Owners"
3. Tap "Sign In" on "Sign to Metamask" modal
4. tap "Allow"
5. Tap "Cryptomories Owners"
6. Select Morie
7. Tap "Claim 1"

#### Expected behavior

8. Open window to sign action

#### Actual behavior

8. Nothing happens

### Reproduction

Please let me know if I can do anything to provide more details.

### Additional Information

- Status version: 1.18.2
- Operating System: Android

### PR DESCRIPTION
**Pull request by qfrank**
fixes #13121

### CODE REVIEW

**Review by flexsurfer — APPROVED** [review]

**Comment by pavloburykh** [comment]
@qfrank thank you for your contribution. Got a couple of e2e that are failing due to PR changes, please take a look at the ISSUE 1

### ISSUE 1 Sign message method does not result in appearing signing pop up in simpldapp

**Description:** for purposes of testing different transaction methods we are using test app https://simpledapp.eth.link/ (this link should be used for Goerli network). Here is also a link to app repo https://github.com/status-im/simple-dapp In a few words, this app gives us a possibility to call different methods via it's interface. 

So one of such methods which is being tested by [these](https://github.com/status-im/status-mobile/pull/13724#issuecomment-1195314939) failed e2e is "Sign message". Calling "Sign message" method should result in opening signing pop up which doesn't happen in current PR builds. 

**Steps:** 

1. On PR build go to browser
2. Open https://simpledapp.eth.link/
3. In appeared pop up tap "Allow" to connect wallet
4. Tap "Transactions"
6. Tap "Sign message"
7. Check if signing pop up appears

**Actual result**: signing pop up does not appear. 

https://user-images.githubusercontent.com/97245802/181048122-60258687-fb09-40bc-848b-b0973b190cf2.mp4

**Expected result:** signing pop up appears. 

https://user-images.githubusercontent.com/97245802/181048318-3a98ef10-5600-4109-8cfb-2f6314325ce8.mp4

I am not sure if this can be considered a bug or our test simpldapp just needs some changes in terms of this PR improvements. Maybe @flexsurfer can assist on this question.

**Comment by qfrank** [comment]
> pavloburykh

Hi @pavloburykh , thanks for reporting, i tried remote branch `develop`, didn't reproduced this issue, so it's probably relate to my PR, i'll look into it

**Comment by qfrank** [comment]
hi @pavloburykh , pls try the latest PR, thanks!

**Comment by pavloburykh** [comment]
@qfrank thanx for fixing ISSUE 1. Please, take a look at a new ISSUE 2

### ISSUE 2 Sign pop ups stopped appearing in some other apps

As an example of such apps I tested crytokitties.co and opensea.io 
Sign pop ups appear when connecting wallet on latest nightly app but stopped appearing in current PR builds

**Steps (cryptokitties.co):**
1. Create/restore multіaccount
2. Open browser
3. Go to cryptokitties.co
4. Tap Start in the right upper corner
5. Tap "Allow" in appeared bottom sheet to connect wallet
6. Observe if Sign pop up will appear to confirm wallet connection

**Actual result:** Sign pop up does not appear. It is impossible to perform purchases. Tapping on Sign up button does not result in appearing sign up modal (See video below)

https://user-images.githubusercontent.com/97245802/181208596-b9c25f36-5473-44d0-ac03-c1bfa351fd89.mp4

**Expected result:** after connecting wallet - sign up modal should appear. User fills up and send sign up form (with email/nickname). After sending registration form the sign pop up appears and user is able to confirm wallet connect action (see video below showing expected behaviour). 


https://user-images.githubusercontent.com/97245802/181209600-bbe6edfe-4bca-4252-abd7-2738bf67e10b.mp4

Similar issue happens to the opensea.io app. 
**Actual result:** 

https://user-images.githubusercontent.com/97245802/181209977-e059756a-4c8d-487d-8a3d-61601dce3545.mp4

**Expected result:** 


https://user-images.githubusercontent.com/97245802/181210088-a4adaf4c-be2a-4a05-9f45-5e9886504e12.mp4

Guys @qfrank @flexsurfer , overall I'd like to discuss if we really need to implement this improvements, because I have some doubts and would like know your opinion. 

My doubts are based on following points:

1. Current PR may result in regression in different apps (as happened in case described in ISSUE 2). As we are unable to check all variety of apps - then we can't be sure that regression will not appear in any of them. I've checked only couple of them and problem was found.  

2. Current PR in fact does not fix initial issue described [here](https://github.com/status-im/status-mobile/issues/13121#issue-1145161726) As was [mentioned](https://github.com/status-im/status-mobile/issues/13121#issuecomment-1196310601) today by @D4nte he is still reproducing the issue. 

3. Current PR fixes appearing sign pop up here https://connect.collab.land/ (which is also was reported as part of the [issue](https://github.com/status-im/status-mobile/issues/13121#issuecomment-1049306158) BUT signing action for this app still fails and, as was mentioned [here](https://github.com/status-im/status-mobile/issues/13121#issuecomment-1195018272) an [here](https://github.com/status-im/status-mobile/issues/13121#issuecomment-1195612561) is not Status related issue. 

So how do you think, are current PR's improvements cover potential risks of regression that can be introduced by it?

**Comment by flexsurfer** [comment]
i'm always against adding "hacks" in our code for specific dapps, we should drop `send` support long time ago, we should instead motivate dapps to use standarts

**Comment by qfrank** [comment]
i prefer continue improve ... i admit current PR is not good enough, but i promise will change it to better and better, i see the old implementation of `ethereum.send` trying to delegate to `ethereum.request`, and `ethereum.request` trying to delegate (back) to `ethereum.sendSync`, looks like a little confused, these 3 methods may have commons but shouldn't "interact" directly or it should behave more clearly. I agree "we should instead motivate dapps to use standarts", but legacy method should have a right implementation like metamask at least, thoughts? :) @pavloburykh @flexsurfer

**Comment by qfrank** [comment]
i guess `7adeee3` would be the last `improvement`

**Comment by qfrank** [comment]
@pavloburykh issue 2 fixed, i guess `7adeee3` will be the last commit

**Comment by flexsurfer** [comment]
`like metamask at least` it's the cause of all issues, most dapps work only in MM because of this and we shouldn't make it worse by implementing like metamask, there are standards 

https://twitter.com/vitalikbuterin/status/1531771109602799617
```
[vitalik.eth](https://twitter.com/VitalikButerin)
[@VitalikButerin](https://twitter.com/VitalikButerin)
Remember that you should always test your dapp with at least one non-metamask wallet (eg. Brave, Status browser). Make sure your dapp conforms to ethereum standards, and not just to accidental properties of one particular wallet!
```

**Comment by pavloburykh** [comment]
@qfrank ISSUE 2 fixed, thanks. At this moment I haven't found other issues. As I have mentioned, there is no guarantee that we will not have regression in some other apps. So its up to you guys @flexsurfer @qfrank  to decide wether to merge this PR or not.

**Comment by flexsurfer** [comment]
`there is no guarantee that we will not have regression in some other apps. ` yes my main concern, from my experience i wouldn't make any changes to this file

**Comment by pavloburykh** [comment]
> `there is no guarantee that we will not have regression in some other apps. ` yes my main concern, from my experience i wouldn't make any changes to this file

agree

**Review by flexsurfer — APPROVED** [review]

**Comment by flexsurfer** [comment]
@pavloburykh could we check most popular dapps? just make sure they work? without sending transactions

**Comment by pavloburykh** [comment]
> @pavloburykh could we check most popular dapps? just make sure they work? without sending transactions

sure, I will check some more top rated dapps and give feedback

**Comment by pavloburykh** [comment]
> @pavloburykh could we check most popular dapps? just make sure they work? without sending transactions

so, some of apps that have been checked are: Opensea, Cryptokitties, 1inch.exchange, Kyberwap, Zerion, Uniswap etc. I didn't send any trans, just went until signing step. Overall I didn't notice any issues with those apps that I checked.

**Comment by flexsurfer** [comment]
thanks

**Pull request merged**
