### PR TITLE
chore_:Add keyUID to table when migrating from v1 to v2

### LINKED ISSUE #20046: Add keyUID to table when migrating from v1 to v2
When migrating from v1 to v2, there's a field that is not being computed for the `accounts` table:

https://github.com/status-im/status-go/blob/c9ee0e04c25d9079bf8a4b9617ad10df6d33fff8/appdatabase/migrations/sql/1683627613_accounts_and_keycards_improvements.up.sql#L8

This `CHECK` constrainst fails from account of the app v1, since `key_uid` is blank.

To overcome this we need a migration outside our normal migration system to calculate `keyUID`:
```
	keyUID := sha256.Sum256(crypto.FromECDSAPub(&a.privateKey.PublicKey))
```

If that can be done at the `SQL` layer, better, but not sure it's feasible/possible. It would have to be a migration outside our normal migration process. 

I can provide some databases for the old version and there's already some tests running them, ping me for the setup.

### PR DESCRIPTION
**Pull request by qfrank**
closes #20046

relate status-go [PR1](https://github.com/status-im/status-go/pull/5203)  [PR2](https://github.com/status-im/status-go/pull/5208)

### Summary
This PR's major goal is to ensure old mobile user can login normally after upgrading from v1 to v2

### Testing notes
- you can use this [PR](https://github.com/status-im/status-mobile/pull/20123) build to create old mobile account.
then install current PR build to upgrade. after upgrading, check if old mobile user can login normally.
- install latest `develop` build to create an account, then install current PR build to override. after that, check if the created account can still login normally.
- after upgrading from V1 to V2, pls check if we can send/receive transaction for the wallet accounts. ideally, we should check each type of wallet account(imported from `seed phrase`/`private key`), `default` and `generated` wallet account as well

#### Platforms

- Android
- iOS

status: wip

### CODE REVIEW

**Review by flexsurfer — APPROVED** [review]

**Comment by pavloburykh** [comment]
Hey @qfrank! Could you please go and mobile branches? After that we will continue testing. Thank you!

**Comment by qfrank** [comment]
> Hey @qfrank! Could you please go and mobile branches? After that we will continue testing. Thank you!

Hi @pavloburykh , thank you for you attention! However, corresponding status-go PR didn't get approved yet, may need more time to investigate, i'll mention you if it's ready to do a manual QA.

**Comment by pavloburykh** [comment]
> > Hey @qfrank! Could you please go and mobile branches? After that we will continue testing. Thank you!
> 
> Hi @pavloburykh , thank you for you attention! However, corresponding status-go PR didn't get approved yet, may need more time to investigate, i'll mention you if it's ready to do a manual QA.

Thank you @qfrank! I will then temporary remove 'request-manual-qa` label. Please, re-add it once PR is ready for manual qa.

**Comment by VolodLytvynenko** [comment]
hey. @qfrank could you please rebase current and status go PR? Thanx

**Comment by qfrank** [comment]
> hey. @qfrank could you please rebase current and status go PR? Thanx

Hi @VolodLytvynenko , rebased.

**Comment by VolodLytvynenko** [comment]
hi @qfrank thank you for PR

How should the display name be shown in such a case? After the migration, the user in the chat shows the old chat key instead of the display name. Other users see such a user as a compressed chat key. Is it expected?

### Steps:
1. Create new user in old apk
2. Install new apk
3. Send messages in chat

### Actual result:
The current user sees his old chat key in the chat
image

How migrated user is shown for other users
image

**Comment by VolodLytvynenko** [comment]
## PR_ISSUE 1: The wallet is shown as white

### Steps:
1. Create new user in old apk
2. Install new apk

### Actual result:
The wallet is shown as white.
image

### Expected result:
The wallets should be shown with the default color (blue).
image

**Comment by VolodLytvynenko** [comment]
> install latest develop build to create an account, then install current PR build to override. after that, check if the created account can still login normally.

@qfrank perhaps I didn't understand this step correctly. Could you please clarify? I'm unsure how to overwrite the current PR with the development build, as the device treats these two builds as separate apps.image

**Comment by VolodLytvynenko** [comment]
> > install latest develop build to create an account, then install current PR build to override. after that, check if the created account can still login normally.
> 
> @qfrank perhaps I didn't understand this step correctly. Could you please clarify? I'm unsure how to overwrite the current PR with the development build, as the device treats these two builds as separate apps.image


Apologies. I can use some other rebased PRs to test this case :)

**Comment by VolodLytvynenko** [comment]
@qfrank Is this PR intended to check for the successful migration of other data such as communities, chats, contacts, messages, etc.?

**Comment by qfrank** [comment]
> @qfrank Is this PR intended to check for the successful migration of other data such as communities, chats, contacts, messages, etc.?


>  after upgrading from V1 to V2, pls check if we can send/receive transaction for the wallet accounts. ideally, we should check each type of wallet account(imported from `seed phrase`/`private key`), `default` and `generated` wallet account as well

I think this ^ is the most important we want to check ATM. cc @cammellos

**Comment by qfrank** [comment]
> hi @qfrank thank you for PR
> 
> How should the display name be shown in such a case? After the migration, the user in the chat shows the old chat key instead of the display name. Other users see such a user as a compressed chat key. Is it expected?
> 
> ### Steps:
> 1. Create new user in old apk
> 2. Install new apk
> 3. Send messages in chat
> 
> ### Actual result:
> The current user sees his old chat key in the chat image
> 
> How migrated user is shown for other users image

this issue seems relate to this exist [one](https://github.com/status-im/status-mobile/issues/20203)

**Comment by VolodLytvynenko** [comment]
@qfrank Got. Thank you for the clarification. Take a look at one more issue. Shoud it be fixed in scope of the current PR?

## PR_ISSUE 1: Unable to create additional account after updating to V2

### Steps:
1. install old v1 from this [PR](https://github.com/status-im/status-mobile/pull/20123)
2. Create a new account.
3. Update to the current build PR.
4. Attempt to create an additional account in the wallet.

### Actual result:
Additional acount can't be created

https://github.com/status-im/status-mobile/assets/52490791/d4a1a3a9-06c4-46ba-b210-2ba068d0fe56

### Expected result:
Additional account is  created

### OS: 
IOS, Android
### Devices:
- Pixel 7a, Android 13

### Logs
[Status-debug-logs.zip](https://github.com/user-attachments/files/15531492/Status-debug-logs.zip)

**Comment by qfrank** [comment]
> @qfrank Got. Thank you for the clarification. Take a look at one more issue. Shoud it be fixed in scope of the current PR?
> 
> ## PR_ISSUE 1: Unable to create additional account after updating to V2
> ### Steps:
> 1. install old v1 from this [PR](https://github.com/status-im/status-mobile/pull/20123)
> 2. Create a new account.
> 3. Update to the current build PR.
> 4. Attempt to create an additional account in the wallet.
> 
> ### Actual result:
> Additional acount can't be created
> 
>  der.mp4 
> ### Expected result:
> Additional account is created
> 
> ### OS:
> IOS, Android
> 
> ### Devices:
> * Pixel 7a, Android 13
> 
> ### Logs
> [Status-debug-logs.zip](https://github.com/user-attachments/files/15531492/Status-debug-logs.zip)

will fix it in a separate PR, already existing [issue](https://github.com/status-im/status-mobile/issues/20048) @VolodLytvynenko

**Comment by VolodLytvynenko** [comment]
> > @qfrank Got. Thank you for the clarification. Take a look at one more issue. Shoud it be fixed in scope of the current PR?
> > ## PR_ISSUE 1: Unable to create additional account after updating to V2
> > ### Steps:
> > 
> > 1. install old v1 from this [PR](https://github.com/status-im/status-mobile/pull/20123)
> > 2. Create a new account.
> > 3. Update to the current build PR.
> > 4. Attempt to create an additional account in the wallet.
> > 
> > ### Actual result:
> > Additional acount can't be created
> > der.mp4
> > ### Expected result:
> > Additional account is created
> > ### OS:
> > IOS, Android
> > ### Devices:
> > 
> > * Pixel 7a, Android 13
> > 
> > ### Logs
> > [Status-debug-logs.zip](https://github.com/user-attachments/files/15531492/Status-debug-logs.zip)
> 
> will fix it in a separate PR, already existing [issue](https://github.com/status-im/status-mobile/issues/20048) @VolodLytvynenko

@qfrank Ok. Thank you. No issues from my side. PR is ready to be merged

**Comment by qfrank** [comment]
Hi @VolodLytvynenko , can we send/receive transaction with this PR after upgrading from V1 to V2? especially for imported wallet account via seed phrase using V1?

**Comment by VolodLytvynenko** [comment]
> Hi @VolodLytvynenko , can we send/receive transaction with this PR after upgrading from V1 to V2? especially for imported wallet account via seed phrase?

@qfrank yes. Transactions go well

**Comment by VolodLytvynenko** [comment]
hi @qfrank [issue 1](https://github.com/status-im/status-mobile/pull/20151#issuecomment-2144678790) has been fixed. However, an additional issue related to derived accounts creation still exists.

## PR_ISSUE 2: Unable to create derived accounts for accounts created in V1  using seed phrase or private key.

### Steps:
1. install old v1 from [this PR](https://github.com/status-im/status-mobile/pull/20123) 
2. Create an additional account by importing a seed phrase.
3. Create another account via a private key.
4. Update to the current build PR.
5. Attempt to create derived accounts for the account imported from the seed phrase.
6. Attempt to create derived accounts for the account created via the private key.

### Actual result:
Derived accounts cannot be created for accounts imported from the seed phrase or created via private key.

### Expected result:
Derived accounts should be creatable for accounts imported from the seed phrase or created via private key.

### Devices:
- Pixel 7a, Android 13

### Logs
[Status-debug-logs.zip](https://github.com/user-attachments/files/15584488/Status-debug-logs.zip)

**Comment by qfrank** [comment]
> hi @qfrank [issue 1](https://github.com/status-im/status-mobile/pull/20151#issuecomment-2144678790) has been fixed. However, an additional issue related to derived accounts creation still exists.
> 
> ## PR_ISSUE 2: Unable to create derived accounts for accounts created in V1 using seed phrase or private key.
> ### Steps:
> 1. install old v1 from [this PR](https://github.com/status-im/status-mobile/pull/20123)
> 2. Create an additional account by importing a seed phrase.
> 3. Create another account via a private key.
> 4. Update to the current build PR.
> 5. Attempt to create derived accounts for the account imported from the seed phrase.
> 6. Attempt to create derived accounts for the account created via the private key.
> 
> ### Actual result:
> Derived accounts cannot be created for accounts imported from the seed phrase or created via private key.
> 
> ### Expected result:
> Derived accounts should be creatable for accounts imported from the seed phrase or created via private key.
> 
> ### Devices:
> * Pixel 7a, Android 13
> 
> ### Logs
> [Status-debug-logs.zip](https://github.com/user-attachments/files/15584488/Status-debug-logs.zip)

@VolodLytvynenko  thank you for your feedback! I want to merge current PR since it's been existing for a while and then create separate PR to fix it. WDYT?

**Comment by VolodLytvynenko** [comment]
> @VolodLytvynenko thank you for your feedback! I want to merge current PR since it's been existing for a while and then create separate PR to fix it. WDYT?

@qfrank Ok. Thanx to you! PR can be merged. Created a follow up https://github.com/status-im/status-mobile/issues/20350 related to issue 2

**Pull request merged**
