### PR TITLE
perf(login)!: Fix slow login by delaying messenger filters initialization

### LINKED ISSUE #20059: Slow app login
App login has become very slow. Sometimes it is okay, but sometimes can take up to 5 seconds. Both platforms are affected. 

**Steps:** 

1. Try logging the app. 
2. Perform re-logins until you face the issue. 

**Actual result:** 

We are facing login delay both after logout (re-login) and first login (when we open the app and login). Mind that login delay might have different rootcauses in case of login and re-login. 

https://github.com/status-im/status-mobile/assets/52490791/a4369ce7-207e-480d-a551-15875581006e

[logs (2).zip](https://github.com/status-im/status-mobile/files/15290999/logs.2.zip)

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by ilmotta**
Fixes https://github.com/status-im/status-mobile/issues/20059

### Summary

This PR fixes the slow login when users have joined large communities, such as the Status one. Related status-go PR https://github.com/status-im/status-go/pull/5229.

**Note**: This PR stayed in WIP for a while until we were sure the solution was reliable enough to deserve code reviews.

### About the fix

What we mean by "slow" is that the user was getting stuck on the login screen for almost 20s in some devices (even on iOS things were bad). And this entire process was happening in status-go, hence this PR is not about optimizing the client directly.

By "login" we mean the process to authenticate and initialize vital data in status-go. Setting up message filters can be slow with large communities, and that's exactly this part we moved out of the login phase in status-go. This step now happens implicitly when the client calls `wakuext_startMessenger`.

In a way, the solution makes sense because setting up filters isn't essential for the user to access other parts of the app, such as the Wallet, Settings, Profile, and Activity Center.

### Demo

Login goes fast now :)

[fast-login.webm](https://github.com/status-im/status-mobile/assets/46027/3b8912cf-383d-42a5-93fe-b22752b983f2)

### Once approved, can we merge this PR?

No. This PR and the status-go one can only be merged once we get the green light from Desktop team because there could be breaking changes for them, just as there were for us.

### How can we magically eliminate the login delay?

In reality, the time we used to spent during login, blocking the user, still happens, but it happens **in the background and after the user is redirected** to the home screen. This also means that, until the filters are established, all chats are still in their "loading skeleton state".

In terms of UX, this is probably fine as long as it doesn't take too long for this setup to finish in status-go. In the future, we have room to further optimize how filters are set up in status-go.

### Steps to test

This PR was already lightly QAed, but it is recommended to check regressions in these areas:

- User can see their data after login and can interact with it. That means chat, communities, contacts, contact requests, notifications, wallet accounts, etc.
- User is correctly redirected to the last opened screen.
- User can logout successfully.
- User can send and receive messages.
- User can sync.

status: ready

### CODE REVIEW

**Comment by ilmotta** [comment]
@churik, @qoqobolo, @pavloburykh, @cammellos: This PR build should theoretically solve the slow login issue. As we aligned yesterday, the plan is to merge PR https://github.com/status-im/status-mobile/pull/20164 before this one because it reduces the time to login and it's helpful even if the solution presented in this PR ends up not working.

QAs: Once you give the green light that the build solves the login problem, I'll open the PR for reviews, update status-go unit tests and coordinate with desktop if the PR is a breaking change. Just a light check on your end would help a lot. Then you can do a full QA after the PR goes out of WIP and gets dev approvals.

**Comment by churik** [comment]
@ilmotta,
### PR_ISSUE 1: Cannot sync with desktop 2.29 

I noticed one breaking change: the sync with the desktop failed and returned an error.

IMAGE 2024-05-28 14:46:24

[logs (85).zip](https://github.com/status-im/status-mobile/files/15469812/logs.85.zip)

We're currently checking on version 2.29. If we test the desktop builds with the same commit, it might resolve the issue. Unfortunately, we don't have a process in place to create status-desktop builds from status-go changes.

**Comment by ilmotta** [comment]
> ### PR_ISSUE 1: Cannot sync with desktop 2.29

Thanks a lot @churik. Because we'are delaying some parts of the messenger initialization (and it does prepare installations), this could be the cause of the sync failure.

I will investigate the problem 👍🏼

**Comment by churik** [comment]
### PR_ISSUE 2: no redirect to the last opened  channel  / chat
**Steps:**
1) restore or create multiaccount 
2) join any community, open channel view
3) reopen app
4) login 

**Expected result:**
will be redirected to channel view

**Actual result:**
redirected to home screen

**OS:** IOS, Android


### PR_ISSUE 3: after loading history chat view reloads by itslef
**Steps:**
1) restore or create multiaccount 
2) join status community 
3) reopen app
4) login > open general channel

**Expected result:**
can see the channel when I navigate to it

**Actual result:**

https://github.com/status-im/status-mobile/assets/4557972/4fa10136-f31d-4aaa-8b37-5da93841efa9

(17 sec to load, and then redirect to Status > general one more time)

**OS:** IOS, Android

Honestly, the issue where channel views take 15-18 seconds to load after login is just as noticeable as the slow login itself. We need to address this 17-second loading skeleton because it is highly visible. 

It's difficult to say which issue is the lesser of two evils.

cc @cammellos @ilmotta

**Comment by ilmotta** [comment]
> Honestly, the issue where channel views take 15-18 seconds to load after login is just as noticeable as the slow login itself. We need to address this 17-second loading skeleton because it is highly visible.
> 
> It's difficult to say which issue is the lesser of two evils.

I think the new solution is definitely better if we can make it work of course. The login step is a critical part of the funnel to grow our user base. And once the user logs in, they can use many other things in the app, not just chats, whereas the current solution (in develop) simply blocks users from using anything in the app.

We can (maybe) speed up how chats are processed in status-go in the future, but even if we manage to do that, it won't be as fast as not doing anything in the login (which is the new proposal). So @churik @cammellos, I think we should pursue this solution because it leads to the fastest possible login and the slow chat processing can be attacked separately.

**Comment by cammellos** [comment]
@ilmotta definitely we should load things once the user logs in, that's also in line with the fact that for 2.30 probably wallet will be the first tab, so it will be much less evident

**Comment by ilmotta** [comment]
### Update on 2024-05-29

- `ISSUE 1` about sync issue I could not reproduce, that is, I successfully synced from desktop to mobile in version [2.29.0-rc.6](https://github.com/status-im/status-desktop/releases/tag/untagged-980efc898c07f3b222ad) and from desktop revision 634591b69f58e0e9a9b2955dd195b53df72fee50 (an old one from 3 months ago I had around).
- Fixed `ISSUE 2` to redirect user to last chat.
- Fixed `ISSUE 3` to not reload chat once already open (root cause was the same as `ISSUE 2`.

----

@churik, could you check this issue using the latest version from GH releases, the one I used [2.29.0-rc.6](https://github.com/status-im/status-desktop/releases/tag/untagged-980efc898c07f3b222ad)? I'm asking you that because I successfully synced using two very different desktop versions, so something tells me syncing is working, at least sometimes (which is odd, I'd expect the changes I made in status-go to either always cause a failure or not). Also, which exact desktop git revision did you use, Android version, app flags, steps to sync, etc? Just so I can more faithfully try to reproduce. Thank you!

### Update on 2024-05-31

- Rebased to latest `develop` in status-go and rebased mobile PR.
- Finally reproduced sync error consistently. Error was fixed by initializing installations before the `node.login` event is emitted by status-go.

**Comment by pavloburykh** [comment]
@ilmotta thank you for your fixes!

I have just checked ISSUE 1 and unfortunately still getting error while syncing. I have used [latest (30.05) RC6 Desktop](https://github.com/status-im/status-desktop/releases/tag/2.29.0-rc.6) 

photo_2024-05-31 15 48 51

**Comment by pavloburykh** [comment]
@ilmotta ISSUE 1 (sync error) has been fixed for me in latest builds. Great job!

Will continue testing the rest on Monday, hopefully Waku issues will be fixed by that time.

**Comment by pavloburykh** [comment]
### QA Notes from @ilmotta 

```Things to watch out for in testing is anything related to sharding and contacts, just because I didn't test any of these things. They should work the same```

**Comment by pavloburykh** [comment]
@ilmotta please take a look at the following issue

### ISSUE 4 Contact requests are not delivered

**Preconditions:** User A and User B both are using current PR builds. 

**Steps:** 

1. User A sends contact request to User B
2. See if contact request is delivered to User B

**Actual result:** contact request is not delivered. 

[android_crReceiver.zip](https://github.com/user-attachments/files/15530927/android_crReceiver.zip)

[ios_crSender.zip](https://github.com/user-attachments/files/15530929/ios_crSender.zip)


https://github.com/status-im/status-mobile/assets/97245802/8a635dc3-fa09-426b-a8e6-3452a07842c4

**Comment by ilmotta** [comment]
@pavloburykh I'll verify ISSUE 4, thank you! By the way, have you checked other parts of the app? Are they working fine overall? Or did you stop testing as soon as you hit ISSUE 4?

**Comment by ilmotta** [comment]
@pavloburykh, `ISSUE 4` fixed.

I think this WIP PR proved to be successful in fixing the slow login. I feel confident enough we can promote both the status-go and mobile WIP PRs to be non-WIP, adapt status-go unit tests and get both PRs through the normal PR process, which after all will go through a normal QA cycle in the end.

For now, I think it's fine if you stop testing this WIP PR, so that your team avoids rework since you'll be testing this PR in the near future anyway once the PRs are approved in status-go and status-mobile.

Thanks QA team for all the help so far o/

**Comment by pavloburykh** [comment]
> @pavloburykh I'll verify ISSUE 4, thank you! By the way, have you checked other parts of the app? Are they working fine overall? Or did you stop testing as soon as you hit ISSUE 4?

Hi @ilmotta I have tried smoke checking other parts, but due to Waku issues I was unable to check properly. Also I have stopped testing once I have faced ISSUE 4 as this was a critical issue which can be considered as a criteria to quit testing until bug is addressed. 

So, as you have mentioned above - we will need to perform another round of checking once PR is approved. Currently we do not have a strong opinion if we want to include this PR in 2.29 release, probably we will have to postpone until 2.30 as we already crossed the deadline for releasing 2.29 (due to lot of found blockers) and all resources are focused on finishing release testing. cc @churik 

Thank you for your work on this PR @ilmotta

**Comment by pavloburykh** [comment]
@ilmotta thank you for great work! No issues from my side so I am moving PR forward. 

One thing: please, let me know in case this [issue](https://github.com/status-im/status-go/pull/5229#issuecomment-2154393264) will require fixes on go side. In this case I will need to re-test PR for regression. 

Also, before merging the PR it is better to make another e2e test run. I have just noticed that status - go [branch](https://github.com/status-im/status-go/pull/5229#issuecomment-2154393264) is very outdated (32 commits behind develop). So we need to run e2e against rebased branch (it can be done right before you will be ready for merging).

**Comment by pavloburykh** [comment]
oh, we still need to get this PR reviewed...Please, let me know if there will be any changes based on PR review. In this case I will also need to perform re-test.

**Comment by ilmotta** [comment]
@pavloburykh, thank you again for testing the build. Great news. Apparently desktop doesn't have regressions.

I'll definitely rebase and re-run e2e before merging. If it takes more than next Tuesday to get this PR approved, then it's probably prudent to have another quick QA pass just in case. Thanks for the reminder.

**Review by mohsen-ghafouri — APPROVED** [review]

**Review by smohamedjavid — APPROVED** [review]

**Comment by pavloburykh** [comment]
Hey @ilmotta! I have smoked checked the PR after rebasing, no issues from my side. Failed e2e are not PR related. Thank you again for great job! ready for merge.

**Comment by pavloburykh** [comment]
@qoqobolo thank you for identifying transaction issue! @ilmotta sorry, when I have checked failed e2e I ignored wallet tests failures, because they have been failing for a long time already but due to other reason, that's why I missed the bug.

**Comment by ilmotta** [comment]
> @qoqobolo thank you for identifying transaction issue! @ilmotta sorry, when I have checked failed e2e I ignored wallet tests failures, because they have been failing for a long time already but due to other reason, that's why I missed the bug.

Good thing it was found on time! I added the label `blocked` in the meantime.

**Pull request merged**
