### PR TITLE
Add screen with join public-chat

### LINKED ISSUE #11256: Show Starter Pack pending 1:1 referral invite
# Problem
When receiving a chat referral url (`https://join.status.im/u/chatkey?=invitecode`), the recipient can accept terms of the referral program to release a Starter Pack (and attribution to a referrer). Currently when the user taps Accept, there is no feedback confirming that a Starter Pack is released. As the transaction can take up to 30 min this can leave people confused about whether they will receive their Starter Pack.

- Show Pending state as previously designed and now technically feasible
- When tapping on `Pending` navigate to transaction history tab in wallet
cc @errorists for your confirmation and other ideas

States

### User story
- As a new user being informed that I will receive a Starter Pack I want to receive feedback showing the state of this transaction
- As a user I want to get more details on a pending transaction

## Future Steps
#11021

### LINKED ISSUE #11432: Show button to Join public chat on deep link
Follow up #11236 and PR #11418 

# Problem
Deep link to public chat has been introduced. This makes it easier to drive new users to relevant content and contacts. The downside is that public chats are more easily discoverable, can get spammed more easily and if spam is send to a public chat that causes the app the crash, the new user would be denied of using the app. A mitigation is to request users to Join a public chat, only fetching messages after an explicit Join.

### User story
As a user
I want to be pointed directly to a chat after creating an account
so that I can find out what to do in the app

As I user
I want to explicitly join the chat
so that if there is spam in the chat, the app doesn't crash without me being able to do anything about it

[Design](https://www.figma.com/file/brK5wYEsm82xbMz7V2orM3/Referral-program-UI-s?node-id=2%3A2)

Public Chat Deeplink - excl Starter Pack

## Acceptance Criteria
- Public chat view is opened after onboarding (welcome screen)
- Messages for public chat are only fetched after user taps Join

## Future Steps
- Add UI for referral link with StarterPack #11433

### LINKED ISSUE #11433: Show button to Accept Starter Pack on deep link to Public chat
Follow up to #11432 

# Problem
Deep link to public chat is intended for use with advertisers and influencers. Prior to introducing deep link to public chat, referral campaigns have been stopped following feedback that attributions were much lower than traffic (referral url use) provided by influencers and advertisers.

Allowing users to receive a Starter Pack in exchange for their attribution should increase attributions, as well as user retention.
_Previously StarterPack release for advertiser and influencer campaigns was too expensive. Gas prices are more favorable now and promo packs will be used to control number of Starter Packs being released_

### User stories
As a user
I want to receive a StarterPack when I join Status
so that I can try features and get crypto for trying out the app

As a user
I want to be pointed directly to a chat after creating an account
so that I can find out what to do in the app

As I user
I want to explicitly join the chat
so that if there is spam in the chat, the app doesn't crash without me being able to do anything about it

[Design](https://www.figma.com/file/brK5wYEsm82xbMz7V2orM3/Referral-program-UI-s?node-id=169%3A153)

Frame 55

## Acceptance Criteria
- User is shown button to Accept StarterPack and join public chat
- Accept Starter Pack behaves the same as referral deep link to 1:1 chat
- Messages for public chat are only fetched after user taps Accept and Join
- Dialog incl Accept and join button remains visible in pending or confirmed state
- User can join chat without accepting Starter Pack and attributing referrer by removing the chat from the chat list and adding it again manually

### PR DESCRIPTION
**Pull request by Ferossgp**
Fixes #11432
Fixes #11433
Fixes #11256 - except there is no redirect to the history tab as the transaction is not visible there (it appears only after confirmation)

### CODE REVIEW

**Comment by hesterbruikman** [comment]
Thanks @Ferossgp!

Gave it a test run, here are my findings. First seems a bug, second seems minor, but is important (copy and removing items).

- Issue 1: Enable notifications and welcome screen are skipped
     - reproduce: 
          - use PublicChatRegistration 
          - get click ID
          - create direct link
          - use direct link with clickID to onboard, don't touch screen after 'Create a password' > `Next`

- Issue 2: UI includes items and components from 1:1 referral (chat registration type)
     - Copy is more generic and doesn't refer to friend
Frame 49


Note just in case: We'd still also need the version below of deeplink with attribution to the referrer, but without Starterpack distribution
Public Chat Deeplink - excl Starter Pack

**Comment by Ferossgp** [comment]
Issue 1: Just to confirm, it is the same for all flows?

Issue 2: fixed

> but without Starterpack distribution 

It is already there, it is displayed if the link is set as non-rewardable

**Review by cammellos — APPROVED** [review]

**Comment by Serhy** [comment]
@Ferossgp thanks a lot for all fixes! 
Retested with the latest build (https://status-im-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-201211-143806-ef7cdb-pr-universal.apk) on Android 9

1) Public chat, no Starter pack: 
* Can create new account and redirect to public chat with 'Accept and Join' button. 'Terms and Conditions' link opens external Android browser as expected. If I tap 'Accept' button then public chat opens. 
It it possible to "bypass" attribution and still join public chat in natural way via `(+)` -> `Join public chat`. Can't think about any downsides of it apart that non-rewardable public chat link screwed stats because no `Attribution` increment
* No redirect if I create another account using the referral link (It opens Status -> Create new key -> .... onboarding ... -> Chats view)
2) Public chat + Starter pack:
* With new account redirect to public chat with `Accept and Join` button displayed. Accepting it sends ETHri (in Rinkeby) to address as expected.
* If I delete public chat and open referral link again in the same account - nothing appears on Chats view as expected
3) 1-1 chat invite + Starter pack:
* Redirect to 1-1 chat as before happens when open Status and create account from invite 1-1 referral link. Upon tap on 'Accept' there is a PN appears. English translation just need a tiny fix of typo (starter-pack-comming in en.json with double 'm')
Screenshot 2020-12-11 at 17 15 32

However there is no no `Pending...` view after Accept'ing Starter Pack. Notification appears but 1-1 chat view has no 'Pending...' button.

**Comment by Serhy** [comment]
I tested in Rinkeby with latest build https://status-im-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-201214-152612-848c4f-pr-universal.apk

**(1)**`Pending...` status now appears in 1-1 after Starter pack `Accept`ance. As well as notification letting now user that 'Starter pack' is on the way. 
However it keeps in `Pending...` all the time until re-login. I don't see in Transaction history note about ETHri received and have to admit I had to "force" ETHri appear by `Scan tokens` feature. Also STT amount in Rinkeby not visible at all (even after relogins) but it's present as transaction in Etherscan. 

Another bug **(2)** now is that there is a notification of `Starter pack on it's way` even for non-rewardable referrals (confirmed for Advertiser and for Public chat + no Starter Pack).
So when, for instance for public chat + no starter pack, I submit Accept (to share IP address) there is a notification about Starter pack appears (screenshot for 9704c62b828d3ccca1af invite code from test referral admin):
Screenshot 2020-12-14 at 21 42 11

**Comment by Ferossgp** [comment]
> However it keeps in Pending... all the time until re-login.

@Serhy I suggest then to always hide it as we can't provide reliability on that side.

**Comment by hesterbruikman** [comment]
@Ferossgp for transparency as we discussed in part on Discord. The notification currently does not wait for the transaction hash, correct?



> @Serhy I suggest then to always hide it as we can't provide reliability on that side.

That makes sense to me. Issue 1 seems to be out of scope of this PR and indeed makes it difficult for the UI to reliably update.

@Ferossgp looks like you fixed issue 2, correct?

@Serhy One thing I noticed yesterday, but haven't been able to reproduce, is that skipping the Welcome screen (and enable notifications) seemed to get me stuck on the Welcome screen lateron. I couldn't pinpoint at what point the screen appeared. But a final test to see if any issues with the welcome screen come up would be good. Some cases to verify
a) accepting StarterPack 
b) tapping out of the public chat without accepting to return later 
c) closing and reopening without accepting

**Comment by Serhy** [comment]
Latest build (https://status-im-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-201215-125538-5f7bae-pr-universal.apk)
tested on Android 9) 

1) Public chat registration without Starter Pack 
 * Navigate back-and-force after onboarding - keeps Public chat on Chats view
 * Tap 'Accept and Join' - joins the chat
 * Closing the app - no public chat is seen anymore
2) Public chat registration with Starter Pack
 * After onboarding - navigate to Chats and back - keeps the public chat and ability to accept Starter pack. 
 * Tap 'Accept and Join': Starter pack received to account, Attributions for referrer increased. Notification letting know user that "Starter pack on it's way" appears after tap on 'Accept and Join'
3) 1-1 chat + Starter pack
* Starter pack received to account,
* Attributions for referrer increased.
* Notification letting know user "Starter pack on it's way" appears after tap on 'Accept'. 
* In 1-1 chat there is a `Pending...` appears. BUT even after starter pack received (on Rinkeby network), - Pending state keeps staying in 1-1 chat until religion.
4) Advertiser registration 
* Poo-up with request to 'share IP' appears and if accepted - attribution increases

**Comment by Serhy** [comment]
Looks good now with last change in 1-1 chat: `Pending...` state disappears after Starter Pack accepted by user. Thanks @Ferossgp let merge.

**Pull request merged**
