### PR TITLE
feature #7266 - added buff token on xdai sidechain

### LINKED ISSUE #7266: Add new asset for Ethdenver event
This is for a custom token on XDAI network

we'll need address, name, symbol and icon image should be added 

For public release 0.9.34

### PR DESCRIPTION
**Pull request by goranjovic**
fixes #7266

### Summary:

Adds BUFF token on xdai sidechain 

### Steps to test:
- Open Status and switch to xdai
- try out new token

status: ready

### CODE REVIEW

**Review by jeluard — APPROVED** [review]

**Review by flexsurfer — APPROVED** [review]

**Comment by annadanchenko** [comment]
nice to include into 0.9.33 if we can verify it today (so no hotfix to be released later)

**Comment by rachelhamlin** [comment]
@annadanchenko agreed. Just waiting on some tokens...

**Comment by annadanchenko** [comment]
triggered e2e again, see https://ci.status.im/job/end-to-end-tests/job/status-app-end-to-end-tests/2307/

<blockquote><div><strong><a href="https://ci.status.im/job/end-to-end-tests/job/status-app-end-to-end-tests/2307/">Error 404 Not Found</a></strong></div></blockquote>

**Comment by annadanchenko** [comment]
> waiting on some tokens...

any news @rachelhamlin ?

**Comment by StatusSceptre** [comment]
Looks like we can get buffdai tokens by exchanging XDAI into Buffidai live here buffidai.io

**Comment by annadanchenko** [comment]
@StatusSceptre @rachelhamlin unfortunately, I can't open buffidai.io in Status app to exchange xDAI to buffdai. It asks for permission to connect to the wallet and then shows page with progress bar that does not move (at least for 10 minutes I've waited on iOS and 5 minutes on Android). I've switched to XDai chain.

log contains many ```StatusNativeLogs: [INFO:CONSOLE(258)] "Error: Given input "NaN" is not a number.", source: webpack:///./src/events.js? (258)```
Steps:
1. install Status app, create an account (it has 0 funds), 
2. switch to xDAI network (Profile -> Development mode -> Network -> xDAI)
3. tap + -> Open DApp -> type buffidai.io and press Enter
4. As soon as page asks for access to the wallet tap on Allow
5. wait. Note that for a second it shows some ui with wallet balance but then goes to progress bar that is not moving


Also tried on recovered account with some xDai in the wallet - have same issue 

### Logs
[Status.log](https://github.com/status-im/status-react/files/2829365/Status.log) (14,8 Mb!)

screenshot_20190204-193335

this where I'm blocked
screenshot_20190204-193528

**Comment by StatusSceptre** [comment]
@annadanchenko I believe you can access the buffidai network with a non-web3 browser to aquire tokens as it utilizes meta-tx's and a native connection to swap to xdai > buffidai 

I don't believe this website working in status browser is a requirement for the token usage. 

What's the correct address you need buffidai sent to? (It will operate on the XDAI network)

**Comment by annadanchenko** [comment]
need to check 
- sending token wallet/chat
- recover account with token
- not sure about any expected use cases of the token in the DApps for ETHDenver (cc @StatusSceptre @rachelhamlin )

**Comment by annadanchenko** [comment]
also note that there are some limitations on xdai chain (Transaction history is not shown for POA and DAI; xDai chain is not shown after upgrade) 

https://github.com/status-im/status-react/pull/6388#issuecomment-432549313

**Comment by annadanchenko** [comment]
@StatusSceptre atm 0 USD is shown as value of 1 BUFF. I'm not sure if it has any value and if yes then what would be enought to have some amount > 0.01 USD

 see BUFF transactions and 0 USD in picture below

screenshot_20190204-203606

**Comment by annadanchenko** [comment]
Works fine for
- sending token wallet/chat - can send BUFF from chat/wallet
- if recover account with token can see BUFF in wallet

Can't verify: non-zero USD value in chat (for request/send message) as for 1 BUFF it shows 0 USD

Looks like there is no USD value of BUFF token (checked with @pablanopete)

**Pull request merged**
