### PR TITLE
refactor: extract storenode cycle to go-waku

### PR DESCRIPTION
**Pull request by richard-ramos**
Requires:
- https://github.com/status-im/status-go/pull/5857

This PR is a refactor that extracts the storenode cycle logic from status-go to go-waku, since this logic shouldn't be part of the application layer but from the waku layer instead.

The areas affected by this change are the message history retrieval as well as automatically choosing a storenode

cc: @pavloburykh @churik

### CODE REVIEW

**Comment by pavloburykh** [comment]
@richard-ramos thanks for the PR. Please take a look at the issue. 

### ISSUE 1 Backed up data is not restored

**Steps:** 

1. Restore the user who has backed up some data (communities, contacts etc) 
2. See is data has been restored

**Expected result:** data has been restored

**Actual result:** data has not been restored

[Status-debug-logs - 2024-11-07T172023.712.zip](https://github.com/user-attachments/files/17663796/Status-debug-logs.-.2024-11-07T172023.712.zip)

**Comment by pavloburykh** [comment]
### ISSUE 2 Curated communities are not fetched in Discovery section

**Steps:** 

1. Login the account
2. Go to Discover communities sections
3. See if curated communities are fetched

**Expected result:** [curated communities ](https://curate.status.app/directory) are fetched

**Actual result:** curated communities not fetched

[Status-debug-logs - 2024-11-07T172237.909.zip](https://github.com/user-attachments/files/17663849/Status-debug-logs.-.2024-11-07T172237.909.zip)

https://github.com/user-attachments/assets/6cf7dbb5-daf5-4703-a002-c305444399cd

**Comment by pavloburykh** [comment]
### ISSUE 3 Communities are not fetched

**Steps:** 

1. Open any community link (for example https://status.app/c/CxOACiUKC2NvbW0gMDcgbm92EgZkc2Fkc2EYASIHIzQzNjBERioDAAECAw==#zQ3shemF4a752ACgbWXRCg1VC4PUARfc3THPpvLMCRQhpLyjR )
2. See if community is fetched

**Expected result:** community is fetched

**Actual result:** community not fetched

[Status-debug-logs - 2024-11-07T182443.341.zip](https://github.com/user-attachments/files/17666482/Status-debug-logs.-.2024-11-07T182443.341.zip)

https://github.com/user-attachments/assets/ecb3a293-97eb-45f1-9428-e396b6298ea8

**Comment by richard-ramos** [comment]
@pavloburykh, I just pushed a new commit with fixes for the observed issues
Thank you and sorry for the delay.

**Comment by pavloburykh** [comment]
@richard-ramos thank you for the PR. Tested and ready for merge.

**Comment by churik** [comment]
can be closed, as already merge to status-go

**Pull request closed without merging**
