### PR TITLE
Kotlinify `StatusOkHttpClientFactory.java`

### PR DESCRIPTION
**Pull request by siddarthkay**
### Summary

This PR converts  
`android/app/src/main/java/im/status/ethereum/StatusOkHttpClientFactory.java` to
`android/app/src/main/java/im/status/ethereum/StatusOkHttpClientFactory.kt`

#### Platforms
- Android

status: ready

### CODE REVIEW

**Comment by churik** [comment]
@siddarthkay If this PR doesn't require testing, you can merge it, as the e2e failed due to https://github.com/status-im/status-mobile/issues/18315

**Comment by siddarthkay** [comment]
yes @churik : unless the app is not crashing on install or account creation stage the changes in PR are good, It didn't crash when I tested on emulator, can you pls check once on your end? 
Meanwhile I will ask others for a PR review 😸

**Review by mohsen-ghafouri — APPROVED** [review]
🚀

**Comment by churik** [comment]
Successfully installed and created profiles on Android 13 and Android 10

**Pull request merged**
