### PR TITLE
upgrade QT for desktop to 5.11.2 (solves #6053)

### PR DESCRIPTION
**Pull request by jakubgs**
solves #6053
Upgrades QT.

### CODE REVIEW

**Review by rasom — APPROVED** [review]

**Comment by churik** [comment]
@jakubgs Linux [build](https://ci.status.im/job/status-react/job/combined/job/desktop-linux/1795/console) was failed with error:
```
CMake Error at /home/jenkins/workspace/status-react/combined/desktop-linux/node_modules/react-native-keychain/desktop/CMakeLists.txt:30 (find_package):
  By not providing "FindQt5.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt5" with any of
  the following names:

    Qt5Config.cmake
    qt5-config.cmake

  Add the installation prefix of "Qt5" to CMAKE_PREFIX_PATH or set "Qt5_DIR"
  to a directory containing one of the above files.  If "Qt5" provides a
  separate development package or SDK, be sure it has been installed.
```
Can you take a look?

**Comment by jakubgs** [comment]
Yeah, there was an issue with how `qtci` unpacked the Qt package. I'm testing a new version of the docker image enow.

**Comment by rasom** [comment]
hm, tried the last build and emojii issue which should be fixed by this upgrade is still there
screen shot 2018-10-02 at 08 01 31

**Comment by rasom** [comment]
Does this change have any impact on macos builds?

**Review by vkjr — APPROVED** [review]

**Review by vitvly — APPROVED** [review]

**Comment by churik** [comment]
@jakubgs agree, seems that build for Mac OS x (tested on Mac OS X high Sierra 10.13.6) doesn't contain new QT.
Would you mind to extend your PR?

**Comment by jakubgs** [comment]
Yeah, these changes don't include MacOS yet. I will deploy QT 5.11.2 to MacOS slaves today and test it.

**Comment by jakubgs** [comment]
Actually, as far as I can tell MacOS slaves __already have__ Qt `5.11.2`:
```
administrators-Mac-Pro:~ administrator$ brew info qt
qt: stable 5.11.2 (bottled), HEAD [keg-only]
Cross-platform application and UI framework
https://www.qt.io/
/usr/local/Cellar/qt/5.11.2 (9,502 files, 305.2MB)
  Poured from bottle on 2018-10-01 at 14:42:53
```

**Review by maxhora — APPROVED** [review]

**Comment by rasom** [comment]
@churik @jakubgs 
the last build looks good for me
screen shot 2018-10-03 at 14 07 29

**Pull request merged**
