### PR TITLE
Remove identicons, replace them with initials of a user

### LINKED ISSUE #15714: Remove identicoin and replace it with user picture if available or the initials of a user
# Bug Report

## Problem 
Currently, we're still using the identicoin in a lot of places, which should be replaced with the initials of the user when the profile photo is not set and otherwise with the user picture.
Places, where the identicoin is still used:
- activity centre
- contact list
- profiles of users (still old UI is used, not sure worth fixing here)
- own profile  (still old UI is used, not sure worth fixing here)

#### Expected behavior

IMAGE 2023-04-21 14:48:54

#### Actual behavior

Contact list:
IMAGE 2023-04-21 14:49:27

Activity center:
IMAGE 2023-04-21 14:50:00

Another user profile:
IMAGE 2023-04-21 14:50:21

Own profile:

IMAGE 2023-04-21 14:52:26

- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by alwx**
fixes #15714

This PR mostly cleans the code up, removes the usage of identicons and the old `status-im.ui.screens.chat.photos/photo` component, and makes sure the new `quo/user-avatar` is used. 
However, there are still places in the old codebase where the `photo` component is still used (but I marked it as deprecated) — I decided it makes no sense to focus on replacing it these because the old code will be rewritten anyway.

#### Platforms

- Android
- iOS

##### Functional

- 1-1 chats
- public chats
- group chats
- wallet / transactions
- dapps / app browsing
- account recovery
- new account
- user profile updates
- networks
- mailservers
- fleet
- bootnodes

status: wip

### CODE REVIEW

**Comment by J-Son89** [comment]
Hi I left a comment in the related issue for this work:

Hi @alwx, @churik this issue extends a bit further in that the current method we use to generate the user initials is currently done in the quo2/user avatar component. However @cammellos and I realised it would be better to generate these initials in Status Go because otherwise we have to parse the url to check whether the user has a valid image and if not then we generate the users initials (more details in the linked issue below) , creating these initials in Status Go is much cleaner and then makes the use of the user avatar much simpler.

Status Mobile issue:
https://github.com/status-im/status-mobile/issues/15751

Status Go issue: 
https://github.com/status-im/status-go/issues/3429 - @jo-mut is currently working on this.

**Comment by alwx** [comment]
It doesn't matter much for this particular issue — some of the code was not even using `user-avatar` (for example, the code for notifications) so I updated it to use it and got rid of most of the usages of the old `photo` component and identicons in the new codebase. 
We can later update the `user-avatar` component to work any way we want and we can for sure create these initials in Status Go but for now even the switch to `user-avatar` is sufficient in the context of this particular issue.

**Comment by J-Son89** [comment]
> It doesn't matter much for this particular issue — some of the code was not even using `user-avatar` (for example, the code for notifications) so I updated it to use it and got rid of most of the usages of the old `photo` component and identicons in the new codebase. 
> 
> We can later update the `user-avatar` component to work any way we want and we can for sure create these initials in Status Go but for now even the switch to `user-avatar` is sufficient in the context of this particular issue.

Ok cool, just wanted to give a heads up incase there was some crossover 👌

**Review by J-Son89 — APPROVED** [review]
Nice work! 😎

**Review by siddarthkay — APPROVED** [review]

**Comment by pavloburykh** [comment]
@alwx thanx for the PR! Please, take a look at the following issues

### ISSUE 1 Identicon rings are lost for profile icons with no picture set

Is there any sense to fix in scope of current PR or we should wait until correspondent PRs [mentioned](https://github.com/status-im/status-mobile/pull/15815#issuecomment-1536013916) by @J-Son89 ?

**Expected result:**  Identicon rings are shown 

**Actual result:** Identicon rings are lost

photo_2023-05-08 18 17 48

**Comment by pavloburykh** [comment]
### ISSUE 2 Accessibility id: `chat-icon` is lost for profile icon element in Profile screen

This is a reason of e2e failure. 

@alwx is it possible to return accessibility id: `chat-icon` for this element?

Appium 2023-05-08 18-19-31

**Comment by alwx** [comment]
@pavloburykh regarding your issues:
1) Yes, that's what [this issue](https://github.com/status-im/status-mobile/issues/15751) is basically about. It will be fixed there.
2) I'm confused — this element had no accessibility label before, and the accessilibity label clearly shouldn't be `chat-icon` there, just because it's not a chat. Are you sure it's related to this PR?

**Comment by pavloburykh** [comment]
Hi @alwx !

> 2\. I'm confused — this element had no accessibility label before, and the accessilibity label clearly shouldn't be `chat-icon` there, just because it's not a chat. Are you sure it's related to this PR?

Here is a screenshot from nightly build, showing accessilibity label `chat-icon` for this element. I know that naming is confusing, but for some reason it was named like that in the past and we are using this id in our tests. 

Appium 2023-05-09 12-45-30

So it is high-likely a PR issue, because as you can see on screenshot from PR build below in case if picture is not set, Profile icon (on old profile screen) is totally lost as a result of refactoring. I assume that accessibility id could also be affected. 

photo_2023-05-09 12 50 48

When Profile picture is set - accessilibity label `chat-icon` is shown and element is not lost. Below screenshot from PR build

Appium 2023-05-09 13-00-30

**Comment by pavloburykh** [comment]
So, despite the fact that we decided not to focus on old screens, we still need to be able to interact with elements in terms of e2e tests until they will be replaced by new ones. If it is possible, could you please fix the above described issue with an empty icon (when picture is not set) on Profile screen, in order we can continue interacting with it in our e2e tests? @alwx

**Comment by alwx** [comment]
@pavloburykh done!

**Comment by pavloburykh** [comment]
@alwx thanx for the fix. PR is ready for merged. Failed e2e are not PR related.

**Pull request merged**
