### PR TITLE
Release 0.9.13 WIP

### LINKED ISSUE #1604: Commands send, request, location are sent several times if quickly tap on send button
### Description

*Type*: Bug

*Summary*: Same message for commands (send, request, location) is sent several times if quickly tap on the send button in 1-1 or group chats. This does not happen for text or emoji. Expected: consistent behaviour for everything that is sent - anything in the input field is sent once even if user taps on send button several times.

#### Expected behavior
message for commands send, request, location is sent once if quickly tap on the send button.
#### Actual behavior
message for commands send, request, location is sent several times if quickly tap on the send button.

### Reproduction
video: https://drive.google.com/open?id=0Bz3t9zSg1wb7MGZhbGNJWkNoMGc
- Open Status
- Open 1-1 chat
- Construct a request to the contact in the input field, e.g. /request 0.1 
- quickly tap on send button several times
- check that messages area for new request messages (expected only 1)
- Construct send command in the input field, e.g. /send 0.3333
- quickly tap on send button several times
- Tap on /location command
- On the suggestions shown, quickly tap several times on the address

### Additional Information
* Status version: develop 0.9.9d130 / 0.9.8-130-g6a56b600 and 0.9.12
* Operating System: 
Real device Samsung Galaxy S6, Android 6.0.1
Real device iPhone 6s, iOS 10.3.3

### LINKED ISSUE #2870: Deleted 1-1 chat reappear in 'Chats' list after next user log in
***Type***: Bug

***Summary***: When I delete 1-1 chat(s) with previously read messages I had with another contacts (so no Unread message counter displayed on Chat screen), after I log out and log back in - all deleted chats reappear and display all messages I had with the contacts, that were deleted, - like they were Unread. 
The main issue is that we should not resurrect deleted 1-1 chats at all.

#### Expected behavior
No deleted 1-1 chat appears if to log out and log back in to account
#### Actual behavior
Previously deleted 1-1 chat appears if to log out and log back in to account

### Reproduction
https://app.testfairy.com/projects/4803622-status/builds/7392267/sessions/24/?accessToken=IFcF1Epo0dBaEz2royLWr5qBAS4 - from 02:23

1) Open Status on Device1
2) Open Status on Device2
3) Create UserA on Device1
4) Create UserB on Device2
5) UserA adds UserB in contacts.
6) UserA sends message to UserB
7) UserB navigates to 1-1 Chat with UserA to read the message.
8) UserB navigates back to 'Chats' list. Confirm no unread messages counter present.
9) UserB deletes the chat with UserA
10) UserB logs out
11) UserB logs back in and stays on Chats list.

Status version: 0.9.10-503-g3e940b5b+ (develop)
Operating System: Android 7.0 (Samsung J7 real device), iOS 11.1.2 (iPhone X)

### LINKED ISSUE #2903: Error Invalid arity: 0 shown in several cases
### Description

*Type*: Bug

*Summary*: when I am switching between networks (RPCs) I can receive Error `Invalid arity:0 `.  This happens when I have more than 1 account on Ropsten for ex and then switch to Rinkeby and vise versa.

or

Error `Error invalid arity:0`  when try to recover access with valid passphrase and password. The same happens if to try to recover user with invalid passphrase/password.

or

Open Status (**## iOS**)
Login on a account witht transactions
Go in airplane mode
Open transaction details
#### Expected behavior
no errors

#### Actual behavior
Error `invalid arity: 0`

image

image

### Reproduction 
- Open Status under Ropsten RPC
- Create account
- Click Switch users
- Create account
- Switch to Rikneby RPC

or 

- Open Status
- From login screen select 'Recover Access'
- Type random words in Passphrase (e.g. 'test lucky qwerty') and use any characters for password (e.g. 'qwerty')
- Submit this data

### Additional Information
* Status version: 0.9.11d512 (2069)
* Operating System: Android, iOS 
* Real device iPhone 7, Huawei P10 Lite, Android 7.0 Samsung, iPhone X

#### Logs
TF https://app.testfairy.com/projects/4803590-status/builds/7434230/sessions/13/?accessToken=5vuVl9Vx7W-Mz6lSOUJvQ60AgpA

TF https://app.testfairy.com/projects/4803622-status/builds/7430381/sessions/18/?accessToken=hMn-tl7TypdpSn/pKg/5MZ7CmwI

### LINKED ISSUE #2957: No matching Clause (android) at attempt to open transaction
### Description

*Type*: Bug

*Summary*: can't open transaction details no matter online or offline

#### Expected behavior
can view transaction details

#### Actual behavior

image

### Reproduction

- Open Status
- Faucet some funds
- Open transaction details

### Additional Information
* Android: https://i.diawi.com/faqSde
* iOS: https://i.diawi.com/WJVhL3

### LINKED ISSUE #3057: Error chat-contact.identity must be of type 'string', got 'object' shown for group chat members after new member is added
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

*Summary*: Error ```chat-contact.identity must be of type 'string', got 'object' (['0x0428c9d6c1aaaa8369a7c63819684f30e34396dc0907d49afeac85a0a774ccb919b3482097d992e66bcc538e7a0c6acf874c77748f396f53c0a102e10d1a37765b'])``` is shown to all group chat members after admin added new member. If close the error then can continue using the app
#### Expected behavior
[comment]: # (Describe what you expected to happen.)
New member is added, info about X added Y is shown in the group chat,
#### Actual behavior
[comment]: # (Describe what actually happened.)
Error message is shown
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Add 1 contact, it should add you as a contact too
- Create group chat with that 1 contact
- send some hi message
- edit Settings and add Jarrad to the group members
- check on other device if there any error shown

From 1:08 https://app.testfairy.com/projects/4803622-status/builds/7512524/sessions/4/?accessToken=RBWKtxNivaRwMwIAr-8P4tzzhgU

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: release build 56 and nightly build for Jan 16
[comment]: # Android and iOS
real devices Galaxy S6 and iPhone 6s. Android 6.0.1, iOs 10.33.3

### PR DESCRIPTION
**Pull request by oskarth**
Release branch for 0.9.13.

Starting point: `f90e1a4ed32642874c3e4b0bafcba691613c7bcc`

https://github.com/status-im/status-react/projects/10

## Current env

Canonical source is `.env.prod`. This gets injected into the environment as part of `Jenkinsfile.release` configuration file (ctrl-f `.env.prod`).

Currently this is:

```
TESTFAIRY_ENABLED=1
STUB_STATUS_GO=0
ETHEREUM_DEV_CLUSTER=0
MAINNET_NETWORKS_ENABLED=0
ERC20_ENABLED=1
OFFLINE_INBOX_ENABLED=1
OFFLINE_INBOX_MANY_ENABLED=0
LOG_LEVEL=debug
LOG_LEVEL_STATUS_GO=info
JSC_ENABLED=1
QUEUE_MESSAGE_ENABLED=1
```

## Cherry-picks

1. Item means must-have for release (issue/PR/commit)
2. Checked means it has been cherry-picked into release branch

- [x] No offline inbox public/group chat: https://github.com/status-im/status-react/issues/2942
- [x] Password request missing bug: https://github.com/status-im/status-react/issues/2925
- [x] Faster msg status updates (partial fix): https://github.com/status-im/status-react/pull/2910 https://github.com/status-im/status-react/issues/2852
- [x] Error Invalid arity: 0 shown in several cases https://github.com/status-im/status-react/issues/2903
- [x] User avatar is misplaced in 1-1 chat when chat history is more than one day bug: https://github.com/status-im/status-react/issues/2782
- [x] 'from [username]'/'to [username]' is not shown in request/send message ... https://github.com/status-im/status-react/issues/2868
- [x] Unresponsive app after /send in 1-1 and group chat (android) https://github.com/status-im/status-react/issues/2721
- [x] Application is not responsive when opening transaction details while offline https://github.com/status-im/status-react/issues/2314 NOTE: 3 commits
- [x] Rows and focus are overlapped by keyboard when text in input field (Chat) contains more than 2 rows of text or 8 rows emoji: https://github.com/status-im/status-react/issues/2822 https://github.com/status-im/status-react/pull/2858

- [x] [fix #2957] no matching clause error in transaction details  https://github.com/status-im/status-react/pull/2966

- [x] [fix #2903] arity 0 bug in section lists https://github.com/status-im/status-react/pull/2969

- [x] bug #2950 - missing action buttons in unsigned transactions list https://github.com/status-im/status-react/pull/2953

- [x] [BUG#2882] Improved wallet asset selection #2973

- [x] JSC or not? Decision YES

- [x] Offline inbox public/group chat? Decision NO

- [x] Currency style is broken on wallet screen when sending funds in 1x1 chat https://github.com/status-im/status-react/issues/2924

- [x] "Insufficient funds" error at attempt to send ETH with sufficient funds on balance https://github.com/status-im/status-react/issues/2417

- [x] [fix #2870] Mark 1-1 chat as inactive when user removes it

- [x] Fix chat list rendering #2915
- [x] [fix #1604] Commands send, request, location are sent several times if quickly tap on send button #2988
- [x] bug #2949 - resolved unset gas info after send from chat #3000
- [x] Feature/async audit #3017
- [x] Update status-go to develop-gd71c66a2 #2954
- [x] Fix realm migration #3002
- [x] [fix #3057] fix chat-contact.identity must be of type string error #3063
- [x] [#3038] Add buffer to process incoming messages asynchronously #3045
- [x] Username and profile icons displayed not from who sent the message in group chat when several contacts send the messages in the same group chat https://github.com/status-im/status-react/issues/3058 PR: https://github.com/status-im/status-react/pull/3061
- [x] Error null is not an object (evaluating 'e.toLowerCase') when switching to Chats or to Wallet [upgrade] https://github.com/status-im/status-react/issues/3081 
---
- [x] Fix tag for this: Versioning for builds - need to contain 0.9.13 as version (or need to revise what we want). Now: iOS:  0.9.11d532, Android:   0.9.10-532-gc50c1c83+ . Previously, iOS and Android were -1 version different, but if we need to fix it for both now then let's make it consistent.

https://docs.google.com/spreadsheets/u/1/d/1AqrAyT-1DleKrNbXBfOhfpVOARUYPEE-Y0--k5434XY/edit#gid=1101725486

status: WIP

### CODE REVIEW

**Comment by oskarth** [comment]
@rasom do you think we should use JSC or not in this release? Re https://github.com/status-im/status-react/pull/2940

**Comment by oskarth** [comment]
@rasom 

>  Versioning for builds - need to contain 0.9.13 as version (or need to revise what we want). Now: iOS: 0.9.11d532, Android: 0.9.10-532-gc50c1c83+ . Previously, iOS and Android were -1 version different, but if we need to fix it for both now then let's make it consistent.

Do you know where this is set? Is it Xcode on machine?

```
> ag -a "0.9.11d532"
> ag -a "0\.9\.11d532"
```

returns nothing. Same for Android equivalent.

**Comment by rasom** [comment]
@oskarth seems that we need to create `0.9.13` push it to repo and make sure that it's pulled on machine.

**Comment by annadanchenko** [comment]
JSC or not? - removed checkbox as not clear is it included or not. Since it's not influencing https://github.com/status-im/status-react/issues/2990 and after check with @rasom seems like we can keep it so, enable JSC @oskarth

**Comment by oskarth** [comment]
To fix release version info, use `./scripts/tag-release.sh` script. https://github.com/status-im/status-react/pull/3053

**Comment by oskarth** [comment]
Release out, closing PR.

**Pull request closed without merging**
