### PR TITLE
Logs: enable nightly

### PR DESCRIPTION
**Pull request by churik**
nightly is not public, so I got a permission to enable logs there.

### CODE REVIEW

**Review by ilmotta — APPROVED** [review]

**Comment by jakubgs** [comment]
>nightly is not public

Yes it is, anyone can download it from here:
https://status-im-nightlies.ams3.cdn.digitaloceanspaces.com/index.html

This is a bad idea.

**Comment by ilmotta** [comment]
> > nightly is not public
> 
> Yes it is, anyone can download it from here: https://status-im-nightlies.ams3.cdn.digitaloceanspaces.com/index.html
> 
> This is a bad idea.

Thanks @jakubgs. We will reconsider our options. As far as @churik and I discussed previously the nightly builds may be public, but not shared anywhere with users (maybe that's what she meant by "public").

**Comment by jakubgs** [comment]
I wonder if it might make sense to add some kind of banner or warning to builds that have these logs enabled to warn about a secret leak possibility.

**Comment by churik** [comment]
@jakubgs @ilmotta I meant we didn't publish it on our website and I doubt that someone download the build from designated URL (which posted somewhere in GH comment) and shake their phone to share the logs without understanding what they are doing. 

I'm ok with any banner on nightly builds indicating that expanded logs are enabled, just let me know if we need task / prioritization for that.

**Comment by jakubgs** [comment]
I think it's useful for visibility, but you do you.

**Pull request merged**
