### PR TITLE
Changed 2-button confirmations to 1-button popups for installing and uninstalling extensions

### LINKED ISSUE #6353: Cancel button is an overkill for extension confirmation dialog
### Description

*Type*: Bug

*Summary*: There is a confirmation dialog when adding an extension. It contains `Cancel` button which is not necessary as this dialog just confirms the extension values are added to db after `install` button is pressed. 

#### Expected behavior
Remove the cancel button. Show alert view with 1 button https://facebook.github.io/react-native/docs/alert

#### Actual behavior

image

### Reproduction

- Open Status
- Enable dev mode
- Go to extensions and add one
```
...
```

<blockquote><div><strong><a href="https://facebook.github.io/react-native/index.html">Alert · React Native</a></strong></div><div>Launches an alert dialog with the specified title and message.</div></blockquote>

### PR DESCRIPTION
**Pull request by FrederikBolding**
[comment]: # (Please replace ... with your information. Remove < and >)
[comment]: # (To auto-close issue on merge, please insert the related issue number after # i.e fixes #566)

Fixes #6353

### Summary:

[comment]: # (Summarise the problem and how the pull request solves it)

Changed the 2-button dialogs to 1-button popups - thereby making it a simple "OK" box instead of "Cancel / OK".

### Steps to test:
- Open Status
- Enable dev mode
- Go to extensions
- Install or uninstall an extension and see the dialog/popup

status: ready

### CODE REVIEW

**Comment by FrederikBolding** [comment]
Ah, I see I have formatting issues - Give me a sec and I'll have that fixed 😄

**Review by jeluard — APPROVED** [review]

**Comment by jeluard** [comment]
@FrederikBolding Thanks for your contribution !

**Review by flexsurfer — APPROVED** [review]

**Comment by FrederikBolding** [comment]
No problem @jeluard - I signed the commit now, so it should be able to merge. Seems like the Windows test is failing as I forked before it was added 😄

**Review by goranjovic — APPROVED** [review]

**Comment by asemiankevich** [comment]
looks great, lets merge

**Pull request merged**
