### PR TITLE
[chat-ui] password-input fix

### PR DESCRIPTION
**Pull request by alwx**
This PR fixes password input and adds an ability to add several spaces between arguments.
For instance, `/password <any number of spaces in between> 123456` will work fine now.

### CODE REVIEW

**Comment by alwx** [comment]
I've updated the code and tested the input on several test cases.
1) Typing command without additional spaces between arguments work fine;
2) Typing command with additional spaces between arguments also work fine; however, sometimes iOS adds a dot (".") in this case, because iOS thinks that two spaces mean the end of the sentence. I think that this is not the most important issue, and it can be solved later (probably when we move to another way of parsing args);
3) Pasting a password instead of typing it also works fine;
4) Pasting in between of the password also works fine, but I am not sure that there may be someone who does this.

**Comment by rasom** [comment]
Problems:
1. 
img_1562
A user can add something after confirmation. This doesn't make any sense. When this happens there are no validation errors, suggestions... A user has to remove content after password to return to a valid state. 

2. 
img_1564

No need to ask user to type confirmation if we know that password is too short, we need to show this error before switching to confirmation

3. 
img_1565
>  i added password, pressed space, added confirmation, moved caret to the first parameter, removed the last symbol, added it again and pressed space… In result, input is switched to confirmation… but it’s already there. And now when i press send button application doesn’t react

**Comment by rasom** [comment]
IMO: 

We have to implement it in the manner as it was implemented previously, which means
1) `/password` is not editable
2) show password input, replace it with confirmation input after pressing send button

or 

show both password and confirmation fields at once, two one-line secure text entries, we don't need multiline input for passwords. We don't need editable `/password` here either.

**Comment by alwx** [comment]
ok, will update it today

**Pull request merged**
