### PR TITLE
Skip fetching 24h of discovery topics on a new account

### PR DESCRIPTION
**Pull request by rasom**
Please review only the last commit.

It makes onboarding a bit faster, also probably reduces traffic from mailservers (I can't live a day without creating 5-15 new accounts).

status: ready

### CODE REVIEW

**Review by mandrigin — APPROVED** [review]

**Review by yenda — APPROVED** [review]

**Comment by rasom** [comment]
@annadanchenko @churik it's based on https://github.com/status-im/status-react/pull/7961 at the moment, so better to test after

**Comment by Serhy** [comment]
It looks great for new account creation! Tested with Android 6.0.1, Android 8.1, iOS 12.1.4, MacOS devices - instantly connected to mailserver after landed on empty Chats screen, - no fetching blue indicator (from 20 average new accounts creation in total). 
Then, - can join public chat and receive it's 7 days history, exchange assets/messages 1-1 chat. 

Recover account flow left unchanged.

Waiting for https://github.com/status-im/status-react/pull/7961 to retest this.

**Comment by rasom** [comment]
@Serhy rebased onto `develop`, can be tested/merged now

**Comment by Serhy** [comment]
looks good to me!

**Pull request merged**
