### PR TITLE
added SPANK token

### LINKED ISSUE #5387: Tokens with checksummed addresses do not show up in transaction history
### User Story

As a user I wan't to see token transfers for all my tokens in Transaction history.
As a developer I want to be able to add checksummed addresses in supported token list without issues.

### Description

*Type*: Bug

*Summary*: Checking token contract addresses in the event logs is case sensitive. For a small number of tokens we had checksummed address added in our list of supported tokens so their token transfers do not show up. 

The issue was first noticed by @asemiankevich while testing PR to add SPANK token #5249
The updated version of that PR also fixes the bug (adding this issue only to document the bug)

#### Expected behavior
All tokens show up in transaction history when user sends or receives them.

#### Actual behavior
Some tokens (SPANK in that PR and also PRG, XAUR, STX)

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Get any of those tokens.
- Send and receive them and check transaction history

### PR DESCRIPTION
**Pull request by goranjovic**
NEW:
this PR now also fixes #5387 

This PR includes #5207 and two additions:

- adds the icon files to resources
- fixes the token name

Super big thanks and kudos to @ChaceHunter on whose original PR this was based.

### Summary:

Adds SPANK token.
Fixes the bug with checksummed contract addresses

#### Expected behavior
All tokens show up in transaction history when user sends or receives them.

#### Actual behavior
Some tokens (SPANK in that PR and also PRG, XAUR, STX)

### Steps to test:
- Open Status in mainnet
- Get and enable SPANK and any of these tokens 
- Send and receive them and check transaction history

status: ready

### CODE REVIEW

**Review by flexsurfer — APPROVED** [review]

**Review by janherich — APPROVED** [review]

**Comment by goranjovic** [comment]
screenshot-2018-07-21_09 55 08 620

**Review by cammellos — APPROVED** [review]

**Review by andytudhope — APPROVED** [review]

**Review by yenda — APPROVED** [review]

**Comment by asemiankevich** [comment]
1. When sending SPANK token - this transaction is always shown as ETH in history
2. When sending SPANK token - no incoming txn is shown in history on the recipient side

**Comment by goranjovic** [comment]
@asemiankevich let's bench it for now, I'll take a look later to see if it's anything on our side

**Comment by goranjovic** [comment]
@asemiankevich Updated the PR to fix the found issue. Not just SPANK, these tokens had the same problem: PRG, XAUR, STX

**Comment by asemiankevich** [comment]
- [x] check SPANK token is shown in assets list (mainnet)
- [x] check I can request/send some SPANK tokens (from wallet and in 1x1 chat) 
- [x] check if SPANK token is shown when recovering account (i have some spank on my wallet)
- [x] check spank transactions appear in history

**Pull request merged**
