### PR TITLE
fix onboarding screens overlap

### LINKED ISSUE #18369: Onboarding screens overlap each other when pressing "I'm new to Status" multiple times [Android]
# Bug Report

### Reproduction

1. Install Status
2. Quickly tap `I'm new to status` several times 
3. Press `Let's go`

https://github.com/status-im/status-mobile/assets/67952253/b0cf0a25-126f-4c03-9370-ad76803e21d8

### Additional Information

- Status version: nightly 3/01
- Operating System: Android

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by Parveshdhull**
fixes https://github.com/status-im/status-mobile/issues/18369

status: ready

### CODE REVIEW

**Review by briansztamfater — APPROVED** [review]

**Comment by Parveshdhull** [comment]
hi, no new changes. Just rebased the PR.

**Comment by qoqobolo** [comment]
Hi @Parveshdhull , thanks for the fix!
Just found another scenario of how you can still reproduce the same issue:

1. Create a profile
2. Log out
3. Go to the profile selection page (`Profiles on device`)
4. Press `+` 
5. Quicky press `Create new profile` several times

Can you check this case as well please?

https://github.com/status-im/status-mobile/assets/67952253/331b5117-9511-47c6-9d09-4989579edc07

**Review by ibrkhalil — APPROVED** [review]

**Comment by Parveshdhull** [comment]
hi @qoqobolo, Thank you very much for finding this issue.

There were a few more places that were showing the same behavior,
- `Add existing Status profile` in the above video
- Privacy Policy from Intro (Didn't checked this one, but the code was the same, so most probably the same issue)

All three should be fixed now.

**Comment by qoqobolo** [comment]
Awesome, thanks @Parveshdhull 👏👏👏 Checking the fixes now.
One question in the meantime. 
There is one issue in develop on Android that looks similar:
if you quickly click the `New chat` button on the `Messages` screen, UI will be frozen.


https://github.com/status-im/status-mobile/assets/67952253/8ad3969c-718d-498d-8b94-aa8731dd9580

Would you like to take a look at this in this PR? 
It also has to do with clicking the button multiple times which causes issues in UI, but I'm not sure if it's the same thing.
Will log this separately with no problem if it's unrelated issue 👌

**Comment by Parveshdhull** [comment]
> I'm not sure if it's the same thing.

Yes, it's the same thing. We should not have allowed multiple presses at the same time.
This should be fixed now (also for Add new contact)

Thank you very much for highlighting this problem. These issues could have been easily avoided at the time of implementation, unfortunately we missed them.

I will create an issue to make sure, we don't have this issue in other places.

**Comment by qoqobolo** [comment]
> (also for Add new contact)

Hm weird, I tried this button as well but it worked fine for me 🤔
But thank you anyway for fixing all these issues and creating one to track potentially remaining. QAs will also update it if anything is found.

**Comment by qoqobolo** [comment]
Two more places:

1. Android: `Invite friends to Status` button on the home screen

https://github.com/status-im/status-mobile/assets/67952253/60f6c119-3d2d-4251-a16c-69bc6a0815c6

2. iOS: `Let's go` button on onboarding (you should tap it very quickly)

https://github.com/status-im/status-mobile/assets/67952253/19e2434b-47b2-45a4-9c19-b6d743abf14c

**Comment by Parveshdhull** [comment]
hi Thank you for finding these cases. `Let's go` issue should be fixed now.
`Invite friends to Status` issue is a little different (navigation outside app), will it be ok if I fix this one in https://github.com/status-im/status-mobile/issues/18431

**Comment by qoqobolo** [comment]
> will it be ok if I fix this one in https://github.com/status-im/status-mobile/issues/18431

Sure thing 👍
Let's merge these fixes, it's a lot already. Thanks for your amazing work!

**Pull request merged**
