### PR TITLE
chore(quo): update styles for account card variant missing keypair

### LINKED ISSUE #20251: Update the `account-card` component design for the `missing-keypair` type
# Feature Issue

Update the `account-card` component design for the `missing-keypair` type

### Design

[Link to Account Card component](https://www.figma.com/design/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?node-id=19513%3A197699&t=okKC6ZVYAA2jeHTU-1)

[Link to Account Card - Missing Keypair type](https://www.figma.com/design/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?node-id=19513%3A197699&t=okKC6ZVYAA2jeHTU-1)

### Description

The existing `missing-keypair` type in the `account-card` component has a background color and solid borders, which must be updated to the new design.

### Acceptance Criteria

- Should match the design

### PR DESCRIPTION
**Pull request by J-Son89**
fixes: https://github.com/status-im/status-mobile/issues/20251

This component mostly existed already. It only needed some minor UI adjustments to match the designs.

**Light mode:**

https://github.com/status-im/status-mobile/assets/22799766/9fa15f35-89fd-4ad4-b6b4-4a2daedd5e91

**Dark Mode:**

https://github.com/status-im/status-mobile/assets/22799766/a39c7bc8-a54a-40fa-9acc-b536328812b9

Manual QA can be skipped but a quick design check will be helpful

### CODE REVIEW

**Review by mohsen-ghafouri — APPROVED** [review]

**Review by smohamedjavid — APPROVED** [review]

**Review by ulisesmac — APPROVED** [review]

**Review by seanstrom — APPROVED** [review]

**Comment by J-Son89** [comment]
@Francesca-G can you check this changes please? 🙏

**Review by BalogunofAfrica — APPROVED** [review]

**Review by Francesca-G — COMMENTED** [review]
Here's the [review](https://www.figma.com/design/e9woQowfaIOCBrXS1jgkhZ/Review-Components-%2F-Mobile?node-id=243-9410&t=0ekRkjSMQEgyQt8S-1) with 2 minor changes to make :)

**Comment by J-Son89** [comment]
thanks @Francesca-G - I updated to the review :)

**Review by Francesca-G — APPROVED** [review]
Looks good now ✨

**Comment by J-Son89** [comment]
oh drat, @status-im/mobile-qa. I ran e2e tests but forgot to wait for the results. How should I proceed here?
These changes are very minimal in that they just changed a small amount of styles on the account card component in the design system.

**Comment by qoqobolo** [comment]
@J-Son89 no worries, we'll check the results once they are here and let you know if there is anything related to those changes.

**Comment by qoqobolo** [comment]
@J-Son89 FYI: the failures here are not related to the PR 👌

**Comment by J-Son89** [comment]
Thanks @qoqobolo!

**Pull request merged**
