### PR TITLE
Reduce image sizes

### LINKED ISSUE #20075: Reduce images sizes
# Problem

Some images are quite large in size which leads to taking a lot of space, we want to reduce the size of these images which will help reduce the size of the application

An overview of the background required to understand the problem.
A problem description.

## Acceptance Criteria

Images reduced in size with minimal loss of quality

### PR DESCRIPTION
**Pull request by jo-mut**
fixes #20075

### Summary
In this pr, we try to reduce the size of the images used especially in the onboarding process to help in reducing the size of the application.

This is just a sample of images. We could achieve much more  space by simply reducing the size of all images. In this pr, all images with over 100kb in Ui2. Combine they had a sum total of 26mb and its been reduced to 7.2mb.

status: wip

### CODE REVIEW

**Comment by jo-mut** [comment]
I also compared between  the compressed versions of all images in both webp and png file formats and while in both case the quality was more or less the same the png(s) achieved a smaller size 

**uncompressed images**

Screenshot 2024-05-17 at 01 32 23

**webp compressed images**

Screenshot 2024-05-17 at 00 54 20

**png compressed images**

Screenshot 2024-05-17 at 00 54 36

**Comment by jo-mut** [comment]
Before compression ios




After compressing ios




there is difference in quality is too small to notice

**Review by siddarthkay — APPROVED** [review]
very nice

**Review by J-Son89 — APPROVED** [review]

**Review by Parveshdhull — APPROVED** [review]

**Comment by jo-mut** [comment]
@Francesca-G I did some work to compress these images, it would help in reducing the size of the application, i think this needs a design review to just be sure you are okay with the quality of the compression. have a look whenever you can

**Review by ilmotta — APPROVED** [review]
@jo-mut, could you share which commands you used to compress PNG files?

WebP should be smaller for the same quality, ~25% less, but I checked that for rasterized images it may not be the best format, which explains the results you reported. I could create smaller WebP files than the PNG ones, but they introduced too many artifacts to my liking, visibly worse than the PNGs. The AVIF format on the other hand generates significantly smaller files than WebP for the same quality, but they still generate visible artifacts to achieve the same file size as the PNGs you generated.

Ideally we should have a quick script to compress a list of files or a directory. This script would have been useful now and in future iterations. If the script is too much to ask, could you at least add the commands in the PR description you used to generate these files?

Great work! 🚀 

Edit: To be fair to other image formats and the quality of the final output, ideally the conversion should start from the original files and not go through original -> PNG -> WebP.

**Comment by jo-mut** [comment]
I used an online tool, tinypng.com. I could try do some more work see if i
can get any better results with webp or avifs.

I think a script for this kind of thing would do better for any future use
as the designs come

**Review by Francesca-G — APPROVED** [review]
Images looks sharp to me (iPhone 13)

as mentioned [here](https://discord.com/channels/624634427930312714/1146065551060389943/1240984505356128268) on Discord we should only use a static illustration (no transition) on the Generating Keys screens, please make sure to address this in a separate issue 🙏

Screenshot 2024-05-17 alle 17 04 37

**Comment by ilmotta** [comment]
> I think a script for this kind of thing would do better for any future use
as the designs come

It would be very helpful @jo-mut to have a basic script because we will surely have to do this again. It will save us time if you could do that. And it would help others reproduce and play with parameters.

> I could try do some more work see if i can get any better results with webp or avifs.

I already tried using imagemagick's `convert` tool and also with Gimp, but the results weren't as good. I think we can ignore WebP and AVIFs for rasterized images tbh. If we were compressing photos of people/places/etc it'd be a different story, they would destroy traditional JPEGs for example.

I just tried `sharp`, a Node lib, quite fast due to native implementation under the hood. I could get a PNG of 55kb instead of 70kb from tinypng with a decent quality. Here's an example of what we can achieve and automate. Here's the script:

```javascript
const sharp = require("sharp");

sharp("generating-keys-1@2x.png")
  .png({
    effort: 10,
    quality: 50, // We can play with this number
    compressionLevel: 9
    palette: true // This is critical to lower file sizes
  })
  .toFile("generating-keys-1@2x.png - compressed")
  .then((info) => {
    console.log("Image compression completed:", info);
  })
  .catch((err) => {
    console.error("Error during image compression:", err);
  });
```

**Comment by ilmotta** [comment]
Given the good results obtained by `sharp` in my previous comment, it would be better if we didn't merge yet because if these images are added to the repo just so we remove them soon the repo size will increase in size even more because git won't be able to reuse bytes.

Well, I'm just giving options @jo-mut. And this topic about image compression is something I did a ton in life, so that's why I tried to dig deeper in this PR.

**Comment by jo-mut** [comment]
@ilmotta  I agree with you, no need to merge now. I can play with this sharp script. Let me see how much we can achieve if i convert all the images in Ui2

**Comment by mariia-skrypnyk** [comment]
> @ilmotta I agree with you, no need to merge now. I can play with this sharp script. Let me see how much we can achieve if i convert all the images in Ui2

Hi @jo-mut !

Have this sharp issue resolved yet?

**Comment by jo-mut** [comment]
@mariia-skrypnyk not yet, i will might take some more time to work on this. Am currently on time off. We can revisit on wednesday

**Comment by mariia-skrypnyk** [comment]
Thanks @jo-mut !
Have a food day-off!

Just tag me and I'll be notified to test your PR.

**Comment by jo-mut** [comment]
@ilmotta 

I am using the Script, and I applied it to all the images on the`ui2`  folder irregardless of their size just to have even more compression but so far am not so sure about the quality on some of the images

on this the image quality property has the value set at `100` and the total size of the whole folder reduces to 9.1mb from 28mb, the quality looks better

its acceptable I think

mobile-how-to-pair-logged-in@2x

the quality on this is not good at all and below `80`, it gets even more poor in quality  , some images of course are not that much noticeable but on this one it was quite pronounced. Also the folder reduced to 6mb.

mobile-how-to-pair-logged-in@2x

**Comment by ilmotta** [comment]
Thanks for trying the different approach @jo-mut. At least now we know we have alternatives that would give competitive asset sizes compared to tinypng and which are open-source.

**Comment by jo-mut** [comment]
@ilmotta I think this is even better, the difference between this approach and tinypng if there is even any is hard to tell, the quality of images is pretty much the same and with the script it achieves even smaller sizes

This pr can be merged I will add the script to our codebase in a separate pr.

Thank you for the suggestion

**Comment by jo-mut** [comment]
@mariia-skrypnyk Hi maria. When you have some time you can take another look at this pr.
Thank you

**Comment by mariia-skrypnyk** [comment]
Please, rebase your PR.
I will take a look at it as soon as I finish my current testing.
Thanks!

**Comment by mariia-skrypnyk** [comment]
Hey @jo-mut !

Thanks for your PR. A lot of work was done!
I've started from iOS and as for me not a huge difference happened from then till now.
But I do see the difference for Android.
I think it was planned, I just wanted to leave my comment.

Going to move PR to @Francesca-G review as well.

**Review by Francesca-G — APPROVED** [review]
Adding follow up required label to address this [issue](https://github.com/status-im/status-mobile/pull/20076#pullrequestreview-2063683025) 👍

**Comment by mariia-skrypnyk** [comment]
@jo-mut You can merge your PR after creating followup @Francesca-G mentioned above 🙌.

**Comment by jo-mut** [comment]
> @jo-mut You can merge your PR after creating followup @Francesca-G mentioned above 🙌.

https://github.com/status-im/status-mobile/issues/20243

**Pull request merged**
