### PR TITLE
Bug/saved mailserver topics

### PR DESCRIPTION
**Pull request by cammellos**
This commit does a few things:
- Add export/import database methods for debugging (only on Android)
- Fixes some issues with topic management
- Adds caching of waku messages (status-go)
- Simplifies login logic and start moving mailserver management to status-go
- Optimize group chats sending of messages (status-go)
- Removes tribute-to-talk (I would have had to fix some linting issues and I though I might just remove the whole thing as it's dead code)

### Testing

- Mailservers logic, custom mailservers, fetching data etc
- Group chats, sending emojis, receiving messages, sending messages 
- Chats and offline in general
- IOS push notifications

### CODE REVIEW

**Review by flexsurfer — APPROVED** [review]

**Comment by Serhy** [comment]
@cammellos When message receives by iOS the app crashes.
Crash_log of crash is here 
[Status PR  25-01-2021, 12-30.crash.txt](https://github.com/status-im/status-react/files/5866036/Status.PR.25-01-2021.12-30.crash.txt)
and from console last items: 
[ios_crashes.txt](https://github.com/status-im/status-react/files/5866045/ios_crashes.txt)

**Comment by Serhy** [comment]
@cammellos  what was tested and confirmed working like in develop (thanks @qoqobolo for help!)
1) Messaging in WiFi 1-1, Public, Group (emoji, images, stickers, audio, text)
2) Messaging in Mobile 1-1, Public, Group (emoji, images, stickers, audio, text)
3) Offline received messages in 1-1, public, Group
4) PN on iOS, Android (with PN for transactions)
5) Custom history node added, data could be fetched from offline
6) No messages and PN from blocked contracts
7) Messaging in different network
8) Messages from Release build received
9) Pairing devices 
10) ENS names and nicknames set and visible to users

**Comment by Serhy** [comment]
i'm looking at last tests @cammellos 
(some of them may need to be polished after recent changes made in tests)

**Comment by Serhy** [comment]
iOS build fetches messages from 1-1, Group and public chat fine.
Also can import and export DB with respective features. Big kudos to you, @cammellos for that!
Autotests above will be fixed separately of this PR (most of them false failed, test_delete_chats_via_delete_button valid issue described in 11683)
Let's merge it, @cammellos , thanks!

**Pull request merged**
