### PR TITLE
[iOS, Android] Upgrade realm-js

### PR DESCRIPTION
**Pull request by rasom**
Currently app can't be built with Xcode 10.2 because of https://github.com/realm/realm-js/pull/2303

status: ready

### CODE REVIEW

**Review by flexsurfer — APPROVED** [review]

**Review by mandrigin — APPROVED** [review]

**Review by pedropombeiro — APPROVED** [review]

**Comment by rasom** [comment]
just realized that realm/realm-js#2303 has not been included into the last release of realm

**Comment by churik** [comment]
@rasom any clues what areas can be affected?
Suppose if that it is only about building process it's enough to install builds \ create account.

**Comment by Serhy** [comment]
Status-github-bot moved back this PR in 'TO TEST' because
Screenshot 2019-04-10 at 16 41 04

**Comment by rasom** [comment]
@flexsurfer @mandrigin @churik fix was released, `realm` is upgraded again in this PR. Ready for merging.

**Review by mandrigin — APPROVED** [review]

**Pull request merged**
