### PR TITLE
Test svg performance

### PR DESCRIPTION
**Pull request by rasom**
The first high bar here is an animation with svg icons (`add-new-chat` bottom bar), the second with png icons. The third and forth are with svg and then png accordingly.

Rendering one svg icon adds 6 extra calls to `UIManager` (comparing to `png` image), in case of `add-new-chat` bottom bar it is 30 extra calls. These relatively heavy calls cause dropped frames during animation, it works noticeable smother with png.

rendering item with svg icon (16 calls to UIManager)

```
05-09 20:39:43.462 12209 12258 I ReactNativeJS: JS->N :
UIManager.setChildren([11855,[11853]]) *
05-09 20:39:43.462 12209 12258 I ReactNativeJS: JS->N :
UIManager.createView([11857,"RCTView",1,{"paddingLeft":16,"flexDirection":"row","alignItems":"center","height":64}]) *
05-09 20:39:43.462 12209 12258 I ReactNativeJS: JS->N :
UIManager.setChildren([11857,[11849,11855]]) *
05-09 20:39:43.462 12209 12258 I ReactNativeJS: JS->N :
UIManager.createView([11859,"RCTView",1,{"accessible":true,"accessibilityLabel":"start-group-chat-button"}]) *
-> 05-09 20:39:43.462 12209 12258 I ReactNativeJS: JS->N :
-> UIManager.setChildren([11859,[11857]]) *
-> 05-09 20:39:43.482 12209 12258 I ReactNativeJS: JS->N :
-> UIManager.createView([11863,"RNSVGPath",1,{"matrix":[1,0,0,1,0,0],"rotation":0,"scaleX":1,"scaleY":1,"propList":["fill","fillRule"],"opacity":1,"fill":[0,-12361505],"fillRule":0,"fillOpacity":1,"stroke":null,"strokeOpacity":1,"strokeLinecap":0,"strokeLinejoin":0,"strokeDasharray":null,"strokeWidth":1,"strokeDashoffset":null,"strokeMiterlimit":4,"d":"M17.7544 4.65411C19.3643 4.15106 21 5.3537 21 7.04034V15.9598C21 17.6464 19.3643 18.8491 17.7544 18.346L12.7302 16.7759L11.3091 19.6181C10.8855 20.465 10.0198 21.0001 9.073 21.0001H7.32959C5.51123 21.0001 4.30127 19.1208 5.05371 17.4655L6.28296 14.7612L5.10522 14.3931C3.85278 14.0018 3 12.8419 3 11.5297V11.4704C3 10.1583 3.85278 8.99835 5.10522 8.60699L17.7544 4.65411ZM19 7.04034C19 6.70306 18.6729 6.46246 18.3508 6.56305L17 6.98517V16.015L18.3508 16.4371C18.6729 16.5377 19 16.2971 19 15.9598V7.04034ZM5.70166 10.5159L15 7.61017V15.39L5.70166 12.4842C5.28418 12.3537 5 11.9671 5 11.5297V11.4704C5 11.033 5.28418 10.6464 5.70166 10.5159ZM8.20654 15.3622L6.87427 18.2931C6.72388 18.6242 6.96582 19.0001 7.32959 19.0001H9.073C9.26245 19.0001 9.43555 18.893 9.52026 18.7237L10.7961 16.1716L8.20654 15.3622Z"}]) *
-> 05-09 20:39:43.482 12209 12258 I ReactNativeJS: JS->N :
-> UIManager.createView([11865,"RNSVGGroup",1,{"matrix":[1,0,0,1,0,0],"rotation":0,"scaleX":1,"scaleY":1,"propList":["fill","fillOpacity","fillRule","stroke","strokeWidth","strokeOpacity","strokeDasharray","strokeDashoffset","strokeLinecap","strokeLinejoin","strokeMiterlimit"],"opacity":1,"fill":[0,-12361505],"fillRule":1,"fillOpacity":1,"stroke":null,"strokeOpacity":1,"strokeLinecap":0,"strokeLinejoin":0,"strokeDasharray":null,"strokeWidth":1,"strokeDashoffset":null,"strokeMiterlimit":4,"font":{}}]) *
-> 05-09 20:39:43.482 12209 12258 I ReactNativeJS: JS->N :
-> UIManager.setChildren([11865,[11863]]) *
-> 05-09 20:39:43.482 12209 12258 I ReactNativeJS: JS->N :
-> UIManager.createView([11867,"RNSVGSvgView",1,{"width":24,"height":24,"bbWidth":"24","bbHeight":"24","backgroundColor":0,"borderWidth":0,"flex":0,"minX":0,"minY":0,"vbWidth":24,"vbHeight":24,"align":"xMidYMid","meetOrSlice":0}]) *
-> 05-09 20:39:43.482 12209 12258 I ReactNativeJS: JS->N :
-> UIManager.setChildren([11867,[11865]]) *
-> 05-09 20:39:43.492 12209 12258 I ReactNativeJS: JS->N :
-> UIManager.createView([11869,"RCTView",1,{"accessibilityLabel":"icon"}]) *
05-09 20:39:43.492 12209 12258 I ReactNativeJS: JS->N :
UIManager.setChildren([11869,[11867]]) *
05-09 20:39:43.492 12209 12258 I ReactNativeJS: JS->N :
UIManager.createView([11873,"RCTView",1,{"borderRadius":50,"width":40,"height":40,"alignItems":"center","justifyContent":"center","backgroundColor":-1249284}]) *
-> 05-09 20:39:43.492 12209 12258 I ReactNativeJS: JS->N :
-> UIManager.setChildren([11873,[11869]]) *
05-09 20:39:43.502 12209 12258 I ReactNativeJS: JS->N :
UIManager.createView([11875,"RCTRawText",1,{"text":"Join public chat"}]) *
05-09 20:39:43.502 12209 12258 I ReactNativeJS: JS->N :
UIManager.createView([11877,"RCTText",1,{"color":-12361505,"fontWeight":"400","fontSize":16,"paddingLeft":16,"fontFamily":"Inter-Regular","lineHeight":22,"maxFontSizeMultiplier":1.25,"accessible":true,"allowFontScaling":true,"ellipsizeMode":"tail"}]) *

```

rendering item with png icon (10 calls to UIManager)

```
05-10 10:14:40.992 12691 12740 I ReactNativeJS: JS->N :
UIManager.setChildren([855,[853]]) *
05-10 10:14:41.002 12691 12740 I ReactNativeJS: JS->N :
UIManager.createView([857,"RCTView",1,{"paddingLeft":16,"flexDirection":"row","alignItems":"center","height":64}]) *
05-10 10:14:41.002 12691 12740 I ReactNativeJS: JS->N :
UIManager.setChildren([857,[849,855]]) *
05-10 10:14:41.002 12691 12740 I ReactNativeJS: JS->N :
UIManager.createView([859,"RCTView",1,{"accessible":true,"accessibilityLabel":"start-group-chat-button"}]) *
05-10 10:14:41.002 12691 12740 I ReactNativeJS: JS->N :
UIManager.setChildren([859,[857]]) *
05-10 10:14:41.012 12691 12740 I ReactNativeJS: JS->N :
UIManager.createView([863,"RCTImageView",1,{"width":24,"height":24,"overflow":"hidden","shouldNotifyLoadEvents":false,"src":[{"uri":"http://localhost:8081/assets/resources/images/public_chat.png?platform=android&hash=3e341e3504d2ede926968249bb6bc65f"}],"defaultSrc":null,"loadingIndicatorSrc":null}]) *
05-10 10:14:41.012 12691 12740 I ReactNativeJS: JS->N :
UIManager.createView([865,"RCTView",1,{"borderRadius":50,"width":40,"height":40,"alignItems":"center","justifyContent":"center","backgroundColor":-1249284}]) *
05-10 10:14:41.012 12691 12740 I ReactNativeJS: JS->N :
UIManager.setChildren([865,[863]]) *
05-10 10:14:41.022 12691 12740 I ReactNativeJS: JS->N :
UIManager.createView([867,"RCTRawText",1,{"text":"Join public chat"}]) *
05-10 10:14:41.022 12691 12740 I ReactNativeJS: JS->N :
UIManager.createView([869,"RCTText",1,{"color":-12361505,"fontWeight":"400","fontSize":16,"paddingLeft":16,"fontFamily":"Inter-Regular","lineHeight":22,"maxFontSizeMultiplier":1.25,"accessible":true,"allowFontScaling":true,"ellipsizeMode":"tail"}]) *
```

### CODE REVIEW

**Comment by yenda** [comment]
Nice findings!

**Comment by yenda** [comment]
@rasom did you run the images through imageoptim to make them as small as possible?

**Comment by rasom** [comment]
@yenda do you mean png? no I didn't

**Comment by yenda** [comment]
@rasom looks like they are compressed already I get 0% gain

**Comment by rasom** [comment]
covered in #8195

**Comment by StatusWrike** [comment]
➤ Oskar Thoren commented:

Anna DanchenkoRoman Volosovskyi how can this be completed when a subtask is suspended/seemingly on hold? Doesn't make sense to me

**Comment by StatusWrike** [comment]
➤ Anna Danchenko commented:

right, adjusted (they should not be subtasks of each other)

**Pull request closed without merging**
