### PR TITLE
Only count images in an album in photo selector

### LINKED ISSUE #17448: In the list of albums, videos are counted as images, which is causing incorrect images counts
### Steps to Reproduce:
1. Save any video format to the device.
2. Go to any chat.
3. Open the photo selector.
4. Open the list of albums.
5. Check the album where the video is saved.

### Actual Behavior:
in the list of albums, videos are counted as images, resulting in an incorrect count for albums containing both images and videos.
image

### Expected Behavior:
In the list of albums, the count should only include only images, and videos should be excluded from this count.
### Devices:
IOS, Android

### ENV:
- Nightly [28 Sep 2023]

### PR DESCRIPTION
**Pull request by ibrkhalil**
fixes #17448 

### Summary

Only counts images as a resource in an album as we support only sending images at the moment.

Album: image 

| iOS before  |  iOS after |
| ------------- | ------------- |
|   |   |

status: ready

### CODE REVIEW

**Review by jo-mut — APPROVED** [review]

**Review by Parveshdhull — APPROVED** [review]

**Review by ilmotta — APPROVED** [review]

**Comment by ibrkhalil** [comment]
Should it be 1 image (Singular) and not 1 images @VolodLytvynenko

**Comment by VolodLytvynenko** [comment]
> Should it be 1 image (Singular) and not 1 images @VolodLytvynenko

@ibrkhalil Would be great to implement it as (singular) "1 image" if only one image is present in album. Thanx

**Comment by ibrkhalil** [comment]
> > Should it be 1 image (Singular) and not 1 images @VolodLytvynenko
> 
> @ibrkhalil Would be great to implement it as (singular) "1 image" if only one image is present in album. Thanx

Done

**Comment by pavloburykh** [comment]
@ibrkhalil thanx for the fix! Failed e2e are not PR related. Ready to be merged.

**Pull request merged**
