### PR TITLE
feat: show pinned messages

### LINKED ISSUE #14023: Show pinned messages - New UI
As a user
I want to be able to see pinned messages
So that I know the important information about a community/channel

This needs to be implemented for 1-to-1, private group chats & communities.

### Designs

https://www.figma.com/file/PPWkgOYlZZDxZv5SDGsZVV/Posts-%26-Attachments?node-id=3425%3A413546

This includes showing the banner on top with the latest pinned message,  the number of pinned messages, and showing the pinned messages https://www.figma.com/file/PPWkgOYlZZDxZv5SDGsZVV/Posts-%26-Attachments?node-id=3505%3A368386

Depends on: #14022 

Component dependency:
https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Mobile-Components?node-id=863%3A26323 Banner component

### PR DESCRIPTION
**Pull request by OmarBasem**
fixes #14023

### Summary

This PR implements the [new UI](https://www.figma.com/file/PPWkgOYlZZDxZv5SDGsZVV/Posts-%26-Attachments-for-Mobile?node-id=3505%3A368386) of showing pinned messages. It implements the [banner](https://www.figma.com/file/PPWkgOYlZZDxZv5SDGsZVV/Posts-%26-Attachments-for-Mobile?node-id=3425%3A413546) at the top, as well as showing the list of pinned messages when pressing on the banner. Unpinning of messages is addressed in a different issue (#14024)

status: ready

### CODE REVIEW

**Comment by du82** [comment]
is there a way for users to hide the banner? It takes up a lot of space, and is annoying if I've already read the pinned message

**Comment by flexsurfer** [comment]
hey @OmarBasem i've merged PR with ui2 namespace, we shouldn't create `-old` anymore, also `src/status_im/ui/screens/chat/message/message.cljs` was moved to `https://github.com/status-im/status-mobile/blob/develop/src/status_im/ui2/screens/chat/messages/message.cljs`, probably it will be simpler to create new branch and PR, but its up to you, please ping me if you need any help

**Comment by flexsurfer** [comment]
all new code for new ui should be created in ui2 namespace, also we shouldn't modify code in ui namespace anymore

**Comment by OmarBasem** [comment]
> is there a way for users to hide the banner? It takes up a lot of space, and is annoying if I've already read the pinned message

For now the banner is not dismissable, as per the design team.

**Comment by OmarBasem** [comment]
Closing this PR. Opened a [new PR](https://github.com/status-im/status-mobile/pull/14184) implemented in ui2 namespace.

**Pull request closed without merging**
