### PR TITLE
use https instead of ssh in package.json

### PR DESCRIPTION
**Pull request by yenda**
We shouldn't require ssh to use public repos

status: ready

### CODE REVIEW

**Review by jakubgs — APPROVED** [review]
Nice.

**Comment by jeluard** [comment]
@alwx Did work on that recently. He probably can provide feedback.

**Review by cammellos — APPROVED** [review]
looks good to me, pending @alwx judgement

**Review by flexsurfer — APPROVED** [review]
yeah did the same locally for development

**Comment by alwx** [comment]
I don't know why but in this case `npm 9` cannot resolve dependencies on my machine, but everything is fine when I use `yarn` instead. Because we're going to switch to yarn, it can be merged.

But to be honest I don't really understand why this change is needed.

**Review by alwx — APPROVED** [review]

**Comment by cammellos** [comment]
@alwx having https helps on CI systems for example, as `ssh` requires to have a key registered with github

**Comment by alwx** [comment]
ok, merge it then

**Pull request merged**
