### PR TITLE
fix home stack height

### LINKED ISSUE #14633: "Jump to" panel overlaps tabs (Xiaomi Mi 9T Pro)
# Bug Report

## Problem 
Was not able to reproduce it on other devices (Tried on Xiaomi, Huawei, and Samsung)
Any help with reproduction is highly appreciated.

#### Expected behavior
no overlapping

#### Actual behavior

https://user-images.githubusercontent.com/4557972/209359542-59a7ba6a-4455-459f-a201-6ac1e1c7232f.mp4

### Reproduction

1) Open Status
2) Tap on "Jump to"

### Additional Information

- Status Version: nightly 23/12/22
- Operating System: Android 10 (MIUI 12.0.5) 
- Device: Mi 9T Pro

### PR DESCRIPTION
**Pull request by Parveshdhull**
fixes: https://github.com/status-im/status-mobile/issues/14633

### Testing:
I don't have access to `Xiaomi Mi 9T Pro`, please can you confirm if this fixes the issue? cc @churik 
Also, updated scroll to bottom accessibility-id as mentioned in https://github.com/status-im/status-mobile/issues/14617#issuecomment-1362778722 cc @VladimrLitvinenko 

status: ready

### CODE REVIEW

**Comment by churik** [comment]
Issue i still here on my  Xiaomi:

https://user-images.githubusercontent.com/4557972/209555965-a7d76387-0695-4ba0-8251-b378a13189c1.mp4

**Comment by Parveshdhull** [comment]
> Issue i still here on my Xiaomi:

The issue probably should be fixed now.
(Please also check fix doesn't break other devices)
Thank you

**Comment by churik** [comment]
on build with https://github.com/status-im/status-mobile/commit/2b945fb2ff50378569eba64f21ed5e0d260ce7a6 on my Xiaomi device issue is still there, sorry 

https://user-images.githubusercontent.com/4557972/209646149-624ecbee-f721-4b5f-85f0-5b146ebe1877.mp4

**Comment by Parveshdhull** [comment]
I am still not sure why Xiaomi is acting differently. Please can you try the latest build and see if it works?
And also please can you provide `Status.log`?
Thank you very much for helping me debug this weird issue.

**Comment by churik** [comment]
It is fixed on Xiaomi 🎉 
I'll check on other devices and let you know the results. Thank you for patience!

**Comment by Parveshdhull** [comment]
> It is fixed on Xiaomi tada I'll check on other devices and let you know the results. Thank you for patience!

Please don't check on other devices yet, this was just a hack. I will provide better solution, once I will find actual value of status bar height in Xiaomi. I look forward to `Status.log` file

**Comment by churik** [comment]
@Parveshdhull 
[Status.log](https://github.com/status-im/status-mobile/files/10313693/Status.log)

**Comment by Parveshdhull** [comment]
So, After trying react-native [dimensions](https://github.com/status-im/status-mobile/issues/14633#issuecomment-1366191478), looking into the working of libraries like [react-native-device-info](https://github.com/status-im/status-mobile/issues/14633#issuecomment-1366576996), and [react-native-android-navbar-height](https://github.com/ConnectyCube/react-native-android-navbar-height), and even after writing [native code](https://github.com/status-im/status-mobile/issues/14633#issuecomment-1366962832), I conclude that there isn't any reliable way to get screen height and even detecting if the device has a [notch](https://stackoverflow.com/questions/51858807/react-native-detect-screen-notch).

**Current State:**
Currently, most of the devices can calculate home-stack dimensions correctly using the old solution, and for devices that are facing issues like Xiaomi, the app have to run once to calculate the dimension of the rendered view. And will work nicely on further logins.

@churik, will that be ok?
@flexsurfer any thoughts?

**Comment by Parveshdhull** [comment]
probably can block the render of the home-stack for the first time until the height is calculated, but not sure if it is worth it.

**Comment by Parveshdhull** [comment]
> probably can block the render of the home-stack for the first time until the height is calculated, but not sure if it is worth it.

Or move this calculation of screen height to any parent view (probably while redesigning onboarding). This way screen height will not be wrong for those devices even for once.

**Review by yqrashawn — APPROVED** [review]

**Comment by churik** [comment]
> @churik, will that be ok?

It is definitely OK! Let me check it and we can merge it afterward.

**Comment by churik** [comment]
Thank you for diving into fixing this outstanding bug.
It is working after the app relaunch on my Xiaomi now, on other devices I'm not able to reproduce it.

**Pull request merged**
