### PR TITLE
[#7451] Stickers support on desktop

### LINKED ISSUE #7451: Stickers support on desktop

### PR DESCRIPTION
**Pull request by flexsurfer**
fixes #7451

image

### CODE REVIEW

**Review by jeluard — APPROVED** [review]

**Comment by jeluard** [comment]
@goranjovic @dmitryn @vkjr Please review :)

**Review by dmitryn — APPROVED** [review]

**Review by vkjr — APPROVED** [review]

**Comment by churik** [comment]
@flexsurfer 
nice PR, thanks!
Several issues:
**1) No preview in chat list if last message is sticker (reproducible on all platforms)**
prs

**2) Constant crash if you restore account with emoji in 1-1 chat (could reproduce only on Windows)**

Steps:
- create account A
- create 1-1 chat with B
- send 10+ messages-stickers from B to A
- restore account A on Windows
- close popup about pairing settings 
- open chat with B
App is crashed. Tried on Windows and Mac OS (Linux build is missing) - could constantly (3/3) reproduce on Windows only (I'm using VM so it is much slower than real device) 
[Status_win.log](https://github.com/status-im/status-react/files/2856210/Status_win.log)
Recovery phrase for testing (can be used for issue reproducing to 13:57 CET 13/02/2019):
`green dolphin object priority undo inspire select under chimney public twin audit`

Nothing more after tesing stickers in 1-1, public, group chats on Mac OSx and Windows (Linux building is still blocked) as incoming and outgoing (after pairing) messages.

**Comment by churik** [comment]
@flexsurfer any comments?

**Comment by flexsurfer** [comment]
hey @churik , thanks for testing, good catch, i'll fix 1) , but i'm not sure about 2) why is it reproduced only on win, i'll check thanks

**Comment by flexsurfer** [comment]
@churik fixed
image

**Comment by churik** [comment]
@flexsurfer 
thanks for fix for 1, it is working!
According crash: I still got a crash when restore account on Windows or Linux with chat with stickers.
So steps are the same as described in https://github.com/status-im/status-react/pull/7452#issuecomment-462785892 ,but it is reproducible on Linux and Windows for me.
Crash-logs are here: [Status.zip](https://github.com/status-im/status-react/files/2871881/Status.zip)
Not sure that it can happen quite often. 
Separate issue or you can take a look now?

**Comment by flexsurfer** [comment]
@churik thanks, let's create a separate issue because I'm 100% sure it's not related to this PR, in this PR small local changes in UI has been made

**Pull request merged**
