### PR TITLE
[feature #5422] universal links scannable via QR code scanner

### LINKED ISSUE #5422: Public Chat QR codes scannable via status QR code scanner
### User Story

As a user, I want to be directed to a public chat when scanning a QR code representing the public chat's universal link so that I may participate in the public chat.

### Description

*Type*: Feature

*Summary*: 

Currently, the status QR code scanner returns an "unable to read this code" when scanning a QR code derived from a public chat universal link. https://wiki.status.im/Universal_Links.

screenshot_20180808-080403_status

#### Expected behavior

It is expected that when a QR code derived from a public chat unviersal link is scanned by a status user by following the path "+" -> "start new chat" -> "qr code symbol" the user is taken to the public chat. 

#### Actual behavior

When a public chat QR code is scanned, it returns an "unable to read this code" error pop up. 

### Reproduction

- On Status chat page tap on the "+" button. 
- Then tap on "start new chat"
- Then tap on the "QR code symbol" top the right of "enter contact code". 
- Then attempt scanning a QR code generated from a public chat unviersal link. 

For example attempt scanning this code generated from ETHIndia public chat group. 
ethindia-1

### Solution
*Summary*: 

Essentailly the public chat universal link format needs to be read as valid by the status QR code scanner when activated via the "start new chat" path. 

<blockquote><div><strong><a href="https://wiki.status.im/Universal_Links">Universal Links - Status Wiki</a></strong></div></blockquote>

### PR DESCRIPTION
**Pull request by yenda**
fixes #5422 

### Steps to test:
- any universal link should work when using qr code scanner from + button -> Scan QR code
- any contact code should work and redirect to contact profile, or own profile when scanning own contact code
- other QR codes should show a pop-up explaining that scanner was unable to read qr code

status: ready

### CODE REVIEW

**Review by janherich — APPROVED** [review]

**Review by Graeme-Code — APPROVED** [review]

**Comment by asemiankevich** [comment]
- [ ] scan QR code button:
1. opens user profile when scanning contact code
2.  ~~`Unable to read this code` when i scan `receive transaction` qr code (does not work on my Android 8, Huawei P10 lite, but works on @annadanchenko Android 6)~~
3. opens public chat when scanning universal link
4. Also i noticed that when i scan universal link for dapp (lets say https://get.status.im/browse/cryptokitties.co for ex) -> Open CK in Status -> tab Back (or cross) -> scanner is opened but i can't scan anything else. I need to close it and start from scratch if i want to scan second code in a row for example.

@yenda could you please take a look at points 2 and 4?


<blockquote><div><strong><a href="https://get.status.im/browse/cryptokitties.co">Browse to cryptokitties.co in Status</a></strong></div></blockquote>

**Comment by asemiankevich** [comment]
@errorists @hesterbruikman @jpbowen @denis-sharypin i need your design / ux approve here
image

**Comment by asemiankevich** [comment]
@yenda please place the `Scan QR code` button in the bottom of the list before `Invite friends` and add a line between `Start new chat` and `Scan QR code` list items.

**Comment by annadanchenko** [comment]
@yenda 
5. If scan invalid QR code (e.g from Receive transaction) then wrong text in error popup shown: "Unable to read this code Please enter or scan a valid contact code or username"
Expected: public chat is also mentioned as valid value in popup
Now:
screenshot_20180903-151403

**Comment by asemiankevich** [comment]
looks good

image

image

**Pull request merged**
