### PR TITLE
fix: user-avatar indicator size and position

### LINKED ISSUE #17188: Only a quarter of an online dot is visible on profile avatar
Perhaps Introduced by https://github.com/status-im/status-go/pull/3967

### Actual result:

https://github.com/status-im/status-mobile/assets/52490791/d0d5af97-2a63-40f0-a689-438d3cb1e5b6

### Expected result:
The online dot is visible fully

### Devices:
Android, IOS

CC: @yqrashawn

### PR DESCRIPTION
**Pull request by yqrashawn**
-------
fix #17188

### Summary
figma https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?type=design&node-id=107-5264&mode=design&t=3IlYad4D0crAiVcf-4

affected all avatars with status indicator
32x32

https://github.com/status-im/status-mobile/assets/15090582/6fd60192-e394-472e-bc82-c4d8ec67296d

80x80

https://github.com/status-im/status-mobile/assets/15090582/65214fa6-1651-4ec0-864c-ef1ea2f16e3a

status: ready

### CODE REVIEW

**Comment by yqrashawn** [comment]
back to draft, will fix the indicator position as well

**Review by flexsurfer — APPROVED** [review]

**Comment by qoqobolo** [comment]
@yqrashawn could you rebase PR, please?
Some important e2e fixes have just been merged, I'll need to rerun tests here.
Thanks!

**Comment by yqrashawn** [comment]
@qoqobolo rebase done

**Comment by qoqobolo** [comment]
Thanks for your work @yqrashawn!
PR is ready for design review @Francesca-G

**Review by Francesca-G — APPROVED** [review]
Looks good to me ✨

**Comment by FFFra** [comment]
This branch is out-of-date with the base branch. Can you please update it?

**Pull request merged**
