### PR TITLE
test_: bump go-waku with filter loop fix

### PR DESCRIPTION
**Pull request by richard-ramos**
Requires:
- https://github.com/status-im/status-go/pull/5909

cc: @chaitanyaprem @pavloburykh

### CODE REVIEW

**Comment by richard-ramos** [comment]
There seems to be a diff issue in the CI this time. Let's see what up

**Comment by siddarthkay** [comment]
Taking a look now

**Comment by siddarthkay** [comment]
should be fixed after https://github.com/status-im/status-mobile/pull/21390 is merged

**Comment by richard-ramos** [comment]
thank you, @siddarthkay. In the meantime while we wait for that to be merged, I rebased this PR against that so it can be tested!

**Comment by pavloburykh** [comment]
@chaitanyaprem @richard-ramos thank you for the PR. 

Our e2e run has failed because contact request sent by User A has not been delivered to receiver User B. 

Please check the logs below

[request_receiver_User_B.log](https://github.com/user-attachments/files/17275297/request_receiver_User_B.log)
[request_sender_User_A.log](https://github.com/user-attachments/files/17275298/request_sender_User_A.log)

**Comment by pavloburykh** [comment]
> ## 18% of end-end tests have passed
> ```
> Total executed tests: 51
> Failed tests: 42
> Expected to fail tests: 0
> Passed tests: 9
> ```
> 
> ```
> IDs of failed tests: 702845,702840,702894,703086,702855,702947,702730,702958,702786,702745,702731,702844,702851,703202,702841,703496,702807,702839,702733,702808,702809,702838,702813,704615,702948,702859,703629,703133,702957,702783,702843,702782,702850,702784,703391,702732,739307,703503,703297,703495,702777,703194 
> ```
> 
> ### Failed tests (42)
> Click to expand
> ### Passed tests (9)
> Click to expand

@chaitanyaprem I see the same issues in second run. 

Here are new logs

[receiver_User_B.log](https://github.com/user-attachments/files/17277708/receiver_User_B.log)
[sender_User_A.log](https://github.com/user-attachments/files/17277709/sender_User_A.log)

**Review by jakubgs — COMMENTED** [review]
Why the hell did the key changed?

**Comment by chaitanyaprem** [comment]
> Why the hell did the key changed?

you mean peerID in staging ams3 node? 

no idea, but i was noticing peerID mismatch errors in the mobile-CI logs which means it changed. 
as per anton it changed when fleet name was changed, would like to know how that happened as well.


`  267 WARN [10-07|10:39:14.135|github.com/status-im/status-go/vendor/github.com/waku-org/go-waku/waku/v2/peermanager/peer_manager.go:740]       connecting to peer                             peerID=16Uiu2HAmEqqio4UR1SWqAc7KY19t6qyDvtmyjreZpzUBJvb4u65R error="failed to dial: failed to dial 16Uiu2HAmEqqio4UR1SWqAc7KY19t6qyDvtmyjreZpzUBJvb4u65R:       all dials failed\n  * [/ip4/143.198.250.233/tcp/30303] failed to negotiate security protocol: peer id mismatch: expected 16Uiu2HAmEqqio4UR1SWqAc7KY19t6qyDvtmyjreZpzU      BJvb4u65R, but remote key matches 16Uiu2HAmQE7FXQc6iZHdBzYfw3qCSDa9dLc1wsBJKoP4aZvztq2d\n  * [/ip4/143.198.250.233/tcp/443/tls/sni/boot-01.do-ams3.shards.staging.stat      us.im/ws] failed to negotiate security protocol: peer id mismatch: expected 16Uiu2HAmEqqio4UR1SWqAc7KY19t6qyDvtmyjreZpzUBJvb4u65R, but remote key matches 16Uiu2HAmQE7      FXQc6iZHdBzYfw3qCSDa9dLc1wsBJKoP4aZvztq2d"`

**Comment by jakubgs** [comment]
Wait, why is this fleet called `shards`? There's no such fleet.
```
 > curl -sL fleets.status.im | grep shards | wc -l
0
```

**Review by jakubgs — COMMENTED** [review]
I can see someone changed the node key on 2024/07/05:

image

And it appears it was me, and the timing fits with the renaming:

image

**Comment by jakubgs** [comment]
I've reverted that change, but the fleets file here is way outdated since it's using wrong hostnames.

**Comment by chaitanyaprem** [comment]
> I've reverted that change, but the fleets file here is way outdated since it's using wrong hostnames.

you mean the peerID is again back to the old one now? 

iirc the older hostnames should still resolve isn't it?

**Comment by jakubgs** [comment]
>you mean the peerID is again back to the old one now?

Possibly, not sure if I got the right one, I just reverted to previous value. Renaming introduced some chaos.

>iirc the older hostnames should still resolve isn't it?

In theory, yes, but in practice we should be using new ones.

**Comment by jakubgs** [comment]
I switched the node key back to previous one since we can't actually determine what was the correct old one.

Please update the fleets file.

**Comment by churik** [comment]
@richard-ramos is it required for having that in 2.31?

**Comment by richard-ramos** [comment]
> @richard-ramos is it required for having that in 2.31?

cc: @chaitanyaprem as he is the author of the PR in status-go https://github.com/status-im/status-go/pull/5909

**Comment by richard-ramos** [comment]
As discussed in https://discord.com/channels/1110799176264056863/1184582858099150958/1293562297465180190 we do need it for 2.31 since getting this PR merged will also make available a lot of prev. fixes/features developed on go-waku merged on status-go 
image

**Comment by pavloburykh** [comment]
@chaitanyaprem recent e2e runs look good. But still, one of them has a failed test due to community has not been fetched. Maybe it is not PR related. Could you check the logs? 

**Steps:** 

1. User A (community Admin) shares community link to User B
2. User B opens the link
3. See if community is fetched for User B

**Actual result:** community has failed to be fetched. 

[User_A_community_admin.log](https://github.com/user-attachments/files/17326633/User_A_community_admin.log)
[User_B_opens_community_link.log](https://github.com/user-attachments/files/17326634/User_B_opens_community_link.log)

**Comment by pavloburykh** [comment]
@chaitanyaprem in case the above issue in not PR related it is ready for merge. Thank you.

**Comment by pavloburykh** [comment]
@chaitanyaprem large part of e2e has failed. Part of tests have failed because of our session provider but big part because of failed community fetching and not delivered contact requests. 

Please take a look at the logs and details below:

### ISSUE 1 Communities are not fetched

**Steps:** 

1. User A (community Admin) shares community link to User B
2. User B opens the link
3. See if community is fetched for User B

**Actual result:** community has failed to be fetched. 

[User_A_community_admin.log](https://github.com/user-attachments/files/17329070/User_A_community_admin.log)
[User_B_community_link_receiver.log](https://github.com/user-attachments/files/17329071/User_B_community_link_receiver.log)


### ISSUE 2 Contact requests are not delivered

**Steps:** 

1. User A sends contact request to User B
2. See if contact request has been delivered to User B

**Actual result:** contact request has not been delivered

[User_A_sender_of_contact_request.log](https://github.com/user-attachments/files/17329128/User_A_sender_of_contact_request.log)
[User_B_receiver_of_contact_request.log](https://github.com/user-attachments/files/17329129/User_B_receiver_of_contact_request.log)

**Review by friofry — APPROVED** [review]
As the status-go PR has already been approved, this PR just bumps the revision.

@jakubgs @yakimant Hopefully the fleet URLs are correct?

**Comment by pavloburykh** [comment]
ISSUE 1 and ISSUE 2 seem to be not PR related. Community fetching failure should potentially be fixed by this PR https://github.com/status-im/infra-status/pull/48

Regarding contact request delivery failure - it is probably related to https://github.com/status-im/status-mobile/issues/21151

**Pull request merged**
