### PR TITLE
Share community via URL with any privileges

### LINKED ISSUE #17116: Community invite is not received if it was shared by non-admin
# Bug Report

## Problem 
Community invite is not received if the user shares the community of which they are not admin.

#### Expected behavior
Can see the community invite 

#### Actual behavior
The unread badge is shown, but there is no invite to community in 1-1 chat

### Reproduction
**Prerequisites:**
- User1, User2 and User3 are contacts
- User1 creates any community and shares it with User2

**Steps:**
1) User2: community > options > Share community to User3
2) User3: see unread indicator > open chat with User2

### Additional Information

- Status version: nightly 25/08/23
- Operating System: Android, iOS

https://github.com/status-im/status-mobile/assets/4557972/f0eff0de-7ed4-4896-9abe-1589731ee0a1

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by ibrkhalil**
fixes #17116 

Allows non admins to share community by sharing a URL.

status: ready

### CODE REVIEW

**Review by flexsurfer — APPROVED** [review]

**Comment by pavloburykh** [comment]
@ibrkhalil thank you for the PR. Could you please updated status mobile branch? Status go is already up to date as far as I see. Thank you.

**Comment by ibrkhalil** [comment]
> @ibrkhalil thank you for the PR. Could you please updated status mobile branch? Status go is already up to date as far as I see. Thank you.

Done, Thanks!

**Comment by pavloburykh** [comment]
Hey @ibrkhalil! Thank you for great job, overall looks good to me. But still there is one issue which might become a blocker for our community e2e tests. 

### ISSUE 1 "Community admins will review you request" screen is displayed for some time before community page is loaded after first opening of community link


**Steps:** 

1. User A shares community to User B
2. User B Opens the community link
3. See if community home page is loaded right after following the link

**Actual result:** "Community admins will review you request" screen is displayed for some time before community page is loaded. Sometimes community screen is not loaded even after several link re-openings. 

[logs (17).zip](https://github.com/status-im/status-mobile/files/13652469/logs.17.zip)


photo_2023-12-12 21 28 55

**This is an example when "Community admins will review you request" screen is displayed just for a moment**

Link example https://status.app/c/CxiACi8KEmFwcHIgcmVxIG5vIHBlcm0gMhIJdnNkdmRzdnNkGAgiByM0MzYwREYqAyMHCgM=#zQ3shesZvchewDj2VsNqmmAhmiwTVjAqkvj1eMsAU5CgEXLMc

https://github.com/status-im/status-mobile/assets/97245802/35c66636-3091-4d5f-8dc3-7c8434d13465

**This is an example when "Community admins will review you request" screen is displayed every time and community screen failed to be loaded**

Link example https://status.app/c/G0UAAMTyNsn2QZDEG0EXftOl8pOEfwEBOOSA_YTfIk85xmADDgINGmxpUHAXzK36bN0fK42Xf4YD2yjPk1z2pbFwFw==#zQ3shcmiJnfj4pLWApgWzP5mYHNj9MsuPRNoUbSfGfPgrEtf7


https://github.com/status-im/status-mobile/assets/97245802/49cbf773-18b2-42da-8f1e-dc7586167d70

**Comment by pavloburykh** [comment]
@ibrkhalil also mind that this PR is a breaking change for our e2e tests, as we previously used community invite cards which are removed by this PR. So besides fixing ISSUE 1 we will need to update our e2e before merging this PR. 

BTW, I have not found any info in PR description about removing community invites in scope of this PR. Would appreciate if such changes are noted in description next time. I was aware about them from some of previous Discord threads but for some other QA it could be confusing to see links instead of invite cards. Thank you!

**Comment by pavloburykh** [comment]
@ibrkhalil thanx for the PR. Failed e2e are not PR related. Ready for merge.

**Pull request merged**
