### PR TITLE
Removed dapps list and introduced simple Dapp store dapp

### PR DESCRIPTION
**Pull request by flexsurfer**
https://youtu.be/N_Ug_KRFlVI

### CODE REVIEW

**Review by errorists — APPROVED** [review]

**Review by goranjovic — APPROVED** [review]

**Comment by goranjovic** [comment]
nice PR, lots of red in it :+1:

**Review by jeluard — CHANGES_REQUESTED** [review]
Not clear yet when we want this merged.

**Comment by rachelhamlin** [comment]
Hey @asemiankevich, could you test this PR this week? Would like to include it in next release, assuming DApp Store is live by Tuesday.

**Review by rachelhamlin — DISMISSED** [review]
URL to be updated to https://dap.ps

**Comment by annadanchenko** [comment]
@flexsurfer @rachelhamlin it looks like PR is not ready for testing yet: branch has conflicts and there are changes requested, so it should be done before we'll start testing.

Screen Shot 2019-04-09 at 22 03 31

**Comment by flexsurfer** [comment]
@Serhy conflicts are resolved, @rachelhamlin @jeluard could you approve if we want to test this PR

**Review by jeluard — APPROVED** [review]

**Review by jeluard — APPROVED** [review]

**Comment by Serhy** [comment]
@flexsurfer all builds are failing with `Error encountered performing task 'cljsbuild' with profile(s): 'prod'` :(

**Comment by flexsurfer** [comment]
@Serhy fixed

**Comment by Serhy** [comment]
@flexsurfer 
1) The 'Share' button on any DApp (ir DappStore itself) picks up a weird value instead of Dapp URL for the universal link (it's element ID or something like that): E.g. for DappStore itself it's `Check out this DApp I'm using on Status: https://get.status.im/browse/1555071219994-902cf606-3fed-54cb-9560-4845578e853f`. For CryptoKitties it's `Check out this DApp I'm using on Status: https://get.status.im/browse/1555071219994-902cf606-3fed-54cb-9560-4845578e853f`

However, if particular Dapp is opened from 'Recent' list it's all fine and Share button picks up the URI value what is in the URL input. 

Screenshot 2019-04-12 at 16 45 55

2. Because simpledapp.eth is the address exists only on Mainnet and Ropsten - DappStore now opens only for that network (it's the same for SimpleTestDapp as well). Before we merge it, will need to check if https://dap.ps behaves correctly on any other networks.

**Comment by Serhy** [comment]
@rachelhamlin could you please let us know when https://dap.ps is ready and available for integration (Fixes for above https://github.com/status-im/status-react/pull/7739#issuecomment-482586642 depends on live DappStore link)

**Comment by flexsurfer** [comment]
one | two
--- | ---
image | image

**Comment by flexsurfer** [comment]
@Serhy 
1-fixed
2-because https://dap.ps is a usual web2 domain, we don't need to resolve it, so it will work in any network

**Comment by Serhy** [comment]
Looks cool to me!

One small issue to address is that when items deleted from 'Recent' list `swip-left` -> `Delete` - whole Dapp screen blinks. 
Video of issue: https://drive.google.com/file/d/1J1G71RsEJS32rUPPUgYali_KXT73PSRz/view
@flexsurfer If we can fix it in the scope of this PR that would be awesome. Or could be done with separate issue.

And `https://dap.ps` side issue ( the same with desktop browser i.e. Chrome/FF):
If Dapp (e.g. cryptokitties) was opened from dap.ps/all or dap.ps/categories page - navigating back (in browser) the `dap.ps/all` / `dap.ps/categories` URL is requested which replies with 404.

**Comment by Serhy** [comment]
When opening `Join the DApp community chat` / `Support` at the bottom of Dapp store, - there is enless loading  on Dapp screen - separately logged https://github.com/status-im/status-react/issues/7996 (the same issue in nightly too)

**Comment by flexsurfer** [comment]
@Serhy  fixed blink

**Comment by Serhy** [comment]
@flexsurfer indeed it's fixed on iOS completely. But with Android (v8.1, v6.0.1 tested) it's almost perfect. 
Before the fix, all the elements on Dapp view were blinking when swipe-to-delete browsed history. 

On **Android** now blinks only icons part of DappStore. It's less noticeable than before, but still would be amazing to perfectize Android part too.

Screenshot 2019-04-18 at 16 11 13

**Comment by flexsurfer** [comment]
@Serhy yeah, agree with you, but i haven't found the solution, let's file a new issue for this, because it's not really often when users will delete these items

**Comment by Serhy** [comment]
Ok, agreed. Let's merge, @flexsurfer !

**Pull request merged**
