### PR TITLE
use auto@status.im Apple account for signing app

### PR DESCRIPTION
**Pull request by jakubgs**
Changing to a different Apple account to avoid the Two-Factor Auth mess that Apple made mandatory for all "Holder" accounts like our support@status.im.

### CODE REVIEW

**Review by mandrigin — APPROVED** [review]
lgtm!

**Comment by jakubgs** [comment]
Holy shit it works!
amazing
I think...

**Review by pedropombeiro — APPROVED** [review]

**Comment by churik** [comment]
@jakubgs anything specific to test here, except IOS build?
Already checked:
- can install build
- can create an account
- can restore existing account

Also checked Mac OSx build

**Comment by jakubgs** [comment]
I don't think so. As long as iOS installs and runs then we know the signing process was successful. Thakns for testing!

**Comment by jakubgs** [comment]
I added changes in `ci/Jenkinsfile.fastlane.clean` to fix the [Clean TestFlight Users](https://ci.status.im/job/status-tools/job/Clean%20Testflight%20Users/) Jenkins job. Also modified it to use the new pipeline format.

**Comment by churik** [comment]
Can install latest IOS build, create account - considering PR as ready to merge

**Pull request merged**
