### PR TITLE
Expose whisper (shh) events #7076

### LINKED ISSUE #7076: Expose whisper (shh) events
### User Story

As a developer, I want to send whisper messages from extensions.

### Description

Not exactly clear what we want to do here so part of the issue is to come up with a coherent proposal.

*Type*: Feature

### PR DESCRIPTION
**Pull request by shamardy**
Closes #7076

### CODE REVIEW

**Comment by jeluard** [comment]
@shamardy Great start! Are you planning to implement the others whisper functions?

**Comment by shamardy** [comment]
@jeluard Yes, I plan to implement the other functions. Sorry for the delay.

**Comment by jeluard** [comment]
@shamardy Let me know when you feel like this PR is ready :)

**Comment by shamardy** [comment]
@jeluard Yes, this is ready for review.

**Review by jeluard — APPROVED** [review]

**Comment by jeluard** [comment]
@shamardy Could you squash your commits?

**Review by flexsurfer — APPROVED** [review]

**Review by goranjovic — APPROVED** [review]

**Comment by jeluard** [comment]
@shamardy Actually you will also have to rebase with latest master due to some internal issue. Sorry for the inconvenience.

**Comment by antdanchenko** [comment]
@shamardy please remove [lines](https://github.com/status-im/status-react/blob/67a47fac561f12a7835b269cb6519766e319510a/test/appium/tests/atomic/chats/test_commands.py#L397-L398) in this PR, for some reason this check is failing, but we don't need that check anymore since we are removing the address caption in #7416

**Comment by antdanchenko** [comment]
@shamardy please ignore my deleted comment

**Comment by asemiankevich** [comment]
@jeluard based on the description `Not exactly clear what we want to do here so part of the issue is to come up with a coherent proposal.` which testing is expected here?

**Comment by jeluard** [comment]
@asemiankevich Just sanity checks. Make sure there is no weird regression? :)

**Comment by asemiankevich** [comment]
> @asemiankevich Just sanity checks. Make sure there is no weird regression? :)

e2e are passed, asking if we need to test more here

**Comment by jeluard** [comment]
@asemiankevich no new features

**Comment by jeluard** [comment]
@shamardy Could you edit the commit message? It's a bit long :)

**Pull request merged**
