### PR TITLE
Add update-status-go.sh script

### PR DESCRIPTION
**Pull request by adambabik**
### Summary:

Add a utility script that simplifies upgrading status-go version.

### Usage:

```
$ ./scripts/update-status-go.sh develop-g246c5321
```

### CODE REVIEW

**Review by cammellos — APPROVED** [review]
@adambabik maybe worth adding a `README.md` in the `scripts` directory documenting the usage? but looks good, thanks

**Comment by adambabik** [comment]
@cammellos I don't see `README.md` in `scripts/` so I added support for `-h` and usage section explaining what it does instead.

**Comment by cammellos** [comment]
@adambabik yes, sorry, I meant to create it, but usage in the scripts works just as well, thanks!

**Comment by jeluard** [comment]
@adambabik Can you squash your commits?

**Comment by adambabik** [comment]
@jeluard I can squash and merge. Would that be ok? Or you need me to squash them for a different purpose.

**Comment by jeluard** [comment]
@adambabik If you merge make sure you use our scripts to have the commit signed.

**Pull request merged**
