### PR TITLE
[fix] request the right topic from inbox when adding new key

### PR DESCRIPTION
**Pull request by yenda**
there will not be any visible effect with this PR as long as we use public key to send messages

status: ready

### CODE REVIEW

**Review by janherich — APPROVED** [review]

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/K4Jgax for branch PR-4256

<blockquote><div><strong><a href="https://i.diawi.com/K4Jgax">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/uZerra for branch PR-4256

<blockquote><div><strong><a href="https://i.diawi.com/uZerra">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Review by cammellos — APPROVED** [review]

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/AJPMeE for branch PR-4256

<blockquote><div><strong><a href="https://i.diawi.com/AJPMeE">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/yb29wf for branch PR-4256

<blockquote><div><strong><a href="https://i.diawi.com/yb29wf">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Pull request merged**
