### PR TITLE
fix: don't delete notification by last-message id

### LINKED ISSUE #17052: All replies and mentions are removed in AC for receiver after sender removes the last message in community chat
### Steps to reproduce:
1. `User_A` and `User_B` are both in the same community.
2. `User_A` sends several replies or mentions to `User_B`.
3. `User_A` sends one more message and then deletes it using the 'delete for everyone' option.
4. `User_B` checks the AC.

### Actual result:
All mentions and replies in the AC are removed for `User_B`.

### Expected result:
Mentions and replies should not be removed from the AC after the last message is deleted.

### Additional info:
This issue is similar in group chats, with the exception that only replies are removed from the AC. Mentions are not removed and

### PR DESCRIPTION
**Pull request by yqrashawn**
https://github.com/status-im/status-go/compare/1ef2434b...33d74c57

-------

status-go PR https://github.com/status-im/status-go/pull/5520

fixes #17052

### Summary

details at https://github.com/status-im/status-mobile/issues/17052#issuecomment-2227722751

#### Platforms

- Android
- iOS

#### Areas that maybe impacted
delete notification when deleting message

### Steps to test
- in a community channel
- user A mention user B 3 times
- user B should see 1, 2, 3 unread notification in activity center
- user A delete last mention
- user B should see 2 unread notifications in activity center

status: ready

### CODE REVIEW

**Comment by yqrashawn** [comment]
not ready, need to update other notifications's last message

**Comment by yqrashawn** [comment]
https://github.com/user-attachments/assets/1068e630-5102-4cc5-a38a-70de8c5058fe

**Comment by yqrashawn** [comment]
ready for review now

**Review by ilmotta — APPROVED** [review]

**Review by flexsurfer — APPROVED** [review]

**Comment by yqrashawn** [comment]
next up: https://github.com/status-im/status-go/pull/5520#issuecomment-2270223309

**Comment by seanstrom** [comment]
Closing in favour of this PR: https://github.com/status-im/status-mobile/pull/21157

**Pull request closed without merging**
