### PR TITLE
Add Uniswap to default DApp list

### LINKED ISSUE #7596: Add Uniswap DApp
### Description

Add Uniswap DApp. 

**Name:** Uniswap
**URL:** https://uniswap.exchange
**Description:** Uniswap offers automated ERC20 exchange on Ethereum. There is no token, platform fee or listing free.
**Category:** Exchanges

Needs logo.

### PR DESCRIPTION
**Pull request by brockelmore**
fixes #7596 

status: ready

### CODE REVIEW

**Review by flexsurfer — APPROVED** [review]

**Review by mandrigin — APPROVED** [review]

**Comment by annadanchenko** [comment]
autotests triggered in https://ci.status.im/job/end-to-end-tests/job/status-app-end-to-end-tests/2505/

**Comment by churik** [comment]
@brockelmore 
No icon is shown for Uniswap Dapp.

img_0ef557d07400-1

Exchange is working fine with Status from my POV, access to wallet is requested and I can sell some SNT.

**Comment by jeluard** [comment]
@brockelmore You also need to update `src/status_im/react_native/resources.cljs`
See this PR as example: https://github.com/status-im/status-react/pull/7845/files

**Comment by flexsurfer** [comment]
@rachelhamlin should we close this PR as well? cc @andytudhope

**Comment by andytudhope** [comment]
Added in this commit https://github.com/status-im/discover-dapps/commit/8db200bef2c8110a6d4a5d57cfc1b7da06651b14

**Pull request closed without merging**
