### PR TITLE
remove git tag steps that seem pointless

### PR DESCRIPTION
**Pull request by jakubgs**
I really don't see what these are for so I'm just gonna drop them
This is causing nightly builds to fail:
https://jenkins.status.im/job/status-react/job/nightly/391/console
```
+ git tag -d 0.9.16-189-g436ac1d7-1-gc80d4bd6
error: tag '0.9.16-189-g436ac1d7-1-gc80d4bd6' not found
```
We had a thread about this here:
https://status-im.slack.com/archives/C8QP8S5UH/p1526475180000522

If anyone knows what this is for please tell me.

<blockquote></blockquote>
<blockquote><div><strong><a href="https://status-im.slack.com/archives/C8QP8S5UH/p1526475180000522">Slack</a></strong></div></blockquote>

### CODE REVIEW

**Review by mandrigin — APPROVED** [review]
👍

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/bSxfK5 for branch PR-4305

<blockquote><div><strong><a href="https://i.diawi.com/bSxfK5">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Review by lukaszfryc — APPROVED** [review]

**Comment by mandrigin** [comment]
@jakubgs I actually had to push this old tag to our GitHub repo to fix the release jobs 🙀 So, I'll be so glad to see this lines gone!

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/smGXbr for branch PR-4305

<blockquote><div><strong><a href="https://i.diawi.com/smGXbr">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Review by rasom — APPROVED** [review]

**Pull request merged**
