### PR TITLE
[#17395] Temporarily disables image options in edit mode

### LINKED ISSUE #17395: Images are not sent if added during message editing
**Steps:**

1. Send a text message
2. Open message aditing
3. Add image/images during editing
4. Send edited message
5. See if images were sent

**Actual result:** images were not sent

**Expected result:** currently editing feature is not implemented with images. This is a reason why we do not show edit button for messages containing images. So in this case we probably need to disable Add image button when editing a message until we implement this feature. 

https://github.com/status-im/status-mobile/assets/97245802/4564579e-a1f7-4c96-81db-8d43cf3cff66

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

### PR DESCRIPTION
**Pull request by SilentCruzer**
fixes #17395 

### Summary
Disabled the camera and pick-from-galley button during editing mode since it has not been implemented yet.

#### Platforms
- Android
- iOS

### Steps to test
- Open Status
- Open a chat
- Long press any message that you have sent and choose edit-message.
- The image options will result in a popup saying it is disabled in the editing mode.
- THe buttons will work as normal when composing a new message.

### Demo
https://github.com/status-im/status-mobile/assets/73246484/5d366375-05fb-4bcd-a7e1-b20daa6e1df9

status: ready

### CODE REVIEW

**Review by ibrkhalil — APPROVED** [review]

**Review by flexsurfer — APPROVED** [review]

**Comment by pavloburykh** [comment]
Hello @jakubgs! Could you please add @SilentCruzer to repo collaborators with read permissions, so he be able to trigger the jobs? Thank you.

**Comment by flexsurfer** [comment]
or @siddarthkay could open PR with the script?

**Comment by jakubgs** [comment]
@pavloburykh done.

image

**Comment by pavloburykh** [comment]
@SilentCruzer please rebase the PR in order to trigger builds.

**Comment by pavloburykh** [comment]
@SilentCruzer thank you for your contribution. PR is tested and ready for merge.

**Pull request merged**
