### PR TITLE
remove the rest of testfairy's mentions from the project

### PR DESCRIPTION
**Pull request by rasom**
It is not running in the project already, but some mentions haven't been cleared. 

status: ready

### CODE REVIEW

**Comment by chadyj** [comment]
~testflight~ testfairy

**Comment by rasom** [comment]
@chadyj fixed

**Review by dmitryn — APPROVED** [review]

**Review by yenda — APPROVED** [review]

**Review by janherich — APPROVED** [review]

**Comment by rasom** [comment]
it seems i broke autotests

**Comment by lukaszfryc** [comment]
@rasom there were broken by other change. I'll rerun them now.

**Comment by lukaszfryc** [comment]
I did a quick smoke test on iOS and macOS and also reviewed E2E. All looks fine 👍

**Pull request merged**
