### PR TITLE
[#5226] Migrate clj scripts to latest clj-rn

### LINKED ISSUE #5226: Migrate clj scripts to latest clj-rn
### User Story

As a developer, I want to reduce the number of commands/shells I have to use.

### Description

*Type*: Feature

Latest `clj-rn` removes the need for `react-native start`. Migrate clj conf to this model.

### PR DESCRIPTION
**Pull request by endenwer**
fixes #5226

### Summary:
Use `clj-rn` for development.

### Steps to test:
- Run `make stardev-ios-simulator` or similar.

status: ready

### CODE REVIEW

**Comment by endenwer** [comment]
Files `/env/dev/figwheel.clj`, `/env/dev/figwheel_api.clj` and `/env/dev/run.clj` are not used anymore even without this pr. I don't know if I should delete them or not. Maybe someone uses them to start figwheel.

**Comment by flexsurfer** [comment]
@endenwer i believe we can remove them, thanks, is this PR still WIP?

**Comment by endenwer** [comment]
@flexsurfer ok, I will remove them. It is still WIP, I wait for this to be merged https://github.com/status-im/clj-rn/pull/10

**Comment by alwx** [comment]
good job, @endenwer. thanks!

**Comment by jeluard** [comment]
@endenwer Awesome! I like all this red :D

**Comment by flexsurfer** [comment]
@endenwer do we still need `config.cljs` and `utils.cljs` files here https://github.com/status-im/status-react/tree/develop/env/dev/env ?


<blockquote><div> GitHub</div><div><strong><a href="https://github.com/status-im/status-react">status-im/status-react</a></strong></div><div>status-react - a free (libre) open source, mobile OS for Ethereum</div></blockquote>

**Comment by endenwer** [comment]
Yes. It is used in main files. For example, here https://github.com/status-im/status-react/blob/develop/env/dev/env/ios/main.cljs

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/status-im/status-react">status-im/status-react</a></strong></div><div>status-react - a free (libre) open source, mobile OS for Ethereum</div></blockquote>

**Comment by endenwer** [comment]
It is ready now.

**Review by flexsurfer — APPROVED** [review]

**Comment by yenda** [comment]
@endenwer is there a way to make the deps downloading retry a couple times before throwing an error ? I had to run the script 3 times getting that kind of errors:

```Downloading: figwheel-sidecar/figwheel-sidecar/0.5.16/figwheel-sidecar-0.5.16.jar from https://repo.clojars.org/
Error building classpath. Could not transfer artifact ring-cors:ring-cors:jar:0.1.12 from/to central (https://repo1.maven.org/maven2/): connect timed out```

**Comment by endenwer** [comment]
@yenda I don't think there is a way to control deps downloading. This is official documentation https://clojure.org/reference/deps_and_cli

<blockquote><div><strong><a href="https://clojure.org/reference/deps_and_cli">Clojure - Deps and CLI</a></strong></div></blockquote>

**Comment by yenda** [comment]
@endenwer also I got 
```
BUILD SUCCESSFUL in 1m 5s
40 actionable tasks: 38 executed, 2 up-to-date
task not available - required dependencies not found
```
when running
```
make prepare-android
clj -R:repl build.clj watch --platform android --android-device avd --nrepl-port 7888
```

**Comment by endenwer** [comment]
@yenda You need to run `clj -R:dev build.clj watch --platform android --android-device avd --nrepl-port 7888`.

**Comment by endenwer** [comment]
@yenda But better run `make startdev-android-avd`

**Comment by yenda** [comment]
@endenwer thanks! --nrepl-port doesn't work anymore. `[Unknown option: "--nrepl-port"]`

I can't use make startdev-android-avd because I want the nrepl port to connect with cider and start the cljs-repl in emacs for interactive development. Unless I'm missing something I don't see another way ?

Looks like the option is missing now in https://github.com/status-im/clj-rn/blob/master/src/clj_rn/main.clj#L102

**Comment by endenwer** [comment]
@yenda It is now specified in config file.

**Comment by yenda** [comment]
@endenwer actually it's all good it works with `startdev-android-avd` as well I can use `cider-connect` and `(figwheel-sidecar.repl-api/cljs-repl)` and interact with the running app.

Thanks for all the good work !

**Review by yenda — APPROVED** [review]

**Review by maxhora — CHANGES_REQUESTED** [review]
Removing of re-natal's figwheel related sources might break Desktop project dev build since Desktop still utilize re-natal to run with fighweel. Will investigate if this the case and post update here.

**Comment by maxhora** [comment]
@endenwer 

> Files /env/dev/figwheel.clj, /env/dev/figwheel_api.clj and /env/dev/run.clj are not used anymore even without this pr. I don't know if I should delete them or not. Maybe someone uses them to start figwheel.

Yes, re-natal with figwheel is still used by Desktop and removing of these files breaks dev build for Desktop app. Could you please move the files back? Thanks!

**Comment by maxhora** [comment]
Have created separate issue to not forget that we want to eliminate re-natal from Desktop as well https://github.com/status-im/status-react/issues/5339

**Comment by endenwer** [comment]
@MaxRis I returned the files. clj-rn does't support desktop yet but there is already pr for this.

**Review by maxhora — APPROVED** [review]
@endenwer thank you! desktop dev build compiles fine now

**Review by alwx — APPROVED** [review]

**Comment by jeluard** [comment]
@endenwer Thanks for your contribution!

**Pull request merged**
