### PR TITLE
Temporary that makes it possible to install only one extension at a time (required for the hackathon)

### LINKED ISSUE #6356: Allow only 1 extension to be added for account
### Description

*Type*: Bug

*Summary*: Since we technically limited extensions to have only 1 for now (current limitation) we need to do the same in UI and don't confuse user.

#### Expected behavior
1 extension could be added for an account in UI

#### Actual behavior

Now I can add as many as I want however only 1 persists in database

image

### Reproduction

- Open Status
- Enable dev mode
- Add >1 extension

### PR DESCRIPTION
**Pull request by alwx**
This thing needs to be removed in the future
Fixed #6356

### CODE REVIEW

**Review by jeluard — APPROVED** [review]

**Review by rasom — APPROVED** [review]

**Comment by rasom** [comment]
restarted build because most likely if failed without reason

**Comment by Serhy** [comment]
Hey @alwx, Jenkins jobs were failed but on different steps, so iOS build (https://i.diawi.com/GJKvhd) and Android (https://ci.status.im/job/status-react/job/combined/job/mobile-android/5629/artifact/StatusIm-181020-153657-b8e17c-pr.apk) builds were created and we tested them:

So if one extension has been added to account, the second, third and so on, - could be added as well but they "replace" previous extensions. This makes sense! However, "extension replacement" changes will take place only after account re-login. Means, if user in the same app session (without re-login) adds three extensions - all of three extensions are available in a list of commands for 1-1 chat. 
 
**Steps to reproduce:** 
1) Open Status and create new account
2) Add first extension: (e.g. use this one https://get.status.im/extension/ipfs@QmbRSgiRbefK8J1Jc2PCLHUh6M33K8r9Bt1mFvP2acYCbf - hook value here is `collectible1`)
3) Add second extension (e.g. use this one https://get.status.im/extension/ipfs@QmbMui8Z36LwFgbtG1vSRAjPmoVVvDQsNomtTtZw6TChJC - hook value here is `collectible2`)
4) After you added the second extension navigate to `Extensions` list:
**Actual result = Expected result:** Collectible2 extestion only is present.
5) Add any contact so you could navigate to 1-1 chat
6) Check 1-1 chat commands list that there is a single `collectible2` command exist
**Actual result:** `/collectible1` and `/collectible2` commands are present
7) Re-login to account
8) Check 1-1 chat commands list that there is a single `collectible2` command exist
**Actual result = Expected result:** `/collectible2` extension command is present only.

Could we force the update of "extension replacement" without re-login? 


<blockquote><div><strong><a href="https://i.diawi.com/GJKvhd">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>
<blockquote></blockquote>
<blockquote></blockquote>
<blockquote></blockquote>

**Comment by Serhy** [comment]
Or, alternatively and also temporary, - force account re-login after extension is added

**Review by janherich — APPROVED** [review]

**Comment by alwx** [comment]
Good catch, thanks.
Has been fixed.

**Comment by alwx** [comment]
Good catch, thanks.
Has been fixed.

**Comment by Serhy** [comment]
All looks good now! 
Only 1 extension could be installed for account. Installing second and third extension leads to replacement of the existing extension, and the latest one installed reflected as a single command in 1-1 chat screen without the need to re-login (https://github.com/status-im/status-react/pull/6428?#issuecomment-431675488 = PASS)
Autotests reviewed and confirmed are existing issues already in GitHib (and known False Fails are in develop as well which is in progress to be fixed)

This one is ready for merge!

**Pull request merged**
