### PR TITLE
Blue hashtags (#435)

### LINKED ISSUE #435: no #hashtags are blue
in drawer, profile edit and user profile screen and in discover none of the hashtags are displayed as blue ?

### PR DESCRIPTION
**Pull request by alwx**
Fixes #435

### CODE REVIEW

**Comment by jarradh** [comment]
looks great!

-[ ] one thing i notice is that even though new lines are still allowed in the status and are removed after the fact, i think if the user hits enter, they have finished writing the status.

- [ ] also the shadows on the popular discover cards is not correct anymore? there is shadow on the top where it is not the case in https://zpl.io/Z1p9XlV

**Comment by alwx** [comment]
@jarradh this is the default android shadow (it is called elevation) and it looked absolutely the same way before. The problem is we cannot control its opacity or anything thus it is impossible to make it look absoultely the same way on screenshots. I've reduced the size of this shadow, but it is still different.

**Comment by jarradh** [comment]
i doubt it is _impossible_ just it needs to be done in a different way

**Comment by rasom** [comment]
Statuses are missed
screen shot 2016-11-22 at 14 06 01

**Comment by rasom** [comment]
```
WARNING: Use of undeclared Var status-im.discovery.views.discovery-list-item/message-id at line 36 src/status_im/discovery/views/discovery_list_item.cljs
WARNING: Use of undeclared Var status-im.discovery.views.discovery-list-item/status at line 38 src/status_im/discovery/views/discovery_list_item.cljs
```

**Comment by alwx** [comment]
@rasom sorry, it was a merge-related problem. Fixed it.

**Comment by rasom** [comment]
```
i think if the user hits enter, they have finished writing the status.
```

@alwx, as I understand you didn't implement this, correct?

**Comment by alwx** [comment]
why? it is implemented

**Comment by rasom** [comment]
a

**Comment by rasom** [comment]
it works on iOS

**Comment by jarradh** [comment]
can confirm, this is what i saw today on Android

**Comment by alwx** [comment]
seems like onBlur doesn't work properly on Android

**Comment by jarradh** [comment]
we can probably read the text of the string and if it has line break character at the end, it can be treated as onBlur

**Comment by alwx** [comment]
It is a bit hacky, but it works now

**Pull request merged**
