### PR TITLE
Photo selector fix

### LINKED ISSUE #14580: The unchecked images  in the selector are still shown as selected within textbox of chat
**Steps to reproduce:**
1. Open 1-1 chat
2. Tap the 'image' icon to select some images
3. Select <image_1> and <image_2> -> tap [confirm] button
4. Tap the 'image' icon one more time
5. Uncheck <image_2> in the selector -> tap [confirm] button

**Actual result:**
<Image_2> is still shown as selected within a textbox
https://user-images.githubusercontent.com/52490791/208525439-45b1a124-d218-4201-a48a-b7306ea74ede.mp4

**Expected result:**
The <image_2> is not shown if it is unchecked within a selector

### PR DESCRIPTION
**Pull request by OmarBasem**
fixes: https://github.com/status-im/status-mobile/issues/14580

This PR fixes a bug in photo selector as described in the above issue.

### CODE REVIEW

**Comment by du82** [comment]
Still facing this issue

Screenshot_2022-12-27-00-45-39-17_435383e61849826ed84c38f611283930

**Comment by OmarBasem** [comment]
@du64 when you reopen the photo selector, unselect an image, then press "confirm selection" it does not update?

**Comment by OmarBasem** [comment]
@du64 oh I think you mean the 'X' button UI? That's a different issue.

**Comment by du82** [comment]
> @du64 oh I think you mean the 'X' button UI? That's a different issue.

yes this

**Review by ilmotta — APPROVED** [review]

**Comment by OmarBasem** [comment]
@VladimrLitvinenko PR ready to be tested

**Comment by pavloburykh** [comment]
Thanx @OmarBasem ! Initial issue seems to be fixed. Please take a look at following issue. 

### ISSUE 1 Confirm select button disappears when all images are unselected

Currently it is not possible to confirm changes after unselecting all images as Confirm select button disappears. 

**Steps:** 

1. Start chat
2. Select images and confirm selection
3. Go back to images selection and unselect all previously selected images
4. See Confirm select button is presented and it is possible to save changes

**Actual result:** It is not possible to confirm changes after unselecting all images as Confirm select button disappears

**Expected result:** it should be possible to save changes after unselecting all previously selected images (e.g. Confirm select button should be shown)

https://user-images.githubusercontent.com/97245802/209656480-7da0dc2d-c6bc-4f64-844b-81e5e1ebf821.mp4

**Comment by pavloburykh** [comment]
### Question 1: 

Currently selected images are cut in message input field on Android so it is hard to tap [X] button to unselect them. Is it related to bottom-sheet global problem or it is a separate one and can be fixed in scope of this PR? 

photo_2022-12-27 12 58 57

**Comment by OmarBasem** [comment]
@pavloburykh thanks for your review!

Issue 1: fixed
Question 1: fixed (tho it may not be very easy to press, but this is the current design. Will try to discuss with the design team if there is a better way to do it)

**Review by qfrank — APPROVED** [review]

**Comment by pavloburykh** [comment]
@OmarBasem thank you for the fixes. PR is tested and ready for merge.

**Pull request merged**
