### PR TITLE
WIP: Abstracting out top bar / list header + replacing community header 

### LINKED ISSUE #17601: Community header issues
### ISSUE 1 Joined/pending tag overlays community banner

**Steps:** 

1. Open community screen
2. Send request to join the community
3. Pay attention at Joined/pending tags position

**Actual result:** tags overlay community banner

photo_2023-10-10 12 23 56
photo_2023-10-10 12 23 59

**Expected result:** 

[Figma](https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?type=design&node-id=1733-127837&mode=design&t=Eb3FaNbz3IY0FKMd-0)

Communities for Mobile – Figma 2023-10-10 12-24-34

### ISSUE 2 Community name and logo are located too close to the banner and go beyond the screen

**Steps:** 

1. Join community
2. Reopen home community screen
3. Pay attention at community name and logo position

**Actual result:** 

photo_2023-10-10 12 26 44

**Expected result:** 

[Figma](https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?type=design&node-id=10276-409196&mode=design&t=Eb3FaNbz3IY0FKMd-0)

Communities for Mobile – Figma 2023-10-10 12-03-35

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

### LINKED ISSUE #17622: Community/Discover – Community header design deviates from Figma mockups (corners are not rounded)
# Bug Report
[Figma design](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS/Feedback-for-Mobile?type=design&node-id=6117-85237&mode=design&t=BNlP5YQ740n4i2xY-0)

## Problem 
The community header in the app does not match the Figma design. Specifically, the header should be overlaid by a rounded card, an effect that is missing in the current implementation.

#### Expected behavior

image

#### Actual behavior

image

### Reproduction

1. Navigate to any community page in the app.
2. Observe the header design.

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by alwx**
fixes https://github.com/status-im/status-mobile/issues/17622
fixes https://github.com/status-im/status-mobile/issues/17601
fixes https://github.com/status-im/status-mobile/issues/17622

also abstracts out the top bar component and list header components to make it possible to use them in other parts of the application as well

status: wip

### CODE REVIEW

**Comment by flexsurfer** [comment]
hey @alwx still relevant?

**Comment by flexsurfer** [comment]
hey @alwx still relevant?

**Comment by alwx** [comment]
@flexsurfer I would like to keep it for now because I will certainly return back to it after the main scope of work is done.

**Comment by flexsurfer** [comment]
will close it for now, feel free to reopen

**Pull request closed without merging**
