### PR TITLE
Enabling WalletConnect feature flag

### LINKED ISSUE #20835: Enable wallet connect feature flag by default
### User Story

As a user, I want to have a access to the wallet connect functionality, so that I can interact with dapps.

### Description

Should enable the wallet connect feature flag by default, so it's available to the users. 

> **Must be the last PR before the branch is cut.**

### Acceptance Criteria

* The users of the production build have access to wallet connect without toggling the feature flag

### Notes

[comment]: # (For the developer who will implement. Include planning poker estimates, guidance, etc.)

### PR DESCRIPTION
**Pull request by clauxx**
fixes #20835

### Summary

Enabling wallet connect functionality by setting the feature flag default value to true.

status: ready

### CODE REVIEW

**Review by J-Son89 — APPROVED** [review]
nit: the title of this pr is a bit misleading.

it's not removing but setting the default to true, no?

**Comment by clauxx** [comment]
> nit: the title of this pr is a bit misleading.
> 
> it's not removing but setting the default to true, no?

You're right, fixed the name. Thanks!

**Review by shivekkhurana — APPROVED** [review]
image

**Comment by clauxx** [comment]
### ISSUE 1

Pending dapp requests are not triggered when switching testnet to mainnet

1. Log in and check the wallet network setting (testnet or mainnet)
2. Assuming you're on testnet, establish a connection with a dapp (testdapp as it's easier to test) on testnet mode. (this would be the same if the user is on mainnet and does the next steps by using the opposite network state)
3. Switch network to mainnet in the wallet
4. Send transaction request from the dapp (the request would be for testnet)
5. Request is shown, but shows not enough balance (NOT expected)

cc: @qoqobolo 

EDIT: edited the reproduction steps, as the original steps were describing a very unlikely edge case (both are fixed though)

**Comment by J-Son89** [comment]
> ### ISSUE 1
> Pending dapp requests are not triggered when switching testnet to mainnet
> 
> 1. Log in and check the wallet network setting (testnet or mainnet)
> 2. Assuming you're on testnet, establish a connection with a dapp (testdapp as it's easier to test) on testnet mode. (this would be the same if the user is on mainnet and does the next steps by using the opposite network state)
> 3. Switch network to mainnet in the wallet
> 4. Send any request from the dapp (the request would be for testnet)
> 5. Nothing happens (as expected)
> 6. Switch wallet network back to testnet and log in
> 7. Nothing happens (NOT expected, as the user should see the request cause it was initiated on the testnet)
> 
> cc: @qoqobolo

do we need to care about testnet though? 🤔

**Comment by clauxx** [comment]
> > ### ISSUE 1
> > Pending dapp requests are not triggered when switching testnet to mainnet
> > 
> > 1. Log in and check the wallet network setting (testnet or mainnet)
> > 2. Assuming you're on testnet, establish a connection with a dapp (testdapp as it's easier to test) on testnet mode. (this would be the same if the user is on mainnet and does the next steps by using the opposite network state)
> > 3. Switch network to mainnet in the wallet
> > 4. Send any request from the dapp (the request would be for testnet)
> > 5. Nothing happens (as expected)
> > 6. Switch wallet network back to testnet and log in
> > 7. Nothing happens (NOT expected, as the user should see the request cause it was initiated on the testnet)
> > 
> > cc: @qoqobolo
> 
> do we need to care about testnet though? 🤔

Sorry, changed the reproduction steps as I was thinking of another even lower prio edge-case when writing it. It's a low priority fix IMO since users don't really care about testnet mostly, but leads to a weird edgecase (the one in the edited comment) and it's an easy fix that was already pushed here. If you say it's better to go without the fix, I'll rebase and remove the commits 👍

**Comment by qoqobolo** [comment]
> do we need to care about testnet though? 🤔

Cristian has already pushed fix for this issue and just let me know what it was (mentioned [here](https://discord.com/channels/1210237582470807632/1217175655729467492/1267423053403525140))


> > > ### ISSUE 1
> > > Pending dapp requests are not triggered when switching testnet to mainnet
> > > 
> > > 1. Log in and check the wallet network setting (testnet or mainnet)
> > > 2. Assuming you're on testnet, establish a connection with a dapp (testdapp as it's easier to test) on testnet mode. (this would be the same if the user is on mainnet and does the next steps by using the opposite network state)
> > > 3. Switch network to mainnet in the wallet
> > > 4. Send any request from the dapp (the request would be for testnet)
> > > 5. Nothing happens (as expected)
> > > 6. Switch wallet network back to testnet and log in
> > > 7. Nothing happens (NOT expected, as the user should see the request cause it was initiated on the testnet)
> > > 
> > > cc: @qoqobolo
> > 
> > 
> > do we need to care about testnet though? 🤔
> 
> Sorry, changed the reproduction steps as I was thinking of another even lower prio edge-case when writing it. It's a low priority fix IMO since users don't really care about testnet mostly, but leads to a weird edgecase (the one in the edited comment) and it's an easy fix that was already pushed here. If you say it's better to go without the fix, I'll rebase and remove the commits 👍

@J-Son89 @clauxx I think it's okay to have this fix here since it's already done and pushed, we'll just check if this case works as expected.
FYI other cases and issues related to testnet are now being reported separately by Shivek, as they have lower priority and can be fixed later.

**Comment by qoqobolo** [comment]
### ISSUE 2: Can't connect to dapps via WC on Android

@clauxx seems like connecting doesn't work on Android at all.
But that's not the issue of this PR - @mariia-skrypnyk  tried to connect in [#20891](https://github.com/status-im/status-mobile/pull/20891), but she didn't succeed either.

**Steps:**
1. Try to connect to a test dapp or any other dapp (e.g. https://app.uniswap.org/swap) on Android

**Actual result:** nothing happens after scanning QR code

**Logs:** 
[Status-debug-logs.zip](https://github.com/user-attachments/files/16411522/Status-debug-logs.zip)

**Comment by clauxx** [comment]
> ### ISSUE 2: Can't connect to dapps via WC on Android
> @clauxx seems like connecting doesn't work on Android at all. But that's not the issue of this PR - @mariia-skrypnyk tried to connect in [#20891](https://github.com/status-im/status-mobile/pull/20891), but she didn't succeed either.
> 
> **Steps:**
> 
> 1. Try to connect to a test dapp or any other dapp (e.g. https://app.uniswap.org/swap) on Android
> 
> **Actual result:** nothing happens after scanning QR code
> 
> **Logs:** [Status-debug-logs.zip](https://github.com/user-attachments/files/16411522/Status-debug-logs.zip)

Pushed a fix. LMK if that fixes it for you @qoqobolo and @mariia-skrypnyk

**Review by alwx — APPROVED** [review]

**Comment by qoqobolo** [comment]
> > ### ISSUE 2: Can't connect to dapps via WC on Android
> > @clauxx seems like connecting doesn't work on Android at all. But that's not the issue of this PR - @mariia-skrypnyk tried to connect in [#20891](https://github.com/status-im/status-mobile/pull/20891), but she didn't succeed either.
> > **Steps:**
> > 
> > 1. Try to connect to a test dapp or any other dapp (e.g. https://app.uniswap.org/swap) on Android
> > 
> > **Actual result:** nothing happens after scanning QR code
> > **Logs:** [Status-debug-logs.zip](https://github.com/user-attachments/files/16411522/Status-debug-logs.zip)
> 
> Pushed a fix. LMK if that fixes it for you @qoqobolo and @mariia-skrypnyk

Thanks @clauxx, can connect now

**Comment by clauxx** [comment]
@mariia-skrypnyk does it work for you as well here?

**Comment by mariia-skrypnyk** [comment]
@clauxx thanks, it works too! 👍

**Comment by clauxx** [comment]
> @clauxx thanks, it works too! 👍

Thank you!

**Comment by qoqobolo** [comment]
### ISSUE 3: Sometimes Status disconnects from dapp

@clauxx I'm experiencing some really weird behavior with connected test dapp https://react-app.walletconnect.com/. 
I connect to it on Mainnet (although it seems that this also happened on testnet) and start triggering some events.
And at some point, I stop receiving any requests from the dapp. 
Moreover, after some time, the dapp disappears from the list of connected dapps on the Status side but stays connected on the dapp side. Most often I noticed this after reopening the Status app. 
I'm struggling to find any specific steps, but no success yet.

**Approximate steps:**
1. Switch to Mainnet
2. Connect to https://react-app.walletconnect.com/ 
3. Start triggering some events (`sendTransaction`, `personal_sign`, etc)

**Expected result:** can receive all the requests
**Actual result:** the dapp is disconnected at some point on the Status side; you still can send requests from the dapp but they'll stay in the `pending` state

The issue is not reproducible every time, I faced it 3-4 times today both on Android and iOS
 
**Logs (after reopening the app):** [Status-debug-logs.zip](https://github.com/user-attachments/files/16412895/Status-debug-logs.zip)

**Comment by qoqobolo** [comment]
> ### ISSUE 3: Sometimes Status disconnects from dapp
> @clauxx I'm experiencing some really weird behavior with connected test dapp https://react-app.walletconnect.com/. I connect to it on Mainnet (although it seems that this also happened on testnet) and start triggering some events. And at some point, I stop receiving any requests from the dapp. Moreover, after some time, the dapp disappears from the list of connected dapps on the Status side but stays connected on the dapp side. Most often I noticed this after reopening the Status app. I'm struggling to find any specific steps, but no success yet.
> 
> **Approximate steps:**
> 
> 1. Switch to Mainnet
> 2. Connect to https://react-app.walletconnect.com/
> 3. Start triggering some events (`sendTransaction`, `personal_sign`, etc)
> 
> **Expected result:** can receive all the requests **Actual result:** the dapp is disconnected at some point on the Status side; you still can send requests from the dapp but they'll stay in the `pending` state
> 
> The issue is not reproducible every time, I faced it 3-4 times today both on Android and iOS
> 
> **Logs (after reopening the app):** [Status-debug-logs.zip](https://github.com/user-attachments/files/16412895/Status-debug-logs.zip)

@clauxx got more logs and a bit more specific steps (tried on iOS this time):

1. Create a profile
2. Connect to https://react-app.walletconnect.com/ on **Testnet**
3. Trigger `eth_signTypedData_v4` event (expected the error toast here but it didn't appear, the request just got stuck in the `pending` state)
4. Close the request on the dapp side
5. Trigger `personal_sign` (no requests on the Status side)
Logs for this state: 
[logs (4) 2.zip](https://github.com/user-attachments/files/16413234/logs.4.2.zip)
6. Reopen Status and log in
7. Check the `Connected dapps` list (actual result: the list is empty)
Logs after re-login: 
[logs (5) 2.zip](https://github.com/user-attachments/files/16413259/logs.5.2.zip)

**Comment by clauxx** [comment]
@qoqobolo @mariia-skrypnyk added a fix to reject typed data requests if invalid, as we couldn't reproduce it based on the steps (although it did happen at some point for me as well, but since I'm changing accounts and connecting/disconnecting dapps often, I can't be sure if it wasn't just me disconnecting the wrong session).

Also added some logs, so that if it happens again, we have some more info on what's up cc: @alwx

**Comment by qoqobolo** [comment]
@clauxx thanks for the PR and all the fixes, amazing job as always!
PR can be merged.

**Pull request merged**
