### PR TITLE
use eth.staging fleet for e2e builds

### PR DESCRIPTION
**Pull request by jakubgs**
This should help us acquire more accurate statistics.

This is in relation to [discussion about user metrics](https://discuss.status.im/t/user-growth-and-retention/1782).

### CODE REVIEW

**Review by flexsurfer — APPROVED** [review]

**Review by churik — APPROVED** [review]

**Comment by churik** [comment]
will update e2e test_log_level_and_fleet a bit later

**Comment by oskarth** [comment]
:+1: 

If we can get this merged today it'd mean we would have accurate starting from July 1. That'd be a clean break for tracking metrics going forward :)

**Comment by jakubgs** [comment]
I just want to get a 100% on e2e... but it won't run.

**Comment by jakubgs** [comment]
This should be it: https://ci.status.im/job/end-to-end-tests/job/status-app-prs/1025/

**Pull request merged**
