### PR TITLE
Don't overwrite delivered status

### PR DESCRIPTION
**Pull request by cammellos**
### Testing

This PR moves all the mailserver logic to status-go, so full regression test on mailserver/offline messaging is needed.
Also basic functionality for waku-2 (you can set the fleet to waku 2).

status: ready

### CODE REVIEW

**Review by flexsurfer — APPROVED** [review]

**Comment by qoqobolo** [comment]
@cammellos unfortunately, still can reproduce the issue with the steps described [here](https://github.com/status-im/status-react/issues/13057).
New logs:
[Device1 geth.log](https://github.com/status-im/status-react/files/7970769/geth.log)
[Device2 geth.log](https://github.com/status-im/status-react/files/7970777/geth.log)

**Comment by churik** [comment]
community e2e are fixed in https://github.com/status-im/status-react/pull/13110, launched for checking

**Comment by churik** [comment]
@cammellos 
thank you, looks promising!
1. Question - seems that logic of pending-sent-delivered statuses has changed for 1-1 chat.
So if device1 send message to device 2 (which is offline):
 - on nightly - message `pending -> sent`
 - on PR - message `pending`
 When device 2 back online:
  - on nightly - `sent -> delivered`
  - on PR - `pending -> delivered`
  
  Is it expected?
  **UPD:** can't reproduce anymore, keep trying

2. Question - about waku2 fleet - can you please elaborate on what should work there (as we didn't test so much)?

**Comment by cammellos** [comment]
@churik 
With that regard, it should work the same as nightly, what likely happen is that it wasn't connected to a mailserver when you sent the messages, though they should be marked as sent once you go back online/connect to a mailserver. Let me know if you can replicate again.

> Question - about waku2 fleet - can you please elaborate on what should work there (as we didn't test so much)?

It should kind of work like normal, you should be able to receive messages and send messages and pull them from mailservers, though only messages sent/received using waku-2 will be visible.

**Comment by churik** [comment]
@cammellos 
Logged in after 3 days of inactivity, joined to public chat - endless loading, can't send/receive messages.
**Sync period:** month
**Mailserver:** mail-02.do.ams3
[logs (13).zip](https://github.com/status-im/status-react/files/8160552/logs.13.zip)
After relogin history for 24h was fetched, but still, the spinner is shown for the previous history, "Pending" at attempt to send messages to 1-1 chat.
IMAGE 2022-03-01 10:52:32
**Platform:** IOS
On Android couldn't reproduce same behavior for now
Actually the same behaviour can be reproduced quite easily on IOS.
- create new multiaccount
- set "Sync history for" to 1 month
- join any public chat / community

**Expected result:** messages atre fetched (on nightly works fine)
**Actual result:** endless loading

**Comment by cammellos** [comment]
Thanks @churik , do you have `geth.log` by any chance? (they are not in the file downloaded)

**Comment by churik** [comment]
Sorry, didn't check. For now by default status PR builds doesn't create any geth.log on usage (need to switch to mainnet to start it)
Here you are:
[geth.log](https://github.com/status-im/status-react/files/8161285/geth.log)

**Comment by churik** [comment]
As far as I can see from e2e, the endless loading when join to public chat is reproducible on Android as well

https://app.saucelabs.com/tests/23dadd2cd32844fb8a327b208a3f7236?auth=e87345eecd5c0adb0e108b562021dbc3#163 (8:36 - 9:19)

Log: [test_pair_devices_sync_one_to_one_contacts_nicknames_public_chat_geth1.log](https://github.com/status-im/status-react/files/8176472/test_pair_devices_sync_one_to_one_contacts_nicknames_public_chat_geth1.log)

**Comment by cammellos** [comment]
@churik thanks, yes, I have found an issue with the code that was causing the behavior, tried to fix it, but something is wrong, investigating

**Comment by churik** [comment]
@cammellos 
not sure it is an issue (you better to elaborate), but the difference between nightly and PR.
### ISSUE (Question) 3: when non-working custom node is chosen for connct, there is no error shown and p2p connection is not working
The reason for failed https://ethstatus.testrail.net/index.php?/tests/view/2542468 

**Steps:**
1) Turn off automatic selection in Sync > History nodes
2) Add non-working custom history node (i.e. `enode://69f72baa7f1722d111a8c9c68c39a31530e9d567695f6108f31ccb6cd8f0adff5991e7fdca8fa770e75bc8a511a87d25690cbc80e008175f50c157d6f6788d58:status-offline-inbox@206.189.250.16:553` )
3) Connect to it, tap save
4) Sign in


**Expected result:**
on nightly: 
- `Error connecting to status node` after a while
IMAGE 2022-03-16 09:50:35

**Actual result:**
on PR:
- no error

Also noticed that once after the first re-login p2p connection stopped working and Status got stuck with an endless spinner on re-login.
It happened only once when I was testing this case. 
General log in case you can extract smth useful from it[geth.log](https://github.com/status-im/status-react/files/8260428/geth.log) (rows  after =2022-03-16T08:54:43+0000 )

**Comment by pavloburykh** [comment]
@cammellos thank you for fixes. Got one more issue


### ISSUE 4: Error modal reopens after closing until re-login into the app (reproducible for IOS only)

**Steps:**
1) Turn off automatic selection in Sync > History nodes
2) Add non-working custom history node (i.e. `enode://69f72baa7f1722d111a8c9c68c39a31530e9d567695f6108f31ccb6cd8f0adff5991e7fdca8fa770e75bc8a511a87d25690cbc80e008175f50c157d6f6788d58:status-offline-inbox@206.189.250.16:553` )
3) Connect to it, tap save
4) Sign in
5) Connect to working node
6) Reconnect again to the non-working custom node
7) In appeared error modal select cancel/choose another node option


**Expected result:**
- Error modal closes and does not reopen after tapping cancel/choose another node option

**Actual result:**
- error modal reopens after tapping cancel/choose another node option. It stops reopening after app re-login. 

[Video](https://drive.google.com/file/d/1KtOpvO98P1mQu4-XxiE8_KZ0wQbdml3z/view?usp=sharing)

[geth.log](https://drive.google.com/file/d/1pFNUw3q0aYdscsZIdmbJG0Q1wwzHAngM/view?usp=sharing)

**Comment by pavloburykh** [comment]
### ISSUE 5: ENS usernames are not resolved in chats 

**Steps:**
1) Start chat with user having ens username. For testing you can scan this deeplink containing ens https://join.status.im/u/nastya.stateofus.eth
2) Pay attention at username, displayed in chat 

**Actual result:**
- 3 random name instead of ens is displayed. Also, unable to mention user by ens in chats. 

**Expected result:**
- ENS name is resolved in chats and contact list

OS: IOS/Android

[geth.log](https://github.com/status-im/status-react/files/8288162/geth.log)


https://user-images.githubusercontent.com/97245802/158849941-bd882256-a513-4bd8-9a0d-364de54fafd1.mp4


https://user-images.githubusercontent.com/97245802/158849974-9b4f74f9-68b5-428c-838f-884809ff3a93.mp4

**Comment by pavloburykh** [comment]
### ISSUE 6: Null is not an object error while trying to send transaction in 1-1 chat to user this ENS 

**Steps:**
1) Start chat with user having ens username. For testing you can scan this deeplink containing ens https://join.status.im/u/nastya.stateofus.eth
2) Inside chat call transaction menu and tap "Send transaction"

**Actual result:**
- Error "Null is not an object (evaluating 'i.undexOf') displayed

**Expected result:**
- user is able to send transaction to user with ENS in 1-1 chat

OS: IOS/Android

photo_2022-03-17 22 21 17

https://user-images.githubusercontent.com/97245802/158888825-ed65719c-6a24-4ba8-bdcc-c052427c9d55.mp4

[geth.log](https://github.com/status-im/status-react/files/8291426/geth.log)

**Comment by pavloburykh** [comment]
@cammellos Thanks for your work! All issues are fixed. 5 failed e2e tests have nothing to do with PR changes so it is ready for merge.

**Comment by cammellos** [comment]
Thank you for your patience & testing @pavloburykh, @churik and @qoqobolo , merged!

**Pull request merged**
