### PR TITLE
Use WakuNodes in ClusterConfig for Waku V2

### LINKED ISSUE #14210: Use `WakuNodes` in `ClusterConfig` for Waku V2
In this PR https://github.com/status-im/status-go/pull/2438 I'm using WakuV2 Identify protocol to obtain the protocols supported by a node. This simplifies the node config by reducing duplication of values. 

The node config in the mobile app for wakuv2 should be changed from:
```
ClusterConfig: {
    ...
    RelayNodes: ["/ip4/127.0.0.1/udp/1234",  "enstree:somednsdiscoveryurl..."],
    StoreNodes: ["/ip4/127.0.0.1/udp/1234",  "enstree:somednsdiscoveryurl..."],
    FilterNodes: ["/ip4/127.0.0.1/udp/1234",  "enstree:somednsdiscoveryurl..."],
    LightpushNodes: ["/ip4/127.0.0.1/udp/1234",  "enstree:somednsdiscoveryurl..."],
    WakuRendezvousNodes: ["/ip4/127.0.0.1/udp/1234",  "enstree:somednsdiscoveryurl..."]
    ...
}
```
to
```
ClusterConfig: {
    ...
    WakuNodes: ["/ip4/127.0.0.1/udp/1234",  "enstree:somednsdiscoveryurl..."]
    ...
}
```

The value that should go in the `WakuNodes` array would depend on the fleet the app is connected to:
- WakuV2Prod: `enrtree://AOGECG2SPND25EEFMAJ5WF3KSGJNSGV356DSTL2YVLLZWIV6SAYBM@prod.waku.nodes.status.im`
- WakuV2Test: `enrtree://AOGECG2SPND25EEFMAJ5WF3KSGJNSGV356DSTL2YVLLZWIV6SAYBM@test.waku.nodes.status.im`
- StatusTest: `enrtree://AOGECG2SPND25EEFMAJ5WF3KSGJNSGV356DSTL2YVLLZWIV6SAYBM@test.nodes.status.im`
- StatusProd: `enrtree://AOGECG2SPND25EEFMAJ5WF3KSGJNSGV356DSTL2YVLLZWIV6SAYBM@prod.nodes.status.im`

### PR DESCRIPTION
**Pull request by qfrank**
close #14210

### CODE REVIEW

**Comment by qfrank** [comment]
Hi @richard-ramos , after added `WakuNodes` to cluster config , i found i can't send/receive message in public chat when using fleet `wakuv2.prod` , could u help to have a look , thanks

[geth.log](https://github.com/status-im/status-mobile/files/9978712/geth.log)
[node-config-formatted.log](https://github.com/status-im/status-mobile/files/9978711/node-config-formatted.log)

**Comment by richard-ramos** [comment]
Please try again with the latest commit from waku2/identify . I've rebased the PR (and now it includes some fixes that were identified for wakuv2 and merged in develop). Thank you!

**Comment by qfrank** [comment]
tried but same .. 🙁
[geth.log](https://github.com/status-im/status-mobile/files/9986521/geth.log)
@richard-ramos

**Comment by qfrank** [comment]
ready to review :) @cammellos

**Review by cammellos — APPROVED** [review]

**Comment by pavloburykh** [comment]
@qfrank @richard-ramos Thank you for your work. 

Could you please clarify the following question: should it be possible for Users on different fleets to send/receive messages from each other?

**For example:** User 1 is on eth.prod, User 2 is on wakuv2.prod

**Steps:**
1. Send messages from User 1 to User 2 and vice verse 
2. Observe if messages are sent/received

**Actual result:** messages are not received
**Expected result:** ?


https://user-images.githubusercontent.com/97245802/201654467-25415f03-6753-4d57-8b67-a32a8f25ff33.mp4

[IOS_geth.log](https://github.com/status-im/status-mobile/files/10002712/IOS_geth.log)
[IOS_Status.log](https://github.com/status-im/status-mobile/files/10002713/IOS_Status.log)
[Android_geth.log](https://github.com/status-im/status-mobile/files/10002714/Android_geth.log)
[Android_Status.log](https://github.com/status-im/status-mobile/files/10002715/Android_Status.log)

**Comment by qfrank** [comment]
> messages are not received

I think expected result would be : "messages are not received" in the case, that's why we need fleet , also there is a [description](https://github.com/status-im/status-mobile/issues/5213)(section of User Story) about fleet :) @pavloburykh

**Comment by pavloburykh** [comment]
> > messages are not received
> 
> I think expected result would be : "messages are not received" in the case, that's why we need fleet , also there is a [description](https://github.com/status-im/status-mobile/issues/5213)(section of User Story) about fleet :) @pavloburykh

Thanx for the answer. If this is expected behaviour then PR LGTM and is ready for merge after resolving conflicts. 
Failed e2e are not related to the PR changes.

**Comment by qfrank** [comment]
waiting this [pr](https://github.com/status-im/status-go/pull/2438) get merged @richard-ramos 🚀

**Pull request merged**
