### PR TITLE
Add support for SOCKS token

### LINKED ISSUE #11979: Add support for SOCKS token 🧦
# Problem

👏 Support 👏 SOCKS 👏

## Implementation

[Icon asset ](https://www.figma.com/file/euHYLLNiRjtHR6xv5qq0KI1C/Userpicks?node-id=829%3A3)

[Exported icons](https://github.com/status-im/status-desktop/files/6294893/SOCKS.Icons.zip)

[Etherscan](https://etherscan.io/token/0x23b608675a2b2fb1890d3abbd85c5775c51691d5) 

## Acceptance Criteria

$SOCKS can be selected as an asset in our token list

thanks 🤗

### PR DESCRIPTION
**Pull request by briansztamfater**
fixes #11979 

### Summary

Adding Unisocks to our token list

#### Platforms

- Android
- iOS

##### Functional

- wallet / transactions

### Steps to test

- Open Status
- Go to wallet
- Open option
- Select Manage assets
- Verify that Unisocks (SOCKS) is available to select and use

status: ready

### CODE REVIEW

**Review by cammellos — APPROVED** [review]

**Comment by errorists** [comment]
IMG_0217

needs to be merged to send SOCKS above 100k 🙏

**Comment by churik** [comment]
@briansztamfater 
name in https://etherscan.io/token/0x23b608675a2b2fb1890d3abbd85c5775c51691d5#readContract is `Unisocks Edition 0`  not `Unisocks `- that's failure of e2e tests, as we have validation for tokens enabled on e2e builds.

**Comment by briansztamfater** [comment]
@churik Thanks, I will change it now

**Comment by errorists** [comment]
as a person wearing `$Socks`  I think it should be `Unisocks`

**Comment by briansztamfater** [comment]
@churik @errorists just force-pushed the changes to make e2e tests pass but we can revert it easily. I'll stay tuned on the conversation.

**Pull request merged**
