### PR TITLE
fix fatal: ambiguous argument 'develop..':...

### PR DESCRIPTION
**Pull request by rasom**
status: ready

### CODE REVIEW

**Review by janherich — APPROVED** [review]

**Comment by oskarth** [comment]
@rasom Not sure if this is tested for the different configurations so didn't do it myself, but assuming it works, could you also add add fix this to `Jenkinsfile.parameters` file? Just merged it.

**Comment by oskarth** [comment]
Maybe nothing is necessary, shot off #95 and #96 with current config to test https://jenkins.status.im/job/status-react/job/parametrized%20build/

**Comment by oskarth** [comment]
Both (develop and old feature branch with our remote) built fine, so seems like a non-issue.

**Review by oskarth — APPROVED** [review]

**Comment by rasom** [comment]
> could you also add add fix this to Jenkinsfile.parameters file? 
@oskarth done

**Pull request merged**
