### PR TITLE
Desktop emoji

### PR DESCRIPTION
**Pull request by flexsurfer**
image

Two issues
- Emoji view renders for like 5s
- :on-selection-change not supported

### CODE REVIEW

**Comment by vkjr** [comment]
@flexsurfer, thanks for the PR!
Did you investigate, what causes such a long loading time? I suspect it is because ScrollView has to load everything before rendering (but still it is quite a long time).
Probably smiles can be shown in a few "pages" to make this faster.

Currently there is an ongoing work to run mobile UI on desktop. If successful, it can help us to get rid of separate screens for desktop and will make UI maintaining easier. I'd suggest not to spend much time on developing new features for desktop, since they can become unnecessary ;)

**Review by vkjr — APPROVED** [review]

**Comment by flexsurfer** [comment]
@vkjr every emoji is a separate object, so yeah it takes really long time to render all of them. We don't have emoji implementation in mobile, we use os emoji, so we need to develop them on a desktop anyway and they don't become unnecessary

**Comment by vkjr** [comment]
@flexsurfer, ok, thats cool 👍

**Review by yenda — APPROVED** [review]

**Comment by churik** [comment]
@flexsurfer 
1) should I create separate issue for rendering emoji view time?
2) emojis on Windows and Linux:
windows 10 2019-02-13 11-54-54
It is #6703.

is it possible to fix here or better to do it later in #6703, WDYT?

**Comment by churik** [comment]
@flexsurfer any comments?

**Comment by flexsurfer** [comment]
hey @churik  , thanks for testing! i'll fix 1. rendering emoji view time here, but #6703 is separate one, thanks

**Comment by flexsurfer** [comment]
ok, give me last change , i'll try to fix it this weekend , this is volunteer issue i work on weekednds

**Comment by jeluard** [comment]
@flexsurfer @vkjr Is this still relevant in the context of latest desktop work?

**Comment by flexsurfer** [comment]
@jeluard i believe yes https://github.com/status-im/status-react/pull/7461#issuecomment-462251494

**Comment by flexsurfer** [comment]
@churik @vkjr 
image

**Comment by vkjr** [comment]
Looks great!

**Comment by churik** [comment]
@flexsurfer thank you again for this PR!
One question - I noticed that on `People and Fantasy` and `Activity` tabs there are a lot of emojis, that are not shown as intended (screenshot is attached)
Act

Should we exclude them or leave as it is?

**Comment by flexsurfer** [comment]
@churik i'll try to fix this, thanks

**Comment by flexsurfer** [comment]
@churik removed them for now

**Comment by churik** [comment]
Tested on Linux 18.04, Windows 10 Home, Mac OSx 10.14.3 in public, group, 1-1 chat.
Performance can be compared with switching to profile - so if you open/close emoji window 5+ times  -> CPU consumption increases from 3-5 % to 10-20% - not a blocker IMO.

**Pull request merged**
