### PR TITLE
Allow non-admin users to see participants profiles in group chat sett…

### LINKED ISSUE #3934: Can't see participants profiles in group chat settings (non-admin)
### Description

*Type*: Bug

*Summary*: as a group chat participant i want to be able to view others' profiles no matter i am admin or not

#### Expected behavior
group chat member is able to navigate to other participants' profile within tap 3 dots -> group info -> tap member's profile

#### Actual behavior
i am not able to see profile of any other member if i am not an admin of group chat

### Reproduction

- Open Status
- In a group chat (non-admin) tap 3 dots -> group info -> tap member's profile

### Additional Information
* Status version: develop
* Operating System: Android|iOS

### PR DESCRIPTION
**Pull request by psdp**
…ings (#3934)

[comment]: # (Please replace ... with your information. Remove < and >)
[comment]: # (To auto-close issue on merge, please insert the related issue number after # i.e fixes #566)

If you submit PR for issue with bounty then write here Fixes #NN where NN is issue number

*otherwise*

fixes #3934

### Summary:

[comment]: # (Summarise the problem and how the pull request solves it)
...

### Steps to test:
- Open Status
- ...
- Step 3, etc.

status: ready

### CODE REVIEW

**Review by goranjovic — APPROVED** [review]

**Review by janherich — APPROVED** [review]

**Comment by asemiankevich** [comment]
@psdp iOS app is crashing when i am trying to view someone's profile from group chat: three dots -> group info -> select member and tap three dots (i am not admin). Also on Android the dialog has a lot of unnecessary space for non-admin

image


I am thinking of skipping this dialog window at all and show next one right away (for non-admins), so a user will see this screen (non-admins of group chat) when tap three dots ->  group info -> tap on any member:

image


@denis-sharypin please confirm

**Comment by denis-sharypin** [comment]
@psdp It would be great if you implement proposed UX improvement from @asemiankevich  from the comment above

**Comment by psdp** [comment]
@asemiankevich @denis-sharypin fixed now, please check.

**Comment by asemiankevich** [comment]
@psdp thanks! works now

**Pull request merged**
