### PR TITLE
send to slack branch that we are building now, if we build PR

### PR DESCRIPTION
**Pull request by v2nek**
This should display PR name in internal jenkins channel

status: ready

### CODE REVIEW

**Comment by v2nek** [comment]
jenkins log

**Comment by v2nek** [comment]
jenkins log

**Comment by oskarth** [comment]
@v2nek Can you please fill out the PR description and also move to Pipeline (moved for now)? It's OK if it is a simplified version but right now it is literally just the template :)

**Review by flexsurfer — APPROVED** [review]

**Comment by v2nek** [comment]
@oskarth cleaned up it a bit, thanks.

**Review by oskarth — APPROVED** [review]

**Review by rasom — APPROVED** [review]

**Comment by oskarth** [comment]
@rasom code signing FYI https://github.com/status-im/status-react/commits/develop

**Pull request merged**
