### PR TITLE
[#17288] refactor: migrate previews to new api

### PR DESCRIPTION
**Pull request by mohsen-ghafouri**
to accomplish #17288

**None of the basic components were touched**

migrated preview screens:
- profile
- reactions
- record_audio
- selectors

status: ready

### CODE REVIEW

**Review by J-Son89 — COMMENTED** [review]
great work @mohsen-ghafouri! 🚀

**Review by J-Son89 — APPROVED** [review]
great work @mohsen-ghafouri 🚀

**Comment by mohsen-ghafouri** [comment]
@status-im/mobile-qa the same as previous PR , these changes didn't effect any screens/design system component. if it's okay i will move it to design review

**Comment by mohsen-ghafouri** [comment]
@Francesca-G please check if it requires design review. just preview screens has been updated.

**Review by Francesca-G — APPROVED** [review]
Looks good, 
the reaction component should be updated with the OS emojis (iOS in my case) as we agreed on not using tweemojis for now.

**Pull request merged**
