### PR TITLE
feat!: add saved addresses to wallet settings 

### LINKED ISSUE #18568: [Epic] - Feature - Wallet - Save Address
### User Story

- As a user, I want to be able to save an address (with ENS if registered) in the wallet settings so that I can quickly choose it for future transactions. 
- I want to be able to give the user a name, color and set the network preferences for what networks to send them tokens on.
- I want to be able to select this saved address when making another transaction in the future
- I want to edit the name, color and network preferences of the saved address
- I want to remove the saved address

### Designs

[Link to Figma](https://www.figma.com/design/hLFPHYnuM0pOzgiabtqQ6k/Descoped-Wallet-settings-for-Mobile?node-id=74-33979&t=QFZQHEfCuyRyrDG5-1)

#### Features
The below features should be hidden behind a feature flag.

add a dedicated screen to list saved addresses:
- [x] https://github.com/status-im/status-mobile/issues/19726

list saved addresses
- [x] https://github.com/status-im/status-mobile/issues/19727

search in the saved addresses list
- [x] https://github.com/status-im/status-mobile/issues/20442

add saved address by typing/pasting the address
- [x] https://github.com/status-im/status-mobile/issues/19764

add network configuration for saved address:
- [x] https://github.com/status-im/status-mobile/issues/16995

add saved address via ens
- [x] https://github.com/status-im/status-mobile/issues/19765

add saved address by scanning QR code
- [x] https://github.com/status-im/status-mobile/issues/19766

saved address operations 
- [x] https://github.com/status-im/status-mobile/issues/19728

share saved address as a QR code
- [x] https://github.com/status-im/status-mobile/issues/19734

edit saved address
- [x] https://github.com/status-im/status-mobile/issues/19737

delete saved address
- [x] https://github.com/status-im/status-mobile/issues/19730

load saved address on send page:
- [x] https://github.com/status-im/status-mobile/issues/16993

#### Closing this issue

Once all of these issues are ready the corresponding feature Flag Can be removed. This PR to remove the feature flag can then be used for QA and Design to ensure everything is feature complete and this issue can be closed.

### LINKED ISSUE #20458: Saved addresses design review
### Description

Check saved addresses text, UI fit and navigation transition.

- there is a text issue when saved addresses is empty, should be "Do you like..."

- address background color is wrong

### PR DESCRIPTION
**Pull request by mohsen-ghafouri**
fixes #18568
fixes #20458

### Summary
This PR attempts to reveal the feature-flagged "Saved addresses" settings inside wallet settings

### Review notes
A summary of the related features that need to tested and reviewed can be found in this epic: #18568

### Platforms

- Android
- iOS

### Areas that maybe impacted

- Wallet Settings
- Wallet -> Account/Send to -> Saved addresses tab

### Steps to test

Steps to test this feature can be found in the related issues that described in this epic: #18568

status: ready

### CODE REVIEW

**Review by seanstrom — APPROVED** [review]
Woooh Wooh! 🚂 
The feature train is here 😄

**Comment by mariia-skrypnyk** [comment]
Hey @mohsen-ghafouri !

Thanks for your PR.

I am wonder if there are any background behind one behaviour I am observing during testing.
Let me explain.
When I add address on Testnet it is not visible for me in Mainnet.
So I get the empty list of Address when I switched to a Mainnet.
But be do have the same wallet address in both cases.
Can I add it as a bug?

**Comment by mohsen-ghafouri** [comment]
Hello @mariia-skrypnyk, I asked this question from the team and to see how it works on desktop too, and they told me:
"we have 2 separate lists of saved addresses for mainnet and testnet. 
When you save an address you have the option to choose preferred networks for that saved address
we used a flag isTest to differentiate addresses in testnet and mainnet modes."

**Comment by mariia-skrypnyk** [comment]
@mohsen-ghafouri thanks for sharing it with me.

As I see on mobile user doesn't have an option to choose will it be address for testnet/mainnet. 
If I choose "Mainnet" network preference during address creation while I am on Testnet as a result I see created address in the Testnet address list. Shouldn't I?

**Comment by mariia-skrypnyk** [comment]
**ISSUE 1: [iOS] Two lines appear above address list after scrolling**

**Steps:**

1. Login to app
2. Go to Profile -> Wallet -> Saved addresses
3. Add as many addresses as needed to scroll to the hidden ones
4. Scroll up and down

**Actual result:**
Two lines appear above address list after scrolling

Screenshot 2024-06-19 at 10 52 56


https://github.com/status-im/status-mobile/assets/147824399/21373f54-6404-4ae3-8af2-5d533ff4f5d1

**Expected result:**

List should look as designed https://www.figma.com/design/hLFPHYnuM0pOzgiabtqQ6k/Descoped-Wallet-settings-for-Mobile?node-id=74-33979&t=oZZqEV7kYBiBMGlh-0

Device: iPhone 13 (17.5.1)

**Comment by smohamedjavid** [comment]
Hey @mariia-skrypnyk - Thank you for testing this PR.

> I am wonder if there are any background behind one behaviour I am observing during testing. Let me explain. When I add address on Testnet it is not visible for me in Mainnet. So I get the empty list of Address when I switched to a Mainnet. But be do have the same wallet address in both cases. Can I add it as a bug?

That's the expected behaviour. The saved addresses are added based on the testnet toggle. This is the current behaviour on the desktop as well. 

> As I see on mobile user doesn't have an option to choose will it be address for testnet/mainnet.
If I choose "Mainnet" network preference during address creation while I am on Testnet as a result I see created address in the Testnet address list. Shouldn't I?

We don't show the option to choose whether the address will be used for testnet or mainnet. The saved addresses are added based on the testnet toggle (`Testnet mode` toggle under `Profile > Advanced`). 

I believe you are confused with the network selection for address with the testnet toggle. All three networks (L1 chain - Ethereum Mainnet and L2 chains - Arbitrum, Optimism) shown in the network preferences sheet will have a mainnet and testnet config. Depending on the testnet toggle, we use the respective config.

**Comment by mariia-skrypnyk** [comment]
**ISSUE 2: No search results if user types Name+Space in a search field**

**Steps:**

1. Login to app
2. Go to Profile -> Wallet -> Saved addresses
3. Add address with name that consist of two+ words (e.g. I am rich)
4. Type `Rich+Space` into Search field

**Actual result:**

Search result is empty

https://github.com/status-im/status-mobile/assets/147824399/b5122ce1-fb99-4be9-99c2-d67c436fece6

**Expected result:**

User will see his `I am rich ` saved address

Device: iPhone 13 (17.5.1)

**Review by smohamedjavid — APPROVED** [review]

**Comment by mariia-skrypnyk** [comment]
**ISSUE 3: The input is not auto-focused and the keyboard is not open automatically when the user enters the Add Address screen**

**Steps:**

1. Login to app
2. Go to Profile -> Wallet -> Saved addresses
3. Tap on `+`

**Actual result:**

https://github.com/status-im/status-mobile/assets/147824399/8d3a0ef6-56e3-499d-9c05-09d0156e9f42

**Expected result:**

https://github.com/status-im/status-mobile/issues/19764

> 5. The input should be auto-focused and the keyboard should open automatically when the user enters the screen

Device: iPhone 13 (17.5.1)

**Comment by mariia-skrypnyk** [comment]
**ISSUE 4: List of design issues when error on Add address screen**

**Steps:** 

1. Login to app
2. Go to Profile -> Wallet -> Saved addresses
3. Tap on +
4. Add an address (e.g. 0x4B0897b0513fdc7C541B6d9D7E929C4e5364d2dB)
5. Tap on + (
6. Type the same address (e.g. 0x4B0897b0513fdc7C541B6d9D7E929C4e5364d2dB)

**Actual result:**

- incorrect `i` icon
- no initials on saved address name and no custom color
- black background

Screenshot 2024-06-19 at 12 39 10

**Expected result:**

https://www.figma.com/design/hLFPHYnuM0pOzgiabtqQ6k/Descoped-Wallet-settings-for-Mobile?node-id=80-168215&t=Ga7XJkYRgYmQQD07-0

Screenshot 2024-06-19 at 12 33 10

**Comment by mariia-skrypnyk** [comment]
**ISSUE 5: [iOS] Incorrect black background behind Saved addresses button**

**Steps:**

1. Login to app
2. Go to Profile -> Wallet -> Saved addresses
3. Tap on +
4. Add an address (e.g. 0x4B0897b0513fdc7C541B6d9D7E929C4e5364d2dB)
5. Tap Continue

**Actual result:**

Screenshot 2024-06-19 at 13 17 24

**Expected result:**

Screenshot 2024-06-19 at 13 20 24

https://www.figma.com/design/hLFPHYnuM0pOzgiabtqQ6k/Descoped-Wallet-settings-for-Mobile?node-id=80-168215&t=SaW7ODkeONIO5IxP-0

**ISSUE 6: [iOS] No checkboxes for network preferences on the network preferences sheet**

**Steps:** 
1. Login to app
2. Go to Profile -> Wallet -> Saved addresses
3. Tap on +
4. Add an address (e.g. 0x4B0897b0513fdc7C541B6d9D7E929C4e5364d2dB)
5. Tap Continue
6. Tap on network preferences icon

**Actual result:**

Screenshot 2024-06-19 at 13 24 09

**Expected result:**

Screenshot 2024-06-19 at 13 25 01

https://www.figma.com/design/hLFPHYnuM0pOzgiabtqQ6k/Descoped-Wallet-settings-for-Mobile?t=wIBeGNBcvTUAsaeV-0

**Comment by mariia-skrypnyk** [comment]
**ISSUE 7: **Saved Addresses list  is not in alphabetical order****

**Steps:**

1. Login to app
2. Go to Profile -> Wallet -> Saved addresses
3. Add several addresses or use account that already has them

**Actual result:**

Saved Addresses list is not in alphabetical order


https://github.com/status-im/status-mobile/assets/147824399/60084449-12b2-4959-a5e3-eab7cd1365bc

**Expected result:**

Saved Addresses list is in alphabetical order

Screenshot 2024-06-19 at 13 45 52

https://www.figma.com/design/hLFPHYnuM0pOzgiabtqQ6k/Descoped-Wallet-settings-for-Mobile?node-id=1395-60328&t=wIBeGNBcvTUAsaeV-0

**Comment by mariia-skrypnyk** [comment]
**ISSUE 8: ENS allows setting network preferences on Add address screen**

**Steps:**

1. Login to app
2. Go to Profile -> Wallet -> Saved addresses
3. Tap on +
4. Add an address (e.g. elonmusk.eth)
5. Tap Continue

**Actual result:**

User see network preferences icon and can open a network preferences sheet

Screenshot 2024-06-19 at 14 38 12


**Expected result:**

> ENS should not allow for setting network preferences

https://github.com/status-im/status-mobile/issues/19765

Screenshot 2024-06-19 at 14 36 16

**Comment by mariia-skrypnyk** [comment]
**ISSUE 9: No specific error when QR code that doesn't work with Status is scanned**

**Steps:**

1. Login to app
2. Go to Profile -> Wallet -> Saved addresses
3. Tap on +
4. Tap on scan icon
5. Scan any QR that is not related to crypto

**Actual result:**

Error toast is the same that is used for case with an incorrect address
Screenshot 2024-06-19 at 15 49 50

**Expected result:**

Screenshot 2024-06-19 at 15 51 36

https://www.figma.com/design/hLFPHYnuM0pOzgiabtqQ6k/Descoped-Wallet-settings-for-Mobile?node-id=71-142051&t=k6Cgpds1VCNG2Vhm-0

**Comment by mohsen-ghafouri** [comment]
Thanks for testing this PR @mariia-skrypnyk, i will review/resolve the issues and update you soon.

**Comment by mariia-skrypnyk** [comment]
**ISSUE 10: [iOS] Scanned address doesn't contain chain on Add address screen**

**Steps:** 

1. Login to app
2. Go to Profile -> Wallet -> Saved addresses
3. Tap on +
4. Tap on scan icon
5. Scan any QR that contain chains 
6. Tap Continue
7. Look if your scanned address contains chain or not

*issue is not 100% reproducible but I could catch it if I change networks on network preferences of address that I am scanning, aprox 2-3 tries from 15-20 scans

**Actual result:**

No chain in wallet address

Screenshot 2024-06-20 at 13 00 13

https://github.com/status-im/status-mobile/assets/147824399/b78cee2c-c225-4c1a-b043-a3a7e1f1323f

**Expected result:**

Address is the same as it was scanned

Device: iPhone 13 (17.5.1)

**Comment by mariia-skrypnyk** [comment]
**ISSUE 11: Share Address QR code design issues**

**Steps:**

1. Login to app
2. Go to Profile -> Wallet -> Saved addresses
3. Long tap on any existing address or add new one
4. Choose `Show address QR` menu item

**Design vs Implementation**

Screenshot 2024-06-20 at 13 23 28

1) Initials font is smaller
2) Tabs are in a wrong order
3) Initials font is too small

Device: iPhone 13 (17.5.1)

**Comment by mariia-skrypnyk** [comment]
**ISSUE 12: The input is auto-focused and the keyboard is opened automatically when Edit address screen opens** 

**Steps:**

1. Login to app
2. Go to Profile -> Wallet -> Saved addresses
3. Long tap on any existing address or add new one
4. Choose `Edit details` menu item

**Actual result:**

1. The input is auto-focused and the keyboard is opened automatically when Edit address screen opens
2. Save address button is hidden behind the opened keyboard. (it's not related to the paticular issue but if you can also somehow deal with it it would be great)

Screenshot 2024-06-20 at 14 31 06

**Expected result:**

Input shouldn't be auto-focused and should look as designed

Screenshot 2024-06-20 at 14 31 47

https://www.figma.com/design/hLFPHYnuM0pOzgiabtqQ6k/Descoped-Wallet-settings-for-Mobile?node-id=85-184787&t=11oArz9T71zM1ZgW-0

Device: iPhone 13 (17.5.1)

**Comment by mariia-skrypnyk** [comment]
**ISSUE 13: No sticky header with letters on the top of the addresses list**

**Steps:**

1. Login to app with user who has a lot of saved addresses
2. Go to Profile -> Wallet -> Saved addresses
3. Scroll list of addresses 
4. Go to Wallet -> Send -> Saved tab 
5. Scroll list of addresses

**Actual result:** 

No sticky header with letters on the top of the addresses list

https://github.com/status-im/status-mobile/assets/147824399/4d581698-9632-4a81-9f97-5cc660adeaae

**Expected result:**

Sticky header with letters on the top of the addresses list
Screenshot 2024-06-20 at 18 55 08



https://www.figma.com/design/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?node-id=689-192611&t=VESt77iOg0vW48x1-0

Example of sticky header is here https://github.com/status-im/status-mobile/pull/19054

**Comment by smohamedjavid** [comment]
@mariia-skrypnyk - For Issue 13, can you help create a separate issue? 🙏  that whole page needs to be refactored to make that sticky header behaviour. The PR you mentioned, it's just a simple page. But, here we need to hide the search input field and keep the rest.

**Comment by mariia-skrypnyk** [comment]
Hey @smohamedjavid!
✅ ISSUE 13 follow up created.

**Comment by mariia-skrypnyk** [comment]
@mohsen-ghafouri I am done wit testing.

Let me know when you will need me again.
Thanks!

**Comment by mohsen-ghafouri** [comment]
Hey @mariia-skrypnyk , thanks i will update you with resolved issues.

**Comment by mohsen-ghafouri** [comment]
- ISSUE 1 ✅
- ISSUE 2 ✅
- ISSUE 3 ✅
- ISSUE 4 ✅
- ISSUE 5 - follow up created  #20543
- ISSUE 6 ✅
- ISSUE 7 - couldn't reproduce the issue. can you double check if it's been resolved?
- ISSUE 8 ✅
- ISSUE 9 - follow up needed
- ISSUE 10 - couldn't reproduce the issue. can you double check if it's been resolved?
- ISSUE 11 ✅
- ISSUE 12 ✅
- ISSUE 13 - follow up created #20527

CC @smohamedjavid @mariia-skrypnyk

**Comment by mariia-skrypnyk** [comment]
Hi @mohsen-ghafouri !

Thanks for all your fixes.
I am on my way to test them all.

Can you tell me was it done on purpose or it is a new issue that Save address button is above the Add address screen.

https://github.com/status-im/status-mobile/assets/147824399/6f5c9959-e0c1-413a-9433-40a3ca65ed05

**Comment by mohsen-ghafouri** [comment]
Hi @mariia-skrypnyk, it's interesting, can be related to Testnet banner, could you please confirm if it only happens when you are in testnet mode? 

I tried to resolve your point in ISSUE 12, the second point about button is behind keyboard.

**Comment by mariia-skrypnyk** [comment]
@mohsen-ghafouri no, Mainnet also has it.
And another place issue.


https://github.com/status-im/status-mobile/assets/147824399/fddcb90b-2204-40de-9d94-c1be3cbf3b52

https://github.com/status-im/status-mobile/assets/147824399/b15c4b26-6fec-404f-99dc-cfc6d9556b86

**Comment by mohsen-ghafouri** [comment]
Okay thanks, i will resolve it @mariia-skrypnyk

**Comment by mariia-skrypnyk** [comment]
**Issue 1:** two lines still visible but it is super low and can be a follow up 

https://github.com/status-im/status-mobile/assets/147824399/ce2613fd-ed9d-4eea-8fda-d2eaba1d413a

**Issue 2:** fixed 👍
**Issue 3:** fixed 👍
**Issue 4:** fixed 👍 except of Continue button
**Issue 5:** still have issue 
**Issue 6:** fixed 👍
**Issue 7:** fixed 👍
**Issue 8:** fixed 👍
**Issue 10:** still exist but it is tricky and can be a follow up 

**Steps:**

1. Install app and create User A (*you need a new user, I think it is specific point)
2. As User A open your Share QR code screen with opened Wallet tab 
3. On another device Add Address by scanning QR code of User B

Reproduced from the first try.
Sometimes when I've found it for the first time I needed to change network preferences of User B and scan once more

**Issue 11:** looks great 👍 but still observe issue with some colours that make letter not so visible, probably leave it to the design approve
Screenshot 2024-06-25 at 16 56 46
**Issue 12:**  fixed 👍

I've checked iOS side and going to start Android.
Will let you know if something went wrong ther.

**Comment by mohsen-ghafouri** [comment]
Thanks @mariia-skrypnyk , 
Issue 4 should be fine now.
Issue 5 https://github.com/status-im/status-mobile/issues/20543
Issue 10 https://github.com/status-im/status-mobile/issues/20571

**Comment by mariia-skrypnyk** [comment]
Hi @mohsen-ghafouri !

Added Issue 4 as a comment to your https://github.com/status-im/status-mobile/issues/20543.
Thanks for your incredible work!
Checked on both platforms and will move your PR to the design review by @Francesca-G 🙌 
Just trigger e2e one more time

**Comment by mohsen-ghafouri** [comment]
Hi @mariia-skrypnyk, Great, thank you for testing this PR. 🙌🏻

**Review by Francesca-G — COMMENTED** [review]
Here's the [review](https://www.figma.com/design/FuHW0rmIa5fQr5yyt3pXM6/Review-Wallet-%2F-Mobile?node-id=122-2486&t=poSDVhpwkuyUWcwH-1) 🙏

**Comment by mariia-skrypnyk** [comment]
Failed e2e are not related.

**Comment by mohsen-ghafouri** [comment]
@Francesca-G could you please check again?

**Review by Francesca-G — APPROVED** [review]
All good now ✨

**Pull request merged**
