### PR TITLE
fix: remove quo preview from nightly builds

### PR DESCRIPTION
**Pull request by mohsen-ghafouri**
remove quo preview from nightly builds

status: ready

### CODE REVIEW

**Review by ibrkhalil — APPROVED** [review]

**Comment by mohsen-ghafouri** [comment]
Hi @VolodLytvynenko , here is the fix.

**Comment by pavloburykh** [comment]
@mohsen-ghafouri thanks for the PR. 

Looks good, except one minor issue: quo preview has been removed in nightly build but there is an empty field left in settings list. Can we remove it too? 

photo_2024-01-19 11 52 07

**Comment by mohsen-ghafouri** [comment]
Hi @pavloburykh , could you please check again? thank you

**Comment by pavloburykh** [comment]
@mohsen-ghafouri thank you! PR is ready for merge.

**Pull request merged**
