### PR TITLE
[#19158] - Broken address input

### PR DESCRIPTION
**Pull request by ulisesmac**
This PR fixes the problem of not being able to type in the address input.

Issue:
- #19158 

Introduced in:
- #18905

However, **the scan feature was also broken, and this draft PR is not addressing it**.

Regarding to the problem reported, it was hard to identify because it's only happening on release compilation.

I couldn't identify the reason, we are using a `use-ref` hook to keep a state, and `use-ref` is not thought to do rendering job, so the solution implemented basically consists of removing the `use-ref-atom` hook and only use the `use-state` one. Although it seems this approach fixes the issue (still not sure how stable it is), it doesn't explain why only happened on release builds.

Any thoughts?

status: wip

### CODE REVIEW

**Comment by ulisesmac** [comment]
I'm opening this PR because I don't have enough context of the components changed and the approach taken during the migration. We can explore different solutions here.

@flexsurfer you mentioned you had another issue in the input in the login screen, and while I was working on another issue I noticed some flickering (that I guess you also solved), video from that PR:

[Screencast from 2024-02-28 12-48-32.webm](https://github.com/status-im/status-mobile/assets/90291778/35145a0d-3c5b-4c53-8db1-94776d0797fe)


So, maybe you can provide more context and a more reliable solution than what I added to this PR?

**Review by flexsurfer — APPROVED** [review]

**Comment by flexsurfer** [comment]
yeah idk, text-input works strangely, but anyway, we should try to avoid using the value

**Comment by briansztamfater** [comment]
> However, the scan feature was also broken, and this draft PR is not addressing it.

This bug is being addressed in #19259 👍

**Comment by ulisesmac** [comment]
> yeah idk, text-input works strangely, but anyway, we should try to avoid using the value

we are using a plan react native input, and since we are not managing the state with reagent, it shouldn't be a problem.

The strangest thing is it only fails on release compilation, since you did the migration, would you mind taking a look at the root cause? please

Although this has been approved, I'd prefer to merge once the root reason is identified, wdyt?

**Comment by flexsurfer** [comment]
ok, so i didn't find any documentation, but it seems if you set value once you MUST control it and set it on text-change, I didn't know that, so we must use state instead of ref, i just wanted to make it more performant and don't re-render text input but we MUST re-render it if we set value

**Comment by flexsurfer** [comment]
so , why it works different in debug and in release, we debug it changes state and text input re-rendered, in release it doesn't update state, idk why and what's the difference

**Comment by flexsurfer** [comment]
https://github.com/status-im/status-mobile/pull/19341

**Comment by ulisesmac** [comment]
> ok, so i didn't find any documentation, but it seems if you set value once you MUST control it and set it on text-change, I didn't know that, so we must use state instead of ref, i just wanted to make it more performant and don't re-render text input but we MUST re-render it if we set value

Yeah, we can find them on the Internet as controlled and uncotrolled components. 

For example, in reagent, typically, a controlled component needs to use `r/flush` since reagent makes updates at the end of the frame (in `requestAnimationFrame`), with `flush` it makes the updates immediatly, so that the "uncontrolled state" is synced with the "controlled state".

**Comment by ulisesmac** [comment]
> so , why it works different in debug and in release, we debug it changes state and text input re-rendered, in release it doesn't update state, idk why and what's the difference

Yeah :cry: that's why I didn't know if this solution was actually reliable, also the issue happens on both iOS and Android, very strange.

**Pull request closed without merging**
