### PR TITLE
Safe deserialization of the last message's content

### PR DESCRIPTION
**Pull request by rasom**
The issue was fixed in #7085 but reintroduced in #7055.

status: ready

### CODE REVIEW

**Review by cammellos — APPROVED** [review]

**Review by flexsurfer — APPROVED** [review]

**Comment by annadanchenko** [comment]
tested iOS, Android, macOS and Windows builds (fresh install), Android and iOS (upgrade from 0.9.32 hotfix-2 to this PR): message with problem char is removed upon app relaunch as expected.

**Comment by churik** [comment]
Tested on Linux Ubuntu 18.04 - message with problem char is removed upon app relaunch as expected.

**Comment by churik** [comment]
@rasom please, merge it also in `release/desktop/0.9.0`

**Comment by rasom** [comment]
@churik done

**Pull request merged**
