### PR TITLE
chore: rename opt to oeth

### LINKED ISSUE #19963: Change Optimism Mainnet short name from opt: to oeth:  everywhere in Desktop, Mobile, website and any other promo materials and documentation.
**Problem**
Wrong short chain name used for the Optimism Mainnet across various Status apps, website, documentation, and promotional materials. While the opt: prefix is currently being used, the official short name according to the chains_mini.json file on https://chainid.network/ is oeth:.

image
[chains_mini.json file on chainid.network](https://chainid.network/chains_mini.json)

**Implementation**
To address this issue, the following steps should be taken:
1. Change the Optimism Mainnet short name from opt: to oeth: This change should be implemented across all relevant components, including Desktop, Mobile, website, documentation, code implementations, promo materials and user interfaces.
2. Ensure consistency: After making the necessary changes, thoroughly review all instances where the Optimism Mainnet prefix is referenced to ensure consistency with the updated oeth: short name.
3. Review and approval: Submit the changes for review and approval by the Status QA team to ensure the correctness and completeness of the implementation.

**Acceptance Criteria**
1. Correct prefix established and documented: The oeth: prefix should be documented as the correct short name for the Optimism Mainnet.
2. Consistency across the project: All references to the Optimism Mainnet prefix within the project should be updated to use the oeth: short name consistently.
3. QA approval: The changes should be reviewed and approved by the Status QA team

**Notes**
[EIP-3770](https://eips.ethereum.org/EIPS/eip-3770) - standard defining name convention. 

**Future Steps**
Consider establishing a protocol for regularly reviewing and verifying the accuracy of cryptocurrency information within the project. This could involve periodic checks against verified sources or setting up automated processes to detect and flag any inconsistencies.

### PR DESCRIPTION
**Pull request by OmarBasem**
fixes: https://github.com/status-im/status-mobile/issues/19963

### Summary
This PR updates the short-name for Optimism network from `opt` to `oeth` across the codebase.

#### QA: What needs to be tested?
Just a smoke test and check the areas where the networks short names are used

### CODE REVIEW

**Review by seanstrom — APPROVED** [review]
Looks good! 👍 
Not sure how to find all the possible usages of `opt`, but I couldn't find any on your branch using a global search. So it should be okay I think 😄

**Comment by mariia-skrypnyk** [comment]
Hi @OmarBasem !

Have found an issue.
It appeared because of renaming and is not present in nightly with old "opt" address version.

**ISSUE 1:** user can not scan receiver address on Send to screen

**Steps:**

1. Login to app
2. Go to Wallet -> Account -> Send
3. Tap on scanner icon in Address field
4. Scan any wallet address that already has new "oeth" naming

photo_2024-05-14_12-29-46

**Actual result:** "Oops" error occurs
**Expected behaviour:** scanned address appeared in Address field on Send to screen
**Devices:** iOS 13 (17.3.1) Samsung A34 (14.0)

**Comment by OmarBasem** [comment]
There is a `status-go` PR  to update the short names there so I will wait for it https://github.com/status-im/status-go/pull/5163

**Comment by mariia-skrypnyk** [comment]
@OmarBasem ok👍 , just let me know then!

**Comment by smohamedjavid** [comment]
@OmarBasem  - Can you help update this branch/PR with the latest changes in the [status-go PR](https://github.com/status-im/status-go/pull/5163)? 

There are migration changes in it. I did run some test locally on Simulator and it worked fine. It's good that we test it in real device.

**Comment by OmarBasem** [comment]
@smohamedjavid are you sure the multichain scan worked for you? It still did not work for me after I updated status-go here. Probably there is something in the validation I need to fix/update

Update: fixed it.

**Comment by OmarBasem** [comment]
@mariia-skrypnyk fixed it!

**Comment by OmarBasem** [comment]
Hey @churik, letting you know that I am updating status-go version here from `v0.179.17` to `v0.179.19`

**Comment by mariia-skrypnyk** [comment]
Hi @OmarBasem !

Thanks for your fix, it works on both platforms!
PR is ready to be merged!

**Pull request merged**
