### PR TITLE
Introduces bounty statistics script

### LINKED ISSUE #3193: Script to measure bounties issued over time period
### User Story

As a dev interested in improving monthly active contributors, I want to see and encourage people who post bounties.

As a dev interested in posting more bounties, I want to see how I'm doing over time so I feel incentivized to post more bounties.

### Description

*Type*: Feature/Tooling

*Summary*: Write a script that outputs a CSV to STDOUT with format something like `PERIOD, GITHUB_NAME, BOUNTIES_POSTED`. This will later be used in a spreadsheet to check (opt-in) bounties posted over some timeframe, such as per week.

PERIOD could be either a specific date or a weekly period such as 2018-01-01-2018-01-08 (e.g.).

### Solution

Inspiration from https://github.com/status-im/status-react/blob/develop/scripts/pr-statistics.sh

Should check issues in a given repo (such as status-react) or over a whole organization. Count issues with `bounty` label. Ideally it should be based on who adds the `bounty-awaiting-approval` label first, but it can also be based on who made the issue that has the `bounty` tag on it.

### Size

Not sure if it is a small or medium bounty.

### PR DESCRIPTION
**Pull request by chuck-sys**
Fixes #3193

### Summary:
Provides a python script that uses Github API to see who initiated bounties given a repository or organization.

Edit: [CSV for status-im/status-react][csv].

### Testing notes:
Username/password pair is required because of Github rate limiting for non-authenticated users, which is capped off at 60 requests/hour. This script uses Basic Authentication, giving us 5000 requests/hour, a bit more to work with. Since it makes a call for every bounty issue, I don't think you should test it on large organization with lots of bounty issues. It also takes a while too, so I recommend using the `-v` option.

### Steps to test:
- `python3 scripts/bounty-statistics -h`
- `python3 scripts/bounty-statistics -r "status-im/clj-rn" -v cheukyin699 # Your username here`
- Type/Paste password/token when prompted
- `python3 scripts/bounty-statistics -r "status-im/clj-rn" -v -d month cheukyin699 # Your username here`
- Type/Paste password/token when prompted
- ...

status: ready

[csv]: https://gist.github.com/cheukyin699/026714b322103559447491e2663a7d49

### CODE REVIEW

**Comment by guyghost** [comment]
For this to work... We need to configure the loading of pipeline library inside Jenkins job

**Comment by andytudhope** [comment]
Hey @cheukyin699 thanks so much for the PR. Unfortunately, I'm no python expert and @oskarth  is on vacation currently. Don't be discouraged, we will get to this!

**Comment by andytudhope** [comment]
Hey @cheukyin699 - I think we should discuss with @pablanopete if we can give you some reward for the work you did here.

We have been back and forth for some time about the future of Open Bounties and we now have a clearer idea of the direction we want to take going forward. I apologise that it has taken us so long to make up our minds, but I am going to close this now as it doesn't really fit into our plans going forward.

Like I say, we can organise with @pablanopete to make sure you still receive some portion of the bounty for what you have submitted.

**Comment by pablanopete** [comment]
@cheukyin699 Please email me at Chris.hutchinson@status.im with your address so I can send you an SOB reward for this contribution!

**Pull request closed without merging**
