### PR TITLE
☝️Point Go to 5807

### PR DESCRIPTION
**Pull request by shivekkhurana**
# Description
This PR is a placeholder to test changes made to Status Go in this PR -> https://github.com/status-im/status-go/pull/5807

# Testing notes
There are notes on changes about the fix on Desktop client, we need to check the paths outlined there
https://github.com/status-im/status-desktop/pull/16330

# Known issues
There were 6 regressions introduced in the last PR that improved the router. We are not sure if it was Status Go changes or client issues, but they issues still exist, and might be reflected while testing this PR. 

If you face one of the 6 issues referred in [this PR](https://github.com/status-im/status-mobile/pull/21235), just refer to the existing issue. If there are new issues, we can follow the process as usual and ask Desktop to fix the problems in that PR itself.

# Time sensitivity
Since this is a cross team issue, it's important to be mindful of time. The last time, the router cleanup issues were dragged for sometime (which is my fault as I couldn't pick up and delegate them). Let's try better this time.

### CODE REVIEW

**Comment by VolodLytvynenko** [comment]
Hey @shivekkhurana, thank you for the PR. The e2e and android builds have failed https://github.com/status-im/status-mobile/pull/21281#issuecomment-2358214833. Could you take a look please

**Comment by shivekkhurana** [comment]
@VolodLytvynenko 

It was probably because of not having the correct commit hash (I used PR number for Go). I have pushed a change, please try again and lmk if it works this time.

**Comment by briansztamfater** [comment]
From what I've seen swaps shouldn't been affected as deprecated methods are still available, but I'll spend some time today to test this locally

**Comment by VolodLytvynenko** [comment]
hi @shivekkhurana The [issue](https://github.com/status-im/status-mobile/issues/21249) is not fixed in current PR. Still reproducible
[Status-debug-logs.zip](https://github.com/user-attachments/files/17056757/Status-debug-logs.zip)

**Comment by VolodLytvynenko** [comment]
[Issue](https://github.com/status-im/status-mobile/issues/21251) with error "eq() not a number: <0.01" is still reproducible as well
[Status-debug-logs (1).zip](https://github.com/user-attachments/files/17056810/Status-debug-logs.1.zip)

**Comment by VolodLytvynenko** [comment]
The [issue](https://github.com/status-im/status-mobile/issues/21250) related to closing the keyboard is also reproducible

**Comment by VolodLytvynenko** [comment]
Hi @shivekkhurana, thank you for the PR. No other issues from my side. I didn’t notice any visual improvements - existing issues still remain, and I didn't find any new ones either. If this is the expected result, then the PR can be merged

**Comment by churik** [comment]
I'll close this PR then, as we do not require bump of version, thank you

**Pull request closed without merging**
