### PR TITLE
Remove mp4s from android bundle

### LINKED ISSUE #19987: Video assets which are iOS only should not end up in Android bundle
# Problem

The video asset files used for onboarding animation are ~ 30 MB and they end up in the Android APK.
The component which uses those assets is not rendered in Android but maybe because its a runtime check those assets make their way into the bundle anyway.

We should find a way to make sure those video assets are included in iOS only so that we can shave off 30 MB from the Android APK.
 
Related links : 
- https://reactnative.dev/docs/images#images-from-hybrid-apps-resources
- https://reactnative.dev/docs/platform-specific-code#platform-specific-extensions

### PR DESCRIPTION
**Pull request by siddarthkay**
## Summary

I recently discovered that we have `mp4` video assets as part of `Android` bundle which are never used on `Android`.
The animations are hidden only shown on certain `iOS` devices and this is done via a runtime check which includes only certain `iOS` devices. 
Because of this logic and the way `react-native` bundles assets into binaries we get these assets inside the Android `APK` as well.

This PR swaps the `mp4` files with fake ones of `4 bytes` each after a release build is generated in a nix phase.
This step would only happen for `nightly`, `PR` and `release` builds, since we care about final `APK` size. 

This helps us to shave off roughly `30 MB` on the `APK` size

## Testing notes
not needed since we just optimise the size of final `APK`.

## Platforms
- Android

fixes: #19987 

status: ready

### CODE REVIEW

**Review by ilmotta — APPROVED** [review]
@siddarthkay Curious, how far are we with this PR from lowering the APK to the 100MB threshold?

**Comment by siddarthkay** [comment]
> how far are we

another 20 MB, we do have some image assets which are upwards of 1 MB each and probably some manual lossless png compression can help us with those assets

**Review by Parveshdhull — APPROVED** [review]

**Review by jo-mut — APPROVED** [review]

**Review by jakubgs — CHANGES_REQUESTED** [review]
I don't like this. I don't want to make the derivation even more complex.

Is it difficult to do this using Gradle?

**Review by apentori — APPROVED** [review]

**Comment by J-Son89** [comment]
@siddarthkay @jakubgs - let's pause this if it adds complications. There is some argument to just remove these videos completely for now. Let's discuss in messenger if you want 👌

**Comment by siddarthkay** [comment]
> Is it difficult to do this using Gradle?

Takes longer the `gradle` way.
Because we first build the android `apk` in a nix sandbox and after the release build is sent to results directory we can then execute a `gradle` task but then we'd need to start a `gradle` daemon for that.

Hence i pivoted to using `nix` for this part.

**Comment by siddarthkay** [comment]
> There is some argument to just remove these videos completely for now

Hmm sounds good.
I'll park this PR as draft for the time being then.

also E2E failures don't look too good as well 
> 0% of end-end tests have passed

**Comment by yevh-berdnyk** [comment]
hi @siddarthkay, I've tried to install e2e apk on my local emulator and got this error:

image


That's also caused SauceLabs session to fail. Here is a [logcat.log](https://github.com/status-im/status-mobile/files/15312266/logcat.3.log) if it can be helpful

**Comment by siddarthkay** [comment]
@yevh-berdnyk : Thanks for taking a look.
I'm closing this PR in favour of https://github.com/status-im/status-mobile/pull/20026

**Pull request closed without merging**
