### PR TITLE
Bug/wallet recovery

### LINKED ISSUE #4745: After recover account some of 1:1 chats with only received messages are shown
### Description

*Type*: Bug

*Summary*: If user recovered an account and had 1:1 chats before this then 
1. some of 1:1 chats are shown with only received messages
2. Usernames on 1:1 chats are shown with default random 3 words and picture  
3. Contacts are empty
4. public chats opened before recover are not shown

#### Before recover:

home before recover
chat before recover

#### After recover:
home after recover
chat after recover
contacts after recover

#### Expected behavior
imo, we set false expectations by showing 1:1 chats and received messages there. We haven't implemented recover contacts/chats/messages for the case when account is recovered and how it works now is a side effect of offline inboxing. 

I would suggest to not show any chats and their content when account is recovered, so user starts with empty Home tab and Contacts (as it was before). In addition, we can add explanation on the Recover screen warning user that only address/public key will be recovered (thus funds and transaction history will be fine) but no Chats, Contacts and Chats history is recovered.

#### Actual behavior
1:1 chats with only received messages are shown after recovery. 

### Reproduction

- As account A: add account B and C to your contacts and exchange messages in 1:1 chats and public chat
- As account A: uninstall app
- As B and C send new messages to the account A
- install app and recover account A. Wait for some time to get 1:1 chats and check their content. Check what's shown in Contacts

### Additional Information
* Status version: nightly build June 13
* Operating System: Android and iOS

### PR DESCRIPTION
**Pull request by cammellos**
fixes #4745

### Summary:

1) When creating a new account / recovery we don't poll the mailserver anymore for historic messages, which solves the immediate issue of fetching only received messages

2) Handle messages sent from a different device in public chat / restore history. The message will be added, shown correctly as sent by the user, and the status will be set as `sent` ( need to check for `seen` race condition, as messages will now be added twice). This means that multidevice should now work for public chats.

3) Move contact updates to discovery topic. This is necessary as there is a pre-existing bug whereby contact updates would not work anymore after wallet recovery, as the code relies on the initial contact request being stored on the mailserver, which we cannot guarantee (we only pull 7 days of data). Not pulling history anymore exacerbate the problems but does not introduce it.
To make sure that contact updates will work after wallet recovery, we also need to consider a `ContactUpdate` in the same way we consider a `ContactRequest` (the other peer has no idea that the user has recovered the wallet). This does not change any behaviour in terms of obscurity/security as `ContactRequest` are automatically processed (in both case the contact will be set as `pending?`, not as accepted)
At this stage `ContactRequest`, `ContactRequestConfirmed`, `ContactUpdate` have all the same logic, i.e. update the contact information, leave the pending flag alone.

4) Only 1 day of history is fetched for newly joined chats, if catching up 7 days is the cap as before.

### Review notes:

I have refactored `add-received-message` as it was getting a bit unwieldy, it would be good to have a careful look at it, as most of it is not covered by tests.

Outgoing is now calculated in `add-received-message` and `add-message`, there's a bit of duplication, but will take care later.

### Testing notes:

1) Sending messages in general
2) Recovery of account
3) Joining public chats after recovery where messages have been sent (previous version will not show your own messages)
4) Multi-device in public chats should now work
5) Recovery of account and updates of info

The behaviour for contact updates is as follow:

Device A runs 0.9.20, Device B runs this version:

B recovery account, A sends contact updates, B will not receive them (existing issue, made worse by the fact that we don't fetch history anymore)
A recovers account, B sends contact updates to A, A will receive the contact update

Both devices runs this version:
No matter which one recovers they should both receive contact updates.

Both devices run 0.9.20
If recovery happens in the first 7 days before contacts have been added, everything works as expected
If recovery happens after, then is unlikely to work (the device that has recovered the account would need to re-add the other, to *receive* updates from it, and even so there's a 50% chance it might not work)

Given the breadth of the changes, this is post-beta material in my opinion.

status: ready

### CODE REVIEW

**Review by janherich — APPROVED** [review]

**Review by dmitryn — APPROVED** [review]

**Comment by lukaszfryc** [comment]
@cammellos I experienced 2 issues that I really want to investigate more before merging this PR. Both of the issues happened on a recovered account that was used on a second device in the same time (multi-device scenarios)

1. I recovered, joined a public chat and I saw messages I sent. Then I clicked on some user that was in the public chat and added him as contact. An error with "transport" message appeared.

2. I recovered and joined a public chat that I used before. Then I decided to log out. When I pressed the log out button "null is not an object" error appeared. I had to kill the app to log in again. Stacktrace: 

```
07-02 07:39:35.287 31343 31409 I ReactNativeJS: PRETTY PRINTED EXCEPTION
07-02 07:39:35.287 31343 31409 I ReactNativeJS:
07-02 07:39:35.287 31343 31409 I ReactNativeJS: ***
07-02 07:39:35.287 31343 31409 I ReactNativeJS: NAME: "TypeError"
07-02 07:39:35.287 31343 31409 I ReactNativeJS: MESSAGE: null is not an object (evaluating 'e.stopWatching')
07-02 07:39:35.287 31343 31409 I ReactNativeJS:
07-02 07:39:35.287 31343 31409 I ReactNativeJS: remove_filter_BANG_@index.android.bundle:12:6870815
07-02 07:39:35.287 31343 31409 I ReactNativeJS: G__34985_34991@index.android.bundle:12:6879315
07-02 07:39:35.287 31343 31409 I ReactNativeJS: index.android.bundle:12:2428656
07-02 07:39:35.287 31343 31409 I ReactNativeJS: invoke_interceptor_fn@index.android.bundle:12:2376022
07-02 07:39:35.287 31343 31409 I ReactNativeJS: invoke_interceptors@index.android.bundle:12:2376323
07-02 07:39:35.287 31343 31409 I ReactNativeJS: execute@index.android.bundle:12:2378693
07-02 07:39:35.287 31343 31409 I ReactNativeJS: handle@index.android.bundle:12:2387185
07-02 07:39:35.287 31343 31409 I ReactNativeJS: re_frame$router$IEventQueue$_process_1st_event_in_queue$arity$1@index.android.bundle:12:2421734
07-02 07:39:35.287 31343 31409 I ReactNativeJS: re_frame$router$IEventQueue$_run_queue$arity$1@index.android.bundle:12:2404073
07-02 07:39:35.287 31343 31409 I ReactNativeJS: index.android.bundle:12:2409825
07-02 07:39:35.287 31343 31409 I ReactNativeJS: re_frame$router$IEventQueue$_fsm_trigger$arity$3@index.android.bundle:12:2414036
07-02 07:39:35.287 31343 31409 I ReactNativeJS: index.android.bundle:12:2406591
07-02 07:39:35.287 31343 31409 I ReactNativeJS: index.android.bundle:212:1369
07-02 07:39:35.287 31343 31409 I ReactNativeJS: x@index.android.bundle:212:643
07-02 07:39:35.287 31343 31409 I ReactNativeJS: callTimers@index.android.bundle:212:2788
07-02 07:39:35.287 31343 31409 I ReactNativeJS: value@index.android.bundle:207:3582
```

I can't reproduce these errors or find TF sessions for those errors. @cammellos do you have any idea what went wrong here?

**Comment by cammellos** [comment]
@lukaszfryc I will investigate, not 100% sure they are related, but needs fixing anyway, so just to make sure probably best to handle here.

I have a question: 2) seems to be caused by 1) , was it the same session / device? or 2 separate devices/accounts/login-logout?

**Comment by cammellos** [comment]
@lukaszfryc Also let me know if you manage to get hold of the TF sessions, not critical, so don't spend extra time, I will try to replicate myself as well

**Comment by lukaszfryc** [comment]
@cammellos I'm doing the final testing now

**Comment by lukaszfryc** [comment]
@cammellos I checked all scenarios related to contact updates and I could not replicate the errors. If you can't replicate it either, I think this might not be related as you suggested. 

But, I noticed one thing and I'm not sure if it's the same issue you described:
> B recovery account, A sends contact updates, B will not receive them (existing issue, made worse by the fact that we don't fetch history anymore)

Here is what I have in mind:
1. Device A: Installs 0.9.20
2. Device B: Installs this PR build
3. Device A and B: Adds each other as contacts
4. Device B: Backups the seed and uninstalls the app
5. Device B: Recovers the account
6. Device A: Sends a message to device B. **Device B receives it but the sender has default name**. If "Add to contact" is clicked, the name updates on Device A.
7. Device A: Upgrades to 0.9.21 and sends another message to Device B. Device B still sees the default username 
8. Device A: Updates the username. Device B: now the updated name is shown

So, unless Device A does not update his username, the Device B will always see his default name. @cammellos is it known and can't be fixed?

**Comment by cammellos** [comment]
@lukaszfryc I tried as well to replicate this morning but no luck, probably worth keeping an eye on it though.

About the updates, yes after recovery you will need the other contact to update their name before you can see it. It could be fixed, there are a few ways we can handle this, but probably outside the scope of this PR for now.

**Comment by lukaszfryc** [comment]
@cammellos sounds good. I'll created https://github.com/status-im/status-react/issues/5036 for it.

Let's merge this PR and test team will test it more deeply tomorrow after cutting the next release.

**Pull request merged**
