### PR TITLE
Fix WalletConnect initialisation after logout

### LINKED ISSUE #20884: Can't connect to dapp after logging out and logging in again
# Bug Report
When scanning a WalletConnect QR code after the user logged out and logged in again (same or different profile), the scanner doesn't respond with anything.

## Problem 
[comment]: # (A problem description)

#### Expected behavior
Can connect after logging out

#### Actual behavior
Can't connect after logging out

### Reproduction

1. Open status
2. Log in and try to connect (should work)
3. Log out (without closing the app)
4. Log into the same account and try to connect
5. After scanning nothing happens

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by clauxx**
fixes #20884

### Summary
Not clearing the network and WalletConnect sdk when logging out.

status: ready

### CODE REVIEW

**Review by shivekkhurana — APPROVED** [review]

**Comment by clauxx** [comment]
@qoqobolo Would be best to get this one in first, so other PRs can rebase and see if the regressions there are fixed.

**Comment by qoqobolo** [comment]
@clauxx could you clarify one moment in the steps please?

```
1. Open status
2. Log in and try to connect (should work)
3. Log out (without closing the app)
4. Log into the same account and try to connect
5. After scanning nothing happens
```
How can I make step 4 if I am already connected to the dapp in step 2?
Do you mean connect to another dapp / or should I not press `Connect` in step 2 / or should I have disconnected before logout?

**Comment by qoqobolo** [comment]
The good news is that now I can connect on the first try without reopening the app and refreshing the dapp page 👍

**Comment by qoqobolo** [comment]
You [mentioned](https://github.com/status-im/status-mobile/pull/20799#issuecomment-2250212162) that https://github.com/status-im/status-mobile/issues/20794 should be fixed here but it's not.
The issue is still reproducible

**Comment by qoqobolo** [comment]
Thanks a lot for the fix @clauxx!
Tested connect and basic flows - LGTM.

**Pull request merged**
