### PR TITLE
Fix bug with characters in password

### PR DESCRIPTION
**Pull request by cammellos**
Backport hotfix on develop branch.

status: wip

### CODE REVIEW

**Comment by ghost** [comment]
### Pull Request Checklist
- [x] Have you updated the documentation, if impacted (e.g. [docs.status.im](https://docs.status.im/docs/build_status.html))?

**Review by mandrigin — APPROVED** [review]

**Review by rasom — APPROVED** [review]

**Comment by Serhy** [comment]
I was tested builds from https://ci.status.im/job/status-react/job/pull%20requests/view/change-requests/job/PR-7065/5/ (job aborted due to Windows build) where iOS, Android, MacOS succeded

- Can create and recover account with password `-/:;()$&@“.,?!’[]{}#%^*+=_\|~<>€£¥•.,?!’` / `àáâãäåæāăą` / `aaaaa12345`
- Autologin with accounts using above passwords works on iOS 12.0.1
- 0.9.32 release build can exchange messages and transactions with current PR build
- Can upgrade 0.9.32 with the accounts using  `-/:;()$&@“.,?!’[]{}#%^*+=_\|~<>€£¥•.,?!’` / `àáâãäåæāăą` / `aaaaa12345` passwords and log in (+ the `-/:;()$&@“.,?!’[]{}#%^*+=_\|~<>€£¥•.,?!’` was with enabled autologin set) 

I'd run e2e tests as well, but makes sense to get successful job with all the builds succeded...

<blockquote><div><strong><a href="https://ci.status.im/job/status-react/job/pull%20requests/view/change-requests/job/PR-7065/5/">status-react » pull requests » PR-7065 #5 [Jenkins]</a></strong></div></blockquote>

**Comment by cammellos** [comment]
@Serhy buid is ready, could you run auto-test?

**Comment by Serhy** [comment]
All looks good (re-tested again https://github.com/status-im/status-react/pull/7065#issuecomment-446117272 builds and failed autotest in known issue will be fixed along with Wallet redesign)

**Pull request merged**
