### PR TITLE
[#7346] Add Aragon dapp

### PR DESCRIPTION
**Pull request by rasom**
solves #7346

status: ready

### CODE REVIEW

**Review by jeluard — APPROVED** [review]

**Review by flexsurfer — APPROVED** [review]

**Review by mandrigin — APPROVED** [review]
We also need one PR with https://aragon.staging.aragonpm.com/#/aracon.aragonid.eth as a URL to be able to test stuff.

**Comment by jeluard** [comment]
@rasom Build failed

**Comment by mandrigin** [comment]
> Unable to resolve module `./resources/images/contacts/aragon.png` from `/home/jenkins/workspace/status-react_prs_android_PR-7347/index.android.js`: The module `./resources/images/contacts/aragon.png` could not be found from `/home/jenkins/workspace/status-react_prs_android_PR-7347/index.android.js`. Indeed, none of these files exist:
>   * `aragon.png`
>  * `/home/jenkins/workspace/status-react_prs_android_PR-7347/resources/images/contacts/aragon.png/index(.native||.android.js|.native.js|.js|.android.json|.native.json|.json)`

**Comment by rasom** [comment]
thanks, fixed, missed image

**Comment by rasom** [comment]
@mandrigin do you mean separate PR?

**Comment by mandrigin** [comment]
@rasom yes, this link that you added isn't live yet afaik, they only have a staging URL that is working now. So if we want to test anything, it should be this staging URL.

**Comment by rasom** [comment]
@mandrigin https://github.com/status-im/status-react/pull/7349

**Comment by asemiankevich** [comment]
@rasom @rachelhamlin @jeluard this dapp opens as blank screen in status browser despite the privacy mode on/ off.
image

I can proceed in metamask and chrome browser on Mainnet.

**Comment by mandrigin** [comment]
just to reiterate in public, Aragon mobile isn't deployed yet to this URL.
We will need to test https://github.com/status-im/status-react/pull/7349,and if it's okay, them merge **this** PR... non-intuitive.

**Comment by mandrigin** [comment]
also cherry-picked to `release/0.9.32-3-aragon-mobile`

**Pull request merged**
