### PR TITLE
Redirect user to Activity Center to manage pending contact requests

### LINKED ISSUE #14579: Redirect user to Activity Center to manage pending contact requests
# Feature Issue

When the user presses the *Pending contact requests* section, the Activity Center should be opened in the *Contact Requests* tab and with the unread filter enabled.

### Shouldn't we use the current design?

The current design specifies that when the user presses the *Pending contact requests* section they should see a bottom sheet, fully featured to manage the requests. This is currently implemented in production code, but it's buggy (UI and behavior) and it's duplicating most of the features already available in the Activity Center.

Instead of fixing the issues, designers and engineers agreed to simply reuse the Activity Center **until the dogfooding of the new mobile app stabilizes**. This will give us more time to work on other important issues. In the future (probably around late Feb/2023 or later), we can reevaluate this feature, therefore it's only temporarily deprioritized @xAlisher, @pedro-et

image

### Resources

- Current design in [Figma - Messages for Mobile](https://www.figma.com/file/7KIYbhoqNGAIFonE0w9TDz/Messages-for-Mobile?node-id=2010%3A507764&t=cguAmdcNZy7qazwk-0).

### LINKED ISSUE #14591: Pending contact requests are only shown when there's at least one friend
# Bug Report

Pending contact requests are not shown when the user doesn't have at least one mutual contact.

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td></td>
      <td></td>
    </tr>
  </tbody>
</table>

#### Expected behavior

The user should see the pending contact requests section if there's one or more pending requests, regardless of the total amount of mutual contacts in their contact list.

### Reproduction

1. Create account A
2. As B, send a contact request to A
3. Open the `Messages` screen, `Contacts` tab.
4. Verify there's no *Pending contacts* section, but the Activity Center shows the request.

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

### PR DESCRIPTION
**Pull request by ilmotta**
fixes #14591
fixes #14579 

### Summary

- [x] `Fixed` https://github.com/status-im/status-mobile/issues/14591
- [x] https://github.com/status-im/status-mobile/issues/14579
- [x] Removed code for the old bottom sheet screen to manage pending contact requests.
- [x] Replaced usages of `status-im.utils.fx` with `utils.re-frame/dispatch` (spoiler, this was much harder than it seems, see the notes below if you're curious).
- [x] Refactored test helper for testing logs in order to better work with asynchronous ClojureScript tests.

#### New behavior

>Given a user has at least 1 pending contact request,
>And they open the `Messages` screen > `Contacts` tab,
>And they press the `Pending requests` section,
>Then the Activity Center should be opened in the `Contact requests` tab with the `unread` filter enabled.

[Pending contact requests.webm](https://user-images.githubusercontent.com/46027/208979440-05a72396-04e1-4711-9cee-d3ea9c3821ab.webm)

### Notes about testing event handlers using our `utils.re-frame/dispatch` function

In order to write tests for event handlers using `re-frame.test/run-test-sync` we need to make sure all calls to `re-frame.core/dispatch` are visible to the macro. The thing is that our guidelines suggest we use `utils.re-frame/dispatch` instead, but this doesn't work with the testing library.

The current implementation in https://github.com/day8/re-frame-test/blob/master/src/day8/re_frame/test.cljc#L297 uses `with-redefs`, which **does not work with our aliased function `utils.re-frame/dispatch`**. This is how `with-redefs` work, there's nothing we can do.

This PR solves this problem by wrapping the original `re-frame.test/run-test-sync` macro body with our own `with-redefs` to explicitly redefine our aliased `utils.re-frame/dispatch` function.

Hence, from now on, we're able to write tests for event handlers that use our `utils.re-frame/dispatch` function, so no more using `re-frame.core/dispatch`. cc @flexsurfer

### Notes about the improved way to test logs

During RDD (REPL-Driven Development) sessions, I have faced limitations to write tests for log messages when the tests are asynchronous, because it was harder to inspect logs when assertions failed. I solved this problem by creating a new fixture.

Therefore, for anyone that wants to test log messages (in event handler namespaces or not), as this PR shows, you just need to call `(status-im.test-helpers/use-log-fixture)` at the top of the namespace. I think the usage is now even simpler and more flexible!

### Platforms

- Android
- iOS

### Steps to test

1. Create a new account A or use an account without contact requests (pending or not).
2. Send a contact request from B to A.
3. Verify the pending request is displayed in `Messages` screen > `Contacts` tab.
4. Click on the pending request and verify the Activity Center is opened in the `Contact requests` tab with the `unread` filter enabled.
5. Switch tabs in the Activity Center and close it.
6. Click again on the `Pending requests` section and notice the Activity Center always opens with the `Contact requests` tab opened. This allows the user to easily manage contact requests.

status: ready

### CODE REVIEW

**Review by smohamedjavid — APPROVED** [review]

**Review by flexsurfer — APPROVED** [review]

**Review by jo-mut — APPROVED** [review]

**Comment by pavloburykh** [comment]
@ilmotta Thanx for your work!

Please, take a look at the following issue

### ISSUE 1 Pending contact request remains in pending list in case if it is cancelled by sender

By canceling contact request I mean: removing user form contacts by sender before receiver accepts/declines the request. 

**Steps:** 
1. User A adds User B as contact to generate contact request
2. User A cancels contact request
3. Pay attention by User B if there are any pending contacts request in contacts section of Chat screen 

**Actuals result:** Pending contact request remains in pending list until relogin/opening AC. At the same time, cancelled contact request is removed from AC as expected. 

**Expected result:** contact request is removed from pending list of the receiver in case of its cancellation by sender. 

https://user-images.githubusercontent.com/97245802/209164770-f73ef616-38aa-4701-a803-4591b246297e.mp4

[Receiver-debug-logs.zip](https://github.com/status-im/status-mobile/files/10287935/Receiver-debug-logs.zip)
[Sender_debug_logs.zip](https://github.com/status-im/status-mobile/files/10287937/Sender_debug_logs.zip)

**Comment by pavloburykh** [comment]
### ISSUE 2 Some elements are missing accessibility ids which are required for development of e2e tests

1. Contacts tab

Appium 2022-12-22 17-46-10

2. Pending request element

Appium 2022-12-22 17-48-36

3. Pending contact requests counter

Appium 2022-12-22 17-49-21

4. Contacts tab unread badge 

Appium 2022-12-22 17-50-06

**Comment by ilmotta** [comment]
Oh it's nice you found some issues @pavloburykh, let's get it all working!

>ISSUE 1 Pending contact request remains in pending list in case if it is cancelled by sender

I'll investigate and see if the fix is sensible. If it is, then I'll try to fix in this PR, otherwise I'll create an issue and fix it as soon as this one is merged. I'll let you know once I have more context.
Edit: Fixed in this PR.

>ISSUE 2 Some elements are missing accessibility ids which are required for development of e2e tests

Cool, I'll add those!
Edit: Accessibility labels added.

**Comment by ilmotta** [comment]
FYI: @pavloburykh, in theory ISSUE 1 and 2 have been solved.

**Comment by pavloburykh** [comment]
@ilmotta Thanx for great job and fixes. PR is tested and ready for merge. Failed e2e is not PR related.

**Pull request merged**
