### PR TITLE
[#7400] implement updated copy for beta alert and disclaimer

### LINKED ISSUE #7400: Update Beta alert
# Problem
When I create a (new) account on Status Beta, I receive an alert that:
- informs me about the Beta state
- informs me to manually select Mainnet if I'm upgrading an existing account
- warns me that the app is on Mainnet and transactions are real, and transfers to testnets 

The message is long, obtrudes the UI and the number of users still upgrading from pre-beta likely has decreased.

The warning needs to be updated and potentially differ between recover and create account.

**Copy will be iterated on in the comment thread of this issue.**

## Current implementation
mainnet alert android
mainnet alert ios

# Acceptance Criteria
UI same as current warning, but with updated copy.

1. warning shown when I create an account
2. warning shown when I recover account
3. warning shown when I create the account in release and upgrade
4. warning shown when I recover account in release and upgrade to this build

# Notes
This is the issue created in June to support Beta release https://github.com/status-im/status-react/issues/4718

# Future Steps
- Create new account
- Upgrade existing pre-beta account?

### PR DESCRIPTION
**Pull request by zeddee**
Fixes #7400

### CODE REVIEW

**Comment by zeddee** [comment]
gpg signing not working on my end for some reason; will fix

**Review by flexsurfer — APPROVED** [review]

**Comment by hesterbruikman** [comment]
iPhone 8:
- [x] Recover
- [x] Create additional account
- [x] Create new account

Android 7:
- [-] Recover: app keeps crashing after the alert has been shown. I doubt that this has anything to do with this PR, but relates to some background account recovery process. @flexsurfer can you confirm that it's unlikely to have something to do with this PR?
- [x] Create additional account
- [x] Create new account

**Comment by flexsurfer** [comment]
@hesterbruikman i can confirm it's not related to this PR.

**Review by hesterbruikman — APPROVED** [review]
Looks good @zeddee  Thank you!

**Comment by zeddee** [comment]
thanks @hesterbruikman @flexsurfer 🎉

**Comment by churik** [comment]
@zeddee thank you for your contribution!

Tested on IOS and Android:

- [x] create account on PR ->  warning
- [x] recover account on PR ->  warning

And as far as I can unterstand from issue https://github.com/status-im/status-react/issues/7400#issue-405757474, disclaimer should be shown in following cases as well:
- [ ] recovering account on 0.9.33, upgrade to current PR -> warning (with autologin enabled)
- [ ] creating account on 0.9.33, upgrade to current PR  -> warning (with autologin enabled)
- [ ] recover account on 0.9.33, upgrade to current PR  -> warning
- [ ] creating account on 0.9.33, upgrade to current PR  -> warning
In these cases disclaimer is not shown for now.

@hesterbruikman please fix me if I misunderstood you.

**Comment by hesterbruikman** [comment]
> 
> 
> @zeddee thank you for your contribution!
> 
> Tested on IOS and Android:
> 
>     * [x]  create account on PR ->  warning
> 
>     * [x]  recover account on PR ->  warning
> 
> 
> And as far as I can unterstand from issue [#7400 (comment)](https://github.com/status-im/status-react/issues/7400#issue-405757474), disclaimer should be shown in following cases as well:
> 
>     * [ ]  recovering account on 0.9.33, upgrade to current PR -> warning (with autologin enabled)
> 
>     * [ ]  creating account on 0.9.33, upgrade to current PR  -> warning (with autologin enabled)
> 
>     * [ ]  recover account on 0.9.33, upgrade to current PR  -> warning
> 
>     * [ ]  creating account on 0.9.33, upgrade to current PR  -> warning
>       In these cases disclaimer is not shown for now.
> 
> 
> @hesterbruikman please fix me if I misunderstood you.

Correct, ideally the alert is shown when upgrading as well; The information is still valid and that way there will be a clear difference when the alert is no longer shown.

I did however, not realize that this introduced a new requirement as I'd been getting the alert on upgrading, but probably I've been upgrading to Public Release from Nightly.

@flexsurfer can you give an estimate on effort required to add the alert to this scenario?

**Comment by hesterbruikman** [comment]
@zeddee looking into this. Thanks for your patience.

**Comment by hesterbruikman** [comment]
Created a new issue to make sure we show the alert on upgrading to a new release as well: https://github.com/status-im/status-react/issues/7598

This means we can approve and close this PR. @flexsurfer can you help merge?

**Comment by rachelhamlin** [comment]
Andrey is afk for most of today. It looks okay to merge but I'll hold off.

**Comment by mandrigin** [comment]
removing the "Issues" label because these issues weren't introduced by this PR and they will be fixed in 
https://github.com/status-im/status-react/issues/7598

**Pull request merged**
