### PR TITLE
rnn leftovers

### LINKED ISSUE #12224: Broken wallet view after Watch only account is deleted
# Bug Report

## Problem 
When user removes Watch only wallet account there is no navigation back to main Wallet view happens. Thus wallet account view looks "broken"
(followed up issue after https://github.com/status-im/status-react/pull/12141)

#### Expected behavior
Navigation to main Wallet view happens after deletion of Watch only account

#### Actual behavior

https://user-images.githubusercontent.com/8749671/122042211-87d33180-cde2-11eb-941a-52678cf44eb2.mov

### Reproduction

1) Open Status and create new account
2) Add `Watch only` wallet account (e.g. address `0xf37354771ec833c6bc0ec94d880da7c0a987981e`)
3) Open Watch only account -> `...` -> `Account settings` -> and tap `Delete account` -> Yes

### Additional Information

- Status version: nightly 0.14.0 (20210614120754)
- Operating System: Android and iOS

[comment]: # (Please, add logs/notes if necessary)

### LINKED ISSUE #12225: No PIN bar panel appears in e2e build when trying to add account in Wallet
# Bug Report

## Problem 
When I tap on 'Add account' button during the 'Add account' flow in Wallet the PIN bar bottom-sheet should appear. This is not the case in e2e builds which is blocker for some tests. 
NOTE: this PIN bar appears then if to reopen 'Add account' Wallet again. 
 
#### Expected behavior
 PIN bar panel appears in e2e build when trying to add account in Wallet
#### Actual behavior

https://user-images.githubusercontent.com/8749671/122084824-d5fc2b00-ce0a-11eb-9b3e-08def8ac4762.mov

### Reproduction

1) Open Status and create new Keycard account
2) Open Wallet view
3) `Add an account` -> `Generate account`
4) Tap `Add an account`

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### LINKED ISSUE #12236: Group chat view doesn't show incoming/outgoing messages after Inviting new member
# Bug Report

## Problem 
After new member has been invited into GroupChat, - then staying in the same GroupChat view(which is navigated to after new member invited), does not show any outgoing/incoming messages. 
If to "re-open" this Group Chat view (navigate back to Chats and again open GroupChat view) then all messages are visible fine.

#### Expected behavior
Group chat view shows incoming/outgoing messages after Inviting new member

#### Actual behavior
Group chat view doesn't show incoming/outgoing messages after Inviting new member

https://user-images.githubusercontent.com/8749671/122570347-582b6000-d054-11eb-90f0-9a7126ccf88e.mp4

### Reproduction

1) Create two new accounts: UserA and UserB
2) UserA adds UserB -> UserB confirms request of the new contact
3) UserA creates empty Group chat
4) UserA - Invites UserB into this GroupChat via `GroupChat Info` -> `Add members` -> select `UserB` and add him
4) UserA stays on Group Chat chat view now
5) UserB -> open GroupChat -> tap Join group -> send several messages in new group
6) UserA sends text messages
Actual result: no incoming (from UserB) messages are shown, no outgoing (by UserA) messages are shown

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by flexsurfer**
fixes: #12224
fixes: #12225
fixes: #12236

### CODE REVIEW

**Review by shivekkhurana — APPROVED** [review]

**Comment by churik** [comment]
@flexsurfer first issues (to be updated):

- [ ] **ISSUE 1:** White screen after navigation during back up seed phrase (keycard account creation) and to navigate to Enter seed phrase screen 

Easiest way to reproduce is to navigate to Access existing keys > Recover with seed phrase
Also reproducible during keycard account creation flow when backing up seed phrase, or if use "Lost or frozen keycard"
Mostly visible on **IOS**

https://user-images.githubusercontent.com/4557972/122747132-fa348d80-d28a-11eb-988d-c8af23b0ea9f.MP4

- [x] **ISSUE 2:** If enter wrong PIN during changing PIN code on IOS, validation message is not shown (need to tap back to see it) 

IOS only

https://user-images.githubusercontent.com/4557972/122749484-b2633580-d28d-11eb-86f2-595e5be6a318.mp4

- [x] **ISSUE 3:**  After reopening app kk login screen looks like screen with password (need to navigate back and select it from the list to get right screen)

https://user-images.githubusercontent.com/4557972/122749682-e76f8800-d28d-11eb-83cf-b9e0610299a7.mp4

- [x] **ISSUE 4:** "This is your signing phrase" popup is shown each time when navigating to wallet

(i.e. just by tapping on wallet tab or when adding account in wallet, or if you delete watch-only multiaccount in wallet)

- [x] **ISSUE 5:** Can't create channel inside community

'Not found' when tapping on "Create channel"

- [x] **ISSUE 6:** 2 close buttons on "Invite" screen in communities
IMAGE 2021-06-21 16:07:43

**Comment by flexsurfer** [comment]
ISSUE 1: unfortunatelly its a bug in RNN, we can try to fix it in separate issue

**Comment by flexsurfer** [comment]
thanks @churik , fixed 2-4

**Comment by churik** [comment]
added 5, 6 about communities

**Comment by flexsurfer** [comment]
thanks @churik , fixed

**Comment by Serhy** [comment]
**Issue 7**
No way to sign into account after force logout during Face ID set up from Profile (nothing happens when Sign In button is tapped on both iOS and Android and on iOS no way to enter anything in password field.

Reproduction:
1) Install latest build (https://status-im-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-210622-070745-43178d-pr12226-universal.apk / https://i.diawi.com/unZwUx )
2) Create new account
3) Open Profile -> Privacy&Security
4) Tap `Face ID` / `Fingerprint` toggle button
5) Try to login or interact with any element on Sign In view
**Actual result:**

https://user-images.githubusercontent.com/8749671/122904833-5e258780-d359-11eb-89d2-9b5fce5b9141.mov

**Comment by churik** [comment]
**Issue 8**
After scanning invalid QR scanner remains opened and can't scan new items.
Blocks test_can_scan_different_links_with_universal_qr_scanner e2e test.
Reproduction:
- scan QR with invalid chat key 
image
- Tap 'Ok' on error.
Expected that QR code view will be closed and you can start again.
In fact camera view remains opened and nothing happens in attempt to scan new QR

**Comment by flexsurfer** [comment]
Issue 8: fixed

**Comment by Serhy** [comment]
Retested all above issues on iOS and Android11 and can confirm they are fixed. Also #12236 and #12225 and #12224 are also fixed.

(**Issue 7** Enabling FaceID from Profile still present)

Another issue with communities:
`:nil is not ISeqable` error appears on tap 'Edit community' button
**Reproduction**:
1) Create new account
2) Create new community
3) Open this community -> `(+)` -> `...` -> `Community info`
4) Tap `Edit community` button
 
**Actual result:** 
Screenshot 2021-06-22 at 19 45 02

**Comment by flexsurfer** [comment]
thanks @Serhy fixed

**Comment by Serhy** [comment]
Looks good to me to proceed and merge with latest changes `3e50448`! There were minor issues were found which is fine to address in separate next PR, but this one is good for merge. Thanks @flexsurfer for fixes! And thanks @churik, @qoqobolo for help with testing

**Pull request merged**
