### PR TITLE
Reabstract Reanimated

### LINKED ISSUE #15176: Abstract Reanimated methods in a better way
The current abstraction of the reanimated module is using very long names. Some files need to use reanimated methods 10s of times, and this causes the code to start looking not so readable. A better abstraction of reanimated methods can fix this problem.

Also see this thread: https://github.com/status-im/status-mobile/pull/15078#discussion_r1105681500

### PR DESCRIPTION
**Pull request by OmarBasem**
fixes: https://github.com/status-im/status-mobile/issues/15176

#### Summay of Changes

- Import `Reanimeted` as `[react-native.reanimated :as ra]`
- Main hooks/helpers will be: `ra/use-val`, `ra/set-val`, `ra/get-val` (instead of `reanimated/use-shared-value`, etc)
- Simplify animation functions. The most used animation function `(reanimated/set-shared-value animation (reanimated/with-timing value)` will simply be `(ra/animate animation value))`. For other animation functions just add the animation name after `animate`. For example: `animate-spring`, `animate-decay`, `animate-delay`.
- Reduced number of function definitions by accepting a variable number of arguments. For example: `animate` can also accept a duration argument, and an easing argument. `(ra/animate animation value 1000))` / `(ra/animate animation value 1000 :linear))`

All of the above are suggestions based on these threads: https://github.com/status-im/status-mobile/pull/15078#discussion_r1105681500, https://github.com/status-im/status-mobile/pull/14897#discussion_r1122578277. Feel free to give your suggestions.

Here is how the [Reanimated file](https://github.com/status-im/status-mobile/blob/2fd9e80650e44f0939efa20cbba61384c4b90678/src/react_native/reanimated.cljs) would look.

### CODE REVIEW

**Review by flexsurfer — DISMISSED** [review]
honestly, for me, it reads worse than before, and there will be a problem for new joiners, so i would say this change introduces more inconvenience than convenience because we're used to reanimated ns and its methods (they are the same as in reanimated documentation), now we need to learn and remember new alias and method names, and what are we gonna do if we want to add more methods, everyone will come up with a new short name? sorry i'm against this change

**Comment by OmarBasem** [comment]
@flexsurfer what is happening now is that everyone is creating their own short names. This PR introduces short names to be one place, better than having to read and remember everyone's abstractions.

**Comment by flexsurfer** [comment]
> @flexsurfer what is happening now is that everyone is creating their own short names. This PR introduces short names to be one place, better than having to read and remember everyone's abstractions.

hm, i don't see many custom names in this PR, so probably it's better to just rename them , but its only my opinion, lets wait other team member who worked a lot with reanimated like @briansztamfater

**Comment by OmarBasem** [comment]
> hm, i don't see many custom names in this PR

@flexsurfer This PR renames the main methods of reanimated (and the custom names of lightbox as I have written them). I did not want to rename the custom names of other people in this PR to not cause much conflict.

**Review by ilmotta — COMMENTED** [review]
Thanks @OmarBasem. I did my fare share of analysis on your PR. I have some suggestions and I liked some of your decisions too. I can see you put a lot of thought into them.

So here it goes :wink: I hope you guys find it useful.

1. Shorten the namespace alias to be less readable to `ra`.

Given how ubiquitous animation is and will be in `status-mobile`, I'm fine with the new alias. Let's just remember that every non-obvious alias puts a burden on everybody, because people will need to memorize from where the namespace comes from. Hopefully this won't be a problem for `ra`. I'm already liking it ;)

2. Rename `set-shared-value` to `set-val`

Seems alright. Is there any other *type* of value that can be set? Or is always a shared value? If it's always a shared value, then I think the rename is good, because it removes a redundant word. I kind of like that `set-val` is perfectly aligned with `use-val` (same length).

3. About functions `animate-spring`, `animate-decay`, etc

I think we could be more consistent in how they're defined and called. For example, `animate-spring` receives a map at the end, but `animate-delay-repeat` receives 6 positional arguments. Reading calls to `animate-delay-repeat` is very confusing given the amount of args that sometimes are just numbers. Here's my suggestion that creates a more readable and consistent API.

Suggested API:

The first argument is always the animation instance, the second is some mandatory value, the third argument (optional for `animate-decay`) is a map of options. Notice how the function signatures are simpler and extensible without causing breaking changes. If new options are needed in our abstractions, nothing will break if we set good defaults.

```clojure
(defn animate-decay
  ([animation velocity]
   ...)
  ([animation velocity {:keys [clamp]}]
   ...))

(defn animate-delay
  ([animation val {:keys [delay duration easing]
                   :or   {duration default-duration
                          easing   :default}}]
   ...))

(defn animate-repeat
 ([animation val {:keys [reps reverse? duration easing]
                  :or   {reverse? false
                         duration default-duration
                         easing   :default}}]
  ...))

(defn animate-delay-repeat
  ([animation val {:keys [reverse? reps duration easing delay]
                   :or   {reverse? false}}]
   ...))
```

I think we end up with much more readable code too (code extracted from `src/quo2/components/messages/system_message.cljs`):

```clojure
;; Current
(ra/animate-delay
 sv-color
 (get-color :bg :default type)
 1000
 0
 :linear)

;; Suggestion
(ra/animate-delay
 sv-color
 (get-color :bg :default type)
 {:delay    1000
  :duration 0
  :easing   :linear})
```

Other points:

- I don't like the `apply-animations-to-style` name because hooks in React have a strong convention of starting with the prefix `use`, and `apply-animations-to-style` is a hook. I suggest just `ra/use-animated-style`, since the native hook `useAnimatedStyle` is never used by any other namespace (and it shouldn't). There's no confusion IMO, just like `rn/dispatch` has the same name as `re-frame.core/dispatch`.

- Right now we need to remember to carefully use camel case keywords when using animations. But all kebab case keywords could be transformed automatically to camel case, so we can stop having to worry about using camel case inside transforms and in other places. We have the library `camel-snake-kebab` precisely for this kind of job. A future iteration of these abstractions could solve this problem once and for all. I'm not suggesting this change in this PR because it would require a lot more changes in the rest of the code.

**Comment by Parveshdhull** [comment]
> Right now we need to remember to carefully use camel case keywords when using animations

Hi @ilmotta, Please can you elaborate on this?

**Comment by Parveshdhull** [comment]
> > Right now we need to remember to carefully use camel case keywords when using animations
> 
> Hi @ilmotta, Please can you elaborate on this?

Are you still facing issue with camelCase (I think it was fixed in https://github.com/status-im/status-mobile/pull/14855)
PS: we were using `camel-snake-kebab` before fix

**Comment by ilmotta** [comment]
> > > Right now we need to remember to carefully use camel case keywords when using animations
> > 
> > 
> > Hi @ilmotta, Please can you elaborate on this?
> 
> Are you still facing issue with camelCase (I think it was fixed in #14855) PS: we were using `camel-snake-kebab` before fix

@Parveshdhull, I think most of the time I see the transforms map keys need to be camel case, like this https://github.com/status-im/status-mobile/blob/develop/src/status_im2/common/scroll_page/style.cljs#L17. `interpolate` calls sometimes, here's an example https://github.com/status-im/status-mobile/blob/develop/src/status_im2/common/scroll_page/view.cljs#L45.

**Comment by Parveshdhull** [comment]
Maybe this is old code, or developer choose to directly pass camelCase key, but I think kebab-case should also work here

**Comment by Parveshdhull** [comment]
> Maybe this is old code, or developer choose to directly pass camelCase key, but I think kebab-case should also work here

In case of transform. (interpolate I didn't checked how it is implemented, maybe @briansztamfater will know more)

**Comment by ilmotta** [comment]
> > Maybe this is old code, or developer choose to directly pass camelCase key, but I think kebab-case should also work here
> 
> In case of transform. (interpolate I didn't checked how it is implemented, maybe @briansztamfater will know more)

Unfortunately it's not gonna work @Parveshdhull. The implementation of `reanimated/interpolate` uses `clj->js` for the extrapolation, and this won't cover the conversion between kebab to camel. The function `interpolateValue` just receives the `#js` map and passes directly to the worklet for `react-native-reanimated`, so I don't see how any of this is converting kebab keywords.

The same goes for transforms. `apply-animations-to-style` calls `clj->js` on the `animations` argument, so it won't convert a map from kebab to camel case. That's why we pass `animations` such as `{:transform [{:translateY translate-y}]}`. I couldn't find a single exception in the code, so I think it's not a matter of old/new code.

**Comment by Parveshdhull** [comment]
> The same goes for transforms. apply-animations-to-style calls clj->js on the animations argument, so it won't convert a map from kebab to camel case. That's why we pass animations such as {:transform [{:translateY translate-y}]}. I couldn't find a single exception in the code, so I think it's not a matter of old/new code.

**Image updated with translate**
image

**Comment by ilmotta** [comment]
> > The same goes for transforms. apply-animations-to-style calls clj->js on the animations argument, so it won't convert a map from kebab to camel case. That's why we pass animations such as {:transform [{:translateY translate-y}]}. I couldn't find a single exception in the code, so I think it's not a matter of old/new code.
> 
> **Image updated with translate** image

I see now, the worklet_factory namespace does the conversion. This is the line for reference https://github.com/status-im/status-mobile/blob/develop/src/js/worklet_factory.js#L51

**Comment by ilmotta** [comment]
So to summarize what we've been discussing @Parveshdhull to help anybody else.

- Worklet `applyAnimationsToStyle` does the manual conversion between kebab to camel case (reference https://github.com/status-im/status-mobile/blob/develop/src/js/worklet_factory.js#L51). It seems to work well enough and if it runs outside the main thread it should be even better than using the kebab library *before* calling it.
- Worklet `interpolateValue` does not work with kebab case keywords because there's no conversion happening on the `interpolateValue` function, nor in the CLJS `reanimated/interpolate` function.

So in the end, it seems that we could make things more consistent by making `interpolateValue` also understand kebab case keywords. Another useful work would be to rename all existing camel case keywords to kebab when calling `apply-animations-to-style`.

**Comment by OmarBasem** [comment]
Thanks for your extensive input @ilmotta.

> Hopefully this won't be a problem for ra. I'm already liking it ;)

Glad you are liking it :)

> Is there any other type of value that can be set?

Always shared value

> About functions animate-spring, animate-decay, etc

I generally like maps for multiple args, but again here using a map would increase the length of calling the function :)


Let's also see what @briansztamfater thinks

**Comment by briansztamfater** [comment]
Hi team, I read all the opinions here. Honestly I liked `set-val` / `get-val` / `use-val` because of its shortness. Regarding the namespace alias as `ra` I think it's fine, but I don't know if we defined some alias for `re-agent` that may collapse. I think `re-agent` has the alias priority if we decide to shorten it too :).

Also I see and understand what @flexsurfer mentions about that changing function names to something different as the original reanimated API may create confusions to newcomers or people using reanimated in our codebase for the first time. So maybe we can divide namespace into `react-native.reanimated` for mapping original functions and `helpers.reanimated` or `utils.reanimated` for functions that helps us to write code faster and DRY.

**Comment by briansztamfater** [comment]
> * I don't like the `apply-animations-to-style` name because hooks in React have a strong convention of starting with the prefix `use`, and `apply-animations-to-style` is a hook. I suggest just `ra/use-animated-style`, since the native hook `useAnimatedStyle` is never used by any other namespace (and it shouldn't). There's no confusion IMO, just like `rn/dispatch` has the same name as `re-frame.core/dispatch`.

I know it's a hook and `use-` prefix should prevail here (it has better arguments than what I am going to propose next 😄), but when I read a style definition with animation I feel the function it is just merging "animated style" with "normal style", so what about `merge-animated-style` or `merge-style`?

#### Current version
```
(defn sticky-header-title
  [animation]
  (reanimated/apply-animations-to-style
   {:opacity animation}
   {:position       :absolute
    :flex-direction :row
    :left           64
    :top            16
    :margin-top     44}))
```

#### With `use- `prefix and `ra` namespace alias
```
(defn sticky-header-title
  [animation]
  (ra/use-animated-style
   {:opacity animation}
   {:position       :absolute
    :flex-direction :row
    :left           64
    :top            16
    :margin-top     44}))
```

#### With `merge-` and `ra` namespace alias
```
(defn sticky-header-title
  [animation]
  (ra/merge-animated-style
   {:opacity animation}
   {:position       :absolute
    :flex-direction :row
    :left           64
    :top            16
    :margin-top     44}))
```
or
```
(defn sticky-header-title
  [animation]
  (ra/merge-style
   {:opacity animation}
   {:position       :absolute
    :flex-direction :row
    :left           64
    :top            16
    :margin-top     44}))
```

I feel the last one is more understandable for newcomers, but not respecting the hook convention nor the original API, so in my proposal it should be in the new utils namespace.

**Comment by ilmotta** [comment]
Good points @briansztamfater, and thanks for reading all the stuff!

>  I think re-agent has the alias priority if we decide to shorten it too :).

In general I think we alias `reagent.core` as `reagent`, so it shouldn't conflict with the reanimated `ra` alias. We will probably add one line to `.clj-kondo/config.edn` to make the reagent alias mandatory as `reagent` and the reanimated alias mandatory as `ra`. This is already used to make sure, for instance, that `clojure.string` is aliased as `string`. Quite useful!

One open point we were waiting for your opinion is about the `animate-*` signatures. Could you please see this comment I made? https://github.com/status-im/status-mobile/pull/15275#pullrequestreview-1328162626 You probably have a different perspective to bring. You can help us break-even :wink: 

> I feel the last one is more understandable for newcomers, but not respecting the hook convention nor the original API, so in my proposal it should be in the new utils namespace.

:+1:  I agree that your very last suggestion is understandable while being concise. I'm sold to be honest!

I like your suggestion to use `merge-style`. I can totally live without the hook name convention ;) I also like your suggestion to drop the `animated` word. Reads better IMO because it's redundant for a var defined in a namespace meant for animations.

> Also I see and understand what @flexsurfer mentions about that changing function names to something different as the original reanimated API may create confusions to newcomers or people using reanimated in our codebase for the first time.

I don't agree much on this one Brian. I don't quite understand why the evolution of the reanimated namespace is being treated differently than all the other RN namespaces we already have, or any other namespace for that matter. To me, the suggestions in this issue are very subtle, sensible, and a natural evolution for devs writing more animation code. I just like the direction we're going :) It's rare that we have deeper discussions around APIs.

Has any newcomer shared specific feedback about the reanimated abstractions that they find confusing?

>  So maybe we can divide namespace into react-native.reanimated for mapping original functions and helpers.reanimated or utils.reanimated for functions that helps us to write code faster and DRY.

If we follow your suggestion, then it means all functions defined in `src/react_native/` should be just wrappers, and all the RN Status abstractions would need to be refactored out into utility namespaces. Is that what you meant? To be consistent (which we should of course), we would then need to refactor the flat list component, section-list, the entire audio toolkit namespace, among others, into wrappers + utilities namespaces. To me, this surely sounds more confusing for newcomers (also to me personally). Also a bunch more refactoring work to be done by core members.

I don't quite follow the points about writing code faster and DRY. Are the abstractions being suggested in this issue going to hinder our ability to write DRY code or slow us down?

**Comment by briansztamfater** [comment]
> In general I think we alias `reagent.core` as `reagent`, so it shouldn't conflict with the reanimated `ra` alias. We will probably add one line to `.clj-kondo/config.edn` to make the reagent alias mandatory as `reagent` and the reanimated alias mandatory as `ra`. This is already used to make sure, for instance, that `clojure.string` is aliased as `string`. Quite useful!

Say no more, I am okay with `ra` then :)

> One open point we were waiting for your opinion is about the `animate-*` signatures. Could you please see this comment I made? [#15275 (review)](https://github.com/status-im/status-mobile/pull/15275#pullrequestreview-1328162626) You probably have a different perspective to bring. You can help us break-even 😉

Sorry I forgot to mention on this one. I agree with your suggestions, with maps for options and default values. I think it is the cleaner solution.

> I like your suggestion to use `merge-style`. I can totally live without the hook name convention ;) I also like your suggestion to drop the `animated` word. Reads better IMO because it's redundant for a var defined in a namespace meant for animations.

Yay! Yes, I felt it reduntant as it comes from the reanimated namespace. My preferred option is `merge-style`, what do other people think about this one? @OmarBasem @Parveshdhull @flexsurfer 

> I don't agree much on this one Brian. I don't quite understand why the evolution of the reanimated namespace is being treated differently than all the other RN namespaces we already have, or any other namespace for that matter. To me, the suggestions in this issue are very subtle, sensible, and a natural evolution for devs writing more animation code. I just like the direction we're going :) It's rare that we have deeper discussions around APIs.
 
> Has any newcomer shared specific feedback about the reanimated abstractions that they find confusing?
> 
> > So maybe we can divide namespace into react-native.reanimated for mapping original functions and helpers.reanimated or utils.reanimated for functions that helps us to write code faster and DRY.

> If we follow your suggestion, then it means all functions defined in `src/react_native/` should be just wrappers, and all the RN Status abstractions would need to be refactored out into utility namespaces. Is that what you meant? To be consistent (which we should of course), we would then need to refactor the flat list component, section-list, the entire audio toolkit namespace, among others, into wrappers + utilities namespaces. To me, this surely sounds more confusing for newcomers (also to me personally). Also a bunch more refactoring work to be done by core members.
> 
> I don't quite follow the points about writing code faster and DRY. Are the abstractions being suggested in this issue going to hinder our ability to write DRY code or slow us down?

Maybe I didn't express myself well, but what I actually meant is that I understand @flexsurfer's concerns and as we are writing functions to help us write better understandable code, maybe place those in a helpers or utils namespace. Personally, I don't have a strong opinion on this one, I am just trying to provide some alternative and also just speculating on the newcomers learning curve of this part of the codebase, mainly because I think usually devs will first try to understand Reanimated by reading the official documentation and then learn how are implemented in our codebase. Said that, I think that your arguments makes lot of sense and actually kinda convinced me to keep going in this direction. We have lots of examples in our codebase for newcomers to learn from, by the way :)

**Comment by flexsurfer** [comment]
what i would like to hear, is WHY? why we want these changes, i mean i don't have any issues with current fullnames, we all work with modern IDEs so we have quick suggestions, we don't need to type long names, my brain adopt them, i can read them fast, but i can't say the same for ra/set-value this is something alien, probably I get use to it  , but idk, so i would say if ppl feel like it will improve somehow their performance im fine with that

**Comment by Parveshdhull** [comment]
> what i would like to hear, is WHY? why we want these changes, i mean i don't have any issues with current fullnames, we all work with modern IDEs so we have quick suggestions, we don't need to type long names, my brain adopt them, i can read them fast, but i can't say the same for ra/set-value this is something alien, probably I get use to it , but idk, so i would say if ppl feel like it will improve somehow their performance im fine with that

Same goes for me, I also don't see any value in this. But I already shared my opinions in Zoomable PR [thread](https://github.com/status-im/status-mobile/pull/15078#discussion_r1118620551), don't see any benefit in repeating them.

**Comment by ilmotta** [comment]
> what i would like to hear, is WHY? why we want these changes, i mean i don't have any issues with current fullnames, we all work with modern IDEs so we have quick suggestions, we don't need to type long names, my brain adopt them, i can read them fast, but i can't say the same for ra/set-value this is something alien, probably I get use to it , but idk, so i would say if ppl feel like it will improve somehow their performance im fine with that

@flexsurfer, @Parveshdhull The *why* is clear. We've seen in recent PRs with lots of animation code that contributors felt the need to create local namespace abstractions to avoid messing with the reanimated namespace. This is more than enough reason to justify the discussions taking place here and the evolution of the API (if we ever agree on something). Saying that there's no point in having these discussions seems a bit too rigid to me.

I like to question myself, if there was a ClojureScript library available to talk to Reanimated, how would it look like? How would the API be? How can we create something that perhaps resembles this fictional library? Can our abstractions on top of Reanimated eventually become useful to the Clojure community? Etc etc. I'm not saying we should create internal libs, but I do think we should exercise our freedom to create the best abstractions that we can.

> Same goes for me, I also don't see any value in this. But I already shared my opinions in Zoomable PR https://github.com/status-im/status-mobile/pull/15078#discussion_r1118620551, don't see any benefit in repeating them.

@Parveshdhull, This issue is focusing on more than just reducing character count, which was mostly the discussion on that thread. @briansztamfater, @OmarBasem and I shared some ideas about evolving the API, and it'd be helpful to get more inputs. If I may copy you here, in that thread you said *If use-val, set-val, and animated are all understable then sounds awesome, I am all in for these changes.*, so perhaps there are indeed things you agree can be improved?

But you know, I think this whole discussion is detracting us from the real value of thinking about how our animation abstractions could be. I wish I could hear more ideas, but unfortunately we don't yet have that many people writing animation code.

**Comment by ilmotta** [comment]
>Personally, I don't have a strong opinion on this one, I am just trying to provide some alternative and also just speculating on the newcomers learning curve of this part of the codebase, mainly because I think usually devs will first try to understand Reanimated by reading the official documentation and then learn how are implemented in our codebase

Yeah @briansztamfater, you're right. That's also what I did, I went for the official docs first, understood the Javascript code, and then tried to play with the existing reanimated namespace in `status-mobile`. But one interesting thing, even with the custom abstractions, it didn't matter much because in the REPL I could always play with the RN namespace imports and ignore our custom code.

It's rather beautiful, just add a `comment` macro and start playing with Reanimated! Once I got the hang of the basics in the REPL, then our abstractions made a lot more sense. Probably each person would learn differently, but just trying to share my experience so far :)

**Comment by Parveshdhull** [comment]
> [@flexsurfer](https://github.com/flexsurfer), [@Parveshdhull](https://github.com/Parveshdhull) The why is clear. We've seen in recent PRs with lots of animation code that contributors felt the need to create local namespace abstractions to avoid messing with the reanimated namespace.

If some developers are not following existing coding patterns and doing things differently.
We should request them to not do that. Instead of changing the code to make it the same as theirs.
I don't know if creating new problems to solve old ones is the right approach.

> If I may copy you here, in that thread you said If use-val, set-val, and animated are all understable then sounds awesome, I am all in for these changes?

There is a *if* in the sentence, and I also mentioned that we should not compromise the understandability for the short names.

`ra/use-val` vs `reanimated/use-shared-value`

Anyone who has checked reanimated docs can understand the second code. It's pretty clear that from reanimated we are using hook `useSharedValue`. And for the first case, we have to check what `ra` means, and what `use-val` referring here.

> Same goes for me, I also don't see any value in this

This is only my opinion. Maybe I will find `ra` and `set-val` all useful.
And will learn to use them, I am just sharing what I think of the changes now.

PS: Discussion starting to run in the circle so that's all for me, don't think I have anything more to add.

**Comment by flexsurfer** [comment]
> If some developers are not following existing coding patterns and doing things differently.
> We should request them to not do that. Instead of changing the code to make it the same as theirs.
> I don't know if creating new problems to solve old ones is the right approach.

good point, agree

**Comment by flexsurfer** [comment]
btw I see this not the first time, when we're wasting time protecting and dissing something just focusing on the implementation itself and not on the root of the problem

so for cases like this one, i would say , first, we should fix the code according to current guidelines, then create a discussion and after consensus, we could create a PR

**Comment by OmarBasem** [comment]
@flexsurfer the below file is a reanimated heavy file showing before and after changes. If you still think it doesn't improve the readability, then I will close this PR.

[File with longer names](https://github.com/status-im/status-mobile/blob/702b8b5d9f1d4019108fa0cd9c9a5d5c14e0fcb4/src/status_im2/contexts/chat/lightbox/zoomable_image/view.cljs)

[File after reabstraction](https://github.com/status-im/status-mobile/blob/2fd9e80650e44f0939efa20cbba61384c4b90678/src/status_im2/contexts/chat/lightbox/zoomable_image/view.cljs)

**Comment by Parveshdhull** [comment]
(Just adding for the context, before comparing files.)
We rarely going to set several shared values at a single time as done in the file.
The code in the file needs to be reimplemented properly with the help of derived values. [related conversation](https://github.com/status-im/status-mobile/pull/15175#discussion_r1119881215)

**Comment by ilmotta** [comment]
> btw I see this not the first time, when we're wasting time protecting and dissing something just focusing on the implementation itself and not on the root of the problem

@flexsurfer There were PRs raising concerns and some fruitful discussions. Some people showed openness (not just me) and this encouraged @OmarBasem to create this issue. @briansztamfater and I jumped in to also discuss interesting improvements to the API (or so we thought), which nobody commented on (only Omar himself).

Every little change suggested in this issue causes a very sharp and defensive response from you and @Parveshdhull, which to me means the Reanimated API was never open for improvements from the start.

I'm sorry to cause any waste of time, this was not my intention, but I'll move on to other issues for the moment.

**Comment by flexsurfer** [comment]
ok as @briansztamfater and @OmarBasem have worked on most complex animation i leave this PR for them, feel free to approve and merge, i won't block this PR

**Comment by flexsurfer** [comment]
if we don't like it we can easily rollback it later ;)

**Comment by OmarBasem** [comment]
> We rarely going to set several shared values at a single time as done in the file.

The values in that file are highly independent. I am not sure about using derived values for these animations, but I will give it a try: https://github.com/status-im/status-mobile/issues/15303

**Comment by flexsurfer** [comment]
hey @OmarBasem still relevant?

**Pull request closed without merging**
