### PR TITLE
Disable external bots #3813

### LINKED ISSUE #3813: Disable external bots
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a developer, I want to disable unused features that might introduce a security risk. External bots is one of them.

### Description

*Type*: Bug

Disable the ability to execute external bots. This is done by removing the `debug` command available in the console.

### PR DESCRIPTION
**Pull request by debragail**
fixes #3813

Removed debug functions from bots.cljs

external bot for debugging was removed.

### CODE REVIEW

**Comment by jeluard** [comment]
@alwx @rasom Anything we could remove clojure side too?

**Comment by rasom** [comment]
@jeluard we also have server on native side which allows us to upload bot.js afaik, though @alwx should know better

**Comment by jeluard** [comment]
@rasom Ok, I guess that should be another issue then.

**Review by jeluard — APPROVED** [review]

**Review by rasom — APPROVED** [review]

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/Da4ean for branch PR-4113

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/X9tKL7 for branch PR-4113

<blockquote><div><strong><a href="https://i.diawi.com/X9tKL7">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/4ggucE for branch PR-4113

<blockquote><div><strong><a href="https://i.diawi.com/4ggucE">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/JgPrqb for branch PR-4113

<blockquote><div><strong><a href="https://i.diawi.com/JgPrqb">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Pull request merged**
