### PR TITLE
request camera permissions from webview #3003

### LINKED ISSUE #3003: Add media API support for DApps
### User Story

As a developper, I want to be able to leverage all web technologies in my DApp.

### Description

Some web API usages require user permission (usually some popup a user has to confirm).
Those API should be available to DApps authors.

As we already asks specific user permission (e.g. camera) it would be great to reuse those and not asks for already granted permission.

At least media permissions should be working and the following site should be usable: https://davidwalsh.name/demo/camera.php

*Type*: Feature

### PR DESCRIPTION
**Pull request by rasom**
resolves #3003

status: ready

### CODE REVIEW

**Comment by rasom** [comment]
https://github.com/status-im/react-native-webview-bridge/pull/11

**Comment by grishick** [comment]
@rasom judging by the changes this is supposed to work only on Android. Am I understanding this correctly?

**Comment by rasom** [comment]
@grishick correct

**Review by flexsurfer — APPROVED** [review]

**Review by janherich — APPROVED** [review]

**Comment by jeluard** [comment]
@rasom Can you resolve conflicts?

**Comment by yenda** [comment]
@asemiankevich Why is it tested ok is it fixed ? I don't see any changes since last time it had to be reverted

**Comment by asemiankevich** [comment]
@yenda I have checked the following build for android:

Branch: PR-3354
Android: https://i.diawi.com/7DmGLP
iOS: https://i.diawi.com/6cLxnB

And I was asked for camera permissions when visiting https://davidwalsh.name/demo/camera.php via Status app.
I have tried different scenarios around the described one. 

What is wrong with this? i dont see why it should be reverted either

**Comment by yenda** [comment]
@asemiankevich my bad I confused this PR with the one for camera :D

**Comment by asemiankevich** [comment]
oh that one is still pending

**Pull request merged**
