### PR TITLE
cache processed description

### PR DESCRIPTION
**Pull request by cammellos**
Optimization to fix:

https://github.com/status-im/status-mobile/issues/19042

it caches the decrypted description & add indexes to hash ratchet keys database:

https://github.com/status-im/status-go/pull/4891/files

### CODE REVIEW

**Comment by pavloburykh** [comment]
@cammellos first of all this is amazing work, thank you! Now it really works really much faster. Please, have a look at the issue

### ISSUE 1 Token gated channels appear to be as non token gated for some time after relogin

Example of community with tg channels on Sepolia https://status.app/c/G3cAAMSwbYgnSdBu0Eh4SIxOiP-4O8YJ0JstMtLA1zJsjK1juKWoPZqx1C9eC46yIwvOejOLeZ3hqKKZ7rMDZ0V5kObC9EDAhKigGfQMSv31U423I1ONfnHnOH6Lc2Q3jlI_yz1e520=#zQ3shsZrnG5NUTTbmdrA6RJEX7d1Y7EzRVQsd4CFmZpzHCG83


**Steps:** 

1. Join given community (make sure Sepolia network is enabled on your account) 
2. See if tg channels are locked in case you are not eligible to View and Post. 
3. Perform relogin and check if channels are still locked

**Actual result:** 

Before joining the community token gated channels are displayed as non token gated (without lock, user can enter them).  Channels are displayed as token-gated after joining the community. After relogin tg channels again appear as non token gated for some time. During this time user can enter channels and post messages even if he is not eligible to do that. Sometimes user gets an error but most of the time messages go through and are delivered into channel. After some time channels become token gated until the next relogin.  See video attached.

[Status-debug-logs - 2024-03-08T231423.647.zip](https://github.com/status-im/status-mobile/files/14543222/Status-debug-logs.-.2024-03-08T231423.647.zip)


https://github.com/status-im/status-mobile/assets/97245802/ec79e564-fe02-416f-a01c-a79222c18495


**Screenshot of channels permissions:**
Status Desktop 2024-03-08 23-04-55

**Comment by cammellos** [comment]
@pavloburykh I am not sure mobile is implementing it correctly. First it checks for permissions client side, which it should not, it should trust the owner and `can-post?` etc flags. I will remove those checks. 
Also, we should show the lock icon if the channel is token gated, not whether you can access it (if you can't access it, we should not show the channel at all I believe).
I'll have a look at this issues and clarify with product, but seems like we are not implementing it correctly.

**Comment by cammellos** [comment]
Correction to the above, I didn't see the distinction between locked/unlocked icon (really hard to spot to be honest).
1) Channel is token gated and you don't have access. -> lock icon
2) Channel is token gated, you have access -> unlocked icon
3) Channel is not token gated -> no icon.

It should work ok now. I have trouble with some permissions, they just seem to be ignored (especially view only), but I believe that's a problem with status-go and should be addressed separately, so I would only test with view & post for now.

**Comment by pavloburykh** [comment]
> It should work ok now. I have trouble with some permissions, they just seem to be ignored (especially view only), but I believe that's a problem with status-go and should be addressed separately, so I would only test with view & post for now.

@cammellos unfortunately [ISSUE 1](https://github.com/status-im/status-mobile/pull/19153#issuecomment-1986432562) is still reproducible. 

On video below you can see the following:

1. TG channels are displayed as locked prior to joining the community
2. After joining community tg channels become unlocked and user is able to view and post messages despite he is not eligible to do that. 

[Status-debug-logs - 2024-03-11T101558.561.zip](https://github.com/status-im/status-mobile/files/14555464/Status-debug-logs.-.2024-03-11T101558.561.zip)

https://status.app/c/G3cAAMSIbSLexOIfNJtYSLv1hYiIOcYJ0JstMtLA1zJsjK1juKUobZLcpTteC464CDvM6aD8276Fo4qsWecCnBXxFGYLpgcCJkQFzaBnUNKjbFLsRdikKDt3jum0WJt3Xs_P7ftzae16Aw==#zQ3shsZrnG5NUTTbmdrA6RJEX7d1Y7EzRVQsd4CFmZpzHCG83 

https://github.com/status-im/status-mobile/assets/97245802/652b84e0-d6bd-4199-9e17-96e1b19d2eef

Status Desktop 2024-03-11 10-19-18

**Comment by pavloburykh** [comment]
@cammellos thank you for the fix! Ready for merge.

**Review by flexsurfer — APPROVED** [review]

**Comment by pavloburykh** [comment]
@cammellos e2e are okay, ready for merge

**Pull request merged**
