### PR TITLE
[#7445] Sticker detail view in chat

### LINKED ISSUE #7445: Sticker detail view in chat
Open stickers pack modal window on pressing sticker in chat

### PR DESCRIPTION
**Pull request by flexsurfer**
fixes #7445

### CODE REVIEW

**Review by jeluard — APPROVED** [review]

**Comment by jeluard** [comment]
@flexsurfer Can you rebase your PR? :)

**Comment by jeluard** [comment]
@flexsurfer Hmm need to rebase again !?

**Comment by jeluard** [comment]
@dmitryn @goranjovic Please review :)

**Review by dmitryn — APPROVED** [review]

**Comment by asemiankevich** [comment]
@flexsurfer could you please provide some details and rebase too? i have this annoying

image

which was fixed yesterday.
Thanks!

**Comment by flexsurfer** [comment]
@asemiankevich done! it just opens sticker pack modal window when you press on sticker in chat

**Comment by asemiankevich** [comment]
@errorists please review
image

**Comment by errorists** [comment]
on my dumb iPhone it's ok, the above Android screenshot is what worries me :D have we tested the Sticker Market designs on Android? Looking at it, looks like the toolbar has a hardcoded value for the system status bar or it's just too high, the icon isn't centered, the part where the divider/shadow is shown should appear at the very bottom of the toolbar - so below the thumbnail and author and not above them, i can't tell why the title is grey and not black and it reminded me we're still not using our Inter UI font on Android, only iOS xD

**Comment by asemiankevich** [comment]
@flexsurfer lets make it in separate issue, what do you think?

**Comment by flexsurfer** [comment]
@asemiankevich agree, let's merge this one

**Pull request merged**
