### PR TITLE
Improved new chat UI

### PR DESCRIPTION
**Pull request by flexsurfer**
Do not show "Contacts" label if there are no contacts and separate scan button

image

### CODE REVIEW

**Review by goranjovic — APPROVED** [review]

**Review by yenda — APPROVED** [review]

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/BLWmTW for branch PR-4553

<blockquote><div><strong><a href="https://i.diawi.com/BLWmTW">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/4jNfss for branch PR-4553

<blockquote><div><strong><a href="https://i.diawi.com/4jNfss">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by antdanchenko** [comment]
Please, see `test_public_chat_management` and  `test_public_chat` 
It's no longer possible to create a public chat, since there is no chat name input on the screen 

0013screenshot

**Comment by flexsurfer** [comment]
thanks @antdanchenko fixed

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/Z93FTo for branch PR-4553

<blockquote><div><strong><a href="https://i.diawi.com/Z93FTo">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/EpVRQe for branch PR-4553

<blockquote><div><strong><a href="https://i.diawi.com/EpVRQe">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Review by jeluard — APPROVED** [review]

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/Kro4Sm for branch PR-4553

<blockquote><div><strong><a href="https://i.diawi.com/Kro4Sm">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/vyjFE7 for branch PR-4553

<blockquote><div><strong><a href="https://i.diawi.com/vyjFE7">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Pull request merged**
