### PR TITLE
Track collectible events in MixPanel [#4799]

### LINKED ISSUE #4799: Track collectible events in MixPanel
### User Story

I'd like to know how many times the collectibles feature is being opened so that I can understand its success.

### Description

*Type*: Feature

*Summary*: Track the following taps on collectibles: 1) collections, 2) individual collectibles, and 3) "View in..." links.

#### Expected behavior
Data is available in MixPanel. 

tap / Wallet / Tap "Open collection"
tap / Wallet: Collectibles / Tap "Open collectible"
tap / Wallet: Collectibles: Collectible / Tap "View in browser"

https://docs.google.com/spreadsheets/d/1wV9CPA1hgTBVHg0bjT2C-ixsRSZGXmeejYluN9yuu2Y/edit#gid=0

<blockquote><div><strong><a href="https://docs.google.com/spreadsheets/d/1wV9CPA1hgTBVHg0bjT2C-ixsRSZGXmeejYluN9yuu2Y/edit#gid=0">Google Sheets - create and edit spreadsheets online, for free.</a></strong></div><div>Create a new spreadsheet and edit with others at the same time -- from your computer, phone or tablet. Get stuff done with or without an internet connection. Use Sheets to edit Excel files. Free from Google.</div></blockquote>

### PR DESCRIPTION
**Pull request by flexsurfer**
fixes #4799

### CODE REVIEW

**Review by jeluard — APPROVED** [review]

**Review by rachelhamlin — APPROVED** [review]

**Comment by flexsurfer** [comment]
@asemiankevich @Serhy ready to test

**Comment by Serhy** [comment]
Hey @flexsurfer. Something is not right it seems to me. 
Above latest builds (https://i.diawi.com/JSMACg and https://i.diawi.com/UfQcKT) tested on Android and iOS. There are no `display-collectible` and `open-collectible-in-browser` events in Mixpanel.
Also, I don't see that any of events reflected in logs (while another Mixpanel tracking tap are visible)

Here is TF session for Android:
https://app.testfairy.com/projects/4803622-status/builds/8513358/sessions/4395420686/?accessToken=STQVs9fUdnM3I2xx5PbRO/hc47g

So
1) tap on any of CryptoKitties/CryptoStrikers/Ethermon from Wallet main screen does not send a display-collectible event in Mixpanel
2) Opening any of collectable in browser view from Wallet (`Wallet -> `CryptoKitties` -> `View in CryptoKitties`) - does not send an `open-collectible-in-browser` tap even to Mixpanel (Note: however, in that case, we log an `open-existing-dapp` tap event)

<blockquote><div><strong><a href="https://i.diawi.com/JSMACg">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>
<blockquote><div><strong><a href="https://i.diawi.com/UfQcKT">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>
<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803622-status/builds/8513358/sessions/4395420686/?accessToken=STQVs9fUdnM3I2xx5PbRO/hc47g">TestFairy: Status 0.9.21 (6152) @2018</a></strong></div></blockquote>

**Comment by flexsurfer** [comment]
thanks @Serhy fixed

**Comment by asemiankevich** [comment]
`collectible-list` and `open-collectible-in-browser` are in Mixpanel now when i:
- open collectible from wallet screen
- open an asset by tapping `view in browser`

Looks good to me now. Thanks @flexsurfer

**Pull request merged**
