### PR TITLE
[ISSUE #4197] Added airswap.io to DApps

### LINKED ISSUE #4197: Add AirSwap Dapp to dapps list in Status
### Description

*Type*: Feature

*Summary*: i want AirSwap dapp https://www.airswap.io/ to be listed in the status dapps list as this dapp is really amazing and works 

https://github.com/airswap

#### Expected behavior

AirSwap dapp is listed in the dapps list

### Reproduction
- Open Status
- Tap plus button
- Tap Open DApp

### PR DESCRIPTION
**Pull request by jeluard**
fixes #4197 

### Summary:

Added airswap to DApps

status: ready

### CODE REVIEW

**Review by janherich — APPROVED** [review]

**Review by dmitryn — APPROVED** [review]

**Comment by dmitryn** [comment]
@jeluard maybe it makes sense to point user directly to trading app url https://www.airswap.io/trade

<blockquote></blockquote>

**Comment by jeluard** [comment]
@dmitryn Probably. @asemiankevich WDYT?

**Comment by asemiankevich** [comment]
@dmitryn @jeluard agree

**Comment by jeluard** [comment]
@asemiankevich Updated

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/mCw9cU for branch PR-4217

<blockquote><div><strong><a href="https://i.diawi.com/mCw9cU">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/38bYsS for branch PR-4217

<blockquote><div><strong><a href="https://i.diawi.com/38bYsS">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Review by flexsurfer — APPROVED** [review]

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/HEAwV6 for branch PR-4217

<blockquote><div><strong><a href="https://i.diawi.com/HEAwV6">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/u7yPMr for branch PR-4217

<blockquote><div><strong><a href="https://i.diawi.com/u7yPMr">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Pull request merged**
