### PR TITLE
Add pairing docs link, disable pfs toggle in release

### PR DESCRIPTION
**Pull request by cammellos**
Add links to the docs, disable pfs toggle in release and change settings for contact recovery.

Disables as well pairing pop up in e2e tests as it interferes with automate tests.

Currently link points to https://status.im/tutorials/pairing.html which returns a 404, still waiting for one PR to be merged and then to be deployed.

You can check provisional content at https://dev.status.im/tutorials/pairing.html

status: ready

### CODE REVIEW

**Review by jeluard — APPROVED** [review]

**Review by pedropombeiro — APPROVED** [review]
lgtm

**Review by mandrigin — APPROVED** [review]

**Comment by annadanchenko** [comment]
@cammellos there is iOs build in progress, so I'm starting with manual test on Android now

**Comment by annadanchenko** [comment]
@cammellos pfs toggle should be disabled only in release builds, right? I see it's enabled in PR build

**Comment by cammellos** [comment]
@annadanchenko correct, disabled only in release build, so it's a bit hard to test

**Comment by mandrigin** [comment]
@annadanchenko I see PFS toggle is visible in every build except release. Is that what you expect?

**Comment by annadanchenko** [comment]
@cammellos can you elaborate on " change settings for contact recovery", please? In what way it was changed?

**Comment by cammellos** [comment]
@mandrigin correct, release should not be have the pfs toggle
@annadanchenko I shortened the time for which we respond to a message, but it should not have any impact on testing.

To test it still works correctly you could do something like:
1) Create user A & B
2) Create a group chat in A & B, exchange messages
3) Re-install and recover on device A, wait for messages to be fetched
4) Send a message from B in the group chat, this message should be received by A (if it fetched old messages from the mailserver, otherwise the next message sent from B will be visible)

**Comment by annadanchenko** [comment]
this is how link "Learn more" looks like on Android mobile

screenshot_20190130-151723

and on windows desktop
learn more


maybe we can get some UI suggestions to improve it? @errorists @hesterbruikman 

(for desktop shouldn't be the blocker, more interested in opinions about mobile)

**Comment by churik** [comment]
@cammellos I have disabled PFS on Mac OS build by default, does it matter?

**Comment by cammellos** [comment]
@churik it should be disabled by default yes, if it's enabled by default it's a bug. On release you should not see the toggle completely, but only on mobile, on desktop you will always see it.

**Comment by annadanchenko** [comment]
> @mandrigin correct, release should not be have the pfs toggle
> @annadanchenko I shortened the time for which we respond to a message, but it should not have any impact on testing.
> 
> To test it still works correctly you could do something like:
> 
> 1. Create user A & B
> 2. Create a group chat in A & B, exchange messages
> 3. Re-install and recover on device A, wait for messages to be fetched
> 4. Send a message from B in the group chat, this message should be received by A (if it fetched old messages from the mailserver, otherwise the next message sent from B will be visible)

recovered A, got the group chat and see only new message from B - think it's fine.
also got pairing popup but even if select to sync with "No info" device then nothing happens - do not get contacts and public chat. Only group chat is shown and 1:1 chat with B as someone not in my contacts


So group and 1:1 chat
screenshot_20190130-154655


Devices screen:
screenshot_20190130-154700

**Comment by churik** [comment]
> To test it still works correctly you could do something like:
> 
> Create user A & B
> Create a group chat in A & B, exchange messages
> Re-install and recover on device A, wait for messages to be fetched
> Send a message from B in the group chat, this message should be received by A (if it fetched old messages from the mailserver, otherwise the next message sent from B will be visible)

Works fine for me on Linux / Mac OS.
For me sync is working after I set custom name and discover device to other device (tap on "+") -  in this case custom name is shown on other device, after enabling pairing starts working.

**Comment by annadanchenko** [comment]
looks ok from my side. pfs will be checked as soon as we have release build

**Comment by annadanchenko** [comment]
need to get e2e test results before merging

**Comment by annadanchenko** [comment]
> ## 5% of end-end tests have passed
> ```
> Total executed tests: 58
> Failed tests: 55
> Passed tests: 3
> ```
> ### Failed tests (55)
> Click to expand
> ### Passed tests (3)
> Click to expand

I've triggered these tests with wrong apk, so ignore the results. triggering again

**Comment by hesterbruikman** [comment]
> this is how link "Learn more" looks like on Android mobile
> 
> screenshot_20190130-151723
> 
> and on windows desktop
> learn more
> 
> maybe we can get some UI suggestions to improve it? @errorists @hesterbruikman
> 
> (for desktop shouldn't be the blocker, more interested in opinions about mobile)

Thanks for tagging @annadanchenko Agreed this will not win a beauty competition. It looks like the **Learn more** [button] and/or the **Paired devices** [label] is missing padding (bounderies) @errorists , this is where I also need a Figma workshop. Can you tell if this is the issue?

Other than that, the pattern of having Learn more as a secondary button below left aligned text with an action button (+) doesn't feel like the best Module in terms of composition. This we should specify and update later, wouldn't want that to be a blocker now as it's a more generic specification.

**Comment by annadanchenko** [comment]
@antdanchenko please, have a look at failing tests in next 2 builds https://ci.status.im/job/end-to-end-tests/job/status-app-end-to-end-tests/2272/ and https://ci.status.im/job/end-to-end-tests/job/status-app-end-to-end-tests/2273

<blockquote><div><strong><a href="https://ci.status.im/job/end-to-end-tests/job/status-app-end-to-end-tests/2272/">end-to-end-tests » status-app-end-to-end-tests PR-7375 [Jenkins]</a></strong></div></blockquote>
<blockquote><div><strong><a href="https://ci.status.im/job/end-to-end-tests/job/status-app-end-to-end-tests/2273">end-to-end-tests » status-app-end-to-end-tests PR-7375 [Jenkins]</a></strong></div></blockquote>

**Comment by antdanchenko** [comment]
@cammellos , @annadanchenko e2e tests are failing due to issues on SauceLabs side, https://status.saucelabs.com/
lets re-run them whenever those issues are fixed
 Approximately tomorrow's morning 

<blockquote><div><strong><a href="https://status.saucelabs.com/">Sauce Labs Inc Status</a></strong></div><div>Welcome to Sauce Labs Inc's home for real-time and historical data on system performance.</div></blockquote>

**Pull request merged**
