### PR TITLE
Fix panic syncing community token gated

### PR DESCRIPTION
**Pull request by cammellos**
status: ready

### CODE REVIEW

**Comment by pavloburykh** [comment]
@cammellos thanks for the PR! Still facing crash after sync on IOS while on Android it is okay. 

### ISSUE 1 IOS app crashes after sync with Desktop

IOS 16.7.2 iPhone X

[logs (16).zip](https://github.com/status-im/status-mobile/files/13502153/logs.16.zip)

https://github.com/status-im/status-mobile/assets/97245802/84bfd293-ee4a-4099-8ab8-75920c3b1bd5

**Comment by churik** [comment]
For me, it was crashed just after logging in (in community list) - IOS only:
[logs (68).zip](https://github.com/status-im/status-mobile/files/13502333/logs.68.zip)

**Comment by cammellos** [comment]
@pavloburykh are you syncing a token gated community? if you sync without a token gated community, does the issue still occours?

**Comment by cammellos** [comment]
> For me, it was crashed just after logging in (in community list) - IOS only: [logs (68).zip](https://github.com/status-im/status-mobile/files/13502333/logs.68.zip)

on android nothing? (I need the crash logs, but not sure how to get them from a ios real device, maybe @qfrank knows?)

**Comment by pavloburykh** [comment]
> @pavloburykh are you syncing a token gated community? if you sync without a token gated community, does the issue still occours?

I have just tried to sync with newly created user who doesn't have any data yet and IOS didn't crash. 

But then I have tried to sync once again with a user who has token gated communities and it didn't crash too...

So this crash is NOT reproducible every time and therefore it is hard to say if there is any relation to the existing data of synced user.

**Comment by qfrank** [comment]
> > For me, it was crashed just after logging in (in community list) - IOS only: [logs (68).zip](https://github.com/status-im/status-mobile/files/13502333/logs.68.zip)
> 
> on android nothing? (I need the crash logs, but not sure how to get them from a ios real device, maybe @qfrank knows?)

to get them from an ios real device, the approach is the same as this [guideline](https://github.com/status-im/status-react/blob/58d5c3d7a5e7ac08a89e774d3a3adb89bc7b0170/doc/how-to-catch-crash-on-ios.md#L1) @cammellos

**Comment by cammellos** [comment]
@churik @pavloburykh could you try to replicate the issue following the instructions in the doc https://github.com/status-im/status-mobile/pull/18024#issuecomment-1832983697 please and send over the logs?
Thank you (and thanks @qfrank for reminding me yet again :) )

**Comment by qfrank** [comment]
> @churik @pavloburykh could you try to replicate the issue following the instructions in the doc [#18024 (comment)](https://github.com/status-im/status-mobile/pull/18024#issuecomment-1832983697) please and send over the logs? Thank you (and thanks @qfrank for reminding me yet again :) )

they won't get useful logs ..  but after following the guideline, they can take a screenshot for the located stacktrace like [this](https://github.com/status-im/status-mobile/blob/58d5c3d7a5e7ac08a89e774d3a3adb89bc7b0170/doc/images/how-to-catch-crash-on-ios/located-stack-trace.png), that's pretty useful and acurate.

TBO, the guideline is suitable for developers rather than QA.  @cammellos 🙂

**Comment by qfrank** [comment]
> For me, it was crashed just after logging in (in community list) - IOS only: [logs (68).zip](https://github.com/status-im/status-mobile/files/13502333/logs.68.zip)

curious is it reproducable between 2 ios devices? @churik @pavloburykh

**Comment by churik** [comment]
I can't reproduce it today with the same steps, so perhaps it is the same https://github.com/status-im/status-mobile/issues/16560

**Comment by pavloburykh** [comment]
@cammellos I think we are ready to merge the PR. The main issue with Android crash and contacts restoring is fixed, thank you! 

The rest of the issues from this https://github.com/status-im/status-mobile/issues/18021 will be logged separately.

**Comment by pavloburykh** [comment]
@cammellos before merge, could you please rebase go and mobile branches once again and I will run e2e tests.

**Comment by churik** [comment]
@cammellos can you please merge PR and update status-go on our side? 
Thanks!

**Pull request merged**
