### PR TITLE
[FIX #4347] Update Launch Screens

### LINKED ISSUE #4347: Update launch screens
### User Story

As a user, I want to see a consistent brand across platforms so that.

### Description

*Type*: Improvement

#### Expected behavior
screenshot 2018-05-18 17 40 38

#### Actual behavior
screenshot 2018-05-18 17 41 09

### Solution

*Summary*:  You need to take new assets from my dropbox https://www.dropbox.com/sh/lj8fa2e75a2ozwe/AADpHMh4mdFX--Y_TyrNp2dQa?dl=0
and replace them here: 

ios:
https://github.com/status-im/status-react/tree/develop/ios/StatusIm/Images.xcassets/LaunchImage.launchimage

Android:
1. https://github.com/status-im/status-react/tree/develop/android/app/src/main/res/drawable-xxhdpi
2. https://github.com/status-im/status-react/tree/develop/android/app/src/main/res/drawable-xhdpi

### Additional Information
* Operating System: Android|iOS

### PR DESCRIPTION
**Pull request by georgiemathews**
[comment]: # (Please replace ... with your information. Remove < and >)
[comment]: # (To auto-close issue on merge, please insert the related issue number after # i.e fixes #566)

Fixes #4347

### Summary:

[comment]: # (Summarise the problem and how the pull request solves it)
Updates launch screens to those specified in #4347 

### Steps to test:
- Open Status
- See if launch screen reflects new assets

status: ready

### CODE REVIEW

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/hJZW9o for branch PR-4463

<blockquote><div><strong><a href="https://i.diawi.com/hJZW9o">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/XnH5VB for branch PR-4463

<blockquote><div><strong><a href="https://i.diawi.com/XnH5VB">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Review by jeluard — APPROVED** [review]

**Review by flexsurfer — APPROVED** [review]

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/gBYR8C for branch PR-4463

<blockquote><div><strong><a href="https://i.diawi.com/gBYR8C">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/6oKEaV for branch PR-4463

<blockquote><div><strong><a href="https://i.diawi.com/6oKEaV">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Pull request merged**
