### PR TITLE
[#7927] import keycard account to new device

### LINKED ISSUE #7913: If card has keys on it, there is no way to use it with new device (cannot restore an account with pairing code)
### Description
_Type_: Bug
_Summary_: when I create account with keycard, there is no way to restore it with pairing code.

#### Expected behavior
can restore account

#### Actual behavior
"This card has already an account on it. If you wish to change it, login first and then reset your card".
So if you don't have card-reader or device with initial install - it is dead end for card.

### Reproduction

* Open Status
* Create account with keycard
* Reinstall build or install on another device
* Tap on "I already have an account" > Keycard
* Tap card and enter valid pairing code

### Additional Information
[comment]: # (Please do your best to fill this out.)

* Status version: https://status-im-prs.ams3.digitaloceanspaces.com/StatusIm-190403-181003-8b6ae2-pr.apk
* Operating System: Android 8, LG V20

### PR DESCRIPTION
**Pull request by dmitryn**
fixes #7913

### Summary

Add support for importing keycard account to new device.

### Steps to test

1. Set up keycard on device A
2. Add existing account to device B
3. Enter pairing code
4. Start importing account
5. Account imported, you should be able to log in to device B
6. You should be also able to log in to device A

status: ready

### CODE REVIEW

**Review by rasom — APPROVED** [review]

**Comment by dmitryn** [comment]
@jeluard @flexsurfer please review

**Review by flexsurfer — APPROVED** [review]

**Comment by asemiankevich** [comment]
@dmitryn i am asked for PIN when i tap Log Out button, that is very simialr what i did see in previous PR, could you please fix it in this branch too?

**Comment by dmitryn** [comment]
@asemiankevich ok, i've merged changes from https://github.com/status-im/status-react/pull/8079 to this PR

**Comment by asemiankevich** [comment]
@dmitryn error and blank screen after logout :( 

image

```
PRETTY PRINTED EXCEPTION
05-10 05:06:54.963  4539  4591 I ReactNativeJS: 
05-10 05:06:54.963  4539  4591 I ReactNativeJS: ***
05-10 05:06:54.963  4539  4591 I ReactNativeJS: NAME: "Error"
05-10 05:06:54.963  4539  4591 I ReactNativeJS: MESSAGE: fx/defn expects a map of cofx as first argument got {:event [:signals/signal-received "{\"type\":\"node.stopped\",\"event\":null}"], :db nil, :now 1557490014951} in function function (a) {
05-10 05:06:54.963  4539  4591 I ReactNativeJS:     switch (arguments.length) {
05-10 05:06:54.963  4539  4591 I ReactNativeJS:       case 1:
05-10 05:06:54.963  4539  4591 I ReactNativeJS:         return status_im.signals.core.process.cljs$core$IFn$_invoke$arity$1(arguments[0]);
05-10 05:06:54.963  4539  4591 I ReactNativeJS: 
05-10 05:06:54.963  4539  4591 I ReactNativeJS:       case 2:
05-10 05:06:54.963  4539  4591 I ReactNativeJS:         return status_im.signals.core.process.cljs$core$IFn$_invoke$arity$2(arguments[0], arguments[1]);
05-10 05:06:54.963  4539  4591 I ReactNativeJS: 
05-10 05:06:54.963  4539  4591 I ReactNativeJS:       default:
05-10 05:06:54.963  4539  4591 I ReactNativeJS:         throw Error(["Invalid arity: ", cljs.core.str.cljs$core$IFn$_invoke$arity$1(arguments.length)].join(""));
05-10 05:06:54.963  4539  4591 I ReactNativeJS:     }
05-10 05:06:54.963  4539  4591 I ReactNativeJS:   }
05-10 05:06:54.963  4539  4591 I ReactNativeJS: 
05-10 05:06:54.963  4539  4591 I ReactNativeJS: cljs$core$IFn$_invoke$arity$2@index.android.bundle:141668:23
05-10 05:06:54.963  4539  4591 I ReactNativeJS: index.android.bundle:142592:72
05-10 05:06:54.963  4539  4591 I ReactNativeJS: index.android.bundle:45740:173
05-10 05:06:54.963  4539  4591 I ReactNativeJS: invoke_interceptor_fn@index.android.bundle:44572:111
05-10 05:06:54.963  4539  4591 I ReactNativeJS: invoke_interceptors@index.android.bundle:44581:53
05-10 05:06:54.963  4539  4591 I ReactNativeJS: execute@index.android.bundle:44622:131
05-10 05:06:54.963  4539  4591 I ReactNativeJS: handle@index.android.bundle:44784:39
05-10 05:06:54.963  4539  4591 I ReactNativeJS: re_frame$router$IEventQueue$_process_1st_event_in_queue$arity$1@index.android.bundle:45142:36
05-10 05:06:54.963  4539  4591 I ReactNativeJS: re_frame$router$IEventQueue$_run_queue$arity$1@index.android.bundle:44958:75
05-10 05:06:54.963  4539  4591 I ReactNativeJS: index.android.bundle:45086:66
05-10 05:06:54.963  4539  4591 I ReactNativeJS: re_frame$router$IEventQueue$_fsm_trigger$arity$3@index.android.bundle:45120:1398
05-10 05:06:54.963  4539  4591 I ReactNativeJS: index.android.bundle:44983:66
05-10 05:06:54.963  4539  4591 I ReactNativeJS: _callTimer@index.android.bundle:185219:17
05-10 05:06:54.963  4539  4591 I ReactNativeJS: _callImmediatesPass@index.android.bundle:185255:19
05-10 05:06:54.963  4539  4591 I ReactNativeJS: callImmediates@index.android.bundle:185474:33
05-10 05:06:54.963  4539  4591 I ReactNativeJS: callImmediates@[native code]
05-10 05:06:54.963  4539  4591 I ReactNativeJS: __callImmediates@index.android.bundle:160413:35
05-10 05:06:54.963  4539  4591 I ReactNativeJS: index.android.bundle:160234:34
05-10 05:06:54.963  4539  4591 I ReactNativeJS: __guard@index.android.bundle:160396:15
05-10 05:06:54.963  4539  4591 I ReactNativeJS: flushedQueue@index.android.bundle:160233:21
05-10 05:06:54.963  4539  4591 I ReactNativeJS: flushedQueue@[native code]
05-10 05:06:54.963  4539  4591 I ReactNativeJS: callFunctionReturnFlushedQueue@[native code]
05-10 05:06:54.963  4539  4591 I ReactNativeJS: 
05-10 05:06:54.963  4539  4591 I ReactNativeJS: ***

```

**Comment by dmitryn** [comment]
>error and blank screen after logout :(

@asemiankevich cannot reproduce it, probably was fixed by https://github.com/status-im/status-react/pull/8079 which  merged here

**Pull request merged**
