### PR TITLE
Add preview and counters for CR system messages #16898

### LINKED ISSUE #16898: Add preview and counters for CR system messages
Followup of https://github.com/status-im/status-mobile/pull/16775 cc @flexsurfer 

### 1. Add counters for "you were removed from contact" and "now is contact" system messages

**Steps:** 

1. Generate "you were removed from contact" and "now is contact" system messages
2. See if unread counter is generated for these types of messages

**Actual result:** unread counter is not generated

**Expected result:** unread counter should be generated

### 2. Add preview for "you were removed from contact"/"you removed from contact" system messages

**Steps:** 

1. Generate "you were removed from contact"/"you removed from contact" system messages
2. See if messages are shown in chat preview and in within chat card in Shell

**Actual result:** preview is not shown

**Expected result:** preview should be shown

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

### PR DESCRIPTION
**Pull request by flexsurfer**
fixes #16898

### CODE REVIEW

**Review by Parveshdhull — APPROVED** [review]

**Review by siddarthkay — APPROVED** [review]

**Comment by pavloburykh** [comment]
Thanx for the PR @flexsurfer ! Please take a look at the issues

### ISSUE 1 "<username> removed as contact" system message is not shown in chat and shell previews


https://github.com/status-im/status-mobile/assets/97245802/9523d600-98e5-4fe5-ba3b-64a3e343bd83

**Comment by pavloburykh** [comment]
### ISSUE 2 "<username> is now a contact" system message is not shown in Shell card preview for CR sender


https://github.com/status-im/status-mobile/assets/97245802/4293add5-4da8-4612-bc85-f420643d8a13

**Comment by pavloburykh** [comment]
### ISSUE 3 Removal system messages icon is lost

@flexsurfer it is not PR related (cause same is in develop) but I wonder if we can address it here? As far as I remember you have added this icon here https://github.com/status-im/status-mobile/pull/16775 not sure when it has been lost again. 

photo_2023-08-10 17 53 32

**Comment by flexsurfer** [comment]
thanks @pavloburykh 1 and 2 are fixed, 3 is by design

**Comment by pavloburykh** [comment]
@flexsurfer thanx for the fixes. Please take a look at the new issue

### ISSUE 4 "<username> sent you CR" system message does not generate unread counter

**Steps:**

1. User A sends CR to User B
2. See if unread counter is generated for User B as a result of new "<username> sent you CR" system message

**Actual result:** unread counter is not generated. 

[video](https://drive.google.com/file/d/1QTFWq3V0wpFRaQtpwAYoJ1M5hODh_T_5/view?usp=drive_link)

**Comment by pavloburykh** [comment]
@flexsurfer thanx for the fixes! PR is ready to be merged.

**Pull request merged**
