### PR TITLE
fix: image typo

### LINKED ISSUE #15389: "No protocol method DateTimeProtocol plus- defined for type null:" error on opening a sent image in chat
@OmarBasem probably a regression of some of recent PRs related to images

**Steps:**

1. Open any chat
2. Send a message containing image
3. Try to open image after sending

**Expected result:** image opens, no error

**Actual result:** "No protocol method DateTimeProtocol plus- defined for type null:" error appears, image is not opened. In case with messages containing more than 1 image - it is able to open them after re-entering chat, when images start showing as an album. See video below. 

[Status-debug-logs (23).zip](https://github.com/status-im/status-mobile/files/10991266/Status-debug-logs.23.zip)

https://user-images.githubusercontent.com/97245802/225630479-38a6f686-cce4-4059-ab45-344a6709667d.mp4

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by OmarBasem**
fixes: https://github.com/status-im/status-mobile/issues/15389

fixes a small typo when opening image

### CODE REVIEW

**Review by flexsurfer — APPROVED** [review]

**Review by ilmotta — APPROVED** [review]

**Comment by pavloburykh** [comment]
@OmarBasem thanx for the fix. 

As a result of fixing current bug a have been able to reproduce another issue which has been blocked by current bug. 

Please take a look and tell if you want to fix it in current PR or I can log it separately after merging current fix. 

### ISSUE 1 App crashes after opening and then closing an image that has been just sent in chat

**Steps:**

1. Open any chat
2. Send message containing image/images
3. Open the image right after sending it
4. Close the image (try closing both by swiping down and tapping close button)
5. Observe error and crash

**NOTE:** you might not reproduce the bug from the first try. Keep sending new images and follow steps 3-4 until you see error and crash. 

**Actual result:** error appears and app crashes (see screenshot and video below)

[Status-debug-logs (24).zip](https://github.com/status-im/status-mobile/files/10992732/Status-debug-logs.24.zip)

photo_2023-03-16 17 43 03

https://user-images.githubusercontent.com/97245802/225672106-10c80f58-4dc5-46dc-b8a6-4a841fe641d6.mp4

**Comment by OmarBasem** [comment]
@pavloburykh it seems the error happens randomly? If so, please log it in a seperate issue.

**Comment by pavloburykh** [comment]
> @pavloburykh it seems the error happens randomly? If so, please log it in a separate issue.

@OmarBasem I cannot say it happens 100% randomly. I am able to reproduce it constantly following the above steps it just needs couple of tires. Okay, i will log separately. For now I have been able to reproduce on only on Android. 

Current PR is tested and ready to be merged.

**Comment by OmarBasem** [comment]
Thanks @pavloburykh, I will look into it.

**Pull request merged**
