### PR TITLE
[#19375] Fix remove modal for seed accounts

### LINKED ISSUE #19357: Display an alert banner when test network mode is enabled
# Feature Issue

Display an alert banner when test network mode is enabled.

### User Story

> As a user, I want to see an alert/warning banner when test networks are enabled. 

### Design
[Figma Link](https://www.figma.com/file/QWJV5WRbroXVDsdubEDjAT/Wallet-settings-for-Mobile?type=design&node-id=153%3A190019&mode=design&t=IaPtUmpso3cJ2pRF-1)

### Acceptance Criteria

An Alert banner with `Testnet mode enabled` text is shown to the user when the test network mode is enabled.

### LINKED ISSUE #19375: Inability to remove eth accounts which created by key pair generation flow or imported by seed phrase
### Steps:
1. Create an account with a newly generated keypair (see flow [here](https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=2070-596827&mode=design&t=iugkFHlUKh8btaCh-0) how to generate keypair)
2. Open current account
3. Try to remove it

### Actual result:
The removing bottom sheet is not shown

https://github.com/status-im/status-mobile/assets/52490791/dd67d469-c472-43da-8fd4-d4d2389c574f

### Expected result:
The removing bottom sheet should be shown with 'remove' and 'cancel' buttons.
https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=900-234771&mode=design&t=x8pd1J3e5lSLbdW3-0

### ENV:
NIghtly [22 Mar 2024]

### PR DESCRIPTION
**Pull request by ulisesmac**
fixes #19375 

### Summary

Just a quick fix, shows the modal to remove accounts created from an imported or new generated keypair

### Steps to test

- Create a new keypair or import a keypair
- Create acounts for it
- Remove them

status: ready

### CODE REVIEW

**Review by smohamedjavid — APPROVED** [review]

**Comment by ulisesmac** [comment]
@status-im/mobile-qa 

Skipping manual QA because it's mostly an UI change. Just want to know if E2E tests are fine.
Thank you.

**Comment by yevh-berdnyk** [comment]
> ## 80% of end-end tests have passed
Hi @ulisesmac, e2e failures are not related to the PR, thanks!

**Comment by churik** [comment]
I'd say it is change in flow, so we'll make a quick round of testing

**Comment by VolodLytvynenko** [comment]
Hi @ulisesmac thank you for PR. Could you take a look if this issue is PR-related?

## ISSUE 1: The removed account can be added back with derivation m/44/60'/0'/0/0 path

### Steps:
1. Create an additional account using seed phrase importing or key pair generation.
2. Remove the current account.
3. Create this account again.

### Actual result:
The keypairs generated with m/44/60'/0'/0/0 path again

https://github.com/status-im/status-mobile/assets/52490791/529d3129-500f-4042-992f-19879b916958

### Expected result:
If the account is removed, the removed derivation path account should not be restored.

How it works on Desktop:

https://github.com/status-im/status-mobile/assets/52490791/e680fb1e-e4bd-4c80-bd2b-7d8d6feda198

**Comment by VolodLytvynenko** [comment]
Another problem, also perhaps not related to PR.

## ISSUE 2: Addresses imported with Private Key can't be removed

### Steps:
1. Create an account on Metamask and copy the private key for that account
2. Import this account on desktop using the "Import Private Key" option.
3. Sync with desktop using mobile (now the imported account via private key is available on mobile).
4. Try to remove the account.

### Actual Result:
The drawer is not shown after attempting to remove the account imported via private key.

https://github.com/status-im/status-mobile/assets/52490791/d846071d-96a8-440c-96b2-d2d81f4782bd


### Expected Result:
The special drawer related to keypair removing is shown after attempting to remove the account imported via private key.
https://www.figma.com/design/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?node-id=903-245913&t=P49gsAwNgFHhQhXp-0

**Comment by ulisesmac** [comment]
> Hi @ulisesmac thank you for PR. Could you take a look if this issue is PR-related?
> ## ISSUE 1: The removed account can be added back with derivation m/44/60'/0'/0/0 path
> ### Steps:
> 
>     1. Create an additional account using seed phrase importing or key pair generation.
> 
>     2. Remove the current account.
> 
>     3. Create this account again.
> 
> 
> ### Actual result:
> 
> The keypairs generated with m/44/60'/0'/0/0 path again
> derpath.mp4
> ### Expected result:
> 
> If the account is removed, the removed derivation path account should not be restored.
> 
> How it works on Desktop:
> keypairs.mp4

Thanks for testing @VolodLytvynenko 

This issue is not related to this PR, and I'm not sure if it is actually wrong or not, since we are re-importing the keypair.

Better to extract this to a separate issue and gather Alisher's feedback, wdyt?

**Comment by ulisesmac** [comment]
> Another problem, also perhaps not related to PR.
> ## ISSUE 2: Addresses imported with Private Key can't be removed
> ### Steps:


@VolodLytvynenko this issue was originally out of scope of this PR, since these accounts are of type `key` and this PR only addressed the issue for `seed` accounts, but now I've decided to fix this issue too, since they are related.

Now the modal is shown and the deletion can be made:




So now, this PR is also implementing the (previously missing) modal to remove these accounts: [figma link](https://www.figma.com/design/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?node-id=903-245913&t=afo5u2TonsUAV9gn-4)

**Comment by VolodLytvynenko** [comment]
hi @ulisesmac thank you for clarification. PR can be merged. No other issues from my side

**Comment by VolodLytvynenko** [comment]
@ulisesmac Thank you for the fixes and clarification. No issues from my side. I have rerun the e2e tests and will update you with the results soon.

**Comment by VolodLytvynenko** [comment]
hi @ulisesmac thank you for your job. PR is ready to be merged.[ Issue 1](https://github.com/status-im/status-mobile/issues/20633) I have created separately with low prior

**Pull request merged**
