### PR TITLE
local pair: optimised finding server cert

### LINKED ISSUE #17458: App stuck in "Syncing" state after scanning QR mobile-mobile
### Steps:
1. mobile device 1 generates the sync QR
2. mobile device 2 scans the QR (now the "oops something went wrong" page is shown)
3. mobile device 2 tap 'try again' button 

### Actual behavior
App Stuck in "syncing" state

### Expected behavior
User is redirected to "syncing" screen

### Additional info:
Private wi-fi network is used with good signal

### Logs:
[android_logcat4 (2).txt](https://github.com/status-im/status-mobile/files/12765017/android_logcat4.2.txt)

### ENV:
Nightly [29 Sep 2023]

### PR DESCRIPTION
**Pull request by qfrank**
fixes #17458

relate [PR](https://github.com/status-im/status-go/pull/4148) for status-go

#### Platforms

- Android
- iOS

status: ready

### CODE REVIEW

**Comment by churik** [comment]
@qfrank works on my side Adroid > IOS, Android > Desktop!
Wonderful job!
Should I ask more people from mobile to verify it? 
Should it also fix https://github.com/status-im/status-mobile/issues/17474 or it is different error?

**Comment by qfrank** [comment]
Thank you for your feedback ❤️ @churik 

> Should I ask more people from mobile to verify it?

sounds good to me

> Should it also fix https://github.com/status-im/status-mobile/issues/17474 or it is different error?

not sure, i can't see useful information from the log @ilmotta provided , maybe @ilmotta can try this PR

**Comment by siddarthkay** [comment]
@qfrank : I will try this branch out

**Comment by ilmotta** [comment]
> Thank you for your feedback ❤️ @churik
> 
> > Should I ask more people from mobile to verify it?
> 
> sounds good to me
> 
> > Should it also fix https://github.com/status-im/status-mobile/issues/17474 or it is different error?
> 
> not sure, i can't see useful information from the log @ilmotta provided , maybe @ilmotta can try this PR

I'll be trying your PR today @qfrank and will report back :)

**Comment by qfrank** [comment]
> > Thank you for your feedback ❤️ @churik
> > > Should I ask more people from mobile to verify it?
> > 
> > 
> > sounds good to me
> > > Should it also fix https://github.com/status-im/status-mobile/issues/17474 or it is different error?
> > 
> > 
> > not sure, i can't see useful information from the log @ilmotta provided , maybe @ilmotta can try this PR
> 
> I'll be trying your PR today @qfrank and will report back :)

Thank you! Pls don't use android simulator as pairing server since listening address in android simulator can't be reachable for application outside except you use some trick like`adb forward` , but physical device(ios/android) or ios simulator doesn't have this restriction. @ilmotta

**Comment by ilmotta** [comment]
> > > Thank you for your feedback ❤️ @churik
> > > > Should I ask more people from mobile to verify it?
> > > 
> > > 
> > > sounds good to me
> > > > Should it also fix https://github.com/status-im/status-mobile/issues/17474 or it is different error?
> > > 
> > > 
> > > not sure, i can't see useful information from the log @ilmotta provided , maybe @ilmotta can try this PR
> > 
> > 
> > I'll be trying your PR today @qfrank and will report back :)
> 
> Thank you! Pls don't use android simulator as pairing server since listening address in android simulator can't be reachable for application outside except you use some trick like`adb forward` , but physical device(ios/android) or ios simulator doesn't have this restriction. @ilmotta

Thank you @qfrank, good to know. Yes, all my tests have been on real devices on different machines, I don't trust the emulator for this kind of work.

**Comment by ilmotta** [comment]
@qfrank, @churik, I could successfully sync using this PR's apk on Android 13 (real device) and with the desktop client `0.13.3`.

**Comment by ilmotta** [comment]
@churik, @qfrank. I think I could reproduce the issue I was facing before. In my previous comment about successfully syncing, I forgot to say I disabled my firewall. When my desktop client runs with firewall disabled, everything is fine, but once it's enabled, I can't sync from the mobile device. We can see that from the logs below, as the mobile client tries two different random ports which are not open on my other device.

Here are the logs captured right after I scan the QR code and see the error screen `Oops, something's wrong` saying "Make sure both devices are powered on ...".

```
t=2023-10-13T15:40:35+0000 lvl=info msg="logging initialised" logSettings="{\"Enabled\":true,\"MobileSystem\":false,\"Level\":\"DEBUG\",\"File\":\"\\/storage\\/emulated\\/0\\/Android\\/data\\/im.status.ethereum.pr\\/files\\/Download\\/geth.log\"}"
t=2023-10-13T15:40:35+0000 lvl=warn msg="messenger nil, not reporting app state change"
t=2023-10-13T15:40:35+0000 lvl=dbug msg=fired
t=2023-10-13T15:40:35+0000 lvl=dbug msg=fired
t=2023-10-13T15:40:35+0000 lvl=info msg="Network state change" package=status-go/api.GethStatusBackend old=unknown new=wifi
t=2023-10-13T15:40:35+0000 lvl=dbug msg=fired port=34609
t=2023-10-13T15:40:35+0000 lvl=dbug msg="p.afterPortChanged != nil"
t=2023-10-13T15:40:45+0000 lvl=warn msg="messenger nil, not reporting app state change"
t=2023-10-13T15:40:46+0000 lvl=warn msg="messenger nil, not reporting app state change"
t=2023-10-13T15:40:47+0000 lvl=dbug msg="empty push notification servers, setting" fleet=status.prod
t=2023-10-13T15:40:47+0000 lvl=dbug msg="setting default push notification servers" cluster servers="[401ba5eda402678dc78a0a40fd0795f4ea8b1e34972c4d15cf33ac01292341c89f0cbc637fa9f7a3ffe0b9dfe90e9cdae7a14925500ab01b6a91c67bae42a97a 181141b1d111908aaf05f4788e6778ec07073a1d4e1ce43c73815c40ee4e7345a1cbf5a90a45f601bf3763f12be63b01624ba1f36eeb9572455e7034b8f9f2c4 5ffc34d5ffda180d94cd3974d9ed2bb082ede68f342babdbe801ceffb7da902087d43f9aa961c7b85029358874c08ef04ecad9f1d95a1f0e448cbdd5d04350c7]"
t=2023-10-13T15:40:49+0000 lvl=warn msg="failed to connect to any of given addresses. Retrying..." error="failed to connect to any of given addresses. IP 192.168.0.14: connecting to 'https://192.168.0.14:37037' failed: dial tcp 192.168.0.14:37037: i/o timeout; " netIPs=[192.168.0.14] retry=1
t=2023-10-13T15:40:51+0000 lvl=warn msg="failed to connect to any of given addresses. Retrying..." error="failed to connect to any of given addresses. IP 192.168.0.14: connecting to 'https://192.168.0.14:37037' failed: dial tcp 192.168.0.14:37037: i/o timeout; " netIPs=[192.168.0.14] retry=2
t=2023-10-13T15:40:53+0000 lvl=warn msg="failed to connect to any of given addresses. Retrying..." error="failed to connect to any of given addresses. IP 192.168.0.14: connecting to 'https://192.168.0.14:37037' failed: dial tcp 192.168.0.14:37037: i/o timeout; " netIPs=[192.168.0.14] retry=3
t=2023-10-13T15:46:09+0000 lvl=dbug msg="empty push notification servers, setting" fleet=status.prod
t=2023-10-13T15:46:09+0000 lvl=dbug msg="setting default push notification servers" cluster servers="[401ba5eda402678dc78a0a40fd0795f4ea8b1e34972c4d15cf33ac01292341c89f0cbc637fa9f7a3ffe0b9dfe90e9cdae7a14925500ab01b6a91c67bae42a97a 181141b1d111908aaf05f4788e6778ec07073a1d4e1ce43c73815c40ee4e7345a1cbf5a90a45f601bf3763f12be63b01624ba1f36eeb9572455e7034b8f9f2c4 5ffc34d5ffda180d94cd3974d9ed2bb082ede68f342babdbe801ceffb7da902087d43f9aa961c7b85029358874c08ef04ecad9f1d95a1f0e448cbdd5d04350c7]"
t=2023-10-13T15:46:11+0000 lvl=warn msg="failed to connect to any of given addresses. Retrying..." error="failed to connect to any of given addresses. IP 192.168.0.14: connecting to 'https://192.168.0.14:34347' failed: dial tcp 192.168.0.14:34347: i/o timeout; " netIPs=[192.168.0.14] retry=1
t=2023-10-13T15:46:13+0000 lvl=warn msg="failed to connect to any of given addresses. Retrying..." error="failed to connect to any of given addresses. IP 192.168.0.14: connecting to 'https://192.168.0.14:34347' failed: dial tcp 192.168.0.14:34347: i/o timeout; " netIPs=[192.168.0.14] retry=2
t=2023-10-13T15:46:15+0000 lvl=warn msg="failed to connect to any of given addresses. Retrying..." error="failed to connect to any of given addresses. IP 192.168.0.14: connecting to 'https://192.168.0.14:34347' failed: dial tcp 192.168.0.14:34347: i/o timeout; " netIPs=[192.168.0.14] retry=3
```

**Comment by qfrank** [comment]
> @churik, @qfrank. I think I could reproduce the issue I was facing before. In my previous comment about successfully syncing, I forgot to say I disabled my firewall. When my desktop client runs with firewall disabled, everything is fine, but once it's enabled, I can't sync from the mobile device. We can see that from the logs below, as the mobile client tries two different random ports which are not open on my other device.
> 
> Here are the logs captured right after I scan the QR code and see the error screen `Oops, something's wrong` saying "Make sure both devices are powered on ...".
> 
> ```
> t=2023-10-13T15:40:35+0000 lvl=info msg="logging initialised" logSettings="{\"Enabled\":true,\"MobileSystem\":false,\"Level\":\"DEBUG\",\"File\":\"\\/storage\\/emulated\\/0\\/Android\\/data\\/im.status.ethereum.pr\\/files\\/Download\\/geth.log\"}"
> t=2023-10-13T15:40:35+0000 lvl=warn msg="messenger nil, not reporting app state change"
> t=2023-10-13T15:40:35+0000 lvl=dbug msg=fired
> t=2023-10-13T15:40:35+0000 lvl=dbug msg=fired
> t=2023-10-13T15:40:35+0000 lvl=info msg="Network state change" package=status-go/api.GethStatusBackend old=unknown new=wifi
> t=2023-10-13T15:40:35+0000 lvl=dbug msg=fired port=34609
> t=2023-10-13T15:40:35+0000 lvl=dbug msg="p.afterPortChanged != nil"
> t=2023-10-13T15:40:45+0000 lvl=warn msg="messenger nil, not reporting app state change"
> t=2023-10-13T15:40:46+0000 lvl=warn msg="messenger nil, not reporting app state change"
> t=2023-10-13T15:40:47+0000 lvl=dbug msg="empty push notification servers, setting" fleet=status.prod
> t=2023-10-13T15:40:47+0000 lvl=dbug msg="setting default push notification servers" cluster servers="[401ba5eda402678dc78a0a40fd0795f4ea8b1e34972c4d15cf33ac01292341c89f0cbc637fa9f7a3ffe0b9dfe90e9cdae7a14925500ab01b6a91c67bae42a97a 181141b1d111908aaf05f4788e6778ec07073a1d4e1ce43c73815c40ee4e7345a1cbf5a90a45f601bf3763f12be63b01624ba1f36eeb9572455e7034b8f9f2c4 5ffc34d5ffda180d94cd3974d9ed2bb082ede68f342babdbe801ceffb7da902087d43f9aa961c7b85029358874c08ef04ecad9f1d95a1f0e448cbdd5d04350c7]"
> t=2023-10-13T15:40:49+0000 lvl=warn msg="failed to connect to any of given addresses. Retrying..." error="failed to connect to any of given addresses. IP 192.168.0.14: connecting to 'https://192.168.0.14:37037' failed: dial tcp 192.168.0.14:37037: i/o timeout; " netIPs=[192.168.0.14] retry=1
> t=2023-10-13T15:40:51+0000 lvl=warn msg="failed to connect to any of given addresses. Retrying..." error="failed to connect to any of given addresses. IP 192.168.0.14: connecting to 'https://192.168.0.14:37037' failed: dial tcp 192.168.0.14:37037: i/o timeout; " netIPs=[192.168.0.14] retry=2
> t=2023-10-13T15:40:53+0000 lvl=warn msg="failed to connect to any of given addresses. Retrying..." error="failed to connect to any of given addresses. IP 192.168.0.14: connecting to 'https://192.168.0.14:37037' failed: dial tcp 192.168.0.14:37037: i/o timeout; " netIPs=[192.168.0.14] retry=3
> t=2023-10-13T15:46:09+0000 lvl=dbug msg="empty push notification servers, setting" fleet=status.prod
> t=2023-10-13T15:46:09+0000 lvl=dbug msg="setting default push notification servers" cluster servers="[401ba5eda402678dc78a0a40fd0795f4ea8b1e34972c4d15cf33ac01292341c89f0cbc637fa9f7a3ffe0b9dfe90e9cdae7a14925500ab01b6a91c67bae42a97a 181141b1d111908aaf05f4788e6778ec07073a1d4e1ce43c73815c40ee4e7345a1cbf5a90a45f601bf3763f12be63b01624ba1f36eeb9572455e7034b8f9f2c4 5ffc34d5ffda180d94cd3974d9ed2bb082ede68f342babdbe801ceffb7da902087d43f9aa961c7b85029358874c08ef04ecad9f1d95a1f0e448cbdd5d04350c7]"
> t=2023-10-13T15:46:11+0000 lvl=warn msg="failed to connect to any of given addresses. Retrying..." error="failed to connect to any of given addresses. IP 192.168.0.14: connecting to 'https://192.168.0.14:34347' failed: dial tcp 192.168.0.14:34347: i/o timeout; " netIPs=[192.168.0.14] retry=1
> t=2023-10-13T15:46:13+0000 lvl=warn msg="failed to connect to any of given addresses. Retrying..." error="failed to connect to any of given addresses. IP 192.168.0.14: connecting to 'https://192.168.0.14:34347' failed: dial tcp 192.168.0.14:34347: i/o timeout; " netIPs=[192.168.0.14] retry=2
> t=2023-10-13T15:46:15+0000 lvl=warn msg="failed to connect to any of given addresses. Retrying..." error="failed to connect to any of given addresses. IP 192.168.0.14: connecting to 'https://192.168.0.14:34347' failed: dial tcp 192.168.0.14:34347: i/o timeout; " netIPs=[192.168.0.14] retry=3
> ```

@ilmotta Thank you for your detailed feedback 👍. The log indicates that the backend did its best to connect to all potentially reachable IPs, with the process taking around 4 seconds. This duration seems reasonable given that there's a 1-second pause after each retry. Perhaps removing this pause and leaving the retry decision to the user would be better, ensuring quicker feedback. I'll make that update.

Regarding the firewall, desktop environments can indeed be restrictive. While the backend supports mobile devices in the receiver server mode to bypass the firewall restrictions, the frontend hasn't incorporated this option yet. cc @cammellos @John-44 

Another area of improvement is the error messages we display. When the client receives a connection error from signal, we should also notify the user if the firewall is active and if in the same LAN etc.

**Comment by churik** [comment]
@qfrank let me know when it needs to be retested

**Comment by qfrank** [comment]
> @qfrank let me know when it needs to be retested

Pls when you got time ❤️ @churik

**Comment by John-44** [comment]
> > @churik, @qfrank. I think I could reproduce the issue I was facing before. In my previous comment about successfully syncing, I forgot to say I disabled my firewall. When my desktop client runs with firewall disabled, everything is fine, but once it's enabled, I can't sync from the mobile device. We can see that from the logs below, as the mobile client tries two different random ports which are not open on my other device.
> > Here are the logs captured right after I scan the QR code and see the error screen `Oops, something's wrong` saying "Make sure both devices are powered on ...".
> > ```
> > t=2023-10-13T15:40:35+0000 lvl=info msg="logging initialised" logSettings="{\"Enabled\":true,\"MobileSystem\":false,\"Level\":\"DEBUG\",\"File\":\"\\/storage\\/emulated\\/0\\/Android\\/data\\/im.status.ethereum.pr\\/files\\/Download\\/geth.log\"}"
> > t=2023-10-13T15:40:35+0000 lvl=warn msg="messenger nil, not reporting app state change"
> > t=2023-10-13T15:40:35+0000 lvl=dbug msg=fired
> > t=2023-10-13T15:40:35+0000 lvl=dbug msg=fired
> > t=2023-10-13T15:40:35+0000 lvl=info msg="Network state change" package=status-go/api.GethStatusBackend old=unknown new=wifi
> > t=2023-10-13T15:40:35+0000 lvl=dbug msg=fired port=34609
> > t=2023-10-13T15:40:35+0000 lvl=dbug msg="p.afterPortChanged != nil"
> > t=2023-10-13T15:40:45+0000 lvl=warn msg="messenger nil, not reporting app state change"
> > t=2023-10-13T15:40:46+0000 lvl=warn msg="messenger nil, not reporting app state change"
> > t=2023-10-13T15:40:47+0000 lvl=dbug msg="empty push notification servers, setting" fleet=status.prod
> > t=2023-10-13T15:40:47+0000 lvl=dbug msg="setting default push notification servers" cluster servers="[401ba5eda402678dc78a0a40fd0795f4ea8b1e34972c4d15cf33ac01292341c89f0cbc637fa9f7a3ffe0b9dfe90e9cdae7a14925500ab01b6a91c67bae42a97a 181141b1d111908aaf05f4788e6778ec07073a1d4e1ce43c73815c40ee4e7345a1cbf5a90a45f601bf3763f12be63b01624ba1f36eeb9572455e7034b8f9f2c4 5ffc34d5ffda180d94cd3974d9ed2bb082ede68f342babdbe801ceffb7da902087d43f9aa961c7b85029358874c08ef04ecad9f1d95a1f0e448cbdd5d04350c7]"
> > t=2023-10-13T15:40:49+0000 lvl=warn msg="failed to connect to any of given addresses. Retrying..." error="failed to connect to any of given addresses. IP 192.168.0.14: connecting to 'https://192.168.0.14:37037' failed: dial tcp 192.168.0.14:37037: i/o timeout; " netIPs=[192.168.0.14] retry=1
> > t=2023-10-13T15:40:51+0000 lvl=warn msg="failed to connect to any of given addresses. Retrying..." error="failed to connect to any of given addresses. IP 192.168.0.14: connecting to 'https://192.168.0.14:37037' failed: dial tcp 192.168.0.14:37037: i/o timeout; " netIPs=[192.168.0.14] retry=2
> > t=2023-10-13T15:40:53+0000 lvl=warn msg="failed to connect to any of given addresses. Retrying..." error="failed to connect to any of given addresses. IP 192.168.0.14: connecting to 'https://192.168.0.14:37037' failed: dial tcp 192.168.0.14:37037: i/o timeout; " netIPs=[192.168.0.14] retry=3
> > t=2023-10-13T15:46:09+0000 lvl=dbug msg="empty push notification servers, setting" fleet=status.prod
> > t=2023-10-13T15:46:09+0000 lvl=dbug msg="setting default push notification servers" cluster servers="[401ba5eda402678dc78a0a40fd0795f4ea8b1e34972c4d15cf33ac01292341c89f0cbc637fa9f7a3ffe0b9dfe90e9cdae7a14925500ab01b6a91c67bae42a97a 181141b1d111908aaf05f4788e6778ec07073a1d4e1ce43c73815c40ee4e7345a1cbf5a90a45f601bf3763f12be63b01624ba1f36eeb9572455e7034b8f9f2c4 5ffc34d5ffda180d94cd3974d9ed2bb082ede68f342babdbe801ceffb7da902087d43f9aa961c7b85029358874c08ef04ecad9f1d95a1f0e448cbdd5d04350c7]"
> > t=2023-10-13T15:46:11+0000 lvl=warn msg="failed to connect to any of given addresses. Retrying..." error="failed to connect to any of given addresses. IP 192.168.0.14: connecting to 'https://192.168.0.14:34347' failed: dial tcp 192.168.0.14:34347: i/o timeout; " netIPs=[192.168.0.14] retry=1
> > t=2023-10-13T15:46:13+0000 lvl=warn msg="failed to connect to any of given addresses. Retrying..." error="failed to connect to any of given addresses. IP 192.168.0.14: connecting to 'https://192.168.0.14:34347' failed: dial tcp 192.168.0.14:34347: i/o timeout; " netIPs=[192.168.0.14] retry=2
> > t=2023-10-13T15:46:15+0000 lvl=warn msg="failed to connect to any of given addresses. Retrying..." error="failed to connect to any of given addresses. IP 192.168.0.14: connecting to 'https://192.168.0.14:34347' failed: dial tcp 192.168.0.14:34347: i/o timeout; " netIPs=[192.168.0.14] retry=3
> > ```
> 
> @ilmotta Thank you for your detailed feedback 👍. The log indicates that the backend did its best to connect to all potentially reachable IPs, with the process taking around 4 seconds. This duration seems reasonable given that there's a 1-second pause after each retry. Perhaps removing this pause and leaving the retry decision to the user would be better, ensuring quicker feedback. I'll make that update.
> 
> Regarding the firewall, desktop environments can indeed be restrictive. While the backend supports mobile devices in the receiver server mode to bypass the firewall restrictions, the frontend hasn't incorporated this option yet. cc @cammellos @John-44
> 
> Another area of improvement is the error messages we display. When the client receives a connection error from signal, we should also notify the user if the firewall is active and if in the same LAN etc.

@qfrank if some desktop design work is needed here, @benjthayer is the person to ping.  Improving error messages is a good idea.  

Ideally the whole pairing process should require as little user intervention as possible.  I don't know what 'receiver server mode' is, but is it something that could either be enabled all the time, or automatically enabled without user intervention after a few attempts to connect fail?  e.g. does enabling 'receiver server mode' require any new UI, or is there a way it can be utilized without adding anything to the UI?

**Comment by qfrank** [comment]
> Would there be any way to automatically enable 'receiver server mode' without adding anything to the UI?

i'd say no, because there's no way to communicate between mobile and desktop in that case cause of the firewall, so we need new UI support for mobile and desktop since when `receiver server mode` enabled on mobile, desktop need to know the corresponding QR code or sync code that comes from mobile to send data to mobile

**Comment by ilmotta** [comment]
@qfrank, do you know if I can force the mobile client to search for a specific port while attempting to sync with desktop? Maybe a setting I can enable at build time? cc @Samyoul

I understand this is not a proper solution for end-users, but it would be great for some users like me if they could open only one port instead of having to disable their entire firewall (even if temporarily) to sync.

**Comment by churik** [comment]
Tested on all directions between Status Desktop master, IOS PR build, Android PR build.

**Comment by qfrank** [comment]
> @qfrank, do you know if I can force the mobile client to search for a specific port while attempting to sync with desktop? Maybe a setting I can enable at build time? cc @Samyoul
> 
> I understand this is not a proper solution for end-users, but it would be great for some users like me if they could open only one port instead of having to disable their entire firewall (even if temporarily) to sync.

100% you can but need some modifications to the code of `status-go` , but this answer seems like i didn't say anything because you need change the code 😅

**Comment by ilmotta** [comment]
> > @qfrank, do you know if I can force the mobile client to search for a specific port while attempting to sync with desktop? Maybe a setting I can enable at build time? cc @Samyoul
> > I understand this is not a proper solution for end-users, but it would be great for some users like me if they could open only one port instead of having to disable their entire firewall (even if temporarily) to sync.
> 
> 100% you can but need some modifications to the code of `status-go` , but this answer seems like i didn't say anything because you need change the code 😅

It's a good direction already @qfrank, now I know there's no setting available. Thanks! I will dig a little bit.

**Review by siddarthkay — APPROVED** [review]
GG 🚀

**Comment by qfrank** [comment]
Hi @status-im/mobile-qa , could you help check the result of e2e ? because `status-go` rebased , thank you

**Comment by pavloburykh** [comment]
> Hi @status-im/mobile-qa , could you help check the result of e2e ? because `status-go` rebased , thank you

Hi @qfrank! E2E results look good. Fails are not PR related.

**Pull request merged**
