### PR TITLE
Fix ParseJail in when running with JSC jail

### PR DESCRIPTION
**Pull request by rasom**
addresses #2661 

Unfortunately we experience deadlock when instantiate 4-5 JSContext objects in parallel, and this is not going to be fixed in JSC wrapper which we are using https://github.com/ericwlange/AndroidJSCore/issues/44#issuecomment-260559230 . 
We can fix it by making `parseJail` calls in the same thread.

status: ready

### CODE REVIEW

**Comment by oskarth** [comment]
How about a thread pool with max count?

**Review by janherich — APPROVED** [review]

**Comment by oskarth** [comment]
https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/Executors.html#newFixedThreadPool-int-

https://developer.android.com/reference/java/util/concurrent/Executors.html

https://www.concretepage.com/java/newfixedthreadpool_java

**Comment by rasom** [comment]
@oskarth thread pool with max count 1? This can happen with two parallel threads as well. We probably can add some kind of queue here, though from JS env this code is async anyway so i'm not sure what advantages we have in this case.

**Comment by oskarth** [comment]
@rasom 

> when instantiate 4-5 JSContext objects in parallel,

I thought it was one JSContext per thread.

> This can happen with two parallel threads as well

I.e. main thread and then spawn one for each call to `parseJail`? OK, didn't realize.

> add some kind of queue here

Visibility into it being blocking (print queue depth if > N to error log), but I think you are right when it comes to actual code execution.

**Review by oskarth — APPROVED** [review]

**Comment by rasom** [comment]
>Branch: bugfix/#2661
Android: https://i.diawi.com/UypGmR
iOS: https://i.diawi.com/2fowUB

**Pull request merged**
