### PR TITLE
[WIP] remove crypto

### PR DESCRIPTION
**Pull request by yenda**
- remove crypto libraries and nodeify hack
- rewrite whisper code to clarify control flow and ease development of future improvements
- add many topics

status: wip

### CODE REVIEW

**Comment by oskarth** [comment]
@yenda Can you please update PR description? What issue is this tied to and why are we doing this now?

**Comment by janherich** [comment]
@yenda what's the status of this and how it's related to separate PR just removing the `nodify` hack ?

**Comment by jeluard** [comment]
@yenda Is this still relevant?

**Comment by oskarth** [comment]
PR over 2 months old, closing. If you feel this is in error, please re-open.

**Pull request closed without merging**
