### PR TITLE
Prevent Unintended Clearing of Previous Community Notifications

### LINKED ISSUE #17052: All replies and mentions are removed in AC for receiver after sender removes the last message in community chat
### Steps to reproduce:
1. `User_A` and `User_B` are both in the same community.
2. `User_A` sends several replies or mentions to `User_B`.
3. `User_A` sends one more message and then deletes it using the 'delete for everyone' option.
4. `User_B` checks the AC.

### Actual result:
All mentions and replies in the AC are removed for `User_B`.

### Expected result:
Mentions and replies should not be removed from the AC after the last message is deleted.

### Additional info:
This issue is similar in group chats, with the exception that only replies are removed from the AC. Mentions are not removed and

### PR DESCRIPTION
**Pull request by ajayesivan**
Fixes #17052

status-go PR: https://github.com/status-im/status-go/pull/4276

### CODE REVIEW

**Review by qfrank — APPROVED** [review]

**Review by mohsen-ghafouri — APPROVED** [review]

**Comment by VolodLytvynenko** [comment]
Hi @ajayesivan could you rebase please, [this](https://github.com/status-im/status-go/pull/4276) status go PR

**Comment by VolodLytvynenko** [comment]
@ajayesivan kindly take a look that the status go PR  https://github.com/status-im/status-go/pull/4276 has not been reviewed yet. We can't perform testing until both PRs (status go and develop) are reviewed. Thanx

**Comment by flexsurfer** [comment]
hey @ajayesivan still relevant?

**Comment by ajayesivan** [comment]
@flexsurfer yes, but I need to update the status-go PR. I will close this one for now & re-open it once the go PR is ready for review.

**Pull request closed without merging**
