### PR TITLE
[FIX #1668] Prevent UI keys from propagating to account model.

### LINKED ISSUE #1668: Error (red screen) on update account name
### User Story

As a user I want to update my account name

### Description

*Type*: Bug

#### Expected behavior
The name is updated, no errors shown.

#### Actual behavior
The error is shown. Name isn't updated.

### Reproduction
Open Status
Log in
Open profile panel and choose Edit (name)
Type in new name
Tap Submit

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: ...
latest develop 8ac1535dab2f7a4b3bf5bbf42171c078e68c14ac
* Operating System: Android

#### Logs

[comment]: # (if on Android please replicate bug whilst running adb logcat)
```
...
```

### PR DESCRIPTION
**Pull request by x-goose-x**
The ```:account-update``` event was being passed the key
```update-status?``` which has nothing to do with an account as
represented in the db. This resulted in a spec failure when this
key was detected on an attempt to save changes.

I've sanitized this event by pulling out the three account keys,
```[:name :photo-path :status]```
that are relevant to ```profile``` and ensuring that only they get
passed to ```:account-update```.

Profile updates now work as expected.

#1668 

### Summary:
- Update status fails due to spec failing the account model.
- We were leaking keys from the profile view to update-account
- I've constrained these keys.

### Steps to test:
- Open Status
- Login to a user
- Attempt to change status
- change should commit correctly

status: ready

### CODE REVIEW

**Comment by jeluard** [comment]
We started adding `re-frame` tests for new code / fixes. Do you mind adding a simple one for this?

**Comment by x-goose-x** [comment]
👍 Sure thing

**Comment by x-goose-x** [comment]
@jeluard I've added some tests

**Review by jeluard — APPROVED** [review]

**Review by rasom — APPROVED** [review]

**Review by flexsurfer — APPROVED** [review]

**Comment by asemiankevich** [comment]
I can't reproduce the issue anymore. Neither real devices nor emulators

**Pull request merged**
