### PR TITLE
Create nl.cljs

### PR DESCRIPTION
**Pull request by Aweyon**
[comment]: # (Please replace ... with your information. Remove < and >)
[comment]: # (To auto-close issue on merge, please insert the related issue number after # i.e fixes #566)
fixes #...

### Summary:
[comment]: # (Summarise the problem and how the pull request solves it)
...

### Steps to test:
- Open Status
- ...
- Step 3, etc.

[comment]: # (PRs will only be accepted if squashed into single commit.)
status: <ready|wip>

### CODE REVIEW

**Comment by mrqupie** [comment]
Aweyon, I think it would be better if we colaborate on one version of this. Because I changed a couple of your translation which either was not correct or was not formal or polite. Would be better to colaborate than work in two different files :) 

Please see my changes here: https://github.com/status-im/status-react/pull/1293#partial-pull-merging

**Comment by Aweyon** [comment]
Hey,

No problem for me!

About the formality factor, I’m still wondering: does it have to be this formal? I was considering “u, uw, …” as well, but when I was starting to compare to the original English file, there are quite a few informal sentences/words written. Such as “phew”, “oops”, “gotcha, “gimmie a sec” etc… For me, this indicates that the ambiance of the program shouldn’t be too formal in my opinion.. But I guess this is open for discussion. What do you think about this?

Regards,
Jens

**Comment by mrqupie** [comment]
Thank you for the reply! 

Yeah I can see where you are going with that. I honest am quite in the middle as well. But because the "how to contribute" wiki clearly stated the same example in Afrikaans (south afrika) I thought that would be the way to go. 

We could discuss it on the slack 

I will give you some love on there ;) 

Please let me know if there is anything you would like some feedback on. A peer review is always nice to have. 

Cheers, 

Joost

**Comment by MrLuit** [comment]
Outdated (#1356)

**Comment by flexsurfer** [comment]
hi @Aweyon, thank you for your contribution, unfortunately, there are conflicts, could you please resolve conflicts, and we can merge this PR

**Comment by flexsurfer** [comment]
@Aweyon  we'll close this PR, please reopen it or open new one, thank you

**Pull request closed without merging**
