### PR TITLE
[Fix #2640] Cleanup react-native source folder

### LINKED ISSUE #2640: Cleanup react-native source folder
### User Story

As a developer, I want to remove useless code.

### Description

React Native way of loading images (via `require`) used to be an issue when running tests under `nodejs`. This is not the case anymore.

Code in [react-native/resources](https://github.com/status-im/status-react/blob/develop/react-native/src/status_im/react_native/resources.cljs) should be integrated in the main `src` structure. Remove the now useless [test glue](https://github.com/status-im/status-react/blob/develop/test/cljs/status_im/react_native/resources.cljs) and make sure tests still pass.

### PR DESCRIPTION
**Pull request by foopang**
Fix #2640

### CODE REVIEW

**Comment by jeluard** [comment]
Thanks @foopang for the PR! Part of the cleanup also involves moving the associated code from `react-native/src` to `src`. 
Do you mind looking at that?

**Comment by foopang** [comment]
@jeluard I just moved everything from `react-native/src` to `src`, is that what you want?

**Comment by jeluard** [comment]
Only `resources.clj` have to be moved. I don't think compilation and tests will run with your changes (`lein test-cljs`).

**Comment by foopang** [comment]
Oops...sorry. Updated but the tests didn't pass yet when I ran the command `lein test-cljs`. Did I miss anything?

```
➜  status-react git:(fix/issue-2640) ✗ lein test-cljs
WARNING: Protocol IFn implements method -invoke with variadic signature (&) at line 61 target/test/reagent/impl/util.cljs

;; ======================================================================
;; Testing with Node:


Testing status-im.test.utils.async

Testing status-im.test.chat.events

Testing status-im.test.accounts.events
re-frame: overwriting :fx handler for: { ns: 'status-im.ui.screens.events',
  name: 'init-store',
  fqn: 'status-im.ui.screens.events/init-store',
  _hash: 171106879,
  'cljs$lang$protocol_mask$partition0$': 2153775105,
  'cljs$lang$protocol_mask$partition1$': 4096 }
re-frame: overwriting :fx handler for: { ns: 'status-im.ui.screens.accounts.events',
  name: 'save-account',
  fqn: 'status-im.ui.screens.accounts.events/save-account',
  _hash: -1683670095,
  'cljs$lang$protocol_mask$partition0$': 2153775105,
  'cljs$lang$protocol_mask$partition1$': 4096 }
re-frame: overwriting :fx handler for: { ns: 'status-im.ui.screens.accounts.events',
  name: 'broadcast-account-update',
  fqn: 'status-im.ui.screens.accounts.events/broadcast-account-update',
  _hash: -2092772778,
  'cljs$lang$protocol_mask$partition0$': 2153775105,
  'cljs$lang$protocol_mask$partition1$': 4096 }
re-frame: overwriting :fx handler for: { ns: 'status-im.ui.screens.accounts.events',
  name: 'send-keys-update',
  fqn: 'status-im.ui.screens.accounts.events/send-keys-update',
  _hash: -1760970941,
  'cljs$lang$protocol_mask$partition0$': 2153775105,
  'cljs$lang$protocol_mask$partition1$': 4096 }
re-frame: overwriting :cofx handler for: { ns: null,
  name: 'get-new-keypair!',
  fqn: 'get-new-keypair!',
  _hash: -115952907,
  'cljs$lang$protocol_mask$partition0$': 2153775105,
  'cljs$lang$protocol_mask$partition1$': 4096 }
re-frame: overwriting :cofx handler for: { ns: 'status-im.ui.screens.accounts.events',
  name: 'get-all-accounts',
  fqn: 'status-im.ui.screens.accounts.events/get-all-accounts',
  _hash: 1729634892,
  'cljs$lang$protocol_mask$partition0$': 2153775105,
  'cljs$lang$protocol_mask$partition1$': 4096 }
DEBUG [status-im.utils.handlers:29] - Handling re-frame event:  :initialize-db
DEBUG [status-im.utils.handlers:29] - Handling re-frame event:  :set
DEBUG [status-im.utils.handlers:29] - Handling re-frame event:  :load-accounts
DEBUG [status-im.utils.handlers:29] - Handling re-frame event:  :add-account
DEBUG [status-im.utils.handlers:29] - Handling re-frame event:  :account-update-keys

Testing status-im.test.profile.events
re-frame: overwriting :fx handler for: { ns: 'status-im.ui.screens.events',
  name: 'init-store',
  fqn: 'status-im.ui.screens.events/init-store',
  _hash: 171106879,
  'cljs$lang$protocol_mask$partition0$': 2153775105,
  'cljs$lang$protocol_mask$partition1$': 4096 }
re-frame: overwriting :fx handler for: { ns: 'status-im.ui.screens.accounts.events',
  name: 'save-account',
  fqn: 'status-im.ui.screens.accounts.events/save-account',
  _hash: -1683670095,
  'cljs$lang$protocol_mask$partition0$': 2153775105,
  'cljs$lang$protocol_mask$partition1$': 4096 }
DEBUG [status-im.utils.handlers:29] - Handling re-frame event:  :initialize-db
DEBUG [status-im.utils.handlers:29] - Handling re-frame event:  :add-account
DEBUG [status-im.utils.handlers:29] - Handling re-frame event:  :initialize-account-db
DEBUG [status-im.utils.handlers:29] - Handling re-frame event:  :my-profile/edit-profile
DEBUG [status-im.utils.handlers:29] - Handling re-frame event:  :navigate-to
DEBUG [status-im.utils.handlers:29] - Handling re-frame event:  :my-profile/update-status
DEBUG [status-im.utils.handlers:29] - Handling re-frame event:  :my-profile/save-profile
DEBUG [status-im.utils.handlers:29] - Handling re-frame event:  :broadcast-status
DEBUG [status-im.utils.handlers:29] - Handling re-frame event:  :navigate-back
DEBUG [status-im.utils.handlers:29] - Handling re-frame event:  :my-profile.drawer/edit-status
DEBUG [status-im.utils.handlers:29] - Handling re-frame event:  :my-profile.drawer/update-status
DEBUG [status-im.utils.handlers:29] - Handling re-frame event:  :my-profile.drawer/save-status
DEBUG [status-im.utils.handlers:29] - Handling re-frame event:  :broadcast-status

Testing status-im.test.wallet.events
re-frame: overwriting :fx handler for: { ns: 'status-im.ui.screens.events',
  name: 'init-store',
  fqn: 'status-im.ui.screens.events/init-store',
  _hash: 171106879,
  'cljs$lang$protocol_mask$partition0$': 2153775105,
  'cljs$lang$protocol_mask$partition1$': 4096 }
re-frame: overwriting :fx handler for: { ns: null,
  name: 'get-prices',
  fqn: 'get-prices',
  _hash: 1105304157,
  'cljs$lang$protocol_mask$partition0$': 2153775105,
  'cljs$lang$protocol_mask$partition1$': 4096 }
re-frame: overwriting :fx handler for: { ns: null,
  name: 'get-balance',
  fqn: 'get-balance',
  _hash: -1283722258,
  'cljs$lang$protocol_mask$partition0$': 2153775105,
  'cljs$lang$protocol_mask$partition1$': 4096 }
DEBUG [status-im.utils.handlers:29] - Handling re-frame event:  :initialize-db
DEBUG [status-im.utils.handlers:29] - Handling re-frame event:  :update-balance-fail
DEBUG [status-im.ui.screens.wallet.events:146] - Unable to get balance:  failed balance update
DEBUG [status-im.utils.handlers:29] - Handling re-frame event:  :update-wallet
DEBUG [status-im.utils.handlers:29] - Handling re-frame event:  :update-prices-fail
DEBUG [status-im.ui.screens.wallet.events:176] - Unable to get prices:  failed price update

Testing status-im.test.data-store.realm.core

Testing status-im.test.bots.events

Testing status-im.test.wallet.transactions.subs

FAIL in (group-transactions-by-date) (cljs/test.cljs:476:9)
expected: (= (transactions-subs/group-transactions-by-date transactions) grouped-transactions)
  actual: (not (= ({:title "20 Sep", :key :20170920, :data ({:timestamp "1505912551000"})} {:title "19 Sep", :key :20170919, :data ({:timestamp "1505764322000"})} {:title "18 Sep", :key :20170918, :data ({:timestamp "1505750000000"})}) ({:title "20 Sep", :key :20170920, :data ({:timestamp "1505912551000"})} {:title "18 Sep", :key :20170918, :data ({:timestamp "1505764322000"} {:timestamp "1505750000000"})})))

Testing status-im.test.wallet.transactions.views

Testing status-im.test.chat.models.input

Testing status-im.test.i18n

Testing status-im.test.utils.utils

Testing status-im.test.utils.money

Testing status-im.test.utils.clocks

Testing status-im.test.utils.ethereum.eip681

Testing status-im.test.utils.ethereum.core

Testing status-im.test.utils.random

Testing status-im.test.utils.gfycat.core

Testing status-im.test.utils.signing-phrase.core

Testing status-im.test.utils.transducers

Ran 48 tests containing 303 assertions.
1 failures, 0 errors.
Error encountered performing task 'doo' with profile(s): 'test'
Subprocess failed
```

**Comment by jeluard** [comment]
@foopang Failing tests doesn't seem related to me so I would say it's fine. Let me get some more feedback.

**Comment by jeluard** [comment]
@foopang Do you have errors running tests with `develop` (i.e. without your changes) ?)

**Comment by andytudhope** [comment]
@jeluard I have been getting this feedback when running `lein test-cljs` on `develop` for a few days now. No tests fail and slightly different to what is above, but worth looking at:
```
Testing status-im.test.accounts.events
re-frame: overwriting :fx handler for: { ns: 'status-im.ui.screens.events',
  name: 'init-store',
  fqn: 'status-im.ui.screens.events/init-store',
  _hash: 171106879,
  'cljs$lang$protocol_mask$partition0$': 2153775105,
  'cljs$lang$protocol_mask$partition1$': 4096 }
re-frame: overwriting :fx handler for: { ns: 'status-im.ui.screens.accounts.events',
  name: 'save-account',
  fqn: 'status-im.ui.screens.accounts.events/save-account',
  _hash: -1683670095,
  'cljs$lang$protocol_mask$partition0$': 2153775105,
  'cljs$lang$protocol_mask$partition1$': 4096 }
re-frame: overwriting :fx handler for: { ns: 'status-im.ui.screens.accounts.events',
  name: 'broadcast-account-update',
  fqn: 'status-im.ui.screens.accounts.events/broadcast-account-update',
  _hash: -2092772778,
  'cljs$lang$protocol_mask$partition0$': 2153775105,
  'cljs$lang$protocol_mask$partition1$': 4096 }
re-frame: overwriting :fx handler for: { ns: 'status-im.ui.screens.accounts.events',
  name: 'send-keys-update',
  fqn: 'status-im.ui.screens.accounts.events/send-keys-update',
  _hash: -1760970941,
  'cljs$lang$protocol_mask$partition0$': 2153775105,
  'cljs$lang$protocol_mask$partition1$': 4096 }
re-frame: overwriting :cofx handler for: { ns: null,
  name: 'get-new-keypair!',
  fqn: 'get-new-keypair!',
  _hash: -115952907,
  'cljs$lang$protocol_mask$partition0$': 2153775105,
  'cljs$lang$protocol_mask$partition1$': 4096 }
re-frame: overwriting :cofx handler for: { ns: 'status-im.ui.screens.accounts.events',
  name: 'get-all-accounts',
  fqn: 'status-im.ui.screens.accounts.events/get-all-accounts',
  _hash: 1729634892,
  'cljs$lang$protocol_mask$partition0$': 2153775105,
  'cljs$lang$protocol_mask$partition1$': 4096 }

Testing status-im.test.profile.events
re-frame: overwriting :fx handler for: { ns: 'status-im.ui.screens.events',
  name: 'init-store',
  fqn: 'status-im.ui.screens.events/init-store',
  _hash: 171106879,
  'cljs$lang$protocol_mask$partition0$': 2153775105,
  'cljs$lang$protocol_mask$partition1$': 4096 }
re-frame: overwriting :fx handler for: { ns: 'status-im.ui.screens.accounts.events',
  name: 'save-account',
  fqn: 'status-im.ui.screens.accounts.events/save-account',
  _hash: -1683670095,
  'cljs$lang$protocol_mask$partition0$': 2153775105,
  'cljs$lang$protocol_mask$partition1$': 4096 }

Testing status-im.test.wallet.events
re-frame: overwriting :fx handler for: { ns: 'status-im.ui.screens.events',
  name: 'init-store',
  fqn: 'status-im.ui.screens.events/init-store',
  _hash: 171106879,
  'cljs$lang$protocol_mask$partition0$': 2153775105,
  'cljs$lang$protocol_mask$partition1$': 4096 }
re-frame: overwriting :fx handler for: { ns: null,
  name: 'get-prices',
  fqn: 'get-prices',
  _hash: 1105304157,
  'cljs$lang$protocol_mask$partition0$': 2153775105,
  'cljs$lang$protocol_mask$partition1$': 4096 }
re-frame: overwriting :fx handler for: { ns: null,
  name: 'get-balance',
  fqn: 'get-balance',
  _hash: -1283722258,
  'cljs$lang$protocol_mask$partition0$': 2153775105,
  'cljs$lang$protocol_mask$partition1$': 4096 }
```

**Comment by jeluard** [comment]
@foopang Apparently this is because of your timezone so we are good.
@andytudhope Yes this is a known `re-frame`issue unfortunately

**Review by jeluard — APPROVED** [review]

**Comment by rasom** [comment]
was built succesfully
```
Branch: foopang:fix/issue-2640
Android: https://i.diawi.com/xnqfRj
iOS: https://i.diawi.com/2iKyJ5
```

**Review by rasom — APPROVED** [review]

**Pull request merged**
