### PR TITLE
[#4492]: Invalid values for `gas limit` and `gas price` are immediately replaced by default ones instead of warning

### LINKED ISSUE #4492: Invalid values for `gas limit` and `gas price` are immediately replaced by default ones instead of warning
### Description

*Type*: Bug

*Summary*:  Value of Gas price is reverted to default one if user is typing inside the field and made some mistake, so value becomes invalid. E.g. typing 0,00034222 and then typing second comma will lead to having a new value inside the field, so user need to start typing again.
Same happens for Gas limit field.

#### Expected behavior
User gets warning that amount is invalid and can correct incorrect value. Field should not get a new value as soon as user typed invalid one. 

#### Actual behavior
As soon as user types invalid value inside Gas price or Gas limit fields value is replaced with default one.
e.g. user typed "0,," and it's replaced with 0.0060465 (or other value)

### Reproduction

- Open Status
- Open Wallet -> Send transaction
- Tap Advanced -> Transaction fee
- Inside Gas price: delete default value, type 0,, and watch the content of the field

### Additional Information
* Status version: nightly build May 28
* Operating System: Android and iOS

### PR DESCRIPTION
**Pull request by alwx**
Fixes #4492 
Status: ready

### CODE REVIEW

**Review by janherich — APPROVED** [review]

**Review by goranjovic — APPROVED** [review]

**Review by mandrigin — APPROVED** [review]

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/kfRPkw for branch PR-4514

<blockquote><div><strong><a href="https://i.diawi.com/kfRPkw">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/PGbkah for branch PR-4514

<blockquote><div><strong><a href="https://i.diawi.com/PGbkah">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/uFdNFB for branch PR-4514

<blockquote><div><strong><a href="https://i.diawi.com/uFdNFB">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/6gumcJ for branch PR-4514

<blockquote><div><strong><a href="https://i.diawi.com/6gumcJ">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by asemiankevich** [comment]
@alwx @annadanchenko i would like to see the error messages unified across the wallet at least.
is it possible to do so?

image

image

**Comment by alwx** [comment]
@asemiankevich @annadanchenko I am afraid the phrase is too long for this half-screen inputs.

**Comment by asemiankevich** [comment]
@alwx yeah i agree :( lets move it then further.

**Pull request merged**
