### PR TITLE
Add ethereum/poll-logs event, fixes #6855

### LINKED ISSUE #6855: Add ethereum/poll-logs events
### User Story

As a developer, I want an event to poll ethereum logs. 
Events for logs, blocks and pending transactions should be provided.
`poll-logs` should follow the syntax used by  [logs](https://github.com/status-im/status-react/pull/6852#issuecomment-441099743)

Internally those events will periodically call `eth_getFilterChanges` to get latest changes.
Periodicity can be configured by users.

```clojure
[ethereum/poll-logs {:value [{:type "uint256" :values ["125"]}] :on-result [some-event]}]
```

`on-result` should be called per result (so array results should be unrolled).

Cancels calls `eth_uninstallFilter` and terminates the internal polling.

```clojure
[ethereum/cancel-poll-logs {:value id}]
```

Resources:

* https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_getfilterchanges
* https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_newpendingtransactionfilter
* https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_newblockfilter
* https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_newblockfilter

### Description

*Type*: Feature

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/ethereum/wiki">ethereum/wiki</a></strong></div><div>The Ethereum Wiki. Contribute to ethereum/wiki development by creating an account on GitHub.</div></blockquote>
<blockquote><div> GitHub</div><div><strong><a href="https://github.com/ethereum/wiki">ethereum/wiki</a></strong></div><div>The Ethereum Wiki. Contribute to ethereum/wiki development by creating an account on GitHub.</div></blockquote>
<blockquote><div> GitHub</div><div><strong><a href="https://github.com/ethereum/wiki">ethereum/wiki</a></strong></div><div>The Ethereum Wiki. Contribute to ethereum/wiki development by creating an account on GitHub.</div></blockquote>

### PR DESCRIPTION
**Pull request by 3ach**
[comment]: # (Please replace ... with your information. Remove < and >)
[comment]: # (To auto-close issue on merge, please insert the related issue number after # i.e fixes #566)

Fixes #6855

[comment]: # (Summarise the problem and how the pull request solves it)
Adds the ethereum poll-logs event, the new-pending-transaction-filter
event, and the new-block-filter event. 

Also adds the cancel-filter event (not yet done)

status: wip

### CODE REVIEW

**Comment by asemiankevich** [comment]
@jeluard is `skip-manual-qa` label missing here? :)

**Comment by asemiankevich** [comment]
@jeluard @flexsurfer please add review here. Not sure why it is in TO TEST without review

**Comment by jeluard** [comment]
Because I need the build

**Comment by jeluard** [comment]
@zachzundel Could you update the event properties to `type`, `from`, `to`, `block-hash` ? In general simple, short and dash based if 2 words are needed. Thanks!

**Comment by 3ach** [comment]
Yes, will do! I’m still working on building a test extension also.

**Comment by 3ach** [comment]
Hi @jeluard, I've implemented the name changes you asked for.

**Review by jeluard — APPROVED** [review]

**Review by flexsurfer — APPROVED** [review]

**Review by goranjovic — APPROVED** [review]

**Pull request merged**
