### PR TITLE
[#18777] Fix exception while calling `money/mul` on `nil` values

### LINKED ISSUE #18777: "times() not number: null" error occurs after returning from the backround
Unfortunately, the provided steps do not accurately reproduce the issue. Hopefully, the logs can help to understand what's going wrong

### Steps:
1. Recover the user with available assets.
2. Go to the 'Select assets' page.
3. Put the application in the background.
4. Wait for at least 10 - 15 minutes.
5. Return from the background.

### Actual result:
The "times() not number: null" error occurs after returning from the backround 

https://github.com/status-im/status-mobile/assets/52490791/8a9ac532-8eed-4cc5-a9e4-96affd03a4dd

### Expected result:
No error should occur after returning from the background.

### Logs:
[Status-debug-logs (2).zip](https://github.com/status-im/status-mobile/files/14223505/Status-debug-logs.2.zip)

### PR DESCRIPTION
**Pull request by ulisesmac**
fixes #18777

### Summary

This PR solves the exception thrown, but I wasn't able to replicate the problem.

It seems the user's tokens lack of the market values, or sometimes other token values are `nil`. This PR makes the funciton `mul` able to work with `nil` and treats it as `0` (same as Clojure's `*`).

### Testing notes
When the issue is replicated, some balances should become zero, the difference is the app isn't crashing now.

### Steps to test

Please follow the steps reported in the issue description, the exception shouldn't be thrown, I couldn't replicate it.

status: ready

### CODE REVIEW

**Review by Parveshdhull — APPROVED** [review]
Hi @ulisesmac, Thank you very much for fixing the issue.

**Comment by Parveshdhull** [comment]
> I think the main problems are in utils.money and status-im.contexts.wallet.common.utils. We have so many js function calls there, without nil checks, I think we should fix them first.

https://github.com/status-im/status-mobile/pull/18532#issuecomment-1911736872

@J-Son89 Should we create an issue, so that we fix these files in one go, instead of applying fixes when we get exceptions?

**Review by smohamedjavid — APPROVED** [review]

**Comment by J-Son89** [comment]
> > I think the main problems are in utils.money and status-im.contexts.wallet.common.utils. We have so many js function calls there, without nil checks, I think we should fix them first.
> 
> 
> 
> https://github.com/status-im/status-mobile/pull/18532#issuecomment-1911736872
> 
> 
> 
> @J-Son89 Should we create an issue, so that we fix these files in one go, instead of applying fixes when we get exceptions?

Yeah makes sense, we should also make sure there's sufficient test coverage on these too

**Comment by ulisesmac** [comment]
I'm closing this PR because this same fix has been already applied in develop in 7d6b2ac87a4dfd869cebf1be01d252304f17b959

**Pull request closed without merging**
