### PR TITLE
Disable geth.log in release builds. Fixes #4782

### LINKED ISSUE #4782: geth.log is present for release build
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug
[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*:  geth.log is created for release build. It should not be available on release builds.

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
No geth.log
#### Actual behavior
[comment]: # (Describe what actually happened.)
Android: Downloads -> geth.log
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Install Status
- Give Storage permission to the Status app
- Run the app
- Check Downloads -> geth.log

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version:  release build 2 for 0.9.20
[comment]: # (Android or iOS.)
* Operating System: Android

### PR DESCRIPTION
**Pull request by pedropombeiro**
This PR disables geth.log generation in status-go.

### CODE REVIEW

**Review by rasom — APPROVED** [review]

**Comment by annadanchenko** [comment]
@PombeirP unfortunately, after installing apk on Android real device and giving Storage permission in OS settings to Status app - there is geth.log created in Downloads folder. Tried same scenario twice.

**Comment by pedropombeiro** [comment]
@annadanchenko does it have any content though, or is it empty?

**Comment by annadanchenko** [comment]
@PombeirP yes it does contain content. So, if give Storage permission to the app, restart the app and create an account in Status then log contains:
```
t=2018-06-15T17:47:25+0000 lvl=info msg="Status service api is disabled" package=status-go/node
t=2018-06-15T17:47:25+0000 lvl=info msg="Starting peer-to-peer node"     instance=StatusIM/v0.9.9-a339d7e/android-arm/go1.10.1
t=2018-06-15T17:47:25+0000 lvl=info msg="Starting P2P networking"
t=2018-06-15T17:47:26+0000 lvl=info msg="App State changed"              package=status-go/api.StatusBackend new-state=background
t=2018-06-15T17:47:28+0000 lvl=info msg="UDP listener up"                net=enode://23be2802dfb0618e40ca903927904fec121fac13e79fe251d71e769eef09114520de01fe9a160a72af64fb9b19f971aa50b4ee4060aba9601a0c0cd5884c4ddb@[::]:46264
t=2018-06-15T17:47:28+0000 lvl=info msg="started whisper v.6.0"
t=2018-06-15T17:47:28+0000 lvl=info msg="RLPx listener up"               self="enode://23be2802dfb0618e40ca903927904fec121fac13e79fe251d71e769eef09114520de01fe9a160a72af64fb9b19f971aa50b4ee4060aba9601a0c0cd5884c4ddb@[::]:37846?discport=0"
t=2018-06-15T17:47:28+0000 lvl=info msg="Handlers registered"            package=status-go/api.StatusBackend
t=2018-06-15T17:47:28+0000 lvl=info msg="Account reselected"             package=status-go/api.StatusBackend
t=2018-06-15T17:47:28+0000 lvl=info msg="Difference with ntp servers"    offset=-2.760918284s
t=2018-06-15T17:47:33+0000 lvl=warn msg="message loop"                   peer=a1a8e2416266020e168a2257851cdb59cd951e822655730dc1bbd50adb892a6444987d3baece727ae83600e1db8db49a707012b7ebe6fd4eb3e350166fe55579 err=EOF
t=2018-06-15T17:47:33+0000 lvl=warn msg="message loop"                   peer=887cbd92d95afc2c5f1e227356314a53d3d18855880ac0509e0c0870362aee03939d4074e6ad31365915af41d34320b5094bfcc12a67c381788cd7298d06c875 err=EOF
t=2018-06-15T17:47:33+0000 lvl=warn msg="message loop"                   peer=4ea35352702027984a13274f241a56a47854a7fd4b3ba674a596cff917d3c825506431cf149f9f2312a293bb7c2b1cca55db742027090916d01529fe0729643b err=EOF
t=2018-06-15T17:47:33+0000 lvl=warn msg="message loop"                   peer=03f21684e777341df7f1b93888c9ba13a4d15130bb3c2d4fb13e817035b6cd6f3ed3dad1cd6c48dc995b17a2f4005188bae6d74d19d361a789c0f7085675a7f2 err=EOF
t=2018-06-15T17:47:33+0000 lvl=warn msg="message loop"                   peer=0440117a5bc67c2908fad94ba29c7b7f2c1536e96a9df950f3265a9566bf3a7306ea8ab5a1f9794a0a641dcb1e4951ce7c093c61c0d255f4ed5d2ed02c8fce23 err=EOF
t=2018-06-15T17:47:33+0000 lvl=warn msg="message loop"                   peer=66ba15600cda86009689354c3a77bdf1a97f4f4fb3ab50ffe34dbc904fac561040496828397be18d9744c75881ffc6ac53729ddbd2cdbdadc5f45c400e2622f7 err=EOF
t=2018-06-15T17:47:33+0000 lvl=warn msg="message loop"                   peer=4ea35352702027984a13274f241a56a47854a7fd4b3ba674a596cff917d3c825506431cf149f9f2312a293bb7c2b1cca55db742027090916d01529fe0729643b err=EOF
t=2018-06-15T17:47:33+0000 lvl=warn msg="message loop"                   peer=4e0a8db9b73403c9339a2077e911851750fc955db1fc1e09f81a4a56725946884dd5e4d11258eac961f9078a393c45bcab78dd0e3bc74e37ce773b3471d2e29c err=EOF
t=2018-06-15T17:47:34+0000 lvl=warn msg="message loop"                   peer=03f21684e777341df7f1b93888c9ba13a4d15130bb3c2d4fb13e817035b6cd6f3ed3dad1cd6c48dc995b17a2f4005188bae6d74d19d361a789c0f7085675a7f2 err=EOF
t=2018-06-15T17:47:34+0000 lvl=warn msg="message loop"                   peer=1d193635e015918fb85bbaf774863d12f65d70c6977506187ef04420d74ec06c9e8f0dcb57ea042f85df87433dab17a1260ed8dde1bdf9d6d5d2de4b7bf8e993 err=EOF
t=2018-06-15T17:47:34+0000 lvl=warn msg="message loop"                   peer=67f731dfdbd038ceae0213257aa83ec89cdb5ed8b3dc032a733044b8a0b44668263a5d06d73bebe4f8d139a6a1cd024956ff5fe6ccf24de4067e39da1c33df09 err=EOF
t=2018-06-15T17:47:36+0000 lvl=warn msg="message loop"                   peer=a1a8e2416266020e168a2257851cdb59cd951e822655730dc1bbd50adb892a6444987d3baece727ae83600e1db8db49a707012b7ebe6fd4eb3e350166fe55579 err=EOF
t=2018-06-15T17:47:36+0000 lvl=warn msg="message loop"                   peer=93d67ae104ab9f28afa253942c7f7efeac300fb2b2cce6e59e661b0781b94365c0d987498022d0a338e7497786cfe5d3fe891173109319b4f92bc7c6df504f73 err=EOF
t=2018-06-15T17:47:36+0000 lvl=warn msg="message loop"                   peer=1d193635e015918fb85bbaf774863d12f65d70c6977506187ef04420d74ec06c9e8f0dcb57ea042f85df87433dab17a1260ed8dde1bdf9d6d5d2de4b7bf8e993 err=EOF
t=2018-06-15T17:47:36+0000 lvl=warn msg="message loop"                   peer=4e0a8db9b73403c9339a2077e911851750fc955db1fc1e09f81a4a56725946884dd5e4d11258eac961f9078a393c45bcab78dd0e3bc74e37ce773b3471d2e29c err=EOF
t=2018-06-15T17:48:02+0000 lvl=info msg="App State changed"              package=status-go/api.StatusBackend new-state=active
t=2018-06-15T17:48:09+0000 lvl=info msg="Whisper identity selected"      id=c0bbb6d9ab8c5e0b2209d27e08d9bf8742c9276dd46681fe025762cebd706bc6 key=0x048ccc39acf1f974a32460dd9743ad2be42b696c1257be072ba8e10204eaae1c0e58f7aadf7e54b41f6fd80f258ef70843bcb62da49297278565096d22c2651ca7
t=2018-06-15T17:48:10+0000 lvl=info msg=RequestMessages                  package=status-go/services/sshext.PublicAPI request="{MailServerPeer:enode://015e22f6cd2b44c8a51bd7a23555e271e0759c7d7f52432719665a74966f2da456d28e154e836bee6092b4d686fe67e331655586c57b718be3997c1629d24167@35.226.21.19:30504 From:1528480090 To:1528566490 Topic:[248 148 106 172] SymKeyID:087c9d236a9c41e4b64cb7cb37bad7fcd81479d86397c78e82f73486bf364ee7}"
t=2018-06-15T17:48:10+0000 lvl=info msg=RequestMessages                  package=status-go/services/sshext.PublicAPI request="{MailServerPeer:enode://015e22f6cd2b44c8a51bd7a23555e271e0759c7d7f52432719665a74966f2da456d28e154e836bee6092b4d686fe67e331655586c57b718be3997c1629d24167@35.226.21.19:30504 From:1528566490 To:1528652890 Topic:[248 148 106 172] SymKeyID:087c9d236a9c41e4b64cb7cb37bad7fcd81479d86397c78e82f73486bf364ee7}"
t=2018-06-15T17:48:10+0000 lvl=info msg=RequestMessages                  package=status-go/services/sshext.PublicAPI request="{MailServerPeer:enode://015e22f6cd2b44c8a51bd7a23555e271e0759c7d7f52432719665a74966f2da456d28e154e836bee6092b4d686fe67e331655586c57b718be3997c1629d24167@35.226.21.19:30504 From:1528652890 To:1528739290 Topic:[248 148 106 172] SymKeyID:087c9d236a9c41e4b64cb7cb37bad7fcd81479d86397c78e82f73486bf364ee7}"
t=2018-06-15T17:48:10+0000 lvl=info msg=RequestMessages                  package=status-go/services/sshext.PublicAPI request="{MailServerPeer:enode://015e22f6cd2b44c8a51bd7a23555e271e0759c7d7f52432719665a74966f2da456d28e154e836bee6092b4d686fe67e331655586c57b718be3997c1629d24167@35.226.21.19:30504 From:1528739290 To:1528825690 Topic:[248 148 106 172] SymKeyID:087c9d236a9c41e4b64cb7cb37bad7fcd81479d86397c78e82f73486bf364ee7}"
t=2018-06-15T17:48:10+0000 lvl=info msg=RequestMessages                  package=status-go/services/sshext.PublicAPI request="{MailServerPeer:enode://015e22f6cd2b44c8a51bd7a23555e271e0759c7d7f52432719665a74966f2da456d28e154e836bee6092b4d686fe67e331655586c57b718be3997c1629d24167@35.226.21.19:30504 From:1528825690 To:1528912090 Topic:[248 148 106 172] SymKeyID:087c9d236a9c41e4b64cb7cb37bad7fcd81479d86397c78e82f73486bf364ee7}"
t=2018-06-15T17:48:10+0000 lvl=info msg=RequestMessages                  package=status-go/services/sshext.PublicAPI request="{MailServerPeer:enode://015e22f6cd2b44c8a51bd7a23555e271e0759c7d7f52432719665a74966f2da456d28e154e836bee6092b4d686fe67e331655586c57b718be3997c1629d24167@35.226.21.19:30504 From:1528912090 To:1528998490 Topic:[248 148 106 172] SymKeyID:087c9d236a9c41e4b64cb7cb37bad7fcd81479d86397c78e82f73486bf364ee7}"
t=2018-06-15T17:48:10+0000 lvl=info msg=RequestMessages                  package=status-go/services/sshext.PublicAPI request="{MailServerPeer:enode://015e22f6cd2b44c8a51bd7a23555e271e0759c7d7f52432719665a74966f2da456d28e154e836bee6092b4d686fe67e331655586c57b718be3997c1629d24167@35.226.21.19:30504 From:1528998490 To:1529084890 Topic:[248 148 106 172] SymKeyID:087c9d236a9c41e4b64cb7cb37bad7fcd81479d86397c78e82f73486bf364ee7}"
t=2018-06-15T17:48:17+0000 lvl=info msg="App State changed"              package=status-go/api.StatusBackend         new-state=background

```

**Comment by pedropombeiro** [comment]
My guess is that the builds that get put here don't use `.env.prod` Maybe @mandrigin knows?

**Comment by pedropombeiro** [comment]
Ah, it uses .env.jenkins. @annadanchenko I'll temporarily change .env.jenkins with the same change so we can tell if it has the desired effect, we can roll that back before merging.

**Comment by annadanchenko** [comment]
@PombeirP unfortunately, on new build account can't be created on both iOS and Android devices. As soon as password is provided, there is spinner shown for at least 5 minutes and nothing else happens.
geth.log is created in Downloads but is empty

TF session from Android device: https://app.testfairy.com/projects/4803622-status/builds/8496015/sessions/4394091657/?accessToken=bY-gkBICZCHC3rG-GlMR9hL7UL4

TF session for iOs device: https://app.testfairy.com/projects/4803590-status/builds/8496218/sessions/4394091790/?accessToken=cdjO8lfj8isRbminiBlg0jFxeIQ

<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803622-status/builds/8496015/sessions/4394091657/?accessToken=bY-gkBICZCHC3rG-GlMR9hL7UL4">TestFairy: Status 0.9.20 (6061) @254</a></strong></div></blockquote>

**Comment by pedropombeiro** [comment]
@annadanchenko :-( seems like we're running against some JSON validation:

```
06-15 22:14:57.480 13309 14092 E StatusModule: StartNode failed: {"error":"Key: 'NodeConfig.LogLevel' Error:Field validation for 'LogLevel' failed on the 'eq=ERROR|eq=WARN|eq=INFO|eq=DEBUG|eq=TRACE' tag"}
```

**Comment by pedropombeiro** [comment]
Shouldn't create a `geth.log` on Android anymore. I don't have macOS device to test with, but at most it should create an empty `geth.log`

**Comment by annadanchenko** [comment]
@PombeirP with the last fix all looks fine:
1. on Android there is no geth.log in Downloads
2. on iOS there is empty geth.log
Can create account, send/receive messages in 1:1 and public chat and transactions in 1:1 chat and in Wallet.

AFTER REMOVING CHANGE FOR .env.jenkins it's ok to merge

**Comment by pedropombeiro** [comment]
Removed .env.jenkins commit, ready to merge.

**Review by mandrigin — APPROVED** [review]
LGTM!

**Review by dmitryn — APPROVED** [review]

**Pull request merged**
