### PR TITLE
chore: add skeleton for sign in with syncing flow

### LINKED ISSUE #15403: Sign In Flow -> Create Skeleton of flow
related to: https://github.com/status-im/status-mobile/issues/15140

Create a basic outline of the Sign In Flow

Designs https://www.figma.com/file/o4qG1bnFyuyFOvHQVGgeFY/Onboarding-for-Mobile?node-id=3486%3A356922&t=ldoreLDhhzhrtWiH-0

### PR DESCRIPTION
**Pull request by J-Son89**
fixes: https://github.com/status-im/status-mobile/issues/15403

Create a quick outline for the Sign In Flow so that developers can work concurrently on this flow.

To test:
You can just check the old flows are working as expected. 
i.e I'm new to Status and then follow the three old flows

### CODE REVIEW

**Review by briansztamfater — APPROVED** [review]

**Review by jo-mut — APPROVED** [review]

**Review by ulisesmac — APPROVED** [review]
Looks good! it'll help a lot :100:

**Comment by pavloburykh** [comment]
hey @J-Son89 ! Is this PR ready for testing? Cause I see that it has been moved from E2E back to REVIEW column.

**Comment by J-Son89** [comment]
> hey @J-Son89 ! Is this PR ready for testing? Cause I see that it has been moved from E2E back to REVIEW column.

@pavloburykh, not sure if it was me who moved it back to Review column but yes this pr is ready for QA testing :)

**Review by smohamedjavid — APPROVED** [review]

**Comment by VolodLytvynenko** [comment]
hi @J-Son89 thanx for your work. No issues from my side. PR is ready to be merged

**Pull request merged**
