### PR TITLE
Other checkboxes are unselected when one checkbox is selected on the network preferences bottom sheet #19543

### LINKED ISSUE #19543: Other checkboxes are unselected when one checkbox is selected on the network preferences bottom sheet
### Preconditions:
 The user has an account with one or more networks selected.

### Steps to Reproduce:
1. Open the eth account Edit flow
2. Open the network preferences.
3. Check any checkbox.

### Actual Result:
When a checkbox is selected, other checkboxes are automatically unchecked.

https://github.com/status-im/status-mobile/assets/52490791/e9b8fcb8-79a4-4063-9f97-58a80bc5de39

### Expected Result:
After a checkbox is checked, it should not influence the unchecking of other checkboxes.

### ENV:
Nightly 5 Apr 2024

### PR DESCRIPTION
**Pull request by mmilad75**
fixes #19543 

Updated video:

https://github.com/status-im/status-mobile/assets/55688834/335f6316-98b8-49a0-ada6-df9c200e9c29

### CODE REVIEW

**Review by ibrkhalil — APPROVED** [review]

**Comment by shivekkhurana** [comment]
Hey, I like this UX more than the existing one, but there is some context to this feature. 

There are two broad perspectives on network selector:
1. When you select networks for your personal wallets (which will be all by default)
2. When you select networks for saved addresses, watch addresses etc (which will be none by default)

In the first case, when marking networks for your own wallets, the UI we had made sense. Ie, if you have only one network selected, and you deselect it, everything gets selected back by default. 

In the second case, the UI you have posted makes much more sense. 
I have talked to the design team and they said that the decision to have the janky checkbox behaviour came from higher up. 

I'm going to review this PR and then show it to the design team. Maybe we can get this version in.

I also feel that it's not worth the fight to convince everyone that this behaviour is better. An alternate strategy can be to make this component pure (right now it plugs into re-frame state). And then update all usages of this components pure. Then if we decide to change the component behaviour later, we will be able to do it easily.

**Review by J-Son89 — APPROVED** [review]
perhaps we can update the video? 🤔

**Comment by mmilad75** [comment]
> perhaps we can update the video? 🤔

Done

**Review by vkjr — APPROVED** [review]

**Comment by qoqobolo** [comment]
The issue is fixed, thank you @mmilad75!
PR can be merged.

**Review by ulisesmac — APPROVED** [review]

**Pull request merged**
