### PR TITLE
[experiment] render only viewable messages

### PR DESCRIPTION
**Pull request by rasom**
Locally in dev mode reduces number of UIManger calls (bridge) from ~2500 to 960 on opening pub chat with 20 messages.

before

after

## galaxy s9
before

after

### CODE REVIEW

**Comment by yenda** [comment]
what do you mean by viewable message?

**Comment by rasom** [comment]
@yenda "viewable" items of the list are shown on the screen
https://facebook.github.io/react-native/docs/flatlist#onviewableitemschanged

**Comment by yenda** [comment]
@rasom doesn't it affect scrolling then?

**Comment by rasom** [comment]
@yenda sure it affects

**Comment by rasom** [comment]
closing because #8191 looks better

**Pull request closed without merging**
