### PR TITLE
[experiment] advanced cljs compilation

### PR DESCRIPTION
**Pull request by rasom**
# Results

time between two events was measured
`ReactNative: ReactInstanceManager.ctor()` -> `ReactNativeJS: DEBUG [status-im.utils.handlers:34] - Handling re-frame event:  :init/app-started`

---

Simple cljs galaxy s9:
Intro screen: 3.65s, 3.5s, 3.6s; *average 3.583s*
Login screen (1 acc): 3.4s, 3.5s, 3.45s; *average 3.45s*

Advanced cljs galaxy s9:
Intro screen: 3.3s, 3.13s, 3.2s; *average 3.21s* **10.5% faster**
Login screen (1 acc): 2.95s, 2.88s, 2.94s; *average 2.923s* **15.3% faster**

---

Simple cljs samsung d500h:
Intro screen: 11.5s, 11.5s, 11.4s; *average 11.47*
Login screen (1 acc): 11.54s, 11.5s, 11.53s; *average 11.523s*

Advanced cljs samsung  d500h:
Intro screen: 9.9s, 9.7s, 9.65s; *average 9.75s* **15% faster**
Login screen (1 acc): 9.83s, 9.81s, 9.9s; *average 9.847s* **15.45% faster**

---

Advanced optimization makes loading of js code *11-15%* faster.

### CODE REVIEW

**Comment by yenda** [comment]
have you tried adding the `^js` type hint on the js functions that cause compilation warnings in advanced compilation when using :infer-externs :true and `*warn-on-infer*` set to true 

also do you think we could use shadow-cljs, it is also better for using js dependencies nowadays

**Comment by rasom** [comment]
@yenda well, not yet

**Comment by yenda** [comment]
@rasom asking because you wouldn't need an extern file then

**Comment by rasom** [comment]
@yenda I'll take a look tomorrow, the idea right now is rather to figure if it makes any difference

**Pull request closed without merging**
