### PR TITLE
status-im/utils/fx replaced with utils/re-frame to avoid ambiguities

### LINKED ISSUE #14569: Remove `<sub`, `>evt` functions in favor of ones from `utils.re-frame`
# Problem

`status-im.utils.fx` namespace contain helper functions `<sub`, `>evt` which are similar to `sub` `dispatch` functions in `utils.re-frame`. This causes ambiguity on what namespace should be used. 

## Implementation

Get rid of `status-im.utils.fx` namespace in favor of `utils.re-frame`

### PR DESCRIPTION
**Pull request by vkjr**
fixes #14569

### Summary
There was a duplicated functionality in the old and new versions of the code.

The old version had `status-im.utils.fx` and `status-im.utils.handlers`namespaces, while new code has`utils.re-frame` with the same content. Unfortunately dependencies on the old namespaces made their way to the new code.

So this PR entirely removes old namespaces to avoid ambiguities. `<sub` and `evt>` are gone. `fx/merge` and `fx/defn` are `rf/merge` and `rf/defn` respectively now.

status: ready

### CODE REVIEW

**Review by ilmotta — APPROVED** [review]
Well well done @vkjr! :parasol_on_ground:

**Review by J-Son89 — APPROVED** [review]

**Comment by flexsurfer** [comment]
did we removed status-im.utils.fx and status-im.utils.handlers i can't see in changes

**Review by flexsurfer — APPROVED** [review]

**Comment by pavloburykh** [comment]
Hi @vkjr! Does this PR require manual regression testing? If yes, could you please specify what areas are impacted and should be tested? 
If manual testing is not required - then we are good to go and merge the PR) Thank you!

**Comment by vkjr** [comment]
Hi @pavloburykh! Thank you for checking, because I wasn't sure about results of e2e tests)
This PR doesn't require manual testing, because it is a refactoring that touches all aspects of the app and if there were problems, they would affect the entire app.
So I will merge it)

**Pull request merged**
