### PR TITLE
[#7455] Added WBTC token

### LINKED ISSUE #7455: Add WBTC token to our ERC-20 list
name:WBTC

see contract adress here: https://etherscan.io/token/0x2260fac5e5542a773aa44fbcfedf7c193bc2c599

project website: https://www.wbtc.network/

### PR DESCRIPTION
**Pull request by trowacat**
fixes #7455

Added icons and listing for WBTC token

### CODE REVIEW

**Review by jeluard — APPROVED** [review]

**Review by flexsurfer — APPROVED** [review]

**Review by goranjovic — APPROVED** [review]

**Comment by Serhy** [comment]
@trowacat could you rebase develop, please?

**Comment by asemiankevich** [comment]
@trowacat @jeluard any idea how i can faucet this token ?

**Comment by jeluard** [comment]
@asemiankevich On mainnet? I don't think you can get that. It's a wrapper for bitcoin

**Comment by asemiankevich** [comment]
> @asemiankevich On mainnet? I don't think you can get that. It's a wrapper for bitcoin

Ropsten would be fine too. 
I want to check sending/receiving this token

**Comment by jeluard** [comment]
This token has not been added on ropsten apparently

**Comment by guylouis** [comment]
@asemiankevich  if still needed I can get a couple $ of wbtc on mainnet and send them to you for tests. If yes, let me know where to send them.

**Comment by trowacat** [comment]
@Serhy @jeluard Any reason jenkins build failing after rebase?

**Comment by jeluard** [comment]
@trowacat It's good now

**Comment by asemiankevich** [comment]
> @asemiankevich if still needed I can get a couple $ of wbtc on mainnet and send them to you for tests. If yes, let me know where to send them.

@guylouis 0x58d8c3D70ce4FA4b9fb10a665C8712238746F2ff

**Comment by asemiankevich** [comment]
image


will test sending / receiving tokens once i get them

**Comment by guylouis** [comment]
@asemiankevich 
Just sent a couple WBTC tokens to the adress you specified

**Pull request merged**
