### PR TITLE
Update release branch 2.30.x

### PR DESCRIPTION
**Pull request by ilmotta**
### Summary

Update the release branch https://github.com/status-im/status-mobile/tree/release/2.30.x with ALL changes in status-mobile `develop` since revision a1784c5e1f7235400c12643e852255fd8975325d.

status: ready

### CODE REVIEW

**Review by jakubgs — APPROVED** [review]
Ain't nobody got time to read all this shit.

**Comment by mariia-skrypnyk** [comment]
Hey @ilmotta !
   
   Can you rebase your PR for smoke checks from our side?

**Comment by churik** [comment]
@ilmotta thank you! we're ready to update the branch and start testing

**Review by clauxx — APPROVED** [review]

**Review by churik — APPROVED** [review]

**Comment by churik** [comment]
@ilmotta 
https://github.com/status-im/status-mobile/pull/20902 this one too!

**Comment by ilmotta** [comment]
@churik, it would be good to cherry pick at least this PR about fallback pairing https://github.com/status-im/status-go/pull/5627.  The pipeline is already running on the status-go side, if it passes should take 50min more.

> https://github.com/status-im/status-mobile/pull/20902 this one too!

Will update 👍🏼

**Comment by churik** [comment]
@ilmotta we didn't check it on the client side. are you sure that it is working?

**Comment by ilmotta** [comment]
> @ilmotta we didn't check it on the client side. are you sure that it is working?

No @churik, we are not sure and I was thinking we would test in this PR before merging it. But let's test it separately and then update the release branch again with a separate PR. Safer.

**Comment by qfrank** [comment]
> > @ilmotta we didn't check it on the client side. are you sure that it is working?
> 
> No @churik, we are not sure and I was thinking we would test in this PR before merging it. But let's test it separately and then update the release branch again with a separate PR. Safer.

I have tested and it works, but it's safer if you can help test it separately 🙂

**Pull request merged**
