### PR TITLE
Update status-go

### PR DESCRIPTION
**Pull request by cammellos**
status: ready

### CODE REVIEW

**Comment by ghost** [comment]
### Pull Request Checklist
- [x] Have you updated the documentation, if impacted (e.g. [docs.status.im](https://docs.status.im/docs/build_status.html))?

**Comment by annadanchenko** [comment]
@cammellos is it for 0.9.32 release?

**Comment by cammellos** [comment]
@annadanchenko yes, I am waiting for the build to test it, and then I can cherry pick on release

**Comment by cammellos** [comment]
@annadanchenko tested and cherry-picked on the release branch

**Pull request closed without merging**
