### PR TITLE
test: limit message hashes per query

### PR DESCRIPTION
**Pull request by richard-ramos**
if the missing message verification is enabled there's no limit for the number of missing message hashes to request and that can increase the load of the storenodes while with this change we reduce the number of message hashes per query to 50.

Requires:
- https://github.com/status-im/status-go/pull/5688

To test:
- Ensure no panics happen during normal app usage or excess memory is being used compared to current release version

cc: @ilmotta  @churik

### CODE REVIEW

**Comment by churik** [comment]
Checked a similar set of tests here:
release: https://app.eu-central-1.saucelabs.com/tests/7cd17e024a6242d0a4111694e60f764d
PR: https://app.eu-central-1.saucelabs.com/tests/3551aa84a13b4758ad3d353a3cc92746

You can check vitals on both devices, frankly, I can't see an improvement - what is expected to change in terms of the app?

I see the difference in Memory performance (632 MB in Release vs 1250 MB in PR), but it can be the difference in the builds (release build type vs PR).


Still need to recheck offline messages and wait one more time for e2e tests.

**Comment by richard-ramos** [comment]
> You can check vitals on both devices, frankly, I can't see an improvement - what is expected to change in terms of the app?

For the app, the improvements should not be noticeable. The benefit of this change is only for the storenodes

**Comment by churik** [comment]
Ok, I don't see any significant changes in the app - I made a test of sending 10 messages in different types of chats + restoring backup from waku + spectating the community (open the community page and see the messages fetched for public channels)

I don't see a significant difference in memory / performance.

Release: 

https://github.com/user-attachments/assets/9c14f0b9-a2fa-4a6f-ac45-ca3b04f60623

PR build:

https://github.com/user-attachments/assets/92ace3c3-0c35-4919-afdb-f2e17b1b7be9

In both builds at some points I got crashes (so I supposed nothing to do with PR)


Also I checked fetching > 50 messages from offline for both communities / private chats, worked in my case.

Tests are failed because sometimes waku backup was not restored or message status didn't update fast enough (and it also can be related to waku store nodes upgrade)

@richard-ramos @ilmotta your call is to merge or not to merge into release.

**Comment by ilmotta** [comment]
Awesome analysis @churik 👏🏼 

@richard-ramos, even though there's no apparent downside to this change, I think we can go without it in 2.30. We want to already start freezing the status-go and mobile release branches because the mobile QA team is trying to catch-up to too many changes introduced in status-go/mobile and this will potentially delay even more our release schedule.

What do you say we introduce this improvement in a small release after 2.30 is out, like 2.30.1?

**Comment by richard-ramos** [comment]
> What do you say we introduce this improvement in a small release after 2.30 is out, like 2.30.1?

I guess it's okay.  Is there an approx date of when 2.30.1 would be released?

**Comment by ilmotta** [comment]
> > What do you say we introduce this improvement in a small release after 2.30 is out, like 2.30.1?
> 
> I guess it's okay. Is there an approx date of when 2.30.1 would be released?

We don't have an approximate date yet @richard-ramos, but we are accumulating a few problems already, not just changes from this PR, so I would expect `2.30.1` to be ready before the end of September, maybe before, but we can't commit to dates yet.

**Comment by churik** [comment]
I believe can be closed

**Pull request closed without merging**
