### PR TITLE
Enable group chats in dev mode in nightlies

### PR DESCRIPTION
**Pull request by cammellos**
Enables group chats in nightlies.
On mobile `dev-mode?` needs to be on, on desktop they will be enabled.

### Testing notes (optional):
Group chats have already been tested by @lukaszfryc , this just enables them in nightlies.

Basically on mobile if `dev-mode?` is on, you should be able to see group chats and receive messages.
If it's off you should not see them nor receive messages.

status: ready

### CODE REVIEW

**Review by flexsurfer — APPROVED** [review]

**Review by rasom — APPROVED** [review]

**Comment by cammellos** [comment]
Not to be tested yet, I would like to get some changes in status-go first

**Comment by lukaszfryc** [comment]
@cammellos is it ready to be tested now?

**Comment by cammellos** [comment]
@lukaszfryc not quite yet, I still want to make some more changes :)

**Comment by cammellos** [comment]
closing as already address in a different PR https://github.com/status-im/status-react/pull/6242

**Pull request closed without merging**
