### PR TITLE
[#6066]: Update Livepeer listing + add livepeer.tv

### PR DESCRIPTION
**Pull request by alwx**
Fixes: #6066

Status: ready

### CODE REVIEW

**Review by jeluard — APPROVED** [review]

**Review by flexsurfer — APPROVED** [review]

**Review by jeluard — APPROVED** [review]

**Review by flexsurfer — APPROVED** [review]

**Comment by asemiankevich** [comment]
@alwx no icon for `Livepeer` under `Utilities` - is that expected? cc @rachelhamlin 

image

**Comment by alwx** [comment]
@asemiankevich probably not. I've just added an image (it's the same as for Livepeer), can easily replace it with something else if needed.

**Comment by asemiankevich** [comment]
looks good - thanks @alwx ! 🙌

**Comment by rachelhamlin** [comment]
@alwx @asemiankevich there's actually a new logo for livepeer.tv in the issue—I assume it wouldn't size down well but did you try @alwx? The other logo for `Livepeer` is okay.

**Pull request merged**
