### PR TITLE
Test filter subscribe order fix

### PR DESCRIPTION
**Pull request by vitvly**
Tests https://github.com/status-im/status-go/pull/4665

### CODE REVIEW

**Comment by pavloburykh** [comment]
@vitvly thank you for the PR. Unfortunately data reliability issues still exist so most of e2e are failed. Below I describe couple of examples. 

### 1. Contact request (CR) sender does not receive a signal about CR has been accepted by receiver

**Steps:**

1. User A [sends](https://app.eu-central-1.saucelabs.com/tests/4d8d3d0b76c344c58a13e0869af5cd9f?auth=603692587aa1794dace30daf57a3f8f6#80) CR to User B
2. User B [receives CR and accepts it](https://app.eu-central-1.saucelabs.com/tests/369788ca0a7f4858a8ecc061f52570d0?auth=56096981af4cb5e7a814952136435a49#66) 
3. See if User A received signal about acceptance of outgoing CR (i.e. User B appeared in contact list of User A)

**Expected result:** User A receives notification about acceptance of his CR by User B. User B appears in contact list of User A. 

**Actual result:** User B [has not appeared](https://app.eu-central-1.saucelabs.com/tests/4d8d3d0b76c344c58a13e0869af5cd9f?auth=603692587aa1794dace30daf57a3f8f6#111) in contact list of User A

[Receiver_User_B.log](https://github.com/status-im/status-mobile/files/14221267/Receiver_User_B.log)
[Sender_User_A.log](https://github.com/status-im/status-mobile/files/14221269/Sender_User_A.log)

**Comment by pavloburykh** [comment]
### 2. Community status has not been updated from Pending to Joined for community request sender

**Preconditions:** User A is an admin of non token gated community which does not require admin's manual approval (hereinafter 'Community') 

**Steps:** 

1. User A [shares](https://app.eu-central-1.saucelabs.com/tests/e29c3f70f93e4c5a9f43b668fd073f37?auth=c73e1b401ed7cfb2f3552e25c05d9047#141) Community link to User B and stays online
2. User B receives a link in 1-1 chat, opens it and [sends](https://app.eu-central-1.saucelabs.com/tests/80491041a85d44c8b16959685118fa23?auth=37fdd65e08abaa845e93104a95c478a6#103) Community join request
3. See if User B joined the community (i.e. Community status is changed from Pending to Joined for User B)

**Expected result:** Community status should change to Joined for User B. 

**Actual result:** Community status [remains in Pending](https://app.eu-central-1.saucelabs.com/tests/80491041a85d44c8b16959685118fa23?auth=37fdd65e08abaa845e93104a95c478a6#110) for User B.

[User_A_comm_adm.log](https://github.com/status-im/status-mobile/files/14219555/User_A_comm_adm.log)
[User_B_comm_req_sender.log](https://github.com/status-im/status-mobile/files/14219557/User_B_comm_req_sender.log)

**Comment by pavloburykh** [comment]
### 3. Message reaction (emoji) is not shown for receiver in 1-1 chat

**Preconditions:** User A and User B are messaging in 1-1 chat

1. User A [sends](https://app.eu-central-1.saucelabs.com/tests/772e533f6dd0465fb0852fb42619702d?auth=9ca57950489ebdf5144d228ac67c56b1#90) a message (text 'Message sender')
2. User A [adds reaction](https://app.eu-central-1.saucelabs.com/tests/772e533f6dd0465fb0852fb42619702d?auth=9ca57950489ebdf5144d228ac67c56b1#99) to the message 
3. See if User B observes the reaction to the message

**Expected result:** User B observes the reaction

**Actual result:** User B received a message but [does not see reaction](https://app.eu-central-1.saucelabs.com/tests/2f6dc050df7649f487cdc489795d2e3e?auth=0675ab5168cf8d473d637d2979f70ff7#100) added to the message by User A

[User_A_reaction_sender.log](https://github.com/status-im/status-mobile/files/14219730/User_A_reaction_sender.log)
[User_B_reaction_receiver.log](https://github.com/status-im/status-mobile/files/14219731/User_B_reaction_receiver.log)

**Comment by pavloburykh** [comment]
> @vitvly thank you for the PR. Unfortunately data reliability issues still exist so most of e2e are failed. Below I describe couple of examples.
> 
> ### 1. Contact request (CR) sender does not receive a signal about CR has been accepted by receiver
> **Steps:**
> 
> 1. User A [sends](https://app.eu-central-1.saucelabs.com/tests/4d8d3d0b76c344c58a13e0869af5cd9f?auth=603692587aa1794dace30daf57a3f8f6#80) CR to User B
> 2. User B [receives CR and accepts it](https://app.eu-central-1.saucelabs.com/tests/369788ca0a7f4858a8ecc061f52570d0?auth=56096981af4cb5e7a814952136435a49#66)
> 3. See if User A received signal about acceptance of outgoing CR (i.e. User B appeared in contact list of User A)
> 
> **Expected result:** User A receives notification about acceptance of his CR by User B. User B appears in contact list of User A.
> 
> **Actual result:** User B [has not appeared](https://app.eu-central-1.saucelabs.com/tests/4d8d3d0b76c344c58a13e0869af5cd9f?auth=603692587aa1794dace30daf57a3f8f6#111) in contact list of User A
> 
> [Receiver_User_B.log](https://github.com/status-im/status-mobile/files/14221267/Receiver_User_B.log) [Sender_User_A.log](https://github.com/status-im/status-mobile/files/14221269/Sender_User_A.log)

@cammellos @vitvly guys, I have messed up with sender's log. I have updated them in the issue. Sorry for wasting your time.

**Comment by vitvly** [comment]
Quick update: after debugging together with @chaitanyaprem the problem with peer exchange has been identified. In case of "accept contact request" message, multiple attempts to send it produced the following log:

```
error="failed to dial: failed to dial 16Uiu2HAmLPEKrB27rifoPYpj7VMdsvPLVeacKc2DJ2cCtHfHA64j:\n  * [/ip4/95.217.230.20/tcp/41803] dial tcp4 0.0.0.0:43393->95.217.230.20:41803: i/o timeout"
```

Important to node that `peerID` was different in all 5 attempts. A detailed issue is here: https://github.com/waku-org/nwaku/issues/2414.

**Comment by vitvly** [comment]
Some notes for contact request delivery troubleshooting:

1. Find `Served wakuext_acceptContactRequest` in the log.
2. Above that line, most recent `sent private message without datasync` will give the `envelopeHash`:
```
DEBUG[02-09|07:19:12.922|github.com/status-im/status-go/protocol/common/message_sender.go:520] sent private message without datasync messageID=0xac27518160c7137cd0e6c5e22fb976e61f88a3296f54bd1ddb8eac33c2f3be46 hashes=[0x8aa99057c52861b68f6f0f4351fd6f079dca1d63812d37f680fe6749355071f8]
```
3. Try to see whether that particular hash was successfully delivered to the fleet by looking for `publishing message via lightpush` containing the hash.
4. In this particular case it wasn't delivered due to `failed to dial peer` errors.
5. If it was delivered successfully, go to Kibana->Discover and try to look it up, in order to check whether it was delivered to the recipient. Recipient can be identified by `PeerID` in Kibana logs, and a particular recipient's `PeerID` can be identified from its status-go log by looking for this line:
```
INFO [02-09|07:13:51.364|github.com/status-im/status-go/vendor/github.com/waku-org/go-waku/waku/v2/node/wakunode2.go:328] listening multiaddr=[/ip4/127.0.0.1/tcp/43393/p2p/16Uiu2HAmCzvdcgCkyBRj316DhJrffX9noV7PktQRJvJygBuuRFDS
INFO [02-09|07:13:51.364|github.com/status-im/status-go/wakuv2/waku.go:1185] WakuV2 PeerID id=16Uiu2HAmCzvdcgCkyBRj316DhJrffX9noV7PktQRJvJygBuuRFDS
```

Kudos to @chaitanyaprem for insights throughout the process.

**Comment by chaitanyaprem** [comment]
> Quick update: after debugging together with @chaitanyaprem the problem with peer exchange has been identified. In case of "accept contact request" message, multiple attempts to send it produced the following log:
> 
> ```
> error="failed to dial: failed to dial 16Uiu2HAmLPEKrB27rifoPYpj7VMdsvPLVeacKc2DJ2cCtHfHA64j:\n  * [/ip4/95.217.230.20/tcp/41803] dial tcp4 0.0.0.0:43393->95.217.230.20:41803: i/o timeout"
> ```
> 
> Important to node that `peerID` was different in all 5 attempts. A detailed issue is here: [waku-org/nwaku#2414](https://github.com/waku-org/nwaku/issues/2414).

@vitvly I had a doubt and had taken a look at the logs again and noticed that peer-exchange issue noticed is not the cause of message delivery failure in this case. 
Because as per steps you had mentioned above, i looked for hash `0x29c490ab1131e5c21f41e39f19688218400c07797dfd63e01ddd34813f7e88a5` in the logs and then found the hash in the fleet which means the contact delivery ack was sent successfully from User-B, but failed to receive user-A. 
Here are fleet logs of same message being sent back to User-B `16Uiu2HAmBLVpsGFjTEiiLnpgaJ3ufmBHGJwbrtJ4cWjco3gh7NGU` via Filter 

Screenshot 2024-02-12 at 10 39 35 AM


Looking at contentTopic `/waku/1/0x4cdd76ba/rfc26` used to respond to the contact request based on this log in the fleet, i had noticed that User-A is not subscribed for filter for this contentTopic as i could not see this contentTopic in user-A logs. Which is why the contact-ack was not delivered back to User-A. 

I don't know how the contentTopic mapping is done for various flows, and hence cannot debug further beyond this. 
Can you or @cammellos take a look to see what might have caused filter subscription not to happen for this content-topic?

**Comment by vitvly** [comment]
> 29c490ab113

@chaitanyaprem Pavlo updated the logs after our initial investigation, the hash you mention (`0x29c490ab1131e5c21f41e39f19688218400c07797dfd63e01ddd34813f7e88a5`) is not found in more recent logs (posted here: https://github.com/status-im/status-mobile/pull/18769#issuecomment-1935796241).

This is the correct hash: `0x8aa99057c52861b68f6f0f4351fd6f079dca1d63812d37f680fe6749355071f8` - and i cannot see it in Kibana.

**Comment by chaitanyaprem** [comment]
> `0x8aa99057c52861b68f6f0f4351fd6f079dca1d63812d37f680fe6749355071f8`

Ah, that makes sense then. 
You are right that this hash won't be there on the fleet as this message was failed to send.

But on retry, the hash would have changed. The new hash is `0x20fc91f9819beb27dd1c558589f54b9da54a9e42e973f5eed315123ee1a49937` which is present in the logs which means the message has been received by User-A but after 6 seconds.

The delay is due to the retry after first failure.

**Comment by pavloburykh** [comment]
Hey, @vitvly @chaitanyaprem! Yesterday I re-ran e2e in this PR. The [results](https://github.com/status-im/status-mobile/pull/18769#issuecomment-1937844574) are much better then in the previous run (83% passed comparing to 27% in previous run). Could it be the case that some changes were committed on Waku side which improved the situation? There are still existing failures related data delivery issues (will post the examples with logs later today) but overall the situation looks better.

**Comment by vitvly** [comment]
@chaitanyaprem you're right. I am still wondering what are other failed attempts then - they refer to the same contentTopic `0x0526aab0`.

**Comment by chaitanyaprem** [comment]
> Hey, @vitvly @chaitanyaprem! Yesterday I re-ran e2e in this PR. The [results](https://github.com/status-im/status-mobile/pull/18769#issuecomment-1937844574) are much better then in the previous run (83% passed comparing to 27% in previous run). Could it be the case that some changes were committed on Waku side which improved the situation? There are still existing failures related data delivery issues (will post the examples with logs later today) but overall the situation looks better.

I don't think any changes got committed on waku side in the last few days.
@richard-ramos can confirm

But i am not sure any changes in status-go happened between the runs that has caused improvement. 

Wrt failures, still trying to figure out if there is an issue in the way we get peers from peer-exchange(which is causing this failure).

**Comment by chaitanyaprem** [comment]
Suspicion: 
Since discv5 is enabled in lightmode as well in status-go, This could be what is causing the fleet nodes discv5 cache to have peers that are no longer available. As the CI runs, mobile nodes connect to fleet via discv5 and their own peerIDs must also be getting added to the discv5 cache (which are then returned via peer-exchange) for subsequent tests.  This could be a reason as to why peer connection is failing.

Will investigate logs to confirm if the peerIDs are of nodes from previous tests which is why they are no longer available.

**Comment by pavloburykh** [comment]
@vitvly @chaitanyaprem 

The [latest e2e run](https://github.com/status-im/status-mobile/pull/18769#issuecomment-1938694398) has failed because of the following reason:

UI gets stuck on keys saving step. 
When attempting to login the account after app re-opening user gets ```node crashed on start: <nil>``` error

[TestOneToOneChatMultipleSharedDevicesNewUi_geth0.log](https://github.com/status-im/status-mobile/files/14239350/TestOneToOneChatMultipleSharedDevicesNewUi_geth0.log)

photo_2024-02-12 16 12 16

https://github.com/status-im/status-mobile/assets/97245802/25668f53-038f-418e-82ff-24d4f476ac95

**Comment by chaitanyaprem** [comment]
> @vitvly @chaitanyaprem
> 
> The [latest e2e run](https://github.com/status-im/status-mobile/pull/18769#issuecomment-1938694398) has failed because of the following reason:
> 
> UI gets stuck on keys saving step. When attempting to login the account after app re-opening user gets `node crashed on start: <nil>` error
> 
> [TestOneToOneChatMultipleSharedDevicesNewUi_geth0.log](https://github.com/status-im/status-mobile/files/14239350/TestOneToOneChatMultipleSharedDevicesNewUi_geth0.log)
> 
> photo_2024-02-12 16 12 16
> telegram-cloud-document-2-5354898850228226284.mp4

That is because the changes ins status-go seem incomplete. 
I pushed changes which should work into https://github.com/status-im/status-go/pull/4665. 
Can  you test with these changes and confirm?
New commit [9c66b21](https://github.com/status-im/status-go/pull/4665/commits/9c66b21a4b5d6e322eed3bdc1ee533e728076354)

**Comment by vitvly** [comment]
thanks @chaitanyaprem ! couldn't quite figure out what was the problem. Just updated here to point to your fix.

**Comment by pavloburykh** [comment]
thank you @vitvly @chaitanyaprem! I have triggered e2e run, let's wait the results.

**Comment by pavloburykh** [comment]
> thank you @vitvly @chaitanyaprem! I have triggered e2e run, let's wait the results.

@vitvly I have manually checked the latest PR build and see that the error is still there.

**Comment by chaitanyaprem** [comment]
> > thank you @vitvly @chaitanyaprem! I have triggered e2e run, let's wait the results.
> 
> @vitvly I have manually checked the latest PR build and see that the error is still there.

I have no idea why it is crashing, maybe something else in status-go is dependent on discovery probably. 
cc @vitvly

**Comment by chaitanyaprem** [comment]
> > > thank you @vitvly @chaitanyaprem! I have triggered e2e run, let's wait the results.
> > 
> > 
> > @vitvly I have manually checked the latest PR build and see that the error is still there.
> 
> I have no idea why it is crashing, maybe something else in status-go is dependent on discovery probably. cc @vitvly

Trying to debug this by running status-desktop locally.

**Comment by chaitanyaprem** [comment]
> > > > thank you @vitvly @chaitanyaprem! I have triggered e2e run, let's wait the results.
> > > 
> > > 
> > > @vitvly I have manually checked the latest PR build and see that the error is still there.
> > 
> > 
> > I have no idea why it is crashing, maybe something else in status-go is dependent on discovery probably. cc @vitvly
> 
> Trying to debug this by running status-desktop locally.

Not sure of cause of crash but was able to run in status-desktop lightMode locally after some more changes. New status-go commit is https://github.com/status-im/status-go/pull/4665/commits/dcb26ffb4c6fb9e07e3027e63a2c2e0a7f3e4639 
cc @vitvly

**Comment by pavloburykh** [comment]
@vitvly @chaitanyaprem 

Recent [e2e run](https://github.com/status-im/status-mobile/pull/18769#issuecomment-1946050996) shows that ```node crashed on start: <nil>``` error still exists. 

[TestOneToOneChatMultipleSharedDevicesNewUi_geth1.log](https://github.com/status-im/status-mobile/files/14297562/TestOneToOneChatMultipleSharedDevicesNewUi_geth1.log)

**Comment by chaitanyaprem** [comment]
> @vitvly @chaitanyaprem
> 
> Recent [e2e run](https://github.com/status-im/status-mobile/pull/18769#issuecomment-1946050996) shows that `node crashed on start: <nil>` error still exists.
> 
> [TestOneToOneChatMultipleSharedDevicesNewUi_geth1.log](https://github.com/status-im/status-mobile/files/14297562/TestOneToOneChatMultipleSharedDevicesNewUi_geth1.log)

This same status-go code works without crashing on my status desktop with lightMode. 
Not sure if there is something else happening in case of status-mobile.
Log doesn't indicate any specific issue as well. 
Maybe someone from mobile team can suggest what to look for and figure out what is causing the crash.

**Comment by pavloburykh** [comment]
> This same status-go code works without crashing on my status desktop with lightMode.
> Not sure if there is something else happening in case of status-mobile.
> Log doesn't indicate any specific issue as well.
> Maybe someone from mobile team can suggest what to look for and figure out what is causing the crash.

@vitvly @chaitanyaprem the interesting fact is that in the previous build [#5](https://ci.status.im/job/status-mobile/job/prs/job/android/job/PR-18769/5/) (the one before recent rebasing) this issue has gone. But after rebase it appeared again. So maybe some problem occurred during recent rebase?

**Comment by vitvly** [comment]
@pavloburykh @chaitanyaprem i think there was an issue in status-go code, related to the way discv5/peerexchange settings were set. I was able to run a local ios build after the fix. Checking e2e now.

**Comment by pavloburykh** [comment]
Hey @vitvly! 

According to the latest e2e run ```node crashed on start: <nil> error``` is gone. 

At the same time there are still bunch of failures related to data delivery issues.

Below is an example of such failure:

### Contact request (CR) has not been delivered to the receiver

**Steps:**

1. User A [sends](https://app.eu-central-1.saucelabs.com/tests/b79c9f95d9b84e9a8808fe6b9027571d?auth=65a6eab344678ee20415a59f1ef5707e#68) CR to User B
2. See if User B received CR

**Actual result:** User B [has not received](https://app.eu-central-1.saucelabs.com/tests/833edfafc9664af89cce4fe091680422?auth=62bde7ac622320ecbcbb47234681c816#74) CR

[UserA_CRsender.log](https://github.com/status-im/status-mobile/files/14328691/UserA_CRsender.log)
[UserB_CRreceiver.log](https://github.com/status-im/status-mobile/files/14328692/UserB_CRreceiver.log)

**Comment by chaitanyaprem** [comment]
> Hey @vitvly!
> 
> According to the latest e2e run `node crashed on start: <nil> error` is gone.
> 
> At the same time there are still bunch of failures related to data delivery issues.
> 
> Below is an example of such failure:
> ### Contact request (CR) has not been delivered to the receiver
> 
> **Steps:**
> 
>     1. User A [sends](https://app.eu-central-1.saucelabs.com/tests/b79c9f95d9b84e9a8808fe6b9027571d?auth=65a6eab344678ee20415a59f1ef5707e#68) CR to User B
> 
>     2. See if User B received CR
> 
> 
> **Actual result:** User B [has not received](https://app.eu-central-1.saucelabs.com/tests/833edfafc9664af89cce4fe091680422?auth=62bde7ac622320ecbcbb47234681c816#74) CR
> 
> [UserA_CRsender.log](https://github.com/status-im/status-mobile/files/14328691/UserA_CRsender.log) [UserB_CRreceiver.log](https://github.com/status-im/status-mobile/files/14328692/UserB_CRreceiver.log)

This is because PeerExchange could not get any peers. 
Explained reasoning here https://github.com/status-im/status-go/pull/4665#discussion_r1495271941

Another point to note is why doesn't mobile show that message send has failed after max retries? Probably that may help user know that peer connectivity is not there.

**Comment by flexsurfer** [comment]
looks stale, feel free to reopen if needed

**Pull request closed without merging**
