### PR TITLE
Changes to onboarding/new-to-status (quo/fonts/spacings/copy)

### LINKED ISSUE #17425: Onboarding: I'm new to Status update
Summary
Changed the illustration, increased the font size and added a button to the generate keys card

Based on user feedback

Screenshot_2023-09-26_at_11 02 33 (1)

### PR DESCRIPTION
**Pull request by clauxx**
fixes #17425

### Summary

Changes:

1. Fixed the font in the `main` variant of `onboarding/small-option-card`
2. Added button to `main` variant of `onboarding/small-option-card`
3. Changed illustration, copy on `onboarding/new-to-status`
4. Fixed spacing between main card and the rest of `onboarding/new-to-status`
5. Adjusted preview of `onboarding/small-option-card`

#### Platforms

- Android
- iOS

##### Functional

- onboarding (new-to-status)

### Steps to test

- Open Status
- Press "I'm new to Status"

### Before and after screenshots comparison

| Figma (if available) | iOS (if available)    | Android (if available)
| --- | --- | --- |
|   |   | Please embed Image/Video here of the before and after. |

status: ready

### CODE REVIEW

**Review by J-Son89 — APPROVED** [review]

**Review by jo-mut — APPROVED** [review]
Looks all good to me

**Comment by clauxx** [comment]
> ## 0% of end-end tests have passed
> ```
> Total executed tests: 43
> Failed tests: 43
> Passed tests: 0
> ```
> 
> ```
> IDs of failed tests: 702809,702782,702733,702784,703194,702859,702732,702813,703133,702957,702851,702840,703495,703086,702948,702894,702745,702783,702850,702742,703297,703503,702869,703496,702936,702855,703202,703391,702786,702839,702947,702838,702844,702846,702843,702807,702731,702808,702730,702845,702958,703382,702841 
> ```
> 
> ### Failed tests (43)
> Click to expand

0 passed tests? 😨

**Comment by qoqobolo** [comment]
> 0 passed tests? 😨

Haha don’t worry :) in PR the changes affect the first screens, most likely something happened to the accessibility IDs of the elements (tests can't find them anymore). I'm looking at this now, I'll be back soon with feedback (a fix may be needed on our or your side)

**Comment by yevh-berdnyk** [comment]
hi @clauxx, I've just pushed a fix and restarted the tests

**Comment by clauxx** [comment]
> hi @clauxx, I've just pushed a fix and restarted the tests

Thank you!! moving it to manual testing

**Comment by qoqobolo** [comment]
Thanks @yevh-berdnyk!

@clauxx I've already checked the PR manually, looks good to me.
Ready to be reviewed by @Francesca-G.

**Comment by qoqobolo** [comment]
@clauxx please mind the @yevh-berdnyk's commit when squashing and merging (after the design review). Thank you!

**Comment by clauxx** [comment]
> @clauxx please mind the @yevh-berdnyk's commit when squashing and merging (after the design review). Thank you!

@qoqobolo do you mean the commit shouldn't be squashed?

**Comment by qoqobolo** [comment]
@clauxx no, I mean it should be included/squashed :) Otherwise, without this fix,  the tests will be broken for nightly and other PRs once this PR is merged

**Comment by clauxx** [comment]
> @clauxx no, I mean it should be included/squashed :) Otherwise, without this fix, the tests will be broken for nightly and other PRs once this PR is merged

Ah, yes, I'll just squash it with GH and it will include all the PR commits 👍

**Review by Francesca-G — APPROVED** [review]
Looks good :)

**Pull request merged**
