### PR TITLE
[#16864] Design review: messages home

### LINKED ISSUE #16864: Design review: messages home
- [ ] 1. Date and hour are not aligned in chats list - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3678:7819&mode=design#511309210)  
- [ ] 2. Wrong margin between list items - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3678:7819&mode=design#510226396)  
- [ ] 3. The badge is not aligned with  date and hour  and name - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3678:7819&mode=design#511306952)  
- [ ] 4. Unread barge may overlap with text and not aligned to design - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3678:7819&mode=design#511306759) 
image

- [ ] 5. Missing counter border - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3678:7819&mode=design#510044277)  
- [ ] 6. + uses outdated color - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3678:7819&mode=design#510043895)  
- [ ] 7. Unmute icon may overlap with date - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3678:7819&mode=design#510042990)  
- [ ] 8. When user set nickname, their real name is not shown anymore - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3709:473614&mode=design#517052552)
- [ ] 9. Missing stroke and margin around counter and dot - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3678:7819&mode=design#511305455)
- [ ] 10. Jump to blur area shoud be shown behind the blur on tabs - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3678:7819&mode=design#510045776)
- [ ] 11. Wrong background color in dark mode - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3678:7819&mode=design#510050996)
Likely it is a part of bigger issue

### PR DESCRIPTION
**Pull request by flexsurfer**
fixes #16864

1. Date and hour are not aligned in chats list - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3678:7819&mode=design#511309210)

 2. Wrong margin between list items - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3678:7819&mode=design#510226396)

 3. The badge is not aligned with date and hour and name - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3678:7819&mode=design#511306952)

 [can't replicate]4. Unread barge may overlap with text and not aligned to design - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3678:7819&mode=design#511306759)
image

 6. + uses outdated color - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3678:7819&mode=design#510043895)

 7. Unmute icon may overlap with date - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3678:7819&mode=design#510042990)

 8. When user set nickname, their real name is not shown anymore - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3709:473614&mode=design#517052552)

### CODE REVIEW

**Review by ibrkhalil — APPROVED** [review]

**Comment by qoqobolo** [comment]
@flexsurfer thank you for the fixes!

There is still a problem with the accessibility-id that causes the e2e failures. 
Since the `name` component has been changed, the id has been removed. Could you add as it was before, please?

`//*[@content-desc='chat-name-text’]`

Screenshot 2023-08-21 at 15 54 35

**Comment by flexsurfer** [comment]
thank @qoqobolo added  :author-primary-name  and :author-secondary-name

**Comment by yevh-berdnyk** [comment]
Hi @flexsurfer, I've pushed a commit with updated locator and restarted the tests

**Review by qoqobolo — APPROVED** [review]

**Comment by qoqobolo** [comment]
@flexsurfer  seems like on iOS the name is still not aligned with the date, could you check plz

Screenshot 2023-08-22 at 12 06 10

**Comment by flexsurfer** [comment]
thanks @qoqobolo fixed

**Comment by qoqobolo** [comment]
LGTM now, thanks for your work @flexsurfer!
@Francesca-G kindly review the fixes 🙏

@flexsurfer also, mind @yevh-berdnyk's commits when merging pls.

**Review by Francesca-G — COMMENTED** [review]
Here's the [Figma frame](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS/Feedback-for-Mobile?type=design&node-id=4612%3A63710&mode=design&t=zQ950i0xUEoPOriS-1) with the review :)

**Comment by flexsurfer** [comment]
design review
- [ ] status dot is smaller than design (separate issue https://github.com/status-im/status-mobile/pull/17110)
- [x] date label too dark
- [x] something happened to the shadow, looks cut off (separate issue  https://github.com/status-im/status-mobile/issues/17098)
- [x] name is smaller than design
- [ ] no border around the notification counter (separate issue https://github.com/status-im/status-mobile/issues/17312)

**Comment by flexsurfer** [comment]
@qoqobolo @yevh-berdnyk could you please resolve test conflict

**Comment by flexsurfer** [comment]
@Francesca-G two comments were addressed, 3 more will be in separate issues

**Review by Francesca-G — APPROVED** [review]

**Comment by churik** [comment]
@flexsurfer on my way of fixing 1 test, please, wait for the last commit, thanks!

**Comment by churik** [comment]
@flexsurfer 
fixed all related changes, ready to be merged - please mind my and Yevhenia commits while merging, thank you!

**Comment by churik** [comment]
@flexsurfer 
 did you create an issue follow-up based on the design review from https://github.com/status-im/status-mobile/pull/17050#issuecomment-1691048181?

Based on https://github.com/status-im/status-mobile/blob/develop/doc/pipeline_process.md > Design review, all follow-up issues have to be created when PR is merged and linked to the original PR.

**Comment by flexsurfer** [comment]
done

**Pull request merged**
