### PR TITLE
Dont open chat on contact request

### LINKED ISSUE #4325: Don't show chats without messages 👻
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to see new chats with messages so that I'm not confused by empty ghost chats.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: A user can be using Status and see a new chat message on Home, but after tapping in discover the chat is empty. This can be caused by contact requests without a message, or perhaps some other reason. In any case it is better to only bother users with chats with actual messages to prevent confusion, eg "why is warlike potent salami sending me a message with no message?".

#### Expected behavior
All chats have messages

#### Actual behavior
Empty chats are shown

screen shot 2018-05-17 at 5 30 04 pm

### Reproduction
- User A sends a contact request with no message to user B
- User B receives empty chat

### Solution

Wait to show chats until a message is present.

### PR DESCRIPTION
**Pull request by cammellos**
fixes #4325

### Summary:

We don't create anymore chats on contact requests/updates. 

I have also moved the name generation in subs as it was in 2 places, and removed the denormalization of `name` in 1-to-1 chats.

I have migrated the data as well, not sure if `js-delete` is needed when removing fields, but I had written it already, so leaving it here, let me know if it's not needed.

status: ready

### CODE REVIEW

**Comment by yenda** [comment]
If we don't open a chat on contact request how does the user knows about a pending contact request ?

**Comment by cammellos** [comment]
@yenda that was really quick :D 

I personally think it's ok, sometimes you want to add someone without letting him know, and then maybe send a message at some other point.

If that is a problem I would rather move towards decoupling them, with two separate actions. But don't feel strongly about it.

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/x5kPWK for branch PR-4336

<blockquote><div><strong><a href="https://i.diawi.com/x5kPWK">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/s8oey9 for branch PR-4336

<blockquote><div><strong><a href="https://i.diawi.com/s8oey9">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Review by yenda — APPROVED** [review]

**Review by janherich — APPROVED** [review]

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/SSWyiW for branch PR-4336

<blockquote><div><strong><a href="https://i.diawi.com/SSWyiW">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/agQQjs for branch PR-4336

<blockquote><div><strong><a href="https://i.diawi.com/agQQjs">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by jeluard** [comment]
@cammellos Can you rebase?

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/null for branch PR-4336

<blockquote><div><strong><a href="https://i.diawi.com/null">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/mqSqMG for branch PR-4336

<blockquote><div><strong><a href="https://i.diawi.com/mqSqMG">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by lukaszfryc** [comment]
@cammellos it works but we need to update e2e tests.

@antdanchenko maybe the best fix is to add `add_contact_and_start_chat` method?

**Comment by lukaszfryc** [comment]
@cammellos how's it going with the autotests?

**Comment by cammellos** [comment]
@lukaszfryc badly, I haven't had time to look at it, today looks pretty busy as well, so probably not going to be able to set it up for this taks

**Comment by lukaszfryc** [comment]
@antdanchenko could you take it?

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/a4L8Ga for branch PR-4336

<blockquote><div><strong><a href="https://i.diawi.com/a4L8Ga">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/gCbsKX for branch PR-4336

<blockquote><div><strong><a href="https://i.diawi.com/gCbsKX">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/9idtd4 for branch PR-4336

<blockquote><div><strong><a href="https://i.diawi.com/9idtd4">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/FgJ4fr for branch PR-4336

<blockquote><div><strong><a href="https://i.diawi.com/FgJ4fr">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by antdanchenko** [comment]
@lukaszfryc, @cammellos automated tests have been updated in scope of the PR, please merge the PR if no issues found

**Comment by cammellos** [comment]
thanks @antdanchenko , @lukaszfryc let me know if it's good to go!

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/mDyD46 for branch PR-4336

<blockquote><div><strong><a href="https://i.diawi.com/mDyD46">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/SLEpnY for branch PR-4336

<blockquote><div><strong><a href="https://i.diawi.com/SLEpnY">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by lukaszfryc** [comment]
@cammellos good to go!

**Pull request merged**
