### PR TITLE
[#11822] Own status updates are shown on other user profiles

### LINKED ISSUE #11822: Own status updates are shown on other user profiles
# Bug Report

## Problem
After posting something to your status it is shown on any other user profile

#### Expected behavior
Only status updates of another user is shown

#### Actual behavior
Can see own updates and other user profile statuses
https://user-images.githubusercontent.com/4557972/109825154-d1d04700-7c39-11eb-80b8-4322350797de.mp4

### Reproduction

- Open Status
- Post something to own status
- Open another user profile (one of your contacts for example)

### Additional Information

[comment]: # (Please do your best to fill this out.)
- Status version: RC 1 1.12
- Operating System: Android, iOS

### LINKED ISSUE #11836: java.lang.numberFormatException when receive TX in 1-1 chat. Can't proceed use Status after, - until Force Stop
# Bug Report

## Problem

`java.lang.numberFormatException for input string ""` error appears when received transaction in 1-1 chat.
After tap on 'Exit' - can't proceed to use Status. It's frozen. When re-opening Status was stuck on logo screen (apparently it's enabled Notifications settings which plays role here of app stuck on  Status logo view because we keep running Status when Notification ON)

#### Expected behavior

No error appears

#### Actual behavior

Screenshot 2021-03-04 at 14 25 37

### Reproduction

- Open Status on Device1 and Device2
- Device1 sends to Device2 'Request transaction' message in 1-1 chat
- Device2 signs with PIN and sends transaction 
- Device2 goes offline (Airplane mode)
- After Device1 receives transaction, - Device2 returns back online
- Device2 receives 'Confirmed' status in 1-1 chat transaction but error also appears (see **Actual result** above) 

### Additional Information

- Status version: `Release 1.12`/ develop
- Operating System: Android

#### Logs

Full logcat log (from emulator): 
[logcat.log](https://github.com/status-im/status-react/files/6083738/logcat.20.log)

```

--------- beginning of crash
03-03 07:14:40.588  5754  5850 E AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
03-03 07:14:40.588  5754  5850 E AndroidRuntime: Process: im.status.ethereum, PID: 5754
03-03 07:14:40.588  5754  5850 E AndroidRuntime: java.lang.NumberFormatException: For input string: ""
03-03 07:14:40.588  5754  5850 E AndroidRuntime: 	at java.lang.Integer.parseInt(Integer.java:627)
03-03 07:14:40.588  5754  5850 E AndroidRuntime: 	at java.lang.Integer.parseInt(Integer.java:650)
03-03 07:14:40.588  5754  5850 E AndroidRuntime: 	at im.status.ethereum.pushnotifications.NewMessageSignalHandler.upsertChat(NewMessageSignalHandler.java:268)
03-03 07:14:40.588  5754  5850 E AndroidRuntime: 	at im.status.ethereum.pushnotifications.NewMessageSignalHandler.handleNewMessage(NewMessageSignalHandler.java:241)
03-03 07:14:40.588  5754  5850 E AndroidRuntime: 	at im.status.ethereum.pushnotifications.PushNotification.presentLocalNotification(PushNotification.java:116)
03-03 07:14:40.588  5754  5850 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-03 07:14:40.588  5754  5850 E AndroidRuntime: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
03-03 07:14:40.588  5754  5850 E AndroidRuntime: 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
03-03 07:14:40.588  5754  5850 E AndroidRuntime: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
03-03 07:14:40.588  5754  5850 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:883)
03-03 07:14:40.588  5754  5850 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
03-03 07:14:40.588  5754  5850 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
03-03 07:14:40.588  5754  5850 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
03-03 07:14:40.588  5754  5850 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
03-03 07:14:40.588  5754  5850 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:919)
03-03 07:14:40.612  5754  6759 D StatusModule: Signal event
03-03 07:14:40.615  1749  1825 D gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 1736704
03-03 07:14:40.619  1749  1825 I chatty  : uid=1000(system) HwBinder:1749_3 identical 1 line
03-03 07:14:40.622  1749  1825 D gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 1736704
03-03 07:14:40.629  5754  5833 D EGL_emulation: eglMakeCurrent: 0xc00b74a0: ver 2 0 (tinfo 0xc00dc3a0)
```

### PR DESCRIPTION
**Pull request by flexsurfer**
fixes #11836
fixes #11822

### CODE REVIEW

**Review by cammellos — APPROVED** [review]

**Comment by flexsurfer** [comment]
@qoqobolo #11836 added to this PR

**Comment by qoqobolo** [comment]
@flexsurfer `Public chat with #{chat_key} name after pairing devices` issue is reproducible again :(
Description and steps for reproduction are here: https://github.com/status-im/status-react/issues/11654

**Comment by cammellos** [comment]
@qoqobolo probably best to fix it separately from 1.13, we need to have a look at that code and change a few things, if that's ok.
Thanks!

**Comment by flexsurfer** [comment]
i think i know whats the reason, i'll fix that

**Comment by flexsurfer** [comment]
@qoqobolo fixed

**Comment by qoqobolo** [comment]
@flexsurfer could you rebase this to the latest develop, please?

**Comment by flexsurfer** [comment]
@qoqobolo done

**Comment by Serhy** [comment]
Can not reproduce https://github.com/status-im/status-react/issues/11836 
Also I re-run the same test which were failing before with `java.lang.numberFormatException for input string ""` error 20 times in a row and error was not appeared (in scope of this PR https://github.com/status-im/status-react/pull/11838)
Notification for Request/Send still appears (as well as other text/emoji/image notifications).
Let's merge, thanks @flexsurfer @cammellos !

**Comment by Serhy** [comment]
One moment e2e tests are finished...

**Comment by flexsurfer** [comment]
@Serhy @qoqobolo  but #11822 is not tested yet? so we can't merge yet, sorry for the confusion with 2 issues in the same PR

**Comment by Serhy** [comment]
> @Serhy @qoqobolo but #11822 is not tested yet? so we can't merge yet, sorry for the confusion with 2 issues in the same PR

Ah sorry haven't mentioned it, - that also was checked. The #11822 is not reproduced anymore. Text/emoji/image posted as "My Status update" is not visible in another user profiles. iOS14 and Android 11 covered. 
It's good for merge (and cherry pick in release/1.12).

**Pull request merged**
