### PR TITLE
[#12047] move colors to quo 

### LINKED ISSUE #12047: move colors to quo
component | status-im.ui | usage | descr | quo | usage | descr
-- | -- | -- | -- | -- | -- | --
colors | status-im.ui.components.colors | 50% |   | quo.design-system.colors | 50% | used by quo components

remove `status-im.ui.components.colors` namespace

### LINKED ISSUE #12556: Black font color of community categories in dark mode
# Bug Report

## Problem 

Screenshot 2021-09-07 at 17 04 48

### Reproduction

1. Settings > Appearance > Dark mode
2. Create a community > create category

### Additional Information

- Status version: nightly 7/09
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by flexsurfer**
fixes #12047
fixes #12556

QA: verify colors in the entire app (dark and light themes)

### CODE REVIEW

**Review by shivekkhurana — APPROVED** [review]
### 🌲

**Comment by Serhy** [comment]
There are a couple of places where we lost colours of curtain elements:

1) Keycard banner (only Dark Mode affected)
Screenshot 2021-08-31 at 16 26 11

2) Send-Receive buttons on wallet account screen (only Dark Mode):
Screenshot 2021-08-31 at 16 26 54

3) No border in account icon after account recover (both Dark and Light modes)
Screenshot 2021-08-31 at 16 35 13

4) Keycard PIN panel should have six dots (indicating that '6-PIN digits' are supposed to be). There are no such dots now (only Dark mode)
Screenshot 2021-08-31 at 16 39 11

5) Lost blue color on toggle-buttons (Dark mode only)
Screenshot 2021-08-31 at 16 42 33

6) No white inner-circle when selecting account during account creation (the same on Profile -> Sync Settings -> Sync history for ... (1 day/one week/one month) view):
Screenshot 2021-08-31 at 16 49 26

7) No grey circle around non-selected buttons on Log Level, Fleet settings view (Dark/Light modes):
Screenshot 2021-08-31 at 16 55 30

8) No toggle buttons at all when selecting Network chain in Profile -> Advanced -> Network -> tap (+) -> Add network view:
Screenshot 2021-08-31 at 16 58 37

9) Outgoing transactions icon (blue one) lost it's color (both Dark and Light mode):
Screenshot 2021-08-31 at 17 08 06

**Comment by flexsurfer** [comment]
thanks, @Serhy  all fixed, except 8

**Comment by flexsurfer** [comment]
@Serhy ,rebased, all should be fixed now

**Comment by Serhy** [comment]
Failed tests are not related to this PR (will be fixed separately)
Retested on Android 9 and iOS14, - all issues above are fixed, no new UI issues noticed. Ready for merge, thanks @flexsurfer

**Pull request closed without merging**
