### PR TITLE
bug fix #2419 : make profile status message box adapt to written text

### LINKED ISSUE #2419: "Description" is partly overlapped by "Save" button on  "Profile > Edit" screen (IPhone 5S, "Predictive" is enabled)
### Description

*Type*: Bug

*Summary*: 
Last row in "Description" is overlapped by "Save" button, so user cannot see what he types. Scrolling to the bottom fixes text in the same state, so "Save" button covers last row.

"Predictive" option on IPhone settings  should be enabled.

#### Expected behavior
"Save" button does not overlap last row, "Description" is shown correctly

#### Actual behavior
Last row in "Description"  is overlapped by "Save"

### Prerequisites
- "Predictive" option should be enabled (Settings > General > Keyboard)

### Reproduction
- Open Status
- Login with existing account
- Open Profile
- Tap on Edit
- Fill up "Description" (more than 4 rows)

### Additional Information

* Status version: 0.9.12

* Operating System: IOS 10.3.2

*Device: IPhone 5s

txt

### LINKED ISSUE #2604: Expansion problem with Status emojis in Message Box
### Description

*Type*: Bug

I wrote a lot of emojis with Android keyboard's emojis in Message Box. Message Box expands as I write. I wrote a lot of emojis with Status emojis in Message Box. Message Box don't expands as I write.

Video: [https://drive.google.com/file/d/1FHMWOQBTUkbFc0WeTVTLCHqpArY4WGcs/view](https://drive.google.com/file/d/1FHMWOQBTUkbFc0WeTVTLCHqpArY4WGcs/view)

### Reproduction

- Open Status
- Sign in
- Chat with Jarrad
- Click Message Box
- Open Android keyboard's emojis
- Write emojis
- Scroll up on Message Box
- Send message
- Click Message Box
- Open Status emojis
- Write emojis
- Scroll down on Message Box

### Solution

- Message box expanded as Status emojis are written.

### Additional Information

* Status version: 0.9.12+

* Operating System: Android 6.0 - LG G4 (Real Device)

### PR DESCRIPTION
**Pull request by SHA-2048**
fix attempt for #2419

### CODE REVIEW

**Review by flexsurfer — APPROVED** [review]

**Comment by churik** [comment]
Hi, @mlahia! Can you please define a scope of this PR?
I mean only bug fix for #2604(Android and IOS) - or whole adaptability of input field to written text?

**Review by goranjovic — APPROVED** [review]

**Comment by SHA-2048** [comment]
@churik yeas sure. I might have done more than what have been described on the first ticket.
the scope of the fix is the following:
 - make status box size adaptable to the length of typed text
 - make status box top and bottom padding equal (looks nicer)
 - make status box show all text on the profile view (after closing the edit, before it was only showing part of the text)

**Comment by churik** [comment]
@mlahia during PR testing I faced with issues:
#2825
#2822
#2823 

All of them are related to message box adaptability.
Can you please take a look?

**Comment by SHA-2048** [comment]
OK @churik, I think the fix I made relates to a problem that is not reported (I misunderstood the issue in #2604). 

The issue is with profile status box. It is having the same problem as with the chat message boxes.

I'll try to complete the current fix to cover all issues you linked. Thanks !

**Comment by SHA-2048** [comment]
@churik actually this related to #2419. Sorry for the incorrect reference.
I think I need to re-submit this PR with correct referencing.

**Comment by churik** [comment]
@mlahia do you still plan to fix #2825, #2822, #2823, #2604?

**Comment by SHA-2048** [comment]
@churik yes, I'll give it a shot.

**Pull request closed without merging**
