### PR TITLE
[FIX #3591] always show full link

### LINKED ISSUE #3591: url text is truncated in the middle so user can't see full link text when tapping on it
### Description

*Type*: Bug
url sent to the chat is not fully shown because some text in the middle is replaced with "...". 
screenshot_20180315-175227

*Summary*: 

#### Expected behavior
According to the design we need to show full url text
screen shot 2018-03-15 at 15 56 14

#### Actual behavior
PArt of the url text in the middle is replaced with ...
### Reproduction

- Open Status
- Open 1:1 chat with Jarrad
- Send https://wiki.status.im/Send_Transaction_flow and check how it's displayed in the chat

### Additional Information
* Status version: nightly build March 14
* Operating System: Android and iOS

### PR DESCRIPTION
**Pull request by kixi**
fixes #3591 

### Summary:

always show the full URL in Chat message

### Review notes (optional):
This is my first PR and I am completely new to the software. Please check if my changes have any side-effects I did not think about.

### Steps to test:

    Open Status
    Open 1:1 chat with Jarrad
    Send https://wiki.status.im/Send_Transaction_flow and check how it's displayed in the chat

status: ready

### CODE REVIEW

**Comment by jeluard** [comment]
Maybe @foopang can comment on the original reason for the truncation?

**Comment by foopang** [comment]
@jeluard Yes, before #3299 long URLs are truncated. But it was a missing feature in my original PR. @lukaszfryc requested it to be fixed [in this comment](https://github.com/status-im/status-react/pull/3299#issuecomment-368461587) so I did.

**Comment by jeluard** [comment]
@kixi Are full URLs shown for both iOS and android?

**Comment by kixi** [comment]
I assume the code part I changed effects both - iOS and Android. However I have no iOS development environment, so I just tested it for Android

**Comment by jeluard** [comment]
@kixi Ok let's validate that during tests!

**Review by jeluard — APPROVED** [review]

**Review by flexsurfer — APPROVED** [review]

**Comment by yevh-berdnyk** [comment]
Branch: PR-3607
Android: https://i.diawi.com/Z8kGq9
iOS: https://i.diawi.com/rADHX2

Tested on both iOS and Android - LGTM, thanks @kixi 

<blockquote><div><strong><a href="https://i.diawi.com/Z8kGq9">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>
<blockquote><div><strong><a href="https://i.diawi.com/rADHX2">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by jeluard** [comment]
@kixi Please squash your commits!

**Pull request merged**
