### PR TITLE
Improve QR code Handler mobile side PR

### PR DESCRIPTION
**Pull request by siddarthkay**
Made this PR so that QA team can test status-go side changes.
Related to status-go PR :  https://github.com/status-im/status-go/pull/3172
status: ready

### CODE REVIEW

**Review by qfrank — APPROVED** [review]

**Review by alwx — APPROVED** [review]

**Comment by siddarthkay** [comment]
@status-im/mobile-qa : refactoring has been done for QR code generation on status-go PR : https://github.com/status-im/status-go/pull/3172 which is approved and waiting to be merged, This PR is made so that QA can see if this breaks anything or not and run E2E.

note : this feature is not yet used anywhere in status-mobile, it may be used later :)

**Comment by pavloburykh** [comment]
@siddarthkay thanx for the PR. 
E2E tests are failing as a result of the following critical issue

### ISSUE 1 Chat key/name of other users are not fetched. Users which were added to contacts are not displayed within contacts list. 

**Steps:**

1. User A adds User B to contact list
2. See if User A can see User's B chat key/name on profile page/within AC notifs/1-1 chat name etc
3. See if User B is displayed within User's A contact list

**Actual result:** User's B chat key/name data is not fetched for User A. User B is not shown within User's A contact list. 

[Status-debug-logs (13).zip](https://github.com/status-im/status-mobile/files/10859341/Status-debug-logs.13.zip)

https://user-images.githubusercontent.com/97245802/222100633-681579a0-8931-4935-a237-52f184a3f345.mp4

**Comment by siddarthkay** [comment]
Hi @pavloburykh : this issue does not seem to be caused by my changes in status-go, I'll however look at the logs and let you know :)

**Comment by pavloburykh** [comment]
> Hi @pavloburykh : this issue does not seem to be caused by my changes in status-go, I'll however look at the logs and let you know :)

I have checked in develop branch, issue is not reproducible there. So I guess the bug is introduced in the new go version which is used in current PR.

**Comment by siddarthkay** [comment]
@pavloburykh : can you try again with latest build. I believe this PR was pointing to correct branch in status-go but it was pointing to an older commit over there, I've just now updated the `commit-sha1`.

This should produce different results 🫣

**Comment by pavloburykh** [comment]
> This should produce different results 

@siddarthkay thanx, issue is not reproducible any more. E2E have passed, no regression found. Failed tests are not related to the PR. Ready for merge.

**Comment by siddarthkay** [comment]
@pavloburykh : Thanks for testing, I will bump version and merge 👍🏻

**Pull request merged**
