### PR TITLE
Watch-only collectibles should not be included on the main wallet page by default #20735

### LINKED ISSUE #20735: Watch-only collectibles should not be included on the main wallet page by default
### Problem:
According to [issue #19657](https://github.com/status-im/status-mobile/issues/19657), the balances and tokens of watch-only accounts should not be shown by default on the wallet main page. Currently, only tokens are excluded. The same logic should apply to collectibles as well

### Steps:
1. Add a watch-only account that contains collectibles (`0x00000000219ab540356cbb839cbe05303d7705fa`)
2. Go to the main wallet page

### Actual result:
Collectibles are shown on the main page

https://github.com/user-attachments/assets/03c0f907-d778-44e0-a74e-00fca6e12416

### Expected result:
Collectibles of watch-only accounts are not shown on the main wallet page

### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

### ENV:
NIghtly [12 Jul 2024, 02:08]

### PR DESCRIPTION
**Pull request by mmilad75**
This PR removes the watch-only collectibles from the list of collectibles in the wallet home screen.

I renamed `:wallet/request-collectibles-for-all-accounts` event to `:wallet/request-collectibles-for-owned-accounts` and `:wallet/all-collectibles-list` to `:wallet/owned-collectibles-list`. They were only used in the wallet home page, so it was secure to rename it.

I could've created a new event to handle all owned collectibles, but it the `:wallet/all-collectibles-list` was not used any where else so it would become an unused code.

fixes #20735

### CODE REVIEW

**Review by ulisesmac — APPROVED** [review]
Hey @mmilad75 !

Thank you, the PR looks great :100: 

Is removing the collectibles a design decision? :thinking:

**Comment by VolodLytvynenko** [comment]
> Is removing the collectibles a design decision? 🤔

hi @ulisesmac Once, the inclusion of watch-only account assets on the overall wallet page was discussed [here](https://discord.com/channels/624634427930312714/852533718790570015/1207978870062587944). After that, @qoqobolo discussed with the design team (in Montenegro, if I am not mistaken) before [issue](https://github.com/status-im/status-mobile/issues/19657) creation, and they agreed that by default, the assets of watch-only accounts should not be included in the overall wallet.

**Review by ilmotta — APPROVED** [review]

**Comment by VolodLytvynenko** [comment]
Hi @mmilad75 thank you for PR. take a look found issues:

## PR_ISSUE 1: Collectibles are not shown when a watch-only account with collectibles is opened
### Steps:
1. Add a watch-only account with available collectibles (example: 0xFC6327a092f6232e158a0Dd1d6d967a2e1c65cD5).
2. Open the current account.
3. Go to the collectibles tab.

### Actual result:
No collectibles are shown for watch only account when current account is opened

https://github.com/user-attachments/assets/6e6525ac-952a-4a0d-bd6c-45284addc86d

### Expected result:
Collectibles should be shown which belongs to the watch only account when the current account is opened.

**Comment by VolodLytvynenko** [comment]
## PR_ISSUE 2: Count of Multi-Collectibles from Watch-Only Account is combined with Regular account

### Steps:
1. Recover a user that has multi-collectibles.
2. Add a watch-only account that has the same multi-collectible.
3. Check the collectibles displayed on the wallet overview page.

### Actual result:
The count of collectibles from the watch-only account is combined with the collectibles of the regular account on the wallet overview page.

https://github.com/user-attachments/assets/380c87b6-51e2-47d8-98c7-c9d4cb43ebae

### Expected result:
The count of collectibles from the watch-only account should not be combined with the collectibles of the regular account on the wallet overview page.





### OS: 
IOS, Android
### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

**Comment by mmilad75** [comment]
@VolodLytvynenko Hi Volodymyr. Thanks for testing. The issues are fixed now. Please check again

**Comment by VolodLytvynenko** [comment]
Hi @mmilad75 issues are fixed. PR is ready to be merged. Thank you for your work!

**Pull request merged**
