### PR TITLE
[#15836] Images not displayed in chat when received by user with app …

### LINKED ISSUE #15836: Images not displayed in chat when received by user with app running in the background
### Preconditions:
User_A and User_B are on the opened chat

### Steps to reproduce:
1. Device of User_A goes to the background
2. User_B sends a few messages with images
3. User_A goes back from the background

### Actual result:
Images are not shown in the chat for user_A until the chat is reopened

https://user-images.githubusercontent.com/52490791/236846176-2b128f12-454e-4568-adba-a9797a9a3d3a.mp4

### Expected result:
Images are shown in the chat for User_A

### Devices:
- iPhone 11 Pro max, ios 16
- Huawei p20 light, android 9

### Logs:
[Status.log](https://github.com/status-im/status-mobile/files/11421801/Status.log)
[geth.log](https://github.com/status-im/status-mobile/files/11421802/geth.log)

### Env:
Nightly 8 May 2023

### PR DESCRIPTION
**Pull request by flexsurfer**
fixes #15836

QA: changes applied to images, albums and audio

### CODE REVIEW

**Review by OmarBasem — APPROVED** [review]

**Review by smohamedjavid — APPROVED** [review]
LGTM 👍

**Comment by pavloburykh** [comment]
Thanx for the PR @flexsurfer ! Please take a look at the following issue

### ISSUE 1 Cannot open images received while being in background [Android]

**Steps:** 

1. User A opens chat and backgrounds the app
2. User B sends image/image album in chat
3. User A comes back from the background
4. User A tries to open received images
5. See if images are opened

**Actual result:** 

Images are not opened upon tap. Tapping multiple times on such images results in app starting to lag. 


https://github.com/status-im/status-mobile/assets/97245802/bb357e49-1902-496d-885d-e960bf7efe5a

**Review by briansztamfater — APPROVED** [review]
💪

**Comment by flexsurfer** [comment]
thanks @pavloburykh should be fixed

**Comment by pavloburykh** [comment]
> thanks @pavloburykh should be fixed

Thanx @flexsurfer ! Issue is partially fixed. Still able to reproduce with some different workaround

### App freezes while opening album images received while user was located outside the chat [Android]

**Steps:** 

1. User A opens shell or Messages screen with list of chats
2. User B sends album with images to User A
3. User A navigates from shell (Messages screen) to chat with newly received album
4. User A starts opening images in album
5. Observe the result

**Actual result:** some album images are not opened upon tap. App freezes after multiple tap on images which are not opening. 


https://github.com/status-im/status-mobile/assets/97245802/e9a0e885-4063-42a6-8b73-9e187382cd99


https://github.com/status-im/status-mobile/assets/97245802/0c80a807-1126-42d3-adc2-b7a76556c285

**Comment by pavloburykh** [comment]
> App freezes while opening album images received while user was located outside the chat [Android]

@flexsurfer nevermind. This issue is not PR related. Also reproducible in develop. Will log separate issue for that. Current PR is ready for merge.

**Pull request merged**
