### PR TITLE
Make the iOS app Universal 🌏

### LINKED ISSUE #4662: iPad Support
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to use Status on a tablet so that I can use Status on all of my mobile devices.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*:  Status can be used on a iPad, but instead of running at native resolution the viewport is set to an iPhone 4 and everything is scaled up. Whilst the app is usable, it is a horrible user experience and doesn't take advantage of the devices resolution and screen real estate.

img_0041 png 2018-06-05 15-11-48

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
Status runs at native resolution

#### Actual behavior
[comment]: # (Describe what actually happened.)
Status runs at a lower resolution and is scaled up

### Solution
* Make Status a universal app as outlined in [this post](https://shellmonger.com/2017/08/14/universal-ios-apps-with-react-native/).
* Additionally, select all device orientation modes so it works in landscape mode too
* Thoroughly test all screens at different tablet resolutions to ensure layouts look/work as expected
* Fix any display bugs that arise
* Bonus: Get split screen mode working ([similar issue](https://github.com/facebook/react-native/issues/16152))

screen shot 2018-06-08 at 1 37 33 pm

### PR DESCRIPTION
**Pull request by chadyj**
[comment]: # (Please replace ... with your information. Remove < and >)
fixes #4662

### Summary:

This enables a universal app so Status can be used on an iPad at native resolution.

### Testing notes (optional):
All screens and flows should be tested on various sized iPad's. 

### Steps to test:
- Install on an iPad

status: ready

### CODE REVIEW

**Review by mandrigin — APPROVED** [review]
LGTM

**Comment by mandrigin** [comment]
Not much to review, but it should be tested thoroughly!

**Comment by lukaszfryc** [comment]
@annadanchenko could you test it on your iPad? I'll check on iPad simulators and double check on phones.

**Review by rasom — APPROVED** [review]

**Comment by lukaszfryc** [comment]
@annadanchenko do you need my help with testing it on simulators?

**Comment by annadanchenko** [comment]
@chadyj @rasom please, restrict only to portrait mode. Currently, it's possible to use landscape mode on iPAd and there is at least one issue with it: grey line to show "Offline"/"Fetching messages" is shown only for part of the screen in landscape mode. There can be more issues, so proposal is to restrict only to portrait mode first.

**Comment by chadyj** [comment]
> @chadyj @rasom please, restrict only to portrait mode. Currently, it's possible to use landscape mode on iPAd and there is at least one issue with it: grey line to show "Offline"/"Fetching messages" is shown only for part of the screen in landscape mode. There can be more issues, so proposal is to restrict only to portrait mode first.

I'd prefer to document any issues and ship with all orientation for anything minor, such as UI quirks. Ipad support is such an improvement over what we have currently that this is a step forward.  We can also get user feedback on any new issues and fix those.  But if we don't ship landscape I'm afraid it will take a long time to get out the door.

We can even mention in the release notes that this is a beta feature (like all of our features) and we want the community to test.

**Comment by chadyj** [comment]
@mandrigin or @rasom Would you be so kind to update https://github.com/status-im/status-react/blob/develop/CHANGELOG.md as part of this PR?

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/status-im/status-react">status-im/status-react</a></strong></div><div>status-react - a free (libre) open source, mobile OS for Ethereum</div></blockquote>

**Comment by annadanchenko** [comment]
@chadyj there are 3 ui issues that does not look nice but if user turn to portrait mode then app can be used. So, potentially they can be fixed later and are not blockers:
https://github.com/status-im/status-react/issues/5023
https://github.com/status-im/status-react/issues/5024

There is ugly ui issue that happened once but I can't repro it yet
https://github.com/status-im/status-react/issues/5025


I've tested on real device iPad mini 3, iOs 11.4
also did quick checks on iPhone 7 plus, iPhone 5s and Galaxy S6 to see there are no regressions and screens there look as before.

**Comment by asemiankevich** [comment]
removed the label so it could be merged. issues will be fixed right after this one is merged

**Comment by goranjovic** [comment]
@chadyj could you pls resolve the conflict?

**Comment by chadyj** [comment]
Would be great for @mandrigin or @rasom to take a look.

**Pull request merged**
