### PR TITLE
PR to generate builds for implement shell scan screen 

### PR DESCRIPTION
**Pull request by siddarthkay**
This PR is only created so that CI can generate builds which can be shared with Design Team.

actual PR ref : https://github.com/status-im/status-mobile/pull/16351

status: Do not review :)

### CODE REVIEW

**Comment by Parveshdhull** [comment]
hi @siddarthkay, what's status of this PR?

**Comment by siddarthkay** [comment]
Hi @Parveshdhull : This is an imported PR made by an external candidate, this would need lint fixes and some reviews internally. 
I'll do the needful and put it up for review. 
Thanks for the reminder.

**Comment by flexsurfer** [comment]
@siddarthkay still relevant?

**Comment by siddarthkay** [comment]
Hi @flexsurfer : Closing this one, I'll open a new one.

**Pull request closed without merging**
