### PR TITLE
Upgrade RN to 0.51 and fix #2604 & #2822 (text-input related auto-focus issues)

### LINKED ISSUE #2604: Expansion problem with Status emojis in Message Box
### Description

*Type*: Bug

I wrote a lot of emojis with Android keyboard's emojis in Message Box. Message Box expands as I write. I wrote a lot of emojis with Status emojis in Message Box. Message Box don't expands as I write.

Video: [https://drive.google.com/file/d/1FHMWOQBTUkbFc0WeTVTLCHqpArY4WGcs/view](https://drive.google.com/file/d/1FHMWOQBTUkbFc0WeTVTLCHqpArY4WGcs/view)

### Reproduction

- Open Status
- Sign in
- Chat with Jarrad
- Click Message Box
- Open Android keyboard's emojis
- Write emojis
- Scroll up on Message Box
- Send message
- Click Message Box
- Open Status emojis
- Write emojis
- Scroll down on Message Box

### Solution

- Message box expanded as Status emojis are written.

### Additional Information

* Status version: 0.9.12+

* Operating System: Android 6.0 - LG G4 (Real Device)

### PR DESCRIPTION
**Pull request by SHA-2048**
fix for #2604 & #2822

### CODE REVIEW

**Comment by oskarth** [comment]
@mlahia Can you explain more in detail why we need to upgrade RN and linear-gradient to fix these issues? It'd be great if you could fill out the PR description with more details :)

**Comment by SHA-2048** [comment]
@oskarth yes of course, where are my manners :) ?
so the problem was a bug reported on react-native [here](https://github.com/facebook/react-native/issues/12799) I saw it was integrated into version 0.51.0. And after migrating to this version I had to upgrade linear-gradient to the version compatible with 0.51.0 as it was not working with the current one.

**Comment by oskarth** [comment]
Thanks @mlahia!

FYI reviewers/QA: RN 0.51 breaking changes:

> Consider negative border radii and widths invalid (99d294b) - @rsnara
(from https://github.com/facebook/react-native/releases)

Not sure if we use this or not, don't recall having seen this.

**Review by oskarth — APPROVED** [review]

**Review by goranjovic — APPROVED** [review]

**Review by yenda — APPROVED** [review]

**Comment by churik** [comment]
Install:
- checked that issue is not reproducible in Console Chat
- created 1-1 chat, send several text messages and checked that issue is not reproducible

Upgrade:
- upgraded app with 1-1 chat history, checked that after upgrade issue is not reproducible

**Pull request merged**
