### PR TITLE
move windows base image to docker image, add workdir

### PR DESCRIPTION
**Pull request by jakubgs**
Changes:

* Changed `GID` of `jenkins` user from `1002` to `1001` which is now used by Jenkins
  - This combined with the [`UID` fix](https://github.com/status-im/infra-misc/commit/317b9e0c3d39d2bfa7c52a954a27badea9f15e8e) will fix:
    - `mkdir: [!] Permission denied @ dir_s_mkdir - /.fastlane` errors
    - `FileNotFoundError: [Errno 2] No such file or directory: /.conan/conan.conf` errors
* Added windows base image `zip` directly to the Docker image.
  - To avoid issues with mounting the `zip` from slaves.
* Added `WORKDIR /home/jenkins` to the base image so it's not `/`.
* Added tools to base image: `autoconf`, `automake`, and `libtool`
  - This __might__ fix issues with `SQLCipher` during `pod install`
* Upgrades Fastlane: `2.112.0` > `2.116.1`

Status: __READY__

### CODE REVIEW

**Review by pedropombeiro — APPROVED** [review]

**Comment by jakubgs** [comment]
I'm still seeing the weird conan failures:
```log
[2019-02-27T12:01:41.092Z] + ./scripts/build-desktop.sh buildClojureScript
[2019-02-27T12:01:42.470Z] ERROR: [Errno 2] No such file or directory: '/.conan/conan.conf'
[2019-02-27T12:01:42.470Z] Traceback (most recent call last):
[2019-02-27T12:01:42.470Z]   File "/usr/local/bin/conan", line 10, in <module>
[2019-02-27T12:01:42.470Z]     sys.exit(run())
[2019-02-27T12:01:42.470Z]   File "/usr/local/lib/python3.5/dist-packages/conans/conan.py", line 6, in run
[2019-02-27T12:01:42.470Z]     main(sys.argv[1:])
[2019-02-27T12:01:42.470Z]   File "/usr/local/lib/python3.5/dist-packages/conans/client/command.py", line 1546, in main
[2019-02-27T12:01:42.470Z]     conan_api, client_cache, user_io = Conan.factory()
[2019-02-27T12:01:42.470Z]   File "/usr/local/lib/python3.5/dist-packages/conans/client/conan_api.py", line 194, in factory
[2019-02-27T12:01:42.470Z]     client_cache = migrate_and_get_client_cache(user_home, out)
[2019-02-27T12:01:42.470Z]   File "/usr/local/lib/python3.5/dist-packages/conans/client/conan_api.py", line 986, in migrate_and_get_client_cache
[2019-02-27T12:01:42.470Z]     client_cache = ClientCache(base_folder, storage_folder, out)
[2019-02-27T12:01:42.470Z]   File "/usr/local/lib/python3.5/dist-packages/conans/client/client_cache.py", line 49, in __init__
[2019-02-27T12:01:42.470Z]     self._store_folder = store_folder or self.conan_config.storage_path or self.conan_folder
[2019-02-27T12:01:42.470Z]   File "/usr/local/lib/python3.5/dist-packages/conans/client/client_cache.py", line 129, in conan_config
[2019-02-27T12:01:42.470Z]     save(self.conan_conf_path, normalize(default_client_conf))
[2019-02-27T12:01:42.470Z]   File "/usr/local/lib/python3.5/dist-packages/conans/util/files.py", line 148, in save
[2019-02-27T12:01:42.470Z]     with open(path, "wb") as handle:
[2019-02-27T12:01:42.470Z] FileNotFoundError: [Errno 2] No such file or directory: '/.conan/conan.conf'
```
Looking at the code of `1.9.0` version we are using the failure when writing to `.conan/conan.conf` happens here:
https://github.com/conan-io/conan/blob/6f996d5a87df0242a61d7a2069e191f4ffdda0ce/conans/client/client_cache.py#L126-L132
Which in turn is caused by:
https://github.com/conan-io/conan/blob/6f996d5a87df0242a61d7a2069e191f4ffdda0ce/conans/client/conan_api.py#L984-L986
Which gets it's `base_folder` from:
https://github.com/conan-io/conan/blob/6f996d5a87df0242a61d7a2069e191f4ffdda0ce/conans/client/conan_api.py#L193-L194
Which is defined in:
https://github.com/conan-io/conan/blob/6f996d5a87df0242a61d7a2069e191f4ffdda0ce/conans/paths.py#L54-L61
Which by default uses `~` if `CONAN_USER_HOME` is not set. So either we are setting `CONAN_USER_HOME` to `/`, or home directory is wrong within the docker container.

**Comment by jakubgs** [comment]
Oh! I see what happened:
```
 caspair > d run --rm -it -u 1002:1002 statusteam/status-build-windows:1.1.1-67cf7368 bash   
I have no name!@cdf4d6be74fb:/home/jenkins$ id
uid=1002 gid=1002(jenkins) groups=1002(jenkins)
I have no name!@cdf4d6be74fb:/home/jenkins$ echo ~
/
I have no name!@cdf4d6be74fb:/home/jenkins$ exit
```
```
 caspair > d run --rm -it -u jenkins:jenkins statusteam/status-build-windows:1.1.1-67cf7368 bash
jenkins@8d8dc137492a:~$ id
uid=1001(jenkins) gid=1002(jenkins) groups=1002(jenkins)
jenkins@8d8dc137492a:~$ echo ~
/home/jenkins
jenkins@8d8dc137492a:~$ exit
```
We set the `UID` of `jenkins` user to `1001` in our `Dockerfile`:
https://github.com/status-im/status-react/blob/bfbc04ebaeb5384c065e0b4980d56e7aa0941652/docker/base/Dockerfile#L36-L38

But apparently Jenkins now uses `1002`.

**Comment by jakubgs** [comment]
Interestingly enough there were no changes to the Docker Pipeline Plugin since Version 1.17 (May 18, 2018)
https://wiki.jenkins.io/display/JENKINS/Docker+Pipeline+Plugin
But we did upgrade Jenkins from `2.163` to `2.164` 2 weeks ago. Might be the cause.

<blockquote><div><strong><a href="https://wiki.jenkins.io/display/JENKINS/Docker+Pipeline+Plugin">Docker Pipeline Plugin - Jenkins - Jenkins Wiki</a></strong></div></blockquote>

**Comment by jakubgs** [comment]
Okay, what the fuck?
* On `linux-05` it got `-u 1001:1001` - [#7594/7](https://ci.status.im/job/status-react/job/prs/job/windows/job/PR-7594/7/console)
* On `linux-01` it got `-u 1002:1002` - [#7594/8](https://ci.status.im/job/status-react/job/prs/job/windows/job/PR-7594/8/console)
* On `linux-02` it got `-u 1001:1001` - [#7594/9](https://ci.status.im/job/status-react/job/prs/job/windows/job/PR-7594/9/console)

**Comment by pedropombeiro** [comment]
On the nix branch I've had to start setting `CONAN_USER_HOME` for the Windows build, so fingers crossed that it'll get fixed :-)

**Comment by jakubgs** [comment]
Okay, going out running helped me think. So it seems like docker container inherits `UID` of `jenkins` user that was used to SSH into the slave:
```
admin@linux-01.do-ams3.ci.misc:~ % id jenkins
uid=1002(jenkins) gid=1002(jenkins) groups=1002(jenkins),999(docker)
```
```
admin@linux-02.do-ams3.ci.misc:~ % id jenkins
uid=1001(jenkins) gid=1001(jenkins) groups=1001(jenkins),999(docker)
```
Which means the fix is to set `jenkins` user `UID` in Ansible so it's always the same when provisioning.

**Comment by jakubgs** [comment]
Fix for Jenkins slave provisioning:
https://github.com/status-im/infra-misc/commit/317b9e0c3d39d2bfa7c52a954a27badea9f15e8e

**Review by vitvly — APPROVED** [review]

**Review by mandrigin — APPROVED** [review]

**Comment by churik** [comment]
@jakubgs 
can install build and create account on all 5 platforms.
waiting for e2e tests results and ready to move to "Merge" if they'll be OK

**Pull request merged**
