### PR TITLE
remove (unused) react-native-level-fs

### PR DESCRIPTION
**Pull request by mandrigin**
Fixes security issues reported from GitHub.
Didn't find any usages of that, tested on iOS a bit, and didn't find any crashes after removals.

Tested: iOS Simulator (iPhone 8), iOS 12
- opened Status
- opened chatrooms
- opened a DApp (uniswap)

No crashes/red screens.

status: ready

### CODE REVIEW

**Review by goranjovic — APPROVED** [review]

**Review by vkjr — APPROVED** [review]

**Comment by mandrigin** [comment]
@Serhy can you help launching e2e tests to this PR?

**Comment by Serhy** [comment]
@mandrigin started https://ci.status.im/job/end-to-end-tests/job/status-app-end-to-end-tests/2478/

**Review by flexsurfer — APPROVED** [review]

**Review by yenda — CHANGES_REQUESTED** [review]
How did you determine it wasn't use, I see it used in realm/core.cljs

**Comment by mandrigin** [comment]
maybe my grep skills failed me :)
but I launched the app, played with it and saw no warnings either.
why do we use leveldb in react?

**Comment by mandrigin** [comment]
I removed react-native-level-fs, react-native-fs is still there.

**Review by yenda — APPROVED** [review]
My bad

**Pull request merged**
