### PR TITLE
[FIX #3650] Blue open dapp button

### LINKED ISSUE #3650: Open dapp button should be blue
### Description

*Type*: Bug

*Summary*: Arrow and `_` sign should be blue by design

#### Expected behavior

image

#### Actual behavior
image

image

### Reproduction

- Open Status
- Tap Open dapp
- Tap any dapp

### Additional Information

* Status version: nightly
* Operating System: Android, iOS

### PR DESCRIPTION
**Pull request by ovx**
[comment]: # (Please replace ... with your information. Remove < and >)
[comment]: # (To auto-close issue on merge, please insert the related issue number after # i.e fixes #566)

fixes #3650 

### Summary:

[comment]: # (Summarise the problem and how the pull request solves it)
Arrow and _ sign should be blue by design. Created a style for the button with a blue transparent background.

### Steps to test:
- Open Status
- Tap Open dapp
- Tap any dapp

status: ready

### CODE REVIEW

**Comment by jeluard** [comment]
@ovx Thanks for the contribution!
We normally do that by just assigning colors to the svg icon itself. Some others button already are implemented this way.

**Review by jeluard — CHANGES_REQUESTED** [review]
Use icon color directly.

**Comment by ovx** [comment]
OK, got it now, the style `action-button-icon-container` has the background set only of ios. But removing `:ios` and making it a default property renders the background on all action buttons and not just in the dapp page (see the screenshot). What is the correct behavior? Blue background on all actions buttons?

screenshot_1521853736

**Comment by jeluard** [comment]
You can manipulate individual icon color using `icon-opts` (see [here](https://github.com/status-im/status-react/blob/5fc4bddfe5813b224069c71e221acb22737ab876/src/status_im/ui/screens/add_new/views.cljs#L21))

**Comment by ovx** [comment]
Sorry, I misunderstood the issue. The 'Expected behavior' screenshots clearly show the blue background circle and I thought this issue is primarily about the missing background. Fixed with `:icon-opts` property.

**Comment by jeluard** [comment]
Awesome thanks!

**Review by jeluard — APPROVED** [review]

**Comment by ovx** [comment]
@flexsurfer mentioned in the issue #3650 that the background should be present also on Android. Can you confirm that style `action-button-icon-container` should be changed, resulting in all action-buttons having a blue background on Android (see the screenshot above)?

**Comment by flexsurfer** [comment]
@denis-sharypin could you confirm?

**Comment by denis-sharypin** [comment]
yes, the blue circle should be also included

**Review by flexsurfer — APPROVED** [review]

**Comment by asemiankevich** [comment]
I am confused. i do see circle now on android but the elements inside are not blue (as well as ios). Also circle colors are different on iOS and Android @ovx Daniel please take a look!

image

image

**Comment by ovx** [comment]
@asemiankevich Looks to me like you don't have the latest commit. And the circle color is configured just the same for both ios and android.

screenshot_1522204860
screenshot_1522204848

**Comment by asemiankevich** [comment]
@ovx would you mind to check your branch if all commits are there? and re-trigger build if necessary

UPD nevermid looks good 

image


image

**Comment by flexsurfer** [comment]
thanks @ovx could you please squash commits

**Pull request merged**
