### PR TITLE
[FIX #3176] align group icons with chat name text

### LINKED ISSUE #3176: icon_public-chat and icon_group-chat on Home screen view are not aligned with chat name text
***Type***: Bug

*Summary*: The icon_public-chat and icon_group-chat on Home screen view are not aligned with the respective chat name. Additionally, on Android the icon_group-chat looks cut off. 
The icon alignment should be made for both Android and iOS.

Android current view:
screenshot_20180131-114801

iOS current view:
image uploaded from ios 1

And mockups representing the alignment:
screen shot 2018-01-31 at 11 33 25

screen shot 2018-01-31 at 11 33 11

#### Expected behavior
icon_public-chat and icon_group-chat are aligned with the chat name on Home screen
#### Actual behavior
icon_public-chat and icon_group-chat are not aligned with the chat name on Home screen

### Reproduction

- Open Status
- Create public chat and GroupChat and navigate to Home screen
- Check the icon_public-chat and icon_group-chat alignment 

### Additional Information
* Status version: Develop 8f1bc5 / 0.9.11d621 (31st of January)
* Operating System: Android 7.0, iOS 11.2.2 (iPhoneX)

### PR DESCRIPTION
**Pull request by ghikio**
Fixes #3176

### Summary:
Top margins have been removed because they caused icons to be aligned
lower than text and width has been incremented since icons were cut off

### Steps to test:
- Open Status
- Create a private group and public group 
- Icons are not longer cut or not aligned.

status: ready

### CODE REVIEW

**Review by jeluard — APPROVED** [review]

**Comment by flexsurfer** [comment]
@denis-sharypin could you confirm we need a different colour for this icon?

**Comment by denis-sharypin** [comment]
@flexsurfer let's create a separate task for this. It wasn't on a scope for this issue

**Comment by flexsurfer** [comment]
@denis-sharypin yes i know but it's a simple one we can do it in this PR, could you provide a color?

**Comment by denis-sharypin** [comment]
@flexsurfer (def gray "#939ba1")

**Comment by ghikio** [comment]
@flexsurfer @denis-sharypin Should I apply that color then? For both the group_chat and public_chat icon?

**Comment by flexsurfer** [comment]
thanks @thecriw for contribution, could you also add a colors for icons, please
```
[vector-icons/icon :icons/public-chat {:color colors/gray}]])
and
[vector-icons/icon :icons/group-chat  {:color colors/gray}]])
```

and remove styles, because they're not used

**Comment by ghikio** [comment]
@flexsurfer maybe I'm missing something, I still understanding how the project is structured, but I'm afraid I can't find a way to change icon's color.

I've tried setting the color both in:

**styles.cljs**
```
(def private-group-icon
  {:width  16
   :height 16
   :color  colors/gray})
```
and

**inner_item.cljs**
```
     (when private-group?
       [react/view styles/private-group-icon-container
        [vector-icons/icon :icons/group-chat {:style styles/private-group-icon
                                              :color status-im.ui.components.colors/gray}]])
```

But none of them seem to change the color, could you give me a hint on what I'm doing wrong?

**Comment by flexsurfer** [comment]
thank you @criwo , i found that we don't have `fill` property in these icons, could you please add it
https://raw.githubusercontent.com/status-im/status-react/develop/resources/icons/group_chat.svg
https://raw.githubusercontent.com/status-im/status-react/develop/resources/icons/public_chat.svg
`<path fill="" ....`  
and please . require colors instead using ns inline, also you can remove `:style` because it's not used, so code should look like this
```
[vector-icons/icon :icons/public-chat {:color colors/gray}]])
and
[vector-icons/icon :icons/group-chat  {:color colors/gray}]])
```
thanks for your effort

**Comment by ghikio** [comment]
Thanks @flexsurfer , it looks okay now!

**Review by flexsurfer — APPROVED** [review]

**Comment by flexsurfer** [comment]
Great job, thanks @criwo !

**Comment by asemiankevich** [comment]
Android:
image

iOS:
image

**Comment by flexsurfer** [comment]
@criwo could you please "Allow edits from maintainers." https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/ , thanks

<blockquote><div><strong><a href="https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/">Allowing changes to a pull request branch created from a fork - User Documentation</a></strong></div><div>For greater collaboration, you can allow commits on branches you've created from forks. Permission to commit to your forked branches is limited to those with push access to the upstream repository of the fork.
…</div></blockquote>

**Comment by ghikio** [comment]
@flexsurfer oh I'm sorry, you should have permissions now

**Pull request merged**
