### PR TITLE
Emoji reactions doesn't resend when sent immediately after network disconnect

### LINKED ISSUE #11553: Emoji reactions doesn't resend when sent immediately after network disconnect
# Bug Report

## Problem

If you turn off network connection and send emoji reaction right after - it won't be delivered when connection turned on. This is because in `status-go` we do not wait for acknowledgements from non-mailserver peers and automatically treat them as delivered. Same thing happens with chat messages - they treated as delivered while in reality they aren't

#### Expected behavior

Reaction resends when devices goes back online

#### Actual behavior

Reaction not resends when devices goes back online

#### Notes

Related to #11020

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- turn off network connection and quickly add emoji reaction to any message
- at this moment reaction can't be seen on other device
- turn on network connection
- make sure reaction seen on other device after short period of time

### Additional Information

[comment]: # (Please do your best to fill this out.)
- Status version: 1.8
- Operating System: Android,iOS

### PR DESCRIPTION
**Pull request by vkjr**
fixes #11553

### Summary

Switching to `status-go` version that fixes problem with incorrect "sent" signal. After that emojis that sent immediately after network disconnect won't be lost.

#### Platforms
- Android
- iOS

#### Areas that maybe impacted
Everything related to message delivering and confirmation

##### Functional

- 1-1 chats
- public chats
- group chats

### Steps to test

- Open Status
- turn off network connection and quickly add emoji reaction to any message
- at this moment reaction can't be seen on other device
- turn on network connection
- make sure reaction seen on other device after short period of time

status: ready

### CODE REVIEW

**Review by cammellos — APPROVED** [review]

**Comment by qoqobolo** [comment]
### ISSUE 1: Endless connecting spinner and "Pending" status of sent messages on Nightly and RC 1.10 [#13](https://status-im-releases.ams3.digitaloceanspaces.com/StatusIm-210111-093412-632a57-release-universal.apk) builds on eth.test fleet

_Steps:_

1. Install RC 1.10 [#13](https://status-im-releases.ams3.digitaloceanspaces.com/StatusIm-210111-093412-632a57-release-universal.apk) on Device 1
2. Settings -> Advanced -> Fleet -> Switch to eth.test
3. Join public chat
4. Send message
5. Check on another device that the message has been received
6. Check that the endless spinner has appeared and sent message has "pending" status on Device 1

[geth.log](https://github.com/status-im/status-react/files/5795783/geth.log)

https://user-images.githubusercontent.com/67952253/104184355-9cfefb00-5413-11eb-81eb-c3c94ffd65d4.mp4

**Comment by qoqobolo** [comment]
Сonnecting issue fix is needed, so PR is temporarily `blocked`.

**Comment by vkjr** [comment]
@qoqobolo, connection to `eth.test` was fixed by @jakubgs. I rebased `status-go` PR to latest develop and updated test mailservers.
When messages sent from PR build via test mailservers they successfully get acknowledged. 
When messages sent from nightly build via test mailservers they shown as "pending" but this is an expected behavior. Reason - receiving acknowledgements didn't work before but we also never waited for them. Now they work fine in test mailservers but nightly build can't process them because of wrong implementation. In pr build that fixed.

**Comment by vkjr** [comment]
blocked by https://github.com/status-im/status-go/issues/2115

**Comment by vkjr** [comment]
Original status-go pr was splitted in two parts:
[part 1 - fix for mailserver code](https://github.com/status-im/status-go/pull/2128)
[part 2 - fix for client code](https://github.com/status-im/status-go/pull/2129)

If either of this part goes into production "as is", users will experience "pending" messages all the time, so plan is to:
1) merge mailserver code, but disable confirmations in mailservers config
2) merge client code
3) wait until most of the clients updated to new version
4) enable  confirmations for mailservers

Since status-go pr closed, this one also should be.

**Pull request closed without merging**
