### PR TITLE
[#12603] Show App commit in About page

### LINKED ISSUE #12603: Include commit hash in About page
# Feature Issue

Since #12597(https://github.com/status-im/status-react/commit/e2c18ea1) has added the `commitHash` metadata for both Android and iOS builds it would be a good idea to display this information in the `About` page as `App commit` or something like that. It could make debugging easier since a commit is more exact than just version and timestamp.

### User Story

If I want to figure out exactly what kind of version someone is running the `App version` field is not exact enough.

### Acceptance Criteria

App commit is visible and can be copied from the `About` page in the app.

### Technical details

The commit hash is exposed in different ways depending on the paltform:

* Via `commitHash` in [`android/gradle.properties`](https://github.com/status-im/status-react/blob/3745a8e2fe284414ed784c7f09b37cc97602a1d0/android/gradle.properties#L51) and provided to Gradle with [the `-P` flag](https://github.com/status-im/status-react/blob/4d580025164359f1c4df593bc0a45c274137ae5b/nix/mobile/android/release.nix#L157).
* Via `CFBundleCommitHash` in [`ios/StatusIm/Info.plist`](https://github.com/status-im/status-react/blob/3745a8e2fe284414ed784c7f09b37cc97602a1d0/ios/StatusIm/Info.plist#L7-L8) and provided to XCode with `plutil`.

Both default to `unknown` if not set - which would be the case for local dev builds - and can be accessed in a native module (i.e `StatusModule.java` and the iOS equivalent), and be exposed in javascript, at which point you can access them in the UI.

Using `make release-android` should make a full build that should include the actual commit hash.

### PR DESCRIPTION
**Pull request by audriu**
Show App commit in About page
fixes #12603

### Summary
Screenshot from 2022-02-07 18-41-04

Added new field "App commit". Did not add any translations.

#### Platforms
I have only tested on Android

### Steps to test
Open about page and see App commit hash line there

status: ready

### CODE REVIEW

**Comment by jakubgs** [comment]
Truth be told I was hoping for full commit sha, not a shortened one. And available for copying separately.

**Comment by audriu** [comment]
> Truth be told I was hoping for full commit sha, not a shortened one. And available for copying separately.

No problem. I will reimplement soon.

**Comment by audriu** [comment]
> Truth be told I was hoping for full commit sha, not a shortened one. And available for copying separately.

Fixed now. Please let me know what you think!

**Review by cammellos — APPROVED** [review]

**Review by jakubgs — APPROVED** [review]
Looks good, thanks!

**Comment by audriu** [comment]
Oops, tests are failing, but I can see that other PRs tests are failing to some extent too. Should I worry about this instance too?

**Comment by pavloburykh** [comment]
> Oops, tests are failing, but I can see that other PRs tests are failing to some extent too. Should I worry about this instance too?

Hey @audriu No worries. Current tests failures do not seem to be connected with changes in this PR. These tests have been failing recently in other PRs as well. We will take care of that.

**Pull request merged**
