### PR TITLE
Remove whitespace at both ends of nickname and disable button on inva…

### LINKED ISSUE #15378: The white space can be set as a nickname
#### Preconditions:
User_A and User_B are mutual contacts

#### Steps to reproduce:
1. User_A: Go to contacts -> open profile of User_B -> tap 'Nickname'
2. Enter only space into the nickname textbox
#### Actual result:
The white space is set as a nickname

https://user-images.githubusercontent.com/52490791/225572434-99e6f474-be97-4423-b441-835cc7c25f0a.mp4

#### Expected result:
Potential solutions:
- The white spaces are ignored in the beginning and in the end
- The 'done' button is inactive if only white space is entered

#### ENV: 
Nightly: 16 Mar 2023

### PR DESCRIPTION
**Pull request by ibrkhalil**
…lid nickname

fixes #15378 

### Summary
Adds whitespace constrains on nickname editing and trims white space at left and right ends of nickname input and disables the button if the nickname is invalid

### Testing notes
Please test whitespace at the end if it's trimmed and test if the button is disabled on invalid input

- Android
- iOS

##### Functional

- Profile nickname editing

- Try to edit the nickname with the above constrainsts

status: ready

### CODE REVIEW

**Review by flexsurfer — APPROVED** [review]

**Comment by VolodLytvynenko** [comment]
Hi @ibrkhalil thank you for PR. One issue is found that does not allow testing the flow of nickname setting

## ISSUE 1: "Undefined is not an object (evaluating trim)" error is shown if to tap on nickname which has not been already set yet

#### Preconditions:
- User_A and User_B are mutual contacts

#### Steps to reproduce:
1. User_A: Go to contacts -> open profile of User_B -> tap 'Nickname'

#### Actual result:
"Underfined is not an object (evaluating trim)" error is shown

https://user-images.githubusercontent.com/52490791/226333925-96f9e871-430a-44ff-8a76-cccfe7ccd7e9.mp4


#### Expected result:
User is able to set a nickname

#### Device:
IOS and Androids

#### Logs:
[Status.log](https://github.com/status-im/status-mobile/files/11017480/Status.log)
[geth.log](https://github.com/status-im/status-mobile/files/11017481/geth.log)

**Comment by VolodLytvynenko** [comment]
Hi @ibrkhalil thank you for fixes. Issue 1 is fixed. One more issue is found:

#### Problem:
There may be a case where the user wants to get back the '3 random names' display by removing the nickname. But 'done' button is inactive if the value is cleared in 'Nickname' textbox

## ISSUE 2: The 'done' button is inactive after the Nickname value is removed
#### Steps to reproduce:
1. User_A: Go to contacts -> open profile of User_B -> tap 'Nickname'
2. Set nickname -> done
3. Tap 'Nickname' again
4. Clear a 'nickname' a textbox
5. Try to save changes

#### Actual result:
The 'done' button is inactive after the Nickname value is removed

https://user-images.githubusercontent.com/52490791/226350167-4d7dc65b-6722-438e-b3a1-6e60f2ebfb7a.mp4

#### Expected result:
Nickname  value is removed and those changes are able to be saved

**Review by ilmotta — COMMENTED** [review]
@ibrkhalil In the mobile app, setting the nickname as empty is currently the only way to remove the nickname. Hence, how is the user going to be able to remove the nickname?

**Comment by ibrkhalil** [comment]
> @ibrkhalil In the mobile app, setting the nickname as empty is currently the only way to remove the nickname. Hence, how is the user going to be able to remove the nickname?

I guess we should allow empty as a valid state

**Comment by ibrkhalil** [comment]
> @ibrkhalil In the mobile app, setting the nickname as empty is currently the only way to remove the nickname. Hence, how is the user going to be able to remove the nickname?

Then we won't need validation at all, only trimming
CC: @flexsurfer

**Comment by ilmotta** [comment]
> I guess we should allow empty as a valid state

Ideally, I think the designs should be improved. I'm not a fan of this "hidden" feature where the user can set an empty nickname and the UI brings back the other names (ENS or 3-word).

A better experience IMO is:

1. User can set a nickname, but only valid text is allowed. Empty should be considered invalid, just as you did @ibrkhalil.
2. The user should be able to remove the nickname. This should be a separate endpoint in status-go that actually clear up the nickname field in the database.

**Comment by flexsurfer** [comment]
actually its an old implementation, so im not sure we should fix it now, it will be fixed in the new designs

**Comment by ilmotta** [comment]
> actually its an old implementation, so im not sure we should fix it now, it will be fixed in the new designs

I agree @flexsurfer. In that case, it would make sense for @ibrkhalil to bring this topic to designers, since they need to be aware of the current limitation of the endpoint in status-go that doesn't allow nickname removal, except with the trick of an empty string). The question to designers could be, *how should the user remove a nickname?* in the new design? Do we have such a design already?

In status-go we can clearly see it accepts whatever is passed as the nickname https://github.com/status-im/status-go/blob/develop/protocol/messenger_contacts.go#L693. In the backend, I think we should also validate the user input, like max string length and check if the string is not blank. Even if the designs didn't change, I think status-go endpoints should validate any user input anyway.

**Comment by ibrkhalil** [comment]
> > I guess we should allow empty as a valid state
> 
> Ideally, I think the designs should be improved. I'm not a fan of this "hidden" feature where the user can set an empty nickname and the UI brings back the other names (ENS or 3-word).
> 
> A better experience IMO is:
> 
> 1. User can set a nickname, but only valid text is allowed. Empty should be considered invalid, just as you did @ibrkhalil.
> 2. The user should be able to remove the nickname. This should be a separate endpoint in status-go that actually clear up the nickname field in the database.

CC: @pedro-et

**Comment by ibrkhalil** [comment]
Fixed in [15557](https://github.com/status-im/status-mobile/pull/15557)

**Pull request closed without merging**
