### PR TITLE
update status-go to use the latest commit with wallet-compatibility

### PR DESCRIPTION
**Pull request by gravityblast**
[142 Wallet Compatiblity Idea](https://ideas.status.im/ideas/142-wallet-compatibility/README)

### CODE REVIEW

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/uKYfvD for branch PR-4262

<blockquote><div><strong><a href="https://i.diawi.com/uKYfvD">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/MaTFam for branch PR-4262

<blockquote><div><strong><a href="https://i.diawi.com/MaTFam">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Review by jeluard — APPROVED** [review]

**Review by flexsurfer — APPROVED** [review]

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/7kmn35 for branch PR-4262

<blockquote><div><strong><a href="https://i.diawi.com/7kmn35">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/9Yq96H for branch PR-4262

<blockquote><div><strong><a href="https://i.diawi.com/9Yq96H">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Pull request merged**
