### PR TITLE
fix the mention highlighted area is only updated after reopening the chat

### LINKED ISSUE #18432: follow up - The mention highlighted area is only updated after reopening the chat view when the name is updated
# Problem

follow up issue for https://github.com/status-im/status-mobile/pull/18270#issuecomment-1878530581

the mention highlighted area is only updated after reopening the chat view when the name is updated
Steps:

https://private-user-images.githubusercontent.com/67952253/294463599-f46772b7-56b0-46d2-b463-89bf696f97bc.MP4?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MjgwMTUsIm5iZiI6MTcwNDcyNzcxNSwicGF0aCI6Ii82Nzk1MjI1My8yOTQ0NjM1OTktZjQ2NzcyYjctNTZiMC00NmQyLWI0NjMtODliZjY5NmY5N2JjLk1QND9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA4VDE1MjgzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2Njc3MjU2NDJlNmUwMGNhZTUyNjAwMGY2ZmI5NjdjZjU1OTVlMDhkMzg5NjhjYzRhYTc2OTVjOWM2MWE5YmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wWqJB-wx8NGnLaBL9di4pSuIoNX9BRtPxXFdM5TPcys

## Acceptance Criteria

the light blue highlight area should be updated and fit the mention area

## Steps

- UserA: mention UserB in a chat
- UserB: update the name to make it shorter
- UserA: check the chat

### PR DESCRIPTION
**Pull request by Parveshdhull**
fixes https://github.com/status-im/status-mobile/issues/18432

status: ready

### CODE REVIEW

**Review by mohsen-ghafouri — APPROVED** [review]

**Comment by pavloburykh** [comment]
@Parveshdhull thank you for the fix! Please take a look at the issue. 

### ISSUE 1 Shorter mention leaves empty space after updating name  [IOS]

IOS only. Reproducing on iPhone X, IOS 16.7.5

**Preconditions:** User A - any device, User B - IOS

**Steps:** 

1. User A opens chat with User B
2. User B sends message with mention + text following the mention and remains on chat screen
3. User A updates username to a shorter one
4. Pay attention at space between mention and text for User B

**Actual result:** shorter mention leaves empty space after updating name. Fixes after chat re-opening. 

photo_2024-03-04 17 55 37

https://github.com/status-im/status-mobile/assets/97245802/f4adee15-8f18-4de2-9aed-0e8186228929

**Comment by Parveshdhull** [comment]
Hi @pavloburykh, Thank you very for testing the PR.

> Shorter mention leaves empty space after updating name [IOS]

Weird, Is this issue only in PR?

UPD: Got it now, so we updated that background but container is still same sized.

**Comment by Parveshdhull** [comment]
Issue 1 should be fixed now.

**Comment by pavloburykh** [comment]
@Parveshdhull thanx for the fix. Ready for merge.

**Pull request merged**
