### PR TITLE
 Fixes #2370 Update en.cljs En to Fr

### PR DESCRIPTION
**Pull request by ghost**
Mirrored the English File and translated all Strings to French
   These changes are being submitted for the Open Bounty concerning Translating strings from EN to FR

### CODE REVIEW

**Comment by andytudhope** [comment]
You've changed the english file (en.cljs) to a French translation, so this will not be accepted. You need to place the translations in the fr.cljs file...

**Comment by ghost** [comment]
Pardon me, this is my first time doing this, I have good translation skills but little understanding of the whole task. I'd like to redo it and properly this time. Could you please reiterate on how What exactly I need to translate and how ? If I inderstand correctly : the French file given in the open bounty summary need to be identical to the english file correct ? Isn't what I did ? Reproduce the english file but all in french keeping the english code on the left column ?

**Comment by ghost** [comment]
Tell me if im wrong but I essentially need to do exactly what I did but place it in the French file. Keeping the same Strings and strings order from the english file but in the french one. So add the missing/remove or move strings ?

**Comment by andytudhope** [comment]
No problem. And yes, your second comment is exactly correct, that would be awesome. And thanks so much for getting your hands dirty 😉 Copy-paste what you have done, close this pull request, put it all in the french file (fr.cljs) and submit a new PR that says `Fixes #2331` (the issue number, not your PR number) in the description.

**Comment by andytudhope** [comment]
Also @titoburito, it turns out we have already reviewed and OK'd the other french translation, so no need for you to duplicate that work. Please join us in chat.status.im to stay up-to-date with developments and find other bounties you can work on...

**Comment by ghost** [comment]
Please update it in the bounty list so other people dont translate stuff for nothing, thank you

**Comment by yenda** [comment]
Thanks for your effort, as mentionned this was already translated, sorry about that :/

When you look at an issue, Github shows you if there is already a PR for an issue: https://github.com/status-im/status-react/issues/2331

screenshot from 2017-11-13 13-45-17

**Pull request closed without merging**
