### PR TITLE
refactor_: rename LOG_REQUEST_GO to API_LOGGING_ENABLED

### PR DESCRIPTION
**Pull request by qfrank**
Changes:

- Rename LOG_REQUEST_GO env variable to API_LOGGING_ENABLED across all env files
- Rename requests.log to api.log for consistency
- Remove standalone initLogging functionality from native modules as it's now handled within InitializeApplication
- Add logging configuration (logEnabled, logLevel, apiLoggingEnabled) to InitializeApplication params
- Add logDir parameter for Android to ensure proper log file location

This change consolidates logging initialization into the InitializeApplication flow and makes the naming more consistent with its actual functionality.

relate status-go [PR](https://github.com/status-im/status-go/pull/6117)

Testing NOTE: we should see `api.log` rather than `requests.log` in log zip file when share logs.

#### Platforms

- Android
- iOS

##### Functional

- error report
- share logs

status: ready

### CODE REVIEW

**Review by ilmotta — APPROVED** [review]

**Comment by mariia-skrypnyk** [comment]
Hi @qfrank !

Can you please resolve the conflicts?

**Comment by qfrank** [comment]
> Hi @qfrank !
> 
> Can you please resolve the conflicts?

resolved

**Comment by igor-sirotin** [comment]
https://github.com/status-im/status-go/pull/6117 is ready to merge, please let me know when this PR is tested 🙏

**Comment by mariia-skrypnyk** [comment]
@qfrank !

Sorry but we need to do a rebase once more as I want to check regression that could be after https://github.com/status-im/status-mobile/pull/21541 and it was merged after your previous rebase.

**Comment by igor-sirotin** [comment]
> Sorry but we need to do a rebase once more as I want to check regression that could be after #21541 and it was merged after your previous rebase.

@mariia-skrypnyk rebased 👌

**Comment by mariia-skrypnyk** [comment]
@qfrank 

I see an issue that send on Testnet is not working.
Mainnet s fine.
Please, take a look is it PR related or not.
Low Priority.

**ISSUE 1: error occurs when user tries to send tokens**

**Steps:**

1. Login to app
2. Try to send ETH on testnet to another user or between your accounts

**Actual result:**

After transaction confirmation user sees an error, transaction didn't appear in a blockchain.

[testnet_send.zip](https://github.com/user-attachments/files/17949570/testnet_send.zip)
photo_2024-11-28_15-48-41


https://github.com/user-attachments/assets/f7482512-6db1-4a8d-8d37-0be0ca1fb32d

**Comment by igor-sirotin** [comment]
> **ISSUE 1: error occurs when user tries to send tokens**

Thanks @mariia-skrypnyk!
The issue looks not related to the changes. But let's wait for @qfrank to confirm, doesn't hurt to wait 👌

**Review by jakubgs — APPROVED** [review]
Seems fine to me.

**Comment by qfrank** [comment]
> > **ISSUE 1: error occurs when user tries to send tokens**
> 
> Thanks @mariia-skrypnyk! The issue looks not related to the changes. But let's wait for @qfrank to confirm, doesn't hurt to wait 👌

Issue 1 is not related to this PR cc @mariia-skrypnyk

**Comment by mariia-skrypnyk** [comment]
Thanks @qfrank !

Please resolve conflicts, I'll reran tests.

**Comment by qfrank** [comment]
> Thanks @qfrank !
> 
> Please resolve conflicts, I'll reran tests.

done @mariia-skrypnyk

**Comment by mariia-skrypnyk** [comment]
Hi @qfrank !

Thanks, PR can be merged!

**Comment by igor-sirotin** [comment]
Merging status-go side then, thanks @mariia-skrypnyk @qfrank ❤️

**Pull request merged**
