### PR TITLE
[#5584] Implement Manage permissions screen and option for web3 provi…

### LINKED ISSUE #5584: Implement Manage permissions screen and option for web3 provider Opt-in access
### Description

*Type*: Feature

*Summary*: 
Nov 2 deadline

Continue implementation of https://github.com/status-im/status-react/issues/5260 task. First part was implemented in https://github.com/status-im/status-react/pull/5497 (web3 injection was a priority). This task implements `manage permissions` screen and option.

#### Expected behavior

image

The design currently shows a link to the `Manage permissions` screen, which has been dropped.

Instead, a user can simply find their settings from the profile screen. The `Web3 permissions` option can be listed beneath `Network`. 

image

### PR DESCRIPTION
**Pull request by flexsurfer**
fixes #5584

### CODE REVIEW

**Review by dmitryn — APPROVED** [review]

**Review by jeluard — APPROVED** [review]

**Comment by denis-sharypin** [comment]
@flexsurfer  Can we use a Dapp icon that could be found in the [figma file](https://www.figma.com/file/JEYzJxBPSmuLBffZO0CT9rj2/Web3-and-Status-API-permissions?node-id=41%3A38) everywhere
screenshot 2019-02-04 13 13 32

**Comment by flexsurfer** [comment]
@denis-sharypin done!

**Review by denis-sharypin — APPROVED** [review]

**Comment by asemiankevich** [comment]
@flexsurfer 

1. ios still says `infura.io` everywhere

image

android uses Dapp name
image

2. on android please correct dapp icon as @denis-sharypin said 
image

3. revoke access button revokes all the access granted (both wallet and profile ) - is this expected?

4. got this error (under 3G right now, so blaming connection). I believe it should be in develop too but want to check with you 
image

**Comment by flexsurfer** [comment]
@asemiankevich thanks !
1. everywhere? is it for status test dapp?
2. we show D icon only for dapps which are not in list, so this is as designed
3. as designed
4. interesting error, but not related to this PR

**Comment by asemiankevich** [comment]
@flexsurfer  regarding point 1 - i checked with ens names and it is `names.statusnet.eth` in permissions screen:

image

alright if all this is expected then merge it

**Comment by flexsurfer** [comment]
@asemiankevich could you please create a separate issue for 4? thank you!

**Comment by asemiankevich** [comment]
> @asemiankevich could you please create a separate issue for 4? thank you!

it is there already https://github.com/status-im/status-react/issues/7427

**Pull request merged**
