### PR TITLE
web3 opt-in updates

### PR DESCRIPTION
**Pull request by flexsurfer**
Updates according to latest changes in EIP

QA:
1) Open Status Test Dapp , check if it works
2) Go to profile, enable dev mode, enable web3 opt-in mode, go to Status Test Dapp

image

### CODE REVIEW

**Review by goranjovic — APPROVED** [review]

**Review by jeluard — APPROVED** [review]

**Comment by Serhy** [comment]
@flexsurfer , could you please resolve conflicts?

**Comment by flexsurfer** [comment]
@Serhy done

**Comment by flexsurfer** [comment]
@Serhy done one more time

**Comment by Serhy** [comment]
Looks good @flexsurfer ! Failed autotests confirmed as false fails, not related to this fix.

**Pull request merged**
