### PR TITLE
display-name -> preferred-name

### LINKED ISSUE #15067: Username set on desktop is not shown in mobile profile
# Bug Report

## Problem 
Checked in the scope of rc-1.
When using the existing sync flow (Profile > Sync > Devices) username set on the desktop is not shown in the user profile, however it is shown on login view.

#### Expected behavior
All data is synced

#### Actual behavior

https://user-images.githubusercontent.com/4557972/218162367-f75e7286-178d-450b-9bd6-6f9157072327.mp4

### Reproduction
**Prerequisites**: have multiaccount on desktop 
1) mobile: restore the same multiaccount 
2) desktop: sync desktop > mobile (Desktop > Device settings)
3) mobile: check the profile

### Additional Information

- Status version: rc-1 #300 
- Operating System: Android, iOS

### PR DESCRIPTION
**Pull request by vitvly**
Use `display-name` in profile view. Depends on https://github.com/status-im/status-go/pull/3193, which fixes account list name display.

Fixes #15067

### CODE REVIEW

**Review by siddarthkay — APPROVED** [review]

**Comment by cammellos** [comment]
@siphiuel would you mind rebasing with the latest version of status-go, I have also marked this as ready for review

**Comment by vitvly** [comment]
@cammellos yes, sorry, done

**Comment by churik** [comment]
@siphiuel thank you for fix!
Everything is synced, but only after re-login.

**Steps:**
- recover multiaccount from desktop on mobile
- open settings > device settings > enable ID of mobile device (can be found under Sync settings > devices)
- click on "Sync all"
- wait and pay attention to displayed name and contacts


**Expected result:** all data is synced
**Actual result:** all data is synced after re-login only

https://user-images.githubusercontent.com/4557972/219095228-3c848446-ca6d-4fe0-a6c1-4c8c1f95b420.mp4

Logs: [logs (25).zip](https://github.com/status-im/status-mobile/files/10745354/logs.25.zip)

**Comment by vitvly** [comment]
@churik ok, looking into it. Sorry, i checked the opposite flow - updating name on desktop and checking whether update is properly received on mobile.

**Comment by vitvly** [comment]
@churik understand now - when clicking `Sync all devices` it does not sync on-the-fly, but it does sync immediately if e.g. one goes to Desktop's profile, changes name there, and clicks `Save changes`.

**Comment by vitvly** [comment]
@churik sorry, i managed to reproduce it once, added logging on mobile and status-go, and since then cannot reproduce it!
Can you please verify my steps?

1. Create an account on desktop, during creation assign some custom display name.
2. Recover that account on mobile, in Sync Settings->Devices click `Advertise device`.
3. On desktop in Settings->Devices settings, see that new device appeared, enable the toggle next to the name, and click `Sync all devices`
4. Observe that profile name has been updated on mobile, like this:
Screenshot 2023-02-16 at 16 50 20

5. Also, after that in Desktop Settings modify `Display name` and click `Save changes` in the popup. Observe that name changes appeared on mobile.

**Comment by churik** [comment]
@siphiuel yes, the steps are right. let me re-check it

**Comment by churik** [comment]
@siphiuel I can replicate it, but if it is working for you we can add this as a follow-up issue.

**Comment by churik** [comment]
when merging, please, cherry-pick it to release/1.21.x

**Comment by vitvly** [comment]
@churik Thank you, ok! Merged and cherry-picked to `release/1.21.x`.

**Pull request merged**
