### PR TITLE
[FiX #3505] Revert "Use re-frame fork with js/setTimeout as next-tick"

### LINKED ISSUE #3505: Error: No item 1 in vector of length 1
### Description

*Type*: Bug

*Summary*: Error when relogin

`1:37 I/ReactNativeJS: NAME: "Error"
01:37 I/ReactNativeJS: MESSAGE: Error: No item 1 in vector of length 1
01:37 I/ReactNativeJS: 
01:37 I/ReactNativeJS: This error is located at:
01:37 I/ReactNativeJS:     in home
01:37 I/ReactNativeJS:     in reagent21
01:37 I/ReactNativeJS:     in RCTView
01:37 I/ReactNativeJS:     in reagent20
01:37 I/ReactNativeJS:     in with-activity-indicator
01:37 I/ReactNativeJS:     in reagent18
01:37 I/ReactNativeJS:     in RCTView
01:37 I/ReactNativeJS:     in RCTView
01:37 I/ReactNativeJS:     in main-tabs
01:37 I/ReactNativeJS:     in reagent17
01:37 I/ReactNativeJS:     in RCTView
01:37 I/ReactNativeJS:     in main
01:37 I/ReactNativeJS:     in root
01:37 I/ReactNativeJS:     in reagent1
01:37 I/ReactNativeJS:     in RCTView
01:37 I/ReactNativeJS:     in RCTView
01:37 I/ReactNativeJS:     in t`

#### Actual behavior

image

#### Scenario 1:
- Open Status
- Logout
- Login back and wait for some time
It happens also when deleting chat and loggin back

#### Scenario 2:
On Pixel XL Android 8.1.0/Galaxy S6 Android 6.0.1(Android only). Can't reproduce in Genymotion emulator Nexus 6P:
- Install Status
- Create account (share usage data)
- as soon as first screen shown - close the app (do not use any ui elements)
- run app
- log in and error is shown

Creating account: https://app.testfairy.com/projects/4803622-status/builds/7812304/sessions/23/?accessToken=SbPb3WEndfneUNeRjHdJHHY4u/U
Log in (error): https://app.testfairy.com/projects/4803622-status/builds/7812304/sessions/24/?accessToken=dk-8Z6AZxuXAkORAYxICvT5F6/k

### Additional Information
* Status version: latest nightly 260
* Operating System: Android, iOS

#### Logs
https://app.testfairy.com/projects/4803622-status/builds/7812289/sessions/3/?accessToken=t8sODtp2IvtLTkVG4nOrqNGFttY

### PR DESCRIPTION
**Pull request by yenda**
This reverts commit ac9b5cd976d6a4aff3e820dcdb39a6a8e0255486.

fix #3505 

status: ready

### CODE REVIEW

**Review by dmitryn — APPROVED** [review]

**Review by oskarth — APPROVED** [review]

**Review by flexsurfer — APPROVED** [review]

**Review by janherich — APPROVED** [review]

**Comment by dmitryn** [comment]
Just FYI:

I've just faced https://github.com/status-im/status-react/issues/3505 while using original re-frame 0.10.5 (while integrating re-frame-10x). 
Reproduced with:
- create account
- restart the app 
- sign in

**Comment by dmitryn** [comment]
Anyways, re-frame-10x requires re-frame version 0.10.5 or higher so reverting to original re-frame speeds up the integration. Otherwise, we need to upgrade our fork from 0.10.2 to 0.10.5.

**Comment by yenda** [comment]
@dmitryn judging from https://github.com/status-im/re-frame/commits/react-native-next-tick-fix it seems our fork is already 0.10.4 even if it says 0.10.2

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/status-im/re-frame">status-im/re-frame</a></strong></div><div>re-frame - A Reagent Framework For Writing SPAs, in Clojurescript.</div></blockquote>

**Comment by yenda** [comment]
@dmitryn which means faulty commit in re-frame was introduces between 0.10.2 (excluded) and 0.10.4 (included)

**Comment by dmitryn** [comment]
>judging from https://github.com/status-im/re-frame/commits/react-native-next-tick-fix it seems our fork is already 0.10.4 even if it says 0.10.2

@yenda we use this branch https://github.com/status-im/re-frame/commits/0.10.2 to deploy jar to clojars. I've just removed `react-native-next-tick-fix` branch to not confuse you.

**Comment by dmitryn** [comment]
@yenda we found error root cause https://github.com/status-im/status-react/pull/3523

**Comment by flexsurfer** [comment]
@yenda let's close this and keep re-frame fork

**Pull request closed without merging**
