### PR TITLE
update status/wakuv2 fleets DNS discovery enrtree

### PR DESCRIPTION
**Pull request by yakimant**
### Summary

Enrtrees were regenerated and need to be changed.

### Testing notes

Please test DNS

### CODE REVIEW

**Review by flexsurfer — APPROVED** [review]

**Comment by flexsurfer** [comment]
@yakimant please run `make lint-fix`

**Comment by yakimant** [comment]
@flexsurfer, thanks!
I wanted to improve a bit =)

**Review by jakubgs — APPROVED** [review]

**Comment by pavloburykh** [comment]
According to the logs currently app is still using old addresses. @cammellos and @richard-ramos are working on the fix.

**Comment by jakubgs** [comment]
@pavloburykh I guess that's because this has not been merged yet and is not being used by the app:

* https://github.com/status-im/status-go/pull/4063

**Comment by pavloburykh** [comment]
@jakubgs thanks, we were not aware that there are also changes on go side. 
I guess we need to update status-go version in this PR to the correspondent go branch https://github.com/status-im/status-go/pull/4063 in order we be able to test it before merge **cc @yakimant**

**Comment by flexsurfer** [comment]
should we close this one, because of https://github.com/status-im/status-mobile/pull/17442 ?

**Comment by yakimant** [comment]
@flexsurfer, status-go still needs to be tested.

**Comment by cammellos** [comment]
@yakimant I have included your commits in my PR, and QA will test them together (it required some changes in status-go as well), I will close it for now and let you know. Feel free to re-open if you think is necessary, but I think we are covered as your commit has been cherry picked.

Thank you!

**Comment by yakimant** [comment]
@cammellos, yes, I see you have `status-go` version changed. Thanks!

**Pull request closed without merging**
