### PR TITLE
[#12526] Connecting autofarm.network dapps with status wallet freezes…

### LINKED ISSUE #12526: Connecting autofarm.network dapps with status wallet freezes browser
## Context
On ethereum mainnet, autofarm.network dApps works well with meta mask. 

## Issue
On ethereum mainnet, a user can't properly connect his wallet to autofarm.network dapps.

## Reproduction
- Status on mainnet 
- with browser go to https://autofarm.network 
- the user gets the bottom pop-up telling him autofarm wants to connect to his wallet 
- if user approves the connection, then status browser gets freezed

### PR DESCRIPTION
**Pull request by flexsurfer**
fixes #12526

QA: check other most popular dapps are not affected

### CODE REVIEW

**Comment by qoqobolo** [comment]
@flexsurfer thank you for this prompt fix!

There is an issue with switching between wallet accounts in `autofarm.network` dapp on iOS.
If open `autofarm.network`, switch to another account (probably switch one more time), and tap `Allow` after connecting the wallet, then the entire Browser screen will be frozen. It will not be possible to scroll the screen and use `back`, `forward`, `tabs`, and other buttons until the next reopening of the app.
The issue is reproducible on iOS only.

**_Steps:_**
1. Open Wallet and add a new account
2. Open Browser tab and navigate to autofarm.network
3. Connect wallet
4. Tap `account` button and switch to the secondary account
5. Tap `Allow`

You may need to switch again to reproduce the issue.

Screenshot 2021-09-02 at 13 11 02

**Comment by flexsurfer** [comment]
@qoqobolo is it replicated only with this dapp and in this PR ? or it can be replicated in develop with another dapp ?

**Comment by flexsurfer** [comment]
i don't think its related to this PR

**Comment by flexsurfer** [comment]
lets merge PR and create another issue

**Comment by qoqobolo** [comment]
@flexsurfer yeah, the issue is not replicated for other dapps in our Store. 
So I agree, that we can go with it and investigate it later.

**Pull request merged**
