### PR TITLE
[#11627] Add GRT erc20 token in our default list of supported tokens …

### LINKED ISSUE #11627: Add GRT erc20 token in our default list of supported tokens in the wallet
**summary** 
add GRT erc20 token to our default list of erc20 token supported by the wallet 

**user story** 
a user holding GRT token in his wallet account should see in his list of assets the number of GRT tokens he holds

**details**
the token details (name, contract address, decimals) are here (provided by the Graph team directly)
https://docs.google.com/document/d/1zFXNliXfeie5ufukQjXLxWI8rqavZIZVx1-cb3qKqy8/edit
and logo here 
[logo](https://drive.google.com/drive/folders/17yaoidIUTd2OQqRKeLW52Vfw7J5QXGT_)

### PR DESCRIPTION
**Pull request by flexsurfer**
fixes #11627

### CODE REVIEW

**Review by guylouis — APPROVED** [review]

**Comment by flexsurfer** [comment]
WAITING FOR E2E

**Comment by churik** [comment]
@flexsurfer I'm now instead of e2e :)
image

**Comment by flexsurfer** [comment]
thanks @churik , fixed

**Comment by flexsurfer** [comment]
@churik could you try the latest build pls

**Comment by churik** [comment]
ready to be merged

**Pull request merged**
