### PR TITLE
fix: use image clock when updating profile images to cause re-render

### LINKED ISSUE #21787: Profile photo is not updated until re-login when it is not empty
# Bug Report

## Problem 

The picture is not updated on mobile after setting it (if it is not the first time). So far most visible on IOS.

#### Expected behavior

The profile picture is updated

#### Actual behavior

https://github.com/user-attachments/assets/ef50eec2-1aeb-46f1-add3-ada03f8ca963

On both apps the profile picture will be updated after reopening.

### Reproduction

1. Open profile
2. Change the picture several times.

### Additional Information

- Status version: release 2.32 
- Operating System: Android, iOS, desktop

[logs (25).zip](https://github.com/user-attachments/files/18081237/logs.25.zip)

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by seanstrom**
fixes https://github.com/status-im/status-mobile/issues/21787

### Summary

* This PR attempts to fix an issue with account images not re-rendering after updating the profile image.
  * Currently this PR fixes the issue by associating a `clock` value to the identity images that are returned by status-go, because for some reason the clocks are defaulted to `0`.
  * Likely we'll need to update status-go to populate the image clocks before forwarding the results.

#### Platforms

- Android
- iOS

##### Functional

* Profile images

### Steps to test

WIP

#### After Changes on iOS

https://github.com/user-attachments/assets/171d6565-5815-49dd-bb5b-6d0a0c22e6e6

status: ready

### CODE REVIEW

**Review by ilmotta — APPROVED** [review]
Tested PR and it all worked for me 🚀

**Comment by seanstrom** [comment]
@status-im/mobile-qa I've rebased this PR to be based on the current release branch `2.32.x`. And the PR will now merge into the release branch when approved. Hopefully this will make the testing experience smoother.

Let me know if there's anything else I can help with 🙏

**Review by ulisesmac — APPROVED** [review]
Looks great! Thanks for fixing it @seanstrom

**Comment by churik** [comment]
Confirmed that the issue with updating is gone, the issue with sync > update is still presented, I'll report it separately

Thank you @seanstrom

**Pull request merged**
