### PR TITLE
[#7799] fix chat does not scroll if touch starts on top of datemark

### LINKED ISSUE #7799: chat does not scroll if touch starts on top of datemark
# Problem

In mobile, in any particular chat with messages, if you touch on the datemark separator(e.g. "Today", "Yesterday") while beginning to scroll - it doesn't scroll.

# Solution

Make the root view of status-im.ui.screens.chat.message.datemark/chat-datemark component a react/touchable-without-feedback view rather than plain react/view

PR incoming

### PR DESCRIPTION
**Pull request by bitsikka**
Fixes #7799 

status: ready

### CODE REVIEW

**Review by yenda — APPROVED** [review]

**Review by flexsurfer — APPROVED** [review]

**Comment by churik** [comment]
@bitsikka can you please rebase it to latest develop? 
Thanks!

**Comment by bitsikka** [comment]
> @bitsikka can you please rebase it to latest develop?
> Thanks!

sure can

coming up!

**Comment by churik** [comment]
Tested chat scrolling and chat list scrolling on Android 8, IOS 11.4.1, Mac OSx in 1-1, public and group chats.
Looks good to me.

**Comment by mandrigin** [comment]
@bitsikka thank you for your help! great job!

**Pull request merged**
