### PR TITLE
[TESTS] build and trigger for e2e tests added to release builds

### PR DESCRIPTION
**Pull request by antdanchenko**
* added (copied from Jenkinsfile.nightly_fastlane ) android build for e2e tests and trigger for end-to-end-tests/status-app-nightly

### CODE REVIEW

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/zJHyvp for branch PR-4516

<blockquote><div><strong><a href="https://i.diawi.com/zJHyvp">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/eGLx4s for branch PR-4516

<blockquote><div><strong><a href="https://i.diawi.com/eGLx4s">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Review by jakubgs — APPROVED** [review]
lgtm

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/d5h8pZ for branch PR-4516

<blockquote><div><strong><a href="https://i.diawi.com/d5h8pZ">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/DMfTrk for branch PR-4516

<blockquote><div><strong><a href="https://i.diawi.com/DMfTrk">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/Kf9rcC for branch PR-4516

<blockquote><div><strong><a href="https://i.diawi.com/Kf9rcC">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/GorJMf for branch PR-4516

<blockquote><div><strong><a href="https://i.diawi.com/GorJMf">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Review by mandrigin — APPROVED** [review]
lgtm

**Pull request merged**
