### PR TITLE
Use STATUS_GO_VERSION for desktop

### PR DESCRIPTION
**Pull request by vitvly**

### CODE REVIEW

**Review by maxhora — APPROVED** [review]

**Review by yenda — APPROVED** [review]

**Review by vkjr — APPROVED** [review]

**Review by yenda — COMMENTED** [review]
why the change on the package-lock ? isn't it going to break when master changes ?

**Comment by SlizkovaGanna** [comment]
Hey, @siphiuel!
There is no description in this PR - am I right that nothing should be changed in app functionality with this update?
Thank you.

**Comment by vitvly** [comment]
@yenda I've removed it. However, now I'm getting
```
Command failed: /usr/local/bin/git checkout 67a4c72a9353ebd589492f08218b218bc020997a
npm ERR! fatal: reference is not a tree: 67a4c72a9353ebd589492f08218b218bc020997a
``` 
during `make dev-desktop`. Maybe it's some local problem.

**Comment by vitvly** [comment]
@SlizkovaGanna Hi Ganna! Right, there are no changes functionality-wise.

**Comment by churik** [comment]
@siphiuel am I right that STATUS_GO_VERSION moved to separate constant and in future will be changed in one place for mobile and desktop?

**Comment by churik** [comment]
In any case, I didn't notice any regression here. Tested account creation, recovering existing account, joining to public chats.
So looking forward to your answer for https://github.com/status-im/status-react/pull/6344#issuecomment-430923301 and free to merge.

**Comment by vitvly** [comment]
@churik - yes, just one place to change from now on.

**Pull request merged**
