### PR TITLE
Log some message information in debug mode to investigate delivery issues 

### LINKED ISSUE #18206: Add more logging to PR builds to trace lost messages
## Problem
Currently, retrieving the message-id from the logs is not a straightforward process. As a result, there are no simple methods available to trace a specific message within the message history. 

This issue was highlighted during the message reliability meeting, emphasizing the need to streamline the tracing of a particular message using its unique id.

#### Acceptance criteria

To address this problem, the following steps will be taken:

1. Implement the necessary logging on the `DEBUG` level to facilitate easier debugging.
2. This enhanced logging functionality will simplify the process of tracing and debugging specific messages from the logs, i.e. from: [https://github.com/status-im/status-mobile/issues/18031](https://github.com/status-im/status-mobile/issues/18031) **only for e2e and PR builds**

By fulfilling these acceptance criteria, we aim to improve the efficiency and effectiveness of message tracing within the application.

### PR DESCRIPTION
**Pull request by siddarthkay**
related status-go PR : https://github.com/status-im/status-go/pull/4494

fixes: [18206](https://github.com/status-im/status-mobile/issues/18206)

status: ready

### CODE REVIEW

**Review by smohamedjavid — APPROVED** [review]

**Review by ilmotta — APPROVED** [review]

**Review by ajayesivan — APPROVED** [review]

**Comment by pavloburykh** [comment]
Hey @siddarthkay! Thanks for the PR! Could you please clarify what exactly should be manually tested? What should I see in debug logs to verify that changes are ready for merge?

**Comment by siddarthkay** [comment]
Hi @pavloburykh : you can test this case : https://github.com/status-im/status-mobile/issues/18031#issuecomment-1851824116 

In logs you can find message info by searching "sendChatMessage" in `geth.log` , before you extract logs please make sure device log level is set to "DEBUG"

Earlier we only used to log the message ID so we'd know how many messages were sent, but we would not know what was the content of those messages so it was hard to figure out which message was dropped.

**Comment by pavloburykh** [comment]
@siddarthkay thank you for the PR. No issues from my side. If you don't mind, I would perform another e2e run before merging to make sure there are no issues in the rebased go branch. Will ping you when results are ready.

**Comment by siddarthkay** [comment]
Sounds good @pavloburykh, I'll wait for your feedback :)

**Comment by pavloburykh** [comment]
@siddarthkay failed e2e are not PR related. Ready for merge.

**Pull request merged**
