### PR TITLE
feature #3767 - added a number of dapps to the default list

### LINKED ISSUE #3767: Add a new batch of DApps to the default list
As a user I want to try out cool dapps in the Status browser. Also, kitties!

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

*Summary*: Add these dapps to default contacts https://docs.google.com/spreadsheets/d/1cPjVu5AizyGgz6J4PJwK62LQfB8LHTnPmAdJvyBqQLE/edit#gid=492008138

<blockquote><div><strong><a href="https://docs.google.com/spreadsheets/d/1cPjVu5AizyGgz6J4PJwK62LQfB8LHTnPmAdJvyBqQLE/edit#gid=492008138">Google Sheets - create and edit spreadsheets online, for free.</a></strong></div><div>Create a new spreadsheet and edit with others at the same time -- from your computer, phone or tablet. Get stuff done with or without an internet connection. Use Sheets to edit Excel files. Free from Google.</div></blockquote>

### PR DESCRIPTION
**Pull request by goranjovic**
fixes #3767 #3314

### Summary:

Added a number of new dapps to the default list.

### Steps to test:
- Open Status
- Try out new dapps
- Kitties!

status: ready

### CODE REVIEW

**Comment by chadyj** [comment]
@pablanopete 🙏

**Review by jeluard — APPROVED** [review]

**Comment by goranjovic** [comment]
screenshot-2018-04-05_13 31 01 435
screenshot-2018-04-05_13 31 12 176

**Review by flexsurfer — APPROVED** [review]

**Review by chadyj — APPROVED** [review]
❤️

**Comment by chadyj** [comment]
Wow Status feels so much better with a full list of DApps!

**Comment by yevh-berdnyk** [comment]
Android: https://i.diawi.com/b2mNK3
iOS: https://i.diawi.com/G3CwoP

Found an issue with ERC dEX - it's not possible to open it twice
To reproduce:

- Click Plus button -> Open DApp -> ERC dEX -> Open
- Click Back button 
- Swipe and delete ERC dEX chat element
- Click Plus button -> Open DApp -> ERC dEX -> Open

 

Loading indicator is showing for a long time and the DApp page was not finally loaded

However when I created new account on the same device I've opened the ERC dEX successfully but also only once

Reproduced on both Android (LG V20, Android 7.0) and iOS (iPhone 8+, iOS 11.1.1)

aa



<blockquote><div><strong><a href="https://i.diawi.com/b2mNK3">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>
<blockquote><div><strong><a href="https://i.diawi.com/G3CwoP">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by chadyj** [comment]
@yevh-berdnyk Good catch! 
Individual dapp bugs aren't part of this scope. Would you mind creating a new issue for this and giving it a dapp label? 

As long as the list looks good and the URL's are correct we can merge this, then work on individual dapp issues.

**Comment by lukaszfryc** [comment]
Can we add description for each app before merging this PR? @rachelhamlin could you provide the descriptions? 

(It will fix https://github.com/status-im/status-react/issues/1664)

**Comment by lukaszfryc** [comment]
Btw, what criteria did we use to select the dapps? Decentralized, popular, easy to use, ..? Can we list them down as **the inclusion criteria** in https://github.com/status-im/ideas/pull/122?

**Comment by rachelhamlin** [comment]
@lukaszfryc on it re: descriptions. I'm going to repurpose the brands' own copy.

My thoughts on criteria fwiw (not sure we followed specific criteria here?) - a) it should be minimal, and b) the three dimensions that matter are:
- Infrastructure (decentralisation + network compatibility),
- Utility is proven (people can/do make transactions),
- UX supports utility (but really the bar for now is just, is it mobile optimized?)

A UX study w/ real users would be nice and can also feed into developer tools work.

We can use DAU and transaction data from DappRadar to gauge utility. As @chadyj pointed out, DTU is north star so those might be good indicators that people will transact w/ these DApps.

**Comment by chadyj** [comment]
Descriptions are in the app, just not showing. Goran created https://github.com/status-im/status-react/issues/3775 to fix (which looks like a dupe of https://github.com/status-im/status-react/issues/1664).

If this issue is ready to go and doesn't break/alter any existing issues, then merge it. No need to wait.

**Comment by lukaszfryc** [comment]
Let's merge it then. @yevh-berdnyk please create a separate issue about the "ERC dEX" dapp.

**Comment by yevh-berdnyk** [comment]
Created #3805

**Review by rachelhamlin — APPROVED** [review]

**Pull request merged**
