### PR TITLE
Keep current version of app in the VERSION file

### PR DESCRIPTION
**Pull request by jakubgs**
Since tagging commits is a very fragile setup that keeps causing problems I think having a clear place where the current version of the app is stored is a good idea. That file is `VERSION` at the root of the repo which simply contains something like `0.9.19` and is used in all `Jeninsfile`s, all Fastlane files, all gradle build configs.

### CODE REVIEW

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/m4R7Hy for branch PR-4420

<blockquote><div><strong><a href="https://i.diawi.com/m4R7Hy">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Review by mandrigin — APPROVED** [review]
I like this approach much more than relying on tag.

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/gTvV4L for branch PR-4420

<blockquote><div><strong><a href="https://i.diawi.com/gTvV4L">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/x7dDq6 for branch PR-4420

<blockquote><div><strong><a href="https://i.diawi.com/x7dDq6">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/ZaY2Ma for branch PR-4420

<blockquote><div><strong><a href="https://i.diawi.com/ZaY2Ma">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/rzSnd4 for branch PR-4420

<blockquote><div><strong><a href="https://i.diawi.com/rzSnd4">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Pull request merged**
