### PR TITLE
Timeout and abort Jenkins jobs after 90 minutes.

### PR DESCRIPTION
**Pull request by mandrigin**
One more step to make our CI more robust.

status: ready 

PS: set your diff settings to ignore whitespace changes to simplify reviewing 😉

### CODE REVIEW

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/rzhusM for branch PR-4368

<blockquote><div><strong><a href="https://i.diawi.com/rzhusM">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/ZVZHnr for branch PR-4368

<blockquote><div><strong><a href="https://i.diawi.com/ZVZHnr">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Review by yevh-berdnyk — APPROVED** [review]

**Comment by jakubgs** [comment]
I really like the idea, but wouldn't it make more sense to wrap each stage in a timeout of about 3x it's average run time? Or is that too granular?

**Review by jakubgs — APPROVED** [review]

**Comment by mandrigin** [comment]
That would be a yet another improvement :)

**Pull request merged**
