### PR TITLE
Feature/tabs ui refresh

### PR DESCRIPTION
**Pull request by GustavoNunes**
### Summary:
Changes to the tab bar styles and behaviour:
- New icons, active and inactive variants
- Tab title always present, style changed if active
- Hide bar when in search or edit mode

status: done

### CODE REVIEW

**Comment by GustavoNunes** [comment]
I need some help with this issue. In [commit fcfe296](https://github.com/status-im/status-react/pull/863/commits/fcfe296985e4c6aabf159fd7e47e673fe5343529) I created a new subscription containing the logic about when to hide the tabs, used it in the `tabs` component, and they were hiding fine.

Then in the next commit, [e6bc230](https://github.com/status-im/status-react/pull/863/commits/e6bc23072a9198e58b0631b460f0a3defd1199a3), I've used that subscription in the `main-tabs` component, to grow its height when the tabs are hidden.
However, in this commit an issue appeared, with these steps to reproduce:
1. Log in, lands in chats list screen.
2. Entering search or edit function works perfectly, the tabs get hidden.
3. Navigate to another tab, then navigate back to chats screen.
4. Entering search or edit function now causes a crash.

What I found out:
- In step 4, entering the search or the edit function triggers the `navigate-to-tab` event, when it shouldn't. [This hack](https://github.com/status-im/status-react/pull/863/commits/4c36013d7e9318a254a2243276cf82bc85352171) fixes the crash, but other navigation issues appears (the tab bar and swiper gets out of sync).
- More generally, the toolbar actions are triggering onMomentumScrollEnd in the swiper (ultimately triggering `navigate-to-tab`), this is driving me crazy because I can't find why.
- When all derefs to the `tabs-hidden` subscription are removed from the `main-tabs` render function, onMomentumScrollEnd doesn't get triggered by the toolbar actions.

**Comment by GustavoNunes** [comment]
@rasom this PR is ready, thanks for the help. Thank you too, @flexsurfer!

**Comment by rasom** [comment]
@GustavoNunes, please resolve conflicts and I will merge PR

**Comment by GustavoNunes** [comment]
done @rasom, I fixed them using the new macros and it worked fine. Tested in Android and iOS. Thanks!

**Pull request merged**
