### PR TITLE
Enable links within messages (#638)

### LINKED ISSUE #638: Enable links within messages
Currently links are plaintext within messages, we should parse these and make them navigatable. 

e78894b9d23f872ecd3509942106e819_original

https://instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/113

### PR DESCRIPTION
**Pull request by alwx**
Fixes #638

### CODE REVIEW

**Comment by jarradh** [comment]
does this open links with `/browse`?

**Comment by rasom** [comment]
Nope, missed this point

**Comment by jarradh** [comment]
we never discussed, but imo it should?

**Comment by rasom** [comment]
Yes, it makes sense.

**Pull request merged**
