### PR TITLE
Fix: nickname modal iOS bottom space

### LINKED ISSUE #15940: Zero bottom padding for "Add nickname" on iOS
unnamed (1)

### PR DESCRIPTION
**Pull request by OmarBasem**
fixes: https://github.com/status-im/status-mobile/issues/15940

### CODE REVIEW

**Review by ibrkhalil — APPROVED** [review]
Thank you

**Comment by OmarBasem** [comment]
Hey @ibrkhalil, is there something specific you are requesting manual qa for? This PR just adds some margin below the buttons

**Comment by ibrkhalil** [comment]
> Hey @ibrkhalil, is there something specific you are requesting manual qa for? This PR just adds some margin below the buttons

Nothing specific, But I just got used to the process of seeking QA approval.

**Comment by pavloburykh** [comment]
@OmarBasem thanx! tested and ready for merge.

**Pull request merged**
