### PR TITLE
Jenkins now downloads package with correct Info.plist

### LINKED ISSUE #4270: Fonts and images shouldn't look blurry in Desktop app
### User Story

As a user I want to have a good experience when using Status Desktop App. Please check https://app.zeplin.io/project/5a324ae5d60d197e7e3369cc/dashboard

### Description

*Type*: Bug

*Summary*: Provide and implement high-quality images for Status Desktop. 

#### Expected behavior
Status Desktop UI is not blurry 

#### Actual behavior
Status desktop UI is poor quality

### Reproduction

- Open Status Desktop
- Click through the app

### Additional Information
* Operating System: macOS

### PR DESCRIPTION
**Pull request by vkjr**
fixes #4270

### Summary:

It turned out that we have to specify one more key in desktop bundle Info.plist file to turn on the support of hdpi. The line is following:
```
<key>NSHighResolutionCapable</key>
<string>True</string>
```

During the build Jenkins downloads prepared desktop bundle from google drive, adds compiled binaries and wraps all abovementioned in StatusIm.dmg.
I modified the `Info.plist` in the prepared bundle to contain abovementioned changes. So only change in this PR is an id of package on google drive.

Full package link - https://drive.google.com/uc?export=download&id=1Vkb6MD3nsmT02Az6rRRZywQSwCz1ZN9V

### Steps to test:
- Open Status
- Check that fonts and images doesn't look blurry

status: ready

### CODE REVIEW

**Review by maxhora — APPROVED** [review]

**Comment by maxhora** [comment]
We probably can benefit if will put deployment related files into the `deployment/macos` directory under git (we already have similar for linux). Probably, the task for near future.
Also such directory can contain appropriate ".env" settings file which is used on production for specific platform or for both platforms.

**Comment by vkjr** [comment]
@MaxRis, could you please run built bundle for this PR? Looks like I'm getting an app hanging on startup. Would like to check if you have the same.

**Comment by maxhora** [comment]
@vkjr yes, it hangs for me as well on start with 100% CPU load

**Comment by vkjr** [comment]
@maxris, thanks. Will investigate the issue.

**Comment by vkjr** [comment]
It turned out that `ubuntu-server` wasn't getting exec permissions after unzipping on Jenkins. Now fixed.

**Review by rcullito — APPROVED** [review]
nice find :+1:

**Comment by churik** [comment]
@cammelos can you please review this PT? 
Thanks in advance!

**Pull request merged**
