### PR TITLE
ci: don't rebase release branches on `develop`

### PR DESCRIPTION
**Pull request by mandrigin**
otherwise our release branches get some weird changes.

status: ready

### CODE REVIEW

**Review by jakubgs — APPROVED** [review]
Good idea.

**Review by pedropombeiro — APPROVED** [review]
Nice!

**Review by yenda — APPROVED** [review]

**Comment by mandrigin** [comment]
will skip QA completely, if there was an error there, it wouldn't even build.

**Review by rasom — APPROVED** [review]

**Comment by mandrigin** [comment]
ios fails on unrelated thing, I'll merge it anyway and add a temp workaround

```
[2019-02-28T08:22:02.872Z] [08:22:02]: {"responseId"=>"db5ab18f-34a7-4233-9aa6-fe328f7d3aa1", "resultCode"=>90002, "resultString"=>"Two-factor authentication must be turned on for your Apple ID. After you turn it on, signing in to your developer account will require both your password and access to your trusted devices or trusted phone number. \n\nTo learn more, see https://developer.apple.com/support/account/authentication/.", "userString"=>"Two-factor authentication must be turned on for your Apple ID. After you turn it on, signing in to your developer account will require both your password and access to your trusted devices or trusted phone number. \n\nTo learn more, see https://developer.apple.com/support/account/authentication/.", "creationTimestamp"=>"2019-02-28T08:22:02Z", "protocolVersion"=>"QH65B2", "userLocale"=>"en_US", "requestUrl"=>"https://developer.apple.com/services-account/QH65B2/account/ios/identifiers/listAppIds.action", "httpCode"=>200}
```

**Pull request merged**
