### PR TITLE
Add Status Waku v2 nodes to fleet configuration

### LINKED ISSUE #13952: Add Status Waku v2 nodes to fleet configuration
# Problem

Add Status Waku v2 nodes to fleet configuration, thus allowing

- connecting to fleets that don't have v1 to v2 bridge (i.e. `status.prod`)
- cross-platform dogfooding on Status nodes

## Implementation

- Possibly extend https://github.com/status-im/status-mobile/blob/b05787b0b2883a6ebc87e276bb49965cb055a1a6/resources/config/fleets.json for https://github.com/status-im/status-desktop/blob/c2c2532986de1391bcc0cc6430da5f7d7d6d50ff/fleets.json
- And update any other files relevant to loading the configuration
  - Maybe those referencing `wakuv2-config` like `src/status_im/node/core.cljs`, `src/status_im/multiaccounts/login/core.cljs` and `src/status_im/waku/core.cljs`

## Acceptance Criteria

- When connected to a Status peer, a sent message is received by Desktop and Web clients

### PR DESCRIPTION
**Pull request by felicio**
[comment]: # (Please replace ... with your information. Remove < and >)
[comment]: # (To auto-close issue on merge, please insert the related issue number after # i.e fixes #566)

### Summary

[comment]: # (Summarise the problem and how the pull request solves it)
Resolves #13952

#### Platforms

- Android
- iOS
- macOS
- Linux
- Windows

##### Functional

- communities
- 1-1 chats
- public chats
- group chats
- user profile updates
- fleet

### Steps to test

1. The `status.prod` and `status.test` fleets are under Settings > Advanced > Fleet
2. When both Mobile and Desktop have `status.test` set, then messages between them should be delivered in real time.
3. When both Mobile and Desktop have `status.prod` set, then messages between them should be delivered in real time.
4. When Mobile has `status.test` set and  Desktop has `eth.test` set, then messages from Desktop should be delivered in real time to Mobile.
5. When Mobile has `status.test` set and Desktop has `wakuv2.prod` set, and when messages are sent from Mobile and Desktop is later set to `status.test`, then messages should be retrieved on Desktop from history.

status: wip

### CODE REVIEW

**Comment by ghost** [comment]
Hey @felicio, and thank you so much for making your first pull request in status-mobile! :heart: Please help us make your experience better by filling out this brief questionnaire https://goo.gl/forms/uWqNcVpVz7OIopXg2

**Comment by churik** [comment]
Hello @felicio !
To clarify: do you just need the new fleet in the list or expect us to check history node functionality on this fleet?
Please, ping me when it is ready to be tested and rebase your repo according to the current `develop`  branch.
Thank you!

**Comment by felicio** [comment]
Hey,

@churik,

> Please, ping me when it is ready to be tested and rebase your repo according to the current develop branch.

Will do.

> To clarify: do you just need the new fleet in the list or expect us to check history node functionality on this fleet?

Both, and relaying (real-time delivery) too.

When ready, I would like to ask you to help me check that:

1. The `status.prod` and `status.test` fleets are under Settings > Advanced > Fleet
2. When both Mobile and Desktop have `status.test` set, then messages between them should be delivered in real time.
3. When both Mobile and Desktop have `status.prod` set, then messages between them should be delivered in real time.
4. When Mobile has `status.test` set and  Desktop has `eth.test` set, then messages from Desktop should be delivered in real time to Mobile.
5. When Mobile has `status.test` set and Desktop has `wakuv2.prod` set, and when messages are sent from Mobile and Desktop is later set to `status.test`, then messages should be retrieved on Desktop from history. 

On web, I could check that afterwards since it hasn't been deployed yet. Or I could do that in paralel to your testing.

@flexsurfer,

By moving this to "E2E tests" you meant to let me know that the changes are legit, as far as you could tell, and that you don't think any other adjustements should be made? Not even the following?

> - And update any other files relevant to loading the configuration
> 	- Maybe those referencing wakuv2-config like src/status_im/node/core.cljs, src/status_im/multiaccounts/login/core.cljs and src/status_im/waku/core.cljs
>
> – https://github.com/status-im/status-mobile/issues/13952#issue-1365689517

I haven't found time to build this and run it locally yet and wanted to avoid requesting QA prematurely.

Guys,

Finally, in the mean time I'll move this to "To rebase" if it's alright with you.

**Comment by flexsurfer** [comment]
sorry moved by mistake

**Comment by flexsurfer** [comment]
https://github.com/status-im/status-mobile/pull/14283

**Pull request closed without merging**
