### PR TITLE
[16467] Fix delete for me doesn't work on chat reopen

### LINKED ISSUE #16467: Sent image/album reappears in chat after reopening chat if "delete for me" option is used
### Steps to reproduce:
1. `B` keeps chat as opened
2. `A` sends a message with at least 1 image to `B`
3. `B` long-tap on the message -> select 'delete for me' option
4. `B` reopen the chat

### Actual result:
After reopening the chat, the previously deleted album reappears in the chat.

https://github.com/status-im/status-mobile/assets/52490791/710566c4-3a3d-4b85-931b-efb4545c9866

### Expected result
The album should remain deleted and not reappear in the chat after reopening.

### ENV:
Nightly: [3 Jul 2023]

### PR DESCRIPTION
**Pull request by ibrkhalil**
fixes #16467 

### Summary
On status-go we used localChatId key instead of chatId to delete-message-for-me, Reverting that change fixed it.

status: ready

### CODE REVIEW

**Review by Parveshdhull — APPROVED** [review]

**Comment by pavloburykh** [comment]
@ibrkhalil hi! PR is blocked for manual QA until https://github.com/status-im/status-go/pull/3732 passes review. Before requesting manual qa, please make sure that correspondent status-go PR is rebased, reviewed and approved. Thank you!

Please, ping me up when PR will be ready for testing.

**Comment by ibrkhalil** [comment]
> @ibrkhalil hi! PR is blocked for manual QA until [status-im/status-go#3732](https://github.com/status-im/status-go/pull/3732) passes review. Before requesting manual qa, please make sure that correspondent status-go PR is rebased, reviewed and approved. Thank you!
> 
> Please, ping me up when PR will be ready for testing.

Ready for a look @pavloburykh

**Comment by pavloburykh** [comment]
> > @ibrkhalil hi! PR is blocked for manual QA until [status-im/status-go#3732](https://github.com/status-im/status-go/pull/3732) passes review. Before requesting manual qa, please make sure that correspondent status-go PR is rebased, reviewed and approved. Thank you!
> > Please, ping me up when PR will be ready for testing.
> 
> Ready for a look @pavloburykh

@ibrkhalil I see there were new commits after you have pinged up for testing. Please, request manual QA only after all branches (both status go and status mobile) are rebased, up-to date and ready for testing. Otherwise we need to re-run e2e which has been already started and in case of manual QA - we need to start testing from scratch.

**Comment by ibrkhalil** [comment]
> > > @ibrkhalil hi! PR is blocked for manual QA until [status-im/status-go#3732](https://github.com/status-im/status-go/pull/3732) passes review. Before requesting manual qa, please make sure that correspondent status-go PR is rebased, reviewed and approved. Thank you!
> 
> > > Please, ping me up when PR will be ready for testing.
> 
> > 
> 
> > Ready for a look @pavloburykh
> 
> 
> 
> @ibrkhalil I see there were new commits after you have pinged up for testing. Please, request manual QA only after all branches (both status go and status mobile) are rebased, up-to date and ready for testing. Otherwise we need to re-run e2e which has been already started and in case of manual QA - we need to start testing from scratch. 

Got it, Thanks Pavlo
I missed a change and had to do it.
Apologies

**Comment by pavloburykh** [comment]
@ibrkhalil thanx for the PR. Ready for merge.

**Pull request merged**
