### PR TITLE
[#7355]Allow-to-close-wallet.settings-from-an-event

### LINKED ISSUE #7355: Allow to close wallet.settings from an event
### User Story

As a developer, I want to be able to close the wallet.settings extension from this same [extension](https://status.im/extensions/) event.

### Description

*Type*: Feature

### PR DESCRIPTION
**Pull request by tbenr**
fixes #7355

test extensions:

wallet.settings and profile.settings:
https://extensions.status.im/?hash=QmWrVsq4RcuFoWXXnRpDv8SAWzidbgTCfG9ToEUNvbgEps

### CODE REVIEW

**Comment by tbenr** [comment]
@jeluard i see there is a profile.settings hook too... i support it as well... dunno if it makes sense..

**Comment by jeluard** [comment]
Oh right we need this one too now :)

**Comment by tbenr** [comment]
@jeluard done 😃

**Comment by jeluard** [comment]
WDYT about having one event per hook type? e.g. `wallet.settings/close`

**Comment by tbenr** [comment]
@jeluard 👌

**Review by jeluard — APPROVED** [review]

**Review by flexsurfer — APPROVED** [review]
thanks! sorry for the delay!

**Comment by Serhy** [comment]
Looks good to me. iOS and Android 8.1 checked.

**Pull request merged**
