### PR TITLE
[#17534] fix: Add contact scan QR screen back handler issue

### LINKED ISSUE #17534: App freezes after closing Add contact Scan QR screen via system back button (Android)
**Preconditions:** 'Status' app is installed and opened. User is logged in.

**Steps to reproduce:**
1. Tap 'Messages' bottom navigation bar;
2. Tap 'Add' bottom button;
3. Tap 'Add a contact' button;
3. Tap 'Scan QR code' button;
4. Tap 'Back' system button

**Actual **result:**** 'Messages' page is displayed and app is frozen.

https://github.com/status-im/status-mobile/assets/97245802/3d919d7e-2914-4f25-885e-4dad152f8855

**Expected result:** 'Add a contact' bottom sheet is displayed and user can interact with app.

### Additional Information

- Status version: nightly 
- Operating System: Android

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by mohsen-ghafouri**
fixes #17534

### Summary
App freezes after closing Add contact Scan QR screen via system back button

#### Platforms

- Android

### Steps to test

1. Tap 'Messages' bottom navigation bar;
2. Tap 'Add' bottom button;
3. Tap 'Add a contact' button;
4. Tap 'Scan QR code' button;
5. Tap 'Back' system button

### Result 

[Screen_recording_20231020_100157.webm](https://github.com/status-im/status-mobile/assets/71308738/25a9bc82-9def-45c9-99eb-465d7cc1321e)

status: ready

### CODE REVIEW

**Comment by briansztamfater** [comment]
Hey @mohsen-ghafouri, we now have a reusable scan QR screen that can be used to replace this old one that is currently being used (check usage in  `status-im2.contexts.wallet.scan-account.view` namespace), I am not sure we should fix code in legacy namespaces. Maybe we can use the new updated screen instead of just fixing the issue in the old code? What do you think? cc @cammellos @pavloburykh

**Comment by mohsen-ghafouri** [comment]
Hi @briansztamfater, i think there are some people working on migrating status to v2. so in this PR i just focus on the issue. maybe @cammellos @flexsurfer have any advice?

**Comment by mohsen-ghafouri** [comment]
as we have a separate process to work on migration, we can just review and test relevant issue in this PR

**Review by ilmotta — APPROVED** [review]

**Comment by ajayesivan** [comment]
In the QR code scanner screen camera is not working on development, is this expected?


Works fine on the PR build 👍

**Review by ajayesivan — APPROVED** [review]

**Comment by mohsen-ghafouri** [comment]
@ajayesivan i'm not sure about the reason but yes there is a flag to disable camera in dev mode `qr-test-menu-enabled?`

**Comment by VolodLytvynenko** [comment]
hi @mohsen-ghafouri thank you for your work. PR is tested and ready to be merged

**Pull request merged**
