### PR TITLE
Remove old status community from the database

### LINKED ISSUE #19868: Remove old status community from the database
Currently when the database is migrated, we add an old Status community to it. We should remove it. This requires a migration in the database in status-go.

### PR DESCRIPTION
**Pull request by Parveshdhull**
fixes https://github.com/status-im/status-mobile/issues/19868

depends on https://github.com/status-im/status-go/pull/5114

status: ready

### CODE REVIEW

**Review by ibrkhalil — APPROVED** [review]
LGTM as it's a simple version bump

**Comment by J-Son89** [comment]
> LGTM as it's a simple version bump

shouldn't that depend if this version bump is also pulling in other changes within Status-Go? 
@Parveshdhull do you know if this version bump to Status-Go brings in changes beyond what is needed? 
If so we should at least tag QA about this?
cc @cammellos

**Comment by ibrkhalil** [comment]
> > LGTM as it's a simple version bump
> 
> shouldn't that depend if this version bump is also pulling in other changes within Status-Go? @Parveshdhull do you know if this version bump to Status-Go brings in changes beyond what is needed? If so we should at least tag QA about this? cc @cammellos

I think that the impact on status-mobile should be taken care of during review of the status-go PR.
But I totally agree that QA should be notified on any status-go changes.

**Comment by pavloburykh** [comment]
Hey @Parveshdhull! Thank you for the PR! Could you please rebase go and mobile branches? Thank you!

**Comment by Parveshdhull** [comment]
closing the PR as removal of status old community is breaking the status go tests and needs some workaround

**Comment by qfrank** [comment]
reopen as removal of status old community is not breaking the status go tests anymore cc @Parveshdhull @pavloburykh

**Comment by pavloburykh** [comment]
> reopen as removal of status old community is not breaking the status go tests anymore cc @Parveshdhull @pavloburykh

thank you! Will take a look at it on Monday

**Comment by pavloburykh** [comment]
Hey @Parveshdhull! Thanx for the PR! Please, take a look at the issue. 

### ISSUE 1 Old Status community is still shown within Opened tab for recovered user

**NOTE:** ask me for the seed phrase of the user.

**Steps:** 

1. Recover given user
2. Go to Communities screen - Opened tab
3. See if old Status community is displayed

**Actual result:** Old Status community is displayed within Opened tab

photo_2024-05-13 15 03 19
[Status-debug-logs - 2024-05-13T150929.932.zip](https://github.com/status-im/status-mobile/files/15294205/Status-debug-logs.-.2024-05-13T150929.932.zip)

**Comment by pavloburykh** [comment]
@Parveshdhull maybe I am missing something: where have we used to show this old community in mobile app? Is it only Opened tab or any other places? I want to make sure what exact places should I check. 

Also, maybe you have some other suggestions on what should be tested in this PR based on related go changes?

**Comment by pavloburykh** [comment]
Talked to @qfrank, we agreed that [ISSUE 1](https://github.com/status-im/status-mobile/pull/19905#issuecomment-2107408002) is not a blocker. So we are ready for merging. 

Tested migration from older app version to PR version - old Status community disappears after upgrade.
For new users who initially installed PR version -  old Status community is not shown.

**Comment by Parveshdhull** [comment]
> So we are ready for merging.

Thank you very much @qfrank for working on the PR and @pavloburykh for testing it.

**Pull request merged**
