### PR TITLE
[fix 7380] bubble width on small devices

### LINKED ISSUE #7380: Message bubble is too wide on iPhone 5s (can't read part of text) and on Galaxy S6 (very close to screen edge)
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: there are 2 issues with bubble width:
1. end of the string is not visible in the bubble on iPhone 5s 
img_4257

2. right side of the bubble is too close to the edge of the screen on Samsung Galaxy S6 that contradicts with design from https://github.com/status-im/status-react/issues/6440 (assuming similar expectations on Android)
screenshot_20190130-134736

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Join #status channel or receive some 3-4 line messages in any other test channel

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: nightly January 30
* Operating System: Android 6.0.1 real Galaxy S6 and iOS 12.1.2 iPhone 5s

### PR DESCRIPTION
**Pull request by yenda**
fixes #7380

### Summary:

Small screen

screenshot_1548982445

Large screen

screenshot_1548982701

status: ready

### CODE REVIEW

**Review by errorists — APPROVED** [review]
Looks great on my dumb iPhone, thanks! @yenda one thing which caught my attention we discussed briefly before in the Chat build, was for the fetching progress bar to not nudge the content downward, just be rendered on top, did you merge that fix somewhere else or it's not done yet?

**Review by mandrigin — APPROVED** [review]

**Comment by yenda** [comment]
@errorists strange it might have been reversed by the more obvious fixes that the changes to prevent the nudging provoked. I found a solution to have the behavior you want (loading indicator over top bar), seems fine on android, waiting for the build to see how it does with iOS.

**Comment by churik** [comment]
LGTM on IPhone 7 (IOS 11.4) and LG V20 (Android 7.0)
@annadanchenko please, verify on your side when you have time

**Comment by annadanchenko** [comment]
@churik I checked only bubble width on iphone 5s and galaxy s6, they look ok now (see images below). I haven't checked https://github.com/status-im/status-react/pull/7393#issuecomment-459689685



screenshot_20190204-124921

**Comment by churik** [comment]
@errorists I didn't check https://github.com/status-im/status-react/pull/7393#issuecomment-459689685 (basically it looks ok for me on nightly as well)
Can you please clarify or verify on your side?

**Comment by churik** [comment]
In any case consider as "Done", issues is fixed

**Pull request merged**
