### PR TITLE
[#19247] feat: migrate to new contact profile

### LINKED ISSUE #19247: Feature: Replace legacy contact profile
### Summary

Replace legacy contact profile with new screen

### PR DESCRIPTION
**Pull request by mohsen-ghafouri**
fixes #19247
### Summary

Migrate to new contact profile

#### Implemented Features

- #19030 
- #19119
- #19028
- #19039
- #19119
- #19075
- #19166
- #19139 
- #19085 
- #19154
- #19144
- #19213
- #19168 
- Issue in review
    - #19087
    - #19237

#### Platforms

- Android
- iOS

#### Areas that maybe impacted

- Contact information
   - Avatar
   - Visibility Status
   - Display name and Nickname
   - Bio
   - Emoji Hash
   - Contact Request Status
- Send Contact Request
- Review Contact Request
- Add Nickname
- Show QR code
- Share profile
- Block user
  - Block user + Remove contact
- Remove Contact (if it's mutual contact)

## After 

<div>

</div>

### Video

https://github.com/status-im/status-mobile/assets/71308738/82b88a59-2b1b-4171-ba32-cd1f821b2c06

status: ready

### CODE REVIEW

**Review by cammellos — APPROVED** [review]

**Comment by pavloburykh** [comment]
@yevh-berdnyk could you please adjust e2e according to the new UI in this PR?

**Comment by yevh-berdnyk** [comment]
hi @mohsen-ghafouri, I've just pushed updates for e2e test, please don't remove  them when adding new commits.
Also could you please add meaningful accessibility ids for the next elements:
Screenshot 2024-03-14 at 19 00 48
Screenshot 2024-03-14 at 19 13 54
Screenshot 2024-03-14 at 19 19 40
Screenshot 2024-03-14 at 19 30 55

Thanks in advance!

**Comment by mohsen-ghafouri** [comment]
Hi @yevh-berdnyk, Added.

**Comment by VolodLytvynenko** [comment]
Hi @mohsen-ghafouri, thank you for the PR. Here is a list of issues. Some of them might not be PR-related. I'm reporting them to ensure we don't overlook any. Please let me know which ones were fixed and which ones are better to create as within separate follow ups
 
## ISSUE 1: Buttons in 'New Contact' profile pages do not inherit selected color

### Steps:
1. Go to the profile -> edit profile -> select any color within accent color
2. Go to the new contact profile flow
3. Check button

### Actual result:
The following buttons do not inherit the selected color.
Add nickname
image
Send contact request
image

Review contact request
image

### Expected result:
The buttons inherit the color that is selected for certain account

**Comment by VolodLytvynenko** [comment]
## ISSUE 2: 'Send contact request' button is enabled when more than 280 chars are in the message input field
### Steps:
1. Go to send Contact request flow
2. Open 'Send contact request' drawer
3. Enter more than 280 chars into message field

### Actual result:
The 'Send contact request' button is enabled when more than 280 characters are entered into the message field.
image

### Expected result:
Potential solution:
- When more than 280 characters are entered, the 'Send contact request' button should be disabled.
- There should be no ability to enter more than 280 characters, and the field should ignore any additional input.

**Comment by VolodLytvynenko** [comment]
## ISSUE 3: No placeholder in the contact request drawer
### Steps:
1. Go to send Contact request flow
2. Open 'Send contact request' drawer

### Actual result:
The placeholder is not shown
image

### Expected result:
'Type something' placeholder is shown
https://www.figma.com/file/jGs1P4RU4R1NRrY0xXmHC1/Profile-interactions?type=design&node-id=50-155803&mode=design&t=HofXmJENRjl7zjhJ-0

**Comment by VolodLytvynenko** [comment]
## ISSUE 4: [iOS] Message input field not focused after opening Contact Request drawer

### Steps:
1. Go to send Contact request flow.
2. Open 'Send contact request' drawer.

### Actual Result:
The message input field is not focused.

https://github.com/status-im/status-mobile/assets/52490791/6808b4b2-fd5b-410c-9104-c0ecb9f7d6db

### Expected Result:
The message input field should be focused after the contact request drawer is opened.

**Comment by VolodLytvynenko** [comment]
## ISSUE 5: Display name not shown, only nickname is displayed
### Steps:
1. Go to the send Contact request flow.
2. Open the profile of any user.
3. Set the display name for the user.

### Actual Result:
The display name disappears after the nickname is set.
image

### Expected result:
The display name is shown near the nickname
image
https://www.figma.com/file/jGs1P4RU4R1NRrY0xXmHC1/Profile-interactions?type=design&node-id=85-233899&mode=design&t=QXNMUsa3bErFxGNZ-0

**Comment by mohsen-ghafouri** [comment]
Hi @VolodLytvynenko, thank you for reviewing this PR, for issue 1 we have this open PR #19087, the rest i will resolve and let you know

**Comment by mohsen-ghafouri** [comment]
@VolodLytvynenko could you please check again, 2,3,4,5 should be resolved.

**Comment by VolodLytvynenko** [comment]
Hi @mohsen-ghafouri the issues 2-5 are fixed. Apologies for the delay in testing. The contact request feature is quite big, and I needed additional time to test everything. Take a look please a few additional issues:

## ISSUE 6:  Navigation to chat review page after tapping 'Block' button

### Steps:
1. `UserA` open profile page of `UserB`
2. `UserA` blocks `UserB`

### Actual result:
The user is navigated to the chat preview page.

https://github.com/status-im/status-mobile/assets/52490791/1ae7f3ec-a1d0-46d3-956c-7ddef278da75


### Expected result:
The user should remain on the same page after blocking a user, rather than being navigated to the chat preview page.

https://www.figma.com/file/jGs1P4RU4R1NRrY0xXmHC1/Profile-interactions?type=design&node-id=19-59400&mode=design&t=jbYw9bXQT1PKajnP-0

**Comment by VolodLytvynenko** [comment]
## ISSUE 7: The 'Remove Contact' checkbox can be enabled/disabled when the drawer is opened for mutual contacts

### Steps:
1. `UserA` and `UserB` are mutual contacts.
2. Tap on the 'Block' option.
3. Check the block drawer.

### Actual result:
The 'Remove Contact' checkbox can be enabled/disabled.

https://github.com/status-im/status-mobile/assets/52490791/255e97ac-097b-4fd6-a837-2bc3b42525d9


### Expected result:
The 'Remove Contact' checkbox is always enabled and cannot be disabled.
https://www.figma.com/file/jGs1P4RU4R1NRrY0xXmHC1/Profile-interactions?type=design&node-id=29-72224&mode=design&t=A9Iw48auRsqsNbhk-0

**Comment by VolodLytvynenko** [comment]
Unfortunately, I didn't find the exact steps to reproduce this issue. The error seems to occur randomly. I hope the logs might help.

## ISSUE 8: 're-find match against the string' error is shown after Show QR code option is selected when user is blocked

### Steps:
1. `UserA` blocks `UserB` 
2. Open right up three dots to open the drawer
3. Select 'Show QR code' option

### Actual result:
're-find match against the string' error is shown after Show QR code option is selected
image

### Expected result:
no error when 'Show QR code' option is selected

### Logs:
[logs (4).zip](https://github.com/status-im/status-mobile/files/14625213/logs.4.zip)

**Comment by VolodLytvynenko** [comment]
## ISSUE 9: 'Jump To' Button not shown when profile of user is opened

### Steps:
1. Open profile page
2. Check for the 'Jump To' button.

### Actual Result:
The 'Jump To' button is not shown.
image

### Expected Result:
The 'Jump To' button should be shown when the profile of a user is opened.
image
https://www.figma.com/file/jGs1P4RU4R1NRrY0xXmHC1/Profile-interactions?type=design&node-id=19-59478&mode=design&t=Y8fg1OIWgtyDIeOS-0

**Comment by VolodLytvynenko** [comment]
## ISSUE 10:  Bio description shown when user is blocked


### Steps:
1. `UserB` set up some bio description for his account
2. `UserA` blocks `UserB`
3. Check bio description

### Actual result:
Bio description is shown of blocked user
image

### Expected result:
When a user is blocked, their bio description should not be shown.
https://www.figma.com/file/jGs1P4RU4R1NRrY0xXmHC1/Profile-interactions?type=design&node-id=43-219041&mode=design&t=uzxQrvI4CCp3J83p-0

**Comment by VolodLytvynenko** [comment]
## ISSUE 11: Opening old profile page UI when navigating to own profile link

### Steps:
1. Share link of your user
2. Navigate to current link

### Actual result:
The old UI profile is opened

https://github.com/status-im/status-mobile/assets/52490791/d1e86c3c-20ab-45d5-9b68-817999bc8a35


### Expected result:
The new UI profile page should be opened.

**Comment by VolodLytvynenko** [comment]
## ISSUE 12: 'add nickname' button is shown instead of 'update nickname'

### Steps:
1. Add a nickname to any user
2. Open again the nickname drawer to update nickname

### Actual result:
The 'Add nickname' button is shown
image

### Expected result:
The 'Update nickname' button is shown
image

https://www.figma.com/file/jGs1P4RU4R1NRrY0xXmHC1/Profile-interactions?type=design&node-id=863-143296&mode=design&t=kCgFyBEmWSObM1sa-0

**Comment by VolodLytvynenko** [comment]
## ISSUE 13: Nickname chars limits are 20 Instead of 24

### Actual result:
Nicknames are limited to 20 characters.
image

### Expected result: 
Nicknames should be limited to 24 characters.
https://www.figma.com/file/jGs1P4RU4R1NRrY0xXmHC1/Profile-interactions?type=design&node-id=863-142710&mode=design&t=YZnzoKcDcej39BHd-0

**Comment by VolodLytvynenko** [comment]
## ISSUE 14: [IOS] Wrong UI for text on 'contact request' drawer when dark mode enabled

### Steps:
1. Enable dark mode
2. Open 'contact request' drawer

### Actual result:
Text is not visible on IOS when dark mode is enabled
image

### Expected result:
Text should be visible in dark mode.
image

**Comment by mohsen-ghafouri** [comment]
Hey @VolodLytvynenko I appreciate your time and consideration for this PR. 

Issues are resolved, could you please check again?

- ISSUE 6 ✅
- ISSUE 7 ✅
- ISSUE 8 -> we have some technical limitation to display profile info for a blocked(removed) contact. so for now i just hide share and show QR options. 
- ISSUE 9 ✅
- ISSUE 10 ✅
- ISSUE 11 ✅
- ISSUE 12 ✅
- ISSUE 13 -> we discussed this with design team, they agreed to use one limitation for profile name and here also for contact nick name. so it should be 20
- ISSUE 14 ✅

Thank you @seanstrom for helping to resolve the issues.

**Comment by VolodLytvynenko** [comment]
Hi @mohsen-ghafouri @seanstrom, thanks for your work! All issues are fixed, and the remaining ones are created as follow-ups. I can't send to merge the PR until the e2e tests are fully fixed due to a recent commit issue. @yevh-berdnyk and I will update you once it's resolved.

**Comment by VolodLytvynenko** [comment]
Hi @Francesca-G could you take a look at this PR, please?

**Comment by cammellos** [comment]
@VolodLytvynenko if the UI is functional, we can merge this before design review and review once it's in, as it'd be good to have it in 2.28, thank you

**Review by Francesca-G — COMMENTED** [review]
here's the [design review](https://www.figma.com/file/1IB0ZZ08ODzuoWmixDSzm7/Review-Messages-%2F-Mobile?type=design&node-id=131%3A17884&mode=design&t=L4g8MICZKq4D7l30-1) :)

**Comment by pavloburykh** [comment]
@mohsen-ghafouri thank you for your work. PR is ready to be merged. Please, include commits by @yevh-berdnyk during merge.

**Comment by VolodLytvynenko** [comment]
Hey @Francesca-G, thank you for your feedback. In your [review](https://www.figma.com/file/1IB0ZZ08ODzuoWmixDSzm7?node-id=131:17884&mode=design#740308025), you specified that the 'Jump to' button should not be visible. However, on the original [design](https://www.figma.com/file/jGs1P4RU4R1NRrY0xXmHC1/Profile-interactions?type=design&node-id=0-38965&mode=design&t=P1JW1rhFJojSbJZe-0), it is visible. Which is the correct approach?

**Comment by Francesca-G** [comment]
> Hey @Francesca-G, thank you for your feedback. In your [review](https://www.figma.com/file/1IB0ZZ08ODzuoWmixDSzm7?node-id=131:17884&mode=design#740308025), you specified that the 'Jump to' button should not be visible. However, on the original [design](https://www.figma.com/file/jGs1P4RU4R1NRrY0xXmHC1/Profile-interactions?type=design&node-id=0-38965&mode=design&t=P1JW1rhFJojSbJZe-0), it is visible. Which is the correct approach?

Apologies for this, there was an inconsistency among different files. I confirmed it with Pedro and the Jump to should be visible in this case 👍

**Pull request merged**
