### PR TITLE
Edit basic community info

### LINKED ISSUE #12018: Allow editing community basic information
As a community admin
I want to be able to edit my community
So that I can correct any mistake or update community info to reflect some changes

### Description

Some fields in the community should be editable (name, color,image and description).
This will probably involve some status-go changes (albeit they should be simple).

#### Designs

https://www.figma.com/file/aS1ct66VQ6V0cio7vSqS8UoG/Chat?node-id=17994%3A167

### PR DESCRIPTION
**Pull request by vkjr**
fixes #12018

### Summary

Editing community: name, description, permissions, thumbnail image

Screenshot 2021-05-17 at 14 29 01

### Review notes
corresponding [status-go pr](https://github.com/status-im/status-go/pull/2229)

#### Platforms
- Android
- iOS

### Steps to test
- Open Status
- Open community profile
- Make sure that `Edit Community` option is available if you are an admin
- change something
- make sure community changes are in place

status: ready

### CODE REVIEW

**Review by flexsurfer — APPROVED** [review]

**Comment by churik** [comment]
@vkjr thank you for PR!
### ISSUE 1: can't see thumbnail image when editing community

**Steps:**
1) create a community with image
2) go to community info > edit

**Expected result:**
can see that image is set
**Actual result:**
IMAGE 2021-05-18 10:52:57

**OS:** IOS, Android

### ISSUE 2: (more question) Not sure that it is right to change the type of community
As on community sync, it was decided to focus on the "Require approval" type of community, not sure that we need to edit the type of community itself.
Moreover, in https://github.com/status-im/status-react/issues/12018 only basic info was mentioned (name, color, image, and description).

Currently, if the admin changes community type (i.e. from open membership to "Require approval") for existing members, the old type is still shown, so this feature contains issues anyway.
I suggest to lock type of community and don't allow to change it.

**Comment by vkjr** [comment]
@churik, thanks!
@cammellos, should we allow editing membership requirements for communities, wdyt?

**Comment by cammellos** [comment]
@vkjr I don't think at this stage it matters much, so given that some extra work would be required to make it working, I would just not allow it, as it's a bit unpredictable how it will behave.

**Comment by vkjr** [comment]
@churik 
- fixed thumbnail image preview - it shows current image
- don't suggest changing membership requirements

**Comment by churik** [comment]
### ISSUE 3: can't edit name or description only (without changing picture)
**Steps:**
1) create a community with image
2) try to change name or description
**Expected result:**
can save community
**Actual result:**
when tapping on Save nothing happened
**OS:** IOS, Android

### ISSUE 4: community info is not updated for existing users
**Steps:**
1) user A: create a community with image,  add user B
2) user A: try to change name or description
3) user B: pay attention to community info

**Expected result:**
info is changed to updated
**Actual result:**
community is not updated
**OS:** IOS, Android

**Comment by vkjr** [comment]
@churik, issue 3 name mentions "without picture" while step 1 says "with image". Which one is correct?

**Comment by churik** [comment]
updated issue, sorry for confusion

**Comment by vkjr** [comment]
@churik, both issues are fixed

**Comment by churik** [comment]
e2e failures are not related to PR.
Tested basic flows - editing fields one-by-one, setting image, editing community while members are offline.

**Devices:**
- IPhone 12 Mini (IOS 14)
- IPhone 7 (IOS 13)
- Xiaomi Mi Note 9 Pro (Android 10)

**Comment by vkjr** [comment]
@churik, thanks!

**Pull request merged**
