### PR TITLE
fix_:still return the image when handleAccountInitialsImpl is unable to get public key

### LINKED ISSUE #20512: Profile picture missing after migration from v1 to v2
# Bug Report

## Problem 

Users can't see their old profile pictures after installing Status v2 on top of Status v1 (migrating to v2).

Reported by @flexsurfer 

#### Expected behavior

After installing Status v2, the user should see the same old profile picture.

#### Actual behavior

After installing Status v2, the old profile picture is missing and not displayed to the user.

### Reproduction

1. Create user in v1.
2. Log in and add a profile picture.
3. Log out, check the avatar is shown.
4. Install Status v2 (any recent build will do).

### Additional Information

- Status version: from release branch `1.20.x`
- Operating System: Android, iOS

cc @qfrank

### PR DESCRIPTION
**Pull request by qfrank**
fixes #20512

before the fix:
image

after the fix:
image

### Testing notes
- install 1.20.x PR build and generate an account use keycard
- install this PR(2.x) build and see if the avatar is blank, it should not be blank. NOTE: we can't generate the ring because we don't have the public key before login. pls see the detail [description](https://github.com/status-im/status-go/pull/5409#issue-2369438648) 

#### Platforms

- Android
- iOS

status: ready

### CODE REVIEW

**Review by flexsurfer — APPROVED** [review]

**Review by ilmotta — APPROVED** [review]

**Comment by pavloburykh** [comment]
Hey @qfrank! Thanks you for the PR. Sorry for delay with testing. Currently our e2e tests are blocked because of issues on Waku side. Once issues are resolved - we will proceed with testing.

**Comment by VolodLytvynenko** [comment]
hi @qfrank could you please rebase current and Status go https://github.com/status-im/status-go/tree/fix/avatar-no-pk PR? Thanx!

**Comment by mariia-skrypnyk** [comment]
Hey @qfrank !

Thanks for your fix!

I've checked two scenarios:

- with photo
- with NO photo

As we have v1 issue on Android that user can not add photo to set his avatar I was able to check it only on iOS.

Result: 
 
- with photo ❌ (iOS)
Screenshot 2024-07-16 at 15 29 00

- with NO photo ✅ (iOS/Android)
Screenshot 2024-07-16 at 15 28 53

**Comment by mariia-skrypnyk** [comment]
Hi @qfrank.

here are logs.

[logs.zip](https://github.com/user-attachments/files/16263396/logs.zip)

And UPD: Profile photo appears after user enters keycard password.

**Comment by mariia-skrypnyk** [comment]
Great job @qfrank !

Finally the avatar photo is on it's place!

I need to check regression and e2e.
Let you know when you can merge.

**Comment by mariia-skrypnyk** [comment]
I am still on my regression testing but here what I've found:

**ISSUE 1: [Android] no fingerprint authorization on android when biometry is turned on**

*this issue happens when it is newly created user, I've tried user restored from seep phrase and it worked

**Steps:**

1. Install app
2. Turn on Biometry on Onboarding
3. Make sure biometrics is turn on in Profile-> Password
4. Kill the app from the background
5. Reopen app

**Expected behaviour:**

User should see fingerprint login on the login screen


https://github.com/user-attachments/assets/2d9f931b-3cc4-4739-a4ac-4aee73fd7439


**Actual behaviour:**

User is inside the app


https://github.com/user-attachments/assets/133dd98f-438e-43ec-8d14-9996a3d69fed


Logcat logs: 
[android_bio.log](https://github.com/user-attachments/files/16282123/android_bio.log)

**Comment by mariia-skrypnyk** [comment]
@qfrank e2e found isssue this issue:

**ISSUE 2: Discover Communities has no cards, endless loading state**

**Steps:**

Install app
Create a user
Tap on discover at Community screen

**Actual behaviour:**

photo_2024-07-18_15-06-31

**Expected behaviour:**

At least default card of Status Inu community should be visible
Nightly 👇


Platforms: iOS and Android

**Comment by mariia-skrypnyk** [comment]
Failed e2e are not related and PR can be merged.
Thanks @qfrank for you patience.

**Pull request merged**
