### PR TITLE
react switch warnings fix

### PR DESCRIPTION
**Pull request by flexsurfer**

### CODE REVIEW

**Review by mandrigin — APPROVED** [review]

**Review by jeluard — APPROVED** [review]

**Review by yenda — APPROVED** [review]

**Comment by churik** [comment]
@flexsurfer can you please elaborate what should be tested here?

**Comment by flexsurfer** [comment]
@churik that switch component (you can find it on login screen for example) works and looks good on both ios and android, thanks

**Comment by churik** [comment]
Tested switches on IOS 11.4.1 (IPhone 7) and Android (LG V20):
1) login screen
2) bootnodes
3) development mode
4) browser privacy mode
5) PFS enabled
6) chaos mode 
7) boot nodes

**Comment by churik** [comment]
e2e test is failed due to `faucet`  error, so not introduced by PR

**Pull request merged**
