### PR TITLE
Bump go version to work with latest status-go changes

### PR DESCRIPTION
**Pull request by ibrkhalil**
Recently status-go version was updated on status-go, So we need to update it here too.

fixes: status-go build

Tested it locally and works.
QA notes: This should be classified as working if the builds were successful.
status: ready

### CODE REVIEW

**Review by cammellos — APPROVED** [review]

**Comment by pavloburykh** [comment]
Hey @ibrkhalil! I was just in the middle of testing this PR but I see it has been already merged. There are some e2e failures which I wanted to investigate. But that's ok, I will open followup issues if I find any issues related to current PR. Thanx.

**Comment by churik** [comment]
@ibrkhalil 
please wait for `Tested-OK` label next time before merge, thank you

**Comment by ibrkhalil** [comment]
@churik @pavloburykh I thought it won't be tested since it's only a version upgrade, I am already waiting for a `tested-ok` label for other PRs.
But will do it from now on for version bumps too.
Thanks :)

**Review by jakubgs — COMMENTED** [review]
Nice. thanks.

**Pull request merged**
