### PR TITLE
Disable group chats in dev mode. Closes #4396

### LINKED ISSUE #4396: Hide group chats outside of dev mode
### User Story

As a user, I want unusable features to be hidden.

As a developer, I want the option to code against the group chat feature.

### Description

*Type*: Bug

*Summary*: 

Hide "Start group chat" feature unless user is in developer mode, for all builds.

#### Expected behavior
"Start group chat" does not appear in this list unless I am in developer mode:

#### Actual behavior
"Start group chat" is available by default.

### Reproduction

- Open Status nightly
- Go to "+" New screen

### Additional Information
* Status version: Nightly 2018-05-23
* Operating System: iOS

### PR DESCRIPTION
**Pull request by pedropombeiro**
[comment]: # (Please replace ... with your information. Remove < and >)
[comment]: # (To auto-close issue on merge, please insert the related issue number after # i.e fixes #566)

fixes #4396 

### Summary:

[comment]: # (Summarise the problem and how the pull request solves it)
This PR changes the options list method so that it only adds the group chat button if dev mode is enabled or the `GROUP_CHATS_ENABLED` flag is enabled. It also sets `GROUP_CHATS_ENABLED` to 0 for all configs except for e2e.

### Steps to test:
- Open Status with dev mode disabled
- Click + button
- Verify that group chat option is not available
- Enable development mode
- Click + button
- Verify that group chat option is now available

status: ready

### CODE REVIEW

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/VmKdea for branch PR-4406

<blockquote><div><strong><a href="https://i.diawi.com/VmKdea">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/SuKeof for branch PR-4406

<blockquote><div><strong><a href="https://i.diawi.com/SuKeof">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/sY4zzZ for branch PR-4406

<blockquote><div><strong><a href="https://i.diawi.com/sY4zzZ">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/aUt4UP for branch PR-4406

<blockquote><div><strong><a href="https://i.diawi.com/aUt4UP">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Review by jeluard — APPROVED** [review]

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/6G7mcP for branch PR-4406

<blockquote><div><strong><a href="https://i.diawi.com/6G7mcP">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/YAjSQX for branch PR-4406

<blockquote><div><strong><a href="https://i.diawi.com/YAjSQX">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/T289i9 for branch PR-4406

<blockquote><div><strong><a href="https://i.diawi.com/T289i9">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/MvMJzt for branch PR-4406

<blockquote><div><strong><a href="https://i.diawi.com/MvMJzt">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by pedropombeiro** [comment]
Ping to reviewers, this is a tiny review :-)

**Review by goranjovic — APPROVED** [review]

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/aL9v79 for branch PR-4406

<blockquote><div><strong><a href="https://i.diawi.com/aL9v79">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/A2pVrd for branch PR-4406

<blockquote><div><strong><a href="https://i.diawi.com/A2pVrd">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/hbEgdJ for branch PR-4406

<blockquote><div><strong><a href="https://i.diawi.com/hbEgdJ">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/fuLDG1 for branch PR-4406

<blockquote><div><strong><a href="https://i.diawi.com/fuLDG1">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Pull request merged**
