### PR TITLE
[Fix #1048] Timestamp format in chat

### LINKED ISSUE #1048: Timestamp format in chat
### Description
image

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
Timestamp should be understandable to the user

#### Actual behavior
[comment]: # (Describe what actually happened.)
Timestamp is shown in period time format, but without AM/PM

### PR DESCRIPTION
**Pull request by foopang**
Another attempt for #1048

I think `moment.js` could be a better alternative, so I'd give it a try :)

status: ready

### CODE REVIEW

**Comment by oskarth** [comment]
Requesting reviews based on Github suggestions

**Comment by jeluard** [comment]
@foopang Can you detail why this is a better alternative?

**Comment by foopang** [comment]
@jeluard Yes, because `moment.js` is a very widely used date time library, it's very well being maintained and well documented. It provides more features out of the box and more flexibility. We are not limited to use merely just those i18n preset formats in `moment.js`, we can also mix and match with many more date time formats available https://momentjs.com/docs/#/displaying/format/
Although it could be overkill to adopt a new library for this particular use case, `cljs-time` + `goog.i18n.DateTimeFormat` can achieve what we want already. I think `moment.js` can be useful for us in some other cases, such as replacing our custom implementation of `time-ago` with `moment.js` [Time from now](https://momentjs.com/docs/#/displaying/fromnow/)

**Comment by jeluard** [comment]
@foopang Does it bring something more than #2897 ? I'd rather introduce new deps only if it bring something.

**Comment by foopang** [comment]
@jeluard Not really bringing something more than #2897. Just a different approach using a lib to solve one issue. So you can decide which one works better can get your approval.

**Comment by oskarth** [comment]
^ @yenda @flexsurfer @janherich review please

**Comment by yenda** [comment]
@foopang thank you very much for your contribution. It was a good solution however I will close this issue as https://github.com/status-im/status-react/pull/2897 was submitted earlier and doesn't introduce new dependencies which we try to avoid as much as possible.

**Pull request closed without merging**
