### PR TITLE
[#7158] EIP1193 (new ethereum provider)

### LINKED ISSUE #7158: EIP1193 (new ethereum provider)
https://eips.ethereum.org/EIPS/eip-1193

<blockquote><div>Ethereum Improvement Proposals</div><div><strong><a href="http://eips.ethereum.org/EIPS/eip-1193">Ethereum Provider JavaScript API</a></strong></div><div>Ethereum Improvement Proposals (EIPs) describe standards for the Ethereum platform, including core protocol specifications, client APIs, and contract standards.</div></blockquote>

### PR DESCRIPTION
**Pull request by flexsurfer**
fixes #7158

status: ready

FOR QA: if you can see "beta" button, that means simple dapp uses beta provider
image

### CODE REVIEW

**Review by jeluard — APPROVED** [review]

**Review by dmitryn — APPROVED** [review]

**Review by goranjovic — APPROVED** [review]

**Comment by asemiankevich** [comment]
@flexsurfer seems app thinks it is on mainnet while it was switched to Ropsten. Nightly looks fine.
image

**Comment by flexsurfer** [comment]
@asemiankevich , unfortunately, simple dapp is not adapted for beta provider yet i'll do it later, so we can ignore this issue for now, thanks

**Comment by asemiankevich** [comment]
> @asemiankevich , unfortunately, simple dapp is not adapted for beta provider yet i'll do it later, so we can ignore this issue for now, thanks

but how autotests and others will receive test funds if this is merged? :)

**Comment by flexsurfer** [comment]
ok let's revert dapp for now then

**Comment by flexsurfer** [comment]
@asemiankevich reverted beta provider usage, now you can see beta provider button, but release provider will be used

**Pull request merged**
