### PR TITLE
Check public key when sending a message

### PR DESCRIPTION
**Pull request by cammellos**
status: ready

### CODE REVIEW

**Comment by pavloburykh** [comment]
This PR fixes https://github.com/status-im/status-react/issues/13479

**Comment by cammellos** [comment]
@pavloburykh oh sorry, I thought I merged it already, that's why I closed the task :facepalm:

**Comment by pavloburykh** [comment]
> @pavloburykh oh sorry, I thought I merged it already, that's why I closed the task 🤦

no worries @cammellos Let's rebase it and move to E2E column. I will perform some more regression tests and then we will be ready to merge the PR.

**Review by audriu — APPROVED** [review]
Looks good to me

**Review by Parveshdhull — APPROVED** [review]

**Comment by pavloburykh** [comment]
Thank you @cammellos Failed e2e are not related to the PR. Ready for merge.

**Pull request merged**
