### PR TITLE
fix ens resolve issue while following deep link

### LINKED ISSUE #11248: 3-random name is resolved instead of ENS when following deeplink
# Bug Report

## Problem

If follow deeplink as 'https://join.status.im/u/%s.stateofus.eth' or scan it on "New contact" screen, the user profile with 3-random name will be opened instead of ENS name in the header.

**The reason why this is nice to fix:** in `test_add_remove_contact_via_contacts_view` when scanning deep link as 'https://join.status.im/u/%s.stateofus.eth'
`expected result` is 3-random username, which presumably is wrong and it should be consistent with the case when you pasting ENS name - so ENS name should be expected result. It is temporary workaround for current behavior.

#### Expected behavior

When scanning or following deeplinks containing ENS name a user profile with a resolved ENS name is opened.

#### Actual behavior

ezgif com-gif-maker (2)

### Reproduction

- Generate QR code from deeplink, e.g. https://join.status.im/u/dikhasi.stateofus.eth
Screenshot 2020-09-30 at 17 20 04

- Create new user
- Open Add new contact screen
- Open QR scanner
- Scan QR code
- Check the name in opened User Profile

### Additional Information

- Status version: Nightly 30/09
- Operating System: Android, iOS

### PR DESCRIPTION
**Pull request by Parveshdhull**
fixes https://github.com/status-im/status-react/issues/11248

status: ready

### CODE REVIEW

**Review by bitgamma — APPROVED** [review]

**Comment by Parveshdhull** [comment]
Hi @pavloburykh, Thanks for testing the PR,
Please can you add details about issues? Thanks

**Comment by pavloburykh** [comment]
@Parveshdhull oh sorry, my comment with issues description was not saved for some reason. 
Thanx for PR. Please take a look at following issues.

## ISSUE 1 (Reproducible on Mainnet)

ENS username is not shown on Profile page after scanning QR code containing ENS with internal domain stateofus.eth. For reproduction use Mainnet.

STR: 
1. Download and install manual build https://ci.status.im/job/status-react/job/manual/203/ for testing this PR on Mainnet. Do not use PR build for testing ENS on Mainnet, as PR builds have ENS_VERIFY_NETWORK parameter set to Ropsten. 
2. Open Chat tab
3. Tap +Add new button => bottom sheet opens
4. Open QR scanner by tapping QR icon in right upper corner of bottom sheet
5. Scan this deeplink QR code https://join.status.im/u/dikhasi.stateofus.eth => Profile screen opens 
6. Pay attention at name on Profile screen

Actual result: after Profile page is opened ENS name is displayed for a second, but after that it is changed for 3 random name. 
On given video you can see that in case of following the deeplink, ENS name is shown on opened Profile screen. But in case of opening deeplink by scanning QR code all subsequent following the deeplink will result in showing 3 random name instead of ENS.  

https://user-images.githubusercontent.com/97245802/153054035-55b923f2-490c-42aa-9cc5-a964e369e482.mp4

[geth.log](https://github.com/status-im/status-react/files/8026679/geth.log)


OS: Android / IOS

## ISSUE 2 (reproducible both on ropsten and mainnet) 

ENS name is not resolved in chats until user is added to contacts through Profile => Contacts => Add new contact => Scan deeplink QR code

STR: 

1. Follow deeplink containing ENS or open it by scanning it's QR code. You can use this deeplink https://join.status.im/u/dikhasi.stateofus.eth for mainnet and this one https://join.status.im/u/sergey.stateofus.eth for ropsten network. 
2. On Profile screen proceed to Chat
3. Pay attention at username on 1-1 chat screen

Actual result: 3 random name is displayed in chats. ENS username starts displaying only after adding user to contacts by opening Profile => Contacts => Add new contact => Scan deeplink QR code

Expected result: ENS user name should be displayed. 


https://user-images.githubusercontent.com/97245802/153055886-2614ee36-9ba0-4e04-aefc-103ebae5c4c3.mp4

**Comment by Parveshdhull** [comment]
Hi @pavloburykh,
Thanks for finding these great issues.
Issue 2 is fixed. 
I am not sure about the cause of Issue 1, but it seems related to issue 2. So hopefully new changes will fix that too.
Please let me know if this is not the case. Thanks

**Comment by pavloburykh** [comment]
@Parveshdhull Thank you for fixes, great job! 
ISSUE 1 - fixed
ISSUE 2 - is partially fixed. There is still one flow which results in unresolved ENS usernames in chats. 
STR: 
1. Open Chats tab
2. Tap + Add button
3. Tap Start new chat - New chat screen opens
4. Open QR scanner by tapping QR icon in right upper corner. - 1-1 chat page opens
5. Scan deeplink's QR code. You can use this on https://join.status.im/u/sergey.stateofus.eth both for ropsten and mainnet. 
6. Pay attention at username on opened 1-1 chat page

Actual result: 3 random name is displayed
Expected result: ENS username is displayed. 

OS: IOS/Android

[geth.log](https://github.com/status-im/status-react/files/8031665/geth.log)


https://user-images.githubusercontent.com/97245802/153178772-2a401049-74e1-4618-bdc8-c09677de41a3.mp4

**Comment by Parveshdhull** [comment]
@pavloburykh , Sorry, I missed this one, there are so many QR scanners 😄, fixed now 👍

**Comment by pavloburykh** [comment]
@Parveshdhull thanx a lot for your work and such quick bugfixing. PR is ready for merge.

**Pull request merged**
