### PR TITLE
chore: bump status-go with filter improvements

### PR DESCRIPTION
**Pull request by chaitanyaprem**
fixes issues noticed in lightClient using Waku-Filter protocol.

### Summary

Improved lightClient functionality especially fixing issues around Waku-Filter protocol usage and optimizing how filter subscriptions are managed and Filter ping occurs with service node. 
Still some optimizations and additional work is pending wrt light client reliability, but this PR brings Filter to a hopefully decent stage(without any major issues) before proceeding with further changes.

Note that if you are subscribed to status community, there would be a lot of filter subscriptions. This still needs optimization which is pending. Anyways, number of subscriptions would help test nwaku node as well to handle soo may :)

~~**Note that to reduce issues with lightClient(by not connecting to other desktop instances), this build only uses fleet nodes and does not do any discovery via peerExchange.**~~

Relevant status-go PR https://github.com/status-im/status-go/pull/4665

### Testing notes (To be updated)
Note to enable debug logs while testing.
- ~~Enable lightClient from Advanced Settings~~ @chaitanyaprem has updated PR so lightClient is Enabled by default
- Login normally, and make sure you got some peers connected  -- Advanced -> Peer Stats
- Run tests by being part of community , 1:1 chats, private group chats etc
- Disconnect from the internet, wait until the peer count goes to 0.  (Note that it takes some time for identifying disconnection - this needs fixing)
- Connect to the internet, You should reconnect to some peers in sometime. (Note that it takes some time for peers to be connected - this needs fixing)
- Test reception of messages on 1:1 chat, groups and community
- Leave it running and ensure no issues in send/receive messages

**In case of any issue please report along with debug logs via DM or as a comment in this PR itself.** 

#### Platforms

- Android
- iOS

##### Functional

- 1-1 chats
- public chats
- group chats
- account recovery
- new account
- user profile updates
- networks
- fleet
- bootnodes

##### Non-functional

None

status: for dogfooding only

### CODE REVIEW

**Comment by fryorcraken** [comment]
On android, my peer stats screen is empty (i enabled light client).

**Comment by pavloburykh** [comment]
> On android, my peer stats screen is empty (i enabled light client).

Hey @fryorcraken! This is a UI issue on Android. Peer stats data is not visible in light mode. Switch appearance to Dark mode and peer stats will be visible for you. See video below. 

https://github.com/status-im/status-mobile/assets/97245802/9e3e362f-2d3a-4152-a097-634da080db8d

**Comment by pavloburykh** [comment]
@chaitanyaprem hey! Recent testrun failed because messages are not delivered in chats. 

### ISSUE 1 Messages are not delivered in chats

**Steps:** 

1. User A adds User B as contact
2. Users send messages to each other in 1-1 chat
3. See if messages are delivered

**Actual result:** messages are not delivered

[User_A_sender.log](https://github.com/user-attachments/files/15788056/User_A_sender.log)
[User_B_receiver.log](https://github.com/user-attachments/files/15788057/User_B_receiver.log)


User A sending messages https://app.eu-central-1.saucelabs.com/tests/03f7f9be92084779901d8a2375174023?auth=5d114754ef23a17d91469fe83aa22813#95

User B not receiving messages https://app.eu-central-1.saucelabs.com/tests/59a110f76b8f49dd9289d20e2583fcdd?auth=6a4cd0d0dc19c74aba0aa15d7bbdaaf6#126

**Comment by pavloburykh** [comment]
@chaitanyaprem Unfortunately tests are still failing. Here are failure examples from the last testrun:

### 1. Community is failed to be fetched 

**Steps:** 

1. User opens community link
2. See if community is fetched

**Actual result:** community is not fetched

[Community_not_fetched.log](https://github.com/user-attachments/files/15800748/Community_not_fetched.log)

https://app.eu-central-1.saucelabs.com/tests/92f6aff6d2d64871b6a852d0e579f0ae?auth=a435101b417271cd7b116e1624d41492#85

### 2. Contact request is not delivered to receiver

**Steps:** 

1. User A [sends](https://app.eu-central-1.saucelabs.com/tests/2404eb81be3b49e3a707d868092da4b2?auth=bc9f1e79f5b5b85c76e59c43fad8aab9#62) contact request to User B
2. See if User B received contact request

**Actual result:** 

[User_A_contact_request_sender.log](https://github.com/user-attachments/files/15800841/User_A_contact_request_sender.log)
[User_B_contact_req_receiver.log](https://github.com/user-attachments/files/15800842/User_B_contact_req_receiver.log)

Contact request [is not delivered](https://app.eu-central-1.saucelabs.com/tests/95daa04699254c018a8e4b500aa3b49d?auth=56137ae3b6f0a08d5698261a89ce66ea#51) to User B.

**Comment by pavloburykh** [comment]
@chaitanyaprem According to the latest e2e [results](https://github.com/status-im/status-mobile/pull/20369#issuecomment-2163077227) the main root cause of the failures is delay in delivering contact requests. 

I have reproduced the issue manually, see the details below:

### Contact request (CR) signals are delivered with delay

**Steps:** 

1. User A sends CR to User B
2. User B receives CR and accepts it
3. See if User B has appeared as contact of User A

**Actual result:** User B appeared in User's A contact list only after User A performs re-login 

[User_A_CR_sender_IOS.zip](https://github.com/user-attachments/files/15806654/User_A_CR_sender_IOS.zip)
[User_B_CR_receiver_Android.zip](https://github.com/user-attachments/files/15806655/User_B_CR_receiver_Android.zip)

https://github.com/status-im/status-mobile/assets/97245802/dbff5e7c-efa9-497d-92d0-7a1ba63e5ed0


**Expected result:** User A should appear in User's B contact list once User A accepts User's B contact request.

**Comment by pavloburykh** [comment]
@chaitanyaprem thank you for the PR! I have completed testing. 

Here is a summary of most noticeable issues that I have faced during testing: 

1. Sometimes backed up data (i.e. communities/contacts etc) is not restored or restored with delay
2. Chat history in communities is not fetched or fetched with delay
3. Curated communities are not fetched or fetched with delay

I would assume that those issues could be related to  current implementation in which we are using only fleet nodes. So, I propose not to block this PR anymore and merge it. We will have another round of testing once connection to other running desktop instances will be fixed, please ping me up once the fix is ready. 

**IMPORATNT:** if you gonna merge mobile PR as well - please do not forget to disable light client as default.

**Comment by chaitanyaprem** [comment]
> @chaitanyaprem thank you for the PR! I have completed testing.
> 
> Here is a summary of most noticeable issues that I have faced during testing:
> 
>     1. Sometimes backed up data (i.e. communities/contacts etc) is not restored or restored with delay
> 
>     2. Chat history in communities is not fetched or fetched with delay
> 
>     3. Curated communities are not fetched or fetched with delay
> 
Thanks a lot for the testing and summarizing the results!

if i am not wrong, these are issues related to store node queries and not with Filter.

> 
> I would assume that those issues could be related to current implementation in which we are using only fleet nodes. So, I propose not to block this PR anymore and merge it. We will have another round of testing once connection to other running desktop instances will be fixed, please ping me up once the fix is ready.
> 

Sure, that would anyways be required.

> **IMPORATNT:** if you gonna merge mobile PR as well - please do not forget to disable light client as default.

Not sure if i should merge it. What is the general procedure? 
I was thinking of just merging the status-go PR only.

**Comment by pavloburykh** [comment]
> if i am not wrong, these are issues related to store node queries and not with Filter.

I am not facing issues on relay mode, in develop builds for instance. So I assume it is related to light client. 

> Not sure if i should merge it. What is the general procedure?
I was thinking of just merging the status-go PR only.  

If there were no changes on mobile side (except enabling light client as default) - then you can just close mobile PR. We will get your go changes next time when go version will be bumped in mobile develop.

**Comment by chaitanyaprem** [comment]
> > if i am not wrong, these are issues related to store node queries and not with Filter.
> 
> I am not facing issues on relay mode, in develop builds for instance. So I assume it is related to light client.
> 

Odd though, because these doesn't seem to have anything to do with filter. 
I am not sure about point-3. `Curated communities are not fetched or fetched with delay` though.

> > Not sure if i should merge it. What is the general procedure?
> > I was thinking of just merging the status-go PR only.
> 
> If there were no changes on mobile side (except enabling light client as default) - then you can just close mobile PR. We will get your go changes next time when go version will be bumped in mobile develop.

Yep, no other changes in mobile so will not merge this one. Will only merge status-go PR.

**Comment by chaitanyaprem** [comment]
Closing this PR as changes are mainly in status-go and this is used only for testing.

**Comment by pavloburykh** [comment]
> Odd though, because these doesn't seem to have anything to do with filter.
> I am not sure about point-3. `Curated communities are not fetched or fetched with delay` though.

But couldn't the fact that we are not connecting to desktop instances cause delay in fetching different kinds of data? I think we need to re-check it once this issue will be fixed. If the issue remains - then we will need to investigate more deeply.

**Comment by chaitanyaprem** [comment]
> > Odd though, because these doesn't seem to have anything to do with filter.
> > I am not sure about point-3. `Curated communities are not fetched or fetched with delay` though.
> 
> But couldn't the fact that we are not connecting to desktop instances cause delay in fetching different kinds of data? I think we need to re-check it once this issue will be fixed. If the issue remains - then we will need to investigate more deeply.

Nope, fleet nodes are supposed to be the fastest way to fetch data, unless if it is something to be fetched from desktop instance of community owner..but i am not sure of the flows there yet.

**Comment by pavloburykh** [comment]
> Nope, fleet nodes are supposed to be the fastest way to fetch data, unless if it is something to be fetched from desktop instance of community owner..but i am not sure of the flows there yet.

Okay, so this is really suspicious as I see a big difference between fetching in develop build and PR. Anyway, I will focus on re-testing this in future PRs related to light client. Thank you.

**Pull request closed without merging**
