### PR TITLE
Show "Kicked from community" notification in Activity Center

### LINKED ISSUE #15733: Show "Kicked from Community" Notification in Activity Center
## Feature Issue

Implement the `Kicked from Community` Notification in Activity Center.

1 line

### User Story

> As a user
> I want to see a notification in my Activity Center for the community which I have been kicked out
> So that I will know about it

### Description

- User `A` and User `B` are mutual contacts. 
- User `A`  is an admin of a closed community and user `B` is a member.
- User `A` kicks out user `B` from the Community
- User `B` receives a notification in Activity Center that he/she has been kicked out.

### Design

[Figma Link](https://www.figma.com/file/eDfxTa9IoaCMUy5cLTp0ys/Shell-for-Mobile?node-id=4537%3A515620&t=H10gqxyikMPF2249-1)

### PR DESCRIPTION
**Pull request by smohamedjavid**
fixes #15733

### Summary

This PR implements the `Kicked from community` notification in Activity Center

#### Platforms

- Android
- iOS

#### Prerequisites:  User `A` and User `B` are mutual contacts. User `A`  is an admin of a closed community and user `B` is a member.

- User `A` kicks out user `B` from the Community
- User `B` receives a notification in Activity Center that he/she has been kicked out.

status: ready

### CODE REVIEW

**Review by flexsurfer — APPROVED** [review]
nice!

**Review by ilmotta — APPROVED** [review]

**Review by J-Son89 — APPROVED** [review]

**Review by ajayesivan — APPROVED** [review]

**Review by alwx — APPROVED** [review]

**Comment by pavloburykh** [comment]
@smohamedjavid thanx for the PR! Please take a look at the following issue:

### ISSUE 1 Unread counter does not appear on Activity Center icon for new "Kicked from community" notification

**Steps:** 

1. User A kicks User B from community
2. See if unread counter will appear on Activity Center icon for User B 

**Actual result:** unread counter does not appear despite notification has arrived in AC. Counter will be updated in case some new notifications arrive into AC. 


https://user-images.githubusercontent.com/97245802/234315885-80ef88e9-2eda-44ea-90a2-e7f664c172e8.mp4



**Expected result:** unread counter is updated on AC icon when new "Kicked from community" notification arrives.

**Comment by smohamedjavid** [comment]
@pavloburykh - Thanks for testing this PR.
Kindly retest, as the issue has been fixed.

**Comment by pavloburykh** [comment]
> @pavloburykh - Thanks for testing this PR. Kindly retest, as the issue has been fixed.

@smohamedjavid thanx for the fix. PR is ready to be merged. Failed e2e are not PR related.

**Pull request merged**
