### PR TITLE
Pinning contact request message leads to a crash #20131

### LINKED ISSUE #20131: Pinning contact request message leads to a crash
After this the profile is not usable anymore. 

**Steps:**
1) User A, B: restore or create multiaccount 
2) User A: start 1-1 chat, send contact request
3) User B: accept CR
4) User B: pin message from CR

**Expected result:**
can pin contact message (works in nightly) or pinning is disabled for this message

**Actual result:**
photo_2024-05-21 13 09 18

**OS:** IOS, Android
**Devices:**
**Logs:** 
[status_logs.zip](https://github.com/status-im/status-mobile/files/15388964/status_logs.zip)

_Originally posted by @churik in https://github.com/status-im/status-mobile/issues/20082#issuecomment-2122388566_

### PR DESCRIPTION
**Pull request by flexsurfer**
fixes #20131

### CODE REVIEW

**Review by Parveshdhull — APPROVED** [review]

**Comment by mariia-skrypnyk** [comment]
Hi @flexsurfer !
Thanks for your fix.
Looks good on both platforms. 
One E2E is under investigation, will send an update soon. 🙏

**Comment by pavloburykh** [comment]
Hey @flexsurfer! Thank you for the PR. @mariia-skrypnyk tested the fix of initial crash and it seems to work fine.

Although I have faced another crash while pinning a message Bridged from Discord. I am wondering if we can handle it in this PR or should I log it separately?

### ISSUE 1 App crashes when Desktop pins message Bridged from Discord

**Steps:** 

1. Recover member of Status community on mobile and desktop
2. From Desktop pin any Bridged from Discord messages
3. Open channel with pinned message on mobile
4. Observe the result

**Actual result:** app crashes with ```Index of bounds``` error

[Status-debug-logs - 2024-05-22T152729.634.zip](https://github.com/status-im/status-mobile/files/15403264/Status-debug-logs.-.2024-05-22T152729.634.zip)

https://github.com/status-im/status-mobile/assets/97245802/d1c7f1f6-d19a-43b1-9aa0-4135ea84b0e1

**Comment by flexsurfer** [comment]
thanks @pavloburykh should be fixed now, but all possible types of pinned messages should be tested

**Comment by pavloburykh** [comment]
> thanks @pavloburykh should be fixed now, but all possible types of pinned messages should be tested

thank you @flexsurfer! The crash is fixed. 

I see there are some other UI issues related to pinned bridged messages on mobile. Mind, that if it is not trivial to fix them - I believe we can ignore, as they are related only to pinned bridged messages. 

1. Pinned bridged messages are not shown within Pinned preview. 
2. There is no pinned icon and the name who pinned bridged message
3. There is no message preview within system message about pinning bridged message

photo_2024-05-22 16 58 50


Here is an example of expected result, how it looks like in case of pinning not bridged message:

photo_2024-05-22 17 03 04
photo_2024-05-22 17 03 08

**Comment by pavloburykh** [comment]
> I see there are some other UI issues related to pinned bridged messages on mobile. Mind, that if it is not trivial to fix them - I believe we can ignore, as they are related only to pinned bridged messages.

@flexsurfer I think it does not make sense to spend time on fixing these issues for now. So once @mariia-skrypnyk approves the PR - we are ready for merge.

**Comment by mariia-skrypnyk** [comment]
@flexsurfer thanks for waiting.
Failed tests are not related.
I double checked pinned scenarios and all looks good.
PR can be merged!
@pavloburykh I'll create issues as followups minors. Thanks for help!

**Pull request merged**
