### PR TITLE
Fixes #3456: Publish diawi links in relevant PR

### LINKED ISSUE #3456: Publish diawi links in relevant PR
### User Story

As a user, I want easy access to diawi links from github PR

### Description

*Type*: Feature

Each time a build is successful associated diawi links should be published to associated PR.
Also make sure build version number is accessible.

### PR DESCRIPTION
**Pull request by pacamara**
Fixes #3456: Publish diawi links in relevant PR

### Summary:

Make relevant github api call to publish diawi links on the associated PR.

Have tested by setting up a local Jenkins with github integration. See tests at https://github.com/pacamara/status-react/pull/4

Jenkins credentials/variables used:
* GIT_HUB_TOKEN (secret text credential): already used in test/appium/Jenkinsfile 
* BRANCH_NAME : used to provide version info
* CHANGE_ID : contains PR number

Hardcodes github user as "status-im", could be parameterized to a credential like GIT_HUB_USER if needed.

status: ready

### CODE REVIEW

**Comment by jeluard** [comment]
@PombeirP Do you mind taking a look at this?

**Comment by pacamara** [comment]
@jeluard @PombeirP Thanks! but please note, definitely not yet review ready :)

**Review by jeluard — APPROVED** [review]

**Comment by pacamara** [comment]
@jeluard Thanks for enabling the jenkins build :)  I get 'Unauthorized' when I try to sign into jenkins using my google account, is there a way to see the logs?

**Comment by jeluard** [comment]
@pacamara You can't unfortunately as of now.

**Comment by pacamara** [comment]
@jeluard Ah ok... does it use the branch's Jenkinsfile or develop/Jenkinsfile ? The latter I guess?

**Review by rasom — APPROVED** [review]

**Comment by pacamara** [comment]
@jeluard @PombeirP @rasom Since testing against status-im Jenkins not possible, have set up a local jenkins. Can see the generated comments for apk/ipa uploads at https://github.com/pacamara/status-react/pull/4. Working fine, status is now READY  :) :beers:

**Comment by asemiankevich** [comment]
i have checked that i can install both builds, messages and money exchange. sanity check passed, i think we can merge this

**Comment by pacamara** [comment]
@asemiankevich Thanks! But if the builds are from this PR, I don't think the changes to Jenkinsfile have been exercised? Since afaik the develop/ branch's Jenkinsfile is still used when building this PR. (Sorry, should have made that clear in testing notes).

I think if someone who has admin rights on the status-im repo branches `pacamara:develop_issue3456_publishDiawiLinksInPr`, creates their own PR, then the builds for that will use the new Jenkinsfile.

**Comment by pacamara** [comment]
Can see from recent PRs under review, eg, https://github.com/status-im/status-react/pull/4233, that the diawi comments are working :D  :champagne: :beers:

**Pull request merged**
