### PR TITLE
[WIP] mailserver logs

### PR DESCRIPTION
**Pull request by rasom**
https://notes.status.im/6aKfal6HR2y5K5-Ejqp33A

status: wip

<blockquote><div><strong><a href="https://notes.status.im/6aKfal6HR2y5K5-Ejqp33A">Mail server monitoring - CodiMD</a></strong></div></blockquote>

### CODE REVIEW

**Comment by rasom** [comment]
logs can be found at `Profile -> Advanced -> Mailserver Logs`

**Comment by rasom** [comment]
https://ci.status.im/job/status-react/job/combined/job/mobile-ios/3362/
https://ci.status.im/job/status-react/job/combined/job/mobile-android/6689/

<blockquote><div><strong><a href="https://ci.status.im/job/status-react/job/combined/job/mobile-ios/3362/">status-react » combined » mobile-ios #3362 [Jenkins]</a></strong></div></blockquote>
<blockquote><div><strong><a href="https://ci.status.im/job/status-react/job/combined/job/mobile-android/6689/">status-react » combined » mobile-android #6689 [Jenkins]</a></strong></div></blockquote>

**Comment by rasom** [comment]
<a href="https://status-im-prs.ams3.digitaloceanspaces.com/StatusIm-181108-164445-d60f6b-pr.apk">Apk</a> 
<a href="https://status-im-prs.ams3.digitaloceanspaces.com/StatusIm-181108-164445-d60f6b-e2e.apk">e2e</a> 
<a href="https://i.diawi.com/6qHVSt">iOS</a> 
<a href="https://status-im-prs.ams3.digitaloceanspaces.com/StatusIm-181108-164445-d60f6b-pr.AppImage">App</a> 
<a href="https://status-im-prs.ams3.digitaloceanspaces.com/StatusIm-181108-164445-d60f6b-pr.dmg">Mac</a>

**Comment by adambabik** [comment]
I played with it a bit more and have some feedback:
* it's cool that the log cleans up after the app is removed from the background,
* `mailserver.request.successful` is a bit misleading; I figured out it means that the message request was sent properly but I don't know how successfulness is determined.

Overall, it's simple but extremely useful! I don't see anything more that we can add here.

**Comment by rasom** [comment]
@adambabik, 
re `mailserver.request.successful`: do we need to rename it?

**Comment by adambabik** [comment]
@rasom Can we do that? Something like `sending mailserver request completed` and `sending mailserver request failed`?

**Pull request closed without merging**
