### PR TITLE
Fix react-native-share auto linking error

### LINKED ISSUE #12683: react-native-share  autolinking  error
error React Native CLI uses autolinking for native dependencies, but the following modules are linked manually: 
  - react-native-share (to unlink run: "react-native unlink react-native-share")
This is likely happening when upgrading React Native from below 0.60 to 0.60 or above. Going forward, you can unlink this dependency via "react-native unlink <dependency>" and it will be included in your app automatically. If a library isn't compatible with autolinking, disregard this message and notify the library maintainers.
Read more about autolinking: https://github.com/react-native-community/cli/blob/master/docs/autolinking.md

### PR DESCRIPTION
**Pull request by briansztamfater**
fixes #12683 

status: ready

### CODE REVIEW

**Review by cammellos — APPROVED** [review]

**Review by shivekkhurana — APPROVED** [review]

**Comment by briansztamfater** [comment]
I think a smoke testing on share image functionality would be fine before merging cc @qoqobolo @churik

**Comment by qoqobolo** [comment]
@briansztamfater can you rebase it, please?
Thanks

**Comment by briansztamfater** [comment]
> @briansztamfater can you rebase it, please? Thanks

Sure, done!

**Comment by qoqobolo** [comment]
Thanks @briansztamfater!
PR is smoke-tested and can be merged.

**Pull request merged**
