### PR TITLE
Implement new splash screen in its static version

### LINKED ISSUE #15011: OnBoarding - Implement new splash screen
Implement new splash screen as per new designs for onboarding:

https://www.figma.com/file/o4qG1bnFyuyFOvHQVGgeFY/Onboarding-for-Mobile?node-id=2231%3A253380&t=fD9St3RpvL2wULMb-0

Are more animations needed for this? Check with design team before starting as the designs/illustrations might not be 100% ready

### PR DESCRIPTION
**Pull request by briansztamfater**
fixes #15011 

### Summary

Implement new splash screen in its static version as the animation is not defined yet

### Development notes

For Android, we had to migrate to new Splash Screen API, so the changes were not as simple as I expected. Keeping `react-native-lottie-splash-screen` library because maybe we will need it, but if not we have to remove it on the following PR when we add animations.

### Testing notes

- Android 12 introduced a new Splash Screen API and impemented it with support for older versions in this PR, so we should test it on devices with Android 12 or greater as well as Android 11 or lower
- iOS 16 has a bug that makes status bar not respecting its light style on the splash screen, for iOS 15 or lower should respect the status bar style -> https://stackoverflow.com/questions/74255415/ios-16-launch-screen-status-bar-style-cannot-be-changed-to-light-content#comment131100612_74255415 there's a workaround but it implies forcing the same status bar for all the views so it doesn't work for us, we need to be customizable for each view. [EDIT] Actually I tested it on my iOS device and worked fine, so maybe is just an issue with simulators

#### Platforms

- Android
- iOS

### Steps to test

- Open Status
- That's it :)

status: ready

### CODE REVIEW

**Comment by flexsurfer** [comment]
hey @briansztamfater are we sure it won't be animated soon? just to do not do double work, also `iOS 16 has a bug that makes status bar not respecting` is this bag happens only in this PR? where does it came from ?

**Comment by briansztamfater** [comment]
> hey @briansztamfater are we sure it won't be animated soon? just to do not do double work, also `iOS 16 has a bug that makes status bar not respecting` is this bag happens only in this PR? where does it came from ?

Hey @flexsurfer we are unsure when / how will it be animated, but either way since Android 12 forces a new Splash Screen API that shows before the other one that we currently have and that also supports animations, it is necessary to do some changes on our implementation and migrate it. https://developer.android.com/develop/ui/views/launch/splash-screen
For iOS 16 here's the issue -> https://stackoverflow.com/questions/74255415/ios-16-launch-screen-status-bar-style-cannot-be-changed-to-light-content#comment131100612_74255415 there's a workaround but it implies forcing the same status bar for all the views so it doesn't work for us, we need to be customizable for each view. [EDIT] Actually I tested it on my iOS device and worked fine, so maybe is an issue with simulators

**Review by yqrashawn — APPROVED** [review]

**Review by flexsurfer — COMMENTED** [review]
i don't see`org.devio.rn.splashscreen.SplashScreen` removed from the deps

**Comment by briansztamfater** [comment]
> i don't see`org.devio.rn.splashscreen.SplashScreen` removed from the deps

@flexsurfer that package is part of `react-native-lottie-splash-screen` (which is a fork of `react-native-splash-screen`), for some reason the library is used in iOS (native side) but I feel it is unnecessary now, not sure if it is safe to remove it but I can raise a follow up PR to remove that library if you agree. There's no `org.devio.rn.splashscreen` dependency at all in gradle.

**Review by jakubgs — COMMENTED** [review]
If you are just changing Gradle/Node/Gem dependencies by changing data files like `deps.json` there is no need to include me in the PR.

Include me if you are changing actual Nix derivations or scripts. Not just a JSON file.

**Comment by pavloburykh** [comment]
@briansztamfater hi! Could you please rebase the PR and move it to E2E column if it is ready for testing? Thank you!

**Comment by flexsurfer** [comment]
btw i like our current animated version, dunno why we want to change it cc @pedro-et @xAlisher

**Comment by pedro-et** [comment]
@flexsurfer that is just a placeholder for now as we are undergoing a small polish to the status brand so it will have to change before release

**Comment by pavloburykh** [comment]
@briansztamfater thanx for the PR. Please, take a look at the following issues

### ISSUE 1 Logo is not displayed on splash screen during first launch of the app (Samsung Galaxy A52, Android 12)

https://user-images.githubusercontent.com/97245802/223761749-6c8032f4-3bf5-4c28-b58a-91e39657dcec.mp4

**Comment by pavloburykh** [comment]
### ISSUE 2 App gets stuck on splash screen after reopening (IOS 14, 16)

Several reopening might be needed to reproduce the bug

**Steps:** 

1. Install app
2. Open app
3. Close and reopen app
4. Keep closing/reopening untill app gets stuck on splash screen. See video below


https://user-images.githubusercontent.com/97245802/223766570-31a359ee-46ca-4627-b204-276cff68babf.mp4

**Comment by pavloburykh** [comment]
### ISSUE 3 Wrong background color and logo on splash screen (IOS 16)

photo_2023-03-08 18 10 49

**Comment by pavloburykh** [comment]
### ISSUE 4 Dark/light screen is shown after splash screen when reopening app on Android

Tested on Samsung Galaxy A52, Android 12; Huawei P20 light, android 9; Huawei P40 Lite EMUI 12, Android 10

Below are the videos from different Android devices

**Samsung Galaxy A52, Android 12**
Splash screen is shown for a moment and then is changed by dark screen which is shown until onboarding screen appears. Also, splash screen background color seems to be wrong. 

https://user-images.githubusercontent.com/97245802/223771598-3b07481e-9a77-44a8-9dbf-ed35e1ed09f1.mp4

**Huawei p20 light, Android 9**

https://user-images.githubusercontent.com/97245802/223774304-9e6eb871-1ee2-4c02-a91b-8cb123648c1c.mp4


**Huawei P40 Lite EMUI 12, Android 10**

Splash screen is shown for a moment and then is changed by light screen which is shown until onboarding screen appears. 

https://user-images.githubusercontent.com/97245802/223773137-3ad0ca2a-1e9c-442a-b2d2-af3ccb092bda.mp4

**Comment by pavloburykh** [comment]
> ### ISSUE 2 App gets stuck on splash screen after reopening (IOS 14, 16)

@briansztamfater looks like this one is not PR related, as I am facing this issue in develop with an old splash screen. So I can log it separately.

**Comment by briansztamfater** [comment]
Sorry for the delay @pavloburykh, I'll check all the issues and come back to you :)

**Comment by pavloburykh** [comment]
> Sorry for the delay @pavloburykh, I'll check all the issues and come back to you :)

no worries @briansztamfater take your time. thanx for the update.

**Comment by briansztamfater** [comment]
> ### ISSUE 3 Wrong background color and logo on splash screen (IOS 16)
> photo_2023-03-08 18 10 49

This one does not make sense to me as I replaced the old image 🤔
Can you provide more context on the device you tested with? I tested with an iPhone 13 Pro (iOS 16.1.1) and is showing the correct logo / color.

**Comment by briansztamfater** [comment]
> @briansztamfater thanx for the PR. Please, take a look at the following issues
> 
> ### ISSUE 1 Logo is not displayed on splash screen during first launch of the app (Samsung Galaxy A52, Android 12)

@pavloburykh After some research I realized this is an issue with the Android API: https://issuetracker.google.com/issues/207386164
You can also reproduce this by entering on App Info, and launch the app from there, and happens with every app that has the new Splash Screen API implemented (Play Store app or Instagram, to name a few). I would leave it as is by now and for sure we will update the library when this is fixed. Also this is happening only with a few Android versions or devices I think, couldn't reproduce it with a Xiaomi Mi 10T with Android 10 but could with a Samsung Galaxy A52 with Android 13

**Comment by pavloburykh** [comment]
> Can you provide more context on the device you tested with? I tested with an iPhone 13 Pro (iOS 16.1.1) and is showing the correct logo / color.

Hi @briansztamfater !

@VladimrLitvinenko is reproducing on his iPhone 11 pro max, IOS 16

@qoqobolo is reproducing on her iPhone SE, IOS 16.1.1

https://user-images.githubusercontent.com/97245802/224943388-fd163622-460d-4efa-a213-92bb4268008b.mp4

**Comment by pavloburykh** [comment]
> @pavloburykh After some research I realized this is an issue with the Android API: https://issuetracker.google.com/issues/207386164 You can also reproduce this by entering on App Info, and launch the app from there, and happens with every app that has the new Splash Screen API implemented (Play Store app or Instagram, to name a few). I would leave it as is by now and for sure we will update the library when this is fixed. Also this is happening only with a few Android versions or devices I think, couldn't reproduce it with a Xiaomi Mi 10T with Android 10 but could with a Samsung Galaxy A52 with Android 13

@briansztamfater thanx for the research. I will log this issue separately as soon as we merge current PR into develop.

**Comment by flexsurfer** [comment]
hey @briansztamfater could you pls elaborate on why so many issues in this PR? we never had any issues with splash screen before

**Comment by pavloburykh** [comment]
> > Can you provide more context on the device you tested with? I tested with an iPhone 13 Pro (iOS 16.1.1) and is showing the correct logo / color.
> 
> Hi @briansztamfater !
> 
> @VladimrLitvinenko is reproducing on his iPhone 11 pro max, IOS 16
> 
> @qoqobolo is reproducing on her iPhone SE, IOS 16.1.1

@briansztamfater **UPDATE:** it turned out that @qoqobolo is not reproducing the bug any more on iPhone SE, IOS 16.1.1

At the same time, it is still reproducible for @VladimrLitvinenko on iPhone 11 pro max, IOS 16.3.1

**Comment by briansztamfater** [comment]
> > > Can you provide more context on the device you tested with? I tested with an iPhone 13 Pro (iOS 16.1.1) and is showing the correct logo / color.
> 
> > 
> 
> > Hi @briansztamfater !
> 
> > 
> 
> > @VladimrLitvinenko is reproducing on his iPhone 11 pro max, IOS 16
> 
> > 
> 
> > @qoqobolo is reproducing on her iPhone SE, IOS 16.1.1
> 
> 
> 
> @briansztamfater **UPDATE:** it turned out that @qoqobolo is not reproducing the bug any more on iPhone SE, IOS 16.1.1
> 
> 
> 
> At the same time, it is still reproducible for @VladimrLitvinenko on iPhone 11 pro max, IOS 16.3.1
> 
> 
> 
> 

So it seems like a cache issue, I'll see how to prevent this happening

**Comment by briansztamfater** [comment]
> hey @briansztamfater could you pls elaborate on why so many issues in this PR? we never had any issues with splash screen before

@flexsurfer here some bullet points on the issues.
- iOS issue seems to be just a cache issue: https://www.theswift.dev/posts/fix-the-cached-launch-screen-image-bug-on-ios already pushed the fix cc @pavloburykh 
- For Android, new Splash Screen API introduces a few changes on how splash screen works. First of all, the maximum (and recommended) duration of the Splash Screen is 1 second, but in that lapse the app is still loading so we may see a blank screen until the first screen is loaded and shown, specially on old devices. So we need to force the splash screen to keep showing, the API provides a way to do it, but we need to know when setNavigationRoot is called from `react-native-navigation` to do it properly. There's an open PR (https://github.com/wix/react-native-navigation/pull/7586) on their repo that implements this so we should wait for it to be merged or add a patch to our library. Also this discussion is relevant https://github.com/wix/react-native-navigation/discussions/7363
I now forced the splash screen to be shown for more seconds, but it is not the optimal solution. cc @pavloburykh 
- Also the other issue, is a known issue of the API happening on all modern apps implementing it (i think it only happens on Samsung devices) and we cannot do anything about it until there is a new version of the API with the fix (also not a big deal from my perspective), more info here https://github.com/status-im/status-mobile/pull/15058#issuecomment-1467194837.

**Comment by pavloburykh** [comment]
@briansztamfater kindly, rebase PR to the latest develop. Currently it is 24 commits behind it. Thanx!

**Comment by briansztamfater** [comment]
> @briansztamfater kindly, rebase PR to the latest develop. Currently it is 24 commits behind it. Thanx!

Done ✅

**Comment by flexsurfer** [comment]
hey @briansztamfater thank you, just want to make sure, does that mean current splash screen will have same issues ?

**Comment by pavloburykh** [comment]
@briansztamfater thanx for the fixes. Please take a look at a few more issues:

Still reproducing [ISSUE 4](https://github.com/status-im/status-mobile/pull/15058#issuecomment-1460480705) (**Dark screen is shown after splash screen when reopening app**) on Huawei P20 light, android 9

At the same time this issue has gone for Samsung Galaxy A52, Android 12 and Huawei P40 Lite EMUI 12, Android 10

https://user-images.githubusercontent.com/97245802/225284521-fdade7e5-72ba-4f12-9b24-e52ff592ea2d.mp4

**Comment by pavloburykh** [comment]
### ISSUE 5 Light stripe in the bottom of the splash screen when light mode is enabled on IOS

Tested on iPhone X, IOS 14.1; iPhone SE, IOS 16.1.1; iPhone 11 Pro Max, IOS 16.3.1 

https://user-images.githubusercontent.com/97245802/225278561-d1423149-861c-4ad6-b137-78e52d8b96d6.mp4

**Comment by pavloburykh** [comment]
### ISSUE 6 Light status bar on splash screen when light theme mode is enabled (Huawei P40 Lite EMUI 12, Android 10)

photo_2023-03-15 12 41 40

**Comment by briansztamfater** [comment]
@pavloburykh I increased the delay on the splash screen which _should_ fix the blank screen on Huawei P20 light with Android 9, also although I couldn't reproduce the other two issues, I think I found the problems and pushed a fix. Let me know how testing goes on those.

**Comment by pavloburykh** [comment]
thanx @briansztamfater ! [ISSUE 4](https://github.com/status-im/status-mobile/pull/15058#issuecomment-1460480705) and [ISSUE 5](https://github.com/status-im/status-mobile/pull/15058#issuecomment-1469770387) are fixed. 

[ISSUE 6](https://github.com/status-im/status-mobile/pull/15058#issuecomment-1469770479) is still reproducible, I think this issue can be addressed in separate PR in order not to block current one. 

**Regarding increased delay:** 

I should admit that increasing delay to current level makes splash screen displaying for too long time on Android devices (see video below) and I am not sure If this is an optimal solution for us. 


https://user-images.githubusercontent.com/97245802/225380577-958be6ae-5934-42b2-8f25-2c8ebbf6f793.mp4


If there is no other solution I guess we will have to put up with [ISSUE 4](https://github.com/status-im/status-mobile/pull/15058#issuecomment-1460480705) but decrease delay to some more optimal and acceptable level.

**Comment by briansztamfater** [comment]
> thanx @briansztamfater ! [ISSUE 4](https://github.com/status-im/status-mobile/pull/15058#issuecomment-1460480705) and [ISSUE 5](https://github.com/status-im/status-mobile/pull/15058#issuecomment-1469770387) are fixed.
> 
> [ISSUE 6](https://github.com/status-im/status-mobile/pull/15058#issuecomment-1469770479) is still reproducible, I think this issue can be addressed in separate PR in order not to block current one.
> 
> **Regarding increased delay:**
> 
> I should admit that increasing delay to current level makes splash screen displaying for too long time on Android devices (see video below) and I am not sure If this is an optimal solution for us.
> 
> If there is no other solution I guess we will have to put up with [ISSUE 4](https://github.com/status-im/status-mobile/pull/15058#issuecomment-1460480705) but decrease delay to some more optimal and acceptable level.

I totally agree regarding the delay, if it is okay with the previous value I can revert it to that delay value for the time being until we are able to apply the optimal fix which depends on this PR being merged in our navigation library https://github.com/wix/react-native-navigation/pull/7586 . We should create an issue to track this.
For issue 6, I'll try to find the correct emulator to reproduce it and see if I can fix it.

**Comment by pavloburykh** [comment]
> if it is okay with the previous value I can revert it to that delay value 

Thanx @briansztamfater !
By previous value you mean before of after this [commit](https://github.com/status-im/status-mobile/pull/15058/commits/deb64a4005b7906c5a3af5e00327dd9add01bec7) 

Because I have just checked this build  https://status-im-mobile-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-230314-200310-04d1f9-pr15058-universal.apk once again and delay still seems to be too long, though it fixed [ISSUE 4](https://github.com/status-im/status-mobile/pull/15058#issuecomment-1460480705) for Samsung Galaxy A52, Android 12 and Huawei P40 Lite EMUI 12, Android 10


https://user-images.githubusercontent.com/97245802/225415423-9fe4eea0-164e-49d2-92f4-4175e312b5eb.mp4

**Comment by briansztamfater** [comment]
> > if it is okay with the previous value I can revert it to that delay value
> 
> Thanx @briansztamfater ! By previous value you mean before of after this [commit](https://github.com/status-im/status-mobile/pull/15058/commits/deb64a4005b7906c5a3af5e00327dd9add01bec7)
> 
> Because I have just checked this build https://status-im-mobile-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-230314-200310-04d1f9-pr15058-universal.apk once again and delay still seems to be too long, though it fixed [ISSUE 4](https://github.com/status-im/status-mobile/pull/15058#issuecomment-1460480705) for Samsung Galaxy A52, Android 12 and Huawei P40 Lite EMUI 12, Android 10

Based on your videos I reduced it to 3.2 seconds, still considerable amount but maybe acceptable for some devices. Either way is just an  arbitrary value and is temporal until we do it the proper way, which would hide the splash when the first screen is loaded depending on the loading time. Also when we add animations this will feel smother, and we will have a Splash implementation with the proper native API on Android.

**Comment by briansztamfater** [comment]
I've just tested our production app from the stores and for me it is showing two Splash screens, the Android 12 splash screen which is currently empty and shown forcedly by the OS, and then the custom animated one that is shown immediately after. Hence that's why is important to use the proper native API for the Splash Screen, even more because it supports animations natively now.

**Comment by briansztamfater** [comment]
Issue 6 should be fixed in latest build also, I was able to reproduce in a custom emulator and not happening anymore on the latest build

**Comment by pavloburykh** [comment]
@briansztamfater thank you for the fixes. PR is ready to be merged.

1. Current delay time of 3.2 seconds seems to be optimal and acceptable 
2. I[SSUE 6](https://github.com/status-im/status-mobile/pull/15058#issuecomment-1469770479) is fixed
3. [ISSUE 4](https://github.com/status-im/status-mobile/pull/15058#issuecomment-1460480705) remained to be fixed for Samsung Galaxy A52, Android 12 and Huawei P40 Lite EMUI 12, Android 10. Though it has appeared again on slow Huawei P20 light, android 9 (see video below) but it is acceptable for now as optimising delay value has more priority. 

https://user-images.githubusercontent.com/97245802/225569199-e2a55ec7-f3b0-40ae-8d93-ea7e25175e5c.mp4

**Pull request merged**
