### PR TITLE
[#17288] refactor: migrate previews to new api

### PR DESCRIPTION
**Pull request by mohsen-ghafouri**
to accomplish https://github.com/status-im/status-mobile/issues/17288

None of the basic components were touched

migrated preview screens:

- settings
- share

status: ready

### CODE REVIEW

**Review by ilmotta — APPROVED** [review]

**Comment by mohsen-ghafouri** [comment]
@status-im/mobile-qa the changes are just related to quo2 preview screens.

**Comment by VolodLytvynenko** [comment]
Hi @mohsen-ghafouri thank you for ping. I'm checking e2e

**Comment by VolodLytvynenko** [comment]
@mohsen-ghafouri e2e are good. Thank you for your work
@Francesca-G could you take a look at this PR?

**Comment by VolodLytvynenko** [comment]
Hi @mohsen-ghafouri A design review is not required. PR is ready to be merged if no need for QA manual testing

**Comment by mohsen-ghafouri** [comment]
Thanks @VolodLytvynenko

**Pull request merged**
