### PR TITLE
Disable Realm Analytics for Desktop builds

### LINKED ISSUE #6200: Disable Realm Mixpanel use on build machines
*EDIT*
How to disable Realm Analytics: https://github.com/realm/realm-js/issues/769

---

In https://github.com/status-im/status-react/pull/5479 we disabled Realm's Mixpanel analytics, but we got a [report](https://github.com/status-im/status-react/issues/5465) that this is still happening.

Roman suggested we need to configure some env var on the build machine.

### PR DESCRIPTION
**Pull request by vitvly**
Fixes #6200

### CODE REVIEW

**Review by jakubgs — APPROVED** [review]

**Comment by jakubgs** [comment]
Nice catch, i didn't pay enough attention to notice it was missing from desktop. Thanks!

**Review by maxhora — APPROVED** [review]

**Review by pedropombeiro — APPROVED** [review]

**Comment by churik** [comment]
@siphiuel still see api.mixpanel in connections for Mac OS build.


Log: [Status.log](https://github.com/status-im/status-react/files/2677035/Status.log)

**Comment by vitvly** [comment]
@churik Fixed in latest build.

**Review by yenda — APPROVED** [review]

**Review by vkjr — APPROVED** [review]

**Comment by vkjr** [comment]
@siphiuel, do we need to put the env var in both - jenkinsfiles and main.cpp? Isn't it redundant?

**Comment by vitvly** [comment]
@vkjr right, thanks, removed Jenkins changes.

**Pull request merged**
