### PR TITLE
Testing fix/loading-hash-ratchet-keys-from-db

### PR DESCRIPTION
**Pull request by vitvly**
Testing https://github.com/status-im/status-go/pull/5138

### CODE REVIEW

**Comment by yevh-berdnyk** [comment]
hi @vitvly,
there is an issue in e2e tests that can be related - messages in community channel are not received by both users who are in this channel. Here are the logs:
[device_1_log.json](https://github.com/status-im/status-mobile/files/15295327/device_1_log.json)
[device_1_logcat.log](https://github.com/status-im/status-mobile/files/15295329/device_1_logcat.log)

[device_2_log.json](https://github.com/status-im/status-mobile/files/15295335/device_2_log.json)
[device_2_logcat.log](https://github.com/status-im/status-mobile/files/15295336/device_2_logcat.log)

**Comment by vitvly** [comment]
Thank you @yevh-berdnyk , checking.

**Comment by yevh-berdnyk** [comment]
hi @vitvly, thanks for the PR, e2e failures are not related

**Comment by vitvly** [comment]
Thank you @yevh-berdnyk , merged the status-go PR (https://github.com/status-im/status-go/pull/5138)  and closing this one.

**Pull request closed without merging**
