### PR TITLE
[TESTS] Updated tests for deleting public chat and wallet recovery

### PR DESCRIPTION
**Pull request by yevh-berdnyk**
### Summary:

e2e tests fix

status: ready

### CODE REVIEW

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/TGtksn for branch PR-4520

<blockquote><div><strong><a href="https://i.diawi.com/TGtksn">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/NZiXgs for branch PR-4520

<blockquote><div><strong><a href="https://i.diawi.com/NZiXgs">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Review by antdanchenko — APPROVED** [review]

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/6qncyp for branch PR-4520

<blockquote><div><strong><a href="https://i.diawi.com/6qncyp">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/z4AEWo for branch PR-4520

<blockquote><div><strong><a href="https://i.diawi.com/z4AEWo">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Pull request merged**
