### PR TITLE
Ensure discover statuses are signed and verified (#436)

### PR DESCRIPTION
**Pull request by alwx**
I've implemented both signing and verification. Since there is no `ecrecover` function in web3.js, I've dived into how it works and used `elliptic` package (https://github.com/indutny/elliptic) instead to implement my own `ecrecover`. This function works fine when I sign with newly generated keypair, but `web3.eth.sign` function doesn't work. I've spent several hours trying to find a reason, but the reason is not related to my work — `web3.eth.sign` doesn't work according to multiple messages like, for instance, this one: https://github.com/ethereum/web3.js/issues/404#issuecomment-267425205

So seems like we have to wait or fix the web3.js issue before using signature verification. However, my code is complete and fine — it may be merged and one condition there can be uncommented later.

### CODE REVIEW

**Comment by jarradh** [comment]
Is it wise to merge this? I feel like this will become a lost "TODO"

**Comment by rasom** [comment]
Lets merge this PR when `personal_sign` and `personal_ecRecover` will be implemented in `web3.js`

**Comment by alwx** [comment]
The code has been rewritten — it finally uses `personal_sign` and `personal_ecRecover`. However, there is a password issue that still needs to be solved. See #436 for more information.

**Comment by jarradh** [comment]
I guess @farazdagi  will definitely have to expose some method to do this

**Comment by jeluard** [comment]
@alwx Can you comment on the status of this PR? Is it still relevant?

**Pull request closed without merging**
