### PR TITLE
chore_: remove passing node config when sync

### LINKED ISSUE #20946: Upgrade status-go to use new simpler local pairing `ReceiverConfig`
# Problem

Corresponding status-go PR:
- https://github.com/status-im/status-go/pull/5643

### PR DESCRIPTION
**Pull request by qfrank**
this is a refactor PR, fixes #20946

relate status-go [PR](https://github.com/status-im/status-go/pull/5643#pullrequestreview-2214748058)

### Testing notes
sync should work as before

#### Platforms

- Android
- iOS
- macOS
- Linux
- Windows

status: ready

### CODE REVIEW

**Comment by igor-sirotin** [comment]
@qfrank thank you for a quick update of mobile!
FYI, you can also remove `receiverConfig.deviceType`, it will be auto set in status-go:
https://github.com/status-im/status-go/blob/746be535185fe04fc1aae00d22b7a1cc25ef1e82/server/pairing/server.go#L303 https://github.com/status-im/status-go/blob/746be535185fe04fc1aae00d22b7a1cc25ef1e82/server/pairing/client.go#L530

**Review by siddarthkay — APPROVED** [review]

**Review by smohamedjavid — APPROVED** [review]

**Comment by pavloburykh** [comment]
@yevh-berdnyk could you please check e2e results above? Thank you!

**Comment by yevh-berdnyk** [comment]
> @yevh-berdnyk could you please check e2e results above? Thank you!

Checked, E2E failures are not related to the PR

**Comment by pavloburykh** [comment]
@igor-sirotin @qfrank thanks for the PR. 

I have quickly tried to sync mobile (Android) with Desktop. 

Here what I get when scanning Desktop sync QR from mobile: 

photo_2024-08-06 19 14 28

Note, that mobile QA team is currently in the middle of release testing, so we will be able to get back to this PR only after we finish with release.

**Comment by qfrank** [comment]
> @igor-sirotin @qfrank thanks for the PR.
> 
> I have quickly tried to sync mobile (Android) with Desktop.
> 
> Here what I get when scanning Desktop sync QR from mobile:
> 
> photo_2024-08-06 19 14 28
> 
> Note, that mobile QA team is currently in the middle of release testing, so we will be able to get back to this PR only after we finish with release.

it should works now @pavloburykh

**Comment by pavloburykh** [comment]
> it should works now @pavloburykh

Thanks. We will get back to this PR after we finish with release testing.

**Comment by qfrank** [comment]
@igor-sirotin thank you for the rebasing ... but ... this was a dangerous force pushing ... which deleted my previous commit ...

**Comment by qfrank** [comment]
no worries, restored @igor-sirotin

**Comment by igor-sirotin** [comment]
> no worries, restored @igor-sirotin 

Oops, sorry for that. 
Thanks for the fix, @qfrank

**Review by flexsurfer — APPROVED** [review]

**Comment by pavloburykh** [comment]
@qfrank @igor-sirotin  while testing the PR I have faced random crashes 3 times during short period of time. 

Please take a look at the logs and see if it can be PR related. 

I see some `panic` in logcat. Although those crashes might be the same as reported here https://github.com/status-im/status-mobile/issues/21032 but might be not. 

There are no specific steps how to reproduce. Once it crashed in logout, other time just while I was logged in the app. 

```
08-13 16:06:22.830  9453     0 E Go      : panic: runtime error: invalid memory address or nil pointer dereference
08-13 16:06:22.831  9453  9685 E GoLog   : panic: runtime error: invalid memory address or nil pointer dereference
```

[crash_logcat_sync_pr.log.zip](https://github.com/user-attachments/files/16600130/crash_logcat_sync_pr.log.zip)
[sync_pr.zip](https://github.com/user-attachments/files/16600131/sync_pr.zip)

**Comment by pavloburykh** [comment]
> @qfrank @igor-sirotin while testing the PR I have faced random crashes 3 times during short period of time.
> 
> Please take a look at the logs and see if it can be PR related.
> 
> I see some `panic` in logcat. Although those crashes might be the same as reported here #21032 but might be not.
> 
> There are no specific steps how to reproduce. Once it crashed in logout, other time just while I was logged in the app.
> 
> ```
> 08-13 16:06:22.830  9453     0 E Go      : panic: runtime error: invalid memory address or nil pointer dereference
> 08-13 16:06:22.831  9453  9685 E GoLog   : panic: runtime error: invalid memory address or nil pointer dereference
> ```
> 
> [crash_logcat_sync_pr.log.zip](https://github.com/user-attachments/files/16600130/crash_logcat_sync_pr.log.zip) [sync_pr.zip](https://github.com/user-attachments/files/16600131/sync_pr.zip)

@qfrank @igor-sirotin besides this crash PR there are no issues from my side. So in case crashes are not related - we are ready for merge. 

@qfrank in case there will be lot of new commits in status go develop at the moment you will be bumping go version in mobile develop - ping me please, it will be better to re-run e2e once again to make sure those commits are not braking mobile. Thank you!

**Comment by igor-sirotin** [comment]
> Please take a look at the logs and see if it can be PR related.

@pavloburykh thanks for the testing!

```nim
08-12 15:41:58.567 17197 17197 F DEBUG   : backtrace:
08-12 15:41:58.567 17197 17197 F DEBUG   :       #00 pc 0000000000fdf488  /data/app/~~heFazm9W9Zudo1Ab2YrHIQ==/im.status.ethereum-c5G7ZRrWHM-ivAOKsfX69A==/lib/arm64/libgojni.so
```

This doesn't look like anything to me. i guess `libgojni.so` is the Go runtime?
@qfrank can you please take a closer look at the logs? Have you seen anything like this before?

**Comment by qfrank** [comment]
> > Please take a look at the logs and see if it can be PR related.
> 
> @pavloburykh thanks for the testing!
> 
> ```nim
> 08-12 15:41:58.567 17197 17197 F DEBUG   : backtrace:
> 08-12 15:41:58.567 17197 17197 F DEBUG   :       #00 pc 0000000000fdf488  /data/app/~~heFazm9W9Zudo1Ab2YrHIQ==/im.status.ethereum-c5G7ZRrWHM-ivAOKsfX69A==/lib/arm64/libgojni.so
> ```
> 
> This doesn't look like anything to me. i guess `libgojni.so` is the Go runtime? @qfrank can you please take a closer look at the logs? Have you seen anything like this before?

this is not the key information, I believe should be this one:

```
08-13 16:06:22.830  9453     0 E Go      : panic: runtime error: invalid memory address or nil pointer dereference
08-13 16:06:22.830  9453     0 E Go      : [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x7047bd9d80]
08-13 16:06:22.830  9453     0 E Go      : 
08-13 16:06:22.830  9453     0 E Go      : goroutine 1784 [running]:
08-13 16:06:22.830  9453     0 E Go      : github.com/status-im/status-go/services/wallet/async.(*Scheduler).Stop.func1()
08-13 16:06:22.830  9453     0 E Go      : 	github.com/status-im/status-go/services/wallet/async/scheduler.go:197 +0x20
08-13 16:06:22.830  9453     0 E Go      : created by github.com/status-im/status-go/services/wallet/async.(*Scheduler).Stop in goroutine 672
08-13 16:06:22.830  9453     0 E Go      : 	github.com/status-im/status-go/services/wallet/async/scheduler.go:196 +0x1b8
08-13 16:06:22.831  9453  9685 E GoLog   : panic: runtime error: invalid memory address or nil pointer dereference
```

There already exist the same [issue](https://github.com/status-im/status-mobile/issues/21032#issuecomment-2283928497) , it should not be relate to this PR, pls re-run e2e once again, thanks @pavloburykh  :)

**Comment by pavloburykh** [comment]
@qfrank @igor-sirotin e2e failures are not PR related. Let's merge it! Thank you.

**Comment by igor-sirotin** [comment]
@qfrank I'm not sure what happened, but the tests are failing now. Can you please take a look? Otherwise it's ready to merge.
All I did was rebase and use the merged to `develop` commit

**Pull request merged**
