### PR TITLE
Fix qr code and bootnode

### PR DESCRIPTION
**Pull request by cammellos**
Fixes: #7779

Just ordering of parameters.

status: ready

### CODE REVIEW

**Review by rasom — APPROVED** [review]

**Review by jeluard — APPROVED** [review]

**Comment by churik** [comment]
@cammellos there is no error when scanning anymore, however, "Save" button is inactive when scanning QR from https://gist.github.com/jacqueswww/3ddfc5ecfa09ecea702744ab15a2200d.
I found that it is because of two whitespaces are placed after the bootnode address.
Should it be fixed in QR code on https://gist.github.com/jacqueswww/3ddfc5ecfa09ecea702744ab15a2200d or we should trim the input, WDYT?

**Comment by cammellos** [comment]
@churik I will strip trailing whitespaces when scanning from qr, but for now only when from QR, is that ok?

**Comment by churik** [comment]
@cammellos I believe it is enough for now, agree

**Comment by cammellos** [comment]
@churik should be fixed now

**Comment by churik** [comment]
Can save bootnode when scan valid QR, paste valid bootnode from https://gist.github.com/jacqueswww/3ddfc5ecfa09ecea702744ab15a2200d when app is offline / online and the bootnodes are disabled / enabled.
Tested on IOS 11.4.1 and Android 8.0

**Pull request merged**
