### PR TITLE
Version bump

### PR DESCRIPTION
**Pull request by ibrkhalil**
bump status-go version

### CODE REVIEW

**Comment by ibrkhalil** [comment]
CC: @churik 
Here's the PR updating status-go version to add POKT changes.

**Comment by churik** [comment]
@ibrkhalil as far as I understand from discussion it is too early to test it?

**Comment by ibrkhalil** [comment]
> @ibrkhalil as far as I understand from discussion it is too early to test it?

Yup, I think it's more than a version bump.
Drafting this for now.

**Comment by ibrkhalil** [comment]
Rebased go and mobile branches
CC: @mariia-skrypnyk

**Comment by flexsurfer** [comment]
@ibrkhalil @mariia-skrypnyk still relevant?

**Pull request closed without merging**
