### PR TITLE
Allow user to be reinvited to the same group after leaving

### LINKED ISSUE #12079: If User joins a group chat and leaves it after, he won't receive a new invitation to the same group chat
# Bug Report

## Problem

If User1 receives an invitation to a group chat created by User2, joins and leaves it, then he won't receive re-invitation from User2 to the same group chat. It will not appear in either the Action Center or the Home screen.

#### Expected behavior

User can receive re-invitation after leaving group chat

#### Actual behavior

User cannot receive re-invitation

### Reproduction

User1:
- Add User2 to contacts
- Create a group chat with User2

User2:
- Navigate to the Activity center
- Join the group
- `Three dots` at the top right
- `Leave chat`

User1:
- `Three dots` at the top right
- `Group info`
- `Add members`
- Add User2

User2:
- Check Activity center and Home screen

### Additional Information

- Status version: Nightly 04/05
- Operating System: Android, iOS

### PR DESCRIPTION
**Pull request by Parveshdhull**
fixes https://github.com/status-im/status-react/issues/12079

### Summary:
This PR allows users to be reinvited to the same group after leaving. Group invitation is received in the activity center notification.

**status-go PR:**
https://github.com/status-im/status-go/pull/2431

### CODE REVIEW

**Review by flexsurfer — APPROVED** [review]

**Comment by qoqobolo** [comment]
Hi @Parveshdhull! Took the PR for testing.

FYI, the e2e fails are not PR related, so you can ignore them for now. 
Also, can you resolve conflicts, please? This is the reason why `status-github-bot` moves this to the Contributor column.
Thanks!

**Comment by qoqobolo** [comment]
@Parveshdhull 

### ISSUE 1: Can't add a user to contacts

Nothing happens when trying to add a user to contacts in any way (scanning QR, adding in the chat view, etc)

**Steps:**
1. Open the user profile (via QR or from a public chat)
2. Tap `Add to contacts`

**OS:** iOS, Android

https://user-images.githubusercontent.com/67952253/141973336-ddc20377-6ee9-4d6a-8623-7a8979df09f6.mp4

**Comment by Parveshdhull** [comment]
Hi @qoqobolo, can you please check this also in develop. Because, I tried previous build #4 and it works fine, this bug came after rebasing.

**Comment by qoqobolo** [comment]
@Parveshdhull yeah, I checked before reporting. On the latest develop it works fine.

**Comment by Parveshdhull** [comment]
Thanks, I will fix this issue 👍

> @Parveshdhull yeah, I checked before reporting. On the latest develop it works fine.

**Comment by Parveshdhull** [comment]
maybe status-go needs to be rebased too

**Comment by Parveshdhull** [comment]
@qoqobolo, Sorry about that 😅, Now I rebased status-go too and tested, and this fixed the issue. Thanks

**Comment by qoqobolo** [comment]
@Parveshdhull it's okay, thank you! :)

### ISSUE 2: No push notification if the user was reinvited to the group by their contact on Android

Also, this group appears in the activity center, but currently, group chat invitations _from contacts_ appear on the home screen. I believe re-invitations _from contacts_ should be displayed on the home screen as well. WDYT?

**Steps:**
1. UserA adds UserB to contacts
2. UserB adds UserA to contacts
3. UserA creates a group chat with UserB
4. UserB joins the group and leaves it
5. UserA re-invites UserB to the group

**Expected behavior:** 
- UserB receives a push notification
- the group chat appears on the home screen

**Actual behavior:**
- No PN
- the group chat appears in the activity center

**Comment by Parveshdhull** [comment]
ISSUE 2: fixed
@qoqobolo thanks for finding these great issues. 
Please let me know if I can improve anything else. Thanks

**Comment by qoqobolo** [comment]
@Parveshdhull thank you!
Yeah, we could add another improvement.

### ISSUE 3: Re-invites to group chats from contacts are not highlighted on the home screen as new chats

Based on https://github.com/status-im/status-react/pull/12654 they should be :)
Could you fix this too, please?

**Comment by Parveshdhull** [comment]
ISSUE 3: fixed
@qoqobolo yes, group re-invites looks more clear now 👍, Thanks

**Comment by qoqobolo** [comment]
Thanks @Parveshdhull !

Unfortunately, found a strange behavior

### ISSUE 4: Re-invitations come endlessly after declining an invitation to a group until the admin of the group re-logs in

If UserA declines the invitation from UserB, then UserA will receive re-invitations to the group while UserB is logged-in (presumably until the first relogin of UserB).

**Steps:**
1. UserB adds UserA to contacts and creates a group chat with UserA
2. UserA opens the Activity center, declines the invitation, and waits ~10-30 sec (UserB is logged-in)

User on the video just waits:

https://user-images.githubusercontent.com/67952253/142232204-c722acb9-cc0f-4731-afc6-91b6c6ed4a2b.mp4

**Comment by Parveshdhull** [comment]
ISSUE 4: fixed 👍

**Comment by qoqobolo** [comment]
@Parveshdhull Thanks for your hard work and patience in solving issues!
PR is ready to be merged.

**Pull request merged**
