### PR TITLE
[#6116] [desktop] escaping was moved to react-native-desktop side

### LINKED ISSUE #6116: Some characters such as < & > are URL encoded on desktop
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to use < & > and other characters.

### Description

Looks like a recent regression started URL encoding certain characters.

Eg typing `>` changes to `&gt;`

#### Expected behavior
Type `>` and see `>`

#### Actual behavior
Type `>` and see `&gt;`

### Reproduction
Type `>` and see `&gt;`

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: Desktop nightly
[comment]: # (Android or iOS.)
* Operating System: Mac desktop

### PR DESCRIPTION
**Pull request by rasom**
fix #6116

status: ready

### CODE REVIEW

**Review by vkjr — APPROVED** [review]

**Review by flexsurfer — APPROVED** [review]

**Review by vitvly — APPROVED** [review]

**Comment by churik** [comment]
@rasom can you please rebase it to latest nightly to prevent crash desktop-app on start (was fixed)?

**Comment by rasom** [comment]
@churik done

**Comment by churik** [comment]
@rasom once more, please

**Comment by rasom** [comment]
@churik done

**Comment by rasom** [comment]
^ @churik @SlizkovaGanna

**Comment by SlizkovaGanna** [comment]
Failed tests checked - one of the issues is already reported as a bug - https://github.com/status-im/status-react/issues/5899
The second one is invalid.

All characters are displayed correctly on desktop MacOs 10.13.4, iOS 12.0 and Android 7.0 in all combinations.

**Pull request merged**
