### PR TITLE
[Fixes #6825] Do not open settings as a modal

### LINKED ISSUE #6825: Unable to manage assets in wallet
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Unable to enable/disable assets lists in wallet, nothing happens when trying to open manage assets list 

#### Expected behavior
Assets list with checkboxes is shown 

#### Actual behavior
User stays in the wallet, assets list is not shown

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Create an account or recover an existing one
- Navigate to wallet and set up it if needed
- Click 3 dots button in the upper right corner
- Click Manage Assets

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.3 (12790); node 27700aa2 (Nov 21 nightly build)
* Operating System: Android, iOS

### PR DESCRIPTION
**Pull request by jeluard**
fixes #6825

### Steps to test:
- Open Status
- Open wallet / settings / manage assets

status: ready

### CODE REVIEW

**Review by yenda — APPROVED** [review]

**Comment by antdanchenko** [comment]
@jeluard  `test_manage_assets` passed, so the fix works, the fastest fix I had ever seen, thanks!

**Review by dmitryn — APPROVED** [review]

**Comment by goranjovic** [comment]
@jeluard what was the cause of the original bug?

**Comment by jeluard** [comment]
@goranjovic An experiment that leaked into my PR .. :sweat_smile:

**Comment by goranjovic** [comment]
@jeluard I meant, how did making this screen non-modal change things?

**Comment by jeluard** [comment]
@goranjovic AFAIK it wasn't modal in the first place

**Pull request merged**
