### PR TITLE
Feature/console suggestions and execution

### PR DESCRIPTION
**Pull request by adrian-tiberius**
Implements console message handling - treats text messages as js command code.

### CODE REVIEW

**Comment by rasom** [comment]
It looks and works much better than `!js` command :)

The only missing thing that i've found is that the previous message isn't shown in the suggestions area.

**Comment by adrian-tiberius** [comment]
I disabled the showing of suggestions on empty input, because we would get into the same situation like the js command where we couldn't see output of previous command.
I added instead the last message as a suggestion for starting to type the last command.

**Comment by jarradh** [comment]
good compromise

**Comment by rasom** [comment]
Looks great, @adrian-tiberius can you please squash commits?

**Comment by adrian-tiberius** [comment]
done

**Pull request merged**
