### PR TITLE
Colours refactoring

### LINKED ISSUE #2146: Create a uniform color palette
### User Story

As a developer, I want to have a uniform color palette so I can quickly and accurately translate designs into real screens, without second guessing what colors to use.

As a user, I want to have a visually pleasing and consistent experience with a few deliberately chosen colors.

### Description

*Type*: Feature

*Summary*: A deliberately chosen set of colors with meaningful names that the whole app can use. A primary, secondary and teritiary palette.

#### Expected behavior
Something like this: 
image
https://ustyle.guide/brand/colours.html

#### Actual behavior
I extracted all the colors we use from the `style.cljs` namespace. We surely have more and do things in an even more ad hoc manner in some other namespaces, but this is the closest thing we have to a global color selection right now.

image
https://jsfiddle.net/nvgmqobp/5/embedded/result/

#### Pieces of work

- [ ] Ensure all colors we use are defined in styles.cljs
- [ ] Reduce the ones we already have somewhat so we don't have 11 shades of grey
- [ ] Design: Make a color palette of expected colors to use with meaningful names
- [ ] Consistency: Decide on hex vs rgb and hex8 vs rgba, as well as rules for applying opacity etc

### PR DESCRIPTION
**Pull request by flexsurfer**
Colours refactoring

Fixes #2146

### CODE REVIEW

**Review by goranjovic — APPROVED** [review]

**Review by dmitryn — APPROVED** [review]

**Comment by denis-sharypin** [comment]
@flexsurfer  some minor changes

**Comment by lukaszfryc** [comment]
@flexsurfer could you apply Denis' suggestions https://github.com/status-im/status-react/pull/6160#issuecomment-427750268?

**Comment by flexsurfer** [comment]
@lukaszfryc applied

**Comment by denis-sharypin** [comment]
@flexsurfer Thanks! Looks good to me

**Comment by lukaszfryc** [comment]
@flexsurfer all looks good for me apart from outgoing message on desktop. It's hardly readable: 



Let's make it the same as on mobile.

**Comment by flexsurfer** [comment]
@lukaszfryc good catch, thanks

**Comment by flexsurfer** [comment]
image

**Comment by lukaszfryc** [comment]
Perfect! 👍

**Pull request merged**
