### PR TITLE
Dont kill task worker on exceptions

### LINKED ISSUE #6114: Missing messages and chats after quitting and re-opening
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want messages to not vanish so that I can read them :).

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

Every day I've been chatting a lot with Status Desktop Mac in 1-1 and public chats, but after quitting and re-opening the app I've seen many messages vanish.

Sometimes I still see the chat channel (eg #status-desktop) but messages are removed. Sometimes all but 1 message is removed, other times there are seemingly random messages removed.

Other times the chat channel is gone too.

So far I haven't been able to notice a pattern.

It has happened both when I quit for the night, then install Status desktop in the morning.
Also happens when I quit for 20 minutes then re-open.

5 other people have reported this on Slack.

**UPDATE**:  This is also happening on mobile

#### Expected behavior
Visible message remain in the app.

#### Actual behavior
Messages vanish.

### Reproduction

I can't reliably repro. But try talking lots. Quitting. Then re-open the app.

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: Nightlies for past few weeks
[comment]: # (Android or iOS.)
* Operating System: Mac + iOS + Android

### PR DESCRIPTION
**Pull request by cammellos**
fixes: #6114 
The async worker was chocking at the first exception, so any error in storing stuff on the database would kill the worker and no more saving to the database until login/logout.

This simply make sure exceptions are caught  so that the behavior is solid, the issues that caused the erros will be fixed separately.

### Testing step

Replicate https://github.com/status-im/status-react/issues/5204#issuecomment-428270354 or #6114 
Open a public chat, login/logout

With the old build that public chat is not there.
With the new build the public chat should be there.

status: ready

### CODE REVIEW

**Review by janherich — APPROVED** [review]

**Review by flexsurfer — APPROVED** [review]

**Review by yenda — APPROVED** [review]

**Review by mandrigin — APPROVED** [review]

**Comment by Serhy** [comment]
@cammellos with the changes made here and builds in the https://github.com/status-im/status-react/pull/6236#issuecomment-428500861:
1) On Android 7, 6.0.1, iOS 12 - I don't see the `transport.topic` error (https://github.com/status-im/status-react/issues/6114#issuecomment-428295076) and after the step when it occurs in develop - all further history saved fine! 
2) However on desktop issue still reproducible - exact steps like in the https://github.com/status-im/status-react/issues/6114#issuecomment-428295076 still reproducible: `transport.topic` appears when I add a contact and further history is not saved. 
Note: for desktop I upgraded the app and both existing account which had an issue with one contact and a new account - still have vanished chats/messages and tranport.topic error.

So it's still an issue for desktop.

**Comment by cammellos** [comment]
@Serhy thanks for testing, indeed it seems in desktop is still happening, I'll look into it,
easier repro steps:
1) Create account A on device 1
2) Create account A on device 2
3) Create account B on  device 3
4) Add B as a contact from device 2
5) Add A as a contact from device 3
6) Add B as a contact from device 1

**Comment by cammellos** [comment]
@Serhy it should be fixed for desktop in the new builds, thanks!

**Comment by Serhy** [comment]
Looks good to me! 
No `transport.topic` error appears anymore on Desktop and Mobile app and history saved fine after re-login!
The 'Add to contacts' option still kept on account which added from another device, but it's another issue.
This PR already solves #5204 and, potentially, #6114 too (as it was one of the reasons that likely happened on app side when exception raised)

**Comment by cammellos** [comment]
@Serhy This PR solves neither of those problems :)
What it fixes is that if one of those two errors occurs, it will keep saving stuff in the database, which was the biggest issue (if you check the logs, the topic error is still there).
Those issue will be fixed separately (they are due to having multiple devices).

**Comment by cammellos** [comment]
actually, I misread, fixes #6114 , but not the other, sorry

**Pull request merged**
