### PR TITLE
messages, android: fix "No automatic scroll to cursor location for long messages #676"

### LINKED ISSUE #676: No automatic scroll to cursor location for long messages
When a user types a long message, there is no automatic scroll to the cursor location (so that the focus remains on the text just typed).

https://instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/83

### PR DESCRIPTION
**Pull request by viebel**
Fixes #676

### CODE REVIEW

**Comment by viebel** [comment]
Listening to `onChange` instead of `onContentSizeChange` (See https://facebook.github.io/react-native/docs/textinput.html).

I have tested on Android.
Not tested on iOS yet.

**Comment by jarradh** [comment]
What about facebook/react-native#6552

**Comment by viebel** [comment]
@jarradh Do you think we should be concerned by the height of the `textinput` for text not entered via keyboard?  In that case, we would need to catch the two events `onChange` and `onContentSizeChange` since for the moment `onContentSizeChange is buggy on Android. 
I could try to test against latest react-native - but I'm not sure it worth it.

By the way, I have tested my changes on iOS - and it works fine with the handler change.

**Comment by alwx** [comment]
First of all, yes, we should care about all possible text changes, because we have an emoji picker, and this commit breaks the ability of input to be resized correctly in the case you select an emoji.
Secondly, the code style is wrong.

**Pull request closed without merging**
