### PR TITLE
fix the last message in chat is not tappable if it's close to the composer

### LINKED ISSUE #20210: The last message in chat is not tappable if it's close to the composer
# Bug Report

## Problem 
[comment]: # (A problem description)

#### Expected behavior
All the messages in chat can be tapped and long pressed

#### Actual behavior
Context menu is not shown when long tapping the last message. Also it's not possible to open a link or user's profile form the last message 

https://github.com/status-im/status-mobile/assets/29711298/89c16e6a-1773-4275-81bc-2e383d15eac9

### Reproduction

1. Open any chat (1-1, group or community channel)
2. Send couple of messages in a row from one user
3. Long press or tap the last one which is near the composer

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by Parveshdhull**
fixes https://github.com/status-im/status-mobile/issues/20210

status: ready

### CODE REVIEW

**Review by flexsurfer — APPROVED** [review]

**Comment by yevh-berdnyk** [comment]
> ## 87% of end-end tests have passed

Hi @Parveshdhull, thanks for the quick fix! E2E failures are not PR related

**Comment by yevh-berdnyk** [comment]
@Parveshdhull the issue is fixed on Android! But I still can reproduce it on iOS, tried with 1-1 chats and community channels.
Checked on iPhone 14 Pro, iOS 17.2.1

**Comment by Parveshdhull** [comment]
Thank you @yevh-berdnyk for finding this issue. Should be fixed now

**Comment by yevh-berdnyk** [comment]
> Thank you @yevh-berdnyk for finding this issue. Should be fixed now

Thanks a lot, it's fixed!

**Pull request merged**
