### PR TITLE
chore_: update status-go

### PR DESCRIPTION
**Pull request by kaichaosun**
### Summary

**Changes**: This PR reset the epoch (next sending time for unacknowledged messages) in MVDS if receiver becomes online. When getting a user status (from receiver) is automatic, alwaysOnline or inactive, it will trigger this logic, and resend the message for ack in a few seconds.

**Status-go PR**: https://github.com/status-im/status-go/pull/5349

**Risk**: low

**How to test**:
- sanity check e2e test is not broken
- database should have a new index idx_mvds_states_peer_id
- business logic
  - add contacts between two users, say alice and bob
  - make bob offline
  - alice keep sending messages, and messages is mark as sent (not acknowledged) 
  - wait for 5 minutes
  - make bob online
  - alice should see the sent messages become acknowledged in a few seconds (less than 1 minute).

#### Platforms

- Android
- iOS
- macOS
- Linux
- Windows

##### Functional

- 1-1 chats
- public chats
- group chats
- wallet / transactions
- dapps / app browsing
- account recovery
- new account
- user profile updates
- networks
- mailservers
- fleet
- bootnodes

##### Non-functional

- battery performance
- CPU performance / speed of the app
- network consumption

### Steps to test

- Open Status
- ...
- Step 3, etc.

### Before and after screenshots comparison

| Figma (if available) | iOS (if available)    | Android (if available)
| --- | --- | --- |
| Please embed Image/Video here of the before and after.  | Please embed Image/Video here of the before and after.  | Please embed Image/Video here of the before and after. |

status: ready

### CODE REVIEW

**Comment by pavloburykh** [comment]
Another question is - does this logic affects only 1-1 chats or group chats/community channels as well? 

I think we have an issue related to community channels

### ISSUE 1 Messages are displayed greyed out (unacknowledged?) for sender

**Steps:** 

1. Sender is online
2. Sender opens community channel
3. Sender sends messages in community channel
4. See how sent messages look like

**Actual result:** messages stay greyed out. In fac messages are delivered to community channel and can be seen by other channel members. 

[Status-debug-logs - 2024-06-24T123255.744.zip](https://github.com/user-attachments/files/15953056/Status-debug-logs.-.2024-06-24T123255.744.zip)

https://github.com/status-im/status-desktop/assets/97245802/0741b4f2-630a-413b-a302-3684304804d6

**Comment by pavloburykh** [comment]
@kaichaosun thank you for the PR. 

I have couple of questions regarding the feature, would appreciate your answers. 

Could you please clarify, what is meant by acknowledged and unacknowledged messages? 

As far as I understand (from UI perspective), messages become acknowledged once receiver of these messages comes back online, is this correct? 

What I now see from user perspective: unacknowledged messages are displayed "greyed out" until receiver comes back online (see the video below). I am not sure such UI behaviour is expected. From sender's perspective it looks a little bit confusing to see messages greyed out, while sender is online and message is in fact sent to the receiver (it is just not Delivered because receiver is offline). Maybe here we need some input from design team or mobile devs cc @ilmotta . 


https://github.com/status-im/status-desktop/assets/97245802/9b48ff47-32ab-4453-a05d-8f0f8c78424e

**Comment by pavloburykh** [comment]
Another question is - does this logic affects only 1-1 chats or group chats/community channels as well? 

I think we have an issue related to community channels

### ISSUE 1 Messages are displayed greyed out (unacknowledged?) for sender in community channel

**Steps:** 

1. Sender is online
2. Sender opens community channel
3. Sender sends messages in community channel
4. See how sent messages look like

**Actual result:** messages stay greyed out. In fac messages are delivered to community channel and can be seen by other channel members. 

[Status-debug-logs - 2024-06-24T123255.744.zip](https://github.com/user-attachments/files/15953056/Status-debug-logs.-.2024-06-24T123255.744.zip)

https://github.com/status-im/status-desktop/assets/97245802/0741b4f2-630a-413b-a302-3684304804d6

**Comment by kaichaosun** [comment]
@pavloburykh thanks for sharing your result!

> what is meant by acknowledged and unacknowledged messages?

If click on a message, it should show something like `sent` or `delivered`, here acknowledged means delivered, sorry for not making it clear before.

> unacknowledged messages are displayed "greyed out" until receiver comes back online (see the video below). I am not sure such UI behaviour is expected.

The outgoing messages should be marked as `sent` and not stay in "gray" after 5 to 10 seconds. Let me know if this is not the case for your test, or this behavior is not suitable for our users. BTW, this behavior is introduced in https://github.com/status-im/status-go/pull/5217 and more detail in there.

> Messages are displayed greyed out (unacknowledged?) for sender in community channel

The messages should also be marked as `sent` and not stay in gray after 5 to 10 seconds if you have good connection with store node, since we mark it as `sent` when successfully queried the message from store node.
The community chat seems no `delivered` state, I haven't tested mobile community chat, please correct me if I'm wrong.

**Comment by pavloburykh** [comment]
@kaichaosun thanx for the answers.

> The outgoing messages should be marked as sent and not stay in "gray" after 5 to 10 seconds. Let me know if this is not the case for your test, or this behavior is not suitable for our users. 

On the video below you can see messages get stuck greyed out for more than 15 seconds sometimes. When I tested PR today morning a have faced grayed out state for more than a minute. I would say that even 10 or 15 seconds is too much from user perspective. 

Also, you can see that messages which have been in fact delivered to the Receiver are still displayed greyed out for some time on Sender's side which is also not expected I guess. 


https://github.com/status-im/status-mobile/assets/97245802/46c84431-6785-456d-b20b-988a82c8c359

> The community chat seems no delivered state, I haven't tested mobile community chat, please correct me if I'm wrong.

There is no Delivered state. But as you can see in [ISSUE 1](https://github.com/status-im/status-mobile/pull/20537#issuecomment-2186083047) all messages stuck in greyed out (Sending) state for Sender. And it seems to be a regression of this PR. Would appreciate if you can take a look at this.

**Comment by kaichaosun** [comment]
@pavloburykh I pushed a change to tuning the "gray" out period to 3~6 seconds.

> messages which have been in fact delivered to the Receiver are still displayed greyed out for some time on Sender's side which is also not expected I guess.

When receiver receiver a message, it will send another "ack" message to sender which takes a regular time for delivery.

> There is no Delivered state. But as you can see in https://github.com/status-im/status-mobile/pull/20537#issuecomment-2186083047 all messages stuck in greyed out (Sending) state for Sender. And it seems to be a regression of this PR.

I just tested community chat in my end, the message should works fine after tunning. There are scenarios that store node is in capacity or user has unhealthy connection with store node, it will affect "gray out" period, or may even stay in "gray" for a pretty long time. There are ongoing tasks to make a e2e acknowledgement for community chat, but it's not in the scope of this task.

Please review and let me know if there are issues, thanks for pointing out above improvement.

**Comment by pavloburykh** [comment]
> Please review and let me know if there are issues, thanks for pointing out above improvement.

@kaichaosun thank you! Looks better and ISSUE 1 is not reproducible. I think we can merge status go.

**Pull request closed without merging**
