### PR TITLE
[#7917] fix - Contacts are not synced between 0.11.0 and current nightly

### LINKED ISSUE #7917: Contacts are not synced between 0.11.0 and current nightly
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug
*Summary*: contact list is not synced if one device is using release 0.11.0 and second - current nightly.

#### Expected behavior
 public chats and contact are shown on Device B.
Also group chats and 1-1 chats are synced correctly.

#### Actual behavior
contacts are not synced.

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Device A: create account on 0.11.0 (tried on IOS), add contact
- Device B: restore the same account on PR build (tried Mac OS and IOS builds)
- Pair devices A and B
- Device A: tap on sync all

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: nightly 04/03/2019
* Operating System: all

#### Logs

Logs for device B:
[geth.log](https://github.com/status-im/status-react/files/3044118/geth.log)
[Status.log](https://github.com/status-im/status-react/files/3044121/Status.log)

### PR DESCRIPTION
**Pull request by bitsikka**
fixes #7917 

- tested with android-real with 0.11.0 as device A and iOS simulator as device B
- tested adding a single contact from user profile
- tested pressing "Sync all devices" in Profile -> Devices

status: ready

### CODE REVIEW

**Comment by churik** [comment]
Tested on IOS, it is working - waiting for reviews.

**Review by goranjovic — APPROVED** [review]

**Review by mandrigin — APPROVED** [review]

**Review by cammellos — CHANGES_REQUESTED** [review]
Not sure this is the right approach, conceptually is what we need to do, but  I'd rather not have this logic in this part of the codebase. I think a better approach is to have a different validation scheme for a syncmessage with contact (as effectively they have now diverged), and then handle the defaulting to `contact/added` in a different namespace (i.e `pairing`). Also, I'd rather not modify the actual message, but only when processing the contacts it should add it to the contact in the db, not on the message itself.

**Comment by bitsikka** [comment]
> Not sure this is the right approach, conceptually is what we need to do, but I'd rather not have this logic in this part of the codebase. I think a better approach is to have a different validation scheme for a syncmessage with contact (as effectively they have now diverged), and then handle the defaulting to `contact/added` in a different namespace (i.e `pairing`). Also, I'd rather not modify the actual message, but only when processing the contacts it should add it to the contact in the db, not on the message itself.

understood

going to see about that approach - an opportunity to dig into specs which are new to me

**Review by yenda — APPROVED** [review]

**Comment by bitsikka** [comment]
@yenda thanks for approving the latest changes but, but for some reason sometimes db spec validation via default interceptor is still failing :( and I'm encountering exception thrown because of it.

so maybe still WIP

I'm running into unrelated problem with my dev build/slowing down of system but I'm still investigating this issue with utmost prio

**Comment by bitsikka** [comment]
@yenda, @cammellos I'm pretty sure I got it in the latest update, please take a look when you get the time

**Comment by yenda** [comment]
@bitsikka nice work, @churik could you check?

**Comment by churik** [comment]
ofc, on it

**Review by cammellos — APPROVED** [review]

**Comment by churik** [comment]
Tested cases:

  | Initial sync of contacts | Adding contacts after pairing
-- | -- | --
Release 0.11 (Device1) -> PR build (Device2) | synced | appeared after adding on Device2
PR build (Device1) -> release 0.11 (Device2) | **not synced** | appeared after adding on Device2
PR build (Device1) -> PR build (Device2) | synced | appeared after adding on Device2

All other info (group, public, 1-1 chats, profile data) - is syncing between versions.

The only case that it is not working right now is when you have device with PR build on Device1 and second with release 0.11.0 on Device2, if you tap "Sync all" on Device1 -> contacts will not appeared on Device2. 
But If I'll add manually contact A on Device1, it is appearing on Device2.

As for me this case is not critical.
Probably good idea is to merge this PR and mention this in release notes, WDYT @rachelhamlin @annadanchenko ?

**Comment by bitsikka** [comment]
> The only case that it is not working right now is when you have device with PR build on Device1 and second with release 0.11.0 on Device2, if you tap "Sync all" on Device1 -> contacts will not appeared on Device2.
> But If I'll add manually contact A on Device1, it is appearing on Device2.

did not account for this; as I only thought about syncing to-> PR build; I can look at this now - should be different part of the code - an addition. Going to try to make it into this PR asap.

**Comment by annadanchenko** [comment]
>As for me this case is not critical.
Probably good idea is to merge this PR and mention this in release notes, WDYT @rachelhamlin @annadanchenko ?

@churik I think it's worth trying to fix in scope of this PR

**Comment by rachelhamlin** [comment]
Is this issue pertinent to 0.11.0 specifically, or any version difference? In any case, great if we can fix in this PR. Thanks @bitsikka.

**Comment by bitsikka** [comment]
@churik done!

@yenda / @cammellos there was a confusion in semantics of what `:pending?` in `<= 0.11.0` meant and what `contact.db/pending?` means after that (now after addition of system-tags), that was causing the syncing contacts from PR build -> 0.11.0 in particular to fail

**Comment by churik** [comment]
@bitsikka thank you for quick fix!
Last builds can't be made because of tests:
```
[2019-04-16T16:19:01.859Z] Testing status-im.test.sign-in.flow

[2019-04-16T16:19:01.859Z] INFO [status-im.node.core:174] - Node config:  {"ClusterConfig":{"Enabled":true,"Fleet":"eth.beta","BootNodes":["enode://436cc6f674928fdc9a9f7990f2944002b685d1c37f025c1be425185b5b1f0900feaf1ccc2a6130268f9901be4a7d252f37302c8335a2c1a62736e9232691cc3a@174.138.105.243:443","enode://43947863cfa5aad1178f482ac35a8ebb9116cded1c23f7f9af1a47badfc1ee7f0dd9ec0543417cc347225a6e47e46c6873f647559e43434596c54e17a4d3a1e4@47.52.74.140:443","enode://ebefab39b69bbbe64d8cd86be765b3be356d8c4b24660f65d493143a0c44f38c85a257300178f7845592a1b0332811542e9a58281c835babdd7535babb64efc1@35.202.99.224:443","enode://5395aab7833f1ecb671b59bf0521cf20224fe8162fc3d2675de4ee4d5636a75ec32d13268fc184df8d1ddfa803943906882da62a4df42d4fccf6d17808156a87@206.189.243.57:443"],"TrustedMailServers":["enode://7de99e4cb1b3523bd26ca212369540646607c721ad4f3e5c821ed9148150ce6ce2e72631723002210fac1fd52dfa8bbdf3555e05379af79515e1179da37cc3db@35.188.19.210:443","enode://015e22f6cd2b44c8a51bd7a23555e271e0759c7d7f52432719665a74966f2da456d28e154e836bee6092b4d686fe67e331655586c57b718be3997c1629d24167@35.226.21.19:443","enode://8a64b3c349a2e0ef4a32ea49609ed6eb3364be1110253c20adc17a3cebbc39a219e5d3e13b151c0eee5d8e0f9a8ba2cd026014e67b41a4ab7d1d5dd67ca27427@206.189.243.168:443","enode://531e252ec966b7e83f5538c19bf1cde7381cc7949026a6e499b6e998e695751aadf26d4c98d5a4eabfb7cefd31c3c88d600a775f14ed5781520a88ecd25da3c6@35.225.227.79:443","enode://c42f368a23fa98ee546fd247220759062323249ef657d26d357a777443aec04db1b29a3a22ef3e7c548e18493ddaf51a31b0aed6079bd6ebe5ae838fcfaf3a49@206.189.243.162:443","enode://7aa648d6e855950b2e3d3bf220c496e0cae4adfddef3e1e6062e6b177aec93bc6cdcf1282cb40d1656932ebfdd565729da440368d7c4da7dbd4d004b1ac02bf8@206.189.243.169:443"],"StaticNodes":["enode://a80eb084f6bf3f98bf6a492fd6ba3db636986b17643695f67f543115d93d69920fb72e349e0c617a01544764f09375bb85f452b9c750a892d01d0e627d9c251e@47.89.16.125:443","enode://552942cc4858073102a6bcd0df9fe4de6d9fc52ddf7363e8e0746eba21b0f98fb37e8270bc629f72cfe29e0b3522afaf51e309a05998736e2c0dad5288991148@130.211.215.133:443"],"RendezvousNodes":["/ip4/206.189.243.57/tcp/30703/ethv4/16Uiu2HAmLqTXuY4Sb6G28HNooaFUXUKzpzKXCcgyJxgaEE2i5vnf","/ip4/174.138.105.243/tcp/30703/ethv4/16Uiu2HAmRHPzF3rQg55PgYPcQkyvPVH9n2hWsYPhUJBZ6kVjJgdV"]},"DataDir":"/ethereum/mainnet_rpc","Rendezvous":true,"WhisperConfig":{"Enabled":true,"LightClient":true,"MinimumPoW":0.001,"EnableNTPSync":true},"LogEnabled":false,"RequireTopics":{"whisper":{"Min":2,"Max":2}},"UpstreamConfig":{"Enabled":true,"URL":"https://mainnet.infura.io/z6GCTmjdP3FETEJmMBI4"},"NetworkId":1,"Name":"StatusIM","NoDiscovery":false,"ShhextConfig":{"BackupDisabledDataDir":null,"InstallationID":"618ec020-13c8-5505-8aa6-9c5444317e7f","MaxMessageDeliveryAttempts":6,"MailServerConfirmations":false,"PFSEnabled":true}}

[2019-04-16T16:19:01.859Z] INFO [status-im.node.core:174] - Node config:  {"Name":"StatusIM","ShhextConfig":{"BackupDisabledDataDir":null},"PFSEnabled":false,"NoDiscovery":true,"LogEnabled":false}

[2019-04-16T16:19:01.859Z] INFO [status-im.node.core:174] - Node config:  {"Name":"StatusIM","ShhextConfig":{"BackupDisabledDataDir":null},"PFSEnabled":false,"NoDiscovery":true,"LogEnabled":false}

[2019-04-16T16:19:01.859Z] DEBUG [status-im.contact-code.core:63] - initializing contact-code
```
Can you take a look what is going on there?

**Comment by bitsikka** [comment]
> @bitsikka thank you for quick fix!
> Last builds can't be made because of tests:
> 
> ```
> [2019-04-16T16:19:01.859Z] Testing status-im.test.sign-in.flow
> 
> [2019-04-16T16:19:01.859Z] INFO [status-im.node.core:174] - Node config:  {"ClusterConfig":{"Enabled":true,"Fleet":"eth.beta","BootNodes":["enode://436cc6f674928fdc9a9f7990f2944002b685d1c37f025c1be425185b5b1f0900feaf1ccc2a6130268f9901be4a7d252f37302c8335a2c1a62736e9232691cc3a@174.138.105.243:443","enode://43947863cfa5aad1178f482ac35a8ebb9116cded1c23f7f9af1a47badfc1ee7f0dd9ec0543417cc347225a6e47e46c6873f647559e43434596c54e17a4d3a1e4@47.52.74.140:443","enode://ebefab39b69bbbe64d8cd86be765b3be356d8c4b24660f65d493143a0c44f38c85a257300178f7845592a1b0332811542e9a58281c835babdd7535babb64efc1@35.202.99.224:443","enode://5395aab7833f1ecb671b59bf0521cf20224fe8162fc3d2675de4ee4d5636a75ec32d13268fc184df8d1ddfa803943906882da62a4df42d4fccf6d17808156a87@206.189.243.57:443"],"TrustedMailServers":["enode://7de99e4cb1b3523bd26ca212369540646607c721ad4f3e5c821ed9148150ce6ce2e72631723002210fac1fd52dfa8bbdf3555e05379af79515e1179da37cc3db@35.188.19.210:443","enode://015e22f6cd2b44c8a51bd7a23555e271e0759c7d7f52432719665a74966f2da456d28e154e836bee6092b4d686fe67e331655586c57b718be3997c1629d24167@35.226.21.19:443","enode://8a64b3c349a2e0ef4a32ea49609ed6eb3364be1110253c20adc17a3cebbc39a219e5d3e13b151c0eee5d8e0f9a8ba2cd026014e67b41a4ab7d1d5dd67ca27427@206.189.243.168:443","enode://531e252ec966b7e83f5538c19bf1cde7381cc7949026a6e499b6e998e695751aadf26d4c98d5a4eabfb7cefd31c3c88d600a775f14ed5781520a88ecd25da3c6@35.225.227.79:443","enode://c42f368a23fa98ee546fd247220759062323249ef657d26d357a777443aec04db1b29a3a22ef3e7c548e18493ddaf51a31b0aed6079bd6ebe5ae838fcfaf3a49@206.189.243.162:443","enode://7aa648d6e855950b2e3d3bf220c496e0cae4adfddef3e1e6062e6b177aec93bc6cdcf1282cb40d1656932ebfdd565729da440368d7c4da7dbd4d004b1ac02bf8@206.189.243.169:443"],"StaticNodes":["enode://a80eb084f6bf3f98bf6a492fd6ba3db636986b17643695f67f543115d93d69920fb72e349e0c617a01544764f09375bb85f452b9c750a892d01d0e627d9c251e@47.89.16.125:443","enode://552942cc4858073102a6bcd0df9fe4de6d9fc52ddf7363e8e0746eba21b0f98fb37e8270bc629f72cfe29e0b3522afaf51e309a05998736e2c0dad5288991148@130.211.215.133:443"],"RendezvousNodes":["/ip4/206.189.243.57/tcp/30703/ethv4/16Uiu2HAmLqTXuY4Sb6G28HNooaFUXUKzpzKXCcgyJxgaEE2i5vnf","/ip4/174.138.105.243/tcp/30703/ethv4/16Uiu2HAmRHPzF3rQg55PgYPcQkyvPVH9n2hWsYPhUJBZ6kVjJgdV"]},"DataDir":"/ethereum/mainnet_rpc","Rendezvous":true,"WhisperConfig":{"Enabled":true,"LightClient":true,"MinimumPoW":0.001,"EnableNTPSync":true},"LogEnabled":false,"RequireTopics":{"whisper":{"Min":2,"Max":2}},"UpstreamConfig":{"Enabled":true,"URL":"https://mainnet.infura.io/z6GCTmjdP3FETEJmMBI4"},"NetworkId":1,"Name":"StatusIM","NoDiscovery":false,"ShhextConfig":{"BackupDisabledDataDir":null,"InstallationID":"618ec020-13c8-5505-8aa6-9c5444317e7f","MaxMessageDeliveryAttempts":6,"MailServerConfirmations":false,"PFSEnabled":true}}
> 
> [2019-04-16T16:19:01.859Z] INFO [status-im.node.core:174] - Node config:  {"Name":"StatusIM","ShhextConfig":{"BackupDisabledDataDir":null},"PFSEnabled":false,"NoDiscovery":true,"LogEnabled":false}
> 
> [2019-04-16T16:19:01.859Z] INFO [status-im.node.core:174] - Node config:  {"Name":"StatusIM","ShhextConfig":{"BackupDisabledDataDir":null},"PFSEnabled":false,"NoDiscovery":true,"LogEnabled":false}
> 
> [2019-04-16T16:19:01.859Z] DEBUG [status-im.contact-code.core:63] - initializing contact-code
> ```
> Can you take a look what is going on there?

on it

**Comment by bitsikka** [comment]
@churik done!

**Comment by churik** [comment]
Rechecked all cases, all is working now.

Thank you again @bitsikka for your help!

**Pull request merged**
