### PR TITLE
[#13933] Fix activity notification delition on message delition

### LINKED ISSUE #13933: Unread indicator remains on activity centre if message was removed by sender
If sending and then removing the very first message to a user without opening activity center by the receiver, the activity center unread indicator remains despite that there are no unread messages. It also remains after re-login.

**Preconditions:** User A and User B are not contacts and do not have any active 1-1 chats yet
**Steps:** 
1. Send message by User A to User B
2. User A deletes the sent message
3. Pay attention if User B has unread indicator on activity center 
4. Open activity center by User B

**Actual result:** unread indicator remains for User B although activity center is empty. Another issue is that in such case another messages sent by User A will not trigger unread indicator in activity center for User B. 

https://user-images.githubusercontent.com/97245802/188431015-8b88de9b-c18c-461e-b707-5fb27876a2b4.mp4

**Expected result:** no unread indicator

### PR DESCRIPTION
**Pull request by rasom**
fix #13933

status: ready

### CODE REVIEW

**Review by flexsurfer — APPROVED** [review]

**Review by briansztamfater — APPROVED** [review]

**Comment by pavloburykh** [comment]
@rasom thanx for the PR. Please take a look at the following issue

### ISSUE 1 Wallets and assets are disappearing after re-login

Have not reproduced the bug in latest nightly, so considering it PR related. 

**Steps:** 
1. Restore/login multiaccount
2. Go to wallet tab, make sure that all wallets (assets) are displayed
3. Perform re-login
4. Go to wallet tab
5. See if wallets and assets are still displayed

**Actual result:**  Wallets and assets disappeared

**Expected result:** all existing wallets and assets are displayed


https://user-images.githubusercontent.com/97245802/189923863-62e6b29b-ec6f-4277-91f7-e3772628d0ca.mp4

[geth.log](https://github.com/status-im/status-mobile/files/9557889/geth.log)

**Comment by rasom** [comment]
@pavloburykh it can't be related to this PR, that's some random regression on status-go side

**Comment by rasom** [comment]
I mean, that's all it has https://github.com/status-im/status-go/pull/2854/files 

I will rebase both pull requests, maybe it is already fixed in develop

**Comment by pavloburykh** [comment]
@rasom thanx, ISSUE 1 if fixed after rebasing. Please, take a look at the following case and tell if we can handle it. 

### ISSUE 2 Deleting last message results in deleting chat from activity center even if there were some other previous unread messages

**Preconditions:** User A and User B are not contacts and do not have any active 1-1 chats yet

**Steps:**
1. Send >1 messages by User A to User B
2. User A deletes the last of sent messages. Rest of the unread messages remain undeleted
3. Pay attention if User B has unread indicator on activity center
4. Open activity center by User B and check if chat with the rest unread new messages still remains there

**Actual result:**
No unread indicator and chat is deleted from activity center. 

**Expected result:** 
Chat should should remain in activity center as only the last message has been deleted by sender and there are other unread and undeleted messages. 

https://user-images.githubusercontent.com/97245802/189948938-e1f15728-22a3-44e4-bf5f-ba9ed5a1d9ae.mp4

**Comment by rasom** [comment]
@pavloburykh issue 2 should be fixed now

**Comment by pavloburykh** [comment]
> 

@rasom hi! still reproducing ISSUE 2

**Comment by pavloburykh** [comment]
@rasom than[ for the fix. Failed tests are not related to the PR. Ready for merge.

**Pull request merged**
