### PR TITLE
Bug/from missing group #1448

### PR DESCRIPTION
**Pull request by goranjovic**
#1448 

### Summary:

Send commands sent within a group chat were erroneously not recognized as group chat messages if group chat was not open in the recipients app when message was received. As the effect, those send commands were not formatted as for a group chat, specifically "to RECIPIENT_NAME" part in the second line was missing.

This PR contains a workaround to the immediate issue. Instead of using `group-chat` flag, the code now checks if a message was created in a group chat by checking the existence of `group-id`. 

As a general solution to these kinds of problems, I recommend that we check the entire life cycle (or flow?) of the most important entities in the app, the first one being a message of course, e.g. what field is added/changed/removed and in what step.

### Steps to test:
See #1448 

status: ready

### CODE REVIEW

**Review by janherich — APPROVED** [review]

**Review by flexsurfer — APPROVED** [review]

**Comment by goranjovic** [comment]
Squashed

**Comment by goranjovic** [comment]
Updated to cover the fix for #1741

**Comment by rasom** [comment]
@goranjovic, please squash commits

**Comment by goranjovic** [comment]
@rasom squashed

**Pull request merged**
