### PR TITLE
Update decimals and token names

### LINKED ISSUE #4673: Incorrect decimals values for Populous, Veros, Cofoundit and Ripio Credit Network tokens
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: 28 of 88 used tokens have inconsistencies in names, symbols or decimals after comparing data from [tokens.cljs](https://github.com/status-im/status-react/blob/develop/src/status_im/utils/ethereum/tokens.cljs) with data from http://api.ethplorer.io/.

## Incorrect decimals values:
- address 0xd4fa1460f537bb9085d22c7bccb5dd450ef28e3a (Populous): 
decimals value 18, expected 8
- address 0xedbaf3c5100302dcdda53269322f3730b1f0416d (Veros): 
decimals value 18, expected 5
- address 0xf970b8e36e23f7fc3fd752eea86f8be8d83375a6 (Ripio Credit Network Token):
decimals value 9, expected 18
- address 0x12fef5e57bf45873cd9b62e9dbd7bfb99e32d73e (Cofoundit):
 decimals value 2, expected 18

## Incorrect names and symbols:
- address 0xd26114cd6EE289AccF82350c8d8487fedB8A0C07:
token name 'OmiseGo', expected 'OMGToken'
- address 0xd4fa1460f537bb9085d22c7bccb5dd450ef28e3a: 
token name 'Populous', expected 'Populous Platform'
- address 0xe94327d07fc17907b4db788e5adf2ed424addff6:
 token name 'Augur', expected 'Reputation'
- address 0xB97048628DB6B661D4C2aA833e95Dbe1A905B280:
token name 'TenXPay', expected 'TenX Pay Token'
- address 0xedbaf3c5100302dcdda53269322f3730b1f0416d: 
symbol 'VERI', expected 'VRS', 
token name 'Veros', expected 'VEROS'
- address 0xe0b7927c4af23765cb51314a0e0521a9645f0e2a:
token name 'DGD', expected 'Digix DAO'
- address 0x5af2be193a6abca9c8817001f45744777db30756:
symbol 'ETHOS', expected 'BQX', 
token name 'Ethos', expected 'Bitquence'
- address 0x744d70fdbe2ba4cf95131626614a1763df805b9e:
token name 'Status Network Token', expected 'Status Network'
- address 0x9B11EFcAAA1890f6eE52C6bB7CF8153aC5d74139: 
symbol 'ATMChain', expected 'ATM'
- address 0xEF68e7C694F40c8202821eDF525dE3782458639f:
token name 'LoopringCoin', expected 'loopring'
- address 0x7A41e0517a5ecA4FdbC7FbebA4D4c47B9fF6DC63:
 token name 'Zeus Shield Token', expected 'Zeus Shield Coin'
- address 0x0cf0ee63788a0849fe5297f3407f701e122cc023:
 token name 'Streamr DATAcoin', expected 'DATAcoin'
- address 0x96A65609a7B84E8842732DEB08f56C3E21aC6f8a:
 symbol 'Centra', expected 'CTR', 
token name 'Centra Token', expected 'Centra'
- address 0x12b19d3e2ccc14da04fae33e63652ce469b3f2fd:
 token name 'GRID+ Token', expected 'GRID Token'
- address 0x0f5d2fb29fb7d3cfee444a200298f468908cc942:
 token name 'Decentraland MANA', expected 'Decentraland'
- address 0x48f775efbe4f5ece6e0df2f7b5932df56823b990:
 token name 'R Token', expected 'R token'
- address 0xaf30d2a7e90d7dc361c8c4585e9bb7d2f6f15bc7:
 token name 'FirstBlood Token', expected 'Firstblood'
- address 0x08d32b0da63e2C3bcF8019c9c5d849d7a9d791e6:
 symbol 'DCN', expected '٨'
- address 0x29d75277ac7f0335b2165d0895e8725cbf658d73:
 token name 'BitDice', expected 'BitDice CSNO'
- address 0x0d88ed6e74bbfd96b831231638b66c05571e824f:
 token name 'AVT', expected 'AVENTUS'
- address 0x6531f133e6deebe7f2dce5a0441aa7ef330b4e53:
 token name 'TIME', expected 'Chronobank TIME'
- address 0x006BeA43Baa3f7A6f765F14f10A1a1b08334EF45:
 token name 'STOX', expected 'Stox'
- address 0x2c974b2d0ba1716e644c1fc59982a89ddd2ff724:
 token name 'Vibe', expected 'VIB'
- address 0x7728dFEF5aBd468669EB7f9b48A7f70a501eD29D:
 token name 'PRG', expected 'ParagonCoin'
- address 0x6c2adc2073994fb2ccc5032cc2906fa221e9b391:
 token name 'Delphy', expected 'Delphy Token'
- address 0x9af4f26941677c706cfecf6d3379ff01bb85d5ab:
 token name 'DomRaider Token', expected 'Domraider'
- address 0x2e071D2966Aa7D8dECB1005885bA1977D6038A65:
 token name 'Dice', expected 'DICE'

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Check token info by address in http://api.ethplorer.io
i.e `http://api.ethplorer.io/getTokenInfo/0x2c974b2d0ba1716e644c1fc59982a89ddd2ff724?apiKey=freekey`

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: develop

<blockquote></blockquote>
<blockquote></blockquote>

### PR DESCRIPTION
**Pull request by cammellos**
fixes #4673

### Summary:

Updated token names,
some of the symbols as well & decimals.

### Review notes (optional):

- Some symbols have been changed 
- A simbol `DENTACOIN` went from `DCN` to `٨`

status: ready

### CODE REVIEW

**Review by goranjovic — APPROVED** [review]

**Comment by jeluard** [comment]
@cammellos What was the source of authority (data) for those changes?
@goranjovic Shall we have a separate issue to rely directly on contract methods?

**Comment by cammellos** [comment]
@jeluard it's described in the issue https://github.com/status-im/status-react/issues/4673 , other than that not sure, @goranjovic might have more context

**Comment by goranjovic** [comment]
@jeluard The source is cross-checked list from etherscan and ethplorer. Yes,  we'll do the contract methods implementation separately, this is just a quickfix.

**Comment by goranjovic** [comment]
PR passes the automated test - https://jenkins.status.im/job/end-to-end-tests/job/status-api-tests/5/


<blockquote></blockquote>

**Review by janherich — APPROVED** [review]

**Comment by asemiankevich** [comment]
@cammellos i am not sure why those 3 are not shown in this PR?
-                   {:symbol   :Centra
-                    :name     "Centra Token"
+                   {:symbol   :CTR
+                    :name     "Centra"
                     :address  "0x96A65609a7B84E8842732DEB08f56C3E21aC6f8a"
                     :decimals 18
                     :hidden?  true}
                    {:symbol   :ROL
-                    :name     "Dice"
+                    :name     "DICE"
                     :address  "0x2e071D2966Aa7D8dECB1005885bA1977D6038A65"
                     :decimals 16
                     :hidden?  true}
-                   {:symbol   :ATMChain
+                   {:symbol   :ATM
                     :name     "Attention Token of Media"
                     :address  "0x9B11EFcAAA1890f6eE52C6bB7CF8153aC5d74139"
                     :decimals 8

Can't find them in Assets (wallet). Can you please take a look?

**Comment by cammellos** [comment]
@asemiankevich I think those 3 have been hidden ( but not in this PR , nightly should be the same), @goranjovic can you confirm?

**Comment by goranjovic** [comment]
@asemiankevich @cammellos Intentionally hidden (for now) because they are not supported by cryptocompare, so their value is shown as 0, which is kind of misleading. We'll probably bring them back later, but now they're hidden.

**Comment by asemiankevich** [comment]
@cammellos @goranjovic good to know, thanks!!

**Comment by asemiankevich** [comment]
well i bought several in bancor /airswap and looks good

**Pull request merged**
