### PR TITLE
fix: modal-view-ids to track multiple modals and fix suggested routes fetching when scanning address by QR

### LINKED ISSUE #18652: Unable to find routes for asset transfer
### Steps:
1. Recover the user with available assets to sent
2. Go to the send page
3. Attempt to send the available amount

### Actual result:
Routes for the asset transfer are not found (no matter testnet or mainnet network is used)

https://github.com/status-im/status-mobile/assets/52490791/7f2f60f0-e00c-4217-a336-20ad9e1282e8

### Expected result:
Routes are found

### Logs:
[logs.zip](https://github.com/status-im/status-mobile/files/14237135/logs.zip)

### ENV:
Nightly 12.02.2024

### PR DESCRIPTION
**Pull request by briansztamfater**
fixes #18652 (hopefully for the last time)

### Summary

This PR adds support for multi level modals while tracking modal-view-ids and small refactor to address input due to removed usage of useEffect by https://github.com/status-im/status-mobile/commit/b7bffb3bd30653abab1e645e0db8d82c5b3e9bca // cc @smohamedjavid 

#### Platforms

- Android
- iOS

##### Functional

- wallet / transactions

### Steps to test

- Open Status
- Log in to your profile
- Navigate to the Wallet tab
- Tap on any account
- Tap on the Send button
- Scan any address
- Select any asset to send
- Enter any amount (below the limit) and be sure you have enough ETH for gas spending
- Verify routes are fetched

Additionally, a general smoke test would be appreciated due to that we are modifying general purpose parts of the codebase.

status: ready

### CODE REVIEW

**Comment by Parveshdhull** [comment]
Hi @briansztamfater, Thank you for the PR.

I see we introduced `: navigation/current-screen-id` and `:modal-view-ids` in https://github.com/status-im/status-mobile/pull/18593. Please can you elaborate on why we need them? Was view-id not providing the correct value and that's why we needed these?

I recently [fixed](https://github.com/status-im/status-mobile/pull/19083) a bug with view-id and modals, please can you check if view-id working now and we still need these modal-view-ids

**Comment by briansztamfater** [comment]
> Hi @briansztamfater, Thank you for the PR.
> 
> I see we introduced `: navigation/current-screen-id` and `:modal-view-ids` in #18593. Please can you elaborate on why we need them? Was view-id not providing the correct value and that's why we needed these?
> 
> I recently [fixed](https://github.com/status-im/status-mobile/pull/19083) a bug with view-id and modals, please can you check if view-id working now and we still need these modal-view-ids

Hi @Parveshdhull! Thanks for reviewing this and pointing out your PR. I tested develop (now that your PR has been merged), and it definitely improved how `:view-id` is working. However, when working with modal stacks (navigating within a modal), `:view-id` doesn't get updated properly. Maybe we could fix that in `:view-id` that and maybe it could work for our case.
However, `:modal-view-ids` is a more sophisticated solution to have a complete track of the modals navigation stacks (this PR adds support for multiple modals, you can check unit tests for examples, or leaving some screenshots below). Currently we are using it to get the last screen in the last modal, but we can use it for get the first one (it may be useful for wizard-type flows that will be implemented in #19059), find if a screen is within a stack, etc.

Here are some examples on how this key shows on re-frisk:

**Comment by Parveshdhull** [comment]
Thank you @briansztamfater for adding context to the PR. Replied to your message in https://discord.com/channels/1103692771585433630/1214229790719086672/1214818715955109888

**Comment by briansztamfater** [comment]
Closing this as changed the approach to use view-id and modal-view-ids will be removed, opened other PR to fix routes fetching when scanning an address in #19259

**Pull request closed without merging**
