### PR TITLE
Use cloudflare dns

### PR DESCRIPTION
**Pull request by cammellos**
Use cloudflare dns for discovery (tempoary), and restart discv5 if it fails.

### CODE REVIEW

**Comment by pavloburykh** [comment]
Hey @cammellos. Thanx for the PR. I see that is it still in progress and not ready for testing yet.
But I just noticed that latest builds are crashing after login, which is a reason of failed e2e. 
Could not get any logs though. 

https://user-images.githubusercontent.com/97245802/207065885-7be5dbc4-7336-492a-9265-a1792f685509.mp4

**Comment by cammellos** [comment]
@pavloburykh thanks, I managed to get logs, I am debugging the issue

**Comment by cammellos** [comment]
@pavloburykh I fixed the crashing issue, but seems like there's still something not working, do you know why/where the tests fail?
Thank you!

**Comment by pavloburykh** [comment]
> 
@cammellos thanks for the fix. 
Regarding failed tests: currently there is an essential time lag for actions between Devices in chats. By actions I mean: sending/receiving, deleting, pinning, setting reactions for messages. I guess, the root cause of the problem is status.prod fleet which is already enabled by default. This is the reason why e2e tests are failing. 

BTW: is it expected that status.prod fleet is enabled by default in this PR? I see that nightly builds are still on eth.prod. 

You can try following steps:

1. Start 1-1 chat between User A and User B
2. Send some messages to each other
3. Perform some actions upon messages (e.g. delete, pin, set reactions)
4. Pay attention at lag time between performing action on User's A side and its apply on User's B side (and vice verse). 

**Actual result:** there is a time lag for actions between Devices in chats. 

I attach couple of videos below, demonstrating the behaviour:

https://user-images.githubusercontent.com/97245802/207290863-3a71dd76-2674-44ab-b7fa-3f242fa22166.mp4


https://user-images.githubusercontent.com/97245802/207292241-e00cedbd-e72f-4c57-8867-6b73d757e68b.mp4

**Comment by pavloburykh** [comment]
> 

Hey @cammellos! 4 test failures in last test run are not related to PR. We can try to rebase PR to the latest develop and re-run e2e to make sure.

**Comment by cammellos** [comment]
@pavloburykh rebased against develop, would you mind running the e2e tests again please?

**Comment by churik** [comment]
already done

**Comment by churik** [comment]
@cammellos ready to be merged, thank you!

**Review by churik — APPROVED** [review]

**Comment by churik** [comment]
I guess can be closed after [3e3a365ffb989ab65164aaa52c83f8f4e9456073](https://github.com/status-im/status-mobile/commit/3e3a365ffb989ab65164aaa52c83f8f4e9456073) ?

**Pull request closed without merging**
