### PR TITLE
[IMPORTED] [#16377] feat: add calendar to quo2

### LINKED ISSUE #16377: Implement calendar component in quo2 preview
Create the quo2 component calendar as per designs:

https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-UI-for-Mobile?node-id=780%3A214042&mode=dev

Should be implemented according to best practices
https://github.com/status-im/status-mobile/blob/develop/doc/new-guidelines.md

Include component spec tests
https://github.com/status-im/status-mobile/blob/develop/doc/component-tests-overview.md

Communicate with design team before starting to make sure there is no unknown requirements and to understand the interactions
In scope:

1) Day input
2) Calendar itself

Out of scope:
1) Hour input is out of scope (anything below and including "Select hour" is out of scope).

### PR DESCRIPTION
**Pull request by siddarthkay**
Fixes #16377 

### Summary

This PR add the calendar component to quo2

Light Mode

Dark Mode

#### Platforms

- Android
- iOS

### Steps to test

- Open Status

- Navigate to Quo2 Preview > calendar > calendar

status: ready

### CODE REVIEW

**Comment by J-Son89** [comment]
this pr should not be imported yet as it was not ready 👍 @ilmotta had requested changes and there was no design review done yet

**Comment by siddarthkay** [comment]
oh right sorry, we can close this PR. 
This was actually a result of me testing the script :D

**Comment by siddarthkay** [comment]
But, lets keep it open, I added a branch syncing feature whichI further want to test.
I'll mark this PR as draft if that helps?

**Comment by J-Son89** [comment]
sure, np @siddarthkay  just wanted to make sure of that 👍

**Comment by J-Son89** [comment]
one thought - "But, lets keep it open, I added a branch syncing feature whichI further want to test."

Do we really need this complexity? 
I thought this is the last step before merging, ie Contributor makes their pr, we are happy with everything and then we want to merge it so we do copy their pr into our own branch so that we can make final edits and run tests etc first.

**Comment by siddarthkay** [comment]
> one thought - "But, lets keep it open, I added a branch syncing feature whichI further want to test."
> 
> Do we really need this complexity? I thought this is the last step before merging, ie Contributor makes their pr, we are happy with everything and then we want to merge it so we do copy their pr into our own branch so that we can make final edits and run tests etc first.

Ideally we shouldn't but in cases where we import and we find something that contributor needs to update on their branch.
For example a failing test or a lint etc.
Then we have to manually keep track of 2 branches....

**Comment by siddarthkay** [comment]
The syncing piece is also just this much more code :D

https://github.com/status-im/status-mobile/pull/16792/files#diff-eb5d96fb5fcad077cdbba13f5e268d92bc2bd2645982717ece58aa1597adec78R38-R53

**Comment by J-Son89** [comment]
"For example a failing test or a lint etc.
Then we have to manually keep track of 2 branches..."

These are simple things that would just be easier for us to manually do though :)

but sure if it's straightforward then all good 👍

**Comment by siddarthkay** [comment]
Well found my first edge case in the merge script, I'll close this PR and delete the branch and re-import for now 👍🏻

**Pull request closed without merging**
