### PR TITLE
[fix] lost contact requests and following messages

### LINKED ISSUE #3984: Messages never reach the contact if he was added while being offline (or being online but different network)
***Type***: Bug

***Summary***: Let's take there are C1 (Sender) and C2 (Recipient). In many cases, 'Sender' may start 1-1 chat with the Recipient while the last is **offline** or **online but use different network** than Client. 
In any of that cases - Recipient will never see messages (and 1-1 chat never appears) from the Sender even if both appear online on the same network and Sender sends messages again and again. 

Neither 1-1 chat created nor messages received by the recipient if message sender starts the chat while recipient in a different network or offline.

#### Expected behavior
1-1 chat created and messages arrive to the recipient after he appears online in the same network 1-1 chat has been created in. 

#### Actual behavior
Messages never reach recipient if contact added while being offline (or being on a different network)

### Reproduction 1
- Open Status on the Device1 and the Device2
- Create an account on Device1 and switch to 'Mainnet with upstream RPC' network (Contact1)
- Create an account on Device2 and switch to 'Ropsten with upstream RPC' network (Contact2)
- Contact1 adds Contact2 in contacts (doesn't matter via QR code scan or public key submit)
- Contact1 sends a message
- Contact2 switch the network to 'Mainnet with upstream RPC'
- Contact2 logs in to account and stays on the Home screen
- (Optional) Contact1 sends a message again 

### Reproduction 2
- Open Status on the Device1 and the Device2
- Create Contact1 and Contact2 respectively
- Keep public key (or QR contact code) of the Contact2
- Contact2 logs out
- Contact1 adds Contact2 in contacts (doesn't matter via QR code scan or public key submit)
- Contact2 logs in to account and stays on the Home screen
- (Optional) Contact1 sends a message again 

### Additional Information
* Status version: Develop (354th build) and release 0.9.17
* Operating System: Android and iOS

#### Logs
Below two sessions reflecting Reproduction 1 (changing network) above:
TF session with logs for Sender side: https://app.testfairy.com/projects/4803590-status/builds/8168269/sessions/25/?accessToken=hjkpX71pGqAuXG8Wk229cmciV9I
TF session with logs for Recipient side: https://app.testfairy.com/projects/4803622-status/builds/8167404/sessions/83/?accessToken=k4UIGu9qIjkTmCJKbx8e3Ige10Y

<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803590-status/builds/8168269/sessions/25/?accessToken=hjkpX71pGqAuXG8Wk229cmciV9I">TestFairy: Status 0.9.17 (2458) @25</a></strong></div></blockquote>
<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803622-status/builds/8167404/sessions/83/?accessToken=k4UIGu9qIjkTmCJKbx8e3Ige10Y">TestFairy: Status 0.9.16-31-ga7bd6b6e+ (2458) @83</a></strong></div></blockquote>

### PR DESCRIPTION
**Pull request by yenda**
fix #3984 

Fetch discovery topic from offline inboxing

status: ready

### CODE REVIEW

**Review by janherich — APPROVED** [review]

**Review by rasom — APPROVED** [review]

**Review by cammellos — APPROVED** [review]

**Comment by Serhy** [comment]
It works great for the contact who created a new account and keep use it: 
* When I'm on Mainnet with upstream RPC and add a user while he is on another network (Ropsten RPC) - when contact switch on Mainnet he receives contact request.
* When I'm on Ropsten with upstream RPC and add a user while he is on another network (Mainnet RPC) - when contact switch on Ropsten he receives contact request.
* When I add a contact while this contact is offline ->  once contact appears online he receives 'Add contact' request
* Same with the Group chat: if it was created with the contact while the last was offline or in another network - as soon as contact appear online in the same network -> GroupChat appears.

However: what happens for recovered accounts is that: all requests from other contacts I received - **re-appears** in the recovered accounts (in the respective network where request has been sent). Further re-login to account pull all the messages that were sent by the contacts. I expect if we merge it with https://github.com/status-im/status-react/issues/3872 - all recovered accounts will pull all the contact requests along with the messages...
This is the scenario:
1) Create account on Device1 and Device2 (Contact1 and Contact2 respectively)
2) Contact2 adds Contact1 in contacts and sends a message there
3) Contact2 creates GroupChat with Contact1 and sends a message there
4) Contact1 flushes all the data in the app (so it's like a fresh new build)
5) Contact1 recovers account and stay on Home screen
**Current result:** Device2 appears on chats screen
6) Contact1 relogins.
**Current result:** All messages which were sent from Device2 appears in 1-1 chat. GroupChat appears without messages
7) Contact1 relogins one more time.
**Current result:** All messages which were sent from Device2 in GroupChat appear. 

Video with TF session for what happens with recovered accounts: https://app.testfairy.com/projects/4803590-status/builds/8226731/sessions/11/?accessToken=5Eei9wXbF2/nt5LqWUOQB2Yi0Gk 



<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803590-status/builds/8226731/sessions/11/?accessToken=5Eei9wXbF2/nt5LqWUOQB2Yi0Gk">TestFairy: Status 0.0.2504 @11</a></strong></div></blockquote>

**Comment by Serhy** [comment]
Builds  Android: https://i.diawi.com/kzB1LA and iOS: https://i.diawi.com/FPxeVF has been tested. 

1) If contact request sent to contact who is offline and this contact appears online ~5 minutes after - nothing received staying on Home screen for 5 minutes or more. Send message again by sender -> nothing appears. However, after next re-login by a receiver pulling contact request and all the messages as expected. 
**To reproduce:**
* Create two account on two devices 
* Contact2 enables airplane mode and stays on Home screen
* Contact1 adds Contact2 in contact and sends in 1-1 chat several messages.
* Contact2 waits ~5 minutes and disables airplane mode
* Contact2 waits 5 more minutes
* Contact1 sends a message. 
**Actual result:** no 1-1 chat appears on Contact2 side.
* Contact2 re-logins to account.
Actual result: 1-1 chat with all the messages appears on Contact2 side as expected.

2) When I switch between networks (Ropsten RPC <-> Mainnet RPC) - on the first/second switch application may crash (It's happening in develop as well https://github.com/status-im/status-react/issues/3981)… However, with above builds there is no way for this contact who switched network to log out (or switch network once again). `Null is not an object (evaluating 'e.stopWatching')` when login out appears all the time, even after re-open the app -> login and try to log out an error in pop-up persists blocking me to log out. 
https://app.testfairy.com/projects/4803622-status/builds/8232122/sessions/51/?accessToken=Q6f2Mx14wsxM0I2HcmSvVtl20Sc
**Update**: The `e.stopWatching` error reproducible for the next account:

* Install above builds
* Recover next account: `kiss nest senior cluster nephew trophy road curtain buzz hello wool decide` password `aaaaaa`
* Try to log out

**Comment by Serhy** [comment]
Builds Android: https://i.diawi.com/URuyyw and iOS: https://i.diawi.com/WALveY has been tested. 
We are almost good to go but lest fix the issue:

If the contact adds another contact and sends messages while the last is offline - the next time contact appears online he received only contact request without messages. Next time this contact logs in offline messages arrives ok. We need to receive everything in one go: contact request + messages that were sent.

* Create two account on two devices
* Contact2 enables airplane mode and stops the app. 
* Contact1 adds Contact2 in contact and sends in 1-1 chat several messages.
* Contact2 waits ~5 minutes, disables airplane mode and logs in to account
**Current result:** Only contact request is received. No offline inboxed messages.
TF session after Contact2 disabled airplane mode and logs into account: https://app.testfairy.com/projects/4803622-status/builds/8255074/sessions/6/?accessToken=cNsumUj3hM3APrqoJJ6XQigzcLY



<blockquote><div><strong><a href="https://i.diawi.com/URuyyw">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>
<blockquote><div><strong><a href="https://i.diawi.com/WALveY">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>
<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803622-status/builds/8255074/sessions/6/?accessToken=cNsumUj3hM3APrqoJJ6XQigzcLY">TestFairy: Status 0efafa5b+ (2519) @6</a></strong></div></blockquote>

**Comment by Serhy** [comment]
With the last builds: Android: https://i.diawi.com/H3vrQG and iOS: https://i.diawi.com/FJAcTy
1) Issue described in https://github.com/status-im/status-react/pull/4094#issuecomment-387372849 still reproduced. So if contact request + message(s) has been sent to user who is offline - next time this contact appears online the contact request is received only without messages. However if to re-login, messages arrive from the offline inbox.

**Comment by Serhy** [comment]
There is a bug with "pervasive" Group Chat requests through different accounts on the same app. See steps to reproduce for what happens:
1) Create on Device1 and Device2 - Contact1 and Contact2 respectively
2) Contact1 sends a contact request to the Contact2
3) Contact2 in 1-1 chat taps 'Add to contacts'
4) Now Contact2 logs out
5) Create one more contact on Device2 side (Contact3)
6) **Contact1** creates GroupChat with the **Contact2** (Nothing happens at this point)
7) Contact1 sends a message in the group chat created with Contac2
**Actual result:** **On the Contact3 side**, who logged in at the moment on Device2, there is like a 1-1 chat created with the message sent in group chat to Contact2.
Further messages in GroupChat OR in 1-1 chat by the Contact1 results in receiving all messages by the Contact3

**Note:** in the above scenario if to exclude 3rd step - it's all OK. So for this pervasive group chat bug happens if GroupChat has been created with the contact who kept in the contact list of any account in the app.  
See TF session for above scenarios:
Contact1 (iPhoneX) - from 13:40 https://app.testfairy.com/projects/4803590-status/builds/8255371/sessions/10/?accessToken=Jv/yL0DW17YTnk9F9HyoC3MgUp4
Contact2 (Android 7.0) - from 05:30 https://app.testfairy.com/projects/4803622-status/builds/8255431/sessions/34/?accessToken=G8aD7Yxea-CankdRgK-EYsYWm-Q

**Comment by Serhy** [comment]
In the latest builds tested: Android: https://i.diawi.com/HBmJA4 and iOS: https://i.diawi.com/2tLn5R the is no issue described in https://github.com/status-im/status-react/pull/4094#issuecomment-387451798

What's left only is: 
1) If contact request or group chat with the contact created with the following messages sent into the chat - the next time contact appears online only chat request received with no messages. Message appear if to re-loging though. (the one described above https://github.com/status-im/status-react/pull/4094#issuecomment-387372849)
2) When user recovers accont for which contact requests was sent in less than 24h - any of that contact requests re-appear again.  (the one described in https://github.com/status-im/status-react/pull/4094#issuecomment-386364618)

Taking into account on what stage we now with this PR and brings significant improvement to message confidence I suggest we can merge it: the first issue above can be looked as a follow up separately and for the second one (account recover) we need to more general agreement (i.e. what exact data should we restore on account recovering process)

@chadyj , @yenda - are you OK to merge with above notes?

<blockquote><div><strong><a href="https://i.diawi.com/HBmJA4">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>
<blockquote><div><strong><a href="https://i.diawi.com/2tLn5R">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by cammellos** [comment]
@Serhy I will merge in the changes, it's clear that will only make the system more reliable.

**Pull request merged**
