### PR TITLE
Fixed multidex configuration for android 4.4

### PR DESCRIPTION
**Pull request by jeluard**
Fixed android build configuration to have application correctly configured for older android devices.

_Steps to test_

* start application on a device running android 4.4
* application should not crash during startup

status: ready
#620

### CODE REVIEW

**Comment by rasom** [comment]
@jeluard how can we test/check this? Is it related to some issue?

**Comment by jeluard** [comment]
Yes this is related to #620 . To test, run on android 4.4. It should not crash during startup.

**Comment by rasom** [comment]
@annadanchenko did you have a chance to test this PR?

**Comment by annadanchenko** [comment]
@rasom it will be tested by @asemiankevich as verification of #620

**Pull request merged**
