### PR TITLE
[#11809] Remove or upgrade react-native-device-info to 7.4.0

### LINKED ISSUE #11809: Remove or upgrade react-native-device-info to 7.4.0
# Description

The dependency on `react-native-device-info` is causing our APK to include Google dependencies that we do not use or want.

Because of this we were force to make a separate branch called [`fdroid-release/1.11.x`](https://github.com/status-im/status-react/tree/fdroid-release/1.11.x) as a [dirty fix](https://github.com/status-im/status-react/commit/f010a0cd8897077bfc9b8864cdb019ae8655bdf0) to the Google dependencies blocking inclusion of our app in the [F-Droid](https://f-droid.org/) application directory as part of [fdroidata#7179](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7179).

# Requirements

As [suggested](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7179#note_511312796) by `@Licaon_Kter` there was a fix implemented for the package in https://github.com/react-native-device-info/react-native-device-info/pull/1153 which was included in [`v7.4.0`](https://github.com/react-native-device-info/react-native-device-info/releases/tag/v7.4.0). We can either upgrade our version to `v7.4.0` or newer, or remove the dependency entirely.

But the removal of the dependency is dependent on the future of Referral program and our need for including `installreferrer`.

### PR DESCRIPTION
**Pull request by flexsurfer**
fixes #11809

### CODE REVIEW

**Comment by jakubgs** [comment]
I did `make release-fdroid` and checked the result after unpacking with `apktool d`:
```
 > ag googleapi
smali/com/learnium/RNDeviceInfo/RNDeviceModule.smali
3297:    invoke-static {}, Lcom/google/android/gms/common/GoogleApiAvailability;->getInstance()Lcom/google/android/gms/common/GoogleApiAvailability;
3306:    invoke-virtual {v0, v1}, Lcom/google/android/gms/common/GoogleApiAvailability;->isGooglePlayServicesAvailable(Landroid/content/Context;)I

```
Seems correct. That's all there is.

**Review by cammellos — APPROVED** [review]

**Comment by churik** [comment]
e2e test results: https://ethstatus.testrail.net/index.php?/runs/view/6987&group_by=cases:section_id&group_order=asc - no related failures

**Comment by Serhy** [comment]
Looks good to me! With latest builds on Android 11 I still can create account with successful referral attributions registration. Tested
- advertisement registration
- 1-1 chat + starter pack registration (tested within Rinkeby network)
- Public chat referral + No StarterPack

Can create/ recover new account with iOS and transact, receive chat messages.
Reviewed failed e2e tests, - they doesn't relate to this PR.

**Comment by jakubgs** [comment]
I didn't change anything. I just squashed one commit and re-arranged the order so it makes more sense when I merge.

**Pull request merged**
