### PR TITLE
[Fixes: #16219] Correctly handle removal event when out of order

### LINKED ISSUE #16219: Access to group chat and options in Manage members are still available for a removed user after logging back In (Until Relogged Again)
Follow up for https://github.com/status-im/status-mobile/pull/16134
### Steps:
1. User A and User B are members of a group chat.
2. User B logs out of the app.
3. User A removes User B from the group.
4. User B logs back into the app.
5. User B check 'Group details'

### Actual result:
After being removed from the group, User B can still see the group chat and potentially access the 'Group Details' option after logging back

https://github.com/status-im/status-mobile/assets/52490791/b00965b4-ca80-4e48-9257-55436c0b338b

### Expected result:
After being removed from the group, User B should not have access to the group details

### PR DESCRIPTION
**Pull request by cammellos**
https://github.com/status-im/status-go/compare/9896ec81...29fd5006

Status-go pr https://github.com/status-im/status-go/pull/3878

Fixes: #16219

The removal message wasn't processed correctly, so it resulted in the user still being displayed as a member.

### CODE REVIEW

**Review by flexsurfer — APPROVED** [review]

**Review by qfrank — APPROVED** [review]

**Comment by VolodLytvynenko** [comment]
Hi @cammellos, thank you for the PR. One issue is found that's preventing complete testing of this PR:

## ISSUE 1: Newly created group chat not visible to other users
### Steps to Reproduce:
1. `User A` creates a new group chat inviting `User B`
2. `User B` check appearing group chat in chat list.

### Actual Result:
The newly created group chat is not visible to other users in their chat list.

### Expected Result:
After the admin user creates a group chat, it should become immediately visible to all other users in the group's chat list.

### Logs:
Logs of user who creates the chat:
[Status.log](https://github.com/status-im/status-mobile/files/12334917/Status.log)
[geth.log](https://github.com/status-im/status-mobile/files/12334918/geth.log)

Logs of user who is invited to the chat:
[geth.log](https://github.com/status-im/status-mobile/files/12334925/geth.log)
[Status.log](https://github.com/status-im/status-mobile/files/12334926/Status.log)

**Comment by cammellos** [comment]
@VolodLytvynenko apologies, I messed up in a rebase, would you mind testing again?
Thank you

**Comment by VolodLytvynenko** [comment]
hi @cammellos thank you for your work. The issue is fixed. PR is tested and ready to be merged

**Comment by churik** [comment]
It is OK to merge it now, as it was tested before and tests are unstable, thank you for double check!

**Pull request merged**
