### PR TITLE
Features/keep contacts in sync

### PR DESCRIPTION
**Pull request by cammellos**
### Summary:

Once two devices are paired, contacts are kept in sync by sending an updated sync message every time we send/accept a contact request.

#### Areas that maybe impacted (optional)
**Functional**
- contact requests

Only the last commit needs reviewing

status: ready

### CODE REVIEW

**Review by janherich — APPROVED** [review]

**Review by yenda — APPROVED** [review]

**Comment by cammellos** [comment]
@churik latest build does not show your own messages as new (the same in public chat), it was a regression introduced by a refactoring PR.

**Review by rasom — APPROVED** [review]

**Comment by asemiankevich** [comment]
@cammellos i have noticed sync is not being done in the following case:

1. Install release build android
2. Install release build ios
3. recover account ios and android builds
4. upgrade android and ios to current PR
5. install nightly build desktop
6. recover same account on desktop
7. install current PR on desktop as upgrade
8. login on android and go to test-team chat. Add someone to contacts (for ex Chad)
9. login on ios
10. on android and ios: Profile-Devices - pair devices - sync all (tap on both devices)
11. make sure the contact added in step 8 is present on ios and android now
12. go to desktop and tap pair devices
13. enable sync on desktop for 2 mobile devices (ios and android)
14. tap sync all devices on desktop
15. make sure contact from step 8 present on desktop now

Actual result: contact added on step 8 is not synced on desktop and not present there in contact list.

Could you please take a look? cc @churik

**Comment by cammellos** [comment]
@asemiankevich sorry just to make sure, sync it's a one directional thing.

I am assuming all devices are paired & enabled here.

So when you click on `Sync all` on `Desktop` all contacts on `Desktop` should be seen on `ios` & `android`. If you click on `Sync all` on `android` all contacts on `android` will be shared on `ios` & `desktop` etc.

Here it seems `contact-8` is not present on desktop, correct?

If you click on `sync-all` on `desktop` you should not see `contact-8` on desktop. But if you click on `sync-all` on mobile (where `contact-8` is), you should see it on `desktop`.

Is that the case or I misunderstood?

**Comment by asemiankevich** [comment]
yes, that is correct @cammellos and i tapped `sync all` on all devices and contact from step 8 never appeared on desktop (

also 1 more question - i need to sync devices manually all the time i add new contacts/ chats across devices?

**Comment by cammellos** [comment]
@asemiankevich no, once paired, they are kept in sync, but it works in the same way as messages, so if for example one device is offline for too long and the message is not on the mailserver, that contact won't be synced etc. 
I will ask you for logs, in pm, so don't throw away anything :)

**Comment by asemiankevich** [comment]
[Status desktop.log](https://github.com/status-im/status-react/files/2580233/Status.desktop.log)
[android logcat.txt](https://github.com/status-im/status-react/files/2580252/android.logcat.txt)

**Comment by asemiankevich** [comment]
@cammellos i have created group chat from mobile device with you. Added you as a contact on ios. Android shows me you in contacts too (good). Desktop **does not show** either group chat or you as a contact.

**Comment by cammellos** [comment]
@asemiankevich ping me on status or here when you have 10 mins, I would like to try out something, thanks!

**Comment by churik** [comment]
@cammellos I'm on it, you can ask me) trying to replicate it

**Comment by churik** [comment]
@asemiankevich I followed your steps and between 14 and 15 should be one step more: tap on "Sync all" from IOS or Android devices, because new device (desktop) was added.

Tried to reproduce from scratch 2 times, and I always have new contact on desktop after I tap on IOS or Android "Sync all" (after 14 step).

But if you say that you tapped on IOS (or Android) "Sync all" after 14 step and nothing appears on desktop - it is device specific or contact-specific and only @cammellos can help

**Comment by asemiankevich** [comment]
@churik i spoke with @cammellos and seems we can merge with this , it is very hard to repro now and definitely not crucial. We can report it later once i can repro it 100%

**Comment by churik** [comment]
Automated tests failures are unrelated to PR.
Tested on 4 devices - IOS, Android, Linux, Mac OSx (fresh install and upgrade)
- contacts are syncing  (when one of device was offline, then go online is also checked)
- your messages in 1-1 chats are syncing and didn't mark as read (when one of device was offline, then go online is also checked)
- your messages in group chats are syncing across devices (when one of device was offline, then go online is also checked)

**Aren't synced:**
- contact pictures (known, will be added as a separate issue)
- reading messages (if you read some of the messages on device1,   the will still be displayed as unread on other devices) - also add as a feature request
- deleting chats/clearing history/public chats (if you join from device1 to public chat, you will not see it until you join it on device2)
- profile name/picture/settings

**Known behavior:**
- if you disable sync in one of the devices, then send from it some messages to 1-1 chat, then enable sync - you will not see messages that you send while sync was disabled
- to start using sync, you need to discover (tap on + on mobile under "Devices" or on "Pair this device" on the desktop) your device to other devices, then enable sync on other devices and tap on "Sync all". It is made to start sync on all devices. Should be done only once.
- old history for chats (which were created before sync was introduced) wouldn't be synced. 
So for example if I had a chat with User A created 01/10/2018 on device1 and have messages only from him because all this time I chatted from device2, then I enable sync - I'll see only my new messages on all devices - the previous history wasn't synced.
- devices names will be more recognizable with time, will create separate issue for this
- now sync is limited to 5 devices

**Comment by churik** [comment]
And we can close #6658 I think

**Pull request merged**
