### PR TITLE
remove unused react-native-intersection-observer library

### PR DESCRIPTION
**Pull request by Parveshdhull**
leftover from https://github.com/status-im/status-mobile/issues/18132

### Summary
This library is not used currently in our project, so removing it.

### Testing
PR is just removing unused library and don't need to be tested manually.

status: ready

### CODE REVIEW

**Review by flexsurfer — APPROVED** [review]

**Review by ibrkhalil — APPROVED** [review]

**Comment by Parveshdhull** [comment]
hi @status-im/mobile-qa Please can you check why e2e tests are failing.

**Comment by pavloburykh** [comment]
> hi @status-im/mobile-qa Please can you check why e2e tests are failing.

Hey @Parveshdhull! Tests are failing due to infrastructure issues. Let me trigger re-run.

**Comment by pavloburykh** [comment]
@Parveshdhull again, failures due to infra issues. E2E are feeling bad today. Let's have another try...

**Comment by pavloburykh** [comment]
@Parveshdhull at last e2e have passed. If PR does not require manual QA - it is ready for merge.

**Pull request merged**
