### PR TITLE
[#14760] - Improve community avatar for shell card

### LINKED ISSUE #14760: crash when rejoin an already joined community on desktop
# Bug Report

error caused by this line below, trying to get the avatar of the rejoined community, got `nil` from `(first (:name avatar-params))`
https://github.com/status-im/status-mobile/blob/ceaa363f087ff825e5d74a9143332b9c834c9a01/src/status_im2/contexts/shell/cards/view.cljs#L133

but it's not the root cause
also, the community is in the pending section instead of joined section in the home screen when the error occurs

error log:
```
***                                                                                                                                                                             [240/2585]
NAME: "TypeError"
MESSAGE: null is not an object (evaluating 's.toUpperCase')

clojure$string$upper_case@
status_im2$contexts$shell$cards$view$avatar@
@
reagent$impl$component$wrap_render@
reagent$impl$component$do_render@
@
reagent$ratom$in_context@
reagent$ratom$deref_capture@
reagent$ratom$run_in_reaction@
re_frisk$reagent$impl$component$wrap_funs_$_render@
finishClassComponent@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:27905:43
updateClassComponent@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:27866:50
invokeGuardedCallbackImpl@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:19480:21
invokeGuardedCallback@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:19574:42
beginWork$1@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:32578:34
performUnitOfWork@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:31755:29
workLoopSync@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:31698:45
renderRootSync@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:31671:25
performSyncWorkOnRoot@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:31442:40
performSyncWorkOnRoot@[native code]
@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:22731:38
unstable_runWithPriority@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:65168:30
flushSyncCallbackQueueImpl@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:22726:28
flushSyncCallbackQueue@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:22715:35
batchedUpdates$1@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:31478:35
batchedUpdates@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:20731:36
_receiveRootNodeIDEvent@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:20823:23
receiveEvent@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:20852:32
__callFunction@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:14551:36
@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:14279:31
__guard@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:14502:15
callFunctionReturnFlushedQueue@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:14278:21
callFunctionReturnFlushedQueue@[native code]

***
[Wed Jan 11 2023 22:15:04.103]  ERROR    TypeError: null is not an object (evaluating 's.toUpperCase')

This error is located at:
    in status_im2.contexts.shell.cards.view.avatar (created by status_im2.contexts.shell.cards.view.screens_card)
    in RCTView (at View.js:34)
    in View (created by status_im2.contexts.shell.cards.view.screens_card)
    in RCTView (at View.js:34)
    in View (created by status_im2.contexts.shell.cards.view.screens_card)
    in TouchableWithoutFeedback (created by status_im2.contexts.shell.cards.view.screens_card)
    in status_im2.contexts.shell.cards.view.screens_card (created by status_im2.contexts.shell.cards.view.card)
    in status_im2.contexts.shell.cards.view.card (created by status_im2.contexts.shell.view.render_card)
    in status_im2.contexts.shell.view.render_card (created by CellRenderer)
    in RCTView (at View.js:34)
    in View (at FlatList.js:596)
    in RCTView (at View.js:34)
    in View (at VirtualizedList.js:2120)
    in CellRenderer (at VirtualizedList.js:900)
    in RCTScrollContentView (at ScrollView.js:1124)
    in RCTScrollView (at ScrollView.js:1260)
    in ScrollView (at ScrollView.js:1286)
    in ScrollView (at VirtualizedList.js:1329)
    in VirtualizedList (at FlatList.js:624)
    in FlatList (created by react_native.flat_list.flat_list)
    in react_native.flat_list.flat_list (created by status_im2.contexts.shell.view.jump_to_list)
    in status_im2.contexts.shell.view.jump_to_list (created by reagent15)
    in RCTView (at View.js:34)
    in View (created by reagent15)
    in reagent15 (created by Context.Consumer)
    in react_native.safe_area.consumer (created by status_im2.contexts.shell.view.shell)
    in status_im2.contexts.shell.view.shell (created by f)
    in RCTView (at View.js:34)
    in View (created by f)
    in f
    in f (created by status_im2.contexts.shell.view.shell_stack)
    in status_im2.contexts.shell.view.shell_stack (created by Context.Consumer)
    in RCTView (at View.js:34)
    in View (created by Context.Consumer)
    in RNCSafeAreaProvider (at SafeAreaContext.tsx:50)
    in SafeAreaProvider (created by reagent14)
    in reagent14 (at gestureHandlerRootHOC.tsx:13)
    in RCTView (at View.js:34)
    in View (at GestureHandlerRootView.tsx:17)
    in GestureHandlerRootView (at gestureHandlerRootHOC.tsx:12)
    in gestureHandlerRootHOC(reagent14) (created by WrappedComponent)
    in WrappedComponent (at renderApplication.js:45)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:106)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:132)
    in AppContainer (at renderApplication.js:39)
```

### Reproduction
Got client A, B, C and account ACC1, ACC2
A, ACC1, ios simulator
B, ACC2, another ios simulator
C, ACC1, status desktop

I created a community few weeks ago for testing, it's synced on A and B, not C
I rebuild client A and the community is not synced
So, I send the community invitation from B to A
The invite was synced on both A and C
I then joined the community on client A, did some development
Then joined the community on client C (request join)
Client A crashed

- Status version: develop branch 
- Operating System: iOS

### PR DESCRIPTION
**Pull request by Parveshdhull**
fixes: https://github.com/status-im/status-mobile/issues/14760

status: ready

### CODE REVIEW

**Comment by Parveshdhull** [comment]
Hi @yqrashawn, I am not able to reproduce issue itself, but added a condition for checking the availability of ` (:name avatar-params)` before calling `string/upper-case` on it.
Please can you check if you can reproduce this issue, otherwise this check should be enough for now.

**Comment by yqrashawn** [comment]
@Parveshdhull I'll try to reproduce

**Comment by yqrashawn** [comment]
> @Parveshdhull I'll try to reproduce

Can't reproduce this too. The community that didn't sync now syncs well, maybe due to I sent messages in the channel recently or network issue.

But I'm pretty certain this will fix the crash.

**Comment by Parveshdhull** [comment]
> Can't reproduce this too.

Thank you for checking.

> But I'm pretty certain this will fix the crash.

Awsm, lets merge PR then.

**Review by flexsurfer — APPROVED** [review]

**Pull request merged**
