### PR TITLE
fix mention turns into unknown in community

### LINKED ISSUE #15276: Mentions turn into @Unknown during editing of messages containing mentions in communities
**Steps:**

1. Open community channel
2. Send a message containing mention
3. Longtap on message => Edit message
4. Pay attention at mention in message

**Actual result:** mention turns into \@Unknown\ during editing of message

[Status-debug-logs (18).zip](https://github.com/status-im/status-mobile/files/10908207/Status-debug-logs.18.zip)

https://user-images.githubusercontent.com/97245802/223390594-e3c80a34-ba4f-4731-9508-d2e52981c5c6.mp4

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by Parveshdhull**
fixes https://github.com/status-im/status-mobile/issues/15276

status: ready

### CODE REVIEW

**Review by qfrank — APPROVED** [review]

**Comment by VolodLytvynenko** [comment]
Hi, @Parveshdhull thank you for PR.  The issue related to "unknown"  showing is fixed. One additional super low priority issue is found:
## ISSUE 1: The display name is not resolved in the group and in 1-1 chat in the appropriate format for Androids

#### Preconditions:
- User_desktop and User_mobile are mutual contacts

#### Steps to reproduce:
1. Go to 1-1 chat as a mobile user or Group chat where User_desktop and User_mobile  are members
2. Enter @ into textbox and select <User_desktop> in the shown suggestions
3. Send the message

#### Actual result:
The name of a desktop user is shown as @<User_desktop> after a message is sent

https://user-images.githubusercontent.com/52490791/223724071-2c42743c-4743-48d7-8b7c-2027dac12c09.mp4

#### Expected result:
The name of a desktop user is shown in an appropriate format
image

#### Additional info:
The issue is related only to Android devices

#### Device:
- Huawei p20 light. version 9

**Comment by Parveshdhull** [comment]
Hi @VladimrLitvinenko, Thank you for testing the PR.
I tried both 1-1 chat and group chat in android, and I am not able to reproduce issue. Please can you take a look.

https://user-images.githubusercontent.com/17097240/223732669-0a45c855-2039-40b2-a09d-a8c405dd6331.mp4

**Comment by flexsurfer** [comment]
this is probably not related and known https://github.com/status-im/status-mobile/issues/15202
cc @pavloburykh

**Comment by pavloburykh** [comment]
> this is probably not related and known #15202 cc @pavloburykh

yeah, this is a separate issue, it is logged and known. @VladimrLitvinenko it is not related to current PR. @flexsurfer thanx for clarification.

**Comment by VolodLytvynenko** [comment]
> this is probably not related and known #15202 cc @pavloburykh

@flexsurfer thanx for the clarification. 
@Parveshdhull no others issues from my side. Thanx for your work. PR is ready to be merged

**Pull request merged**
