### PR TITLE
Fix message showing behind message composer

### LINKED ISSUE #14148: Message drawer covers messages
The drawer covers messages after you reopen a chat. When tapping the message box, you actually hit the message below, which causes the message actions sheet to appear

Screenshot_2022-10-11-10-37-40-15_65ad86f86fd2321a85272a99323da10f

### PR DESCRIPTION
**Pull request by ibrkhalil**
fixes #14148 

### Testing notes
1- Open a chat on Android (But on latest develop where you'll be able to reproduce the issue)
2- Look if you can see latest message
3- Issue happens only when it's the first time you open the chat in the current session

status: ready

### CODE REVIEW

**Review by rasom — APPROVED** [review]

**Comment by ibrkhalil** [comment]
Gonna test on a couple of physical devices and then merge

**Comment by du82** [comment]
> Gonna test on a couple of physical devices and then merge

will test on three physical devices + a few VMs

**Comment by ibrkhalil** [comment]
> > Gonna test on a couple of physical devices and then merge
> 
> will test on three physical devices + a few VMs

Okay, I tested and looking good on my side .. Waiting for your reply

**Comment by du82** [comment]
> > > Gonna test on a couple of physical devices and then merge
> > 
> > 
> > will test on three physical devices + a few VMs
> 
> Okay, I tested and looking good on my side .. Waiting for your reply

looks good to me!

**Pull request merged**
