### PR TITLE
🚀 contacts performance 🚀

### PR DESCRIPTION
**Pull request by flexsurfer**
🚀 contacts performance 🚀

replaced systemTags on added and blocked fields, all other changes in status-go

QA: pls ping me when testing

### CODE REVIEW

**Comment by churik** [comment]
@flexsurfer 
can you please rebase it? 
let me know when it is ready for testing.
Thank you!

**Comment by flexsurfer** [comment]
@churik  done

**Comment by churik** [comment]
@flexsurfer thank you for PR!
### ISSUE 1: unblocking and removing the user from contacts is not synced between paired devices

**Steps:**
1) restore multiaccount from seed phrase on Device A and B
2) pair devices
3) device A: add user A, block user B 
4) device B: wait until it will be synced
5) device A: remove user A from contacts, unblock User B

**Expected result:**
unblocking and removing will be synced

**Actual result:**
not synced

**OS:** IOS, Android


### ISSUE 2: Users, who are not added to contacts, don't appear in mention suggestion list
Monosnap 2021-09-27 14-58-39

**Comment by flexsurfer** [comment]
> ISSUE 2: Users, who are not added to contacts, don't appear in the mention suggestion list

unfortunately its a price for now, but anyway we want to remove public chats soon, for communities and group chats there should be another solution implemented separately

**Comment by churik** [comment]
@cammellos @hesterbruikman 
so currently it means that mention for non-contacts will not work (public/group chats/communities), not sure what should we do here.

**Comment by cammellos** [comment]
My 2p is that it would be frustrating for user if they ever have to mention someone, so I'd be inclined in fixing it, communities I'd be ok as still in alpha, but public/group chats he would be noticeable

**Comment by flexsurfer** [comment]
i'll fix that then, thanks

**Comment by flexsurfer** [comment]
thanks @churik  all fixed

**Comment by churik** [comment]
Awesome work @flexsurfer!
No regression found.

**Review by shivekkhurana — APPROVED** [review]

**Pull request merged**
