### PR TITLE
🖋 SVG support for NFTs

### PR DESCRIPTION
**Pull request by shivekkhurana**
### Summary
Add support for rendering NFTs that are returned as SVGs.

### Testing notes
This can be checked by viewing an address that contains NFTs from the [Clovers Network](https://opensea.io/collection/clovers) ex: `0x9C7e0603E0f504127Fb1cb6bC14136eFDeCDe107`.

### Screenshots
| Listing | Detail |
|---|---|
| Simulator Screen Shot - iPhone 11 - 2021-10-27 at 17 38 02 | Simulator Screen Shot - iPhone 11 - 2021-10-27 at 17 47 20 |

### Platforms
- Android
- iOS

### Functional
- wallet / transactions

status: ready
bitmoji

### CODE REVIEW

**Review by rasom — APPROVED** [review]

**Comment by hesterbruikman** [comment]
Sorry for the delay in checking @shivekkhurana 

I noticed that it takes a while to get the Clover NFT to display. Initially I get: 
Screenshot_20211102-121430_Status PR

Will reinstall again to see if the issue is time-based or triggered by changing tabs. When I navigated away from wallet and back the image was shown, but that might be a coincidence

**Comment by hesterbruikman** [comment]
> 
> 
> Sorry for the delay in checking @shivekkhurana
> 
> I noticed that it takes a while to get the Clover NFT to display. Initially I get: Screenshot_20211102-121430_Status PR
> 
> Will reinstall again to see if the issue is time-based or triggered by changing tabs. When I navigated away from wallet and back the image was shown, but that might be a coincidence

Didn't encounter this issue after uninstalling/reinstalling. Could it be an IPFS catching issue? Is there any way to detect that as to not show `No collectibles available`, but rather the empty image currently shown ahead of loading?

**Comment by shivekkhurana** [comment]
@hesterbruikman That error message "No collectibles available" shows up when OpenSea returns an empty asset list. I have seen this earlier and this bug it not related to SVG NFTs. 

I don't feel it's a caching issue but I could be wrong. @alaibe what do you think?

**Comment by hesterbruikman** [comment]
> 
> 
> @hesterbruikman That error message "No collectibles available" shows up when OpenSea returns an empty asset list. I have seen this earlier and this bug it not related to SVG NFTs.
> 
> I don't feel it's a caching issue but I could be wrong. @alaibe what do you think?

Just to clarify, it's not persistant. What happens:
1. Install PR
2. Recover account
3. Change to Mainnet
4. Go to Wallet > Collectibles > Enable OpenSea > Expand Clover
5. View error `No collectibles available`
6. Navigate to other tab or wait (can't confirm which had an effect)
7. Navigate back to Wallet
8. View Clover image

Next: Uninstall/Reinstall PR
- Repeat steps 2-4
- View Clover image as exected

**Comment by qoqobolo** [comment]
@shivekkhurana thanks for your work!

### ISSUE 1: `No collectibles available` when first opening Clovers Network collectibles until re-expanding Clovers
Faced the same issue as @hesterbruikman. 
_Sometimes_ the issue is reproducible after relogin, sometimes isn't reproducible at all.
So, I believe we can live with it if it's not easy to figure out and fix.

**Steps to reproduce:**
1. Recover account
2. Change to Mainnet
3. Go to Wallet > Collectibles > Enable OpenSea > Expand Clovers
4. View error No collectibles available
5. Collapse Clovers
6. Expand again (sometimes it needs to be repeated several times, but just waiting definitely doesn't work)

**OS:** Android, iOS

https://user-images.githubusercontent.com/67952253/140726742-179ec64f-824c-4d9f-882b-55b5d418d8d9.MP4

### ISSUE 2: Can endlessly open collectible details modal when pressing on the collectible image

**Steps:**
1. Open collectibles
2. Expand some
3. Tap the picture
4. Tap the picture on the modal screen

https://user-images.githubusercontent.com/67952253/140729981-f7146c5e-1b31-4d35-a75a-da96eba11dce.MP4

**Comment by shivekkhurana** [comment]
@qoqobolo I feel we can create a bug for Issue 1. It's not related to this PR specifically and applies to all. I have seen this happen with other collections too.

I'll submit a fix for Issue 2 today.

**Comment by shivekkhurana** [comment]
@qoqobolo `Issue 2` is fixed.

**Comment by qoqobolo** [comment]
Thanks @shivekkhurana!
PR can be merged.

**Pull request merged**
