### PR TITLE
[#12520] Sync deleted chats

### LINKED ISSUE #12520: Syncing of delete chats
As a user
I want my deleted chats to be synced
So that I can keep a consistent view of my data across my devices

### Description

Currently only added chats are synced, we want to make sure deleted chats are also synced across devices.

### PR DESCRIPTION
**Pull request by rasom**
fix #12520

status: ready

### CODE REVIEW

**Review by flexsurfer — APPROVED** [review]

**Comment by qoqobolo** [comment]
@rasom thanks!
The feature works fine but there is an issue in develop that can affect it:

[Unable to rejoin public chat after deletion until relogin](https://github.com/status-im/status-react/issues/12669). Currently syncing of deleted public chat works fine, but there is a problem with syncing after rejoining the same chat.

How it looks in PR:
1. Sync Device1 and Device2
2. Join a public chat on Device1
3. Delete the chat on Device1 (the chat is deleted on Device2 as expected)
4. Relogin (because without relogin it's currently impossible to rejoin public chat at all due to [#12669](https://github.com/status-im/status-react/issues/12669))
5. Rejoin the same public chat on Device1
**Expected result:** the chat is added on synced Device2
**Actual result:** the chat is not added, need to add it manually 

What do you think, this issue could be fixed in current PR or it's only #12669 related (if so PR can be merged)?

**Comment by rasom** [comment]
@qoqobolo should be fixed in this pr

**Comment by qoqobolo** [comment]
@rasom In `5eba6a4` the app crashes on iOS and the "Unknown" screen opens on Android when trying to join a public chat (without pairing)

Screenshot 2021-09-30 at 15 08 59

**Comment by rasom** [comment]
@qoqobolo pushed anther attempt to fix it. Apparently history is not loaded on adding chat back, but that should be a separate problem...

**Comment by qoqobolo** [comment]
@rasom now https://github.com/status-im/status-react/issues/12669 is fixed, thanks!
But the issue from [this comment](https://github.com/status-im/status-react/pull/12662#issuecomment-931191036) is still reproducible:

#### ISSUE 1: Re-added chat does not re-appear on paired device

**Steps:**

1. Sync Device1 and Device2
2. Join a public chat on Device1
3. Delete the chat on Device1
4. Rejoin the same public chat on Device1

**Expected result:** the chat is added on synced Device2
**Actual result:** the chat is not added, need to add it manually

Also, there are a couple of issues more

#### ISSUE 2: If the chat list on the home screen contains several chats (2 and more, any type) then when deleting one of them the rest will become invisible

Pairing doesn't matter in that case.

**Steps:**
1. Join several public chats
2. Delete one of them

https://user-images.githubusercontent.com/67952253/135594324-1f3fa920-e4af-46ba-8d6c-b0cba3e27940.mp4

#### ISSUE 3: If open a chat (any type) on the primary device and delete the same chat on the secondary device, then `Unknown` screen will be shown on the primary device 

**Steps:**
1. Sync Device1 and Device2
2. Join a public chat on Device1
3. Open that public chat on Device2
4. Delete the chat from the home screen on Device1

**Expected result:** redirect to the home screen or message like "Chat is removed" on Device2
**Actual result:** `Unknown` screen with an endless spinner on Device2

**Comment by rasom** [comment]
issues 1 and 2 are fixed now, 3 in progress

**Comment by rasom** [comment]
@qoqobolo all known issue should be fixed

**Comment by qoqobolo** [comment]
Thanks @rasom 

#### ISSUE 4: Deleted chat re-appears on the paired device after relogin

**Steps:**
1. Sync Device1 and Device2
2. Join a public chat on Device1
3. Delete this chat from Device1
4. Relogin on Device2 and check chat list

Video from Device2:

https://user-images.githubusercontent.com/67952253/135881708-05800758-a721-4dbb-a2bc-2b5677972dfc.mp4

**Comment by rasom** [comment]
@qoqobolo should be fixed now

**Comment by qoqobolo** [comment]
@rasom thanks, works fine now!
PR can be merged

**Pull request merged**
