### PR TITLE
Remove automatic sending of contact request

### PR DESCRIPTION
**Pull request by cammellos**
Fixes: #7401 
Fixes: #7500 
Removes sending automatically a contact request on "Send message" or "Start new chat".

Also allows to send transactions to non-contacts.
cc @goranjovic , the change is pretty small (we just build the contact if it's not in our list), but maybe you would like to have a quick look at it.

### Testing
- Send message should not add a user a contact
- Start new chat -> QR CODE / Public Key should not add a user as a contact

status: ready

### CODE REVIEW

**Review by hesterbruikman — APPROVED** [review]

**Review by gravityblast — APPROVED** [review]

**Review by rasom — APPROVED** [review]

**Review by mandrigin — APPROVED** [review]

**Comment by antdanchenko** [comment]
@cammellos please wait for e2e test updates before merging this PR, I will add them in separate commit to the PR

**Comment by cammellos** [comment]
@antdanchenko for sure, thanks for looking into it!

**Comment by asemiankevich** [comment]
@antdanchenko ^

**Comment by asemiankevich** [comment]
@cammellos what is expected in this PR if:
1. user 1: add user 2 to contacts, send him some messages
2. as user 2: send some messages to user 1, but do not add to contacts 
3. recover user 1 on another device

Should i see [add to contacts] as user 1 (recovered) in 1x1 chat ? @churik has logged bug in develop https://github.com/status-im/status-react/issues/7500 however wondering what is expected here in PR

**Comment by cammellos** [comment]
@asemiankevich you should not see it (unless devices were paired, but does not seem to be the case), so looks like the same issue as develop.

**Comment by antdanchenko** [comment]
@cammellos, @hesterbruikman please see the [video](https://app.saucelabs.com/tests/28c30e19fcaf426c8d38c5f8b7c104ac?auth=954522963184f895e7622e7f90f0fde0) starting from 5:15

I would suggest to block send/request commands in chat for users which are not in your contacts (and some message, e.g. `Add a user to contacts before making a transaction) otherwise the flow looks completely broken

**Comment by gravityblast** [comment]
> I would suggest to block send/request commands in chat for users which are not in your contacts

That was what we wanted to do in another PR but we agreed that we want to be able to send transactions to anyone, to enable other features like kudos etc.

**Comment by antdanchenko** [comment]
@gravityblast but we are not, since a user is not added to contacts, we definitely need to let him know whats wrong, `intrinsic gas too low` is a misleading error

**Comment by cammellos** [comment]
@hesterbruikman @gravityblast @antdanchenko I can possibly change that in the scope of this PR, basically we want to allow people to send transaction to non-contacts, is that correct?

**Comment by antdanchenko** [comment]
@cammellos Let's wait for a decision from design or UX before making any new changes

**Comment by gravityblast** [comment]
> basically we want to allow people to send transaction to non-contacts, is that correct?

sorry I confused the problem, I don't want to ask for changes :)
I thought we were talking about sending a tx to someone who didn't add me. but that's another thing.

**Comment by asemiankevich** [comment]
@hesterbruikman @rachelhamlin @denis-sharypin we are running in the exactly same dialog as in previous PR. Can we make some UI hint in this case for user? I personally dont want to "make" automation ignore this error because it is indicator of some problem (the exact aim of autotests). Please advise

**Comment by hesterbruikman** [comment]
@cammellos thanks for pinging. Apologies for the incoming wall of text. I'm not sure we've carefully phrased the _question_ (a) and _decision_ (b) to allow people to send transactions to non-contacts. 

Overall I would feel much more comfortable with a Send Transaction Request (i.s.o Send Transaction), if we want to allow sending kudo rewards to non-contacts, _until_ we can offer all users control over what transactions can be mapped to their name and what they say (i.e. multi-wallet support).

From the usability perspective this PR was really about giving users _control_ and _transparency_. If I add someone as a contact they become a contact. If I don't, they don't. As long as copy and controls in the UI accurately represent what happens, this really is more a _privacy_ and _security decision._ cc @corpetty @jarradh 

1. Regarding phrasing of the _question_: IMO this is not so much about do we want to allow sending transactions to non-contacts, but more about do we want to allow non-contacts access to a given address. 

2. To me the decision depends on what other transactions and exposure are connected to this address at the moment of release. i.e. Will the contact gaining access to the address see a bunch of meaningless transactions low value chat transactions as it is only one of the addresses in Status used for transactions and the user can control to limit transactions that can be connected to their behaviour in chat.
OR 
Will they see your history of Spankchain transactions and when they were made because at the time of release there is only one address you can use for all transactions and this is the same address anyone (non-contacts) can access. 
_Also, taking into consideration the delta to the current implementation and again how transparent we are about the information you give up._

With the recent proposals regarding the wallet structure I'm not sure what address will be used to send transactions to non-contacts and what other transactions and exposure are connected to this. Hence, why I would prefer a Send Transaction Request alternative at this stage.

**Comment by cammellos** [comment]
My turn for a wall of text :)

I understand that some effort will be made in separating wallet keys, but I think that's a separate discussion and I'd like to keep the discussion more focused on the immediate problem we are solving.

Our objective is to remove the automatic sending of the contact request.

There is a mechanism which we were not aware of that relies on this automatic sending of request:

I can only send transactions to users who either added me in their contacts (which makes sense) or (this is the important point, and does not make much sense) **I have added to my contacts**. 

Mind that adding someone to your contacts (say B) is completely transparent to B, and does not require any interaction on B part. No disclosure of data on B's side by having A adding B to their contacts.

Removing the automatic sending of the contact request exposed this issue, as an error is shown if you try to send a transaction to someone not in your contacts.

Furthermore the issue can be replicated outside this PR (see details below @antdanchenko  ):

So just to achieve our initial goal (don't send the automatic contact request), there are a few options:

1) Allow sending transactions to non-contacts (again, this has no impact on privacy, as currently I can just send a transaction to x just by adding them to my contact, without explicit permission or x's info disclosure)

2) Force A to add B to their contacts before sending a transaction (does not make sense to me, as you are not asking permission, you are just ticking a box really, and we would just be bending to a technical constrain for no good reason)

3) Force B to have added A to their contacts before sending a transaction 

4) Have a Send Transaction Request flow for non-contacts (similar to 3 I guess but more explicit)

1 or 2 are low effort, and allows us to achieve the goal of this task in the short term, effectively making the product better now (probably a day worth of effort say, unless there are some complications).

3 & 4 require more effort and will need design/ux input as currently the contact request flow is opaque (in the case of 3), and I understand we haven't started on 4.

So the question is simply, is it better to go for 1 or 2 now, or wait for 3 or 4? 

In my opinion there's no reason to wait for 3 & 4 as the current behavior is clearly an artifact of a technical decision (sending the contact request automatically), and I doubt it was a deliberate choice, and we can always improve and move to 3 or 4 when ready.

What do you think? 

### Replicate issue on release

1) Go to a profile of a user not in your contacts
2) Click on send-transaction, you will be redirected to the chat (this flow does not automatically add the user to contacts)
3) Try to send a transaction

The recipient field is then empty and you can't send a transaction (you have already all the information to send one i.e their public key).

**Comment by hesterbruikman** [comment]
Thanks for bringing focus and options @cammellos . Agreed, we shouldn't derail this PR to accomodate a new requirement. 

> 1. Allow sending transactions to non-contacts (again, this has no impact on privacy, as currently I can just send a transaction to x just by adding them to my contact, without explicit permission or x's info disclosure)

I believe this has impact on privacy, it's just no different from the current situation and out of scope of this PR. So seems like the best way forward for now, next to creating a new issue for 4.

**Comment by cammellos** [comment]
Thanks for the reply,

When I said it has no impact on privacy, I meant that it does not make any concession compared to the current behavior (of course it would improve things as we would not send a contact request automatically).

I will then close this PR and removing the automatic contact request will be done in the scope of 4 (as we can't get this through otherwise it would make things worse), is that correct?

**Comment by cammellos** [comment]
@hesterbruikman as discussed we'd go for 1 so we can get this through and then we will work on 4 once the keys are decouple.

**Comment by hesterbruikman** [comment]
Adding rationale: 2 would reinforce the perception of Contacts being mutual and that by adding a contact you will always have the other persons wallet address. This is the case at the moment, but might/should (?) change.

**Comment by cammellos** [comment]
@antdanchenko I have fixed the issue, could you run e2e tests again against this? (I have moved it to TEST and back but not sure they have been triggered)

**Comment by asemiankevich** [comment]
> @antdanchenko I have fixed the issue, could you run e2e tests again against this? (I have moved it to TEST and back but not sure they have been triggered)

let me start them when build arrives

**Comment by cammellos** [comment]
@asemiankevich thanks!

**Comment by asemiankevich** [comment]
@cammellos so what is left here? @antdanchenko to fix the rest of tests? or they are fixed?

**Comment by cammellos** [comment]
@asemiankevich I will try to fix them myself today, on monday if I have still have made no progress, I will ask @antdanchenko to assist

**Comment by cammellos** [comment]
@antdanchenko I have updated the e2e tests, change is minimal and new flow is tested. @asemiankevich if you would like to test it again, it's ready.

**Comment by asemiankevich** [comment]
Those scenarios work as expected. 

- [x] Send message should not add a user a contact
- [x] Start new chat -> QR CODE / Public Key should not add a user as a contact

No regressions found so far.

**Pull request merged**
