### PR TITLE
Update to status-go which now uses discovery for every network

### PR DESCRIPTION
**Pull request by dshulyak**

### CODE REVIEW

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/JazUMQ for branch PR-4246

<blockquote><div><strong><a href="https://i.diawi.com/JazUMQ">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/YLaHcx for branch PR-4246

<blockquote><div><strong><a href="https://i.diawi.com/YLaHcx">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Review by flexsurfer — APPROVED** [review]

**Review by adambabik — APPROVED** [review]

**Comment by lukaszfryc** [comment]
@dshulyak looks like there is no change in battery and network consumption between nightly and this PR. Also, I didn't notice any functional regressions 👍 

Sample test (100 messages send and another 100 received. All in foreground): 

|Build|Data transferred|Power usage|
|---|---|---|
|PR|4.72 MB total (1.31 MB received, 3.41 MB transmitted)|0.72%|
|Nightly|4.25 MB total (0.89 MB received, 3.36 MB transmitted)|0.72%|

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/aVBpvq for branch PR-4246

<blockquote><div><strong><a href="https://i.diawi.com/aVBpvq">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/cHwXm8 for branch PR-4246

<blockquote><div><strong><a href="https://i.diawi.com/cHwXm8">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/qyyurL for branch PR-4246

<blockquote><div><strong><a href="https://i.diawi.com/qyyurL">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/g4QK6V for branch PR-4246

<blockquote><div><strong><a href="https://i.diawi.com/g4QK6V">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Pull request merged**
