### PR TITLE
[#4010] Allow both release and develop version to coexist

### LINKED ISSUE #4010: Allow both release and develop version to coexist
### User Story

As a developer, I want to have both release and developer version running at the same time on iOS.

### Description

Currently both versions share same identifier preventing to keep the released version installed.

*Type*: Feature

### PR DESCRIPTION
**Pull request by endenwer**
fixes #4010

### Summary:
Add ability to install debug and release build together.

### Steps to test:
- Install release build
- Install debug bulid
- Check that two apps exist: Status and Status Debug.

Wait for the new icon.

status: ready

### CODE REVIEW

**Comment by jeluard** [comment]
@endenwer Any reason why this is wip?

**Review by jeluard — APPROVED** [review]

**Comment by endenwer** [comment]
Wait for icon.

**Comment by endenwer** [comment]
@jeluard Do I need to change the icon for debug build as on android?

**Comment by jeluard** [comment]
@endenwer Yes please! @denis-sharypin will provide you those.

**Comment by endenwer** [comment]
ok, I wait for #4018

**Comment by yenda** [comment]
@endenwer it seems the icon has been delivered can you udpate your PR ? https://github.com/status-im/status-react/issues/4018#issuecomment-385021861

**Comment by endenwer** [comment]
@jeluard @yenda Done.
simulator screen shot - iphone 6 - 2018-04-29 at 19 25 28

**Review by flexsurfer — APPROVED** [review]

**Review by goranjovic — APPROVED** [review]

**Comment by Serhy** [comment]
@endenwer could you please rebase on latest develop branch, please? There was an issue (which is fixed by https://github.com/status-im/status-react/pull/4084 already!)

**Comment by flexsurfer** [comment]
hey @endenwer thanks, could you please "Allow edits from maintainers." https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/

<blockquote><div><strong><a href="https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/">Allowing changes to a pull request branch created from a fork - User Documentation</a></strong></div><div>For greater collaboration, you can allow commits on branches you've created from forks. Permission to commit to your forked branches is limited to those with push access to the upstream repository of the fork.
…</div></blockquote>

**Pull request merged**
