### PR TITLE
Feature/introduce desktop

### LINKED ISSUE #3203: Reorganize code sources, to make it possible to use views in desktop and fiddle projects

### PR DESCRIPTION
**Pull request by flexsurfer**
fixes #3203

The major change, I moved react components and svg slurp into a separate folder outside status-react sources, to be able to rewrite this code in other projects (electron and fiddle), i'm not super fan of this change, so if you have better ideas please tell, thanks

@MaxRis  @vkjr there is a new entry point for desktop `env.desktop.main`, and the same functionality as in electron

### CODE REVIEW

**Comment by jeluard** [comment]
@flexsurfer Can you give some context on why we want desktop in status-react codebase?

**Comment by flexsurfer** [comment]
@jeluard it's just one more target platform, we have ios and android but want to build status-react for desktop, the difference will be only in some views and styles, the rest of the code will be the same

**Comment by jeluard** [comment]
Have you considered using [reader conditionals](https://clojure.org/guides/reader_conditionals) for the svg function?

**Comment by flexsurfer** [comment]
What do you mean?

**Comment by jeluard** [comment]
Instead of moving to the `components` source folder, add some `:mobile` and `:desktop` conditions that would only be enabled when the associated build is triggered.

**Comment by flexsurfer** [comment]
this needed only for electron and fiddle, not for desktop, status-react "doesn't know" about these projects

**Comment by dmitryn** [comment]
@flexsurfer have you considered using `:modules` compiler option to split project source code?
https://clojurescript.org/reference/compiler-options#modules

<blockquote><div><strong><a href="https://clojurescript.org/reference/compiler-options#modules">ClojureScript - Compiler Options</a></strong></div></blockquote>

**Comment by flexsurfer** [comment]
yeah thanks @dmitryn so we have component icons, i want to use this component in different projects, but this component uses svg, but realisation for svg should be different
my idea just replace svg source in other projects

**Review by jeluard — APPROVED** [review]

**Pull request merged**
