### PR TITLE
Add default command scope

### LINKED ISSUE #2855: `status.response` no longer works
### User Story

As a developer, I want to be able to use response messages so that I can guide users intuitively through any chatbot interactions.

### Description

*Type*: Bug

*Summary*: `status.response` used to work well, now it doesn't.

#### Expected behavior
`status.response` returns a message based on a user's input.

#### Actual behavior
The user message that should trigger `status.response` just hangs at `Sending...`

### Reproduction

- Open Status
- Follow the steps outlined [here](https://github.com/andytudhope/StatusSeekers) to add Status Seekers locally
- Hit `/start` and follow through the prompts, accepting the price.
- Notice that trying to send `Yes` in order to accept the price hangs the conversation.

### Additional Information
* Status version: 0.9.12+
* Operating System: Android and iOS

#### Logs

Conversation Hangs on status.response

### PR DESCRIPTION
**Pull request by janherich**
[comment]: # (Please replace ... with your information. Remove < and >)
[comment]: # (To auto-close issue on merge, please insert the related issue number after # i.e fixes #566)

fixes #2855

### Summary:

[comment]: # (Summarise the problem and how the pull request solves it)
Since we introduced command scopes this summer, we didn't properly document them to the outside world, so people developing bots just omit them, which has unfortunate consequence of commands/responses not being available anymore (see our `DemoBot` for example).
Also while command scopes are nice and flexible, it feels like unnecessary to specify them always, where in most cases people writing bots just want commands defined by it to be available in chat with that bot and nothing more. 
This PR solves it by providing meaningful default scope which is used when command/response scope is not otherwise specified.

### Testing notes (optional):
Super basic testing of command/response availability, eq, make sure that no commands/responses disappeared, we still have console commands. send/request etc. available. Also observe that `DemoBot` is actually working again.

EDIT:
Esseentially, you need to have 
1. A build of Jan's branch running on your device/emulator (something it is not currently trivial for me to set up, otherwise I would just test myself and report).
2. Clone the repo in the link I provided in the issue to get the DApp to be tested. 
3. Follow the steps given to get the DApp running locally and connected to the build of Jan's branch (i.e. `npm install`, figure out the IP of your device emulator using `status-dev-cli scan` and then `IP=<device_ip> npm run start` and then navigate to the DApp that gets added by virtue of that start script.
4. Click `/start` to get the bot going and test that the full interaction works, rather than getting stuck on when you try to confirm that the offered price is ok (currently sending `yes` to the `status.response` question just results in that message hanging with `Sending...` displayed below it and no response from the bot)

status: ready

### CODE REVIEW

**Review by andytudhope — APPROVED** [review]
I'm not sure I can confidently review files like this just yet 😅 but it seems simple enough even for me to understand, LGTM.

**Review by flexsurfer — APPROVED** [review]

**Comment by yevh-berdnyk** [comment]
Blocked by https://github.com/status-im/status-react/issues/3217 - unable to add DApps/bots

**Comment by janherich** [comment]
As this change is quite small, and I'm 99,9% sure it doesn't break anything, I'm inclined to merge it and do further testing in develop - Main reason is that we have to fix #3217 before being able to truly test the feature and it will be easier and faster with just develop + #3217 branch then with two distinct non-develop branches.
Do you agree @oskarth @annadanchenko @yevh-berdnyk ?

**Comment by janherich** [comment]
Branch merged, will be tested in develop once #3217 is resolved

**Comment by annadanchenko** [comment]
@janherich ok let's move to develop and test after #3217

**Pull request merged**
