### PR TITLE
add github releases for mobile

### PR DESCRIPTION
**Pull request by jakubgs**
## Description

This PR adds GitHub release automation to `status-react` release builds. But in addition to that does a lot of general cleanup in Jenkinsfiles and Groovy scripts.

## Changes

* Adding a step for releasing mobile builds on GitHub using [github-release](https://github.com/aktau/github-release) tool
* Extracted `ghcmgr` related methods to `ci/ghcmgr.groovy`
* Extracted Jenkins related methods to `ci/jenkins.groovy`
* Extracted small utility methods to `ci/utils.groovy`
* Extracted GitHub related methods to `ci/ghcmgr.groovy`
* Added GitHub release methods to `ci/github.groovy`
* Dropped useless methods since all they do is call `make` or `lein`:
  - `cmn.runLint`, `cmn.runTests`, `cmn.clean`n
* Combined `notifyPRFailure` and `notifyPRSuccess` into `notifyPR`
* Improved `cmn.copyArts` so it gets just one argument which has both build name and number
* Dropped `Notify` stage from `Jenkinsfile.combined` since it does nothing(we build PRs separately)
* Replaced multiple calls to `cmn.getBuildType` with one call and `btype` variable
* Added `UseModernBuildSystem: N` to `export_options` for iOS release in Fastlane

## Notes
So far we only do proper releases of Mobile app so that's the one I've added. Because we have two different versions for mobile and desktop(`mobile_files/VERSION` and `desktop_files/VERSION`) we can't release those together, so I'm adding a `-mobile` suffix to distinguish them once we start doing desktop releases as well.

The releases created are __drafts__ and are not public unless made so manually in GitHub UI.
Repeated release builds for the same version delete the release draft from GitHub and re-create it.

## Status
__READY__

### CODE REVIEW

**Comment by oskarth** [comment]
What's the state of this PR @jakubgs? If it isn't been actively worked on (~1w), would it make sense to close it?

cc @mandrigin

**Comment by jakubgs** [comment]
It was blocked due to work on `0.9.33`.

**Comment by mandrigin** [comment]
@jakubgs isn't it done already?

**Comment by jakubgs** [comment]
@mandrigin for the most part, it's just there's been so much work with releases all the time I didn't have the time to test it properly. I guess I can do it today since no one will be bothered by release builds.

**Comment by jakubgs** [comment]
Manual release build that proves it works:
https://ci.status.im/job/status-react/job/manual/182/
Resulting release draft:
https://github.com/status-im/status-react/releases/tag/untagged-e12f1c8453d7b3e07c28

**Review by mandrigin — APPROVED** [review]
lgtm

**Review by pedropombeiro — APPROVED** [review]

**Comment by Serhy** [comment]
Builds made with Manual job from with nightly, release settings, as well as pr build (made "naturally") succeed. MacOS, Android-e2e, Android, iOS builds can be installed fine.

**Pull request merged**
