### PR TITLE
[#13086] stateofus.eth ENS username is not connected with chat key af…

### LINKED ISSUE #13086: stateofus.eth ENS username is not connected with chat key after purchasing
# Bug Report
This is regression of https://github.com/status-im/status-react/pull/13029
After purchasing ENS with internal domain (stateofus.eth) it appears not to be connected with chat key

Therefore, after ENS purchasing it is not possible initiate chat with such ENS. 
 
#### Expected behavior
ENS is connected to chat key after purchasing. During ENS purchasing process user is signing 2 transactions: one for registration of ENS and second for connecting ENS with chat key. 

#### Actual behaviour
During initial ENS purchase process no transaction for connecting ENS with chat key was required. Therefore, ENS is not connected to chat key after purchasing.  Subsequent adding ENS to user's Profile requires a transaction to connect username with chat key. 

### Reproduction

1) Open Status
2) Go to Profile tab => ENS => choose available ENS username => proceed with buying ENS
3) Pay attention if signing of transaction for connection of username with chat key is required. 

https://user-images.githubusercontent.com/97245802/153014210-797a7b0c-9ec9-4b32-baa9-ae45225e2608.mp4

photo_2022-02-01_16 22 46
[Status-debug-logs_4.zip](https://github.com/status-im/status-react/files/8024962/Status-debug-logs_4.zip)

### Additional Information

- Status version: it was tested on manual build https://status-im-nightlies.ams3.digitaloceanspaces.com/StatusIm-Mobile-220128-150900-bbf6d0-nightly-universal.apk
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by flexsurfer**
fixes #13086

### CODE REVIEW

**Review by Parveshdhull — APPROVED** [review]

**Comment by pavloburykh** [comment]
@flexsurfer thanx for PR. 

## ISSUE 1

Unable to proceed with connecting already registered ENS with chat key: (Proceed button [->] does not respond. 

In terms of testing I was trying to connect my ENS pavlo.statofus.eth with chat key, as this ENS has not been connected with chat key previously during purchase testing. 

Tested on manual Android build https://ci.status.im/job/status-react/job/manual/209/


https://user-images.githubusercontent.com/97245802/153591950-55a950cb-201f-4c82-8f3d-95b24698f5f3.mp4

[geth.log](https://github.com/status-im/status-react/files/8048590/geth.log)

**Comment by flexsurfer** [comment]
thanks @pavloburykh fixed

**Comment by pavloburykh** [comment]
@flexsurfer thank you for fix. 

Unfortunately, after signing of transaction to connect ENS pavlo.stateofus.eth with chat key, this ENS is still not connected with ENS. 
Adding ENS to my Profile still requires signing a transaction for connecting it to chat key. 

https://user-images.githubusercontent.com/97245802/153632678-6402d005-61c3-427c-be19-ba1412744e09.mp4

Link to signed transaction on etherscan https://etherscan.io/tx/0xd713d3b9a44a60885580cf6d96b7d93375443895180cc447d7c1cf67d8abf3d8

[geth.log](https://github.com/status-im/status-react/files/8050267/geth.log)

**Comment by flexsurfer** [comment]
thanks @pavloburykh should be fixed now

**Comment by pavloburykh** [comment]
@flexsurfer thanks for your fix! Please, take a look at ISSUE 2

## ISSUE 2

ENS pavlo.stateofus.eth appears to be connected to wrong cryptoaddress. 

Actual result: ENS pavlo.stateofus.eth is connected to 0x32878dd27c5ab43e36f54cbc2e06902cdae6c77f

Expected result: ENS pavlo.stateofus.eth should be connected to 0x527d22094166ad33e7523D2CBCa287798e149C7F as this is the address of wallet from which ENS purchase transaction was made.  

Link to ENS purchase transaction on etherscan https://etherscan.io/tx/0xdc2f1eeb53123285fdcddb4e095ee9c8b1231accbf2baa01f92bd368547f9746

photo_2022-02-14 16 13 42
photo_2022-02-14 16 17 39

https://user-images.githubusercontent.com/97245802/153888106-06bca793-cde2-4681-987d-d3e8c59418d3.mp4

**Comment by pavloburykh** [comment]
## UPDATE 
ISSUE 2 has been fixed by a hotfix which is already merged to develop. 

@flexsurfer could you please rebase current branch with develop when you have a chance so I can continue with testing the PR? Thanx

**Comment by pavloburykh** [comment]
@flexsurfer thanx for commits. 

### ISSUE 3 
Typo in word "proccess" (should be "process") in Warning modal message. 

photo_2022-02-18 17 33 05

**Comment by flexsurfer** [comment]
@pavloburykh thanks, fixed

**Comment by pavloburykh** [comment]
### ISSUE 4

ENS is not displayed in Profile after signing purchase transaction. 

Expected result: 
after signing purchase transaction, ENS should be added to Profile and have state "in progress" until transaction is confirmed. After transaction confirmation ENS automatically connected in user's Profile. 

Actual result: 
after signing purchase transaction, ENS is not displayed in Profile. After transaction is confirmed - ENS is not automatically connected in Profile. For adding ENS to Profile user needs to search for this ENS and add it manually. 

https://user-images.githubusercontent.com/97245802/154990192-e9b686d2-c8ed-4947-a0c6-bd697169360f.mp4

[geth.log](https://github.com/status-im/status-react/files/8110646/geth.log)

https://user-images.githubusercontent.com/97245802/154990212-4d425098-46ae-4643-8901-df8a477d45db.mp4

**Comment by flexsurfer** [comment]
thanks @pavloburykh fixed

**Comment by pavloburykh** [comment]
@flexsurfer thank you for fixes. Ready for merge.

**Pull request merged**
