### PR TITLE
Fix missing password prompt regression (#2925)

### PR DESCRIPTION
**Pull request by oskarth**
Always initialize LOG_LEVEL_STATUS_GO. To INFO in prod. This was unset.

I was reliably able to reproduce behavior in: https://github.com/status-im/status-react/issues/2925 by toggling LOG_LEVEL_STATUS_GO flag from INFO to unset back and forth.

## Regression and how to avoid it

Assuming this indeed fixes the issue:

Regression was introduced in https://github.com/status-im/status-react/pull/2803 and noted in code review, but only after it was merged: https://github.com/status-im/status-react/pull/2803#discussion_r159733193

Not sure about specific root cause, other than that (a) this seems to fix regression (b) it is not a good idea to leave uninitialized things.

This points to a few things:

- General: don't leave variables uninitialized, always have sane defaults.
- Code review: consider not allowing modifications after review to avoid regressions in patches
- Testing: Consider testing multiple environments when behavior is introduced
- Oskar: trust intuition and push more when something smells wrong

status: ready

### CODE REVIEW

**Comment by oskarth** [comment]
Cherry-picked to release branch too. https://github.com/status-im/status-react/pull/2919

**Review by flexsurfer — APPROVED** [review]

**Review by jeluard — APPROVED** [review]
Makes sense! @PombeirP any idea why this would trigger the described behavior?

**Review by yenda — APPROVED** [review]

**Comment by pedropombeiro** [comment]
@jeluard My initial thought was that maybe the empty log level value was being passed to the native side as `nil`, and in doing so causing a fault in [line 204 of RTCStatus](https://github.com/status-im/status-react/blob/develop/modules/react-native-status/ios/RCTStatus/RCTStatus.m#L204), but that wouldn't explain why the Android app only fails intermittently, since it should suffer from the same problem in [line 185 of StatusModule](https://github.com/status-im/status-react/blob/develop/modules/react-native-status./android/src/main/java/im/status/ethereum/module/StatusModule.java#L185). I'd really love to understand why this is happening though, don't fancy leaving it like this without understanding the root cause.

I'd suggest we go one step further with this PR by either:
- Validating log levels, so that empty/invalid entries are not allowed.
- or - still allow an empty log level, but in that case pass a default level such as `FATAL` in the JSON config and set `LogEnabled` to false.

**Comment by oskarth** [comment]
@PombeirP 
> I'd suggest we go one step further with this PR by either:

We can definitely do this, but not right now. Today is bug fixing day and we have a release coming up later this week. Feel free to create an issue and we can investigate further if you want!

**Comment by pedropombeiro** [comment]
@jeluard found the source of this bug. The empty value causes the JSON validation [here](https://github.com/status-im/status-go/blob/develop/geth/params/config.go#L292) to fail (see in [logs](https://gist.github.com/oskarth/d472e5b42503e62e5df979a6662ddbe4#file-gistfile1-txt-L344) from @oskarth):

```
2018-01-08 16:11:48.903783+0900 StatusIm[68569:15960379] logUrlPath /Users/oskarth/Library/Developer/CoreSimulator/Devices/146E42AA-FA0F-4CDD-9DAA-C4B47AE74292/data/Containers/Data/Application/D34C9E85-4169-4A49-8BBD-1C22D60848B9/Documents/ethereum/testnet_rpc/geth.log
Key: 'NodeConfig.LogLevel' Error:Field validation for 'LogLevel' failed on the 'eq=ERROR|eq=WARNING|eq=INFO|eq=DEBUG|eq=TRACE' tag
2018-01-08 16:11:48.920304+0900 StatusIm[68569:15958614] StartNode result {"error":"Key: 'NodeConfig.LogLevel' Error:Field validation for 'LogLevel' failed on the 'eq=ERROR|eq=WARNING|eq=INFO|eq=DEBUG|eq=TRACE' tag"}
```

Looks like I missed taking the new value into consideration for the JSON validation in the initial PR :-(. I suggest that I add a check so that if there's an empty value, we just replace it for a valid value such as `ERROR` in the JSON that gets passed to `StartNode`. cc @oskarth 
 
One thing that bothers me is that it was pretty easy for this log entry to be missed. Wish we could make it more visible somehow. It doesn't seem like that log writes out the log level, for instance. That could help in making entries like this stand out more (especially when viewed in a log viewer app).

**Comment by jeluard** [comment]
@PombeirP Awesome! Your suggestion makes complete sense.

**Comment by pedropombeiro** [comment]
@jeluard How should I go about this? Is it OK to create a new PR against https://github.com/status-im/status-react/issues/2925?

**Comment by jeluard** [comment]
@PombeirP Sounds good!

**Comment by oskarth** [comment]
@asemiankevich confirmed it had been tested and works, also in release branch

**Pull request merged**
