### PR TITLE
implemented webview using react-native features.

### LINKED ISSUE #3046: Implement webview using react-native features
### User Story

As a developer, I want to use supported libraries

### Description

*Type*: Feature

Our webview support currently relies on an [unsupported library](https://github.com/alinz/react-native-webview-bridge). 
Migrate to the native react-native [webview support](https://facebook.github.io/react-native/docs/webview.html).

Note that our [fork](https://github.com/status-im/react-native-webview-bridge) contains a number of hooks and hacks which have to be considered.

### LINKED ISSUE #3175: Accents characters (è, ù) in webview are shown as question marks [Android]
### Description
[comment]: # (Feature or Bug? i.e Type: Bug)
_Type_: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
_Summary_: Only on Android: accents characters (è, ù) are shown as question marks on webpages if opened in Status app. Same pages if open on same device via Chrome or Android Web browser look ok.
screenshot!UNITO-UNDERSCORE!20180131-101709

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
Accents characters (è, ù) on webpages are shown

#### Actual behavior
[comment]: # (Describe what actually happened.)
Accents characters (è, ù) are shown as question marks

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)
https://app.testfairy.com/projects/4803622-status/builds/7599983/sessions/2/?accessToken=-jxDfarrj/ngtQ3frMvmYZLejaw

* Open Status and sign in
* Tap on + to open "Start new chat" screen
* Tap on Open URL
* paste this url http://www.lantidiplomatico.it/dettnews-un_eroismo_sovrumano_anche_per_i_nemici_il_ruolo_poco_conosciuto_dellurss_nella_seconda_guerra_mondiale/11_22978/ and tap on checkmark on keyboard
* After page is loaded check if there are any question marks shown instead of characters in the article text

### Additional Information
[comment]: # (Please do your best to fill this out.)

* Status version: nightly build from January 31. 0.9.10-621-g8f1bc58b+
* Operating System: Android only. Real Samsung Galaxy S6, Android 6.0.1 and Google Pixel XL, Android 8.1.0

### PR DESCRIPTION
**Pull request by ghost**
Fixes #3046 
Fixes #3175
### Steps to test:
- Open Status
- Use webview

status: ready

### CODE REVIEW

**Comment by jeluard** [comment]
What about things that were added in our `webview` bridge fork? Thinks like permission handling?

**Comment by audriu** [comment]
@jeluard  do we still use location permission?

**Comment by jeluard** [comment]
@audriu Geolocation? no

**Comment by jeluard** [comment]
Actually might still be needed for DApps using this permission @rasom

**Pull request closed without merging**
