### PR TITLE
Desktop popup

### PR DESCRIPTION
**Pull request by flexsurfer**
Contribute to  #4434 (only functionality without design)

Introduced popup for "+" menu and 3 new screens (1-1, public, group chat)

image

**This PR doesn't introduce new design or new functionality for group chats**

### CODE REVIEW

**Comment by ghost** [comment]
### Pull Request Checklist
- [x] Have you updated the documentation, if impacted (e.g. [docs.status.im](https://docs.status.im/docs/build_status.html))?

**Comment by chadyj** [comment]
Holy moly that is fantastic!  Makes desktop feel 500% less janky!
I tested on Mac and it worked like a treat :)

**Review by yenda — APPROVED** [review]

**Review by vitvly — APPROVED** [review]
Cool! :)

**Review by vkjr — APPROVED** [review]

**Comment by churik** [comment]
Tested on Windows 10 Home, Linux Ubuntu 18.04, Mac Os Mojave

**Review by rcullito — APPROVED** [review]
👏

**Comment by chadyj** [comment]
🍻

**Pull request merged**
