### PR TITLE
Sync indicator (#312)

### PR DESCRIPTION
**Pull request by alwx**
It may seem a bit overcomplicated, but it isn't :)

The main and most important part of it is `:initialize-sync-listener` handler in `status-im.protocol.handlers` namespace. Here we add a listener that switches states when a new portion of information comes (the main purpose of all this "overcomplication" is to make animations look smooth and also to avoid flickering when the information comes too fast).
The easiest way to test it without this listener is by executing the combination of commands manually, like that:
```
(js/setTimeout #(dispatch [:set :sync-state :pending]) 1500)
(js/setTimeout #(dispatch [:set :sync-state :offline]) 6000)
(js/setTimeout #(dispatch [:set :sync-state :pending]) 9500)
(js/setTimeout #(dispatch [:set :sync-state :synced]) 12500)
```

### CODE REVIEW

**Comment by rasom** [comment]
Don't know how it is related to PR but, for some reason, request's input is broken. Works fine in `develop`

**Comment by rasom** [comment]
Console's icon disappeared

**Comment by alwx** [comment]
React Native doesn't support z-index property completely thus everything works fine on iOS, but not on Android :( I've updated the PR and made it work without z-index.

**Comment by rasom** [comment]
I removed chain data and then it infinitely blinks (on adnroid) :

status

**Comment by jarradh** [comment]
My guess @alwx hadn't gotten around to the following logic;
`highestBlock - currentBlock > BLOCKS_PER_HOUR` then show syncing
where BLOCKS_PER_HOURS would be around 120 (kind of arbritrary (7200/24 - 1440/24) / 2 = 120)

**Comment by jarradh** [comment]
Ah I see, because of course `highestBlock` and `currentBlock` are catching up with one another during initial sync.  Unclear to me whats the best solution, waiting arbitrary amount of time seems..not good

**Comment by alwx** [comment]
Fixed the core logic. Now everything works without this strange flickering.

**Pull request merged**
