### PR TITLE
Handle wrong pairing password

### LINKED ISSUE #7908: "Enter pair code" field partially or fully overlapped (depends on text size) by keyboard
### Description
_Type_: Bug

_Summary_: on "Enter pair code" screen input field partially (with default "Medium" text size) or fully (with "Large" text size) overlapped by keyboard and it is not scrollable. 

#### Expected behavior
Can see what I'm typing or can scroll

### Reproduction
_Prerequisites:_ have initialized card

* Open Status
* Tap on "I already have an account"
* Select keycard
* Hold your card to start process

### Additional Information
[comment]: # (Please do your best to fill this out.)

* Status version: https://status-im-prs.ams3.digitaloceanspaces.com/StatusIm-190403-181003-8b6ae2-pr.apk
* Operating System: Android

### LINKED ISSUE #7909: "Invalid card cryptogram" after entering wrong code when pairing card
### Description
_Type_: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
_Summary_: after entering wrong pairing code when pairing code instead of validation error "Invalid card cryptogram" is shown and to start again you need manually get back on "Choose an authentication method to protect your account" or relaunch app. If you keep tapping the card, this error is constantly shown, tap on "try again" does nothing visible to user

#### Expected behavior
Validation error that code is invalid.

### Reproduction
_Prerequisites:_ have initialized card

* Open Status
* Tap on "I already have an account"
* Select keycard
* Hold your card to start process
* Enter wrong pairing code. 

### Additional Information
[comment]: # (Please do your best to fill this out.)

* Status version: https://status-im-prs.ams3.digitaloceanspaces.com/StatusIm-190403-181003-8b6ae2-pr.apk
* Operating System: Android

### PR DESCRIPTION
**Pull request by dmitryn**
fixes #7909 
fixes #7908 

### Summary

* show "invalid pairing password" message when invalid pairing password entered
* wrap view intro scroll view to fit content 

status: ready

### CODE REVIEW

**Review by flexsurfer — APPROVED** [review]

**Review by goranjovic — APPROVED** [review]

**Comment by asemiankevich** [comment]
@dmitryn is keycard flag enabled here? https://status-im-prs.ams3.digitaloceanspaces.com/StatusIm-190416-094027-93049c-pr.apk this apk does not allow me to create account with a card

**Comment by dmitryn** [comment]
@asemiankevich sorry, just enabled the flag.

**Comment by asemiankevich** [comment]
@dmitryn [Something went wrong] when PIN is confirmed

image

**Comment by dmitryn** [comment]
@asemiankevich weird, as i only changed code related to pairing (Added scrolling to Enter pair code screen and handling wrong pairing password entered). I also see this error in some of other opened PRs.

**Comment by dmitryn** [comment]
Hopefully fix from https://github.com/status-im/status-react/pull/7942 should be also applied here if we talk about error on PIN confirmation during installation.

**Comment by asemiankevich** [comment]
@dmitryn not sure what is going on with the PRs, now in this one i can't proceed, recovery account flow sends me always back to main screen when i tap a card.

```
2019-04-24 15:22:52.815 26161-26216/? D/ReactNativeJS: DEBUG [status-im.data-store.realm.core:199] - Opening base realm... (first run)
2019-04-24 15:22:52.818 26161-26216/? I/ReactNativeJS: INFO [status-im.data-store.realm.core:177] - migrate-realm
2019-04-24 15:22:52.838 26161-26216/? I/ReactNativeJS: INFO [status-im.data-store.realm.core:148] - migrate schemas -1
2019-04-24 15:22:52.842 26161-26216/? D/ReactNativeJS: DEBUG [status-im.data-store.realm.core:47] - Opening realm at  /data/user/0/im.status.ethereum.pr/files/../no_backup/realm/default.realm ...
2019-04-24 15:22:52.862 26161-26216/? D/ReactNativeJS: DEBUG [status-im.data-store.realm.core:49] - Using encryption key...
2019-04-24 15:22:52.874 26161-26216/? D/ReactNativeJS: DEBUG [status-im.data-store.realm.core:203] - Created @base-realm
2019-04-24 15:22:52.881 26161-26216/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:34] - Handling re-frame event:  :init.callback/init-store-success
2019-04-24 15:22:52.892 26161-26216/? D/ReactNativeJS: DEBUG [status-im.ui.screens.navigation:19] - current view-id  nil changing to  :intro
2019-04-24 15:22:52.899 26161-26216/? D/ReactNativeJS: DEBUG [status-im.ui.screens.navigation:98] - :navigate-to-clean :intro
2019-04-24 15:22:52.937 26161-26216/? D/ReactNativeJS: DEBUG [status-im.ui.screens.routing.core:179] - :component :intro
2019-04-24 15:22:53.680 26161-26216/? D/ReactNativeJS: DEBUG [status-im.ui.screens.views:72] - :main-component-did-update :intro
2019-04-24 15:22:53.689 26161-26216/? D/ReactNativeJS: DEBUG [status-im.ui.screens.routing.core:30] - :on-will-focus :intro
2019-04-24 15:22:53.700 26161-26216/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:34] - Handling re-frame event:  :screens/on-will-focus
2019-04-24 15:22:55.029 26161-26216/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:34] - Handling re-frame event:  :accounts.recover.ui/recover-account-button-pressed
2019-04-24 15:22:55.040 26161-26216/? D/ReactNativeJS: DEBUG [status-im.ui.screens.navigation:80] - :navigate-to :hardwallet-authentication-method
2019-04-24 15:22:55.372 26161-26216/? D/ReactNativeJS: DEBUG [status-im.ui.screens.routing.core:30] - :on-will-focus :hardwallet-authentication-method
2019-04-24 15:22:55.383 26161-26216/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:34] - Handling re-frame event:  :screens/on-will-focus
2019-04-24 15:22:55.398 26161-26216/? D/ReactNativeJS: DEBUG [status-im.ui.screens.views:72] - :main-component-did-update :hardwallet-authentication-method
2019-04-24 15:22:56.672 26161-26216/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:34] - Handling re-frame event:  :hardwallet.ui/status-hardwallet-option-pressed
2019-04-24 15:22:56.680 26161-26216/? D/ReactNativeJS: DEBUG [status-im.ui.screens.navigation:80] - :navigate-to :hardwallet-connect
2019-04-24 15:22:56.842 26161-26216/? D/ReactNativeJS: DEBUG [status-im.ui.screens.routing.core:30] - :on-will-focus :hardwallet-connect
```
maybe the build is old or whatever.. Please, take a look

**Comment by dmitryn** [comment]
@asemiankevich should be fixed now.

 I was redirected to "Pair" screen and then to "Enter pairing password" screen using keycard with account and another mobile device.

**Pull request merged**
