### PR TITLE
fix App crashes when pressing on community link

### LINKED ISSUE #16018: App crashes when pressing on community link
### Bug

https://github.com/status-im/status-mobile/assets/17097240/4e5504be-9b97-4328-b5d6-914b9c7f9aad

### PR DESCRIPTION
**Pull request by Parveshdhull**
fixes: https://github.com/status-im/status-mobile/issues/16018

status: ready

### CODE REVIEW

**Review by siddarthkay — APPROVED** [review]

**Review by flexsurfer — APPROVED** [review]

**Comment by pavloburykh** [comment]
@Parveshdhull thanx for the PR! Please, take a look at the following issue. 

### ISSUE 1 Following community link does not redirect to community screen

Expample of community link: https://join.status.im/c/zQ3shapbjWPruNK89YMEtXA1n7jnb777v8wJxSaYrL4LTGVu5 This link was copied from one of communities on desktop app. 

**Steps:** 

1. Send community link in chat/community channel
2. Tap the link
3. See if User is redirected to community screen

**Actual result:** 

**Android:** 
- Following link private chat opens screen with message "Community admins will review your reauest"
-  Following link in community channel does nothing. Closing current channel leads to the screen with message "Community admins will review your reauest". Logo of current joined comminity is displayed on the screen. 

https://github.com/status-im/status-mobile/assets/97245802/8398901f-0e2e-4e1e-a7c8-842153b95d73

**IOS:**
- Following link private chat opens screen with message "Community admins will review your reauest"
-  Following link in community channel leads to the screen with message "Community admins will review your reauest". Logo of current joined comminity is displayed on the screen. 


https://github.com/status-im/status-mobile/assets/97245802/0f21f15e-dfd3-4021-bbfa-098431e63c4b

**Comment by pavloburykh** [comment]
@Parveshdhull is this one ready for re-test?

**Comment by Parveshdhull** [comment]
hi @pavloburykh, Thank you very much for testing the PR.
I fixed the crash but for some reason, the community is not fetched. And that's why once the community screen is opened, it shows the above the screen.

Not sure what is the issue. @cammellos Please can you take a look at that.

**Comment by pavloburykh** [comment]
> hi @pavloburykh, Thank you very much for testing the PR. I fixed the crash but for some reason, the community is not fetched. And that's why once the community screen is opened, it shows the above the screen.
> 
> Not sure what is the issue, maybe @cammellos can take a look at that.

Thanx @Parveshdhull ! Take your time. Feel free to ping me up when re-testing will be needed.

**Comment by Parveshdhull** [comment]
Hi @ilmotta,

In the old ui when we were creating a preview of the community links, we used to also fetch community using `:chat.ui/resolve-community-info` in the client itself.

Do you know how we are handling (or going to handle) in the new UI?
Are we going to resolve the community in status-go itself? Currently, it's not resolved, even if the preview is created community is just nil.

Also, cc @qfrank

**Comment by qfrank** [comment]
not sure, let me take a look 🧐

**Comment by ilmotta** [comment]
> In the old ui when we were creating a preview of the community links, we used to also fetch community using `:chat.ui/resolve-community-info` in the client itself.

@Parveshdhull, the new link preview feature completely ignores the need for generating community previews (for the moment). I believe the code you mention still exists (for example the old view is still there in `status-im2.contexts.chat.messages.link-preview.view`).

> Do you know how we are handling (or going to handle) in the new UI? Are we going to resolve the community in status-go itself? Currently, it's not resolved, even if the preview is created community is just nil.

IMO resolving the community in status-go would be ideal, but I haven't looked at the existing code at all, so it's just my guess.

**Comment by qfrank** [comment]
@Parveshdhull is this community(https://join.status.im/c/zQ3shapbjWPruNK89YMEtXA1n7jnb777v8wJxSaYrL4LTGVu5) created > 1 month ago? I tried calling API in status-go maually, it did return nothing by searching community id.

**Comment by qfrank** [comment]
> Do you know how we are handling (or going to handle) in the new UI?

I've no idea 

> Are we going to resolve the community in status-go itself?

we have some relate APIs in status-go to resolve the community , e.g. `RequestCommunityInfoFromMailserver` `RequestCommunityInfoFromMailserverAsync` , we also have API `ShareCommunity` which support share community to users directly so that frontend don't have to call backend to resolve community info again.

IMO, tested issues should not be relate to this PR 🙂

**Comment by Parveshdhull** [comment]
hi @qfrank,  Thank you very much for looking into this

**Comment by Parveshdhull** [comment]
hi @pavloburykh as the issue with fetched community is not related to original issue itself (and currently don't know how to fix it), how we should handle it?

We can close PR and add related issue in original issue. Or we can merge PR with above message(Community admins will review your request) and report that separately? Or we can merge PR with crash fix, but don't do anything when link is pressed?

**Comment by pavloburykh** [comment]
> Or we can merge PR with above message(Community admins will review your request) and report that separately

Hi @Parveshdhull! This option sounds good to me. Crash will be fixed by this PR and broken community page will be handled separately.

**Pull request merged**
