### PR TITLE
remove views pre-rendering hack

### PR DESCRIPTION
**Pull request by rasom**
As was discussed in slack, it seems that navigation performance on both iphone 6 and galaxy note 4 (which are minimal devices) is acceptable without this hack.

Things to test:
1) navigation between main tabs
2) navigation from chats-list to chat and back
3) briefly others paths 

status: ready

### CODE REVIEW

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/e77b3h for branch PR-4422

<blockquote><div><strong><a href="https://i.diawi.com/e77b3h">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/2okzKq for branch PR-4422

<blockquote><div><strong><a href="https://i.diawi.com/2okzKq">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Review by janherich — APPROVED** [review]

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/8ijGXF for branch PR-4422

<blockquote><div><strong><a href="https://i.diawi.com/8ijGXF">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/FT94C3 for branch PR-4422

<blockquote><div><strong><a href="https://i.diawi.com/FT94C3">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Review by jeluard — APPROVED** [review]

**Pull request merged**
