### PR TITLE
[#5452][desktop] Add help center in profile menu

### LINKED ISSUE #5452: Add "Frequently added questions" to Menu
### Description
*Type*: Feature

*Summary*: to help users get the better experience we need to add FAQ  to Profile. In mobile it is presented in Profile > Help Center > Frequently asked questions.

img_df4d840da4b3-1 jpeg 2018-08-10 15-20-06
If you tap on it > WIKI page with FAQ is opened.

### Solution
[comment]: # (Please summarise the solution and provide a task list on what needs to be fixed.)
*Summary*: 

Same as mobile:
- On profile tab, add `Need help?` item
-  Add submenu:
  - Frequently asked questions (links to https://status.im/docs/FAQ-desktop.html)
  - Ask a question or report a bug (links to #status)

### PR DESCRIPTION
**Pull request by yenda**
fix #5452 

screenshot from 2018-12-14 16-58-15

status: ready

### CODE REVIEW

**Review by vitvly — APPROVED** [review]

**Comment by churik** [comment]
@yenda 
FAQ should redirect to https://status.im/docs/FAQ-desktop.html, not to https://status.im/docs/FAQs.html



<blockquote><div><strong><a href="https://status.im/docs/FAQ-desktop.html">Status, a Mobile Client for Ethereum 2.0</a></strong></div></blockquote>
<blockquote><div><strong><a href="https://status.im/docs/FAQs.html">Status, a Mobile Client for Ethereum 2.0</a></strong></div></blockquote>

**Comment by vkjr** [comment]
@churik, @yenda  what do you think about also changing the default chat for `Ask question or report a bug`?
#status channel is quite noisy. I'd suggest to create a specific one for desktop support.

**Comment by churik** [comment]
@vkjr I'm OK if issues will be posted to status-desktop

**Comment by vkjr** [comment]
#status-desktop in fact should be retired, because for desktop swarm we have #318-desktop now.
I think it would be nice to have something like #status-desktop-support, with name that clearly speaks about purpose

**Comment by yenda** [comment]
@churik @vkjr I updated the FAQ link and chat to #status-desktop on desktop

**Review by vkjr — APPROVED** [review]

**Comment by churik** [comment]
@yenda please, rebase it to the last develop

**Comment by yenda** [comment]
@chu it was already rebased an hour ago

**Comment by churik** [comment]
@yenda please, merge it to develop and to `release/desktop/0.9.0` branch.
Have no idea why it was in Contributor

**Comment by vitvly** [comment]
@churik @yenda merged and cherry-picked to release branch

**Pull request merged**
