### PR TITLE
[WIP] Android Only `react-native` Upgrade to 0.73.x

### PR DESCRIPTION
**Pull request by siddarthkay**
This PR contains only Android side changes for upgrading react-native to 0.73.x

do not review yet.

This PR is just made to test CI behaviour on my changes.

status: wip

### CODE REVIEW

**Comment by siddarthkay** [comment]
@status-im/mobile-qa : I am running E2E here just to see the effect of the upgrade on Android side.
I won't be merging this PR, this PR is just made to verify CI stages.

**Comment by pavloburykh** [comment]
@siddarthkay hello. Please, rebase your PR, otherwise you will not receive valid e2e results. PR is 149 commits behind develop.

**Comment by siddarthkay** [comment]
> @siddarthkay hello. Please, rebase your PR, otherwise you will not receive valid e2e results. PR is 149 commits behind develop.

Hey @pavloburykh : 
Sorry I'll move this PR out from E2E lane.
This PR was made just to store the Android side of upgrade journey, we won't be merging this one.

Thank you

**Comment by siddarthkay** [comment]
closed in favour of https://github.com/status-im/status-mobile/pull/18563

**Pull request closed without merging**
