### PR TITLE
[Fixes: #11105][Fixes: #9895] Fix transaction unread counter and watching requests

### PR DESCRIPTION
**Pull request by cammellos**
This commit fixes two issues:

- Unread counter was wrongly calculated when hiding messages
- Only the default account was watched for command transactions

status: ready

### CODE REVIEW

**Review by flexsurfer — APPROVED** [review]

**Comment by churik** [comment]
@cammellos 
issue #9895 is still reproducible in this PR (tried with tokens and ETH,in android and IOS - no luck)
IMAGE 2020-12-08 12:50:17
Receivieng 0.0000002 SALT to 'Account 1'
[status_logs.zip](https://github.com/status-im/status-react/files/5659066/status_logs.zip)

**Comment by cammellos** [comment]
@churik thanks, I'll try to replicate as it worked locally, but I must have missed something. 
Would you mind to replicate with debug logs on please if you have time? (otherwise no worries)
Thanks!

**Comment by churik** [comment]
UPD: seems the issue is gone after relogin.
So it is reproducible only for commands messages which were created after account creation (or recovering) and until 1t relogin.
All subsequent commands messages will update their states as expected.
That's the reason why I can't attach `DEBUG` logs - after that issue will not reproducible anymore.

**Comment by churik** [comment]
@cammellos issue is not reproducible anymore on both mainnet and ropsten builds (tried ETH and tokens) 
Maybe it is related to new transaction history fetching methods.

Sorry for confusion.
Ready to be merged.

**Pull request merged**
