### PR TITLE
Fix collectibles scroll crash

### LINKED ISSUE #18644: [IOS] App crashes and unsmooth scrolling in the collectibles tab
### Steps:
1. Recover a user account with a substantial number of collectibles (be aware, collectibles sometimes are not displayed. You need to wait at least 1 minute after recovering and relogin https://github.com/status-im/status-mobile/issues/18613)
2. add watch only account `0x8d2413447ff297d30bdc475f6d5cb00254685aae`
3. Open  "collectibles" tab to see all collectibles available for all added adresses
4. Scroll through the collectibles list consistently.

### Actual result:
Unsmooth scrolling of collectibles, the app crashes during the process of scrolling collectibles

https://github.com/status-im/status-mobile/assets/52490791/5d378dff-8ac8-4ecb-973e-53982e042c98

### Expected result:
The scrolling of collectibles should be smooth, and the app should not crash during the scrolling process.

### Device:
iPhone 11 Pro max, IOS 16

### Logs:
[logs.zip](https://github.com/status-im/status-mobile/files/14051089/logs.zip)

### PR DESCRIPTION
**Pull request by clauxx**
fixes #18644 

### Summary

The crash seems to come from using `react-native-fast-image`, caused by excessive memory usage. There's an [old issue](https://github.com/DylanVann/react-native-fast-image/issues/195) there, where rendering tons of large images in a flatlist causes a huge memory jump (usually from quick scrolling) and a crash. The core cause though seems to be the size/resolution of our images and GIFs, some of which can easily exceed 10MB.

This is a temporary fix by going back to using the RN image component until we find a way to show the images without sacrificing performance. Ideally, we'd generate lower-res previews on status-go that would be displayed in the flatlist. 

#### Platforms

- Android
- iOS

##### Functional

- collectibles tab

##### Non-functional

- memory performance

### Steps to test

> Follow the steps from the [original issue](https://github.com/status-im/status-mobile/issues/18644#issue-2102272264)

status: ready

### CODE REVIEW

**Review by smohamedjavid — APPROVED** [review]
Thank you for the quick fix @clauxx 🙏

**Comment by ulisesmac** [comment]
@clauxx
Thanks for fixing this issue.

Probably another fix we should first try (before trying to implement something in status-go) is changing the window size in the flat-list.

**Comment by clauxx** [comment]
> @clauxx Thanks for fixing this issue.
> 
> Probably another fix we should first try (before trying to implement something in status-go) is changing the window size in the flat-list.

@ulisesmac could you explain? Not sure how that will help

**Comment by ulisesmac** [comment]
> > @clauxx Thanks for fixing this issue.
> > Probably another fix we should first try (before trying to implement something in status-go) is changing the window size in the flat-list.
> 
> @ulisesmac could you explain? Not sure how that will help

It'd be good to check if the app is breaking because of the cache size or because of too many images/gifs/svgs being drawn at the same time.

We could use change the window size (reduce it) to check if it solves the problem:
https://reactnative.dev/docs/optimizing-flatlist-configuration#windowsize

**Comment by clauxx** [comment]
> > > @clauxx Thanks for fixing this issue.
> > > Probably another fix we should first try (before trying to implement something in status-go) is changing the window size in the flat-list.
> > 
> > 
> > @ulisesmac could you explain? Not sure how that will help
> 
> It'd be good to check if the app is breaking because of the cache size or because of too many images/gifs/svgs being drawn at the same time.
> 
> We could use change the window size (reduce it) to check if it solves the problem: https://reactnative.dev/docs/optimizing-flatlist-configuration#windowsize

It will help with the performance, but will add more blank space while scrolling and wouldn't solve the memory issue of rendering images and gifs that are sometimes too heavy (>10MB) when using `fast-image`. I think it'll be good to both find a sweet spot for the window size and reduce the size of the images we show in the list.

**Comment by clauxx** [comment]
@status-im/mobile-qa I moved it to E2E but the tests didn't show up for some reason :(

**Comment by VolodLytvynenko** [comment]
> @status-im/mobile-qa I moved it to E2E but the tests didn't show up for some reason :(


@clauxx Thank you. The e2e tests were not triggered again. I have rerun it one more time. Now, I see the run in a queue. The result should be ready in 40-50 minutes

**Comment by mariia-skrypnyk** [comment]
Hi @clauxx !
Thanks for your fix!
PR tested and can be merged.
Failed tests are not related to it.

**Pull request merged**
