### PR TITLE
Fix console responses

### LINKED ISSUE #4443: No response messages in Console
***Type***: Bug

***Summary***: No response message to any command(message). However, after re-login all message responses are shown. /faucet request or any of web3 requests returns nothing. 

**Note**: it's only messages does not appear: for instance, funds are received when request /faucet fine. 
The issue introduced with #4221 

#### Expected behavior
Response messages appear to requests sent in Console

#### Actual behavior
No response messages appear to requests sent in Console

screen shot 2018-05-24 at 18 19 16

### Reproduction

- Open Status and create an account
- Enable Dev mode from Profile so Console could be accessed from Home
- Navigate to Console
- Send /faucet request
- Send web3.eth.blockNumber 
- Send `hello`
- (Optionally): relogin to account and navigate to Console. All responses are visible in that case.

### Additional Information
* Status version: Develop (403rd Jenkins build) 
* Operating System: Android and iOS

#### Logs
TF session with logs: https://app.testfairy.com/projects/4803622-status/builds/8357948/sessions/52/?accessToken=YnwTYuFA0YHP4Qql75xwf9Wevz4

<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803622-status/builds/8357948/sessions/52/?accessToken=YnwTYuFA0YHP4Qql75xwf9Wevz4">TestFairy: Status build-6010+ (6010) @52</a></strong></div></blockquote>

### PR DESCRIPTION
**Pull request by janherich**
[comment]: # (Please replace ... with your information. Remove < and >)
[comment]: # (To auto-close issue on merge, please insert the related issue number after # i.e fixes #566)

fixes #4443 

### Summary:

In previous perf PR (introducing message-groups), the requirements of the `:chat-received-message/add` changed little bit, so the function requires knowledge whether message to be added is also to be shown or not (`:show?`) and timestamp is now required for proper grouping as well (`:timestamp` key). 
This PR merely updates the console code to adhere to those requirements and so, solves the bug

### Steps to test:
Test that the bug is not happening anymore

status: ready

### CODE REVIEW

**Review by yenda — APPROVED** [review]

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/2t1f1t for branch PR-4495

**Review by rasom — APPROVED** [review]

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/LZM5fK for branch PR-4495

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/z1vbWz for branch PR-4495

<blockquote><div><strong><a href="https://i.diawi.com/z1vbWz">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/dsA8ja for branch PR-4495

<blockquote><div><strong><a href="https://i.diawi.com/dsA8ja">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by Serhy** [comment]
Looks good! Everything works and no regressions here (failed test_public_chat_management will be fixed separately)

**Pull request merged**
