### PR TITLE
cleanup and i18n revert

### PR DESCRIPTION
**Pull request by flexsurfer**
revert i18n:
i18n namespace is a wrapper for i18n.js library, so it shouldn't know anything about status

cleanup warnings and todos

### CODE REVIEW

**Review by OmarBasem — APPROVED** [review]

**Review by J-Son89 — APPROVED** [review]
Nice one! :D

**Comment by pavloburykh** [comment]
Hey @flexsurfer ! Thanx for the PR. Could you please provide some QA notes what should be tested in terms of this changes, which areas have been impacted and might have a regression? Thanx!

**Comment by flexsurfer** [comment]
hey @pavloburykh just briefly look at the app if it's ok

**Comment by pavloburykh** [comment]
@flexsurfer LGTM except one issue on IOS. 

I am not sure if it is PR related, but I have tried several times on latest nightly and failed to reproduce it. 

So maybe you can say if it can be related to PR changes or not. 

### ISSUE 1 Cancel/Request to join buttons are not responding on IOS

Steps: 

1. User A creates community and invites User B (IOS) to this community
2. User B goes to Discover community - finds new community - opens community screen - taps Request to join community
3. On Community rules screen tap Cancel or Request to join buttons
4. Observe the result

**Actual result:** buttons are not responding

**Expected result:** buttons are responding  


https://user-images.githubusercontent.com/97245802/210414251-c05c9dc2-2c5d-4d60-9c7a-aa086412e59c.mp4

[geth.log](https://github.com/status-im/status-mobile/files/10338740/geth.log)
[Status.log](https://github.com/status-im/status-mobile/files/10338741/Status.log)

**Comment by J-Son89** [comment]
> @flexsurfer LGTM except one issue on IOS. 
> 
> 
> 
> I am not sure if it is PR related, but I have tried several times on latest nightly and failed to reproduce it. 
> 
> 
> 
> So maybe you can say if it can be related to PR changes or not. 
> 
> 
> 
> ### ISSUE 1 Cancel/Request to join buttons are not responding on IOS
> 
> 
> 
> Steps: 
> 
> 
> 
> 1. User A creates community and invites User B (IOS) to this community
> 
> 2. User B goes to Discover community - finds new community - opens community screen - taps Request to join community
> 
> 3. On Community rules screen tap Cancel or Request to join buttons
> 
> 4. Observe the result
> 
> 
> 
> **Actual result:** buttons are not responding
> 
> 
> 
> **Expected result:** buttons are responding  
> 
> 
> 
> 
> 
> https://user-images.githubusercontent.com/97245802/210414251-c05c9dc2-2c5d-4d60-9c7a-aa086412e59c.mp4
> 
> 
> 
> [geth.log](https://github.com/status-im/status-mobile/files/10338740/geth.log)
> 
> [Status.log](https://github.com/status-im/status-mobile/files/10338741/Status.log)
> 
> 

This is unrelated to this work, let's file a separate issue and I can take a look :)

**Pull request merged**
