### PR TITLE
[ISSUE #889] Show app version in profile

### LINKED ISSUE #889: Show app version
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to find app version in the app's interface so that I know which version is used.

Instabug: 
* https://dashboard.instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/264
* https://dashboard.instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/387

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature 

*Summary*: There is no app version in the app. User needs to go to settings and check the version there. It would be better to show the app version, e.g. in profile

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
App version can be found in the app
#### Actual behavior
[comment]: # (Describe what actually happened.)
there is no app version now in the app interface

### Solution
[comment]: # (Please summarise the solution and provide a task list on what needs to be fixed.)
*Summary*: 

- [ ] Design app version place and look
- [ ] Implement "show app version"

### PR DESCRIPTION
**Pull request by jeluard**
fixes #889

### Summary:

Add status version (or git hash for dev builds) in profile tab

### Steps to test:
- Open Status
- Navigate profile tab
- See version number

status: ready

### CODE REVIEW

**Review by flexsurfer — APPROVED** [review]

**Comment by dmitryn** [comment]
On iOS version text seems not aligned horizontally with "Log out" text 
screenshot 2018-03-22 17 10 18

**Review by dmitryn — CHANGES_REQUESTED** [review]
Please align text on iOS

**Comment by denis-sharypin** [comment]
@jeluard  pay attention to the text color

**Comment by jeluard** [comment]
@dmitryn Fixed now

**Review by cammellos — APPROVED** [review]

**Review by dmitryn — APPROVED** [review]

**Comment by jeluard** [comment]
@annadanchenko You might want to take a look at this one

**Comment by denis-sharypin** [comment]
I still see this
screenshot 2018-03-23 19 19 14

**Comment by jeluard** [comment]
@denis-sharypin Should be good now

**Comment by denis-sharypin** [comment]
@jeluard I've checked a new build. And `version number` should be moved to the line where `logout button` is. Not vice-versa. 
image

**Comment by jeluard** [comment]
@denis-sharypin You didn't check the latest version, it's still the same number. Version should be `7d415e9  `

**Comment by denis-sharypin** [comment]
@jeluard  I've checked this version. And yes they are on the one line right now but both of them are too close to the top grey line. That's why I posted the previous comment where I mentioned that it's better to move down a version number
img_3818

**Comment by jeluard** [comment]
Ah ok makes sense now :) 👀 #designers

**Comment by jeluard** [comment]
@denis-sharypin Should be fixed now

**Comment by denis-sharypin** [comment]
@jeluard Layout is good thanks! One thing I mentioned in the issue: decrease the tappable size of the logout button to a half of the row. Is it possible to implement?

**Comment by jeluard** [comment]
@denis-sharypin Do you want that for all actionable items? They all share the same logic

**Comment by denis-sharypin** [comment]
@jeluard  No then. When we have any user complains about this we will fix this.

**Pull request merged**
