### PR TITLE
Use updated status-go with contact bio persistence

### LINKED ISSUE #19211: No Bio data in User's B Profile if User A made a logout
# Bug Report
https://github.com/status-im/status-mobile/pull/19030#

## Problem 
[comment]: # (A problem description)
If user A has User B in a contacts and sees User's B bio then do a logout - no Bio data in User's B Profile

#### Expected behavior
Data should't disappear after relogin

#### Actual behavior
No Bio data in User's B Profile

https://github.com/status-im/status-mobile/assets/147824399/6563d478-75a1-4b01-993d-ec6414fdc05e

### Reproduction

**Steps:**

1. Login to mobile app as User A (new-contact-ui flag is OFF)
2. As User B make sure you have text in your Bio field
3. As user A send contact request to User B
4. Accept contact request as user B
5. As user A turn ON new-contact-ui flag
6. As User A go to Contacts - User B profile (sees Bio data)
7. Logout as User A
8. As User A go to Contacts - User B profile

### Additional Information

- Status version: (https://github.com/status-im/status-mobile/pull/19030#)
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by seanstrom**
[comment]: # (Please replace ... with your information. Remove < and >)
[comment]: # (To auto-close issue on merge, please insert the related issue number after # i.e fixes #566)

fixes #19211 

### Summary

[comment]: # (Summarise the problem and how the pull request solves it)

This PR attempts to update the status-go to a new version that support persistence of a contact's bio description.

#### Platforms

- Android
- iOS

#### Areas that maybe impacted

Potentially the entire app could be affected by a status-go update, but stuff related to contacts like contact profile screen.

### Steps to test

The reproduction steps are best described in #19211 

status: ready

### CODE REVIEW

**Review by cammellos — APPROVED** [review]

**Review by mohsen-ghafouri — APPROVED** [review]

**Comment by mohsen-ghafouri** [comment]
@seanstrom I believe #19209 also has been resolved with this changes, no?

**Review by yqrashawn — APPROVED** [review]

**Comment by seanstrom** [comment]
@mohsen-ghafouri I'm not sure if #19209 is resolved because it mentions testing with Status desktop, and I think this PR only helps with the mobile apps updating bio descriptions and fetching bio descriptions. Should we count #19209 as resolved in this repo and move it to the status desktop repo?

**Comment by mohsen-ghafouri** [comment]
@seanstrom I think it worth to mention that Bio updating between 2 mobile devices works fine so they can test it and move #19209 to desktop board as there is nothing we can do about it.

**Comment by seanstrom** [comment]
@status-im/mobile-qa Can you review these E2E results please?

If everything looks alright, I've been told that I can merge the status-go PR https://github.com/status-im/status-go/pull/4916, and close this PR because the status-go version will be updated when the release-branch is cut.

Please lmk if that sounds alright 🙏

**Comment by VolodLytvynenko** [comment]
Hi @seanstrom, it seems the current PR includes the previously fixed issue. Could you rebase this PR and status go  https://github.com/status-im/status-go/tree/seanstrom/add-and-persist-bio-in-contacts? We need to rerun e2e then once more time.

**Comment by seanstrom** [comment]
@VolodLytvynenko yup yup just rebased and pushed 🙏

**Comment by VolodLytvynenko** [comment]
Hi @seanstrom thank you for PR. No issues from my side. PR is ready to be merged

**Comment by seanstrom** [comment]
Okay I just merged the status-go PR https://github.com/status-im/status-go/pull/4916, and I'm closing this PR because the status-go version should be updated when the release-branch is cut.

Thank you for the testing and support 🙌

**Pull request closed without merging**
