### PR TITLE
Add gif support on Android

### LINKED ISSUE #6871: Add gif support on Android
### User Story

As a developer, I want gif support on all platform

### Description

*Type*: Feature

Follow [those instructions](https://facebook.github.io/react-native/docs/image#gif-and-webp-support-on-android) to add gif support to the `image` element on Android.

### PR DESCRIPTION
**Pull request by shamardy**
Fixes #6871

### CODE REVIEW

**Comment by jeluard** [comment]
@shamardy Could you validate that it works?

**Comment by shamardy** [comment]
@jeluard It's working now with fresco 1.9, gif support is added but there is no gifs in the app to test it with.

**Comment by jeluard** [comment]
@shamardy You could test with this simple extension that allows to search and display gif in the chat: https://status-im.github.io/pluto/try.html?hash=Qmb1B3jXNdc9WZCcWFzpkTXtrurnKxYQFvUDhp2J4SVCCX

<blockquote><div><strong><a href="https://status-im.github.io/pluto/index.html">Pluto · A grammar for data manipulation</a></strong></div><div>A grammar for data manipulation</div></blockquote>

**Comment by shamardy** [comment]
@jeluard Tested it with the extension the gifs work in the chat.

**Review by jeluard — APPROVED** [review]

**Review by dmitryn — APPROVED** [review]
Approving this as we're already using gif animation for keycard installation screens and it works good there

**Comment by jeluard** [comment]
@shamardy Can you squash your commits?

**Review by goranjovic — APPROVED** [review]

**Comment by asemiankevich** [comment]
@jeluard @shamardy Second item search crashes Status app. **Also , please add expected scenarios to be working in this PR.**

Device: Huawei P10 Lite Android 8

Steps to reproduce:

1. Install extension https://status-im.github.io/pluto/try.html?hash=Qmb1B3jXNdc9WZCcWFzpkTXtrurnKxYQFvUDhp2J4SVCCX
2. Go to 1x1 chat
3. Call /gfycat command
4. Search for a gif and send any (for ex "cat")
5. Search second time for "hello"

Logs: 

```
2018-12-06 17:01:07.106 10539-10539/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: im.status.ethereum, PID: 10539
    java.lang.RuntimeException: Canvas: trying to draw too large(144000000bytes) bitmap.
        at android.view.DisplayListCanvas.throwIfCannotDraw(DisplayListCanvas.java:229)
        at android.view.RecordingCanvas.drawBitmap(RecordingCanvas.java:97)
        at com.facebook.fresco.animation.bitmap.BitmapAnimationBackend.drawBitmapAndCache(BitmapAnimationBackend.java:343)
        at com.facebook.fresco.animation.bitmap.BitmapAnimationBackend.drawFrameOrFallback(BitmapAnimationBackend.java:218)
        at com.facebook.fresco.animation.bitmap.BitmapAnimationBackend.drawFrameOrFallback(BitmapAnimationBackend.java:237)
        at com.facebook.fresco.animation.bitmap.BitmapAnimationBackend.drawFrameOrFallback(BitmapAnimationBackend.java:237)
        at com.facebook.fresco.animation.bitmap.BitmapAnimationBackend.drawFrame(BitmapAnimationBackend.java:165)
        at com.facebook.fresco.animation.backend.AnimationBackendDelegate.drawFrame(AnimationBackendDelegate.java:59)
        at com.facebook.fresco.animation.backend.AnimationBackendDelegateWithInactivityCheck.drawFrame(AnimationBackendDelegateWithInactivityCheck.java:109)
        at com.facebook.fresco.animation.drawable.AnimatedDrawable2.draw(AnimatedDrawable2.java:206)
        at com.facebook.drawee.drawable.ForwardingDrawable.draw(ForwardingDrawable.java:145)
        at com.facebook.drawee.drawable.ForwardingDrawable.draw(ForwardingDrawable.java:145)
        at com.facebook.drawee.drawable.ScaleTypeDrawable.draw(ScaleTypeDrawable.java:123)
        at com.facebook.drawee.drawable.FadeDrawable.drawDrawableWithAlpha(FadeDrawable.java:302)
        at com.facebook.drawee.drawable.FadeDrawable.draw(FadeDrawable.java:289)
        at com.facebook.drawee.drawable.ForwardingDrawable.draw(ForwardingDrawable.java:145)
        at com.facebook.drawee.generic.RootDrawable.draw(RootDrawable.java:81)
        at android.widget.ImageView.onDraw(ImageView.java:1429)
        at android.view.View.draw(View.java:19314)
        at android.view.View.updateDisplayListIfDirty(View.java:18250)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4252)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4232)
        at android.view.View.updateDisplayListIfDirty(View.java:18209)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4252)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4232)
        at android.view.View.updateDisplayListIfDirty(View.java:18209)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4252)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4232)
        at android.view.View.updateDisplayListIfDirty(View.java:18209)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4252)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4232)
        at android.view.View.updateDisplayListIfDirty(View.java:18209)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4252)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4232)
        at android.view.View.updateDisplayListIfDirty(View.java:18209)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4252)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4232)
        at android.view.View.updateDisplayListIfDirty(View.java:18209)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4252)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4232)
        at android.view.View.updateDisplayListIfDirty(View.java:18209)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4252)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4232)
        at android.view.View.updateDisplayListIfDirty(View.java:18209)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4252)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4232)
        at android.view.View.updateDisplayListIfDirty(View.java:18209)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4252)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4232)
2018-12-06 17:01:07.492 1153-1302/? W/InputDispatcher: channel '87d28af im.status.ethereum/im.status.ethereum.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
2018-12-06 17:01:07.492 1153-1302/? E/InputDispatcher: channel '87d28af im.status.ethereum/im.status.ethereum.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
2018-12-06 17:01:07.494 1153-2028/? I/ActivityManager: Process im.status.ethereum (pid 10539) has died: fore TOP 
2018-12-06 17:01:07.497 1153-2028/? D/ActivityManager: cleanUpApplicationRecord app: ProcessRecord{b608da3 10539:im.status.ethereum/u0a525}, app.bad: false, restarting: false, allowRestart: true
2018-12-06 17:01:07.498 1153-1836/? I/WindowManager: WIN DEATH: Window{87d28af u0 im.status.ethereum/im.status.ethereum.MainActivity}
2018-12-06 17:01:07.498 1153-1836/? V/WindowManager: removeIfPossible: Window{87d28af u0 im.status.ethereum/im.status.ethereum.MainActivity} callers=com.android.server.wm.WindowState.-wrap1:0 com.android.server.wm.WindowState$DeathRecipient.binderDied:2481 android.os.BinderProxy.sendDeathNotice:840 <bottom of call stack> <bottom of call stack> 
2018-12-06 17:01:07.498 1153-1836/? W/InputDispatcher: Attempted to unregister already unregistered input channel '87d28af im.status.ethereum/im.status.ethereum.MainActivity (server)'
2018-12-06 17:01:07.500 1153-1836/? I/WindowManager: Destroying surface Surface(name=im.status.ethereum/im.status.ethereum.MainActivity) called by com.android.server.wm.WindowStateAnimator.destroySurface:2089 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:899 com.android.server.wm.HwWindowStateAnimator.destroySurfaceLocked:1006 com.android.server.wm.WindowState.removeImmediately:1899 com.android.server.wm.WindowState.removeIfPossible:2051 com.android.server.wm.WindowState.-wrap1:0 com.android.server.wm.WindowState$DeathRecipient.binderDied:2481 android.os.BinderProxy.sendDeathNotice:840 
2018-12-06 17:01:07.500 1153-1836/? I/WindowManager: Destroying surface Surface(name=im.status.ethereum/im.status.ethereum.MainActivity) called by com.android.server.wm.WindowStateAnimator.destroySurface:2089 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:899 com.android.server.wm.HwWindowStateAnimator.destroySurfaceLocked:1006 com.android.server.wm.WindowState.removeImmediately:1899 com.android.server.wm.WindowState.removeIfPossible:2051 com.android.server.wm.WindowState.-wrap1:0 com.android.server.wm.WindowState$DeathRecipient.binderDied:2481 android.os.BinderProxy.sendDeathNotice:840 
2018-12-06 17:01:07.502 1153-1836/? W/WindowManager: Exception thrown when updateSurfaceStatusWindowStateAnimator{1327c1 im.status.ethereum/im.status.ethereum.MainActivity}: android.os.DeadObjectException
2018-12-06 17:01:07.502 1153-1836/? V/WindowManager: postWindowRemoveCleanupLocked: Window{87d28af u0 im.status.ethereum/im.status.ethereum.MainActivity}
2018-12-06 17:01:07.503 1153-1836/? V/WindowManager: Removing Window{87d28af u0 im.status.ethereum/im.status.ethereum.MainActivity} from AppWindowToken{edad285 token=Token{29cbfc ActivityRecord{c5174ef u0 im.status.ethereum/.MainActivity t2899}}}
2018-12-06 17:01:07.508 1153-2028/? W/ActivityManager: Scheduling restart of crashed service im.status.ethereum/.module.StatusService in 1000ms
2018-12-06 17:01:07.513 1153-2028/? W/ActivityManager: Force removing ActivityRecord{c5174ef u0 im.status.ethereum/.MainActivity t2899}: app died, no saved state
2018-12-06 17:01:07.520 1153-2028/? V/WindowManager: removeAppToken: AppWindowToken{edad285 token=Token{29cbfc ActivityRecord{c5174ef u0 im.status.ethereum/.MainActivity t2899}}} delayed=false Callers=com.android.server.wm.DisplayContent.removeAppToken:994 com.android.server.wm.AppWindowContainerController.removeContainer:352 com.android.server.am.ActivityRecord.removeWindowContainer:1045 com.android.server.am.ActivityStack.removeActivityFromHistoryLocked:4486 
2018-12-06 17:01:07.529 1153-2028/? W/HwActivityManagerServiceEx: appSwitch from: im.status.ethereum to: com.huawei.android.launcher
2018-12-06 17:01:07.545 1622-1817/? I/AppsUsage: scnOff:false FgAPP:com.huawei.android.launcher BgAPP:im.status.ethereum
2018-12-06 17:01:07.559 1622-2100/? I/PGServer: report state:10000 event type:2 pid:0 uid:0 pkg:im.status.ethereum to pid: 1153
2018-12-06 17:01:07.559 1622-2100/? I/PGServer: report state:10000 event type:2 pid:0 uid:0 pkg:im.status.ethereum to pid: 1622
2018-12-06 17:01:07.559 1622-2100/? I/SceneReceiver: state type: 10000 eventType:2 pid:0 uid:0 pkg:im.status.ethereum
2018-12-06 17:01:07.634 1153-5010/? D/ActivityManager: Skipping intent:act=android.intent.action.DELETE dat=package:im.status.ethereum flg=0x10800000 cmp=com.google.android.packageinstaller/com.android.packageinstaller.UninstallerActivity
2018-12-06 17:01:08.510 1153-1169/? V/ActivityManager: startProcess: name=im.status.ethereum app=null knownToBeDead=true thread=null pid=-1
2018-12-06 17:01:08.547 1153-1169/? I/ActivityManager: Start proc 11944:im.status.ethereum/u0a525 for service im.status.ethereum/.module.StatusService
2018-12-06 17:01:08.652 11944-11959/? I/HwApiCacheMangerEx: apicache mCurPackageName=im.status.ethereum uptimes=289873494
2018-12-06 17:01:08.674 11944-11959/? I/HwApiCacheMangerEx: apicache path=/storage/emulated/0 state=mounted key=im.status.ethereum#10525#256
2018-12-06 17:01:08.678 11944-11959/? I/HwApiCacheMangerEx: apicache path=/storage/emulated/0 state=mounted key=im.status.ethereum#10525#0
2018-12-06 17:01:08.678 11944-11959/? I/HwApiCacheMangerEx: apicache async read begin packageName=im.status.ethereum userid=0
2018-12-06 17:01:08.682 11944-11959/? I/HwApiCacheMangerEx: apicache async read finished packageName=im.status.ethereum userid=0 totalus=4103
2018-12-06 17:01:08.733 11944-11944/? I/HwApiCacheMangerEx: apicache pi PackageInfo{118b61c im.status.ethereum}
2018-12-06 17:01:08.761 11944-11944/? D/SoLoader: Preparing SO source: com.facebook.soloader.DirectorySoSource[root = /data/app/im.status.ethereum-lUM3bmsxikPOLWLHlxk9NQ==/lib/arm flags = 0]
2018-12-06 17:01:08.761 11944-11944/? D/SoLoader: Preparing SO source: com.facebook.soloader.ApkSoSource[root = /data/data/im.status.ethereum/lib-main flags = 1]
2018-12-06 17:01:08.762 11944-11944/? V/fb-UnpackingSoSource: locked dso store /data/user/0/im.status.ethereum/lib-main
2018-12-06 17:01:08.762 11944-11944/? I/HwApiCacheMangerEx: apicache pi PackageInfo{118b61c im.status.ethereum}
2018-12-06 17:01:08.764 11944-11944/? I/fb-UnpackingSoSource: dso store is up-to-date: /data/user/0/im.status.ethereum/lib-main
2018-12-06 17:01:08.764 11944-11944/? V/fb-UnpackingSoSource: releasing dso store lock for /data/user/0/im.status.ethereum/lib-main
2018-12-06 17:01:08.795 11944-11966/? I/HwApiCacheMangerEx: apicache pi PackageInfo{118b61c im.status.ethereum}
2018-12-06 17:01:08.799 11944-11966/? I/FA: To enable faster debug mode event logging run:
      adb shell setprop debug.firebase.analytics.app im.status.ethereum
```



<blockquote><div><strong><a href="https://status-im.github.io/pluto/index.html">Pluto · A grammar for data manipulation</a></strong></div><div>A grammar for data manipulation</div></blockquote>

**Comment by jeluard** [comment]
@asemiankevich Could you confirm that with this PR you can see moving gifs on android but don't see them without the PR?

**Comment by jeluard** [comment]
@asemiankevich Is the crash something you can reproduce consistently? How about w/o this PR?

**Comment by asemiankevich** [comment]
> @asemiankevich Is the crash something you can reproduce consistently? How about w/o this PR?

yes, i can repro it all the time as described. W/o this PR i cant install this gif extension so hard to say



> @asemiankevich Could you confirm that with this PR you can see moving gifs on android but don't see them without the PR?

yes

1. In this PR:
image

2. in latest release
image

**Comment by jeluard** [comment]
@asemiankevich This extension definitely works with latest nightly

**Comment by shamardy** [comment]
@asemiankevich @jeluard I couldn't reproduce this crash, it worked normally with me with over 10 searches and sending of gifs

Device: Sony Xperia Z2 Android 6

@asemiankevich Could you tell me an exact gif that makes this crash to try it on my side, I searched for cat and hello like the steps you written and continued to search and send multiple other gifs.

**Comment by asemiankevich** [comment]
> @asemiankevich This extension definitely works with latest nightly

looking into this

> @asemiankevich @jeluard I couldn't reproduce this crash, it worked normally with me with over 10 searches and sending of gifs
> 
> Device: Sony Xperia Z2 Android 6
> 
> @asemiankevich Could you tell me an exact gif that makes this crash to try it on my side, I searched for cat and hello like the steps you written and continued to search and send multiple other gifs.

could it be dependent on Android version? I dont have Android 6 by hand at this moment but can try 7 for example

**Comment by asemiankevich** [comment]
so i tried to use same extension with latest nightly and android 7 + android 8.

just to be precise: 
- Huawei P10 Lite Android 8 , EMUI version 8.0.0 
- Xiaomi Redmi Note pro 4: Android 7 , MIUI Global 10.1.1.0 

1. Null is shown when i type `cat` in a search bar and hit `enter` button on keyboard of my android 7 device. Or when i type `cat` in a search bar and then scroll the results on Android 8

image

image

2. I was not able to reproduce the crash with Android 7 and Android 8 now, using last nightly build

@shamardy @jeluard does this `null` error worth a separate issue?

**Comment by jeluard** [comment]
@asemiankevich Those might be internet connectivity issues. Do you have a link of the extension you are testing?

**Comment by jeluard** [comment]
Now the real question is can you see animated gifs w/o the PR.

**Comment by asemiankevich** [comment]
> @asemiankevich Those might be internet connectivity issues. Do you have a link of the extension you are testing? 

https://status-im.github.io/pluto/try.html?hash=Qmb1B3jXNdc9WZCcWFzpkTXtrurnKxYQFvUDhp2J4SVCCX



<blockquote><div><strong><a href="https://status-im.github.io/pluto/index.html">Pluto · A grammar for data manipulation</a></strong></div><div>A grammar for data manipulation</div></blockquote>

**Comment by asemiankevich** [comment]
> Now the real question is can you see animated gifs w/o the PR.

as i said in the comment above - i used nightly to test. Yes, i can see them. I dont see any update of the issue description so i assume this is the only scenario that should work. In case you dont want to deal with the `null` issue now  - i will log it separately and this PR i believe could be merged.

**Comment by jeluard** [comment]
@asemiankevich Do you see them animated w/o the PR?

**Comment by asemiankevich** [comment]
@jeluard nope

**Comment by jeluard** [comment]
@asemiankevich And after ? (before the crash)

**Comment by asemiankevich** [comment]
> @asemiankevich And after ? (before the crash)

yes before the crash they are animated in this PR

**Comment by asemiankevich** [comment]
@shamardy please rebase the branch

**Comment by asemiankevich** [comment]
@jeluard i am not able to reproduce the crash anymore ( but you may want to consider this when merging.

**Pull request merged**
