### PR TITLE
[#6156] fix Share link button in user's profile does not contain profile universal link

### LINKED ISSUE #6156: Share link button in user's profile does not contain profile universal link
### Description

*Type*: Bug

*Summary*: Comes from https://github.com/status-im/status-react/pull/5862. `Share link` in profile contains only public address, should be a universal link instead.

#### Expected behavior

- `Share link` button in my profile produces universal link to my profile that i could share. 
- `Share link` button in someone's profile produces universal link to my profile that i could share. 

https://get.status.im/user/CONTACT-ADDRESS

#### Actual behavior
Share link contains only contact address

### Reproduction

- Open Status
- Open profile
- Tap Share link -> copy -> paste the content to check it (for ex in 1x1 or public chat)

<blockquote><div><strong><a href="https://get.status.im/user/CONTACT-ADDRESS">View user CONTACT-ADDRESS profile in Status</a></strong></div></blockquote>

### PR DESCRIPTION
**Pull request by rasom**
fix #6156
status: ready

### CODE REVIEW

**Comment by ghost** [comment]
### Pull Request Checklist
- [x] Have you updated the documentation, if impacted (e.g. [docs.status.im](https://docs.status.im/docs/build_status.html))?

**Review by jeluard — APPROVED** [review]

**Review by janherich — APPROVED** [review]

**Comment by lukaszfryc** [comment]
@rasom @asemiankevich I suppose clicking "Share profile link" in someone's else profile should create a universal link with his/her contact address, right? It's not the case now. It works only for my own profile.

**Comment by rasom** [comment]
ok @lukaszfryc, will check it soon

**Review by dmitryn — APPROVED** [review]

**Comment by rasom** [comment]
@lukaszfryc fixed

**Review by flexsurfer — APPROVED** [review]

**Comment by lukaszfryc** [comment]
@rasom I missed https://github.com/status-im/status-react/issues/6347 that was probably introduced by this PR. Could you fix it?

**Pull request merged**
