### PR TITLE
Update welcome image

### LINKED ISSUE #3942: Update welcome image on the home tab
### User Story

As a user, I want QUALITY images

### Description

*Type*: Bug

*Summary*: Seems like we use @ 1x image for retina devices. Please double check.
Bug report https://status-im.slack.com/archives/C90325XL6/p1524085907000048

#### Expected behavior
Each device size should have their appropriate file size . Please check all images https://github.com/status-im/status-react/tree/develop/resources/images/ui

#### Actual behavior
Retina devices use @ 1x images

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Create account

### Additional Information

* Status version: nightly/release 
[comment]: # (Android or iOS.)
* Operating System: Android|iOS

### PR DESCRIPTION
**Pull request by dmitryn**
Fixes #3942 

Updates welcome image with HQ image.

### CODE REVIEW

**Comment by dmitryn** [comment]
screenshot 2018-05-21 13 46 30

**Comment by dmitryn** [comment]
screenshot 2018-05-21 13 46 36

Not sure about welcome image on wallet screen. Does not seem like HQ. @denis-sharypin what do you think?

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/null for branch PR-4358

<blockquote><div><strong><a href="https://i.diawi.com/null">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/Ke2qVK for branch PR-4358

<blockquote><div><strong><a href="https://i.diawi.com/Ke2qVK">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Review by flexsurfer — APPROVED** [review]

**Comment by denis-sharypin** [comment]
@dmitryn yep, seems like that. Do you need a separate task for that?

**Review by rasom — APPROVED** [review]

**Comment by dmitryn** [comment]
>Do you need a separate task for that?

@denis-sharypin no, i just need new HQ image. Where can i find it?

**Comment by denis-sharypin** [comment]
@dmitryn 

Image 1x
wallet-welcome 1x

Image 2x
wallet-welcome 2x

Image 3x
wallet-welcome 3x

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/wungaL for branch PR-4358

<blockquote><div><strong><a href="https://i.diawi.com/wungaL">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/3JiJBc for branch PR-4358

<blockquote><div><strong><a href="https://i.diawi.com/3JiJBc">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/X5WrQy for branch PR-4358

<blockquote><div><strong><a href="https://i.diawi.com/X5WrQy">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/tyjmGV for branch PR-4358

<blockquote><div><strong><a href="https://i.diawi.com/tyjmGV">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Pull request merged**
