### PR TITLE
Feature/refactor protocol listeners #1805

### PR DESCRIPTION
**Pull request by goranjovic**
#1805

### Summary:

Refactored `status-im.protocol.listeners` as a pipeline of separate functions, each of them with such an interface to allow easy composition. Specifically, the following rules have been applied to ensure the composability.

All functions except the first and the last in the pipeline have both input and output parameter in the following format, let's call it `scope`:

```
{:message   MESSAGE
 :error     ERROR
 :options   OPTIONS}
```

Where: 

- `message` is the actual object being transformed by the successive steps in the pipeline
- `error` is  the "bad" alternative to the message, any step that encounters a problem should emit it in its output scope and any step that sees it in its input should just output the scope as it is and do nothing. In that case the next step would just see the error and do the same until the end of the pipeline is reached. (It's actually possible to short circuit it as well, but usually not worth the effort in short pipelines)
- `options` is just a map with all the extra parameters any of the function within the pipeline might need. It's only purpose is to avoid having to pass a large number of params through steps that don't need them only so that they are used is say step 4, or avoiding nested closures just to access the enclosing parameters, etc. Its main difference from `message` (or `error`) is that it is not supposed to be included in the final result of the pipeline. So, just an intermediary convenience map.

The first function in the pipeline has input parameters in whatever way they were supplied by the caller and its only purpose is to transform that into the `scope` format above. 

Likewise, the last function takes its input in that format and *typically* just takes out either just the `message` part or the `error` part, not the whole `scope`. Note that in this case, though, we didn't really return anything meaningful as the only purpose of the pipeline and its last step was to produce a side effect, not yield a value.

Finally, the main function is just a composition of all the functions in between:

```FIRST -> STEP1 -> STEP2 -> .... -> FINAL```

Or in this case:

```init-scope -> parse-payload -> filter-messages-from-same-user -> parse-content -> handle-message```

status: ready

### CODE REVIEW

**Comment by janherich** [comment]
This looks great, much more readable logic then before !

The only thing which I don't like is the fact that in every step function, one has to implement (repetitive) logic for checking if the previous step didn't returned `:error` and if yes, just propagate it to the end of the chain (every step function must participate).

I think that better abstraction for such linear processes are interceptor chains, where instead of the actual stack (composing function calls, here with the help of `->` threading macro) you have virtual stack, which enables you to pause/reverse step processing whenever you wish.
`re-frame` actually already has this [built-in](https://github.com/Day8/re-frame/blob/v0.9.4/src/re_frame/interceptor.cljc) and we can leverage it too.

**Comment by goranjovic** [comment]
@janherich  I agree about repetitive error checking, that was actually the immediate next thing on my refactor list when I decided to box this in order to keep the scope of the task under check. The main purpose of this refactor was to get rid of the monolithic `message-listener` so that's there. 
Obviously, there are things to tighten up here and there, but they are incremental and with diminishing returns. 

The most commonly known thing that implements this pattern is ring, so I guess something like middlewares could factor out error checking. Or even just a function factory for steps that adds the error propagation by default... It's too easy to over-engineer, must... resist... temptation!

Regarding interceptors, I'm not sure in what way the value they add justifies the complexity they bring along. A good thing about Clojure(Script) is that some of their best tools you'll find are right there in `core`.

**Review by janherich — APPROVED** [review]
I agree @goranjovic it's good as it is, as the most important target of the refactoring was achieved.

Regarding ring style middleware for step composition, that's exactly what interceptors are trying to achieve (no wonder that concept of interceptor chain with virtual stack was made popular with pedestal, ring "competitor") and I believe they are fundamentally better abstraction, not really more difficult to understand then middleware implemented as higher order functions.

**Comment by goranjovic** [comment]
@janherich Not saying I'm against it, just that it deserves a discussion of its own!

**Review by rasom — APPROVED** [review]

**Comment by goranjovic** [comment]
squashed

**Pull request merged**
