### PR TITLE
[fix] use icons from design components

### PR DESCRIPTION
**Pull request by yenda**
### Summary:

Use all icons from https://www.figma.com/file/cb4p8AxLtTF3q1L6JYDnKN15/Index?node-id=787%3A825 and remove all unused icons.

### Review notes (optional):
Review of all icons with @andmironov and @errorists 

### Testing notes (optional):
Only updating icons, automated tests are sufficient

status: ready

### CODE REVIEW

**Review by vitvly — APPROVED** [review]

**Comment by yenda** [comment]
someone accept this PR please it's just icon fixes

**Review by flexsurfer — APPROVED** [review]

**Review by errorists — APPROVED** [review]

**Comment by yenda** [comment]
@churik 100% e2e tests wdyt I think we can merge?

**Comment by churik** [comment]
@yenda I think yes, installed and checked briefly IOS, Android, Mac OS. So resolve conflicts, e2e tests 100% and PR is ready to go.

One strange icon appeared near "Sync all devices" on desktop, but IMO not blocker.
fdgdg

**Comment by yenda** [comment]
The conflicts are just because I made a fix in a separate commit for the failing desktop build and it has been merged since

**Comment by yenda** [comment]
@churik the strange icon that appeared was always supposed to be there but was missing in the imports for desktop

**Comment by yenda** [comment]
@churik e2e test failure seem to be unrelated

**Comment by antdanchenko** [comment]
@yenda I am not sure how icons are connected to `#404` error after opening Status Test DAap, but I can reproduce it manually using [latest](https://status-im.ams3.digitaloceanspaces.com/StatusIm-190206-115317-c407d0-e2e.apk) build from this PR 

Also the error is not reproducible on latest nightly build :(

**Comment by antdanchenko** [comment]
Any chance that the issue was introduced in #7429 ?

Only #7429 was merged without running e2e, at least from what I can see in history

**Comment by yenda** [comment]
@antdanchenko there is no way any of the changes in this PR is causing that. I tested with #7429 and the bug was already there, but I think it might have been introduced earlier in the IPFS commit it's producing an invalid URL. I'm merging this.

**Pull request merged**
