### PR TITLE
Feature/remove seen from public chats

### PR DESCRIPTION
**Pull request by cammellos**
### Summary:

Remove sending seen from public chat as it is not used anymore.

I have also fixed some code that has not been running for a while (3/4 months): we used to show a checkmark if the last message is "seen" on the chat, is this something we want to keep or remove @denis-sharypin ?

status: ready

### CODE REVIEW

**Comment by denis-sharypin** [comment]
@cammellos can you share a screenshot with the checkmark, please? I can't remember it

**Review by rasom — APPROVED** [review]

**Comment by cammellos** [comment]
@denis-sharypin attached, let me know if it is to stay, as I would have to remove the checkmark as well from public chats. 
2018-05-04-100022_3840x1980_scrot

**Comment by denis-sharypin** [comment]
@cammellos please remove

**Review by denis-sharypin — APPROVED** [review]

**Comment by cammellos** [comment]
@denis-sharypin removed, thanks

**Review by yenda — APPROVED** [review]

**Review by janherich — APPROVED** [review]

**Pull request merged**
