### PR TITLE
upgrade fastlane to 2.104.0

### PR DESCRIPTION
**Pull request by jakubgs**
Fighting with some issues related to `fastlane` dependencies:

https://ci.status.im/job/status-react/job/combined/job/mobile-ios/857/consoleFull

```
[20:42:22]: $ set -o pipefail && xcodebuild -workspace ios/StatusIm.xcworkspace -scheme StatusIm -configuration Release -destination 'generic/platform=iOS' -archivePath /Users/jenkins/Library/Developer/Xcode/Archives/2018-09-11/StatusIm\ 2018-09-11\ 20.42.22.xcarchive clean archive | tee /Users/jenkins/Library/Logs/gym/StatusIm-StatusIm.log | xcpretty  --no-color
[20:42:22]: ▸ Ignoring json-2.1.0 because its extensions are not built. Try: gem pristine json --version 2.1.0
[20:42:22]: ▸ Ignoring unf_ext-0.0.7.5 because its extensions are not built. Try: gem pristine unf_ext --version 0.0.7.5
[20:42:22]: ▸ [31mCould not find unf_ext-0.0.7.5 in any of the sources[0m
[20:42:22]: ▸ [33mRun `bundle install` to install missing gems.[0m
[20:43:54]: ▸ ** ARCHIVE FAILED **
```

Also enables Fastalen auto-updates.

<blockquote><div><strong><a href="https://ci.status.im/job/status-react/job/combined/job/mobile-ios/857/consoleFull">status-react » combined » mobile-ios #857 Console [Jenkins]</a></strong></div></blockquote>

### CODE REVIEW

**Comment by jakubgs** [comment]
Related:
https://github.com/fastlane/fastlane/issues/12547

**Comment by jakubgs** [comment]
I think I fixed the `unf_ext` error by removing `~/.gem/ruby/`, but an uprade is in order anyway.

**Review by yenda — APPROVED** [review]

**Comment by chadyj** [comment]
Looking at the Fastlane changelog there are hot fixes happening quite often, and in our own experience we have had to upgrade Fastlane a few times because of shifting sands.

So why not just set Fastlane to autoupdate? It is a Fastfile setting https://docs.fastlane.tools/actions/update_fastlane/#update_fastlane

**Comment by jakubgs** [comment]
I wasn't aware this was an option. Good idea!

**Comment by chadyj** [comment]
Sorry I had the incorrect link. Here is the right one https://docs.fastlane.tools/actions/update_fastlane/#update_fastlane

<blockquote><div><strong><a href="https://docs.fastlane.tools/actions/update_fastlane/#update_fastlane">update_fastlane - fastlane docs</a></strong></div></blockquote>

**Review by chadyj — APPROVED** [review]

**Pull request merged**
