### PR TITLE
Rework transactions sending

### LINKED ISSUE #218: Rework transactions sending
In regards to changes introduced in https://github.com/status-im/status-go/pull/31, we need to change the flow of the transaction sending in the react-native app. ~~Also, this will require additional changes on `status-go` side.~~ (done) 

  ~~So currently, when `eth.sendTransaction` is invoked it returns a temporal `id` of a transaction and that `id` is used to complete transaction later. 
This changes the behaviour of `eth.sendTransaction` and it would be a problem for the end user. Instead of usage of the temporal `id` from `eth.sendTransaction` any result will not be returned from RPC call until transaction's confirmation.~~

When the result will be returned to the `eth.sendTransaction` we will receive the signal from `status-go` with both `message-id` and transaction's `hash`.

Implemented in `status-go` https://github.com/status-im/status-go/pull/31
https://github.com/status-im/status-go/issues/30

### LINKED ISSUE #341: Contact appeared second time

### PR DESCRIPTION
**Pull request by rasom**
closes #218 
fixes #341

### CODE REVIEW

**Comment by rasom** [comment]
Currently `!send` command can be used in both android/ios.
There are some things that are not implemented: currency parameter, confirmation of transaction etc.
And there is a set of different bugs.

I suppose that it's better to create new issues regarding these features/bugs as the goal of this PR was to integrate last changes of `status-go` into `status-react`.

**Comment by jarradh** [comment]
we can drop currency for initial alpha because we'll only be supporting ETH anyway and not other ERC20 tokens

**Comment by rasom** [comment]
Ok, so then we don't need to make changes to `!send` command.

**Comment by alwx** [comment]
There are some layout problems, and looks like it is impossible to send eth on iOS (button is not clickable and there is no info what's wrong)
screen shot 2016-10-18 at 16 17 38

**Comment by jarradh** [comment]
let's close the entire transaction queue screen if theres no more transactions in queue (if the user hits X on the final transaction in list)

**Comment by rasom** [comment]
That's actually how it worked before, but there is a small problem... When we are trying to confirm the transaction with a wrong password it is removed from the queue, and if we will close confirmation screen user will not even see that there was some error.

**Pull request merged**
