### PR TITLE
Design/remove letter spacing property

### PR DESCRIPTION
**Pull request by yenda**
Tested on Android emulator

Screenshot_1552345066
Screenshot_1552345083
Screenshot_1552345084
Screenshot_1552345092
Screenshot_1552345098
Screenshot_1552345101
Screenshot_1552345105
Screenshot_1552345111
Screenshot_1552345116
Screenshot_1552345168
Screenshot_1552345175
Screenshot_1552345179
Screenshot_1552345186

status: ready

### CODE REVIEW

**Review by errorists — APPROVED** [review]

**Comment by yenda** [comment]
@churik it should have some minor effect on text in the app on iOS

**Review by vitvly — APPROVED** [review]

**Comment by errorists** [comment]
> @churik it should have some minor effect on text in the app on iOS

Both Android and iOS actually, this property makes the spaces between all letters tighter and… yeah, I really don't know why we had it in the first place lol

**Comment by yenda** [comment]
@errorists yeah it also changes android now because I changed quite a few font-size to be the same on both android and ios

**Comment by errorists** [comment]
@yenda the only thing left is for both to use the same font :D

**Comment by churik** [comment]
Tested on LG V20 (Android 8), IPhone 7 (IOS 11.4.1) on Russian and English. 
Didn't notice any issues.

**Pull request merged**
