### PR TITLE
Enable mailserver confirmations in all builds.

### PR DESCRIPTION
**Pull request by mandrigin**
This commits enables Whisper-level mailserver confirmations in all builds. That should uncover issues with messages not being delivered to the mailservers. Part of improvements of message-reliability.

#### Platforms (optional)
- Android
- iOS
- macOS
- Linux
- Windows

#### Areas that maybe impacted (optional)
**Functional**
- 1-1 chats
- public chats
- group chats

status: ready

### CODE REVIEW

**Review by cammellos — APPROVED** [review]

**Comment by dshulyak** [comment]
It was flaky as hell when @cammellos tried it. I didn't look yet why connection is not stable

**Review by pedropombeiro — APPROVED** [review]

**Comment by mandrigin** [comment]
@dshulyak yeah, this PR needs to be tested first and these connection issues should be resolved somehow...

**Comment by dshulyak** [comment]
@mandrigin i overwrote your change with rebased version.

tested it on mobile and re-tested whole flow with standalone statusd node. it works fine, so maybe mail servers were flaky when it was tested initially.

**Review by dshulyak — APPROVED** [review]

**Comment by mandrigin** [comment]
@dshulyak thank you! let's wait for it to build and then ask QA to test message sending.

**Comment by dshulyak** [comment]
Sometimes my message is not getting confirmed by a mail server. It is rare but happens. will try to find out the root cause

**Comment by mandrigin** [comment]
@dshulyak is there any specific mail server that behaves that way?

**Comment by dshulyak** [comment]
@mandrigin no, i first noticed this with chinese mail server, but later reproduced it with do mail server

**Comment by cammellos** [comment]
I had the same, in this case though, does it make sense to automatically
retry sending the message? sounds reasonable to me

**Comment by dshulyak** [comment]
@cammellos agree, i would like to retry at least once too. also we wait 30s for message to be acknowledged, that is too long.

but i don't understand what is the root cause of these errors, connection seems to be stable. and from what i can tell all messages are acknowledged properly

**Comment by dshulyak** [comment]
it would be right to assume that connection is flaky, and then retrying makes even more sense in current solution

**Comment by cammellos** [comment]
@dshulyak I assumed whisper every now and then drops messages (or they are dropped by the client), as for example I never received your messages yesterday, even after querying the mailserver for more. Unclear what is due to exactly, but retrying such messages sounds good.

**Comment by mandrigin** [comment]
@dshulyak I think we can pass an "auto-retry" parameter as a whisper config or something... just retry sending failed messages 3 times by default with 2 and 4 seconds between them. If all failed, we can report the error upwards to the API client...
This confirmation thing might uncover something interesting. I would also be awesome to keep some stats per mailserver like: 98 percentile → first try, 99.5 percentile → 2nd try, 99.9 percentile → 3rd try or something like that. It might be super useful for hunting the issues down.

**Comment by asemiankevich** [comment]
@mandrigin any insight how i can see this somewhere ? geth log, anything?

**Comment by mandrigin** [comment]
@asemiankevich if you add a mailserver that isn’t working you shouldn’t be able to send messages, probably that

**Comment by cammellos** [comment]
@asemiankevich messages might be sent, but they will be marked as "Not confirmed"

**Comment by mandrigin** [comment]
@asemiankevich ping on that issue :-)

**Comment by asemiankevich** [comment]
@mandrigin i am not working on it. maybe @Serhy can pick it up , or @churik . I am in the middle of other tasks right now

**Comment by cammellos** [comment]
Shall we just enable this in nightlies and see how it goes?

**Comment by mandrigin** [comment]
@asemiankevich ah, okay... yeah, we can just do that

**Comment by churik** [comment]
I can pick it up

**Comment by churik** [comment]
@mandrigin do you have QR for the non-working mailserver that can pass our validation?

**Comment by churik** [comment]
@mandrigin @dshulyak in this PR ~10% messages are shown as not confirmed regardless of mailserver.
In fact these messages are sent and are shown in history of public chats.
This issue is not reproducible in current nightly build.
not_confirmed
Geth.log: 
[geth.log](https://github.com/status-im/status-react/files/2865200/geth.log)

**Comment by mandrigin** [comment]
@churik is that the same on mobile as well?

**Comment by churik** [comment]
@mandrigin yes, on mobile (IOS) the same.
Steps:
- join to public chat 
- send quickly 10+ messages until one of them is hanging in pending state
- wait until spinner will be replaced with "Not confirmed"
- check puclic chat history on other device. It contains "Not confirmed" message

**Comment by mandrigin** [comment]
@churik okay, I will take a look later...

**Comment by antdanchenko** [comment]
@mandrigin, @churik the PR should be rebased on develop so all tests will run on Android 8 and we won't get this kind of failures

**Comment by mandrigin** [comment]
Yeah, there are issues anyway, I will rebase it for sure.

**Comment by mandrigin** [comment]
@dshulyak it would be awesome to get your fixes for confirmatons to a new status-go release and to this PR :)

**Comment by mandrigin** [comment]
@churik I hope this new status-go version will fix this issue, but it probably will require a slightly more thorough testing.

**Comment by mandrigin** [comment]
@Serhy the same status-go is in Andrea's PR: https://github.com/status-im/status-react/pull/7526 so it makes no sense to throroughly test both of them.

**Comment by mandrigin** [comment]
Here it is about sending messages in chatrooms.

**Comment by Serhy** [comment]
OK, cool, thanks for this note, @mandrigin 
I'll test #7526 as well after this one.

**Comment by Serhy** [comment]
@mandrigin on MacOS:
Each time message is received in chat (1-1/public/group) the error appears:

``` 
55db1d399542673d73d953bde8d2a89aac772a1" callbackId: 88197
16:23:04.762 - D - [RCTStatus] - ::callPrivateRPC CallPrivateRPC succeeded
16:23:04.786 - D - [RCTStatus] - ::callPrivateRPC call - payload: "[{\"jsonrpc\":\"2.0\",\"id\":2662,\"method\":\"shhext_getNewFilterMessages\",\"params\":[\"d8408fda4e08585cc3b44f62a4e54e826125e8a002f2efb7af" callbackId: 88217
16:23:04.789 - D - [RCTStatus] - ::callPrivateRPC CallPrivateRPC succeeded
16:23:04.790 - D - [jsserver] - [status-im.utils.handlers:34] - Handling re-frame event:  :transport/messages-received
16:23:04.803 - D - [jsserver] - [status-im.utils.handlers:34] - Handling re-frame event:  :message/add
DEBUG [status-im.utils.handlers:34] - Handling re-frame event:  :message/messages-persisted
16:23:04.811 - D - [jsserver] - PRETTY PRINTED EXCEPTION

***
NAME: "TypeError"
MESSAGE: status_im.transport.utils.shh(...).confirmMessagesProcessedByID is not a function

TypeError: status_im.transport.utils.shh(...).confirmMessagesProcessedByID is not a function
    at G__31314_31318 (evalmachine.<anonymous>:11:6619555)
    at evalmachine.<anonymous>:11:1657908
    at Object.re_frame.interceptor.invoke_interceptor_fn (evalmachine.<anonymous>:11:1613149)
    at Object.re_frame.interceptor.invoke_interceptors (evalmachine.<anonymous>:11:1613433)
    at Object.re_frame.interceptor.execute (evalmachine.<anonymous>:11:1615805)
    at Object.re_frame.events.handle (evalmachine.<anonymous>:11:1624309)
    at re_frame.router.EventQueue.re_frame$router$IEventQueue$_process_1st_event_in_queue$arity$1 (evalmachine.<anonymous>:11:1651395)
    at re_frame.router.EventQueue.re_frame$router$IEventQueue$_run_queue$arity$1 (evalmachine.<anonymous>:11:1636323)
    at evalmachine.<anonymous>:11:1639436
    at re_frame.router.EventQueue.re_frame$router$IEventQueue$_fsm_trigger$arity$3 (evalmachine.<anonymous>:11:1643773)

***
16:23:05.265 - D - [RCTStatus] - ::callPrivateRPC call - payload: "[{\"jsonrpc\":\"2.0\",\"id\":2665,\"method\":\"shhext_getNewFilterMessages\",\"params\":[\"03c6e7e374855db1d399542673d73d953bde8d2a89aac772a1" callbackId: 88495
```

screenshot 2019-02-21 at 16 20 04


iOS and Android doesn't have this issue (Linux/Windows wasn't checked yet)

**Comment by Serhy** [comment]
It looks good in terms of guarantees about message delivering. But message status is really playing safe:
There are cases when on sender side message is marked as ‘Not sent’ (marked by `Not confirmed. Tap for options`) but in fact, it sent and stored on mailserver (since it can be received from offline inbox later).
Especially this issue is visible when connecting to mailserver blue status bar in progress. For example after new account creation, at the moment it takes relatively long to establish the connection to mail server. And while it's in progress - almost all messages (yes, 1-2 of 10 are confirmed, so not all messages) marked on sender side as `Not confirmed. Tap for options`.

Please see video between Desktop (sender) and iOS (receiver) here: https://drive.google.com/file/d/1TG23DfjxwdBDnY06B-AjRIKACVRS0o5Z/view?usp=sharing (it’s 4mins long, but it shows all use-cases)

screenshot 2019-02-22 at 11 21 30


Logs from Desktop build are: 
[Status.log](https://github.com/status-im/status-react/files/2893185/Status.log)


In terms of message reliability, this is correct, because user is not connected to mailserver, so no guarantees message is delivered. But consequences are described above. 

But when connected to mailserver - there are no issues, no regressions. 

<blockquote><div>Google Drive</div><div><strong><a href="https://drive.google.com/file/d/1TG23DfjxwdBDnY06B-AjRIKACVRS0o5Z/view?usp=sharing&usp=embed_facebook">Fake_not_connected_message_status.mov</a></strong></div></blockquote>

**Comment by churik** [comment]
Tested on Linux Ubuntu 18.04, Windows 10, Mac OS Mojave:
- creating account with  password containing special chars;
- resoring account from seed phrase;
- 1-1 chat messages;
- group chats - chatting, offline inboxing, make another user as admin, leaving chat;
- joining to public chat;
- resending messages from state "Not confirmed";
- deleting chats/clearing history;
- mailserver switching;
- logging enabling/disabling;
- PNs;
- log out;
- devices pairing/sync;

Tested on IOS/Android:
- creating account;
- blocking/unblocking users;

Except https://github.com/status-im/status-react/pull/7243#issuecomment-466331874 no regression issues found.

**Comment by Serhy** [comment]
To add for above https://github.com/status-im/status-react/pull/7243#issuecomment-466331874
Blue spinner indicates that messages are in fetching progress. And so the same applies to message status. If user sent a message, app awaits a response from mailserver about the message status on the same level as app in progress to fetch offline inboxed messages.
I'd say the issue is rather with really long (sometimes continuous) progress of fetching from mailserver. 
However, it's anyway will look weird at least for next scenario: 

User sent a message while connected to mailserver and requesting messages -> received 'Not confirmed' response on it (while in fact the message has reached mailsever) -> there are two options below the message 'Resend'/'Delete' -> user taps 'Delete' -> the message is gone but only for him/her, everyone else will see it (and will fetch from offline inbox).

@mandrigin what if we do not stop retrying message status request while 'Fetching messages' in progress? It should eliminate above scenario at least. At the moment if `Not connected. Tap for options`status appears - it keep staying. And what we do (on react side) is: 
- if `connected to mailserver` and `Fetching messages...` -> retry message status.
- If connected to mailsever and no 'Fetching messages...' -> same behavior for 'Not connected. Tap for options' what we have now

I'm OK with merge if we disable MAILSERVER_CONFIRMATIONS_ENABLED for Release for now.

**Comment by mandrigin** [comment]
@Serhy @churik yeah, I'm disabling that for releases but let's keep it for nightlies and PR builds.
Can you create a separate issue for this regression while connecting so we can point people to it if they are confused?

**Comment by mandrigin** [comment]
@Serhy @churik disabled confirmations for release builds but kept them for every other one.

**Comment by Serhy** [comment]
OK, will create a separate issue. 
UPD: https://github.com/status-im/status-react/issues/7559 issue created

**Pull request merged**
