### PR TITLE
Fix endless spinner on Fetch messages

### LINKED ISSUE #7969: Tap on "Fetch messages" leads to endless spinner if connection is lost during fetching
### Description
_Type_: Bug
_Summary_: introduced in https://github.com/status-im/status-react/pull/7919 - decision was to fix it separately. "Fetch messages" still can lead to the endless spinner when the app goes offline-online during fetching. 

#### Expected behavior
messages fetched normally

#### Actual behavior
https://user-images.githubusercontent.com/4557972/55971883-9f528500-5c82-11e9-9bd6-b3e399175304.png

### Reproduction
**Prerequisites:** "Fetch messages" should be shown (app offline for > 24h)

* Open chat with "Fetch messages"
* tap on it
* go to offline 
* go back online

### Additional Information
[comment]: # (Please do your best to fill this out.)

* Status version: nightly 13/04/2019
* Operating System: Android, iOS

### PR DESCRIPTION
**Pull request by rasom**
fix #7969 

status: ready

### CODE REVIEW

**Comment by bitsikka** [comment]
Cool!

Leaving this comment here for whatever it's worth, please don't mind me

This looks like a better approach to handle abstraction for :mailserver/fetching lifecycle in general for all different scenarios of mailserver/fetching 🤔 

I ran into a different scenario in #7454 and surely there are others

In https://github.com/status-im/status-react/pull/7663#issuecomment-473954395 @yenda said
> @bitsikka good job on spotting mailserver/fetching? inconsistencies. I didn't realize that. After discussing with @cammellos I think the best solution would be to have it rely on a value separated from pending-requests. However this shouldn't be part of this PR.

> @StatusSceptre @hesterbruikman could we make a bounty for this?
Fix mailserver/fetching? inconsistencies There should be a 1 second delay between the moment the last request gets completed and the mailserver/fetching? subscription becomes false.

In this comment for **Application Performance and UX** https://discuss.status.im/t/application-performance-and-ux/1168/3 @hesterbruikman said
> This is some painful stuff to watch. For reference here, some factors I think we should investigate:
> ...
> **Design**
> - GUI performance (loading states, empty states, user controlled fetching)
>
> ...

**Comment by rasom** [comment]
@bitsikka this specific bug is not related to general fetching from mail servers, it's about fetching messages by demand when "gap" is detected. It was a leftover after #7919, and this issues appears because some state (which was added in #7919) is not cleared properly on failure.

**Comment by bitsikka** [comment]
> @bitsikka this specific bug is not related to general fetching from mail servers, it's about fetching messages by demand when "gap" is detected. It was a leftover after #7919, and this issues appears because some state (which was added in #7919) is not cleared properly on failure.

understood

I'm just noting a pattern/lifecycle I think I'm noticing surrounding mailserver fetching in different scenarios and getting inspired by how you are handling it in this scenario - to perhaps use the same pattern in other scenarios

**Review by mandrigin — APPROVED** [review]

**Review by cammellos — APPROVED** [review]

**Comment by churik** [comment]
@rasom can you please make builds with 60s default interval for testing? Or just say me where can I change it in code, and I'll do it by myself.

**Comment by rasom** [comment]
@churik this line https://github.com/status-im/status-react/blob/9a2dfe31baaaa22e171864628368ab16bd9c6b7d/src/status_im/mailserver/core.cljs#L38

should be `(def max-request-range 60) `

**Comment by churik** [comment]
Tested on IOS 11.4 and Android 8 :
- can't reproduce https://github.com/status-im/status-react/issues/7969;
- fetching messages is working as before;
- "Fetching messages" is blocked while offline;

@rasom delete or squash my commits, and thanks for clue!

Failed test is due to faucet error, so it is not introduced by PR

**Pull request merged**
