### PR TITLE
WIP - Move coercion to place after id computation

### PR DESCRIPTION
**Pull request by janherich**
[comment]: # (Please replace ... with your information. Remove < and >)
[comment]: # (To auto-close issue on merge, please insert the related issue number after # i.e fixes #566)

Alternative attempt at fixing #6466 - works by moving the receive coercion (compatibility changes needed to convert older message data to newest message format which app can understand) to place after message-id calculation, so the message-id is always calculated from raw, original received data. 
The only reason why `:message-id-old-format` is necessary anymore is the fact that record namespaces were changed.

status: WIP

### CODE REVIEW

**Comment by annadanchenko** [comment]
@janherich I'm going to test https://github.com/status-im/status-react/pull/6448 Please, let me know if this PR overwrites or modifies logic for #6448 and if it makes sense to have it tested

**Comment by janherich** [comment]
@annadanchenko This PR is just another attempt, currently not finished/compiling, so please proceed with #6448, if it fixes the problem, then I will close this PR.

**Comment by annadanchenko** [comment]
#6448 didn't fix the problem @janherich

**Comment by annadanchenko** [comment]
@janherich build for this PR failed, are you fixing it?

**Comment by janherich** [comment]
Will be solved in different way

**Pull request closed without merging**
