### PR TITLE
[#13331] Back button changes in chat view when scrolling (iOS)

### LINKED ISSUE #12806: statusBar is black with translucent true option when showOverlay on some Android devices
# Bug Report

## Problem 
statusBar is black with translucent true option when showOverlay on some Android devices

bump react-native-navigation when https://github.com/wix/react-native-navigation/pull/7343 is merged

### LINKED ISSUE #13330: Wallet buttons are overlapped with tabs buttons in the individual wallet account view (iOS)
# Bug Report

## Problem 

Screenshot 2022-05-06 at 15 53 05

### Reproduction

1. Open Wallet on iOS
2. Open `Ethereum account`

### Additional Information

- Status version: version with merged https://github.com/status-im/status-react/pull/13324
- Operating System: iOS

[comment]: # (Please, add logs/notes if necessary)

### LINKED ISSUE #13331: Back button changes in chat view when scrolling (iOS)
# Bug Report

## Problem 

https://user-images.githubusercontent.com/67952253/167147848-69a12165-8c59-45a0-b9e0-b97bbf2edd36.MP4

### Reproduction

1. Open Status
2. Join a public chat
3. Scroll up and down

### Additional Information

- Status version: version with merged https://github.com/status-im/status-react/pull/13324
- Operating System: iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by flexsurfer**
fixes #13330
fixes #13331
fixes #12806

### CODE REVIEW

**Review by Parveshdhull — APPROVED** [review]

**Comment by jakubgs** [comment]
The error is:
```
Could not determine the dependencies of task ':react-native-notifications:compileReactNative60ReleaseAidl'.
> Could not resolve all task dependencies for configuration ':react-native-notifications:reactNative60ReleaseCompileClasspath'.
   > Could not resolve com.google.firebase:firebase-installations-interop:16.0.1.
     Required by:
         project :react-native-notifications > com.google.firebase:firebase-messaging:21.1.0
         project :react-native-notifications > com.google.firebase:firebase-iid:21.1.0
         project :react-native-notifications > com.google.firebase:firebase-installations:16.3.5
```
But we can clearly see that version `16.0.1` of `firebase-installations-interop` is included in the Gradle dependencies:
https://github.com/status-im/status-react/blob/3e9ea86d4045d45ed138f4fcf87a8585e73225ab/nix/deps/gradle/deps.list#L412-L413

**Comment by jakubgs** [comment]
But we can also see that `firebase-installations-interop` JSON entry lacks SHA of the JAR:
https://github.com/status-im/status-react/blob/3e9ea86d4045d45ed138f4fcf87a8585e73225ab/nix/deps/gradle/deps.json#L4440-L4448
And after running `make nix-updage-gradle` myself I now see it:
```diff
diff --git a/nix/deps/gradle/deps.json b/nix/deps/gradle/deps.json
index 4612c8040..ac53edf3d 100644
--- a/nix/deps/gradle/deps.json
+++ b/nix/deps/gradle/deps.json
@@ -4444,6 +4444,10 @@
     "pom": {
       "sha1": "2af5462edc7e7f96f6a222bee0d6e85b0722df2f",
       "sha256": "0652akff9fhs88slpzqjcsbk29lji32xf0nm7qhn0w229dcvjwn8"
+    },
+    "jar": {
+      "sha1": "02d0ec2c402c28576438d997293ba7dea90c87c9",
+      "sha256": "0g7w3wyk69qyr4ypi8nml6sw9f3a92sqaq8vinjfp98jv4ifb4mp"
     }
   },
```
So that just looks like a temporary networking issue causing a missing JAR.

**Comment by qoqobolo** [comment]
@flexsurfer thanks for the fixes!

### ISSUE 1: The back button is slightly shifted upward when reopening the app (device specific issue)
I tried to reproduce this issue on several emulators and on a couple of real devices, but it seems to be replicated only on one device: **Pixel 2** (Android 11), so not sure it's worth fixing.
But other devices still can be affected. WDYT?

UPD: Also reproduced on Xiaomi redmi note 7 and Pixel 3a emulators

_Steps:_
1. Create a user
2. Close the app
3. Open the app

After reopening the login screen the button is positioned normally.

https://user-images.githubusercontent.com/67952253/167447131-0686479d-aa05-41d2-9f0a-6c088fffbcc9.mp4

**Comment by flexsurfer** [comment]
https://github.com/wix/react-native-navigation/issues/7094

**Comment by flexsurfer** [comment]
@qoqobolo should be fixed now, i've made changes in splash screen, so we need to check splash screen dark/light on both android/ios

also https://github.com/status-im/status-react/issues/12806 should be fixed

**Comment by qoqobolo** [comment]
Thanks @flexsurfer!
Yeah, there is an issue with the splash screen on iOS.

### ISSUE 2: Splash screen is light in dark mode on iOS
There is a comparison of the develop and the PR build on the video.
The device is in dark mode and both builds are set to system mode.
If set dark mode in the setting, nothing changes. 

https://user-images.githubusercontent.com/67952253/167635980-6124641d-3bc1-4e71-898e-68852223e54d.MP4

**Comment by flexsurfer** [comment]
thanks @qoqobolo fixed

**Pull request closed without merging**
