### PR TITLE
chore: add composer button to quo2 and use in app

### LINKED ISSUE #16844: Wrong color of composer buttons
сс @J-Son89 followup of https://github.com/status-im/status-mobile/pull/16772

**Actual result:** 

photo_2023-08-01 14 19 15

**Expected result:** 

[Figma](https://www.figma.com/file/7KIYbhoqNGAIFonE0w9TDz/Messages-for-Mobile?type=design&node-id=8438-538622&mode=design&t=GsYjbzFe6Llu9kHy-0)

Messages for Mobile – Figma 2023-08-01 14-18-48

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

### PR DESCRIPTION
**Pull request by J-Son89**
fixes: https://github.com/status-im/status-mobile/issues/16844

This pr adds the composer buttons: https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?type=design&node-id=25780-229859&mode=design&t=8CjTcYy1jVp0FHLe-4

and adds them to quo2 preview screens in Buttons -> composer buttons.

It also uses them on the composer screen:
https://www.figma.com/file/wA8Epdki2OWa8Vr067PCNQ/Composer-for-Mobile?type=design&node-id=3253-535124&mode=design&t=EYHMPxRHOmb8Ofg1-4

Design and QA test 🙏 

**light mode & dark mode**
<div>

</div>
**composer dark and light mode**
<div>

</div>

### CODE REVIEW

**Review by flexsurfer — APPROVED** [review]

**Review by ajayesivan — COMMENTED** [review]
The code looks good to me. 

The icon & blur background is not aligned properly.

**Comment by J-Son89** [comment]
> The code looks good to me. 
> 
> 
> 
> The icon & blur background is not aligned properly. 
> 
> 
> 
> 
> 
> 

Whoops, good spot @ajayesivan !!

**Review by OmarBasem — APPROVED** [review]
LGTM 👍

**Review by alwx — APPROVED** [review]

**Comment by pavloburykh** [comment]
@J-Son89 thanx for the PR. Please take a look at the issues


### ISSUE 1 Record/mic button still has wrong color

**Actual result:**

photo_2023-08-09 12 43 56

**Comment by pavloburykh** [comment]
### ISSUE 2 Alert is missing when tapping stickers button

**Actual result:**

https://github.com/status-im/status-mobile/assets/97245802/fda53185-219c-4f7b-99ae-50c09c068e53

**Expected result:**


https://github.com/status-im/status-mobile/assets/97245802/d82eea25-7b5f-435b-9f2b-af6907f21add

**Comment by J-Son89** [comment]
Thanks @pavloburykh, will address! :)

**Comment by J-Son89** [comment]
@pavloburykh both issues should be addressed now 👍

**Comment by pavloburykh** [comment]
> @pavloburykh both issues should be addressed now 👍

Thanx @J-Son89 ! LGTM! 

@Francesca-G please review from your side.

**Review by Francesca-G — APPROVED** [review]
Good job ✨

**Pull request merged**
