### PR TITLE
[#4779] fix Bootnodes are shown as enabled when they are not

### LINKED ISSUE #4779: Toggles ("Bootnodes", "Development mode", "Save password until login") are shown as enabled when they are disabled until app restart
### Description

*Type*: Bug

*Summary*: Bootnodes (Profile -> Bootnodes) are being enabled when development mode is turned ON. It happens only on iOS, Android works fine.

#### Expected behavior
Bootnodes are not enabled when dev mode is ON. They can be enabled only by a user switching the "bootnodes enabled" toggle.

#### Actual behavior
Bootnodes are enabled when dev mode is ON.

### Reproduction

- Open Status on iOS 
- Go to Profile
- Turn on dev mode
- Open Bootnodes settings

### Additional Information
* Status version: nightly, 15 June
* Operating System: iOS

### PR DESCRIPTION
**Pull request by rasom**
fix #4779

status: ready

### CODE REVIEW

**Comment by ghost** [comment]
### Pull Request Checklist
- [x] Have you updated the documentation, if impacted (e.g. [docs.status.im](https://docs.status.im/docs/build_status.html))?

**Review by flexsurfer — APPROVED** [review]

**Review by mandrigin — APPROVED** [review]

**Review by dmitryn — APPROVED** [review]

**Comment by annadanchenko** [comment]
@rasom is the fix only about bootnodes or other places where toggle is used (e.g. Save password until login on Sign in screen; and several toggles in Profile ->  Advanced besides bootnodes)?

**Comment by SlizkovaGanna** [comment]
**Cases tested:**

1) The failed auto test scenarios (**all false fails**) - tested on Android and iOS
test_create_account
test_filters_from_daap
test_copy_and_paste_messages

2) The main scenario with bootnodes - tested on Android and iOS

**Fixed:** Bootnodes (Profile -> Bootnodes) are being enabled when development mode is turned ON. It happens only on iOS, Android works fine. - checked with all 3 toggle bars: Bootnodes, web3, Development mode

3) Secondary scenarios  - tested on Android and iOS

**Cannot reproduce:** Create another account, the dev mode toggle shows ON but in reality the development mode is off 

**Cannot reproduce:** "Save password until login" looks as turned on (toggle is enabled; but actually it is turned off, which is visible after app restart) 

4) "Save password until login" scenarios - tested on iOS only

**Issues found** Killing the app 3 scenarios:

1. just run the app - passed
2. use Push Notifications when app is closed to open the app - issues are described below
3. use deep link when app is closed to open the app (ex. https://get.status.im/chat/public/status ) - issues are described below

**Passed:** Leaving app on the background scenario - user is redirected to the app directly, skipping Login screen 

5) Negative scenarios, info taken from https://github.com/status-im/status-react/pull/5617

**Not implemented yet:** A case with Face ID/Touch ID not being set up - 'Save password until logout' toggle button is present, but not available, see https://github.com/status-im/status-react/issues/5674 for details

**Issues found:** ( reproducible on iOS 11.4.1)
All those issues were checked on a nightly dev build also, and they do not reproduce there:
An issue that reproduces on Dev was reported separately - https://github.com/status-im/status-react/issues/6155

**1) No matter if "Save password until login" is turned off or on, upon click on Push Notification, user is redirected to Login screen with 'Signing you in' stuck in an infinite loop**

Steps to reproduce:
1. On login screen, switch toggle button 'Save password until logout' On
2. Login with your account
3. Leaving the app to run on the background, go to Homepage and kill the app
4. From a separate user that is added to your contacts, send a message to 1-1 chat
5. Click on Push Notification message

_Expected behavior:_ User is directed to the app skipping the Login screen - on Login screen 

_Actual behavior:_ User is directed to Login screen with 'Signing you in' stuck in an infinite loop, not being actually logged in.

Note: If you repeat Steps 3-5 after this, user is directed to Login screen with no actions, even though 'Signing you in' message should appear indicating that user is being auto-logged in

**Same, but negative scenario:**
 
Steps to reproduce:
1. On login screen, switch toggle button 'Save password until logout' On
2. Login with your account
3. Leaving the app to run on the background, go to Homepage and kill the app
4. From a separate user that is added to your contacts, send a message to 1-1 chat
5. Click on Push Notification message

_Expected behavior:_ User is directed to Login screen with nothing happening

_Actual behavior:_ User is directed to Login screen with 'Signing you in' stuck in an infinite loop, even though there should be no attempts to auto-login the user

**2) For deep links, when "Save password until login" was turned on, auto-login is not sucessful**

Steps to reproduce:
1. For a new account, on login screen, switch toggle button 'Save password until logout' On
2. Login with your account
3. Leaving the app to run on the background, go to Homepage and kill the app 
4. Use a deep link and select 'Open in Status app' option (ex. https://get.status.im/chat/public/status )

_Expected behavior:_ User is directed to Login screen with 'Signing you in' in process, and after - user is auto-logged in 

_Actual behavior:_ User is directed to Login screen with 'Signing you in' in process, but after it's done, user is still on Login page.

**Comment by SlizkovaGanna** [comment]
@rasom I've re-tested the issues on nightly DEV (5 Oct), and those two can be reproduced only on PR:

**1) No matter if "Save password until login" is turned off or on, upon click on Push Notification, user is redirected to Login screen with 'Signing you in' stuck in an infinite loop**

Steps to reproduce:

On login screen, switch toggle button 'Save password until logout' On
Login with your account
Leaving the app to run on the background, go to Homepage and kill the app
From a separate user that is added to your contacts, send a message to 1-1 chat
Click on Push Notification message
Expected behavior: User is directed to the app skipping the Login screen - on Login screen

Actual behavior: User is directed to Login screen with 'Signing you in' stuck in an infinite loop, not being actually logged in.

Note: If you repeat Steps 3-5 after this, user is directed to Login screen with no actions, even though 'Signing you in' message should appear indicating that user is being auto-logged in

Same, but negative scenario:

Steps to reproduce:

On login screen, switch toggle button 'Save password until logout' On
Login with your account
Leaving the app to run on the background, go to Homepage and kill the app
From a separate user that is added to your contacts, send a message to 1-1 chat
Click on Push Notification message
Expected behavior: User is directed to Login screen with nothing happening

Actual behavior: User is directed to Login screen with 'Signing you in' stuck in an infinite loop, even though there should be no attempts to auto-login the user

**2) For deep links, when "Save password until login" was turned on, auto-login is not sucessful**

Steps to reproduce:

For a new account, on login screen, switch toggle button 'Save password until logout' On
Login with your account
Leaving the app to run on the background, go to Homepage and kill the app
Use a deep link and select 'Open in Status app' option (ex. https://get.status.im/chat/public/status )
Expected behavior: User is directed to Login screen with 'Signing you in' in process, and after - user is auto-logged in

Actual behavior: User is directed to Login screen with 'Signing you in' in process, but after it's done, user is still on Login page.

There is a guess that those issues might get fixed on DEV after https://github.com/status-im/status-react/pull/6060 and 
https://github.com/status-im/status-react/pull/6056

@rasom could you please re-base your PR on the latest Nightly, so that those issues can be re-tested once more, and crossed out.
Thank you!

<blockquote><div><strong><a href="https://get.status.im/chat/public/status">Join the public chat: #status in Status</a></strong></div></blockquote>

**Comment by rasom** [comment]
@SlizkovaGanna rebased

**Comment by SlizkovaGanna** [comment]
Re-tested with the new PR against the new nightly PR

Failed auto-tests were checked, and none of them were PR-specific bugs

Main toggle button scenarios were tested, and no new issues were found.

Cannot reproduce Issue #2 - For deep links, when "Save password until login" was turned on, auto-login is not sucessful 

Reported separately, as it is a general issue - Issue #1 - https://github.com/status-im/status-react/issues/6186

So, there are no PR-specific issues, this one is good to go.

**Pull request merged**
