### PR TITLE
Correct ordering of messages (#224)

### LINKED ISSUE #224: Ordering of messages
Currently we don't guarantee that all messages will be received in the same order.
For example, user A sends 5 messages: "1", "2", "3", "4", "5"
User B receives "1", "3", "4", "2", "5"

### PR DESCRIPTION
**Pull request by alwx**
Fixes #224 
Uses Lamport timestamps (https://en.wikipedia.org/wiki/Lamport_timestamps) algorithm cause it is much simpler than vector clock, but works perfect in this case.

### CODE REVIEW

**Comment by rasom** [comment]
Something went wrong when I sent command:

ezgif-4097290114

**Comment by alwx** [comment]
@rasom fixed

**Comment by rasom** [comment]
Wrong order of the messages in console chat

ezgif-3583716800

**Comment by alwx** [comment]
Fixed and squashed. 
Sorry for the delay and all those problems with this task.

**Comment by rasom** [comment]
I turned off wifi on genymotion, sent for messages, and then turned it on again.

real device (sender):



genymotion (receiver):

screen shot 2016-10-19 at 16 04 28

**Comment by alwx** [comment]
@rasom finally everything is fine with commands too

**Pull request merged**
