### PR TITLE
Dont use json-string in network config

### LINKED ISSUE #4450: App crashes when creating custom networks
### Description

App crashes when creating custom network

#### Expected behavior
Custom network is added
#### Actual behavior
App crashes

### Reproduction

1) Go to profile
2) Enable dev mode
3) Go to networks
4) Click on +
5) Add a network

### PR DESCRIPTION
**Pull request by cammellos**
fixes #4450 
### Summary:

Updates code to use clojure data structure rather than json string

status: ready

### CODE REVIEW

**Review by jeluard — APPROVED** [review]

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/e5ZnXe for branch PR-4451

<blockquote><div><strong><a href="https://i.diawi.com/e5ZnXe">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/5pHsUd for branch PR-4451

<blockquote><div><strong><a href="https://i.diawi.com/5pHsUd">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Review by flexsurfer — APPROVED** [review]

**Review by janherich — APPROVED** [review]

**Review by yenda — APPROVED** [review]

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/ZSB87o for branch PR-4451

<blockquote><div><strong><a href="https://i.diawi.com/ZSB87o">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/nH7sCX for branch PR-4451

<blockquote><div><strong><a href="https://i.diawi.com/nH7sCX">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/UevkTt for branch PR-4451

<blockquote><div><strong><a href="https://i.diawi.com/UevkTt">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/uVqBdK for branch PR-4451

<blockquote><div><strong><a href="https://i.diawi.com/uVqBdK">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by annadanchenko** [comment]
After discussion with @cammellos in slack:  App users will not experience the issue because to get the crash app should be run in debug mode, but developers who run app locally will get the crash. 

moving the PR to ready to merge as it was already tested bby @cammellos that PR will fix the issue for developers

**Pull request merged**
