### PR TITLE
[#4554] prevent error on removing nil filter

### LINKED ISSUE #4554: "null is not an object" appeared every time I wanted to switch networks
### Description

*Type*: Bug

*Summary*: The error was appearing when I tried to switch networks. I was on Rinkeby and I wanted to switch to Ropsten. In the end I wasn't able to change networks. Every time I pressed connect button, the error appeared. Killing the app fixed it. I could not replicate it anymore.

#### Expected behavior
No error when switching networks.

#### Actual behavior
"null is not an object" error was preventing me from switching networks.

### Reproduction

I was not able to reproduce the issue.

### Additional Information
* Status version: release/0.9.19 25, 08e0ee9, May 31
* Operating System: happened on iOS

### PR DESCRIPTION
**Pull request by rasom**
fixes #4554 

status: ready

### CODE REVIEW

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/4vFbFb for branch PR-4557

<blockquote><div><strong><a href="https://i.diawi.com/4vFbFb">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/oxSfWA for branch PR-4557

<blockquote><div><strong><a href="https://i.diawi.com/oxSfWA">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Review by yenda — COMMENTED** [review]
I'm ok with it but what are the cases where this occurs ? For me it only happens when there was other bugs so I'm worried that it would hide symptoms of more problematic bugs

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/RM4BQZ for branch PR-4557

<blockquote><div><strong><a href="https://i.diawi.com/RM4BQZ">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
@yenda agree, better to figure why it actually happens

**Pull request closed without merging**
