### PR TITLE
[Fix] User is able to join the community without approval of admin

### LINKED ISSUE #15705: The request sender is able to join the community without an admin request accepting if the sender leaves the community, cancels the request, then sends the request one more time
#### Preconditions:
- User_A is a private community admin
- User_B joined the community

#### Steps to reproduce:
1. User_B: leaves the community
2. User_B: Sends the request to join the community 
3. User_B: Cancels request to join
4. User_B: Sends the request to join the community 

#### Actual result:
User_B joined the community after step 4

https://user-images.githubusercontent.com/52490791/233016009-f6460b8c-0cbb-4e05-b656-e661a401202b.mp4

#### Expected result:
User_B sent a request which should be handled by the Admin user

#### ENV:
- Nightly 20 Apr 2023

### PR DESCRIPTION
**Pull request by smohamedjavid**
fixes #15705

### Summary

This PR fixes the bug where the user can join the community without the explicit approval of the admin.

Status Go PR: https://github.com/status-im/status-go/pull/3425

### Problem

When a user leaves the community. The user is not removed from the member's list (as the admin has the right to do it) but marked as **not** joined the community. Until the `RequestToLeave` message is received by the admin, the user is not removed from the community.

If the admin node is **offline**, the user would be under the false impression that they have left the community.

### Solution

Introducing the `RequestToLeaveCommunity` method, where the user will send just the `request to leave` message without modifying any community data/description.

In the existing handling of the request to leave, the admin will automatically remove the user from the community when the admin is online. This will remove the user in a **clean state**. 

We just need to inform the user that they will be removed from the community when the admin node is online when they leave the community.

### Platforms

- Android
- iOS

##### Preconditions:
- User **"A"** is a admin of private community
- User **"B"** joined that community

##### Steps to reproduce:
- User **"B"** leaves the community
- User **"B"** Sends the request to join the community
- User **"B"** Cancels request to join
- User **"B"** Sends the request to join the community

status: ready

### CODE REVIEW

**Review by J-Son89 — APPROVED** [review]

**Review by ilmotta — APPROVED** [review]

**Review by briansztamfater — APPROVED** [review]

**Review by ajayesivan — APPROVED** [review]

**Review by jo-mut — APPROVED** [review]

**Comment by pavloburykh** [comment]
Hey @smohamedjavid, thanks for the PR! I appreciate your effort on this. However, I'd like to discuss a few concerns based on the current implementation and the @status-im/design-team's input.

Based on current [designs](https://www.figma.com/file/apCsJHT8J58JXbJD2igtbd/Context-Drawers-for-Mobile?node-id=793-275497&t=1l2jBKZHrOk4QPlV-0)  it appears that the new "leaving community" functionality differs from our initial expectations. 

As a user, I would expect the ability to leave a community at any time, regardless of whether the admin node is online or offline.

Consider the case where the community admin remains offline for an extended period (days, weeks, months). In this scenario, the user would still be a community member despite their intention to leave. This user experience could be confusing.

Additionally, I'd like to clarify whether the current implementation should affect both private and open communities. 
Because of this bug https://github.com/status-im/status-mobile/issues/14956 it becomes impossible to leave open community under new implementation.

**Comment by pavloburykh** [comment]
Please also take a look at the following issue:

### ISSUE 1 User who has left community receives "You are kicked from community" notification

**Preconditions:** User A is community admin, User B is a regular community member. User A node is online

**Steps:** 

1. User B leaves the community
2. See if there any new notifications for User B in AC

**Expected result:** We should use a different type of notification with text like "You have left the community" or something similar. If this is not possible, it is better not to show any notification. The "You are kicked from community" notification does not accurately represent the situation when a user initiates leaving the community, as they are not being kicked but instead leaving voluntarily.

**Actual result:** User B  receives "You are kicked from community" notification


https://user-images.githubusercontent.com/97245802/235137134-a2e9bc7f-6b52-4f54-86fe-12f8da4dfeb5.mp4

**Comment by pavloburykh** [comment]
I'd appreciate it if you could address these concerns and clarify the current implementation with the @status-im/design-team. Thank you!

**Comment by smohamedjavid** [comment]
Hey @pavloburykh!

Apologies for the late response, and thanks a lot for testing this PR!

I agree that the current fix would deviate from the original requirements.

> As a user, I would expect the ability to leave a community at any time, regardless of whether the admin node is online or offline.
>
> Consider the case where the community admin remains offline for an extended period (days, weeks, months). In this scenario, the user would still be a community member despite their intention to leave. This user experience could be confusing.

The current Figma design is under the impression the user will leave the community immediately. 
If the admin is Offline, that's where the bug is encountered. We need to think about this scenario too as removing the user from the community is actually done by the admin, NOT by the user themselves.

I will close this PR as the bug fix requires discussion with the design team for a proper solution for closed and open communities citing UX concerns.

Thanks for testing this PR! @pavloburykh

**Pull request closed without merging**
