### PR TITLE
fix: remove qa-only features(unicorn, skull)

### LINKED ISSUE #17483: Remove leftovers of handling cellular data from the app
Leftovers from cellular data handling can be removed from the app: 
- popup "Sync using mobile data?"
IMAGE 2023-10-03 13:47:48
- indicators of offline/online/mobile data
IMAGE 2023-10-03 13:47:56
- Mobile data settings (and I suppose should be set to "Use mobile data" by default)
IMAGE 2023-10-03 13:49:01

Not sure about the logic related to this functionality (should it be removed @cammellos ?), but this should be definitely removed from UI

### PR DESCRIPTION
**Pull request by codemaster115**
fixes #17483 

### Summary

Fix Design feedback - 1.25
https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS/Feedback-for-Mobile?type=design&node-id=6139-38783&mode=design&t=uNHJAWN7C6mRMmCJ-4

#### Platforms

- Android
- iOS
- macOS
- Linux
- Windows

status: ready

### CODE REVIEW

**Review by J-Son89 — APPROVED** [review]
nice :)

**Review by ilmotta — APPROVED** [review]

**Comment by churik** [comment]
@codemaster115 
I installed build, switched to the mobile network, and got a bottom sheet that should not be there according to https://github.com/status-im/status-mobile/issues/17483

Please, take a look.
IMAGE 2023-10-11 12:40:35

**Review by ilmotta — APPROVED** [review]

**Comment by churik** [comment]
The leftovers from profile will be removed with profile re-design, the rest from https://github.com/status-im/status-mobile/issues/17483 has been removed.

**Comment by codemaster115** [comment]
> The leftovers from profile will be removed with profile re-design, the rest from #17483 has been removed.

Do you mean that there's something else more to be removed yet? @churik

**Comment by churik** [comment]
@codemaster115 
https://github.com/status-im/status-mobile/issues/17483#issue-1923955580 - Mobile data from settings, as mentioned in issue, but it can be removed later

**Comment by churik** [comment]
@codemaster115 is there a reason why it is not merged yet?

**Comment by codemaster115** [comment]
> @codemaster115 is there a reason why it is not merged yet?

Nope, I will merge it soon.

**Pull request merged**
