### PR TITLE
fix: ask for push notification permissions on toggle in settings if skipped during onboarding

### PR DESCRIPTION
**Pull request by siddarthkay**
related to  #18251

## Summary

The Android app would not ask for permissions to show push notifications if the permissions were skipped during login but later enabled via settings.
This PR fixes that.
We also take this opportunity to upgrade `react-native-permissions` library to `4.1.1`
 
## Testing notes
- Create fresh account.
- Don't give notification permissions during onboarding.
- Go to Profile > Notifications.
- Enable "Local Notifications" switch.
- You would now get a permissions prompt on Android 13 and above.

## Platforms
- Android

## Screenshot
Screenshot 2024-02-18 at 2 41 42 AM

status: ready

### CODE REVIEW

**Review by ibrkhalil — APPROVED** [review]

**Review by jakubgs — APPROVED** [review]

**Comment by mariia-skrypnyk** [comment]
Hi @siddarthkay !

Thanks for your PR. 
Can you describe me what in your opinion is the common result if we:

1) skip notification permissions during onboarding
2) go to the device settings-> Status app 
3) turn on Notifications

I've tried this and I had Notification toggle OFF in Status app

I've googled best practice for Android 13.0+ and found that:

> if we declined notification permission during installation and then turned it on in device settings then status settings should also be turned on

**Comment by siddarthkay** [comment]
ah @mariia-skrypnyk : I did not think of this user journey, we could add a check on notifications screen when user comes back from background to see if permissions were changed or not outside the app and directly in system settings.
Our existing app relies on the user giving permissions first and then we would enable the toggle.
If this does not add additional perf overhead I could look into making that change in this PR.

**Comment by mariia-skrypnyk** [comment]
> ah @mariia-skrypnyk : I did not think of this user journey, we could add a check on notifications screen when user comes back from background to see if permissions were changed or not outside the app and directly in system settings. Our existing app relies on the user giving permissions first and then we would enable the toggle. If this does not add additional perf overhead I could look into making that change in this PR.

@siddarthkay  I need to recheck the behaviour of PN in the scenario I've described above and let you know!
Thanks!

**Comment by mariia-skrypnyk** [comment]
@siddarthkay asked Design regarding use cases above [here](https://discord.com/channels/624634427930312714/928625369542713396/1212390388455968769)

Also, rechecked what happened if user turns ON skipped PN permissions on Onboarding from device settings and we have NO working PN after that (wrong behaviour)

**Comment by mariia-skrypnyk** [comment]
**ISSUE 2: Error on Wallet tab of Share screen**

**Steps:**
1) Login to app
2) Go to Share-> Wallet tap
3) try to scroll the screen

**Actual result:**
Screenshot 2024-02-28 at 14 46 20

Logs are attached. 
[status_logs (1).zip](https://github.com/status-im/status-mobile/files/14434846/status_logs.1.zip)

**Expected result:** no error

**Comment by flexsurfer** [comment]
looks stale

**Pull request closed without merging**
