### PR TITLE
Include a 'My Profile' button in the Start New Chat dialogue

### LINKED ISSUE #11990: Include a 'My Profile' button in the Start New Chat dialogue
# Problem

The scope of this issue is to add a shortcut to your contact details (chat key and ENS username) inside the Start New Chat dialogue. This follows recent user research studies and prior experiences where we identified that people have difficulty figuring out what to enter when asked for a chat key or ENS name _and_ expecting to share their details with others also from this location.

## Implementation

A small fixed location button is anchored at the bottom of the screen. After interacting it shows the [same popover](https://www.figma.com/file/aS1ct66VQ6V0cio7vSqS8UoG/Chat?node-id=19775%3A177) with user details that we use for sharing a profile. It reacts to keyboard position.

Screenshot 2021-04-14 at 12 08 12

---

👉  [Figma](https://www.figma.com/file/aS1ct66VQ6V0cio7vSqS8UoG/Chat?node-id=7957%3A169) 👈 

## Acceptance Criteria

Design was implemented 

Thank you 🙏

### PR DESCRIPTION
**Pull request by briansztamfater**
fixes #11990 

### Summary

Include a 'My Profile' button in the Start New Chat dialogue

##### iOS

my-profile-demo-ios

##### Android

my-profile-demo-android

#### Platforms

- Android
- iOS

##### Functional

- 1-1 chats

### Steps to test

- Open Status
- Go to Chat tab
- Tap on + button
- Tap on "Start new chat"
- Interact with "My Profile" button

status: ready

### CODE REVIEW

**Comment by errorists** [comment]
please tell me you didn't hardcode the user profile picture 😅

**Comment by briansztamfater** [comment]
> please tell me you didn't hardcode the user profile picture 😅

didnt-see-anything

**Review by flexsurfer — APPROVED** [review]

**Comment by qoqobolo** [comment]
@briansztamfater thanks for your work! Looks great :)

Please, add accessibility-id to the profile picture in the 'My Profile' button.
Once it is added, the PR is ready to be merged.

Screenshot 2021-04-27 at 15 16 51

**Comment by errorists** [comment]
agree, great work! 👏

**Comment by briansztamfater** [comment]
Thanks, just added the accessibility id to the profile picture :)

**Pull request merged**
