### PR TITLE
Small thing: package-lock.json removed

### PR DESCRIPTION
**Pull request by alwx**
There is no need to keep package-lock.json in the repo. This PR removes it and adds a line to .gitignore

### CODE REVIEW

**Comment by jeluard** [comment]
Goal of `package-lock.json` is to be in a repo, see the [doc](https://docs.npmjs.com/files/package-lock.json) for more context.

**Review by jeluard — CHANGES_REQUESTED** [review]
We want to keep this file.

**Comment by alwx** [comment]
What's the point of having this file in VCS but asking to remove it from commits then?

**Comment by jeluard** [comment]
@alwx It is supposed to change only when you update a npm module version or add a new one. On some environment there is an issue where it changes but shouldn't not. We have an open issue for that.

**Pull request closed without merging**
