### PR TITLE
fix/3509 workaround for permissions callback not working

### LINKED ISSUE #3509: Camera doesn't open after giving permission when adding contact
### Description

*Type*: Bug

*Summary*: After installing app when user adds a contact scanning QR code and giving camera access he needs to tap QR code again

#### Expected behavior
Camera opens

#### Actual behavior
User stays on the New chat view with list of contacts and should tap QR code icon again to scan QR code

### Reproduction
- Open Status after the install
- Click Plus button on the Home view
- Click Start new chat
- Click QR code icon
- Allow camera access

### Additional Information
* Status version: 0.9.10-740-gba056bee+ (nightly build from 02.03)
* Operating System: OnePlus 5, Android 8.0.0

### PR DESCRIPTION
**Pull request by yenda**
Fixes #3509 

This is a workaround to get a callback for the permission request on android. 

When prompting the user for a permission request the promise never executes the  `.then` however there is a `status-module-initialized` event that is triggered when the user grants or denies the permissions.
So we reset this atom in `request-permissions` for android and if it is not `nil` we dispatch it in the `:status-module-initialized` event this time `.then` will be called. 
If the user denies he will be asked a second time but it is better than nothing happening when the user accepts.

To fix definitively: find out why the promise doesn't executes it's then the first time, might have something to do with the fact that the app is apparently resumed once the user responds to the pop-up (that's what triggers status-module-initialized event)

I also cleaned up the last `handlers->` macro usage

status: ready

### CODE REVIEW

**Comment by jeluard** [comment]
The issue is that the `then` is not triggered right after the permission is first granted?

**Comment by yenda** [comment]
@jeluard yes the callback is not called back the first time, as explained I suspect that it is lost somehow as the app seems to be backgrounded while the user is asked for permission in the popup, because after he gives his answer the :status-module-initialized is called which means app was resumed

**Review by jeluard — APPROVED** [review]

**Review by cammellos — APPROVED** [review]
Just tested it and works fine.

**Comment by dmitryn** [comment]
@yenda found the root cause of this bug https://github.com/status-im/status-react/pull/3556

**Pull request closed without merging**
