### PR TITLE
Splash Screen feature

### PR DESCRIPTION
**Pull request by jarradh**
Thanks @adrian-tiberius for getting this working!

### CODE REVIEW

**Comment by rasom** [comment]
It doesn't work on iOS for some reason

**Comment by jarradh** [comment]
@adrian-tiberius can you take a look?

**Comment by rasom** [comment]
That's how it looks in iOS simulator now, do I miss something? 

image

**Comment by rasom** [comment]
That's how it looks on android, and this is what expected as I understand

android

**Comment by jarradh** [comment]
oh jeez, yeah thats not right, it should be using ios/StatusIm/Images.xcassets/LaunchImage.launchimage/Contents.json and the assets in there

**Pull request merged**
