### PR TITLE
Updated status-go

### LINKED ISSUE #2479: Web3 Filters do not work with status chat bot
Steps to reproduce:

paste
```
var filter = web3.eth.filter('latest');
filter.watch(function (error, log) {
    if(!error) {
        status.sendMessage(log.toString()); 
    } else {
        status.sendMessage(error.toString());
    }
});
```
into a js file and add as a chat bot

returns a message with:

Error: EOF

### PR DESCRIPTION
**Pull request by flexsurfer**
fixes #2479, #3822

### CODE REVIEW

**Review by mandrigin — APPROVED** [review]
LTGM

**Review by yenda — APPROVED** [review]

**Comment by antdanchenko** [comment]
An error `undefined is not an object (evaluating 'status_im.transport.utils.sshext(e).requestMessages') ` is shown after account creation/recovery

0008screenshot

**Comment by yenda** [comment]
Works for me

**Comment by yenda** [comment]
bumped to latest version of status-go

**Comment by Serhy** [comment]
No regression here.

**Comment by jeluard** [comment]
@flexsurfer @yenda Can you squash commits?

**Pull request merged**
