### PR TITLE
Upgrade to react-native 0.56

### PR DESCRIPTION
**Pull request by maxhora**
Updating react-native-desktop to version based on react-native 0.56.1

Dependent PRs to be merged along with current one:
https://github.com/status-im/react-native-desktop/pull/340
https://github.com/status-im/re-natal/pull/3

### CODE REVIEW

**Review by vitvly — APPROVED** [review]

**Review by vkjr — APPROVED** [review]

**Comment by yenda** [comment]
did you delete package-lock on purpose ?

**Comment by maxhora** [comment]
@yenda thank you for finding out that, need to back it into git

**Review by yenda — APPROVED** [review]
Do you think it will be possible to get rid of re-natal and use clj-rn soon ?

**Comment by maxhora** [comment]
@churik PR is ready to be tested, but WIP status will be removed only after all depended PRs will be merged (after passing your tests) in 3rd party repos.

**Comment by maxhora** [comment]
@yenda we have ticket for this, just the question of prioritization, I believe.

**Comment by churik** [comment]
@MaxRis 
Got a crash after deleting 1-1 chat > relogin
Crash report: https://github.com/status-im/status-react-desktop-reports/issues/14
Couldn't reproduce anymore.

This is only issue I encountered during testing. 
#### Tested on desktop:
- Link to testrun is [here](https://ethstatus.testrail.net/index.php?/runs/view/1532&group_by=cases:section_id&group_order=asc)
#### Tested on IOS:
- installation
- creating account
- chatting in 1-1, public chats

Can you take a look to crash (was it caused by PR or not)?
If not, Pr is ready to merge.

**Comment by maxhora** [comment]
Thank you @churik ,
I will give it a run, but most of all this crash is related to some another issue and I have seen that someone already reported similar crashed on login occurred randomly, looks like. Thanks!

**Pull request merged**
