### PR TITLE
[WIP] nimbus-light-proxy integration

### PR DESCRIPTION
**Pull request by vitvly**
Depends on https://github.com/status-im/status-go/pull/3281

Tracking issue: https://github.com/status-im/status-go/issues/3282

### CODE REVIEW

**Comment by flexsurfer** [comment]
hey @siphiuel still relevant?

**Comment by flexsurfer** [comment]
hey @siphiuel still relevant?

**Comment by vitvly** [comment]
@flexsurfer yes

**Comment by flexsurfer** [comment]
closing for now as there is no activity for the long time

**Comment by flexsurfer** [comment]
@siphiuel feel free to reopen

**Pull request closed without merging**
