### PR TITLE
[TESTS] Automated tests updated according to new wallet onboarding flow

### PR DESCRIPTION
**Pull request by yevh-berdnyk**
status: ready

### CODE REVIEW

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/Zirson for branch PR-4236

<blockquote><div><strong><a href="https://i.diawi.com/Zirson">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/jaCuri for branch PR-4236

<blockquote><div><strong><a href="https://i.diawi.com/jaCuri">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Review by antdanchenko — APPROVED** [review]

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/EP81S1 for branch PR-4236

<blockquote><div><strong><a href="https://i.diawi.com/EP81S1">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/5S6VJA for branch PR-4236

<blockquote><div><strong><a href="https://i.diawi.com/5S6VJA">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Pull request merged**
