### PR TITLE
Better handling of contact request state & fix on go-waku panic

### LINKED ISSUE #14942: A1 remains in contacts for B1 if B1 has been offline during A1 removed him from contacts and re-sent CR after that
Followup issue from https://github.com/status-im/status-mobile/pull/14878 **cc @cammellos** 

**Steps:**
1. A1 adds B1 to contacts list
2. A1 syncs data to A2 and pair devices
3. B1 performs logout
4. A1 removes B1 from contacts
5. A1 re-sends CR to B1
6. B1 logs in
7. Observe the result

**Actual result:** A1 is still contact to B1. No CR is displayed in AC for B1. B1 is able to send messages to A1 while A1 has got banner about Pending CR. 

**Expected result:** A1 is not in contact list for B1. CR is displayed in AC for B1. 

https://user-images.githubusercontent.com/97245802/215796055-4f53c9fa-ca8a-47d0-b1b8-64807394e7c4.mp4

[A1.zip](https://github.com/status-im/status-mobile/files/10547467/A1.zip)
[B1.zip](https://github.com/status-im/status-mobile/files/10547468/B1.zip)

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### LINKED ISSUE #15023: App crashes on login
# Bug Report

## Problem 

Managed to catch crashes in several cases.
This is the most reliable way to reproduce it:

1. UserA sends a contact request to UserB via `Chat screen` > `+` button > `Add a new contact`
2. UserB accepts the request
3. UserB performs log out > log in several times 

Logs for this case: [crashlog_112.log](https://github.com/status-im/status-mobile/files/10677795/crashlog_112.log)

Also, sometimes the app crashes for the sender of the contact request (step 3, in this case, will be: **UserA** performs log out > log in several times).

Another scenario that was caught in e2e in [this PR](https://github.com/status-im/status-mobile/pull/14988):
1. UserA sends a contact request to UserB via `Chat screen` > `+` button > `Add a new contact`
2. UserB accepts the request and just waits on the home screen

It did not reproduce after rerunning the tests. 

Most often the crash happens with this error:

Screenshot 2023-02-07 at 18 28 58

However, sometimes there is no error at all (Crash on login as well, logs for this case: [geth.log](https://github.com/status-im/status-mobile/files/10677834/geth.log)) or another error in shown (unfortunately I don't have a screenshot, but you can likely see it in the first logs)

### Additional Information

- Status version: nightly 7/02
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by cammellos**
Fixes: #14942
Fixes: #15023

Fixes some issues with contact request state & a panic in go-waku, I can split the two in separate commits if necessary

### CODE REVIEW

**Comment by pavloburykh** [comment]
@cammellos thanx! Please, take a look at the following issue

### ISSUE 1 A1 is removed from B1's contact list after A1 syncs and pairs data with A2

**Steps (that can be observed on video below):**

1. A1 and B1 become mutual contacts
2. Perform relogin by B1 to make sure that A1 is still in contact list
3. Logout by B1
4. Restore A1 multiaccount on A2 (I am using same device for B1 and A2)
5. A1 syncs and pairs with A2
6. Logout by A2
7. Login by B1
8. Pay attention if A1 is still in contact list for B1

**Actual result:** A1 disappeared from B1's contact list. What has not been captured on video but happens sometimes: if A1 re-adds B1 to contacts (e.i. A1 and B1 become mutual contacts again), B1 does not appear in contact list for A2. 

**Expected result:** A1 remains in contact list for B1

https://user-images.githubusercontent.com/97245802/216964911-b73c4535-277e-459a-b5a4-69d7436f947f.mp4

[A1.zip](https://github.com/status-im/status-mobile/files/10662687/A1.zip)
[A2.zip](https://github.com/status-im/status-mobile/files/10662688/A2.zip)
[B1.zip](https://github.com/status-im/status-mobile/files/10662689/B1.zip)

**Comment by pavloburykh** [comment]
### ISSUE 2 B1 does not receive CR from A1 if A1 removes and then re-adds B1 to contact while B1 is offlline

**Steps:**
1. A1 and B1 become mutual contacts
2. A1 syncs and pairs with A2
3. Logout by B1
4. A1 removes B1 form contacts
5. A1 re-adds B1 to contacts
6. Login by B1
7. See if CR from A1 has arrived to AC

**Actual result:** no CR from A1

**Expected result:** CR form A1 should be in AC

[A1.zip](https://github.com/status-im/status-mobile/files/10662763/A1.zip)
[B1.zip](https://github.com/status-im/status-mobile/files/10662764/B1.zip)

https://user-images.githubusercontent.com/97245802/216966618-4f02efaa-f6a5-4c21-b7df-cfa5095ab0f7.mp4

**Comment by pavloburykh** [comment]
@cammellos thanx! ISSUES 1 and 2 seem to be fixed. 

I've face another one, please tale a look

### ISSUE 3 B1 appears as contact to A1 but is not in contact list for paired A2

**Steps:** 

1. Make A1 and B1 mutual contacts
2. Recover A1 account on A2
3. Sync and pair A1 and A2
4. Logout by A2
5. Login by B1
6. A1 removes and re-adds B1 couple of times. Try to add B1 and remove before B1 accepts CR, then send another CR and accept it by B1
7. Logout by B1
8. Login by A2
9. See if B1 in contact list for A2

**Actual result:** B1 is not contact to A2 but in contact list of A1

**Expected result:** B1 should be contact both for A1 and A2 as those are paired accounts. 

[A1.zip](https://github.com/status-im/status-mobile/files/10667415/A1.zip)
[B1_A2.zip](https://github.com/status-im/status-mobile/files/10667416/B1_A2.zip)

https://user-images.githubusercontent.com/97245802/217039661-ece69701-3538-4091-bfa9-f7f1447d4155.mp4

**Review by J-Son89 — APPROVED** [review]

**Review by ilmotta — APPROVED** [review]

**Comment by qoqobolo** [comment]
@cammellos the app just crashed on my device after several logouts > logins in the latest PR build https://github.com/status-im/status-mobile/commit/903d573adcc47b0cdefc46b337883cfe9ab695ab (reproduces constantly)

There are no contacts / contact requests in the account, the app crashed without any error after logout while entering the password. 

[crashlog_0802.log](https://github.com/status-im/status-mobile/files/10683554/crashlog_0802.log)


https://user-images.githubusercontent.com/67952253/217481842-6f9b7fd4-6b77-4b8f-92a0-bbbbdc59fcc7.mp4

**Comment by pavloburykh** [comment]
@cammellos thanx for your fixes!

Just wanted to clarify regarding issues that are in [scope](https://github.com/status-im/status-mobile/pull/14985#issue-1570167216) of this PR: this issue https://github.com/status-im/status-mobile/issues/14946 is still reproducible, so we agreed to fix it separately, correct?

**Comment by pavloburykh** [comment]
@cammellos here are additional logs related to [ISSUE 3](https://github.com/status-im/status-mobile/pull/14985#issuecomment-1419444771) extracted from latest PR builds

[A1.zip](https://github.com/status-im/status-mobile/files/10683619/A1.zip)
[A2_B1.zip](https://github.com/status-im/status-mobile/files/10683620/A2_B1.zip)

**Comment by cammellos** [comment]
> @cammellos thanx for your fixes!
> 
> Just wanted to clarify regarding issues that are in [scope](https://github.com/status-im/status-mobile/pull/14985#issue-1570167216) of this PR: this issue #14946 is still reproducible, so we agreed to fix it separately, correct?

Yes, also, if that's ok, I would fix issue 3 separately, not sure it's a release blocker, I would try to squeeze it in, but I think it should not block cutting the branch/starting to test RC, what do you think?

**Comment by pavloburykh** [comment]
> what do you think?

I agree, thank you!

**Comment by qoqobolo** [comment]
@cammellos still seeing this error on login in https://github.com/status-im/status-mobile/commit/f5da69ac354e88890935a8a51c558dec9e925cb9 :(

[crashlog_08021.log](https://github.com/status-im/status-mobile/files/10685808/crashlog_08021.log)

Screenshot 2023-02-08 at 14 10 34

**Comment by pavloburykh** [comment]
@cammellos thanx a lot for all the fixes. PR is ready to be merged. Failed e2e are not PR related.

**Pull request merged**
