### PR TITLE
ci: use default IPFS Gateway URL

### LINKED ISSUE #20958: Stickers sent from desktop are displayed as a blank message on mobile (Only on release Jenkins builds)
# Bug Report

### Reproduction

1. Make mobile and desktop users mutual contacts
2. Desktop: send a sticker to the chat
3. Mobile: check the chat

#### Expected behavior
The sticker is visible

#### Actual behavior
The sticker is not visible

Screenshot 2024-08-05 at 14 58 26

### Additional Information

- Status version: RC 2.30 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by siddarthkay**
## Summary

This PR removes the config for setting IPFS Gateway URL.
The default in status-go is `https://ipfs.status.im/` which works well.

fixes : https://github.com/status-im/status-mobile/issues/20958

## Testing notes
Please test stickers in PR builds and in release builds.

## Additional notes
This PR should only be merged after https://github.com/status-im/status-jenkins-lib/pull/98 is merged and a tagged version is present in this PR.

## Platforms
- Android
- iOS

status: ready

### CODE REVIEW

**Review by Parveshdhull — APPROVED** [review]

**Review by jakubgs — APPROVED** [review]
We probably will need to improve monitoring of this service.

**Comment by mariia-skrypnyk** [comment]
Hey @siddarthkay !

Checked issue on iOS PR build and on Android release build issue still exist.


Screenshot 2024-09-04 at 11 41 58

**Comment by mariia-skrypnyk** [comment]
@siddarthkay any updates on this?

**Comment by siddarthkay** [comment]
@mariia-skrypnyk : I'll check today. thanks!

**Comment by siddarthkay** [comment]
@mariia-skrypnyk 
I fixed the issue and could receive stickers from Desktop App on both PR and on release builds on my iPhone.

IMG_6269

**Comment by mariia-skrypnyk** [comment]
Hey @siddarthkay !

Thanks for your fix.
Looks good on PR builds.
Couldn't build android release build. Build is failed. 
Can you help me with iOS or Android release build for testing?

**Comment by siddarthkay** [comment]
you can find iOS for this branch in Testflight -> 2.30.21106 (20240912141620)

**Comment by mariia-skrypnyk** [comment]
@siddarthkay checked on release too!

All good!
Thanks!

PR can be merged!

**Pull request merged**
