### PR TITLE
[#6083] upgrade react-native-webview-bridge

### LINKED ISSUE #6083: MY ACCOUNT on explorer.livepeer.org is not available on Status Android App.
### User Story

As a user of **Status Android App** and [**Livepeer open-source video infrastructure**](https://livepeer.org), I want to bond my [Livepeer Tokens (LPT)](https://etherscan.io/token/0x58b6a8a3302369daec383334672404ee733ab239) to Livepeer's Delegated-Proof-of-Stake protocol using Status App's Browser running [Livepeer's Protocol Explorer](https://explorer.livepeer.org/).

This is so that Status Android App's community can also participate in Livepeer's protocol, and become more aware of the opportunities open to them as owners of Livepeer Tokens (LPT).

### Description

*Type*: <Bug|Feature>

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: I would like to be able to use Status' browser to interact with Livepeer's protocol via https://explorer.livepeer.org.

#### Expected behavior

I expect that the wallet built in to Status app is visible to [Livepeer's Protocol Explorer](https://explorer.livepeer.org/me), to the extent that a user can see "MY ACCOUNT".

For example, when I load the same page and logged in with MetaMask add-on to Firefox in Android, it gives me the option of "MY ACCOUNT":

image

#### Actual behavior

As above, when I load [Livepeer's Protocol Explorer](https://explorer.livepeer.org/me) in Status Android App, it does not connect that it is Web 3.0 enabled.

### Reproduction

- Open Status
- Go to Home
- Tap the + icon
- Select Open DApp
- Where it says "Enter URL", type `https://explorer.livepeer.org`
- Notice that "MY ACCOUNT" is not an Option, as it is with MetaMask add-on to Firefox.

### Solution

Need to fix integration between Status App Wallet and Status App Browser. Talk to @ligi about Ethereum Foundation Foundations for Wallets on Android. And did you incorporate @peepdroid into your app as a dApp yet?

### Additional Information

* Status version: ...
Android 0.9.28 Status App

<blockquote><div><strong><a href="https://explorer.livepeer.org/">Livepeer | Protocol Explorer</a></strong></div></blockquote>

### PR DESCRIPTION
**Pull request by rasom**
fix #6083 and http://mandrigin.ru/shh.html

status: ready 

<blockquote></blockquote>

### CODE REVIEW

**Review by dmitryn — APPROVED** [review]

**Review by mandrigin — APPROVED** [review]
👍👍👍

**Review by flexsurfer — APPROVED** [review]

**Comment by lukaszfryc** [comment]
I'm getting 404 while trying to open http://mandrigin.ru/shh.html. @mandrigin is this site up?

**Comment by lukaszfryc** [comment]
Apart from that all looks fine. I have the account tab on Android (and iOS) 👍

**Comment by mandrigin** [comment]
@lukaszfryc I see a typo in the address on your screenshot :)

**Pull request merged**
