### PR TITLE
Upgrade status-go

### PR DESCRIPTION
**Pull request by cammellos**
Contains a fix for decryption of old messages and reset limits on mailserver changed.

### Testing

light regression tests on messaging/mailserver is enough, little changes since what we have in currently.

status: ready

### CODE REVIEW

**Review by mandrigin — APPROVED** [review]

**Review by rasom — APPROVED** [review]

**Comment by annadanchenko** [comment]
@cammellos testing on Android only till we'll have ios build working. 

See that retrieving history from "testanna" public chat took 3-4 minutes on one of the phones (Android 6.0.1, Galaxy s6). Not sure if it's related to this PR but here are logs:
[geth.log](https://github.com/status-im/status-react/files/2918835/geth.log)
[Status.log](https://github.com/status-im/status-react/files/2918836/Status.log)

First time see such errors in geth.log:
```
t=2019-03-01T09:30:13+0000 lvl=eror msg="bad envelope received, peer will be disconnected" peer=82c196d7a77d3a73d7a3b0bb7ec43ed8d6b758703815c4b7191332170cadd331 err="very old message"
t=2019-03-01T09:30:13+0000 lvl=eror msg="bad envelope received, peer will be disconnected" peer=82c196d7a77d3a73d7a3b0bb7ec43ed8d6b758703815c4b7191332170cadd331 err="very old message"
t=2019-03-01T09:30:13+0000 lvl=warn msg="failed to deliver confirmation"                   hash=0x95e82a449bcc86442d882d40446cab06158906ae6ba04b112eb49aaca37737ae peer=82c196d7a77d3a73d7a3b0bb7ec43ed8d6b758703815c4b7191332170cadd331 error="write tcp 192.168.178.20:46074->47.91.156.93:443: use of closed network connection"
```

**Comment by annadanchenko** [comment]
on new Android build 3, if join public chat "testanna" - only 1-2 messages from today are retrieved and no history from yesterday (waiting for 5-6 minutes already)
Galaxy S6, Android 6.0.1 logs: 
[geth.log](https://github.com/status-im/status-react/files/2919110/geth.log)
[Status.log](https://github.com/status-im/status-react/files/2919112/Status.log)

Pixel XL Android 9 logs:
[geth.log](https://github.com/status-im/status-react/files/2919113/geth.log)
[Status.log](https://github.com/status-im/status-react/files/2919115/Status.log)

Steps:
1. install app
2. create account
3. join testanna public chat and wait for history

**Comment by annadanchenko** [comment]
Can reproduce same issue (no yesterday's history retrieved after waiting for 5 minutes) if reinstall build and repeat same steps, geth.log is not very big

```
t=2019-03-01T11:56:35+0000 lvl=info msg="LES protocol is disabled" package=status-go/node
t=2019-03-01T11:56:35+0000 lvl=info msg="Status service api is disabled" package=status-go/node
t=2019-03-01T11:56:35+0000 lvl=info msg="Starting peer-to-peer node"     instance=StatusIM/v0.23.0-beta.7/android-arm/go1.11
t=2019-03-01T11:56:35+0000 lvl=info msg="started whisper v.6.0"
t=2019-03-01T11:56:35+0000 lvl=info msg="Handlers registered"            package=status-go/api.StatusBackend
t=2019-03-01T11:56:35+0000 lvl=info msg="Account reselected"             package=status-go/api.StatusBackend
t=2019-03-01T11:56:35+0000 lvl=info msg="New local node record"          seq=1 id=a54dda8efe01a53f3c65c5a118b4f8885afb1aa7be129cb0e1ca627d77a8cf66 ip=127.0.0.1 udp=0 tcp=58334
t=2019-03-01T11:56:35+0000 lvl=info msg="Started P2P networking"         self="enode://076fefea804f84a9dae45c8ee656abe6d1d3cb558ec306019dfae8bac7687628c984e86c89aad62a6ceffcd6c99732d986994ba957ad0b02f84cca7019193187@127.0.0.1:58334?discport=0"
t=2019-03-01T11:56:35+0000 lvl=info msg="UDP listener up"                net=enode://076fefea804f84a9dae45c8ee656abe6d1d3cb558ec306019dfae8bac7687628c984e86c89aad62a6ceffcd6c99732d986994ba957ad0b02f84cca7019193187@[::]:56174
t=2019-03-01T11:56:35+0000 lvl=info msg="Difference with ntp servers"    offset=3.618481384s
t=2019-03-01T11:56:37+0000 lvl=info msg="Whisper identity selected"      id=5080fa50a8b4692f7e040e6fbeae27dadf630ee789fe71d5f7dbbc06bdfa40de key=0x04f0abd32397bf1c8c6e0a7d8a75d82f04b718887588d95486f9678243af3c0aa2e8d4ca72afb4c35f9e9dfae1032ae27972d557862b2632ae5d598a7d664a030f
t=2019-03-01T11:56:37+0000 lvl=info msg="Initialized encryption service" package=status-go/services/sshext.chat installationID=63f05d0f-4008-5ff8-9d0c-1cfc11a97a64
t=2019-03-01T11:56:38+0000 lvl=info msg="New local node record"          seq=2 id=a54dda8efe01a53f3c65c5a118b4f8885afb1aa7be129cb0e1ca627d77a8cf66 ip=83.162.201.68 udp=0 tcp=58334
t=2019-03-01T11:56:39+0000 lvl=info msg=RequestMessages                  package=status-go/services/sshext.PublicAPI request="{MailServerPeer:enode://74957e361ab290e6af45a124536bc9adee39fbd2f995a77ace6ed7d05d9a1c7c98b78b2df5f8071c439b9c0afe4a69893ede4ad633473f96bc195ddf33f6ce00@47.52.255.195:443 From:1551354999 To:1551441399 Limit:2000 Cursor: Topic:[0 0 0 0] Topics:[[170 128 172 161] [248 148 106 172] [188 106 251 244]] SymKeyID:f834b6cddf1bc6bc791b0196b13ed35a38ba06873fd3b4486acec626aed8772c Timeout:30ns Force:false}"
t=2019-03-01T11:56:50+0000 lvl=info msg=RequestMessages                  package=status-go/services/sshext.PublicAPI request="{MailServerPeer:enode://74957e361ab290e6af45a124536bc9adee39fbd2f995a77ace6ed7d05d9a1c7c98b78b2df5f8071c439b9c0afe4a69893ede4ad633473f96bc195ddf33f6ce00@47.52.255.195:443 From:1551354999 To:1551441399 Limit:2000 Cursor:5c78f016099a871491dd89bf17497a25bbccad49a9f761fdadb3d5771b9dbc7c2fc1364e Topic:[0 0 0 0] Topics:[[170 128 172 161] [248 148 106 172] [188 106 251 244]] SymKeyID:f834b6cddf1bc6bc791b0196b13ed35a38ba06873fd3b4486acec626aed8772c Timeout:30ns Force:false}"
t=2019-03-01T11:58:39+0000 lvl=eror msg="Failed handling message with error" package=status-go/services/sshext.PublicAPI err="no payload"

```

After this changed log level to debug and relaunched the app, today's messages were retrieved but no yesterdays history:
[geth.log](https://github.com/status-im/status-react/files/2919312/geth.log)
[Status.log](https://github.com/status-im/status-react/files/2919313/Status.log)

**Comment by annadanchenko** [comment]
looks like there is some other issue not releated to this PR as in release 0.10.0 I also have similar issue with getting history (waited for 4 minutes already and got only today's history with 3 messages). After waiting for 6 minutes finally history is retrieved in release build
[geth.log](https://github.com/status-im/status-react/files/2919350/geth.log)
[Status.log](https://github.com/status-im/status-react/files/2919351/Status.log)


geth.log contains "very old message" error
```
t=2019-03-01T12:16:18+0000 lvl=eror msg="bad envelope received, peer will be disconnected" peer=4cf1de823dfbc51ed0deaf629e2b319f5908bb641d20d0083884115c65f68c82 err="very old message"
t=2019-03-01T12:16:18+0000 lvl=eror msg="bad envelope received, peer will be disconnected" peer=4cf1de823dfbc51ed0deaf629e2b319f5908bb641d20d0083884115c65f68c82 err="very old message"
t=2019-03-01T12:16:18+0000 lvl=eror msg="bad envelope received, peer will be disconnected" peer=4cf1de823dfbc51ed0deaf629e2b319f5908bb641d20d0083884115c65f68c82 err="very old message"
t=2019-03-01T12:16:18+0000 lvl=eror msg="bad envelope received, peer will be disconnected" peer=4cf1de823dfbc51ed0deaf629e2b319f5908bb641d20d0083884115c65f68c82 err="very old message"
```

**Pull request closed without merging**
