### PR TITLE
Prices handling in commands impl

### PR DESCRIPTION
**Pull request by janherich**
[comment]: # (Please replace ... with your information. Remove < and >)
[comment]: # (To auto-close issue on merge, please insert the related issue number after # i.e fixes #566)

Erasing tech-debt introduced in last commit, with better `EnhancedParameters` protocol, we can again decouple generic message handling from command nuances completely.

### Testing notes (optional):
Only superficial regression testing is necessary, eq sending `/send` and `/request` commands and confirming that it looks good (amount and currency is displayed) on the receiver side.

status: ready

### CODE REVIEW

**Review by dmitryn — APPROVED** [review]

**Review by dmitryn — APPROVED** [review]

**Review by rasom — APPROVED** [review]

**Review by yenda — APPROVED** [review]

**Comment by lukaszfryc** [comment]
@janherich I noticed few issues:
1. "~ USD" is shown for outgoing transaction requests. For incoming tx requests, the average fiat value is shown correctly
2. There is no fiat value for outgoing transactions that were send. Again, it works fine on receiver side (when "/send" tx is received).

**Comment by janherich** [comment]
@lukaszfryc Already fixed, new build should be ready soon

**Comment by lukaszfryc** [comment]
@janherich now "~ 0 USD" is shown for all outgoing transactions. Works fine for incoming txs:

**Comment by janherich** [comment]
@lukaszfryc Should be already fixed.

**Comment by lukaszfryc** [comment]
@janherich all works fine when "." is used as delimeter. But, if I use comma ",", the fiat value is 0:

**Comment by janherich** [comment]
@lukaszfryc fixed in the newest build (soon to be ready)

**Comment by lukaszfryc** [comment]
@janherich now all works fine 👍

**Pull request merged**
