### PR TITLE
Rerun appium tests failed due to infrastructure reasons

### PR DESCRIPTION
**Pull request by lukaszfryc**
### Summary:

Automatically rerun failed appium tests: 

- rerun `--rerun_count` times. By default 0
- rerun only because of errors defined in `RERUN_ERRORS`
- each test can have multiple runs
- use latest testrun in the test report 

I tested it on sauce labs. 

- [x] run PR tests when http://artifacts.status.im:8081/artifactory/ is working again

status: ready

### CODE REVIEW

**Comment by lukaszfryc** [comment]
http://artifacts.status.im:8081/artifactory/ is currently down. Please run the PR tests against this Pr when the artifactory is up again.

**Comment by antdanchenko** [comment]
@lukaszfryc overall looks great, however approach with rerunning tests will use a lot of additional sessions on SauceLabs. And in case of rerunning failed tests we will wait for all tests to be executed (~10 minutes) and only then we will start new tests (additional ~10 minutes for them to be executed)

Please note that we have 10+ tests which are using more than 1 session and in nearest future we are going to add even more (in scope of extended automated tests)
And in most cases only one session from all session will catch one of those errors
The ideal solution is to rerun the session instead of of rerunning failed tests

**Comment by jeluard** [comment]
@lukaszfryc Any news about that PR?

**Comment by lukaszfryc** [comment]
I'll try to finish it today

**Comment by lukaszfryc** [comment]
@antdanchenko I bumped `pytest-xdist` which fixes issue with `report.longrepr`. Could you update the e2e jenkins job to use this lib?

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/null for branch PR-4048

<blockquote><div><strong><a href="https://i.diawi.com/null">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/MZ6sL7 for branch PR-4048

<blockquote><div><strong><a href="https://i.diawi.com/MZ6sL7">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/XtryJv for branch PR-4048

<blockquote><div><strong><a href="https://i.diawi.com/XtryJv">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/HF9zba for branch PR-4048

<blockquote><div><strong><a href="https://i.diawi.com/HF9zba">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Review by antdanchenko — APPROVED** [review]

**Review by yevh-berdnyk — APPROVED** [review]

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/T5uYST for branch PR-4048

<blockquote><div><strong><a href="https://i.diawi.com/T5uYST">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/HzBfiX for branch PR-4048

<blockquote><div><strong><a href="https://i.diawi.com/HzBfiX">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Pull request merged**
