### PR TITLE
Show loading until all messages are processed

### PR DESCRIPTION
**Pull request by cammellos**
This build fixes an issue with receiving messages.

Before we would stop showing loading and mark a request as completed as soon as the messages made it to our device, but not necessarily processed.
This caused 2 issues:
1) If the device would be killed while it was processing messages, all those messages would be lost.
2) The "loading..." indicator was not accurate, it would stop showing even though messages were not in the chat.

### Testing

It's hard to replicate in real scenario, so I prepared a couple of builds that intentionally slow down the processing of messages.

One is faulty (old behavior), while the other one includes the fix.

Test faulty behavior:

1) Install build `#4` (https://status-im-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-211126-101731-c1102f-pr12834-universal.apk).
2) Join a chat with a known amount of messages (at least 30)
3) Wait 3,4 seconds
4) Kill the app
5) Re-open the app
6) Look at the chat and wait 60 seconds

Expected:
messages are retrieved
Actual:
messages are not retrieved

Also notice that on 3, the "loading..." spinner is gone in the chat, while messages are not there.

To test the fixed behavior, follow the same steps, but use build 5.
The chat should still show "loading..." in step 3, and on reopening the app. 
Messages should be eventually retrieved in step 6.

### CODE REVIEW

**Review by Parveshdhull — APPROVED** [review]

**Comment by churik** [comment]
@cammellos thank you for the instructions for testing, appreciate it!


Public chat (51 messages for last 24h, #chu, 29.11.21) | Build 4 | Build 5  (https://github.com/status-im/status-react/commit/4d7d17e371ee87bb3215beec5df33020c102984c) | Build 7 (https://github.com/status-im/status-react/commit/f5fabafe1cb17c24b8d00f7bcdd450cf6d2980e2) 
-- | -- | -- | --
Waiting 4 sec | nothing is shown | loading | loading
Reopening, wait 60-120 sec more | nothing was fetched | all messages fetched | loading - [logs.zip](https://github.com/status-im/status-react/files/7619147/Status-debug-logs.zip)
Waiting until messages will be loaded | ~120 sec | ~ 130 sec | nothing fetched in 300sec - [logs.zip](https://github.com/status-im/status-react/files/7619179/Status-debug-logs.zip)


Is everything expected here?

**Comment by churik** [comment]
@cammellos 
checked builds 4/5, results in table, everything works as mentioned in description)

PUBLIC CHAT(51 messages for last 24h) | Build 4 | Build 5
-- | -- | --
Waiting 4 sec | nothing was shown | Loading...
Reopening, wait 60-120 sec more | nothing was fetched | all messages fetched
Waiting until messages will be loaded | ~120s | ~ 130s
**GROUP CHAT( 30 messages for last 24h)** |   |  
Waiting 4 sec | nothing is shown | several messages fetched (no loading indicator)
Reopening, wait 60-120 sec more | all were fetched in ~90s | all were fetched in ~120s
**1-1 CHAT(30 messages for last 24h)** |   |  
Waiting 4 sec | nothing is shown | several messages fetched (no loading indicator)
Reopening, wait 60-120 sec more | all were fetched in ~180s | all were fetched in ~100s
**COMMUNITY CHAT(30 messages for last 24h)** |   |  
Waiting 4 sec | nothing was shown | Loading...
Reopening, wait 60-120 sec more | nothing were fetched | all were fetched in ~120s
Waiting until messages will be loaded | ~35 sec | ~300s

**ISSUE 1:** On build 9 (https://github.com/status-im/status-react/commit/90f6538c81fb8ede709e472897949d811da424ea) endless "loading..." is shown when all history was fetched (instead of "Fetch more")

**Steps:**
- join any empty public chat (or chat with history and scroll to the beginning of the history)
IMAGE 2021-11-30 13:33:16
Logs: [Status-debug-logs.zip](https://github.com/status-im/status-react/files/7625713/Status-debug-logs.zip)

**Comment by cammellos** [comment]
@churik it should be fixed now, sorry I have messed up the rebase

**Comment by churik** [comment]
e2e failures are not related to PR.
Tested different length of history, mobile data, types of messages.

**Devices:**
- IPhone 12 Mini (IOS 14)
- IPhone 7 (IOS 13)
- Xiaomi Mi Note 9 Pro (Android 10)

**Pull request merged**
