### PR TITLE
Close chat when closing group chat details

### LINKED ISSUE #17391: Messages are marked as read automatically in group chats after opening Group details
# Bug Report

### Reproduction

1. Create/join a group chat
2. Open the home screen
3. Long-press on the group > Group details
4. Go back to the home screen
5. Receive a message in the group

https://github.com/status-im/status-mobile/assets/67952253/a487941e-6c4e-4ad8-b95f-9b4988e439ff

#### Expected result:
Can see unread dots/counters on receiving new messages

#### Actual result:
Dots and counters appear for a second on the group chat

### Additional Information

- Status version: nightly 22/09
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by ibrkhalil**
fixes #17391 

### Summary

Clears chat's state that it's active when closing group chat details

status: ready

### CODE REVIEW

**Review by J-Son89 — APPROVED** [review]

**Review by Parveshdhull — APPROVED** [review]

**Comment by pavloburykh** [comment]
@ibrkhalil thank you for the fix. Still reproducing the issue if Group details are closed by system back button (Android) or back-swipe (IOS). 


### ISSEUE 1 Messages are marked as read automatically in group chats after closing Group details by system back button (Android) or back-swipe (IOS). 

**Steps:** 

1. Create/join a group chat
2. Open the home screen
3. Long-press on the group > Group details
4. Close Group details by system back button (Android) or back-swipe (IOS)
5. Receive a message in the group
6. See if messages are not read automatically

**Actual result:** messages are read automatically. 

**Android:**

https://github.com/status-im/status-mobile/assets/97245802/d61fd2d7-d968-4100-9d66-8b443892c6f5


**IOS:**


https://github.com/status-im/status-mobile/assets/97245802/f2080db3-2f30-4952-97a1-b754b8c28510

**Comment by ibrkhalil** [comment]
> @ibrkhalil thank you for the fix. Still reproducing the issue if Group details are closed by system back button (Android) or back-swipe (IOS).
> 
> ### ISSEUE 1 Messages are marked as read automatically in group chats after closing Group details by system back button (Android) or back-swipe (IOS).
> **Steps:**
> 
> 1. Create/join a group chat
> 2. Open the home screen
> 3. Long-press on the group > Group details
> 4. Close Group details by system back button (Android) or back-swipe (IOS)
> 5. Receive a message in the group
> 6. See if messages are not read automatically
> 
> **Actual result:** messages are read automatically.
> 
> **Android:**
> 
>  telegram-cloud-document-2-5463003185658478371.mp4 
> **IOS:**
> 
>  telegram-cloud-document-2-5463003185658478372.mp4

Should be fixed now.

**Comment by pavloburykh** [comment]
@ibrkhalil thank you, issue 1 is fixed. Please take a look at issue 2

### ISSUE 2 Group details screen gets broken after interacting with Mute group button

**Steps:**

1. Open Group details
2. Tap Mute/Unmute group button
3. Observe the result

**Actual result:** screen is broken. Element (group name, members list) disappear, buttons turn white. 

https://github.com/status-im/status-mobile/assets/97245802/b76f5489-69a8-484b-baef-c0f76252e8c9


@ibrkhalil could you please clarify if anything has been refactored on Group details screen aside from fixing initial issue? Need this info in order to know what should be re-tested for regression cause this one was kinda unexpected for me.

**Comment by ibrkhalil** [comment]
> @ibrkhalil thank you, issue 1 is fixed. Please take a look at issue 2
> 
> ### ISSUE 2 Group details screen gets broken after interacting with Mute group button
> **Steps:**
> 
> 1. Open Group details
> 2. Tap Mute/Unmute group button
> 3. Observe the result
> 
> **Actual result:** screen is broken. Element (group name, members list) disappear, buttons turn white.
> 
>  telegram-cloud-document-2-5465307680425921526.mp4 
> @ibrkhalil could you please clarify if anything has been refactored on Group details screen aside from fixing initial issue? Need this info in order to know what should be re-tested for regression cause this one was kinda unexpected for me.

Sorry Pavlo for this, I missed something while refactoring the existing code to use React hooks.
Should be working now.

**Comment by pavloburykh** [comment]
> Sorry Pavlo for this, I missed something while refactoring the existing code to use React hooks.
> Should be working now.

No worries @ibrkhalil! Thank you for the fix. Let's wait until e2e run results and after that hopefully we will be ready for merge. I will keep you updated.

**Comment by pavloburykh** [comment]
@ibrkhalil thank you! PR is ready for merge now.

**Pull request merged**
