### PR TITLE
Show parsed bridge messages

### LINKED ISSUE #19976: Links bridged from Discord to Status community are displayed as plain text
**Steps:** 

1. Join Status community on mobile
2. Send message containing link using Discord app
3. See how link looks like in Status app

**Actual result:** link is displayed as plain text and not tappable 

photo_2024-05-10 17 10 01

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

### LINKED ISSUE #19977: Messages bridged from Discord to Status community are not tappable
**Steps:** 

1. Join Status community on mobile
2. Send message using Discord app
3. Long tap bridged message in Status app
4. See if message is tappable

**Actual result:** message is not tappable, bottom sheet does not appear. 

https://github.com/status-im/status-mobile/assets/97245802/20f9e9f5-63f8-4846-bc2b-6d4f8a65cb11

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by Parveshdhull**
fixes https://github.com/status-im/status-mobile/issues/19977
fixes https://github.com/status-im/status-mobile/issues/19976

status-go PR: https://github.com/status-im/status-go/pull/5192

### Testing Note:

Only newly fetched messages will be parsed.

status: ready

### CODE REVIEW

**Review by flexsurfer — COMMENTED** [review]
hey @Parveshdhull thank you for the PR, could we please keep it as a separate component and do not mix with our message components

**Comment by Parveshdhull** [comment]
hi @flexsurfer thank you for reviewing PR.

> hey @Parveshdhull thank you for the PR, could we please keep it as a separate component and do not mix with our message components

Having separate components do looks neater, but it lacks functionality. We are already duplicating author/message container styles for bridge message, if we are to support [press/long-press](https://github.com/status-im/status-mobile/blob/34cf65bfc999a21f5d0cb86c9c6cc931b0ec44df/src/status_im/contexts/chat/messenger/messages/content/view.cljs#L176) etc. we have to duplicate this to and more.
https://github.com/status-im/status-mobile/blob/34cf65bfc999a21f5d0cb86c9c6cc931b0ec44df/src/status_im/contexts/chat/messenger/messages/content/view.cljs#L176

Please can you elaborate what will the benefit of having it as separate and what are drawbacks of current approach.

**Comment by flexsurfer** [comment]
> hi @flexsurfer thank you for reviewing PR.
> 
> > hey @Parveshdhull thank you for the PR, could we please keep it as a separate component and do not mix with our message components
> 
> Having separate components do looks neater, but it lacks functionality. We are already duplicating author/message container styles for bridge message, if we are to support [press/long-press](https://github.com/status-im/status-mobile/blob/34cf65bfc999a21f5d0cb86c9c6cc931b0ec44df/src/status_im/contexts/chat/messenger/messages/content/view.cljs#L176) etc. we have to duplicate this to and more.
> 
> https://github.com/status-im/status-mobile/blob/34cf65bfc999a21f5d0cb86c9c6cc931b0ec44df/src/status_im/contexts/chat/messenger/messages/content/view.cljs#L176
> 
> Please can you elaborate what will the benefit of having it as separate and what are drawbacks of current approach.

thank you @Parveshdhull , it should be separate, it's not duplicating, it's just the same implementation, but it's fine that it's still separate, because it's not a regular status message, and it shouldn't behave like status message, so we should keep separate implementation for it, there should be no interactions (like press/long press) etc , adding conditions like `(when-not bridge-name added?)` to our components not good as well

**Comment by Parveshdhull** [comment]
> there should be no interactions (like press/long press) etc

@pavloburykh Please can you confirm? Because according to issue https://github.com/status-im/status-mobile/issues/19977,

> 3. Long tap bridged message in Status app

> Actual result: message is not tappable, bottom sheet does not appear.

PS: I can revert these changes in PR and only address parsing of bridge message if that's what we want. But If we want to support reactions etc. on bridged message then I think they are working in PR.

**Comment by flexsurfer** [comment]
> Please can you confirm?

can't confirm sorry :)

**Comment by pavloburykh** [comment]
Hey @Parveshdhull! Thank you for this PR. 

> @pavloburykh Please can you confirm?

That's a good point. Let me compare the behaviour on Desktop and I will come back with an answer after that.

**Comment by pavloburykh** [comment]
> > there should be no interactions (like press/long press) etc
> 
> @pavloburykh Please can you confirm? Because according to issue #19977,
> 
> > 3. Long tap bridged message in Status app
> 
> > Actual result: message is not tappable, bottom sheet does not appear.
> 
> PS: I can revert these changes in PR and only address parsing of bridge message if that's what we want. But If we want to support reactions etc. on bridged message then I think they are working in PR.

So, I have compared with Desktop app and here what I see. 


On **Desktop** user can perform following interactions with Bridged for Discord messages:

1. Set a reaction
2. Send reply
3. Pin
4. Mark as unread (I believe we do not have such feature on mobile, so this is Desktop only)

Status Desktop 2024-05-22 13-51-29

On **mobile** in PR build longtap menu options are slightly different:

1. Set a reaction
2. Send reply
3. Copy text
4. Delete for me
5. Delete for everyone

photo_2024-05-22 14 09 08



### Summary:

Based on the above comparison I believe we should show the following options for bridged messages on mobile:

1. Set a reaction
2. Send reply
3. Copy text (Desktop does not show it but I think it is okay to leave this option on mobile)
4. Pin message (if available)
5. Delete for me

We should not show: 

Delete for everyone
Mark as unread - as we do not have such feature on mobile, we can ignore it.

**Comment by Parveshdhull** [comment]
thank you very much @pavloburykh for checking. Will update the PR as per summary

**Comment by pavloburykh** [comment]
> thank you very much @pavloburykh for checking. Will update the PR as per summary

thank you! I have updated summary and added 'Delete for me` based on our conversation in Discord.

**Comment by Parveshdhull** [comment]
> it's not a regular status message, and it shouldn't behave like status message

@flexsurfer, as we have confirmed that bridge messages should behave somewhat like regular messages, please can we go ahead with PR?
We can further explore more about simplification of these components later.

**Comment by flexsurfer** [comment]
> > it's not a regular status message, and it shouldn't behave like status message
> 
> @flexsurfer, as we have confirmed that bridge messages should behave somewhat like regular messages, please can we go ahead with PR? We can further explore more about simplification of these components later.

this should be done on status-go side then, I don't really like that we need to add bridge conditions everywhere

**Review by flexsurfer — APPROVED** [review]

**Comment by pavloburykh** [comment]
Hey @Parveshdhull! Is this one ready for re-test?

**Comment by Parveshdhull** [comment]
> Hey @Parveshdhull! Is this one ready for re-test?

hi @pavloburykh, yes PR is ready for re-testing.

**Comment by pavloburykh** [comment]
@Parveshdhull thanx for your fixes!

Regarding Delete for you / Delete for everyone: I think we need to remove these options for Bridged messages as currently it is impossible to delete such messages using Status app. On video below you can see deleted Bridged messages being restored after chat reopening. The easiest way is not to show these options for Bridged messages, so let's do it. 


https://github.com/status-im/status-mobile/assets/97245802/536c6b62-19d6-4c8a-8a5d-f264e50f5a2f

**Comment by Parveshdhull** [comment]
> The easiest way is not to show these options for Bridged messages, so let's do it.

Yes, sounds good. Removed

**Comment by churik** [comment]
@Parveshdhull just in case - can we rebase your PR to include hide browser feature? 
Thank you!

**Comment by churik** [comment]
### PR_ISSUE 3: Incorrectly shown system CR message

**Steps:**
1) restore or create multiaccount 
2) add someone to Contacts


**Expected result:**
IMAGE 2024-05-24 15:19:52

**Actual result:**
IMAGE 2024-05-24 15:20:13


**OS:** IOS, Android

**Comment by churik** [comment]
no more issues from my side :) 

Let me know when it is ready! Thanks

**Comment by Parveshdhull** [comment]
Thank you @churik for finding this bug, should be fixed now.

**Comment by churik** [comment]
No more issues from my side, thank you for your amazing work!!!
I'll wait for the final e2e results and send PR to merge.

**Comment by pavloburykh** [comment]
> No more issues from my side, thank you for your amazing work!!! I'll wait for the final e2e results and send PR to merge.

@churik @Parveshdhull, E2E failures seem to be not related to the PR. So it is ready for merge.

**Comment by Parveshdhull** [comment]
Hi @pavloburykh, @churik, Thank you very much for testing the PR.

I just realized that I forgot to add the status-go label to the PR. It's a very small 2-line [change](https://github.com/status-im/status-go/pull/5192/files), but as soon as I will rebase it will pull more changes.

So as we are close to the release branch cutting,
- should I rebase with develop and use the tag from that
- or cherry-pick commit to status-go 0.179.x [branch](https://github.com/status-im/status-go/commits/release/0.179.x) and update status-mobile with that.
 
cc @cammellos

**Comment by Parveshdhull** [comment]
Will update status-mobile develop with status-go develop tag, but will also cherry-pick status-go commit to status-go release branch.
So even if develop will pull new changes, release branch will only include this commit not other rebased commits.

Discussed with Andrea. @pavloburykh, @churik please let me know if this sounds ok?

**Comment by pavloburykh** [comment]
Hey @Parveshdhull! We will need to re-run e2e tests after go branch is rebased in this PR in order to make sure develop go commits will not brake mobile develop after bumping go version.

**Comment by Parveshdhull** [comment]
@pavloburykh Please can you check e2e test results.

**Review by jo-mut — APPROVED** [review]

**Comment by pavloburykh** [comment]
> test_wallet_send_asset_from_drawer

Thank you @Parveshdhull! E2E failures are not PR related. Ready for merge!

**Pull request merged**
