### PR TITLE
move blob to rn, remove unused code, move images events to status-im2

### PR DESCRIPTION
**Pull request by flexsurfer**
move blob to rn, remove unused code, move images events to status-im2

### CODE REVIEW

**Review by Parveshdhull — APPROVED** [review]

**Comment by flexsurfer** [comment]
57% hm, @status-im/mobile-qa need you confirm then

**Comment by flexsurfer** [comment]
hm test cases looks related to the code i touched :(

**Comment by VolodLytvynenko** [comment]
hi @flexsurfer. One issue found by the e2e tests. The other failures seem to be due to an appium connection issue. I've re-run them and am awaiting the results

## ISSUE 1: "Share" button unresponsive when opening and attempting to Share an Image
### Steps:
1. Send the image in the chat
2. Open current image
3. Tap "share" button

### Actual result:
The 'share' button fails to trigger any response or display the sharing drawer

https://github.com/status-im/status-mobile/assets/52490791/e2c66e8a-0a19-40d4-92cd-9f0f404514ea


### Expected result:
The 'sharing' drawer should be shown when share button is tapped
image

**Review by OmarBasem — APPROVED** [review]

**Review by siddarthkay — APPROVED** [review]
nice cleanup 💯

**Comment by VolodLytvynenko** [comment]
## ISSUE 2: "Unhandled content type 10" message is shown at the beginning of the opened community channel
### Steps:
1. Create any community
2. Open any channel

### Actual result:
At the beginning of the channel, the  'unhandled content-type 10' message is shown
image

### Expected result:
The "Unhandled content type" Message is not shown

**Comment by VolodLytvynenko** [comment]
@flexsurfer all other e2e fails are not PR-related

**Comment by flexsurfer** [comment]
thanks @VolodLytvynenko fixed

**Comment by flexsurfer** [comment]
much better

**Comment by VolodLytvynenko** [comment]
> much better

@flexsurfer thank you for the fixes. The failed test is not PR-related

**Pull request merged**
