### PR TITLE
PR to add `Kotlin` support and to Kotlinifiy `MainApplication.java`, `MainActivity.java`

### PR DESCRIPTION
**Pull request by siddarthkay**
### Summary

This PR is a pre-requisite to upgrading `react-native` to `0.73.x`, now that react-native has completely moved their android code over from `Java` to `Kotlin` , it is also necessary for us to begin doing the same.

This PR converts just 2 files which are important at the moment.
- `android/app/src/main/java/im/status/ethereum/MainActivity.java`
- `android/app/src/main/java/im/status/ethereum/MainApplication.java`

I will can convert the remaining files in follow ups.

#### Platforms
- Android

#### Areas that maybe impacted
- Push Notifications
- Permissions
- Splash Screen

status: ready

### CODE REVIEW

**Review by mohsen-ghafouri — APPROVED** [review]
Finally kotlin 🚀💪

**Review by ibrkhalil — APPROVED** [review]

**Review by yakimant — APPROVED** [review]
Looks good! And Kotlin is great!

Just to confirm, you don't need to install Kotlin as a Nix package, but Gradle dependency is enough?

**Comment by siddarthkay** [comment]
@yakimant : Thank you and yes gradle dep was enough to compile kotlin

**Review by smohamedjavid — APPROVED** [review]

**Comment by siddarthkay** [comment]
Hi @status-im/mobile-qa : This PR refactors 2 files from Java to Kotlin and in theory the new code should perform exactly the same. However there may or may not be minute side effects on Android, could you please do a smoke test ?

**Review by OmarBasem — APPROVED** [review]

**Comment by churik** [comment]
Smoke checked:

- Push Notifications
- Permissions
- Splash Screen

on Android10 and Android13, can't see any differences in nightly.

**Comment by briansztamfater** [comment]
A bit late to the party, but nice to see some migration to Kotlin! ❤️

**Pull request merged**
