### PR TITLE
[#13672] Sync contact request decision

### LINKED ISSUE #13672: Synchronize accepting/dismissing contact requests
As a user with a paired device
When I accept a contact request on one device I want it to be accepted on the other device as well
So that my state is sync and I don't have to perform the same action twice

1) Create device A1 & A2 (same seed phrase on both devices), pair them (ask qa for assistance if needed)
2) Create device B1 (different chat key)
3) Enable mutual contact requests on all devices
4) Send a contact request from B to A 
5) Accept/Dismiss the contact request on A1

A2 should also show the contact request as dismissed or accepted.

Most of the work is to be done in status-go

### PR DESCRIPTION
**Pull request by rasom**
fix #13672

status: ready

### CODE REVIEW

**Review by flexsurfer — APPROVED** [review]

**Comment by pavloburykh** [comment]
Waiting for review of go PR **https://github.com/status-im/status-go/pull/2789**

**Comment by rasom** [comment]
@pavloburykh it was approved on status-go side, should be ready fro testing

**Comment by pavloburykh** [comment]
@rasom is it possible with a help of attached logs to figure out what's going on in issue below? I am not sure if this issue is PR related. 

### ISSUE 1 Contact is being added/deleted by itself (without user's action) on paired Devices

Unfortunately I haven't found exact steps how to generate such account with this bug

On Video below you can see the following:

1. Two paired devices - Android and IOS 
2. On the first seconds of the video you can see that 1 contact appears without any user's actions
3. Then I delete contact form Device 1 (it is deleted on paired Device 2)
4. I generate another contact request from deleted contact
5. Accept contact request on Device 1 (Android)

**Actual result:** after contact request acceptence - user is added to contacts on Device 2 (IOS) but is deleted from contacts on paired Device 2 (Android). 


https://user-images.githubusercontent.com/97245802/185388288-ae918469-bd82-4c87-88ed-0225c91138e7.mp4

[Android_logs.zip](https://github.com/status-im/status-mobile/files/9373573/Android_logs.zip)

[IOS_logs.zip](https://github.com/status-im/status-mobile/files/9373564/IOS_logs.zip)

**Comment by rasom** [comment]
@pavloburykh 
> On the first seconds of the video you can see that 1 contact appears without any user's actions

how do I reproduce this?

**Comment by rasom** [comment]
@qoqobolo 
issue 1 should be fixed now

**Comment by qoqobolo** [comment]
@rasom 
### ISSUE 2 (it may be the same as issue 1 though): Contact is not deleted from the synced secondary device if delete it from the primary device while the secondary device is offline

**Steps:**
1. Sync device1 and device2
2. Send a contact request from device3
3. Approve the request on device1 (device3 is added as a contact on device1 and device2)
4. Close Status on device2
5. Remove contact from device1
6. Open Status on device2, check contacts 

**Expected result:** no contacts on device2
**Actual result:** device3 is still in contacts on device2

The issue is not reproducible on develop, removed contacts are synced fine there.

[device1 geth.log](https://github.com/status-im/status-mobile/files/9381792/geth.log)
[device2 geth.log](https://github.com/status-im/status-mobile/files/9381794/geth.log)

**Comment by qoqobolo** [comment]
@rasom can you also rebase this PR, please? Go version was bumped to 0.105.1

**Comment by rasom** [comment]
@qoqobolo PR is rebased

**Comment by rasom** [comment]
@qoqobolo both issue should be fixed already

**Comment by qoqobolo** [comment]
Thanks @rasom!
Something's wrong with Jenkins, I cannot rebuild the builds to retest it. Jakub is already on it, and apparently we need to wait until Jenkins comes to life.

**Comment by rasom** [comment]
@qoqobolo my fault, this also should be fixed already

**Comment by qoqobolo** [comment]
@rasom thanx for the fixes!
E2e failures are not related to PR, it can be merged (after approval from desktop on the go side, I've pinged them).

**Pull request merged**
