### PR TITLE
[#6415] mark button as inactive when no internet or mailserver connec…

### LINKED ISSUE #6415: Messages sent when "Connecting to peers" is displayed will be lost
### Description

*Type*: Bug
*Summary*: "Connecting to peers" error doesn't lead to disappearing "Send" button, so you can type and send message but in fact it will not be sent. The same for desktop - you can send message, it will be shown in "Sent" state, but in fact will be never received.

#### Expected behavior
**Mobile**
button is hidden on mobile. If for some reason user sent a message before the send button was hidden, there should be a spinner when the message is trying to be sent. It it's not sent after a timeout, the "Not sent. Tap for options" status with resend option. Refer to https://github.com/status-im/status-react/pull/3964 if you need details of how resend should work.

offl 

**Desktop**
"Not sent" status on desktop (like for Offline mode).

#### Actual behavior
message status is Sent, but in fact messages are lost
genymotion for personal use - samsung galaxy s7 - 7 1 0 - api 25 - 1440x2560 1440x2560 640dpi - 192 168 58 101 2018-10-19 16-10-30

### Reproduction

- Open Status
- Trigger "Connecting to peers" (for exapmle like in issue https://github.com/status-im/status-react/issues/6396 or https://github.com/status-im/status-react/issues/6414)
- Send message

### Additional Information

* Status version: nightly 19/10/2018
* Operating System: Android, iOS, Mac OSx

#### Logs

* StatusIm.log (desktop): [StatusIm_time.log](https://github.com/status-im/status-react/files/2495860/StatusIm_time.log)
* Geth.log  (desktop): [geth_time.log](https://github.com/status-im/status-react/files/2495854/geth_time.log)

Consequence of  https://github.com/status-im/status-react/issues/6414 or https://github.com/status-im/status-react/issues/6396, but I believe should be fixed separately and has higher priority IMO.

### PR DESCRIPTION
**Pull request by dmitryn**
fixes #6415

### Summary:

Disable chat send button when no internet or mailserver connection.

status: ready

### CODE REVIEW

**Review by janherich — APPROVED** [review]

**Review by goranjovic — APPROVED** [review]

**Comment by churik** [comment]
@dmitryn 
Build is failed due to incorrect formatting. Can you please resolve this?
Build: is [here](https://ci.status.im/job/status-react/job/pull%20requests/view/change-requests/job/PR-6467/)
Log:
```
Updating hook:  pre-commit
src/status_im/ui/screens/desktop/main/chat/views.cljs has incorrect formatting
--- a/src/status_im/ui/screens/desktop/main/chat/views.cljs
+++ b/src/status_im/ui/screens/desktop/main/chat/views.cljs
[036m@@ -320,9 +320,9 @@[0m
                           :submit-shortcut        {:key "Enter"}
                           :on-submit-editing      #(when (and (= :online network-status)
                                                               mailserver-connected?)
[031m-                                                         (.clear @inp-ref)[0m
[031m-                                                         (.focus @inp-ref)[0m
[031m-                                                         (re-frame/dispatch [:chat.ui/send-current-message]))[0m
[032m+                                                     (.clear @inp-ref)[0m
[032m+                                                     (.focus @inp-ref)[0m
[032m+                                                     (re-frame/dispatch [:chat.ui/send-current-message]))[0m
                           :on-change              (fn [e]
                                                     (let [native-event (.-nativeEvent e)
                                                           text         (.-text native-event)]
1 file(s) formatted incorrectly
```

**Comment by dmitryn** [comment]
@churik thanks, i missed it somehow. New build is ready, please take a look.

**Comment by churik** [comment]
@dmitryn 
Can you please change styling for disabling button (desktop)?
When you start typing, grey button becomes white and it is clickable.
Video: http://take.ms/Sx6ly
Thanks!


<blockquote><div>Monosnap screenshot tool</div><div><strong><a href="https://monosnap.com/file/9IHWyOk4RCwvF405hSVSS9tYHv238H">File "screencast 2018-10-31 11-49-52.mp4"</a></strong></div><div>Monosnap — the best tool to take & share your screenshots.</div></blockquote>

**Comment by churik** [comment]
Well, it is not critical, but nice to fix, so let me know if you want to have it like separate issue

**Comment by dmitryn** [comment]
@churik i can fix it here

**Comment by dmitryn** [comment]
@churik styling has been fixed. Please take a look.

**Pull request merged**
