### PR TITLE
feat: add blur effect on scroll for buttons inside gallery view

### LINKED ISSUE #16127: Add blur effect on scroll for buttons inside gallery view
Implement blur effect on scroll for buttons inside gallery view as per design below

https://www.figma.com/file/wA8Epdki2OWa8Vr067PCNQ/Composer-for-Mobile?type=design&node-id=6376-372379&t=LgBrTeQVDEFhr9J9-0

Composer for Mobile – Figma 2023-06-01 11-51-31

### PR DESCRIPTION
**Pull request by briansztamfater**
fixes #16127 

### Summary

This PR adds blur effect on gallery view buttons and dropdown, and some UI adjustments to comply with Figma designs

###### Light
https://github.com/status-im/status-mobile/assets/18485527/69995208-aaa6-4f20-b378-e42bb1f9f82d

###### Dark
https://github.com/status-im/status-mobile/assets/18485527/bc2d0185-0bea-4919-9c16-d9caa98b20db

###### Light
https://github.com/status-im/status-mobile/assets/18485527/03f38569-48de-4a2b-8ffd-16f69fd80cbf

###### Dark
https://github.com/status-im/status-mobile/assets/18485527/9e7e6304-42f8-4936-8fff-726a5aa4507d

#### Platforms

- Android
- iOS

### Steps to test

- Open Status
- Open a chat
- Tap on send image button on composer
- Scroll through images and verify the blur inside buttons / dropdown

status: ready

### CODE REVIEW

**Review by yqrashawn — APPROVED** [review]
LGTM!

**Review by ajayesivan — APPROVED** [review]

**Comment by VolodLytvynenko** [comment]
Hi @briansztamfater thank you for PR. One low priority issue is found:

## ISSUE 1: Album selection button is not visible in the list of albums
### Steps:
1. Open album gallery -> tap 'recent'
2. Check color of button in the upper part

### Actual result:
image
image

### Expected result:
image
https://www.figma.com/file/wA8Epdki2OWa8Vr067PCNQ/Composer-for-Mobile?type=design&node-id=6376-372320&t=uXQVORtKcspvBGC8-0

**Comment by briansztamfater** [comment]
Hi @VladimrLitvinenko thank you for testing! I'll fix this issue and let you know when is ready to test

**Comment by briansztamfater** [comment]
@VladimrLitvinenko issue should be fixed now. Let me know if there's anything else that should be addressed :)

**Review by vkjr — APPROVED** [review]

**Review by alwx — APPROVED** [review]

**Comment by VolodLytvynenko** [comment]
Hi @briansztamfater thank your for PR. No issues from my side. PR ready to be merged

**Comment by briansztamfater** [comment]
> Hi @briansztamfater thank your for PR. No issues from my side. PR ready to be merged

Graat to hear @VladimrLitvinenko! Unfortunately I had to solve conflicts and would want to make sure I didn't break anything during the rebase process, could you please make a quick additional testing before I merge? Thanks a lot!

**Comment by VolodLytvynenko** [comment]
> > Hi @briansztamfater thank your for PR. No issues from my side. PR ready to be merged
> 
> Graat to hear @VladimrLitvinenko! Unfortunately I had to solve conflicts and would want to make sure I didn't break anything during the rebase process, could you please make a quick additional testing before I merge? Thanks a lot!

@briansztamfater Thank you for resolving the conflicts and returning the PR. I have rechecked it and found no new issues. PR is ready to be merged

**Pull request merged**
