### PR TITLE
[#13173] move stickers business logic to status-go 

### LINKED ISSUE #12770: Stickers in the Sticker Market and chat views are not loaded sometimes
# Bug Report

## Problem 
Sometimes stickers are partially downloaded and displayed in the Sticker Market, and sometimes cannot open the Sticker Market itself at all (an endless spinner is shown).

#### Actual behavior

https://user-images.githubusercontent.com/67952253/139454405-dd042c44-b7c6-4853-95a6-5a5039f2b672.mp4

https://user-images.githubusercontent.com/67952253/139454412-cad13294-3d09-4abf-8ef8-6a8edf71c25a.mp4

### Reproduction

1. Open Status
2. Join a public chat
3. Tap the Stickers icon to open the Sticker Market
4. Open several sticker packs

### Additional Information

- Status version: nightly 29/10
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### LINKED ISSUE #13173: move stickers business logic to status-go
move stickers business logic to status-go
status-go: https://github.com/status-im/status-go/pull/2518
desktop: https://github.com/status-im/status-desktop/pull/4808/files

### PR DESCRIPTION
**Pull request by flexsurfer**
fixes: #13173
fixes: #12770

### CODE REVIEW

**Review by rasom — APPROVED** [review]

**Comment by qoqobolo** [comment]
### ISSUE 1: App crashes when switching to Mainnet or logging out on Android and iOS
@flexsurfer take a look please

**Comment by flexsurfer** [comment]
thanks @qoqobolo fixed

**Comment by pavloburykh** [comment]
Hi @flexsurfer. Could you please resolve conflicts in order I be able to build IOS build? Currently it's failing https://ci.status.im/job/status-react/job/prs/job/ios/job/PR-13247/9/console
Thanx!

**Comment by jakubgs** [comment]
This branch needs rebasing, it still references Jenkins label `nix-2.3` which no longer exists, so the builds can't run.

**Comment by flexsurfer** [comment]
@pavloburykh done

**Comment by pavloburykh** [comment]
@flexsurfer thanx, PR is ready for merge. Please, mind my commit when squashing before merge.

**Comment by flexsurfer** [comment]
hey @pavloburykh thanks, i was looking for tested-ok label usually QA add it when ready for merge :)

**Comment by pavloburykh** [comment]
> hey @pavloburykh thanks, i was looking for tested-ok label usually QA add it when ready for merge :)

my bad, forgot to add a label. Sorry.

**Pull request closed without merging**
