### PR TITLE
update for testing local pairing

### PR DESCRIPTION
**Pull request by qfrank**
### Summary

This PR is used for testing purpose that testing the feature local pairing since currently `status-go-version` status-mobile used on branch `develop` doesn't contains the corresponding feature [Sync all devices after initial pairing](https://github.com/status-im/status-mobile/issues/14447).

[Relate PR](https://github.com/status-im/status-mobile/pull/14514) for status-mobile. 
[Relate PR](https://github.com/status-im/status-go/pull/3047) for status-go.

To make sure local pairing works as expected, we should request a manual QA. 

### Testing notes
- it should worked on two different devices
- we should get all the data(profile picture/contact/display name/chat/chat message read/clear history/community/bookmark/setting/trusted user/verification request/wallet/saved address etc that `Sync all devices` support) on the receiver side in **LAN**

#### Platforms
- Android
- iOS

### Steps to test
- Open Status on Sender Device
- Create a new account and generate some data that `Sync all devices` support
- Scroll down to settings page and tap on Syncing menu item
- Tap on Sync new device
- Tap on Setup Syncing
- Enter the password of your account
- You will now see a QR code
- Open Status on Receiver Device
- Tap on 3 dots on top right on login screen
- Tap on scan sync code
- Scan the QR code which you see on Sender Device
- Wait for a few seconds for the Receiver Device, after paring successfully, it should be login automatically
- Check the data on Receiver Device

status: ready

### CODE REVIEW

**Comment by qfrank** [comment]
Hi @pavloburykh , could u pls take a look? thank you 🙂

**Comment by pavloburykh** [comment]
> Hi @pavloburykh , could u pls take a look? thank you 🙂

Hey @qfrank Sure. We will take PR into work as soon as it passes dev review.

**Review by cammellos — APPROVED** [review]

**Comment by pavloburykh** [comment]
@qfrank Thanx for the PR. Please, take a look at following issues

### ISSUE 1 Receiver is not logged in automatically after scanning Sync QR

**Steps:** 

1. Generate Sync QR code on Senders device
2. Scan Sync QR on Receiver's device
3. Observe the result

**Actual result:** QR scanner screen keeps to be opened. User is not logged in automatically into account with synced data.  See video below ISSUE 2

**Expected result:** Receiver is logged in automatically after scanning Sync QR

**Comment by pavloburykh** [comment]
### ISSUE 2 Error on manual login for Receiver after scanning Sync QR

**Steps:**

1. Generate Sync QR code on Senders device
2. Scan Sync QR on Receiver's device
3. Close  QR scanner screen by Receiver
4. Try to manually login the account by Receiver
5. Observe an error

**Actual result:** error appears. User is not able to log in the account

**Expected result** Receiver should be logged in automatically after scanning Sync QR and also be able to log in manually. 

photo_2023-01-13 12 53 42


https://user-images.githubusercontent.com/97245802/212307412-565ff088-3062-4c8d-8386-fdfe60be7532.mp4

**Comment by cammellos** [comment]
@pavloburykh it seems like there's already an account on the first device, is that correct?

We should start with a device logged in, and on the other device, no account (or at least, not the same account)

Basically steps should be:

1) Install status on device A
2) Install status on device B
3) Create account X on device A
4) Show QR code on device A
5) Scan QR code on device B

After these steps, you should have account X on device B with the synced data (from the video, it looks like X was already on B, but correct me if I am wrong)

**Comment by pavloburykh** [comment]
> @pavloburykh it seems like there's already an account on the first device, is that correct?
> 
> We should start with a device logged in, and on the other device, no account (or at least, not the same account)
> 
> Basically steps should be:
> 
> 1. Install status on device A
> 2. Install status on device B
> 3. Create account X on device A
> 4. Show QR code on device A
> 5. Scan QR code on device B
> 
> After these steps, you should have account X on device B with the synced data (from the video, it looks like X was already on B, but correct me if I am wrong)

@cammellos this is correct, Device B has already recovered X account before pairing. Thanx for providing correct flow, it works. Will continue testing. 

But still, do we need to handle case when Receiver already recovered X account on his device and just trying to sync existing data from Device A?

**Comment by cammellos** [comment]
> But still, do we need to handle case when Receiver already recovered X account on his device and just trying to sync existing data from Device A?

To some extent yes :) it should not break the other account I think as a first pass, ideally eventually it pairs the two devices and syncs them bilaterally, but that's definitely out of scope, but the bug you reported needs fixing (just throw an error at pairing, without breaking the account as a first step), though I am not sure we need to do in the scope of this PR.

**Comment by qfrank** [comment]
> > But still, do we need to handle case when Receiver already recovered X account on his device and just trying to sync existing data from Device A?
> 
> To some extent yes :) it should not break the other account I think as a first pass, ideally eventually it pairs the two devices and syncs them bilaterally, but that's definitely out of scope, but the bug you reported needs fixing (just throw an error at pairing, without breaking the account as a first step), though I am not sure we need to do in the scope of this PR.

i'll add a fix in this PR so that it won't breaking the existing account, the fix will just throw an error at pairing if account already exist, i think it will be out next Monday @pavloburykh

**Comment by pavloburykh** [comment]
I've performed syncing of the following data:

- profile picture
- contact 
- contact nickname
- chats  (1-1 chats, group chats) 
- chat message read/unread
- clear history
- communities
- setting: Accept new chat from/See profile picture from/Show profile picture to
- contact request decision 

**NOTE:** before generating data on Device A I have disabled Backup though waku in order to avoid automatic backup of contacts, communities etc. 

### ISSUE 3 Contacts, chats, CR decision have not been synced

**Steps:** 

1. Disable Backup though waku on Device A
2. Generate described above data on Device A
3. Generate sync QR code on Device A
4. Scan generated sync QR code on Device B
5. After login check if all the data has been synced on Device B

**Actual result:** Contacts, chats, CR decision have not been synced

**Expected result:** all the data has been synced

Video below demonstrating data on Device A (sender, right part, IOS) and Device B (receiver, left part, Android) after sync:


https://user-images.githubusercontent.com/97245802/212330674-d2a882a5-6416-4840-952a-067c987ad98a.mp4

[receiver_logs.zip](https://github.com/status-im/status-mobile/files/10411893/receiver_logs.zip)
[sender_logs.zip](https://github.com/status-im/status-mobile/files/10411894/sender_logs.zip)

**Comment by pavloburykh** [comment]
@qfrank @cammellos regarding synced data, could you please specify:
1. What kinds of chats are included into sync? 
2. What kind of settings are included into sync?

**Review by siddarthkay — APPROVED** [review]

**Comment by cammellos** [comment]
@pavloburykh Chats are not included in the sync for now, while settings synced should be:

Currency
Default sync period
Display name
Gifs favorites
Recent gifs
Messages from contacts only
ENS name
Preview privacy
Show profiles picture to
Which profiles picture I want to see
Send status updates (online/offline)

**Comment by qfrank** [comment]
> @qfrank @cammellos regarding synced data, could you please specify:
> 
> 1. What kinds of chats are included into sync?
> 2. What kind of settings are included into sync?

public group chats will be included @pavloburykh

**Comment by qfrank** [comment]
> I've performed syncing of the following data:
> 
> * profile picture
> * contact
> * contact nickname
> * chats  (1-1 chats, group chats)
> * chat message read/unread
> * clear history
> * communities
> * setting: Accept new chat from/See profile picture from/Show profile picture to
> * contact request decision
> 
> **NOTE:** before generating data on Device A I have disabled Backup though waku in order to avoid automatic backup of contacts, communities etc.
> 
> ### ISSUE 3 Contacts, chats, CR decision have not been synced
> **Steps:**
> 
> 1. Disable Backup though waku on Device A
> 2. Generate described above data on Device A
> 3. Generate sync QR code on Device A
> 4. Scan generated sync QR code on Device B
> 5. After login check if all the data has been synced on Device B
> 
> **Actual result:** Contacts, chats, CR decision have not been synced
> 
> **Expected result:** all the data has been synced
> 
> Video below demonstrating data on Device A (sender, right part, IOS) and Device B (receiver, left part, Android) after sync:
> 
>  data_after_sync.mp4 
> [receiver_logs.zip](https://github.com/status-im/status-mobile/files/10411893/receiver_logs.zip) [sender_logs.zip](https://github.com/status-im/status-mobile/files/10411894/sender_logs.zip)

Hi @pavloburykh , could u pls check if this issue also exist for feature `Sync all device`? I guess this is a bug but not relate to this PR... thanks in advance

BTW, latest update contains the fix(throw error if account already exist when local pairing), this means if the account already exist and u r trying to scan sync code, nothing will happen for the UI then, pls try it!

**Comment by pavloburykh** [comment]
### ISSUE 4

Hey @qfrank ! After recent commits user is not redirected to account after scanning sync QR. 
I have tried to scan both from state when user is not logged in yet to any account and logged into another account. 

https://user-images.githubusercontent.com/97245802/212741568-8b0196ad-befb-4458-bb77-b39403ce68d7.mp4

**Comment by qfrank** [comment]
> Hey @qfrank ! After recent commits user is not redirected to account after scanning sync QR. I have tried to scan both from state when user is not logged in yet to any account and logged into another account.
> 
>  telegram-cloud-document-2-5345823219259549899.mp4

if the account already exist on the device that u r trying to use the camera to scan, i'd say it's normal, there should be an error message(key file already exists) in status-mobile log

**Comment by pavloburykh** [comment]
> > Hey @qfrank ! After recent commits user is not redirected to account after scanning sync QR. I have tried to scan both from state when user is not logged in yet to any account and logged into another account.
> > telegram-cloud-document-2-5345823219259549899.mp4
> 
> if the account already exist on the device that u r trying to use the camera to scan, i'd say it's normal, there should be an error message(key file already exists) in status-mobile log

Hey @qfrank! As I mentioned above, I have tried to scan both from state when user is not logged in yet to any account (as you can see on video) and logged into another account. I have not been logged into scanned account on receiver device. 

But this is wierd, cause I tried today and was redirected to account successfully. Maybe there were some network issues its hard to say. I will let you know if I face the issue again.

**Comment by pavloburykh** [comment]
@qfrank could you please rebase the PR. There are some important fixes in develop. Thanx.

**Comment by qfrank** [comment]
> @qfrank could you please rebase the PR. There are some important fixes in develop. Thanx.

done @pavloburykh

**Comment by qfrank** [comment]
update: CR decision won't been synced in this case(local pairing) since we don't have user messages(contact request) on the receiver side. This is a little different from `Sync all device`. @pavloburykh @cammellos

**Comment by qfrank** [comment]
update: CR decision won't been synced in this case(local pairing) since we don't have user messages(contact request) on the receiver side. This is a little different from `Sync all device`. @pavloburykh @cammellos

**Comment by pavloburykh** [comment]
> Hey @qfrank ! After recent commits user is not redirected to account after scanning sync QR. I have tried to scan both from state when user is not logged in yet to any account and logged into another account.
> 
>  telegram-cloud-document-2-5345823219259549899.mp4

@qfrank I am still facing this issue. More often when I use IOS as receiver. App crashes. 

To reproduce the issue try to scan sync QR from state when receiver device has just installed the app and has not logged into any accounts yet.  

Below is video and logs from IOS

[logs (11).zip](https://github.com/status-im/status-mobile/files/10435938/logs.11.zip)

https://user-images.githubusercontent.com/97245802/212923769-05d6dbb2-abdb-41ff-9437-a63ea3eff54b.mp4

Screenshot of an error from Android device as receiver

photo_2023-01-17 16 23 58

**Comment by pavloburykh** [comment]
**Regrading sync overall:**

I have performed sync both by old Sync all method and by new transferring account. 

Data which has been generated for testing:

- Currency
- Default sync period
- Messages from contacts only
- ENS name
- Preview privacy
- Show profiles picture to
- Which profiles picture I want to see
- Send status updates (online/offline)
- profile picture
- contacts
- display name (only desktop for now) test nickname for 1 contact. 
- community
- contact request decision

As a result following data has not been synced:

- contacts
- ENS name
- Preview privacy
- Default sync period
- contact request decision

Current issue exists in old sync all method, so it will be logged and addressed separately from this PR.

**Comment by pavloburykh** [comment]
### ISSUE 5 Unable to add new contact on receiver device after sync until app relaunch
Cannot reproduce the bug via old sync so I assume this is PR issue

**Steps:**

1. Generate sync QR by User A
2. Scan sync QR by User B
3. Try to add new contact by User B after redirection into account

**Actual result:** add contact button does not respond. Fixes after app relaunch. 

**Expected result:** add contact button responds, user is able to add new contact


https://user-images.githubusercontent.com/97245802/212936776-81691a13-0b57-42a2-8dd5-4a23504d41c1.mp4

[receiver_Android.zip](https://github.com/status-im/status-mobile/files/10436432/receiver_Android.zip)

**Comment by qfrank** [comment]
Hi @pavloburykh , regarding issue 4, it's proberbly because receiver can't connect to sender device, are you sure both device are in the same network and not use other tools like VPN?

**Comment by qfrank** [comment]
BTW, currently, status-mobile looks like don't take care of signal like:
```
local pairing signal received {:signal-type "{\"type\":\"localPairing\",\"event\":{\"type\":\"connection-error\",\"error\":\"dial tcp 10.0.2.15:38683: connect: operation timed out\",\"action\":3}}"}
```
should we handle this type of signal before next release? @cammellos

**Comment by pavloburykh** [comment]
> Hi @pavloburykh , regarding issue 4, it's proberbly because receiver can't connect to sender device, are you sure both device are in the same network and not use other tools like VPN?

Hi @qfrank! both devices use the same WiFi network and no VPN is enabled.

**Comment by qfrank** [comment]
> > Hi @pavloburykh , regarding issue 4, it's proberbly because receiver can't connect to sender device, are you sure both device are in the same network and not use other tools like VPN?
> 
> Hi @qfrank! both devices use the same WiFi network and no VPN is enabled.

Oh, i saw your ios device has account 'Midnightblue...', i was wondering account corresponding to the qr code generated from android are also 'Midnightblue...' too? @pavloburykh

**Comment by pavloburykh** [comment]
> uce the issue try to scan sync QR from state when receiver device has just installed the app and has not logged into any accounts yet.
> 
> Below is video and logs from IOS

If you see it from the added logs I guess it is because I have pulled out logs after I have managed to log in the account on receiver device after couple of tries.

**Comment by pavloburykh** [comment]
@qfrank on the [video](https://github.com/status-im/status-mobile/pull/14763#issuecomment-1385506833) you can see that IOS device is not logged into any account yet at the moment when it was recorded. The app has just been installed.

**Comment by pavloburykh** [comment]
@qfank here is more detailed video of behaviour from [ISSUE 4](https://github.com/status-im/status-mobile/pull/14763#issuecomment-1385506833) and some more logs

What you can see on video:
1. I install the app
2. Try to scan QR - nothing happens, user is not redirected into account
3. I relaunch the app
4. Try to scan QR once again - nothing happens, user is not redirected into account
5. I relaunch app

**Actual result:** I see the login page into scanned account. 

https://user-images.githubusercontent.com/97245802/213139164-d9bfe872-8085-4541-b1f5-a832140e1348.mp4

[logs (12).zip](https://github.com/status-im/status-mobile/files/10444386/logs.12.zip)

**Comment by qfrank** [comment]
> ### ISSUE 5 Unable to add new contact on receiver device after sync until app relaunch
> Cannot reproduce the bug via old sync so I assume this is PR issue
> 
> **Steps:**
> 
> 1. Generate sync QR by User A
> 2. Scan sync QR by User B
> 3. Try to add new contact by User B after redirection into account
> 
> **Actual result:** add contact button does not respond. Fixes after app relaunch.
> 
> **Expected result:** add contact button responds, user is able to add new contact
> 
>  telegram-cloud-document-2-5345984851763799211.mp4 
> [receiver_Android.zip](https://github.com/status-im/status-mobile/files/10436432/receiver_Android.zip)
Hi @pavloburykh , i can't add contact too, this issue seems not relate to this PR ... since i tried create a new account , it does not work neither

**Comment by qfrank** [comment]
> @qfank here is more detailed video of behaviour from [ISSUE 4](https://github.com/status-im/status-mobile/pull/14763#issuecomment-1385506833) and some more logs
> 
> What you can see on video:
> 
> 1. I install the app
> 2. Try to scan QR - nothing happens, user is not redirected into account
> 3. I relaunch the app
> 4. Try to scan QR once again - nothing happens, user is not redirected into account
> 5. I relaunch app
> 
> **Actual result:** I see the login page into scanned account.
> 
>  telegram-cloud-document-2-5350311339824784260.mp4 
> [logs (12).zip](https://github.com/status-im/status-mobile/files/10444386/logs.12.zip)

found the cause of the issue 4, need figure out a way to solve, thinking...

**Comment by qfrank** [comment]
closed since relate issues r resolved

**Pull request closed without merging**
