### PR TITLE
✅ 🗝️ Enable password reset UI

### PR DESCRIPTION
**Pull request by shivekkhurana**
### Summary
Enables password reset feature implemented in #12163. 
Results of tests performed on that PR can be posted here.

### CODE REVIEW

**Comment by churik** [comment]
@shivekkhurana 
at attempt to reset password after entering old and new password got error:
IMAGE 2021-06-25 15:34:53

**Comment by shivekkhurana** [comment]
This will unblock https://github.com/status-im/status-react/issues/11777

**Comment by churik** [comment]
@shivekkhurana  thank you for work! 
Several issues:
### ISSUE 1: Can tap "next" several times on reset password screen 

**Steps:**
1) restore multiaccount from seed phrase
2) go to Security > Reset password 
3) enter passwords
4) tap "Next" several times

**Expected result:**
"Next" can be tapped only once

**Actual result:**
IMAGE 2021-06-30 16:20:38

**OS:** IOS, Android

### ISSUE 2: Automatic logout doesn't work after resetting password until relogin
**Steps:**
1) restore multiaccount from seed phrase
2) reset password
3) go to Advanced > Network > change Network

**Expected result:** should be logged out

**Actual result:** is not logged out

### ISSUE 3: Reset password is available for keycard users

### ISSUE 4: Endless spinner if resetting password with enabled biometric login (IOS only)
**Steps:**
1) restore multiaccount from seed phrase
2) enable biometric login
3) reset password
4) reopen app
In case of Android after attempt to login user stays on login screen with "Wrong password" error - suppose this is expected behaviour
In case of IOS - blank screen with endless spinner
IMAGE 2021-06-30 17:10:55
[status_logs.zip](https://github.com/status-im/status-react/files/6741965/status_logs.zip)

**Comment by shivekkhurana** [comment]
@churik 

> ISSUE 1: Can tap "next" several times on reset password screen

✅ Added an overlay that cannot be closed until password reset is complete. The user can no longer press the next button.

> ISSUE 3: Reset password is available for keycard users

✅ Fixed 

> ISSUE 4: Endless spinner if resetting password with enabled biometric login (IOS only)

🤞🏼 The problem was that password reset didn't update the password in OS keychain. Have fixed it now, should work hopefully

**Comment by shivekkhurana** [comment]
> ISSUE 2: Automatic logout doesn't work after resetting password until relogin
> Steps:
> 1. restore multiaccount from seed phrase
> 2. reset password
> 3. go to Advanced > Network > change Network

I feel this is a problem in multiaccount recovery flow. I checked resetting password and then changing network on an existing account. It worked fine. 

Can you please confirm this is not an issue if step 1 is removed?

**Comment by churik** [comment]
> Can you please confirm this is not an issue if step 1 is removed?

Well, if I create multiaccount from scratch, reset password, and change network - no autologout.
Tested on latest build with https://github.com/status-im/status-react/commit/8edd260e90e94c856b701ffd1efc5839fead0050 commit

**Comment by shivekkhurana** [comment]
@churik All issues fixed.

**Comment by churik** [comment]
@shivekkhurana 
thank you!
I can still tap next several times, but it is not a big deal now as we have automatic logout after.
So considering it as ready to be merged.

**Review by flexsurfer — APPROVED** [review]

**Comment by shivekkhurana** [comment]
@churik 
> I can still tap next several times

I'm not able to understand this. When you fill the form and press the next button, an overlay should cover the screen. 

It is not possible to close the overlay, until the password reset is complete, in which case the only way to proceed is to logout or close the app.

Can you give me the steps to reproduce the behaviour you see?

**Comment by shivekkhurana** [comment]
[SELF NOTE] Get rid of feature flag before merging.

**Comment by churik** [comment]
Sure. The way to reproduce it is to be quick enough to tap "Next" several times before overlay is shown.
But as I said it is quite edge case - and only the issue that that error is shown in background.

https://user-images.githubusercontent.com/4557972/124620623-e89dd900-de79-11eb-900f-e81036deb0b7.mp4

**Comment by shivekkhurana** [comment]
I understand now. I'll push a fix tomorrow.

**Comment by shivekkhurana** [comment]
@churik I have added a condition that disables the `Next >` button when the password is resetting. In terms of the UI, it might not seem obvious (ie. it might feel that you are able to press the button), but multiple requests are not made.

**Comment by churik** [comment]
Ready to be merged.

**Pull request merged**
