### PR TITLE
[ISSUE #3633] Migrated profile lists to latest design

### LINKED ISSUE #3633: Transfer Network and Offline messages screens to a new design
### User Story

As a user, I want to see a consistent design over all screens.

### Description

*Type*: Feature

Scope of this issue:

1. Transfer Network settings screen in the profile to a new `List component`; get rid of a grey background;  use our new blue color for selected elements.
2. Transfer Offline messages settings screen in the profile to a new `List component`; get rid of a grey background;  use our new blue color for selected elements.
3. Get rid of the word `settings` since we have it as a title of the whole list.
img_3753

#### Expected behavior

Showing example only for Network settings screen. The same result is expecting to have for Offline messages settings screen.

settings

#### Actual behavior
img_3752

### Additional Information
* Status version: 0.9.15
* Operating System: <Android|iOS>

### PR DESCRIPTION
**Pull request by jeluard**
fixes #3633

### Summary:

Migrated profile lists to latest design

### Steps to test:
- Open Status
- Navigate to profile
- Validate lists reflect latest design

status: ready

### CODE REVIEW

**Review by dmitryn — APPROVED** [review]

**Review by flexsurfer — APPROVED** [review]

**Comment by antdanchenko** [comment]
@jeluard please take a look at new error after sending a transactions via request or send command, both from chat and wallet
also you can check the behavior on the [video record](https://saucelabs.com/beta/tests/c7c0e9c5d9134fd08accbcb9400af6a0/watch?auth=001ab7920db2e09caf7ce434866bf0b1#80) starting from 5:35
e.g.
0034screenshot

**Comment by jeluard** [comment]
@antdanchenko Great catch! Would have been hard to track after merge !

How can I retrigger automated tests now? I did a force push.

**Comment by asemiankevich** [comment]
@jeluard please 

1. rename `Network` to `Network Settings` on Android and align to left (according to https://app.zeplin.io/project/5a55d587ba304eed4d2c942f/screen/5ab1263608d6788eb27c760d):

image

`Offline messages` should also be aligned to left on Android
image

2. add delimiters for iOS on both screens if possible, I assume it is not in scope of this PR (please check https://app.zeplin.io/project/5a55d587ba304eed4d2c942f/screen/5ab1263608d6788eb27c760d )

image

image


i can confirm i can exchange messages and transactions in this PR

**Comment by jeluard** [comment]
@asemiankevich Actually all toolbars are now centered on iOS. Looks like a regression in develop.

**Comment by jeluard** [comment]
@asemiankevich Fixed all other issues

**Pull request merged**
