### PR TITLE
[WIP] Add spec generators for addresses / public keys

### PR DESCRIPTION
**Pull request by gnl**
Add spec generators for addresses / public keys

See also https://github.com/status-im/status-react/pull/6064

### CODE REVIEW

**Comment by ghost** [comment]
### Pull Request Checklist
- [ ] Have you updated the documentation, if impacted (e.g. [docs.status.im](https://docs.status.im/docs/build_status.html))?

**Comment by oskarth** [comment]
What's the state of this PR?

**Comment by gnl** [comment]
Not abandoned – needs just a little bit more love and some performance optimisations, on it.

**Comment by oskarth** [comment]
No activity for a month. Closing PR as inactive. Feel free to reopen if this is in error / when it is ready.

**Pull request closed without merging**
