### PR TITLE
[#16455] Updated button style

### LINKED ISSUE #16455: Communities - Close button with incorrect background
# Bug

The close button **with the light theme** doesn't have the correct background.

### PR DESCRIPTION
**Pull request by andresceballosm**
[comment]: # (To auto-close issue on merge, please insert the related issue number after # i.e fixes #16455)

fixes #16455 

### Summary

Updated button style

#### Platforms

- Android
- iOS
- 

status: ready

### CODE REVIEW

**Comment by ilmotta** [comment]
@andresceballosm, thanks for working on this PR. I ran the branch, but the button looks completely rounded, which is not what's in Figma.

#### Actual



#### Expected

https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?type=design&node-id=12510-427273&mode=design&t=ckwhbv6fbnhJf3Fi-0

**Comment by andresceballosm** [comment]
> @andresceballosm, thanks for working on this PR. I ran the branch, but the button looks completely rounded, which is not what's in Figma.
> 
> #### Actual
> 
> #### Expected
> https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?type=design&node-id=12510-427273&mode=design&t=ckwhbv6fbnhJf3Fi-0
> 
> 

Hey @ilmotta, I got it, the thing is, I don't have access to Figma, so I took the image in the PR as a reference, but it's done now thanks!

**Comment by andresceballosm** [comment]
Hey @ilmotta , I got it, the thing is, I don't have access to Figma, so I took the image in the PR as a reference, but it's done now thanks!

**Comment by ilmotta** [comment]
> Hey @ilmotta , I got it, the thing is, I don't have access to Figma, so I took the image in the PR as a reference, but it's done now thanks!

Sorry, I was assuming you had basic access to Figma. Without access it's nearly impossible to get some UI settings right. For this particular PR it may have worked, but it's far from ideal.

@cammellos, do you know if we need to give Figma access on-demand or if we can generally make some Figma files publicly available to external contributors?

**Comment by cammellos** [comment]
> @cammellos, do you know if we need to give Figma access on-demand or if we can generally make some Figma files publicly available to external contributors?

We give access to people on demand, we would need the contributor email address (they can ping me on discord directly if they want "cammellos")

**Review by jo-mut — APPROVED** [review]

**Review by ilmotta — APPROVED** [review]

**Review by smohamedjavid — APPROVED** [review]

**Comment by qoqobolo** [comment]
Hi @andresceballosm, thanks for PR!
Could you rebase it to get builds for testing, please? 

---

closed the PR by accident, sorry :)

**Comment by qoqobolo** [comment]
@andresceballosm please ping the mobile QA team with `@status-im/mobile-qa` here in comments once the PR is ready to be manually tested.
Thank you!

**Review by jo-mut — APPROVED** [review]

**Comment by flexsurfer** [comment]
hey @andresceballosm is this still relevant? should we move it to testing?

**Pull request closed without merging**
