### PR TITLE
Emoji and numeric keyboards are shown when tap on /send while emojis are opened (#1056)

### LINKED ISSUE #1056: Emoji and numeric keyboards are shown when tap on /send while emojis are opened
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Open emoji keyboard in chat. Tap on /send command. Both emoji and numeric keyboards are shown
2 keyboards

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
Onlu numeric keyboard is shown if tap on /send
#### Actual behavior
[comment]: # (Describe what actually happened.)
Both emoji and numeric keyboards are shown if tap on /send
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status and login
- Open 1-1 chat
- Tap on "emoji" button in input field to open emoji keyboard
- Tap on /send

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.7d67
* Operating System: Android and iOS

### PR DESCRIPTION
**Pull request by alwx**
Fixes #1056

### CODE REVIEW

**Comment by rasom** [comment]
It works on android (though i guess we could avoid flickering)

ezgif-3-06bc13b1d1

But it doesn't work on iOS, we have to click emoji icon twice 


i

**Comment by alwx** [comment]
The easier and better fix is actually a simple one-liner. I've updated the PR.

**Comment by rasom** [comment]
I suppose this fix solves original issue, but there are some problems anyway:
- On iOS when we 1) focus 2) press emoji icon 3) press emoji icon again input doesn't get focused again


- on Android it still flickers  (also ui is super slow on my android device, but that's another issue too)
andr

@annadanchenko should we merge this PR and create separate issue for problems above?

**Comment by annadanchenko** [comment]
@rasom let's merge it and I will create separate issues

**Pull request merged**
