### PR TITLE
[Refactor browser and permissions and add qr-code-api

### LINKED ISSUE #2854: Cannot Scan QR code from DApp
### User Story

As a developer, I want to be able to build DApps that can scan QR codes.

### Description

*Type*: Feature

*Summary*: In line with this idea for Decentralart: https://github.com/status-im/ideas/issues/66, we need to be able to scan QR codes directly from a DApp within Status.

#### Expected behavior
Can scan a QR code easily and get the returned data to display.

#### Actual behavior
Permission request for access to camera never shows up. 

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Navigate to Console
- `@browse` to either https://schmich.github.io/instascan/ or https://webqr.com/
- Notice that a request for permission to use the camera never materialises and that you cannot scan anything.

### Solution

*Summary*: 

- Bug @jeluard @flexsurfer or @alwx to figure out how to give DApps access to our scanning a QR code screen, or allow DApps to request these sort of permissions.

### Additional Information
* Status version: 0.9.12+
* Operating System: Android and iOS

### LINKED ISSUE #5870: Add QR code scanner API
### User Story

As a developer, I want access to a QR code scanner in the Status browser so that my DApp can read users' QR codes for functionalities like those listed in [EIP 945](https://github.com/ethereum/EIPs/issues/945).

### Description

*Type*: Feature

*Summary*: See [EIP 945](https://github.com/ethereum/EIPs/issues/945). This is being implemented primarily by request for the Blockparty team, to facilitate faster check-in processes. 

Blockparty will be used to check in several hundred attendees at the #CryptoLife hackathon in October.

#### Expected behavior
A developer has access to a QR code scanning API within the Status browser, regardless of whether the user has granted permissions to the DApp to access the full Ethereum provider.

#### Actual behavior
No QR code scanner API

### LINKED ISSUE #5895: Null is not an object: (evaluating e.lastIndexOf') crash when closing webview on Android
***Type***: Bug

***Summary***: After user navigated to URL that causes redirect (or to unexisting domain), (e.g. opening bbc.com redirects to http://www.bbc.com) and then closing this webview via top-left cross icon - app crashes with the `Null is not an object: (evaluating 'e.lastIndexOf')` error. 

#### Expected behavior
No crash when closing http URL ebview
#### Actual behavior
Crash when closing the webview with opened 'http' URL (or unexisting domain) on Android 
screen shot 2018-09-19 at 12 02 59
### Reproduction

- Open Status and log in to account
- Navigate to `Open Dapp` -> paste `bbc.com` -> `Done`
- Tap top-left cross icon to close webview

### Additional Information
* Status version: Develop `0.9.28 (8561); node 0.14.1`
* Operating System: Android 8, 7.0, 6.0+

#### Logs

TF session with logs: https://app.testfairy.com/projects/4803622-status/builds/8597460/sessions/4401822965/?accessToken=CTEHa1ilpWLFd2sA9ZyqjoHMVOc

<blockquote><div><strong><a href="http://www.bbc.com/">BBC - Homepage</a></strong></div><div>Breaking news, sport, TV, radio and a whole lot more. The BBC informs, educates and entertains - wherever you are, whatever your age.</div></blockquote>
<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803622-status/builds/8597460/sessions/4401822965/?accessToken=CTEHa1ilpWLFd2sA9ZyqjoHMVOc">TestFairy: Status 0.9.28 (8561) @2018</a></strong></div></blockquote>

### PR DESCRIPTION
**Pull request by yenda**
fixes #5895
fixes #5870
fixes #2854

- move db and models ns to browser module
- remove browser navigation/preload-data
- rewrite dapp-permission logic and move code to permissions ns
- rewrite all browser events according to guidelines and move them to
`status-im.events` ns
- rewrite tests for browser and permissions

TODOS:
- qr-code-api

### Steps to test:
- Play around in the browser

status: ready

### CODE REVIEW

**Review by janherich — APPROVED** [review]

**Review by jeluard — APPROVED** [review]

**Comment by lukaszfryc** [comment]
All works fine for me 👍

@Serhy if it works on your side as well, move the PR to merge column please. 

Btw, I noticed https://github.com/status-im/status-react/issues/5950 that I believe was introduced in https://github.com/status-im/status-react/pull/5606

**Comment by lukaszfryc** [comment]
@yenda one e2e test failed while requesting ETH from Wallet tab. Could you check if this is related to your changes?

**Comment by yenda** [comment]
@lukaszfryc  it's not related

**Comment by Serhy** [comment]
Looks good on my side as well. The `'Error: Error: Error: Error: Error: There is no route defined for key home.` fixed in scope of https://github.com/status-im/status-react/issues/5936.

**Comment by lukaszfryc** [comment]
@yenda please cherry pick it to `release/0.9.28` branch

**Comment by lukaszfryc** [comment]
@yenda @Serhy I think this PR introduced https://github.com/status-im/status-react/issues/6012 as it was working before. See #6012 description.

**Pull request merged**
