### PR TITLE
fixed: getting stuck on the "Keys saved" randomly

### PR DESCRIPTION
**Pull request by qfrank**
### Summary
After this PR, the issue of getting stuck during the creation of a new profile when the screen shows 'Keys saved' should be resolved.

relate [comment](https://github.com/status-im/status-mobile/issues/16560#issuecomment-1655405293)
relate [PR](https://github.com/status-im/status-go/pull/3823) for status-go

#### Platforms

- Android
- iOS

status: ready

### CODE REVIEW

**Review by siddarthkay — APPROVED** [review]

**Comment by siddarthkay** [comment]
@status-im/mobile-qa : This PR is going to require some extensive testing :D

**Comment by qoqobolo** [comment]
@qfrank thanks a lot for the fix!
We couldn't reproduce the issue after multiple attempts in different scenarios and on different devices.
If it comes back, we will let you know.
PR can be merged.

**Review by Francesca-G — APPROVED** [review]
I didn't get stuck on the "Keys saved" and everything looked good.

Follow up issue about the animation:
There's a frame that shouldn't be there at the end of the key saving animation, as you can see after the key has been grabbed by the end and goes inside the device the particles appear once again at the end of the animation, for a couple of frames.


https://github.com/status-im/status-mobile/assets/122543089/d5728659-0b11-4289-995e-6662ca549684

The animation should end here:
IMG_0292

**Comment by qoqobolo** [comment]
> There's a frame that shouldn't be there at the end of the key saving animation, as you can see after the key has been grabbed by the end and goes inside the device the particles appear once again at the end of the animation, for a couple of frames.

Oops, this PR was not supposed to be reviewed by you @Francesca-G, I moved it to the wrong column out of habit, sorry 😅
But that's cool that you found this issue with the animation, I'll log the follow-up.
Thank you!

**Pull request merged**
