### PR TITLE
[WIP] Updated profile link format: replace join.status.im with status.app

### LINKED ISSUE #16810: Update link format (to fix inconsistency with desktop)
# Bug Report

## Problem 

The link format should be updated for three types of URLs: 

- link to user
- link to a community
- link to a channel inside a community

**New links format (on Desktop; example for profile links):** https://status.app/u/iwSACghxb3FvYm9sbwM=#zQ3shrgSaffLisbiqj2brkDK8Le7wpbpbpzriWd8kPUmdYhs1

**Links on Mobile:** https://join.status.im/u/zQ3shS1FWUrdQeoLeZKxYhcuFGUW93Rj23psb5XYKzW9z653b

As a result, users can't add each other to contacts by pasting profile links into the search field.

Screenshot 2023-07-28 at 16 34 25

Screenshot 2023-07-28 at 16 41 49

### Reproduction

On Mobile 
1. Copy a profile/community/channel link on Desktop (`https://status.app/u/...` format)
2. Try to use it on Mobile

### Additional Information

- Status version: nightly 28/07
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by alwx**
fixes #16810

#### Platforms

- Android
- iOS

##### Functional

- 1-1 chats
- public chats
- group chats

status: ready

### CODE REVIEW

**Comment by siddarthkay** [comment]
Hey @alwx : do you know if https://github.com/status-im/universal-links-handler project has been updated to handle the change in these url schemes?

**Comment by John-44** [comment]
@alwx there is much more than simply changing the domain needed to support the new link format. I recommend speaking to @felicio from the web team who designed the new link format and also recommended reviewing the specification for the new link format. The link format is for three types of URLs: link to user, link to a community, link to a channel inside a community.

Desktop team should have already implemented backend to support new link format in status-go, speak to @jrainville for more details.

The old link format should be removed for everywhere, any time a user copies or shares a link to a user, community or channel they should be sharing the new link format. Any input field that accepts a user or community public key should also accept a new format URL.

cc @siddarthkay

**Comment by alwx** [comment]
@siddarthkay oh wow, never saw this project. And it seems like the last time it was updated was more than a year ago.

**Review by jakubgs — CHANGES_REQUESTED** [review]
@siddarthkay good question, and no, it has not. So not sure what this PR is supposed to achieve.

There currently is no https://status.app/.

**Comment by alwx** [comment]
Now I'm confused then — so the issue says about `https://status.app` which doesn't exist? Why do the links on desktop get generated with this domain then?

**Comment by alwx** [comment]
Also: @jakubgs requested changes without specifying what these changes need to be about 😀

**Comment by siddarthkay** [comment]
> Why do the links on desktop get generated with this domain then

They do not work on Desktop as well they just generate this url scheme, they're currently targeting to fix it in 0.14 release 
Ref : Discord chat : https://discord.com/channels/624205794384281629/1048212980904501329/1133701710561419305

**Comment by jrainville** [comment]
Like others have said, we will have status.app later, but it's normal if it doesn't work right now.

The goal is mostly to align on the new link structure. 

You can see the new backend functions that were added in status-go in this PR https://github.com/status-im/status-go/pull/3665

You can talk to @borismelnik or @MishkaRogachev on how those functions work and how they used it in our front-end.

**Comment by jakubgs** [comment]
@alwx I didn't request changes, I simply blocked this from being merged since `status.app` doesn't exit.

**Comment by alwx** [comment]
Restoring this PR because of this comment:
https://github.com/status-im/status-mobile/issues/16810#issuecomment-1676454610

**Comment by alwx** [comment]
@jakubgs requesting the review again because of the discussion we had here: https://github.com/status-im/status-mobile/issues/16810

**Comment by flexsurfer** [comment]
@jakubgs could you pls take a look

**Comment by John-44** [comment]
> @jakubgs could you pls take a look

@flexsurfer before this change merges, the new URLs generated need to be tested to ensure they work with the web preview pages by @felicio or @prichodko

**Review by jakubgs — APPROVED** [review]
@flexsurfer I don't see anything wrong with this PR technically. The only issue is that `status.app` domain doesn't host anything yet.

**Comment by flexsurfer** [comment]
hey @alwx what's the status of this PR ?

**Comment by alwx** [comment]
@cammellos what's the current status? I checked the original issue and it seems like not everything was done but maybe I'm wrong.

**Comment by John-44** [comment]
@cammellos fully supporting the new Status User, Community and Channel inside a community URL formats (and getting rid of the old format links) is a must-have feature for 1.26

Includes: updating everywhere where links are shared to the new format, ensuring all inputs where keys can be entered support the new URL being entered, update the URL handler and testing the generated URLs with the web preview pages.

**Comment by cammellos** [comment]
@Samyoul can update you, there's a bunch of people that are working on it

**Comment by churik** [comment]
I believe might be closed because of https://github.com/status-im/status-mobile/pull/17480

**Pull request closed without merging**
