### PR TITLE
Feature/communities notifications

### LINKED ISSUE #11806: Send notification on receiving a request for a community (android)
```
As an admin
I want to receive a push notification when someone requests access to a community
So that I can promptly react to it
```

### Description

A notification should be visualized on someone receiving a notification, if clicked on, it should take the user to the list of membership requests.

This is only for android devices.

Part of https://github.com/status-im/status/issues/75

### LINKED ISSUE #11807: Send notification on receiving a request for a community (ios)
```
As an admin
I want to receive a push notification when someone requests access to a community
So that I can promptly react to it
```

### Description

A notification should be visualized on someone receiving a notification, if clicked on, it should take the user to the list of membership requests.

This is only for ios devices.

Part of https://github.com/status-im/status/issues/75

### PR DESCRIPTION
**Pull request by cammellos**
Fixes: #11806 
Fixes: #11807 

### Features added
- An admin should receive a notification on android if a community request is made
- Clicking on the push notification will take you to the list of requests

### Changes to android push notifications

- Push notification for messages are grouped by chat,  similarly to discord. Only the first notification in a chat will alert, the next will be "silent" notification. Meaning you will see the message but it will not alert. This is consistent with discord/whatsapp.
- Clicking on a transaction notification will take you to wallet (not sure it was doing that before, but it might have)
- Changed the behavior of the notification toggle, before `Notifications` and `wallet transactions` were separate, meaning you could have `wallet transaction` and `Notifications` disabled and you'd still receive transactions notifications.  Now you need to have `Notifications` enabled to receive wallet transactions. Eventually we will have an option to toggle message notifications.

### Changes to IOS push notifications

- A notification should be received when a user joins a community (not tested as I don't have an IOS device). The build needs to be set on `staging` from the start for it to work (This PR should start on staging).

### Technical details

- Removes headless tasks, they were not used
- Message notifications are passed unchanged to java, we still check if the chat is in the foreground, but no modifications are made to the notification object. This should get us closer to avoid clojure completely.
- Merged the two notifications implementation (NewMessageSignalHandler and PushNotificationHelper). We should split maybe off in more meaningful classes, but there's less code duplication now, and it can be re-used for non-chat (communities) notifications.
- Parsing of text for message notifications is done in status-go
- Signal is not passed to status-react if notifications are not enabled

### Next step

To completely remove notification code from status-react the following are required:

- Java needs to be alerted of which chat is in the foreground and whether the app is in the foreground
- Transaction notification body message need to be created in status-go
- Notification signal needs to be stopped in Java

### Limitations

If the name of a contact changes, the notification will not change, once is displayed, it won't be modified

### Testing push notifications

1) Create a "on-request" community on user A
2) Invite user B
3) Join community with B
4) On B, share community with user C
4) On C click on request to join button

Expected: 
User A should have received a notification

### CODE REVIEW

**Review by rasom — APPROVED** [review]

**Comment by Serhy** [comment]
Thanks @cammellos !
#11806 and  #11807 are fixed.
Push notifications are grouped now by chat

**Issue 1**
When tap upon notification received for Group chat - its redirects (and at the same time joins) the public chat with `#g` name.

**Issue 2**
 I had several app crashes in some relatively random places. But they related to Push Notifications (according to what crash error says). One time it happened when I switch Network from Mainnet to Ropsten, other two times it happened when I tap upon notification about received transaction. Switching network not reproducible, but the 'Notification about TX' reproducible
**Reproduction**:
1) Recover account UserA with assets (Ropsten should be OK). And create new account UserB (Android)
2) Switch both users to Ropsten network
3) Enabled Notifications on both devices
4) UserA sends ETHro to UserB
5) Put UserB on background and wait till Notification appears (In order to speed up this process I pull-to-refresh in Wallet which makes a call for incoming TX)
6) Tap upon notification. 
**Actual result:**  If you are on background - nothing happens no redirects. And if you open Status from App list - the crash appears

Screenshot 2021-03-23 at 11 22 09

``` 
--------- beginning of crash
03-23 10:49:47.442 25860 27248 E AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
03-23 10:49:47.442 25860 27248 E AndroidRuntime: Process: im.status.ethereum.pr, PID: 25860
03-23 10:49:47.442 25860 27248 E AndroidRuntime: java.lang.IllegalArgumentException: Receiver not registered: im.status.ethereum.pushnotifications.PushNotificationHelper$1@4142d2c
03-23 10:49:47.442 25860 27248 E AndroidRuntime: 	at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:1523)
03-23 10:49:47.442 25860 27248 E AndroidRuntime: 	at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1712)
03-23 10:49:47.442 25860 27248 E AndroidRuntime: 	at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:733)
03-23 10:49:47.442 25860 27248 E AndroidRuntime: 	at im.status.ethereum.pushnotifications.PushNotificationHelper.stop(PushNotificationHelper.java:788)
03-23 10:49:47.442 25860 27248 E AndroidRuntime: 	at im.status.ethereum.pushnotifications.PushNotification.disableNotifications(PushNotification.java:129)
03-23 10:49:47.442 25860 27248 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-23 10:49:47.442 25860 27248 E AndroidRuntime: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
03-23 10:49:47.442 25860 27248 E AndroidRuntime: 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
03-23 10:49:47.442 25860 27248 E AndroidRuntime: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
03-23 10:49:47.442 25860 27248 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
03-23 10:49:47.442 25860 27248 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
03-23 10:49:47.442 25860 27248 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
03-23 10:49:47.442 25860 27248 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:246)
03-23 10:49:47.442 25860 27248 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
03-23 10:49:47.442 25860 27248 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:923)
03-23 10:49:47.443 25860  6828 I Dialog  : mIsSamsungBasicInteraction = false, isMetaDataInActivity = false
03-23 10:49:47.444 25860  6828 I DecorView: [INFO] isPopOver=false, config=false
03-23 10:49:47.444 25860  6828 I DecorView: updateCaptionType >> DecorView@ab2242c[], isFloating=true, isApplication=true, hasWindowDecorCaption=false, hasWindowControllerCallback=false

```
Full logcat: 
[crash_when_tap_of_notif.txt](https://github.com/status-im/status-react/files/6188277/crash_when_tap_of_notif.txt)

**NOTE:** That second issue actually appears also when Notification appears on Android for the **sent** transaction. So to reproduce simply send TX and when Notification appears - tap it. No issue on iOS, only reproduced on Android.

**Issue 3** This is related to **Changes to iOS push notification** (notification should be received when a user joins a community). 
I'm not getting notification on iOS or Android, but doubt whether I check the correct scenario (communities are not very obvious so far, and there are many items reported in https://github.com/status-im/status-react/issues/11914).

**Reproduction:**
1) Create two new users: UserA (iOS device) and UserB (Android device)
2) Enabled notifications on both devices
3) UserA adds UserB in contacts
4) UserA creates Community with 'No requirement' membership (default)
5) In the newly created community invite UsetB: Comunity -> top-right `...`-> `View Profile` -> top-right `Share` -> select UserB from the list -> `Share`
6) UserB receives in 1-1 chat invitation.
7) UserA (iOS) put app on background
8) UserB -> 1-1 chat -> `View community` -> tap `Join`

**Actual result:** No notification on UserA side for new member joined the community
**Expected result:** Notification about new user joined the chat appears

The same behavior with community which 'Require approval' membership

**Comment by Serhy** [comment]
@cammellos in the last builds https://status-im-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-210324-114301-32cbf3-pr-universal.apk and https://i.diawi.com/LcPEHd on iOS and Android i'm getting this during onboarding on Notification screen when pressing any of two buttons:

Screenshot 2021-03-24 at 15 58 50

The same error when I press any button in account (I re-opened Status after account creation/recover and logged in but for instance in Profile there is no way to enter into any of views because the same error appears)

**Comment by cammellos** [comment]
@Serhy rebased against develop, the error should be gone now, thanks!

**Comment by Serhy** [comment]
@cammellos in the latest build https://status-im-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-210324-155514-c26836-pr-universal.apk - the issue 2 from https://github.com/status-im/status-react/pull/11835#issuecomment-804782233 still reproduced (so app crashes when tapping notification about Received/Sent transaction)

**Comment by Serhy** [comment]
Issue2 (https://github.com/status-im/status-react/pull/11835#issuecomment-804782233) reproduced in latest build (`80161a9`) https://status-im-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-210325-154233-80161a-pr-universal.apk

So app crashes when user taps upon Push Notification for received/sent transaction, - reproducible all the time.

**Comment by Serhy** [comment]
The only issue noticed is the regression that there is no unread indicator (and no message preview in Chats view) appears for audio and images messages on Android when 'Notifications' is enabled. 
**To reproduce:** 
1) Create new UserA and UserB 
2) UserA enabled notifications
3) UserA stays on the Chats main view
4) UserB sends in 1-1 chat (or Group chat) to UserA any Image (or Audio) message

**Comment by Serhy** [comment]
@cammellos with the last version, everything is fixed! :) Awesome! Thanks a lot!

**Pull request merged**
