### PR TITLE
adds numa dapp

### PR DESCRIPTION
**Pull request by hstove**
Hey Status team! I'm Hank, and I just launched [Numa](https://numaverse.com), a distributed social network built on Ethereum. You can learn more about it from this [FAQ](https://numaverse.com/messages/4).

I've followed the [instructions](https://wiki.status.im/Adding_your_DApp_to_Status) for how to add a dapp to Status, but let me know if I missed anything. It's fully tested on Ropsten (and mainnet), and you can view the Ropsten version at https://ropsten.numaverse.com . I linked to the mainnet version in this PR, because I wasn't sure which one I was supposed to. I can change that if need be.

Thanks for Status! I've been playing with it, and everything is really top notch. Amazing design, and very intuitive.

Let me know if you have any questions.

Thanks,
Hank

status: ready

<blockquote><div><strong><a href="https://ropsten.numaverse.com/">Numa: a distributed social network</a></strong></div><div>It's a social network that is run entirely on a blockchain, so no central entity owns your data. We use Ethereum smart contracts and IPFS to store data in a distributed way.</div></blockquote>

### CODE REVIEW

**Comment by chadyj** [comment]
Hey Hank,
Thanks for the pull request!

I checked out Numa and ran into a few problems with Status.

1. There were some responsive issues, for example, the text was cut off on the homepage.
img_2092

2. The login page was unresponsive
img_2093

3. This isn't technical feedback, but as a user I couldn't easily find out how to get started. I had to scroll a very long way to see the get started text at the bottom of the page.

I tested on Mainnet.

**Review by chadyj — CHANGES_REQUESTED** [review]
Hey Hank,
Thanks for the pull request!

I checked out Numa and ran into a few problems with Status.

1. There were some responsive issues, for example, the text was cut off on the homepage.
img_2092

2. The login page was unresponsive
img_2093

3. This isn't technical feedback, but as a user I couldn't easily find out how to get started. I had to scroll a very long way to see the get started text at the bottom of the page.

I tested on Mainnet.

**Review by andytudhope — CHANGES_REQUESTED** [review]
Same issues as Chad.

**Comment by flexsurfer** [comment]
@hstove thanks for contribution, let's close PR , feel free to reopen it or create new one, thanks

**Pull request closed without merging**
