### PR TITLE
Bring the seedphrase backup flow to the new settings #19554

### LINKED ISSUE #19554: Bring the seedphrase backup flow to the new settings
# Bug Report

## Problem 
[comment]: # (A problem description)
The user should be able to backup their seedphrase from the new settings. 

For now, it should be enough to show the old UI, but it should be accessible from the new settings.

#### Expected behavior
The user can backup the seedphrase from the new settings

#### Actual behavior
The user can backup the seedphrase only from the old settings

### PR DESCRIPTION
**Pull request by flexsurfer**
fixes #19554

### CODE REVIEW

**Review by mohsen-ghafouri — APPROVED** [review]

**Review by ibrkhalil — APPROVED** [review]

**Comment by yevh-berdnyk** [comment]
Failed e2e tests are not related to this PR, thanks!

**Comment by qoqobolo** [comment]
@flexsurfer two things to fix as discussed:

- [x]  `1` in legacy settings when recovery phrase is not backed up

Screenshot 2024-05-06 at 15 59 44


- [x]  "backup" instead of "back up" and "recovery phrase" instead of "seed phrase"

Screenshot 2024-05-06 at 15 58 56
Screenshot 2024-05-06 at 15 59 06

**Review by clauxx — APPROVED** [review]

**Comment by flexsurfer** [comment]
thanks @qoqobolo fixed

**Comment by qoqobolo** [comment]
Thanx for the fixes @flexsurfer
Found another issue on iOS: the `Next` button is hidden behind the keyboard when typing the seed phrase words.
When testnet mode is disabled, it's still only partially visible on some devices. 
PR vs nightly:



Screenshot 2024-05-07 at 11 43 26


Screenshot 2024-05-07 at 11 41 38

**Comment by flexsurfer** [comment]
thanks @qoqobolo  should be fixed

**Comment by qoqobolo** [comment]
Thank you @flexsurfer, PR can be merged.

**Pull request merged**
