### PR TITLE
Communities Sync

### PR DESCRIPTION
**Pull request by Samyoul**
Issue here : https://github.com/status-im/status-react/issues/12145
Code implemented here : https://github.com/status-im/status-go/pull/2253

Test branch for the purposes of running full e2e manual tests on community syncing functionality.

### CODE REVIEW

**Review by flexsurfer — APPROVED** [review]

**Comment by qoqobolo** [comment]
@Samyoul 

### ISSUE 1: Communities appear and disappear from the chat list on the home screen after pairing devices

**_Steps:_**
- Recover the same account on Device1 and Device2
- Sync devices
- On Device1 join/create a community (you can also join/create a community first and then sync devices > same behavior)
- Check the Home screen on both devices


https://user-images.githubusercontent.com/67952253/123432645-e199df80-d5ca-11eb-8d80-c67e6ac32096.MOV

**Comment by Samyoul** [comment]
Hey @qoqobolo , I've implemented a fix for this issue. Do I need to change the pipeline QA column?

**Comment by qoqobolo** [comment]
Hey @Samyoul, cool, I'll check it!

>Do I need to change the pipeline QA column?

Yes, you need to change the column as soon as there are changes in the PR that you think should be tested by QA. You can move it to `To test` for manual testing or to `E2Etests` to kick off the e2e test suit.
So we will definitely see the PR that needs to be tested, and will not miss anything.
Thank you!

**Comment by qoqobolo** [comment]
@Samyoul 

### ISSUE 2: Communities aren't synced on previously paired devices
If User syncs Device1 and Device2, joins a community on Device1, it won't be shown on Device2.
In addition, if User joins the same community (via `Home screen > + button > communities` or the invitation link) on Device2, it will disappear from the chat list on Device1. In this case, User needs to join it again (but after that it will disappear on Device2).

If User leaves the community from one of the paired devices, it will appear on the secondary device.

**_Steps:_**
1. Sync Device1 and Device2
2. Device3: create a community and post an invitation link in some public chat
3. Device1: request access to the community
4. Device3: approve the request
5. Device2: check the chat list 
**Expected result:** the community is presented in the list
**Actual result:** no community in the list
6. Device2: follow the same invitation link > tap `Join`
7. Check Device1

**Comment by churik** [comment]
@Samyoul 
can I ask you to test basic scenario before you move PR to  `TEST` column again (it is to pair 2 devices create community on 1 device and check that it appears on another)?
Emulators or real devices can be used (it doesn't matter actually).

It is time-saving action for all participants.
Thank you.

**Comment by churik** [comment]
@Samyoul 
can I ask you to test basic scenario until you move PR to  `TEST` column again (it is to pair 2 devices create community on 1 device and check that it appears on another)?

It is time-saving action for all parts.

**Comment by Samyoul** [comment]
Hey @qoqobolo and @churik, thank you and I apologise. I will do my due diligence here. I had rebased the latest `status-go` changes which also included changes to communities that effected syncing. I've resolved these problems, but I will do as much testing as I can. After I've done my own testing I will change this QA column.

**Comment by Samyoul** [comment]
@qoqobolo I've made the needed changes, and I've manually tested the functionality of this as much as I was able to. When you have availability would you be able to manually test this PR? Thank you very much.

**Comment by qoqobolo** [comment]
@Samyoul Issue 2 is still reproducible in the latest build `834630e`

**Comment by Samyoul** [comment]
@qoqobolo I've worked through this issue and it seems to be resolved in `status-go` e2e tests that replicate this issue

**Comment by qoqobolo** [comment]
@Samyoul thanks for the fix!

### ISSUE 3: When User leaves a community the changes are not reflected on the paired device. If leave it manually on the secondary device, it will reappear on the primary one

**_Reproduction:_**
1. Pair Device1 and Device2
2. Join or create a community
3. Leave this community on one of the devices

**Expected behavior:** the changes are reflected on the paired device (according to [the requirements](https://github.com/status-im/status-react/issues/12145#issue-900618181))
**Actual behavior:** if User leaves the community on Device1, it remains on Device2. If User then leaves the community on Device2, it reappears on Device1.

**OS:** Android, iOS

**Comment by Samyoul** [comment]
Hello @qoqobolo , I've made the changes needed for this issue. I've also gone through a lot of other scenarios to see if I can prevent any future issues from blocking this merge. I'm sorry about the issues so far.

**Comment by churik** [comment]
Tested (paring devices as a member of community) in offline/online mode:
- community appears on both devices during sync if it was added before or after pairing
- edited messages, reactions, images, audio messages are synced between devices
- leaving community is synced


Tested (paring devices as an admin of community) in offline/online mode:
- creating community
- editing community info
- creating / editing categories
- editing / deleting channels
- pinning different messages

Also rechecked that the existing pairing devices feature is working in the same way.
e2e failures are not related to PR.

**Devices:**
- IPhone 12 Mini (IOS 14)
- IPhone 7 (IOS 13)
- Xiaomi Mi Note 9 Pro (Android 10)

**Comment by Samyoul** [comment]
🎆 🎉 🍰 🎈 🥳 💥 🎺 🎶 🤘 Hooray

**Pull request merged**
