### PR TITLE
📶 [#11716] Implement new Connectivity dialogues and remove 'Offline' sn… 📶

### LINKED ISSUE #11716: Implement new Connectivity dialogues and remove 'Offline' snackbars
# Problem
Currently we display prominent 'Offline' snackbars whenever mail server connection is lost. This is misleading in setting the expectation that all messaging is offline when that's not the case. In addition the interface used to capture communication around network state is too prominent prominent compared to the kind of reliability that's experienced.

## Implementation

[Design here](https://www.figma.com/file/aS1ct66VQ6V0cio7vSqS8UoG/Chat?node-id=18667%3A61903)

* [ ] Remove 'offline' and 'waiting for wi-fi' snackbars, and replace them with appropriate icons situated in Chat top bars
* [ ] Tapping those icons should display a bottom sheet with appropriate content
* [ ] nodes offline: crossed out cloud icon
* [ ] completely offline: crossed out wireless icon, red colour
* [ ] on mobile connection and syncing: mobile device with signal
* [ ] on mobile connection and not syncing: crossed out mobile device with signal
* [ ] from the dialogue, tapping on `Settings` takes you to `Sync settings`

## Acceptance Criteria
The interface is implemented and tested. Please be extra mindful around triggering those states and only display the icons once we can reasonably predict that something is wrong, let's not be overzealous.

## Notes
I'm not 100% happy with the `on mobile connection and not syncing icon`, please let me know if you have a better idea that works at that size

## Future Steps
Work towards improving reliability and bandwidth consumption so this dialogue will be less and less necessary :crossed_fingers:

### PR DESCRIPTION
**Pull request by flexsurfer**
fixes #11716

* [x] Remove 'offline' and 'waiting for wi-fi' snackbars, and replace them with appropriate icons situated in Chat top bars
* [x] Tapping those icons should display a bottom sheet with appropriate content
* [x] nodes offline: crossed out cloud icon
* [x] completely offline: crossed out wireless icon, red colour
* [x] on mobile connection and syncing: mobile device with signal
* [x] on mobile connection and not syncing: crossed out mobile device with signal
* [x] from the dialogue, tapping on `Settings` takes you to `Sync settings`

### CODE REVIEW

**Review by cammellos — APPROVED** [review]

**Review by shivekkhurana — APPROVED** [review]
Looks good.

**Comment by churik** [comment]
@flexsurfer 
Please, accessibility-ids 🙏 
1) To connection-status icon. If it will correspond a name of icon, it would be great! (like "conn-offline", "conn-mobile-on", "conn-mobile-off"
image
2) To mobile data settings screen:
Android Emulator - my_emu_nex:5554 2021-02-12 13-52-35
3) To "Continue Settings" bottom sheet:
Android Emulator - my_emu_nex:5554 2021-02-12 13-54-11
4)To "Connection status" bottom sheet:
Android Emulator - my_emu_nex:5554 2021-02-12 13-55-15

**Comment by flexsurfer** [comment]
@churik  done

**Comment by qoqobolo** [comment]
@flexsurfer thanks for PR, it looks great for me!

But one question.
According to the description, the `Settings` button in the new dialogue takes us to `Sync settings`, but in fact, it takes to `Status nodes` settings.
Is it expected? 

Asking because actually, the `Settings` button is located in the `Status nodes` block in all dialogues (i.e. "completely offline", "on a mobile connection" status, etc). And it looks logical. But I would still expect to be redirected to `Sync settings`.


https://user-images.githubusercontent.com/67952253/107969163-ae599b00-6faf-11eb-8e90-a319cadc5fa7.mp4

**Comment by flexsurfer** [comment]
lets summon @errorists  :)

**Comment by flexsurfer** [comment]
oh thanks @qoqobolo so i've implemented not according to description? that's my mistake then

**Comment by flexsurfer** [comment]
thanks @qoqobolo , fixed

**Comment by churik** [comment]
this PR should wait for fix in e2e, I'm on it

**Comment by qoqobolo** [comment]
Tested (Google Pixel 2 Android 11, iPhone SE iOS 14):

- switching between networks while in foreground/background/app preview state/closed app/different tabs and views
- completely offline and on cellular network
- mobile data: sync/stop syncing
- Status nodes: disabled using Status nodes, invalid node (pop-up with error), combination with offline state and cellular network
- navigation from the dialogue to Sync settings
- switching between multiaccounts (settings are independent)
- creating new multiaccount offline
- dark mode
- settings are saved after re-login
- multiple quick tap on icons

**Comment by churik** [comment]
all e2e are fixed in #11753 
Ready to be merged.

**Pull request merged**
