### PR TITLE
update statusgo

### PR DESCRIPTION
**Pull request by cammellos**
[comment]: # (Please replace ... with your information. Remove < and >)
[comment]: # (To auto-close issue on merge, please insert the related issue number after # i.e fixes #566)

If you submit PR for issue with bounty then write here Fixes #NN where NN is issue number

*otherwise*

fixes #...

### Summary

[comment]: # (Summarise the problem and how the pull request solves it)
...

Documentation change PR (review please): https://github.com/status-im/status.im/pull/xxx

#### Platforms

- Android
- iOS
- macOS
- Linux
- Windows

##### Functional

- 1-1 chats
- public chats
- group chats
- wallet / transactions
- dapps / app browsing
- account recovery
- new account
- user profile updates
- networks
- mailservers
- fleet
- bootnodes

##### Non-functional

- battery performance
- CPU performance / speed of the app
- network consumption

### Steps to test

- Open Status
- ...
- Step 3, etc.

status: ready

### CODE REVIEW

**Comment by cammellos** [comment]
@Serhy do you know what's up with the test?
seems like there's not enough balance on the test account
cc @Samyoul

**Comment by Samyoul** [comment]
Hmm, there's a few of these that look like they could be caused by the new locking.

- (3) test_push_notification_1_1_chat, id: 6283
  - `Device 2: Push notification with text was not received`
- (5) test_offline_add_new_group_chat_member, id: 3998
  - `Device 1: Invite to group chat was not fetched from offline`
- (21) test_send_eth_in_1_1_chat_transaction_push, id: 6253
  - `Device 1: No message is shown after sending ETH in 1-1 chat for sender`
- (29) test_set_profile_picture, id: 6646
  - `Device 1: Profile picture was not updated in chat`
- (32) test_keycard_send_eth_in_1_1_chat, id: 6293
  - `Device 1: No message is shown after sending ETH in 1-1 chat for sender`

**Comment by Serhy** [comment]
> @Serhy do you know what's up with the test?
> seems like there's not enough balance on the test account
> cc @Samyoul

@cammellos almost all of those are valid fails. 
Assets are not fetched after account recover. I rechecked on real device build from this PR and after account recover balance of ETH and tokens are empty (on mainnet). `Scan tokens` helps in that case. 
And when sending transaction there is also no update of balance even after 20+ confirmations (TX is always Pending in Status).
And i've got indefinite spinner after pull-to-refresh of History in account...
This is in https://status-im-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-210409-130835-683f2f-pr-universal.apk build

**Comment by Serhy** [comment]
Let me grab the logs...

**Comment by cammellos** [comment]
sam did you rebase against latest develop?

**Comment by Serhy** [comment]
'Debug' logcat and geth.log are here just in case (Opened Status -> Wallet -> pull-to_refresh TX history and got indefinite spinner: [geth.log](https://github.com/status-im/status-react/files/6287334/geth.log) [Status.log](https://github.com/status-im/status-react/files/6287337/Status.log)

**Comment by Samyoul** [comment]
@cammellos https://github.com/status-im/status-go/pull/2181 has been rebased against `develop`

**Pull request closed without merging**
