### PR TITLE
Test Node Fleet Integration

### LINKED ISSUE #5901: Switch from Grove to Node Fleet RPC provider
status-go changes for https://github.com/status-im/infra-proxy/issues/10 
https://www.notion.so/Node-Fleet-1128f96fb65c8049ac7ad1c9c57e19ea

`grove` -> `nodefleet`:
* Update URLs in `default_networks.go`.
* tests
* Probably `EditNetworkViewPage.qml` and `AppMain.qml` in status-desktop and `config.cljs` in mobile should also be updated

>Client changes (status-go is the client)
Node Fleet as the primary provider
Infura as the secondary fallback option.
Grove as a backup if both Node Fleet and Infura fail.

### LINKED ISSUE #20970: Insufficient funds for gas error is thrown when building L1-L1 routes despite user has enough funds to cover fee
User has enough balance on L1 ETH to cover fee. Please try to test on Mainnet not testnet. Looks like it is more reproducible on Mainnet.

**Steps:** 

1. Try sending tokens / collectibles L1-L1
2. See if routes are build and user if able to perform transaction

**Actual result:** very often ``insufficient funds for gas``` error is thrown when building L1-L1 routes despite user has enough funds to cover fee

On the video below you can see me trying to build L1-L1 route in order to perform 0.01 ETH transaction. My balance is 0.015.

Finally (at 01:11) I was able to build routes and perform transaction. 

The final fee according to etherscan https://etherscan.io/tx/0xe38a312a2dab16212aae551a5831f8e06a2b9c95d6df7ae204bac0418b54e2f9 was just 0.000020496115248 ETH
($0.05) which means I had enough funds on balance cover fee and despite this fact I received errors multiple times. 

[logs (43).zip](https://github.com/user-attachments/files/16707770/logs.43.zip)

https://github.com/user-attachments/assets/3ecef998-cf35-4942-81d6-564b5a4064f7

### Additional Information

- Status version: release 2.30
- Operating System: Android, iOS

### PR DESCRIPTION
**Pull request by friofry**
This PR to integrate https://github.com/status-im/status-go/pull/5904

fixes status-im/status-go#5901
fixes https://github.com/status-im/status-mobile/issues/20970

see:

* https://www.notion.so/Node-Fleet-1128f96fb65c8049ac7ad1c9c57e19ea?pvs=4
* https://github.com/status-im/infra-proxy/issues/10#issuecomment-2386269111

### CODE REVIEW

**Comment by pavloburykh** [comment]
@friofry thank you for the PR. Please take a look at the issue. 

### ISSUE 1 Routes building while bridging from L1 to L2 results in error `abi: cannot use func as type ptr as argument`

**Steps:** 

1. Recover account which has some tokens on L1 (in my case Eth)
2. Try to bridge/perform transaction from L1 to L2
3. See if routes are built successfully 

**Actual result:** building route results in `abi: cannot use func as type ptr as argument` error

[logs (50).zip](https://github.com/user-attachments/files/17246021/logs.50.zip)
photo_2024-10-03 17 52 07

https://github.com/user-attachments/assets/8fd3c127-767e-403d-9744-dae548d837f7

**Comment by pavloburykh** [comment]
As a result of investigation it turned out [ISSUE 1](https://github.com/status-im/status-mobile/pull/21378#issuecomment-2391630385) is not PR related. Logged a separate issue https://github.com/status-im/status-mobile/issues/21385

@friofry current PR is ready for merge, thank you. 

Thanks to @VolodLytvynenko for taking part in testing this PR.

**Review by pavloburykh — APPROVED** [review]

**Comment by pavloburykh** [comment]
Closing this PR as go changes https://github.com/status-im/status-go/pull/5904 are already in mobile develop.

**Comment by friofry** [comment]
thank you!

**Pull request closed without merging**
