### PR TITLE
feat:enable pxClient in relay and lightclient (not to merge)

### PR DESCRIPTION
**Pull request by chaitanyaprem**
### Summary

This PR is not to be merged, but only to be used for dogfooding.
This is based on https://github.com/status-im/status-go/pull/5411 and https://github.com/status-im/status-go/pull/5350/

Affected areas
LightMode/LightClient peer connectivity
Enhance relay peer connectivity

### LightClient dogfooding

To enable light-client, go to Profile --> Advanced and select "Light Client". This will require an app restart.

Dogfooding steps and things to look for in lightClient:

-  Login normally, and make sure you enable Node Management and Debug in Advanced Settings.
-  Make sure you got some peers connected in Node Management tab
-  Run tests by being part of community , 1:1 chats, private group chats etc
-  Disconnect from the internet, wait until the peer count goes to 0.
-  Connect to the internet, You should reconnect to some peers in sometime. (Note that it takes some time for peers to be connected - this needs fixing)
-  Test reception of messages on 1:1 chat, groups and community
-  Leave it running and ensure no issues in send/receive messages

### Relay dogfooding

- Login normally, and make sure you enable Node Management and Debug in Advanced Settings.
- Mane sure you got some peers connected in Node Management tab
- Run tests by being part of community , 1:1 chats, private group chats etc
- Disconnect from the internet, wait until the peer count goes to 0.
- Connect to the internet, You should reconnect to some peers in sometime.
- Test reception of messages on 1:1 chat, groups and community
- Leave it running and ensure no issues in send/receive messages
- The peer count should increase gradually over a period of time beyond 15/20 peers.

##### Non-functional

- network consumption in relay mode

status: wip

### CODE REVIEW

**Comment by pavloburykh** [comment]
Hey @chaitanyaprem! 

Recent e2e run has identified crash during [recovering](https://app.eu-central-1.saucelabs.com/tests/42760d4a0cc24350bd232ed406b35109?auth=871966bae5708ea4633194b8f82b06b9#263) of multiaccount via seedphrase. 

Could you please check get log and see if there are any related errors? Thank you!

[test_restore_multiaccount_with_waku_backup_remove_switch_geth1.log.zip](https://github.com/user-attachments/files/16009453/test_restore_multiaccount_with_waku_backup_remove_switch_geth1.log.zip)

**Comment by chaitanyaprem** [comment]
> Hey @chaitanyaprem!
> 
> Recent e2e run has identified crash during [recovering](https://app.eu-central-1.saucelabs.com/tests/42760d4a0cc24350bd232ed406b35109?auth=871966bae5708ea4633194b8f82b06b9#263) of multiaccount via seedphrase.
> 
> Could you please check get log and see if there are any related errors? Thank you!
> 
> [test_restore_multiaccount_with_waku_backup_remove_switch_geth1.log.zip](https://github.com/user-attachments/files/16009453/test_restore_multiaccount_with_waku_backup_remove_switch_geth1.log.zip)

Nothing in the log points to anything obvious. Can we get console logs or any other app logs...maybe there is a stacktrace there that can indicate where the crash could be?

**Comment by pavloburykh** [comment]
> Nothing in the log points to anything obvious. Can we get console logs or any other app logs...maybe there is a stacktrace there that can indicate where the crash could be?

we also have logcat 
[logcat (9).log.zip](https://github.com/user-attachments/files/16009910/logcat.9.log.zip)

**Comment by chaitanyaprem** [comment]
> > Nothing in the log points to anything obvious. Can we get console logs or any other app logs...maybe there is a stacktrace there that can indicate where the crash could be?
> 
> we also have logcat [logcat (9).log.zip](https://github.com/user-attachments/files/16009910/logcat.9.log.zip)

Nothing i can find wrt stacktrace. Maybe @cammellos has some idea what could be the reason for crash.

**Comment by cammellos** [comment]
@chaitanyaprem 

```
06-26 16:08:31.096  7963     0 E Go      : panic: enode: can't sign record: record bigger than 300 bytes
06-26 16:08:31.096  7963     0 E Go      : 
06-26 16:08:31.096  7963     0 E Go      : goroutine 7296 [running]:
06-26 16:08:31.096  7963  8282 E GoLog   : panic: enode: can't sign record: record bigger than 300 bytes
06-26 16:08:31.096  7963     0 E Go      : github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/p2p/enode.(*LocalNode).sign(0xc000d58200)
06-26 16:08:31.096  7963     0 E Go      : 	github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/p2p/enode/localnode.go:310 +0x51f
06-26 16:08:31.096  7963     0 E Go      : github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/p2p/enode.(*LocalNode).Node(0xc000d58200)
06-26 16:08:31.096  7963     0 E Go      : 	github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/p2p/enode/localnode.go:122 +0x172
06-26 16:08:31.096  7963     0 E Go      : github.com/status-im/status-go/vendor/github.com/waku-org/go-discover/discover.(*UDPv5).Self(...)
06-26 16:08:31.096  7963     0 E Go      : 	github.com/status-im/status-go/vendor/github.com/waku-org/go-discover/discover/v5_udp.go:178
06-26 16:08:31.097  7963     0 E Go      : github.com/status-im/status-go/vendor/github.com/waku-org/go-discover/discover.(*UDPv5).lookupWorker(0xc001c88000, 0xc001fbd8c0, {0xdb, 0x8d, 0x29, 0x78, 0x74, 0x69, 0xe5, 0x70, ...})
06-26 16:08:31.097  7963     0 E Go      : 	github.com/status-im/status-go/vendor/github.com/waku-org/go-discover/discover/v5_udp.go:313 +0x1da
06-26 16:08:31.097  7963     0 E Go      : github.com/status-im/status-go/vendor/github.com/waku-org/go-discover/discover.(*UDPv5).newRandomLookup.(*UDPv5).newLookup.func1(0xb7ff1f7a1cacdddb?)
06-26 16:08:31.097  7963     0 E Go      : 	github.com/status-im/status-go/vendor/github.com/waku-org/go-discover/discover/v5_udp.go:296 +0x2e
06-26 16:08:31.097  7963     0 E Go      : github.com/status-im/status-go/vendor/github.com/waku-org/go-discover/discover.(*lookup).query(0xc0015126c0, 0xc001fbd8c0, 0xc001d0cfb0?)
06-26 16:08:31.097  7963     0 E Go      : 	github.com/status-im/status-go/vendor/github.com/waku-org/go-discover/discover/lookup.go:144 +0xaf
06-26 16:08:31.097  7963     0 E Go      : created by github.com/status-im/status-go/vendor/github.com/waku-org/go-discover/discover.(*lookup).startQueries in goroutine 1849
06-26 16:08:31.097  7963     0 E Go      : 	github.com/status-im/status-go/vendor/github.com/waku-org/go-discover/discover/lookup.go:126 +0x225
06-26 16:08:31.310  8438  8438 W libc    : Access denied finding property "ro.debuggable"

```
If you search for `status-go` in the logs (logcat, since panics go to stdout), you are able to check.
When the app crashes, it means status-go paniced, and those don't go in `geth.log`

**Comment by chaitanyaprem** [comment]
> @chaitanyaprem
> 
> ```
> 06-26 16:08:31.096  7963     0 E Go      : panic: enode: can't sign record: record bigger than 300 bytes
> 06-26 16:08:31.096  7963     0 E Go      : 
> 06-26 16:08:31.096  7963     0 E Go      : goroutine 7296 [running]:
> 06-26 16:08:31.096  7963  8282 E GoLog   : panic: enode: can't sign record: record bigger than 300 bytes
> 06-26 16:08:31.096  7963     0 E Go      : github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/p2p/enode.(*LocalNode).sign(0xc000d58200)
> 06-26 16:08:31.096  7963     0 E Go      : 	github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/p2p/enode/localnode.go:310 +0x51f
> 06-26 16:08:31.096  7963     0 E Go      : github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/p2p/enode.(*LocalNode).Node(0xc000d58200)
> 06-26 16:08:31.096  7963     0 E Go      : 	github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/p2p/enode/localnode.go:122 +0x172
> 06-26 16:08:31.096  7963     0 E Go      : github.com/status-im/status-go/vendor/github.com/waku-org/go-discover/discover.(*UDPv5).Self(...)
> 06-26 16:08:31.096  7963     0 E Go      : 	github.com/status-im/status-go/vendor/github.com/waku-org/go-discover/discover/v5_udp.go:178
> 06-26 16:08:31.097  7963     0 E Go      : github.com/status-im/status-go/vendor/github.com/waku-org/go-discover/discover.(*UDPv5).lookupWorker(0xc001c88000, 0xc001fbd8c0, {0xdb, 0x8d, 0x29, 0x78, 0x74, 0x69, 0xe5, 0x70, ...})
> 06-26 16:08:31.097  7963     0 E Go      : 	github.com/status-im/status-go/vendor/github.com/waku-org/go-discover/discover/v5_udp.go:313 +0x1da
> 06-26 16:08:31.097  7963     0 E Go      : github.com/status-im/status-go/vendor/github.com/waku-org/go-discover/discover.(*UDPv5).newRandomLookup.(*UDPv5).newLookup.func1(0xb7ff1f7a1cacdddb?)
> 06-26 16:08:31.097  7963     0 E Go      : 	github.com/status-im/status-go/vendor/github.com/waku-org/go-discover/discover/v5_udp.go:296 +0x2e
> 06-26 16:08:31.097  7963     0 E Go      : github.com/status-im/status-go/vendor/github.com/waku-org/go-discover/discover.(*lookup).query(0xc0015126c0, 0xc001fbd8c0, 0xc001d0cfb0?)
> 06-26 16:08:31.097  7963     0 E Go      : 	github.com/status-im/status-go/vendor/github.com/waku-org/go-discover/discover/lookup.go:144 +0xaf
> 06-26 16:08:31.097  7963     0 E Go      : created by github.com/status-im/status-go/vendor/github.com/waku-org/go-discover/discover.(*lookup).startQueries in goroutine 1849
> 06-26 16:08:31.097  7963     0 E Go      : 	github.com/status-im/status-go/vendor/github.com/waku-org/go-discover/discover/lookup.go:126 +0x225
> 06-26 16:08:31.310  8438  8438 W libc    : Access denied finding property "ro.debuggable"
> ```
> 
> If you search for `status-go` in the logs (logcat, since panics go to stdout), you are able to check. When the app crashes, it means status-go paniced, and those don't go in `geth.log`

Ah, thanks! Will keep that in mind. 
 
We have also observed this crash and fix is in progress @pavloburykh . 
https://github.com/waku-org/go-waku/issues/1138

**Comment by pavloburykh** [comment]
> We have also observed this crash and fix is in progress @pavloburykh .
> [waku-org/go-waku#1138](https://github.com/waku-org/go-waku/issues/1138)

Thank you @cammellos, @chaitanyaprem! So, do I understand correctly that this crash is not related to current PR?

**Comment by chaitanyaprem** [comment]
> > We have also observed this crash and fix is in progress @pavloburykh .
> > [waku-org/go-waku#1138](https://github.com/waku-org/go-waku/issues/1138)
> 
> Thank you @cammellos, @chaitanyaprem! So, do I understand correctly that this crash is not related to current PR?

It is not directly related to the current PR, but this could be due to one of the fixes done earlier in go-waku https://github.com/waku-org/go-waku/pull/1129 which is pulled into this PR indirectly.

**Comment by chaitanyaprem** [comment]
@pavloburykh , pushed changes to include crash fix. Maybe we can run tests to see if issue happens.

**Comment by pavloburykh** [comment]
> @pavloburykh , pushed changes to include crash fix. Maybe we can run tests to see if issue happens.

@chaitanyaprem looks like the fix has totally broke everything)))

Most of the tests have failed in recent run. 

The reason of failures is crash after [creating](https://app.eu-central-1.saucelabs.com/tests/916f7be4cf604206bc35678c9b40a3d4?auth=4bca075721918fd55156b328787a7369#29) multiaccount. 

Here is the logcat 
[logcat (10).log.zip](https://github.com/user-attachments/files/16013515/logcat.10.log.zip)

**Comment by chaitanyaprem** [comment]
> > @pavloburykh , pushed changes to include crash fix. Maybe we can run tests to see if issue happens.
> 
> @chaitanyaprem looks like the fix has totally broke everything)))
> 
> Most of the tests have failed in recent run.
> 
> The reason of failures is crash after [creating](https://app.eu-central-1.saucelabs.com/tests/916f7be4cf604206bc35678c9b40a3d4?auth=4bca075721918fd55156b328787a7369#29) multiaccount.
> 
> Here is the logcat [logcat (10).log.zip](https://github.com/user-attachments/files/16013515/logcat.10.log.zip)

Looks that way, reverting the fix for now.

**Comment by pavloburykh** [comment]
> Looks that way, reverting the fix for now.

@chaitanyaprem Please, let know when you revert changes. I will re-run e2e, just in case.

**Comment by chaitanyaprem** [comment]
> > Looks that way, reverting the fix for now.
> 
> @chaitanyaprem Please, let know when you revert changes. I will re-run e2e, just in case.

Already reverted the fix.

**Comment by pavloburykh** [comment]
@chaitanyaprem thank you for the PR. No other issues from my side

**Comment by chaitanyaprem** [comment]
Closing as relevant dogfooding and tests are executed.

**Pull request closed without merging**
