### PR TITLE
adding Civitas DApp

### PR DESCRIPTION
**Pull request by leonprou**
### Summary:

Adding Civitas Dapp of the CLN network to the status DApp list.

- [x] Has it been tested in Status? Mainnet and testnets?
- [x] Are there any responsive layout issues?
- [x] Are there any technical issues?
- [x] Does the Dapp work fully over HTTPS? - it is but Status shows the connection isn't secured - https://github.com/status-im/status-react/issues/5327.
- [x] Is the code open source? If so, please link to the repo - https://github.com/colucom/CLN-community-app.

status: ready

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/colucom/CLN-community-app">colucom/CLN-community-app</a></strong></div><div>Contribute to CLN-community-app development by creating an account on GitHub.</div></blockquote>

### CODE REVIEW

**Comment by ghost** [comment]
Hey @leonprou, and thank you so much for making your first pull request in status-react! :heart: Please help us make your experience better by filling out this brief questionnaire https://goo.gl/forms/uWqNcVpVz7OIopXg2

<blockquote><div> Google Docs</div><div><strong><a href="https://docs.google.com/forms/d/e/1FAIpQLSewRMgMD6FLe9yO7oCipVn7YTn1HboJc4ZDJ_Va_BsDAemQwQ/viewform?usp=send_form&usp=embed_facebook">Status 1st commit dev survey</a></strong></div><div>First of all thank you so much for taking the time to make your first foray into the world of Status. We want to make sure that your experience with building the future of the decentralized web with us is not only enjoyable but gives you real purpose.

 Please check out our wiki at https://wiki.status.im and our Dev forum at https://discuss.status.im for more in depth longform discussion -- You can also join our Riot at https://chat.status.im which has all of our developers to answer any pressing questions you may have.</div></blockquote>

**Review by andytudhope — APPROVED** [review]
It works well on mobile for me and is fairly easy to navigate. Can't do much in the DApp currently, but I hope that changes soon @leonprou?

**Comment by leonprou** [comment]
@antdanchenko thanks for the checks 😊 

Yeah, we're working on the Buy and Sell feature - https://github.com/colucom/CLN-community-app/tree/feature_buy_sell. Then we'll develop the issuance of community currencies.

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/colucom/CLN-community-app">colucom/CLN-community-app</a></strong></div><div>Contribute to CLN-community-app development by creating an account on GitHub.</div></blockquote>

**Review by rachelhamlin — APPROVED** [review]

**Comment by Serhy** [comment]
Hello, @leonprou. There is a conflict appeared, could you fix it please so we could merge?

**Comment by leonprou** [comment]
@Serhy solved the conflicts via rebase, waiting for tests now

**Comment by Serhy** [comment]
Thanks, @leonprou ! 
(Failed autotests are not part of this PR, - confirmed as knowns already having GH issue exist to be fixed)

**Pull request merged**
