### PR TITLE
remove message appearing animation

### PR DESCRIPTION
**Pull request by rasom**
Until messages appearing animation will be rewritten more efficiently better just to remove it from application.

status: ready

### CODE REVIEW

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/iMZNLy for branch PR-4331

<blockquote><div><strong><a href="https://i.diawi.com/iMZNLy">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/qYE64A for branch PR-4331

<blockquote><div><strong><a href="https://i.diawi.com/qYE64A">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/dhc3NP for branch PR-4331

<blockquote><div><strong><a href="https://i.diawi.com/dhc3NP">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/qCLyUB for branch PR-4331

<blockquote><div><strong><a href="https://i.diawi.com/qCLyUB">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Review by cammellos — APPROVED** [review]

**Review by janherich — APPROVED** [review]

**Review by yenda — APPROVED** [review]

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/uUejvY for branch PR-4331

<blockquote><div><strong><a href="https://i.diawi.com/uUejvY">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Pull request merged**
