### PR TITLE
kyber ui (image source support and placeholder color)

### PR DESCRIPTION
**Pull request by flexsurfer**
image
image
image

https://status-im.github.io/pluto/try.html?hash=QmXmnHLattP8XanJQ4qcUQm2cMADWTPdBNWMyxpvPxKpGN

### CODE REVIEW

**Review by jeluard — APPROVED** [review]

**Review by goranjovic — APPROVED** [review]

**Comment by asemiankevich** [comment]
@flexsurfer just checked this UI briefly:

1. UI does not fit the screen a bit (5.2")
2. Amount [Specify] placeholder is not fully visible
3. [Amount to receive] is neither dynamic nor editable (always 0)
4. [Sign to confirm] is not active
5. Assets selection is not cleared when i tap back (to main screen) and open this Kyber exchange screen again
6. The thing i can't repro now, but seen it once: when i selected assets to exchange and tapped [back] - i saw Onboarding screen again however i completed it before (using recovered account)

image

**Comment by flexsurfer** [comment]
thanks @asemiankevich 
1 - yeah good catch, maybe we need to add new scroll-view component
2 - oh Android 👍 
3-5 - not in the scope of this PR

**Comment by flexsurfer** [comment]
@asemiankevich fixed 1 and 2 in new extension, and added a new screen https://status-im.github.io/pluto/try.html?hash=QmXmnHLattP8XanJQ4qcUQm2cMADWTPdBNWMyxpvPxKpGN

<blockquote><div><strong><a href="https://status-im.github.io/pluto/index.html">Pluto · A grammar for data manipulation</a></strong></div><div>A grammar for data manipulation</div></blockquote>

**Comment by asemiankevich** [comment]
> @asemiankevich fixed 1 and 2 in new extension, and added a new screen https://status-im.github.io/pluto/try.html?hash=QmXmnHLattP8XanJQ4qcUQm2cMADWTPdBNWMyxpvPxKpGN
> 
> > **[Pluto · A grammar for data manipulation](https://status-im.github.io/pluto/index.html)**A grammar for data manipulation

```Errors
unknown-query:"wallet/tokens"
unknown-reference:{"value":"wallet/tokens","type":"query"}``` so can't install it. Anyway i am not blocking this PR , i was just curious how it looks like

<blockquote><img src="/pluto/img/favicon.png" width="48" align="right"><div><strong><a href="https://status-im.github.io/pluto/index.html">Pluto · A grammar for data manipulation</a></strong></div><div>A grammar for data manipulation</div></blockquote>

**Comment by rachelhamlin** [comment]
Looks great. @flexsurfer my suggested copy for the confirmation screen is:

"Check for traded assets in your wallet."

I see we also need to remove `<` back button from this screen and add `Back to wallet` link.

image

Plus add `Powered by Kyber Network` fine print to swap slides:

image

**Pull request merged**
