### PR TITLE
ci: upgrade CI hosts to Xcode 15.1

### PR DESCRIPTION
**Pull request by jakubgs**
Hosts are also upgrade to macOS 14.2.1.

- https://developer.apple.com/documentation/xcode-release-notes/xcode-15-release-notes
- https://developer.apple.com/documentation/xcode-release-notes/xcode-15_0_1-release-notes
- https://developer.apple.com/documentation/xcode-release-notes/xcode-15_1-release-notes

Infra change:

- [`infra-role-bootstrap-macos#8db6aa78`](https://github.com/status-im/infra-role-bootstrap-macos/commit/8db6aa78) - xcode: upgrade from 14.3 to 15.1

### CODE REVIEW

**Comment by jakubgs** [comment]
Something is not right:
```
clang: error: SDK does not contain 'libarclite' at the path '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/arc/libarclite_macosx.a'; try increasing the minimum deployment target
/tmp/nix-build-ios-deploy-1.11.0.drv-0/source/ios-deploy.xcodeproj: warning: The macOS deployment target 'MACOSX_DEPLOYMENT_TARGET' is set to 10.8, but the range of supported deployment target versions is 10.13 to 14.2.99. (in target 'ios-deploy' from project 'ios-deploy')
```
But appears to be only due to my attempt at removing `ios-deploy` from overlay, so I'll leave that be.

**Comment by jakubgs** [comment]
But it appears even without that change something is not quite right:
```
xcodebuild: error: Unable to find a destination matching the provided destination specifier:
	{ generic:1, platform:iOS }
Ineligible destinations for the "StatusImPR" scheme:
	{ platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any iOS Device, error:iOS 17.2 is not installed. To use with Xcode, first download and install the platform }
[22:54:04]: Exit status: 70
```
That's something new:
```
error:iOS 17.2 is not installed. To use with Xcode, first download and install the platform
```

**Comment by jakubgs** [comment]
It appears the new Xcode 15.1 does not provide iOS 17.2 platform by default:

image

Which means you have to start Xcode and click `Get` to download it. This is yet another example of how Apple is hostile to any kind of automation in infrastructure and loves forcing people to do things manually. What a garbage company.

**Comment by jakubgs** [comment]
I can actually download the iOS simulation runtime from Apple downloads as DMG, but how does one install it?

image

**Comment by jakubgs** [comment]
Okay, it appears this should be doable in CLI with `xcodebuild`:
```
 > xcodebuild --help 2>&1 | grep download
    -downloadAllPlatforms                                    download all platforms
    -downloadPlatform NAME                                   download the platform NAME
    -downloadAllPreviouslySelectedPlatforms                  download all previously selected platforms
```
https://developer.apple.com/documentation/xcode/installing-additional-simulator-runtimes

image

Which is nice, since I won't have to click buttons like a savage.

**Comment by jakubgs** [comment]
Success.

**Review by siddarthkay — APPROVED** [review]

**Comment by yakimant** [comment]
FYI there is a tool for xcode/runtimes installation:
https://github.com/XcodesOrg/xcodes

Might be interesting.

**Comment by jakubgs** [comment]
That's cute.

**Pull request merged**
