### PR TITLE
[#21573] Keycard - Sign up with a new Keycard 

### LINKED ISSUE #21573: Keycard - Sign up with a new Keycard
The user will be asked for an empty Keycard. New key pair will be generated on Keycard. App will derive chatkey  and grant the user access to associated content and ability to sign authorization requests and transactions on wallet accounts derived from key pair.

Figma: https://www.figma.com/design/YGm3igIOAcwMqUVJWCJ6f1/Keycard-UX?node-id=3-89231&t=OElozp386NzL1OzB-1

### PR DESCRIPTION
**Pull request by flexsurfer**
fixes #21573

### CODE REVIEW

**Review by Parveshdhull — APPROVED** [review]

**Comment by mariia-skrypnyk** [comment]
Hey @flexsurfer !

Thanks for your PR!

I found one issue with PIN code validation.
Please take a look!

**ISSUE 1: no PIN validation in case user enters wrong PIN**

**Precondition:** Keycard with a set PIN

**Steps:**

1) Install app
2) Go to Create user with a Keycard
3) Scan Keycard
4) Enter wrong PIN
5) Scan Keycard
6) Scan Keycard 2-3 times more and you will get locked card

**Actual result:**

no validation that PIN is incorrect

https://github.com/user-attachments/assets/6458cffa-630a-4e78-8a08-af8476826e3b

**Expected result:**

as a User I would like to see smth like this

Screenshot 2024-11-21 at 16 40 14

**Comment by flexsurfer** [comment]
thank you @mariia-skrypnyk should be fixed

**Comment by mariia-skrypnyk** [comment]
Hi @flexsurfer !

No text with number of attempts on both platforms.

Screenshot 2024-11-22 at 16 10 19

**Comment by flexsurfer** [comment]
> No text with number of attempts on both platforms.

i believe there is a separate bug which i can't reproduce :(

**Review by ilmotta — COMMENTED** [review]
Code wise PR LGTM. Thank you @flexsurfer 

@flexsurfer @mariia-skrypnyk, the following bug always happens to me in iPhone Max 14 Pro. Because of this bug I can't complete the journey. Please, have a look:

1. Factory reset keycard or use empty one.
2. Open Status > Create profile > Use Keycard
3. In the `Create profile on empty Keycard` screen, press `Scan Keycard`
4. In the `Keycard is empty` screen, press `Let's go!` to create a new profile.
5. Backup recovery phrase and continue.
6. Create pin
7. In the `Ready to add key pair to Keycard` screen, press `Ready to Scan`
8. Try to scan the keycard. Scanning never works in this step and then it always happens as in the video below, where we can see that after not being able to scan the card, when pressing again `Ready to Scan` the `Oops, this isn't a Keycard` screen immediately appears simultaneously with the pop-up `Ready to Scan` successful even though I didn't even had the time to scan the second time. Finally at the end of the video we see pressing `Try again` shows the `Keycard is not empty`.
9. After the above steps, I have to reset the card in the desktop app, but trying again leads to the same bug.

https://github.com/user-attachments/assets/783cefac-3bca-43b2-bb36-5e49990d9b67

**Comment by mariia-skrypnyk** [comment]
Hey @ilmotta @flexsurfer !

Very appreciate your help in testing!
Your steps are so detailed!

Oops issue was found before and reported here https://github.com/status-im/status-mobile/pull/21612#issuecomment-2485144840

@flexsurfer tried to fix it and it looked fine.

I see that it appears in the current PR again on both platforms.

I suppose the main reason of why you cannot finish the login is that the last scanning step on `Ready to add key pair to Keycard` needs more time. Unfortunately it not so quick as on `Create profile on empty Keycard` and takes 3-5 second to scan card without moving. If you move or take your card away and try again you will se Oops issue (which should not exist and should be fixed). 

@ilmotta please, let me know if not moving card and waiting 3-5 sec of scanning worked for you.
@flexsurfer please, look at the Oops issue once more. It appeared again.

**Comment by flexsurfer** [comment]
thank you @ilmotta  so i see the only on code issue in your comment, about ops screen, but it's tricky to find and fix, it's not easy to reproduce, other issues are mostly UX, which i pointed to @xAlisher right at the first time i saw figma. We're collecting data and then do all keycard commands in one go, so it make UI better if all go well, and worse if not, because you can get a state when only some command were done, and some not, and you need to go to another flow, actually your state is not implemented fully yet, there will be a button saing your card is not empty and you can now just sign in and go to sign in flow, so it will be better, for now i think we could merge this PR because there is no blockers and continue working on some followups

**Comment by mariia-skrypnyk** [comment]
Hey @flexsurfer .

Do not want to block this PR.
E2E are not related.
Oops issue will be created in a separate bug and fill free to merge!

**Comment by ilmotta** [comment]
> @ilmotta please, let me know if not moving card and waiting 3-5 sec of scanning worked for you.

@mariia-skrypnyk at the moment I can't reset keycard and I can't test keycard flows. I'm facing some serious limitations from my machines and environments and I don't have access to a machine with Windows, where my card reader actually works.

I would imagine most users would behave similarly as myself, but I dunno, I'm pretty sure I was holding the card pretty steady for many seconds as I usually do because the reader is very sensitive in my iPhone. Unless the UI provides the correct feedback at the right time, some users might be frustrated and not be able to sign-up.

@flexsurfer @mariia-skrypnyk It would be helpful to ask other CCs with iPhones to test the current implementation in `develop`. Gathering this early feedback before the release from our internal CCs can help us understand if the blocker I faced would be a problem to more external users.

**Pull request merged**
