### PR TITLE
don't move accepted invitations to activity center

### LINKED ISSUE #12190: Accepting inviation to group chat brings group chat to activity centre
# Bug Report
also reproducible on 1.13

## Problem 
Currently, if user requests  membership to group chat, chat won't appear in home screen.
When admin accepts invite, it will be shown for member in activity centre and if user open invite again, he will be redirected to group chat with previous message history.

#### Expected behavior
4) chat not will be moved to activity centre
5) will be redirected to group chat, can't re-request access as you've joined

#### Actual behavior
IMAGE 2021-06-03 14:14:12

### Reproduction

1) User A: create group chat, send link to it to any public chat
2) User B: tap on link, request access
3) User A: accept access
4) User B: go back to home screen, open activity centre
Chat will be in Activity centre
5) User A (Android only): tap on link second time

### Additional Information

- Status version: RC 1.14 
- Operating System: Android, iOS (only 4 step)

### PR DESCRIPTION
**Pull request by bitgamma**
Fixes #12190.

the behaviour described has been fixed (the chat is not moved to activity center), however you still need to go in the chat and tap "Join the group". Is this confirmation expected to be there or should it be automatic?

### CODE REVIEW

**Review by flexsurfer — APPROVED** [review]

**Comment by qoqobolo** [comment]
@bitgamma, thanks for the fix, works great!

Regarding your question, it would be really nice to have an automatic confirmation. The logic is that if I sent a request to join, then I already want to be a member, and additional confirmation (`Join` button) is not required in this case.

How would it be more convenient for you: fix it now or in a separate PR?

**Comment by bitgamma** [comment]
@qoqobolo I will try to make it as part of this PR then

**Comment by bitgamma** [comment]
@qoqobolo now the chat is automatically joined as soon as the invitation is received

**Comment by churik** [comment]
@bitgamma please, mind my commit while squashing. Thank you!

**Review by churik — APPROVED** [review]

**Comment by qoqobolo** [comment]
@bitgamma awesome, thanks!
No issues were found. PR can be merged.

**Pull request merged**
