### PR TITLE
Update `status-go` go `gaabbcbe5`.

### PR DESCRIPTION
**Pull request by mandrigin**
DiscV5 discovery protocol is controlled by the same config flag as
a regular discovery.
Should theoretically consume less energy and less CPU than the "normal" version.

Part of https://github.com/status-im/ideas/issues/83

status: ready

### CODE REVIEW

**Review by rasom — APPROVED** [review]

**Review by flexsurfer — APPROVED** [review]

**Review by yenda — APPROVED** [review]

**Comment by lukaszfryc** [comment]
I've used [Android Batterystats & Battery Historian](https://developer.android.com/studio/profile/battery-historian.html) to compare battery usage between this Android build and [latest nightly](http://artifacts.status.im:8081/artifactory/nightlies-local/im.status.ethereum-e9e145.apk).

I went through a typical user flow that lasted ~13 min: create new account, request faucet, start new chat, send and receive messages, receive ETH, create group chat, turn on airplane mode, send some messages, turn off airplane mode, receive group chat messages, send ETH, logout, login again, put the app in background for ~3 min. 

Here are some insights: 
1. The build shows "Messages connection problem" all the time. But despite this, messages can be send and received. Nightly build works fine.

2. This build stats:
- Battery percentage consumed: 0.48%
- Device estimated power use due to CPU usage: 0.59%
- Wifi data transferred: 6.24 MB total (1.84 MB received, 4.41 MB transmitted)

3. Latest nightly stats:
- Battery percentage consumed: 0.62%
- Device estimated power use due to CPU usage: 0.94%
- Wifi data transferred: 119.94 MB total (99.79 MB received, 20.15 MB transmitted)

@mandrigin is this reduction of data transferred related to "Messages connection problem"? Is it expected? It's probably the reason why the stats look better for this PR build vs nightly.

**Comment by lukaszfryc** [comment]
I also think we need to run much longer tests. I'm checking how we can use our end-end suite to simulate app usage on a real device and then gather the stats.

**Comment by mandrigin** [comment]
@lukaszfryc hmm, it is also whisper v5 vs whisper v6, that is why the data reduction and this "Messages connection problem". Can you also check a difference between this build and the BKK build?

**Comment by lukaszfryc** [comment]
@mandrigin good news :) Looks like battery consumption is indeed improved in comparison to BKK build. 

I've repeated the same test / experiment for BKK build 2 times. I consistently got following results:
- Battery percentage consumed: 1.52%
- Device estimated power use due to CPU usage: 2.95%
- Wifi data transferred: 10.85 MB total (9.87 MB received, 0.98 MB transmitted)
It's worth noting that I tried to use the BKK build less extensively than the PR-3533 build.

Still, I wonder why we are going to do with the "Message connection problem" that shows all the time in home and chat screens. How it's gonna be fixed?

**Comment by mandrigin** [comment]
@lukaszfryc great! 🎉 
regarding  "Message connection problem", it is very unlikely introduced by my change, but we can try bisecting is anything...

**Comment by mandrigin** [comment]
@lukaszfryc so, I made a  table, does that look correct?
```
|-----------------+---------------------+---------------------+-----------------------|
| /               | develop (whisperV5) | PR-3533 (whisperV6) | BKK build (whisperV6) |
|-----------------+---------------------+---------------------+-----------------------|
| Battery (total) |               0.62% |               0.48% |                 1.52% |
|-----------------+---------------------+---------------------+-----------------------|
| Battery (CPU)   |               0.94% |               0.59% |                 2.95% |
|-----------------+---------------------+---------------------+-----------------------|

```

**Comment by lukaszfryc** [comment]
@mandrigin based on the experiment described in this PR (~10 min of activity then 3 min in the background) - yes, it is correct :)

**Comment by jeluard** [comment]
Duplicated by #3480

**Pull request closed without merging**
