### PR TITLE
Added EasyTrade to DApps

### PR DESCRIPTION
**Pull request by dmf7z**
## Submiting dapp 
EasyTrade - [https://easytrade.io](https://easytrade.io)

### Has it been tested in Status? Mainnet and testnets?
Yes, it has been tested on Mainnet and testnets.

### Are there any responsive layout issues?
No.

### Are there any technical issues?
No.

### Does the Dapp work fully over HTTPS?
Yes, it does.

### Is the code open source? If so, please link to the repo
Yes, it is open source. Link: [https://github.com/dexdexplatform/dexdex-mono](https://github.com/dexdexplatform/dexdex-mono)

<blockquote><div><strong><a href="https://easytrade.io/">EasyTrade Beta</a></strong></div></blockquote>
<blockquote><div> GitHub</div><div><strong><a href="https://github.com/dexdexplatform/dexdex-mono">dexdexplatform/dexdex-mono</a></strong></div><div>dexdex-mono - Mono Repo for dexdex platform</div></blockquote>

### CODE REVIEW

**Comment by dmf7z** [comment]
@jeluard / @rachelhamlin, PR updated as there was a conflict with file `src/status_im/ui/screens/contacts/default_dapps.cljs`  because other dapp was merged.

**Review by rachelhamlin — APPROVED** [review]

**Comment by jeluard** [comment]
@dmf7z LGTM! Can you squash your commits ?

**Review by jeluard — APPROVED** [review]

**Comment by Serhy** [comment]
Hey @dmf7z, the app itself looks good withing status, there is a minor check left on how it looks with the integrated Dapp list. 
Could you squash commits so we are able to check it within new build before merge?

**Comment by dmf7z** [comment]
@rachelhamlin @Serhy commits squashed.

**Comment by jeluard** [comment]
@dmf7z Sorry it looks like there is a conflict now :( Do you mind taking a look at it?

**Comment by dmf7z** [comment]
@jeluard  merged ;)

**Comment by asemiankevich** [comment]
the dapp is shown in dapps list
i was able to perform transaction to this dapp
transaction is shown in history in correct form
not too many glitches and overlapps for this dapp from the first sight

looks good to me from QA perspective. 

Also see that some CI checks are failed, @dmf7z could you please take a look?

**Comment by jeluard** [comment]
@asemiankevich Build failure looks unrelated. I restarted the build process

**Comment by jeluard** [comment]
@asemiankevich Build went fine this time

**Comment by asemiankevich** [comment]
then signing commits is left :) @dmf7z

**Comment by jeluard** [comment]
@asemiankevich Core team signs commit. Was the test ok?

**Comment by asemiankevich** [comment]
yes, i stated this above

**Comment by jeluard** [comment]
I was waiting for my green label ;)

**Pull request merged**
