### PR TITLE
chore: fix some comments

### PR DESCRIPTION
**Pull request by longxiangqiao**
### Summary

fix some comments

...

Documentation change PR (review please): https://github.com/status-im/status.im/pull/xxx

#### Platforms

- Android
- iOS
- macOS
- Linux
- Windows

##### Functional

- 1-1 chats
- public chats
- group chats
- wallet / transactions
- dapps / app browsing
- account recovery
- new account
- user profile updates
- networks
- mailservers
- fleet
- bootnodes

##### Non-functional

- battery performance
- CPU performance / speed of the app
- network consumption

### Steps to test

- Open Status
- ...
- Step 3, etc.

### Before and after screenshots comparison

| Figma (if available) | iOS (if available)    | Android (if available)
| --- | --- | --- |
| Please embed Image/Video here of the before and after.  | Please embed Image/Video here of the before and after.  | Please embed Image/Video here of the before and after. |

status: ready

### CODE REVIEW

**Review by J-Son89 — APPROVED** [review]

**Review by churik — APPROVED** [review]

**Comment by churik** [comment]
Can skip manual qa or any testing phases, as fixes only comments.

**Comment by J-Son89** [comment]
Hey @longxiangqiao - can you please sign your commits and then rebase so we can get this merged?
Thanks!

**Comment by flexsurfer** [comment]
merged here https://github.com/status-im/status-mobile/pull/20410

**Comment by J-Son89** [comment]
thanks @flexsurfer! and thanks @longxiangqiao for your contribution. Feel free to reach out if you would like to take on some slightly larger issues 👍

**Pull request closed without merging**
