### PR TITLE
Fix the arithmetic function exposed by extensions

### PR DESCRIPTION
**Pull request by morelazers**

### CODE REVIEW

**Review by jeluard — APPROVED** [review]

**Review by rachelhamlin — APPROVED** [review]

**Review by flexsurfer — APPROVED** [review]

**Comment by jeluard** [comment]
@morelazers  Can you squash those 2 commits? Then I will merge this PR :)

**Comment by jeluard** [comment]
@flexsurfer Could you merge this one?

**Comment by morelazers** [comment]
@jeluard squashed

**Comment by jeluard** [comment]
Cool thanks! @flexsurfer Can you merge this one?

**Pull request merged**
