### PR TITLE
Fix JS lock files, switch to yarn

### LINKED ISSUE #2541: npm install breaks lock files across developer machines
### User Story

As a developer, I want to have consistent package lock files so that I don't go crazy.

### Description

*Type*: Bug

*Summary*: `npm` is kind of busted–running `npm install` on my machine modifies the existing `package-lock.json` file. This is wrong behavior, as I have not added/removed/upgraded any packages.

#### Expected behavior

Running `npm install` out of the box does not swap around the lock file.

#### Actual behavior

Probably depending on your machine, the lock file will change. They should call it `package-lock-except-for-a-few-packages.json`

Here is the diff that gets produced on my machine:

```
diff --git i/package-lock.json w/package-lock.json
index 207e0166..6fef781f 100644
--- i/package-lock.json
+++ w/package-lock.json
@@ -446,12 +446,56 @@
           "resolved": "https://registry.npmjs.org/babel-register/-/babel-register-6.26.0.tgz",
           "integrity": "sha1-btAhFz4vy0htestFxgCahW9kcHE=",
           "requires": {
+            "babel-core": "6.26.0",
             "babel-runtime": "6.26.0",
             "core-js": "2.5.1",
             "home-or-tmp": "2.0.0",
             "lodash": "4.17.4",
             "mkdirp": "0.5.1",
             "source-map-support": "0.4.18"
+          },
+          "dependencies": {
+            "babel-core": {
+              "version": "6.26.0",
+              "resolved": "https://registry.npmjs.org/babel-core/-/babel-core-6.26.0.tgz",
+              "integrity": "sha1-rzL3izGm/O8RnIew/Y2XU/A6C7g=",
+              "requires": {
+                "babel-code-frame": "6.26.0",
+                "babel-generator": "6.26.0",
+                "babel-helpers": "6.24.1",
+                "babel-messages": "6.23.0",
+                "babel-register": "6.26.0",
+                "babel-runtime": "6.26.0",
+                "babel-template": "6.26.0",
+                "babel-traverse": "6.26.0",
+                "babel-types": "6.26.0",
+                "babylon": "6.18.0",
+                "convert-source-map": "1.5.0",
+                "debug": "2.6.9",
+                "json5": "0.5.1",
+                "lodash": "4.17.4",
+                "minimatch": "3.0.4",
+                "path-is-absolute": "1.0.1",
+                "private": "0.1.8",
+                "slash": "1.0.0",
+                "source-map": "0.5.7"
+              }
+            },
+            "babel-generator": {
+              "version": "6.26.0",
+              "resolved": "https://registry.npmjs.org/babel-generator/-/babel-generator-6.26.0.tgz",
+              "integrity": "sha1-rBriAHC3n248odMmlhMFN3TyDcU=",
+              "requires": {
+                "babel-messages": "6.23.0",
+                "babel-runtime": "6.26.0",
+                "babel-types": "6.26.0",
+                "detect-indent": "4.0.0",
+                "jsesc": "1.3.0",
+                "lodash": "4.17.4",
+                "source-map": "0.5.7",
+                "trim-right": "1.0.1"
+              }
+            }
           }
         }
       }
@@ -7001,9 +7045,9 @@
       }
     },
     "realm": {
-      "version": "2.0.3",
-      "resolved": "https://registry.npmjs.org/realm/-/realm-2.0.3.tgz",
-      "integrity": "sha1-F+vG4qBx9AaFZxdeQ6bIrFfQaT0=",
+      "version": "2.0.7",
+      "resolved": "https://registry.npmjs.org/realm/-/realm-2.0.7.tgz",
+      "integrity": "sha1-1SbWxzksVklafHgASDwG61hcbdY=",
       "requires": {
         "command-line-args": "4.0.7",
         "decompress": "4.2.0",
```

Either someone forgot to update `package-lock.json` when adding/upgrading some packages, or I'm seeing the same old `npm` behavior I'm used to.

### Reproduction

For me it was checking out the repo (OS X), and running `npm install` out of the box.

### Solution

Here are some links I tracked down today:

* https://github.com/npm/npm/issues/17722
* https://github.com/npm/npm/issues/18135
* https://github.com/npm/npm/issues/18712
* https://stackoverflow.com/questions/45022048/why-does-npm-install-rewrite-package-lock-json

To fix this on other projects, I've found the easiest and cheapest thing to do was to just switch to Yarn:

* Takes about 15 minutes.
* Yarn caches your builds in `~/.yarn/cache`, so future `yarn install` runs are really fast (~1-2 seconds if you haven't changed your packages)
* The lock files don't change until you tell them to

There's a bit of an extra cost here, which is adding one more dependency (`brew install yarn`). After that it's smooth sailing though!

### Additional Information

* Operating System: OS X building

### PR DESCRIPTION
**Pull request by dbalatero**
Fixes #2541

### Summary:

There was a lot of funny interactions between `npm install`, and the `package-lock.json` file. `npm install` was modifying the lock file, and the `postinstall.sh` script was doing a bunch of extra weird stuff external to the lock file that it shouldn't be doing. As well, subsequent runs of `npm install` were not intelligently checking whether `node_modules` was up to date, and was doing a full rebuild, slowing down `scripts/setup`.

I am currently waiting for #2574 to land, so I can merge the setup script updates that I made in here with those changes, so this is pending that.

### Steps to test:

1. Check out this branch
2. Run `scripts/setup`
3. It should `yarn install` successfully

status: wip

### CODE REVIEW

**Comment by rasom** [comment]
Hi @dbalatero, thanks for contribution!

Switching to `yarn` also affects our jenkins pipeline so please add corresponding changes to
[Jenkinsfile](https://github.com/status-im/status-react/blob/develop/Jenkinsfile) and [Jenkinsfile.nightly](https://github.com/status-im/status-react/blob/develop/Jenkinsfile.nightly) because currently build fails with:
```
+ npm install

> StatusIm@0.0.1 preinstall /Users/jenkins/workspace/status-react/parametrized build
> node -e "if (process.env.npm_execpath.indexOf('yarn') === -1) { throw new Error('You must use Yarn to install, not NPM') }"

[eval]:1
if (process.env.npm_execpath.indexOf('yarn') === -1) { throw new Error('You must use Yarn to install, not NPM') }
                                                       ^

Error: You must use Yarn to install, not NPM
    at [eval]:1:62
    at ContextifyScript.Script.runInThisContext (vm.js:50:33)
    at Object.runInThisContext (vm.js:139:38)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:635:30)
    at evalScript (bootstrap_node.js:462:27)
    at startup (bootstrap_node.js:163:9)
    at bootstrap_node.js:608:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! StatusIm@0.0.1 preinstall: `node -e "if (process.env.npm_execpath.indexOf('yarn') === -1) { throw new Error('You must use Yarn to install, not NPM') }"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the StatusIm@0.0.1 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jenkins/.npm/_logs/2017-12-07T10_01_25_475Z-debug.log
```

**Review by rasom — CHANGES_REQUESTED** [review]
see comment above

**Comment by dbalatero** [comment]
@rasom Sounds good. The PR isn't ready to merge yet btw, still pending another. I'll update the build files.

Also another nudge on this ;) https://github.com/status-im/status-react/issues/2566 <-- surfacing CI builds to OSS contributors like me is a top priority for easier contribution

**Comment by jeluard** [comment]
@dbalatero #2574 has now been merged, is that the one you were waiting for?

**Comment by dbalatero** [comment]
Yes I'll be back from Hawaii Dec 20 and can address then!

**Comment by jeluard** [comment]
We might want to consider [turbo](https://medium.com/@ericsimons/introducing-turbo-5x-faster-than-yarn-npm-and-runs-natively-in-browser-cc2c39715403) too.

**Comment by oskarth** [comment]
Nice one @dbalatero! Switching to yarn would indeed make things easier for us. Would you mind rebasing on develop when you get back? Quite a lot of things have changed recently, most notably RN upgrade (which breaks a lot of npm stuff).

Also, do you think it is possible to gracefully introduce `yarn`? I.e. make it possible for Jenkins to do its current thing but local devs to use yarn, and then we can replace it in Jenkins once we know it is working?

**Comment by dbalatero** [comment]
@oskarth sure I'll rebase! However I'd like CI to match the dev environment, otherwise we'll end up with parallel worlds. I think changing both will be easy once yarn is in place, unless you see any specific pitfalls?

**Comment by oskarth** [comment]
> @oskarth sure I'll rebase! However I'd like CI to match the dev environment, otherwise we'll end up with parallel worlds. I think changing both will be easy once yarn is in place, unless you see any specific pitfalls?

Sure, that's fine by me as well. Are you able to change the things @rasom requested "coding blind" and we can paste build result here? It's not ideal but better than nothing right now. We have someone who is working on getting auth/Github to Jenkins setup.

**Comment by dbalatero** [comment]
@rasom @oskarth I have redone this PR as requested, and updated Jenkinsfile / nightly as well.

I'm hoping that `yarn install` will work on CI, but it's likely that the package isn't there. I'd like to open a new issue to convert Jenkins to use `scripts/setup` to pull in all dependencies, which will always ensure dependencies are on CI (and will force `scripts/setup` to stay up to date by virtue of CI exercising it).

**Comment by pablodip** [comment]
@dbalatero Here you go in case it helps: https://gist.github.com/dmitryn/0720acb5837fdae3c5fcc172890e3244

**Comment by rasom** [comment]
https://gist.github.com/rasom/a9d6c61a84a67acf29bdd6416052a284

So that's how it ends on jenkins

**Comment by rasom** [comment]
@dbalatero this usually means that we have some problems with `babel`'s deps. that's why we had them configured in `package.json` https://github.com/status-im/status-react/blob/develop/package.json#L16-L21

**Comment by rasom** [comment]
That's script which can be used to reproduce this error locally https://gist.github.com/rasom/603645bff40cfe5a0bb4c106a7e09946

**Comment by dbalatero** [comment]
@rasom thanks, i'll get on this! Oh and you have jenkins ✅ / ❌ status now, that's great!

**Comment by oskarth** [comment]
@dbalatero Any luck with this? Do you need something? Really yearning for some yarn :)

**Comment by dbalatero** [comment]
@oskarth Hey sorry! Been knee deep in work for my job. Planning on checking this out tomorrow. No reason to have it sitting here, especially if someone runs another npm install forcing me to do it all over again… ;)

**Comment by dbalatero** [comment]
@rasom @oskarth There's three issues I'm having now that I'm diving into this

1. I don't have Android build configured on my machine. This has been a pending todo for me for a bit, as it's been a PITA so far. Any tips? I'm on OS X. I'll take whatever the fastest way to nirvana is.

2. Your repro script has invalid Bash

```
yarn install \
[ -f node_modules/react-native/packager/src/JSTransformer/index.js ] && sed -i "" "s/301000/1201000/g" node_modules/react-native/packager/src/JSTransformer/index.js || echo "New packager"
 ```

specifically running something like `yarn install [ -f path/to/file.js ]` doesn't make sense. Did you mean to run something else?

3. I need to know what the error you're seeing is, so I can make sure I get the same error on my end, otherwise it's harder for me to repro if I don't know.

Thanks!

**Comment by oskarth** [comment]
@dbalatero Sorry for the slow replies, we are in the middle of a release and fixing critical bugs for this. Quick one re 2: I think this is just a copy paste / shell artifact. It should be something like:

```
yarn install

[ -f node_modules/react-native/packager/src/JSTransformer/index.js ] && sed -i "" "s/301000/1201000/g" node_modules/react-native/packager/src/JSTransformer/index.js || echo "New packager"
```

Where the second line is/was used to seamlessly shift from old RN version to new one.

**Comment by oskarth** [comment]
> 1

Where do you get stuck in specifically? https://wiki.status.im/Building_Status We have some new devs who joined and they also had issues, so getting better build instructions is definitely something we want. You can also create a new issue for this for better visibility.

> 3

What more logs do you need than https://gist.github.com/rasom/a9d6c61a84a67acf29bdd6416052a284? This is the full Jenkins output as far as I can tell. @rasom's repro is literally just our Jenkinsfile (in root dir, slightly different pipelines but essentially same build steps) but without the Groovy syntax (`sh '...'` etc).

**Comment by dbalatero** [comment]
Ack sorry, I totally forgot/missed that Gist link to the logs. Sorry about
that.

I think I need to just hit my head against the wall for Android SDK. If I
get a good solution I'll code up a script or at least document it. Also you
should ask your new devs do that as well, since they freshly experienced
the pain :)

**Comment by jeluard** [comment]
@dbalatero Do you still have issues with Android?

**Comment by dbalatero** [comment]
Hey @jeluard sorry for the delay. I've been pretty sick and unable to get any energy after work to do anything. Should we close this PR for now? I feel like it will take me a little while to get back to strength.

**Comment by jeluard** [comment]
@dbalatero Ok no problem!
Could you quickly summarize the state of this PR?
How far are we from having yarn support?

**Comment by dbalatero** [comment]
@jeluard currently needs:

* fixing the Jenkins build
* any changes to `package.json` since this PR was opened need to probably propagate over… which means the work might have to be restarted :(

Let me see if I can quickly re-run this against the latest package.json. That won't be a ton of work… getting the Android build going was the larger pain I was feeling.

**Comment by goranjovic** [comment]
@dbalatero What's the status with this PR, it's been open for a while now?

**Comment by flexsurfer** [comment]
@dbalatero can we close this PR?

**Comment by flexsurfer** [comment]
@dbalatero let's close it , feel free to reopen or create new one ,thanks!

**Pull request closed without merging**
