### PR TITLE
Validate community channel names

### LINKED ISSUE #12010: Naming validation for communities
As a user
I want to limit the number of characters available when creating community names/channel names/channel categories
So that the UI is not cluttered

### Description

Community names should allow anything and just limit to 30 characters

Channel names should allow anything besides:
 - spaces, they should be replaced as the user types with dashes `-`
 - Uppercase letter, they should be replaced by the lowercase counterpart as the user types
 - limit to 30 characters

If categories are also implemented, they should have the same limitations as channel names, if they are not implemented, this is out of scope for this taks.

### PR DESCRIPTION
**Pull request by cammellos**
Fixes: #12010

### CODE REVIEW

**Review by flexsurfer — APPROVED** [review]

**Comment by flexsurfer** [comment]
still relevant ?

**Review by shivekkhurana — APPROVED** [review]

**Comment by flexsurfer** [comment]
@cammellos  still relevant ?

**Comment by du82** [comment]
It's unnecessary and a bad idea. Why limit what people can name community channels? Lets not be discord where it's all lowercase and with dashes instead of spaces.

If a community thinks having crazy unicode characters is a good idea, let them. Don't limit what everyone can do because a few people think it doesn't look good.

**Comment by flexsurfer** [comment]
i guess we can close it for now

**Pull request closed without merging**
