### PR TITLE
Make profile photos visible by default

### LINKED ISSUE #16060: Make profile photos visible by default
There is a setting in the application to enable/disable showing profile picture to all other users by default
and another similar setting to enable/disable showing profile pictures from everyone else.

Currently both of these are disabled by default. There is a request to enable them by default

cc @churik

### PR DESCRIPTION
**Pull request by alwx**
Fixes https://github.com/status-im/status-mobile/issues/16060
Also requires https://github.com/status-im/status-go/pull/3553

#### Platforms

- Android
- iOS

status: ready

### CODE REVIEW

**Review by rasom — APPROVED** [review]

**Review by ilmotta — APPROVED** [review]

**Comment by VladimrLitvinenko** [comment]
Hi @alwx  Could you please rebase the PR and resolve existing conflicts? Thanx

**Comment by VolodLytvynenko** [comment]
Hi @alwx. Thank you for your work. PR is tested and ready to be merged

**Comment by pavloburykh** [comment]
@alwx hi! Could we merge this one please? As it has been tested last week. If there will be any conflicts after rebasing  please request another QA test to make sure there is no regression after resolving. Thanx!

**Comment by alwx** [comment]
Will update and merge this and the golang counterpart today/tomorrow!

**Pull request merged**
