### PR TITLE
fix reloading of views

### PR DESCRIPTION
**Pull request by rasom**
status: ready

### CODE REVIEW

**Review by janherich — APPROVED** [review]

**Review by flexsurfer — APPROVED** [review]

**Comment by lukaszfryc** [comment]
Let me check e2e as there was 14 failures for some reason

**Comment by rasom** [comment]
@lukaszfryc sure

**Comment by rasom** [comment]
yep mobile version of app looks broken

**Comment by lukaszfryc** [comment]
@rasom yes, for sure I can't use create or recover buttons on iOS.

**Comment by lukaszfryc** [comment]
@rasom I noticed https://github.com/status-im/status-react/issues/6121 on Android. Would be great to fix it. At least the part with not showing the "Add to contacts" button.

**Comment by rasom** [comment]
but that's a separate issue, not for this PR for sure

**Comment by rasom** [comment]
whatever, i'm checking

**Comment by lukaszfryc** [comment]
@rasom as far as I tested, this issue appears only in this PR. Are you with introducing it to nightlies? :)

**Comment by rasom** [comment]
@lukaszfryc can you check it again please?

**Comment by lukaszfryc** [comment]
@rasom It works good for me. But, I'd wait for new e2e test results to make sure they pass. The last tests failed but I can't reproduce those issues https://github.com/status-im/status-react/pull/6118#issuecomment-426774810

**Comment by lukaszfryc** [comment]
I just scheduled them.

**Comment by rasom** [comment]
ok

**Comment by lukaszfryc** [comment]
@rasom looks good, feel free to merge!

**Pull request merged**
