### PR TITLE
fix Unable to tap on chats/channels after opening profile link

### LINKED ISSUE #21065: Unable to tap on chats/channels after opening profile link from chat or after opening group details
# Bug Report

### Reproduction
1. Open a chat and send a link to your profile.
2. Tap the link to open your profile.
3. Return to the Messages screen.
4. Attempt to tap on any other chat or community channel.

#### Expected behavior
Chats and community channels are not tappable. The user is unable to open any chat or community channel.

#### Actual behavior
Chats and community channels are not tappable. The user is unable to open any chat or community channel.

https://github.com/user-attachments/assets/dcf87ec5-6c45-45b8-84bc-d32ed4db5b68

### Additional Information
- Status version: release
- Operating System: Android, iOS

### PR DESCRIPTION
**Pull request by Parveshdhull**
fixes https://github.com/status-im/status-mobile/issues/21065

### Summary

We need to ensure that the chat is properly closed when popping to the root. This was not happening previously because, for universal links, we were directly calling the `pop-to-root-fx` instead of the `pop-to-root` event, which is responsible for closing the chat, as mentioned in the [comment](https://github.com/status-im/status-mobile/pull/21142#discussion_r1735986515).

status: ready

### CODE REVIEW

**Review by mohsen-ghafouri — APPROVED** [review]
🙏

**Review by flexsurfer — APPROVED** [review]

**Comment by pavloburykh** [comment]
Hey @Parveshdhull! Thanks for the PR. Initial issue described [here](https://github.com/status-im/status-mobile/issues/21065) is fixed. 

Although scenario pointed out by Tetiana [here](https://github.com/status-im/status-mobile/issues/21065#issuecomment-2485564448) is still reproducible and this is IOS specific. See the details below. 

### ISSUE 1 Cannot enter chats after closing Group details by swipe (IOS only)

reproducing on iPhone 15, IOS 17.6.1

**Steps:** 

1. Open a group chat
2. Go to Group details
3. Close Group details by swiping screen to the right
4. Close goup chat
5. Try to enter any chat from the list

**Actual result:** cannot enter any chat from the list until relogin. 


Uploading telegram-cloud-document-2-5328186932490951334.mp4…

**Comment by ulisesmac** [comment]
@Parveshdhull 

The issue @pavloburykh needs to properly clean the navigation state when we navigate back.

Since we don't have a way to properly solve this and given that the navigation between chats by pressing a channel text (e.g. #cats) is broken, I marked the issue as blocked.

**Comment by Parveshdhull** [comment]
> Group details by swipe (IOS only)

Thank you @pavloburykh for testing the PR and sharing reproduction step. Issue should be fixed now.

**Comment by pavloburykh** [comment]
> given that the navigation between chats by pressing a channel text (e.g. #cats) is broken

@ulisesmac can you expand on this please? Navigation between channels in community using hashtag is not broken. See the video below.


https://github.com/user-attachments/assets/2e1fd05c-6a7e-4833-8c5d-3cab9876d7f2

**Comment by pavloburykh** [comment]
> > Group details by swipe (IOS only)
> 
> Thank you @pavloburykh for testing the PR and sharing reproduction step. Issue should be fixed now.

thanks a lot @Parveshdhull! I will check tomorrow morning.

**Comment by Parveshdhull** [comment]
> @Parveshdhull
> 
> The issue @pavloburykh needs to properly clean the navigation state when we navigate back.
> 
> Since we don't have a way to properly solve this and given that the navigation between chats by pressing a channel text (e.g. #cats) is broken, I marked the issue as blocked.

Thank you @ulisesmac for checking out the PR. Please can you explain, what the issue with navigation state while using the current solution?

> given that the navigation between chats by pressing a channel text (e.g. #cats) is broken

That's separate issue(if exists), we can look into that later. But current PR should fix both issues mentioned in https://github.com/status-im/status-mobile/issues/21065

**Comment by ulisesmac** [comment]
> > given that the navigation between chats by pressing a channel text (e.g. #cats) is broken
> 
> @ulisesmac can you expand on this please? Navigation between channels in community using hashtag is not broken. See the video below.



@pavloburykh It's broken because the history is not preserved, we don't push a new screen, we just update the shown content. if you navigate through multiple channels and then go back, none of those will appear again.

**Comment by ulisesmac** [comment]
> > @Parveshdhull
> > The issue @pavloburykh needs to properly clean the navigation state when we navigate back.
> > Since we don't have a way to properly solve this and given that the navigation between chats by pressing a channel text (e.g. #cats) is broken, I marked the issue as blocked.
> 
> Thank you @ulisesmac for checking out the PR. Please can you explain, what the issue with navigation state while using the current solution?
> 
> > given that the navigation between chats by pressing a channel text (e.g. #cats) is broken
> 
> That's separate issue(if exists), we can look into that later. But current PR should fix both issues mentioned in #21065

Sure @Parveshdhull !

The problem is that this bug was introduced in:

- https://github.com/status-im/status-mobile/pull/20326

And also, that PR didn't properly fixed its issue:

- https://github.com/status-im/status-mobile/issues/20313

Since it introduced what I mentioned before about navigating by pressing channel texts. I'd say it used a  "hacky solution" because we don't push new screens for new chats

Adding more patches to this "hacky" navigation solution it's not great, IMO we'd be accumulating tech debt with more complex solutions, harder to properly fix in the futrure.

 I'd suggest solving the root issue for real and this problem with the profile link press will probably dissappear. If our current navigation library doesn't let us proerply solve it, we could wait for the new lib integration.
 
 wdyt?

**Comment by pavloburykh** [comment]
> @pavloburykh It's broken because the history is not preserved, we don't push a new screen, we just update the shown content. if you navigate trough multiple channels and then go back, none of those will appear again.

@ulisesmac would you mind sharing a link to the issue if it exists in our repo? If not, could you please log it with details and reproduction steps so we can track it? Cause unfortunately this problem was not known to me until you pointed out.

**Comment by Parveshdhull** [comment]
Thank you very much for elaborating.
> It's broken because the history is not preserved,

- Navigation history - I am not sure this qualifies as a bug, maybe a feature we lack
- This is related to community channel navigation, how this is affecting the current issue/pr?

>Adding more patches to this "hacky" navigation solution

Please can you elaborate, on how it is hacky? We are navigating back/popping to root, and we are closing `:chat/close` while doing that.

> If our current navigation library doesn't let us proerply solve it

In the scope of the current issue, I don't see any technical limitation we are facing. The [comment](https://github.com/status-im/status-mobile/pull/21142#discussion_r1756142869) in the old PR was related to calling events in unmount and that might be creating confusion.

**Comment by ulisesmac** [comment]
> Thank you very much for elaborating.
> 
> > It's broken because the history is not preserved,
> 
>    * Navigation history - I am not sure this qualifies as a bug, maybe a feature we lack

I wouldn't call it a lacking feature, since our default is to push screens and we aren't doing so. We avoid pushing to fix a blank screen, that's why I call it "hacky".

>    * This is related to community channel navigation, how this is affecting the current issue/pr?

Will explain below
 
> 
> > Adding more patches to this "hacky" navigation solution
> 
> Please can you elaborate, on how it is hacky? We are navigating back/popping to root, and we are closing `:chat/close` while doing that.
> 

Sorry, for "hacky" I was referring to the navigation solution for the blank screen, and for "patch" I'm referring to this PR.

So, basically what I say is:

We fixed the blank screen (https://github.com/status-im/status-mobile/pull/20326), but created the following:
  1. The chat history is not preserved
  2. The current issue about pressing on user's own profile link

Instead of fixing `2` (this PR) and later fixing `1` with patches on the root cause, rework the root cause, so that it doesn't create these issues. 

I'm not focusing exclusively on this PR, I'm taking into consideration the root cause. This PR itself and its changes look good.

**Comment by pavloburykh** [comment]
@Parveshdhull thank you for the PR. Issues are fixed, ready for merge.

**Comment by pavloburykh** [comment]
> > @pavloburykh It's broken because the history is not preserved, we don't push a new screen, we just update the shown content. if you navigate trough multiple channels and then go back, none of those will appear again.
> 
> @ulisesmac would you mind sharing a link to the issue if it exists in our repo? If not, could you please log it with details and reproduction steps so we can track it? Cause unfortunately this problem was not known to me until you pointed out.

@ulisesmac could you please reply to the quoted comment please? Unfortunately I am not sure that I understand the issue correctly, so would appreciate if you can log it with detailed steps and video. Thank you!

**Comment by ulisesmac** [comment]
Hi @pavloburykh 

Yeah, I'll open it and link it to this PR.

**Pull request merged**
