### PR TITLE
Update status-go to 0.10.0

### PR DESCRIPTION
**Pull request by adambabik**
Update to release 0.10.0. The first RC is here: https://github.com/status-im/status-go/releases/tag/0.10.0-rc.0

The most important additions:
- geth 1.8.11,
- `RequestMessages` returns a hash now,
- validate query range on `requestMessages` API,
- mailserver pagination,
- Add asymmetric key support for MailServer requests.

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/status-im/status-go">status-im/status-go</a></strong></div><div>status-go - The Status module that consumes go-ethereum</div></blockquote>

status: ready

### CODE REVIEW

**Comment by vkjr** [comment]
@adambabik, please also add change for desktop.
In this line: https://github.com/status-im/status-react/blob/develop/modules/react-native-status/desktop/CMakeLists.txt#L40
should be
`GIT_TAG 60249e46`

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/status-im/status-react">status-im/status-react</a></strong></div><div>status-react - a free (libre) open source, mobile OS for Ethereum</div></blockquote>

**Comment by adambabik** [comment]
@vkjr would something like `refs/tags/0.10.0-rc.0` worked instead of `60249e46`?

**Comment by vkjr** [comment]
@adambabik, cmake documentation says:
`[GIT_TAG tag]               # Git branch name, commit id or tag`

So tag name should work, but I didn't try.
If build systems for ios and android reference particular commit by hash, probably that would be more logical to use the same approach for desktop.

**Comment by adambabik** [comment]
@vkjr that makes sense. I'd like to switch from hash reference to tag reference in the future but I will do that for the app and desktop at the same time.

**Comment by mandrigin** [comment]
Now someone needs to actually fix the Clojure parts of it... Since RN bug I was planning to work on seems to be fixed, I can take care of this today.

**Comment by adambabik** [comment]
I update this PR for this release: https://github.com/status-im/status-go/releases/tag/v0.10.0. It includes removed `shh` and `shhext` APIModules which requires using `CallPrivateRPC()` binding. 

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/status-im/status-go">status-im/status-go</a></strong></div><div>status-go - The Status module that consumes go-ethereum</div></blockquote>

**Comment by mandrigin** [comment]
yeap, that sounds good, I'll try to take a look at that after lunch today

**Review by mandrigin — APPROVED** [review]
lgtm!

**Review by janherich — APPROVED** [review]

**Review by rasom — APPROVED** [review]

**Comment by lukaszfryc** [comment]
@mandrigin any particular areas that I should focus my testing on?

So far I did basic smoke tests and I checked for the private key in the test dapp and `web3.ssh` is undefined so I believe it works as expected.

**Comment by mandrigin** [comment]
@lukaszfryc no, it is just a regular status-go update, these always need to be tested thoroughly. DApps, Transactions, Tokens & Chat (with mailservers).

**Comment by lukaszfryc** [comment]
@adambabik @mandrigin some issues:

1) Looks like I cannot sign a transaction, the progress bar keeps spinning forever (iOS, Android). I don't see anything specific in logcat

To reproduce:
- Install the app, switch to Ropsten and request ETH in the test dapp
- Have 1-1 chat with someone, type "/send" and try to send him some ETH. When you click "Sign transaction" the spinner will not disappear

2) One time, when I installed the app, switched to Ropsten and went to the test dapp to request ETH I got `TypeError: null is not an object (evaluating 't.minus')` when I clicked the request button (Android). I could not reproduce it afterwards. Here is stacktrace:
```
08-02 06:35:55.304 24259-24336/? E/unknown:ReactNative: TypeError: null is not an object (evaluating 't.minus')
    
    This error is located at:
        in send-transaction
        in reagent86
        in RCTView
        in main
        in root
        in reagent1
        in RCTView
        in RCTView
        in t, stack:
    check_sufficient_gas@12:4800402
    G__30676_30688@12:4801702
    <unknown>@12:2479528
    <unknown>@12:2479540
    in_context@12:2279594
    deref_capture@12:2279737
    _run@12:2300259
    cljs$core$IDeref$_deref$arity$1@12:2305245
    _deref@12:153854
    deref@12:211756
    <unknown>@12:7298067
    <unknown>@12:2314361
    wrap_render@12:2315042
    do_render@12:2316224
    <unknown>@12:2316777
    in_context@12:2279594
    deref_capture@12:2279737
    run_in_reaction@12:2308070
    <unknown>@12:2316718
    f@136:83728
    beginWork@136:87321
    o@136:128242
    a@136:128621
    T@136:132129
    y@136:131565
    v@136:131402
    h@136:130681
    c@136:129935
    enqueueForceUpdate@136:60452
    forceUpdate@198:1315
    run_queue@12:2275286
    flush_queues@12:2276558
    run_queues@12:2276705
    <unknown>@12:2276134
    <unknown>@118:1369
    x@118:643
    callTimers@118:2788
    value@113:3582
    <unknown>@113:1067
    value@113:3009
    value@113:1039
```

**Comment by lukaszfryc** [comment]
Btw, I tested other parts of the app and I didn't notice any other issues.

**Comment by adambabik** [comment]
I will work on https://github.com/status-im/status-go/issues/1136 as soon as possible.

**Comment by adambabik** [comment]
@lukaszfryc I have just updated this PR (commit https://github.com/status-im/status-react/pull/5319/commits/26620028105dd70e58c189a716b8e13ab96f0c55) with a fix for https://github.com/status-im/status-go/issues/1136.

**Comment by lukaszfryc** [comment]
@adambabik thanks. I'm looking at it now.

**Comment by annadanchenko** [comment]
@adambabik is full re-testing needed after the update in PR (so testing all features that were already tested regardless the area)?

**Comment by lukaszfryc** [comment]
@adambabik I tried iOS build (https://i.diawi.com/VP4U2X) and I can't login or create new account. The app is stuck on "Creating your account...". Here are TF sessions if you find them useful:
- [Create account](https://app.testfairy.com/projects/4803590-status/builds/8552462/sessions/4398177670)
- [Sign in](https://app.testfairy.com/projects/4803590-status/builds/8552462/sessions/4398177228)

Android does not have these issues. I'm testing other areas there.

**Comment by churik** [comment]
@adambabik @lukaszfryc 
Cannot log in or create new account via status-desktop in this PR.
Log:
```
"fff7ac99c8e4feb60c9750054bdc14ce1857f181\":{\"balance\":\"0x3635c9adc5dea00000\"}},\"number\":\"0x0\",\"gasUsed\":\"0x0\",\"parentHash\":\"0x0000000000000000000000000000000000000000000000000000000000000000\"}")))))("ListenAddr", QVariant(QString, ":0"))("LogEnabled", QVariant(bool, false))("LogFile", QVariant(QString, ""))("LogLevel", QVariant(QString, "ERROR"))("LogToStderr", QVariant(bool, true))("MaxPeers", QVariant(double, 25))("MaxPendingPeers", QVariant(double, 0))("Name", QVariant(QString, "StatusIM"))("NetworkId", QVariant(double, 1))("NoDiscovery", QVariant(bool, false))("NodeKeyFile", QVariant(QString, ""))("RPCEnabled", QVariant(bool, false))("RegisterTopics", QVariant(QVariantList, ()))("Rendezvous", QVariant(bool, false))("RequireTopics", QVariant(QVariantMap, QMap(("whisper", QVariant(QVariantMap, QMap(("Max", QVariant(double, 2))("Min", QVariant(double, 2))))))))("StatusServiceEnabled", QVariant(bool, false))("SwarmConfig", QVariant(QVariantMap, QMap(("Enabled", QVariant(bool, false)))))("TLSEnabled", QVariant(bool, false))("UpstreamConfig", QVariant(QVariantMap, QMap(("Enabled", QVariant(bool, false))("URL", QVariant(QString, "https://mainnet.infura.io/nKmXgiFgc2KqtoQ8BCGJ")))))("Version", QVariant(QString, "0.9.9-"))("WhisperConfig", QVariant(QVariantMap, QMap(("DataDir", QVariant(QString, "/Users/curikovatm/Library/Application Support/StatusIm/ethereum/mainnet_rpc/wnode"))("EnableMailServer", QVariant(bool, false))("EnableNTPSync", QVariant(bool, true))("Enabled", QVariant(bool, true))("FirebaseConfig", QVariant(QVariantMap, QMap(("AuthorizationKeyFile", QVariant(QString, ""))("NotificationTriggerURL", QVariant(QString, "https://fcm.googleapis.com/fcm/send")))))("LightClient", QVariant(bool, false))("MailServerAsymKey", QVariant(std::nullptr_t, (nullptr)))("MailServerAsymKeyFile", QVariant(QString, ""))("MailServerCleanupPeriod", QVariant(double, 0))("MailServerPassword", QVariant(QString, ""))("MailServerPasswordFile", QVariant(QString, ""))("MailServerRateLimit", QVariant(double, 0))("MinimumPoW", QVariant(double, 0.001))("TTL", QVariant(double, 120))))))

Debug: call of RCTStatus::jailSignalEventCallback ... signal:  {"type":"node.crashed","event":{"error":"node is already running"}}

Debug: call of RCTStatus::emitSignalEvent ... signal:  {"type":"node.crashed","event":{"error":"node is already running"}}

Debug: RCTStatus::startNode StartNode result:  {"error":""}

Debug: call of RCTStatus::onJailSignalEvent ... signal:  ��k��ݺ �

Debug: ubuntu-server std:  "DEBUG [status-im.utils.handlers:37] - Handling re-frame event:  :signal-event \xEF\xBF\xBD\xEF\xBF\xBDk\x07\xEF\xBF\xBD\xEF\xBF\xBD\xDD\xBA \xEF\xBF\xBD\b"

Debug: ubuntu-server std:  "DEBUG [status-im.ui.screens.events:391] - :event-str \xEF\xBF\xBD\xEF\xBF\xBDk\x07\xEF\xBF\xBD\xEF\xBF\xBD\xDD\xBA \xEF\xBF\xBD\b"

Debug: ubuntu-server std:  "DEBUG [status-im.ui.screens.events:403] - Event  nil  not handled"

Debug: call of RCTStatus::jailSignalEventCallback ... signal:  {"type":"discovery.stopped","event":null}

Debug: call of RCTStatus::emitSignalEvent ... signal:  {"type":"discovery.stopped","event":null}

Debug: call of RCTStatus::onJailSignalEvent ... signal:  ��k��ݺ��e

Debug: ubuntu-server std:  "DEBUG [status-im.utils.handlers:37] - Handling re-frame event:  :signal-event \xEF\xBF\xBD\xEF\xBF\xBDk\x07\xEF\xBF\xBD\xEF\xBF\xBD\xDD\xBA\xEF\xBF\xBD\xEF\xBF\xBD""e"

Debug: ubuntu-server std:  "DEBUG [status-im.ui.screens.events:391] - :event-str \xEF\xBF\xBD\xEF\xBF\xBDk\x07\xEF\xBF\xBD\xEF\xBF\xBD\xDD\xBA\xEF\xBF\xBD\xEF\xBF\xBD""e"

Debug: ubuntu-server std:  "DEBUG [status-im.ui.screens.events:403] - Event  nil  not handled"

```
Build is [here](https://ci.status.im/job/status-react/job/desktop/job/pull-requests/view/change-requests/job/PR-5319/lastSuccessfulBuild/artifact/StatusImPackage/StatusIm.dmg)

**Comment by adambabik** [comment]
@churik 

```
Debug: call of RCTStatus::jailSignalEventCallback ... signal:  {"type":"node.crashed","event":{"error":"node is already running"}}
```

This is the problem that the node crashed. It looks like it was initialized twice...? Are there more logs?

**Comment by churik** [comment]
@adambabik 
[This](https://github.com/status-im/status-react/files/2283041/StatusIm.txt) is full log since the first launch.

**Comment by adambabik** [comment]
@churik Thanks. I found this:
```
Debug: call of RCTStatus::jailSignalEventCallback ... signal:  {"type":"discovery.started","event":null}
Debug: call of RCTStatus::emitSignalEvent ... signal:  {"type":"discovery.started","event":null}
Debug: call of RCTStatus::jailSignalEventCallback ... signal:  {"type":"node.started","event":null}
Debug: call of RCTStatus::emitSignalEvent ... signal:  {"type":"node.started","event":null}
Debug: call of RCTStatus::jailSignalEventCallback ... signal:  {"type":"node.ready","event":null}
Debug: call of RCTStatus::emitSignalEvent ... signal:  {"type":"node.ready","event":null}
```
which suggests that the node started correctly. However, a little bit down I can see that the node is tried to be started again:
```
Debug: call of RCTStatus::startNode with param configString: "{\"NetworkId\":1,\"DataDir\":\"/ethereum/mainnet_rpc\",\"UpstreamConfig\":{\"Enabled\":true,\"URL\":\"https://mainnet.infura.io/z6GCTmjdP3FETEJmMBI4\"}}"
```
and I don't see any reason why it is so. The result is a node crash because node was already running and it's expected. Someone from the Desktop Team should take a look.

**Comment by lukaszfryc** [comment]
@adambabik @churik the Android and iOS apps look fine. 

@adambabik should we merge it and work on the desktop fix in a separate PR?

**Comment by maxhora** [comment]
@lukaszfryc at least change in `desktop/CMakeLists.txt` should be removed to not break Desktop nightly builds

**Comment by adambabik** [comment]
@MaxRis I reverted the update of the Desktop client.

@lukaszfryc merging :)

**Pull request merged**
