### PR TITLE
[TESTS] Added test for searching not used translation strings

### LINKED ISSUE #8693: Test if strings from en.json are used in the code and create a list of unused strings
# Problem

Some stings from https://github.com/status-im/status-react/blob/develop/translations/en.json are not used in the app anymore but they are present in all translations files and eat space. For example, 
```
   "phone-e164": "International 1",
```

 We need some test that would detect unused strings and lists them in a bug report. This test also can become part of nightly suite to detect similar issues in the future

### PR DESCRIPTION
**Pull request by yevh-berdnyk**
fixes #8693

status: ready

### CODE REVIEW

**Comment by yevh-berdnyk** [comment]
@annadanchenko, couple of questions here:

- The test is added for checking en.json only, should other languages be verified too?
- Do we need it in a nightly suite? Now it can be run by the pytest mark **translations**

**Comment by annadanchenko** [comment]
> @annadanchenko, couple of questions here:
> * The test is added for checking en.json only, should other languages be verified too?

No, only en.json should be checked. Other languages will be updated as soon as we remove stings from en.json

> * Do we need it in a nightly suite? Now it can be run by the pytest mark **translations**

yes, would be useful to have it in nightly suite. 


@yevh-berdnyk can you please attach the test result after running this test, so issue can be created with list of not-used strings to be removed from  en.json?

**Comment by Serhy** [comment]
@yenda correctly stated that "there are some programmaticaly generated labels so there will be exceptions" 
For instance: 

```  
  "intro-wizard-text1": "Your identity is secure by design. You get a locally generated cryptographic keypair",
  "intro-wizard-title2": "Choose a key and name",
  "intro-wizard-text2": "This name is your identity in Status.  It can’t be changed once you choose one. ",
  "intro-wizard-title3": "Select key storage",
  "intro-wizard-text3": "Your key is stored locally. There is no copy. Only you have access.",
  
  ```

Nothing from those keys are used in views because we generate them like  (if i'm correct with the place we use that title)
```
      (i18n/label (keyword (str "intro-wizard-title" (when  (and (#{:create-code :confirm-code} step) encrypt-with-password?)
                                                       "-alt") (step-kw-to-num step))))] 
```
Means we add figure to text depending of some conditions.
So such keys are among the exceptions.

**Comment by yevh-berdnyk** [comment]
@annadanchenko I've added https://ethstatus.testrail.net/index.php?/cases/view/6223 so the test will run in each nightly.

@Serhy now the test is updated with 2 types of errors: 

- the list of translations with index (which can be generated) to recheck,
- all other not found translation keys.

**Comment by yevh-berdnyk** [comment]
## 0% of end-end tests have passed
```
Total executed tests: 1
Failed tests: 1
Passed tests: 0
```
<h3>Failed tests (1)</h3><details><summary>Click to expand</summary><br/><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. test_find_unused_translations</b> (TestRail link is not found)</td></tr><tr><td><code> Translations to recheck: 
     ['intro-wizard-title3', 'intro-wizard-title-alt5', 'intro-wizard-title1', 'intro-wizard-title2', 'intro-wizard-text7', 'intro-wizard-title-alt4', 'intro-wizard-text2', 'intro-wizard-text4', 'intro-wizard-text6', 'intro-wiza</code><br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/0?auth=445d87c85871cb27d6023ad7f712a65e">Steps, video, logs</a></li><li><a href="None">Failure screenshot</a></li></ul></p></ul></p></td></tr></tbody></table></details>

**Comment by yevh-berdnyk** [comment]
## 0% of end-end tests have passed
```
Total executed tests: 1
Failed tests: 1
Passed tests: 0
```
<h3>Failed tests (1)</h3><details><summary>Click to expand</summary><br/><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. test_find_unused_translations</b> (TestRail link is not found)</td></tr><tr><td><code> Translations to recheck: 
     ['intro-wizard-title-alt5', 'intro-wizard-title2', 'intro-wizard-title3', 'intro-wizard-text4', 'intro-wizard-text6', 'intro-wizard-title1', 'intro-wizard-text2', 'intro-wizard-title-alt4', 'intro-wizard-text7', 'intro-wiza</code><br/><br/></td></tr></tbody></table></details>

**Comment by yevh-berdnyk** [comment]
## 0% of end-end tests have passed
```
Total executed tests: 1
Failed tests: 1
Passed tests: 0
```
<h3>Failed tests (1)</h3><details><summary>Click to expand</summary><br/><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. test_find_unused_translations</b> (TestRail link is not found)</td></tr><tr><td><code> Translations to recheck: 
     ['intro-wizard-title2', 'intro-wizard-text7', 'intro-wizard-title-alt4', 'intro-wizard-text4', 'intro-wizard-text6', 'intro-wizard-text3', 'intro-wizard-text2', 'intro-wizard-title3', 'intro-wizard-title-alt5', 'intro-wizar</code><br/><br/></td></tr></tbody></table></details>

**Comment by yevh-berdnyk** [comment]
@annadanchenko Here is the test result: https://ethstatus.testrail.net/index.php?/tests/view/799897&group_by=tests:status_id&group_order=desc&group_id=10

**Review by annadanchenko — APPROVED** [review]

**Comment by flexsurfer** [comment]
Just to make sure, do we find strings from en file in status-im/src and components/src folders ?
we shouldn't use test folder at all

**Comment by Serhy** [comment]
> Just to make sure, do we find strings from en file in status-im/src and components/src folders ?
> we shouldn't use test folder at all

Yes, both `status-im/src` and `components/src` (only `.js` or `.cljs` files) included for where the script is looking for translations keys. 
And any `test` or `translation` folder excluded.

**Review by Serhy — APPROVED** [review]

**Review by Serhy — CHANGES_REQUESTED** [review]
@yevh-berdnyk I was talking with Andrey and we need to make some changes here:
Ignore everything but `.cljs` files. 
And look for those files only from `status-im/src` and `components/src` path

**Review by Serhy — APPROVED** [review]

**Comment by Serhy** [comment]
All of three tests (https://github.com/status-im/status-react/pull/8720#issuecomment-520607876) failed due to known issues opened in GH now.

**Pull request merged**
