### PR TITLE
[#7188] undefined is not an object (evaluating 'e.substring') when da…

### LINKED ISSUE #7188: undefined is not an object (evaluating 'e.substring') when dapps / stickers offline
### Description

*Type*: Bug

*Summary*: `undefined is not an object (evaluating 'e.substring')` when accessing [ens.status.eth] url

#### Expected behavior
If this URL could not be opened - show user-friendly pop-up

#### Actual behavior
image

### Reproduction

- Open Status
- Recover account
- Open ens.status.eth in browser

#### Logs

```
2018-12-26 13:01:27.566 1566-1622/? I/GnssLocationProvider: WakeLock acquired by handleInjectNtpTime()
2018-12-26 13:01:27.568 1566-12095/? D/NtpTrustedTime: getCachedNtpTime() cache hit
2018-12-26 13:01:27.568 1566-12095/? E/LocSvc_eng: E/int loc_eng_inject_time(loc_eng_data_s_type &, GpsUtcTime, int64_t, int): log_eng state error: instance not initialized
2018-12-26 13:01:27.568 1566-12095/? I/GnssLocationProvider: WakeLock acquired by sendMessage(10, 0, null)
2018-12-26 13:01:27.569 1566-12095/? I/GnssLocationProvider: WakeLock released by handleInjectNtpTime()
2018-12-26 13:01:27.569 1566-1622/? I/GnssLocationProvider: WakeLock released by handleMessage(10, 0, null)
2018-12-26 13:01:27.640 1844-1844/? I/PhenotypeExpConfig: refreshConfiguration() : Force = false : UpdateAvailable = false : Age = 4 minutes : MaxAge = 720 minutes
2018-12-26 13:01:27.642 1844-1844/? I/GifEntryExtension: onDeactivate()
2018-12-26 13:01:27.643 1844-1844/? I/EmojiDataExtension: onDeactivate() : Locale = zz
2018-12-26 13:01:27.643 1844-11538/? W/Delight5Decoder: removePredictionEngine() : Unknown engine bzr@a87754
2018-12-26 13:01:27.655 11363-11425/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:34] - Handling re-frame event:  :browser.ui/dapp-url-submitted
2018-12-26 13:01:27.662 1566-2782/? I/WindowManager: input method visible height changed 0
2018-12-26 13:01:27.712 11363-11425/? D/ReactNativeJS: DEBUG [status-im.ui.screens.navigation:80] - :navigate-to :browser
2018-12-26 13:01:27.837 11363-11425/? D/ReactNativeJS: DEBUG [status-im.ui.screens.views:83] - :on-will-focus :browser
2018-12-26 13:01:27.874 11363-11363/? W/ResourceType: No package identifier when getting name for resource number 0x00000000
2018-12-26 13:01:27.884 11363-11425/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:34] - Handling re-frame event:  :set
2018-12-26 13:01:27.888 11363-11425/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:34] - Handling re-frame event:  :set
2018-12-26 13:01:27.897 11363-11425/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:34] - Handling re-frame event:  :show-tab-bar
2018-12-26 13:01:27.904 11363-11425/? D/ReactNativeJS: DEBUG [status-im.ui.screens.views:396] - :main-component-did-update :browser
2018-12-26 13:01:27.929 11363-11363/? D/EgretLoader: EgretLoader(Context context)
2018-12-26 13:01:27.929 11363-11363/? D/EgretLoader: The context is not activity
2018-12-26 13:01:27.955 11363-11603/? W/cr_media: Requires BLUETOOTH permission
2018-12-26 13:01:27.958 11363-12101/? E/libEGL: validate_display:99 error 3008 (EGL_BAD_DISPLAY)
2018-12-26 13:01:27.974 11363-11363/? W/ContentCatcher: Failed to notify a WebView
2018-12-26 13:01:28.063 11363-11363/? V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@6e43c15
2018-12-26 13:01:28.063 11363-11363/? V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@6ba2b2a
2018-12-26 13:01:28.082 11363-12101/? W/VideoCapabilities: Unrecognized profile 2130706433 for video/avc
2018-12-26 13:01:28.082 11363-12101/? W/VideoCapabilities: Unrecognized profile 2130706434 for video/avc
2018-12-26 13:01:28.093 11363-12101/? W/Utils: could not parse long range '175-174'
2018-12-26 13:01:28.096 11363-12101/? W/VideoCapabilities: Unrecognized profile 2130706433 for video/avc
2018-12-26 13:01:28.096 11363-12101/? W/VideoCapabilities: Unrecognized profile 2130706434 for video/avc
2018-12-26 13:01:28.098 11363-12101/? W/VideoCapabilities: Unrecognized profile 2130706433 for video/avc
2018-12-26 13:01:28.098 11363-12101/? W/VideoCapabilities: Unrecognized profile 2130706434 for video/avc
2018-12-26 13:01:28.101 1566-1644/? I/WindowManager: Destroying surface Surface(name=InputMethod) called by com.android.server.wm.WindowStateAnimator.destroySurface:2045 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:897 com.android.server.wm.WindowState.destroyOrSaveSurface:2118 com.android.server.wm.WindowSurfacePlacer.performSurfacePlacementInner:440 com.android.server.wm.WindowSurfacePlacer.performSurfacePlacementLoop:237 com.android.server.wm.WindowSurfacePlacer.performSurfacePlacement:185 com.android.server.wm.WindowManagerService$H.handleMessage:8356 android.os.Handler.dispatchMessage:102 
2018-12-26 13:01:28.102 11363-12101/? W/VideoCapabilities: Unrecognized profile/level 0/3 for video/mpeg2
2018-12-26 13:01:28.104 11363-12101/? W/VideoCapabilities: Unrecognized profile/level 0/3 for video/mpeg2
2018-12-26 13:01:28.122 11363-12101/? W/VideoCapabilities: Unsupported mime video/mp4v-esdp
2018-12-26 13:01:28.135 11363-11425/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:34] - Handling re-frame event:  :browser/navigation-state-changed
2018-12-26 13:01:28.135 11363-12101/? I/VideoCapabilities: Unsupported profile 4 for video/mp4v-es
2018-12-26 13:01:28.171 11363-11425/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:34] - Handling re-frame event:  :browser/loading-started
2018-12-26 13:01:28.175 11363-11425/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:34] - Handling re-frame event:  :browser/navigation-state-changed
2018-12-26 13:01:28.272 11363-11425/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:34] - Handling re-frame event:  :browser.callback/resolve-ens-contenthash
2018-12-26 13:01:27.655 11363-11425/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:34] - Handling re-frame event:  :browser.ui/dapp-url-submitted
2018-12-26 13:01:28.729 11363-11425/? I/ReactNativeJS: PRETTY PRINTED EXCEPTION
    
    ***
    NAME: "TypeError"
    MESSAGE: undefined is not an object (evaluating 'e.substring')
    
    cljs$core$IFn$_invoke$arity$3@index.android.bundle:12:294710
    resolve_ens_contenthash_callback@index.android.bundle:12:5666121
    index.android.bundle:12:5398103
    index.android.bundle:792:1299
    index.android.bundle:748:575
    index.android.bundle:12:7500429
    value@index.android.bundle:19:3651
    index.android.bundle:19:1257
    value@index.android.bundle:19:2621
    value@index.android.bundle:19:1227
    [native code]
```

### PR DESCRIPTION
**Pull request by flexsurfer**
fixes #7188

### CODE REVIEW

**Review by dmitryn — APPROVED** [review]

**Review by jeluard — APPROVED** [review]

**Comment by asemiankevich** [comment]
@flexsurfer can reproduce the error when tapping Get stickers in offline

Steps:
1. open status while offline
2. log in
3. open 1x1 chat
4. tap stickers -> get stickers 

image

**Comment by flexsurfer** [comment]
@asemiankevich good catch, thanks!

**Comment by flexsurfer** [comment]
@asemiankevich fixed

**Review by yenda — APPROVED** [review]

**Comment by asemiankevich** [comment]
@Serhy  would you mind to help with https://ethstatus.testrail.net/index.php?/tests/view/545456 ? I can pass it manually , not sure why automated test taps this + button instead of vertical scroll

**Pull request merged**
