### PR TITLE
Upgrade to status-go 0.25.0-beta.0

### PR DESCRIPTION
**Pull request by cammellos**
status: ready

### CODE REVIEW

**Comment by yenda** [comment]
Can upgrade to beta.1 instead I already have a PR that needs it

**Review by flexsurfer — APPROVED** [review]

**Comment by cammellos** [comment]
@yenda this will go in the release hotfix, is it ok to releaseh 0.25.1? If so, have you already created a release for 0.25.1 or should I create one?

**Review by rasom — APPROVED** [review]

**Review by pedropombeiro — APPROVED** [review]

**Comment by yenda** [comment]
> @yenda this will go in the release hotfix, is it ok to releaseh 0.25.1? If so, have you already created a release for 0.25.1 or should I create one?

Do you mean `0.25.0-beta.1` or really `0.25.1`? Personally I haven't released anything maybe @mandrigin 

@cammellos `0.25.0-beta.1` is `0.25.0-beta.0` plus a few tests and minus a bug. So I'm just saying this PR could safely use the former instead of the latter

**Review by yenda — CHANGES_REQUESTED** [review]
this change was already testted and merged into develop within #8158

**Pull request closed without merging**
