### PR TITLE
Upgrade Instabug to 2.11.0 #4128

### LINKED ISSUE #4128: Upgrade Instabug to 2.12.0
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a developer and tester, I want to see [crash reports](https://instabug.com/crash-reporting) so that I can debug crashes.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Improvement

*Summary*: Instabug v2.12.0 now has [crash reporting](https://instabug.com/crash-reporting) which can be useful for debugging

#### Expected behavior

Instabug version is 2.12.0

#### Actual behavior

Instabug version is older

### PR DESCRIPTION
**Pull request by debragail**
Fixes #4128 

Updated package.json to have upgraded instabug version

Current:

Instabug version is 2.11.0

replaced

Instabug version is 2.8.1

### CODE REVIEW

**Comment by flexsurfer** [comment]
@debragail something wrong with the branch, could you check please

**Comment by dmitryn** [comment]
Not sure what has happened here, i did not merge anything related to this PR.

**Comment by debragail** [comment]
@dmitryn weird ... i'm just going to create a new branch then @flexsurfer.

**Comment by dmitryn** [comment]
@debragail yes, i guess it may happen because of branch name collision. I also use `feature/3738-send-instabug-user-events` in another PR.

**Comment by flexsurfer** [comment]
and also branches mixed up `feature/3738-send-instabug-user-events from develop ` should be `into develop`

**Comment by debragail** [comment]
@dmitryn you musth have just typed insta in the search for the pull request and let it autocomplete ... maybe?  I'm trying to fix now.  Thanks guys creating a new PR and fixing my repo.

**Pull request merged**
