### PR TITLE
Runtime permissions (#762)

### LINKED ISSUE #762: Cleanup Application Permissions (on-demand only)
http://wiki.status.im/getting-started/faq/#what-about-all-these-permissions-in-the-app
https://github.com/status-im/status-react/blob/develop/android/app/src/main/AndroidManifest.xml

All permissions need to be on-demand basis and we need to cleanup our plugin/reactnative permissions.

ie `SYSTEM_ALERT_WINDOW`  see facebook/react-native#5886
 in our gradle we can do

```
buildTypes {
        debug {
            manifestPlaceholders = [excludeSystemAlertWindowPermission: "false"]
        }
        release {
            manifestPlaceholders = [excludeSystemAlertWindowPermission: "true"]
        }
    }
```

### PR DESCRIPTION
**Pull request by alwx**
Fixes #762

### CODE REVIEW

**Comment by alwx** [comment]
Please, notice: React Native requires "draw over other apps" permission on Android 6.0+, thus the first run of the app may fail and require you to grant this permission manually. Fortunately, because of the condition in `AndroidManifest.xml`, it happens only in debug mode, and release mode works absolutely fine without any unnecessary permissions.

**Comment by jarradh** [comment]
great work @alwx

**Comment by rasom** [comment]
I cannot start app on real device, always see this:
screenshot_2017-03-14-12-18-22

Logs:
https://gist.github.com/rasom/083ade909c7b9687f57979cbded09bb4

**Comment by alwx** [comment]
@rasom there is a comment above about it: https://github.com/status-im/status-react/pull/864#issuecomment-285401980

**Comment by rasom** [comment]
oh, sorry, thanks @alwx, I just misunderstood

**Comment by jarradh** [comment]
Can't we modify the gradle to add permissions in debug mode?
https://gist.github.com/MarkMjw/7998381#file-build-gradle-L89

Or just use different manifest files for release and debug?
`manifest.srcFile 'other/AndroidManifest.xml'`
https://developer.android.com/studio/build/build-variants.html

**Comment by alwx** [comment]
Because we use React Native 0.43 now, I've rebased this PR and checked — it still requires "draw over the apps" permission in debug mode (it's needed for React Native YellowBox; thus we need it only in dev mode). 

However, there is no problem with granting this permission anymore — you just need to tap "OK" on the first launch. 
@roma, please, check it.

**Comment by rasom** [comment]
> WARNING: Use of undeclared Var status-im.components.permissions/rest-permissions at line 17 /Users/rasom/clj/rs/src/status_im/components/permissions.cljs

**Comment by alwx** [comment]
Have you tried changing your app settings or doing `Settings -> Apps -> Hamburger menu (three dots in the upper right corner) -> Reset app preferences`?

Seems like you're the only one who has this problem with overlay :( And also seems like this is the only way to make runtime permissions work. However, nobody faces this problem with "Screen overlay detected" so I don't really know how to solve it.

**Comment by alwx** [comment]
Alternatively, you can grant "Draw over other apps" permission manually: http://www.gadgetraid.com/2016/10/screen-overlay-detected/

**Comment by alwx** [comment]
I've removed `react-native-udp` package (seems like it was useless) and got rid of ` CHANGE_WIFI_MULTICAST_STATE` permission.
`READ_EXTERNAL_STORAGE` and `WRITE_EXTERNAL_STORAGE` are required thus they cannot be removed.

@rasom, please, check.

**Comment by rasom** [comment]
Got this when tried to make photo 
```
 DEBUG [status-im.profile.photo-capture.screen:53] - Error capturing image:  Error: No camera found.
```

**Comment by alwx** [comment]
Camera fix was pretty easy. It works now.

**Comment by alwx** [comment]
I've added some code to move files from external to internal storage. @rasom, please, take a look.

**Pull request merged**
