### PR TITLE
[FIX #3629] remove extra hyphenation of text in empty home tab

### LINKED ISSUE #3629: Extra hyphenation of description text on the empty home tab
### User Story

As a user, I want to to see good right formatting.

### Description

*Type*: Bug

Delete extra hyphenation between first sentence and second. 

#### Expected behavior
ios_signup_12_1 copy 18 1x

#### Actual behavior
img_3740

### Additional Information
* Status version:  nightly 20.03.18
* Operating System: <Android|iOS

### PR DESCRIPTION
**Pull request by msuess**
fixes #3629

### Summary:

The description text on the empty home tab has a linebreak that makes the formatting look ugly depending on the user's screen size. This PR removes the linebreak for more consistent formatting across devices..

### Steps to test:
- Open Status
- navigate to home tab
- delete all conversations
- behold the consistent formatting ;)

status: ready

### CODE REVIEW

**Review by jeluard — APPROVED** [review]

**Review by flexsurfer — APPROVED** [review]

**Review by cammellos — APPROVED** [review]

**Comment by asemiankevich** [comment]
i am not sure why i am not able to install ios build using https://i.diawi.com/5vHJsh ? it prompts me to open something in app store on my phone @msuess 

<blockquote><div><strong><a href="https://i.diawi.com/5vHJsh">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by asemiankevich** [comment]
apart that the issue if fixed

image

**Comment by msuess** [comment]
@asemiankevich I have no idea what that's about, but I highly doubt that it's because of this change... does anyone know what that could be?

**Comment by asemiankevich** [comment]
have no idea Marco :) @msuess  @jeluard any thoughts?

**Comment by jeluard** [comment]
This change is harmless. Let's merge it.
@asemiankevich No idea. Can this be reproduced on other iOS?

**Comment by asemiankevich** [comment]
yeah lets merge. Just curious what is it :)

**Pull request merged**
