### PR TITLE
[#15690] Fix frozen ui on iOS

### LINKED ISSUE #15690: [IOS only] The UI is frozen after app comes back from the background when 'chat key' overlay is opened
#### Steps to reproduce:
1. Go to profile -> Open 'chat key' overlay
2. Go to the background
3. Return from the background
4. Try to tap UI elements

#### Actual result:
The UI is frozen after the app comes back from the background

https://user-images.githubusercontent.com/52490791/233143505-a0a00b55-a721-488f-a0a3-da72b8099575.mp4

#### Expected result:
UI elements are not frozen

#### ENV:
- Nightly: 18 Apr 2023

#### Device:
iPhone 11 pro max, IOS 16

### PR DESCRIPTION
**Pull request by rasom**
fix #15690

status: ready

### CODE REVIEW

**Review by ibrkhalil — APPROVED** [review]

**Review by Parveshdhull — APPROVED** [review]
hi @rasom, Thank you for the fix.
Btw, curious why popover getting dismissed on own while minimizing app

**Comment by Parveshdhull** [comment]
This is a nice solution and also future proofs from bugs like this.
We probably should also log a separate issue about popover getting destroyed on the app coming from the background.

**Comment by Parveshdhull** [comment]
btw, we have `(dismiss-all-modals)` in navigate function to avoid cases like these. Maybe we can also add [Navigation.dismissAllOverlays();](https://wix.github.io/react-native-navigation/api/overlay#dismissalloverlays) in the function. 
if doesn't affect performance and works, it will fix undismissed overlays even in other cases along with the app going in the background issue.

**Comment by Parveshdhull** [comment]
> We probably should also log a separate issue about popover getting destroyed on the app coming from the background.

Sorry for spamming PR, logged a separate issue for this: https://github.com/status-im/status-mobile/issues/15708

**Comment by rasom** [comment]
@Parveshdhull I'm a bit lost now, do we want to keep this fix or better to close this PR and you will fix it in a different way?

**Comment by Parveshdhull** [comment]
hi @Roman, Initially I thought this issue is the limitation of our bottom tabs implementation, and reanimated causing this weird reload. So this fix was good enough.

But now we know, the theme change [bug](https://github.com/facebook/react-native/issues/28525) is the culprit. So I think it will be better to fix the root cause. I can do that in different PR.
Sorry for the confusion, and thank you very much for your work.

**Comment by rasom** [comment]
@qoqobolo no need to test this PR

@Parveshdhull it is yours now, thanks

**Pull request closed without merging**
