### PR TITLE
fix(communities): token-gated community info text

### LINKED ISSUE #21211: Placeholder text in the token gated communities info drawer
# Design Feedback 2.30

## Placeholder text in the token gated communities info drawer
When tapping the info button in a token gated community a drawer with placeholder text appears

Figma design for context [here](https://www.figma.com/design/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?m=auto&node-id=8091-547073&t=UKLpBGZrIEzt5odb-1)

Screenshot 2024-09-09 alle 08 56 49

>
The correct copy to replace the placeholder text will be provided by @Fabiomorais87 🙏

### Reproduction

1. Open a token gated community
2. Tap on the info button in the _Community token gating_ component

### Additional Information

- Status version: 2.30
- Operating System: Android, iOS

### PR DESCRIPTION
**Pull request by ulisesmac**
fixes #21211 

### Summary

This PR fixes an info text for the token-gated communities:

https://github.com/user-attachments/assets/cfe4768d-32a0-4263-99dc-d400e2faa903

#### Platforms

- Android
- iOS

### Steps to test
- Open Status
- Go to communities
- Pick any token-gated community where the current user is not joined, or you can use the following community:  https://status.app/c/G1EAAMTyFm0fBflGtiFYF5IgNAQzPiCADTgBCjTjlZ_tpjItNSiTKjz7Bvw2VF7r7XG_tFRcPsgFyoCnHC2MDzF5Bw==#zQ3shsQJt1uYuzLvQ1mpcDHSUnEYTV5wMmtzkoqER8kezGqAE
- Press on the info icon

status: ready

### CODE REVIEW

**Comment by ulisesmac** [comment]
@Francesca-G Could you please approve if the content is the expected?

Thank you!

**Review by Francesca-G — APPROVED** [review]
Looks good to me 👍

**Comment by ulisesmac** [comment]
@ilmotta Could you please approve this if it's fine? it's just a text change.

**Review by ilmotta — APPROVED** [review]

**Comment by yevh-berdnyk** [comment]
Hi @ulisesmac, thanks for the PR, it can be merged. E2E failures are not related. Also, I've checked a token-gated community on a real device - LGTM

**Pull request merged**
