### PR TITLE
Fix: Updates for unread messages indicator

### PR DESCRIPTION
**Pull request by alwx**
Intented to fix both issues here: https://github.com/status-im/status-mobile/issues/16696#issuecomment-1740705191
The actual fix is on go side: https://github.com/status-im/status-go/pull/4085

#### Platforms

- Android
- iOS

##### Functional

- 1-1 chats
- public chats
- group chats

status: ready

### CODE REVIEW

**Comment by alwx** [comment]
The Go part (https://github.com/status-im/status-go/pull/4085) was approved already so I'm moving it to E2E
cc @churik @pavloburykh

**Comment by churik** [comment]
waiting for @John-44  confirm in chat

**Comment by churik** [comment]
So it was discussed with @John-44  that eventually we need to show counters like they were in 1-1 chat, sorry for the confusion.
I'm closing original issue https://github.com/status-im/status-mobile/issues/16696 and waiting for the logic how it was working before in this PR (or in new one, as a follow-up)

Thanks!

**Comment by pavloburykh** [comment]
> I'm closing original issue #16696 and waiting for the logic how it was working before in this PR (or in new one, as a follow-up)

@alwx hello! Is there a followup PR that reverts counter logic?

**Pull request closed without merging**
