### PR TITLE
fix endless logout

### LINKED ISSUE #18063: Endless logout occurs if performed when device is connected to the network without access to internet (or poor connection)
**Steps:** 

1. Connect device to a network that has no access to internet (or simulate poor connection in emulator)
2. Login the app
3. Perform manual logout
4. See if user is redirected to login screen

**Actual result:** endless logout. User is not redirected to login screen. Sometimes I face endless login. But endless logout is easier to reproduce as it happens every time when following the above steps. 

[Status-debug-logs (87).zip](https://github.com/status-im/status-mobile/files/13545527/Status-debug-logs.87.zip)

https://github.com/status-im/status-mobile/assets/97245802/2d9b7d65-87bb-4194-9efa-137a53e6b07c

**Expected result:** user is redirected to login screen, logout is successful. 

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

### PR DESCRIPTION
**Pull request by qfrank**
fixes #18063

relate PRs: [status-go](https://github.com/status-im/status-go/pull/4563) [go-waku](https://github.com/waku-org/go-waku/pull/1006)

status: ready

### CODE REVIEW

**Review by siddarthkay — APPROVED** [review]

**Review by ilmotta — APPROVED** [review]

**Comment by pavloburykh** [comment]
Hey @qfrank! Thank you for the PR and all the efforts on investigation and fixing. 

Unfortunately initial [issue](https://github.com/status-im/status-mobile/issues/18063#issuecomment-1882860466) is still reproducible for me (on both IOS and Android devices)

 
[Status-debug-logs (96).zip](https://github.com/status-im/status-mobile/files/14041128/Status-debug-logs.96.zip)

https://github.com/status-im/status-mobile/assets/97245802/b1c9cdd1-9ee1-4f25-8972-2d04129cfee5

**Comment by qfrank** [comment]
found something suspicious:

```
goroutine 667 [semacquire, 9 minutes, locked to thread]:
sync.runtime_SemacquireMutex(0x0?, 0x80?, 0x101aba0e6?)
	/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.19.9/share/go/src/runtime/sema.go:77 +0x25
sync.(*RWMutex).Lock(0xc000ec0120?)
	/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.19.9/share/go/src/sync/rwmutex.go:152 +0x71
github.com/status-im/status-go/vendor/github.com/waku-org/go-waku/waku/v2/service.(*CommonService).Stop(0xc000ee07d0, 0xc002a479d8)
	/private/tmp/nix-build-status-go-develop-unknown-ios.drv-0/go/src/github.com/status-im/status-go/vendor/github.com/waku-org/go-waku/waku/v2/service/common_service.go:49 +0x3a
github.com/status-im/status-go/vendor/github.com/waku-org/go-waku/waku/v2/protocol/filter.(*WakuFilterLightNode).Stop(0xc0006a8600?)
	/private/tmp/nix-build-status-go-develop-unknown-ios.drv-0/go/src/github.com/status-im/status-go/vendor/github.com/waku-org/go-waku/waku/v2/protocol/filter/client.go:112 +0x38
github.com/status-im/status-go/vendor/github.com/waku-org/go-waku/waku/v2/node.(*WakuNode).Stop(0xc0002ef400)
	/private/tmp/nix-build-status-go-develop-unknown-ios.drv-0/go/src/github.com/status-im/status-go/vendor/github.com/waku-org/go-waku/waku/v2/node/wakunode2.go:532 +0x316
github.com/status-im/status-go/wakuv2.(*Waku).Stop(0xc00024d680)
	/private/tmp/nix-build-status-go-develop-unknown-ios.drv-0/go/src/github.com/status-im/status-go/wakuv2/waku.go:1329 +0x56
github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/node.(*Node).stopServices(0xc0000e6000, {0xc0002ef000, 0x16, 0xc164ae2dc13e2168?})
	/private/tmp/nix-build-status-go-develop-unknown-ios.drv-0/go/src/github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/node/node.go:298 +0xbd
github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/node.(*Node).Close(0xc0000e6000)
	/private/tmp/nix-build-status-go-develop-unknown-ios.drv-0/go/src/github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/node/node.go:218 +0x191
github.com/status-im/status-go/node.(*StatusNode).stop(0xc0006a8200)
	/private/tmp/nix-build-status-go-develop-unknown-ios.drv-0/go/src/github.com/status-im/status-go/node/get_status_node.go:460 +0x159
github.com/status-im/status-go/node.(*StatusNode).Stop(0xc0006a8200)
	/private/tmp/nix-build-status-go-develop-unknown-ios.drv-0/go/src/github.com/status-im/status-go/node/get_status_node.go:446 +0x8f
github.com/status-im/status-go/api.(*GethStatusBackend).Logout(0xc0004d0420)
	/private/tmp/nix-build-status-go-develop-unknown-ios.drv-0/go/src/github.com/status-im/status-go/api/geth_backend.go:2219 +0x170
github.com/status-im/status-go/mobile.Logout()
	/private/tmp/nix-build-status-go-develop-unknown-ios.drv-0/go/src/github.com/status-im/status-go/mobile/status.go:474 +0x25
main.proxystatusgo__Logout()
	/private/tmp/nix-build-status-go-develop-unknown-ios.drv-0/gomobile-work/iossimulator/src/gobind/go_statusgomain.go:1232 +0x1f
```

**Comment by qfrank** [comment]
Found the dead lock:
image
image
image

my solution(add context support for `v5_udp` to resolve discv5 deadlock issue):
image
image

but i don't have write permission to [go-discover](https://github.com/waku-org/go-discover) , may i have it?

cc @richard-ramos @cammellos

**Comment by cammellos** [comment]
@richard-ramos @chaitanyaprem the above solution looks good to me, another thing we noticed, is that there's a lot of Locks/wait groups that are public in go-waku, I think that's a patter we might want to remove and prefer communications/synchronization using channels/contextes instead, and using locks/wait groups only for internals, in order to avoid deadlocks, understandably is quite a large change, but maybe we can gradually move away from it? What do you think?

**Comment by richard-ramos** [comment]
@cammellos I agree with the idea. Might even help simplify the code as I feel some complexity has crept up in diff parts of go-waku

**Comment by qfrank** [comment]
Hi @pavloburykh , can you retry this PR? thank you

> Hey @qfrank! Thank you for the PR and all the efforts on investigation and fixing.
> 
> Unfortunately initial [issue](https://github.com/status-im/status-mobile/issues/18063#issuecomment-1882860466) is still reproducible for me (on both IOS and Android devices)
> 
> [Status-debug-logs (96).zip](https://github.com/status-im/status-mobile/files/14041128/Status-debug-logs.96.zip)
> 
>  telegram-cloud-document-2-5298888018512330963.mp4

**Comment by pavloburykh** [comment]
@qfrank great job, thank you! The bug is no more reproducible for me. Ready to be merged.

**Pull request merged**
