### PR TITLE
Reject typeddata request when wrong chainId inside typed data

### LINKED ISSUE #20757: Failing to sign typed data if it contains the wrong chainId in the domain
No error is shown when signing the event when user's network differs from event network.

For typed data, we check if the  chainId inside the data is the same as the session-request chainId (for security reasons) and if they're different, the signing will fail. We should show an error telling the user that it failed and the reason.

If there is no chainId in the typeddata, we assume it's not chain specific and it should pass successfully [(fixed here)](https://github.com/status-im/status-go/pull/5522#pullrequestreview-2177991600).

cc: @xAlisher we will need an extra toast during typeddata signing requests

**Steps:** 

1. Connect to https://react-app.walletconnect.com/ using testnetwork (Sepolia)
2. Trigger eth_signTypedData_v4 request
3. Sign the request
4. See if error about wrong network is shown

**Actual result:** no error after signing the request. In fact the request is not signed as it is triggered on Mainnet while user is on testnet. 

Also, the same actual result happens  when I am trying to sign eth_signTypedData_v4 request while being connected on Mainnet (Ethereum + Optimism networks) and triggering request on Optimism

**Expected result:** we should show an error toast informing user that request has not been signed because user's network differs from request network.

_Originally posted by @pavloburykh in https://github.com/status-im/status-mobile/issues/20693#issuecomment-2228248044_

### PR DESCRIPTION
**Pull request by clauxx**
fixes #20757

### Summary

We should reject any request where the typed data includes the wrong chainId (to prevent replay attacks). As a measure of security, we are checking that the typed data has the correct chain-id and reject potentially malicious requests without showing them to the user. Instead, we just show a toast, informing them that the signing is intended for a different network.

Included in the PR:
* `:wallet-connect/send-response` no longer dismissed the modal, not it's done in `:wallet-connect/finish-session-request`. This is done because sometimes we need to reject (with send-response) without having a modal open, which breaks navigation if we dismiss a modal that doesn't exist.
* rejecting requests when processing a request fails
* rejecting a request when signing/transaction fails
* checking the chainId inside the typeddata to make sure it's not different from the chainId of the session. If different, we show a toast informing the user about it.

### Steps to test

1. Make sure you're on the testnet
2. Connect on https://react-app.walletconnect.com/
3. Send a `eth_signTypedData_v4`
4. A toast is shown and the request is rejected

status: ready

### CODE REVIEW

**Review by shivekkhurana — APPROVED** [review]

**Comment by clauxx** [comment]
@qoqobolo @pavloburykh Ready for QA testing

**Comment by qoqobolo** [comment]
@clauxx could you take a look at the `tests` please? The build has failed

Screenshot 2024-07-23 at 15 30 37

**Comment by clauxx** [comment]
> @clauxx could you take a look at the `tests` please? The build has failed
> 
> Screenshot 2024-07-23 at 15 30 37

thanks! Pushed again

**Comment by qoqobolo** [comment]
Thanks @clauxx, the PR is ready for merge.

**Pull request merged**
