### PR TITLE
[#4671 #4708] mainnet_rpc as default network, no mainnet warning

### LINKED ISSUE #4671: Set mainnet as default network for beta ⚡️
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to to be on mainnet by default so that I can easily transact and use dapps.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Improvement

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: The key feature of Status beta is mainnet by default. This issue will default all new accounts to mainnet.

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
New accounts are on mainnet

#### Actual behavior
[comment]: # (Describe what actually happened.)
New accounts are on testnet

### Solution

Mainnet is default network

### Additional Information

This issue will be coordinated with the beta launch. It shouldn't be merged until the beta release is being prepared.

### LINKED ISSUE #4708: Remove mainnet network switch warning on release builds
[comment]: # (Please replace ... with your information. Remove < and >)

### Description

In https://github.com/status-im/status-react/issues/3953 we added mainnet as an option for alpha release builds, and along with it a warning message. 

For the beta release, we can revert this and remove the warning message.

#### Expected behavior
No warning when switching networks

#### Actual behavior
Warning described in https://github.com/status-im/status-react/issues/3953

### Reproduction

On a Testflight/Play release build, switch to Mainnet.

### Solution

Remove the warning message work done in https://github.com/status-im/status-react/pull/4138

### Additional Information

This issue will be coordinated with the beta launch. It shouldn't be merged until the beta release is being prepared.

Needs to be done together with https://github.com/status-im/status-react/issues/4671

### PR DESCRIPTION
**Pull request by rasom**
fix #4671
fix #4708

status: ready

### CODE REVIEW

**Review by janherich — APPROVED** [review]

**Review by dmitryn — APPROVED** [review]

**Comment by antdanchenko** [comment]
@rasom please, set `DEFAULT_NETWORK=testnet_rpc` for [.env.e2e](https://github.com/status-im/status-react/pull/4740/files#diff-7b1bded1588d9fe0e80cc75cd7aab013) since we need Ropsten as default network for running transaction tests

**Comment by rasom** [comment]
@antdanchenko done

**Comment by rasom** [comment]
@antdanchenko done

**Comment by annadanchenko** [comment]
upgrade from 0.9.20 using this PR does not change network to Mainnet if it was Ropsten before upgrade (tested on Android). Checking with @chadyj if it should be fixed in scope of this PR

**Comment by chadyj** [comment]
Should be fine since we advise users to switch networks here https://github.com/status-im/status-react/issues/4718

**Comment by annadanchenko** [comment]
tested ok both iOS and Android:
1. Fresh install: Mainnet is by default, no warning if switch to Ropsten -> Mainnet
2. Upgrade from 0.9.20: 
2.1 if ropsten was before upgrade then it remains, no warning if switch to Ropsten -> Mainnet
2.2 if mainnet was before upgrade then it remains
3. If recover account on fresh installation: mainnet is by default

**Pull request merged**
