### PR TITLE
[16219] fix: sync group chat member removal

### LINKED ISSUE #16219: Access to group chat and options in Manage members are still available for a removed user after logging back In (Until Relogged Again)
Follow up for https://github.com/status-im/status-mobile/pull/16134
### Steps:
1. User A and User B are members of a group chat.
2. User B logs out of the app.
3. User A removes User B from the group.
4. User B logs back into the app.
5. User B check 'Group details'

### Actual result:
After being removed from the group, User B can still see the group chat and potentially access the 'Group Details' option after logging back

https://github.com/status-im/status-mobile/assets/52490791/b00965b4-ca80-4e48-9257-55436c0b338b

### Expected result:
After being removed from the group, User B should not have access to the group details

### PR DESCRIPTION
**Pull request by ibrkhalil**
fixes #16219 

### Summary

Fixes an issue with removing private group members changes being applied correctly

status: ready

### CODE REVIEW

**Review by qfrank — APPROVED** [review]

**Comment by VolodLytvynenko** [comment]
Hi @ibrkhalil . Thank you for PR. The issue is still reproducible
## ISSUE 1: Access to group chat and options in Manage members are still available for a removed user after logging back In (Until Relogged Again)
### Steps:
1. User A and User B are members of a group chat.
2. User B logs out of the app.
3. User A removes User B from the group.
4. User B logs back into the app.
5. User B check 'Group details'

### Actual result:
After being removed from the group, User B can still see the group chat and potentially access the 'Group Details' option after logging back

https://github.com/status-im/status-mobile/assets/52490791/df510d2d-0599-4b44-86cc-c32a2208762f


### Expected result:
After being removed from the group, User B should not have access to the group details

**Comment by ibrkhalil** [comment]
@VolodLytvynenko Kindly take another look

**Comment by VolodLytvynenko** [comment]
Hi @ibrkhalil thank you for the fixes. The issue 1 https://github.com/status-im/status-mobile/pull/16299#issuecomment-1598884438 is fixed. But still, the removed from the group user is able to see group details  in the different case:

## ISSUE 2: User can still access group chat and 'Group Details' after being removed from the group
### Steps:
1. `User A` and `User B` are contacts
2. `User B` logs out of the app.
3. `User A` Add `User B` to the group. (while `User B` is logged out)
4. `User A` removes `User B` from the group.
5. `User B` logs back into the app.
6. `User B` check 'Group details'

### Actual result:
After being added and removed from the group, User B can still see the group chat and access the 'Group Details' option after logging back

### Expected result:
After being removed from the group, User B should not have access to the group details

**Comment by VolodLytvynenko** [comment]
@ibrkhalil I wanted to let you know that I'll be off next week. @pavloburykh, please check this PR once it's fixed.

**Comment by ibrkhalil** [comment]
Hey @pavloburykh @VolodLytvynenko, After chatting @cammellos, He is going to continue this task as it requires extensive status-go experience

**Pull request closed without merging**
