### PR TITLE
[#3799] Missing iOS App Store Icon

### LINKED ISSUE #3799: Missing iOS App Store Icon
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a developer, I want to iOS builds to iTunes Connect so that there aren't any errors.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: ...

Every iOS submission Apple complains about an error on submission:

> We identified one or more issues with a recent delivery for your app, "Status - Ethereum. Anywhere.". Your delivery was successful, but you may wish to correct the following issues in your next delivery:
> 
> Missing App Store Icon - iOS Apps must include a 1024x1024px App Store Icon in PNG format. Without providing the icon in the Asset Catalog or via iTunes Connect, apps cannot be submitted for App Review or Beta App Review. Refer to https://developer.apple.com/ios/human-interface-guidelines/icons-and-images/app-icon/ for more information.
> 
> After you’ve corrected the issues, you can use Xcode or Application Loader to upload a new binary to iTunes Connect.

THis should be fixed to make sure it isn't a blocker for beta.

#### Expected behavior
[comment]: # (Describe what you expected to happen.)

iOS can be submitted without issue

#### Actual behavior
[comment]: # (Describe what actually happened.)

iOS is submitted with an error

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

Submit iOS to iTC

### Solution
[comment]: # (Please summarise the solution and provide a task list on what needs to be fixed.)
*Summary*: 

A possible solution here https://stackoverflow.com/a/47051829

@andmironov @denis-sharypin Can you add the 1024x1024px App Store Icon in PNG format?

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: All
* Operating System: iOS

<blockquote><div><strong><a href="https://developer.apple.com/ios/human-interface-guidelines/icons-and-images/app-icon/">App Icon - Icons and Images - iOS Human Interface Guidelines</a></strong></div><div>Learn about designing apps for iOS.</div></blockquote>
<blockquote><div><strong><a href="https://stackoverflow.com/questions/46987694/missing-app-store-icon-ios-apps-must-include-a-1024x1024px-app-store-icon-in/47051829">Missing App Store Icon. iOS Apps must include a 1024x1024px App Store > Icon in PNG format</a></strong></div><div>when I try to submit the app 
  Missing App Store Icon. iOS Apps must include a 1024x1024px App Store
  Icon in PNG format. Without providing the icon in the Asset Catalog or
  via iTunes Connect,...</div></blockquote>

### PR DESCRIPTION
**Pull request by endenwer**
fixes #3799

### Summary:
Add ios 1024x1024 icon.

status: ready

### CODE REVIEW

**Review by rasom — APPROVED** [review]

**Review by flexsurfer — APPROVED** [review]

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/6BPPN3 for branch PR-4182

<blockquote><div><strong><a href="https://i.diawi.com/6BPPN3">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/tM8EHn for branch PR-4182

<blockquote><div><strong><a href="https://i.diawi.com/tM8EHn">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/FUGRgn for branch PR-4182

<blockquote><div><strong><a href="https://i.diawi.com/FUGRgn">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/8dCbi5 for branch PR-4182

<blockquote><div><strong><a href="https://i.diawi.com/8dCbi5">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Pull request merged**
