### PR TITLE
Remove JSC_ENABLED flag and turn on behavior by default

### LINKED ISSUE #3689: Remove JSC_ENABLED flag and turn on behavior by default
### User Story

As a developer, I want flags to reflect possible variables in app, so it's clear what configurations app can be in and options are minimized.

### Description

We always want to use JSC since this is required for App store releases, and behavior is stable enough.

*Type*: Feature/Tooling

*Summary*:  Remove JSC_Enabled flag everywhere and turn on behavior by default.

#### Expected behavior
No JSC_ENABLED flag

#### Actual behavior
JSC_ENABLED flag

### Additional Information
Additionally, we probably want to remove old jail code on status-go side, but this is out of scope of this issue.

### PR DESCRIPTION
**Pull request by psdpfw**
fixes #3689 
Remove JSC_ENABLED flag and turn on behavior by default

status: ready

### CODE REVIEW

**Comment by ghost** [comment]
Hey @ambilo, thanks for making your first pull request in status-react! :heart:

**Review by cammellos — APPROVED** [review]

**Review by jeluard — APPROVED** [review]

**Comment by jeluard** [comment]
@ambilo Do you mind rebasing your PR? Sorry about that.

**Comment by psdpfw** [comment]
@jeluard OK, done.

**Comment by flexsurfer** [comment]
@ambilo could you please resolve conflicts, thanks

**Review by rasom — APPROVED** [review]

**Comment by rasom** [comment]
thanks for contribution, @ambilo!

**Comment by rasom** [comment]
@asemiankevich, iOS version crashes btw :)

**Comment by andytudhope** [comment]
@ambilo please log into openbounty.status.im, select the dropdown in the top right and update your payment details with an Ethereum address you own and that can receive ERC20 tokens (i.e. not an account generated on an exchange like Coinbase etc, MetaMask accounts are good).

**Comment by pablanopete** [comment]
@ambilo just following up on @andytudhope instruction please confirm and we can payout your bounty!

**Comment by psdpfw** [comment]
@pablanopete sorry for not replying sooner. I've updated my payment details.

**Pull request merged**
