### PR TITLE
Extract groovy scripts

### PR DESCRIPTION
**Pull request by jakubgs**
This PR extracts all the `ci/*.groovy` scripts into a separate __private__ repo located at:
https://github.com/status-im/status-react-jenkins

The main reasons for a separate repo are:

* Hiding the internal details of our CI setup
* Hiding names of Jenkins credentials available in CI jobs
* Lowering attack surface for malicious external contributors
* Increasing focus on PRs related to CI setup

You can read more about how Jenkins pipeline shared libraries work [here](https://jenkins.io/doc/book/pipeline/shared-libraries/). In simple terms I've added the repo to the main Jenkins configuration in `Global Pipeline Libraries` section and load it using:
```Groovy
library 'status-react-jenkins@master'
```
Which makes globally available all of the libraries defined in the `vars` directory of that repo.
This also eliminates the need for statements like `android = load 'ci/android.groovy'`.

### CODE REVIEW

**Review by rasom — APPROVED** [review]

**Comment by jakubgs** [comment]
Logs show it's loading the library as expected:
```
Loading library status-react-jenkins@v1.0.0
Examining status-im/status-react-jenkins
Attempting to resolve v1.0.0 as a branch
Attempting to resolve v1.0.0 as a tag
Resolved v1.0.0 as tag v1.0.0 at revision 9b4c926d6a6c3cddd966663987caee7694460e95
using credential status-im-auto
Cloning the remote Git repository
Cloning with configured refspecs honoured and with tags
Cloning repository https://github.com/status-im/status-react-jenkins.git
 > git init /var/jenkins_home/workspace/tatus-react_prs_android_PR-10149@libs/status-react-jenkins # timeout=10
Fetching upstream changes from https://github.com/status-im/status-react-jenkins.git
 > git --version # timeout=10
...
```
https://ci.status.im/job/status-react/job/prs/job/android/job/PR-10149/1/consoleFull

**Review by andremedeiros — APPROVED** [review]

**Review by corpetty — APPROVED** [review]
good work.

**Comment by jakubgs** [comment]
I'm wondering if using a tag like `v1.0.0` makes sense. It would mean that every time we change anything in `status-react-jenkins` we'd need to create a new tag and make a PR for `status-react`.

There are 2 alternatives.
* Simply use `library 'status-react-jenkins@master'` and follow the `master` branch
* Use `library 'status-react-jenkins'` and change the tag/branch in global Jenkins config

What do you think @corpetty @0kok0 @andremedeiros ?

**Review by 0kok0 — APPROVED** [review]

**Comment by jakubgs** [comment]
Okay, I modified it to use `master` branch by default. Since we're going to have a rigorous process for PRs in `status-react-jenkins` I think this should be fine. And if we want to test it we can always make a PR specifying a different `@{branch}` in the `library` line, or just use `Replay` option in Jenkins.

**Pull request merged**
