### PR TITLE
Etherscan api update

### LINKED ISSUE #3294: Update etherscan URL
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a developer, I want to reflect etherscan API URL changes

### Description

*Type*: Bug

etherscan API URL have been [updated](https://etherscancom.freshdesk.com/support/solutions/articles/35000051806-change-of-testnet-api-service-endpoint-url). Reflect those changes in our codebase.

### PR DESCRIPTION
**Pull request by tarekskr**
Fixes #3294

### CODE REVIEW

**Review by jeluard — APPROVED** [review]

**Review by flexsurfer — APPROVED** [review]

**Review by antdanchenko — APPROVED** [review]

**Review by yenda — APPROVED** [review]

**Comment by tarekskr** [comment]
Hey guys: thank you for approving this! It's my first time using Open Bounty however and no SNT has been transferred to me (shows bounty as 'open claim' though). I'd really appreciate your input on this. Thanks again.

**Comment by jeluard** [comment]
@tarekskr You will receive them once the PR is merged. Don't worry it will come!

**Comment by tarekskr** [comment]
@jeluard oh ok, thank you! :)

**Review by rasom — APPROVED** [review]

**Comment by jeluard** [comment]
@tarekskr BTW please squash your commits.

**Comment by tarekskr** [comment]
@jeluard I am not sure how to do that? According to the [docs](https://help.github.com/articles/about-pull-request-merges/), it should give you this option at merge time.

**Comment by jeluard** [comment]
@tarekskr Part of our flow is that PR are just 1 commit (so squashed). Your have to use `git rebase -i develop` and make sure you `fixup` the second commit.

**Comment by tarekskr** [comment]
@jeluard done, thanks a lot for the help.

**Pull request merged**
