### PR TITLE
Add rendezvous nodes to configuration

### PR DESCRIPTION
**Pull request by dshulyak**

### CODE REVIEW

**Comment by dshulyak** [comment]
I am not sure why there were empty space. my editor removed them by itself. do you want to preserve them?

**Review by pedropombeiro — APPROVED** [review]
Looks good. Yeah, the spaces shouldn't be there, we can leave them out.

**Review by adambabik — APPROVED** [review]

**Review by flexsurfer — APPROVED** [review]

**Review by cammellos — APPROVED** [review]

**Comment by dshulyak** [comment]
what else needs to be done to merge this?

**Comment by pedropombeiro** [comment]
@dshulyak I guess the bot didn't automatically move it to TO TEST because there's a check missing (GPG). I'd try moving it manually in the [project board](https://github.com/status-im/status-react/projects/7). Not sure if that'll work though.

**Review by rasom — APPROVED** [review]

**Comment by lukaszfryc** [comment]
@dshulyak @PombeirP is some (system) testing needed for this PR? Like compatibility between different app versions?

**Comment by dshulyak** [comment]
@PombeirP thanks didn't check react inbox today.

@lukaszfryc compatibility testing is not required. it provides additional way to discover peers. so i just tested that app is started in a similar time as before and it can discover required number of peers.

**Pull request merged**
