### PR TITLE
Replace react-navigation-stack with fork without default background color

### PR DESCRIPTION
**Pull request by rasom**
status: ready

### CODE REVIEW

**Review by yenda — CHANGES_REQUESTED** [review]
can you use a tag to please the bot?

**Review by flexsurfer — APPROVED** [review]

**Comment by rasom** [comment]
@yenda done

**Review by mandrigin — CHANGES_REQUESTED** [review]
if that is a branch we tracking, let's also make a tag and let's track it instead.

**Comment by rasom** [comment]
@mandrigin isn't that the same thing as @yenda requested? I suppose that's done already

**Review by yenda — APPROVED** [review]

**Comment by mandrigin** [comment]
hmm why is packages-check-bot unhappy then?

**Comment by rasom** [comment]
@mandrigin because of line which hasn't been touched in this PR? :)

**Review by mandrigin — APPROVED** [review]

**Comment by mandrigin** [comment]
@flexsurfer can you take a look and make this webview bridge warning go away? looks like related to DApps

**Comment by asemiankevich** [comment]
ios and windows builds are failing for some reason, restart does not help @rasom 

```
09:37:24  warning "react-navigation > create-react-context@0.2.2" has unmet peer dependency "prop-types@^15.0.0".
09:39:02  [4/4] Building fresh packages...
09:39:02  success Saved lockfile.
09:39:02  $ yarn build
09:39:02  yarn run v1.13.0
09:39:02  $ babel --no-babelrc --plugins=syntax-jsx,syntax-class-properties,syntax-object-rest-spread,transform-flow-strip-types src --copy-files --out-dir dist --ignore '**/__tests__/**'
09:39:02  internal/modules/cjs/loader.js:582
09:39:02      throw err;
09:39:02      ^
09:39:02  
09:39:02  Error: Cannot find module 'core-js/library/fn/object/keys'
09:39:02      at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
09:39:02      at Function.Module._load (internal/modules/cjs/loader.js:506:25)
09:39:02      at Module.require (internal/modules/cjs/loader.js:636:17)
09:39:02      at require (internal/modules/cjs/helpers.js:20:18)
09:39:02      at Object.<anonymous> (/Users/jenkins/Library/Caches/Yarn/v4/.tmp/2c1913c5afdf8957a3b46d6cd09fe0ce.2f1f8cd782ffcba362ae333e3dc630e237e97669.prepare/node_modules/babel-runtime/core-js/object/keys.js:1:93)
09:39:02      at Module._compile (internal/modules/cjs/loader.js:688:30)
09:39:02      at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
09:39:02      at Module.load (internal/modules/cjs/loader.js:598:32)
09:39:02      at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
09:39:02      at Function.Module._load (internal/modules/cjs/loader.js:529:3)
09:39:02  error Command failed with exit code 1.
09:39:02  info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
09:39:02  error Command failed with exit code 1.
09:39:02  info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
09:39:02  make: *** [prepare-ios] Error 1
```

@jakubgs

**Comment by rasom** [comment]
@asemiankevich  @jakubgs yes, though I can't reproduce the issue locally, so not sure what and how to fix

**Comment by jakubgs** [comment]
I `ssh`d onto the host and ran `yarn cache clean` as `jenkins` and that fixed it. Weird, but what can you do. I did it on all 3 MacOS hosts.

**Comment by rasom** [comment]
@jakubgs thanks, it worked

**Comment by rasom** [comment]
@asemiankevich iOS build is fixed

**Comment by asemiankevich** [comment]
all good then, lets merge

**Pull request merged**
