### PR TITLE
Remove unused erc20-enabled flag

### LINKED ISSUE #3001: Remove ERC20_ENABLED flag
### User Story

As a developer, I want to have a clean codebase

### Description

ERC20 support has now be finalized and enabled. `ERC20_ENABLED` flag is now useless

*Type*: Feature

### PR DESCRIPTION
**Pull request by cammellos**
Fixes #3001 

### Summary:

I have removed the ERC20 flag from the config, the jenkins build and the two control flows that were using it.

status: ready

### CODE REVIEW

**Review by oskarth — APPROVED** [review]

**Review by goranjovic — APPROVED** [review]

**Review by jeluard — APPROVED** [review]

**Comment by asemiankevich** [comment]
Previous build is expired on diawi and I cant build new one, here is an error:

`FAILURE: Build failed with an exception.

* What went wrong:
Gradle build daemon disappeared unexpectedly (it may have been killed or may have crashed)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org`

Please, assist @cammellos

**Comment by cammellos** [comment]
Hi @asemiankevich ,

could you please provide a stack trace so I can look into it?
is it consistently failing?

thanks

**Comment by asemiankevich** [comment]
@cammellos would you mind to rebase your branch ?

**Comment by cammellos** [comment]
@asemiankevich  rebased, seems like Jenkins is happy now, would you mind confirming that?

thanks!

**Comment by andytudhope** [comment]
Hey @cammellos - sorry to comment on an unrelated PR, but please see [this comment](https://github.com/status-im/status-react/pull/3024#issuecomment-357862910) and address so I can confirm your bounty payout?

**Comment by asemiankevich** [comment]
----------------
Branch: PR-3027
Android: https://i.diawi.com/4kfCjY
iOS: https://i.diawi.com/UHNpfQ

**Comment by yenda** [comment]
@cammellos Thanks you for your contribution, can you rebase the PR please ?

**Comment by cammellos** [comment]
Hi @yenda ,

just rebased , it seems like Jenkins is not happy, not sure whether the build is failed or it did not run the build at all.
Do you have a stacktrace / some logs I can have a look at?

cheers

**Comment by yenda** [comment]
@cammellos don't worry there is no space left on device it's not related, I'll merge once it has built.

**Pull request merged**
