### PR TITLE
[#13203] feat: move fetch prices to status-go

### LINKED ISSUE #13203: feat: move fetch prices to status-go
https://github.com/status-im/status-go/pull/2595

### PR DESCRIPTION
**Pull request by flexsurfer**
fixes #13203

### CODE REVIEW

**Review by Parveshdhull — APPROVED** [review]

**Comment by qoqobolo** [comment]
@flexsurfer could you rebase it, please? 
Thanks

**Comment by flexsurfer** [comment]
sorry for the delay @qoqobolo done

**Comment by churik** [comment]
@flexsurfer 
nice!
Is it possible to show 0 for converted value instead of ... on Ropsten? 
It is a reason of some e2e failures in current PR

**Comment by flexsurfer** [comment]
@churik  i think its better to show "..." if we can't fetch the price ? so probably better to change the e2e ?

**Comment by churik** [comment]
@flexsurfer please, mind my commits when squashing. Thank you!

**Pull request closed without merging**
