### PR TITLE
Wakuv2 rendezvous

### PR DESCRIPTION
**Pull request by vitvly**
This PR enables support for Waku v2 rendezvous feature. Depends on https://github.com/status-im/status-go/pull/2475 and https://github.com/status-im/go-waku/pull/182.

### CODE REVIEW

**Comment by flexsurfer** [comment]
hey @siphiuel is it still relevant ?

**Comment by vitvly** [comment]
@flexsurfer yes, it should be. I'll double check with waku v2 team though. Thanks for reminding, i virtually forgot this was around.

**Comment by flexsurfer** [comment]
hey @siphiuel any updates ?

**Comment by vitvly** [comment]
discv5 is now used instead of rendezvous

**Pull request closed without merging**
