### PR TITLE
Remove username from outgoing messages

### LINKED ISSUE #4091: Remove your username near the chat bubble in all chats
### User Story

Two stories:

1. As a user, I already know my username and don't need to see it near my chat bubbles in all chats

2. As a user, I already know a username of the recipient (displays in the navbar) so I don't need to have see it near every recipient's message in 1-to-1 chat.

3. The exception only for System messages that could be found in the group chats. For them, we should keep name System message

*Type*: Feature

#### Expected behavior

expected

#### Actual behavior
actual

### Solution
*Summary*: 
1. don't show the username of a user of an account
2. don't show recipient username in 1-to-1 chat

### Additional Information
* Status version: 03.05.18 nightly
* Operating System: Android|iOS

### PR DESCRIPTION
**Pull request by cammellos**
fixes #4091

### Summary:

We don't display username anymore if the message originated with the user, removes extra paddings as well.

status: ready

### CODE REVIEW

**Review by flexsurfer — CHANGES_REQUESTED** [review]
in 1-1 we should remove both

**Comment by cammellos** [comment]
@flexsurfer thanks, didn't notice that, updated!

**Review by janherich — APPROVED** [review]

**Comment by jeluard** [comment]
@flexsurfer Can you re-review? :sweat_smile:

**Review by flexsurfer — APPROVED** [review]

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/Uscaz1 for branch PR-4168

<blockquote><div><strong><a href="https://i.diawi.com/Uscaz1">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/xtD5Ga for branch PR-4168

<blockquote><div><strong><a href="https://i.diawi.com/xtD5Ga">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/UbsG2x for branch PR-4168

<blockquote><div><strong><a href="https://i.diawi.com/UbsG2x">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/atPJJ3 for branch PR-4168

<blockquote><div><strong><a href="https://i.diawi.com/atPJJ3">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by lukaszfryc** [comment]
@cammellos have you removed both usernames from 1-1 chat? I still can see username of the other user. Rest looks good. I tested https://i.diawi.com/atPJJ3 (iOS).

<blockquote><div><strong><a href="https://i.diawi.com/atPJJ3">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by cammellos** [comment]
@lukaszfryc , I believe I did, but maybe I got something wrong, let me have a look

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/nkEk7S for branch PR-4168

<blockquote><div><strong><a href="https://i.diawi.com/nkEk7S">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/yYT2Me for branch PR-4168

<blockquote><div><strong><a href="https://i.diawi.com/yYT2Me">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by cammellos** [comment]
@lukaszfryc updated, sorry for the confusion, I had left out some code I think :(

**Comment by lukaszfryc** [comment]
let me check it

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/ugogf9 for branch PR-4168

<blockquote><div><strong><a href="https://i.diawi.com/ugogf9">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/wPKZJq for branch PR-4168

<blockquote><div><strong><a href="https://i.diawi.com/wPKZJq">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by jeluard** [comment]
@cammellos Can you squash your commits?

**Comment by cammellos** [comment]
@jeluard done!

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/qMHzku for branch PR-4168

<blockquote><div><strong><a href="https://i.diawi.com/qMHzku">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/ZMBxx8 for branch PR-4168

<blockquote><div><strong><a href="https://i.diawi.com/ZMBxx8">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Pull request merged**
