### PR TITLE
chore: rename alias of promesa to be more verbose

### PR DESCRIPTION
**Pull request by J-Son89**
This pr renames the alias of promesa from `p` to `promesa`. We can look to revisit this in the future but while it is quite new to the codebase it is good to leave it more verbose and apparent to devs of what the code is doing.

### CODE REVIEW

**Comment by J-Son89** [comment]
Skipping manual QA here as this pr does not change any code, it only renames the importing of some dependencies.

**Comment by J-Son89** [comment]
@clauxx can you take a quick look when you get a chance? this pr is straightforward enough

**Review by clauxx — APPROVED** [review]
No issues from my side, but I still prefer `p` TBH :)

**Comment by flexsurfer** [comment]
> No issues from my side, but I still prefer `p` TBH :)

we can change it later, when all devs will be familiar with it, same as we have rn or rf

**Review by flexsurfer — APPROVED** [review]

**Review by alwx — APPROVED** [review]

**Comment by J-Son89** [comment]
> > No issues from my side, but I still prefer `p` TBH :)
> 
> we can change it later, when all devs will be familiar with it, same as we have rn or rf

yeah +1 on this, it's just temporary while devs are becoming familiar with promesa 👍

**Review by OmarBasem — APPROVED** [review]

**Comment by pavloburykh** [comment]
@J-Son89 hey! E2E are fine here.

**Pull request merged**
