### PR TITLE
Community requests to join when admin is offline

### LINKED ISSUE #17576: User automatically joins a community even after canceling the join request when the community admin comes online.
### Steps:
1. `User A` creates an open community.
2. `User A` shares the community with User B.
3. `User A` goes offline.
4. `User B` requests to join the community.
5. `User B` cancels the request (changing the community status to "opened").
6. `User A` goes online.
7. `User B` checks the community status.

### Actual result:
`User B` is automatically joined to the community after the community owner goes online.

https://github.com/status-im/status-mobile/assets/52490791/1866de33-d925-4476-9c4b-14c33f22f269

### Expected result:
`User B`  should only join the opened community if it is in a pending status when the community owner comes online.

### Env:
- Nightly [6 Oct 2023]

### Logs:
[Status-debug-logs.zip](https://github.com/status-im/status-mobile/files/12832979/Status-debug-logs.zip)

### PR DESCRIPTION
**Pull request by ibrkhalil**
fixes #17576 

### Summary
Fixes an issue if User A sends a request to join and cancels it in an open community while admin is offline during both requests.

status: ready

### CODE REVIEW

**Review by OmarBasem — APPROVED** [review]

**Review by ulisesmac — APPROVED** [review]

**Comment by pavloburykh** [comment]
@ibrkhalil hi! Please rebase the go branch as it is outdated. Thank you!

**Review by vkjr — APPROVED** [review]

**Comment by churik** [comment]
@ibrkhalil apologies for delay, can you please rebase your PR to latest version?

**Comment by ibrkhalil** [comment]
> @ibrkhalil apologies for delay, can you please rebase your PR to latest version?

Done

**Comment by pavloburykh** [comment]
I have triggered e2e run. Waiting for the results.

**Comment by pavloburykh** [comment]
> > @ibrkhalil apologies for delay, can you please rebase your PR to latest version?
> 
> Done

Hey @ibrkhalil! I have just noticed that status-go PR has not been rebased https://github.com/status-im/status-go/pull/4321? Could you please rebase it? Whenever PR contains go changes we need to rebase both mobile and go branches.

**Comment by ibrkhalil** [comment]
> > > @ibrkhalil apologies for delay, can you please rebase your PR to latest version?
> > 
> > 
> > Done
> 
> Hey @ibrkhalil! I have just noticed that status-go PR has not been rebased [status-im/status-go#4321](https://github.com/status-im/status-go/pull/4321)? Could you please rebase it? Whenever PR contains go changes we need to rebase both mobile and go branches.

Done

**Comment by VolodLytvynenko** [comment]
Hey @ibrkhalil thank you for your work. The issue in this PR is fixed.

One more issue has been detected, but I'm unsure if it's related to this PR. I attempted to reproduce it in other rebased PRs or on the nightly build without success. Hopefully, the logs can show what going wrong and if this PR could affect this issue. The steps to reproduce this issue aren't exact; it seems like the crash occurs randomly after the following steps:

## ISSUE 1: Android app crashes after admin shares community and logs in

### Steps:
 1. `User Android` creates no manual approval required community and shares it with `User B`
 2. `User Android` logs out
 3. `User B` sends the request to join to community
 4. `User Android` logs in

### Actual result:
The Android app crashes after 'User Android' logs in.


https://github.com/status-im/status-mobile/assets/52490791/bd15f0a5-7e69-4bde-b5dd-8e0cd1d98a80


this is a quickly blinked error screen which is not so visible on the record
image


### Expected result:
The app on android does not crash after login

### Logs:
[android_logcat4.txt](https://github.com/status-im/status-mobile/files/13582790/android_logcat4.txt)

**Comment by ibrkhalil** [comment]
> Hey @ibrkhalil thank you for your work. The issue in this PR is fixed.
> 
> One more issue has been detected, but I'm unsure if it's related to this PR. I attempted to reproduce it in other rebased PRs or on the nightly build without success. Hopefully, the logs can show what going wrong and if this PR could affect this issue. The steps to reproduce this issue aren't exact; it seems like the crash occurs randomly after the following steps:
> 
> ## ISSUE 1: Android app crashes after admin shares community and logs in
> ### Steps:
> 1. `User Android` creates no manual approval required community and shares it with `User B`
> 2. `User Android` logs out
> 3. `User B` sends the request to join to community
> 4. `User Android` logs in
> 
> ### Actual result:
> The Android app crashes after 'User Android' logs in.
> 
>  crash.mp4 
> this is a quickly blinked error screen which is not so visible on the record image
> 
> ### Expected result:
> The app on android does not crash after login
> 
> ### Logs:
> [android_logcat4.txt](https://github.com/status-im/status-mobile/files/13582790/android_logcat4.txt)

I don't think it's related

**Comment by pavloburykh** [comment]
> I don't think it's related

@ibrkhalil is it clear from logs what causes the crash?

**Comment by ibrkhalil** [comment]
> > I don't think it's related
> 
> 
> 
> @ibrkhalil is it clear from logs what causes the crash?
> 
> 

I didn't touch any code that's related to the part throwing the error.
But I'll investigate better and go  back with an answer.

**Comment by pavloburykh** [comment]
> I didn't touch any code that's related to the part throwing the error.
> But I'll investigate better and go back with an answer.

Thank you! I am asking so we know who we should ping on this issue.

**Comment by qfrank** [comment]
```
12:43:07.482  E  panic: runtime error: invalid memory address or nil pointer dereference
12:43:07.482  E  [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x7a852fdcc8]
12:43:07.482  E  
12:43:07.482  E  goroutine 1006 [running]:
12:43:07.482  E  github.com/status-im/status-go/services/wallet/transfer.(*loadBlocksAndTransfersCommand).fetchHistoryBlocks(0x400391b4d0, {0x4002d04e78?, 0x4?}, 0x4?, {0xd8, 0xea, 0xb9, 0x85, 0x4f, 0x8a, ...}, ...)
12:43:07.482  E          github.com/status-im/status-go/services/wallet/transfer/commands_sequential.go:803 +0x2d8
12:43:07.482  E  github.com/status-im/status-go/services/wallet/transfer.(*loadBlocksAndTransfersCommand).Run(0x400391b4d0, {0x7a85e33e58, 0x40039312c0})
12:43:07.482  E          github.com/status-im/status-go/services/wallet/transfer/commands_sequential.go:745 +0x3c4
12:43:07.483  E  github.com/status-im/status-go/services/wallet/async.InfiniteCommand.Run({0x4003933920?, 0x4003925930?}, {0x7a85e33e58, 0x40039312c0})
12:43:07.483  E          github.com/status-im/status-go/services/wallet/async/async.go:72 +0x40
12:43:07.483  E  github.com/status-im/status-go/services/wallet/async.(*Group).Add.func1()
12:43:07.483  E          github.com/status-im/status-go/services/wallet/async/async.go:101 +0x34
12:43:07.483  E  created by github.com/status-im/status-go/services/wallet/async.(*Group).Add
12:43:07.483  E          github.com/status-im/status-go/services/wallet/async/async.go:100 +0x8c
```

**Comment by siddarthkay** [comment]
github.com/status-im/status-go/services/wallet/transfer.(*loadBlocksAndTransfersCommand).fetchHistoryBlocks 
should have been fixed in latest status-go. 
A rebase will fix this for you :)

**Comment by siddarthkay** [comment]
ref : https://github.com/status-im/status-go/pull/4433

**Comment by ibrkhalil** [comment]
@pavloburykh Rebased to latest go changes

**Comment by VolodLytvynenko** [comment]
hi @ibrkhalil thank you for your work. No issues from my side. PR is ready to be merged

**Pull request merged**
