### PR TITLE
Bug/fix status go panic

### PR DESCRIPTION
**Pull request by cammellos**

### CODE REVIEW

**Comment by flexsurfer** [comment]
@cammellos could you rebase it? looks outdated

**Comment by churik** [comment]
all failures are known, but @qoqobolo faced a crash one more time on IOS (just with the opened app, no more additional steps), trying to reproduce and catch at least some info
If no success after 1 hour -ready to be merged and cherry-picked

**Comment by churik** [comment]
OK, no luck. 
@cammellos read to be merged and cherry-picked to release 1.21 branch

**Comment by pavloburykh** [comment]
@cammellos I guess that a have got Android crashed on login, though I am not sure on 100%. Could you please check logcat and see if there are any crash events? It should be somewhere between 18:28-18:29.

[logcat](https://drive.google.com/file/d/1dCZPyaDObb3kbe2utgYjiBfJEAW2FnHJ/view?usp=share_link)

**Comment by cammellos** [comment]
> @cammellos I guess that a have got Android crashed on login, though I am not sure on 100%. Could you please check logcat and see if there are any crash events? It should be somewhere between 18:28-18:29.
> 
> [logcat](https://drive.google.com/file/d/1dCZPyaDObb3kbe2utgYjiBfJEAW2FnHJ/view?usp=share_link)

Yes, that's a crash, but looks like it might be using the old code, can you replicate on RC1 (the new build)?

**Comment by pavloburykh** [comment]
> Yes, that's a crash, but looks like it might be using the old code, can you replicate on RC1 (the new build)?

Yes, I will try. The crash with an old code that you mentioned might be not from PR build but from previous RC that is installed on my device. 

`02-13 16:12:14.865 11934     0 E Go      : panic: runtime error: slice bounds out of range [:2] with capacity 0`

time is 16:12. But crash on PR build happened between 18:28-18:29. Anyway, I will try to catch in new build. Thank you.

**Pull request closed without merging**
