### PR TITLE
[#4550] fix delete group chat label

### LINKED ISSUE #4550: Copy for deleting public chat mentions group chats
### Description

*Type*: Bug

*Summary*: While deleting a public chat, the copy says something about group chat. Instead, it should probably be "Are you sure you want to delete this chat?" for all chat types to unify them.

#### Expected behavior
Have "Are you sure you want to delete this chat?" for all chat types.

#### Actual behavior
 "Are you sure you want to delete this **group** chat?" is shown while removing public chat.

### Reproduction

- Open Status
- Join public chat
- Delete public chat

### Additional Information
* Status version: nightly, May 31
* Operating System: Android, iOS

### PR DESCRIPTION
**Pull request by rasom**
fixes #4550 

status: ready

### CODE REVIEW

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/5xoBLP for branch PR-4559

<blockquote><div><strong><a href="https://i.diawi.com/5xoBLP">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/q4dYYK for branch PR-4559

<blockquote><div><strong><a href="https://i.diawi.com/q4dYYK">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Review by yenda — APPROVED** [review]

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/kRnWZY for branch PR-4559

<blockquote><div><strong><a href="https://i.diawi.com/kRnWZY">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/vSmAE4 for branch PR-4559

<blockquote><div><strong><a href="https://i.diawi.com/vSmAE4">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Review by yenda — APPROVED** [review]

**Review by janherich — APPROVED** [review]

**Review by cammellos — APPROVED** [review]

**Pull request merged**
