### PR TITLE
chat: change command char from ! to /  #687

### LINKED ISSUE #687: Change command character from '!' to '/'
It has been decided we should change from ! to / for the command character

### PR DESCRIPTION
**Pull request by GustavoNunes**
Note: also removed the #594 fix, no longer seems necessary.

fixes #687

### CODE REVIEW

**Comment by jarradh** [comment]
Please re-add #594 fix, it is for specific keyboards.

**Comment by jarradh** [comment]
What do you think about moving instances of  "/" to constants.cljs so it's easy to modify in the future if we have to?

**Comment by jarradh** [comment]
Also can we re-enable #594 like we chatted about in slack? awesome contributions btw @GustavoNunes  thanks :D

**Comment by GustavoNunes** [comment]
done @jarradh!

Note: the **constants** and **chat.constants** namespaces are being imported under various aliases in the project; to avoid confusion, I used the _chat-consts_ alias in these files.

**Comment by jarradh** [comment]
please pull into `develop`, not `master`, thanks :)

**Comment by jarradh** [comment]
thanks again for yet another contirbution @GustavoNunes  :D

**Comment by GustavoNunes** [comment]
Good catch @johnmn3, I missed that one. Thanks!

**Pull request merged**
