### PR TITLE
[FIX #4296] Rename Recent Recipients to Contacts in Wallet

### LINKED ISSUE #4296: Rename Recent Recipients to Contacts in Wallet
### User Story

As a user, I don't want to get confused when treating `Recent recipients` incorrectly

### Description

*Type*: Bug

*Summary*: I realized that `Recent recipients` is confusing when sending funds from the wallet. I sent some test ETH to mycrypto account and then I wanted to send some more and realized that I need to scan the code again as nothing is shown in recent recipients

#### Expected behavior
Rename `Recent recipients` to `Contacts` everywhere in Wallet so it would be less confusing

### Reproduction

1. Wallet tab - send transaction - specify recipient
2. Wallet tab - receive transaction - send a transaction request - specify recipient

### Additional Information
* Status version: nightly
* Operating System: Android, iOS

### PR DESCRIPTION
**Pull request by georgiemathews**
[comment]: # (Please replace ... with your information. Remove < and >)
[comment]: # (To auto-close issue on merge, please insert the related issue number after # i.e fixes #566)

fixes #4296 

### Summary:

[comment]: # (Summarise the problem and how the pull request solves it)
Renames the "Recent recipients" label in wallet to "Contacts".

### Steps to test:
- Open Status
- Go to Wallet tab
- Verify that label is correct

status: ready

### CODE REVIEW

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/BegJvq for branch PR-4326

<blockquote><div><strong><a href="https://i.diawi.com/BegJvq">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/wrjzZc for branch PR-4326

<blockquote><div><strong><a href="https://i.diawi.com/wrjzZc">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/mkcLqR for branch PR-4326

<blockquote><div><strong><a href="https://i.diawi.com/mkcLqR">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Review by yenda — APPROVED** [review]

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/pCni9h for branch PR-4326

<blockquote><div><strong><a href="https://i.diawi.com/pCni9h">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/hTd3Bc for branch PR-4326

<blockquote><div><strong><a href="https://i.diawi.com/hTd3Bc">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by jeluard** [comment]
Thanks @georgiemathews !

**Pull request merged**
