### PR TITLE
Show correct error message while unlocking app

### LINKED ISSUE #15842: Show correct error message when app unlock fails
### Summary

Currently when app fails to unlock it shows error `Oops, wrong password!`,
even when error returned by status-go is different, like `node is already running`

### PR DESCRIPTION
**Pull request by Parveshdhull**
fixes https://github.com/status-im/status-mobile/issues/15842

status: ready

### CODE REVIEW

**Review by ibrkhalil — APPROVED** [review]

**Review by J-Son89 — APPROVED** [review]

**Comment by VolodLytvynenko** [comment]
Hi @Parveshdhull. Could you rebase current PR please?

**Comment by VolodLytvynenko** [comment]
Hi @Parveshdhull, I'm not clear on the description. Should the input data be cleared when tapping the 'log in' button, or should the cursor simply disappear from the current input field? Can you please clarify? Thank you!

If the password field should be cleared, here is one found issue related to this.

## ISSUE 1: [Android] 'Login' button remains enabled after clearing the 'password' field during an unsuccessful login attempt
#### Steps to reproduce:
1. Enter an invalid password into the 'password' field.

#### Actual result:
The 'login' button remains enabled.

https://github.com/status-im/status-mobile/assets/52490791/9acd4f00-5658-4bd1-bc31-28c3ddf4258c


#### Expected result:
The 'login' button should be disabled if the 'password' field becomes empty.

#### Device:
- Real device: Huawei P20 Lite, Android 9
- Emulator: Pixel 6, Android 12

**Comment by VolodLytvynenko** [comment]
## ISSUE 2: [iOS] Input remains enabled after an initial interaction with 'log in' button

### Problem 
Sometimes the 'login' button should be tapped at least thrice to disable the input

### Steps to reproduce:
1. Enter an invalid password
2. Tap 'login'
3. Focus on the input field 
4. Tap 'login' again

### Actual result:
Input remains enabled after an initial interaction with 'log in' button

https://github.com/status-im/status-mobile/assets/52490791/aee62afa-8f0b-4f76-93b7-c632b13f2b4c


### Expected result:
Input is disabled

### Device:
- iPhone 11 Pro Max, IOS 16

**Comment by Parveshdhull** [comment]
Hi, @VladimrLitvinenko, thank you very much for testing the PR.

Looks like there is probably something wrong with the input component itself and it re initializes on changing the value of the disabled param.

I discussed this with @ulisesmac, and this needs further investigation.
So I am removing the fix for https://github.com/status-im/status-mobile/issues/15779 issue from pr, and only keeping the fix for https://github.com/status-im/status-mobile/issues/15842.

As https://github.com/status-im/status-mobile/issues/15842 issue is not directly testable (the issue happens mostly while using debug app), I am skipping manual testing and merging PR. Will that be ok?

**Comment by Parveshdhull** [comment]
Added both issue in #15779

**Comment by VolodLytvynenko** [comment]
> Hi, @VladimrLitvinenko, thank you very much for testing the PR.
> 
> Looks like there is probably something wrong with the input component itself and it re initializes on changing the value of the disabled param.
> 
> I discussed this with @ulisesmac, and this needs further investigation. So I am removing the fix for #15779 issue from pr, and only keeping the fix for #15842.
> 
> As #15842 issue is not directly testable (the issue happens mostly while using debug app), I am skipping manual testing and merging PR. Will that be ok?

Hi @Parveshdhull, Sure. Just checked the last build. PR can be merged. Thank you!

**Pull request merged**
