### PR TITLE
Feature fix/ttt settings

### PR DESCRIPTION
**Pull request by yenda**
Splitted the final touches to the settings part of ttt to limit scope of the final ttt PR

- settings are stored in a manifest that is pointed at by the contract
- during login the contract is checked to fetch the settings

### Steps to test

On Ropsten on an account with some test eth, go to settings and set up tribute to talk, try recovering the account on another device (should fetch the settings), try changing network (shouldn't keep settings).

status: ready

### CODE REVIEW

**Review by goranjovic — APPROVED** [review]

**Comment by yenda** [comment]
@siphiuel Can you review it so we move to testing?

**Review by vitvly — APPROVED** [review]

**Comment by yenda** [comment]
@churik Ready to test

**Comment by churik** [comment]
@yenda @rachelhamlin @hesterbruikman 
I think that for sure should be fixed 1, 2, 3, 4, 6.
5 should be elaborated. 11 is a question.
Lower prio IMO but still can happen for 7, 9 - so medium to fix as for me.
Definitely can go with 10 (minor)

Please tell if you have another opinion.

#### 1) Missing labels in user profiles
**Severity:** critical
*Steps:*
- join any public chat
- tap on user icon

*Expected result:* can see all labels
*Actual result:* photo_2019-04-25 12 01 39
*Severity:* critical

#### 2) TTT looks enabled when it is not on "Share my profile" and "Receive" screens
**Severity:** critical
*Steps:*
- install build
- open wallet > receive (also the same on Profile > "Share my profile")

*Expected result:* no additional label that TTT is enabled 
*Actual result:* label "You have TTT enabled"
photo_2019-04-25 11 57 35


#### 3) TtT is shown as '0 SNT' after you set up and open settings (on Android) or erased at all (IOS)
**Severity:** critical
*Steps:*
- install build
- create new account and send to it some STT
- go to Profile > Set TtT (i.e. 10 SNT )
- wait until the transaction is completed
- got to profile > TTT > tap on it
- go back

*Expected result:* TTT is still 10 SNT
*Actual result:* 

nottt
On IOS value is erased and you are again and app suggests to start over from 1 step.
The issue is not reproducible if you relogin after setting up TTT (so only when you set TTT for very first time)

#### 4) White bottom panel on "Send transaction" screen when setting up TtT (Android 8, LG V20)
**Severity:** high
*Steps:*
- install build
- go to Profile > Set TtT
- pay attention to "Send transaction" screen

*Expected result:* no bottom panel
*Actual result:* 
sdasdasd
Also reproducible when sending transaction from wallet and open Transaction Fee option (it is not reproducible on nightly - normal bottom panel is shown)

#### 5) No fiat value is shown when TTT is set
Probably (but I'm not sure) this is because of ropsten

#### 6) When go to TTT settings on "Pending confirmation" state, it has shown the state that is not valid yet (or already)
**Severity:** high
*Steps:*
- install build
- go to Profile > Set TtT (i.e. 10 SNT )
- in "Pending confirmation" open Profile > Set TtT

*Expected result:* "Pending confirmation" screen
*Actual result:* it looks like 10 SNT is already set but it is not
The similar problem when you remove TtT - in "Pending confirmation" state it is shown that TtT is still enabled, so previous state.
I don't think that's a good idea to give users edit setting when the transaction is not completed yet (or at least have 3 confirmations) - it can cause other issues from my POV.


#### 7) When editing TTT settings and go back to profile before the last step - all setting are shown as saved
**Severity:** medium
*Steps:*
- go to Profile > Set TtT (i.e. 10 SNT )
- tap on TTT > edit
- set new amount (20 SNT) and message
- go back to profile

*Expected result:* 10 SNT is set in profile 
*Actual result:* 20 SNT is shown in profile


#### 8) Can set 0.0 SNT as TtT - "Continue" button is enabled
**Severity:** low

#### 9) 'TypeError: Network request failed' if connection is lost during TTT setup
**Severity:** medium
- go to Profile > TTT
- go to airplane mode
- try to set TTT

*Expected result:* message that feature is unavailable in offline
*Actual result:* 'TypeError: Network request failed' on signing transaction
When go back to online, should start over.
photo_2019-04-25 14 59 00


#### 10)  TtT is marked as NEW after relogin even if you opened it already
**Severity:** low
*Steps:*
- go to Profile > open TtT
- go back. there is no "New" label anymore
- close and open app

*Expected result:* no "new"  label anymore
*Actual result:* TtT is shown as NEW

#### 11) Question - setting up TtT is available only on ropsten now, yep?

**Comment by hesterbruikman** [comment]
Thanks @churik great work.

> I think that for sure should be fixed 1, 2, 3, 4, 6.

Agreed to 1,2,3,4,6 For 6 I'll check the design. To see if there actually is a pending state for the set TTT screen.

> 5 should be elaborated. 11 is a question.
> Lower prio IMO but still can happen for 7, 9 - so medium to fix as for me.

I would classify 7 as severe, but I don't see the behavior you describe in the gif, it actually looks to me like the edit to 100 SNT is not saved as expected.
Regarding 9 @yenda @siphiuel how much control do you have over the error message here. Looks like this is just a copy update. Please confirm I can provide an alternative.

> Definitely can go with 10 (minor)

**Comment by yenda** [comment]
#### 1) Missing labels in user profiles
fixed

> #### 2) TTT looks enabled when it is not on "Share my profile" and "Receive" screens

fixed

> #### 3) TtT is shown as '0 SNT' after you set up and open settings (on Android) or erased at all (IOS)

should be fixed

> #### 4) White bottom panel on "Send transaction" screen when setting up TtT (Android 8, LG V20)

can't reproduce, is it specific to that model? I don't see what can cause this in this PR, can you check in tomorrows nightly as well?

> #### 5) No fiat value is shown when TTT is set

yes ropsten crypto doesn't have any value, it's a utopia

> #### 6) When go to TTT settings on "Pending confirmation" state, it has shown the state that is not valid yet (or already)

fixed

> #### 7) When editing TTT settings and go back to profile before the last step - all setting are shown as saved

fixed

> #### 8) Can set 0.0 SNT as TtT - "Continue" button is enabled
> **Severity:** low

fixed

> #### 9) 'TypeError: Network request failed' if connection is lost during TTT setup
> **Severity:** medium
> 
> * go to Profile > TTT
> * go to airplane mode
> * try to set TTT

Will show the transaction has failed screen and behave the same for now, need a copy here if you want to show something different

> #### 10) TtT is marked as NEW after relogin even if you opened it already
 fixed/can't reproduce

> #### 11) Question - setting up TtT is available only on ropsten now, yep?
yes

**Comment by churik** [comment]
@yenda looks great to me, much better now!
2 more issues found:
#### 12) Missing label for token names
**Severity:** critical
*Steps:*
- open wallet > manage assets
*Expected result:* can see all labels
*Actual result:* 
saasdasd

#### 13) Can't set TtT with decimals 
**Severity:** high
*Steps:*
- set TtT with decimal part, i.e. 10,1
- wait until transaction is completed
*Expected result:* TtT is 10,1 SNT
*Actual result:* TtT is 10 SNT

**Comment by rachelhamlin** [comment]
Thanks for the thorough testing @churik and quick fixes @yenda. 

Two comments.

**Tx failure error state - insufficient gas**
I don't have enough eth for gas in my test wallet and got a transaction failed message right away when trying to create the setting. 

It goes from "Waiting to sign transaction" to "Transaction failed" and there is no further detail—whether it's a wallet feature or a TtT error state, I think it would be really helpful in the future if we explained why this particular failure is happening. Wallet can validate that I don't have enough ETH for gas, right? And so Status should be able to too?

Alternatively we could offer some pointers about common reasons for tx failure in the error screen copy. Wdyt about that @hesterbruikman?



Also @yenda silly but important for polish—can we please capitalize both letters in `OK`? 

**Scroll behavior on feature info screen**
This is a kind of funky scroll behavior in my opinion. On the TtT settings `Learn more` screen, I have to hold my thumb to scroll far enough to read all of the copy. Releasing screen scrolls up and cuts off the bottom paragraph.

**Comment by yenda** [comment]
@churik 12 and 13 should be fixed

@rachelhamlin I think you are trying on mainnet? It goes to failed state straight away because the contract doesn't exist on mainnet

**Comment by yenda** [comment]
@rachelhamlin scrolling in learn more should be fix

regarding better UX flow I suggest we bounty these once the copy is defined so we can move on to more important issues

**Comment by rachelhamlin** [comment]
> @rachelhamlin I think you are trying on mainnet? It goes to failed state straight away because the contract doesn't exist on mainnet

🤦‍♀️ Problem solved. I wondered why I didn't get a wallet screen anyway. 

Thanks for fixing scroll issue.

**Comment by yenda** [comment]
@churik can you retest please? current build is not important it is just for the OK, got it button, what is built is already containing other fixes. Also keep in mind that this is merged behind a flag so not accessible to users

**Comment by churik** [comment]
@yenda I'll retest on Monday. Currently in the middle of other PR.
Thanks for fixes.

**Comment by hesterbruikman** [comment]
> Alternatively we could offer some pointers about common reasons for tx failure in the error screen copy. Wdyt about that @hesterbruikman?

Excellent point, we should be doing this in general. I am still to set up guidelines so that we can unify error messages. Agree with @yenda we can change copy later through a bounty. Specifically for the "Not enough ETH for gas" I think it should be ok for now; When using on Ropsten (or contract chain) at least you get a message inside the wallet, which I think is also most appropriate.

Great work on the rapid fixes @yenda @siphiuel!

**Comment by churik** [comment]
@yenda 
#### 14. Button "Ok, got it" was changed to "OK, got it"  (see https://ethstatus.testrail.net/index.php?/tests/view/600779).
Was it intentionally?

#### 15. Wrong value is shown when editing amount of TTT
Steps:
- set TtT with decimal part, i.e. 10.1
- wait until transaction is completed
- open TTT, tap on Edit
Expected result: 10.1 SNT on Step 1
Actual result: 1010000000000000000000 SNT

Monosnap 2019-04-29 10-54-53

**Comment by yenda** [comment]
@churik 14 was requested by @rachelhamlin, 15 should be fixed in a moment

sorry for 15 it was an obvious one, my testing skills were really bad last Friday, seems like I only checked settings ttt and recovering but not editing

**Comment by yenda** [comment]
@churik ready for testing

**Comment by yenda** [comment]
@churik I removed the commit that enables ttt so from now on the purpose of the tests is just to check that ttt is disabled

I will check on Android:
- no trace of ttt in profile
- no trace of ttt in share qr code
- check list items in wallet assets settings (as there was a bug there in this build)

let me know if you have other ideas of what could go wrong

**Comment by churik** [comment]
@yenda 
please, before merge:  change 228 line in https://github.com/status-im/status-react/blob/develop/test/appium/views/profile_view.py ("Ok, got it" to "OK, got it" )- you erased my commit when force-pushed.

After this ready to merge from my POV.

**Comment by yenda** [comment]
@churik my bad thanks for the heads up

**Pull request merged**
