### PR TITLE
[DO NOT MERGE]Test react-native-desktop popup changes 

### PR DESCRIPTION
**Pull request by rasom**
Do not commit!

Summary:
This is a test PR to check that changes in react-native-desktop (status-im/react-native-desktop#363) don't have negative impact on Status desktop.

Steps to test:
Open Status
Check it all!
status: wip

status: ready

### CODE REVIEW

**Comment by vkjr** [comment]
@churik, could you please check that my changes in `react-native-desktop` has no negative impact on status-react?

**Comment by churik** [comment]
@rasom @vkjr please, rebase it on current develop

**Comment by churik** [comment]
and also please explain, is it is possible what areas can be affected by this  - chatting, UI, popups (I suppose it is right area according to https://github.com/status-im/react-native-desktop/pull/363, or something more)
Thanks!

**Comment by vkjr** [comment]
@churik, build that was made 6 hours ago was already rebased.
Rebased it one more time :)

In `react-native-desktop` I made `View` components able to catch mouse events. That fixed popup closing issue. So it worth checking if all clicks on components work as before.

**Comment by churik** [comment]
@vkjr 

**1. When I tap outside this window, popup isn't closed**
spam_1
To trigger it you need to send 10+ messages in row (quickly)

**2. Issues with quick typing in message input field and in recovery phrase field came back in this PR.**
Caret is jumping through several chars when typing fast in text input area
Video: http://take.ms/0yoOo

**Comment by vkjr** [comment]
@churik, on your picture is `Alert`. It shouldn't be closed by clicking outside.
This fix is for the issue - https://github.com/status-im/react-native-desktop/issues/321
And it is about using 3rd party implementation of popups - `react-native-menu-popup`.
We don't have them yet in `status-react`, so you won't see the fix itself :(

Will check TextInput, shouldn't really be affected at all by changes.
Thanks.

**Comment by churik** [comment]
@vkjr 
I don't know the reason (not rebased or your branch in RN-desktop is not up-to date) - but I can say for sure - I can see problem with test input in this build https://github.com/status-im/status-react/pull/6218#issuecomment-428618333 and cannot see it in latest nightly (13/10/2018), so I'm considering this  as regression.
Make sure that it is up-to-date, thank you!

**Comment by vkjr** [comment]
@churik, rebased rnd pr. Now everything is ok with textinput.

**Comment by vkjr** [comment]
@SlizkovaGanna, could you please take a look?
Thanks.

**Comment by SlizkovaGanna** [comment]
@vkjr 
I see no issues with text input, but I can see an issue with deleting a group chat specifically on iOS in this PR (the issue https://github.com/status-im/status-react/issues/6289) - could you please rebase it?

@errorists @vkjr 
Also, could you please help me with this:
**Alert** pop-up 'Sorry, we limit sending several messages in quick succession to prevent spam. Please try again in a moment' does not close on the outside click, but other (presumably) alert pop-ups do. For example, the warning one when changing a mailserver is closed on click outside:

image

Or this one, about a message being copied to your clipboard is also closed on clicking outside:

image

So, what should be the consistent behavior for desktop?

Tested on:
mobile: iOS 12.0.1 
desktop: MacOS 10.13.4

**Comment by errorists** [comment]
> So, what should be the consistent behavior for desktop?

cc @EugeOrtiz My 2 gwei, alerts shouldn't be dismissed on clicking outside. The reason for which, users shouldn't be left figuring out whether clicking outside triggers the negative 'Cancel' / 'No' action or positive 'Ok' / 'Yes'.

**Comment by churik** [comment]
@SlizkovaGanna 
about IOS build - this RNd PR, so I don't think we need to test IOS build for merging these changes. (eventually, PR will be closed, changes will go to https://github.com/status-im/react-native-desktop repo which used only for desktop - @vkjr fix me if I'm wrong here).
And I think it is not the right place to discuss the behavior of popups, it should be placed separately.

@vkjr didn't notice any other regression issues, so free to merge changes 


<blockquote><div> GitHub</div><div><strong><a href="https://github.com/status-im/react-native-desktop">status-im/react-native-desktop</a></strong></div><div>A Desktop port of React Native, driven by Qt, forked from Canonical - status-im/react-native-desktop</div></blockquote>

**Review by yenda — CHANGES_REQUESTED** [review]
I request change to block the merge in case the DO NOT MERGE warning is not obvious enough for someone who sees Test OK and feels like merging :smile:

**Comment by vkjr** [comment]
@SlizkovaGanna, I'm not sure why there is a difference between closing different alert popus. Agree that "cancel/confirm" dialog shouldn't be closed by clicking outside.

@yenda, @churik, thanks!

**Pull request closed without merging**
