### PR TITLE
enable proguard, modify rules & upgrade okhttp lib

### PR DESCRIPTION
**Pull request by siddarthkay**
## Summary

This PR turns on `proguard` optimisation and asset minification.

Screenshot 2024-05-10 at 7 30 54 PM

This PR should help shave off a few MBs from PR and release builds.
After enabling `proguard` we get a savings of  ~ `4 MB`.

## Testing notes
Should just impact APK size but please do a basic smoke test.

## Platforms
- Android

status: ready

### CODE REVIEW

**Review by cammellos — APPROVED** [review]

**Review by mohsen-ghafouri — APPROVED** [review]

**Review by BalogunofAfrica — APPROVED** [review]

**Comment by siddarthkay** [comment]
hmm turning on `proguard` saved us around `4MB` I think I can do better than that.

**Review by Parveshdhull — APPROVED** [review]

**Comment by siddarthkay** [comment]
> I think I can do better than that.

Logged a separate issue for this -> https://github.com/status-im/status-mobile/issues/19987 might require some more research.

**Comment by siddarthkay** [comment]
The latest E2E failures are due to 
Screenshot 2024-05-11 at 10 09 16 PM

**Comment by siddarthkay** [comment]
I see a `proguard` rule related fix in `okhttp` version `4.11.0` -> https://square.github.io/okhttp/changelogs/changelog_4x/#version-4110

> Fix: Embed Proguard rules to prevent warnings from tools like DexGuard and R8. These warnings were triggered by OkHttp’s feature detection for TLS packages like org.conscrypt, org.bouncycastle, and org.openjsse.

we are currently on `okhttp` version `4.9.2` -> https://github.com/status-im/status-mobile/blob/f50ca4606f0e92ffc45900e468139242aa44fb3e/android/app/build.gradle#L296

**Review by jakubgs — APPROVED** [review]
A good idea, our size is starting to get out of hand.

**Comment by siddarthkay** [comment]
E2E on this PR is feeling like 

fail

**Comment by siddarthkay** [comment]
Hi @status-im/mobile-qa : could you please take a look at E2E results and let me know the top 2 or 3 issues in this PR which may be the cause of other E2E failures as well?

**Comment by mariia-skrypnyk** [comment]
Hi @siddarthkay !

Asked @yevh-berdnyk to take a look 🙏.

**Comment by yevh-berdnyk** [comment]
hi @siddarthkay, sorry for the delay :(
Issues from e2e tests: 
1. All tests related to communities are failed because Plus button is disappeared from communities screen. We should have an ability to create communities in e2e builds
2. 1-1 and group chats tests are failed because of inability to open an activity center. That is not related to this PR, I'll make a fix and rerun them

**Comment by yevh-berdnyk** [comment]
One more issue, unfortunately:
image
Steps to reproduce:
1. Send an image in 1-1 chat
2. Click on that image


[logcat.log](https://github.com/status-im/status-mobile/files/15314431/logcat.3.log)

**Comment by yevh-berdnyk** [comment]
> hi @siddarthkay, sorry for the delay :( Issues from e2e tests:
> 
> 1. All tests related to communities are failed because Plus button is disappeared from communities screen. We should have an ability to create communities in e2e builds
> 2. 1-1 and group chats tests are failed because of inability to open an activity center. That is not related to this PR, I'll make a fix and rerun them

hi @siddarthkay 
regarding the last e2e results: the most failures are caused by the issue 1

**Comment by siddarthkay** [comment]
> the most failures are caused by the issue 1

Thanks for explaining.
Appreciate your help.

I'll try replicating on `x86_64` simulators on my `linux` box.

**Comment by siddarthkay** [comment]
@yevh-berdnyk : I believe I've fixed the issues, can you pls take a look at the latest E2E result?
I verified on x86_64 Android Emulator.

**Comment by yevh-berdnyk** [comment]
> @yevh-berdnyk : I believe I've fixed the issues, can you pls take a look at the latest E2E result? I verified on x86_64 Android Emulator.

hi @siddarthkay, thank you for the fixes! Remaining e2e failures are not related to this pull request

**Comment by pavloburykh** [comment]
@siddarthkay I have performed a basic manual test, no issue from my side. Ready for merge.

**Pull request merged**
