### PR TITLE
fix: add spacing between wrong-password error and forgot-password link

### LINKED ISSUE #21207: Missing spacing in the Wrong password message
# Design Feedback 2.30

## Missing spacing in the Wrong password message
The error message about the wrong password has a missing space between _**Oops, wrong password!**_ and the action _**Forgot password?**_ causing the action to be hard to click, resulting in poor UX.

Figma review [here](https://www.figma.com/design/oznddnBnDbLlLQIaACYNuj?node-id=2249-7147#936081118)

#### Expected behavior

Screenshot 2024-09-06 alle 15 52 34

#### Actual behavior

Screenshot 2024-09-06 alle 15 53 17

### Reproduction

1. Log out of your profile
2. Log in using a wrong password

### Additional Information

- Operating System: Android, iOS
- Devices in the screenshots: iPhone 13, Realme 10

### PR DESCRIPTION
**Pull request by seanstrom**
fixes #21207

### Summary

* This PR attempts to fix an appearance issue when submitting an incorrect password when attuning to sign-in to a profile. Now the "oops, wrong password" error message and the "forgot password?" link will have spacing between them.

#### Platforms

- Android
- iOS

##### Functional

* Places where the password input is used for authentication, for example:
  * Profile login

### Steps to test

- Open Status mobile app
- Attempt to sign-in to a profile with the wrong password
- Confirm that the wrong-password error message and the forgot-password link are spaced correctly.

#### After changes

Screenshot 2024-11-06 at 10 35 13

status: ready

### CODE REVIEW

**Review by ulisesmac — APPROVED** [review]
Thanks for fixing it, it annoys me a lot!

**Review by ilmotta — APPROVED** [review]

**Comment by mariia-skrypnyk** [comment]
Hey @seanstrom !

Do you need any help from QA side?

**Comment by seanstrom** [comment]
Hey @mariia-skrypnyk 👋 

I think I just need a quick check on e2e tests, I think my changes should be unrelated to any failures.
If I'm all good on e2e stuff, I'll move this through to design review 🎨

**Comment by yevh-berdnyk** [comment]
Hi @seanstrom, e2e failure is not PR related, thanks!

**Comment by seanstrom** [comment]
@Francesca-G I think this PR is ready for a design-review 🙏

**Review by Francesca-G — APPROVED** [review]
Looks good ✨ thanks for the fixes!

**Pull request merged**
