### PR TITLE
ci: fetch E2E APK from android-e2e jobs

### PR DESCRIPTION
**Pull request by jakubgs**
Using `copyArtifacts()` is more reliable and faster then fetching APKs based on URLs acquired by parsing GitHub comments from Jenkins builds.

### CODE REVIEW

**Comment by jakubgs** [comment]
Looks like it's working:
```
Copied 1 artifact from "[status-mobile » prs » android-e2e » PR-14993](https://ci.status.im/job/status-mobile/job/prs/job/android-e2e/job/PR-14993/)" build number [4](https://ci.status.im/job/status-mobile/job/prs/job/android-e2e/job/PR-14993/4/)
```
```
+ python3 -m pytest --numprocesses 4 --rerun_count=2 --testrail_report=True -k  --apk=/home/jenkins/workspace/status-mobile/e2e/test-copy-apk-status-apps-prs/result/StatusIm-Mobile-230206-153659-08cdee-pr14993-x86.apk --build=PR-14993-230206-164906 --pr_number=14993 -m new_ui_critical
Testrun: https://ethstatus.testrail.net/index.php?/runs/view/10987
Start upload file

Upload time 0:00:00.../ .🐱.............
```
Those emojis in progress bar tho...

**Comment by jakubgs** [comment]
This is the progress bar function:
https://github.com/Slamnlc/saucelab-api-client/blob/0605f70799273dc5b273af5bf88d8cde96d8581f/saucelab_api_client/models/service.py#L67-L103
And here it's use in `upload` method:
https://github.com/Slamnlc/saucelab-api-client/blob/6be97d33d5d40e8e5dede12a3c2f47870700a1ad/saucelab_api_client/base_classes/storage_api.py#L79
Looks like it's hardcoded...

**Comment by jakubgs** [comment]
I want to drop the `APK_NAME` argument, but that might break how the github bot starts jobs.
The best way is to leave it be for now, and remove it once it's removed from the bot separately.

**Review by churik — APPROVED** [review]
thank you!

**Comment by jakubgs** [comment]
The changes for `ci/tests/Jenkinsfile.e2e-prs` are tested and working, but other two `Jenkinsfiles` have not been tested.

I'm going to merge this, but `ci/tests/Jenkinsfile.e2e-nightly` and `ci/tests/Jenkinsfile.e2e-upgrade` probably need more work.

**Pull request merged**
