### PR TITLE
[WIP]: Fallback flow for pairing

### PR DESCRIPTION
**Pull request by cammellos**
This PR adds a fallback flow in case syncing does not work.

The flow is as follow:

1) If the syncing fails, the empty device (A2) will be prompted to enter their seed phrase.
2) Once logged in A2 will show a popup with their own installation id
3) On A1, it should show a prompt with A2 installation ID and an option to "Enable and Sync"
4) If enable and sync is clicked, the devices should be now paired, and data transfer should happen.

Devices need to be connected to the internet for this to work, but don't need to be on the same network.

I have tested the happy path yesterday, and the two devices are paired correctly, there's some issues with the actual data being synchronized, but @qfrank will be looking into it, he will be taking over the status-go pr.

@xAlisher can share the design and flows.

Things left to do:

###  fire pair installation when generating a code, to facilitate correct discovery

When displaying a QR code from the sending device, it would be nice if we could call `SendPairInstallation` RPC, so that metadata is available.

### Styling & translations

Styling and translations needs to be checked

### Double modal 

When/if the data confirmation modal is merged, there could be a clash of modals when logging in if the user of the receiving pair is on mobile network (i.e two modals opened at the same time), something to watch out for.

### Testing

Please use this PR for both A1 & A2, as this is a breaking change 2.30 will only local pair with 2.30. Or you can use desktop if @jrainville has finished with his part.

Client A1 is logged in
Client A2 is logged out

1) Client A1 shows a QR code
2) Client A2 goes offline/mobile data, Client A2 scans a QR code (it should fail).
3) If connection fails on A2, the user will be prompted to enter a seed phrase. Make sure you are connected now.
4) If the generated account matches the `key-uid` from the QR code, A2 should call `FinishPairingThroughSeedPhraseProcess` with the installation id passed in the QR code. This will send installation information over waku. The user should be shown its own installation id and prompted to check the other device.
5) Client A1 will receive new installation data through waku, if they are still on the qr code page, they should show a popup to the user showing the received installation id, and a way to `Enable and Sync`, which should call the `EnableAndSyncInstallation` endpoint. This should finish the fallback syncing flow.

Other areas of testing: Pairing flow when no error is returned.

Status-go pr: https://github.com/status-im/status-go/pull/5567

### CODE REVIEW

**Comment by Parveshdhull** [comment]
Issues so far

- [ ] when A1 and A2 can sync successfully without waku, I saw A1 show the popup, this is not we should expect.
- [x] based on issue1,  press continue, A2 will stuck as 3rd screenshot(A2 screenshot2) shows, restart A2 can login successfully. (Please also test https://github.com/status-im/status-mobile/pull/20725, as issue/fix is related to that)
- [x] Syncing progress screen style is broken (only taking half screen)

I am working on these issues. CC @qfrank @churik 

UPD: pushing fix for last 2 issues in separate PR - https://github.com/status-im/status-mobile/pull/20883

**Comment by Parveshdhull** [comment]
Marking the PR as draft for now, as its moved to next milestone

**Comment by ilmotta** [comment]
On top of what @Parveshdhull shared above https://github.com/status-im/status-mobile/pull/20766#issuecomment-2250061072 Given the circumstances and the tight schedule for 2.30 and available capacity for QA, we have decided that:

1. We should try to get the status-go PR merged before 2.30 is out https://github.com/status-im/status-go/pull/5567 because it's safe to do so.
2. On the clients, we can adapt the connection string to adjust to the breaking change and still be compatible with 2.29.
3. We are not going to try to implement the UI changes for 2.30.

cc @qfrank

**Comment by qfrank** [comment]
> On the clients, we can adapt the connection string to adjust to the breaking change and still be compatible with 2.29.﻿

yeah, v2.30 can parse QR generated by v2.29, but not the other way around. We may ignore the opposite use case, I mean ppl won't use v2.29 to scan the QR generated by v2.30 right?
﻿

> We are not going to try to implement the UI changes for 2.30.

so once status-go PR get merged, we actually won't support fallback flow for pairing for v2.30? according to this [message](https://discord.com/channels/@me/1260881735420215378/1266051074729709661), we will support it in v2.30.1 ?

@ilmotta

**Comment by ilmotta** [comment]
> > On the clients, we can adapt the connection string to adjust to the breaking change and still be compatible with 2.29.
> 
> yeah, v2.30 can parse QR generated by v2.29, but not the other way around. We may ignore the opposite use case, I mean ppl won't use v2.29 to scan the QR generated by v2.30 right? ﻿
> 
> > We are not going to try to implement the UI changes for 2.30.
> 
> so once status-go PR get merged, we actually won't support fallback flow for pairing for v2.30? according to this [message](https://discord.com/channels/@me/1260881735420215378/1266051074729709661), we will support it in v2.30.1 ?
> 
> @ilmotta

~Yes for both questions @qfrank :) We are descoping the fallback feature (on the UI/front) for 2.30 due to risks and capacity to QA the work adequately in the face of other priorities.~

Edit: Further discussions with the desktop team led to a different decision. @cammellos will reach out to you @qfrank until Monday for more technical details.

**Comment by ilmotta** [comment]
Hey @qfrank, can we close this PR for now given PR https://github.com/status-im/status-go/pull/5614 won't require changes in clients once merged?

**Comment by qfrank** [comment]
> Hey @qfrank, can we close this PR for now given PR [status-im/status-go#5614](https://github.com/status-im/status-go/pull/5614) won't require changes in clients once merged?

I think so, we can reopen it later or create new one if needed

**Pull request closed without merging**
