### PR TITLE
Features/allow specify password mailserver

### PR DESCRIPTION
**Pull request by cammellos**
### Summary:

Allow to specify different password for mailservers, this is needed in order to use custom mailservers. 

No existing functionality will be changed, it only adds the ability to connect to custom mailservers with different passwords.

### Testing
Light regression testing only on fetching from mailserver, as new feature is behind a toggle, but parts of the codebase has been changed.

status: ready

### CODE REVIEW

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/9LxivC for branch PR-4517

<blockquote><div><strong><a href="https://i.diawi.com/9LxivC">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/5crBGo for branch PR-4517

<blockquote><div><strong><a href="https://i.diawi.com/5crBGo">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/kwDqbG for branch PR-4517

<blockquote><div><strong><a href="https://i.diawi.com/kwDqbG">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/sqw2KX for branch PR-4517

<blockquote><div><strong><a href="https://i.diawi.com/sqw2KX">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Review by janherich — APPROVED** [review]

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/YRSJPV for branch PR-4517

<blockquote><div><strong><a href="https://i.diawi.com/YRSJPV">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/Z6vRBK for branch PR-4517

<blockquote><div><strong><a href="https://i.diawi.com/Z6vRBK">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Review by dmitryn — APPROVED** [review]

**Review by yenda — APPROVED** [review]

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/STkv7i for branch PR-4517

<blockquote><div><strong><a href="https://i.diawi.com/STkv7i">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/19r7Zy for branch PR-4517

<blockquote><div><strong><a href="https://i.diawi.com/19r7Zy">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Pull request merged**
