### PR TITLE
include current commit-sha next to desktop app version

### LINKED ISSUE #5140: Make application version more informative
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a QA/developer, I want to know what exact version of app I used to make sure I installed build with right changes.

### Description

*Type*: Feature
*Summary*: 
For now, version for desktop is the same through different PRs (V0.0.1) and it is not associated with Jenkins build (it is just read from a file).  For testing purposes it would be very convenient to use additional version which will point to list of specific changes.

The example in mobile “0.9.21 (6181) node a339d7e”:
* Main version (0.9.21): https://github.com/status-im/status-react/blob/develop/VERSION
* Specific version number (in parentheses, 6181): https://github.com/status-im/status-react/blob/develop/scripts/build_no.sh
* Node: node commit hash
All commits that are built get tagged with `build-${number}`, which can be found in Jenkins log.

### Solution

*Summary*: 

Add specific version to status-desktop app, i.e. based on commit sha to see what exact build is installed.

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/status-im/status-react">status-im/status-react</a></strong></div><div>status-react - a free (libre) open source, mobile OS for Ethereum</div></blockquote>
<blockquote><div> GitHub</div><div><strong><a href="https://github.com/status-im/status-react">status-im/status-react</a></strong></div><div>status-react - a free (libre) open source, mobile OS for Ethereum</div></blockquote>

### PR DESCRIPTION
**Pull request by rcullito**
Fixes #5140 

includes the commit sha of the current branch next to the app version

### CODE REVIEW

**Review by vitvly — APPROVED** [review]

**Review by maxhora — APPROVED** [review]
👍

**Review by vkjr — APPROVED** [review]

**Review by goranjovic — APPROVED** [review]

**Comment by churik** [comment]
@rcullito where can I find it in Jenkins build?
for example, I'm currently using this [build](https://jenkins.status.im/job/status-react/job/desktop/job/pull-requests/view/change-requests/job/PR-5143/2/)
App shows that version is `ea5c125f`
I cannot find this value [here](url) or in GitHub:
vers
Also I coudn't find it in [console output](https://jenkins.status.im/job/status-react/job/desktop/job/pull-requests/view/change-requests/job/PR-5143/2/console).

**Comment by rcullito** [comment]
@churik looking into this now as it made sense during development but will have to check for the built version of the app. have moved back to `contributor` for now. thanks!

**Comment by rcullito** [comment]
jenkinsbuildrevision
desktopappimagebuild

@churik so I verified that once the jenkins job completes there will be a revision number for that specific build of the PR and that is the commit-sha that will be abbreviated in the app itself. I've attached a couple of screenshots from both Jenkins and the desktop app to clarify, and if you want to check the link for this it is: https://jenkins.status.im/job/status-react/job/desktop/job/pull-requests/job/PR-5143/4/

Hopefully that's reproducible, but let me know if you have any other questions! Moving back to `To Test` for now. 

<blockquote><div><strong><a href="https://jenkins.status.im/job/status-react/job/desktop/job/pull-requests/job/PR-5143/4/">status-react » desktop » pull-requests » PR-5143 #4 [Jenkins]</a></strong></div></blockquote>

**Comment by churik** [comment]
@rcullito I believe this was caused by several commits in one build.
If I face with this once more, I'll create separate issue.

**Pull request merged**
