### PR TITLE
[FIX #2636] Add script for merging external contributions

### LINKED ISSUE #2636: Merge PR script from external contributor with code signing
### User Story

As a developer, I want all commits that make it into develop to be code signed by a core contributor's PGP key so that I know the certified source of changes introduced in our code base.

### Description

*Type*: Feature/Tooling

*Summary*: Write a script that automate most parts of merging a PR from an external contributor while still signing the commit from the command line.

For context: https://github.com/status-im/status-react/pull/2611 for merge script for core contributors, and https://wiki.status.im/Code_signing_commits_into_develop.

#### Expected behavior
Something like: `./merge-external-pr.sh REMOTE BRANCH` (some manual action) and then commit shows up in `develop` branch, GPG signed by person running script and authored by person submitting initial commit.

While it'd be nice if PR was created automatically it isn't necessary. For example script can prompt you to do action in UI and then continue once you confirmed X is done. Perhaps it ends up being two scripts, as PR needs to be reviewed with our current Github trust model.

Preferably written in a similar style as `merge-sh` (short, self-contained, documented). Optional dependency: something that simplifies pull request dealings (such as hub by Github).

Nice to have but very optional: flow that makes external PRs appear as merged as opposed to closed. No idea how this is possibly though without introducing other branches.

#### Actual behavior
Either no code signing (or Github only) or a quite cumbersome manual process as outlined in Wiki.

### PR DESCRIPTION
**Pull request by dottedmag**
Pulls, rebases, displays, signs and pushes external contributions.

If jq(1) and curl(1) are available, can pull data from GitHub and
mark PRs as closed, otherwise only code merging works.

### CODE REVIEW

**Comment by yenda** [comment]
GH PRs normally are automatically marked as merged if they are merged from the command line as far as I know.

**Comment by dottedmag** [comment]
This patch squashes, signs the commit and submits it from a different branch, so it is no longer a part of original pull request.

**Comment by oskarth** [comment]
@dottedmag Thanks for the contribution, good start!

> Add a remote to your repository: git remote add <name> <url>
> Fetch it: git fetch <name>
> Review the commits: git log <name>/develop..<name>/<pr-branch>

Can we script these things? Parameterize as so you run `./merge-external.sh <ARGS>` and then these things happen. For example, in `merge-pr.sh` it interactively prompts you to rebase - something similiar could happen here w.r.t reviewing commits.

> Note that GitHub PR will be left dangling and needs to be closed manually as there is no good way to manipulate GitHub PRs from the command line (neither from Bash, nor using hub(1)),

You mean the original PR right? Seems like it from code.

**Review by oskarth — CHANGES_REQUESTED** [review]
See feedback in comment

**Comment by dottedmag** [comment]
I'm adding steps to pull the PR remote/branch, can be either queried from GitHub via PR number (if `curl` and `jq` are available) or specified manually.

If `curl` and `jq` are available, then I can also mark the PR as merged in GitHub (by pushing signed commits back to the PR branch, if allowed on GitHub).

**Comment by dottedmag** [comment]
Should I squash all the commits automatically, or is it better to keep them as is, and add a sign-off and a signature to each?

**Comment by oskarth** [comment]
> I'm adding steps to pull the PR remote/branch, can be either queried from GitHub via PR number (if curl and jq are available) or specified manually.

Great! I think it'd also be OK to require `curl` and `jq` to be installed as these are quite standard and useful tools on any Unix-based systems. But if it can be specified manually too that's even better :)

> Should I squash all the commits automatically, or is it better to keep them as is, and add a sign-off and a signature to each?

Ideally contributor squashes beforehand, but we can also squash automatically. I don't think there's a case where we want to keep all commits as they are, as we generally prefer a more  "linear and atomic" git history.

**Comment by dottedmag** [comment]
Please try this one. Pulls PRs, previews them, squashes, signs and merges if OKayed. If "Allow edits from maintainers" option is selected in PR (which happens to be a default setting), then it also updates PR with the signed commit, so the PR will be marked as merged.

Correctly deals with PRs authored by several people (by appending author information to commit message).

Does not touch `develop` and remote until the very last step, and cleans up if anything happens. 

Can be used in other repositories too, if `merge-external-pr.conf` file is provided, overriding default settings.

**Comment by oskarth** [comment]
@dottedmag Looks great! Unfortunately it looks like I screwed it up a bit - I was trying to use the script to merge it to `develop-pseudo` but ended up with the squash commit above. Any idea of what went wrong? Most obvious thing wrong is that it is me as author, but  it seems like I ended up with a nested squash commit as well. Sorry - would you mind fixing the commit to one squashed by you and I'll try again?

**Comment by oskarth** [comment]
What I did:

Copied script manually and ran `./merge-external-pr.sh 2747`, had to reset a few times to stash/checkout latest develop/abort rebase. Then I also changed the branch target to `develop-pseudo` to verify author info.

**Comment by dottedmag** [comment]
You probably have ran PR merging script twice, first time it squashed my commits and pushed them back, and second time it squashed the squashed commit.

Which is bad, by the way — if there is only single commit on a branch, `merge-external-pr` should not squash it again.

**Comment by oskarth** [comment]
@dottedmag Should I try to run it again?

**Comment by dottedmag** [comment]
Please do.

**Comment by oskarth** [comment]
@dottedmag Seems to still show me as AUTHOR in Github, see https://github.com/status-im/status-react/commits/experiment/develop-mirror and https://github.com/status-im/status-react/commit/3f9cd19de152e91a432bae35d569be404e1a226b

Here's what I did to test:

1. Copy script file to project root dir
2. Make the following changes:

```
diff --git a/merge-external-pr.sh b/merge-external-pr.sh
index 40dd97af..8f6b5bec 100755
--- a/merge-external-pr.sh
+++ b/merge-external-pr.sh
@@ -25,7 +25,7 @@ load_config() {
   : ${OWNER:=status-im}
   : ${REPO:=status-react}
   : ${REMOTE:=origin}
-  : ${BRANCH:=develop}
+  : ${BRANCH:=experiment/develop-mirror}
 }
 
 check_pr_prereq() {
@@ -127,11 +127,11 @@ verify_pr() {
 merge_pr() {
   # If PR is specified and can be pushed into, do it to mark PR as closed
   if [[ -n $RW_PR_REPO ]]; then
-      git push -f $PR_REMOTE_NAME $PR_LOCAL_BRANCH-squashed:$PR_BRANCH
+      echo "GITPUSH $PR_REMOTE_NAME $PR_LOCAL_BRANCH-squashed:$PR_BRANCH"
   fi
   git checkout $BRANCH
   git merge --ff-only $PR_LOCAL_BRANCH-squashed
-  git push $REMOTE $BRANCH
+  echo "GITPUSH $REMOTE $BRANCH"
 }
 
 cleanup() {
```

3. Run `./merge-external-pr.sh 2747`
4.  ` git push origin experiment/develop-mirror`

Thoughts? Also as an aside I think it is OK if squash to one commit is required beforehand, not sure if this simplifies things in any way.

**Comment by dottedmag** [comment]
Bummer. I'll check it out. I can throw away squashing code, should make the script way simpler, but keep the check that the branch has only one commit before merging.

**Comment by dottedmag** [comment]
Squashing code was the source of wrong author information.

Now the authorship is preserved, and non-squashed PRs are not merged.

**Review by oskarth — APPROVED** [review]

**Comment by oskarth** [comment]
@dottedmag This is perfect, thank you so much!

image

cc @andytudhope

**Comment by dottedmag** [comment]
Great. Glad it works so smoothly with GitHub. Did you have to close the corresponding issue manually?

**Comment by dottedmag** [comment]
Also, I see "Won USD 553.98 for Merge PR script from external contributor with code signing (payout pending maintainer confirmation)" on open bounty site, could you please confirm?

**Comment by oskarth** [comment]
> Did you have to close the corresponding issue manually?

Nope!

> could you please confirm?

I pinged @andytudhope about this, hopefully he'll respond soon (it's a semi-manual process right now).

**Comment by andytudhope** [comment]
Hey @dottedmag - you bounty payout has just been confirmed: https://etherscan.io/tx/0xbb1d3fe4919b635df7ff32777b49d8c1a37983e8d4d4335aafd16a337a1123c0 👍

**Comment by dottedmag** [comment]
Great, thanks.

**Pull request merged**
