### PR TITLE
[slow sign in] unlock account's db before starting node

### PR DESCRIPTION
**Pull request by rasom**
implements 
> No need to wait for `Statusgo.Login` callback in order to start unlocking realm db: now it is encrypted via key which is derived from user’s password, so we can try to unlock it before starting node. That’s how we will check whether password is correct. Right after that `:home` screen can be shown and starting node/`Statusgo.Login` call might be performed in parallel. **D**

from https://notes.status.im/VxmgW_rJQkqHsPoqGiMGxQ

https://streamable.com/y6p9b a5 0.9.31 (7k unread messages) ~45s
https://streamable.com/g1e36 a5 #6886 (7k unread messages) ~4s
https://streamable.com/acf0q galaxys9 0.9.31 (15k unread messages) ~24s
https://streamable.com/aev7v galaxys9 #6886 (15k unread messages) ~1.3s

# Sign in flow
**How it worked before**
1. User enters password
2. Presses "Sign In"
3. The node is started
4. "node.ready" event received
5. Statusgo.Login is called
6. Statusgo.Login callback
7.
    a. If password is incorrect show error label over input
    b. Otherwise continue
8. Open account's db
9. 
    a. if can't encrypt show error popup
    b. Otherwise continue
10. 
    a. if can't migrate schema show error popup
    b. Otherwise continue
11. Open `:home` screen
12. Load necessary data
13. Show chats
14. Done

old flow

**How it works now**

**Main flow**:
1. User enters password
2. Presses "Sign In"
3. Attempt to open account's db
4. a. If DB file doesn't exist go to **Empty DB flow**
   b. Otherwise continue
5.     
    a. If db can't be encrypted go to **Verify password flow**
    b. Otherwise continue
6.   a. If db can't be migrate DB schema **show migrations failure popup with option to erase DB**
    b. Otherwise continue
7. Procced with **UI flow** and **Statusgo.Login flow**
  
**Empty DB flow**:
1. Verify password
2. a. If password is wrong **show "Wrong password" label**
   b. Otherwise continue
3. Create account's DB (by opening it with correct encryption key)
4. Procced with **UI flow** and **Statusgo.Login flow**

**Verify password flow**:
1. Verify password
2. a. If password is correct **show encryption failure popup with option to erase DB**
   b. Otherwise **show "Wrong password" label**

**Statusgo.Login flow**:
1. Start node
2. "node.ready" event received
3. Statusgo.Login is called
4. Statusgo.Login callback
5. 
    a. If password is incorrect **show error popup (passwords used for db encryption and for account do not match)**
    b. Otherwise continue
6. Done

**UI flow**:
1. Show `:home` screen
2. Load necessary data
3. Show chats
4. Done

img

status: ready

side note: **`Statusgo.Login`** may take more than 10s on slow devices ([see here](https://notes.status.im/DuS3ghwPT0KC81oVIONNKA)), though it doesn't have an impact on signing in now. But still, messaging is not available until account is fully "logged in". @cammellos is going to take a look at this.

### CODE REVIEW

**Review by goranjovic — APPROVED** [review]

**Review by flexsurfer — APPROVED** [review]

**Comment by yenda** [comment]
@rasom: does it work on desktop?

**Comment by rasom** [comment]
@yenda works on mac, i didn't run it on other desktop OS

**Review by yenda — APPROVED** [review]

**Comment by yenda** [comment]
So if I understand correctly `Status.login` is much slower than `Status.verify`? Could you add a comment to mention that?

**Comment by rasom** [comment]
@yenda, currently `Statusgo.VerifyAccountPassword` is faster than`Statusgo.Login`, but we are considering to move heavy stuff which is happening during `Statusgo.Login` into a separate thread, so both methods should be relatively equal (in terms of their duration). Anyway, opening realm db is faster than both these methods, and if it succeeds it also verifies the password. 

The reason why `Statusgo.VerifyAccountPassword` was used is that we can't say for sure that password was wrong if we can't decrypt realm db. It also might be caused by a corrupted db file. `Statusgo.VerifyAccountPassword` is used to double check this.

**Comment by yenda** [comment]
@rasom thanks for the details explanation, that change makes lot of sense. Could you put in a comment in the code I think that's valuable for the next person to touch that code to understand why it was done like this.

**Review by yenda — DISMISSED** [review]
While it is a great change, I think more care should be put into handling the callbacks that happen after login. There is already race conditions in the current login flow and I fear this will add some more, could you investigate the consequences of these changes first? 

I am especially concerned about logout and relogin now that so much stuff is done after the login that was previously done within. It still calls back after you logged out. 

Even on a OnePlus5T I get login before I touch login for some reason (after login out and trying to log in again), sometimes the app hangs and then crashes, sometimes I get stucked on a white screen.

**Review by rcullito — COMMENTED** [review]
@rasom thanks for this and in particular your document on CodiMD shedding more light on the login process and the inner workings of loading.cljs

In terms of realm-db, where in the codebase do we store those messages (and other metadata) in the first place? Is this done once as part of account setup or on a rolling basis of "most recent messages" for subsequent user sessions? (thanks for bearing with me, just trying to understand the larger framework that your PR is addressing)

**Comment by rasom** [comment]
> I am especially concerned about logout and relogin now that so much stuff is done after the login that was previously done within. It still calls back after you logged out.

ok, this one is worth looking into

> Even on a OnePlus5T I get login before I touch login for some reason (after login out and trying to log in again), sometimes the app hangs and then crashes, sometimes I get stucked on a white screen.

@yenda does it happen in `develop` or in this branch? If you can reproduce this in `develop` please create an issue and it will be fixed separately.

also while i was afk i figured that there are at least two more edge cases which are not handled:
1) if db was erased before signing in (after failed migration or because of a corrupted db file) it might happen that user will enter a wrong password but realm db will be opened successfully because a new file will be created. Though `Statusgo.Login` will fail. So we need to check if db file exists and if it doesn't at first call `Statusgo.VerifyAccountPassword` and then proceed with opening db.
2) also as part of the previous case db file might be replaced with another one which is encrypted via different password, and then again if the user enters this "wrong" password realm will be opened but `Statusgo.Login` will fail. I can't imagine the reason for doing that, but let's handle this case too.

Besides that, it seems that we need to write the doc which will explain how it works here and covers different edge cases.

**Comment by rasom** [comment]
@rcullito you can explore `status-im.data-store.*` namespaces, these namespaces contain the code related to realm db. Schemas at `status-im.data-store.realm.schemas.*`, migrations there as well, db management and helper functions (for fetching/storing data) in `status-im.data-store.realm.core`, and entity specific functions at  `status-im.data-store.entity` namespaces (it might be de/serialization if necessary, functions for specific queries, etc).

**Comment by yenda** [comment]
Removing request for change as the issue mentioned appeared even before the PR series on fast login. However if you can make sure there isn't new race conditions that are going to be introduced that'd be great.

**Comment by rasom** [comment]
signin

**Comment by rasom** [comment]
> 1) if db was erased before signing in (after failed migration or because of a corrupted db file) it might happen that user will enter a wrong password but realm db will be opened successfully because a new file will be created. Though `Statusgo.Login` will fail. So we need to check if db file exists and if it doesn't at first call `Statusgo.VerifyAccountPassword` and then proceed with opening db.

> 2) also as part of the previous case db file might be replaced with another one which is encrypted via different password, and then again if the user enters this "wrong" password realm will be opened but `Statusgo.Login` will fail. I can't imagine the reason for doing that, but let's handle this case too.

These two cases are handled now.

**Comment by rasom** [comment]
signin

**Comment by rasom** [comment]
@yenda ready for the next review round

**Review by yenda — APPROVED** [review]
Nioce schemas can you add them to the docs?

**Comment by asemiankevich** [comment]
@rasom 

1. second logout in a row crashed the app which i could not reproduce with nightly build. However i logged very similar issue today https://github.com/status-im/status-react/issues/7070. Could you please confirm the issue described (`second logout in a row crashed the app`) is / is not part of this PR? Thanks.

Steps to repro:
1. Create new account
2. Logout
3. Login to same account
4. Logout

2. `Set device passcode to save password` toggle is not working - expected?

**Comment by rasom** [comment]
@asemiankevich both platforms or ios/android only?

**Comment by rasom** [comment]
@yenda, yes i will do this, but after i merge these PRs because there can be changes

**Comment by rasom** [comment]
@asemiankevich can reproduce on both platforms

**Comment by rasom** [comment]
```
12-11 19:22:14.400  4417  4417 I /system/bin/tombstoned: received crash request for pid 22915
12-11 19:22:14.403 26330 26330 I crash_dump32: performing dump of process 22915 (target tid = 26296)
12-11 19:22:14.404 26330 26330 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
12-11 19:22:14.404 26330 26330 F DEBUG   : Build fingerprint: 'samsung/starltexx/starlte:8.0.0/R16NW/G960FXXS2BRI1:user/release-keys'
12-11 19:22:14.404 26330 26330 F DEBUG   : Revision: '26'
12-11 19:22:14.404 26330 26330 F DEBUG   : ABI: 'arm'
12-11 19:22:14.404 26330 26330 F DEBUG   : pid: 22915, tid: 26296, name: pool-3-thread-1  >>> im.status.ethereum <<<
12-11 19:22:14.404 26330 26330 F DEBUG   : signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
12-11 19:22:14.404 26330 26330 F DEBUG   :     r0 00000000  r1 00000006  r2 cd037d00  r3 00000000
12-11 19:22:14.404 26330 26330 F DEBUG   :     r4 00000001  r5 00000000  r6 00000000  r7 000000ee
12-11 19:22:14.404 26330 26330 F DEBUG   :     r8 00000000  r9 00000000  sl adb2ab60  fp 00000002
12-11 19:22:14.404 26330 26330 F DEBUG   :     ip 00000000  sp 5ede7f9c  lr cb85279c  pc cb86bbac  cpsr 200b0010
12-11 19:22:14.405 26330 26330 F DEBUG   :
12-11 19:22:14.405 26330 26330 F DEBUG   : backtrace:
12-11 19:22:14.405 26330 26330 F DEBUG   :     #00 pc 00226bac  /data/app/im.status.ethereum-aRVXqtxZ_kgL043Ca6nj-Q==/lib/arm/libstatusgoraw.so
12-11 19:22:14.405 26330 26330 F DEBUG   :     #01 pc 0020d798  /data/app/im.status.ethereum-aRVXqtxZ_kgL043Ca6nj-Q==/lib/arm/libstatusgoraw.so
```

**Comment by rasom** [comment]
```
12-11 21:21:27.183  9164  9204 D StatusNativeLogs: panic: runtime error: invalid memory address or nil pointer dereference
12-11 21:21:27.183  9164  9204 D StatusNativeLogs: [signal SIGSEGV: segmentation violation code=0x1 addr=0
12-11 21:21:27.183  9164     0 E Go      : 	/ext-go/1/src/github.com/status-im/status-go/rpc/client.go:97 +0x14
12-11 21:21:27.183  9164  9204 D StatusNativeLogs: x14 pc=0xca7b7210]
12-11 21:21:27.183  9164  9204 D StatusNativeLogs:
12-11 21:21:27.183  9164  9204 D StatusNativeLogs: goroutine 1825 [running, locked to thread]:
12-11 21:21:27.183  9164  9204 D StatusNativeLogs: github.com/status-im/status-go/rpc.(*Client).CallContext(0x0, 0
12-11 21:21:27.183  9164  9204 D StatusNativeLogs: xcb164cd0, 0xa9c9c020, 0xcb0894c8, 0xab4afee0, 0xac935850, 0xd, 0xac4ac5e0, 0x1, 0x4, ...)
12-11 21:21:27.183  9164  9204 D StatusNativeLogs: 	/ext-go/1/src/github.com/status-im/
12-11 21:21:27.184  9164  9204 D StatusNativeLogs: status-go/rpc/client.go:97 +0x14
12-11 21:21:27.184  9164  9204 D StatusNativeLogs: github.com/status-im/status-go/rpc.(*Client).callSingleMethod(0x0, 0xcb164cd0, 0xa9c9c020,
12-11 21:21:27.184  9164  9204 D StatusNativeLogs: 0xabf96240, 0x81
12-11 21:21:27.184  9164  9204 D StatusNativeLogs: , 0x90, 0x90
12-11 21:21:27.184  9164     0 E Go      : github.com/status-im/status-go/rpc.(*Client).callSingleMethod(0x0, 0xcb164cd0, 0xa9c9c020, 0xabf96240, 0x81, 0x90, 0x90, 0xabf96240)
12-11 21:21:27.184  9164     0 E Go      : 	/ext-go/1/src/github.com/status-im/status-go/rpc/call_raw.go:120 +0xe8
12-11 21:21:27.184  9164  9204 D StatusNativeLogs: , 0xabf96240)
12-11 21:21:27.184  9164  9204 D StatusNativeLogs: 	/ext-go/1/src/github.com/status-im/status-go/rpc/call_raw.go:120 +0xe8
12-11 21:21:27.184  9164  9204 D StatusNativeLogs: github.com/status-im/status-go/rpc.(*Clie
12-11 21:21:27.184  9164  9204 D StatusNativeLogs: nt).callRawContext(0x0, 0xcb164cd0
12-11 21:21:27.184  9164  9204 D StatusNativeLogs: , 0xa9c9c020,
12-11 21:21:27.184  9164  9204 D StatusNativeLogs: 0xabf96240, 0x81
12-11 21:21:27.184  9164  9204 D StatusNativeLogs: , 0x90,
12-11 21:21:27.184  9164     0 E Go      : github.com/status-im/status-go/rpc.(*Client).callRawContext(0x0, 0xcb164cd0, 0xa9c9c020, 0xabf96240, 0x81, 0x90, 0xa9d2e280, 0xcb15bd48)
12-11 21:21:27.184  9164  9204 D StatusNativeLogs: 0xa9d2e280, 0xcb15bd48)
12-11 21:21:27.184  9164  9204 D StatusNativeLogs: 	/ext-go/1/src/github.com/status-im/status-go/rpc/call_raw.go
12-11 21:21:27.184  9164  9204 D StatusNativeLogs: :74 +
12-11 21:21:27.184  9164     0 E Go      : 	/ext-go/1/src/github.com/status-im/status-go/rpc/call_raw.go:74 +0xb4
12-11 21:21:27.184  9164  9204 D StatusNativeLogs: 0xb4
12-11 21:21:27.184  9164  9204 D StatusNativeLogs: github.com/status-im/status-go/rpc.(*Client).CallRaw(
12-11 21:21:27.184  9164  9204 D StatusNativeLogs: 0x0, 0xabf96000,
12-11 21:21:27.184  9164  9204 D StatusNativeLogs: 0x81, 0xabf96000
12-11 21:21:27.184  9164     0 E Go      : github.com/status-im/status-go/rpc.(*Client).CallRaw(0x0, 0xabf96000, 0x81, 0xabf96000, 0x81)
12-11 21:21:27.184  9164  9204 D StatusNativeLogs: , 0x81)
12-11 21:21:27.184  9164  9204 D StatusNativeLogs: 	/ext-go/1/src/github.com/status-im/status-go/rpc/call_raw.go
12-11 21:21:27.184  9164     0 E Go      : 	/ext-go/1/src/github.com/status-im/status-go/rpc/call_raw.go:27 +0x5c
12-11 21:21:27.184  9164  9204 D StatusNativeLogs: :27 +0x5c
12-11 21:21:27.184  9164  9204 D StatusNativeLogs:
12-11 21:21:27.184  9164  9204 D StatusNativeLogs: github.com/status-im/status-go/api.(*StatusBackend).CallPrivateRPC(0xa9e614c0
12-11 21:21:27.184  9164  9204 D StatusNativeLogs: , 0xabf96000,
12-11 21:21:27.184  9164  9204 D StatusNativeLogs: 0x81, 0xaa1a4f58
12-11 21:21:27.184  9164     0 E Go      : github.com/status-im/status-go/api.(*StatusBackend).CallPrivateRPC(0xa9e614c0, 0xabf96000, 0x81, 0xaa1a4f58, 0xc9ec686c)
12-11 21:21:27.184  9164  9204 D StatusNativeLogs: , 0xc9ec686c)
12-11 21:21:27.184  9164  9204 D StatusNativeLogs: 	/ext-go/1/src/github.com/status-im/status-go/api/backend.go
12-11 21:21:27.184  9164     0 E Go      : 	/ext-go/1/src/github.com/status-im/status-go/api/backend.go:228 +0x3c
12-11 21:21:27.184  9164  9204 D StatusNativeLogs: :228 +0x3c
12-11 21:21:27.184  9164  9204 D StatusNativeLogs:
12-11 21:21:27.184  9164  9204 D StatusNativeLogs: main.CallPrivateRPC
12-11 21:21:27.184  9164  9204 D StatusNativeLogs: (0x81c042c0,
12-11 21:21:27.184  9164     0 E Go      : main.CallPrivateRPC(0x81c042c0, 0xcb15b7b8)
12-11 21:21:27.184  9164  9204 D StatusNativeLogs: 0xcb15b7b8)
12-11 21:21:27.184  9164  9204 D StatusNativeLogs: 	/ext-go/1/src/github.com/status-im/status-go/lib/library.go:
12-11 21:21:27.184  9164     0 E Go      : 	/ext-go/1/src/github.com/status-im/status-go/lib/library.go:235 +0x30
12-11 21:21:27.184  9164  9204 D StatusNativeLogs: 235 +0x30
12-11 21:21:27.184  9164  9204 D StatusNativeLogs: main._cgoexpwrap_64ea121b28ff_CallPrivateRPC
12-11 21:21:27.184  9164  9204 D StatusNativeLogs: (0x81c042c0,
12-11 21:21:27.184  9164     0 E Go      : main._cgoexpwrap_64ea121b28ff_CallPrivateRPC(0x81c042c0, 0x0)
12-11 21:21:27.184  9164  9204 D StatusNativeLogs: 0x0)
12-11 21:21:27.184  9164  9204 D StatusNativeLogs: 	_cgo_gotypes.go:
12-11 21:21:27.184  9164     0 E Go      : 	_cgo_gotypes.go:263 +0x4c
12-11 21:21:27.184  9164  9204 D StatusNativeLogs: 263 +0x4c
12-11 21:21:27.320  9887  9886 F google-breakpad: Microdump skipped (uninteresting)
12-11 21:21:27.342  9164  9231 D ReactNativeJS: DEBUG [status-im.utils.handlers:34] - Handling re-frame event:  :init.callback/init-store-success
12-11 21:21:27.353  9164  9886 W google-breakpad: ### ### ### ### ### ### ### ### ### ### ### ### ###
12-11 21:21:27.353  9164  9886 W google-breakpad: Chrome build fingerprint:
12-11 21:21:27.353  9164  9886 W google-breakpad: 70.0.3538.110
12-11 21:21:27.353  9164  9886 W google-breakpad: 353811052
12-11 21:21:27.353  9164  9886 W google-breakpad: ### ### ### ### ### ### ### ### ### ### ### ### ###
12-11 21:21:27.353  9164  9886 F libc    : Fatal signal 6 (SIGABRT), code -6 in tid 9886 (pool-3-thread-3)
```

**Comment by rasom** [comment]
https://github.com/status-im/status-go/blob/develop/rpc/client.go#L97

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/status-im/status-go">status-im/status-go</a></strong></div><div>The Status module that consumes go-ethereum. Contribute to status-im/status-go development by creating an account on GitHub.</div></blockquote>

**Comment by rasom** [comment]
@asemiankevich can't reproduce now, can you test again?

**Comment by asemiankevich** [comment]
@rasom sure, on it

**Comment by asemiankevich** [comment]
@rasom cant repro now , seems to be fixed.

**Comment by rasom** [comment]
@asemiankevich any other issues?

**Comment by asemiankevich** [comment]
> @asemiankevich any other issues?

checked upgrade and seems this fast sign in is only effective when i create new account. So if i on release version recovered account and updated then status to this PR - the login is same slow as it was usual. But if i create new one - then it is fast :)

No other issues i see so far. If this upgrade scenario is expected - then lets merge this PR

**Comment by rasom** [comment]
@asemiankevich did you test it on android device? There is no difference on iOS. It is mostly noticeable on a slow android device, though there is ~2.5s difference on galaxy s9 as well.

> the login is same slow as it was usual

can you please specify which device is used and how many chats you have there

**Comment by rasom** [comment]
so it's 3.1-3.4s in `0.9.32` vs 0.5-0.6s in this PR when i'm testing on galaxy s9 with empty account

**Comment by asemiankevich** [comment]
> @asemiankevich did you test it on android device? There is no difference on iOS. It is mostly noticeable on a slow android device, though there is ~2.5s difference on galaxy s9 as well.
> 
> > the login is same slow as it was usual
> 
> can you please specify which device is used and how many chats you have there

indeed, ios is no difference. I am using huawei under android 8. 


 ok lets merge

**Pull request merged**
