### PR TITLE
move profile tab 

### PR DESCRIPTION
**Pull request by flexsurfer**
move profile tab

cc @churik

### CODE REVIEW

**Review by Parveshdhull — APPROVED** [review]

**Comment by churik** [comment]
@flexsurfer thank you for PR, let's wait for results with e2e fix.
Question: if we're using "open in Status" for links in chat, they are opened behind the chat view (see attached video):

https://user-images.githubusercontent.com/4557972/222154315-8ce585dc-4f54-4b66-b059-d319ceb3c825.mp4

Should we fix it here or I should log it separately?

**Comment by flexsurfer** [comment]
@Parveshdhull wdyt about this case ?

**Comment by flexsurfer** [comment]
do we have something like reset-stack so we close all screens and open browser stack ?

**Comment by flexsurfer** [comment]
actually i just probably need to keep `(navigation/pop-to-root :shell-stack)`

**Comment by flexsurfer** [comment]
@churik fixed, @Parveshdhull nvm :)

**Comment by churik** [comment]
@flexsurfer 
accessibiliy-id is still not there:
Appium 2023-03-01 19-27-15

**Comment by flexsurfer** [comment]
ops ,fixed

**Pull request merged**
