### PR TITLE
fix double @@ in `component-test-watch` and don't do `yarn install` for component tests

### PR DESCRIPTION
**Pull request by siddarthkay**
### Summary

This PR contains tiny fixes for the `Makefile`

status: ready

### CODE REVIEW

**Review by jakubgs — APPROVED** [review]

**Review by flexsurfer — APPROVED** [review]

**Review by J-Son89 — APPROVED** [review]

**Comment by yqrashawn** [comment]
I remember there will be a problem if skip `yarn install`
something related to native module

**Comment by siddarthkay** [comment]
Thanks @yqrashawn was this issue CI specific or reproducible locally also?

**Comment by yqrashawn** [comment]
https://github.com/status-im/status-mobile/pull/15071#issuecomment-1436850662
it's ok to remove `yarn install` if do `make test` first

**Comment by siddarthkay** [comment]
Thanks @yqrashawn!

Yeah i think since component tests are the last stage in CI It seems safe to get rid of `yarn install` as a mandatory step inside Makefile.

Screenshot 2024-01-16 at 7 10 27 PM

To be super sure I also run `make component-test` after `make clean` locally and it seems to work consistently
Screenshot 2024-01-16 at 7 14 39 PM

**Review by yqrashawn — APPROVED** [review]

**Pull request merged**
