### PR TITLE
[DO NOT MERGE] Test desktop with react-native-desktop 0.57

### PR DESCRIPTION
**Pull request by vkjr**
### Summary:

[comment]: # (Summarise the problem and how the pull request solves it)
`react-native-desktop` is going to switch to react-native 0.57. This build is for preliminary testing of `status-react` with the changes.

### Testing notes (optional):
Build won't affect mobile, only desktop. @churik  @SlizkovaGanna, could you please fully test the `status-react` to ensure it works as expected with new react-native version?

#### Platforms (optional)
- macOS
- Linux
- Windows

#### Areas that maybe impacted (optional)
**Functional**
- 1-1 chats
- public chats
- group chats
- wallet / transactions
- dapps / app browsing
- account recovery
- new account
- user profile updates
- networks
- mailservers
- fleet
- bootnodes

**Non-functional**
- battery performance
- CPU performance / speed of the app
- network consumption

### Steps to test:
- Open Status
- Test it all!

status: ready

### CODE REVIEW

**Comment by churik** [comment]
@vkjr can you please include fixes that are made in RN-repo?
Thanks!

**Comment by vkjr** [comment]
@churik, I was going to make it as a next step. This one is to test only version update because there are a lot of changes. If it works well, I'll commit react-native-desktop branches and create new PR with all rnd improvements including 0.57 version. Is it ok?

**Comment by churik** [comment]
@vkjr  there are a lot of changes - would be nice at least to know to what areas I should pay more attention

**Comment by vkjr** [comment]
Here is a changelist of react-native up to 0.57.7 and it is huge...
So I can't really restrict testing to any specific area. But I believe more attention should be paid to UI and communication.

**Comment by churik** [comment]
@vkjr can you rebase it on latest develop? (cannot build it; [conversation](http://take.ms/6StwE) from #status-core-infra)

**Comment by vkjr** [comment]
Will do

**Comment by churik** [comment]
@vkjr can you please rebase it; I'm blocked because I don't have builds

**Comment by vkjr** [comment]
@churik, build fails not because it is not rebased. It has issue and I'm working on it :)

**Comment by churik** [comment]
Ah, sorry, didn't know. Thanks!

**Comment by vkjr** [comment]
@churik, rebased and fixed, build succeeded, but has issue when launching. So let postpone it for now. I'll try to fix issue quickly. If not - can be postponed until 0.9.0 release.

**Comment by churik** [comment]
@vkjr does new RN version improve application for end users or there are mostly technical fixes which need work on clojure side as well?
Just wondering if it improves the application, would be nice to see it in release.

**Comment by vkjr** [comment]
New RN isn't really necessary for a release. No noticeable improvements will happen. This is more for developers.

**Comment by churik** [comment]
@vkjr feel free to ping me when it will be ready for retest

**Comment by vkjr** [comment]
@churik, build passed successfully and can be checked.

**Review by churik — APPROVED** [review]
Tested on Linux Ubuntu 18.04, Windows 10 Home, Mac OSx:
- creating/restoring account
- PNs
- logging enabling\disabling
- navigation in input fields
- quick typing
- 1-1, public, group chats - creating, joining, messaging (replies, emojis, non-latin chars)
- user profile view from public chat
- switching mailservers
- PFS enabling
- log out
- Share my contact code
- editing profile name
- deleting chat / clearing history
- fetching 24h history
- reopening app with several accounts

**Comment by churik** [comment]
@vkjr RN-changes are ready to merge

**Comment by vkjr** [comment]
@churik, good news, thanks!

**Pull request closed without merging**
