### PR TITLE
fix #15899 : failed to reset password

### LINKED ISSUE #15899: "cannot retrieve valid key for given multiaccount.." error when trying login under updated password
**Case 1:** "cannot retrieve valid key for given multiaccount.." error when trying login under updated password

**Steps:** 

1. Login multiaccount
2. Change password
3. Try to login under new password
4. Observe an error

**Expected result:** can login app under updated password. 

**Actual result:** "cannot retrieve valid key for given multiaccount.." error is shown, user is unable to login under updated password. At the same time it is possible to login under old password. 

photo_2023-05-15 15 15 33

https://github.com/status-im/status-mobile/assets/97245802/b6bef7d6-5fcd-4e3f-9fec-b8c0f1633377

**Case 2:** "sql: no rows in result set" when trying to login the newly created account
this case is directly related to Case 1

**Steps:** 

1. Login multiaccount
2. Change password
3. Try to login under new password
4. Observe an error "cannot retrieve valid key for given multiaccount.." 
5. Do not login the account under old password but proceed with creating a new account
6. Observe user stucks on Generating keys step
7. Re-open app
8. Select newly created profile in profile list
9. Try to login the profile
10. Observe an error

**Expected result:** keys are successfully generated and user can login newly created account 

**Actual result:** "sql: no rows in result set" error is displayed. cannot login newly created account. 

photo_2023-05-15 15 15 30

https://github.com/status-im/status-mobile/assets/97245802/ac77f902-24a5-4eb7-ac88-72c8efe5fd8c

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by qfrank**
fixes #15899 

#### Platforms

- Android
- iOS

status: ready

### CODE REVIEW

**Review by flexsurfer — APPROVED** [review]

**Comment by pavloburykh** [comment]
@qfrank I am blocked from testing this for now until we will find out and fix status-go issue with slow login. Andrea is looking on that.

**Review by ilmotta — APPROVED** [review]

**Review by J-Son89 — APPROVED** [review]

**Comment by cammellos** [comment]
Failed to reload keystore contents" err="open /data/user/0/im.status.ethereum.pr/no_backup/keystore/0x6f56979602c2f951397ec87170664cc870e39774338b290653af9dfa98343233: no such file or directory"

I had this error on this build by 
1) Create account
2) Logout
3) Delete a bunch of accounts, including the new one created
4) Create another account
5) Logout
6) Login

**Comment by qfrank** [comment]
> Failed to reload keystore contents" err="open /data/user/0/im.status.ethereum.pr/no_backup/keystore/0x6f56979602c2f951397ec87170664cc870e39774338b290653af9dfa98343233: no such file or directory"
> 
> I had this error on this build by
> 
> 1. Create account
> 2. Logout
> 3. Delete a bunch of accounts, including the new one created
> 4. Create another account
> 5. Logout
> 6. Login

interesting, let me check

**Comment by cammellos** [comment]
@qfrank it's the geth keystore, not sure is related to your pr though

**Comment by qfrank** [comment]
it's just hanging here, what i did:
- Create account
- Logout
- Create another account
- stuck here
image
image
don't you have this issue with this PR?  we need fix this stuck issue first, my PR only fix "failed to reset password"
@cammellos

**Comment by pavloburykh** [comment]
> don't you have this issue with this PR? we need fix this stuck issue first, my PR only fix "failed to reset password" @cammellos

I have faced such issue in this PR.

**Comment by qfrank** [comment]
> I have faced such issue in this PR.

this issue should also exist on branch `develop` right? @pavloburykh

**Comment by pavloburykh** [comment]
> this issue should also exist on branch `develop` right? @pavloburykh

right. I have just re-checked and can confirm. 

Reproduced both login issue and stuck Generation keys screen. 

But regarding login case, in develop after waiting for some time I am facing "cannot retrieve valid key for given multiaccount.." error and not redirected into account. 

photo_2023-05-17 16 24 08

I believe this particular error has been fixed by current PR as I have not faced it here. 

So, slow login and  stucked Generation keys screen issues are not related to this PR. We just used builds from current PR to reproduce those issues.

**Comment by qfrank** [comment]
found the cause that causing stuck

**Comment by qfrank** [comment]
> Failed to reload keystore contents" err="open /data/user/0/im.status.ethereum.pr/no_backup/keystore/0x6f56979602c2f951397ec87170664cc870e39774338b290653af9dfa98343233: no such file or directory"
> 
> I had this error on this build by
> 
> 1. Create account
> 2. Logout
> 3. Delete a bunch of accounts, including the new one created
> 4. Create another account
> 5. Logout
> 6. Login

after resolving the stuck issue , i'm unable to reproduce this issue 🙂 @cammellos

**Comment by qfrank** [comment]
can you retry again after last rebase , the stuck issue should not exist anymore, also pls re-check issue @cammellos reported (i'm unable to reproduce), thank you @pavloburykh

**Comment by pavloburykh** [comment]
> can you retry again after last rebase , the stuck issue should not exist anymore, also pls re-check issue @cammellos reported (i'm unable to reproduce), thank you @pavloburykh

thanx, I will re-check today.

**Comment by pavloburykh** [comment]
@qfrank thank you for the fix. PR is tested and ready to be merged.

**Pull request merged**
