### PR TITLE
js: remove unused visual tests and detox package

### PR DESCRIPTION
**Pull request by yakimant**
### Summary

After the `nixpkgs` upgrade we started to have Xcode command line tools installation popup on each `make test`, `dtrace-provider` was failing meanwhile:
https://github.com/status-im/status-mobile/issues/16356#issuecomment-1602680977

It appeared, that it was failing before the upgrade with different issue:
https://github.com/status-im/status-mobile/issues/16356#issuecomment-1604097134

`dtrace-provider` is a dependency for `detox`, which was added for visiual tests in https://github.com/status-im/status-mobile/pull/14329
These tests don't run.

This build issues didn't cause any problems, because it was not obligatary.
See `NODE_DTRACE_PROVIDER_REQUIRE` option, which can enforce this requirement.

See https://github.com/status-im/status-mobile/issues/16356 for more details.

In this PR we disable `detox` dependency for now.
And also Visual Tests.

### Review notes
There are many libs removed from yarn.lock.
Looks a bit suspicious, or maybe it's just `detox` has so many dependencies.

status: ready

### CODE REVIEW

**Comment by J-Son89** [comment]
Can you also remove `.detoxrc.js` as it is redundant if the dependency is not in the codebase.

Additionally you can remove folder:
`visual-test` 

I think that's all there is to visual tests.

**Comment by J-Son89** [comment]
actually there is also some scripts in the Make file -> 
```
run-visual-test-ios: export TARGET := clojure
run-visual-test-ios: XCODE_DERIVED_DATA := $(HOME)/Library/Developer/Xcode/DerivedData
run-visual-test-ios: APPLICATION_NAME := StatusIm-brfnruzfrkkycpbndmdoeyrigthc
run-visual-test-ios: export TEST_BINARY_PATH := $(XCODE_DERIVED_DATA)/$(APPLICATION_NAME)/Build/Products/Debug-iphonesimulator/StatusIm.app
run-visual-test-ios: ##@test Run tests once in NodeJS
	detox test --configuration ios.sim.debug
```	
these can be removed too

**Comment by yakimant** [comment]
@J-Son89, done, cleaned up visual tests too

**Review by J-Son89 — APPROVED** [review]

**Review by jakubgs — APPROVED** [review]
You love to see it.

image

**Pull request merged**
