### PR TITLE
[#7155] Clear last message preview on deleting chat history

### LINKED ISSUE #7155: Message preview is not cleared when deleting chat history on desktop
### Description

*Type*: Bug

*Summary*: ...

#### Expected behavior
[Not messages] placeholder in message preview when chat history is deleted

#### Actual behavior
image

### Reproduction

- Open Status
- Join any chat
- Send some messages
- Delete history
- Go to Home screen

### PR DESCRIPTION
**Pull request by rasom**
fix #7155 

status: ready

### CODE REVIEW

**Review by mandrigin — APPROVED** [review]

**Review by cammellos — APPROVED** [review]

**Review by flexsurfer — APPROVED** [review]

**Review by vitvly — APPROVED** [review]

**Comment by Serhy** [comment]
It's all fine for Desktop (Mac, Windows checked). The 'No messages yet' placeholder displayed in chat (1-1/Group/Public) with no history.
@rasom could we add, in scope of this PR, the `No messages yet` placeholder to iOS and Android as well if there are no messages in the chat, so it would be same to Desktop behavior? 

This is iOS view for chats with no data: 

screenshot 2018-12-24 at 13 36 05

**Comment by rasom** [comment]
@Serhy i suppose we can, will check it

**Comment by rasom** [comment]
@Serhy done

**Comment by Serhy** [comment]
All looks good!

**Pull request merged**
