### PR TITLE
Update status-go to v0.16.4-4-gaf1f6eb5

### PR DESCRIPTION
**Pull request by pedropombeiro**
- Gets rid of status-go support for mailserver bundle requests (not yet supported by deployed mailservers)
- Removes no longer used scripts/update-status-go.sh script

status: ready

### CODE REVIEW

**Comment by cammellos** [comment]
@PombeirP have you checked it works with the current fleet? I have tried to upgrade before to 0.16.4 but seems like there's some breaking change (status-react is not able to fetch any messages with the beta fleet, works ok with the staging fleet)

**Comment by cammellos** [comment]
Also there's an extra `v` in the version & no release on github  https://github.com/status-im/status-go/releases, things have changed since you have been away :)

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/status-im/status-go">status-im/status-go</a></strong></div><div>The Status module that consumes go-ethereum. Contribute to status-im/status-go development by creating an account on GitHub.</div></blockquote>

**Comment by yenda** [comment]
@cammellos from the tag of the go-version you commited it seemed like the breaking change was included in latest nightly  that's why @PombeirP made a release that exclude the commit

**Comment by pedropombeiro** [comment]
@cammellos yeah, that's what this commit is trying to fix. The currently used status-go version contains `a75f9c34cf37ece10c33be8679676dbf539e154c` (Request historical messages in batches (#1245)) which breaks compatibility. The staging cluster is probably already running the latest status-go which is why you can run it there. I'll fix the `v` in the version.

**Comment by cammellos** [comment]
@PombeirP there's something odd, I cherry picked that commit on a different branch https://jenkins.status.im/job/status-go/job/status-go-manual/516/consoleFull (`release/0.16.3.2` https://github.com/status-im/status-go/tree/release/0.16.3.2 ) specifically to avoid that commit, can you figure out why it has been included?

<blockquote><div><strong><a href="https://jenkins.status.im/job/status-go/job/status-go-manual/516/consoleFull">status-go » status-go-manual #516 Console [Jenkins]</a></strong></div></blockquote>
<blockquote><div> GitHub</div><div><strong><a href="https://github.com/status-im/status-go">status-im/status-go</a></strong></div><div>The Status module that consumes go-ethereum. Contribute to status-im/status-go development by creating an account on GitHub.</div></blockquote>

**Comment by pedropombeiro** [comment]
No idea, what I can see is that current `develop` is based on that commit, and the version used by status-react matches the current `develop`. Weird.

**Comment by cammellos** [comment]
https://jenkins.status.im/job/status-go/job/status-go-manual/516/consoleFull
you can see here it never checks out the branch, it picks the hash (which is the same for cherry picked commits), and then `checkout -f` the branch, landing back on the default branch and ignoring the branch variable.
Probably something we need to take a look at.

<blockquote><div><strong><a href="https://jenkins.status.im/job/status-go/job/status-go-manual/516/consoleFull">status-go » status-go-manual #516 Console [Jenkins]</a></strong></div></blockquote>

**Pull request closed without merging**
