### PR TITLE
[#6642] Feature/chat command extra key

### LINKED ISSUE #6642: Allow adding extra key/value pair to chat command
As a developer, I want to add extra key/value pair data to the chat command message payload accessible to all recipients.

### Description

Chat command parameters are sent to all message recipients. Sometimes you need to add extra parameters. Those should be accessible to local and recipients messages, using the same syntax.
A new event hook property could be responsible for generating those.

This could leverage `command/yield-control`

*Type*: Feature

### PR DESCRIPTION
**Pull request by flexsurfer**
fixes #6642

Introduced two new events

```
[chat.command/set-parameter-with-custom-params {:value "Yohoho" :params {:param1 "value1"}}]

[chat.command/set-custom-parameter {:key :param1 :value "value1"}]

```

usage

```
views/suggetsion
 [view {:style {:flex-direction :row
                :align-items    :flex-start}}
  [button {:on-click [chat.command/set-parameter-with-custom-params {:value "Yohoho" :params {:param1 "Test"}}]}]]
 
```

### CODE REVIEW

**Comment by ghost** [comment]
### Pull Request Checklist
- [x] Have you updated the documentation, if impacted (e.g. [docs.status.im](https://docs.status.im/docs/build_status.html))?

**Review by jeluard — APPROVED** [review]

**Comment by asemiankevich** [comment]
@flexsurfer @jeluard would e2e run be sufficient for sanity checks here?

**Comment by flexsurfer** [comment]
@asemiankevich i think so, thanks

**Comment by goranjovic** [comment]
How does this handle communication between different versions?
What happens when old version receives a messages with the new extra key?

**Comment by jeluard** [comment]
@goranjovic  Versions of what? Extensions? As far as messaging is concerned this is just a serialized payload.

**Comment by goranjovic** [comment]
Versions of messages/Status. My question is what happens when Status before this PR receives a messages from Status after this PR

**Comment by jeluard** [comment]
@goranjovic It's just a map as far as messaging is concerned. So this is not related to message versioning.

**Comment by jeluard** [comment]
@goranjovic This PR does not add any feature in this regards, this is handled by the chat command protocol.

**Review by goranjovic — APPROVED** [review]

**Pull request merged**
