### PR TITLE
Cleaning

### PR DESCRIPTION
**Pull request by flexsurfer**
Removed

**npm modules**

"react-native-action-button",	
"react-native-vector-icons/Ionicons",	
"react-native-vector-icons/Octicons",
"react-native-linear-gradient",	
"react-native-orientation"

**screens**
discovery
network

**components**
carousel
image-button
status-view
text-field
drag-drop
native-action-button
sticky-button

image

### CODE REVIEW

**Review by yenda — APPROVED** [review]

**Comment by jeluard** [comment]
@flexsurfer Can you include the new `package-lock.json` ?

**Review by jeluard — APPROVED** [review]
Awesome cleanup congrats!

**Comment by flexsurfer** [comment]
@jeluard thanks, done

**Comment by Serhy** [comment]
Looks good for me, @flexsurfer !

**Pull request merged**
