### PR TITLE
swap react-native-mail fork with patch

### PR DESCRIPTION
**Pull request by siddarthkay**
## Summary

This PR swaps the fork of react-native-mail with a patch.

needed for : https://github.com/status-im/status-mobile/issues/18138

## Review & Test notes

Verify if mailing logs still works.

## Platforms
- iOS
- Android

status: ready

### CODE REVIEW

**Review by Parveshdhull — APPROVED** [review]

**Review by ajayesivan — APPROVED** [review]

**Review by OmarBasem — APPROVED** [review]

**Review by mohsen-ghafouri — APPROVED** [review]

**Comment by siddarthkay** [comment]
@status-im/mobile-qa : just a smoke test for this PR will do

**Comment by siddarthkay** [comment]
@status-im/mobile-qa : please smoke test this PR briefly, The only flow that should be impacted would be sending of the email we use for sharing logs.
Thank you!

**Comment by qoqobolo** [comment]
> @status-im/mobile-qa : please smoke test this PR briefly, The only flow that should be impacted would be sending of the email we use for sharing logs. Thank you!

Hey, since this is a really small change and this is the only thing that might be impacted, it makes sense to skip manual QA in this case according to [the new process](https://github.com/status-im/status-mobile/blob/develop/doc/pipeline_process.md).
Would you mind just checking this flow yourself and merging it please?🙂🙏
I've checked the e2e results, they are okay👌

**Comment by siddarthkay** [comment]
Thanks @qoqobolo : I tested it just now and sending email flow seems to work!
Thanks for taking a look at the E2E.

**Pull request merged**
