### PR TITLE
[WIP] [DO NOT MERGE] Re introduce textbox styling

### PR DESCRIPTION
**Pull request by mandrigin**
reverts changes from https://github.com/status-im/status-react/pull/4878

🛑 do not merge until the performance regression in RN is fixed. The issue is described here: https://github.com/status-im/status-react/issues/4794

status: wip

### CODE REVIEW

**Comment by mandrigin** [comment]
@cammellos it is time to re-introduce this one, wdyt?

**Comment by cammellos** [comment]
@janherich did some work on this as well in different PRs I believe, and might have addressed the issue?
Otherwise I will rebase it and resolve the conflicts.

**Comment by mandrigin** [comment]
@cammellos ping here as well :)

**Comment by janherich** [comment]
@mandrigin I did all the work from this PR (+ extra unrelated things) in another PR which was already merged, so I think we can close this one.

**Comment by mandrigin** [comment]
Thanks! Closing this one then.

**Pull request closed without merging**
