### PR TITLE
Double-tap for communities & fix for 'Recent' tab not being shown as selected if message icon is double tapped

### LINKED ISSUE #15810: 'Recent' tab is not shown as selected if message icon is double tapped
Related to https://github.com/status-im/status-mobile/issues/15569

### Steps to reproduce:
1. Open the 'Contacts' or 'Group' tab
2. Doble tap on the messaging icon

### Actual result:
The 'Contacts' tab is still shown as opened (but actually the 'Recent' tab is opened)

https://user-images.githubusercontent.com/52490791/236149931-9b516554-23c7-4a1a-b27f-7bcc5cb857a0.mp4

### Expected result:
The 'Recent' tab is opened and shown as opened

### ENV:
- nightly 4 May 2023

### PR DESCRIPTION
**Pull request by alwx**
fixes #15810 

Also implements https://github.com/status-im/status-mobile/issues/15569 but for communities.

#### Platforms

- Android
- iOS

status: ready

### CODE REVIEW

**Review by rasom — APPROVED** [review]

**Review by siddarthkay — APPROVED** [review]

**Comment by pavloburykh** [comment]
@alwx thanx for the PR. Please take a look at the following issue

### ISSUE 1 Non of the messaging tabs is shown as selected after relogin

**Steps:** 

1. Login the app (make sure any of messages tab is selected)
2. Perform relogin
3. See if any of messaging tabs is shown as selected

**Actual result:** non of tabs is shown as selected 

photo_2023-05-10 13 37 05

https://github.com/status-im/status-mobile/assets/97245802/7b5fd7a9-4e33-4287-9ba6-193dbbe03681



**Expected result:** recent tab should be shown as selected. On the other hand we might want to save the state of the last selected tab, but such feature should be discussed and confirmed by @status-im/design-team Currently we are saving the state until relogin.

**Comment by pavloburykh** [comment]
@alwx can we implement the same feature for the community tab as described in the [comment](https://github.com/status-im/status-mobile/issues/15569#issuecomment-1541987585)? Or it is better to log separate ticket for that?

**Comment by alwx** [comment]
@pavloburykh no worries, will do it here as well.

**Comment by alwx** [comment]
@pavloburykh ready to be tested! Double-tapping on communities icon also works now.

**Comment by pavloburykh** [comment]
@alwx thanx for the fixes! PR is ready to be merged. Failed e2e are not PR related.

**Pull request merged**
