### PR TITLE
chore: bump react-native-camera-link version to Status fork to remove usage of ML Kit

### LINKED ISSUE #20876: FDroid build failing due to react-native-camera-kit dependencies
The FDroid build is [currently failing](https://gitlab.com/cammellos/fdroiddata/-/jobs/7418712679) because of dependencies in the `react-native-camera-kit` package, which relies on Google ML Kit for QR scanning. This issue needs to be addressed to ensure our app is compliant with FDroid guidelines.

**Steps to Reproduce:**
1. Attempt to submit PR on FDroid repository and let job build the app for FDroid.
2. Notice the build failure due to Google dependencies.

**Proposed Solutions:**
1. Fork the `react-native-camera-kit` library and remove the Google ML Kit dependencies.
2. Submit a PR to the original library to remove these dependencies.
3. As a last resort, remove the `react-native-camera-kit` library only for FDroid builds, though this is not preferable since QR scanning is a crucial feature of our app.

**Action Items:**
1. Investigate the feasibility of forking `react-native-camera-kit` and removing the Google ML Kit dependencies.
2. Track and prioritize the work needed for this change.

**Additional Context:**
QR scanning is an essential feature of our app, and we need a solution that maintains this functionality while being compliant with FDroid requirements.

### PR DESCRIPTION
**Pull request by briansztamfater**
fixes #20876

### Summary

The FDroid build is [currently failing](https://gitlab.com/cammellos/fdroiddata/-/jobs/7418712679) because of dependencies in the react-native-camera-kit package, which relies on Google ML Kit for QR scanning. This PR changes version of react-native-camera-kit to [our own fork](https://github.com/status-im/react-native-camera-kit). I've tested the changes in the library with the example app with good results, I expect this build to work but we need to be sure, so manual QA is needed here.

Relevant changes in our library fork can be [seen here](https://github.com/teslamotors/react-native-camera-kit/commit/90821bc45c950c98119acc896651997a5357dd4f).

#### Platforms

- Android

##### Functional

- 1-1 chats
- public chats
- group chats
- wallet / transactions
- dapps / app browsing
- account recovery

### Steps to test

Basically verify that QR scanner is properly working on Android on all the flows that is used. iOS should not be affected by this PR, but a quick smoke testing wouldn't hurt.

status: ready

### CODE REVIEW

**Review by J-Son89 — APPROVED** [review]

**Review by siddarthkay — APPROVED** [review]

**Review by smohamedjavid — APPROVED** [review]
@briansztamfater - Nice work 🙌 

From `v13.0.0` to `v14.0.0-beta15` 🎉  with MLKit replaced with Zxing

**Review by ilmotta — APPROVED** [review]

**Review by jakubgs — APPROVED** [review]
Very nice, love to see it:

image

I'm sure it's going to come back at some point once again due to some other dependency.

**Comment by mariia-skrypnyk** [comment]
Hi @briansztamfater !

Can you tell me could your fix affect Wallet Connect feature when we scan dapp QR?

I tried your rebased build on iOS and Android and see that Wallet Connect doesn't work on Android:

after I scan QR code by status app nothing happens (tried 10 times with reloading QR on dapp and relogin of status).

UPD: not your PR issue, it's global

**Comment by mariia-skrypnyk** [comment]
@briansztamfater thanks for your fix!

I've did smoke on iOS.
Android was checked more detailed in such areas:

**Sync:** 

onoarding
profile

**Wallet:** 

save address
send
add watch only
import keypair

**Camera** on Profile/Chats

Looks good, can be merged!

**Pull request merged**
