### PR TITLE
[#6277] Back button does not clear extensions cache

### LINKED ISSUE #6277: Back button does not clear extensions cache
### Description

*Type*: Bug

*Summary*: Extension details are cached if the user has opened extension screen from URL so going back to Extensions screen does not clear the details.

#### Expected behavior

Extension details are not cached so if I went back to the previous screen and add a new extension from scratch - previous details should not be pre-populated

#### Actual behavior

Extension details are cached

### Reproduction
- Open Status develop
- Enable dev mode
- Go to extensions - add extension
- Paste the following URL https://get.status.im/extension/gist@asemiankevich/d40950973105f8cdd1cabe0b18be69d1
- Tap Find button
- Make sure the details of extension are shown
- Tap back to return to `Find extension` screen
- Tap back to return to `Extensions` screen
- Tap `+` 
- Tap `Find` button (**do not add any new URL**)

<blockquote></blockquote>

### PR DESCRIPTION
**Pull request by flexsurfer**
fixes #6277

### CODE REVIEW

**Comment by ghost** [comment]
### Pull Request Checklist
- [ ] Have you updated the documentation, if impacted (e.g. [docs.status.im](https://docs.status.im/docs/build_status.html))?

**Review by jeluard — APPROVED** [review]

**Comment by alwx** [comment]
I think it's better to not merge this one because it will become useless after we merge this issue: https://github.com/status-im/status-react/pull/6301

**Comment by jeluard** [comment]
Does #6301 fixes this? How does it make it irrelevant?

**Comment by alwx** [comment]
There is no `:extension-url` in db anymore

**Comment by jeluard** [comment]
@alwx Ahh.. so your PR fixes this issue too?

**Pull request closed without merging**
