### PR TITLE
No logs in desktop release

### LINKED ISSUE #6569: Do not display logs by default in release builds; make it possible to enable in the UI
### Description
We should disable all logs by default. However, it should be possible to temporarily enable logging via advanced settings in Profile.

### PR DESCRIPTION
**Pull request by vkjr**
fixes #6569

### Summary:

Flag added to build system to disable logs in desktop release build.
By default no records will appear in Status.log when app started/used/finished.

To enable logs for specific application areas: 
1. open terminal

2. set environment variable:
```sh
export QT_LOGGING_RULES="ViewManager=false;Networking=true"
```
List of all existing areas can be found here - https://github.com/status-im/status-react/pull/7029/files#diff-b3598ffec8b87686b94e17539c68ea4aR262

3. Start app: `open Status.app`

### Testing notes (optional):
These changes impact only release build. So instead of taking binaries from PR, please take them from this build - 
https://ci.status.im/job/status-react/job/release/job/release%252Ftest-desktop-nologs-remove-later2/
It has the same changes but build for release

#### Platforms (optional)
- macOS
- Linux
- Windows

#### Areas that maybe impacted (optional)
Only console logging impacted

### Steps to test:
See steps in Summary section

status: ready

### CODE REVIEW

**Comment by jakubgs** [comment]
I really don't think `withEnv` is going to affect a sub-job started with `build()`. Also, for future, instead of `withEnv` you can just do `env.MY_VAR = 1`.
Let me fix this.

**Comment by jakubgs** [comment]
This should be better.

**Review by jakubgs — APPROVED** [review]
I'm going to approve it because the rest looks good but please check if it works properly.

**Comment by vkjr** [comment]
@jakubgs, thanks for correction!
I moved env var settings from `buildClojureScript()` to `compile()` function.

Is it possible to create release build from this branch? It would be nice to test it.

**Comment by chadyj** [comment]
> Is it possible to create release build from this branch? It would be nice to test it.

A release build will be created if push to a branch and name it `/release/*`. It will show up here https://ci.status.im/job/status-react/job/release/

<blockquote><div><strong><a href="https://ci.status.im/job/status-react/job/release/">Branches (9) [status-react » release] [Jenkins]</a></strong></div></blockquote>

**Comment by chadyj** [comment]
Release builds failed :(
https://ci.status.im/job/status-react/job/release/job/release%252Ftest-desktop-nologs-remove-later/

<blockquote><div><strong><a href="https://ci.status.im/job/status-react/job/release/job/release%252Ftest-desktop-nologs-remove-later/">release/test-desktop-nologs-remove-later [status-react » release] [Jenkins]</a></strong></div></blockquote>

**Comment by vkjr** [comment]
@jakubgs, had a strange error in release build:
```
19:31:16 -- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- broken
19:31:16 CMake Error at /usr/local/Cellar/cmake/3.12.2/share/cmake/Modules/CMakeTestCXXCompiler.cmake:45 (message):
19:31:16   The C++ compiler
19:31:16 
19:31:16     "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++"
19:31:16 
19:31:16   is not able to compile a simple test program.
19:31:16 
```

Any ideas why that can happen? (I restarted the build just in case that was a temporary problem)

**Comment by jakubgs** [comment]
You should read the whole error:
```
18:30:26     /usr/bin/c++    '-DBUILD_FOR_BUNDLE=1    -o CMakeFiles/cmTC_cc5a1.dir/testCXXCompiler.cxx.o -c /home/jenkins/workspace/status-react/combined/desktop-linux/desktop/CMakeFiles/CMakeTmp/testCXXCompiler.cxx
18:30:26     /bin/sh: 1: Syntax error: Unterminated quoted string
18:30:26     CMakeFiles/cmTC_cc5a1.dir/build.make:65: recipe for target
```
Especially: __`Syntax error: Unterminated quoted string`__

**Comment by vkjr** [comment]
@jakubgs, good point :) thanks for noticing

**Comment by vkjr** [comment]
@jakubgs, what about this one? Does it look familiar? 
https://ci.status.im/job/status-react/job/combined/job/desktop-linux/4719/console

<blockquote><div><strong><a href="https://ci.status.im/job/status-react/job/combined/job/desktop-linux/4719/console">status-react » combined » desktop-linux #4719 Console [Jenkins]</a></strong></div></blockquote>

**Comment by jakubgs** [comment]
Looks like NVM failure but with no clear reason. Never seen it.

**Comment by jakubgs** [comment]
`java.lang.InterruptedException` would indicate something like `SIGHUP` or some other similar `SIG*`, but that's not what happened.

**Comment by jakubgs** [comment]
Usually this happens alongside `Cannot contact ${NODENAME}` but here there is no such thing.
Like so:
https://issues.jenkins-ci.org/browse/JENKINS-43038

<blockquote><div><strong><a href="https://issues.jenkins-ci.org/browse/JENKINS-43038">[JENKINS-43038] Intermittent error "Cannot contact node123: java.lang.InterruptedException " in jenkins - Jenkins JIRA</a></strong></div></blockquote>

**Comment by vkjr** [comment]
@jakubgs, I rerun the release build with the same changes as in PR and it went well - https://ci.status.im/job/status-react/job/release/job/release%252Ftest-desktop-nologs-remove-later2/

But Jenkins fails when builds the PR itself - https://ci.status.im/blue/organizations/jenkins/status-react%2Fprs%2Fmacos/detail/PR-7029/2/pipeline/36
`java.lang.IllegalArgumentException: Null value not allowed as an environment variable: BUILD_TYPE`

Could you please help? I'm not sure where I should look into. Is it possible that this change produces error for non-release build? (I doubt but just to double check):
```
if (params.BUILD_TYPE == 'release') {
    env.STATUS_NO_LOGGING = 1
  }
```


<blockquote><div><strong><a href="https://ci.status.im/job/status-react/job/release/job/release%252Ftest-desktop-nologs-remove-later2/">release/test-desktop-nologs-remove-later2 [status-react » release] [Jenkins]</a></strong></div></blockquote>
<blockquote><div><strong><a href="https://ci.status.im/blue/organizations/jenkins/status-react%2Fprs%2Fmacos/detail/PR-7029/2/pipeline/36">Jenkins</a></strong></div></blockquote>

**Comment by jakubgs** [comment]
Ignore that, you're looking at a wrong build. I'm setting up a new PR pipeline,it's here:
https://ci.status.im/job/status-react/job/prs/
Ignore it.

<blockquote><div><strong><a href="https://ci.status.im/job/status-react/job/prs/">All [status-react » prs] [Jenkins]</a></strong></div></blockquote>

**Comment by vkjr** [comment]
@jakubgs, is it work in progress?
Right now I'm getting this error in a new pipeline:
```
+ git rebase origin/develop
fatal: Needed a single revision
invalid upstream 'origin/develop'
script returned exit code 1
```

PR was rebased to develop a minute ago.

**Comment by jakubgs** [comment]
Please ignore any jobs coming from:
https://ci.status.im/job/status-react/job/prs/
The current PR setup is at:
https://ci.status.im/job/status-react/job/prs/job/macos/view/change-requests/

<blockquote><div><strong><a href="https://ci.status.im/job/status-react/job/prs/">All [status-react » prs] [Jenkins]</a></strong></div></blockquote>
<blockquote><div><strong><a href="https://ci.status.im/job/status-react/job/prs/job/macos/view/change-requests/">Pull Requests (38) [status-react » prs » macos] [Jenkins]</a></strong></div></blockquote>

**Comment by vkjr** [comment]
Yes, I'm looking at this one - https://ci.status.im/job/status-react/job/prs/job/macos/view/change-requests/job/PR-7029/

If it is wrong, what is the correct one?
If it is work in progress, sorry for distraction, I'm just trying to understand when I should get back to this PR. Eagerly want it to be checked and merged :)

<blockquote><div><strong><a href="https://ci.status.im/job/status-react/job/prs/job/macos/view/change-requests/job/PR-7029/">PR-7029 [status-react » prs » macos] [Jenkins]</a></strong></div></blockquote>

**Comment by jakubgs** [comment]
This one:
https://ci.status.im/job/status-react/job/pull%20requests/view/change-requests/job/PR-7029/

<blockquote><div><strong><a href="https://ci.status.im/job/status-react/job/pull%20requests/view/change-requests/job/PR-7029/">PR-7029 [status-react » pull requests] [Jenkins]</a></strong></div></blockquote>

**Comment by vkjr** [comment]
@siphiuel, @MaxRis, could you please take a look at this one? Thanks!

**Review by vitvly — APPROVED** [review]

**Review by maxhora — APPROVED** [review]

**Comment by vkjr** [comment]
@churik, could you please take a look? Thanks!

**Comment by churik** [comment]
@vkjr there are no desktop builds at all in https://ci.status.im/job/status-react/job/release/job/release%252Ftest-desktop-nologs-remove-later2/
Can you please take a look?


<blockquote><div><strong><a href="https://ci.status.im/job/status-react/job/release/job/release%252Ftest-desktop-nologs-remove-later2/">release/test-desktop-nologs-remove-later2 [status-react » release] [Jenkins]</a></strong></div></blockquote>

**Comment by vkjr** [comment]
@churik, I definetely was downloading one for macos yesterday. By pressing on MacOs build and following the success build link. But now it is [not found](https://ci.status.im/job/status-react/job/combined/job/desktop-macos/4821/)
Let me restart the build, maybe they were cleaned up somehow.

**Comment by vkjr** [comment]
@churik, build is not yet fully completed, but build artefacts are ready and can be downloaded for desktop platforms - https://ci.status.im/job/status-react/job/release/job/release%252Ftest-desktop-nologs-remove-later2/

<blockquote><div><strong><a href="https://ci.status.im/job/status-react/job/release/job/release%252Ftest-desktop-nologs-remove-later2/">release/test-desktop-nologs-remove-later2 [status-react » release] [Jenkins]</a></strong></div></blockquote>

**Comment by churik** [comment]
@vkjr
1) Logs are not disabled by default in release builds
I downloaded build from https://ci.status.im/job/status-react/job/combined/job/desktop-macos/4917/ , installed it, created account and I still can see that Status.log is created and it is not empty.

2) If I performed `export QT_LOGGING_RULES="VIEWMANAGER=false;NETWORKING=false;UIMANAGER=false;FLEXBOX=false;WEBSOCKETMODULE=false;RCTNOTIFICATION=false;DEFAULT=false;RCTSTATUS=false;JSSERVER=false;STATUS=false"` and launch app from console, I can see that log is created, but it is empty.
Should it be created at all in this case?



<blockquote><div><strong><a href="https://ci.status.im/job/status-react/job/combined/job/desktop-macos/4917/">status-react » combined » desktop-macos #4917 [Jenkins]</a></strong></div></blockquote>

**Comment by vkjr** [comment]
@churik, did you remove the old Status.log before first run of release build?
I just installed the build from your link, removed old log and launched app. It does create log file, but it is empty and no info generated.

As for empty file - yes, probably that should be fixed.

**Comment by churik** [comment]
@vkjr yes, of course. It was completely fresh installation.
I'll retest it one more time.

**Comment by vkjr** [comment]
I'm on mac and checking Status.log in `Library/Application Support/Status` directory

**Comment by churik** [comment]
@vkjr I did a mistake (probably launch a wrong build), so sorry for this. rechecked on Mac Os and Linux.
Only fix for empty file is needed.

**Comment by vkjr** [comment]
@jakubgs, Could you please help with this?
release build fails with error:
https://ci.status.im/job/status-react/job/release/job/release%252Ftest-desktop-nologs-remove-later3/
```
Started by upstream project "status-react/release/release%2Ftest-desktop-nologs-remove-later3" build number 1
originally caused by:
 Push event to branch release/test-desktop-nologs-remove-later3
java.lang.IllegalArgumentException: Null value not allowed as an environment variable: CHANGE_ID
	at hudson.EnvVars.put(EnvVars.java:377)
	at hudson.model.StringParameterValue.buildEnvironment(StringParameterValue.java:59)
	at hudson.model.ParametersAction.buildEnvironment(ParametersAction.java:145)
	at hudson.model.Run.getEnvironment(Run.java:2377)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.getEnvironment(WorkflowRun.java:468)
	at org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition.create(CpsScmFlowDefinition.java:106)
	at org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition.create(CpsScmFlowDefinition.java:67)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:293)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Finished: FAILURE
```

Release branch is a copy of branch in this PR and this PR built fine.


<blockquote><div><strong><a href="https://ci.status.im/job/status-react/job/release/job/release%252Ftest-desktop-nologs-remove-later3/">release/test-desktop-nologs-remove-later3 [status-react » release] [Jenkins]</a></strong></div></blockquote>

**Comment by churik** [comment]
@vkjr 
installed last build from https://ci.status.im/job/status-react/job/release/job/release%252Ftest-desktop-nologs-remove-later3/ - by default no log file, as expected
But If I performed export QT_LOGGING_RULES="VIEWMANAGER=true;NETWORKING=true;UIMANAGER=true;FLEXBOX=true;WEBSOCKETMODULE=true;RCTNOTIFICATION=true;DEFAULT=true;RCTSTATUS=true;JSSERVER=true;STATUS=true" and launch app from console, I can't see log as well.
Am I doing something wrong or it is an issue?

<blockquote><div><strong><a href="https://ci.status.im/job/status-react/job/release/job/release%252Ftest-desktop-nologs-remove-later3/">release/test-desktop-nologs-remove-later3 [status-react » release] [Jenkins]</a></strong></div></blockquote>

**Comment by vkjr** [comment]
@churik, sorry, my bad, name of categories in export command are case-sensitive. My bad, I used uppercase in a description. So correct command would be:
```sh
export QT_LOGGING_RULES="ViewManager=true;Networking=true;UIManager=true;Flexbox=true;WebSocketModule=true;RCTNotification=true;default=true;RCTStatus=true;jsserver=true;status=true"
```

**Pull request merged**
