### PR TITLE
Replace accounts/accounts by account/account in app-db [#3907]

### LINKED ISSUE #3907: Replace accounts/accounts by account/account in app-db
### User Story

As a developper I want to share the minimal amount of informations between accounts and I don't need other accounts infos when the user is logged in.

### Description

*Type*: Bug

- move all informations that are not necessary to login from the base realm to account specific realm
- remove accounts/accounts and accounts/current-account-id from app-db, replace by account/account when user is logged in (logged out can have dedicated key)

### PR DESCRIPTION
**Pull request by psdp**
fixes #3907

### Summary:

Replace accounts/accounts by account/account in app-db

- move all informations that are not necessary to login from the base realm to account specific realm
- remove accounts/accounts and accounts/current-account-id from app-db, replace by account/account when user is logged in (logged out can have dedicated key)

status: ready

### CODE REVIEW

**Comment by janherich** [comment]
@psdp please resolve conflicts

**Comment by psdp** [comment]
@janherich conflicts have been resolved now.

**Comment by flexsurfer** [comment]
sorry @psdp it has conflicts again, could you take a look, thanks

**Comment by yenda** [comment]
@flexsurfer let's move this to priority for testing once conflict are resolved because it will easely have new conflicts considering the size of the change

**Comment by psdp** [comment]
@flexsurfer @yenda done, I've resolved conflicts again.

**Review by yenda — APPROVED** [review]

**Review by janherich — APPROVED** [review]

**Comment by asemiankevich** [comment]
@psdp 

1. app crashes when I create account or recover it (app first launch). 
`java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
	at org.json.JSONTokener.nextCleanInternal(JSONTokener.java:116)
	at org.json.JSONTokener.nextValue(JSONTokener.java:94)
	at org.json.JSONObject.(JSONObject.java:156)
	at org.json.JSONObject.(JSONObject.java:173)
	at im.status.ethereum.module.StatusModule.doStartNode(StatusModule.java:212)
	at im.status.ethereum.module.StatusModule.access$000(StatusModule.java:32)
	at im.status.ethereum.module.StatusModule$1.run(StatusModule.java:362)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:776)`

2. error shown when requesting funds (android)

image

3. can't call /send command in 1x1 chat - transaction screen is not shown

**Comment by psdp** [comment]
@asemiankevich Sorry about that. It's fixed now. Would you mind to check again?

**Comment by asemiankevich** [comment]
i have tested creation  of multiple accounts, recovering, /send and /request of different scenarios. Everything looks good to me except upgrade that we do not support for now.

**Pull request merged**
