### PR TITLE
 [#21559] Keycard - Fresh install sign in

### LINKED ISSUE #21559: Keycard - Fresh instal sign in
User has a keycard with the keys, it should be possible to create new profile for these keys

Figma: https://www.figma.com/design/YGm3igIOAcwMqUVJWCJ6f1/Keycard-UX?node-id=3-89231&t=jkqE6Rpi1XjXiH5v-1

### LINKED ISSUE #21592: No Oops, this isn't a Keycard screen when scanning not a Keycard
# Bug Report
https://github.com/status-im/status-mobile/pull/21467

### Reproduction

1. Login to app
2. Turn on Keycard feature flag
3. Go to Keycard Profile menu
4. Tap Setup Keycard
5. Tap Ready to scan
6. Use bank card instead of a Keycard

#### Actual behavior

**iOS** user sees previous `Check your Keycard` screen 

Image

**Android** freezes on scanning

Image

#### Expected behavior

User should see `Oops, this isn't a Keycard` screen

Image

https://www.figma.com/design/YGm3igIOAcwMqUVJWCJ6f1/Keycard-UX?node-id=3-89231&node-type=canvas&t=uyFSGjy76z82d9RO-0

### Additional Information

- Status version: PR build https://github.com/status-im/status-mobile/pull/21467
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by flexsurfer**
fixes #21559
fixes #21592

### CODE REVIEW

**Review by seanstrom — APPROVED** [review]

**Review by Parveshdhull — APPROVED** [review]

**Comment by mariia-skrypnyk** [comment]
Hi @flexsurfer !

Thanks for your PR.

Here is an issue that blocks my testing.
Please take a look below.

**ISSUE 1:** [iOS] Oops screen opens instead of scanning keycard modal

**Steps:**

1. Login to app
2. Go to Profile -> Keycard
3. Start migration flow
4. Set pin and tap on `Ready to scan`

**Actual result:**

Oops screen now opens every time I want to start the flow

https://github.com/user-attachments/assets/d75493a0-b24b-4fea-8a5b-88b0fd2baf25

**Expected result:**

User is able to magrate a key pair and Oops flow appears in case user scan's not a Keycard

**Comment by flexsurfer** [comment]
hey @mariia-skrypnyk  thank you, sorry i can't reproduce, works fine for me :(

**Comment by mariia-skrypnyk** [comment]
Hope it will help!  
UPD: iOS only!


https://github.com/user-attachments/assets/1c823f3b-c613-414d-86fa-a86ebbbc6f8f

**Comment by mariia-skrypnyk** [comment]
**ISSUE 2: No warning text regarding PIN attempts**

**Steps:**

1. Install app
2. Login with Keycard
3. Scan Keycard with a key pair in it
4. Enter invalid PIN

**Actual result:**

photo_2024-11-18_18-47-53

**Expected result:**

Screenshot 2024-11-18 at 18 44 01

https://www.figma.com/design/YGm3igIOAcwMqUVJWCJ6f1/Keycard?node-id=3-89231&node-type=canvas&t=t0IkcfqJEaXgHC90-0


**ISSUE 3: Keycard is locked is shown after PIN entering**

1. Install app
2. Login with Keycard that is locked


**Actual result:**

Navigation is : 

`Enter Keycard PIN` -> `Keycard locked`

**Expected result:**

Navigation is : 

`Check your keycard` -> `scan` -> `Keycard locked`

Screenshot 2024-11-18 at 18 42 05


https://www.figma.com/design/YGm3igIOAcwMqUVJWCJ6f1/Keycard?node-id=3-89231&node-type=canvas&t=t0IkcfqJEaXgHC90-0

**Comment by mariia-skrypnyk** [comment]
**ISSUE 4: Oops screen appears every time user quickly scans his Keycard during login**

1. Install app
2. Login with Keycard : remove your card from scanner before scanning ends

**Actual result:**

Oops screen appears after every unsuccessful try of scanning

https://github.com/user-attachments/assets/08d1b3ae-fc74-4473-a71f-369829cd4516

**Expected result:**

Scanning drawer should be opened and no Oops screen

**Comment by mariia-skrypnyk** [comment]
**ISSUE 5: Keycard is not empty screen is shown instead of This is a different Keycard screen**

**Steps:**

1. Install app
2. Go to Login with a Keycard
3. Scan card that contains a key pair of User 1
4. On the next scanning use card with a key pair of User 2

**Actual result:**

Screenshot 2024-11-19 at 11 31 19

**Expected result:**

Screenshot 2024-11-19 at 11 22 41

https://www.figma.com/design/YGm3igIOAcwMqUVJWCJ6f1/Keycard?node-id=3369-60058&node-type=frame&t=uGB1LVLJZSppaulB-0

**Comment by flexsurfer** [comment]
- [ ] ISSUE 2: No warning text regarding PIN attempts - **Unable to reproduce**
- [x] ISSUE 3: Keycard is locked is shown after PIN entering
- [x] ISSUE 4: Oops screen appears every time user quickly scans his Keycard during login
- [ ] ISSUE 5: Keycard is not empty screen is shown instead of This is a different Keycard screen - let's create a separate task to unblock this PR

**Comment by flexsurfer** [comment]
thanks @mariia-skrypnyk 2 issues fixed, for other lets create separate tasks, thank you

**Comment by mariia-skrypnyk** [comment]
ISSUE 2

video how to reproduce


https://github.com/user-attachments/assets/d7fe71b1-8e7e-4dbe-9c18-237a1956c03d

**Comment by mariia-skrypnyk** [comment]
ISSUE 2 will be reported as a follow up

**Comment by mariia-skrypnyk** [comment]
Hey @flexsurfer !

Thanks.
I will add all leftovers as separate issues.
Failed e2e are not related and PR can be merged!

**Pull request merged**
