### PR TITLE
handle multiple calls to frozen-keycard-popup

### LINKED ISSUE #12462: App freezes until reopening when signing tx with frozen Keycard
# Bug Report

## Problem 
If Keycard was frozen in logged-in state and User tries to sign another tx, Status will freeze on the PIN screen. In this case, reopening is needed to continue using the app.

https://user-images.githubusercontent.com/67952253/129910068-666b4db6-7ef8-43f1-bb0d-d3eb2dead20c.mp4

### Reproduction

1. Open Wallet
2. Send transaction > Enter invalid PIN 3 times
3. Tap `Dismiss`
4. Enter valid PIN or tap `Cancel` and try to sign a new tx
5. Reopen Status

### Additional Information

- Status version: 1.15
- Operating System: Android, iOS

cc @bitgamma

### PR DESCRIPTION
**Pull request by bitgamma**
Fixes #12462

### CODE REVIEW

**Review by rasom — APPROVED** [review]

**Comment by churik** [comment]
@bitgamma 
Thank you for fix!
Noticed that on reproducing this issue https://github.com/status-im/status-react/issues/12462 on IOS apart from "Keycard is frozen" screen can see confusing "Wrong card" popup
Steps are: 
- login with keycard
- open Profile > Keycard > Change PIN
- enter wrong PIN 3 times
- on Frozen keycard popup tap "Dismiss"
- try to send tx
The same issue is reproducible on e2e builds, but I don't see it on Android.

Can you please take a look? 
IMAGE 2021-08-23 13:33:58

**Comment by bitgamma** [comment]
@churik thanks for catching this, hadn't tested on iOS. Should be fixed now

**Comment by churik** [comment]
Can reproduce with same steps on https://github.com/status-im/status-react/commit/ce576527f91317ee4905cd2782b14e9a4f720a97 commit
IMAGE 2021-08-23 14:41:05

**Comment by bitgamma** [comment]
@churik only on iOS or e2e build too? I had tested my fix against the e2e build for simplicity. Will have to check on iOS too

**Comment by churik** [comment]
@bitgamma 
on IOS it is reproducible with same steps.

on e2e: for me it is reproducible on e2e builds with test `test_keycard_frozen_card_flows`
Logs: https://app.saucelabs.com/tests/562b4c415cd84ceea4397b56723db935#421
Test steps for e2e:
- enter wrong PIN 3 times in "Change PIN"
- Dismiss
- go back to Profile
- open Keycard > Change PIN
- enter wrong PIN again

It appeared on nightly 20/08/21 and may be related to https://github.com/status-im/status-react/commit/2a6cb978ba73a57999b0b517b40f75ff3eec6584 
It can be separate and not related to this PR, however not sure ( I mean how it will be better to fix it here or separately)

**Comment by bitgamma** [comment]
@churik as agreed I removed the ineffective fix and will fix that issue separately. Is this PR ready to merge?

**Comment by churik** [comment]
yes, I'll report remaining separately

**Pull request merged**
