### PR TITLE
fix deep links to user profiles don't do anything on tap

### LINKED ISSUE #15068: Deep links to user profiles don't do anything on tap
# Bug Report

## Problem 
When tapping deep link with user profile  > open in status, there is no redirect to corresponding user profile

#### Expected behavior
user profile is opened

#### Actual behavior

https://user-images.githubusercontent.com/4557972/218164563-2bad51e1-a590-4965-8a20-f69b64107ec3.mp4

### Reproduction

1) Paste the link to the brower
2) Tap on open in Status

### Additional Information

- Status version: rc-1 #300 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by Parveshdhull**
fixes https://github.com/status-im/status-mobile/issues/15068

status: ready

### CODE REVIEW

**Review by ibrkhalil — APPROVED** [review]

**Comment by VolodLytvynenko** [comment]
Hi @Parveshdhull thank you for PR. Here the list of found issues:

**ISSUE 1: The shared profile page is not opened  if multi-account is created after deep link tapping**
**Precondition:**
- Multi-account of User_A is not created yet

**Steps to reproduce:**
1. User_B shares his deep link profile
2. User_A tap on the shared link

**Actual result:**
The profile of User_B is shown for a while, then 'jump to' page is opened

https://user-images.githubusercontent.com/52490791/219030632-691fe25d-daf7-44fc-b1f3-5cf190060769.mp4




**Expected result:**
The profile of User_B is opened

**ENV:** iPhone 11 Pro Max, version 15; Huawei P20 light version 9.



**ISSUE 2: The profile page is not opened for androids devices**
**Preconditions:** 
User_A uses Android OS

**Steps to reproduce:**
1. User_B shares his deep link profile
2. User_A tap on the shared link

**Actual result:**
The user is not navigated to the profile page after the profile page link is tapped

https://user-images.githubusercontent.com/52490791/219029116-301790b1-c5c8-4bb4-9825-53027f905cf7.mp4


**Expected result:**
The user is navigated to the profile page after the profile page link is tapped


**Additional info:**
For me, Issue 2 is reproducible probably in 90% of cases for android real and emulator devices

**ENV:** Real device:  Huawei p20 light, version 9. Android studio device: Pixel 6, version 10

**Comment by VolodLytvynenko** [comment]
**ISSUE 3: The non-compressed chat key is shown instead of compressed  if profile page is opened by shared link**
**Preconditions:**
User_A and User_B are not mutual  contacts

**Steps to reproduce:**
1. User_A shares his deep link
2. User_B taps on the shared link of User_A

**Actual result:**
The profile page is opened with the non-compressed chat key of User_A
image

**Expected result:**
The profile page is opened with the compressed chat key of User_A

**Additional info:**
The chatkey will be turned as compressed If in the last step the 'add to contacts' button is tapped

**Comment by churik** [comment]
From all the issues a blocker for PR is `Issue 2` , others can be fixed later.

**Comment by Parveshdhull** [comment]
Hi @VladimrLitvinenko, Thank you very much for testing the PR.

> For me, Issue 2 is reproducible probably in 90% of cases for android real and emulator devices

I tried both on emulator and real device, with app closed and open state. But I am not able to reproduce this issue myself

**Comment by Parveshdhull** [comment]
issue 3 should be fixed now

**Comment by VolodLytvynenko** [comment]
> Hi @VladimrLitvinenko, Thank you very much for testing the PR.
> 
> > For me, Issue 2 is reproducible probably in 90% of cases for android real and emulator devices
> 
> I tried both on emulator and real device, with app closed and open state. But I am not able to reproduce this issue myself

@Parveshdhull Got it. I will try to reproduce and more accurately describe the steps

**Comment by churik** [comment]
ISSUE 2 and ISSUE 3 are not reproducible for me on Xiaomi Mi Note 9.
@VladimrLitvinenko please, re-check on your side as well and ready to go.


Thank you @Parveshdhull 👍

**Comment by VolodLytvynenko** [comment]
@Parveshdhull Thank you for the fixes. No critical issues from my side. Could you merge it, please?

**Pull request merged**
