### PR TITLE
Dont try to show current chat if nil

### LINKED ISSUE #6963: 'Null is not an object located in group-chat-profile' app crash when deleting Group Chat from group info screen
*Type*: Bug

*Summary*: App crashes when group chat member (admin or participant) deletes Group Chat via 'Delete Chat' option located at `Group info` screen.
Note: It's OK if delete group chat via 'Delete Chat` option from chat-menu options.

#### Expected behavior
After 'Delete chat' option submitted from 'Group info' screen: Group chat deleted and user navigated to Home screen. 

#### Actual behavior
'Null is not an object located in group-chat-profile' app crash when deleting Group Chat from group info screen

screenshot 2018-11-30 at 13 09 28

### Reproduction

- Open Status and create new account (`Contact1(admin)`)
- Add any contact (`Contact2(member)`)
- Create 'Group Chat' with added contact
- Navigate by `Contact1(admin)` OR `Contact2(member)` from Group Chat screen to: top-right menu -> `Group info`
- Tap `Delete chat` option

### Additional Information
* Status version: Develop, release 0.9.32
* Operating System: Android and iOS

#### Logs

TBD....

### PR DESCRIPTION
**Pull request by cammellos**
fixes: #6963 
It seems for some reason there's a bit of race condition in navigation, quick fix for release, I'll look into it more deeply after release rush
status: ready

### CODE REVIEW

**Comment by lukaszfryc** [comment]
Is it needed if we cherry pick https://github.com/status-im/status-react/pull/6932?

**Comment by cammellos** [comment]
@lukaszfryc no, but I split it in case we didn't want to include this in release

**Comment by Serhy** [comment]
I've tested above builds https://github.com/status-im/status-react/pull/6965#issuecomment-443206616 and can confirm issue is not reproduced. 
Single failed autotest is a known issue. 

Once this PR gets approves we can merge it and include in release/0.9.32

**Comment by cammellos** [comment]
@Serhy I have already cherry picked this on release branch, @lukaszfryc was keen on cherry-picking https://github.com/status-im/status-react/pull/6932 as it tested ok, what should we do?

**Comment by Serhy** [comment]
I would say we keep current fix in 0.9.32 and do not include https://github.com/status-im/status-react/pull/6932 

#6932 consists new features we are about to merge after decision of what were we going to intruduce in the upcoming Release build, - i.e. release/0.9.32 branch cut off (note, - https://github.com/status-im/status-react/pull/6935 is the one that fixed release blocker #4868 )

**Comment by cammellos** [comment]
i am ok with that if we are all in agreement, in that case nothing to be
done as already cherry picked

**Review by dmitryn — APPROVED** [review]

**Comment by lukaszfryc** [comment]
Removing release label as it's already cherry picked into release/0.9.32.

**Review by flexsurfer — APPROVED** [review]

**Pull request merged**
