### PR TITLE
test DO waku nodes

### PR DESCRIPTION
**Pull request by qfrank**
this PR is created only for testing message reliablity

### CODE REVIEW

**Comment by churik** [comment]
As e2e show, the issue with contact request is still there, they are stuck sometimes.
Sender (from 04:40): https://app.eu-central-1.saucelabs.com/tests/dc35b270806c441ab8e99867f1f8f02e?auth=4f36ec7c3f266d7ad4180ed41746fad2#56
Geth.log: 
[TestOneToOneChatMultipleSharedDevicesNewUiTwo_geth0.log](https://github.com/status-im/status-mobile/files/13614688/TestOneToOneChatMultipleSharedDevicesNewUiTwo_geth0.log)

The receiver could not get a contact request for 60 seconds and the whole group of tests are failed because of that.
Receiver (waiting till 05:52): https://app.eu-central-1.saucelabs.com/tests/63b6441483b24386a2e405e1544047b6?auth=e7d246cd193ef61fc66c620bb6898fc7#64

Geth.log: 
[TestOneToOneChatMultipleSharedDevicesNewUiTwo_geth1.log](https://github.com/status-im/status-mobile/files/13614709/TestOneToOneChatMultipleSharedDevicesNewUiTwo_geth1.log)

The default fleet in your PR is `status.prod`.

Manually the message reliability seems better.

**Comment by qfrank** [comment]
Thank you for your feedback, @churik. I've shut down the Waku nodes to prevent further increasing the Digital Ocean fees. I'll check the logs to see if I can find any useful information.

**Comment by qfrank** [comment]
image

Is above possibly related to the message reliability issue? cc @cammellos 

also from the log we can see reason why can't send message:

```
...

ERROR[12-08|12:35:35.395|github.com/status-im/status-go/vendor/github.com/waku-org/go-waku/waku/v2/protocol/lightpush/waku_lightpush.go:184] creating stream to peer                  peer=16Uiu2HAm9VCJHSbMt6jDE4X2zdTPDyUk9APL7aPRkUPdxN9HcyW6 error="failed to dial: failed to dial 16Uiu2HAm9VCJHSbMt6jDE4X2zdTPDyUk9APL7aPRkUPdxN9HcyW6:\n  * [/ip4/139.59.255.0/tcp/60002] failed to negotiate security protocol: EOF"
ERROR[12-08|12:35:35.395|github.com/status-im/status-go/wakuv2/waku.go:1044]                                                                 could not send message                   envelopeHash=0x3acabcf5cc6d42a7757f5126cfe1db50cb7d557a4a314402f7a29fb47f630595 pubsubTopic=/waku/2/default-waku/proto contentTopic=/waku/1/0x6f09b96e/rfc26 timestamp=1,702,038,935,066,015,430 error="failed to dial: failed to dial 16Uiu2HAm9VCJHSbMt6jDE4X2zdTPDyUk9APL7aPRkUPdxN9HcyW6:\n  * [/ip4/139.59.255.0/tcp/60002] failed to negotiate security protocol: EOF"

...


ERROR[12-08|12:35:35.398|github.com/status-im/status-go/vendor/github.com/waku-org/go-waku/waku/v2/protocol/lightpush/waku_lightpush.go:184] creating stream to peer                  peer=16Uiu2HAm5tZRpbHwYJSxfdt945EbeoysizD28pPmNQCyeS2S341Q error="failed to dial: failed to dial 16Uiu2HAm5tZRpbHwYJSxfdt945EbeoysizD28pPmNQCyeS2S341Q:\n  * [/ip4/139.59.255.0/tcp/60001] dial backoff"
ERROR[12-08|12:35:35.398|github.com/status-im/status-go/wakuv2/waku.go:1044]                                                                 could not send message                   envelopeHash=0x22e0bae6d04e5baa466fd30ef1bae8b8abcca18317718957f8c2da95c17e1453 pubsubTopic=/waku/2/default-waku/proto contentTopic=/waku/1/0x6f09b96e/rfc26 timestamp=1,702,038,935,397,839,568 error="failed to dial: failed to dial 16Uiu2HAm5tZRpbHwYJSxfdt945EbeoysizD28pPmNQCyeS2S341Q:\n  * [/ip4/139.59.255.0/tcp/60001] dial backoff"
DEBUG[12-08|12:35:35.398|github.com/status-im/status-go/protocol/transport/envelopes_monitor.go:291]                                         retrying to send a message               namespace=EnvelopesMonitor hash=0x22e0bae6d04e5baa466fd30ef1bae8b8abcca18317718957f8c2da95c17e1453 attempt=6
```

it seems the network of simulator is totally not usable

**Comment by qfrank** [comment]
maybe we can retry once this [PR](https://github.com/status-im/status-mobile/pull/17773) get merged? @churik

**Comment by churik** [comment]
cc @status-im/mobile-qa

**Comment by flexsurfer** [comment]
hey @qfrank still relevant?

**Comment by qfrank** [comment]
> hey @qfrank still relevant?

we can close this now, because message reliability has been improved from my experience, e.g. Contact/Community Request

**Pull request closed without merging**
