### PR TITLE
[#19299] fix: design feedback for settings screen

### LINKED ISSUE #19299: Profile - Settings screen issues
# Design Feedback 2.27

## [Profile] Settings screen issues
Figma frame of the Review [here](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj/Release-Reviews?type=design&node-id=36%3A115879&mode=design&t=O3UNQJbRpr0lqKTe-1)

- **Status dropdown icon** [[comment](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj?node-id=36:115879&mode=design#717791641)] has switched colors when set to _Automatic_
- **Vertical spacing** [[comment](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj?node-id=36:115879&mode=design#726028743)] between settings category list
- **Placeholder icon** [[comment](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj?node-id=36:115879&mode=design#717793279)] in the _dApp_ setting category should be updated according to design
- **Opening animation** [[comment](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj?node-id=36:115879&mode=design#726065519)] of the category should be from right to left, not coming from the bottom
- **Jump to button** [[comment](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj?node-id=36:115879&mode=design#727293681)] shouldn't be below the overlay, there should only be one _Jump to_ that "travels" with the user wherever they are
- **Bottom margin** [[comment](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj?node-id=36:115879&mode=design#727520919)] between _Jump to_ and bottom of the screen

Screenshot 2024-03-18 alle 09 53 00

### Reproduction

1. Open Profile settings by pressing the user avatar at the top left corner of the screen

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS
- Devices in the screenshots: iPhone 13

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by mohsen-ghafouri**
fixes #19299

#### Done
- Vertical spacing [[comment](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj?node-id=36:115879&mode=design#726028743)] between settings category list
- Placeholder icon [[comment](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj?node-id=36:115879&mode=design#717793279)] in the dApp setting category should be updated according to design
- Jump to button [[comment](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj?node-id=36:115879&mode=design#727293681)] shouldn't be below the overlay, there should only be one Jump to that "travels" with the user wherever they are
- Bottom margin [[comment](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj?node-id=36:115879&mode=design#727520919)] between Jump to and bottom of the screen

#### Follow up
using right to left animation is not applicable to old screens yet. it should be done once we redesign them 
- Opening animation [[comment](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj?node-id=36:115879&mode=design#726065519)] of the category should be from right to left, not coming from the bottom

#### Areas that maybe impacted

- Settings screen

### Steps to test

- Open Profile settings by pressing the user avatar at the top left corner of the screen

### Result

status: ready

### CODE REVIEW

**Review by jo-mut — APPROVED** [review]

**Review by Parveshdhull — APPROVED** [review]

**Comment by mohsen-ghafouri** [comment]
@status-im/mobile-qa could you please check test results and if all good move it to design review step?

**Comment by VolodLytvynenko** [comment]
@mohsen-ghafouri failures are not PR related. Thank you. Moved to design review

**Comment by VolodLytvynenko** [comment]
hi @Francesca-G could you take a look at this PR , please?

**Review by Francesca-G — APPROVED** [review]
Looks good ✨

**Pull request merged**
