### PR TITLE
Update usage of Login/Create/Restore account

### LINKED ISSUE #19419: Update usage of Login/Create/Restore account
# Problem

This PR introduces breaking changes to `LoginAccount`/`CreateAccountAndLogin`/`RestoreAccountAndLogin`:
- https://github.com/status-im/status-go/pull/4980

## What changed?

- Added `FetchBackup` parameter to `RestoreAccount`. 
It's `false` by default, this is a change of default behaviour.
If you want to keep your current behaviour, set this to `true`.

- Added `ImageCropRectangle` to `CreateAccount`. 
Don't know if you want to reuse it. Cropping already works for you now.

- Allow `CreateAccount.displayName` to be empty when an account is being restored. 
This is to create an account, then fetch the backup and save the displayName from backup.
Since you don't currently support restoring an account without setting a new `displayName`, maybe you don't need this.

- `CreateAccount.CurrentNetwork` is deprecated. Just remove it, no need to pass anything instead

- `CreateAccount.NetworkID` is now optional. Default network is selected automatically.

## QA

@qoqobolo it would be nice to make sure that those workflows are fine with my status-go changes:
- login into account
- create a new account
- restore an account from seed phrase

### PR DESCRIPTION
**Pull request by seanstrom**
[comment]: # (Please replace ... with your information. Remove < and >)
[comment]: # (To auto-close issue on merge, please insert the related issue number after # i.e fixes #566)

fixes https://github.com/status-im/status-mobile/issues/19419

### Summary

 * WIP

#### Platforms

- Android
- iOS

##### Functional

* Login of accounts
* Creating accounts
* Restoring Accounts

### Steps to test
WIP

### Before and after screenshots comparison
WIP

status: ready

### CODE REVIEW

**Comment by smohamedjavid** [comment]
I don't know why this PR is in Draft state, but the code looks good to me 👍

**Comment by qfrank** [comment]
> I don't know why this PR is in Draft state, but the code looks good to me 👍

same feeling

**Comment by qoqobolo** [comment]
@smohamedjavid @qfrank thanks for reviewing guys!
This PR is created to test [these go changes](https://github.com/status-im/status-go/pull/4980) on the mobile side. 

But I see that this PR also contains some changes on our side. @seanstrom could you confirm if we're gonna merge this PR as well and clarify why it's in Draft state please? 

---

From the QA perspective: I tested the basic flows manually (creating a new profile, restoring from seed, login, logout, biometrics, sync, a new wallet account creation), e2e results also look good, so both this and go PR can be merged.
cc @igor-sirotin

**Comment by seanstrom** [comment]
Yup yup we'll be ready to merge this PR once the [status-go changes](https://github.com/status-im/status-go/pull/4980) are merged and the status-go version is bumped and tagged in git.

**Comment by seanstrom** [comment]
Sorry for the draft state, I wasn't sure if this PR was going to be merged initially, I've made it ready for review now 👍. 
cc @qfrank @smohamedjavid

**Review by smohamedjavid — APPROVED** [review]

**Comment by qoqobolo** [comment]
Thanx for the clarification @seanstrom!
Let's wait for the go PR then 👍

**Comment by igor-sirotin** [comment]
Thanks everyone! I've merged the status-go PR now 🙌

**Review by qfrank — APPROVED** [review]

**Comment by pavloburykh** [comment]
@seanstrom PR is ready to be merged. In case this is your first time of merging PR containing go changes please ask devs how to bump status go version correctly when merging. Thank you!

**Comment by seanstrom** [comment]
I've updated the status-go version in this PR to the newly tagged version of status-go v0.178.0
Let me know if this seems alright 🙏 
cc @qfrank @smohamedjavid @igor-sirotin

**Pull request merged**
