### PR TITLE
Design review: create profile password

### LINKED ISSUE #17503: Design review: create profile password
* [x] 1. "Tips to improve password" text alignment - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=5960:183&mode=design#567057141)
* [x] 2. Password circle progress bar size  - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=6117:67315&mode=design#570703335)
* [ ] 3. Password circle should animate as password improves  - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=6117:67315&mode=design#567045823)

### PR DESCRIPTION
**Pull request by alwx**
fixes #17503
BUT doesn't add the animation because it's a bit tricky with SVG and because there is no animation specification.

#### Platforms

- Android
- iOS

##### Functional

- create password screen

status: ready

### CODE REVIEW

**Review by flexsurfer — APPROVED** [review]

**Review by ajayesivan — APPROVED** [review]

**Comment by mariia-skrypnyk** [comment]
Hi @alwx !

Are you sure you added your fixes to the build?
I see incorrect alignment and wrong circle size. 
photo_2024-01-29_15-53-41
photo_2024-01-29_15-53-45

**Review by jo-mut — APPROVED** [review]

**Comment by mariia-skrypnyk** [comment]
Hi @alwx do you have any updates on this PR?

**Comment by alwx** [comment]
@mariia-skrypnyk ready

**Comment by mariia-skrypnyk** [comment]
Hi Alex!

Thanks for your fixes. 
I've checked and move it to the design review for @Francesca-G approve.

Failed tests are not related to the current changes.

**Review by Francesca-G — COMMENTED** [review]
here's the [design review](https://www.figma.com/file/oRQ5TcgMHKkK79EUfURg3e/Review-Onboarding-%2F-Mobile?type=design&node-id=1%3A86622&mode=design&t=3Ht8TUwWYenqrGZ5-1) ☺️

**Comment by alwx** [comment]
@Francesca-G could you check it again? I replaced the component we use to show the info message ("Minimum 10 characters") with the same one used on the previous screen (which is "Create profile") so now it's consistent and its style is the same.

**Review by Francesca-G — APPROVED** [review]
@alwx I noticed that now the "Passwords do not match" error is grey and should be red:

Screenshot 2024-02-14 alle 16 44 50

>
Besides that everything looks good now ✨

**Comment by alwx** [comment]
@Francesca-G updated now

**Pull request merged**
