### PR TITLE
Implement Onboarding - New intro screen

### LINKED ISSUE #21561: Onboarding - Update carousel
# Feature

### Description

We are changing the order of images in the onboarding carousel. Wallet and Keycard images are shown first. Communities image is gone. The new order is:

- Own your crypto
- Store your assets on Keycard
- Chat privately with friends
- Discover web3

Figma: https://www.figma.com/design/o4qG1bnFyuyFOvHQVGgeFY/Onboarding-for-Mobile?node-id=15075-44523&node-type=instance&m=dev

### Acceptance Criteria

Images in Figma are not ready as of Nov 5 2024. Before working in this issue, check if the assets are ready.

### LINKED ISSUE #21562: Onboarding - New intro screen
# Feature

### Description

The new intro screen is less intrusive and easier to understand. Notable changes:

- There's no checkbox to accept the Terms of Service and Privacy Policy.
- Buttons have been renamed to "Create profile" and "Sign in".
- When the user first proceeds from "Create profile" or "Sign in", an opt-in usage data screen is shown (not a bottom sheet).
- The usage data screen is simpler and the user has to press on "Learn more" to see more details about what will be collected.

### Acceptance Criteria

- Images in Figma are not ready as of Nov 5 2024. It's fine to work in this issue without the assets because they can be updated in a follow-up PR.

- We have separated the changes for the new usage data screen, so they are out of scope.

### Resources

- Figma https://www.figma.com/design/o4qG1bnFyuyFOvHQVGgeFY/Onboarding-for-Mobile?node-id=15075-44520&node-type=frame&m=dev

### PR DESCRIPTION
**Pull request by Parveshdhull**
fixes https://github.com/status-im/status-mobile/issues/21562
fixes https://github.com/status-im/status-mobile/issues/21561

https://github.com/user-attachments/assets/2776f640-bbc9-4b9f-beb2-e33a1da58880

status: ready

### CODE REVIEW

**Review by ilmotta — APPROVED** [review]

**Comment by Parveshdhull** [comment]
It seems that we also need to update the end-to-end tests to align with the new onboarding changes. cc: @status-im/mobile-qa

**Comment by pavloburykh** [comment]
> It seems that we also need to update the end-to-end tests to align with the new onboarding changes. cc: @status-im/mobile-qa

Thanks for the PR and pinging @Parveshdhull 

@yevh-berdnyk could you please take a look?

**Review by flexsurfer — APPROVED** [review]
have you looked if it's possible to simplify improve performance of this screen?

**Comment by Parveshdhull** [comment]
> have you looked if it's possible to simplify improve performance of this screen?

Hi, For now, I’m primarily focused on UI changes to prepare the onboarding migration for 2.32.0. (Removal of code/features should give at least some performance improvement)

Regarding the intro screen, I believe the heaviest component is the background carousel. I think In trying to make it reusable, we ended up complicating it with tangled logic and an unusual blur overlay state management. I can revisit this once the migration is complete.

Please let me know if you have any suggestions.

**Comment by yevh-berdnyk** [comment]
**UPD: not relevant**

Hi @Parveshdhull, thanks for the PR!
I've updated e2e tests and now I see that one of the tests fails because of the next issue:
Having 2 profiles on the device we remove one of them. After that we terminate the app, restart it and got the next screen:
Screenshot 2024-05-23 at 19 44 04
But we expect the remaining profile to be shown on this step. 
Please look at the video: 

https://github.com/user-attachments/assets/c37792b5-2b4b-4c7e-a9f0-91794d27b691

**Comment by yevh-berdnyk** [comment]
> Hi @Parveshdhull, thanks for the PR! I've updated e2e tests and now I see that one of the tests fails because of the next issue: Having 2 profiles on the device we remove one of them. After that we terminate the app, restart it and got the next screen: Screenshot 2024-05-23 at 19 44 04 But we expect the remaining profile to be shown on this step. Please look at the video:
> 
>  2024-11-08.19.51.52.mp4

@Parveshdhull sorry, I've missed that this screen was added in other PR and it's expected :(
I'll finish with updating the tests right now

**Comment by Parveshdhull** [comment]
hi, @Francesca-G PR is ready for design review, thank you

**Comment by Francesca-G** [comment]
> hi, @Francesca-G PR is ready for design review, thank you

Hello! Design isn't locked yet for this, the Figma file of the simplified onboarding is still a WIP. Please refer to Pedro for any question :)

**Review by seanstrom — APPROVED** [review]

**Comment by Parveshdhull** [comment]
We agreed that onboarding simplification PRs will be merged without a design review. Once the designs are finalized, we can review these screens and give them the final touch.

Skipping manual QA as the PR is simple, minor, and self-tested.

**Pull request merged**
