### PR TITLE
Feature: add wallet network settings to app settings

### LINKED ISSUE #19947: [Epic] - Feature - Mobile Wallet Settings - Network Settings
All features related to issue for epic - [E:Mobile Wallet Settings - Key Pairs and Accounts](https://github.com/status-im/status-mobile/labels/E%3AMobile%20Wallet%20Settings%20-%20Key%20Pairs%20and%20Accounts)

### User Story
- As a user, I want to be able to manage my network settings from within the wallet settings screen. 
- I want to be able to view the supported wallet networks
- I want to be able to enable and disable Testnet mode from the network settings inside wallet settings
- ~~I want to be able to disable Testnet mode by pressing on the global Testnet mode banner~~

**Related Designs**:
Overview of the de-scoped Network Settings flows: [the Figma designs](https://www.figma.com/file/hLFPHYnuM0pOzgiabtqQ6k/Descoped-Wallet-settings-for-Mobile?type=design&node-id=128-219598&mode=design&t=CtD5ivvGpzuXMOt0-4)

**Features**:
These features should be hidden behind a feature flag.

Mobile Wallet Settings: implement the UI for displaying supported wallet networks:
- [x] https://github.com/status-im/status-mobile/issues/19924

Mobile Wallet Settings: implement the UI for enabling and disabling Testnet mode:
- [x] https://github.com/status-im/status-mobile/issues/19925

Update: this feature has been descoped from this epic
~~Mobile Wallet Settings: implement the UI for disabling Testnet mode via pressing the global Testnet mode banner:~~
~~https://github.com/status-im/status-mobile/issues/19926~~

**Closing this issue**
Once all of these issues are ready the corresponding feature Flag Can be removed. This pr to remove the feature flag can then be used for QA and Design to ensure everything is feature complete and this issue can be closed.

### PR DESCRIPTION
**Pull request by seanstrom**
[comment]: # (Please replace ... with your information. Remove < and >)
[comment]: # (To auto-close issue on merge, please insert the related issue number after # i.e fixes #566)

fixes #19947

### Summary

* This PR attempts to reveal the feature-flagged network settings inside wallet settings

### Review notes

* A summary of the related features that need to tested and reviewed can be found in this epic: https://github.com/status-im/status-mobile/issues/19947

### Testing notes

* If testing with a development environment, remember to update the `.env` file with `ENABLE_ALERT_BANNER=1` so the app will display the Testnet Mode banner.

#### Platforms

- Android
- iOS

##### Functional

- Settings
- Wallet Settings
- Wallet Network Settings
- Testnet Mode

### Steps to test

* Steps to test this feature can be found in the related issues that described in this epic: https://github.com/status-im/status-mobile/issues/19947

status: ready

### CODE REVIEW

**Review by mohsen-ghafouri — APPROVED** [review]

**Review by smohamedjavid — APPROVED** [review]

**Comment by VolodLytvynenko** [comment]
Hi @seanstrom, I'm trying to understand how to achieve the "testnet is not available" status as shown in [this design](https://www.figma.com/design/hLFPHYnuM0pOzgiabtqQ6k/Descoped-Wallet-settings-for-Mobile?node-id=128-219598&t=epEb8OHUygRgXLp3-0) for Optimism.

I encountered a toast message saying "the provider for the following chain is down: Arbitrum" even though Arbitrum is shown as active in the wallet settings.
image


Should the network be displayed as "testnet is not available" when the provider is down?

### Logs:
[Status-debug-logs.zip](https://github.com/user-attachments/files/15534066/Status-debug-logs.zip)

**Comment by smohamedjavid** [comment]
> Should the network be displayed as "testnet is not available" when the provider is down?

@VolodLytvynenko - No, The label `Testnet is not available` is meant if the user changes the network configuration for a chain (not available in mobile yet), resulting in a network error.

On the other hand, the desktop app shows the `Sepolia active` label even if the provider is down.

**Comment by VolodLytvynenko** [comment]
> > Should the network be displayed as "testnet is not available" when the provider is down?
> 
> @VolodLytvynenko - No, The label `Testnet is not available` is meant if the user changes the network configuration for a chain (not available in mobile yet), resulting in a network error.
> 
> On the other hand, the desktop app shows the `Sepolia active` label even if the provider is down.
> 
> 

@smohamedjavid  Thank you for the clarification.

@seanstrom PR is ready to be merged. Thank you for your work!

**Comment by seanstrom** [comment]
@Francesca-G can you do a design review for this PR please? 🙏

**Review by Francesca-G — COMMENTED** [review]
Here's the [review](https://www.figma.com/design/FuHW0rmIa5fQr5yyt3pXM6/Review-Wallet-%2F-Mobile?node-id=78-23031&t=iYrf0sOVLP2Yehgi-1) 🙏

**Comment by seanstrom** [comment]
@Francesca-G Oki doki 🧑‍🌾 
I think we're ready for another design review 🎨 

* I think I fixed the spacing issues
* I think I fixed the colour issues related to the button and info-box
* I've tried my best to fix the colour issues that are related to blurry backgrounds being too blue.
  * We may need to do a separate design-review for all the places that have issues with blur, I think there may be more than ones related to wallet settings. Lmk if that's okay with you to create a separate issue 🙏 
  * There are some prior issues for context: https://github.com/status-im/status-mobile/pull/14783#discussion_r1084603578 and https://github.com/status-im/status-mobile/issues/14903#issuecomment-1624357867

**Review by Francesca-G — COMMENTED** [review]
@seanstrom thank for addressing the issues!

the blur and the color issues seem to be fixed. nice job! ✨
the vertical spacing still needs some adjusting ([Figma](https://www.figma.com/design/FuHW0rmIa5fQr5yyt3pXM6/Review-Wallet-%2F-Mobile?node-id=78-23031&t=c9gzHDsusj2wDglx-1))

Screenshot 2024-06-04 alle 16 09 38

>

Feel free to create a separate issue for the blur as it's a recurring problem, thanks for pointing it out 🙏

**Comment by seanstrom** [comment]
@Francesca-G thanks for the feedback!
I've tried tweaking the spacing/alignment of these elements to closely match the designs 📏
So I think I'm ready for another design review 🙏

**Review by Francesca-G — APPROVED** [review]
Looks good now ✨ nice job!

**Pull request merged**
