### PR TITLE
[#6283] fix unknown chat after transaction

### LINKED ISSUE #6283: 'Unknown' contact screen is shown after transaction signed in Dapp
### Description

*Type*: Bug

*Summary*: Unknown contact screen is shown after i requested stt from simple dapp on Ropsten
There is a forced navigation chat screen happens after Sign Transaction -> tap 'Got it' button in the case when `Transaction Fee` being updated during. 
Navigation occurs to the most recent chat visited before transacting in the Dapp. In a case, there were no chats prior Dapp TX at all - 'Unknown' chat created.
In any case issue is that we navigate to chat screen after the transaction in Dapp made. 

#### Actual behavior

image

#### Expected behavior
 User stays on Dapp screen after transaction sign in Dapp.

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status develop (build locally)
- Go to Ropsten with new account
- Request ETH in simple dapp
- Request STT in simple dapp (expand Adnaced screen )
- Pay attention to the screen after you tap Got it

### Reproduction 2 
1) Open Status and create an account
2) Join public chat (e.g. `#cryptopeople`)
3) Open `SimpleTestDapp` -> `Assets`
4) `Request Ropsten ETH` (skip if you have ETH already)
4) `Advanced` -> `Transaction Fee` -> Tap `Done` button
5) Sign transaction 
**Actual result:** Contact navigated to `#cryptopeople` public chat 

TF session with logs: https://app.testfairy.com/projects/4803622-status/builds/8625368/sessions/4403800939/?accessToken=Zxcidk0V/5fszsWM0ymrc9M3n3I

### PR DESCRIPTION
**Pull request by rasom**
fix #6283

status: ready

### CODE REVIEW

**Review by yenda — APPROVED** [review]
could you rename act -> actions ?

**Review by dmitryn — APPROVED** [review]

**Comment by Serhy** [comment]
@rasom looks almost fixed! 
The only scenario I noticed when redirecting to chat happens is when Wallet 'Set Up' takes place prior transaction sign in Dapp. If Wallet had been set up not while Transacting in Dapp - all good.
As an example, - an app crash happens is when signing two transactions in a row. Please See steps to reproduce with TF session below:

1) Open Status and create new account
2) Switch to `RINKEBY RPC` network
3) Navigate to `Simple Test DApp` -> `Assets` -> tap `Request Rinkeby ETH`
4) Wait till assets received to your address (you can check in Wallet modal staying in Test Dapp balance)
5) Once ETH balance > 0, in Test Dapp navigate to` Transactions`
6) Tap `Send two Txs in batch, 0.00001 and 0.00002 ETH` button
7) `Set UP` wallet
8) `Advanced` -> `Transaction Fee` -> Tap `Done` button
9) Sign transaction
10) In the second `Send transaction` -> `sign transaction` again

**Actual result:** App crash with `01:15 E/ReactNativeJS: Error: Error: There is no route defined for key wallet-transaction-sent.
01:15 E/ReactNativeJS: Must be one of: 'open-dapp','home','new-chat','browser','new','new-group','qr-scanner','chat','group-chat-profile','dapp-description','add-participants-toggle-list','new-public-chat','contact-toggle-list','profile'
`

screen shot 2018-10-15 at 19 35 29


TF session: https://app.testfairy.com/projects/4803622-status/builds/8627765/sessions/4404027554/?accessToken=uWf3HtP-imeilrVAAfjdhcf00Yc

<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803622-status/builds/8627765/sessions/4404027554/?accessToken=uWf3HtP-imeilrVAAfjdhcf00Yc">TestFairy: Status 0.9.29 (10505) @2018</a></strong></div></blockquote>

**Comment by rasom** [comment]
@Serhy fixed

**Comment by asemiankevich** [comment]
looks good to me, i was not able to see this Unknown or been redirected to public chat when transactioning. The issue @Serhy mentioned is also fixed. Lets merge it

**Pull request merged**
