### PR TITLE
Remove fastlane metadata because no one use it

### PR DESCRIPTION
**Pull request by vkjr**
### Summary

Checked with @jakubgs, @cammellos, and @jinhojang6. No one needs those metadata files.

#### Platforms
- Android
- iOS

#### Areas that maybe impacted
Unknown

status: ready

### CODE REVIEW

**Review by jakubgs — COMMENTED** [review]
You haven't removed the Jenkinsfile at `ci/tools/Jenkinsfile.playstore-meta`.

**Comment by vkjr** [comment]
@jakubgs, thanks, done.

**Review by jakubgs — CHANGES_REQUESTED** [review]
Shouldn't you also remove the section about this in `doc/RELEASE_GUIDE.md` that you moved in #12085?

**Comment by vkjr** [comment]
@jakubgs, done

**Review by jakubgs — APPROVED** [review]

**Pull request merged**
