### PR TITLE
Fix crash when selecting photos from cameraroll [iOS]

### LINKED ISSUE #17203: iOS: app crashes when sharing an image message
## Problem 
When sharing an image message on iOS, the app crashes soon after selecting the image

#### Expected behavior
No crash

#### Actual behavior

https://github.com/status-im/status-mobile/assets/28704507/6750def7-295f-4199-a8f3-aee4dd1d8875

### Reproduction

1. Launch app
2. Open a 1-1 chat
3. Try to share an image message
4. As soon as you confirm to send the image, app crashes

### Additional Information
- Operating System: iOS

### PR DESCRIPTION
**Pull request by clauxx**
fixes #17203

### Summary

Fix the crash when selecting a photo from the camera roll e.g. when selecting photos from the chat composer.

#### Platforms

- iOS

##### Functional

- 1-1 chats
- public chats
- group chats

### Steps to test

- Open Status
- Open chat
- Press the image selector from the composer
- (Optionally accept permissions)
- Select images to share
- When pressing `Confirm selection`, the app would crash

status: ready

### CODE REVIEW

**Review by ajayesivan — APPROVED** [review]

**Comment by pavloburykh** [comment]
@clauxx thanx for the PR. 

I am wondering if this crash can be reproduced on real device via develop build? I am not able to reproduce therefore I cannot verify the fix. 

Are there any details how can I reproduce this crash on nightly build using real device?

**Comment by clauxx** [comment]
> @clauxx thanx for the PR. 
> 
> 
> 
> I am wondering if this crash can be reproduced on real device via develop build? I am not able to reproduce therefore I cannot verify the fix. 
> 
> 
> 
> Are there any details how can I reproduce this crash on nightly build using real device? 

Seems like the bug only appears in dev builds

**Comment by pavloburykh** [comment]
> Seems like the bug only appears in dev builds

No issues from my side on PR build. @clauxx if you are not facing crash on dev build any more then PR is ready for merge.

**Comment by ajayesivan** [comment]
I tested this branch and the issue is resolved for me. I think it's good to go 🚀

**Pull request merged**
