### PR TITLE
feature #3443 - automatically loading all dev contacts in nightlies 

### LINKED ISSUE #3443: Import Status Workspace Directory contacts for internal builds
Status has almost 100 employees, but (as yet) there isn't an easy mechanism that allows for Status members to easily find, add and start chatting with each other. By making it easy to find workmates it will be much easier to use status everyday https://github.com/status-im/ideas/issues/75 for internal chats.  

Todo:
- [x] Generate static json member directory for quick prototyping
- [x] Automate this json directory from the work done in https://github.com/status-im/status-workspace-directory with @jacqueswww 
- [ ] In the Status app, read this json file and add the members as contacts
- [ ] Only works in dev builds

The goal is to have this done this week in time for the offsite.

### PR DESCRIPTION
**Pull request by goranjovic**
fixes #3443

### Summary:

Automatically adds all Status devs as contacts in any non-release version. Useful for dogfooding.

### Steps to test:

- Start Status and create an account
- Try sending a message to check if you have any default contacts other than Jarrad. There should be all of us.

- Recover an existing account
- Also see if the contacts are there.

status: ready

### CODE REVIEW

**Review by jeluard — APPROVED** [review]

**Review by janherich — APPROVED** [review]

**Comment by oskarth** [comment]
@goranjovic How does this deal with push notification contact handshake?

**Comment by goranjovic** [comment]
@oskarth 

It uses the same code that previously added the Jarrad from the hardcoded json file, except in now it also adds the rest of us too, obtaining the list from a url. That's the only change I made.

Is that sufficient for PNs? Did they ever work for Jarrad's account?

**Comment by oskarth** [comment]
@goranjovic Not sure it did, at least on default account. They are definitely two different code paths - if you add someone as a contact you get their `fcm-token`, which is how you reach them. I'm not sure what the best way to fix it for this scenario is, but it seems like a desirable property to have. Otherwise PN won't be received during offsite.

(Making this robust and decoupled is in scope for PN v2, a separate swarm that will likely be lead by @PombeirP soon)

**Comment by goranjovic** [comment]
@oskarth Let's see if we can do that programmatically

**Comment by asemiankevich** [comment]
image

**Comment by asemiankevich** [comment]
@goranjovic can we check why I dont see myself in the list?

**Comment by goranjovic** [comment]
Closing this PR as fixing it properly would require changes well outside the scope of what was supposed to be a quick and dirty hack. Also we did this primarily for the offsite and which passed anyway.

**Pull request closed without merging**
