### PR TITLE
Merge/develop in desktop

### PR DESCRIPTION
**Pull request by maxhora**
related to #4730 

### Summary:

[comment]: # (Summarise the problem and how the pull request solves it)
Changes from `develop` branch merged into `desktop

### Review notes (optional):

Main change that had to be made in this merge is support of work with keychain.
`develop` branch uses `react-native-keychain` and `react-native-securerandom` 3rdparty libs to create/store/restore keys for realm db encryption.
So now we have 2 forks with desktop support:
https://github.com/status-im/react-native-keychain
https://github.com/status-im/react-native-securerandom

`react-native-keychain` implemented with the help of this project - https://github.com/frankosterfeld/qtkeychain

### Important
When you login or create account in StatusIm, your OS will ask you to enter system password to allow app accessing keychain. 

### Testing notes:
Linux package seems to be broken and errors out on startup. We agreed to investigate this and resolve after these changes are merged.
MacOS bundle from Jenkins should work fine.

### Steps to test:
- Open Status
- Enjoy!

status: ready 

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/status-im/react-native-keychain">status-im/react-native-keychain</a></strong></div><div>react-native-keychain - :key: Keychain Access for React Native</div></blockquote>
<blockquote><div> GitHub</div><div><strong><a href="https://github.com/status-im/react-native-securerandom">status-im/react-native-securerandom</a></strong></div><div>react-native-securerandom - A crypto-secure random bytes generator for react native</div></blockquote>
<blockquote><div> GitHub</div><div><strong><a href="https://github.com/frankosterfeld/qtkeychain">frankosterfeld/qtkeychain</a></strong></div><div>qtkeychain - Platform-independent Qt API for storing passwords securely.</div></blockquote>

### CODE REVIEW

**Comment by maxhora** [comment]
This PR is based on https://github.com/status-im/status-react/pull/4916 , but with following updates:
- available commits are rebased against latest desktop and signed with my signature
- linux build issues resolved ( react-native-desktop fixes + react-native-keychain temporary references custom branch with fix https://github.com/MaxRis/react-native-keychain.git#bug/linux-support )
- Jenkins build issues resolved (MacOS bundle should work fine; Linux package has known runtime failure on startup)

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/MaxRis/react-native-keychain">MaxRis/react-native-keychain</a></strong></div><div>react-native-keychain - :key: Keychain Access for React Native</div></blockquote>

**Comment by maxhora** [comment]
@rcullito updated changes shouldn't fail on Linux compilation, but on runtime during startup. I will try to resolve this failure in first order after this PR is merged.

**Review by vitvly — APPROVED** [review]

**Review by rcullito — APPROVED** [review]
thanks for the heads up regarding the linux runtime @MaxRis :+1:

**Comment by churik** [comment]
# 1.Status-Desktop is not usable after creating account if you click on "Share Data with Status"
### Steps
- Open StatusIm
- Create account
- Tap on "Share data". Popup with confirmation should appear.
- Tap on "Yes" or "Cancel"

### Expected result
can use Status

### Actual result
merged status

* OS: Mac OSx High Sierra
* Log: https://drive.google.com/file/d/1q5-9vglUXIhUt9znUsIy744QYju6UQRJ/view?usp=sharing
* Note: confirmation popup is missing in `desktop` branch, so the issue is presented only in particular PR. Only workaround is click on "Don't share".

**Comment by maxhora** [comment]
@churik thank you for finding this issue, I'm going to merge current PR and create separate Issue with your description.

**Pull request merged**
