### PR TITLE
Reloadable js resources for jail

### PR DESCRIPTION
**Pull request by rasom**
Instead of 
```
lein figwheel android
```

 you can run 

```
lein repl
```

and javascript files from `resources` dir will be reloaded on changes.

### CODE REVIEW

**Comment by jarradh** [comment]
does `BUILD_IDS=` need to be set? judging by changes this is more synonymous with `lein figwheel android ios` ?

**Comment by rasom** [comment]
Yes, if you are going to run builds for both android and ios it needs to be set to `BUILD_IDS="ios,android"`. By default `android` build will be started, so if you want to start only `ios` build you have to run `BUILD_IDS=ios lein repl`. 

I didn't find more elegant way to handle this with `lein repl` but maybe it exists.

**Comment by jarradh** [comment]
I got this error typing on a the command list icon after submitting the password message in Console. If dismissing the message i can no longer press the command list button.

- git checkout feature/reloadable-js-resources && git pull
- rm -rf node_modules && lein deps && npm install && ./re-natal deps
- new tab BUILD_IDS=android lein repl
- new tab react-native start
- react-native run-android
- tap password request, enter password, send message
- after confirmation messages, tap command icon

screen

**Comment by jarradh** [comment]
leaving chat and going to chats list, then tapping on console again shows
screen

**Comment by jarradh** [comment]
dismissing that message, somehow blue icon of command list icon goes to bottom left of icon, wut?

screen

**Comment by rasom** [comment]
Both issues were related to `reagent`, the last screen is hard to reproduce, I suppose it is related to broken state after previous error.

**Comment by jarradh** [comment]
works well! please squash

**Comment by rasom** [comment]
done

**Pull request merged**
