### PR TITLE
RN 63 and xcode12

### PR DESCRIPTION
**Pull request by flexsurfer**
RN 63 and xcode12

READY TO BE MERGED, WAITING FOR 10 release

### CODE REVIEW

**Comment by jakubgs** [comment]
Nice, in the process of doing this I found lack of support for transitive dependencies in `go-maven-resolver`:
https://github.com/status-im/go-maven-resolver/pull/5
Bu it's still not working. I'm getting some dependency errors that make no sense to me:
```
   > Could not find org.json:json:20180813.
     Searched in the following locations:
       - file:/nix/store/f3smfq421vkjx10kxapxcin22qah0ivn-status-react-maven-deps/org/json/json/20180813/json-20180813.pom
       - file:/nix/store/f3smfq421vkjx10kxapxcin22qah0ivn-status-react-maven-deps/org/json/json/20180813/json-20180813.jar
     Required by:
         project :react-native-config > com.android.tools.build:gradle:4.1.0 > com.google.crypto.tink:tink:1.3.0-rc2
```
Because `com.google.crypto.tink:tink:1.3.0-rc2` does not depend on `json-20180813`.

I've pushed what I have for now because I'm out tomorrow. This might be a bit tricky.

**Comment by jakubgs** [comment]
I also upgraded `macos-02` to XCode `12.3` and changed its label.

**Comment by jakubgs** [comment]
Even running updated `go-maven-resolver` with no ignored scopes returns multiple `json` packages but not the `20180813` one:
```
 > echo com.android.tools.build:gradle:4.1.0 | go-maven-resolver -ignoreScopes="" 2>/dev/null | grep json-20   
https://repo.maven.apache.org/maven2/org/json/json/20201115/json-20201115.pom
https://repo.maven.apache.org/maven2/org/json/json/20090211/json-20090211.pom
https://repo.maven.apache.org/maven2/org/json/json/20201115/json-20201115.pom
https://repo.maven.apache.org/maven2/org/json/json/20080701/json-20080701.pom
```

**Comment by jakubgs** [comment]
Why does `react-native-config` have to depend on such an ~~old~~ version of Gradle:
```
        classpath 'com.android.tools.build:gradle:4.1.0'
```
https://github.com/luggit/react-native-config/blob/601814f6066c8fb57ce138c1ca15d078ecb3befd/android/build.gradle#L8

~~It's over 3 years old.~~ Actually, this is Gradle build tools, not Gradle itself. Interesting.

**Comment by jakubgs** [comment]
Oh, I didn't even remember this but I forked that package to fix some build issue with this commit:
https://github.com/status-im/react-native-config/commit/248bb4454bf4c51e6e4111d0f8399d078ce79d26

**Comment by jakubgs** [comment]
Ooooooh, there we have it:

Plugin version | Required Gradle version
-|-
3.6.0 - 3.6.4 | 5.6.4+
4.0.0+ | 6.1.1+
4.1.0+ | 6.5+

https://developer.android.com/studio/releases/gradle-plugin

Looks like that build tools version can't work with our Gradle which is `5.6.4`. At most we can use `3.6.4` build tools.

**Comment by jakubgs** [comment]
So we should be able to use version `1.3.3` of `react-native-config`:
```
        classpath 'com.android.tools.build:gradle:3.1.4'
```
https://github.com/luggit/react-native-config/blob/v1.3.3/android/build.gradle#L8

**Comment by jakubgs** [comment]
Actually, the upgrade to `go-maven-resolver` might not be necessary if we're not pulling in Gradle Build tools `4.1.0`.

By not including that change we avoid pulling in additional `7` dependencies:
```
https://repo.maven.apache.org/maven2/antlr/antlr/2.7.7/antlr-2.7.7.pom
https://repo.maven.apache.org/maven2/com/google/protobuf/protobuf-bom/4.0.0-rc-2/protobuf-bom-4.0.0-rc-2.pom
https://repo.maven.apache.org/maven2/org/antlr/stringtemplate/3.2.1/stringtemplate-3.2.1.pom
https://repo.maven.apache.org/maven2/org/slf4j/jcl-over-slf4j/2.0.0-alpha1/jcl-over-slf4j-2.0.0-alpha1.pom
https://repo.maven.apache.org/maven2/org/slf4j/slf4j-api/2.0.0-alpha1/slf4j-api-2.0.0-alpha1.pom
https://repo.maven.apache.org/maven2/org/slf4j/slf4j-jdk14/2.0.0-alpha1/slf4j-jdk14-2.0.0-alpha1.pom
https://repo.maven.apache.org/maven2/org/slf4j/slf4j-parent/2.0.0-alpha1/slf4j-parent-2.0.0-alpha1.pom
```
We will need it once we decide to switch to Gradle 6 though.

**Comment by jakubgs** [comment]
Hmmmm
```
[2021-01-07T21:34:26.773Z] ❌  Undefined symbols for architecture arm64
[2021-01-07T21:34:26.773Z] > Symbol: _OBJC_CLASS_$_ReactNativeConfig
[2021-01-07T21:34:26.773Z] > Referenced from: objc-class-ref in AppDelegate.
[2021-01-07T21:34:26.773Z] ❌  ld: symbol(s) not found for architecture arm64
[2021-01-07T21:34:26.773Z] ❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
Seems like `clang` doesn't like something.

**Comment by flexsurfer** [comment]
thanks @jakubgs but there is a change in v1.4.0 we need for xcode12 in react-native-config, why latest version doesn't work for us ?

**Comment by flexsurfer** [comment]
can we upgrade gradle ?

**Comment by jakubgs** [comment]
Remember that if you merge this into `develop` there will be only one CI host available to do iOS builds.

On Monday I can upgrade another one to XCode 12.

**Comment by flexsurfer** [comment]
@jakubgs what project do we use to build ios PR ? it seems it ignores my changes

**Comment by flexsurfer** [comment]
@jakubgs ok i found the reason, fixed, lets merge and move all instances on xcode12

**Comment by cammellos** [comment]
@flexsurfer before we move all instances to xcode, maybe should we wait until release process is over?

**Comment by cammellos** [comment]
unless you are really confident that it won't impact it

**Comment by jakubgs** [comment]
That's probably sensible. When do we plan to release?

**Comment by cammellos** [comment]
@jakubgs this week RC has already been built, finger crossed it should work

**Comment by jakubgs** [comment]
BTW, I'd keep the `nix: add missing -u flag for sort in deps/gradle readme` commit as separate(first?) and merge the other ones, as they all are doing the same thing.

**Comment by flexsurfer** [comment]
@cammellos ok lets wait then, don't want to mess with the release

**Review by jakubgs — APPROVED** [review]
@flexsurfer  I've upgraded `macos-02` to XCode 12 too. Now only `macos-01` is using XCode 11. So I'd say we're ready to merge this. Though we probably should squash into one commit first.

A rebase would probably be a good idea too.

**Comment by flexsurfer** [comment]
done

**Comment by jakubgs** [comment]
Looks like iOS build failed on `macos-02` with:
```
The following build commands failed:
	CompileC /Users/jenkins/Library/Developer/Xcode/DerivedData/StatusIm-caaafoitvkzpeodouerqmjigllgn/Build/Intermediates.noindex/ArchiveIntermediates/StatusImPR/IntermediateBuildFilesPath/ReactNativeConfig.build/Release-iphoneos/ReactNativeConfig.build/Objects-normal/armv7/ReactNativeConfig.o /Users/jenkins/workspace/status-react_prs_ios_PR-11612/node_modules/react-native-config/ios/ReactNativeConfig/ReactNativeConfig.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /Users/jenkins/Library/Developer/Xcode/DerivedData/StatusIm-caaafoitvkzpeodouerqmjigllgn/Build/Intermediates.noindex/ArchiveIntermediates/StatusImPR/IntermediateBuildFilesPath/ReactNativeConfig.build/Release-iphoneos/ReactNativeConfig.build/Objects-normal/arm64/ReactNativeConfig.o /Users/jenkins/workspace/status-react_prs_ios_PR-11612/node_modules/react-native-config/ios/ReactNativeConfig/ReactNativeConfig.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(2 failures)
[09:42:59]: Exit status: 65
```
https://ci.status.im/job/status-react/job/prs/job/ios/job/PR-11612/11/consoleFull

**Comment by jakubgs** [comment]
Let me try to do some cleaning up on 02 first.

**Comment by jakubgs** [comment]
Oh, looking at `/Users/jenkins/Library/Logs/gym/Status PR-StatusImPR.log` gives some extra info:
```
../../../ios/Pods/Headers/Public/Flipper-Folly/folly/string.h:20:10: fatal error: 'cstdarg' file not found
#include <cstdarg>
         ^~~~~~~~~
1 error generated.
```
And near the end:
```
In file included from /Users/jenkins/workspace/status-react_prs_ios_PR-11612/node_modules/react-native-config/ios/ReactNativeConfig/ReactNativeConfig.m:1:
In file included from /Users/jenkins/workspace/status-react_prs_ios_PR-11612/node_modules/react-native-config/ios/ReactNativeConfig/ReactNativeConfig.h:2:
../../../ios/Pods/Headers/Public/React-Core/React/RCTBridgeModule.h:8:9: fatal error: could not build module 'Foundation'
#import <Foundation/Foundation.h>
```

**Comment by jakubgs** [comment]
Appears to be building fine on `macos-03`, so the issue is witht he host not with this PR:
https://ci.status.im/job/status-react/job/prs/job/ios/job/PR-11612/13/

**Comment by flexsurfer** [comment]
so its build fine with xcode11 but not with xcode12 ?

**Comment by jakubgs** [comment]
No no, `macos-01` is the only one with XCode 11 and we're not using it because of the Jenkins host labels.

Both `02` and `03` are on XCode 12 but `02` fails to build. I've cleaned up `02` and will try again.

**Comment by jakubgs** [comment]
you did it you crazy son of a bitch

**Comment by flexsurfer** [comment]
@churik @jakubgs lets merge ?

**Pull request merged**
