### PR TITLE
Fix status-go version

### PR DESCRIPTION
**Pull request by cammellos**
revert to 0.16.3
status: ready

### CODE REVIEW

**Comment by ghost** [comment]
### Pull Request Checklist
- [x] Have you updated the documentation, if impacted (e.g. [docs.status.im](https://docs.status.im/docs/build_status.html))?

**Review by pedropombeiro — APPROVED** [review]

**Review by yenda — APPROVED** [review]

**Comment by yenda** [comment]
@cammellos Does it require QA ?

**Comment by cammellos** [comment]
no, it s a revert basically

**Comment by cammellos** [comment]
tested the android build, all good, i will merge when in front of the
keyboard

**Pull request merged**
