### PR TITLE
Design Feedbacks on "Create profile password" screen

### LINKED ISSUE #15783: Design notes: generate keys flow > Password screen
## Problem 
Suggestions/issues on implementation in Figma are [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS/Feedback-for-Mobile?node-id=1922-172632&t=IygHPkoLwgiVR8Xa-4)

### First step
- [ ] Active first input with  opened keyboard (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1922:172632#428342839))
- [ ] Update "eye" icon (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1922:172632#428346840))
- [ ]  Update icon "Min 10 chars" (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1922:172632#428343023))
- [ ] Update background (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1922:172632#429038637))

### Security tips
- [ ]  Fix keyboard overlapping with "Confirm password"(full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1922:172632#428356533))
- [ ]  "I understand my password can't be recovered" should appear only when passwords match (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1922:172632#428356770))

### Errors
- [ ]  Update icon (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1922:172632#428370344))

### Disclaimer
- [ ]  Checkbox white/black (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1922:172632#428375016))

### PR DESCRIPTION
**Pull request by smohamedjavid**
fixes #15783

### Summary

This PR addresses the design feedback received on the Onboarding `Create profile password` screen.

#### Platforms

- Android
- iOS

### Steps to test

- Open Status
- Tap on `I'm new to status`
- Complete the profile name step
- Navigate to the `Create profile password` screen

status: ready

### CODE REVIEW

**Review by J-Son89 — APPROVED** [review]
nice, @churik these icon adjustments will affect across some of the other stories you created

**Review by briansztamfater — APPROVED** [review]

**Comment by pavloburykh** [comment]
@smohamedjavid thanx for the PR! Please, take a look at the following issues. 

### ISSUE 1 Disclaimer overlays password field/passwords match info message

**Screenshot from iPhone X:**

photo_2023-05-12 11 55 02

**Screenshot from iPhone SE:**

photo_2023-05-12 11 55 47

**Screenshot from Samsung Galaxy A52:** disclaimer is sticked to "Passwords match" info message

photo_2023-05-12 11 58 16

**Comment by pavloburykh** [comment]
### ISSUE 2 Cannot close keyboard by tapping on empty area

**Steps:** 

1. Proceed to Set password screen 
2. Open keyboard
3. Try to close keyboard by tapping on empty area
4. Observe the result

**Expected result:** should be able to close keyboard by tapping on empty area. 

https://github.com/status-im/status-mobile/assets/97245802/fc00fe4a-536d-4aa0-bba3-3548e1c7c648

**Actual result:** cannot close keyboard by tapping on empty area. Can close only by using return button (IOS) or system back button on Android.

**Comment by pavloburykh** [comment]
@smohamedjavid I have pushed [commit](https://github.com/status-im/status-mobile/pull/15863/commits/9a029d3d6e38844f1cf7b2808bbcb1efc0991036) with a small e2e fix. Please, include it during squashing and merging of this PR. Thank you.

**Comment by smohamedjavid** [comment]
@pavloburykh Thanks a lot for testing this PR.

> ISSUE 1 Disclaimer overlays password field/passwords match info message

Thanks for spotting this.

I checked the [Figma](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS/Feedback-for-Mobile?type=design&node-id=1922%3A172632&t=g4YFgtlihHGpBeRq-1), the disclaimer is displayed only when two passwords are matched, and the help box is removed from the UI. Maybe this is not reported in the design feedback. But, I updated the behaviour accordingly. so, there would be no overlap.

Password


> ISSUE 2 Cannot close keyboard by tapping on empty area

Fixed. Kindly retest.

**Comment by pavloburykh** [comment]
@smohamedjavid thanx! ISSUES 1 and 2 are fixed. Please, take a look at ISSUE 3

### ISSUE 3 Keyboard is not closed when info bottom sheet is opened

**Steps:**

1. Open set password screen
2. Keep keyboard opened
3. Tap on info button to ope info bottom sheet. 
4. See if keyboard is closed

**Expected result:** keyboard is closed and bottom sheet is opened instead of keyboard

**Actual result:** 

**Android:** keyboard is not closed, bottom sheet is opened above the keyboard

https://github.com/status-im/status-mobile/assets/97245802/d69d9637-9b49-42e3-afdc-1b8fc2f93b4b

**IOS:** keyboard is not closed. bottom sheet is opened behind the keyboard. 


https://github.com/status-im/status-mobile/assets/97245802/86eb7c18-a6e1-41e5-8531-9ab2e93772b0

**Comment by smohamedjavid** [comment]
> ISSUE 3 Keyboard is not closed when info bottom sheet is opened

@pavloburykh ISSUE 3 is fixed. Kindly retest.

**Comment by pavloburykh** [comment]
@smohamedjavid thanx for the fix. PR is ready to be merged.

**Pull request merged**
