### PR TITLE
 💩 [WIP] Add an unread messages indicator inside chats [#6375]  💩

### PR DESCRIPTION
**Pull request by flexsurfer**
[WIP] Add an unread messages indicator inside chats [#6375]

Implementation notes : https://notes.status.im/-iLVTV7ESK68JCFc0AzvmQ?both
Blockers: https://notes.status.im/-iLVTV7ESK68JCFc0AzvmQ?both#2-persists-scroll-position-between-chats
Miro board: https://miro.com/app/board/o9J_kjoK_tI=/

### CODE REVIEW

**Comment by flexsurfer** [comment]
@churik @Serhy would be cool to try scroll persistence on ios and android, thanks

**Comment by Serhy** [comment]
@flexsurfer could you rebase develop please (so there is https://github.com/status-im/status-react/pull/11655/commits/eba6b6325807c32b0e69881e132549cd1654f068 included) because now app even on Android crashing too often when user receives messages while I scrolling chat (especially reproducible when opening Status from background. 
With crashlog snippet:
```
--------- beginning of crash
01-27 15:45:52.935 27911 28000 F libc    : Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 28000 (Thread-11), pid 27911 (tus.ethereum.pr)
01-27 15:45:53.193 28327 28327 I crash_dump64: obtaining output fd from tombstoned, type: kDebuggerdTombstone
01-27 15:45:53.195  3481  3481 I /system/bin/tombstoned: received crash request for pid 28000
01-27 15:45:53.196 28327 28327 I crash_dump64: performing dump of process 27911 (target tid = 28000)
01-27 15:45:53.224 28327 28327 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
01-27 15:45:53.224 28327 28327 F DEBUG   : Build fingerprint: 'samsung/dreamltexx/dreamlte:9/PPR1.180610.011/G950FXXSBDTJ1:user/release-keys'
01-27 15:45:53.224 28327 28327 F DEBUG   : Revision: '10'
01-27 15:45:53.224 28327 28327 F DEBUG   : ABI: 'arm64'
01-27 15:45:53.224 28327 28327 F DEBUG   : pid: 27911, tid: 28000, name: Thread-11  >>> im.status.ethereum.pr <<<
01-27 15:45:53.224 28327 28327 F DEBUG   : signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
01-27 15:45:53.224 28327 28327 F DEBUG   : Abort message: 'Unknown reference: 42'
01-27 15:45:53.225 28327 28327 F DEBUG   :     x0  0000000000000000  x1  0000000000006d60  x2  0000000000000006  x3  0000000000000008
01-27 15:45:53.225 28327 28327 F DEBUG   :     x4  fefeff70ca07423f  x5  fefeff70ca07423f  x6  fefeff70ca07423f  x7  7f7f7f7fff7f7f7f
01-27 15:45:53.225 28327 28327 F DEBUG   :     x8  0000000000000083  x9  00000071cb0bc878  x10 fffffff87ffffbdf  x11 0000000000000001
01-27 15:45:53.225 28327 28327 F DEBUG   :     x12 0000007119eeff08  x13 ffffffffffffffff  x14 ffffffffff000000  x15 ffffffffffffffff
01-27 15:45:53.225 28327 28327 F DEBUG   :     x16 00000071cb0f32a0  x17 00000071cb032920  x18 0000007119eef6ca  x19 0000000000006d07
01-27 15:45:53.225 28327 28327 F DEBUG   :     x20 0000000000006d60  x21 0000000000000083  x22 0000007118fdf000  x23 0000000000000040
01-27 15:45:53.225 28327 28327 F DEBUG   :     x24 92c2ace3c9756a38  x25 043af3c59f709602  x26 0000007118347648  x27 0000000000000180
01-27 15:45:53.225 28327 28327 F DEBUG   :     x28 0000004000000d80  x29 0000007119ef0330
01-27 15:45:53.225 28327 28327 F DEBUG   :     sp  0000007119ef02f0  lr  00000071cb025d68  pc  00000071cb025d94
01-27 15:45:53.229 28327 28327 F DEBUG   : 
01-27 15:45:53.229 28327 28327 F DEBUG   : backtrace:
01-27 15:45:53.229 28327 28327 F DEBUG   :     #00 pc 0000000000021d94  /system/lib64/libc.so (abort+124)
01-27 15:45:53.229 28327 28327 F DEBUG   :     #01 pc 00000000014784f4  /data/app/im.status.ethereum.pr-7vQT1zVqLq2u3Ax2N_TeLQ==/lib/arm64/libgojni.so (go_seq_from_refnum+236)
```

**Comment by Serhy** [comment]
@flexsurfer that looks good to me on Android 9, 10 and iOS 14!
When user in the middle of chat messages view, - in 1-1, Group and public chats, - and sends a message or receives message (doesn't matter whether it's text 1line message or big text message, image or audio or command message), - chat view doesn't have this blinking effect. When resuming app from background and it was in the middle of chat then again, - receiving messages looks good to me on chat view.

**Comment by flexsurfer** [comment]
[Spike] Investigate using a replacement for RN FlatList #11724

**Pull request closed without merging**
