### PR TITLE
Pass topics when querying the mailserver

### PR DESCRIPTION
**Pull request by cammellos**
Currently we are still using a bloom filter when querying mailserver.
This commit changes the behavior so that topics are used instead.

### Testing

Fetching messages from mailservers

status: ready

### CODE REVIEW

**Review by flexsurfer — APPROVED** [review]

**Comment by churik** [comment]
@cammellos please ping me when conflicts are resolved.
Any testing notes are highly appreciated.

**Comment by cammellos** [comment]
@churik rebased, added areas to test, basically just smoke tests on mailserver usage

**Comment by churik** [comment]
e2e failures are not related to PR.
Tested:
- automatic node selection
- switched to all history nodes one-by-one and sending messages to chat
Got "Can't connect to history code" only for `mail-01-gc-us`. Is it worth to investigate @cammellos or not related to this PR?
For other history nodes everything was fine.
- reconnecting after offline state, backgrounding app
- push notifications
- "Use history nodes" is off

Please tell me if smth more should be tested, otherwise looks good to me.

**Devices:**
- IPhone 12 Mini (IOS 14)
- IPhone 7 (IOS 13)
- Xiaomi Mi Note 9 Pro (Android 10)

**Comment by churik** [comment]
сс @cammellos

**Comment by cammellos** [comment]
@churik that's enough, perfect, thanks!

**Pull request merged**
