### PR TITLE
[15550] Allow unpinning of deleted-for-me messages

### LINKED ISSUE #15550: The deleted pinned message can't be unpinned in 1-1 chat
### Problem:
1-1 chat does not have restrictions to pin/unpin messages for both users. But the message is not able to be unpinned when a current message is shown as deleted

#### Steps to reproduce:
1. USER_A: Send the message
2. USER_A: Delete the message by the 'delete for me' option
3. USER_B: Pin the message
4. USER_A: Go to the pinned list and try to unpin deleted message

#### Actual result:
USER_A can't unpin deleted message

https://user-images.githubusercontent.com/52490791/229103487-8214ba0f-b749-42ef-ba05-d04a808d25cf.mp4

#### Expected result:
USER_A can unpin deleted message

#### ENV:
Nightly [31 Mar 2023]

### PR DESCRIPTION
**Pull request by ibrkhalil**
fixes #15550 

### Summary

This PR just adds a filter on deleted-for-me pinned messages and doesn't add them to the list of pinned messages

status: ready

### CODE REVIEW

**Comment by yqrashawn** [comment]
This may cause user not be able to pin more messages if there are 3 pinned and deleted-for-me messages, and we hide them in the pinned message list.
I think we need a better solution. Maybe show them in pinned message list and allow user to unpin them

**Comment by ibrkhalil** [comment]
> This may cause user not be able to pin more messages if there are 3 pinned and deleted-for-me messages, and we hide them in the pinned message list. I think we need a better solution. Maybe show them in pinned message list and allow user to unpin them

Going to test if that case might happen and how to avoid it, Thanks Rashawn

**Comment by briansztamfater** [comment]
I think it shouldn't be filtered, just shown as "deleted for me" message.

**Comment by ilmotta** [comment]
In Telegram, if Alice deletes a pinned message only for her, then the pinned message also disappears, along with the actual message (for her only). I don't understand the point of displaying a *deleted pinned message* at the top and allowing Alice to *unpin a deleted message*. In essence, I much prefer Telegram's behavior here.

**Comment by ibrkhalil** [comment]
> In Telegram, if Alice deletes a pinned message only for her, then the pinned message also disappears, along with the actual message (for her only). I don't understand the point of displaying a _deleted pinned message_ at the top and allowing Alice to _unpin a deleted message_. In essence, I much prefer Telegram's behavior here.

Love the mock names
I agree
CC: @pedro-et

**Comment by VolodLytvynenko** [comment]
> In Telegram, if Alice deletes a pinned message only for her, then the pinned message also disappears, along with the actual message (for her only). I don't understand the point of displaying a _deleted pinned message_ at the top and allowing Alice to _unpin a deleted message_. In essence, I much prefer Telegram's behavior here.

hi @ilmotta . agree with you about convenience. The "deleted message" showing in the pinned bar was implemented in https://github.com/status-im/status-mobile/issues/14488#issue-1475919856 

But, I think one of the reasons to avoid more than 3 pinned messages (we have limits of no more than 3 pinned messages. Telegram does not have the pinning messages limits) CC: @yqrashawn correct me if I am wrong about the purpose of this functionality which is done in https://github.com/status-im/status-mobile/issues/14488#issue-1475919856 

#### Example: 
1. User_A and User_B have 3 pinned messages. 
2. User_A removes one message by 'delete for me' (now User_A has 2 pinned messages, User_B has 3 pinned messages)
3. User_A sends the 4-th message and pins it (now User_A has 3 pinned messages)

#### Expected result:
How many pinned messages the User_B should have after step 3?

####  Potential solution:
- User_B has 4 pinned messages despite limits of 3 pinned and maybe we should consider rejecting the functionality of message pinning limiting 
- User_B has 3 pinned messages (the first pinned is removed)

CC: @pedro-et need your help here

**Comment by yqrashawn** [comment]
@VladimrLitvinenko That's correct. #14488 allows user to unpin deleted messages (show both deleted/deleted for me messages in pinned message list), and it introduced another edge case, which is what to do with pinned deleted for me messages. 

Users don't care about deleted-for-me messages, definitely, but I think users do care about if they can pin more messages.

**Comment by VolodLytvynenko** [comment]
Hi  @ibrkhalil, thank you for your work. No issues from my side. PR is tested and ready to be merged

**Review by Parveshdhull — APPROVED** [review]

**Pull request merged**
