### PR TITLE
Fix for empty display-name

### LINKED ISSUE #15120: 3 random name is lost after relogin (release blocker)
Probably related to https://github.com/status-im/status-mobile/pull/15083 cc @siphiuel @cammellos 

**Steps:**

1. Create/restore multiaccount
2. Open Profile tab, make sure that user's 3 random name is shown
3. Perform relogin (manually tap Sign out and then login again)
6. See if 3 random name is still displayed on profile screen 

**Expected result:** 3 random name is not lost. It is possible to mention user by 3 random name both from mobile and desktop.

**Actual result:** 3 random name is lost. After that it is impossible to mention such user from desktop.

https://user-images.githubusercontent.com/97245802/219677446-6a7d3797-ca40-4b05-9a98-12afb9f72707.mp4

 
[Status-debug-logs (2).zip](https://github.com/status-im/status-mobile/files/10767601/Status-debug-logs.2.zip)

### Additional Information

- Status version: release 1. 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by vitvly**
Fixes #15120

### CODE REVIEW

**Review by cammellos — APPROVED** [review]
We probably want to have a deeper look at this issue post rc, would you mind opening an issue so we don't forget?
Also linting :)

**Comment by vitvly** [comment]
Left a status-go issue https://github.com/status-im/status-go/issues/3205, did `make lint-fix`.

**Comment by cammellos** [comment]
@siphiuel @pavloburykh  if we are happy, we can merge & cherry pick

**Comment by pavloburykh** [comment]
@siphiuel thanx for the fix! 

Please, take a look at the following issues

### ISSUE 1 Displayed names are not resolved in mentions list for mobile users

**Preconditions:** User A - mobile. User B - user who has set displayed name

**Steps:**

1. Join any chat by User A with User B (1-1, group, community channel)
2. By User A start typing @ to open mentions list
3. See if User's B displayed name is resolved within the mentions list

**Expected result:** Displayed name is resolved in mentions list. 

**Actual result:** Displayed name is not resolved. 3 random name is displayed. After sending mention displayed name is resolved within message history. 


https://user-images.githubusercontent.com/97245802/219737641-3ea2c9a8-0c33-4133-bfc8-d5e170374b31.mp4

[logs.zip](https://github.com/status-im/status-mobile/files/10769533/logs.zip)

**Comment by pavloburykh** [comment]
### ISSUE 2 Displayed name is not resolved in AC on mobile

**Preconditions:** User A - mobile. User B - user who has set displayed name

**Steps:** 

1. Generate any AC notification by User B (displayed name owner) to User A (mobile), e.g. Contact request, mention/reply in community channel etc. 
2. Open AC by User A
3. See if User's B name is resolved in generated notificartion

**Expected result:** Displayed name is resolved within AC notifs on mobile

**Actual result:** 3 random name instead of displayed name is shown within AC notification

photo_2023-02-17 20 19 42


https://user-images.githubusercontent.com/97245802/219748269-474b9ff2-3917-419c-82d8-b3236f881c06.mp4

**Comment by cammellos** [comment]
@pavloburykh are you sure this are only in this PR? ISSUE 2 I noticed on previous RC's as well, and just by looking at the code, issue 1 might also be already present (though I could be wrong)

**Comment by pavloburykh** [comment]
> @pavloburykh are you sure this are only in this PR? ISSUE 2 I noticed on previous RC's as well, and just by looking at the code, issue 1 might also be already present (though I could be wrong)

@cammellos you are right about ISSUE 2. We can address it separately. Not sure if it is a release blocker. 

Regarding ISSUE 1: it has been previously fixed by @flexsurfer here https://github.com/status-im/status-mobile/pull/15086 and I am not reproducing it in latest manual release [build](https://ci.status.im/job/status-mobile/job/manual/306/). But reproducing in this PR. 

**Screenshot form latest release build** 
photo_2023-02-17 20 32 32

**Comment by cammellos** [comment]
@pavloburykh thanks, odd about issue 1, but worth investigating

Fix for issue 2 is here https://github.com/status-im/status-mobile/pull/15126 we could include it in RC since it's a small change

**Comment by vitvly** [comment]
Also looking into issue 1, strange indeed.

**Comment by pavloburykh** [comment]
> Also looking into issue 1, strange indeed.

@siphiuel let me know please if you will be unable reproduce it. I will try to help or perform deeper investigation.

**Comment by vitvly** [comment]
@pavloburykh sorry, i think i've messed up the branch - it's based not on release branch, but on develop. Hence https://github.com/status-im/status-mobile/pull/15086 is not included here. So that's why issue 1 is reproducible here.

I wasn't sure if the PR should be based against develop or release, sorry for that.

**Comment by vitvly** [comment]
Ok, what i'm even talking about, the commit should be in develop, therefore in `fix/display-name-empty` branch, but it isn't! One sec.

**Comment by vitvly** [comment]
Ah, ok, so issue 1 was cherry-picked to release branch, but the pr was not merged to develop.

**Comment by pavloburykh** [comment]
> Ah, ok, so issue 1 was cherry-picked to release branch, but the pr was not merged to develop.

Thanx for clearing out @siphiuel! The initial issue has been fixed so let's go ahead and cherry-pick the fix into release branch.

**Pull request merged**
