### PR TITLE
move legacy subs step 1

### PR DESCRIPTION
**Pull request by flexsurfer**
when status-im2 was starting, i moved all subs into new namespace, but it seems like its better to move gradually, so i keep only subs for functionality which have been moved already, and move "old" subscriptions back to status-im namespace

for example we're developing wallet from scratch, so no need to move any wallet parts to status-im2, so better to keep it in old status-im namespace, so less confusion, and easy to remove later

### CODE REVIEW

**Comment by J-Son89** [comment]
can you describe a bit clearer what is happening in this pr 🙏

**Comment by flexsurfer** [comment]
sure @J-Son89 updated the description

**Comment by J-Son89** [comment]
Thanks!

**Review by J-Son89 — APPROVED** [review]

**Review by siddarthkay — APPROVED** [review]

**Review by Parveshdhull — APPROVED** [review]

**Review by ilmotta — APPROVED** [review]

**Comment by flexsurfer** [comment]
@status-im/mobile-qa could someone please confirm e2e not related to this PR

**Comment by qoqobolo** [comment]
@flexsurfer confirming that the failures are not related to this PR

**Pull request merged**
