### PR TITLE
ci: use arm64 macos hosts for iOS builds

### PR DESCRIPTION
**Pull request by jakubgs**
Lets see what happens...

### CODE REVIEW

**Comment by jakubgs** [comment]
Of course:
```
[2021-11-25T14:35:28.383Z] No Android SDK tarballs are available for system architecture: aarch64-darwin
```
I need to merge https://github.com/status-im/status-react/pull/12797 first.

**Comment by jakubgs** [comment]
Looks like `status-go` build fails:
```
[2021-11-25T14:49:35.017Z] cgo: exec objc[61089]:: exec: "objc[61089]:": executable file not found in $PATH
```

**Comment by jakubgs** [comment]
If I build locally it works:
```
jenkins@macm1-01.ms-eu-dublin.slave.ci:~/workspace/status-react_prs_ios_PR-12849 % nix-build --no-out-link -A targets.status-go.mobile.ios default.nix
/nix/store/2paw9qzipvpxlc2ijlaiq3gi2g3c6g8z-status-go-0.91.5-1d752c0-ios
```

**Comment by jakubgs** [comment]
Looks like the issue is indeed building of `SQLCipher`: https://github.com/status-im/status-react/issues/12799
```
16:39:00  Installing SQLCipher (3.4.2)
16:39:04  [!] /nix/store/gpf2hyxynkkijvqk2ijlw25jnb8q8fk4-bash-interactive-5.1-p8/bin/bash -c 
16:39:04  set -e
16:39:04  ./configure --enable-tempstore=yes --with-crypto-lib=commoncrypto CFLAGS="-DSQLITE_HAS_CODEC -DSQLITE_TEMP_STORE=2 -DSQLITE_SOUNDEX -DSQLITE_THREADSAFE -DSQLITE_ENABLE_RTREE -DSQLITE_ENABLE_STAT3 -DSQLITE_ENABLE_STAT4 -DSQLITE_ENABLE_COLUMN_METADATA -DSQLITE_ENABLE_MEMORY_MANAGEMENT -DSQLITE_ENABLE_LOAD_EXTENSION -DSQLITE_ENABLE_UNLOCK_NOTIFY -DSQLITE_ENABLE_FTS3_PARENTHESIS -DSQLITE_ENABLE_FTS4 -DSQLITE_ENABLE_FTS4_UNICODE61 -DSQLITE_ENABLE_JSON1 -DSQLITE_ENABLE_FTS5 -DHAVE_USLEEP=1 -DSQLITE_MAX_VARIABLE_NUMBER=99999"; make sqlite3.c
16:39:04  
16:39:04  checking build system type... 
16:39:04  Invalid configuration `arm64-apple-darwin20.6.0': machine `arm64-apple' not recognized
16:39:04  configure: error: /nix/store/ppzr8yab3s3883skd0da5i4ylzpksk9l-bash-5.1-p8/bin/bash ./config.sub arm64-apple-darwin20.6.0 failed
```

**Comment by flexsurfer** [comment]
@jakubgs still relevant ?

**Comment by jakubgs** [comment]
Sure is, see https://github.com/status-im/status-react/issues/12799#issuecomment-988340136. Either we have to wait for Coreutils release with the fix, or we have to patch our own coreutils in `nixpkgs`. Or we have to get SQLite and then SQLCipher to update their `config.sub` and `config.guess` scripts. Another option is running everything via Rosetta binary translation in an `x86_64` shell, but that kinda defeats the purpose of using an M1 machine in the first place...

**Comment by jakubgs** [comment]
I tried applying just [the patch](https://git.savannah.gnu.org/cgit/coreutils.git/patch/?id=e3d1ff04370b3e090e4cfeb8f6cc4a63590a516f) to Coreutils version `9.0` but that fails, so it needs other changes:
```
src/uname.c:170:41: error: unknown type name 'MAYBE_UNUSED'
  170 | print_element_env (char const *element, MAYBE_UNUSED char const *envvar)
      |                                         ^~~~~~~~~~~~
```
So it cannot be easily patched.

**Comment by jakubgs** [comment]
It appears iOS builds on M1 are failing with:
```
[2022-06-03T11:03:21.245Z] ❌  error: failed to read asset tags:
    The command `(
        cd /Users/jenkins/workspace/status-react_prs_ios_PR-12849/ios &&
            /Applications/Xcode.app/Contents/Developer/usr/bin/actool \
                --print-asset-tag-combinations \
                --output-format xml1 \
                /Users/jenkins/workspace/status-react_prs_ios_PR-12849/ios/StatusIm/Images.xcassets
    )`
exited with status 255. The command's standard error was:
[2022-06-03T11:03:21.245Z] 
[2022-06-03T11:03:21.245Z] 
[2022-06-03T11:03:21.245Z] ** ARCHIVE FAILED **
[2022-06-03T11:03:21.245Z] [12:03:20]: Exit status: 65
```

**Comment by jakubgs** [comment]
Inside of `/Users/jenkins/Library/Logs/gym/Status PR-StatusImPR.log` there's this:
```
Backtrace:
  0   __exceptionPreprocess (in CoreFoundation)
  1   objc_exception_throw (in libobjc.A.dylib)
  2   -[DVTExtension valueForKey:error:] (in DVTFoundation)
  3   _IDEInitializeOnePlugInAndPrerequisites (in IDEFoundation)
  4   _IDEInitializePlugIns (in IDEFoundation)
  5   IDEInitialize (in IDEFoundation)
  6   IBIDEInitialize (in ibtoold)
  7   main (in ibtoold)
  8   start (in dyld)
```
Which is worrying.

**Comment by jakubgs** [comment]
Some threads online suggest it's a bug in Xcode:
https://stackoverflow.com/questions/50331031/xcode-archive-error-command-actool-failed-with-exit-code-255

While others say it's because of attribute slicing in Asset Catalog:
https://developer.apple.com/forums/thread/13522

**Comment by jakubgs** [comment]
This build on i7 Mac worked just fine:

* https://ci.status.im/job/status-react/job/prs/job/ios/job/PR-12849/13/

But these failed:

* Because of `actool` crashing without clear error
    - https://ci.status.im/job/status-react/job/prs/job/ios/job/PR-12849/12/
    - https://ci.status.im/job/status-react/job/prs/job/ios/job/PR-12849/17/
* Because of `status-go` build error [#13346](https://github.com/status-im/status-react/issues/13346)
    - https://ci.status.im/job/status-react/job/prs/job/ios/job/PR-12849/14/
    - https://ci.status.im/job/status-react/job/prs/job/ios/job/PR-12849/15/
    - https://ci.status.im/job/status-react/job/prs/job/ios/job/PR-12849/16/

Seems unstable.

**Comment by jakubgs** [comment]
Now we're seeing something new:
```
Building status-go for: ios,iossimulator
/nix/store/wqldq7k6f0am19x3qs7nar8w6gix3sq0-gomobile-unstable-2022-05-18/bin/gomobile: iossimulator/arm64: go build -ldflags -X github.com/status-im/status-go/params.GitCommit=22669d0423bc792e650150b01568870699ff1d25 -X github.com/status-im/status-go/params.Version=0.102.2 -s -w -buildmode=c-archive -o /private/tmp/nix-build-status-go-0.102.2-22669d0-ios.drv-0/gomobile-work/Statusgo-iossimulator-arm64.a ./gobind failed: exit status 2
# runtime/cgo
cgo: C compiler "objc[57723]:" not found: exec: "objc[57723]:": executable file not found in $PATH
```
__EDIT__: This is a known issue caused by `xcrun` warnings: https://github.com/status-im/status-mobile/issues/13949

**Comment by jakubgs** [comment]
Currently the error appears to be:
```
Provisioning profile '94a83f39-326a-458c-b338-3a25675e8e5a' is not available on the Developer Portal for the user ****, fixing this now for you 🔨
...
[11:51:29]: $ xcodebuild -showBuildSettings -workspace ios/StatusIm.xcworkspace -scheme StatusImPR -configuration Release
[11:51:32]: Command timed out after 3 seconds on try 1 of 4, trying again with a 6 second timeout...
...
[!] xcodebuild -showBuildSettings timed out after 4 retries with a base timeout of 3. You can override the base timeout value with the environment variable FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT, and the number of retries with the environment variable FASTLANE_XCODEBUILD_SETTINGS_RETRIES 
```
Some links that might be relevant:

* https://github.com/fastlane/fastlane/issues/4621
* https://developer.apple.com/forums/thread/95354
* https://developer.apple.com/forums/thread/673778
* https://stackoverflow.com/questions/55122513/

**Comment by jakubgs** [comment]
Looks like the upgrade to Xcode in https://github.com/status-im/status-mobile/pull/14759 has fixed the issues. And the build takes only 8 minutes!

**Review by flexsurfer — APPROVED** [review]

**Review by briansztamfater — APPROVED** [review]

**Pull request merged**
