### PR TITLE
add remote notifications preferences

### LINKED ISSUE #13127: Push notifications are received for 1-1 messages in Activity center with remote PNs enabled (Android)
# Bug Report

## Problem 
If a user enables _remote push notifications_, sends the app to the background, and receives a new message from a non-contact user in the Activity center, a push notification will also be received for that message.
The issue is more relevant for Android since there is an option to disable PNs from non-contacts on iOS.

#### Expected behaviour
No push notification

#### Actual behaviour

https://user-images.githubusercontent.com/67952253/155172845-b2481f53-b605-4ba2-a0ef-0df9d1e6d6cd.mp4

### Reproduction

1. Create UserA and UserB
2. UserA: enable _remote_ PNs in settings, send the app to the background
3. UserB: start 1-1 chat with UserA, send a message
4. UserA: check PNs

### Additional Information

- Status version: nightly 23/02
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by Parveshdhull**
fixes https://github.com/status-im/status-react/issues/13127

### CODE REVIEW

**Review by flexsurfer — APPROVED** [review]

**Comment by qoqobolo** [comment]
@Parveshdhull thank you for this quick fix!
No issues found so far, but I have 2 questions

**1. Can we have all options in the `Notifications preferences` inactive (greyed out) until local or remote notifications are enabled?**
I mean to me as a user, it really doesn't seem very intuitive why I can't enable toggles `Notifications from non-contacts` and `Show @ mentions` even though they look the same as toggles `Local notifications` and `Remote notifications`.


https://user-images.githubusercontent.com/67952253/155757028-f2a73c9b-d364-4b68-af29-dd358e906f67.mp4



So probably it would be expected if we had _inactive_:
- `Notifications from non-contacts`, `Show @ mentions` and `Wallet transactions` - by default (both PN types are disabled)
- `Notifications from non-contacts` and `Show @ mentions` - with `Local notifications` enabled (since they only work with `Remote notifications`)


**2. Is this expected that I cannot enable `Wallet transactions` with `Remote notifications` enabled on Android?** 
On iOS it's possible to enable `Wallet transactions` PNs.

https://user-images.githubusercontent.com/67952253/155757242-63767e37-1eb0-48fc-b6c2-6ef7ebf270fd.mp4

**Comment by Parveshdhull** [comment]
@qoqobolo, Thanks for testing the PR.
1. Yes, that's great idea, we should disable those options. let me change this 👍
2. Yes, this is not supported yet, checkout this  [issue](https://github.com/status-im/status-react/issues/13122)

**Comment by Parveshdhull** [comment]
Please let me know if this looks ok? (also for ios)

**Comment by qoqobolo** [comment]
@Parveshdhull thank you! Looks and works great.
E2e failures are not PR-related. PR can be merged.

**Pull request merged**
