### PR TITLE
[#4300] Updated DApps icons

### LINKED ISSUE #4300: Update icons for featured DApps
### User Story

As a user, I want DApp icons to be clearly visible. 

### Description

*Type*: Feature

*Summary*: 
Update the list of DApp icons: 

- Each must be visible against a white background. 

- Remove the double dot icon from the corner of each.

#### Expected behavior
All featured DApp list icons contrast with the Home screen and have Status ".." element removed.

#### Actual behavior
Certain DApp icons have white backgrounds and the visual effect is poor.
".." badge on every icon.

### PR DESCRIPTION
**Pull request by jeluard**
fixes #4300

### Summary:

Updated DApps icons

status: ready

### CODE REVIEW

**Review by goranjovic — APPROVED** [review]

**Review by flexsurfer — APPROVED** [review]

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/GY9ydS for branch PR-4385

<blockquote><div><strong><a href="https://i.diawi.com/GY9ydS">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/FSTeV9 for branch PR-4385

<blockquote><div><strong><a href="https://i.diawi.com/FSTeV9">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/F8kjGq for branch PR-4385

<blockquote><div><strong><a href="https://i.diawi.com/F8kjGq">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/BpJTJS for branch PR-4385

<blockquote><div><strong><a href="https://i.diawi.com/BpJTJS">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/ZVBm53 for branch PR-4385

<blockquote><div><strong><a href="https://i.diawi.com/ZVBm53">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/dnCgwN for branch PR-4385

<blockquote><div><strong><a href="https://i.diawi.com/dnCgwN">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/GkZBDf for branch PR-4385

<blockquote><div><strong><a href="https://i.diawi.com/GkZBDf">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/kyzhDC for branch PR-4385

<blockquote><div><strong><a href="https://i.diawi.com/kyzhDC">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by asemiankevich** [comment]
image
according to ticket blue dots for dapp icon should be removed as well. @rachelhamlin is it still in scope ?

this is current PR implementation
image

i  see new pics are picked up but blue dots are in place still

**Comment by rachelhamlin** [comment]
@asemiankevich I'll create a separate issue for the dots, it's okay for now because requires one other small update.

**Comment by asemiankevich** [comment]
okay thanks!

**Pull request merged**
