### PR TITLE
upgrade rn-camera (attempt to fix #3289)

### LINKED ISSUE #3289: Error Attempt to invoke virtual method when capturing a photo
### Description

*Type*: Bug

*Summary*: App crashes with `java.lang.NullPointerException: Attempt to invoke virtual method 'android.hardware.Camera$Parameters android.hardware.Camera.getParameters()' on a null object reference` on Android when multitapping when capturing user picture

#### Expected behavior
no crash

#### Actual behavior
image
 as well as

`java.lang.RuntimeException: Camera is being used after Camera.release() was called`

### Reproduction
- Open Profile
- Tap edit - capture
- Tap the screen several times in fast manner

### Additional Information

* Status version: 0.9.10-663-gd0dff14e+ (2220) develop
* Operating System: Android

#### Logs
https://app.testfairy.com/projects/4803622-status/builds/7671704/sessions/2/?accessToken=EzO1CCG3FCs91s5XA/0RimxKjMA

### PR DESCRIPTION
**Pull request by rasom**
fix #3289 

status: ready

### CODE REVIEW

**Review by flexsurfer — APPROVED** [review]

**Review by janherich — APPROVED** [review]

**Comment by rasom** [comment]
Branch: PR-3297
Android: https://i.diawi.com/GdjXrF
iOS: https://i.diawi.com/iuf5Wi

**Comment by asemiankevich** [comment]
1. Access to camera pop up shown when open user profile right after the app is installed and launched
2. Black screen shown when trying to capture a user avatar. Unable to capture a photo
3. No errors shown when tapping inside the camera area or camera button

**Comment by rasom** [comment]
@asemiankevich which OS? Both?

**Comment by asemiankevich** [comment]
@rasom Android only. iOS is just fine

**Comment by rasom** [comment]
https://github.com/react-native-community/react-native-camera/issues/1234

**Comment by asemiankevich** [comment]
Branch: PR-3297
Android: https://i.diawi.com/mMw86C
iOS: https://i.diawi.com/ThunxQ

**Comment by asemiankevich** [comment]
I would merge it as original issue ( errors when tapping multiple times at camera area and camera buttoN) are gone. No camera access message is shown when open user profile. The issue with black screen when capturing photo on Android is described https://github.com/react-native-community/react-native-camera/issues/1234 and will be handled separately

**Comment by asemiankevich** [comment]
please roll this commit back from develop branch, we have to wait for fix https://github.com/react-native-community/react-native-camera/issues/1234 @yenda

**Pull request merged**
