### PR TITLE
chore: bump status-go for community join response use mvds

### PR DESCRIPTION
**Pull request by kaichaosun**
### Summary

Make `ApplicationMetadataMessage_COMMUNITY_REQUEST_TO_JOIN_RESPONSE` message to use MVDS.

Status-go: https://github.com/status-im/status-go/pull/5787

### Testing notes

The change should increase the stability of join community process.

- Create a community, test join community process without any error, with or without auto accept.
- Create Owner Token for the community, test join community process without any error, with or without auto accept.
- The change should be compatible with master

#### Platforms

- Android
- iOS
- macOS
- Linux
- Windows

##### Functional

- 1-1 chats
- public chats
- group chats
- wallet / transactions
- dapps / app browsing
- account recovery
- new account
- user profile updates
- networks
- mailservers
- fleet
- bootnodes

##### Non-functional

- battery performance
- CPU performance / speed of the app
- network consumption

### Steps to test

- Open Status
- ...
- Step 3, etc.

### Before and after screenshots comparison

| Figma (if available) | iOS (if available)    | Android (if available)
| --- | --- | --- |
| Please embed Image/Video here of the before and after.  | Please embed Image/Video here of the before and after.  | Please embed Image/Video here of the before and after. |

status: ready 

### Risk

Described potential risks and worst case scenarios.

Tick **one**:
- [ ] Low risk: 2 devs MUST perform testing as specified above and attach their results as comments to this PR **before** merging.
- [x] High risk: QA team MUST perform additional testing in the specified affected areas **before** merging.

### CODE REVIEW

**Comment by pavloburykh** [comment]
@kaichaosun thanks for the PR. Please take a look at the issue

### ISSUE 1 Community request stucks in Pending for more than 1 minute (auto approval community)

**Steps:** 

1. Create a community with requests autoapproval
2. Send community request from mobile (keep the control node online)
3. See how much time does it take until Pending request is changed to Joined for mobile sender

**Actual result:** sometimes it takes more than a minute. 

[community_request_sender.zip](https://github.com/user-attachments/files/16850729/community_request_sender.zip)
[control_node.zip](https://github.com/user-attachments/files/16850730/control_node.zip)

On the video pay attention at request status at the top right corner. It remains Pending for more than a minute. 

https://github.com/user-attachments/assets/f1a408b2-5d8d-4289-ae54-59434f74a287

**Comment by kaichaosun** [comment]
@pavloburykh  This may relates to the validation logic, https://github.com/status-im/status-go/blob/develop/protocol/communities/manager.go#L3521. MVDS use the sender key (creator key of community) to sign the message.
Will see how to fix it.

**Comment by pavloburykh** [comment]
@kaichaosun thank you for the fixes. ISSUE 1 seems to be fixed.

At the same time, while testing current PR I have faced a critical issue which resulted in braking my account on Android (it crashed couple of times and after that I was not able to login). I do not know if this issue is PR related or not, as there are no steps for reproduction. Would be great if you can check the logs and description below and try to identify what went wrong.

### ISSUE 2 At some point app has crashed and after that user is unable to login

Here are some steps which I performed by my user before the issue occured:

1. Created new mobile user using PR build
2. Joined different communities (tokenized (with minted Owner token) / non tokenized, with / without autoapproval. Note, that the control node of those communities was Desktop master (not [PR](https://github.com/status-im/status-desktop/pull/16243) build). 
3. At some point mobile app crashed. 
4. Then I was able to successfully login and noticed notifications center is empty (video attached), despite there were notifications about joining communities/kicking from communities. 
5. After some time app crashed once again
6. After the last crash I was not able to login this account anymore. Endless spinner on login (see video attached)

In the logs there is an error

```ERROR[09-04|10:50:31.079|github.com/status-im/status-go/mobile/status.go:367]                                                             loginAccount failed                      error="failed to select account: failed to apply migrations: failed to apply status-go/protocol migrations: failed to migrate: file does not exist"```

[mobile_user_geth_log.zip](https://github.com/user-attachments/files/16869468/mobile_user_geth_log.zip)
[geth_control_node_Desktop_master.log.zip](https://github.com/user-attachments/files/16869464/geth_control_node_Desktop_master.log.zip)
[mobile_user_android_logcat.zip](https://github.com/user-attachments/files/16869467/mobile_user_android_logcat.zip)


https://github.com/user-attachments/assets/c1c277ab-2b6e-492c-bd6d-9e1c09edc0a4


https://github.com/user-attachments/assets/a5bbf912-4152-466b-8729-1b7286d9d27e

**Comment by pavloburykh** [comment]
@kaichaosun besides [ISSUE 2](https://github.com/status-im/status-mobile/pull/21165#issuecomment-2328704129) I do not see any other issues. I faced couple of times community request stucking in Pending on mobile but it can be due to some network issues. In case you do not consider ISSUE 2 PR related you are good to merge.

**Comment by kaichaosun** [comment]
Thanks @pavloburykh 

>  error="failed to select account: failed to apply migrations: failed to apply status-go/protocol migrations: failed to migrate: file does not exist"

It seems related to https://github.com/golang-migrate/migrate/issues/79

For ISSUE 2, may caused by https://github.com/status-im/status-mobile/issues/21174, I will bump status go after the fix and let's see if it helps.

**Comment by pavloburykh** [comment]
> For ISSUE 2, may caused by #21174, I will bump status go after the fix and let's see if it helps.

Thank you @kaichaosun. Unfortunately we will not be able to verify if it is fixed or not because there no steps to reproduce, seems it is happening randomly. I was not able to reproduce the issue by another newly created user though I tried to follow the same flow as the user with failed migration.

**Pull request closed without merging**
