### PR TITLE
Pass `WhisperConfig.LightClient: true` in node config. Closes #3442

### LINKED ISSUE #3442: Enable WhisperConfig.LightClient in node config for Android and iOS
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a developer, I want to take advantage of optimizations in status-go/geth so that we consume less resources when running on resource-constrained devices.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*

For that to happen, we need to signal that to status-go by enabling `WhisperConfig.LightClient` when starting the node.

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
When a node is started on a mobile app, we pass the `WhisperConfig.LightClient` JSON flag set to true.

#### Actual behavior
[comment]: # (Describe what actually happened.)
Flag isn't currently being set, meaning that the bloom filter will be inactive and that all incoming messages will be processed, resulting in decreased efficiency.

### PR DESCRIPTION
**Pull request by pedropombeiro**
[comment]: # (Please replace ... with your information. Remove < and >)
[comment]: # (To auto-close issue on merge, please insert the related issue number after # i.e fixes #566)

This PR enables the new functionality in status-go `feature/whisperv6-#665` to use bloom filters to filter out unwanted topics on light nodes.

fixes #3442 

### Testing notes (optional):

I haven't been able to deploy to the phone for testing (looks like `develop` is not stable).

status: ready

### CODE REVIEW

**Review by janherich — APPROVED** [review]

**Review by mandrigin — APPROVED** [review]
LGTM

**Comment by asemiankevich** [comment]
I have checked basic messaging functionality - 1x1 , group and public chats in this PR currently and when upgrading release version to this PR. Messaging works the same way, I can send / receive messages. I don't see the WhisperConfig.LightClient JSON on android geth log but i assume it depends on log level. Traffic consumption will have an effect with Whisper v6, which we will have later.

**Comment by pedropombeiro** [comment]
I'm finally able again to deploy to my Android phone and was able to see that while `WhisperConfig.LightClient` is present, it is somehow set to `false`. Moving this back to `CONTRIBUTOR` while I check what is going on.

**Comment by pedropombeiro** [comment]
Fixed the issue. The log now shows:

```json
{
	"DevMode": true,
	"NetworkId": 3,
	"DataDir": "\/data\/user\/0\/im.status.ethereum\/ethereum\/testnet_rpc",
	"KeyStoreDir": "\/data\/user\/0\/im.status.ethereum\/keystore",
	"NodeKeyFile": "",
	"Discovery": false,
	"ListenAddr": ":0",
	"Name": "StatusIM",
	"Version": "0.9.9-unstable",
	"APIModules": "db,eth,net,web3,shh,personal,admin,debug",
	"HTTPHost": "localhost",
	"RPCEnabled": false,
	"HTTPPort": 8545,
	"WSHost": "localhost",
	"WSPort": 8546,
	"WSEnabled": false,
	"IPCFile": "geth.ipc",
	"IPCEnabled": false,
	"TLSEnabled": false,
	"MaxPeers": 25,
	"MaxPendingPeers": 0,
	"LogFile": "\/storage\/emulated\/0\/Download\/geth.log",
	"LogLevel": "INFO",
	"LogToStderr": true,
	"UpstreamConfig": {
		"Enabled": true,
		"URL": "https:\/\/ropsten.infura.io\/z6GCTmjdP3FETEJmMBI4"
	},
	"BootClusterConfig": {
		"Enabled": true,
		"BootNodes": ["enode:\/\/1b995ba494e880e9b55fa0c093eb94db2d9de65de473d0fbd173f1d5af86f1c99da57e68fb00e58303c2b7abbbcd59396c7293c6c865ead4e5334feab4397feb@163.172.168.202:30303", "enode:\/\/1b995ba494e880e9b55fa0c093eb94db2d9de65de473d0fbd173f1d5af86f1c99da57e68fb00e58303c2b7abbbcd59396c7293c6c865ead4e5334feab4397feb@51.15.194.39:30303"]
	},
	"LightEthConfig": {
		"Enabled": true,
		"Genesis": "...",
		"DatabaseCache": 16
	},
	"WhisperConfig": {
		"Enabled": true,
		"PasswordFile": "",
		"Password": "",
		"LightClient": true,
		"EnableMailServer": false,
		"DataDir": "\/data\/user\/0\/im.status.ethereum\/ethereum\/testnet\/wnode",
		"MinimumPoW": 0.001,
		"TTL": 120,
		"FirebaseConfig": {
			"AuthorizationKeyFile": "",
			"NotificationTriggerURL": "https:\/\/fcm.googleapis.com\/fcm\/send"
		}
	},
	"SwarmConfig": {
		"Enabled": false
	},
	"LogEnabled": true
}
```

**Comment by jeluard** [comment]
@PombeirP Shall we retest this PR?

**Comment by pedropombeiro** [comment]
@jeluard let me just push and I think we can merge directly.

**Comment by pedropombeiro** [comment]
Ready to be merged

**Pull request merged**
