### PR TITLE
chore: point to recovery account fix in status-go

### LINKED ISSUE #18092: App crashes after recover of any user
This bug is not in our develop yet. So it should be reproduced in the builds looking at current go develop. 

You can reproduce the bug in PR builds that include new go version, for example https://github.com/status-im/status-mobile/pull/17941 or https://github.com/status-im/status-mobile/pull/18069

**Steps:**

1. Recover any user
2. See if app is not crashing after recovery

**Actual result:** app crashes

[Status-debug-logs (88).zip](https://github.com/status-im/status-mobile/files/13583223/Status-debug-logs.88.zip)

https://github.com/status-im/status-mobile/assets/97245802/1b295bea-0ef4-4966-9745-d5f19f3aea1a

**Expected result:** app does not crash

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by siddarthkay**
@status-im/mobile-qa 

PR to test status-go fix.

fixes #18092 

status: ready

### CODE REVIEW

**Comment by pavloburykh** [comment]
@siddarthkay thank you for creating mobile PR! I am on it.

**Review by qfrank — APPROVED** [review]

**Comment by pavloburykh** [comment]
@IvanBelyakoff thank you for the fix. The issue is still reproducible for me in case of recovering user with tokens. 

### ISSUE 1 App crashes after recover of user with tokens

**Steps:** 

1. Recover user with tokens
2. Stay logged in the app and wait some time until it starts crashing
3. If app is not crashing right after recover try couple re-logins and stay logged in for some more time. 

**Actual result:** 

[raw_logcat.log.zip](https://github.com/status-im/status-mobile/files/13598097/raw_logcat.log.zip)
[Status-debug-logs (89).zip](https://github.com/status-im/status-mobile/files/13598098/Status-debug-logs.89.zip)

https://github.com/status-im/status-mobile/assets/97245802/ed967516-1f5d-45ac-b163-0d24e8163f40

**Comment by IvanBelyakoff** [comment]
> @IvanBelyakoff thank you for the fix. The issue is still reproducible for me in case of recovering user with tokens.
> 
> ### ISSUE 1 App crashes after recover of user with tokens
> **Steps:**
> 
> 1. Recover user with tokens
> 2. Stay logged in the app and wait some time until it starts crashing
> 3. If app is not crashing right after recover try couple re-logins and stay logged in for some more time.
> 
> **Actual result:**
> 
> [raw_logcat.log.zip](https://github.com/status-im/status-mobile/files/13598097/raw_logcat.log.zip) [Status-debug-logs (89).zip](https://github.com/status-im/status-mobile/files/13598098/Status-debug-logs.89.zip)
> 
>  telegram-cloud-document-2-5445149560659787548.mp4

Got it. Ok, i will have a look at it now one more time. I think I tested on an empty account. Will make a quick fix for you and then add a test for it

**Comment by IvanBelyakoff** [comment]
@pavloburykh So this is another crash from what I fixed. I am not sure why this crash appeared because as I see we never (or if it happened, then long ago) sent a block number with RecentHistoryReady event, but that case was not handled in local notification service. I don't think it makes sense to send any block number with this event.
I reproduced the crash from your log in a test and fixed it.
I updated the PR https://github.com/status-im/status-go/pull/4433
Please have a look

**Comment by pavloburykh** [comment]
@IvanBelyakoff thank you for the fix. Tested manually and no crash is detected. Failed e2e either known or related to global data delivery issues. Ready for merge.

**Comment by siddarthkay** [comment]
fixed in status-go and included in version `v0.171.30`

**Pull request closed without merging**
