### PR TITLE
Bottom tab animation on leaving/entering main tabs

### PR DESCRIPTION
**Pull request by rasom**
status: ready

### CODE REVIEW

**Comment by errorists** [comment]
thanks for working on it, just chiming in to make sure, the minimised state should be included in all subviews and not only chats. We show the full tab bar on each of the root views, Home, Wallet, Profile, but once you navigate inside any of their subviews we should minimise it. sorry if I didn't make it clear enough :)

**Comment by rasom** [comment]
@errorists thanks

yep it wasn't clear, though it probably makes it even a bit simpler :)

**Comment by errorists** [comment]
@rasom coool, so yes it's ok but I'd like us to improve if possible. How many callbacks do we get from the transition, because I have a feeling that the animation is too delayed, both on entry and especially exit. It should happen ms away from when we request the transition. 
The swipe gesture also has a tolerance, if you drag and let go the screen less than halfway, it doesn't fire the transition, so we don't animate the tab bar. But if you drag it to at least middle of screen, the back event is fired and then we could immediately start the tab bar animation? Is that out of reach?

**Review by flexsurfer — APPROVED** [review]

**Comment by errorists** [comment]
Also, correct me if I'm wrong but it looks like on exit transition we use different timings for the tab bar background and icons/labels, the tab background animates much faster than the icons. It should use the same value for both to look good. I couldn't find the easing value in code, could we try [circular](https://facebook.github.io/react-native/docs/easing#circle) function to make the tab bar motion more lifelike? 🙏

**Comment by rasom** [comment]
@errorists added one change, so that we react on starting transition. It's probably a bit faster than before, but I doubt it is really noticeable. I also doubt we can do it faster on gestures, we react on the same event but still animation happens with delay (when navigate from chat to chats using gesture). In this commit only chats->chat->chats (except input focusing, it is broken) will work properly, just to test if this way to initiate animation is better.

**Comment by rasom** [comment]
@errorists can you please take a look at iOS version https://i.diawi.com/RW2cLm ?

**Comment by errorists** [comment]
@rasom thanks, tried it and there is a difference actually quite a huge one 🚀 

In the previous build, this is where the animation starts on a video recording, you can see it's more than halfway during the transition
screenshot 2019-03-07 at 08 49 40
In the new one it starts exactly on the same frame as transition, samesies for exit transition
that's cool, awesome work you're doing here.

image

here's one bug I managed to find, on transitioning to a minimised tab state, it looks like we leave a blank area under where the tab bar was. I take it because it's where scroll view ends, if so it's ok to leave it like that, I don't want us animating the view height or stuff

two things I'd like us to improve further if possible:
swipe back gesture, is there anything we can do to trigger it when the navigate transition starts, it looks like we animate the tab bar only after the transition ends.
also it would be cool if we'd have a playground to test the different animation curves and timings - hello fiddle :) cc @flexsurfer - , I think there's still room for improvement there, I'd love to see a build with the mentioned circular easing as it should make it accelerate and decelerate faster, nicer.

**Comment by rasom** [comment]
@errorists  tha bug should be fixed https://i.diawi.com/SXKA38

**Comment by rasom** [comment]
> Also, correct me if I'm wrong but it looks like on exit transition we use different timings for the tab bar background and icons/labels, the tab background animates much faster than the icons.

@errorists I'm not sure that I understand what you mean here. In this PR the wall bar is animated, there is no separate animation for icons

**Comment by errorists** [comment]
> @errorists I'm not sure that I understand what you mean here. In this PR the wall bar is animated, there is no separate animation for icons

That's fixed in the current build and no longer an issue, what happened before was the tab bar container animated faster than its content 👍

**Comment by rasom** [comment]
@errorists a new build with circular easing https://i.diawi.com/voSq2s

**Comment by errorists** [comment]
@rasom thanks for giving it a shot, shame it's worse, too stiff, hard to prescribe the right one with only https://easings.net to help you ;) 
Please change it to Cubic and I'll shut up about easing 🙌  
If we can do something about the swipe back gesture, that would make it perfect, if not I'm giving it a green ✅ review, we can go to testing.

**Comment by rasom** [comment]
@errorists https://i.diawi.com/Y5pT44

**Comment by errorists** [comment]
@rasom Cubic is the winner. Thanks! How is it on Android, everything ok?

**Comment by rasom** [comment]
@errorists looks fine to me https://youtu.be/Zke5TgpmP_g

**Comment by rasom** [comment]
@flexsurfer @yenda, pr should be ready finally, please review

**Review by cammellos — APPROVED** [review]

**Review by flexsurfer — APPROVED** [review]

**Comment by asemiankevich** [comment]
@errorists could you please explain what exactly is expected here?  Thanks!

**Comment by errorists** [comment]
@asemiankevich Sure, the expected behaviour is as follows: whenever you transition from any of the root views so : Home, Wallet, Profile to any of their subviews (chats, send tx flow, settings etc.) the tab bar should shrink and remain this way until you transition back to the root view or change tabs to another root view. 
You may ask why bother? We do this do open up some extra space to show as much content as possible and reduce the visual noise of having too much navigation placed on the bottom, so the footprint of tab bar is much smaller when you're navigating deeper inside one of the key areas. We leave the labels when you're at ground level to better communicate what are the features of the app and where you can go to, I'm afraid leaving icons totally on their own would not be clear enough for some, at least not yet.

👉 What to test? I'd say if you can find a reproducible way for the tab bar to not animate when it's required to :) try navigating around the app, changing tabs, you'll notice a pattern when it shrinks and when expands, I could only fool it once into not animating but it's not reproducible on my end.

**Comment by asemiankevich** [comment]
@rasom can't access Done button on iOS (iphone XR) , chat tab is autofocused. Then i can swich to wallet tab and procceed but looks buggy  because this onboarding screen present twice : on chat tab and wallet tab

image

**Comment by rasom** [comment]
@asemiankevich can you please specify steps to reproduce?

**Comment by asemiankevich** [comment]
> @asemiankevich can you please specify steps to reproduce?

- open status
- create new account
- switch to ropsten
- open Test Dapp
- open Transaction tab
- tap deploy contract
- see Onboarding screen present however you are on chat tab
- switch to Wallet tab
- complete onboarding on wallet tab
- see that one more onboarding is shown

**Comment by asemiankevich** [comment]
@rasom also , when i am under mobile network and try to create account - i can't switch between tabs. + Mobile Settings pop up is not shown. it's like something invisible appears on foreground when 3G enabled which locks the screen for any action. 

i was able to reproduce as well as @Serhy 

Steps:
- turn off Wifi
- turn on mobile newtork
- open status and proceed with account creation
- switch between tabs

**Comment by rasom** [comment]
@asemiankevich is the last issue specific to this PR or can be reproduced in develop?

**Comment by asemiankevich** [comment]
> @asemiankevich is the last issue specific to this PR or can be reproduced in develop?

develop looks good however i dont see the Syncing pop up upon launch here too.. But it is not frozen, i can tap everywhere.

**Comment by rasom** [comment]
did you test it on android? I can't reproduce the issue on iOS

**Comment by asemiankevich** [comment]
@rasom right, can't reproduce the issues on android

**Comment by rasom** [comment]
@asemiankevich i have an impression that our messages contain opposite statements. Can you please clarify: is it iOS or Android bug?

**Comment by asemiankevich** [comment]
> @asemiankevich i have an impression that our messages contain opposite statements. Can you please clarify: is it iOS or Android bug?

as i stated above, all issues i described, i saw on iOS (iPhone XR) device and can't reproduce on Android device.

**Comment by rasom** [comment]
testing last ipa https://webapp.diawi.com/install/Xdt4fM , can't reproduce the issue on iPhone X

**Comment by asemiankevich** [comment]
@rasom would you mind to check video i captured? https://drive.google.com/open?id=1xmf9_uTmUcdgmbwukbYdGjCMhAbGd2w8

**Comment by rasom** [comment]
requested access

**Comment by asemiankevich** [comment]
> requested access

yeah granted. Not sure why it was not done automatically, sorry Oo

**Comment by rasom** [comment]
I was asking about the last issue, 
> when i am under mobile network and try to create account - i can't switch between tabs. 

you def can switch between tabs on video, am I missing something?

**Comment by asemiankevich** [comment]
> I was asking about the last issue,
> 
> > when i am under mobile network and try to create account - i can't switch between tabs.
> 
> you def can switch between tabs on video, am I missing something?

yeah that one i could not reproduce anymore, I probably misread your comment, multitasking. Sorry for confusion (

@Serhy would you mind to check https://webapp.diawi.com/install/Xdt4fM too? You were able to repro the issue with frozen tabs too :D

**Comment by rasom** [comment]
huh, ok, I'm switching to the first problem then

**Comment by Serhy** [comment]
Ok, so with https://webapp.diawi.com/install/Xdt4fM (and with Develop build) and strong 3G mobile connection I don't have an issue with freezes. 
What happens though, is when I have super limited connection (set to 2G (or limited access to network with 3G established as when I checked in https://github.com/status-im/status-react/pull/7623#issuecomment-470910466 ) - in that case I have freezes in app. 
It's on iPhoneX but all fine on Android. And it's in Develop too.

We'll create a separate issue for this, @rasom 

That what may happen to you @asemiankevich, when you've got frozen iOS on account creation: mobile network connected but become really limited at some point... and app freeze. And next time it was all fine.

**Comment by rasom** [comment]
@Serhy is it specific to this PR or can be reproduced in develop?

**Comment by rasom** [comment]
@asemiankevich on-boarding and modals related issue should be fixed now

**Pull request merged**
