### PR TITLE
[TESTS] Message reliability tests

### PR DESCRIPTION
**Pull request by yevh-berdnyk**
### Summary:
Added tests:

- test_message_reliability_1_1_chat
- test_message_reliability_public_chat
- test_message_reliability_offline_public_chat

status: ready

### CODE REVIEW

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/q5AGmV for branch PR-4468

<blockquote><div><strong><a href="https://i.diawi.com/q5AGmV">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/SDCU4A for branch PR-4468

<blockquote><div><strong><a href="https://i.diawi.com/SDCU4A">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/HFXLzN for branch PR-4468

<blockquote><div><strong><a href="https://i.diawi.com/HFXLzN">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/x7oyub for branch PR-4468

<blockquote><div><strong><a href="https://i.diawi.com/x7oyub">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/cAJjqn for branch PR-4468

<blockquote><div><strong><a href="https://i.diawi.com/cAJjqn">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/eq3mKK for branch PR-4468

<blockquote><div><strong><a href="https://i.diawi.com/eq3mKK">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/s4KnrQ for branch PR-4468

<blockquote><div><strong><a href="https://i.diawi.com/s4KnrQ">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/YkkMSN for branch PR-4468

<blockquote><div><strong><a href="https://i.diawi.com/YkkMSN">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/mDQWJr for branch PR-4468

<blockquote><div><strong><a href="https://i.diawi.com/mDQWJr">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/4zyn9Y for branch PR-4468

<blockquote><div><strong><a href="https://i.diawi.com/4zyn9Y">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Review by antdanchenko — APPROVED** [review]

**Pull request merged**
