### PR TITLE
[#12585] Clear modal's dissmissing state after reopening app with ena…

### LINKED ISSUE #12585: No redirection to some views if enable PNs and reopen the Status app (Android)
# Bug Report

## Problem 
If enable push notifications on an Android device, reopen the app (frequently need to reopen **multiple times**) and tap 3-random name/mention in the public chat to open a user profile, or try to start a new 1-1/join another public chat, or post smth on Timeline (tap `+` on the Timeline screen), there will be no redirection to the corresponding screens.
Disabling PNs and reopening the app fixes the issue. 

#### Expected behavior

Can navigate to the corresponding screens after enabling PNs and reopening the app

#### Actual behavior

https://user-images.githubusercontent.com/67952253/133436134-9afa5b2a-417d-4ddf-9bab-2c9f49977174.mp4

### Reproduction

1. Open Status
2. Join public chat
3. `Settings` > `Notifications` > enable
4. Kill the app
5. Open the app
6. Open public
7. Tap some user name or mention in the chat history (if the behavior doesn't reproduce, reopen the app a few times)
8. Open the home screen > `+` button > tap `Start new chat` or `Join public chat`

### Additional Information

- Status version: release 1.16
- Operating System: Android

### Logs
[geth.log](https://github.com/status-im/status-react/files/7170364/geth.log)

### PR DESCRIPTION
**Pull request by rasom**
…bled background service

fixes #12585

status: ready

### CODE REVIEW

**Review by flexsurfer — APPROVED** [review]

**Comment by qoqobolo** [comment]
@rasom can't launch the app
This error on Android and crash when opening on iOS

Screenshot 2021-09-24 at 10 20 06

**Comment by rasom** [comment]
@qoqobolo should be fixed now

**Comment by qoqobolo** [comment]
@rasom thanks!
But still can replicate https://github.com/status-im/status-react/issues/12585 in the latest build:(
Enabled PNs and reopened Status two times

https://user-images.githubusercontent.com/67952253/134656288-e2f6d356-c683-4e91-9540-4d37b40c33fe.mp4

**Comment by rasom** [comment]
@qoqobolo let's try again then, added one more line

**Comment by qoqobolo** [comment]
@rasom seemed to work! Thank you

**Pull request merged**
