### PR TITLE
Different date/time format on "Transaction details" screen

### LINKED ISSUE #4558: Different date/time format on "Transaction details" screen
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to see same time format (ideally the same as I specify in my phone settings) across the app.

### Description
*Type*: Bug
*Summary*: in "Chats", "Transaction history" 12h time format is using; the only  place where I can see 24h time format is "Transaction details" screen
#### Expected behavior
30 May, 3:41 PM;
same time format everywhere

#### Actual behavior
May, 30 15:41:08
- Tap on the top transaction to see "Transaction details".
image

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Go to "Wallet" (should have some Transaction History)
- Tap on "Transaction history". Pay attention to datetime format - 30 May, 3:41 PM)
- Tap on the top transaction to see "Transaction details".

### Additional Information

* Status version: nightly 31/05/2018
* Operating System: Android, iOS

### PR DESCRIPTION
**Pull request by tbenr**
Fixes #4558

### CODE REVIEW

**Comment by jeluard** [comment]
@tbenr Can you detail how this change fixes the issue?

**Comment by tbenr** [comment]
@jeluard Yes, i moved from an unlocalized hardcoded format to a google i18n date-time format that is already referenced above in the file. So the date time in transaction detail is now localized. The transaction list screen has already a localized time format.
If the solution is OK, it can be also applied to the grouping format on the left in the transaction list (dd MMM), so it become localized as well.

**Comment by jeluard** [comment]
I am confused about `keyword` previously used.

**Comment by tbenr** [comment]
I'm quite new in closureJs, for the moment I cant say why `keyword` has been used.
I just replicated how time format is generated for the transaction list.

time is defined like this:
`
(defn timestamp->time [ms]
  (.format time-fmt (-> ms
                        from-long
                        (plus time-zone-offset))))
`

I did the same thing for date-time, referencing `date-time-fmt`

**Comment by jeluard** [comment]
The contract of the function you modified is now different but callers haven't been modified (used to return a keyword, now a string).
I would expect this to break?

**Comment by tbenr** [comment]
I have to learn and check. back to you soon.

**Comment by jeluard** [comment]
@tbenr Thanks!

**Comment by tbenr** [comment]
to be honest, after some hours of clojure tutorials, now I know something more about cljs but I still can't understand how the original function returning a `keyword` was handled by the code to display the date.

I still have to setup my env to be able to run a debug session to understand what happens. It seems to me that the result of fn `timestamp->long-date` is redered using `react\text` ui component which deals with strings.

I don't know if somewhere a magical keyword to string conversion is done. A more experienced clojurejs\re-frame programmer may help..

btw, returning a string it works on my android-real.

**Comment by jeluard** [comment]
@tbenr Great to hear!

I am not clear either why this fn used to return a keyword. @yenda Any clue? I can see you touched it last.

**Comment by yenda** [comment]
@jeluard: @tbenr assumption is right, the function wrongfully returns a keyword but it shows as a string through react/text. It can be removed safely as this is the only place where this function was used

**Comment by tbenr** [comment]
@yenda thanks, and what about here?

https://github.com/tbenr/status-react/blob/da3185325e4fb05fe0a274a11ddbabcf6426cb9f/src/status_im/utils/datetime.cljs#L81-L84

it is used to implement the group-by. Is keyword needed?

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/tbenr/status-react">tbenr/status-react</a></strong></div><div>status-react - a free (libre) open source, mobile OS for Ethereum</div></blockquote>

**Comment by jeluard** [comment]
@tbenr I guess we can left the other one untouch. Let's see what QA can find here ! :)

**Review by jeluard — APPROVED** [review]

**Review by goranjovic — APPROVED** [review]

**Comment by goranjovic** [comment]
Special kudos for getting rid of that awkward `keyword` @tbenr ! :beers:

**Comment by tbenr** [comment]
The only thing I may add in this PR is a localized version of date used for grouping transaction in transaction history.

Currently is:
https://github.com/tbenr/status-react/blob/308f106dfa90e174352d507377a57188ed86f956/src/status_im/utils/datetime.cljs#L71-L74

not 100% matching the issue topic but deals with the same things.
What do you think?

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/tbenr/status-react">tbenr/status-react</a></strong></div><div>status-react - a free (libre) open source, mobile OS for Ethereum</div></blockquote>

**Comment by jeluard** [comment]
@churik Any opinion on that?

**Comment by tbenr** [comment]
to be clear, I'm talking about this:
screenshot_20180723-160655

**Comment by churik** [comment]
Thanks, @tbenr ! much more clear.
Looks good to me.
I'll test it soon and let you know if I find smth.

**Comment by jeluard** [comment]
@churik I understood @tbenr comment as doing something more than what you requested

**Comment by churik** [comment]
@tbenr 
Thanks for your PR!
I took a look and it and noticed that for now for IOS we have 24h format everywhere (chat, transaction, transaction screen), but for Android 12 h time format (regardless of user settings on the phone)
andr
I suggest to use or 24h or 12h format for both IOS and Android (as a simple solution) , but ideally, make the timestamp depends on user phone settings.

**Comment by tbenr** [comment]
Hi @churik, it's strange because the screenshot I posted above was actually taken from an android device (Galaxy S6) Italian language, and it is a 24h format.
Can you tell me android version and language setting you are using to replicate the issue?

**Comment by churik** [comment]
Hi, @tbenr!
Operating System: Android 7.0
Device: Samsung Galaxy S7
Language: English
Time format: tried both 24h and 12h - regardless of settings 12h format is displayed inside app.
TF session: https://app.testfairy.com/projects/4803622-status/builds/8535051/sessions/4397044349/?accessToken=dTFTLjRnbpvjfs4VUr-f1zLe36o

<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803622-status/builds/8535051/sessions/4397044349/?accessToken=dTFTLjRnbpvjfs4VUr-f1zLe36o">TestFairy: Status 0.9.23 (6242) @2018</a></strong></div></blockquote>

**Comment by tbenr** [comment]
Thanks @churik, ok now I understand. Currently the time format is taken only from the locale settings and not from device settings. To be able to "see" user device settings we should integrate this:
https://github.com/risedigital/react-native-device-time-format
or maybe a more general\maintained module like https://github.com/rebeccahughes/react-native-device-info that can be also used to get more info from the device.

let me do some tests.

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/risedigital/react-native-device-time-format">risedigital/react-native-device-time-format</a></strong></div><div>react-native-device-time-format - Device time format information for React Native</div></blockquote>
<blockquote><div> GitHub</div><div><strong><a href="https://github.com/rebeccahughes/react-native-device-info">rebeccahughes/react-native-device-info</a></strong></div><div>react-native-device-info - Device Information for React Native iOS and Android</div></blockquote>

**Comment by tbenr** [comment]
Hi @churik @jeluard @yenda.
I improved a lot the PR by:

- integrating [react-native-device-info](https://github.com/rebeccahughes/react-native-device-info) to get device 24H\AMPM settings
- consistently generate localized datetime formats based on the 24H\AMPM device setting (_**when you change device settings, the app must be restarted to see changes in formats**_)
- expanded datetime format tests to cover new settings

some screenshots:

**----------in transaction history---------------**


**------------in transaction details:------------**
screenshot_20180730-022531

**----------in chat----------------------------**
screenshot_20180730-022330

**Comment by jeluard** [comment]
@tbenr Sorry for not making this clearer but we usually try to avoid adding new dependencies.
What would be the downside of not relying on it?

Also it looks like this is not specifically part of the scope of the original issue?

**Comment by tbenr** [comment]
Hi @jeulard, I understand that.
I added it to cover the need of switching hour format based on device settings (which is described in the user story)

To avoid a new dep, I may try integrate the needed functions (android/ios) in the existing status react module but please double check if it the right direction to take.

**Comment by jeluard** [comment]
Great thanks for pushing this!

My understanding of the original issue is to make sure time is displayed uniformly in the app. If your experiments fail it would make sense to implement only this bit in this PR.

**Comment by tbenr** [comment]
@jeluard ok, I would prefer to detach the dependency from this PR and leave the predisposition here and plug the device info settings in another PR. Is it ok for you?

**Comment by jeluard** [comment]
@tbenr Makes sense!

**Comment by tbenr** [comment]
good :-)  any way my idea is to implement the device info gathering in here: https://github.com/status-im/react-native-status. It seem to me a generic reactive module that is already included. is it the right place? 

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/status-im/react-native-status">status-im/react-native-status</a></strong></div><div>Contribute to react-native-status development by creating an account on GitHub.</div></blockquote>

**Comment by jeluard** [comment]
@tbenr Currently the whole native part is in this same repo: e.g. https://github.com/status-im/status-react/tree/develop/android/app/src/main/java/im/status/ethereum

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/status-im/status-react">status-im/status-react</a></strong></div><div>status-react - a free (libre) open source, mobile OS for Ethereum</div></blockquote>

**Comment by tbenr** [comment]
@jeluard done!

**Comment by jeluard** [comment]
@tbenr Thanks!

**Comment by churik** [comment]
Tested (IOS, Android):
- creating new account
- restoring account with real ETH and transaction history
- timestamps in Transaction history, Transaction details, 1-1 chat and public chats with 24h/12h formats,
- #4558 is not reproducible 

NOTE: https://github.com/status-im/status-react/pull/5158#issuecomment-407420121 is also reproducible on current nightly (30/07/18, 0.9.24 (6259)) so it wasn't introduced by this PR

What I noticed that regardless of settings I still can see 12 H for my Android but 24 H for IOS.
wr

@tbenr  as I understood from previous comments  - the application should change time format accordingly to device settings due to last changes?

**Comment by tbenr** [comment]
Hi @churik, with @jeluard we agreed to implement the 12/24h device settings detection on a separate PR. Here we have the fix for consistency arownd the APP and the predisposition to allow, in a separate PR, the switch between 12/24. Is it OK?

**Comment by churik** [comment]
@tbenr yes, thanks for clarification!

**Comment by jeluard** [comment]
@tbenr Thanks for your contribution!

**Pull request merged**
