### PR TITLE
Make bold work on desktop again

### PR DESCRIPTION
**Pull request by janherich**
[comment]: # (Please replace ... with your information. Remove < and >)
[comment]: # (To auto-close issue on merge, please insert the related issue number after # i.e fixes #566)

Fixes bold highlighting (wrapping chat message text in *) on desktop.

Due to recently merged https://github.com/status-im/status-react/pull/6554/, `{:font :medium}` style for desktop was not working again, on the good side, it's now consistent with mobile, so no `platform/desktop?` necessary anymore.

status: ready

### CODE REVIEW

**Review by flexsurfer — APPROVED** [review]

**Review by yenda — APPROVED** [review]

**Review by rasom — APPROVED** [review]

**Comment by churik** [comment]
@janherich 
#### `No protocol method` error at attemt to open any chat
**Steps:**
1) Log in with existing account
2) Open any chat from chat list

**Expected result:**
Can see chat history

**Actual result:**
undef

**Log:** [Status.log](https://github.com/status-im/status-react/files/2566475/Status.log)

**Comment by janherich** [comment]
@churik I just tested it and the same problem is present in latest develop, so it doesn't have anything with this PR but I understand it's impossible to actually test with that condition :/

**Comment by yenda** [comment]
@janherich @churik fixed here https://github.com/status-im/status-react/pull/6677

**Comment by janherich** [comment]
@churik ready to be tested again (as soon as new build is finished)

**Comment by SlizkovaGanna** [comment]
Failed tests are unrelated.

Bold and italic fonts are fixed for desktop.
Checked in MacOS 10.13.4 and Linux ubuntu 18.04.1 (emulated)

General related issues discovered:
https://github.com/status-im/status-react/issues/3199 - already reported, low severity
https://github.com/status-im/status-react/issues/6704 and https://github.com/status-im/status-react/issues/6705 - newly reported, low severity

**Comment by jakubgs** [comment]
Merged at: https://github.com/status-im/status-react/commit/f5ab49a4a486ac998a180f9b37dce1627793c2b9

**Pull request closed without merging**
