### PR TITLE
cleanup jenkinsfile and prepare for builds on new linux slaves

### PR DESCRIPTION
**Pull request by jakubgs**
General `Jenkinsfile` cleanup for desktop builds an a few fixes to prepare it for use of new Linux Jenkins slaves.
Not ready yet, needs a fix for the steps referencing `/home/maxr/qttools/StatusImAppImage.zip`.

### CODE REVIEW

**Comment by jakubgs** [comment]
Most successful build so far:
https://ci.status.im/job/status-react/job/desktop/job/manual/78/console

**Comment by jakubgs** [comment]
Also needs a fix for downloading:
https://github.com/probonopd/linuxdeployqt

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/probonopd/linuxdeployqt">probonopd/linuxdeployqt</a></strong></div><div>linuxdeployqt - Makes Linux applications self-contained by copying in the libraries and plugins that the application uses, and optionally generates an AppImage. Can be used for Qt and other applica...</div></blockquote>

**Comment by jakubgs** [comment]
IT'S ALIVE!
https://ci.status.im/job/status-react/job/desktop/job/manual/83/

<blockquote><div><strong><a href="https://ci.status.im/job/status-react/job/desktop/job/manual/83/">status-react » desktop » manual #83 [Jenkins]</a></strong></div></blockquote>

**Comment by jakubgs** [comment]
Since we are in a rush I've left the `/home/maxr/qttools/StatusImAppImage.zip` thing in for now. @MaxRis is aware of it and will be fixed in the future.

**Review by maxhora — APPROVED** [review]
@jakubgs thank you!!

**Comment by jakubgs** [comment]
I've included changes from:
https://github.com/status-im/status-react/pull/5363/

**Review by vkjr — APPROVED** [review]

**Comment by jakubgs** [comment]
I've cherry picket the commit and pushedit by hand becaue I didn't feel like dealing with the conflicts and the merge script:
https://github.com/status-im/status-react/commit/8eaed87a964484a8c1902669b72e9b9413f14279

**Pull request closed without merging**
