### PR TITLE
Desktop no bubbles

### PR DESCRIPTION
**Pull request by flexsurfer**
image

### CODE REVIEW

**Review by janherich — APPROVED** [review]

**Comment by chadyj** [comment]
I'd love to merge this ASAP and iterate on it.  What do you think @errorists @denis-sharypin @andmironov?

Also it seems like chat bubbles and layouts are deeply personal and there is no one size fits all. What do you think about theme support? This could actually be a very cool way to get the community involved on a lower technical level in addition to exciting users.  A dark theme is already one of our top feature requests.

A Status theme store could be a very cool thing :). Get a new theme for X SNT and all that goes to the author.

**Comment by errorists** [comment]
@chadyj I have yet to see an in-app 'theme store' that would serve quality content, so colour me an unbeliever :) But let's say we manage to attract people who'd contribute the good stuff, I still think it's too early to open up our UI to theming because it's still a baby, barely started teething, things are changing left and right, we're moving stuff around, we could be breaking themes on a weekly basis. 
Also, a dark theme is a different animal as it's actually not only a matter of taste but usability, I switch everything to a dark theme, not because of aesthetics but I don't enjoy staring at a 27" lightbulb the entire day. So, it's a matter of 'when' and not 'if' we introduce a dark mode to our apps, it's definitely happening. 

Oh, and on the merge. I'm not sure tbh, I'd prefer to have it the other way around, design first followed by implementation. In the current state, this stuff is still rough :) Paging @EugeOrtiz the desktop design wunderkind.

**Comment by chadyj** [comment]
Hey @errorists there are heaps of quality theme stores around and have been for years. Just google "theme store" and you'll find them for Chrome, Shopify, Wordpress and more. 

I'm not sure I buy your argument it is too early to attract contributors to Status. That is our whole mission right now and we are doing what we can to promote inclusivity (bounties, outreach, docs, transparency) and attract all types of people, so why not this too?  I'm not too concerned about breaking stuff as we all do this on a weekly basis in the core app so that is just part of the thrill of building something new.  And besides we have a great design team here to kick it off with a few themes :-)

As for the point of some themes being "not only a matter of taste but usability", I couldn't agree more. What is usable for one person isn't usable for another and one size doesn't fit all. So why not let users create the theme that works best for them?  It might be good for others too.

**Comment by errorists** [comment]
Ok sure but Shopify and Wordpress were built from the ground up with the intent of customisability, to me, it's apples and oranges, actual product UI is different :) Oh and you got me wrong there, I'm not saying no to contributors, I'm saying opening up our UI at this early stage might burn some talented people that will have to deal with the constant tinkering on our part. I've created themes for a living, and I know how it feels when you're getting angry emails from people because the theme you created doesn't support the latest nightly. It's just a different point of view I'm trying to introduce here. It's a good idea, I think we're just not ready for it yet.

**Comment by denis-sharypin** [comment]
I don't mind to have like this: just a few things to make it even more readable:
- add a grey outline to user picks (take a look at the mobile product) 
- delete an extra space between two separate messages of one person. Here for instance:
screenshot 2018-10-11 09 45 48
- fix replies with outlining the reply box. Similar to this but without user pick and X button
screenshot 2018-10-11 09 47 03

**Comment by errorists** [comment]
public chat - messages copy 3

I agree with Denis, the reply needs a different container to make it work, like so

**Comment by flexsurfer** [comment]
image
@errorists wdyt? it's not ideal, but looks good for the first iteration, @chadyj ?

**Comment by chadyj** [comment]
Looks like a perfect first iteration :+1:  Happy to ship this and iterate.  Nice one Andrey!

@EugeOrtiz is back and she can help on the next iterations too.

**Comment by chadyj** [comment]
Just noticed that the reply is below the message. I find this odd as it makes the reply out of chronological order and convention.  Personal preference is to flip it.

Such as:

> old quote for context

New reply

**Comment by EugeOrtiz** [comment]
@flexsurfer Let's also align the images to the top of the text. It will improve scanning/readibility a lot.

Design:
captura de pantalla 2018-10-12 a la s 2 11 15 p m

Implementation:
captura de pantalla 2018-10-12 a la s 2 10 38 p m

**Review by vitvly — APPROVED** [review]
Love it.

**Comment by errorists** [comment]
> Just noticed that the reply is below the message. I find this odd as it makes the reply out of chronological order and convention. Personal preference is to flip it.

Yeah, the quote below reply was a habit of mine coming from Twitter and Slack, agree that in hindsight this probably doesn't make logical sense lol :) 

@flexsurfer can I suggest some quick fixes? The reply icon is too large there, should be 16px. The timestamps appear to be washed out, are they using our Dark Grey color? The outline around avatars should also be the 10% Black. To make the layout appear lighter I also increased the left and right margin around the avatar to 16px. I know they're mobile, but I keep my designs [here](https://www.figma.com/file/aS1ct66VQ6V0cio7vSqS8UoG/Chat?node-id=300%3A0) if they can be of any help

But hey, it's great start man! Kudos 👍

**Comment by flexsurfer** [comment]
image
@EugeOrtiz @errorists

**Comment by chadyj** [comment]
Hey @flexsurfer we have 4 :+1:'s on your latest change. Shall we merge and try this on for size?

Will be nice to play with this for a week and see how we like it and can iterate based on feedback.

**Comment by flexsurfer** [comment]
@chadyj yes sure, it's ready for merge

**Comment by asemiankevich** [comment]
@chadyj @flexsurfer let me quickly try it

**Pull request merged**
