### PR TITLE
[#17288] refactor: migrate previews to new api

### PR DESCRIPTION
**Pull request by mohsen-ghafouri**
to accomplish https://github.com/status-im/status-mobile/issues/17288

migrated : 
- browser
- list_items
  - token_value
  - user_list
- navigation

status: ready

### CODE REVIEW

**Review by ilmotta — APPROVED** [review]
Way to go!

**Review by vkjr — APPROVED** [review]

**Comment by mohsen-ghafouri** [comment]
@status-im/mobile-qa just it touch some renaming in token-value and bottom nav. I added qa label as a precaution

**Review by jo-mut — APPROVED** [review]

**Comment by VolodLytvynenko** [comment]
@mohsen-ghafouri Thank you for PR. Here a found issues:

## ISSUE 1: The positive and negative arrows of token value are shown at the end

### Actual result:
The positive and negative arrows of the token value are shown at the end
image

### Expected result:
The positive and negative arrows of the token value are shown at the beginning

image

https://www.figma.com/file/Q92CTbwanXZwSWrHWKfJqS/Wallet-UX-for-Mobile?type=design&node-id=3400-504834&mode=design&t=orwouQRS58RczuSl-0

**Comment by VolodLytvynenko** [comment]
I'm not certain if this issue could arise when the 'clear' button is exclusively used for quo. If this problem might impact the appearance in other scenarios, it'll be better to address it. Otherwise, we could choose to leave it as is. WDYT?

## ISSUE 2: The app crashes with `cannot read property 'toUpperCase' of null` error when token value is cleared

### Steps:
List items -> token value -> open 'token' dropdown -> tap 'clear'

### Actual result:

The app crashes after with `cannot read property 'toUpperCase' of null` error when token value is cleared

https://github.com/status-im/status-mobile/assets/52490791/635260c5-da3b-40b2-a688-685c9d606a96


### Logcat
[Status-debug-logs.zip](https://github.com/status-im/status-mobile/files/12701295/Status-debug-logs.zip)

**Comment by mohsen-ghafouri** [comment]
Thanks @VolodLytvynenko , i will check these issues

**Comment by mohsen-ghafouri** [comment]
@VolodLytvynenko regarding issue one i think there is an mismatch between design system and usages part, will confirm with design team
https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?type=design&node-id=114-5860&mode=design&t=NPfipUlaTfuu55CP-4

**Comment by mohsen-ghafouri** [comment]
@VolodLytvynenko  i fixed the second issue, for issue 1 , design team need to update figma. we can add followup label to this. i will take care of it in another PR

**Comment by VolodLytvynenko** [comment]
Thanks for the fix @mohsen-ghafouri . No issues from my side anymore.
Let's wait for the design review.

**Comment by mohsen-ghafouri** [comment]
regarding issue 1 , it seems that link was old and this is updated figma file. so implementation is correct and no changes needed. 
https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=1-46441&mode=design&t=PGpfJP4HM0QCrehl-4

**Comment by VolodLytvynenko** [comment]
> regarding issue 1 , it seems that link was old and this is updated figma file. so implementation is correct and no changes needed. https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=1-46441&mode=design&t=PGpfJP4HM0QCrehl-4

@mohsen-ghafouri thank you for clarification of this. Issue 1 is not valid https://github.com/status-im/status-mobile/pull/17366#issuecomment-1731441689

@status-im/design-team  could you check this please?

### NOTES for design reviewer:
area where UI is changed:
1. quo -> list items -> token-value

all other described in https://github.com/status-im/status-mobile/pull/17366#issue-1905353654 is without changes

**Review by Francesca-G — APPROVED** [review]
Component looks good ✨

I had an issue when changing between states. 
As you can see I change between default, pressed and active state but nothing changes visually. Moreover when I press the component it seems like its state becomes "pressed" when I tap and hold, and than "active" on release:


https://github.com/status-im/status-mobile/assets/122543089/d1bacab4-ba82-49a6-a1a6-6c8ca09d5bf9

**Comment by mohsen-ghafouri** [comment]
Thanks @Francesca-G as i checked states are internal values for token-value component and we can see different state when we press on it as you already mentioned. i just removed state from preview screen.

**Pull request merged**
