### PR TITLE
chat: implement emoji replace

### LINKED ISSUE #840: Implement Emoji Replace
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to type and have emoji's automatically replaced for me.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: https://github.com/mugendi/emoji-replace

### PR DESCRIPTION
**Pull request by matthieu-beteille**
fixes #840 

### Summary:
- This will replace text-based emoticons with emojis in the chat. 
- This PR uses this very simple emoji package that provides a json containing all the emojis indexed by their names: https://github.com/muan/emojilib 

### Steps to test:
- Open Status
- Go to the chat and type one of the emoji name between `:` (ex:  `:smile:` `:+1:`  `:123:` `:cactus:` )
(all the keys of the following json are supported: https://github.com/muan/emojilib/blob/master/emojis.json )

status: ready

### CODE REVIEW

**Comment by jeluard** [comment]
Would you mind adding some unit tests?

**Comment by matthieu-beteille** [comment]
Sure. 
I tried to run the test with `lein doo node test once` didn't work out really well though.
Is that how I am supposed to run them?

**Comment by jeluard** [comment]
You can find inspiration in this [PR](https://github.com/status-im/status-react/pull/1249/files) (not yet merged).

Ideally you would only add your tests and not changes required to make test run. This way we will reduce possible conflicts.

**Comment by matthieu-beteille** [comment]
Ok cool. I wrote some tests but I am not able to run them even after following the PR you sent me.

I get this weird error when running `lein doo node test once`, and I haven't been able to spend much more time on that:


```
;; ======================================================================
;; Testing with Node:

.../status-react/node_modules/react-native/Libraries/react-native/react-native-implementation.js:16
if (__DEV__) {
    ^
ReferenceError: __DEV__ is not defined
    at Object.<anonymous> (/Users/matthieu/workspace/status-react/node_modules/react-native/Libraries/react-native/react-native-implementation.js:16:5)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
   at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/matthieu/workspace/status-react/node_modules/react-native-i18n/index.js:3:35)
    at Module._compile (module.js:573:32)
```

**Comment by rasom** [comment]
@matthieu-beteille, let's just skip test for now, we have some problems with tests env atm, this will be fixed soon. Please resolve conflict.

**Comment by matthieu-beteille** [comment]
Done.

**Comment by rasom** [comment]
Thanks @matthieu-beteille

**Pull request merged**
