### PR TITLE
[#12821] Fix unread indicator for mentions

### LINKED ISSUE #12821: Unread indicator is not reset for mentions
# Bug Report

## Problem 
All received mentions are counted as new by the unread message counter, even if they were read.
In other words, if the user receives a mention, opens the chat to read it, returns to the home screen, and receives another mention, the count `2` will be shown, although only one mention was received. 
Also, all mention messages are displayed as new after relogin.

#### Expected behavior
Refresh the unread message counter when reading a mention message; display `1` when one new mention is received. 

#### Actual behavior

https://user-images.githubusercontent.com/67952253/141995204-499be66a-0c63-4251-9408-d3fb0101df01.MP4

### Reproduction

1. UserA and UserB join the same public chat (works for any type of chat)
2. UserA sends a message and returns to the home screen
3. UserB sends a message mentioning UserA
4. UserA opens the public chat and returns to the home screen
5. UserB sends another mention of UserA
6. UserA checks the unread counter on the public chat

### Additional Information

- Status version: nightly 16/11
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by rasom**
fix #12821

status: ready

### CODE REVIEW

**Review by flexsurfer — APPROVED** [review]

**Comment by qoqobolo** [comment]
@rasom the issue is fixed, thank you!
However, there is an issue with the confirmation of delivery of messages.

### ISSUE 1: Delivery status of some messages is not detected correctly

If UserA sends a message to UserB, e.g. in 1-1 chat (but the issue is reproduced in all types of chat), the delivery status is detected as `delivered` at first, but after some time (~ 15 seconds) it changes to `sent`. In the video below keep an eye on the status of the last two messages. In fact, all these messages are delivered to the receiver.

https://user-images.githubusercontent.com/67952253/142449465-6ffee4d2-1ba0-4336-8cde-38a994d417fd.mp4

Sometimes, the status changes to `Not confirmed`. 

Screenshot 2021-11-18 at 16 52 18

Not sure, if the reason is in the changes of this PR, but could not reproduce it in develop.
The e2e test failed for the same reason.

**Comment by rasom** [comment]
@qoqobolo the change in my PR is so tiny that I can guarantee it couldn't cause that issue. 
But although my PR on status-go is very small, here on status-react I had to upgrade status-go from `v0.90.0` to `v0.91.1` an I thing there is something between those versions that causes the issue.
If this specific fix is necessary for the release I can create a separate branch on status-go and create a specific commit for the release branch. Anyway this new issue should be handled separately.

Any thoughts what could be the cause @cammellos ?

**Comment by cammellos** [comment]
> Any thoughts what could be the cause @cammellos ?

Many, that's most likely, almost certainly, my fault

**Comment by cammellos** [comment]
> Any thoughts what could be the cause @cammellos ?

Reverted the commit on develop, if you rebase it should be gone 
:magic_wand:

**Comment by rasom** [comment]
@qoqobolo the issue should be fixed now

**Comment by qoqobolo** [comment]
@rasom @cammellos thank you!
After resolving conflicts PR can be merged.

**Comment by rasom** [comment]
@qoqobolo it is already merged in another PR, I will just close this one

**Pull request closed without merging**
