### PR TITLE
Whisper v6/geth 1.8.1 migration

### LINKED ISSUE #3448: Update mailserver addresses for Whisper v6 in constants.cljs
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a developer, I want status-react to use the new Whisper v6-enabled mailservers so that we can start switching to the new cluster.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: <Bug|Feature>

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: https://github.com/status-im/status-react/blob/4fa9459e40f312a60a9512d309fea9525f8b4420/src/status_im/constants.cljs#L87-L93 needs to be updated with addresses from new cluster

cc @feuGeneA

### PR DESCRIPTION
**Pull request by pedropombeiro**
[comment]: # (Please replace ... with your information. Remove < and >)
[comment]: # (To auto-close issue on merge, please insert the related issue number after # i.e fixes #566)

Closes #3448 

### Summary:

[comment]: # (Summarise the problem and how the pull request solves it)
This PR updates status-react to use status-go branch `feature/whisperv6-#665` which brings Whisper v6 and geth 1.8.1. It also updates the main mailserver address to point to a v6 instance in the cluster (test mailserver wasn't changed and will not work).

### Note:

This PR is for testing purposes only at the moment.

TODO:
- [x] Update test mailserver address.

status: ready

### CODE REVIEW

**Review by yenda — APPROVED** [review]

**Review by janherich — APPROVED** [review]

**Comment by annadanchenko** [comment]
tested for data consumption
1. `Create account and wait 5 minutes in Console doing nothing` on nightly and PR build then data usage diff is ~11 Mb on PR vs 84 Mb on nightly build for Feb 28
2. `Create account, add contact, send text message in 1:1 chat and check balance in Wallet` data consumption on PR is 12-13 Mb vs 76-82 Mb on nightly for Feb 28
3. `Create account, add contact, send/receive text message in 1:1 chat, create group chat, send/receive text message in group chat, join public chat, send/receive text message in public chat, check balance in Wallet`: data consumption on PR build is 15-14 Mb vs 78-83 Mb on nightly. If log in again and send text text message in public, group and 1:1 chat and then receive text message in public, group and 1:1 chat  then total data consumption on PR build is 26-27 Mb vs 146-154 Mb on nightly
4. Also tested scenario to recover account, send transaction in chat and from DApp, send text in all kind of chats, get Pn when app is closed

**Review by oskarth — APPROVED** [review]
IMO we can merge this to nightly already. We've been using it in Bangkok last day or so and seems to work OK.

I don't think we should have to worry about people downloading nightly and compatibility. 0.9.15 will have v5 and nightly from merge-point and 0.9.16 will have v6.

@adambabik @PombeirP WDYT from status-cluster migration POV? Do you see a problem with merging this or can we just make a new PR once that happens (presumably after offsite)?

**Comment by pedropombeiro** [comment]
@oskarth If that's the case then I don't see an issue with merging this to `develop`. The issue for the cluster migration is https://github.com/status-im/status-go/issues/640. @feuGeneA will be creating a PR for it soon.

**Comment by pedropombeiro** [comment]
One thing I've done is use a second mailserver as a backup mailserver, instead of a test mailserver (not sure what the configuration for that one was, will probably need @adambabik's input here).

**Comment by adambabik** [comment]
There were the same in terms of configuration, just the second was added later,

**Comment by pedropombeiro** [comment]
@adambabik so for this PR, should we move to the `backup mailserver` terminology, or keep the existing `test mailserver` terminology?

**Comment by pedropombeiro** [comment]
Would like to get this merged today and kick a nightly build, so that the test team can start using it (including for dogfooding sessions).
For reference, the status-cluster PR is https://github.com/status-im/status-cluster/pull/53

**Comment by adambabik** [comment]
@PombeirP I would not distinguish between `regular` and `backup` mailservers. These two are equal in terms of features and their status, however, we should distinguish them for debugging purposes. So maybe just `Mailserver A` and `Mailserver B`?

**Pull request merged**
