### PR TITLE
Various fixes for Contact Request flows

### PR DESCRIPTION
**Pull request by ilmotta**
### Summary

This PR was created due to a request from the Desktop team because the [status-go PR #3327](https://github.com/status-im/status-go/pull/3327) will soon be merged and **we need to know if there's any impact on mobile in Contact Request flows**.

Please, see the status-go PR for more details. For visibility purposes, cc'ing @MishkaRogachev.

### Steps to test (for QA team)

Generally test CR flows.

**This PR should not be merged, since it's just for verification purposes.**

status: ready

### CODE REVIEW

**Review by ibrkhalil — APPROVED** [review]

**Comment by ilmotta** [comment]
Hi @status-im/mobile-qa, could one of you kindly review CR flows in mobile until Apr 7th? The reason being that the desktop team will do a release and the branch used by  [status-go PR #3327](https://github.com/status-im/status-go/pull/3327) will be merged this Friday.

I opened this mobile PR as a way to help double-check if the status-go PR won't introduce regressions, as requested from the Desktop team. I have tested basic workflows to accept/decline CRs between two devices, but I haven't checked for super edgy cases. I see there are two e2e tests failing related to CRs, but I don't know if they're failing due to a regression or due to some other randomness.

I will be off tomorrow (Friday). If you find any issues, please, reach out to @MishkaRogachev, since he was the author of the status-go PR and has more context about what's being changed.

Thanks a lot!

Edit: **This PR should not be merged**, since it's just for verification purposes.

**Comment by VladimrLitvinenko** [comment]
Hi @MishkaRogachev! Could you resolve existing conflicts?  Thanx!

**Comment by VladimrLitvinenko** [comment]
hi @MishkaRogachev. Thank you for your work. Here is the found issue:

## ISSUE 1: The pending CR is shown in the Activity Center as 'read' already after the CR sending
#### Steps to reproduce:
1. Go to non-contact profile
2. Tap 'add to contacts'
3. Check the AC bell
4. Open AC
5. Tap a filter in AC to show already read notifications 
image

#### Actual result:
The outgoing CR is shown as read in AC after CR sending

https://user-images.githubusercontent.com/52490791/230589671-70bf14a8-b175-40ac-816e-34f28b5626b5.mp4


#### Expected result:
The outgoing CR is shown initially as unread in AC.
image

image

**Comment by VolodLytvynenko** [comment]
Hi, @MishkaRogachev thank you for your work. Here are found issues:

## ISSUE 1: Pending "outgoing contact request" is still shown in the AC and in 1-1 chat after the Contact Request has been accepted by the receiver

#### Steps to reproduce:
1. USER_A: Send a CR to USER_B
2. USER_B: Open AC -> Tap 'Accept' on a shown CR
3. USER_A: Open AC  (now outgoing contact request is still shown)
4. USER_A: Open 1-1 chat

#### Actual result:
- The USER_A still sees outgoing contact request in AC after USER_B accepted it
image
- System message with 'pending' contact request is shown in 1-1 chat for both USER_A and USER_B
image


#### Expected result:
- The outgoing contact request should disapeare in the AC as soon as the current CR is accepted. As a result, user should see only notifications then about successful contact request accepting
image
- Only messages with  'accepted' contact request status is shown  in 1-1 chat
image

**Comment by VolodLytvynenko** [comment]
## ISSUE 2: The outgoing pending CR is shown in the Activity Center as already read after it has been sent
#### Steps to reproduce:
1. Go to non-contact profile
2. Tap 'add to contacts' tab
3. Check the AC bell
4. Open AC
5. Tap a filter in AC to show already read notifications 
image

#### Actual result:
The outgoing CR is shown as read in AC after CR sending

https://user-images.githubusercontent.com/52490791/230589671-70bf14a8-b175-40ac-816e-34f28b5626b5.mp4


#### Expected result:
The outgoing CR is shown initially as unread in AC.
image

image

**Comment by VolodLytvynenko** [comment]
## ISSUE 3: The CR is not received by User_B if User_A removes User_B from contacts and sends CR to him one more time

This one is probably caused by [ISSUE 1](https://github.com/status-im/status-mobile/pull/15591#issuecomment-1500191128)

#### Steps to reproduce:
1. User_A sends CR to User_B
2. User_B accepts CR
3. User_A goes profile of User_B -> taps 'remove from contacts'
4. User_A sends CR to User_B one more time

#### Actual result:
User_B does not receive the CR from User_A

#### Expected result:
User_B should receive the CR from User_A

**Comment by MishkaRogachev** [comment]
@VladimrLitvinenko, thank you for detailed testing! I've just rebased status-go branch on latest develop, but this should not affect the behaviour. Give me please some time to confirm that we having same results for the desktop client. 

1. **Pending "outgoing contact request" is still shown in the AC and in 1-1 chat after the Contact Request has been accepted by the receiver** - potential issue, checking with desktop. Expected result is right: we should see accepted and read AC notification when receiver accepts CR. 

2. **The pending CR is shown in the Activity Center as already read after the CR sending** - this kind of expected: when we send a CR we get notifications in the pending state on both sender and receiver sides. And for sender side this notification should be initially in read state.

3.  **The CR is not received by User_B if User_A removes User_B from contacts and sends CR to him one more time** - this is definitely an issue, checking with desktop.

@John-44 can you please confirm the requirements for p.2

**Comment by MishkaRogachev** [comment]
I've checked both unexpected cases with desktop and they works. I bet that's because we are using different endpoints. @cammellos way i see is to add a few new test cases, using `addContact`.

1. **Accepted state for outgoing notification**. This one is working properly on the desktop: 
https://user-images.githubusercontent.com/2522130/230610593-50feab76-ce63-4fd7-9fff-360f279761ed.mov

2. **Add/remove/add contact**. Here we have different flow using `retractContactRequest`: 

https://user-images.githubusercontent.com/2522130/230615597-33ec0edd-b3cf-42af-9cc2-77921467e037.mov

**Comment by John-44** [comment]
> @VladimrLitvinenko, thank you for detailed testing! I've just rebased status-go branch on latest develop, but this should not affect the behaviour. Give me please some time to confirm that we having same results for the desktop client.
> 
> 1. **Pending "outgoing contact request" is still shown in the AC and in 1-1 chat after the Contact Request has been accepted by the receiver** - potential issue, checking with desktop. Expected result is right: we should see accepted and read AC notification when receiver accepts CR.
> 2. **The pending CR is shown in the Activity Center as already read after the CR sending** - this kind of expected: when we send a CR we get notifications in the pending state on both sender and receiver sides. And for sender side this notification should be initially in read state.
> 3. **The CR is not received by User_B if User_A removes User_B from contacts and sends CR to him one more time** - this is definitely an issue, checking with desktop.
> 
> @John-44 can you please confirm the requirements for p.2

@MishkaRogachev I assume you are asking about "**The pending CR is shown in the Activity Centre as already read after the CR sending**"?  If this is the question, then the answer is that this is correct: On the contact request sender's side, the pending contact request should be shown in the sender's activity centre in the 'read' state immediately after the contact request has been sent.

@VladimrLitvinenko ^

**Comment by MishkaRogachev** [comment]
Status-go changes moved here: https://github.com/status-im/status-go/pull/3379. @ilmotta probably we can close this PR and open a new one

**Comment by ilmotta** [comment]
> Status-go changes moved here: [status-im/status-go#3379](https://github.com/status-im/status-go/pull/3379). @ilmotta probably we can close this PR and open a new one

:+1: Closing now. As per our conversation yesterday, I'll start integrating with the new changes in the new status-go branch soon. Thanks @MishkaRogachev

**Pull request closed without merging**
