### PR TITLE
Switcher blurred background view

### PR DESCRIPTION
**Pull request by Parveshdhull**
### Summary
PR implements blurred background view for switcher and also allows switcher to draw over status bar in android, same as ios.

status: ready

### CODE REVIEW

**Comment by du82** [comment]
Switcher doesn't cover notification bar

Screenshot_20220727-195004_Status PR

**Comment by Parveshdhull** [comment]
Hi @du64, Thank you very much for finding this issue. Fixed now.

**Comment by du82** [comment]
@Parveshdhull still has a rendering issue
Screenshot_20220731-152514_Status PR

**Comment by Parveshdhull** [comment]
@du64, Please can you check if issue if fixed now? Thank you

**Comment by du82** [comment]
Tested, looks good!
One small thing: Is it possible to have the navigation bar icons switch to being light when the switcher is open, then revert to its previous state when it was closed? In the design it's white when open, and black when closed.

**Comment by Parveshdhull** [comment]
> Is it possible to have the navigation bar icons switch to being light when the switcher is open, then revert to its previous state when it was closed?

Yes, we can change icon colors on the opening switcher, but they will change all at once. So timing the icon change with the switcher opening animation will be a little difficult. 
Ex. Switcher is circular, so if all of them will change color at once then some will be white over switcher, while some which yet not covered by switcher will blend in the white status bar of the home screen.

Still, Thank you very much for this great observation. I will forward your feedback/question to the design team. Thank you

**Comment by du82** [comment]
That's probably out of the scope of this PR, so I'd say this looks good from a UI/UX perspective

**Review by flexsurfer — APPROVED** [review]

**Pull request merged**
