### PR TITLE
fix profile name not displayed on the login page for synced device in the fallback flow

### LINKED ISSUE #21263: Profile name not displayed on the login page for synced device in falback flow
# Bug Report
**Follow up: #21090** 

### Reproduction
1. Device A1 syncs with Device A.
2. Complete the entire fallback flow, but do not confirm pairing on Device A (Device A use Wi-fi, device A1 use mob data).
3. Go to the profile settings on Device A1.
4. Log out of the profile.

#### Expected behavior: 
The profile on Device A1 shows 3 random names. The same name should appear on the login page.

#### Actual behavior:
The profile on Device A1 shows 3 random names. However, no name is displayed on the login page.
йййййй
ццццц

### Additional Information

- Status version: PR build for #21090 
- Operating System: Android, iOS

### PR DESCRIPTION
**Pull request by Parveshdhull**
fixes https://github.com/status-im/status-mobile/issues/21263

### Summary
This PR resolves the issue of missing profile names on the login page for synced devices using the fallback flow.

status-go pr: https://github.com/status-im/status-go/pull/5876

status: ready

### CODE REVIEW

**Review by flexsurfer — APPROVED** [review]

**Comment by Horupa-Olena** [comment]
@Parveshdhull 
Hi! Thanks for your PR!
Can I start test it??

**Comment by Parveshdhull** [comment]
> @Parveshdhull Hi! Thanks for your PR! 

Hi @Horupa-Olena, Thank you for picking the PR.

> Can I start test it??

Yes, please

**Comment by Parveshdhull** [comment]
Just a sec, let me rebase the PRs with latest develop.

**Review by seanstrom — APPROVED** [review]

**Comment by Horupa-Olena** [comment]
@Parveshdhull Thanks for your PR! It looks good.

I have only one question about specific case. My step was:
1. Restore profile and give it new name N1 on Device 1
2. Device 2 try to sync with Device 1 by fallback flow
3. Log out on Device 2 to check bugfix

**Expected results:** 3 random name  shows in login page same as in profile settings

**Actual results:** another third profile name (I guess it can be first name profile before restoring that saving in status-go) shows on login page

https://github.com/user-attachments/assets/cd538037-f232-4443-a60b-b2960ec20e46

If confirm Pair and sync, profile name N1 shows correctly on synced Device 2

Do it expected results? Are we need fixed it?

**Comment by Parveshdhull** [comment]
> another third profile name (I guess it can be first name profile before restoring that saving in status-go) shows on login page

Thank you, @Horupa-Olena, for testing the PR.

So, by "N1," you mean "Android login test," right? In the video, instead of displaying "Android login test," it showed "account3." I’m unclear about where this came from. Do you have the same account recovered somewhere else with the name "account3"? Also, could you please confirm whether you can reproduce this issue consistently, even with different account?

**Comment by Horupa-Olena** [comment]
> Also, could you please confirm whether you can reproduce this issue consistently, even with different account?

I try to reproduce it in two ways:
**For new acccount**
1. Create new account with name "21321" on Device 1
2. Restore this account with new name "Login test" on Device 2
3. Try to sync Device 3 with Device 2 -> on Device 3 show profile name "Moral Jolly Flies" in profile settings (as expected).
4. Log out on Device 3 -> show profile name "Moral Jolly Flies" in login page (as expected)

**For old acccount**
1. Open old account with name "Android" on Device 1
2. Restore this account with new name "Login test 2" on Device 2
3. Try to sync Device 3 with Device 2 -> on Device 3 show profile name "Coordinated Official Arachnid" in profile settings (as expected).
4. Log out on Device 3 -> show profile name "Android" in login page. And this profile name is displayed after re-login until pairing is confirmed
@Parveshdhull Is this enough to confirm the consistency repro of this case?

**Comment by Parveshdhull** [comment]
Thank you, @Horupa-Olena, for the detailed steps. To me, this behavior seems expected. In the video above, I initially thought that "account3" was synced randomly. However, from the reproduction steps, it is clear that the name was synced from one of our devices.

**Comment by Horupa-Olena** [comment]
@Parveshdhull Okay. Thank you. Then I have no reason to hold the PR. You can merge it.

**Pull request merged**
