### PR TITLE
Add the Contract Tests to the mobile CI/CD pipeline

### LINKED ISSUE #18782: Add the Contract Tests to the mobile CI/CD pipeline.
Following on from https://github.com/status-im/status-mobile/pull/18665#issuecomment-1935836005

Add the Contract Tests to the mobile CI/CD pipeline. 

This should be very similar to https://github.com/status-im/status-mobile/pull/18304

Reach out to @siddarthkay if you need any assistance with this 👍  

the make command is `make test-contract`

### PR DESCRIPTION
**Pull request by FFFra**
Fixes #18782

### Summary
This quick PR modifies the JenkinsFile adding Contract Tests to Ci/CD pipeline

### Steps to test
Check Jenkins output here or at https://ci.infra.status.im/job/status-mobile/

### Notes
Tried to run it in parallel with Unit Tests but it was not working

status: ready!

### CODE REVIEW

**Review by siddarthkay — APPROVED** [review]

**Review by J-Son89 — APPROVED** [review]

**Review by smohamedjavid — APPROVED** [review]

**Review by jakubgs — APPROVED** [review]
Time to clean this up a bit.

**Comment by FFFra** [comment]
Can I merge?

**Comment by siddarthkay** [comment]
@FFFra : sure go ahead and merge

**Comment by FFFra** [comment]
Just a note: we are increasing the timeout to 20 minutes because is happening timeout error very frequently. Please let me know if anyone disagree

**Comment by FFFra** [comment]
Add the Contract Tests to the mobile CI/CD pipeline

**Comment by FFFra** [comment]
Add the Contract Tests to the mobile CI/CD pipeline

**Comment by jakubgs** [comment]
Why did you overwrite my changes?

image

I guess you didn't notice them?

**Pull request merged**
