### PR TITLE
fix chat layout breaking when combining normal text with code blocks

### LINKED ISSUE #15575: Layout is broken if using markdown with code
# Bug Report

## Problem 
On Android text is overlaying with the background:
IMAGE 2023-04-04 19:14:20
On IOS all rows after 1 are not visible:
IMAGE 2023-04-04 19:15:53

Also the same issue is reproducible with mentions (they are shifted up and not centered)

### Reproduction

1) Open Status
2) Send in any community text with markdown  (in  `` backticks) in several lines

### Additional Information

- Status version: release 1.22 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by siddarthkay**
fixes #15575

Simulator Screen Shot - iPhone 14 Pro - 2023-04-05 at 18 57 40

status: ready

### CODE REVIEW

**Review by cammellos — APPROVED** [review]

**Review by briansztamfater — APPROVED** [review]

**Comment by churik** [comment]
@siddarthkay 
seeing {:weight :code} at the beginning of each code block
IMAGE 2023-04-05 17:12:21
IMAGE 2023-04-05 17:12:25

**Comment by siddarthkay** [comment]
@churik : ah sorry, I know how to fix it, one sec

**Comment by siddarthkay** [comment]
@churik : fix pushed

**Comment by churik** [comment]
Please, cherry-pick fix to release branch  1.22, thank you!!

**Pull request merged**
