### PR TITLE
Add manual exception reporting to instabug - #4128 #4160

### LINKED ISSUE #4128: Upgrade Instabug to 2.12.0
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a developer and tester, I want to see [crash reports](https://instabug.com/crash-reporting) so that I can debug crashes.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Improvement

*Summary*: Instabug v2.12.0 now has [crash reporting](https://instabug.com/crash-reporting) which can be useful for debugging

#### Expected behavior

Instabug version is 2.12.0

#### Actual behavior

Instabug version is older

### PR DESCRIPTION
**Pull request by debragail**
Added manual exception reporting to error_handler.cljs

Fixes #4128 
Fixes #4160 PR

converted js snippet to cljs

https://docs.instabug.com/docs/react-native-crash-reporting#section-report-exception

try {
      throw new SyntaxError();
    } catch (error) {
      alert(error.name);
      Instabug.reportJSException(error);
    }

<blockquote><div><strong><a href="https://docs.instabug.com/docs/react-native-crash-reporting#section-report-exception">Crash Reporting</a></strong></div><div> In this page, you will find some APIs specific for the crash reporting. In the [**Reports Data** ](react-native-reports-data) section, you can find more information about the information and data sent with each crash report.   If your [**plan**](https://instabug.com/pricing) has crash reporting, cr...</div></blockquote>

### CODE REVIEW

**Comment by debragail** [comment]
@dmitryn my cljs isn't so good please review translation

**Comment by dmitryn** [comment]
@debragail i think we can do that in https://github.com/status-im/status-react/pull/4160 not sure separate PR is needed.

**Comment by goranjovic** [comment]
What's the status of this PR? The commit count doesn't look right and it's a bit stale

**Comment by dmitryn** [comment]
@goranjovic I would close this one as it seems not relevant anymore (linked issues and PRs are already closed).

**Pull request closed without merging**
