### PR TITLE
[Fix #2699] Messages are received in different order then sent

### LINKED ISSUE #2699: Messages are received in different order then sent
[comment]: # (Please replace ... with your information. Remove < and >)

### Description

When user A sends messages in rapid succession to user B, while user B is offline, once user B starts the app and and the messages are received, they are displayed in a wrong order, see the attached screenshot.

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status on device A
- Open Status on device B
- Exchange contact info so A and B are mutual contacts
- Starts 1-1 chat between A and B (doesn't matter who starts it)
- Close the app on device B
- Send couple of messages in rapid succession from device A to device B
- Open status app on device B, wait till messages from A are received and examine their order
screen shot 2017-12-12 at 13 53 14

### PR DESCRIPTION
**Pull request by foopang**
[Fix #2699] Messages are received in different order then sent

I haven't tested it yet but apparently there is a bug in `earliest-clock-value-seen?` function as `@seen` is being filtered by `message-id`, as a result `clock-value` being passed to the function always equals to `clock-value` after sort, the function always returns true.

### CODE REVIEW

**Comment by janherich** [comment]
@foopang we will most probably introduce whole different way of solving the issue of definite message ordering and get rid of the `:pre-receiver` logic altogether (have a look at the recent commits in `experiment/new-protocol-app` branch if you are interested), but I'm fine with this solution if it really solves the problem for now.

**Review by janherich — APPROVED** [review]

**Review by oskarth — APPROVED** [review]
Thanks @foopang! I personally find it a bit difficult to reason about without running this code myself, but if you have tested it and feel confident it works I think let's pass this on to QA. The changes seems clean and local :)

**Comment by annadanchenko** [comment]
Messages are still received in different order if use same steps as in the issue. 
### Steps:
1. device A: Add device B to the contacts
2. device B: in new 1:1 chat with A use Add to contacts link
3. each device send 1 message to see you can see received messages
4. close app on device B
5. device A: send 25 messages in 1:1 chat with device B (1,2,3,4,5... 25)
6. device B: you'll see notifications "You have a new message)
7. After 25 messages are sent from device A: do not close app on device A
8. device B: open app and log in. On Home tab wait till 25 unread counter will be shown next to chat with device A. As soon as it shows "25" open chat and check the message order (should be 1,2,3,4,5...23,24,25)
Currently: 
screenshot_20180227-122203

Also see video below
Log and video (device B: Android phone, Pixel XL, Android 8.1.0): https://app.testfairy.com/projects/4803622-status/builds/7782166/sessions/6/?accessToken=Z-Zfiugrl6vZnIKlBS/UD63MgkY 
Installed PR build 4 on real iPhone 6s, iOS 10.3.3 (device A) and real Pixel XL, Android 8.1.0 (device B)

**Comment by janherich** [comment]
@foopang @oskarth 
I'm afraid the issue here actually can't be solved with any tweaks to receive buffering at all - the whole reason why it was introduced was the expectation that when many messages are received at once, it's the case of offline inboxing kicking in, and relatively short buffer window is enough to sort the incoming messages correctly.
However, the steps described by @annadanchenko actually trigger something else I think - It's the case of user `A` (online the whole time) sending messages to user `B` (offline during the sending, online immediately after that) where re-transmit logic kicks in (https://github.com/status-im/status-react/blob/develop/src/status_im/protocol/web3/delivery.cljs#L195-L209).
And this logic doesn't deliver messages all at once, basically if last message from the 10 sent will be sent 5 seconds after the first (very plausible), then the re-transmission will also happen 5 seconds later, what's even worse, I'm not sure if the `pending-messages` queue maintains correct order - solving such situation with receive buffer would mean very long lived receive buffer (much more then 500ms), clearly not a good solution for instant messenger app.
In my opinion we should abandon the receive buffering for good, take inspiration from `experiment/new-protocol-app` (ordering is solved there for 1-1 chats), make sure that the logic can be adapted to public group chats and port it to develop.
So the question is, @foopang , do you wan't to give it a try ? In case of any questions, I'm ready to help and explain everything necessary.

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/status-im/status-react">status-im/status-react</a></strong></div><div>status-react - a free (libre) open source, mobile OS for Ethereum</div></blockquote>

**Comment by oskarth** [comment]
@janherich While I agree the vector clock and placeholder message approach is better in principle, I don't see the problem in trying to solve it in two different ways at the same time.

> the whole reason why it was introduced was the expectation that when many messages are received at once ... and relatively short buffer window is enough to sort the incoming messages correctly.

I'd like to see logs / numbers that this _isn't_ the case. Offline inboxing uses same mechanism for sending messages like normal ones, so not convinced it isn't solvable in 99% case with this approach. As to why this PR didn't work I don't know, would need to see debug logs to figure this out I think.

That said, if we can get the vector clock + placeholder UI PR in very soon, before offsite, then that'd be amazing! Maybe it makes sense to split the UI placeholder portion into a separate bounty or something?

**Comment by foopang** [comment]
@janherich So it doesn't address the issue. Thanks for explaining why it is not working! I think I will give up on this now as I am still very unfamiliar about the logic behind. I will try to study and follow `experiment/new-protocol-app` later on. This PR can be closed now. Thanks!

**Comment by janherich** [comment]
@oskarth No the offline inboxing doesn't use the same mechanism with same semantics as re-delivery mechanism built in app - with offline inboxing, you request the messages and they are all delivered (almost) instantly by mailbox server, while re-delivery mechanism doesn't do that (because there is a re-try/wait logic attached to *each* message in the pending-messages queue).
I agree that the approach with receive buffer could theoretically work well for most of the cases, but it doesn't play well with the re-try logic implemented in the app, so we would still need changes on protocol layer.

**Pull request closed without merging**
