### PR TITLE
[FIX #1774] Added react-native-camera exception to global handler

### LINKED ISSUE #1774: App crashes if tap several times on photo area when capturing a photo
### Description

*Type*: Bug

*Summary*: App crashes if on Profile image screen tap several times on area with a photo. Can't reproduce on released 0.9.10 version

```
java.lang.NullPointerException: Attempt to invoke virtual method 'android.hardware.Camera$Parameters android.hardware.Camera.getParameters()' on a null object reference
	at com.lwansbrough.RCTCamera.RCTCameraViewFinder.onTouchEvent(RCTCameraViewFinder.java:349)
	at android.view.View.dispatchTouchEvent(View.java:9998)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2839)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2456)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2839)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2456)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2839)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2456)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2839)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2456)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2839)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2456)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2839)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2456)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2839)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2456)
	at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2816)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1848)
	at android.app.Activity.dispatchTouchEvent(Activity.java:3046)
	at com.testfairy.p.q.dispatchTouchEvent(SourceFile:188)
	at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2777)
	at android.view.View.dispatchPointerEvent(View.java:10233)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5397)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5233)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4673)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4726)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4692)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4834)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4700)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4891)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4673)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4726)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4692)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4700)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4673)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7359)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7237)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7198)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7469)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:323)
	at android.os.Looper.loop(Looper.java:143)
	at android.app.ActivityThread.main(ActivityThread.java:7229)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```
#### Expected behavior
nothing happens if tap several times on a picture area
#### Actual behavior

app crashes

### Reproduction
from 00:23 https://app.testfairy.com/projects/4803622-status/builds/6504857/sessions/5/?accessToken=LJdwEpiLsjl/mnBJZ5AHu/ThfhE
- Open Status
- Open drawer
- edit profile picture
- select Capture
- on Profile image screen tap several times (3-4) on the area where your future selfie is shown and move a finger after each tap. if it does not crash then return back and select Capture again to open Profile image. Usually, after 1-2 attempts app crashes. Sometimes it's enough to tap twice, sometimes you need 3 taps and then 2 more.

### Additional Information
* Status version: develop build  0.9.10-69-gf88c3fea+
* Operating System: 
Real device Samsung Galaxy S6, Android 6.0.1

### PR DESCRIPTION
**Pull request by nrakochy**
Fixes #1774 

### Summary:
Explored several options on this, including [fixing the underlying lib](https://github.com/react-native-community/react-native-camera/pull/1009). Ended up adding a work-around to the global Android exception handler.

Please let me know if there is a more preferred way.

Thanks.

status: ready

### CODE REVIEW

**Comment by nrakochy** [comment]
Fixes #1774 

Inadvertently closed (sorry).

**Comment by jeluard** [comment]
It makes sense to have this fixed upstream and included in our codebase. If your PR is not mergedf we can still fork the repo.

There is probably some value in having a more generic mechanism to filter exception Android side (maybe an array of messages to filter?).

Could you validate that when this happen we can still have one photo captured?

**Comment by nrakochy** [comment]
@jeluard Thanks for the note. It looks like there were some changes on `react-native-camera`, so I am going to re-base the PR and go from there. Will also make a `known-exceptions-handler` that is a bit more generic on the global uncaught exception handler and follow-up with you.

**Comment by nrakochy** [comment]
Made the known exceptions a bit more generic and moved the bool outside of the generated UI thread. 

I think(?) I have a working repro of the [issue](https://github.com/nrakochy/react-native-camera/blob/touchEventCrashTest/android/src/main/java/com/lwansbrough/RCTCamera/RCTCameraViewFinder.java#L76), where the MotionEvent is dispatched before camera has completed initialization. 

The problem with the PR is that it is expected behavior to kill the thread on an uncaughtException, which, in this case, is the main background thread for the app. It can leave the app in a bad state. I tried several variations of throwing-and-catching on this handler, and the app did indeed hang at times. 

In spite of the time invested down the Android UncaughtExceptions rabbit hole, I think the best bet may to be fork or simply re-visit a `react-native-camera` PR...

**Comment by nrakochy** [comment]
Opened [new PR](https://github.com/status-im/status-react/pull/3023)

**Pull request closed without merging**
