### PR TITLE
Don't specify `to` when making the request to mailserver.

### PR DESCRIPTION
**Pull request by cammellos**
In some cases (say the clock of the device has drifted) specifying a `to` parameter
is decrimental and might result in missing messages.

We have changed the mailservers to default `to` if not present to `now`,
which should gives us better guarantees.

We also removed the 24 hours limit as now all the requests will be
paginated according to the `limit` parameter.

### Testing

Currently it only works on `staging` and `test` fleet

1) Create a new account
2) Connect to `staging` or `test` fleet
3) Set your clock to -1 hour
4) Join an empty public chat
5) Logout
6) From a different device send a few messages
7) Login and Fetch 24 hours on that chat 

On develop those offline messages won't be fetched, while they should be fetched in this build.

Please do no merge before we update `beta` fleet, I will only do that once tested successfully.

status: ready

### CODE REVIEW

**Review by mandrigin — APPROVED** [review]

**Review by rasom — APPROVED** [review]

**Comment by cammellos** [comment]
just rebased against develop, might help with tests

**Comment by asemiankevich** [comment]
@cammellos would you mind to rebase please?

**Comment by cammellos** [comment]
@asemiankevich , done !

**Comment by asemiankevich** [comment]
so the descirbed scenario works , i can see messages on device which is 1h behind. 
It results in error on beta fleet but seems to be expected, right @cammellos ? 

I want to do more testing here though

**Comment by cammellos** [comment]
@asemiankevich correct, beta fleet has not been updated, so it will throw an error.

**Comment by asemiankevich** [comment]
@cammellos https://ethstatus.testrail.net/index.php?/tests/view/538902 will fail because of 
image

however messaging on test / staging fleet looks good to me. Is there anything else i need to check in this PR ? Above mentioned scenario is also working okay

**Comment by cammellos** [comment]
could you smoke test release app with staging fleet? just to make sure it s
all ok, and we can then upgrade the fleet. Thanks!

**Comment by asemiankevich** [comment]
@cammellos i briefly checked release app, i can chat and transact on staging , looks good to me

**Comment by cammellos** [comment]
@asemiankevich I have deployed the mailservers, could you re-run auto tests please?
Thanks!

**Comment by asemiankevich** [comment]
> @asemiankevich I have deployed the mailservers, could you re-run auto tests please?
> Thanks!

yes sure

**Pull request merged**
