### PR TITLE
wip: check contact request e2e test fix

### PR DESCRIPTION
**Pull request by Parveshdhull**
realted to https://github.com/status-im/status-go/pull/4813

### CODE REVIEW

**Comment by pavloburykh** [comment]
@igor-sirotin @Parveshdhull Thank you for the PR! Please take a look at the issue. Most likely related to https://github.com/status-im/status-go/pull/4813 because I do not reproduce this issue in latest develop. 


### ISSUE 1 App crashes after restore via seed phrase

**Steps:** 

1. Restore user via seedphrase
2. See if app does not crash after restoration

**Actual result:** app crashes. Works fine after relogin. 

[Status-debug-logs - 2024-02-27T111457.656.zip](https://github.com/status-im/status-mobile/files/14417247/Status-debug-logs.-.2024-02-27T111457.656.zip)

https://github.com/status-im/status-mobile/assets/97245802/04ae5327-3fc8-4727-b422-3eea63ecfc34

**Comment by cammellos** [comment]
> @igor-sirotin @Parveshdhull Thank you for the PR! Please take a look at the issue. Most likely related to [status-im/status-go#4813](https://github.com/status-im/status-go/pull/4813) because I do not reproduce this issue in latest develop.
> 
> ### ISSUE 1 App crashes after restore via seed phrase
> **Steps:**
> 
> 1. Restore user via seedphrase
> 2. See if app does not crash after restoration
> 
> **Actual result:** app crashes. Works fine after relogin.
> 
> [Status-debug-logs - 2024-02-27T111457.656.zip](https://github.com/status-im/status-mobile/files/14417247/Status-debug-logs.-.2024-02-27T111457.656.zip)
> 
>  telegram-cloud-document-2-5400192398510799678.mp4

I think we will need the raw logcats for this one if you have them @pavloburykh

**Comment by pavloburykh** [comment]
> I think we will need the raw logcats for this one if you have them @pavloburykh

@cammellos @igor-sirotin here is a logcat

[crashlog_restore.log.zip](https://github.com/status-im/status-mobile/files/14418458/crashlog_restore.log.zip)

```02-27 12:59:42.469  6009     0 E Go      : panic: runtime error: invalid memory address or nil pointer dereference```

**Comment by pavloburykh** [comment]
@igor-sirotin @cammellos I have checked last builds which includes recent go fixes but [ISSUE 1](https://github.com/status-im/status-mobile/pull/19009#issuecomment-1966176347) is still reproducible. Can we at this moment merge current fix as it is because it fixes the main issues with 0 peers and will unblock mobile development. 

And we can continue investigation and fixing [ISSUE 1](https://github.com/status-im/status-mobile/pull/19009#issuecomment-1966176347) separately. WDYT?

**Pull request closed without merging**
