### PR TITLE
Community logo and title are not aligned on the channels screen #17214

### LINKED ISSUE #17214: Community logo and title are not aligned on the channels screen
# Bug Report

### User opens the community for the first time: the title is not aligned
Screenshot 2023-09-07 at 12 15 16

### The user has already viewed the community before: the logo and the title are not aligned
Screenshot 2023-09-07 at 12 15 49

#### Expected behavior

https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?type=design&node-id=10276-409196&mode=design&t=EX0FaWSnPwXybLJa-4

Screenshot 2023-09-07 at 12 20 55

Screenshot 2023-09-07 at 12 21 05

### Reproduction

1. UserA: share a community with UserB
2. UserB: open the community, join it, open it again

### Additional Information

- Status version: nightly 7/09
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by flexsurfer**
fixes #17214

### CODE REVIEW

**Review by ajayesivan — COMMENTED** [review]
LGTM!

**Review by ajayesivan — APPROVED** [review]

**Review by J-Son89 — APPROVED** [review]
looks good, nice one @flexsurfer 💪

**Review by siddarthkay — APPROVED** [review]

**Comment by qoqobolo** [comment]
@flexsurfer LGTM, thanks for the fix!
@Francesca-G could you check this PR, please?

**Review by Francesca-G — APPROVED** [review]
Looks good to me

**Pull request merged**
