### PR TITLE
[Fixes: #16203] Fix delete for me replies images

### PR DESCRIPTION
**Pull request by cammellos**
https://github.com/status-im/status-go/compare/323e02eb...4cde8605

### CODE REVIEW

**Review by ibrkhalil — APPROVED** [review]

**Review by flexsurfer — APPROVED** [review]

**Comment by VolodLytvynenko** [comment]
hi @cammellos Could you rebase the current PR , please? One critical fix https://github.com/status-im/status-mobile/commit/a7ddda40c4667db4f4c4aab50f330831e8274d0c is merged to develop

**Comment by VolodLytvynenko** [comment]
@cammellos please take a look. one blocker issue that prevents us from proceeding with testing is found.

## ISSUE 1: "failed to create bindata migration..." error is shown on login by newly created user
### Steps:
1. Proceed with creation of a new account (user will get stuck on Generating keys screen)
2. Reopen the app
3. Try to login multiaccount
4. Observe an error

### Actual result:
"failed to create bindata migration..." error is shown on login by newly created user

### Device:
Real device: Pixel 7a, Android 13

### logs:
[android_logcat.txt](https://github.com/status-im/status-mobile/files/11905284/android_logcat.txt)

**Comment by cammellos** [comment]
@VladimrLitvinenko I will update the PR and include the fix, I believe that's fixed in status-go already, I'll ping you when ready. Thank you.

**Comment by cammellos** [comment]
@VladimrLitvinenko it should be ready to be tested, thank you

**Comment by VolodLytvynenko** [comment]
Hi, @cammellos thank you for your work. The issue is fixed. PR is ready to be merged

**Pull request merged**
