### PR TITLE
fix: min pwd length for ::multiaccounts.db/password

### LINKED ISSUE #18393: Confirm button becomes enable after user enters 6 characters to the Password field
# Bug Report

## Problem 
[comment]: # (A problem description)
Our app has several places where we enter user's password: login, biometrics settings, creating wallet accounts etc. Since we use validation rule that user's password should contain at least 10 characters we do not need to confuse user by enabling Confirm button after he entered only 6 of them (characters).

#### Expected behavior
Confirm button on Enter Password popup becomes enable after user enters 10 characters

#### Actual behavior
Confirm button on Enter Password popup becomes enable after user enters 6 characters

https://github.com/status-im/status-mobile/assets/147824399/475378ec-5377-4577-88dc-906749a83e4f

### Reproduction

**Precondition**: app installed and user exist

1. Open Status
2. Put 6 characters into Password field

### Additional Information

- Status version: nightly from January,4
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by yqrashawn**
fixes #18393

### UPDATE

This PR is blocked as we do not not have a decision yet about upgrading from the old Status app to a new one. See the comment [here](https://github.com/status-im/status-mobile/pull/18425#issuecomment-1885063577).

### Summary

it's used in status-im.common.standard-authentication.enter-password
to decide if confirm button should be disabled

#### Areas that maybe impacted
legacy add new wallet view (not used anymore?)
places where we enter user's password: login, biometrics settings, creating wallet accounts etc

status: ready

### CODE REVIEW

**Comment by ibrkhalil** [comment]
I think old users had a password created with a minimum length of 6 characters, Should we stop support for them?
CC: @cammellos

**Review by flexsurfer — APPROVED** [review]

**Comment by cammellos** [comment]
@ibrkhalil that might be a good point, we should allow inputting a password of 6 characters when logging in, but prevent when creating an account, less headaches, otherwise we might lock some people out of their account

**Comment by mariia-skrypnyk** [comment]
@ibrkhalil hi!

This is the credentials to restore an old user that was created at the times of 6 character passwords:

general fiscal punch drum crop smile daughter metal name island cliff they

**Comment by pavloburykh** [comment]
> @ibrkhalil that might be a good point, we should allow inputting a password of 6 characters when logging in, but prevent when creating an account, less headaches, otherwise we might lock some people out of their account

@cammellos AFAIK we used to have 6 characters validation only in our old app (that is currently in stores), correct me if I am wrong. Taking into consideration the fact, that after releasing the new app users will need to re-install the app from scratch (not upgrade) I do not see any concern in changing validation on login from 6 to 10 as they will need to recover their users and set up password according to the new 10 chars validation rules.

**Comment by pavloburykh** [comment]
> @ibrkhalil hi!
> 
> This is the credentials to restore an old user that was created at the times of 6 character passwords:
> 
> general fiscal punch drum crop smile daughter metal name island cliff they

@ibrkhalil I don't think that credentials of the old user will help you in anyway, because you are setting a new password every time you restore the user. Maybe I am missing something and you have asked for the old user credentials for some other reason?

**Comment by yqrashawn** [comment]
> users will need to re-install the app from scratch (not upgrade)

If 
1. user need to install the new app
2. old app data won't get migrated to new app
3. no sync feature that sync old encrypted account into new app (any keycard related feature?)
then I think it's safe to set this to 10

@ibrkhalil @cammellos

**Comment by ibrkhalil** [comment]
> > @ibrkhalil hi!
> > This is the credentials to restore an old user that was created at the times of 6 character passwords:
> > general fiscal punch drum crop smile daughter metal name island cliff they
> 
> @ibrkhalil I don't think that credentials of the old user will help you in anyway, because you are setting a new password every time you restore the user. Maybe I am missing something and you have asked for the old user credentials for some other reason?

My point was, If I user did an OTA update from the app store, Will they use the old password validation rules or the new password validation rules, And does this mean we need to force all the users to backup their seed phrases and reinstall the app for it to work?

**Comment by cammellos** [comment]
we actually had a discussion about this today, we don't know yet, so best to hold on with this PR, as we might want to provide an upgrade path

**Comment by pavloburykh** [comment]
> we actually had a discussion about this today, we don't know yet, so best to hold on with this PR, as we might want to provide an upgrade path

@cammellos thanx for the update! 

@yqrashawn I will temporary move this PR to Contributor column until we will have a decision about upgrade. Thank you for your work.

**Comment by flexsurfer** [comment]
feel free to reopen when needed

**Pull request closed without merging**
