### PR TITLE
fix status-bar color for new ui

### LINKED ISSUE #13612: Switcher sometimes shows glitched bar
When opening the switcher, there's a white (or sometimes black) bar at the top

Screenshot_20220701-172544_Status PR

### PR DESCRIPTION
**Pull request by Parveshdhull**
fixes https://github.com/status-im/status-react/issues/13612

status: ready

### CODE REVIEW

**Review by cammellos — APPROVED** [review]

**Comment by qoqobolo** [comment]
@Parveshdhull, thanks for PR!
Noticed one thing in the status bar behaviour:

https://user-images.githubusercontent.com/67952253/178709305-3d521a1b-3a30-4066-8dc7-ff2832a00b9f.mp4

If I open the chat from the activity center the status bar is light grey, but when I open it from the home screen it's white in the chat view.
Is it expected for the time being?

**Comment by Parveshdhull** [comment]
Hi @qoqobolo, Thank you very much for testing the PR and finding this issue.

So, for opening of the chat from the activity center notification, we are still using the navigation1 method, and in navigation1 we didn't pass the status bar color for each screen because it was the same as the home view, all white in light mode and black in dark mode.

But for redesign, we need to pass the status-bar color for each screen separately because as you can see in screenshots, the status bar in the home is light grey while in chat it is white.
image
image


Once the redesign of the activity center will be complete, we will migrate it to navigation 2 and pass the status-bar color accordingly, and that will fix this issue.

**Comment by qoqobolo** [comment]
@Parveshdhull got it! Thanks for detailed clarification as usual and sorry for the endless questions what is expected and what is not 🙏

**Comment by Parveshdhull** [comment]
> @Parveshdhull got it! Thanks for detailed clarification as usual and sorry for the endless questions what is expected and what is not

No problem :), You are right to ask the question, because It is still a bug. It is just that it will be fixed later.

**Pull request merged**
