### PR TITLE
chore: drop wakuv2 fleets, use waku fleets

### PR DESCRIPTION
**Pull request by yakimant**
See https://github.com/status-im/infra-nim-waku/issues/91 for details

Mostly done automatically. Some parts manually.

### CODE REVIEW

**Comment by yakimant** [comment]
@flexsurfer, @cammellos, can you help with review?

**Comment by yakimant** [comment]
@churik, can you please help to test this PR?

**Comment by flexsurfer** [comment]
hey @yakimant still relevant?

**Comment by yakimant** [comment]
Yes, it is relevan, sorry, missed you comment.

@churik, can you help with testing?

**Comment by churik** [comment]
Hello @yakimant !
Sorry for delay.
I'm unclear on the specific user expectations for testing for particular PR. Currently, we're using `shards.test` as the default fleet on all platforms, including for e2e automation, so I have no idea whether wakuv2 even working and where it is used.

If you have more details on the areas that need to be tested, please let me know. 

Thanks!

**Comment by yakimant** [comment]
Actually I don't have any details, I just replace everything wakuv2 with waku.
Also in status-go: https://github.com/status-im/status-go/pull/4933

@cammellos, @richard-ramos, can you please help to understand, what should be tested?

**Review by cammellos — APPROVED** [review]

**Comment by churik** [comment]
Hello!
The e2e results are reviewed, the failed tests are not related to the PR.

Checked that wakuv2 fleets are not available for choosing anymore. 
PR can proceed to the next stage.

**Pull request merged**
