### PR TITLE
[install] Initial checkin of install script for linux.

### LINKED ISSUE #2548: Need an easy setup script for linux boxes
### User Story

As a developer, I want to be able to get going quickly with Status on my Linux machine so that I don't get blocked by trivial things I shouldn't need to worry about before getting my hands really dirty.

### Description

*Type*: Feature

*Summary*: I would love @dbalatero (or any other contributor) to write a bash script for Linux that devs can use to build Status easily.

#### Expected behavior
Easy as 1, 2, 3 to setup and build Status on a Linux box.

#### Actual behavior
Currently, you need to read the wiki and follow a lot of steps with plenty of room for error, which can be discouraging.

### Solution
*Summary*: 

- Farm it out to Open Bounty and let our amazing community get to work!

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.12+
[comment]: # (Android or iOS.)
* Operating System: Linux

### PR DESCRIPTION
**Pull request by charlesg3**
Fixes #2548 

### Summary:

Adds an initial install script for Linux.

### Review notes (optional):
Should be run on a linux box (can test in a VM later)

### Steps to test:
- Create a VM
- run scripts/install.sh

status: wip

to be done: 
- merge with brew install scripts so that there is 1 script that installs per-requesites for OSX and Linux.

### CODE REVIEW

**Comment by dbalatero** [comment]
@charlesg3 before you get any further, I was partway thru this work on a Linux VM tonight, extending the work I did in #2525 for OS X. The Linux script should probably use the same script as the OS X one, if #2525 ends up merging. Wanted to bring this to your attention in case you missed the comment I left on #2548.

**Comment by charlesg3** [comment]
Got it -- thanks for the heads up. Happy to help take on some of that
effort. I noted as well in my PR merging with an OSX script seems sensible.

**Comment by dbalatero** [comment]
@charlesg3 no problem. I think there's a fair amount of work here, as we might want to support a few flavors of Ubuntu. That might be a good place to split+test?

**Comment by charlesg3** [comment]
Cool -- I was thinking of using docker to do some of the testing, with the
added benefit of being able to be a good option for people to also get up
and running if they don't have the right flavor (or perhaps a good windows
solution as well so there's less caveats and moving targets)

**Comment by andytudhope** [comment]
Supporting different flavours and figuring out an easy way to fire up an emulator (not GenyMotion because it's not FOSS) on a Linux machine would be amazing guys - very happy for you 2 to work together on this. One of the things we want to do is extend the SOB contracts to handle PRs with multiple contributors, but for the time being, work together on what you can, the bot will award the bounty to one of you and I will follow up manually with the other.

**Comment by dbalatero** [comment]
@charlesg3 I took some of your setup commands and integrated it into the setup script in a way that supports OS X and Linux.

https://github.com/status-im/status-react/pull/2574

I think the next steps might be for you to extend it with Docker if you want to do that for testing? I'm also looking into how to setup the Android SDK in a non-ridiculous way…

**Comment by pablanopete** [comment]
Really awesome to see a multi-man approach to OSS issues 🍡 @charlesg3 are you already part of our riot? If not I encourage you to join up at https://chat.status.im/#/register and send me a ping @hutch so we can make introductions!

**Comment by dbalatero** [comment]
@pablanopete @charlesg3 we might want to make separate issues for Docker and for getting a sane Android SDK configuration bootstrapped on OS X/Linux as well.

**Comment by charlesg3** [comment]
@dbalatero -- sounds good to me.

**Comment by jeluard** [comment]
@charlesg3 Is this superseded by #2574 ?

**Comment by charlesg3** [comment]
Yes we merged our efforts on that PR.

**Pull request closed without merging**
