### PR TITLE
fix: update status-go to fix panic on logout

### LINKED ISSUE #18202: Random crashes occur during manual logout
Unfortunately there are no clear steps of how to reproduce the crash. Last time I have reproduced it following below steps in the [PR](https://github.com/status-im/status-mobile/pull/18140#issuecomment-1857859652). Maybe something will be clear based on attached logs.  cc @vitvly 

**Steps:** 

1. Recover User A on Device 1 and Device 2. Set different passwords and Enable biometrics for both devices during recovery (not sure if it is important step)
2. Sync Devices
3. Change profile picture on Device 1, add some community on Device 2 (also not sure if this step is important)
4. Perform manual logout on devices
5. See if app has not crashed on logout

**Actual result:** sometimes (both IOS and Android) crash on manual logout. 

[logcat_151223.log.zip](https://github.com/status-im/status-mobile/files/13685497/logcat_151223.log.zip)

[Status-debug-logs (90).zip](https://github.com/status-im/status-mobile/files/13685499/Status-debug-logs.90.zip)

https://github.com/status-im/status-mobile/assets/97245802/fef2f67f-90fa-42df-98c4-b92ba5890ffb

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

### PR DESCRIPTION
**Pull request by richard-ramos**
fixes #18202

status: ready

### CODE REVIEW

**Review by flexsurfer — APPROVED** [review]

**Comment by pavloburykh** [comment]
@richard-ramos thank you for the fix. Tested, ready for merge.

**Comment by richard-ramos** [comment]
I merged the status-go PR. Should I merge this one on mobile or it is not necessary? (dunno what's the process to follow on this repo)

**Comment by pavloburykh** [comment]
> I merged the status-go PR. Should I merge this one on mobile or it is not necessary? (dunno what's the process to follow on this repo)

We need to bump status-go version in mobile so these changes are included in our develop branch. @vitvly could you please help with this?

**Comment by flexsurfer** [comment]
https://github.com/status-im/status-mobile/pull/18254

**Pull request closed without merging**
