### PR TITLE
Quo2: Token Input followup

### LINKED ISSUE #16856: Quo2 Wallet: complete Token Input component
The Token Input component implemented in this PR https://github.com/status-im/status-mobile/pull/16819 is still missing the Network Tag component which has not been merged yet https://github.com/status-im/status-mobile/pull/16747.

### PR DESCRIPTION
**Pull request by OmarBasem**
fixes: https://github.com/status-im/status-mobile/issues/16856

This PR is a follow up to https://github.com/status-im/status-mobile/pull/16819. It adds Network Tag component to Token Input component.

[Designs](https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?type=design&node-id=464-18950&mode=design&t=5HsLFiQwEiqvfXTu-0)

### CODE REVIEW

**Review by flexsurfer — APPROVED** [review]

**Comment by OmarBasem** [comment]
@Francesca-G a design review please :)

**Review by smohamedjavid — APPROVED** [review]

**Review by Francesca-G — COMMENTED** [review]
Here's the [frame](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS/Feedback-for-Mobile?type=design&node-id=3446%3A227419&mode=design&t=PqN01meInlPIXgF0-1) with the design review :)

**Comment by OmarBasem** [comment]
Thanks for your review @Francesca-G, fixed the issues!

**Review by Francesca-G — COMMENTED** [review]
Here's the updated [review](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS/Feedback-for-Mobile?type=design&node-id=3446%3A227419&mode=design&t=PqN01meInlPIXgF0-1) 
Please refer to review 2 :)

**Comment by OmarBasem** [comment]
@Francesca-G regarding the cursor I replied to your comment. 
The alignment should be fixed now

**Review by J-Son89 — APPROVED** [review]

**Review by Francesca-G — APPROVED** [review]

**Pull request merged**
