### PR TITLE
Switcher button in chat is back

### LINKED ISSUE #14668: Switcher buttons missing in chat view
The switcher buttons are missing now

Screenshot_2022-12-29-09-54-39-13_435383e61849826ed84c38f611283930

### PR DESCRIPTION
**Pull request by alwx**
fixes https://github.com/status-im/status-mobile/issues/14668

### Summary

Adds switcher button back to chat (or, to say it more correctly, fixes the positioning of this button because it was already there)

#### Platforms

- Android
- iOS

status: ready

### CODE REVIEW

**Comment by flexsurfer** [comment]
cc @du64

**Review by ilmotta — APPROVED** [review]
Looks good as far as I tested locally.

The only problem I have with this switcher button behavior (not related to this PR) is that once I am on chat screen and I press "Jump to", a new screen is displayed where I can't go back to the chat I was before. If I press the OS back button it closes the app (known and old issue) and if I press the chat button on the bottom switcher it opens the Messages home screen.

@alwx Do you know if we have a Github issue about this problem? The solution is to either fix the OS back button behavior or add a software back button (like the one displayed in 1:1 chat screens, but not being able to go back is a nuisance.

**Comment by qoqobolo** [comment]
Hi @ilmotta!
I assume the `Jump to` screen doesn't have a back button on purpose, because the chats you have visited are saved on this screen.
Therefore, when you go from a chat to the `Jump to` screen, you will see this chat there and you can return to it right from this screen by pressing on the chat card.

The other issue I can see here is that the chat is not persisted on the first opening. 
I.e. if you create a new community and hit `Jump to`, this card won't be there. For the community card to appear on the screen, you need to open that chat again from the chat screen.


https://user-images.githubusercontent.com/67952253/210815118-58000ef9-8221-4b65-8505-7c5b8685a4eb.mp4


I was just about to clarify this thing and decide if we want to fix it with @Parveshdhull here: [Persist switcher cards](https://github.com/status-im/status-mobile/pull/14701)

So, @ilmotta could you confirm that persisting the chat cards will solve the problem you describe?
> a new screen is displayed where I can't go back to the chat I was before

Or I misunderstood you?

---
UPD:
> The other issue I can see here is that the chat is not persisted on the first opening.
I.e. if you create a new community and hit Jump to, this card won't be there. For the community card to appear on the screen, you need to open that chat again from the chat screen.

Responded [here](https://github.com/status-im/status-mobile/pull/14701#issuecomment-1372385347)

**Comment by Parveshdhull** [comment]
> Looks good as far as I tested locally.
> 
> The only problem I have with this switcher button behavior (not related to this PR) is that once I am on chat screen and I press "Jump to", a new screen is displayed where I can't go back to the chat I was before. If I press the OS back button it closes the app (known and old issue) and if I press the chat button on the bottom switcher it opens the Messages home screen.
> 
> @alwx Do you know if we have a Github issue about this problem? The solution is to either fix the OS back button behavior or add a software back button (like the one displayed in 1:1 chat screens, but not being able to go back is a nuisance.

Hi @ilmotta, This is expected behavior as the shell is the base layer on which all applications like messaging, and communities will run. So if we press back there, it will just close.

**Review by Parveshdhull — APPROVED** [review]
lgtm, thank you for fixing it.

**Comment by Parveshdhull** [comment]
> Hi @ilmotta, This is expected behavior as the shell is the base layer on which all applications like messaging, and communities will run. So if we press back there, it will just close.

You can think shell as a windows desktop and the jump-to button as a minimize button, which minimizes corresponding applications into a card. You can open that window back from shell cards (same as the Alt-tab feature) or manually from the chat screen.

**Comment by ilmotta** [comment]
@qoqobolo, @Parveshdhull, thanks for the explanations.

I understand the reasoning now and it makes more sense.

But still, the OS back button behavior is questionable. But it's okay by me, let's let's see how real users react to this behavior. Perhaps it's going to be just fine!

**Comment by du82** [comment]
It crashes for me

https://user-images.githubusercontent.com/65834069/210842248-c57d79f3-0219-4c86-877b-0f1568af37b1.mp4

**Comment by flexsurfer** [comment]
cc @qoqobolo

**Comment by churik** [comment]
@du64 
is there a  chance that you have another PR build installed and installed this on top?
Can I ask you to reinstall it and create a fresh account?

**Comment by cammellos** [comment]
@du64 could you give us the logs?

if you connect it to your laptop, make sure it has access, and run `adb logcat` (you can redirect the output to a log file, something like `adb logcat > /tmp/crash-log.txt`), and replicate, it would be very helpful.

Thanks!

**Comment by qoqobolo** [comment]
> It crashes for me

Tested on several Android devices (on fresh builds) with saved password, all types of chats and data, and wasn't able to reproduce the crash.
So yeah, please try to reinstall the PR build and if the issue is still reproducible, share logs.
Thank you.

**Comment by cammellos** [comment]
@du64 please try to replicate on this build, don't reinstall, better first to understand what kind of crash it is, it might be state-based and not related to installing over another build.

**Comment by du82** [comment]
> @du64 please try to replicate on this build, don't reinstall, better first to understand what kind of crash it is, it might be state-based and not related to installing over another build.

I cant connect my laptop with my phone for some reason, and have been relying on the prebuilt APKs

**Comment by alwx** [comment]
How's is it going with the testing? Can I merge this PR already?

**Comment by flexsurfer** [comment]
cc @qoqobolo

**Comment by qoqobolo** [comment]
> How's is it going with the testing? Can I merge this PR already?

The PR has been tested and no issues have been found. 
But the merge has been delayed due to an issue that @du64 faced.

@du64 can you clarify, just to make sure: you installed this PR build on top of another PR that has already been installed on your device, is this correct?
Also, can you tell us what device you're using, please?


> I cant connect my laptop with my phone for some reason, and have been relying on the prebuilt APKs

@cammellos should @du64 try to reinstall a fresh build then?
We could try to investigate this issue later, but we don't have enough details atm.

**Comment by flexsurfer** [comment]
@qoqobolo looking at the code, @du64 issues not related to this PR 100%, most likely its develop

**Comment by flexsurfer** [comment]
i suggest to merge this PR

**Comment by qoqobolo** [comment]
> i suggest to merge this PR

I agree.
I believe @cammellos's point was to get logs while the issue is being reproduced to rule out the possibility of a state-based issue. 
But since we can't get the logs, there's no point in blocking PR.

@du64 please let us know if you run into this in the future.
We'll also try to figure it out.

@alwx thanks for your work and waiting!
PR can be merged.

**Pull request merged**
