### PR TITLE
Pull images from status-go

### LINKED ISSUE #16885: Images in replies are not displayed in AC
# Bug Report

## Problem 

Screenshot 2023-08-04 at 15 18 59

#### Expected behavior
https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?type=design&node-id=599-22025&mode=design&t=EwtL1KId2dSfwRif-0

#### Actual behavior
No images are displayed 

### Reproduction

1. UserA and UserB: join a community
2. UserA: send a message, close the chat
3. UserB: reply to the message with an image
4. UserA: check the notification in AC

### Additional Information

- Status version: nightly 4/08
- Operating System: Android, iOS

### Note
Displaying images in AC has also not yet been implemented on Desktop (https://github.com/status-im/status-mobile/issues/16800#issuecomment-1655874343)

### PR DESCRIPTION
**Pull request by cammellos**
Fixes: #16885

Images were not "prepared" before being sent to the frontend.

status-go PR: https://github.com/status-im/status-go/pull/3875

https://github.com/status-im/status-go/compare/57e64122...4f413ab1

### CODE REVIEW

**Review by ibrkhalil — APPROVED** [review]

**Review by qfrank — APPROVED** [review]

**Comment by VolodLytvynenko** [comment]
Hi @cammellos Thank you for the PR. The fix in the PR works and the image is displayed in the AC after the reply is sent.

Nevertheless, I'm uncertain about the complete list of features that should be done within the scope of this PR.  If these reported issues are included within the scope of this PR, kindly address them. If not, the PR can  be merged

## ISSUE 1: Only one image is shown in AC if the album is sent in the reply message
### Steps to reproduce:
1. User_A sends a reply in a community or group with an album.
2. User_B checks the AC

### Actual result:
One image is shown in AC
image

### Expected result:
The album images are shown in AC after the album is sent
image

https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?type=design&node-id=13336-165824&mode=design&t=OJ19Y2XS9VJFzJhJ-0

**Comment by VolodLytvynenko** [comment]
## ISSUE 2: The text is not shown in AC if reply is sent with image and with text

### Steps to reproduce:
1. User_A sends a reply in a community or group with both an image and text.
2. User_B checks the AC

### Actual result:
The text that was included in the reply is not displayed in the AC. Only image is shown
image

### Expected result:
The AC should display both the image and the accompanying text in the reply.
image
https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?type=design&node-id=13336-165824&mode=design&t=OJ19Y2XS9VJFzJhJ-0

**Comment by VolodLytvynenko** [comment]
## ISSUE 3: Image not displayed in AC when sent with mention

### Steps to Reproduce:
1. User_A sends a message containing an image and a mention.
2. User_B checks the AC.

### Actual Result:
The image that was sent with the mention is not displayed in the AC.
image

### Expected result:
Image is shown in AC when mention is sent
image

**Comment by cammellos** [comment]
@VolodLytvynenko thank you, if it's ok, I will merge this, and address the others in a separate issue, as they are slightly different and might require different fixes.
Thank you

**Comment by VolodLytvynenko** [comment]
> @VolodLytvynenko thank you, if it's ok, I will merge this, and address the others in a separate issue, as they are slightly different and might require different fixes. Thank you

@cammellos Thank you. PR can be merged

**Comment by cammellos** [comment]
@VolodLytvynenko thanks, I had to rebase status-go, could you please re-run e2e on the last build when ready? after that I can merge.

**Comment by VolodLytvynenko** [comment]
> @VolodLytvynenko thanks, I had to rebase status-go, could you please re-run e2e on the last build when ready? after that I can merge.

Sure. Triggered e2e run. I let you know the result

**Comment by VolodLytvynenko** [comment]
@cammellos e2e tests are passed. PR can be merged

**Pull request merged**
