### PR TITLE
Fix Add Contact crash

### LINKED ISSUE #12872: App crashes on processing new messages in 1-1 chat
# Bug Report

## Problem 
When user opens a new message in the activity center, the app crashes. And after re-login keeps crashing after couple of seconds.
**Blocks around 40% e2e**
Appeared on nightly 02.12.21, it is not presented on nightly 01.12.21
#### Expected behavior
app doesn't crash

#### Actual behavior
app crash 

### Reproduction

From e2e:
1) User A: sens User B a message
2) User B: tap on Activity center

### Additional Information

- Status version: nightly 02.12.21 
- Operating System: Android, IOS
Example of log: [test_send_non_english_message_to_newly_added_contact_on_different_networks_geth1 (3).log](https://github.com/status-im/status-react/files/7641117/test_send_non_english_message_to_newly_added_contact_on_different_networks_geth1.3.log)

### PR DESCRIPTION
**Pull request by vitvly**
Fixes #12872

### CODE REVIEW

**Review by flexsurfer — APPROVED** [review]

**Comment by churik** [comment]
why another commit appeared @siphiuel ?

**Comment by vitvly** [comment]
@churik changed it to point to status-go tag instead of branch.

**Comment by churik** [comment]
@siphiuel is it the same or we should launch e2e one more time?

**Comment by vitvly** [comment]
Tag included 2 more commits with waku v2 changes, the contact crash fix is unchanged.

**Pull request closed without merging**
