### PR TITLE
fix_: no log file generated after set log level

### LINKED ISSUE #20944: Debug logs are absent despite DEBUG log level is enabled in release 2.32 builds
**Steps:** 

1. Install release 2.32 type of build
2. Create/recover a user
3. Change log level to DEBUG (Profile - Advanced - Log level - DEBUG)
4. Download the logs 
5. Check if there are debug logs in downloaded files
6. Check if geth log is there

**Actual result:** geth.log is absent at all. There are not debug logs in Status log file. 

Example of logs 

[logs (54).zip](https://github.com/user-attachments/files/18095267/logs.54.zip)

**Expected result:** geth.log should be in log folder. all log files should contain debug logs. 

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

### PR DESCRIPTION
**Pull request by qfrank**
fixes #20944

For details, pls see relate status-go [PR](https://github.com/status-im/status-go/pull/6202)

#### Platforms

- Android
- iOS

status: ready

### CODE REVIEW

**Review by ilmotta — APPROVED** [review]

**Review by flexsurfer — APPROVED** [review]

**Review by Parveshdhull — APPROVED** [review]

**Comment by pavloburykh** [comment]
@qfrank thanks for the PR. Please take a look at the issues

### ISSUE 1 Cannot login after switching log level to TRACE

**Steps:** 

1. Login the acccount
2. Change log level to Trace
3. Try to login 

**Actual result:** I get `wrong password` error despite password is correct. 

In Status log I see

`2024-12-12T12:36:47.287Z DEBUG [status-im.contexts.profile.login.events:156] - [signals] node.login error failed to setup log settings: unrecognized level: "TRACE"
`
[logs (53).zip](https://github.com/user-attachments/files/18111629/logs.53.zip)

https://github.com/user-attachments/assets/c1f8d520-89d4-42c4-af7b-1faad0ecd8e5

**Comment by churik** [comment]
@ilmotta 
may be we can skip this one than? as we do not collect logs from users anyway

**Comment by ilmotta** [comment]
> may be we can skip this one than? as we do not collect logs from users anyway

@churik I still consider going to 2.32.0 without logs quite bad. It's not just external users, but internal CCs using the public build won't be able to share anything, and nasty bugs may appear.

We can postpone a little bit this PR and try to do a 2.32.1 release very soon. It's a calculated risk we can take.

**Comment by qfrank** [comment]
> @qfrank thanks for the PR. Please take a look at the issues
> 
> ### ISSUE 1 Cannot login after switching log level to TRACE
> **Steps:**
> 
> 1. Login the acccount
> 2. Change log level to Trace
> 3. Try to login
> 
> **Actual result:** I get `wrong password` error despite password is correct.
> 
> In Status log I see
> 
> `2024-12-12T12:36:47.287Z DEBUG [status-im.contexts.profile.login.events:156] - [signals] node.login error failed to setup log settings: unrecognized level: "TRACE" ` [logs (53).zip](https://github.com/user-attachments/files/18111629/logs.53.zip)
> 
>  telegram-cloud-document-2-5393602003123331792.mp4

zap log doesn't support `trace`, can we just remove it on the side of frontend? @ilmotta cc @osmaczko

**Comment by ilmotta** [comment]
> zap log doesn't support `trace`, can we just remove it on the side of frontend? @ilmotta cc @osmaczko

@qfrank the `timbre` library we use in ClojureScript already doesn't support the same log levels as what's used in status-go. I faced this yesterday while experimenting with different log levels (e.g. in status-go there's _some_ support for `CRIT` (although the json tag validation doesn't allow this level to go through in status-go).

With that in mind, I think it's perfectly reasonable to remove support for `trace` in Advanced Settings (a UI only change). We only have one `trace` call in status-mobile to log the signal payload (which can be large).

**Comment by ilmotta** [comment]
@qfrank @pavloburykh I changed both the mobile PR and status-go PR to be based off of their respective release branches. This way, if these PRs are merged, the changes will go to release builds and then we need to cherry-pick onto `develop`. I hope this helps with testing.

A reminder that if somebody merges this mobile PR, merge first status-go PR and then update this PR's `status-go-version.json` to point to the updated `release/7.1.x` branch in status-go.

**Comment by pavloburykh** [comment]
> @qfrank @pavloburykh I changed both the mobile PR and status-go PR to be based off of their respective release branches. This way, if these PRs are merged, the changes will go to release builds and then we need to cherry-pick onto `develop`. I hope this helps with testing.
> 
> A reminder that if somebody merges this mobile PR, merge first status-go PR and then update this PR's `status-go-version.json` to point to the updated `release/7.1.x` branch in status-go.

Thank you @qfrank @ilmotta PR is ready for merging into release branch and cherrypicking onto develop. cc @alwx

**Comment by ilmotta** [comment]
@pavloburykh I added the label `Tested - OK`. Is that correct?

**Comment by ilmotta** [comment]
FYI @alwx According to this comment https://github.com/status-im/status-go/pull/6202#pullrequestreview-2502170310 we shouldn't bring this PR directly into status-mobile `develop`, so for the moment, nothing else to do with this PR. Already merged onto the mobile release branch.

**Comment by pavloburykh** [comment]
> @pavloburykh I added the label `Tested - OK`. Is that correct?

oh, my bad @ilmotta, sorry I have forgotten to add it. Thanks for adding.

**Pull request merged**
