### PR TITLE
chore: bump status-go

### PR DESCRIPTION
**Pull request by osmaczko**
run e2e for: https://github.com/status-im/status-go/pull/5438

### CODE REVIEW

**Comment by churik** [comment]
@osmaczko can you rebase it and try one more time? 
The builds failed.

**Comment by pavloburykh** [comment]
Hey @osmaczko! Thanks for the PR. 

E2E run has caught a [crash](https://app.eu-central-1.saucelabs.com/tests/33c2108236d64efa9b48ccdac28b4145?auth=2229c93f877da7fb0d6b21f055a694c3#82) while user was logged in the account. 

Please check the logs below. 

[test_group_chat_offline_pn_geth3.log.zip](https://github.com/user-attachments/files/16078110/test_group_chat_offline_pn_geth3.log.zip)

[logcat (11).log.zip](https://github.com/user-attachments/files/16078119/logcat.11.log.zip)

**Comment by pavloburykh** [comment]
> E2E run has caught a [crash](https://app.eu-central-1.saucelabs.com/tests/33c2108236d64efa9b48ccdac28b4145?auth=2229c93f877da7fb0d6b21f055a694c3#82) while user was logged in the account.

### UPDATE:

@osmaczko I have checked logcat and I see

```07-02 14:22:22.627  5220     0 E Go      : panic: enode: can't sign record: record bigger than 300 bytes```

Looks like it should have been fixed already by https://github.com/status-im/status-go/pull/5446

Could you please rebase status go branch to include this fix and rebase status mobile as well? After that I will perform another run. Thank you!

**Comment by osmaczko** [comment]
@pavloburykh thanks for looking into this. I've just rebased :+1:

**Comment by osmaczko** [comment]
@pavloburykh there are plenty of tests failed, is it something caused by this PR or considered as not stable in general? For instance, I don't see any correlation of my changes with `test_1_1_chat_push_emoji` :thinking:

**Comment by pavloburykh** [comment]
> @pavloburykh there are plenty of tests failed, is it something caused by this PR or considered as not stable in general? For instance, I don't see any correlation of my changes with `test_1_1_chat_push_emoji` 🤔

@osmaczko this time tests have failed because of the issues on our sessions provider side, so failures are not PR related. 

Based on previous run, most of the failures were because of crash (not PR related) which should be fixed here https://github.com/status-im/status-go/pull/5446

So I believe we do not need to block this PR anymore, ready for merge. Mobile PR can be closed I guess. Thank you.

**Comment by osmaczko** [comment]
> > @pavloburykh there are plenty of tests failed, is it something caused by this PR or considered as not stable in general? For instance, I don't see any correlation of my changes with `test_1_1_chat_push_emoji` 🤔
> 
> @osmaczko this time tests have failed because of the issues on our sessions provider side, so failures are not PR related.
> 
> Based on previous run, most of the failures were because of crash (not PR related) which should be fixed here [status-im/status-go#5446](https://github.com/status-im/status-go/pull/5446)
> 
> So I believe we do not need to block this PR anymore, ready for merge. Mobile PR can be closed I guess. Thank you.

Thanks :pray:

**Pull request closed without merging**
