### PR TITLE
Fix #3145 Update Ethereum to Ether asset name

### LINKED ISSUE #3145: Update Ethereum to Ether asset name
### Description

*Type*: Bug

*Summary*: We want to use `Ether` in asset name 

#### Actual behavior

image

### Reproduction

- Open Status
- Go to Manage assets on wallet tab

### Additional Information
* Status version: latest develop
* Operating System: Android, iOS

### PR DESCRIPTION
**Pull request by hanwencheng**
fixes #3145 

### Steps to test:
- Open Status
- Open Wallet
- Open Send Transaction

status: ready

### CODE REVIEW

**Comment by oskarth** [comment]
@hanwencheng Thanks for your contribution!

**Review by oskarth — APPROVED** [review]

**Comment by oskarth** [comment]
Small change, moving to MERGE. Reminder to self: keep issue open so QA can verify in develop.

**Comment by oskarth** [comment]
Moving to TO TEST by request from QA.

**Review by pedropombeiro — APPROVED** [review]

**Comment by asemiankevich** [comment]
Branch: hanwencheng:bug/#3145
Android: https://i.diawi.com/H4sWj1
iOS: https://i.diawi.com/sUbdZ3

Asset name is updated to `Ether` both for Send and Receive screens.

**Pull request merged**
