### PR TITLE
[#21205] Update metadata for F-Droid

### LINKED ISSUE #21205: Update application page metadata for F-Droid
# Problem

The Status' about page in F-Droid https://f-droid.org/en/packages/im.status.ethereum/ should match other app stores. ~We should try to merge the updates in `status-mobile` approximately at the same time as the merge request in Gitlab is merged~ https://gitlab.com/fdroid/fdroiddata/-/merge_requests/15445 In future issues updating F-Droid we must update the repo assets before merging the merge request.

## Implementation

According to the official docs https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/, we merely need to update assets and text files in our own repo, at `fastlane/metadata/android`.

> Metadata from the repository is copied to the F-Droid repo automatically (thus no merge requests are needed)

> F-Droid will only use metadata files from the latest release. This means that fdroidserver will check out the latest version it knows and scan the repository at the state of that version for metadata files.

## Localization

Only use the languages defined in https://www.notion.so/Translations-ccc6b1532c0441e1821d6202dacee349. Delete language directories we are not supporting in `fastlane/metadata/android/`.

**Product description**: https://www.notion.so/Translations-ccc6b1532c0441e1821d6202dacee349
**Product title**: `Status`
**Product subtitle**: `Crypto Wallet & Private Messenger` (ping @ilmotta for the translations)
**Assets**: https://www.figma.com/design/skL9NPo713hUNE3UkBKDML/Assets?node-id=3020-12165&node-type=CANVAS&t=faAuY1S7IFw6HSUs-0

## Resources

- https://monitor.f-droid.org/builds/needsupdate
- https://monitor.f-droid.org/builds

### PR DESCRIPTION
**Pull request by ulisesmac**
fixes #21205

### Summary

Changes in this PR:

1. Remove unsupported languages
~~2. Rename folders to match Notion language names: `ar` -> `ar-SA` and `uk`->`uk-UA`~~ (reverted)
3. Update assets for all languages:
    - The aspect ratio of previous images doesn't match the new ones, so the previous resolution is 
      `1284 x 2568` and the picked for the new ones is `1440 x 2560`.

status: ready

### CODE REVIEW

**Comment by ulisesmac** [comment]
@ilmotta Could you please tell me if the changes `2` and `3` listed in the description are fine?

**Review by jakubgs — APPROVED** [review]

**Comment by licaon-kter** [comment]
there's no reason to add English screenshots to other languages. Nor duplicate the other like featureGraphic and icon

If images are missing English ones are used by default, afaik

**Comment by ulisesmac** [comment]
> there's no reason to add English screenshots to other languages. Nor duplicate the other like featureGraphic and icon
> 
> If images are missing English ones are used by default, afaik

@licaon-kter Thank you. I've fixed the duplicates

**Comment by ilmotta** [comment]
@ulisesmac, the images seem too large for our repo. They will probably shrink significantly if you use the recently merged script `scripts/compress_image.sh`. Could you try it and see if you get images that look similar in quality? You might even want to play and reduce the quality in the `magick` command, which is currently set at 100.

**Comment by ilmotta** [comment]
> @ilmotta Could you please tell me if the changes `2` and `3` listed in the description are fine?

@ulisesmac:

> Rename folders to match Notion language names: ar -> ar-SA and uk->uk-UA

Unfortunately I'm not sure as well. But I found this, which suggests we should perhaps prefer to keep `ar`, and not the country variations:

> First and foremost, Android must [already support](https://android.googlesource.com/platform/frameworks/base/+/master/core/res/res/values/locale_config.xml) the specific language and locale you want to add. We cannot work with languages that Android and the SDK do not support, the tools simply break down. Next, if you are considering adding a country-specific variant of a language (e.g. de-AT), first make sure that the main language is well maintained (e.g. de). Your contribution might be useful to more people if you contribute to the existing version of your language rather than the country-specific variant.
>
> -- https://f-droid.org/docs/Translation_and_Localization/

> The aspect ratio of previous images doesn't match the new ones

I couldn't find anything in F-Droid docs, but because Android phones vary a lot in aspect ratio, it's probably fine that we are slightly changing them.

**Comment by ulisesmac** [comment]
> @ulisesmac, the images seem too large for our repo. They will probably shrink significantly if you use the recently merged script `scripts/compress_image.sh`. Could you try it and see if you get images that look similar in quality? You might even want to play and reduce the quality in the `magick` command, which is currently set at 100.


@ilmotta 
Weird that our script created slightly heavier images (added around 200KB).

Now I compressed the images, they look identical IMO, I compressed them to get 90% of their quality, previously our heavier image was 1.45MB and now it is 450 KB :partying_face: 

LMK if any other change is needed.

**Comment by ulisesmac** [comment]
> > @ilmotta Could you please tell me if the changes `2` and `3` listed in the description are fine?
> 
> @ulisesmac:
> 
> > Rename folders to match Notion language names: ar -> ar-SA and uk->uk-UA
> 
> Unfortunately I'm not sure as well. But I found this, which suggests we should perhaps prefer to keep `ar`, and not the country variations:
> 
> > First and foremost, Android must [already support](https://android.googlesource.com/platform/frameworks/base/+/master/core/res/res/values/locale_config.xml) the specific language and locale you want to add. We cannot work with languages that Android and the SDK do not support, the tools simply break down. Next, if you are considering adding a country-specific variant of a language (e.g. de-AT), first make sure that the main language is well maintained (e.g. de). Your contribution might be useful to more people if you contribute to the existing version of your language rather than the country-specific variant.
> > -- https://f-droid.org/docs/Translation_and_Localization/
> 
> > The aspect ratio of previous images doesn't match the new ones
> 
> I couldn't find anything in F-Droid docs, but because Android phones vary a lot in aspect ratio, it's probably fine that we are slightly changing them.

Done :+1:

**Review by ilmotta — APPROVED** [review]
LGTM, let's go F-Droid!

**Comment by licaon-kter** [comment]
Also note, these will be used by the next release that includes them. They won't magically appear in F-Droid on merge. ;)

**Comment by ilmotta** [comment]
> Also note, these will be used by the next release that includes them. They won't magically appear in F-Droid on merge. ;)

> F-Droid will only use metadata files from the latest release. This means that fdroidserver will check out the latest version it knows and scan the repository at the state of that version for metadata files.
>
> -- https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/

@licaon-kter, my mistake on that. From the docs I had the impression the repo would be scanned for the metadata every so often because I read the word "latest" carelessly, but of course, in retrospect, makes no sense. The next release should happen in less a month from now, well 🤷🏼

**Pull request merged**
