### PR TITLE
feature #6239 - showing native currency symbol differently for non-ma…

### LINKED ISSUE #6239: Allow native currencies to be displayed differently on different network
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user I want to be able to see the actual native currency name when I use a side chain.
As a user I may want to have a clear distinction between mainnet ether and testnet one.

### Description

*Type*: Feature

*Summary*: The native currency on Ethereum netwoirks in called Ether and displayed with ETH symbol. Some Ethereum-based sidechains chose different names for their native currencies. To avoid any confusion, we want to optionally display name, logo and symbol of the native currency differently depending on the currently selected network.

### PR DESCRIPTION
**Pull request by goranjovic**
fixes #6239

### Summary:

Allows us to set different name, displayed symbol and logo icon for native currency of other chains.E.g. we can now display native currency on Ropsten as "Ropsten Ether" with "ETHro" as the symbol as opposed to just "Ether" and "ETH".

The main reason for this functionality is to be able to correctly display native currencies in sidechains. 

#### Areas that maybe impacted (optional)
**Functional**
- 1-1 chats
- wallet / transactions
- dapps / app browsing
- networks

### Steps to test:
On each network:
- Send a transaction via chat, wallet and a dapp
- Receive a transaction via chat and wallet
- Check transaction history

On each screen Ether is supposed to be displayed like this:

For mainnet:
Name: Ether
Symbol: ETH
Icon: ethereum icon with round border

For ropsten:
Name: Ropsten Ether
Symbol: ETHRO (or ETHro)
Icon: ethereum icon without round border

For rinkeby:
Name: Rinkeby Ether
Symbol: ETHRI (or ETHri)
Icon: ethereum icon without round border

Places where this is mentioned: main wallet screen, wallet send, request, advanced settings (where you set gas info), chat messages for chat transactions, transaction history. (Let me know if I missed any spots)

status: ready

### CODE REVIEW

**Comment by goranjovic** [comment]
screenshot-2018-10-11_15 34 12 689

**Review by dmitryn — APPROVED** [review]

**Review by flexsurfer — APPROVED** [review]

**Comment by annadanchenko** [comment]
@goranjovic  On Ropsten ETH instead of ETHro is shown on 2 screens:
Transaction Fee

Select asset (Wallet -> Send transaction -> Asset field)

**Comment by goranjovic** [comment]
@annadanchenko good catch, I'll push the fix for that and the conflict shortly

**Comment by goranjovic** [comment]
@annadanchenko pushed the fix for both items and the conflict

**Comment by annadanchenko** [comment]
@goranjovic sorry missed one more screen (Transaction history, Gas price and Fee show ETH instead of ETHri)

**Comment by goranjovic** [comment]
@annadanchenko pushed the fix

**Comment by annadanchenko** [comment]
@goranjovic @jakubgs after 4 hours build is still pending. Can we fix it, please?
screen shot 2018-10-16 at 18 26 21

**Comment by goranjovic** [comment]
@annadanchenko I tried to restart it a few times after it failed, but now it just seems stuck or maybe just very very slow.

**Comment by annadanchenko** [comment]
@goranjovic recipient of the "rinkeby ETH" in 1:1 chat sees ETH/ETHro if his network is not on Rinkeby. Expected: recipient of ETHri can see ETHri in 1:1 chat
Recipient is on Mainnet and gets ETHri, currently ETH is shown in 1:1 chat
screenshot_20181016-185059
Steps:
1. Recipient is on mainnet
2. Sender is on Rinkeby and sends 0.01 ETHri in 1:1 chat
3. As recipient, check sent message and currency shown (expected: 0.01 ETHri and rinkeby network)

Note: for request messages expected ETH currency is shown even if recipient is on another network. E.g. if request is sent from Ropsten then recipient on Mainnet sees "0.05 ETHro" in 1:1 chat, so works fine

**Comment by annadanchenko** [comment]
@goranjovic @jakubgs for some reason there is no diawi link for iOS in https://github.com/status-im/status-react/pull/6260#issuecomment-430616048 Can you fix it, please?

**Comment by annadanchenko** [comment]
@goranjovic previous bug is fixed ok for send in 1:1 chat. 
But if I send Request from Wallet (Wallet-> Receive transaction) then sent request message in 1:1 chat always shows ETH instead of ETHri or ETHro for both recipient and sender:
screenshot_20181017-161759

Steps:
1. Sender is in Ropsten, recipient is in Rinkeby
2. Sender: Wallet-> Receive Transaction -> Send transaction request -> specify recipient and 13 ETHro and send
3. On both ends: check 1:1 chat with request message. It should show 13 ETHro

**Comment by goranjovic** [comment]
^ this one is a re-run with ios included, ignore it.

**Comment by goranjovic** [comment]
@annadanchenko pushed the fix for request from wallet.

**Pull request merged**
