### PR TITLE
nix: upgrade nixpkgs to latest nixos-unstable

### PR DESCRIPTION
**Pull request by jakubgs**
Notable upgrades:

* Go `1.17.11` to `1.18.6`
* NodeJS `16.15.0` to `16.17.1`
* Clojure `1.11.1.1139` to `1.11.1.1165`
* Ruby Gem `3.2.26` to `3.3.20`
* Bundler `2.3.9` to `2.3.22`
* Git `2.36.1` to `2.37.3`
* Curl `7.83.1` to `7.85.0`
* OpenSSL `1.1.1o` to `3.0.5`
* PatchELF `0.14.5` to `0.15.0`
* Android SDK Platform Tools `33.0.1` to `33.0.2`

### CODE REVIEW

**Review by audriu — APPROVED** [review]

**Comment by jakubgs** [comment]
I'm holding off on merging this until the `1.20.0` release is out.

**Comment by jakubgs** [comment]
Rebased and refreshed with newer `nixpkgs` version.

**Comment by jakubgs** [comment]
I found this error:
```
Failed to construct transformer:  Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:130:10)
    at stableHash (/build/node_modules/metro-cache/src/stableHash.js:19:8)
    at JsTransformer.getCacheKey (/build/node_modules/metro/src/JSTransformer/worker.js:471:7)
    at getTransformCacheKey (/build/node_modules/metro/src/DeltaBundler/Transformer/getTransformCacheKey.js:39:29)
    at new Transformer (/build/node_modules/metro/src/DeltaBundler/Transformer.js:147:28)
    at /build/node_modules/metro/src/Bundler.js:54:29
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
```
Caused by [Node 16.17.0](https://github.com/nodejs/node/releases/tag/v16.17.0) upgrade. We need to set `NODE_OPTIONS="--openssl-legacy-provider"` to avoid this [issue](https://github.com/vercel/next.js/issues/30078).

**Comment by jakubgs** [comment]
Apparently the test failures are unrelated to the PR:

* https://github.com/status-im/status-mobile/issues/14111

**Pull request merged**
