### PR TITLE
Add Ethcro Dapp to default contacts

### PR DESCRIPTION
**Pull request by kemargrant**
### Summary:
Ethcro Dapp added to default contacts

### Steps to test:
- Open Status
- Navigate to contacts
- Select Ethcro

status: ready

### CODE REVIEW

**Comment by pablanopete** [comment]
DApp in reviewal with @kemargrant

**Comment by pablanopete** [comment]
Blocked right now because cannot get DApp to work properly in Status - may need to create issue in regards to this after more testing is done

**Comment by kemargrant** [comment]
Can you tell me what issue you are having?
It may be a misunderstanding of what the application does.

**Review by pablanopete — COMMENTED** [review]
LGTM

**Review by pablanopete — APPROVED** [review]

**Comment by asemiankevich** [comment]
@kemargrant could you please rebase ? http://138.197.185.225:8080/job/status-react/job/parametrized%20build/55/parameters/ fails

**Comment by kemargrant** [comment]
@asemiankevich I have rebased

**Comment by oskarth** [comment]
http://138.197.185.225:8080/job/status-react/job/parametrized%20build/58/console builds with kemargrant:develop and default ENV (internal link only, unfortunately)

**Pull request merged**
