### PR TITLE
discard backup message when recovering account

### PR DESCRIPTION
**Pull request by qfrank**
this PR aligned with [PR](https://github.com/status-im/status-go/pull/3781)

### Testing notes
recovery account using keycard should works as before, pls attach debug logs if it works as before so i can check configuration passed correctly, thanks!

#### Platforms

- Android
- iOS

status: ready

### CODE REVIEW

**Review by flexsurfer — APPROVED** [review]

**Review by jo-mut — APPROVED** [review]

**Comment by churik** [comment]
OK, I'm not able to check it because this flow is not implemented in re-designed app, so no option to check this flow in particular

But the flow "recover multiaccount " from seed phrase is broken

[geth_cr.log](https://github.com/status-im/status-mobile/files/12146229/geth_cr.log)

IMAGE 2023-07-24 15:10:43

**Comment by churik** [comment]
Unfortuanately, the flow "recover with keycard" is not implemented in re-designed app, so I can't verify it. 
During check of "restore from seed phrase" flow one blocker  is found

### ISSUE 1: unable to restore a multiaccount from seed on IOS

**Steps:**
1) restore the multiaccount from seed phrase


**Actual result:**
app is freezing on "Keys saved", after reopen: 
IMAGE 2023-07-24 15:18:46

**OS:** IOS
[logs (51).zip](https://github.com/status-im/status-mobile/files/12146313/logs.51.zip)

**Comment by qfrank** [comment]
> Unfortuanately, the flow "recover with keycard" is not implemented in re-designed app, so I can't verify it. During check of "restore from seed phrase" flow one blocker is found
> 
> ### ISSUE 1: unable to restore a multiaccount from seed on IOS
> **Steps:**
> 
> 1. restore the multiaccount from seed phrase
> 
> **Actual result:** app is freezing on "Keys saved", after reopen: IMAGE 2023-07-24 15:18:46
> 
> **OS:** IOS [logs (51).zip](https://github.com/status-im/status-mobile/files/12146313/logs.51.zip)

Hi @churik , issue 1 should be relate to this [commit id](543b0878963a9b62e132cb5e6cab00e9aeb27b4c) which include 
a [migration](https://github.com/status-im/status-go/blob/f1db6d16156c6d0a40631dc7330c8319a97865f6/appdatabase/migrations/sql/1689498471_make_wallet_accounts_positions_non_negative.up.sql#L3) , not relate to this PR cc @saledjenic

**Comment by qfrank** [comment]
if it's not implemented in re-designed app, maybe we can just merge it so that building status-mobile won't get blocked. but before merge it , we have to fix issue 1 , could you help take a look? @saledjenic or i may take a deep look tomorrow.

**Comment by saledjenic** [comment]
@qfrank I haven't ever run the iOS app, don't have an environment set for it to check. For the desktop app all went well, also looking at [this script](https://github.com/status-im/status-go/blob/f1db6d16156c6d0a40631dc7330c8319a97865f6/appdatabase/migrations/sql/1689498471_make_wallet_accounts_positions_non_negative.up.sql#L3) cannot see anything problematic.

**Pull request merged**
