### PR TITLE
Fix bad navigation call

### LINKED ISSUE #5936: App crash when sending Request to contact from Wallet
***Type***: Bug

***Summary***: App crashes with an `Error: Error: There is no route defined for key home.
Must be one of: 'wallet-request-transaction','wallet-send-transaction-request','wallet-request-assets','recent-recipients'` when contact sends a `Request` from `Wallet` -> `Receive tranaction` -> `New request` screen.

#### Expected behavior
Request message sent in 1-1 chat

#### Actual behavior
Error: Error: There is no route defined for key home.
Must be one of: 'wallet-request-transaction','wallet-send-transaction-request','wallet-request-assets','recent-recipients'` followed by the app crash

screen shot 2018-09-21 at 11 57 04

### Reproduction

- Open Status and create new account
- Add a contact in the list of contacts
- Navigate to `Wallet` -> `Receive tranaction` -> `New request`
- Choose recipient and specify valid amount
- Tap `Send request` button

### Additional Information
* Status version: Develop `0.9.29 (8885); node 0.15.0` (NOTE: it's all **fine** in **Release 0.9.28**)
* Operating System: Android and iOS

#### Logs
`Error: Error: There is no route defined for key home.
Must be one of: 'wallet-request-transaction','wallet-send-transaction-request','wallet-request-assets','recent-recipients'
`
TF session with logs: https://app.testfairy.com/projects/4803590-status/builds/8601407/sessions/4401998975/?accessToken=CaMnkA1/DSdD4B/6rhFTDg8Su4U

<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803590-status/builds/8601407/sessions/4401998975/?accessToken=CaMnkA1/DSdD4B/6rhFTDg8Su4U">TestFairy: Status 0.9.29 (8885) @2018</a></strong></div></blockquote>

### PR DESCRIPTION
**Pull request by janherich**
[comment]: # (Please replace ... with your information. Remove < and >)
[comment]: # (To auto-close issue on merge, please insert the related issue number after # i.e fixes #566)

Fix bad navigation call introduced in recent refactoring/navigation rebase combo.

fixes #5936 

### Steps to test:
Test that bug is no more

status: ready

### CODE REVIEW

**Review by yenda — APPROVED** [review]

**Review by cammellos — APPROVED** [review]

**Review by dmitryn — APPROVED** [review]

**Review by rasom — APPROVED** [review]

**Review by flexsurfer — APPROVED** [review]

**Comment by asemiankevich** [comment]
@janherich 

contract deploy transaction appears when i respond to transaction request in 1x1 chat on Android
image

**TF link:**  https://app.testfairy.com/projects/4803622-status/builds/8601935/sessions/4402178597/?accessToken=-Ez2s-EBu4m9D2sJhbFCVcQpA2k

- Open status
- Having 2 devices (ios and android) add them to contacts
- Faucet some funds and tokens for each
- From Android to iOS: send a request from wallet (0.123456789012345678 STT)
- From iOS to Android: respond to this request
- On Android check that new transaction message appears in chat
- From iOS: navigate to wallet - receive transaction - select STT - enter amount (0.123456789012345678 STT) - send the request
- on Android: check that new request appears in 1x1 chat
- on Android: respond to the request
- on Android: pay attention blue screen for deploy new contract is shown right after you tap Git It button


NOTE: when performing same scenario vise versa (iOS is recipient in last step) : chat history is not shown in 1x1 chat on iOS. It appears when i go back to home screen and then open 1x1 chat again.
Also it does not depend on Asset (STT or ETH).

image

<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803622-status/builds/8601935/sessions/4402178597/?accessToken=-Ez2s-EBu4m9D2sJhbFCVcQpA2k">TestFairy: Status 0.9.29 (8927) @2018</a></strong></div></blockquote>

**Comment by asemiankevich** [comment]
@janherich not sure, checking now! :)

**Comment by asemiankevich** [comment]
@janherich unfortunately it is impossible to check in develop - app crashes when sending request from wallet (

**Comment by asemiankevich** [comment]
@janherich lets merge this one as it fixes the issue. I will open new issue for develop

**Pull request merged**
