### PR TITLE
[#3845] added edcon to public chats

### PR DESCRIPTION
**Pull request by pablanopete**
this is a public channel needed for the upcoming edcon event.

### CODE REVIEW

**Comment by pablanopete** [comment]
fixes #3845 hopefully :D let me know if there's something else in the logic that needs to be changed to add this channel in status by next release.

**Comment by goranjovic** [comment]
@pablanopete Mind signing the commit?
Also, is there a reason to remove `ethereum` channel, other than to make room for this one?

**Comment by flexsurfer** [comment]
@pablanopete do we need this in the current release?

**Comment by pablanopete** [comment]
@flexsurfer in the next release yes please; so we'll have by edcon. I'm having GPG fun issues though; may need to get @goranjovic to sign a new pr with this.

**Comment by flexsurfer** [comment]
@goranjovic please create new PR, and fix avoidekeyboard, because it's annoying to click twice

**Comment by pablanopete** [comment]
Thanks @flexsurfer @goranjovic closing this in anticipation of Goran making a new PR.

**Pull request closed without merging**
