### PR TITLE
[android] send logs to specific emails

### PR DESCRIPTION
**Pull request by rasom**
status: wip

### CODE REVIEW

**Comment by rasom** [comment]
@mandrigin @annadanchenko I added `roman@status.im", "logs@status.im"`, which email are we going to use for this?

**Comment by rasom** [comment]
@mandrigin @annadanchenko still waiting for you response

**Comment by mandrigin** [comment]
@rasom let's do "error-reports@status.im". @corpetty can you set up an email group with this alias. It would be nice to have me, Roman, Anna and Serhy there.

**Review by mandrigin — APPROVED** [review]

**Comment by rasom** [comment]
thanks @mandrigin

**Comment by rasom** [comment]
updated

**Comment by corpetty** [comment]
Just seeing this, I'll create the email group now.

**Pull request closed without merging**
