### PR TITLE
Enter adds new line only at the end of last string (#1161)

### PR DESCRIPTION
**Pull request by alwx**
Done. Fixes #1178

### CODE REVIEW

**Comment by flexsurfer** [comment]
btw, genymotion adds line break somehow, so there is such an ability in RN, we need to figure out somehow what kind of signal it does

**Comment by flexsurfer** [comment]
and there are native solutions https://github.com/facebook/react-native/issues/11669 just in case

**Comment by alwx** [comment]
As for me, is's better to solve it this way instead of using native solution which means adding one more library and writing Android-specific code.

**Comment by annadanchenko** [comment]
App crashes if send command with invalid arrgument `@browse url` and tap on Enter in device keyboard.
video: https://drive.google.com/open?id=0Bz3t9zSg1wb7WnhLZlUtOE0ySlU

Android 7.0, Samsung Galaxy S7
Log: [20171005142743-logcat.txt](https://github.com/status-im/status-react/files/989712/20171005142743-logcat.txt)

**Comment by annadanchenko** [comment]
@alwx there are no more crashes or initial issues that this PR was going to solve. Ok to close it?

**Comment by alwx** [comment]
Hm. Okay then.

**Pull request closed without merging**
