### PR TITLE
Address field in Send to Contacts Screen (#522)

### LINKED ISSUE #522: Address field in Send to Contacts Screen
In Wallet send function in Send to Contacts Screen, above Scan QR we should have an input field with placeholder text "Address" with address validation that allows the user to send directly to an address. alternatively they can choose scan qr or select a contact as usual

### PR DESCRIPTION
**Pull request by alwx**
Fixes #522

### CODE REVIEW

**Comment by alwx** [comment]
screen shot 2016-12-01 at 16 07 50

This is how it looks now. "Enter address" icon will be updated in the nearest future, I suppose.

**Comment by jarradh** [comment]
looks good to me, lets merge this when we get new icon from @andmironov

**Comment by andmironov** [comment]
Zeplin: https://zpl.io/Z6ykr2

Preview:  enter_address

**Comment by alwx** [comment]
done!

**Pull request merged**
