### PR TITLE
nuke react-native-mail and move over the logic to our native modules

### PR DESCRIPTION
**Pull request by siddarthkay**
## Summary

In this PR we nuke the unmaintained library `react-native-mail` and move over the logic to our native modules.
This also helps to fix `make nix-update-gradle` which would fail because of that library.

## Platforms

- Android
- iOS

status: ready

### CODE REVIEW

**Review by jakubgs — APPROVED** [review]
I'm not sure if this functionality should go into `NetworkManager` files, rather than into its own files for easier removal in the future if need be. But that's up for mobile devs to decide.

Also, do we even use this library? Does anyone actually read the emails this genereates?
Wouldn't it be easier just to take someone to github issues page?

**Comment by siddarthkay** [comment]
> Does anyone actually read the emails this genereates?

Good question!, @status-im/mobile-qa might know

> rather than into its own files for easier removal in the future if need be

Yes thats a good idea

**Review by mohsen-ghafouri — APPROVED** [review]

**Comment by churik** [comment]
as far as I understand the question, we need theses emails, as they have logs attached to them. We use it a lot. If there is another mechanizm, it is OK to substitute it, but the main requirement is to be able to extract logs on shake and share them fast (the mean doesn't matter that much)

**Comment by churik** [comment]
as far as I understand the question, we need theses emails, as they have logs attached to them. We use it a lot. If there is another mechanizm, it is OK to substitute it, but the main requirement is to be able to extract logs on shake and share them fast (the mean doesn't matter that much)

**Comment by siddarthkay** [comment]
tested on android simulator and hence using `skip-manual-qa`

**Pull request merged**
