### PR TITLE
remove crypto libraries and nodeify hack

### PR DESCRIPTION
**Pull request by yenda**
Since the new protocol has been merged, we can remove the crypto libraries and nodeify hack from the codebase

Goes from 1277 packages built in 27 sec to 1244 packages built in 24 sec

### Testing notes:

Test if app still works

status: ready

### CODE REVIEW

**Comment by yenda** [comment]
Build 

Android: https://i.diawi.com/WG5bBK
iOS: https://i.diawi.com/YZa55w


<blockquote><div><strong><a href="https://i.diawi.com/WG5bBK">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>
<blockquote><div><strong><a href="https://i.diawi.com/YZa55w">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Review by jeluard — APPROVED** [review]

**Review by flexsurfer — APPROVED** [review]

**Comment by flexsurfer** [comment]
@yenda could you elaborate why do we need 3 new scheme?

**Comment by Serhy** [comment]
Builds Android: https://i.diawi.com/WG5bBK and iOS: https://i.diawi.com/YZa55w tested on Android 7.0 and iOS 11.2.5 on real devices.

Messaging poorly works. What happens is that even device stays online - the app loses connection at some point (<1 minute) so the message sent to this Contact is not received. After some time once message sender sends one more message - it picks up all previous messages from offline inbox (from offline inbox - because bunch of unreceived messages appears in 'Waiting for message to arrive...' state - very similar to that described in https://github.com/status-im/status-react/issues/3778 but here Contact does not even need to go into offline mode).

There are TF sessions for two contacts: 
https://app.testfairy.com/projects/4803590-status/builds/8053706/sessions/4/?accessToken=sX4LXF4an-42lhKmICS7Ij9r7kE
https://app.testfairy.com/projects/4803622-status/builds/8053679/sessions/27/?accessToken=rxJKKQhnkL6m4OQppSBctYhB-3U

To reproduce - just create two contacts on two devices: Contact1 sends 20 messages to Contact2 and Contact2 replies with 20 messages to Contact1.  

<blockquote><div><strong><a href="https://i.diawi.com/WG5bBK">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>
<blockquote><div><strong><a href="https://i.diawi.com/YZa55w">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>
<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803590-status/builds/8053706/sessions/4/?accessToken=sX4LXF4an-42lhKmICS7Ij9r7kE">TestFairy: Status 0.0.2405 @4</a></strong></div></blockquote>
<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803622-status/builds/8053679/sessions/27/?accessToken=rxJKKQhnkL6m4OQppSBctYhB-3U">TestFairy: Status fbc0569b+ (2405) @27</a></strong></div></blockquote>

**Comment by yenda** [comment]
@flexsurfer to remove the public and private key that was used to encrypt group chat and discoveries on clojure side

**Review by rasom — APPROVED** [review]

**Comment by Serhy** [comment]
The same as what described in https://github.com/status-im/status-react/pull/3779#issuecomment-379186066 is develop, - not this PR issue.

**Pull request merged**
