### PR TITLE
Fix add contacts

### LINKED ISSUE #3900: While adding members to group chat don't display dapp list.
### User Story

As a user, I want to add only users (not dapps) to a group chat.

### Description

*Type*: Bug

#### Expected behavior
artboard

#### Actual behavior
img_4544

### Reproduction
- Open Status
- Create a group chat
- Add members to this chat from the chat profile

### Solution
*Summary*: 
- delete dapps from this list

### Additional Information
* Status version:  nightly 17.04.18
* Operating System: Android|iOS

### PR DESCRIPTION
**Pull request by janherich**
[comment]: # (Please replace ... with your information. Remove < and >)
[comment]: # (To auto-close issue on merge, please insert the related issue number after # i.e fixes #566)

fixes #3900 #3891 #3893 #3464 

### Testing notes (optional):
Test all scenarios in tickets

status: ready

### CODE REVIEW

**Review by cammellos — APPROVED** [review]

**Review by flexsurfer — APPROVED** [review]

**Comment by asemiankevich** [comment]
@janherich https://github.com/status-im/status-react/issues/3891 is still in place

**Comment by janherich** [comment]
Rebased, ready to be tested again

**Comment by asemiankevich** [comment]
@janherich for https://github.com/status-im/status-react/issues/3891 : deleted member is able to post in a group chat from where he was deleted and others can see the message.

**Comment by rasom** [comment]
@janherich any updates on this PR? should it be closed?

**Comment by janherich** [comment]
Closing because of the outdated code, will open another PR fixing Group Chat issues later.

**Pull request closed without merging**
