### PR TITLE
[wallet #11860] Show preloaded tx history when app is offline

### LINKED ISSUE #11860: After relogin on mobile network transaction history is reset (need to load it again) and "Load more" button doesn't do anything when open history for 1 time
# Bug Report

## Problem
2 issues with transaction history on mobile network: 

#### 2) No caching of transaction history in view, so after relogin on mоbile network (with "Use mobile data" = OFF) it is empty again
Also there is no indication that it should be pull-to-refresh to download transaction history (cc @errorists how to do it in better way)

#### Expected behavior
1) if "Load more" button is useless - let's hide it
2) if transaction history was loaded before, assume it should be loaded after relogin.

#### Actual behavior
1) https://user-images.githubusercontent.com/4557972/110498872-00499880-80f8-11eb-8603-8503fae1f554.mp4
2) https://user-images.githubusercontent.com/4557972/110498884-02abf280-80f8-11eb-8279-cbe86b724817.mp4

### Reproduction

- Open Status (on cellular network)
- Restore multiaccount with transaction history
- Tap on "Load more" (ISSUE 1)
- Pull-to-refresh
- Relogin and open transaction history (ISSUE 2)

### Additional Information

- Status version: release 1.12
- Operating System: Android, iOS

### PR DESCRIPTION
**Pull request by rasom**
fixes #11860

When syncing is not allowed (the app is either offline or it is on cellular network and syncing is disabled by the user):
- we show transfers stored in the database when user opens tx history screen
- if user reaches history's end and syncing is still not allowed "fetch more" button is greyed out
- once user connects to wifi or enables syncing on cellular "fetch more" is available again

In case if account is created on cellular/offline "fetch more" is shown but greyed out.

status: ready

### CODE REVIEW

**Comment by qoqobolo** [comment]
@rasom 

### ISSUE 1: `Load more` button becomes available for one pressing after first using 'pull-to-refresh' on cellular network with using mobile data disabled.

#### Expected behavior

`Load more` button is greyed out as long as syncing is not allowed 

#### Actual behavior

https://user-images.githubusercontent.com/67952253/111810778-abb3d380-88d6-11eb-97c7-9d5a56b3d95a.mp4

#### Steps:
- Restore multiaccount with transaction history on mobile network
- Open Wallet
- Pull-to-refresh
- Tap `Load more`

**Comment by rasom** [comment]
@qoqobolo issue 1 should be fixed

**Comment by qoqobolo** [comment]
@rasom 
### ISSUE 2: If recover multiaccount on mobile network, navigate to tx history, enable WiFi, and tap `Load more`, tx history won't be updated.

The button `Load more` will disappear and in 70% of cases you get the message "Transfer history could not be updated. Check your connection and pull down to try again" (sometimes it appears only after using pull-to-refresh).

https://user-images.githubusercontent.com/67952253/111981197-a5f10480-8b07-11eb-9435-869c883d5d42.mp4

If after that, disable WiFi and syncing again and pull down, part of the tx history will be downloaded, but there will be no `Load more` button at the end of the history.

https://user-images.githubusercontent.com/67952253/111981421-f36d7180-8b07-11eb-89a0-30389cff5a31.mp4

#### Steps:
- Recover multiaccount on cellular network
- Open Wallet
- Enable WiFi and wait for `Load more` is available
- Tap `Load more`
**
- Disable  WiFi
- Stop syncing
- Open Wallet
- Pull down
- Scroll to the end of the history

[geth.log](https://github.com/status-im/status-react/files/6181764/geth.log)
[Status.log](https://github.com/status-im/status-react/files/6181765/Status.log)

**Review by flexsurfer — APPROVED** [review]

**Comment by rasom** [comment]
@qoqobolo 
I can't reproduce those steps, tried iOS and android. Maybe that's acc specific

**Comment by qoqobolo** [comment]
Apparently, Issue 2 is device specific and can only be reproduced on Google Pixel so far.
Will continue testing on another Android device.

**Review by shivekkhurana — APPROVED** [review]

**Pull request merged**
