### PR TITLE
Merge develop branch into desktop

### PR DESCRIPTION
**Pull request by vkjr**
related to #4730 

### Summary:

[comment]: # (Summarise the problem and how the pull request solves it)
Changes from `develop` branch merged into `desktop

### Review notes (optional):

Main change that had to be made in this merge is support of work with keychain.
`develop` branch uses `react-native-keychain` and `react-native-securerandom` 3rdparty libs to create/store/restore keys for realm db encryption.
So now we have 2 forks with desktop support:
https://github.com/status-im/react-native-keychain
https://github.com/status-im/react-native-securerandom

`react-native-keychain` implemented with the help of this project - https://github.com/frankosterfeld/qtkeychain

### Important
When you login or create account in StatusIm, your OS will ask you to enter system password to allow app accessing keychain. 

### Steps to test:
- Open Status
- Enjoy!

status: ready 

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/status-im/react-native-keychain">status-im/react-native-keychain</a></strong></div><div>react-native-keychain - :key: Keychain Access for React Native</div></blockquote>
<blockquote><div> GitHub</div><div><strong><a href="https://github.com/status-im/react-native-securerandom">status-im/react-native-securerandom</a></strong></div><div>react-native-securerandom - A crypto-secure random bytes generator for react native</div></blockquote>
<blockquote><div> GitHub</div><div><strong><a href="https://github.com/frankosterfeld/qtkeychain">frankosterfeld/qtkeychain</a></strong></div><div>qtkeychain - Platform-independent Qt API for storing passwords securely.</div></blockquote>

### CODE REVIEW

**Comment by cammellos** [comment]
I am not sure a merge is the best way to go here, I think it would be smoother if you rebase against develop, make sure there are no conflicts, and then you will be in a position where you can keep up to date, otherwise I feel it might become quite difficult to keep the branch up to date (as I take it might take some time before it gets merged into develop). just my 2p :)

**Comment by maxhora** [comment]
@cammellos rebasing seems really should work better, but it removes gpg signature from rebased commits. I'm wondering if exists workaround to place gpg signatures back or we can deal with some another solution ( person who will rebase will sign all rebased commits with personal gpg ? )

**Comment by cammellos** [comment]
@MaxRis yes, it would replace the signature of the commits on top (not the ones already in history), I think it's ok to have whoever rebases to sign all the commits, sounds good enough to me

**Comment by maxhora** [comment]
@cammellos regarding the current PR, how do you think, will it work better, if to take latest develop branch and cherry pick into it all unique commits from the desktop branch (we already previously did merge from develop branch into desktop branch and the history contains commits from develop branch as well mixed with desktop related commits)

**Comment by cammellos** [comment]
@MaxRis hard to say,
seems like the options are:
1) looking at https://github.com/status-im/status-react/tree/desktop you only have 22 commits to add, so I almost feel that a straight rebase is doable (`git rebase develop` from `desktop` and then keep it up to date daily and get it merged as soon as possible). Previous merges are going to be a bit painful to handle probably though, so you can use cherry-pick or just rebase using a hash-range.
2) Merge this is as it is, at the moment, but this is basically unreviewable, and if a PR like this one comes to develop I am not sure how we are going to handle it, ideally we can try and have a look on how github shows the diff once this PR has been merged (we can try on a different branch).

Not really sure on how to move forward, I guess the path of least resistance :)



<blockquote><div> GitHub</div><div><strong><a href="https://github.com/status-im/status-react">status-im/status-react</a></strong></div><div>status-react - a free (libre) open source, mobile OS for Ethereum</div></blockquote>

**Comment by maxhora** [comment]
@cammellos thanks for suggestion!
@rcullito @siphiuel how do you think regarding to merge this PR as is ( I'm still in progress to resolve build failures on Linux and Jenkins build, so additional commit should appear in this PR ) ?
I've tested PR changes on MacOS, seems, works good. On Linux there is some runtime failure related to db encryption, but since Linux is not priority, lets resolve this later.

**Comment by rcullito** [comment]
@MaxRis my vote would be to merge it, despite the current build issues on linux as you say. Locally I am receiving 

```
make[2]: *** No rule to make target 'node_modules/react-native-keychain/desktop/qtkeychain/build/lib/libqt5keychain.a', needed by 'bin/StatusIm'.  Stop.
make[1]: *** [bin/CMakeFiles/StatusIm.dir/all] Error 2
make: *** [all] Error 2
```

Not sure if this is what you were getting as well?

But yes, would vote to merge and spend our time working on ironing out the build issues :+1: Seems like this will have good positive side effects in the long term rather than continuing to do feature implementation without taking `develop` branch into account. 

thanks for doing the heavy lifting on the merge thus far @vkjr !

**Review by rcullito — APPROVED** [review]
as @cammellos said, I don't quite have the breadth of the codebase to comment on the scale of the diff here. Rather approving based on the belief that it is better to tackle this when desktop branch only has 22 commits rather than in a few weeks when that number has grown even more. Thanks for getting the ball rolling @vkjr

**Comment by vitvly** [comment]
Also vote for merging-as-is.

**Review by vitvly — APPROVED** [review]

**Comment by maxhora** [comment]
Work to be continued in PR https://github.com/status-im/status-react/pull/4927

**Pull request closed without merging**
