### PR TITLE
removes the `to clipboard`

### PR DESCRIPTION
**Pull request by decanus**
some non technical users may be confused if they see the `clipboard` term without knowing its definition.

### CODE REVIEW

**Comment by hesterbruikman** [comment]
@decanus Thanks for your contribution and zooming in on this! I'd be happy with this change. I can't find where in the UI 'Copy to clipboard' is used at the moment. Could you please point out the screen or share a screenshot?

**Comment by decanus** [comment]
@hesterbruikman when you long press on a message on iOS at least it is shown in a list of options.

**Comment by hesterbruikman** [comment]
Got it, thanks @decanus ! 

I imagine the intention was to differentiate between 'reply' in the chat or copy to clipboard (not in the chat), but agree that this day and age [Copy] should be enough and is more consistent. Will ping to get you some more reviews.

Additional context: Designs include [Copy]; we tested this and found no issues. 
https://docs.google.com/presentation/d/10qb5jRXwRT9lYkxrn8Ui5Bov_JRuf1WBaPqSXd0ZAtY/edit#slide=id.g3f411e60e9_0_155

**Review by hesterbruikman — APPROVED** [review]

**Review by yenda — APPROVED** [review]

**Comment by mandrigin** [comment]
fun fact: on iOS and macOS it is called a **pasteboard** anyways.

**Review by errorists — APPROVED** [review]

**Comment by churik** [comment]
@hesterbruikman 
I believe if we are aiming to get rid of `clipboard` word to avoid user confusion, we need to do it everywhere.
For now in https://github.com/status-im/status-react/blob/develop/translations/en.json:
1) "sharing-copy-to-clipboard": "Copy to clipboard"
2) "wallet-address-from-clipboard": "Use Address From Clipboard"
3) "sharing-copied-to-clipboard": "Copied to clipboard"
4) "copy-to-clipboard": "Copy to clipboard"
Only 1 and 3 are changed.

So there are more places where Clipboard is using.
I propose to fix all these translations in this case.

@decanus thank you for contribution!
After comment of @hesterbruikman if there will be more changes needed to translations - please, rebase your branch to last `develop`.

**Comment by hesterbruikman** [comment]
> So there are more places where Clipboard is using.
> I propose to fix all these translations in this case.

Thanks for catching those @churik ! I would update 4 as well by removing 'to clipboard'. For 2 I would say update to "Paste", but I'm lacking context. Does anyone know where this is used?

1. "sharing-copy-to-clipboard": "Copy to clipboard" > Copy
1. "wallet-address-from-clipboard": "Use Address From Clipboard" > Paste?
1. "sharing-copied-to-clipboard": "Copied to clipboard" > Copy
1. "copy-to-clipboard": "Copy to clipboard" > Copy

**Comment by churik** [comment]
@hesterbruikman I know.
And I propose a bit different:

1. "sharing-copy-to-clipboard": "Copy to clipboard" > Copy
2. "wallet-address-from-clipboard": "Use Address From Clipboard" > Paste?
Not really sure, paste in this case is OK IMO.
3. "sharing-copied-to-clipboard": "Copied to clipboard" > Copied
The popup that appears after copying the QR code.
4. "copy-to-clipboard": "Copy to clipboard" > Copy

Are you agree?

**Comment by hesterbruikman** [comment]
> Are you agree?

Yes, thank you!

**Comment by churik** [comment]
so @decanus there are some changes required:

- [ ] change "wallet-address-from-clipboard": "Use Address From Clipboard" > Paste and "sharing-copied-to-clipboard": "Copied to clipboard" > Copied

- [ ] to change several lines in e2e tests: in https://github.com/status-im/status-react/blob/develop/test/appium/tests/atomic/chats/test_one_to_one.py 487, 499 rows and
in https://github.com/status-im/status-react/blob/develop/test/appium/tests/atomic/chats/test_chats_management.py, row 80  change 'Copy to clipboard' to 'Copy'

Thank you!

**Comment by decanus** [comment]
@churik done

**Comment by churik** [comment]
@decanus sorry for one more question -
> After comment of @hesterbruikman if there will be more changes needed to translations - please, rebase your branch to last develop.

Can you please rebase it because unfortunately, I can't start tests from your branch - it contains `develop` with issue?

**Comment by decanus** [comment]
@churik done

**Comment by mandrigin** [comment]
@decanus it is al good, but can you please squash the PR commits before I merge it?

**Comment by decanus** [comment]
@mandrigin I messed up the squash. Will do a new branch

**Comment by mandrigin** [comment]
you probably can still force-push to the same one and it will be reopened.

**Comment by decanus** [comment]
@mandrigin I just opened a new one https://github.com/status-im/status-react/pull/7744

**Comment by mandrigin** [comment]
@decanus you can now just cherry-pick `3cd09c607ab5cb498bb7c8dcc31520d7a053c06c` to this branch and force-push, I'd prefer to merge this PR with tests, etc.

**Comment by decanus** [comment]
@mandrigin `cherry-pick` doesn't work. I think I borked the branch too much locally.

**Comment by mandrigin** [comment]
ah, ok :(
there is always `git reflog` to undo these types of operations, of course.

**Comment by decanus** [comment]
@mandrigin I am afraid this is where my git power user skills reach their limit

**Comment by mandrigin** [comment]
okay, nevermind, I'll ask to re-run autotests in the new PR and then will merge if it is successful.

**Pull request closed without merging**
