### PR TITLE
fix(sha3)_: support hex string

### PR DESCRIPTION
**Pull request by qfrank**
fix relate mobile [issue](https://github.com/status-im/status-mobile/issues/21819)

relate status-go [PR](https://github.com/status-im/status-go/pull/6216)

#### Platforms

- Android
- iOS

status: ready.

### CODE REVIEW

**Review by flexsurfer — APPROVED** [review]

**Comment by pavloburykh** [comment]
Hey @qfrank! Thank you for the fix. Please ping me up once PR is reviewed and ready for QA.

**Comment by qfrank** [comment]
> Hey @qfrank! Thank you for the fix. Please ping me up once PR is reviewed and ready for QA.

ready for QA now :) @pavloburykh

**Comment by pavloburykh** [comment]
> > Hey @qfrank! Thank you for the fix. Please ping me up once PR is reviewed and ready for QA.
> 
> ready for QA now :) @pavloburykh

Would be great if go PR https://github.com/status-im/status-go/pull/6216 is reviewed prior to QA as there might be some additional changes based on review.

**Comment by flexsurfer** [comment]
@pavloburykh approved both

**Review by ilmotta — APPROVED** [review]

**Comment by pavloburykh** [comment]
@qfrank @flexsurfer thanks for the PR. Unfortunately we still have critical issue during upgrade flow

### ISSUE 1 Wrong derived addresses are created after upgrade from v1 Status app

**Steps:** 

1. Install Status v1 app
2. Create account
3. Upgrade to Status 2.32
4. Migrate user to Keycard
5. Create additional wallet account via keycard (from default keypair) 
6. Check if new account address is correct 

**Actual result:** account address is incorrect

[Status-debug-logs - 2024-12-16T172321.128.zip](https://github.com/user-attachments/files/18152746/Status-debug-logs.-.2024-12-16T172321.128.zip)


photo_2024-12-16 17 22 05

**Expected result:** 

photo_2024-12-16 17 23 04

**Comment by pavloburykh** [comment]
@qfrank @flexsurfer Because of ISSUE 1 it was decided to disable possibility to create additional accounts via keycard https://github.com/status-im/status-mobile/issues/21828

**Comment by flexsurfer** [comment]
v1 upgrade is a separate isssue, keycard doesn't support paths like `m/1`

**Comment by flexsurfer** [comment]
@pavloburykh could you please create a new issue for `v1 upgrade is a separate isssue, keycard doesn't support paths like m/1` , this one is fixed, and has been merged on go side

**Comment by flexsurfer** [comment]
@qfrank could you pls bump go version and merge pls

**Comment by ilmotta** [comment]
@pavloburykh PR is now updated to latest commit from status-go release branch and also rebased against latest mobile `release/2.32.x`. Do you want to do a final check or can we merge as soon as the CI passes the basic checks?

**Comment by flexsurfer** [comment]
> @pavloburykh PR is now updated to latest commit from status-go release branch and also rebased against latest mobile `release/2.32.x`. Do you want to do a final check or can we merge as soon as the CI passes the basic checks?

hey @ilmotta i believe this change won't go to release, because we have another issue and we just disabled account creation in the release

**Comment by ilmotta** [comment]
> hey @ilmotta i believe this change won't go to release, because we have another issue and we just disabled account creation in the release

Sure thing @flexsurfer, in that case I'll leave it up for @qfrank to handle this PR since it's not urgent anymore.

The status-go PR needs to be applied onto status-go `develop` before updating and merging this PR because https://github.com/status-im/status-go/pull/6216 was only applied merged onto `release/7.1.x`. I'm adding the `blocked` label @qfrank just to make sure this PR is not merged by mistake onto the current base branch `release/2.32.x`.

**Comment by pavloburykh** [comment]
> @pavloburykh could you please create a new issue for `v1 upgrade is a separate isssue, keycard doesn't support paths like m/1` , this one is fixed, and has been merged on go side

@flexsurfer created a separate issue about derivation paths https://github.com/status-im/status-mobile/issues/21836

**Comment by qfrank** [comment]
we only need to merge the changes into `develop` , however, the changes on status-go side already merged into `release/7.1.x`, @flexsurfer asked @igor-sirotin to remove it from release if needed, it's up to @igor-sirotin , I'll just leave the PR as it is ATM, created separate [PR](https://github.com/status-im/status-mobile/pull/21837) to merge the changes into `develop` cc @pavloburykh

**Pull request closed without merging**
