### PR TITLE
Change copy for browser options from chat link

### LINKED ISSUE #4938: Change copy for browser options from chat link
### User Story

As a user, I want to know the difference between two confusing browser options when I open a link.

### Description

*Type*: Feature

*Summary*: Change copy on the first option when opening a link inside Status. 

#### Expected behavior
When a user clicks on a link from chat, the options should read:

`Open in Status`
`Open in web browser`

#### Actual behavior
See above.

### Reproduction
Send someone a link in chat, and click on it.

### PR DESCRIPTION
**Pull request by tbenr**
Fixes #4938

### CODE REVIEW

**Review by cammellos — APPROVED** [review]

**Review by flexsurfer — APPROVED** [review]

**Comment by chadyj** [comment]
@obi2020 is here to help review copy changes :)

**Comment by chadyj** [comment]
cc @obi2020

**Comment by tbenr** [comment]
I  resolved the conflicts but there where problems on CI. I tried to rebase against latest develop but there still problems. Any suggestion on how to fix?

**Comment by tbenr** [comment]
it seems I forgot to update\refactor test scripts.

**Comment by Serhy** [comment]
Thanks @tbenr! Builds https://i.diawi.com/VSu1ve (Android) and https://i.diawi.com/5fKCK6 (iOS) Looks good! `Open in Status` is the label now. No unknown regressions found.
Test scripts has been reviewed, and apart `test_send_and_open_links` are confirmed as known issues (which have respective issues in GH). No worries, I'll update this test.
 

<blockquote><div><strong><a href="https://i.diawi.com/VSu1ve">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>
<blockquote><div><strong><a href="https://i.diawi.com/5fKCK6">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by Serhy** [comment]
Sorry, realised i can't make the changes in you branch :)
@tbenr could you please update also in `status-react/test/appium/views/chat_view.py` the
`        self.locator = self.Locator.xpath_selector("//*[@text='Open in browser']")`
to 
`        self.locator = self.Locator.xpath_selector("//*[@text='Open in Status']")` please?

**Comment by tbenr** [comment]
@Serhy do you think that all `open_in_browser_button ` and `OpenInBrowserButton` should be refactored to `open_in_status_button` and `OpenInStatusButton`?

**Comment by Serhy** [comment]
Makes sense, @tbenr, yes.

**Comment by tbenr** [comment]
@Serhy it is strage: it is still failing even if i made the changes. `OpenInBrowserButton` doesn't even exist anymore.. any cache somewhere?

**Comment by Serhy** [comment]
The reason is that tests were not updated yet in status develop branch.
But with your changes - it will ;)
It's good to merge, @tbenr. Thanks a lot for the contribution!

**Comment by tbenr** [comment]
Thanks @Serhy! It was a good place to start, now its time to start learning clojure :-)

**Comment by jeluard** [comment]
@tbenr Thanks for your contribution!

**Comment by andytudhope** [comment]
Hey @tbenr - there were a number of bounties that you did for us that just weren't confirmed by the people who were supposed to handle it.

I cannot apologies enough for this, and have ensured that all your outstanding bounties have been confirmed and paid out - so you should see quite a lot of SNT in your wallet now ;)

Generally speaking, we are much more on it than this, so please accept my apologies again - we really ❤️ having contributors like you around our codebase!

**Comment by tbenr** [comment]
Thanks @andytudhope - I appreciate that! I whant to continue contributimg in my spare time. I think the web3 industry in general needs contributors as much as possible (not only speculators)

**Pull request merged**
