### PR TITLE
feat(wallet)_: keycard support for swap and approval

### LINKED ISSUE #21619: 💳 🔁 Add Keycard support to Swap Txns
# Feature Issue

### User Story

As a Keycard user,
I want to be able to sign native swap txns using my Keycard
**so that** I can call myself a cool kid and my funds stays secure, . 

### Description

If the account being used to sign a swap txn is a Keycard account, the flow should change as per the designs.

Figma: https://www.figma.com/design/YGm3igIOAcwMqUVJWCJ6f1/Keycard-UX?node-id=409-58818&t=VFIzh8BRInCRKpP9-1

### Acceptance Criteria

- [ ] A Keycard account should see "Sign with Keycard" message and Keycard logo when trying to sign a swap txn
- [ ] User should be able to complete txn signing with Keycard

### PR DESCRIPTION
**Pull request by smohamedjavid**
fixes #21619

### Summary

This PR adds support for Keycard in the swap flow

### Review Notes

Since we share the same signals for all transaction building and signing, the keycard support for swap is a bit easier

### Platforms

- Android
- iOS

### Steps to test

- Open Status
- Navigate to the wallet tab
- Perform a swap transaction with a Keycard
- Verify the transaction is successfully placed

status: ready

### CODE REVIEW

**Review by mohsen-ghafouri — APPROVED** [review]

**Comment by mohsen-ghafouri** [comment]
@smohamedjavid does it mean we don't need this Feature unavailable modal for swap anymore? https://github.com/status-im/status-mobile/issues/21763

**Comment by smohamedjavid** [comment]
> @smohamedjavid does it mean we don't need this Feature unavailable modal for swap anymore? #21763

This feature (Keycard support for Swap) was initially planned for 2.33. Since this PR is not a big change, and it's something we squeeze in 2.32 if needed. Only the Dapps flow support would left for now.

cc @shivekkhurana

**Review by alwx — APPROVED** [review]

**Review by vkjr — APPROVED** [review]

**Comment by VolodLytvynenko** [comment]
hi @smohamedjavid thank you for PR. No issues from my side. PR is ready to be merged

**Comment by smohamedjavid** [comment]
@VolodLytvynenko - Thank you for testing the PR quickly 🙏 . Happy to have a 100% E2E result (I don't remember when was the time I saw it 😄 )

**Pull request merged**
