### PR TITLE
Updated dependencies.md

### LINKED ISSUE #16305: `depdendencies.md` is out of date, update it to match current usage and reasoning behind dependencies.
# Problem

We used to keep this document up to date : 
https://github.com/status-im/status-mobile/blob/develop/doc/dependencies.md
It is no longer up to date and needs a refresh

note : We want to capture the "why" and the "how" on each dependencies. 
They matter more than the version.

## Notes

- [ ] Go check https://github.com/status-im/status-mobile/blob/develop/package.json for latest dependencies
and update https://github.com/status-im/status-mobile/blob/develop/doc/dependencies.md

### PR DESCRIPTION
**Pull request by AnmolSirola**
fixes #16305 

### Summary

Updated dependencies.md with latest dependencies

### CODE REVIEW

**Comment by flexsurfer** [comment]
hey @AnmolSirola thank you for the contribution, im wondering if there are abandoned deps we need to remove or new one we need to add to the doc

**Comment by AnmolSirola** [comment]
@flexsurfer Here are some dependencies which are present in the json file but not in our dependency file:
1) @react-native-community/cameraroll
2) @react-native-community/push-notification-ios
3) react-native-navigation
4) react-native-permissions

Here are the dependencies which are present in our json file but there versions are not specified in our dependency file (but they are present in our dependency file):
1) rn-emoji-keyboard
2) react-native-draggable-flatlist

**Comment by siddarthkay** [comment]
Hey @AnmolSirola : Thanks for raising a PR for https://github.com/status-im/status-mobile/issues/16305.
We want to capture the "why" and the "how" on each dependencies. They matter more than the version.

We will always know the versions numbers from `package.json`.

So thats the idea behind having and updating `dependencies.md`.

also quick note : from next time onwards please raise a PR only if you've been assigned an issue. 
I remember https://github.com/gulshanpr asking a question on the original issue but I could not respond to them on time.

@gulshanpr : I'll try to find you something else to work on.

**Review by siddarthkay — CHANGES_REQUESTED** [review]
Once you have added missing dependencies over here, do mention why they were installed and how they are used within the project.

**Comment by AnmolSirola** [comment]
@siddarthkay I am sorry for solving this issue wtihout asking prior permission(without getting assigned), I thought it is not assigned to anyone so I did it( it is not a proper way to make a pr and it is MY FAULT that I thought this way).

In terms of the PR part, I have mentioned a few dependencies earlier. However, there are approximately more dependencies for which the version, as well as the reasons and methods for their inclusion, have not been explained. I will proceed to add that information now.

**Comment by AnmolSirola** [comment]
@siddarthkay I have updated the dependencies and also add information on why they are used.

**Comment by siddarthkay** [comment]
Thanks @AnmolSirola I will take a look, I see you've added some missing dependencies and their explanations. 
Could you please also remove the un-used dependencies from `dependencies.md` ?

**Comment by AnmolSirola** [comment]
@siddarthkay I have removed the dependencies which are not in use now.

**Review by siddarthkay — CHANGES_REQUESTED** [review]
you're removing "react-native-languages" from `dependencies.md` but I do see it in `package.json` which means its being used in the project.

Please check once more before asking for a review.

**Comment by AnmolSirola** [comment]
@siddarthkay I have removed some dependencies which are not in use, changed/updated the version of old dependencies. Please have a look.
If you find any mistakes please let me know I am happy to correct them.

**Comment by siddarthkay** [comment]
Hi @AnmolSirola : Thanks for putting in the work, I'll review the changes by the end of day today 👍🏻

**Comment by flexsurfer** [comment]
ping @siddarthkay

**Comment by flexsurfer** [comment]
feel free to reopen when needed

**Pull request closed without merging**
