### PR TITLE
upload sha256 checksums of built artifacts

### PR DESCRIPTION
**Pull request by jakubgs**
Show and upload an `*.sha256` file to DO for comparing resulting artifacts.

### CODE REVIEW

**Comment by ghost** [comment]
### Pull Request Checklist
- [ ] Have you updated the documentation, if impacted (e.g. [docs.status.im](https://docs.status.im/docs/build_status.html))?

**Review by yenda — APPROVED** [review]

**Comment by jakubgs** [comment]
IT WORKS:
http://status-im-prs.ams3.digitaloceanspaces.com/StatusIm-181129-154331-d57d0f-pr.sha256

<blockquote></blockquote>

**Review by mandrigin — APPROVED** [review]

**Comment by jakubgs** [comment]
Actually, I'd prefer if there was no `pkg/` before the names so I'll remove that.

**Comment by jakubgs** [comment]
Much better:
https://status-im-prs.ams3.digitaloceanspaces.com/StatusIm-181129-171753-acf307-pr.sha256
```
45e11a95260674861c2c24176fe6e5742c82659d455a0b134c7cf2af2831a64b  StatusIm-181129-171807-acf307-e2e.apk
95d8148feccd1514eb22ee82c7cd6247f3a5e70ff66ba9fdffdb4601d6a3bff0  StatusIm-181129-171807-acf307-pr.AppImage
354f70abf1562730da4df9f8f3b895e99a8f8cd25f2bc96bb6739b1c0ca88e7f  StatusIm-181129-171807-acf307-pr.apk
b979446d2b493aea0c69c201f16623881643386756fc7463627aa8d2dddd62e1  StatusIm-181129-171807-acf307-pr.dmg
c599d32ca371caf79dd89db890c5e1b1054677bc79363115a70617179f3ff9c9  StatusIm-181129-171807-acf307-pr.exe
6840c4e57901950b206111136498a610105c7c848bb5c3bffe12cfe1c01d4211  StatusIm-181129-171807-acf307-pr.ipa
```

**Review by corpetty — APPROVED** [review]
nailed it

**Pull request merged**
