### PR TITLE
Use modern build system for iOS

### PR DESCRIPTION
**Pull request by pedropombeiro**
[comment]: # (Please replace ... with your information. Remove < and >)
[comment]: # (To auto-close issue on merge, please insert the related issue number after # i.e fixes #566)

### Summary

[comment]: # (Summarise the problem and how the pull request solves it)
This PR gets rid of the code to use the legacy build system for iOS to work around an issue with Xcode 10.1 (we now require 10.2.1). It also does a bit of reformatting (using Rubocop) and simplification of the Ruby code.

status: ready

### CODE REVIEW

**Review by jakubgs — APPROVED** [review]
I see, the main change is dropping `UseModernBuildSystem=N`, but I approve of the formatting fixes and Fastlane upgrade too. Nice.

**Comment by jakubgs** [comment]
Uh oh, but are we sure we want to skip manual QA? This is a big change in build system.

**Comment by pedropombeiro** [comment]
> Uh oh, but are we sure we want to skip manual QA? This is a big change in build system.

True, especially since I don't have an iOS device to test on. Dropping the label. @churik do you have an iOS device you could test this with? It should be enough to just open the app and create an account.

**Comment by Serhy** [comment]
On iOS 12.4.1 (iPhoneX) can install Status, can create new and can recover successfully accounts. 
Message history is loaded, messages exchanged between two contacts in 1-1 chat fine

**Pull request merged**
