### PR TITLE
Use ReactText for links

### PR DESCRIPTION
**Pull request by vitvly**
- Use nested ReactText elements
  - Add text selection capability
  - Modify regexp somewhat to use the same regexp for both urls and channels

Depends on https://github.com/status-im/react-native-desktop/pull/366

### CODE REVIEW

**Review by yenda — CHANGES_REQUESTED** [review]
approved but waiting for react-native-desktop to be merged to use status-im repo.

also did you check that when there is a link in the middle of a line, it doesn't cut the line and the text continues ?

**Comment by vitvly** [comment]
@yenda like this? https://monosnap.com/file/tum86RBv1MqDAthvQDgARRXTH1RMw6

<blockquote><div>Monosnap screenshot tool</div><div><strong><a href="https://monosnap.com/file/tum86RBv1MqDAthvQDgARRXTH1RMw6">Screenshot "Monosnap 2018-10-11 21-55-36.png"</a></strong></div></blockquote>

**Comment by yenda** [comment]
@siphiuel yes perfect!

also @janherich might want to have a look at this he's currently working on saving messages pre-parsed to improve rendering performance

**Comment by vitvly** [comment]
@yenda thanks! And regarding pre-processing messages work by @janherich - that would be so cool. Would the processed results get stored in Realm, or would it be a subscription-only change?

**Comment by janherich** [comment]
@siphiuel Awesome, this will make my work actually bit easier as now the rendering in desktop and mobiles works similarly, without the special treatment of sentences :)
The pre-processed info will be assoc-ed into standard content, which is just `{:text text-string}` now, but will contain additional keys specifying where (index ranges) to render special styling (bold, italic) and semantics (links, tags, mentions).
It will offload views (much less logic), remove duplication existing between desktop & mobile and get rid of the strange state, where special styling (like bold) is working on mobile but on desktop, etc.

**Review by janherich — APPROVED** [review]

**Comment by vitvly** [comment]
thank you for explaining @janherich! Yours is a great initiative. By the way, I ended up quite disliking the current mobile logic of link parsing, seems to be too convoluted. @yenda's change is much simpler.

**Comment by yenda** [comment]
@janherich I want to see your PR I'm still not convinced that a map is better than vector of [type content] tuples :smile:

**Review by vkjr — APPROVED** [review]

**Comment by vitvly** [comment]
@yenda Related PR 
https://github.com/status-im/react-native-desktop/pull/366 is approved. I've accidentally merged it and reverted back afterwards - it should not get merged into `react-native-desktop/master` until this is tested. I will fix the repo URL in package.json once this PR is tested and verified.

**Review by yenda — APPROVED** [review]

**Comment by janherich** [comment]
@siphiuel The build failed for iOS because of the obsolete fastlane dep, do you mind if I rebase this on newest develop ?

**Comment by vitvly** [comment]
@janherich Thanks for noticing it! Just rebased, hopefully will work this time.

**Comment by churik** [comment]
Amazing work @siphiuel !
It also fixes https://github.com/status-im/status-react/issues/6240

However, there is one issue.
Click on any link makes this text appears in message area for reply.
**Steps:**
1) open status
2) join any public channel
3) send message with link (i.e.`Link inside https://github.com text`)
4) click on link

**Expected result:**
can proceed to link, the message input field remains empty
**Actual result:**
message with link appeared in input message field.
response

**Comment by vitvly** [comment]
@churik - thanks for uncovering this! Made a fix.

**Comment by churik** [comment]
@siphiuel don't see any new commits.
GitHub issue?

**Comment by vitvly** [comment]
@churik - no, not GitHub issue, rather my personal one :) The relevant fix affected react-native-desktop only. I've rebased here against latest develop, this triggered a fresh Jenkins build.

**Comment by churik** [comment]
Cannot be built, 8 attempts, [link](https://ci.status.im/job/status-react/job/pull%20requests/view/change-requests/job/PR-6263/)
Android builds are failed with errors:
```
* What went wrong:
Could not resolve all files for configuration ':react-native-camera:releaseCompileClasspath'.
> Could not find play-services-basement.aar (com.google.android.gms:play-services-basement:15.0.1).
  Searched in the following locations:
      https://jcenter.bintray.com/com/google/android/gms/play-services-basement/15.0.1/play-services-basement-15.0.1.aar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```
cc @siphiuel @jakubgs

**Comment by jakubgs** [comment]
I believe this was already fixed here: https://github.com/status-im/status-react/pull/6490
Please rebase from `develop`, and if that doesn't work poke me again.

**Comment by churik** [comment]
@siphiuel please, rebase it! Thanks.

**Comment by vitvly** [comment]
Done. Thanks guys!

**Comment by SlizkovaGanna** [comment]
Tested on MacOS 10.13.4
There is a small issue with a link not being clickable for a specific case (desktop only):

image
image
image

@siphiuel it was reported separately in https://github.com/status-im/status-react/issues/6531 (reproduces on nightly)

**Pull request merged**
