### PR TITLE
[FIX #3172] Wipe db when logging out

### LINKED ISSUE #3172: Can return to Home after log out if tap device back button [android]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: After user taps on log out it's still possible to return to Home and see chats if tap on device back button. It should not be possible. To see Home tab user needs to log in again

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
if tap on device back button after user logged out then same Sign in screen should be shown
#### Actual behavior
[comment]: # (Describe what actually happened.)
if tap on device back button after user logged out then Profile tab is shown and it's possible to swith to other tabs and see/use chats
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)
TF (00:19) https://app.testfairy.com/projects/4803622-status/builds/7593342/sessions/18/?accessToken=bLHV9vPSiihDLFAV03qgvylhkOE
- Open Status
- Sign in
- Open Profile
- Tap on log out
- On Sign in screen use device back button
- Check what screen is shown

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: nightly build from January 30, 0.9.15
* Operating System: Android only

### PR DESCRIPTION
**Pull request by yenda**
fix #3172 

To test:

check that you can:
- create an account, login logout, can't go back from profile screen to account, 
- login in other account
- recover account
- switch network

### CODE REVIEW

**Review by jeluard — APPROVED** [review]

**Review by janherich — APPROVED** [review]

**Comment by yenda** [comment]
@annadanchenko 

Branch: PR-3183
Android: https://i.diawi.com/xaokuX
iOS: https://i.diawi.com/wRWjcX

**Comment by yenda** [comment]
Branch: PR-3183
Android: https://i.diawi.com/aBKLxo
iOS: https://i.diawi.com/ZgmaRo

**Comment by janherich** [comment]
@yenda Please resolve conflicts

**Comment by goranjovic** [comment]
@yenda Is there anything specific blocking this one?

**Comment by yenda** [comment]
@goranjovic it needs to be tested

**Comment by annadanchenko** [comment]
@yenda 
### Issue 1. 
Recover option is shown instead of "<" button after account is created, so user can't get out from Console chat. Expected: Recover is changed to "<" after account is created in Console.
It does not happen on nightly builds from Feb 14 and 15. Both iOs and Android
screenshot_20180215-100534

Steps:
- install app and run it first time
- provide passwords in Console to create account
- try to get back from Console to Home

TF From 00:35 https://app.testfairy.com/projects/4803622-status/builds/7710515/sessions/2/?accessToken=oCSo2rfHXiX26ytIwgIXtqqCBJs

on build 17 https://jenkins.status.im/job/status-react/job/pull%20requests/view/change-requests/job/PR-3183/17/

### Issue 2
 If try to select recipient in the Wallet then error ` Assert failed: (not (nil? address))` is shown. Also no address is shown for the recipient. Both iOs and Android. Issue does not happen in the nightly builds for Feb 14 and 15.

Steps:
- install app, create account on 2 devices
- add device 1 to the contacts by scanning it's contact code. Send "ok" in 1:1 chat
- as device 2: in new 1:1 chat tap on Add to contacts to add device 1. Send "ok" message
- as device 1: open Wallet -> Send Transaction -> select recipient. Tap on the device 2 in the list of recipients. Error is shown

TF (01:40) https://app.testfairy.com/projects/4803622-status/builds/7710515/sessions/7/?accessToken=d1OSoaSGtM9yeJp9Zl3Ty7kjD4c

``` 01:43 I/ReactNativeJS: NAME: "Error"
01:43 I/ReactNativeJS: MESSAGE: Assert failed: (not (nil? address))
01:43 I/ReactNativeJS: 
01:43 I/ReactNativeJS: fill_request_details@index.android.bundle:12:7053224
01:43 I/ReactNativeJS: index.android.bundle:12:7059189
01:43 I/ReactNativeJS: index.android.bundle:12:4674916
01:43 I/ReactNativeJS: invoke_interceptor_fn@index.android.bundle:12:4609489
01:43 I/ReactNativeJS: invoke_interceptors@index.android.bundle:12:4609790
01:43 I/ReactNativeJS: execute@index.android.bundle:12:4611487
01:43 I/ReactNativeJS: handle@index.android.bundle:12:4621917
01:43 I/ReactNativeJS: re_frame$router$IEventQueue$_process_1st_event_in_queue$arity$1@index.android.bundle:12:4649186
01:43 I/ReactNativeJS: re_frame$router$IEventQueue$_run_queue$arity$1@index.android.bundle:12:4632568
01:43 I/ReactNativeJS: index.android.bundle:12:4635748
01:43 I/ReactNativeJS: re_frame$router$IEventQueue$_fsm_trigger$arity$3@index.android.bundle:12:4639959
01:43 I/ReactNativeJS: index.android.bundle:12:4633870
01:43 I/ReactNativeJS: index.android.bundle:32:1772
01:43 I/ReactNativeJS: b@index.android.bundle:32:628
01:43 I/ReactNativeJS: w@index.android.bundle:32:992
01:43 I/ReactNativeJS: callImmediates@index.android.bundle:32:3173
01:43 I/ReactNativeJS: value@index.android.bundle:27:2778
01:43 I/ReactNativeJS: index.android.bundle:27:1360
01:43 I/ReactNativeJS: value@index.android.bundle:27:2606
01:43 I/ReactNativeJS: value@index.android.bundle:27:1330
01:43 I/ReactNativeJS: [native code]
01:43 I/ReactNativeJS: value@index.android.bundle:27:938
01:43 I/ReactNativeJS: [native code]
01:43 I/ReactNativeJS: 
01:43 I/ReactNativeJS: *** ```


Recover, switch networks, log in/log out tested ok, cant return with back button from Sign in screen (main fix) is also ok. Need to retest after issue 1 and issue 2 in this comment are fixed

**Comment by jeluard** [comment]
@yenda Is this still relevant?

**Comment by oskarth** [comment]
PR over 2 months old, closing. If you feel this is in error, please re-open.

**Pull request closed without merging**
