### PR TITLE
fix notification screen displayed twice

### LINKED ISSUE #12276: Notifications screen appears twice during onboarding after recovering or creating multiaccount with Keycard
# Bug Report

## Problem 
If recover a multiaccount with Keycard and quickly tap `Maybe later`, the notifications screen will be opened again. If just stay a little on the notification screen, it blinks. More visible on Android

https://user-images.githubusercontent.com/67952253/124471234-ea459f00-dd9c-11eb-95d0-a701e59504c9.mp4

### Reproduction

1. Recover or create multiaccount with Keycard
2. Quickly tap `Maybe later` as soon as it appears

### Additional Information

- Status version: nightly 05/07
- Operating System: Android, iOS

### PR DESCRIPTION
**Pull request by bitgamma**
Fixes #12276 and some leftovers from #12306

### CODE REVIEW

**Review by briansztamfater — APPROVED** [review]

**Comment by churik** [comment]
@bitgamma 
sorry that in this PR, but found one more leftover from  https://github.com/status-im/status-react/pull/12306
But better to fix them asap, so just leaving it here.

### ISSUE 1: 'Migration successful' popup appears only after re-login if migrate multiaccount with resetting database

**Steps:**
1) restore multiaccount from seed phrase
2) migrate multiaccount to keycard with resetting database


**Expected result:**
"Migration successful" popup after migrating multiaccount

**Actual result:**
"Migration successful" popup after re-login with keycard

**OS:** IOS, Android

**Comment by qoqobolo** [comment]
Hey @bitgamma ! Thanks for the fix, works great now.

However, one more issue was found. Seems to be a leftover of https://github.com/status-im/status-react/pull/12306. Could you take a look and maybe fix it in this PR, please?

#### If migrate from a regular multiaccount to Keycard and do not reset the database first, but when asked for a password to move the database, tap `Skip`, then after 6-digit passcode confirmation nothing happens. So a user cannot complete migration flow.

**_Steps:_**
1. Recover regular multiaccount with mnemonic
2. Log out
3. Manage keys and storage
4. Select only `Move keystore file`
5. Enter seed phrase
6. Choose Keycard as a keystorage
7. Tap `Skip` on the "Enter password" screen
8. Create and confirm the passcode

**OS:** Android, iOS

https://user-images.githubusercontent.com/67952253/126350401-05e406ad-64ad-4279-a751-af4fd726040a.mp4

**Comment by bitgamma** [comment]
@churik @qoqobolo both issues are fixed now

**Comment by qoqobolo** [comment]
@bitgamma thanks a lot for fixing these leftovers too!
PR is ready to be merged.

**Pull request merged**
