### PR TITLE
Update instabug to 2.8.1

### LINKED ISSUE #3555: Upgrade Instabug SDK for new features
Instabug has several new features that can be beneficial to the test, UX, and product teams, and will be useful as an enhanced source in OKR measurement.

Some of the new features:

> Enhanced User Steps: To easily reproduce the bug reports your users have encountered and reported, Instabug automatically tracks the steps users have taken in the app before a bug is reported or a crash has occurred. We are enhancing our User Steps making them more structured, readable; alongside with capturing more gestures so you easily collect the needed insights to solve your bugs faster. We are capturing your UI components from text to labels and bringing them associated with the bug reports for better understanding. For iOS, we are now capturing the tap, long press, force touch, swipe, scroll and the pinch gestures. Check out the structure of the user steps you will receive on your dashboard for iOS in our docs.
> 
> New Surveys Experience: The more you interact and collect feedback from your users the better you know what to build and how. In-App Surveys will help you gain more insights from your users. Definitely, keeping your users away from any disruption is a key, that’s why we enhanced the in-App Surveys to provide a better, seamless experience that will increase the surveys responses through a better showing and dismissal experience.
> 
> Support For Cross-Platform Apps. You’ll receive one token to be used in your initialization code, and all your bugs and chats will be grouped in the same place.
> 
> Network Performance Monitoring.  We alert you about the three most common network request errors: network request failures, network requests that timed out, and network requests that took too long to complete.

https://github.com/Instabug/instabug-reactnative

In addition to upgrading, we have switched from two project for iOS and Android, and have setup a new RN Instabug project.  Both iOS and Android now have a single shared token: `758630ed52864cbad9c5eeeac596c60c`.

This should be moved to the .env file (@dmitryn suggestion).

### PR DESCRIPTION
**Pull request by dmitryn**
Fixes #3555 

### Summary

* Update Instabug to 2.8.1 so we could use new Instabug features like in-app surveys.
* Use original version not Status fork

status: ready

### CODE REVIEW

**Comment by dmitryn** [comment]
Have this error during `gradlew assemble`:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:preDebugBuild'.
> Android dependency 'com.android.support:appcompat-v7' has different version for the compile (24.2.0) and runtime (26.0.2) classpath. You should manually set the same version via DependencyResolution
```

`com.android.support:appcompat-v7` was added in https://github.com/status-im/status-react/pull/3086

@pacamara do you have an idea what causing this error?

**Comment by pacamara** [comment]
> com.android.support:appcompat-v7 was added in #3086
> @pacamara do you have an idea what causing this error?

Hi @dmitryn : `com.android.support:appcompat-v7` wasn't added in #3086, it was already a status-react dependency. The only change was to declare the dependency with `implementation` rather than the deprecated `compile`, i.e. : 
```
-    compile "com.android.support:appcompat-v7:23.0.1" 
+    implementation "com.android.support:appcompat-v7:23.0.1"
```
This change would only impact other projects using status-react as a library. So I doubt it's connected to the error here. Glad you got it fixed already!   :muscle:

**Review by flexsurfer — APPROVED** [review]

**Comment by dmitryn** [comment]
hi @pacamara !  You're right `com.android.support:appcompat-v7:23.0.1` was already there, my bad.
Thanks for clarifying!

**Review by jeluard — APPROVED** [review]

**Comment by asemiankevich** [comment]
dont see any reports coming to instabug in this PR, @dmitryn is looking into it. Something weird with token

**Comment by dmitryn** [comment]
>dont see any reports coming to instabug in this PR, @dmitryn is looking into it. Something weird with token

It turned out that we switched to new Instabug project "Status Beta". Please find reports there.

Also, i've checked automatic and manual surveys, both work on ios/android emulators. Automatic survey appears several seconds after you run the app. Manual - whenever you call `(.showSurveyWithToken instabug "SURVEY_TOKEN")`

screenshot 2018-03-30 17 02 30

**Comment by asemiankevich** [comment]
yep i can receive the surveys now
image

image

**Pull request merged**
