### PR TITLE
[#11468] Hide/show option for accounts in the wallet

### LINKED ISSUE #11468: Hide/show option for accounts in the wallet
# Feature Issue

Hide/show option for accounts in the wallet

### User Story

As a user, i want to hide accounts in the wallet

### Description

Deleting accounts is a complex issue, as a quick solution we could implement a hide feature

### Acceptance Criteria

It's possible to hide accounts in the wallet

### PR DESCRIPTION
**Pull request by flexsurfer**
fixes #11468

|Hide  | Manage | Manage |
| ------------- | ------------- | ------------- |
| image | image | image |

### CODE REVIEW

**Comment by qoqobolo** [comment]
@flexsurfer thanks for PR!

### ISSUE 1: No `Hide` option in the bottom sheet for newly generated Keycard accounts
The option is kept if account was generated before migration to Keycard.

**_Reproduction:_**
1. Create or recover Keycard multiaccount
2. Generate a new account
3. Tap `...` on the account to open bottom sheet

**_OS:_** iOS, Android

https://user-images.githubusercontent.com/67952253/129180668-d40545e1-3d80-432a-90ad-fa1b6873cfdf.mp4

### ISSUE 2: Screen gets faded when tapping `From` in tx dialog in 1-1 chat if all accounts are hidden (Android only)

**_Reproduction:_**
1. Hide all accounts in Wallet
2. Start 1-1 chat
3. Tap `Send tx`
4. Tap `From`

**_OS:_** Android

https://user-images.githubusercontent.com/67952253/129182543-4c8820b7-de42-4ca6-8be7-0a9bfe83854b.mp4

**Comment by hesterbruikman** [comment]
@flexsurfer apologies for the late review! Is it an option for you to pause this work without it going stale in the next days or week? As wallet lead I think it'll be good if @carlfairclough has a chance to review

**Comment by flexsurfer** [comment]
@hesterbruikman sure , np

**Comment by flexsurfer** [comment]
thanks @qoqobolo , fixed

**Comment by carlfairclough** [comment]
Thanks for highlighting this @hesterbruikman.

@flexsurfer just FYI we have some upcoming settings changes that may alter the architecture of this as we need to incorporate:
 - removing items from balance summaries
 - including watch-only accounts
 - network preferences
 - etc
 
That being said, I think we should go ahead and merge functionality that is ready now, rather than wait.

I would suggest that we alter the list items to have a shown/hidden icon rather than a checkbox. It makes it a little more clear what the feature does. If you need additional UI guidance please let me know

Icons:
https://github.com/status-im/status-react/blob/develop/resources/images/icons/show%402x.png
https://github.com/status-im/status-react/blob/develop/resources/images/icons/hide%402x.png

**Comment by flexsurfer** [comment]
thanks @carlfairclough 
image

**Comment by flexsurfer** [comment]
@qoqobolo ready for retesting

**Comment by qoqobolo** [comment]
@flexsurfer thank you! 

Tested on Android 11 and iOS 14:
- add new account
- watch only account
- add with seed phrase
- Keycard
- migration from regular account to Keycard
- dark mode
- hidden accounts in tx dialog in 1-1 chat and browser tab

No issues found.

Could you add accessibility-ids to these icons, please?
After that PR can be merged.

Screenshot 2021-08-17 at 12 42 38

**Comment by flexsurfer** [comment]
@qoqobolo by default they have label "icon" do you need a different one?

**Comment by churik** [comment]
@flexsurfer 
yes, basically we need some differences when account is hidden or not hidden. As far as I understand 'icon' will be in both cases

**Comment by flexsurfer** [comment]
ok , done

**Review by bitgamma — APPROVED** [review]

**Comment by flexsurfer** [comment]
@qoqobolo could you please confirm that we can merge and failed e2e not related, thanks

**Comment by churik** [comment]
e2e failures are not related to PR.

**Comment by flexsurfer** [comment]
mhm why has it closed status but not merged

**Pull request closed without merging**
