### PR TITLE
Kotlinify `im.status.ethereum.pushnotifications` package

### PR DESCRIPTION
**Pull request by alwx**
This PR converts the whole `im.status.ethereum.pushnotifications` package from Java to Kotlin

#### Platforms

- Android

status: ready

### CODE REVIEW

**Comment by siddarthkay** [comment]
Hi @alwx : seems like gradle task `react-native-status:compileReleaseKotlin` is failing and you have compilation errors to fix

**Comment by alwx** [comment]
@siddarthkay ok, fixing right now

**Comment by alwx** [comment]
@siddarthkay now finally done completely. It was actually not as easy as I was expecting but happy to take more tasks like that if needed!

**Comment by siddarthkay** [comment]
haha @alwx  yeah I figured! it was a lot of files, Thanks for the effort, I'll take a look :)

**Review by siddarthkay — APPROVED** [review]

**Comment by pavloburykh** [comment]
@alwx thanx for the PR. Please, provide QA notes in PR description on what should be tested. As far as I understand it is everything related to push notifications? Or something else should be covered/has beed affected?

**Comment by alwx** [comment]
@pavloburykh yes, that's correct — that's the package that is responsible for spawning the background service for handling push notifications which means testing it is making sure push notifications still work the same way they worked before.

**Comment by VolodLytvynenko** [comment]
Hi @alwx thank you for PR. Here is a found issue

## ISSUE 1: [Android] The Push Notifications are not received at all

### Steps:
1. `User B` enables PN notifications
2. `User B` backgrounds app
3. `User A` sends messages to any common chat with User B (1-1, group, community channel)
4. See if `User B` received PN about new message

### Actual result:
Push Notifications are not received

https://github.com/status-im/status-mobile/assets/52490791/075ab87c-1285-44c4-a809-cd09dce6522b



### Expected result:
Push Notifications are received

### Devices:
real device: Pixel 7a, Android 14
android studio: Pixel XL API 33

### Logs:
[Status-debug-logs.zip](https://github.com/status-im/status-mobile/files/14063425/Status-debug-logs.zip)

**Comment by flexsurfer** [comment]
hey @alwx still relevant?

**Comment by siddarthkay** [comment]
If you need help to look at that issue we could pair on it @alwx

**Comment by alwx** [comment]
@siddarthkay oh my, I've completely lost it after I got overwhelmed with UI work. Will check it out today and get back to you.

**Comment by flexsurfer** [comment]
stale, feel free to reopen when needed

**Pull request closed without merging**
