### PR TITLE
Adding hide? to react/navigation-wrapper if the onboarding is not passed

### PR DESCRIPTION
**Pull request by alwx**
Fixes the issue described here: https://status-im.slack.com/archives/C8KB9DR60/p1527088583001042

<blockquote><div><strong><a href="https://status-im.slack.com/archives/C8KB9DR60/p1527088583001042">Slack</a></strong></div></blockquote>

### CODE REVIEW

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/YnUkdC for branch PR-4407

<blockquote><div><strong><a href="https://i.diawi.com/YnUkdC">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/T28XMK for branch PR-4407

<blockquote><div><strong><a href="https://i.diawi.com/T28XMK">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/DeLwWi for branch PR-4407

<blockquote><div><strong><a href="https://i.diawi.com/DeLwWi">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/7zrZKG for branch PR-4407

<blockquote><div><strong><a href="https://i.diawi.com/7zrZKG">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by mandrigin** [comment]
@alwx since the voting went to `zIndex` approach, I'll close this PR if you don't mind...

**Pull request closed without merging**
