### PR TITLE
 [ISSUE #1858] Improved wallet main screen refresh

### LINKED ISSUE #1858: Improve main wallet screen pull-to-refresh
### User Story

As a user, I want to have a nice visual effect when doing a pull-to-refresh

### Description

When doing a pull-to-refresh the whole screen should be pullable (both `assets` and `actions` lists must not be pullable individually)
The visual indication then appears on top of the amount.

*Type*: Feature

### LINKED ISSUE #2819: Improve `pull-to-refresh` gesture performance on iOS
### Description

*Type*: Bug

*Summary*: this is the issue @Chad noticed during test session and it is clearly visible on my iPhone 5S: when I pull down the screen to refresh (transaction history or main wallet) it is not smooth and I can see 2 spinners sometimes for a second as well as the UI itself hangs for a second. TF does not show it perfectly but if you try to do it on real device i believe you will see it too (if even iPhone X has this issue) .
I can also reproduce it (but in not so obvious way) on iPhone 7.

image

image

NOTE: looks much better on Android

#### Expected behavior
I can refresh history and list of assets by `pull-to-refresh` gesture smoothly

### Reproduction
- Open Status
- Go to Wallet and Refresh
- Go to transaction history and refresh

### Additional Information
* Status version: develop
* Operating System: iOS

#### Logs
TF iPhone 5S: https://app.testfairy.com/projects/4803590-status/builds/7370858/sessions/10/?accessToken=gL2WTmOk1G1f06ABpXDAOoErePE

TF iPhone 7: https://app.testfairy.com/projects/4803590-status/builds/7371255/sessions/1/?accessToken=NDKe/Xv8yMw5r5CCGCcx0QkiDQk

### PR DESCRIPTION
**Pull request by jeluard**
fixes #1858
fixes #2819

### Summary:

Make sure the whole main wallet screen is refreshable, not individual lists.

### Steps to test:
- Open Status
- Navigate wallet
- Test refresh behaviour

status: ready

### CODE REVIEW

**Review by goranjovic — APPROVED** [review]

**Review by alwx — APPROVED** [review]

**Comment by asemiankevich** [comment]
@jeluard is there anything  we can do with this "jumping" on iOS (wallet main screen)? I do see this jumping (pulling breaks for a second) when pulling the screen down.

**Comment by jeluard** [comment]
@asemiankevich What kind of jumping is it?

**Comment by denis-sharypin** [comment]
I made a video of this jumping. It’s not a critical bug, just to achieve super smooth experience. Good job anyway! https://www.dropbox.com/s/cqjkrmc7pxx0mx2/Video%2024-02-2018%2C%2009%2049%2040.mov?dl=0

Also small issue: when I’m swiping this screen up I could see a blue background under white. It should ve white all the time. Maybe we can just expand height of a white rectangle? 
https://www.dropbox.com/s/pbuncsso55u5su7/Photo%2024-02-2018%2C%2009%2049%2053.png?dl=0

<blockquote><div>Dropbox</div><div><strong><a href="https://www.dropbox.com/s/cqjkrmc7pxx0mx2/Video%2024-02-2018%2C%2009%2049%2040.mov?dl=0">Video 24-02-2018, 09 49 40.mov</a></strong></div><div>Shared with Dropbox</div></blockquote>
<blockquote><div>Dropbox</div><div><strong><a href="https://www.dropbox.com/s/pbuncsso55u5su7/Photo%2024-02-2018%2C%2009%2049%2053.png?dl=0">Photo 24-02-2018, 09 49 53.png</a></strong></div><div>Shared with Dropbox</div></blockquote>

**Comment by jeluard** [comment]
Sure will look at the jumping.

I noticed the blue part but could not find a workaround to it. It was either that or having the spinning area with a blue backround.

**Comment by jeluard** [comment]
@asemiankevich Made changes, please take a look!

**Comment by asemiankevich** [comment]
@jeluard I dont see spinner anymore when pull-to-refresh on ios :( 

as well as no assets shown on android http://prntscr.com/iurg8g

**Comment by denis-sharypin** [comment]
@jeluard  layout of the screen works much better! thanks!

**Comment by jeluard** [comment]
@asemiankevich Pushed some changes

**Comment by asemiankevich** [comment]
@jeluard no spinner still and jumping is back in latest build

**Comment by jeluard** [comment]
@asemiankevich Can't get both spinner and no jump on iOS. I sugest we merge this as it's much better than develop and bounty to get the spinner.

**Comment by asemiankevich** [comment]
so can we have previous build then? With smooth scrolling but without spinner . @denis-sharypin

**Comment by jeluard** [comment]
Yes I restored it.

**Comment by asemiankevich** [comment]
then please merge it and create a bounty for jumping (if you dont mind)

**Pull request merged**
