### PR TITLE
[issue-13545] Tab component

### LINKED ISSUE #13545: UI Component - Tab
This issue is to track the creation of the component: **Tab**

You can access the link at https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Mobile-Components?node-id=57%3A13215.

Please have a chat with the design team before starting with the component, and don't forget to add sizing to the issue

### PR DESCRIPTION
**Pull request by ibrkhalil**
fixes #13545 
status: WIP

### CODE REVIEW

**Comment by flexsurfer** [comment]
hey @ibrkhalil i believe Tab is already implemented `quo2.components.tab`

**Comment by flexsurfer** [comment]
quo2 is the new designs

**Comment by ibrkhalil** [comment]
So the Tab and Tabs components don't need any work ?

**Comment by flexsurfer** [comment]
yes don't need

**Pull request closed without merging**
