### PR TITLE
Update status-go

### PR DESCRIPTION
**Pull request by cammellos**
status: ready

### CODE REVIEW

**Review by mandrigin — APPROVED** [review]

**Comment by rasom** [comment]
build failed because of `NotifyUsers`

**Comment by cammellos** [comment]
@rasom I am a bit confused and a bit behind with current development, what is the current situation with NotifyUsers?

**Comment by pedropombeiro** [comment]
> @rasom I am a bit confused and a bit behind with current development, what is the current situation with NotifyUsers?

@cammellos I'm in the process of merging the new method signature in status-go and status-react. See https://github.com/status-im/status-go/pull/1352 and https://github.com/status-im/status-react/pull/7294.
Basically, that method has been replaced with `SendDataNotification` (to be more explicit and avoid confusion). Not sure if it makes sense to include those changes here?

**Comment by cammellos** [comment]
@PombeirP thanks, probably then that PR should go first, is that correct?

**Comment by pedropombeiro** [comment]
Right.

**Pull request closed without merging**
