### PR TITLE
Bug/Show onboarding for transaction from chat [#4456]

### LINKED ISSUE #4456: New user is not prompted to set up his wallet when signing a transaction from chat
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to set up my wallet before signing any transactions so that I can remember my signing phrase and be sure that all my transaction are secure.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Newly created user who has not set up his wallet can sign a transaction without setting up his wallet if sending it from a chat

#### Expected behavior
User should be redirected to wallet screen first and prompted to set up his wallet before signing a transaction

#### Actual behavior
User is redirected to wallet send transaction view and can sign in a transaction

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Create new account
- Start one-one chat
- Click Commands button - > `/send`
- Input valid amount and click Send message button 

### Additional Information
* Status version: `09c11e90 (5aae87a)`, nightly build from May 25
* Operating System: Android, iOS

### PR DESCRIPTION
**Pull request by flexsurfer**
fixes #4456

### CODE REVIEW

**Review by goranjovic — APPROVED** [review]

**Review by jeluard — APPROVED** [review]

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/iFNvGj for branch PR-4545

<blockquote><div><strong><a href="https://i.diawi.com/iFNvGj">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/NX2t87 for branch PR-4545

<blockquote><div><strong><a href="https://i.diawi.com/NX2t87">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/null for branch PR-4545

<blockquote><div><strong><a href="https://i.diawi.com/null">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/pKEPE5 for branch PR-4545

<blockquote><div><strong><a href="https://i.diawi.com/pKEPE5">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by asemiankevich** [comment]
can't send funds until i set up my wallet (1x1 chat , group chat, wallet)

**Pull request merged**
