### PR TITLE
[#13116] Load audio messages from http server

### LINKED ISSUE #13116: Load audio messages from http server
# Feature Issue

We've moved base64 images to the HTTP server https://github.com/status-im/status-react/pull/13039
We need to do the same for audio messages because currently, we pass them through the RN bridge and its slow

### PR DESCRIPTION
**Pull request by flexsurfer**
fixes #13116

### CODE REVIEW

**Review by Parveshdhull — APPROVED** [review]

**Review by bitgamma — APPROVED** [review]

**Comment by churik** [comment]
@flexsurfer 
Can't play audio messages (IOS/Android)

https://user-images.githubusercontent.com/4557972/155555506-5fb6c9ad-1452-4372-a344-b6f6168a0d95.mp4
[logs (5).zip](https://github.com/status-im/status-react/files/8133719/logs.5.zip)

**Comment by flexsurfer** [comment]
@churik thanks, lets try next build

**Comment by flexsurfer** [comment]
@churik  thanks, fixed

**Comment by qoqobolo** [comment]
@flexsurfer thank you, it works fine now.
PR is ready to be merged.

**Pull request merged**
