### PR TITLE
fix: take lightclient bad peer logic from waku

### PR DESCRIPTION
**Pull request by chaitanyaprem**
### Summary
changes mentioned in  https://github.com/waku-org/go-waku/pull/1241
A simple logic to delete bad peers based on dial failures so that they don't get reused. this may help stabilize filter subscriptions faster. 

..### Testing notes

#### Platforms

- Android
- iOS

#### Areas that maybe impacted
network switch
startup of app
bringing to foreground

##### Functional

- 1-1 chats
- public chats
- group chats

### Steps to test

- Open Status
- ...
- Step 3, etc.

status: ready

### CODE REVIEW

**Comment by chaitanyaprem** [comment]
@pavloburykh i see that 1 test has failed. 
Is this a failure that is noticed with other builds as well?
Do let me know if i can go ahead with the merge the status-go PR.

**Comment by pavloburykh** [comment]
> @pavloburykh i see that 1 test has failed. Is this a failure that is noticed with other builds as well? Do let me know if i can go ahead with the merge the status-go PR.

Hey @chaitanyaprem! Thanks for the PR. Failed e2e is not PR related. I have also performed manual testing and message reliability improved a lot. Status-go PR is ready to be merged. 

@qfrank would appreciate if you can bump status go version in mobile develop once corresponding go changes are merged by @chaitanyaprem. Thank you.

**Comment by chaitanyaprem** [comment]
Closing this as underlying status-go PR is merged.

**Comment by chaitanyaprem** [comment]
> Hey @chaitanyaprem! Thanks for the PR. Failed e2e is not PR related. I have also performed manual testing and message reliability improved a lot. Status-go PR is ready to be merged.

@ilmotta @pavloburykh @churik  i am wondering if we can include this change in 2.32 since it is not released yet since there is a significant reliability improvements noticed. Or if not a minor version 2.32.1 can be released to include these changes. wdyt?

**Comment by churik** [comment]
to 2.32 nothing can be included for sure, we can ask @ilmotta if it makes sense to do minor update

**Comment by ilmotta** [comment]
Thank you for the fix @chaitanyaprem. The mobile builds are final already, we have approvals from app stores and we have a tentative date to release Status early January after holidays. The fix in status-go was picked up by mobile PR https://github.com/status-im/status-mobile/pull/21865 and tested already. We will merge today onto mobile `develop`.

As you all suggested, let's make a quick & safe 2.32.1 release right after we publish 2.32.0 to users.

**Pull request closed without merging**
