### PR TITLE
[16866] Action Drawer design review

### LINKED ISSUE #16866: Design review: context drawer
- [x] 1. Align title and icon - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3678:7819&mode=design#510573462)  
- [x] 2. The title and icon should be the same color - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3678:7819&mode=design#510048139)

### PR DESCRIPTION
**Pull request by ibrkhalil**
fixes #16866 
status: ready
| Light | Dark |
| ------------- | ------------- |
|   |   |

### CODE REVIEW

**Review by smohamedjavid — APPROVED** [review]

**Review by J-Son89 — APPROVED** [review]

**Review by Francesca-G — APPROVED** [review]
Looks good to me :)

Adding follow up required for the view profile icon which isn't updated.

design:
Screenshot 2023-08-23 alle 09 13 56

implementation:
Screenshot 2023-08-23 alle 09 13 59

**Comment by ibrkhalil** [comment]
> Looks good to me :)
> 
> Adding follow up required for the view profile icon which isn't updated.
> 
> design: Screenshot 2023-08-23 alle 09 13 56
> 
> implementation: Screenshot 2023-08-23 alle 09 13 59

Will update it here

**Comment by ibrkhalil** [comment]
> Looks good to me :)
> 
> Adding follow up required for the view profile icon which isn't updated.
> 
> design: Screenshot 2023-08-23 alle 09 13 56
> 
> implementation: Screenshot 2023-08-23 alle 09 13 59

Fixed

**Comment by VolodLytvynenko** [comment]
hi @ibrkhalil please don't merge this PR now

**Comment by VolodLytvynenko** [comment]
@ibrkhalil  I noticed that this PR transferred to the merge column without QA approval, although the PR had the request-manual-QA label.

I'd like to remind you that at the moment the process for PRs is as follows:

1. The PR must receive at least one approval from the dev review

2. Then the PR should be moved to the e2e tests column to run autotests (for all PRs)

3. If the developer is 100% sure that changes in the PR cannot introduce new issues or regression, the request-manual-QA label can be omitted. Otherwise, the label should be added.

4. Then you should wait for manual testing from someone on the QA team.
If no issues are found, the QA will add the tested-OK label.

5. Then, depending on changes in the PR, this may also be sent for design review (corresponding column on the board).
If the designer finds issues (now Francesca is doing it), they add the followup required label.
After that, the PR is moved to the Merge column and can be merged.

If a design review is not required, the QA moves the PR to the merge column immediately.

You can also find the PR workflow instructions here (although it's a little outdated and doesn't include the new design review

**Comment by ibrkhalil** [comment]
> @ibrkhalil  I noticed that this PR transferred to the merge column without QA approval, although the PR had the request-manual-QA label.
> 
> 
> 
> I'd like to remind you that at the moment the process for PRs is as follows:
> 
> 
> 
> 1. The PR must receive at least one approval from the dev review
> 
> 
> 
> 2. Then the PR should be moved to the e2e tests column to run autotests (for all PRs)
> 
> 
> 
> 3. If the developer is 100% sure that changes in the PR cannot introduce new issues or regression, the request-manual-QA label can be omitted. Otherwise, the label should be added.
> 
> 
> 
> 4. Then you should wait for manual testing from someone on the QA team.
> 
> If no issues are found, the QA will add the tested-OK label.
> 
> 
> 
> 5. Then, depending on changes in the PR, this may also be sent for design review (corresponding column on the board).
> 
> If the designer finds issues (now Francesca is doing it), they add the followup required label.
> 
> After that, the PR is moved to the Merge column and can be merged.
> 
> 
> 
> If a design review is not required, the QA moves the PR to the merge column immediately.
> 
> 
> 
> You can also find the PR workflow instructions here (although it's a little outdated and doesn't include the new design review

Understood, I really didn't want to take from QA time since it's only a matching to figma type of task.

**Comment by VolodLytvynenko** [comment]
> Understood, I really didn't want to take from QA time since it's only matching to figma type of task.

Got it, thank you for clarifying. Since this is a component PR, it can be directly moved to the "Design review" column, and the manual testing step can be skipped. And then there's no need to add a "request-manual-qa" label. Additionally, please make sure to add the PR to the e2e column before

**Comment by VolodLytvynenko** [comment]
@ibrkhalil Thank you for your patience. PR can be merged

**Pull request merged**
