### PR TITLE
Fixes #2668: Feature/repo cleanup

### LINKED ISSUE #2668: General repository cleanup
### User Story

As a developer, I want to have a clean repository with no old files and clean structure.

### Description

* remove irrelevant files (verify they are not used anymore): (e.g. `CHANGELOG.md`, ..)
* verify if `shim.js` is still used, remove if not
* remove `env/test` and simplify `env/dev/user.clj` accordingly
* migrate `docs` to wiki.status.im

*Type*: Bug

### PR DESCRIPTION
**Pull request by placer14**
Fixes #2668

### Summary:

This PR removes some unused files and some recommended removals as prescribed in #2668.

### Steps to test:
- Verified by running tests and ensuring production build does not fail

status: ready

### CODE REVIEW

**Review by jeluard — COMMENTED** [review]
Thanks! Could you validate dev and release compilation still work as expected?

Also could you migrate the doc to the wiki?

**Comment by placer14** [comment]
@jeluard (https://wiki.status.im/index.php?title=Frequently_Asked_Questions&diff=prev&oldid=1262) was the only part of the markdown missing from the wiki that needed adding.

**Comment by placer14** [comment]
I also mentioned that I did test the release build in my PR submission. I verified using `lein prod-build`, `lein repl`, and ran tests via `lein test-cljs` from within the status docker container that I've been helping @charlesg3 with in [this branch (still due for PR)](https://github.com/charlesg3/status-react/tree/feature/docker-compose-dev). Please let me know if you require additional verification.

**Comment by jeluard** [comment]
Could you make some basic test on the release app deployed on a phone? It's not clear if there could be impact due to `shim.js` being removed.

Also do we have the `refactoring-guidelines.md` content somewhere in the wiki?

**Comment by ghost** [comment]
@placer14 Do you need any help with this one? I can help.

**Comment by oskarth** [comment]
Closing PR due to inactivity. If you feel this was in error, feel free to re-open this.

cc @poiga if you want to pick this up.

**Comment by ghost** [comment]
@oskarth I have submitter the PR  #2911

**Comment by oskarth** [comment]
@poiga Ah yes, thanks!

**Pull request closed without merging**
