### PR TITLE
Testing update status go

### PR DESCRIPTION
**Pull request by pavloburykh**
Created to test https://github.com/status-im/status-go/pull/3944

### CODE REVIEW

**Comment by richard-ramos** [comment]
@pavloburykh . status-go version is updated now!

**Comment by pavloburykh** [comment]
@richard-ramos thank you! 

Please take a look at the issue. 

### ISSUE 1 App crashes on joining community

**Steps:**

1. User A (mobile) requests joining community
2. See if User A joins community 

**Actual result:** app crashes on joining community.

[Status-debug-logs (59).zip](https://github.com/status-im/status-mobile/files/12657006/Status-debug-logs.59.zip)

https://github.com/status-im/status-mobile/assets/97245802/17f59bd1-eb20-4dbd-8a69-9f4f15956217

**Comment by cammellos** [comment]
> @richard-ramos thank you!
> 
> Please take a look at the issue.
> 
> ### ISSUE 1 App crashes on joining community
> **Steps:**
> 
> 1. User A (mobile) requests joining community
> 2. See if User A joins community
> 
> **Actual result:** app crashes on joining community.
> 
> [Status-debug-logs (59).zip](https://github.com/status-im/status-mobile/files/12657006/Status-debug-logs.59.zip)
> 
>  crash_join_comm.mp4

@pavloburykh do you have the raw logcat for this bug please?

**Comment by pavloburykh** [comment]
> @pavloburykh do you have the raw logcat for this bug please?

Sure @cammellos! Here it is
[crashlog_000.log.zip](https://github.com/status-im/status-mobile/files/12659403/crashlog_000.log.zip)

**Comment by pavloburykh** [comment]
looks like this is the problem @cammellos @richard-ramos 
```
09-19 14:48:24.500   843   843 E audit   : type=1400 audit(1695124104.495:105843): avc:  denied  { bind } for  pid=25769 comm="Thread-13" scontext=u:r:untrusted_app:s0:c250,c263,c512,c768 tcontext=u:r:untrusted_app:s0:c250,c263,c512,c768 tclass=netlink_route_socket permissive=0 SEPF_SM-A525F_12_0001 audit_filtered
09-19 14:48:24.525 25769     0 E Go      : panic: runtime error: invalid memory address or nil pointer dereference
09-19 14:48:24.525 25769     0 E Go      : [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x75cc0d3f60]
09-19 14:48:24.525 25769     0 E Go      : 
09-19 14:48:24.525 25769     0 E Go      : goroutine 1793 [running]:
09-19 14:48:24.526 25769     0 E Go      : github.com/status-im/status-go/wakuv2.(*Waku).StorePubsubTopicKey(...)
09-19 14:48:24.526 25769     0 E Go      : 	github.com/status-im/status-go/wakuv2/waku.go:1538
09-19 14:48:24.526 25769     0 E Go      : github.com/status-im/status-go/eth-node/bridge/geth.(*gethWakuV2Wrapper).StorePubsubTopicKey(0x40001b0020?, {0x40056bc4e0?, 0xb7?}, 0x4003e48c08?)
09-19 14:48:24.526 25769     0 E Go      : 	github.com/status-im/status-go/eth-node/bridge/geth/wakuv2.go:244 +0x20
09-19 14:48:24.526 25769     0 E Go      : github.com/status-im/status-go/protocol/transport.(*Transport).StorePubsubTopicKey(...)
09-19 14:48:24.526 25769     0 E Go      : 	github.com/status-im/status-go/protocol/transport/transport.go:674
09-19 14:48:24.526 25769     0 E Go      : github.com/status-im/status-go/protocol.(*Messenger).UpdateCommunityFilters(0x4001f10000, 0x4001413110, 0x30?)
09-19 14:48:24.526 25769     0 E Go      : 	github.com/status-im/status-go/protocol/messenger_communities.go:2020 +0x84
09-19 14:48:24.526 25769     0 E Go      : github.com/status-im/status-go/protocol.(*Messenger).handleCommunityShardAndFiltersFromProto(0x4001f10000, 0x4001413110, 0x0?, 0x0?, {0x0, 0x0, 0x0})
09-19 14:48:24.526 25769     0 E Go      : 	github.com/status-im/status-go/protocol/messenger_communities.go:2988 +0xf8
09-19 14:48:24.526 25769 25861 E GoLog   : panic: runtime error: invalid memory address or nil pointer dereference
09-19 14:48:24.526 25769     0 E Go      : github.com/status-im/status-go/protocol.(*Messenger).HandleCommunityRequestToJoinResponse(0x4001f10000, 0x4003e06990, 0x40010a7d60, 0x40007de820?)
09-19 14:48:24.526 25769 25861 E GoLog   : [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x75cc0d3f60]
```

**Comment by richard-ramos** [comment]
Thank you! with that error i have enough information to solve the issue!

**Comment by richard-ramos** [comment]
@pavloburykh Issue's been fixed!

**Comment by pavloburykh** [comment]
> @pavloburykh Issue's been fixed!

Thank you @richard-ramos!

I am facing another issue, pleas take a look. 

### ISSUE 2 Mobile and desktop users do not see each other's messages in communities

I tested between mobile and Desktop 0.9.90 (go-version 0.167.0)

**Steps:**

1. Desktop user creates community and invites Mobile user
2. Mobile user joins community
3. Desktop and Mobile users send messages in community channel
4. Check if users see each other's messages

**Actual result:** Mobile and desktop users do not see each other's messages in community channel

[Desktop_user.log](https://github.com/status-im/status-mobile/files/12672756/Desktop_user.log)
[Mobile_user_geth.zip](https://github.com/status-im/status-mobile/files/12672757/Mobile_user_geth.zip)
[Android_logcat.log.zip](https://github.com/status-im/status-mobile/files/12672755/Android_logcat.log.zip)

https://github.com/status-im/status-mobile/assets/97245802/bc69819f-2ea0-4435-b405-a8cc3fd30aab

**Comment by richard-ramos** [comment]
> @pavloburykh: Mobile and desktop users do not see each other's messages in community channel

:thinking: does mobile <-> mobile work?

**Comment by pavloburykh** [comment]
> > @pavloburykh: Mobile and desktop users do not see each other's messages in community channel
> 
> 🤔 does mobile <-> mobile work?

yes

**Comment by pavloburykh** [comment]
@richard-ramos should current PR go version be compatible with current develop go version (or go-version 0.167.0) in terms of messaging in communities? Cause I am facing the bug while testing between mobile build from current PR and master Desktop 0.9.90 (go-version 0.167.0). 

Could it be the problem that we need to use for testing Desktop version that includes https://github.com/status-im/status-go/pull/3944 ?

**Comment by richard-ramos** [comment]
Both versions should be compatible! I'll try to reproduce the bug

**Comment by richard-ramos** [comment]
desktop <-> desktop works too :-/ weird
I imagine it has something to do with the encryption for the communities

**Comment by richard-ramos** [comment]
@pavloburykh :) I was finally able to fix it!!
The problem was that the message was not being sent in the right [pubsub topic](https://rfc.vac.dev/spec/23/#pubsub-topics)

**Comment by richard-ramos** [comment]
Ah no. I identified an err in the version being used. Will update once it's solved

**Comment by richard-ramos** [comment]
There was no error, it's all good :)

**Comment by pavloburykh** [comment]
@richard-ramos thanx! 

Unfortunately [ISSUE 2](https://github.com/status-im/status-mobile/pull/17305#issuecomment-1727589995) is still reproducible for me. You can try to reproduce it using this android PR [build](https://status-im-mobile-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-230920-230557-c5166f-pr17305-universal.apk) and Desktop app. 

Also, please take a look at another issues

### ISSUE 3 Currated communities are not fetched

**Steps:**

1. Open Discover communities screen
2. See if communities are fetched

**Actual result:** communities are not fetched. Re-login doesn't help

[Status-debug-logs (64).zip](https://github.com/status-im/status-mobile/files/12683669/Status-debug-logs.64.zip)

https://github.com/status-im/status-mobile/assets/97245802/2eb5e950-6c00-49e6-9ef6-ceab46022226

**Comment by pavloburykh** [comment]
### ISSUE 4 Community status does not change from Pending to Joined after request approval. 

@richard-ramos this one is being constantly caught by our e2e and causes majority of tests to fail. So we consider this issue to be e2e blocker for us. 

At the same time, I am unable to reproduce this issue manually. A have attached geth log below, please check. 

**Steps:**

1. User A (community admin) invites User B to open community 
2. User B requests to join community
3. User A admin node stays online

**Actual result:** community status does not automatically changes for User B to Joined but remains in Pending

[User_A_admin.log](https://github.com/status-im/status-mobile/files/12683920/User_A_admin.log)
[User_B.log](https://github.com/status-im/status-mobile/files/12683921/User_B.log)


This is video from failed test run demonstrating User B steps https://app.eu-central-1.saucelabs.com/tests/8f7f8888b2d5429aa20ddf348f81775c?auth=f89e2c70f70268611ae513c5d28e0d1a#88

**Comment by richard-ramos** [comment]
I think I managed to fix the issues. Here you can see the communities, the `Joined` state, and messages going back and forth between desktop and mobile








image

**Comment by pavloburykh** [comment]
@richard-ramos thank you! Could you please rebase both go and mobile branches? They are currently outdated. After that I will proceed with testing.

**Comment by pavloburykh** [comment]
@richard-ramos meanwhile I have checked latest builds with fixes. ISSUE 3 is fixed. 

ISSUE 4 seems to be unrelated to PR changes. We are facing it in other PRs too, so I will log it separately. I have reproduced this issue manually in your PR again, so it is not fixed.  

Unfortunately [ISSUE 2](https://github.com/status-im/status-mobile/pull/17305#issuecomment-1727589995) is still reproducible. Mobile users do not see any messages in community created on Desktop except own messages (See video below). 

On this video IOS and Android users are members of same community which is created on Desktop. 

There are couple of issues: 
1. They do not see any messages except own messages
2. Android user does not see IOS user in community member list (I do not suppose it is device/OS related). 

[Android_user.zip](https://github.com/status-im/status-mobile/files/12700779/Android_user.zip)
[IOS_user.zip](https://github.com/status-im/status-mobile/files/12700781/IOS_user.zip)

https://github.com/status-im/status-mobile/assets/97245802/afebbd79-0589-4264-bd74-8620ffc3717c

I have asked @churik to check and she also reproduced this issue. 

I have tried old/new desktop users, old/new communities but result is the same. 

@richard-ramos let me know what can I do to help you investigate/resolve the issue?

**Comment by richard-ramos** [comment]
I'm so confused. I'm getting messages between mobile and desktop as shown in https://github.com/status-im/status-mobile/pull/17305#issuecomment-1730110554
Are these the exact steps to reproduce the issue?
```
Steps:

    Desktop user creates community and invites Mobile user
    Mobile user joins community
    Desktop and Mobile users send messages in community channel
    Check if users see each other's messages
```

**Comment by churik** [comment]
@richard-ramos what desktop build are you using?

**Comment by richard-ramos** [comment]
I'm using https://github.com/status-im/status-desktop/pull/12033  which uses the same status-go version. Perhaps there's a breaking change? I'll try using latest `master`

**Comment by churik** [comment]
ofc, because we are using the current master, and seems they are incompatible.

**Comment by richard-ramos** [comment]
:) With latest version, messages between Desktop `master` and Mobile work!

**Comment by pavloburykh** [comment]
@richard-ramos thank you! Now users see each other's messages in community. 

Could you please rebase both go and mobile branches as they are quite outdated (mobile is 30 commits behind develop)? I tried to rebase mobile by myself but there are conflicts that should be resolved. After that we will continue testing and re-run e2e.  Thank you!

**Comment by richard-ramos** [comment]
Done! sorry for the delay!

**Comment by pavloburykh** [comment]
@richard-ramos hi! Thank you for the update. 

As you know, currently we are experiencing data delivery issues which kinda blocks me from proper testing of this PR.

Delivery issues also exist in our nightly builds, but it seems to me that those issues are even more visible in current PR.  

Below I attach video demonstrating messages sent from IOS user are not delivered to Android in communities and chats. The video is long, you can check first 1-2 minutes. Messages appear for receiver after re-login but after some time messages delivery gets stuck again. 

[Android_receiver_logs.zip](https://github.com/status-im/status-mobile/files/12727180/Android_receiver_logs.zip)
[IOS_sender_logs.zip](https://github.com/status-im/status-mobile/files/12727291/IOS_sender_logs.zip)


https://github.com/status-im/status-mobile/assets/97245802/54469699-4909-491b-bcf6-d442b856fd5a

Probably we need to wait for fleet update and perform another round of testing after that in order to localize the source of the issue. Tell WDYT? 

cc @churik

**Comment by pavloburykh** [comment]
Hello @richard-ramos! We have finally merged messages reliability fix into develop. Could you please rebase go and mobile branches once again so we can perform another round of testing? Thank you!

**Comment by pavloburykh** [comment]
> Hello @richard-ramos! We have finally merged messages reliability fix into develop. Could you please rebase go and mobile branches once again so we can perform another round of testing? Thank you!

hey @richard-ramos! Mentioning you once again in case you missed message above.

**Comment by richard-ramos** [comment]
@pavloburykh
done!

**Comment by pavloburykh** [comment]
Thank you @richard-ramos. PR is tested and ready to be merged. 
@cammellos are we going to bump go version in order to include these changes https://github.com/status-im/status-go/pull/3944 ?

**Comment by pavloburykh** [comment]
closing as these changes are already in develop.

**Pull request closed without merging**
