### PR TITLE
adjust padding for QR Images

### PR DESCRIPTION
**Pull request by siddarthkay**
This PR allows adjusts the padding in QR Images around the profile to match the design.

All the work is on status-go side.

Relevant status-go PR : https://github.com/status-im/status-go/pull/3510

#### Platforms
- Android
- iOS

status: ready

### CODE REVIEW

**Review by qfrank — APPROVED** [review]

**Review by ajayesivan — APPROVED** [review]

**Comment by VolodLytvynenko** [comment]
hi @siddarthkay thank you for PR. One issue if found:

## ISSUE 1: The user is not navigated to the scanned profile
### Precondition:
- Both user_a and user_b use the same PR build

### Steps to reproduce:
1. User_A: Login to app
2. User_A: Scan the QR of User_B
3. User_A: Tap 'Open in Status' button -> select 'Status PR'

### Actual result:
The User_A is not navigated directly to the profile page of User_B

https://github.com/status-im/status-mobile/assets/52490791/9f16cd89-2b7e-4d76-8c0a-a0a9285d3a7b


### Expected result:
The User_A is navigated directly to the profile page of User_B
How it works on the latest nightly:

https://github.com/status-im/status-mobile/assets/52490791/4bb79826-d570-432d-9109-c63c73f13c39



### Devices:
- real device: iPhone 11 Pro Max, IOS 16
- real device: Huawei p20 light, Android 9

**Comment by siddarthkay** [comment]
Hi @VladimrLitvinenko : Thanks for testing, I will have a look at this!

**Comment by siddarthkay** [comment]
Hi @VladimrLitvinenko : I tried the following setup to replicate this issue.
Device A -> iOS Simulator running this build generates QR code.
Device B -> My iPhone 11 where i installed the PR build. ( this device also contains old status App which I use).

On scanning The app shows no option to open Status PR and directly opens up old Status App.
So what i do in this case is to copy the url and open it in safari. In safari I get an option to open this link via Status PR.
And when I do that I am navigated to the correct profile.

Here is a screen recording demonstrating that experience :

https://github.com/status-im/status-mobile/assets/64726664/7b64b1bf-99e2-431a-a2ce-f607b20c487f

Maybe I missed something while trying to replicating the issue, could you please check and let me know :)

**Comment by VolodLytvynenko** [comment]
Apologies for the confusion. It appears that the issue mentioned in [PR #15782 ](https://github.com/status-im/status-mobile/pull/15782#issuecomment-1549689304) is not yet resolved, as it remains reproducible even in the latest nightly build. This explains why I encountered the issue within the current PR.

Thanx to @pavloburykh for conducting the investigation.

**Comment by VolodLytvynenko** [comment]
@siddarthkay no issues from my side. PR ready to be merged. Created an separate issue  https://github.com/status-im/status-mobile/issues/15991 related to https://github.com/status-im/status-mobile/pull/15782#issuecomment-1549689304

**Comment by pavloburykh** [comment]
> Apologies for the confusion. It appears that the issue mentioned in [PR #15782 ](https://github.com/status-im/status-mobile/pull/15782#issuecomment-1549689304) is not yet resolved

@siddarthkay hello! Small clarification on that: reproducible only on IOS for me. Android seems to work correctly.

**Comment by siddarthkay** [comment]
not yet

**Pull request merged**
