### PR TITLE
Remove dApps tab from Wallet

### LINKED ISSUE #20793: Remove dApps tab from wallet
# Bug Report

## Problem 
[comment]: # (A problem description)
We shouldn't show the dApps tab in the wallet, as we have a dedicated button at the top of the account for connected dApps already.

#### Expected behavior
No dApps tab in the wallet

#### Actual behavior
dApps tab present in the wallet

Image

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by alwx**
fixes #20793 

#### Platforms

- Android
- iOS

status: ready

### CODE REVIEW

**Review by clauxx — APPROVED** [review]
Looks good!

**Review by ulisesmac — APPROVED** [review]
Thanks for the PR!

**Review by J-Son89 — APPROVED** [review]

**Review by shivekkhurana — APPROVED** [review]

**Comment by qoqobolo** [comment]
@alwx no issues so far, but I've got one question:

Can/should we make the tabs non-scrollable in case the screen is wide enough to fit all the tabs? Is it possible at all, what do you think? 
The device on the video is Pixel 7a

https://github.com/user-attachments/assets/3de69d14-6d45-4897-bd96-0169fdd69776

**Comment by clauxx** [comment]
> @alwx no issues so far, but I've got one question:
> 
> Can/should we make the tabs non-scrollable in case the screen is wide enough to fit all the tabs? Is it possible at all, what do you think? The device on the video is Pixel 7a
> 
>  video_2024-07-23_14-31-36.mp4

We could, but unclear how easy it could be. I think it could be a separate issue, but not specific for the dapp-team I guess.

**Comment by qoqobolo** [comment]
> > @alwx no issues so far, but I've got one question:
> > Can/should we make the tabs non-scrollable in case the screen is wide enough to fit all the tabs? Is it possible at all, what do you think? The device on the video is Pixel 7a
> > video_2024-07-23_14-31-36.mp4
> 
> We could, but unclear how easy it could be. I think it could be a separate issue, but not specific for the dapp-team I guess.

I agree, asking here just because it became visible after removing the dapps tab.

@alwx thanks for the PR, it's ready to be merged.

**Pull request merged**
