### PR TITLE
Fix mute chat & reset navigation

### LINKED ISSUE #12191: Mute can't be enabled and leads to disappering of 1-1 chat  until relogin
# Bug Report

## Problem 

Mute button doesn't work visually, and after muting 1-1 chat disappears from home screen until relogin.
Not reproducible on 1.13

#### Expected behavior
Can mute user

#### Actual behavior
When tapping on mute: 

https://user-images.githubusercontent.com/4557972/120653058-a2bbb280-c480-11eb-9693-4f7e1f7cd124.mp4

### Reproduction

1) User А: create chat with User B
2) User A: open options > View profile > Mute

### Additional Information

- Status version: RC 1.14 
- Operating System: iOS

[comment]: # (Please, add logs/notes if necessary)

### LINKED ISSUE #12196: Skip 'Accept and join' view when navigating back from public chat joined from referral
# Bug Report

## Problem 
When Status installed from a 'public chat registration' referral link - we show 'Accept and Join' view which. When tap on Accept button - user is redirected to public chat. However, when navigating back via <- top-left Back button - user is navigated back to 'Accept and Join' view. We have to skip(to remove) this view after 'Accept and Join' button pressed.

#### Expected behavior
User navigated to Chats main view from public view after 'Accept and join' pressed

#### Actual behavior

https://user-images.githubusercontent.com/8749671/120666706-778f8e00-c495-11eb-88c6-4d39b5a0d855.mov

### Reproduction
- Install Status
- Open Status from the 'public chat registration' referral link
- Create new account till the 'Accept and join' view is opened
- Tap 'Accept and Join' button
- Tap top-left Back button

**Actual result:** 'Accept and Join' view displayed

### Additional Information
- Status version: Release/Develop 1.14
- Operating System: Android

### PR DESCRIPTION
**Pull request by cammellos**
Fixes: #12191
Fixes: #12196

### CODE REVIEW

**Comment by flexsurfer** [comment]
if we don't need this in release, i would postpone it to react navigation PR, if we still want to merge it we need to check all places with navigation-reset? in the codebase , because they worked without this param before and may be broken now

**Comment by churik** [comment]
I'm afraid that we need this for release. At least part for Mute user.
Not sure about fix for referrals 
cc @Serhy

**Comment by cammellos** [comment]
I can split the fixes if needed, also I found an issue I need to fix, I'll update the PR

**Comment by Serhy** [comment]
@cammellos @flexsurfer @churik , 
'Mute contact' issue #12191 we need to fix, because it's medium-high severity. However if it would be only second issue with referrals i'd say we may go with it because there is an easy workaround.
So if #12191 could be fixed without toughing `navigation-reset?` let's split the fix.

**Review by flexsurfer — APPROVED** [review]

**Comment by Serhy** [comment]
In latest build `51fcab5` the referral related navigation issue fixed, however `Mute user` still present.

**Comment by cammellos** [comment]
In the next build should be fixed

**Comment by Serhy** [comment]
Looks good to me with iOS14 and Android 11
#12191 is fixed.
#12196 - still present but agreed as OK to move into next release.

Failed e2e test is a false fail (network latency issue)

**Pull request merged**
