### PR TITLE
refactor: reformat all clojure code with zprint

### PR DESCRIPTION
**Pull request by yqrashawn**
status: ready

### CODE REVIEW

**Comment by ilmotta** [comment]
image

**Review by ilmotta — APPROVED** [review]

**Review by siddarthkay — APPROVED** [review]

**Comment by smohamedjavid** [comment]
rocket_1f680

**Review by smohamedjavid — APPROVED** [review]

**Review by J-Son89 — APPROVED** [review]
🚀🚀🚀🚀🚀🚀

**Comment by smohamedjavid** [comment]
@yqrashawn - the commit is `unverified` and this will block the merge. you might need to upload the signature on GitHub or commit with the correct email address.

**Review by jo-mut — APPROVED** [review]

**Comment by flexsurfer** [comment]
image

**Comment by flexsurfer** [comment]
> @yqrashawn - the commit is `unverified` and this will block the merge. you might need to upload the signature on GitHub or commit with the correct email address.

thats fine. it will be signed by github on merge

**Comment by yqrashawn** [comment]
> thats fine. it will be signed by github on merge

can't click the merge button.. `The base branch requires all commits to be signed`

**Comment by siddarthkay** [comment]
> > thats fine. it will be signed by github on merge
> 
> can't click the merge button.. `The base branch requires all commits to be signed`

I can amend your commit and merge if you'd like? @yqrashawn

**Comment by yqrashawn** [comment]
trying the `merge-pr.sh`

**Comment by yqrashawn** [comment]
No luck, the script just signed the pr with my own GPG key. gonna merge this way

**Comment by yqrashawn** [comment]
merged 🎉

**Comment by yqrashawn** [comment]
Note:

if there are too much conflicts try:

1. rebase onto the commit before this PR, https://github.com/status-im/status-mobile/commit/39e29cfb5
2. run 
```sh
make shell TARGET=default
clojure-lsp clean-ns
ALL_CLOJURE_FILE=$(git ls-files | grep -e \.clj$ -e \.cljs$ -e \.cljc$ -e \.edn$) && \
clojure-lsp clean-ns && \
zprint '{:search-config? true}' -sw $ALL_CLOJURE_FILE && \
zprint '{:search-config? true}' -sw $ALL_CLOJURE_FILE
```
3. commit the above changes
4. rebase on to `origin/develop`

**Pull request merged**
