### PR TITLE
JC/Fraschetti - Feature flag descoped features from MVP to streamline initial release

### PR DESCRIPTION
**Pull request by FFFra**
Notes: Need fixes included at https://github.com/status-im/status-mobile/pull/19667#pullrequestreview-2005493910

### Summary

This PR is part of the Montenegro OffSite discussions regarding our initial release. 

Items Feature Flagged:
- edit derivation path
- wallet/send/contacts

Removed:
- confirm address -> info icon
- create account -> import from keycard

status: ready !

### CODE REVIEW

**Review by J-Son89 — APPROVED** [review]
Nice one @FFFra!!

**Comment by J-Son89** [comment]
@status-im/mobile-qa this just adds feature flags for some descoped features and removes some  unneeded buttons too.
Can we skip manual Qa?

**Comment by qoqobolo** [comment]
> @status-im/mobile-qa this just adds feature flags for some descoped features and removes some unneeded buttons too. Can we skip manual Qa?

Yes, manual testing can be skipped for this PR.
@FFFra @J-Son89 please resolve the conflicts and move the PR to the E2E column.
Also, ping us again if the test results are unclear and need review.
Thank you!

**Comment by FFFra** [comment]
@qoqobolo  More feature flags were added due to this PR https://github.com/status-im/status-mobile/pull/19583

**Review by ulisesmac — APPROVED** [review]

**Pull request merged**
