### PR TITLE
update status go version

### LINKED ISSUE #20206: Point status go to release/0.179.x
# Problem

This https://github.com/status-im/status-mobile/pull/20164 was merged but the status-go branch had not been merged, We want to merge the pr on status-go, create a tag and point status-mobile to the updated status-go tag

## Acceptance Criteria

Status mobile points to the latest update of status-go tag

### PR DESCRIPTION
**Pull request by jo-mut**
The pr updates status-go version to the current tag which has the changes made in the pr  https://github.com/status-im/status-mobile/pull/20164

fixes https://github.com/status-im/status-mobile/issues/20206

### CODE REVIEW

**Review by flexsurfer — APPROVED** [review]

**Review by siddarthkay — APPROVED** [review]

**Review by ilmotta — APPROVED** [review]

**Comment by jo-mut** [comment]
@status-im/mobile-qa this pr in my opinion does not need manual-qa. The changes on status-go have already been merged here ilmotta/partially-fix-slow-login, it just updates the status-go version on status-mobile to point to the corrent tag instead of the branch.

with your approval I will merge it

**Comment by pavloburykh** [comment]
@yevh-berdnyk could you please review e2e failures here? Thank you! 

@jo-mut once @yevh-berdnyk approves the PR - we can merge it

**Comment by jo-mut** [comment]
@pavloburykh thank you

**Comment by yevh-berdnyk** [comment]
> ## 73% of end-end tests have passed

Hi @jo-mut, e2e failures are not PR related, thanks!

**Pull request merged**
