### PR TITLE
React native 0.57.5

### PR DESCRIPTION
**Pull request by yenda**
#7074 

status: wip

### CODE REVIEW

**Review by mandrigin — CHANGES_REQUESTED** [review]
does this RN branch contains our 2 patches for React Native?

**Comment by yenda** [comment]
@mandrigin it contains 2 of the patches that we have made. I asked you in chat if you can have a look at https://github.com/status-im/react-native/commit/aa51c6e7a17776f7277f7f2124467fc0d41d6841 because the merge conflict when cherry picking might suggest it has been fixed upstream.
If I understand correctly inverted scrollview scrolling isn't properly inverted on android P? Maybe that could just be tested

**Comment by mandrigin** [comment]
@yenda yeah, I fixed this issue upstream: https://github.com/facebook/react-native/pull/21117
Didn't know that it is already in the release. That means, this patch can be removed.

**Review by mandrigin — APPROVED** [review]

**Comment by mandrigin** [comment]
but I'm pretty sure that this patch was added only to **0.57.6**

**Comment by jakubgs** [comment]
Why the change to `maven { url "https://maven.google.com" }`?

**Comment by jakubgs** [comment]
The only package visible under `com.google.gms` in https://dl.google.com/dl/android/maven2/index.html seems to be `oss-licenses`. Did they somehow remove their own package?

What's interesting is that you are trying to get `4.2.0` but we use `4.1.0` in `develop` but that fails in the same way too:
https://ci.status.im/job/status-react/job/combined/job/mobile-android/9696/console

<blockquote><div><strong><a href="https://dl.google.com/dl/android/maven2/index.html">Google's Maven Repository</a></strong></div></blockquote>
<blockquote><div><strong><a href="https://ci.status.im/job/status-react/job/combined/job/mobile-android/9696/console">status-react » combined » mobile-android #9696 Console [Jenkins]</a></strong></div></blockquote>

**Comment by jakubgs** [comment]
It's just gone:
```
% curl -sv https://dl.google.com/dl/android/maven2/com/google/gms/google-services/4.2.0/google-services-4.2.0.pom
< HTTP/2 404
```
Even the older versions:
```bash
$ curl -sv https://dl.google.com/dl/android/maven2/com/google/gms/google-services/3.1.0/google-services-3.1.0.pom
< HTTP/2 404
```

**Comment by jakubgs** [comment]
This is weird, I can see `4.2.0` here:
https://mvnrepository.com/artifact/com.google.gms/google-services/4.2.0
~~But the version is not listed here:~~
~~https://mvnrepository.com/artifact/com.google.gms/google-services~~
Ah now, it's here: https://mvnrepository.com/artifact/com.google.gms/google-services?repo=bt-android-tools

We could try adding this repo and see what happens:
```
maven { url "http://mvnrepository.com/artifact" }
```

**Comment by jakubgs** [comment]
Or you can try:
```
maven { url "https://dl.bintray.com/android/android-tools/" }
```

**Comment by yenda** [comment]
@jakubgs yes that's the one I used

**Comment by jakubgs** [comment]
This repo seems to work for android in my fix PR: https://github.com/status-im/status-react/pull/7062/files
```
maven { url "http://mvnrepository.com/artifact" }
```

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/status-im/status-react/pull/7062">add mvnrepository.com for gradle by jakubgs · Pull Request #7062 · status-im/status-react</a></strong></div><div>Possible fix for:
* What went wrong:
A problem occurred configuring root project &#39;StatusIm&#39;.
&gt; Could not resolve all files for configuration &#39;:classpath&#39;.
   &gt; Could not find ...</div></blockquote>

**Comment by jakubgs** [comment]
The fact that it only tries JCenter:
```
02:50:42      Searched in the following locations:
02:50:42        - https://jcenter.bintray.com/com/android/tools/build/gradle/2.3.3/gradle-2.3.3.pom
02:50:42        - https://jcenter.bintray.com/com/android/tools/build/gradle/2.3.3/gradle-2.3.3.jar
```
Indicates to me that the dependency that pulls in `2.3.3` has only `jcenter.bintray.com` defined in repos and ignores the ones we have defined, otherwise this list would have been much longer.

Which dependency pulls this in? Maybe we need to upgrade it.

**Comment by vkjr** [comment]
@yenda, do you plan to continue work on this one?

**Comment by jakubgs** [comment]
This needs to be rebased, it's till using an old github updating method.

**Comment by mandrigin** [comment]
it makes sense to upgrade to https://github.com/facebook/react-native/releases/tag/v0.58.0 already

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/facebook/react-native">facebook/react-native</a></strong></div><div>A framework for building native apps with React. Contribute to facebook/react-native development by creating an account on GitHub.</div></blockquote>

**Comment by mandrigin** [comment]
v0.59.0 is almost there, there is no need not to wait a bit and upgrade to that one

**Comment by jakubgs** [comment]
And by the time we finish work on upgrading to `0.59.0` there will be `0.60.0` out :D.

**Comment by mandrigin** [comment]
@jakubgs nah, I was waiting for my last patch to land, so now we can get rid of our fork of RN for the time being.

**Comment by oskarth** [comment]
Since this PR is not actively being worked on (>1w), I suggest we close it. We can always reopen it once it becomes priority again. Would you mind closing it @yenda?

**Comment by mandrigin** [comment]
yeah, I wanted to keep it open until RN 0.59 release, but still there are already conflicts I think it makes no sense to do so, closing then.

**Pull request closed without merging**
