### PR TITLE
fastlane: debug failed Diawi uploads

### PR DESCRIPTION
**Pull request by jakubgs**
We've been having more and more failed Diawi uploads:
```
[10:16:00]: Start uploading file to diawi. Please, be patient. This could take some time.
[10:16:04]: Processing file...
[10:16:06]: Processing file...
[10:16:08]: Processing file...
[10:16:10]: Processing file...
[10:16:12]: Processing file...
[10:16:14]: File is not processed.
[10:16:14]: Try to upload file by yourself: StatusIm-200121-100440-39b3aa-release.ipa
```
~~In order to debug this I'm enabling `callback_emails` for [`fastlane-plugin-diawi`](https://github.com/pacification/fastlane-plugin-diawi) and adding the `--verbose` flag to Fastlane call in hope that we can get a reason for these issues.~~

Changes:
* Use our fork of [fastlane-plugin-diawi](https://github.com/status-im/fastlane-plugin-diawi/tree/add-timeout-option)
* Use the newly added `last_hope_attempts_backoff` to 5 seconds
* Set the `last_hope_attempts_count` to 5

### CODE REVIEW

**Review by yenda — APPROVED** [review]

**Review by flexsurfer — APPROVED** [review]

**Comment by jakubgs** [comment]
Well, I got the email and apparently it did get uploaded, just the Fastlane task didn't get back the URL:
diawi_upload_email
This might be an issue with some changes on Diawi backend that might require plugin changes.

**Comment by jakubgs** [comment]
I've already reported this to the plugin repo: https://github.com/pacification/fastlane-plugin-diawi/issues/10
No response so far. Either I fix it myself or we have to find some workaround.

**Comment by jakubgs** [comment]
Here is where the message comes from:
https://github.com/pacification/fastlane-plugin-diawi/blob/513995f6f/lib/fastlane/plugin/diawi/actions/diawi_action.rb#L136
The code is pretty simple:
```ruby
status_ok = 2000
status_in_progress = 2001
status_error = 4000

while polling_count > polling_attempts  do
    response = RestClient.get STATUS_CHECK_URL, {params: {token: token, job: job}}

    begin
        response
    rescue RestClient::ExceptionWithResponse => error
        UI.important("Check file status request error:")
        UI.important(error)
        polling_attempts += 1
        sleep(2)
        next
    end

    json = JSON.parse(response.body)

    case json['status']
    when status_ok
        link = "#{DIAWI_FILE_LINK}/#{json['hash']}"
        UI.success("File successfully uploaded to diawi. Link: #{link}")
        Actions.lane_context[SharedValues::UPLOADED_FILE_LINK_TO_DIAWI] = link
        return

    when status_in_progress
        UI.message("Processing file...")

    when status_error
        UI.important("Error uploading file to diawi.")
        UI.important(json['message'])
    else
        UI.important("Unknown error uploading file to diawi.")
    end

    polling_attempts += 1
    sleep(2)
end

UI.important("File is not processed.")
```
It seems to me like something on Diawi backend changed and the `status` field returned in the response JSON contains only the `status_in_progress` code and then times out after all attempts have been tried.

It's a pity the wait time is hardcoded at 2 seconds, wish we could increase that. I could probably make a PR for that. But for now all I can do is bump `last_hope_attempts_count`.

**Comment by jakubgs** [comment]
I've created a PR with the plugin repo to add backoff option: https://github.com/pacification/fastlane-plugin-diawi/pull/12

**Review by yenda — APPROVED** [review]

**Comment by jakubgs** [comment]
Looks like setting a 5 second timeout has worked:
```
[12:32:49]: Start uploading file to diawi. Please, be patient. This could take some time.
[12:32:54]: Processing file...
[12:32:59]: Processing file...
[12:33:05]: Processing file...
[12:33:10]: File successfully uploaded to diawi. Link: https://i.diawi.com/uKuypQ
```
https://ci.status.im/job/status-react/job/prs/job/ios/job/PR-9862/5/console

**Pull request merged**
