### PR TITLE
Added password validation for Restore Access flow #1224

### LINKED ISSUE #1224: Add password validation for Restore Access flow
### User Story

As a user I should not be able to login with a password that doesn't match security criteria (ex. password length <6 symbols)

### Description

*Type*: Bug

#### Expected behavior
[comment]: As a user I should not be able to proceed with a password that doesn't match security criteria (ex. password length <6 symbols)

#### Actual behavior
[2017_05_18_16_50_28 - logcat.txt](https://github.com/status-im/status-react/files/1011101/2017_05_18_16_50_28.-.logcat.txt)
[comment]: I am able to login with insecure password , for ex. "1" after I restore an access to account

### Reproduction
[comment]: https://drive.google.com/open?id=0B7h1U1joPifRazlFaEgxeU9lc2M

- Open Status
- Set up a password 
- Copy the secure phrase
- Tap Switch Account
- Tap Restore Access
- Enter the secure phrase and enter insecure password (like "1")
- Tap Restore Access
- Select newly created account and proceed with the newly created password

### Solution
Add the password validation for Restore Access flow exactly the same as for the setting up new password flow

### Additional Information
* Operating System: Android
* Status version: 0.9.7+
* [2017_05_18_16_50_28 - logcat.txt](https://github.com/status-im/status-react/files/1011117/2017_05_18_16_50_28.-.logcat.txt)

### PR DESCRIPTION
**Pull request by ghost**
[comment]: fixes #1224)

Summary:Added password validation for Restore Access flow

Steps to test:
-Open Status
-Set up a password
-Copy the secure phrase
-Tap Switch Account
-Tap Restore Access
-Enter the secure phrase and enter insecure password (like "1")
-Observe "Restore Access" Enabled

status: ready

### CODE REVIEW

**Review by oskarth — APPROVED** [review]

**Review by yenda — APPROVED** [review]

**Comment by yenda** [comment]
Thank you for your contribution ! The PR as it is would already be good to merge. 

It made me realize that we currently have multiple specs for the same thing so I created an issue about it: https://github.com/status-im/status-react/issues/2432

If you want you can tackle this as well (for passwords at least)

**Comment by ghost** [comment]
so you can only merge this one after #2432 done?

**Comment by yenda** [comment]
@poiga no unless you want to include that in the PR it will be merged after testing

**Comment by ghost** [comment]
next time :) I think.

**Comment by asemiankevich** [comment]
I have opened https://github.com/status-im/status-react/issues/2436 that has to be fixed before merge 
Tested `0.9.10-364-g79ff253a+ (1921)`. Moreover @yenda @poiga I dont see `Recover` button in this bracnch when the account is above to set up . It worth be tested too. Please, fix. 
image

**Comment by ghost** [comment]
#2436 looks like is fixed now.

**Comment by oskarth** [comment]
@poiga Thanks for being a contributor and pinging us! #2436 is still open. Once this is resolved and closed we'll move this one back to ready for testing.

**Comment by asemiankevich** [comment]
@oskarth is it possible to check the same logic is applied for password validation process in `restore account` as it is now implemented for `create account` ? I agree with @annadanchenko that https://github.com/status-im/status-react/issues/2436 is only one of possible cases and major thing we need to be sure in that logic is the same for both screens (create and restore account). I assume it could be done by code review, so @oskarth could you please assist with that?

Once this is done I will perform several checks (like https://github.com/status-im/status-react/issues/2436) and we will close the initial PR.
cc @poiga

**Comment by oskarth** [comment]
@asemiankevich I lack the context to give you a quick and correct answer, and I currently don't have bandwidth available to look into the matter. Pinged Clojure team.

**Comment by asemiankevich** [comment]
@oskarth can we process the item to `ready-for-testing` ?

**Comment by asemiankevich** [comment]
@poiga @oskarth can we please rebase so I can get links for the builds in the logs

**Comment by poiga** [comment]
Sure

**Comment by asemiankevich** [comment]
@poiga Audrius please do  :)

**Comment by poiga** [comment]
done.

**Comment by asemiankevich** [comment]
@poiga @oskarth I still can't find links to builds in console output, does anyone know how to fix that?

**Comment by poiga** [comment]
What do you mean by that? You want to locate the binary created?

**Comment by oskarth** [comment]
@asemiankevich Hm, I can't even find the PR here: https://jenkins.status.im/job/status-react/job/pull%20requests/ - do you know where it usually shows up in Jenkins for external contributors?

@poiga For our CI, we have issues with build notifications so we print build URL in our logs. After your rebase it is present here: https://github.com/poiga/status-react/blob/bug/password-validation-on-restore-1224/Jenkinsfile#L75

However, we have a slightly different pipeline for external contributors (PRs submitted not from repo branch), so right now I can't even find the build for this PR. We'll investigate.

**Comment by asemiankevich** [comment]
@poiga can you please rebase again?

**Comment by ghost** [comment]
rebased.

**Comment by asemiankevich** [comment]
@poiga Recover button is still missing in iOS build. However I can see it on Android

image

Can you please check this?

**Comment by ghost** [comment]
oops - I do not have IOS device neither my laptop is powerful enough to emulate it. Could it be raised as a separate ticket or something like this. Sorry about it.

**Comment by asemiankevich** [comment]
@janherich @oskarth could you please assist? The problem is - in current PR that we want to merge we are missing `Recover` button on iOS device when setting up account. So if we merge this - i assume the same would be in develop? Or not?

**Comment by ghost** [comment]
I don't believe that password validation is somehow related to this button appearance...

**Comment by oskarth** [comment]
I too doubt this is related to @poiga's changes so I think we should merge it if it fixes the linked issue.

@asemiankevich Can you confirm if you see this regression in current `develop` on iOS and then possibly open a new issue? (The only difference between @poiga's branch and develop is https://github.com/status-im/status-react/pull/2567 and https://github.com/status-im/status-react/pull/2471 so it's still possible one of those commits fixes the regression in current develop, even if I don't see how exactly).

**Comment by asemiankevich** [comment]
@oskarth this is not happening in develop `0.9.11d411 - 1557.411`

**Comment by ghost** [comment]
I would help for sure, but can not do IOS on my setup for now. Sorry about.

**Comment by asemiankevich** [comment]
lets merge this and I will verify the regression in develop

**Comment by oskarth** [comment]
Merging directly without code signing due to https://github.com/status-im/status-react/issues/2636. Thanks for your patience @poiga!

**Pull request merged**
