### PR TITLE
use timesource(synced) to generate/validate server cert time

### LINKED ISSUE #17458: App stuck in "Syncing" state after scanning QR mobile-mobile
### Steps:
1. mobile device 1 generates the sync QR
2. mobile device 2 scans the QR (now the "oops something went wrong" page is shown)
3. mobile device 2 tap 'try again' button 

### Actual behavior
App Stuck in "syncing" state

### Expected behavior
User is redirected to "syncing" screen

### Additional info:
Private wi-fi network is used with good signal

### Logs:
[android_logcat4 (2).txt](https://github.com/status-im/status-mobile/files/12765017/android_logcat4.2.txt)

### ENV:
Nightly [29 Sep 2023]

### PR DESCRIPTION
**Pull request by qfrank**
fixes [issue](https://github.com/status-im/status-mobile/issues/17458#issuecomment-1781135163)

#### Platforms

- Android
- iOS

#### Areas that maybe impacted
local pair

### Steps to test

- prepare 2 devices to do local pair
- change one of the device time: alter the system time of the device to make it less accurate, such as adjusting it 1 day ahead or 1 day behind the correct time.
- do local pair and check the result

status: ready

### CODE REVIEW

**Review by smohamedjavid — APPROVED** [review]
Nice! 🚀

**Review by ibrkhalil — APPROVED** [review]
Thank you very much!
I think that'll fix the issue that I assigned to myself that's related to syncing

**Review by siddarthkay — APPROVED** [review]

**Comment by VolodLytvynenko** [comment]
Hi @qfrank could you please rebase this status go https://github.com/status-im/status-go/tree/chore/use-timesource-to-generate-cert  PR?

**Comment by qfrank** [comment]
> Hi @qfrank could you please rebase this status go https://github.com/status-im/status-go/tree/chore/use-timesource-to-generate-cert PR?

done @VolodLytvynenko

**Comment by VolodLytvynenko** [comment]
Hi @qfrank thank you for PR. Unfortunatly the issue is still reproduced for me. 

## ISSUE 1: Failed sync after  changing date on device
### Steps to Reproduce:
1. Change the date on any device (no matter device which generates the sync code or which scans it)
2. Attempt to sync with the current device.

### Actual Result:
The sync process fails

### Expected Result:
The sync should be successful even after changing the date 

### Logs:
[logs 2.zip](https://github.com/status-im/status-mobile/files/13228337/logs.2.zip)

### Device:
- Real device: Pixel 7a, Android 13
- Real device: iPhone 11 Pro max, IOS 16

**Comment by qfrank** [comment]
> Hi @qfrank thank you for PR. Unfortunatly the issue is still reproduced for me.
> 
> ## ISSUE 1: Failed sync after changing date on device
> ### Steps to Reproduce:
> 1. Change the date on any device (no matter device which generates the sync code or which scans it)
> 2. Attempt to sync with the current device.
> 
> ### Actual Result:
> The sync process fails
> 
> ### Expected Result:
> The sync should be successful even after changing the date
> 
> ### Logs:
> [logs 2.zip](https://github.com/status-im/status-mobile/files/13228337/logs.2.zip)
> 
> ### Device:
> * Real device: Pixel 7a, Android 13
> * Real device: iPhone 11 Pro max, IOS 16

Hi @VolodLytvynenko , can you provide both device logs so that i can check the time? thank you. Also this PR should only be tested on mobile devices, and each mobile device should use the same version with this PR, no desktop!

**Comment by VolodLytvynenko** [comment]
@qfrank Here are the logs:

## Case 1:
IOS device logs. This device generates the QR (this device set +1 hour)
[logs.zip](https://github.com/status-im/status-mobile/files/13228661/logs.zip)


Android device logs. This device scans the QR (This device has automaticall set up for date)
[Status-debug-logs.zip](https://github.com/status-im/status-mobile/files/13228673/Status-debug-logs.zip)


## Case 2:
Android device logs. This device generates the QR (This device has -1 hour)
[Status-debug-logs (1).zip](https://github.com/status-im/status-mobile/files/13228744/Status-debug-logs.1.zip)


IOS device logs. This device scans the QR (This device has automaticall set up for date)
[logs (2).zip](https://github.com/status-im/status-mobile/files/13228738/logs.2.zip)

**Comment by qfrank** [comment]
> @qfrank Here are the logs:
> 
> ## Case 1:
> IOS device logs. This device generates the QR (this device set +1 hour) [logs.zip](https://github.com/status-im/status-mobile/files/13228661/logs.zip)
> 
> Android device logs. This device scans the QR (This device has automaticall set up for date) [Status-debug-logs.zip](https://github.com/status-im/status-mobile/files/13228673/Status-debug-logs.zip)
> 
> ## Case 2:
> Android device logs. This device generates the QR (This device has -1 hour) [Status-debug-logs (1).zip](https://github.com/status-im/status-mobile/files/13228744/Status-debug-logs.1.zip)
> 
> IOS device logs. This device scans the QR (This device has automaticall set up for date) [logs (2).zip](https://github.com/status-im/status-mobile/files/13228738/logs.2.zip)

should be fixed now 🙂 @VolodLytvynenko

**Comment by VolodLytvynenko** [comment]
Hi @qfrank unfortunately the issue is still reproduced:

### CASE 1:
1. `Android` sets date in the past (-1 day)
2. `Android` generates the QR code
3. `IOS` sets date automatically
4. `IOS`scan the QR

Android logs:
[Status-debug-logs.zip](https://github.com/status-im/status-mobile/files/13236803/Status-debug-logs.zip)

IOS logs:
[logs.zip](https://github.com/status-im/status-mobile/files/13236810/logs.zip)


### CASE 2:
1. `Android` sets date automatically
2. `Android` generates the QR code
3. `IOS`sets date in the future (+1 day)
4. `IOS`scans the QR

Android logs:
[Status-debug-logs (1).zip](https://github.com/status-im/status-mobile/files/13236928/Status-debug-logs.1.zip)

IOS logs:
[logs (2).zip](https://github.com/status-im/status-mobile/files/13236915/logs.2.zip)


### CASE 3:
1. `IOS` sets date in the future (+ 1 hour)
2. `IOS` generates the QR code
3. `Android`sets date automatically
4. `Android`scans the QR

IOS logs:
[logs (3).zip](https://github.com/status-im/status-mobile/files/13237005/logs.3.zip)

Android logs:
[Status-debug-logs (2).zip](https://github.com/status-im/status-mobile/files/13237015/Status-debug-logs.2.zip)

**Comment by qfrank** [comment]
> Hi @qfrank unfortunately the issue is still reproduced:
> 
> ### CASE 1:
> 1. `Android` sets date in the past (-1 day)
> 2. `Android` generates the QR code
> 3. `IOS` sets date automatically
> 4. `IOS`scan the QR
> 
> Android logs: [Status-debug-logs.zip](https://github.com/status-im/status-mobile/files/13236803/Status-debug-logs.zip)
> 
> IOS logs: [logs.zip](https://github.com/status-im/status-mobile/files/13236810/logs.zip)
> 
> ### CASE 2:
> 1. `Android` sets date automatically
> 2. `Android` generates the QR code
> 3. `IOS`sets date in the future (+1 day)
> 4. `IOS`scans the QR
> 
> Android logs: [Status-debug-logs (1).zip](https://github.com/status-im/status-mobile/files/13236928/Status-debug-logs.1.zip)
> 
> IOS logs: [logs (2).zip](https://github.com/status-im/status-mobile/files/13236915/logs.2.zip)
> 
> ### CASE 3:
> 1. `IOS` sets date in the future (+ 1 hour)
> 2. `IOS` generates the QR code
> 3. `Android`sets date automatically
> 4. `Android`scans the QR
> 
> IOS logs: [logs (3).zip](https://github.com/status-im/status-mobile/files/13237005/logs.3.zip)
> 
> Android logs: [Status-debug-logs (2).zip](https://github.com/status-im/status-mobile/files/13237015/Status-debug-logs.2.zip)

Were you changing system time while keep status app opened?
I can't reproduce it except change system time while keep status app opened, but i think this is a rare and pretty special case and we can ignore it? @VolodLytvynenko cc @cammellos

**Comment by VolodLytvynenko** [comment]
> Were you changing system time while keep status app opened? I can't reproduce it except change system time while keep status app opened, but i think this is a rare and pretty special case and we can ignore it? @VolodLytvynenko cc @cammellos

@qfrank Just checked it one more time. 
In each case, I did the following pre steps:
1. Both devices have closed apps
2. `Android` device set up a date (-1 day)
3. `Android` device create new account
4. `Android` generates a new QR code
5. `IOS` device scans the current QR

### Actual result:
`iOS` device becomes stuck in the sync process after scanning the QR code from the Android device

IOS logs:
[logs.zip](https://github.com/status-im/status-mobile/files/13238221/logs.zip)

Android logs:
[Status-debug-logs.zip](https://github.com/status-im/status-mobile/files/13238231/Status-debug-logs.zip)

### Additional info:
I thought it might be a network issue, and after setting date as automatically, the sync was successful

**Comment by churik** [comment]
@qfrank @VolodLytvynenko 
tried https://github.com/status-im/status-mobile/pull/17771#issuecomment-1790554600 on the PR build and was unable to reproduce. 
Devices are synced.

**Comment by VolodLytvynenko** [comment]
@qfrank Thank you for your work and for your patience. The PR is ready to be merged

**Pull request merged**
