### PR TITLE
Request to join community screen is not scrollable on Android #15748

### LINKED ISSUE #15748: Request to join community screen is not scrollable on Android
The current bug is causing a large portion of our end-to-end tests to fail.

This issue is reproducible on devices with relatively small screens that require scrolling the page.

**Preconditions:** User A and User B are mutual contacts. User A - is a community admin, User B is Android device. 

**Steps:** 
1. User A shares community to User B
2. User B opens community screen => tap Request join community button
3. See if Request join community scree is scrollable

**Actual result:** Request join community screen is not scrollable

https://user-images.githubusercontent.com/97245802/234505750-6a4dcb1f-fc64-4016-8d58-bf0aaffa2063.mp4

**Expected result:** Request join community screen is scrollable
### Additional Information

- Status version: nightly 
- Operating System: Android

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by flexsurfer**
fixes #15748

### CODE REVIEW

**Review by Parveshdhull — APPROVED** [review]

**Review by J-Son89 — APPROVED** [review]
nice!

**Review by churik — APPROVED** [review]

**Comment by churik** [comment]
@flexsurfer 
please, mind my commit while squashing, thank you for quick fix!

**Comment by flexsurfer** [comment]
it seems like there is only one your commit :)

**Comment by churik** [comment]
yeah, I was faster this time :)

**Pull request merged**
