### PR TITLE
Update ko.json

### PR DESCRIPTION
**Pull request by jinhojang6**
update and sort the ko.json file in alphabetical order

### CODE REVIEW

**Review by mandrigin — APPROVED** [review]

**Comment by jinhojang6** [comment]
Tested the Jenkins builds

**Review by rasom — APPROVED** [review]

**Comment by annadanchenko** [comment]
> ### Jenkins Builds
> ❔	Commit	#️⃣	Finished (UTC)	Duration	Platform	Result
> ✔️	[66f203a](https://github.com/status-im/status-react/commit/66f203a6cfda92f346b28866fa27988b82f34559)	[#1](https://ci.status.im/job/status-react/job/prs/job/macos/job/PR-7966/1/)	2019-04-12 09:37:11	~19 min	`macos`	[📦 dmg](https://status-im-prs.ams3.digitaloceanspaces.com/StatusIm-190412-091752-66f203-pr.dmg)
> ✔️	[66f203a](https://github.com/status-im/status-react/commit/66f203a6cfda92f346b28866fa27988b82f34559)	[#1](https://ci.status.im/job/status-react/job/prs/job/android-e2e/job/PR-7966/1/)	2019-04-12 10:02:42	~45 min	`android-e2e`	[📦 apk](https://status-im.ams3.digitaloceanspaces.com/StatusIm-190412-091740-66f203-e2e.apk)
> ✔️	[66f203a](https://github.com/status-im/status-react/commit/66f203a6cfda92f346b28866fa27988b82f34559)	[#1](https://ci.status.im/job/status-react/job/prs/job/linux/job/PR-7966/1/)	2019-04-12 10:12:14	~54 min	`linux`	[📦 App](https://status-im-prs.ams3.digitaloceanspaces.com/StatusIm-190412-091748-66f203-pr.AppImage)
> ✔️	[66f203a](https://github.com/status-im/status-react/commit/66f203a6cfda92f346b28866fa27988b82f34559)	[#1](https://ci.status.im/job/status-react/job/prs/job/android/job/PR-7966/1/)	2019-04-12 10:14:39	~56 min	`android`	[📦 apk](https://status-im-prs.ams3.digitaloceanspaces.com/StatusIm-190412-091743-66f203-pr.apk)
> ✔️	[66f203a](https://github.com/status-im/status-react/commit/66f203a6cfda92f346b28866fa27988b82f34559)	[#1](https://ci.status.im/job/status-react/job/prs/job/windows/job/PR-7966/1/)	2019-04-12 10:19:54	~1 hr 1 min	`windows`	[📦 exe](https://status-im-prs.ams3.digitaloceanspaces.com/StatusIm-190412-091755-66f203-pr.exe)

Screen Shot 2019-04-12 at 17 49 07


@jakubgs for some reason ios build is not shown in bot table however there is an ios build https://ci.status.im/job/status-react/job/prs/job/ios/view/change-requests/job/PR-7966/

**Comment by annadanchenko** [comment]
@jinhojang6 I don't understand Korean but it seems that `mainnet-is-default-alert-tex` has outdated translation. English text was changed but I can see old "Switch Developer Mode on" in Korean. Can you, please, update it with new translation? 

Korean text I can see in PR (Android, build 1):
Screenshot_20190412-181737

English text on 0.11.0 release and in https://github.com/status-im/status-react/blob/66f203a6cfda92f346b28866fa27988b82f34559/translations/en.json
`"mainnet-is-default-alert-text": "Status is in Beta and on the Ethereum Mainnet. Use it wisely. Don't store more crypto than you need for testing and only share data with people you trust. By using the app you assume full responsibility for all risks concerning your data and funds."`

Screenshot_20190412-183250

**Comment by jinhojang6** [comment]
Thanks! I've updated and fixed some strings as above

**Pull request merged**
