### PR TITLE
fix Issue with scrolling WalletConnect transaction on Android

### LINKED ISSUE #20795: Issue with scrolling WalletConnect transaction on Android
Transaction data is not scrollable in the request modal on Andoid

I tried it on Pixel 7a (works fine on iOS)
Dapp: https://app.uniswap.org/

https://github.com/user-attachments/assets/bdb91bba-b12b-4baa-9e3a-69f5a80e6208

_Originally posted by @qoqobolo in https://github.com/status-im/status-mobile/issues/20755#issuecomment-2233515157_

### PR DESCRIPTION
**Pull request by Parveshdhull**
fixes https://github.com/status-im/status-mobile/issues/20795

status: ready

### CODE REVIEW

**Review by mohsen-ghafouri — APPROVED** [review]

**Review by clauxx — APPROVED** [review]
Looks good! Thank you!

**Review by shivekkhurana — APPROVED** [review]

**Comment by shivekkhurana** [comment]
Cute.

**Comment by clauxx** [comment]
@qoqobolo @pavloburykh ready to be tested

**Comment by qoqobolo** [comment]
Hey @Parveshdhull , thanks for the fix!
Super minor issue but maybe it's also a super easy fix? :) Take a look pls

### ISSUE 1: The last line of the message is hidden 

Checked on Pixel 7a

https://github.com/user-attachments/assets/607da2de-af60-4136-8827-109f308a8778

**Comment by Parveshdhull** [comment]
Thank you @qoqobolo for testing the PR and finding the issue. Should be fixed now.

**Comment by mariia-skrypnyk** [comment]
Hey @Parveshdhull !

Thanks for your quick fixes.
I checked both platforms and scroll regression in communities, group chats, info on create profile screen etc.
PR can be merged!

**Pull request merged**
