### PR TITLE
fix: App crashes on syncing QR of the account

### LINKED ISSUE #15446: App crashes on syncing QR of the account that has previously been restored numerous times on different devices before.
cc @qfrank 

For reproduction use this seed phrase that belongs to account which has been restored lot of times on different devices: section involve corn song gold verb topic nurse morning dream snack very

**Steps:** 

1. Restore given above account on Device A
2. Generate sync QR on Device A
3. Scan sync QR on Device B
4. Observe the result

**Actual result:** Device B crashes after scanning QR. It is possible to login account on Device B manually, data is synced **BUT** devices are not paired. 

https://user-images.githubusercontent.com/97245802/226872792-9a30219f-f110-43e7-a394-259a42b92c23.mp4

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by qfrank**
fixes #15446 

relate [PR](https://github.com/status-im/status-go/pull/3332) for status-go

### Testing notes
I have already tested by invoke `(re-frame.core/dispatch [:syncing/input-connection-string-for-bootstrapping {:data "cs2...."}])` manually with repl and LGTM. For manual QA, we need wait the UI to be ready.

#### Platforms

- Android
- iOS

status: ready

### CODE REVIEW

**Review by flexsurfer — APPROVED** [review]

**Comment by VolodLytvynenko** [comment]
hi @qfrank. Thanks for the PR. At the moment, I can't test this fix due to the new included design, after which we don't have the ability to scan the QR code. To test this PR we need to wait until https://github.com/status-im/status-mobile/pull/15416 is merged where QR scanning is implemented. After that, the current PR can be rebased and tested.
I'll let you know when it's ready. Thank you!

**Review by ilmotta — APPROVED** [review]

**Comment by VolodLytvynenko** [comment]
@qfrank The PR  https://github.com/status-im/status-mobile/pull/15416 with the QR ui has been ready. Could you please rebase the PR and resolve existing conflicts?

**Comment by qfrank** [comment]
> @qfrank The PR #15416 with the QR ui has been ready. Could you please rebase the PR and resolve existing conflicts?

done @VladimrLitvinenko

**Comment by VolodLytvynenko** [comment]
@qfrank thank you for the fix. PR is tested and ready to be merged

**Pull request merged**
