### PR TITLE
contacts: add contact rouleth dapp - issue #631

### PR DESCRIPTION
**Pull request by tomby42**

### CODE REVIEW

**Comment by jarradh** [comment]
thanks for your contribution @tomby42 ! at the moment it seems rouleth is on `mainnet` whereas Status is on the `testnet`. Before we accept can you please confirm it works on Ropsten testnet?

**Comment by tomby42** [comment]
Ok. I will check it.

**Comment by tomby42** [comment]
@jarradh It seems that it does not work when I use `testnet` :( Lets postpone this patch.

**Comment by jarradh** [comment]
no worries, thanks for contributing all the same! :) 👍

**Pull request closed without merging**
