### PR TITLE
refactor #3141 - replaced :refer with :as in ui.components

### LINKED ISSUE #3141: Refactor all ui.components namespaces to replace :refer with :as
### User Story

As a developer I want to both have a clean code and to easily submit/review PRs.

### Description

*Type*: Refactor

*Summary*: Right now we spend way too much effort communicating back and forth about refactoring to meet the guideline and always require namespaces with aliases, i.e. with `:as` and without `:refer`.

Instead of doing that in every PR, we'll do a number of package wide refactors with nothing but this change. 

The scope of this refactor is every namespace under `ui.components`. If you want any namespace to be omitted from this batch, e.g. to avoid conflicts, please let me know.

### PR DESCRIPTION
**Pull request by goranjovic**
fixes #3141
### Summary:

Replaced `:refer` with `:as` in namespaces under `ui.components`.
Omitted components `chat-icon` and `action-button` to avoid conflicts.

status: ready

### CODE REVIEW

**Review by janherich — APPROVED** [review]

**Review by jeluard — APPROVED** [review]

**Review by yenda — APPROVED** [review]

**Comment by oskarth** [comment]
@goranjovic Please resolve conflicts so we can merge this.

**Comment by goranjovic** [comment]
Rebased, squashed

**Comment by janherich** [comment]
@goranjovic please resolve conflicts

**Comment by goranjovic** [comment]
@janherich done

**Pull request merged**
