### PR TITLE
add decision 0006-wallet-compatibility

### PR DESCRIPTION
**Pull request by gravityblast**
can be merge only after #4262

### CODE REVIEW

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/xRrXvU for branch PR-4263

<blockquote><div><strong><a href="https://i.diawi.com/xRrXvU">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/G3fU2f for branch PR-4263

<blockquote><div><strong><a href="https://i.diawi.com/G3fU2f">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/i5Zrxx for branch PR-4263

<blockquote><div><strong><a href="https://i.diawi.com/i5Zrxx">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/dm5Pqj for branch PR-4263

<blockquote><div><strong><a href="https://i.diawi.com/dm5Pqj">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Review by oskarth — APPROVED** [review]
Awesome, cheers!

**Comment by oskarth** [comment]
I think this would be great to present at town hall for increased visibility

**Comment by gravityblast** [comment]
@oskarth yes I'll do it!

**Review by flexsurfer — APPROVED** [review]

**Pull request merged**
