### PR TITLE
fix: endless logout

### LINKED ISSUE #17899: Endless logout on IOS and endless login on Android until app reopeing
# Bug Report

## Problem 
CRs are not delivered to the recipient

#### Expected behavior
can see CR

#### Actual behavior
no CR

### Reproduction

1. Android: create profile > logout > login 

https://github.com/status-im/status-mobile/assets/4557972/1f8efd42-1d39-45ce-92c3-856bf3754400

2. IOS: create profile > logout

https://github.com/status-im/status-mobile/assets/4557972/6357d382-4fba-4585-a1b3-a8b37642b4ac

### Additional Information

- Status version: release 1.26 RC1 
- Operating System: Android, iOS

[CR_receiver_Anndroid.zip](https://github.com/status-im/status-mobile/files/13340946/CR_receiver_Anndroid.zip)
[CR_sender_IOS.zip](https://github.com/status-im/status-mobile/files/13340947/CR_sender_IOS.zip)

### PR DESCRIPTION
**Pull request by richard-ramos**
### Summary
fixes #17899

status: ready

### CODE REVIEW

**Comment by richard-ramos** [comment]
@qfrank @churik 

https://github.com/status-im/status-mobile/assets/1106587/8ebb73ba-6a10-46d1-8ee0-981ee8b5cb13

This seems to fix the issue in my mobile device. I don't have an iphone to test tho.

**Comment by churik** [comment]
@richard-ramos 
hello! 
If the point of this PR is to check this particular issue and merge the fix on status-go side - I confirm that this issue is fixed. 
Can login/logout on both platforms with/without biometric authentication.

Full regression here is impossible due to other issues mentioned here https://github.com/status-im/status-mobile/pull/17922

**Review by churik — APPROVED** [review]

**Comment by richard-ramos** [comment]
Awesome! will merge that status-go PR then in the meantime! 
Thank you, @churik!

**Review by qfrank — APPROVED** [review]

**Comment by churik** [comment]
I believe that's already in go-develop branch, so Pr can be closed

**Pull request closed without merging**
