### PR TITLE
[Feature 4387] Request 7 days of history

### LINKED ISSUE #4387: Query mail server in bunches of 24 hours
### User Story

```
Given I've been disconnected for more than 24 hours
When I query mail server to get the messages history
Then I should receive the whole history of messages
```

### Description

Recent changes on status-go mail servers are avoiding recovering messages for periods longer than 24 hours. This behavior makes queries with periods larger than 24 hours to not receive any message.

#### Expected behavior

The user can get all messages on the app even if the messages are older than 24 hours

#### Actual behavior

The user doesn't get messages older than 24h.

### Solution

Query mail servers in batches of 24 hours instead of trying to get the whole history.

### PR DESCRIPTION
**Pull request by yenda**
fixes #4387

status: ready

### CODE REVIEW

**Review by cammellos — APPROVED** [review]

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/bbYsfi for branch PR-4493

<blockquote><div><strong><a href="https://i.diawi.com/bbYsfi">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/M431Hb for branch PR-4493

<blockquote><div><strong><a href="https://i.diawi.com/M431Hb">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Review by janherich — APPROVED** [review]

**Review by dmitryn — APPROVED** [review]

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/whR9Nn for branch PR-4493

<blockquote><div><strong><a href="https://i.diawi.com/whR9Nn">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/ymD4xX for branch PR-4493

<blockquote><div><strong><a href="https://i.diawi.com/ymD4xX">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by asemiankevich** [comment]
checked that i can see messages in public chats with 7-day period. Can't check it in 1x1 chat now because moving system date makes messaging broken. Checked sanity that all other functionality works.

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/TxgyZq for branch PR-4493

<blockquote><div><strong><a href="https://i.diawi.com/TxgyZq">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/eTUiG4 for branch PR-4493

<blockquote><div><strong><a href="https://i.diawi.com/eTUiG4">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Pull request merged**
