### PR TITLE
Update `quo/data-item` to show accounts and networks as preview

### LINKED ISSUE #20259: 🌐🔖 Update `quo/data-item` to show accounts and networks as preview
# Feature Issue

### User Story

As a developer
I want to use the `quo/data-item` component to preview networks and accounts. 

### Description

WalletConnect pairing UI shows the networks and the account being used to connect to the user:

<details><summary>UI screen</summary>
<p>

image

</p>
</details> 

[Figma Link](https://www.figma.com/design/mLyiYPXqu8KetdQONOlZpV/Descoped-dApp-Interactions?node-id=32-249259&t=3MAv98aAkxk30T8T-4)

The component is a [data-item](https://www.figma.com/design/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?node-id=22655-218943&t=CkAHJltTj9gt0Rlu-4) inside a [category](https://www.figma.com/design/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?node-id=9419-161493&t=CkAHJltTj9gt0Rlu-4).

[Current implementation of `data-item`](https://github.com/status-im/status-mobile/blob/841a6140e339d878aa7a0bec3acebdc55bb1b04e/src/quo/components/settings/data_item/view.cljs#L114) only supports `community-list` as preview. Extend the component to support `networks` and `accounts`. 

The preview components for networks and accounts already exists in [Figma](https://www.figma.com/design/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?node-id=2219-32021&t=CkAHJltTj9gt0Rlu-4) and [code](https://github.com/status-im/status-mobile/tree/develop/src/quo/components/list_items).

Further changes to fit the `data-item` in `category` will be handled in a seperate PR.

### Acceptance Criteria

- [x] `data-item` quo component should work with type `:network`
- [x] `data-item` quo component should work with type `:account`
- [x] Quo preview should be updated to accommodate these new types
- [ ] The `data-item` malli schema should be update to work with new types

### PR DESCRIPTION
**Pull request by alwx**
Fixes #20259

There is no malli schema for this component so I skipped this part.

#### Platforms

- Android
- iOS

status: ready

### CODE REVIEW

**Comment by shivekkhurana** [comment]
There is a design issue with this particular feature.

The design team made a new component for dapp-settings, instead of updating the data-item component:
https://www.figma.com/design/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?node-id=39475-13230&t=Ij20mh6kwHZFw510-1

I'm talking to Mario about potentially merging the two at design level. If the design team agrees, this PR can go forward.

If not, then we'll reason with them until they agree.

**Comment by shivekkhurana** [comment]
Tested UI correctness, looks good 👍 

| Big Accounts | Small Accounts | Networks |
|--------|--------|--------|
| Simulator Screenshot - iPhone 13 - 2024-06-11 at 20 14 44 | Simulator Screenshot - iPhone 13 - 2024-06-11 at 20 14 59 | Simulator Screenshot - iPhone 13 - 2024-06-11 at 20 17 01 |

Regarding my last message. The design team has approved the way we built it.

**Review by shivekkhurana — APPROVED** [review]
It's nice that you removed the `icon-right?` and `label` prop. It was quite confusing.

Thanks for the PR <3

**Comment by alwx** [comment]
@Francesca-G it needs a design review as well

**Review by Francesca-G — APPROVED** [review]
👍

**Pull request merged**
