### PR TITLE
[#4535] decode browser's uri

### LINKED ISSUE #4535: Render UTF-8 characters in browser URL instead percent-encoded value
### Description

***Type***: Bug

***Summary***: Url value changes to parsed chars after navigating to Cyrillic page like:

#### Expected behavior
UTF-8 characters rendered in-app browser URL instead of percent-encoded values

#### Actual behavior
Percent-encoded values on UTF-8 chars in-app browser URL field

### Reproduction

- Open Status
- Open dapp browser
- Navigate to ru.wikipedia.org (or `https://ja.wikipedia.org/wiki/%E3%83%A1%E3%82%A4%E3%83%B3%E3%83%9A%E3%83%BC%E3%82%B8`

### Additional Information
* Status version: nightly, May 30
* Operating System: Android, iOS

### PR DESCRIPTION
**Pull request by rasom**
fixes #4535

status: ready

### CODE REVIEW

**Comment by rasom** [comment]
apk uploaded to https://i.diawi.com/5ndRV8 for branch PR-4572

<blockquote><div><strong><a href="https://i.diawi.com/5ndRV8">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by rasom** [comment]
ipa uploaded to https://i.diawi.com/Ki1KjR for branch PR-4572

<blockquote><div><strong><a href="https://i.diawi.com/Ki1KjR">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Review by janherich — APPROVED** [review]

**Review by yenda — APPROVED** [review]

**Comment by asemiankevich** [comment]
@rasom can we also make this Browser shortcuts more meaningful on the home page? URL looks good but those browser items still have this issue

image

image

**Comment by rasom** [comment]
@asemiankevich sure

**Comment by rasom** [comment]
@asemiankevich it is ready. Though old dapps chats need to be open first in order to be "fixed", but that should be fine

**Comment by asemiankevich** [comment]
This is fine now, thanks @rasom

**Pull request merged**
