### PR TITLE
Use partitioned topic for discovery

### PR DESCRIPTION
**Pull request by rasom**
Updated version of https://github.com/status-im/status-react/pull/4135 and https://github.com/status-im/status-react/pull/5004
### Summary:

Currently we use a single topic for discovery.
This provides the best obscurity at the cost of bandwidth, as a message
sent on the discovery topic will be received by any peer.
This PR changes this behavior and start listening on a partitioned
topic.
Each pk will be hashed to a limited number of topics.

Everytime someone is in a conversation with someone from another topic
they will have to listen as well to avoid loosing obscurity, because we
only forward messages that we also advertise in the bloom filter.

The choice for the number of partitions depends on 2 factors:

1) The expected number of users using the network
2) The average number of contacts each user has

Any change to the discovery topic will need to be split across 3
releases, to avoid breaking compatibility:

1) Listen to the new and old topic, publish to the old topic
2) Listen to the new and old topic, publish to the new topic
3) Listen to the new topic, publish to the new topic

This is step 1, probably worth documenting somewhere the steps, code or wiki?

### changes added in this pr
- kind of rebased onto current develop
- minor typose and naming changes
- in all places where `constants/discovery-topic` was used it is replaced with `(public-key->discovery-topic-hash pub-key)`, with the corresponding pubkey

### Review notes 
I [cammellos] have added some that might be a bit more mathematically inclined, just to make sure the math checks out, calculations don't take into consideration bloom filters, which will skew the result towards more bandwidth & more anonymity.

### Testing notes:
This is a fully backward compatible change, no differences should be detected.
Regression tests on publishing messages on one-to-one and contact updates, group chats, etc., compatibility between Beta and current PR

builds # 10 (# 11 for ios) must be compatible with 0.9.32
builds # 11 (# 12 for ios) can receive messages from both  # 10 (# 11 for ios) and 0.9.32, but 1-1, group chats, contact request, etc, sent form this build will not be received in 0.9.32

status: ready

### CODE REVIEW

**Comment by mandrigin** [comment]
@rasom @cammellos I'm not sure I understand how topic negotiation works...

**Comment by rasom** [comment]
@mandrigin there is no negotiation, topics are derived from pubkeys 
https://notes.status.im/9T8Nt1CIQlu2Wps1-8fIQg#Stable-topic

<blockquote><div><strong><a href="https://notes.status.im/9T8Nt1CIQlu2Wps1-8fIQg#Stable-topic">Reduce load on discovery topic - CodiMD</a></strong></div></blockquote>

**Comment by mandrigin** [comment]
@rasom ah, okay... maybe we can add a document to https://github.com/status-im/status-react/tree/develop/doc/decisions, with explanation how topic partitioning actually works?

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/status-im/status-react">status-im/status-react</a></strong></div><div>a free (libre) open source, mobile OS for Ethereum - status-im/status-react</div></blockquote>

**Comment by rasom** [comment]
@mandrigin do you want it to be a part of this PR or as separate doc/decision pr? I would prefer to do it afterward because review might cause some changes, still in progress.

**Comment by mandrigin** [comment]
@rasom sounds good to me!

**Review by mandrigin — APPROVED** [review]

**Review by cammellos — APPROVED** [review]

**Comment by rasom** [comment]
looks like group chats are broken

**Comment by churik** [comment]
@rasom I can't receive messages on release 0.9.32 (IOS) and PR build(Android) from current PR (Mac OS, build #14).

Logs:
[Status.log](https://github.com/status-im/status-react/files/2807654/Status.log)
[geth.log](https://github.com/status-im/status-react/files/2807656/geth.log)

Steps:
- installed desktop release build
- created account
- start 1-1 chat
- upgraded to PR build
- log in
- send one more message to 1-1 chat

**Comment by rasom** [comment]
@churik that's expected, what about # 13?

**Comment by asemiankevich** [comment]
@rasom when swipe-to-delete chat:

image

**Comment by rasom** [comment]
@asemiankevich i'll check it

**Comment by rasom** [comment]
@asemiankevich fixed

@asemiankevich @churik 
just to make it less confusing:
1) the next build will be compatible with 0.9.32 
2) when we finish testing it with 0.9.32 i will add another commit which will switch partitioning flag to 1, and that build will not be compatible with 0.9.32 but only with the previous one. We need to test this case in order to be sure that migration will go smoothly when it will  necessary

**Comment by asemiankevich** [comment]
> @asemiankevich fixed
> 
> @asemiankevich @churik
> just to make it less confusing:
> 
> 1. the next build will be compatible with 0.9.32
> 2. when we finish testing it with 0.9.32 i will add another commit which will switch partitioning flag to 1, and that build will not be compatible with 0.9.32 but only with the previous one. We need to test this case in order to be sure that migration will go smoothly when it will  necessary

so once we test latest build here, we need to retest it once more with one more commit? @rasom

**Comment by rasom** [comment]
@asemiankevich right

**Comment by asemiankevich** [comment]
looks good to me @rasom , will you make additional commit so i can check again?

**Comment by rasom** [comment]
@asemiankevich commit is pushed

**Comment by asemiankevich** [comment]
@rasom for some reason i can't chat between android and ios device in last PR build

**Comment by churik** [comment]
@rasom 
### 1) Checked:

Case | Commit | Sender | Receiver | Compatible?
-- | -- | -- | -- | --
1 | https://github.com/status-im/status-react/commit/67be9f8d287fda8a08c645fae95143c78d2b9ebf | Wndows PR build | 0.9.32 release (IOS) | yes
2 | https://github.com/status-im/status-react/commit/67be9f8d287fda8a08c645fae95143c78d2b9ebf | Mac OS PR build | 0.9.32 release (IOS) | yes
3 | https://github.com/status-im/status-react/commit/67be9f8d287fda8a08c645fae95143c78d2b9ebf | Wndows PR build | Mac OS PR build | yes
4 | https://github.com/status-im/status-react/commit/67be9f8d287fda8a08c645fae95143c78d2b9ebf | Mac OS PR build | Wndows PR build | yes
5 | https://github.com/status-im/status-react/commit/67be9f8d287fda8a08c645fae95143c78d2b9ebf | 0.9.32 release (IOS) | Wndows PR build | yes
6 | https://github.com/status-im/status-react/commit/67be9f8d287fda8a08c645fae95143c78d2b9ebf | 0.9.32 release (IOS) | Mac OS PR build | yes
7 | https://github.com/status-im/status-react/commit/cae16bd9fd32fba37fb78104640faa24a78ce62f | Wndows PR build | 0.9.32 release (IOS) | no
8 | https://github.com/status-im/status-react/commit/cae16bd9fd32fba37fb78104640faa24a78ce62f | Mac OS PR build | 0.9.32 release (IOS) | no
9 | https://github.com/status-im/status-react/commit/cae16bd9fd32fba37fb78104640faa24a78ce62f | Wndows PR build | Mac OS PR build | no
10 | https://github.com/status-im/status-react/commit/cae16bd9fd32fba37fb78104640faa24a78ce62f | Mac OS PR build | Wndows PR build | no
11 | https://github.com/status-im/status-react/commit/cae16bd9fd32fba37fb78104640faa24a78ce62f | 0.9.32 release (IOS) | Wndows PR build | yes
12 | https://github.com/status-im/status-react/commit/cae16bd9fd32fba37fb78104640faa24a78ce62f | 0.9.32 release (IOS) | Mac OS PR build | yes

Cases 9 and 10 - same as @asemiankevich mentioned in https://github.com/status-im/status-react/pull/7331#issuecomment-458892223

### 2) There are no messages fetching from offline
Tested on cases 11-12 and 5-6

Steps:
- install release build on device A
- install PR build on device B
- start chat between A and B
- close app on device B 
- send messages from device A
- open app and login an device B

**Expected result:** can see messages sent from device A
**Actual result:** no new messages
Logs from device B:
[geth.log](https://github.com/status-im/status-react/files/2812196/geth.log)
[Status.log](https://github.com/status-im/status-react/files/2812197/Status.log)

@cammellos @annadanchenko are we sure that we need to include this one into release? Seems that it can cause regression issues.

**Comment by yenda** [comment]
This shouldn't stop the release cutting process, if it works by then it can be cherry picked otherwise it will just delay this change for one release cycle

**Comment by rasom** [comment]
Communication issue is fixed, all devices can send/receive messages now

The issue with history is quite weird because data is definitely requested. Still not sure what's the reason.

**Comment by rasom** [comment]
fetching of history is fixed now

**Comment by churik** [comment]
Tested:

Case | Commit | Sender | Receiver | Chat | Compatible?
-- | -- | -- | -- | -- | --
1 | https://github.com/status-im/status-react/commit/386a9bba08f3f3d06bd719293e3f668b687223b1 | Mac OS PR build | 0.9.32 release (IOS) | one-to-one, group | no
2 | https://github.com/status-im/status-react/commit/386a9bba08f3f3d06bd719293e3f668b687223b2 | Mac OS PR build | 0.9.32 release (IOS) | public | yes
3 | https://github.com/status-im/status-react/commit/386a9bba08f3f3d06bd719293e3f668b687223b1 | Wndows PR build | Mac OS PR build | one-to-one, group | yes
4 | https://github.com/status-im/status-react/commit/386a9bba08f3f3d06bd719293e3f668b687223b1 | Mac OS PR build | Wndows PR build | one-to-one, group | yes
5 | https://github.com/status-im/status-react/commit/386a9bba08f3f3d06bd719293e3f668b687223b1 | 0.9.32 release (IOS) | Wndows PR build | one-to-one, group | yes
6 | https://github.com/status-im/status-react/commit/386a9bba08f3f3d06bd719293e3f668b687223b1 | 0.9.32 release (IOS) | Mac OS PR build | one-to-one, group | yes


Fetching messages from offline is fixed.

**Comment by asemiankevich** [comment]
mobile looks good now

**Pull request merged**
