### PR TITLE
chore: bump status-go v0.179.18

### PR DESCRIPTION
**Pull request by J-Son89**

### CODE REVIEW

**Review by smohamedjavid — APPROVED** [review]

**Comment by churik** [comment]
@J-Son89 can you check the tests please? Thanks!

**Comment by J-Son89** [comment]
checking now @churik

**Comment by J-Son89** [comment]
@churik afaik failing tests are related to a different pr merged earlier today

**Comment by churik** [comment]
it was working fine for 20-30 mins, and then again endless "Provider is down" messages (mostly for Optimizm, Arbitrum) on Mainnet.

For testnet it seems to be better.
https://github.com/status-im/status-mobile/assets/4557972/b9127bc5-0615-468e-a624-c0ab99db15d2

Logs: [logs (82).zip](https://github.com/status-im/status-mobile/files/15336111/logs.82.zip)

**Comment by churik** [comment]
```
DEBUG[05-16|13:48:01.480|github.com/status-im/status-go/services/wallet/transfer/commands_sequential.go:1028]                                      end loadBlocksAndTransfers command       chain=42161 accounts="[0xeD620C9dC11401b63B35Dfe8e93F2b11DB0F6F9e 0x0F2D408f1544D27035c46e8A3bAb6508a0b1E7b2 0x9B2802fc4a83b846227343C16243cA76DefFF5e0 0x92FFCE3A76491780bDAdF2c14FD6F50BF0Df1a9B 0xA2910cb7742560B00496A3Ef6a2701F1fd9F431d 0x4401377eF1511f327b9E9C36586124fF59994fa8 0x8D2413447FF297d30BdC475F6D5cb00254685aae]" error="failed to dowload transfers using concurrent downloader: fallback failed with '429 Too Many Requests: {\"jsonrpc\":\"2.0\",\"id\":78,\"error\":{\"code\":-32005,\"message\":\"daily request count exceeded, request rate limited\",\"data\":{\"see\":\"https://infura.io/dashboard\"}}}'. run error was 'hystrix: circuit open'" group=finiteGroup
```

**Review by OmarBasem — APPROVED** [review]

**Comment by churik** [comment]
So I checked:
- sync
- signing tx (when there were no provider's errors, worked, routes were calculated for both Testnet and Mainnets)
- adding new account inside profiles
- unread counters in different types of chats
- collectibles on different networks 
- joining to community with permissioned channels

Issues that I faced:
- https://github.com/status-im/status-mobile/pull/20060#issuecomment-2115312327 still the case
- https://github.com/status-im/status-mobile/issues/20092 still the case
- endless login couple of times (decided that it is the same as https://github.com/status-im/status-mobile/issues/20059 as it was also 
- test failures seemed started couple of days ago in https://github.com/status-im/status-mobile/pull/19989#issuecomment-2115559769 - we'll keep an eye on it, but from that I think that it might be related to waku updates on fleets - communities might stuck in Pending even if control node is online


Will wait for one more round of e2e and merge

**Comment by J-Son89** [comment]
@churik we're already on `v0.179.19` from a recent pr. Closing this 👍

**Pull request closed without merging**
